### ISSUE TITLE
Password not in principal 

### ISSUE THREAD

**Issue by parisni** [prestodb/presto#10000]
Hello,

I have implemented my own plugin, based on file-access, with a custom rules.json file.
The goal is to filter users based on the password given.

Both jdbc access or presto-cli seems not passing the password to presto. The Identity.getPrincipal is always empty. I feel like I am not understanding how to get the password  inside the plugin. Does presto stores that information in the Principal class  from the Identity class ?

Thanks for your help

**Comment by electrum** [comment]
Password authentication is pluggable in 0.195 with this: https://prestodb.io/docs/current/develop/password-authenticator.html

The above creates an authenticated principal containing a username. You can use a System Access Control to check if the principal is authorized to be the provided Presto username (potentially different from the authentication username which allows for impersonation), along with other authorization checks.

**Comment by parisni** [comment]
This sounds good. Funny thing is the 0.195 was released few hours ago. I feel like lucky. 

If I succeed in implementing this, I will come back with a working plugin implementation example.

**Comment by ayush-chauhan** [comment]
@parisni Do you have a working example which I can refer?

**Comment by parisni** [comment]
yes that should be feasible to share. Just give me a week to push
