### ISSUE TITLE
Parquet predicate pushdown tests are broken.

### ISSUE THREAD

**Issue by luohao** [prestodb/presto#10009]
I found that the parquet predicate pushdown is not tested in the test suites. There are two issues with the predicate pushdown tests.

1. `parquetCursorPushdownSession` in `TestHiveFileFormats` is broken. Although the code calls `setParquetPredicatePushdownEnabled(true)` to set the property, but when creating Parquet Reader, `isParquetPredicatePushdownEnabled(session)` will always return false from `TestingConnectorSession.getProperty()`. The  `TestingConnectorSession` checks the `propertyValues` and it is always `null`, therefore it will return `metadata.getDefaultValue()` which is `false`.

2.  When creating parquet reader, `TupleDomain.all()` is passed as the `effectivePredicate` argument to the parquet reader factory. So no predicates is actually pushed down.

Is there any other tests that actually is enabled and testing predicate pushdown feature?

@zhenxiao @dain @nezihyigitbasi

**Comment by findepi** [comment]
>  the code calls setParquetPredicatePushdownEnabled(true) to set the property, 
> but when creating Parquet Reader, isParquetPredicatePushdownEnabled(session) will always return false

This sounds wrong. Did you try to fix these tests?

**Comment by luohao** [comment]
@findepi  This first issue is with `testCursorProvider` function. It doesn't receive the session from `assertRead` and use the default `SESSION`. I fix it by adding a new `session` argument to `testCursorProvider`. 

For the second issue, I cherrypicked a set of columns and pass them as `effectivePredicate` to parquet source factory so that these predicates will be pushed down.

I will create a PR for this issue later today.

**Comment by luohao** [comment]
@findepi  #10008 has the fix for the tests.

**Comment by nezihyigitbasi** [comment]
Fixed by https://github.com/prestodb/presto/pull/9156.
