### ISSUE TITLE
last_value doesn't return the last value

### ISSUE THREAD

**Issue by pavlindrom** [prestodb/presto#10013]
I have a query here that shows the issue I'm seeing:

```
select value, first_value(value) over (order by counter desc) first, last_value(value) over (order by counter asc) last from (
  values (1, 'a'), (2, 'b'), (3, 'c')
) as t (counter, value)
```

`first` always returns `c`, but `last` returns the same as `value`. I expected `first` and `last` to match.

**Comment by electrum** [comment]
Can you paste the full query including the window function call?

**Comment by electrum** [comment]
The problem is the default window frame is “range between unbounded preceding and current row”. You need to use “range between unbounded preceding and unbounded following” (or “rows” instead of “range”, though it doesn’t matter for unbounded on both ends).

**Comment by haozhun** [comment]
In case you are confused, "between unbounded preceding and unbounded following" is the default when you don't have an "order by" in your window. And "between unbounded preceding and current row" is the default when you have an "order by" in your window.

**Comment by pavlindrom** [comment]
That still doesn't explain it to me. This query, where I add an id to partition by, it should now work right for `last`, but show the problem for `first`. 

```
select id, value, first_value(value) over (partition by id order by counter desc) first, last_value(value) over (partition by id order by counter asc) last from (
  values (1, 1, 'a'), (1, 2, 'b'), (1, 3, 'c'), (2, 4, 'd'), (2, 2, 'e'), (2, 3, 'f'), (2, 1, 'g')
) as t (id, counter, value)
```

`first` is still good, `last` is still current. Notice the change in counter going mostly down for id=2.
