### ISSUE TITLE
Handle unsigned integer types for MySQL connector

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#10017]
For everything except `bigint`, we could use the next larger type (.e.g., a MySQL `int unsigned` becomes a Presto `bigint`). For `bigint`, we could use `decimal` or throw an error on read for values that are too large. This introduces a problem on the write side, since we can now try to insert values that are too large, and they might get silently truncated on the MySQL server side, depending on the MySQL server mode setting. We expect that Presto should never cause silent data loss, so we should always fail (regardless of how the MySQL server is configured).

**Comment by CH-JoelBondurant** [comment]
Epic fail, Presto can't handle unsigned ints.

`presto> select * from piwik_operations.piwik_pro.log_action limit 1;

Query 20181218_012523_02106_g4jaf, RUNNING, 2 nodes, 18 splits
0:05 [    0 rows,     0B] [    0 rows/s,     0B/s] [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 0%

Query 20181218_012523_02106_g4jaf, FAILED, 2 nodes
Splits: 18 total, 0 done (0.00%)
0:07 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20181218_012523_02106_g4jaf failed: com.mysql.jdbc.exceptions.jdbc4.MySQLDataException: '2.185545258E9' in column '3' is outside valid range for the datatype INTEGER.

presto> show create table piwik_operations.piwik_pro.log_action;
                     Create Table
------------------------------------------------------
 CREATE TABLE piwik_operations.piwik_pro.log_action (
    idaction integer,
    name varchar(65535),
    hash integer,
    type tinyint,
    url_prefix tinyint
 )
(1 row)
================================================================================================
mysql> show create table log_action;
+------------+--------------------------------------------------------------+
| Table      | Create Table                                                 |
+------------+--------------------------------------------------------------+
| log_action | CREATE TABLE `log_action` (
  `idaction` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` text,
  `hash` int(10) unsigned NOT NULL,
  `type` tinyint(3) unsigned DEFAULT NULL,
  `url_prefix` tinyint(2) DEFAULT NULL,
  PRIMARY KEY (`idaction`),
  KEY `index_type_hash` (`type`,`hash`)
) ENGINE=InnoDB AUTO_INCREMENT=3625168 DEFAULT CHARSET=utf8`

**Comment by CH-JoelBondurant** [comment]
What an epic fail, is there a workaround to this mess?
=======================================================================
mysql> show create table log_action;
+------------+--------------------------------------------------------------+
| Table      | Create Table                                                 |
+------------+--------------------------------------------------------------+
| log_action | CREATE TABLE `log_action` (
  `idaction` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` text,
  `hash` int(10) unsigned NOT NULL,
  `type` tinyint(3) unsigned DEFAULT NULL,
  `url_prefix` tinyint(2) DEFAULT NULL,
  PRIMARY KEY (`idaction`),
  KEY `index_type_hash` (`type`,`hash`)
) ENGINE=InnoDB AUTO_INCREMENT=3625168 DEFAULT CHARSET=utf8

=======================================================================
presto> select * from piwik_operations.piwik_pro.log_action limit 1;

Query 20181218_012523_02106_g4jaf, RUNNING, 2 nodes, 18 splits
0:05 [    0 rows,     0B] [    0 rows/s,     0B/s] [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 0%

Query 20181218_012523_02106_g4jaf, FAILED, 2 nodes
Splits: 18 total, 0 done (0.00%)
0:07 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20181218_012523_02106_g4jaf failed: com.mysql.jdbc.exceptions.jdbc4.MySQLDataException: '2.185545258E9' in column '3' is outside valid range for the datatype INTEGER.

presto> show create table piwik_operations.piwik_pro.log_action;
                     Create Table
------------------------------------------------------
 CREATE TABLE piwik_operations.piwik_pro.log_action (
    idaction integer,
    name varchar(65535),
    hash integer,
    type tinyint,
    url_prefix tinyint
 )
(1 row)
=======================================================================

**Comment by CH-JoelBondurant** [comment]
Here's a link to a suggested workaround:
https://drill.apache.org/
