### ISSUE TITLE
Memory leak: OperatorContext holds reference to Driver and Operators after Drivers are closed

### ISSUE THREAD

**Issue by sopel39** [prestodb/presto#10036]
`OperatorContext#memoryRevocationRequestListener` comes from lambda from `Driver`. `OperatorContext` are kept for some time after sql tasks are finished. However, since `memoryRevocationRequestListener` isn't reset, actual Operators (and all structures they had) are kept too.

**Comment by sopel39** [comment]
Fixed by: https://github.com/prestodb/presto/pull/10035

**Comment by findepi** [comment]
> `OperatorContext` are kept for some time after sql tasks are finished

what for? Why should they survive `Driver`?

**Comment by sopel39** [comment]
> what for? Why should they survive Driver?

`SqlTaskManager` keeps information about ended tasks (`SqlTaskManager#tasks`) for a while (default 15 minutes) so that they can be queried by coordinator.
