### ISSUE TITLE
PREPARE statement query failing with 500 error

### ISSUE THREAD

**Issue by jamsesso** [prestodb/presto#10049]
I am trying to run a prepared statement query but I am getting a 500 error in the output. Running the query without preparing it works fine (there are no parameters to bind). This error is occurring on both the Presto CLI tool and in my application.

Input:

```
PREPARE stmt0 FROM <<SELECT query 11.7 kbytes in size>>;
```

Output:

```
java.lang.RuntimeException: Error fetching next at http://localhost:28881/v1/statement/20180228_143747_01091_gjj7v/1 returned an invalid response: JsonResponse{statusCode=500, statusMessage=Server Error, headers={connection=[close]}, hasValue=false} [Error: ]
    at com.facebook.presto.client.StatementClient.requestFailedException(StatementClient.java:390)
    at com.facebook.presto.client.StatementClient.advance(StatementClient.java:333)
    at com.facebook.presto.cli.StatusPrinter.printInitialStatusUpdates(StatusPrinter.java:122)
    at com.facebook.presto.cli.Query.renderQueryOutput(Query.java:134)
    at com.facebook.presto.cli.Query.renderOutput(Query.java:118)
    at com.facebook.presto.cli.Console.process(Console.java:299)
    at com.facebook.presto.cli.Console.runConsole(Console.java:251)
    at com.facebook.presto.cli.Console.run(Console.java:145)
    at com.facebook.presto.cli.Presto.main(Presto.java:32)
Query is gone (server restarted?)
```

There is no indication that the query failed in the presto UI or in the server.log file. It is marked as finished. Perhaps there is an error in Presto parsing the output of the query?

The query selects 108 fields from 15 tables across 2 MySQL nodes. There are 4 INNER JOINs followed by 10 LEFT JOINs.

**Presto server version:** 0.195
**Presto CLI version:** 0.195

**Comment by electrum** [comment]
Can you provide us with a simple reproduction?

**Comment by jamsesso** [comment]
@electrum Sure thing. I'm attaching 3 files in the zip. Run `setup.sql` to create the schema, then run `query.sql` from the Presto CLI to observe the problem. `teardown.sql` is for convenience to delete the schema.

[presto-10049.zip](https://github.com/prestodb/presto/files/1771797/presto-10049.zip)

**Comment by jamsesso** [comment]
I've done some debugging and it looks like the issue is caused by the response header size. This is caused by the length of the query.

<img width="1100" alt="screen shot 2018-03-02 at 1 57 37 pm" src="https://user-images.githubusercontent.com/107810/36915501-5981c2c4-1e27-11e8-97ca-6f593528c33c.png">

The `StatementResource` is returning a 200 OK correctly, but the `Response` object contains all of the prepared and deallocated statements which can cause this error: `X-Presto-Added-Prepare` and `X-Prest-Deallocated-Prepare`.

**Comment by kokosing** [comment]
Is this a duplicate of https://github.com/prestodb/presto/issues/5759?

**Comment by jamsesso** [comment]
@kokosing Yes it appears to be. We are also using the Teradata driver as the Presto JDBC driver does not yet support prepared statements.

Closing in favor of that issue.

**Comment by kokosing** [comment]
What version of Presto are you using? Long prepared statements should work either with Teradata or Starburst branded Presto version.

**Comment by jamsesso** [comment]
I am running master locally. Seeing this issue all the way back to version 0.192. I specifically tested 0.192 and 0.195

**Comment by kokosing** [comment]
In order to make long prepared statements in Presto it is required to implement v2 JSON based client-server protocol. It is already in progress, see: https://github.com/prestodb/presto/pull/9607

Teradata or Starburst version have something similar to v2, but very minimalistic. Just to make prepared statements to work until v2 got merged.
