### ISSUE TITLE
Presto doesn't remove columns from plans which can be concluded to be literals

### ISSUE THREAD

**Issue by sopel39** [prestodb/presto#10058]
```
presto> explain select y from (select x from (values 3) t(x) where x = 3), (select y from (values 3) t(y)) where x=y;
                                                               Query Plan
----------------------------------------------------------------------------------------------------------------------------------------
 - Output[y] => [field_4:integer]
         Cost: {rows: 1 (10B), cpu: 200.00, memory: 80.00, network: 0.00}
         y := field_4
     - CrossJoin => [field_4:integer]
             Distribution: REPLICATED
             Cost: {rows: 1 (10B), cpu: 200.00, memory: 80.00, network: 0.00}
         - FilterProject[filterPredicate = ("field" = 3)] => []
                 Cost: {rows: 1 (10B), cpu: 20.00, memory: 0.00, network: 0.00}/{rows: 1 (0B), cpu: 20.00, memory: 0.00, network: 0.00}
             - LocalExchange[ROUND_ROBIN] () => field:integer
                     Cost: {rows: 1 (10B), cpu: 10.00, memory: 0.00, network: 0.00}
                 - Values => [field:integer]
                         Cost: {rows: 1 (10B), cpu: 0.00, memory: 0.00, network: 0.00}
                         (3)
         - LocalExchange[SINGLE] () => field_4:integer
                 Cost: {rows: 1 (10B), cpu: 20.00, memory: 0.00, network: 0.00}
             - Filter[filterPredicate = (3 = "field_4")] => [field_4:integer]
                     Cost: {rows: 1 (10B), cpu: 20.00, memory: 0.00, network: 0.00}
                 - LocalExchange[ROUND_ROBIN] () => field_4:integer
                         Cost: {rows: 1 (10B), cpu: 10.00, memory: 0.00, network: 0.00}
                     - Values => [field_4:integer]
                             Cost: {rows: 1 (10B), cpu: 0.00, memory: 0.00, network: 0.00}
                             (3)
```
In this case we can conclude that `field_4=3` therefore we could just remove the symbol completely above `- Filter[filterPredicate = (3 = "field_4")] => [field_4:integer]`

Probably we need a rule that based on effective predicate (watch out for nulls!!!) would try to simplify expressions by rewriting them without usage of symbols (one by one)  

FYI: @martint @findepi

**Comment by kokosing** [comment]
I believe a proper fix for this would consist of: 
1. `PredicatePushdown` to be ported to iterative optimizer
2.  `PredicatePushdown` to be run along with `SimplifyExpression` in single `IterativeOptimizer`
3.  Handle effective predicates as traits (aka logical plan property), something similar to what we have for cost and stats information in `Memo`. This looks like a prerequisite for 1.

Sounds like a lot of work, but there is something already started around: https://github.com/prestodb/presto/pull/7377 and https://github.com/prestodb/presto/pull/9691. Maybe we (Starburst) could handle that in Q2.

**Comment by martint** [comment]
> Handle effective predicates as traits (aka logical plan property), something similar to what we have for cost and stats information in Memo.

Yes! That was the vision for how effective predicates and other derived features should be modeled so that rules can take advantage of them.

**Comment by sopel39** [comment]
I am not sure traits are needed for this (or PP for that matter). It could be that PP can derive properties about symbols just from local node surrounding as long as we mix PP rule with other cleanup rules.

**Comment by kokosing** [comment]
> I am not sure traits are needed for this (or PP for that matter).

Notice that some effective predicate (derived property) is taken from the leafs (table scan or value nodes). However may we start with recursion like we do for other rules. It is not a big deal because effective predicates are used only (am I right?) for `JoinNode` in PP.

**Comment by sopel39** [comment]
> Notice that some effective predicate (derived property) is taken from the leafs (table scan or value nodes).

That's still not a problem. Equivalence information from leafs will be propagated to higher nodes if we mix PP with other rules (e.g: unalias, remove unreferenced, replace symbol with literal (new from this issue)).

**Comment by kokosing** [comment]
> That's still not a problem. Equivalence information from leafs will be propagated to higher nodes if we mix PP with other rules (e.g: unalias, remove unreferenced, replace symbol with literal (new from this issue)).

It may work only for simple case like `A = 3`, but you might also have range information saying that A may have value from range `[3,4,6,7]` i.e. table scan tuple domain.

**Comment by sopel39** [comment]
> It may work only for simple case like A = 3, but you might also have range information saying that A may have value from range [3,4,6,7] i.e. table scan tuple domain.

True, e.g: `presto> explain select y from (select x from (values 3) t(x) where (x = 3 or x=4)), (select y from (values 3) t(y)) where x=y;` woundn't be optimized where it is now.
