### ISSUE TITLE
Presto CLI fail when home folder isn't writable

### ISSUE THREAD

**Issue by bivas** [prestodb/presto#10083]
When starting presto in console mode (not using `--file` or `--execute` flags, if the user home folder is not writable (or doesn't exists) - Presto CLI will exit with the following errors message:
```
[WARN] Failed to create directory
Readline error: No such file or directory
```

I've reproduced it using a Docker container so I can mimic a non-writable home folder:
```
$ docker run --rm -it --user 9999 iguaziodocker/presto:0.195-1.5.1_b7 /bin/bash
I have no name!@873adbdaaf26:/$ presto --server prestodb.cluster.local:8080
presto> select count(1) from foo;
[WARN] Failed to create directory: /?
Readline error: No such file or directory
```

The actual fault is with the jline library in `jline.console.history.FileHistory` when `flush()` is called. Even that jline lib detects this path isn't writable, it still tries to write to that path causing `IOException` which isn't handled correctly in `Console#runConsole` method

**Comment by nezihyigitbasi** [comment]
Fixed by #10084
