### ISSUE TITLE
How to set the isolation level for a catalog?

### ISSUE THREAD

**Issue by GarouDan** [prestodb/presto#10092]
If when we are configuring a catalog to presto we would like to just use "uncommited reads", how can we set the isolation level for the catalogs?

Specifically I was trying to configure this when using SQLServer database.

**Comment by kokosing** [comment]
It is not supported today. There is now way to configure that.

I am not aware of any effort to make it possible. However, any contributions are welcomed! Related classes are: `com.facebook.presto.plugin.sqlserver.SqlServerClient` and `com.facebook.presto.plugin.jdbc.DriverConnectionFactory`.

Please use user group mailing list for such questions next time. You will get more attention as here issue tracking is mainly for contributors. See https://groups.google.com/forum/#!forum/presto-users

I am going to close this issue, if you disagree please reopen.
