### ISSUE TITLE
create table failed when using viewfs

### ISSUE THREAD

**Issue by sandflee** [prestodb/presto#10099]
command: CREATE TABLE lt_hive.tmp_dw.dw_dim_photo_tmp01zzxx AS SELECT * FROM cp_hive.ks_dw_dim.dw_dim_photo_tmp WITH NO DATA;

 failed: Unable to rename from viewfs://hadoop-lt-cluster/home/dp/dw/tmp_dw.db/dw_dim_photo_tmp01zzxx/.hive-staging/e89d40f1-188c-4140-b86a-1d36b725a4e7 to viewfs://hadoop-lt-cluster/home/dp/dw/tmp_dw.db/dw_dim_photo_tmp01zzxx: target directory already exists

**Comment by piyushnarang** [comment]
We're running into similar issues on both create table and create table as select:
```
presto:piyush> CREATE TABLE piyush_orders_test( orderkey bigint, orderstatus varchar, totalprice double, orderdate date ) WITH (format = 'ORC');
Query 20180406_194310_00013_perkk failed: Unable to create directory viewfs://root/user/piyush/hive/piyush_orders_test: target directory already exists
com.facebook.presto.spi.PrestoException: Unable to create directory viewfs://root/user/p.narang/hive/piyush_orders_test_1: target directory already exists
	at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore$Committer.prepareAddTable(SemiTransactionalHiveMetastore.java:956)
...
```

Similar issue on a CTAS:
```
Query 20180409_180433_00000_g7r4c failed: Unable to rename from viewfs://root/user/piyush/hive/my_dim_campaign/.hive-staging/920c6a4e-9b74-443d-8729-40710f5b7e8c to viewfs://root/user/piyush/hive/my_dim_campaign: target directory already exists
com.facebook.presto.spi.PrestoException: Unable to rename from viewfs://root/user/piyush/hive/my_dim_campaign/.hive-staging/920c6a4e-9b74-443d-8729-40710f5b7e8c to viewfs://root/user/piyush/hive/my_dim_campaign: target directory already exists
	at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore.renameDirectory(SemiTransactionalHiveMetastore.java:1616)
...
```

Issue seems to be that we're creating the staging directory as a sub-dir under the target path. As part of doing this, the target path directory is also created. When it ends up being time to run `SemiTransactionalHiveMetastore$Committer.prepareAddTable` Presto throws an exception as the target path already exists.

**Comment by findepi** [comment]
`viewfs` is currently supported in INSERT but not in CREATE -- see https://github.com/prestodb/presto/pull/11590#issuecomment-425669585
