### ISSUE TITLE
Mongo connector does not take advantage of index for timestamp type

### ISSUE THREAD

**Issue by ch7025833** [prestodb/presto#10119]
I have tried to use a CATs to create a simple table from mongodb connector, and the filter condition includes a field of timestamp type. But it seems the connector will do a full collection scan for this field, which takes a lot of time.

Example:
create table test as select * from mongodb_core_test.good.good where created_date > timestamp '2018-01-01 00:00:00.000 UTC';

![image](https://user-images.githubusercontent.com/8772970/37146868-fbb1574e-22ff-11e8-98d7-9109f1f66346.png)

Is this a problem of my misunderstanding of using this kind of query, or this can be improved in the code?

**Comment by findepi** [comment]
@ch7025833 , for the record, is `created_date` of type `timestamp` or `timestamp with time zone`?
(`timestamp '2018-01-01 00:00:00.000 UTC'` is obviously a `timestamp with time zone`, but in the title you wrote just `timestamp`)

**Comment by ch7025833** [comment]
@findepi Sorry for the late reply. I did some evaluations of this issue:

I have about 130 million records in mongodb collection, and I just want to get some data through mongodb date condition. And through CATs to create a local table in presto.

Test senarios:
1. mongodb _schema collection will have a schema with field name created_date, type is timestamp, there is a document existing with created_date field, and its value is ISODate("2018-03-21T10:38:42.883Z"). In presto , I run query select * from mongodb_core_test.good.good where created_date = timestamp '2018-03-21 10:38:42.883'; 
![image](https://user-images.githubusercontent.com/8772970/37750379-9d9073d4-2dc7-11e8-88b0-187f0c7701c8.png)
It's very fast, but there is no result found.

2. mongodb _schema collection will have a schema with field name created_date, type is timestamp, there is a document existing with created_date field, and its value is ISODate("2018-03-21T10:38:42.883Z"). In presto , I run query select * from mongodb_core_test.good.good where created_date = timestamp '2018-03-21 10:38:42.883 UTC'; 
![image](https://user-images.githubusercontent.com/8772970/37753639-d40b0ce2-2dd8-11e8-9590-592f979fc139.png)
it takes almost 2 hours, and finally we can find the result. And it clearly did a full table scan for this field and find the result.

3. mongodb _schema collection will have a schema with field name created_date, type is timestamp with time zone, there is a document existing with created_date field, and its value is ISODate("2018-03-21T10:38:42.883Z"). In presto , I run query select * from mongodb_core_test.good.good where created_date = timestamp '2018-03-21 10:38:42.883 UTC'; 
![image](https://user-images.githubusercontent.com/8772970/37753812-c0a3c8e6-2dd9-11e8-80a4-cfce03b10838.png)
It's still fast with no result. For timestamp with time zone, we can't use CATs from mongodb, since this type is not supported in hive
![image](https://user-images.githubusercontent.com/8772970/37753871-0cf54d5a-2dda-11e8-9d59-acbc12ff744c.png)


So any ideas about how to find data in through mongo connector , with date condition in a fast way?

**Comment by findepi** [comment]
i don't know mongo connector too well. @ch7025833 i asked, because your initial question didn't seem clear.

> For timestamp with time zone, we can't use CATs from mongodb, since this type is not supported in hive

This is going to change under #7122.
Generally, until that issue is resolved, I would prefer not to discuss timestamp-related problems and solutions, as any solution (or workaround) crafted today will most likely become obsolete when #7122 delivers fixed semantics of timestamp data type.

I'd recommend:
- not using `timestamp` for now
- using  `timestamp with time zone` or number storing sth like Java timestamp (as `bigint`)
  - CTAS problem can be worked around by adding `CAST` (or some other conversion) to your CTAS query. Still I don't know what output you expected when you use `timestamp`.

**Comment by findepi** [comment]
( as i said, I can't give you any mongo-specific advice, if there is any )

**Comment by ch7025833** [comment]
@findepi Thanks for your reply!
