### ISSUE TITLE
Presto Use system idle port

### ISSUE THREAD

**Issue by Tartarus0zm** [prestodb/presto#10123]
I run Presto On Yarn, I want every Presto Worker use system idle port, not a fixed port.

**Comment by dain** [comment]
Set `http-server.http.port=0` and the worker will pick a random port.  The worker will still announce to the discovery service in the coordinator, so everything will work as expected (this is how Presto unit tests work)

**Comment by Tartarus0zm** [comment]
@dain   Yes , I has tested it . so I add the docs to Presto . please take a look at [PR-10125](https://github.com/prestodb/presto/pull/10125) , thanks
