### ISSUE TITLE
QueryManager is reporting RunningQueries wrong

### ISSUE THREAD

**Issue by yingsu00** [prestodb/presto#10134]
https://fburl.com/ods/0qjke3vt
RunningQueries from QueryManager was 450-500 sometimes while the RunningQueries counters from the resource groups are just 40-50.

**Comment by nezihyigitbasi** [comment]
This looks like a duplicate of https://github.com/prestodb/presto/issues/10046

**Comment by rschlussel** [comment]
@yingsu00 I'm closing this as a duplicate.  If it's a different issue, feel free to reopen and explain
