### ISSUE TITLE
Presto JDBC Client should return meaningful error when encountering network issues

### ISSUE THREAD

**Issue by wenleix** [prestodb/presto#10149]
Today it always returns errorCode = 0.

From https://github.com/prestodb/presto/wiki/Error-Codes:

> The range 0x00FF is reserved for use in clients (such as JDBC) to return client-side errors to applications. Error codes in this range will never be returned from the server.

**Comment by daliadefelipee** [comment]
Hi. Wouldn't the solution be the implementation example in the link state above?
