### ISSUE TITLE
"LIMIT x" still executes a query without the limit in mysql

### ISSUE THREAD

**Issue by rookie7799** [prestodb/presto#10153]
prestodb-server / cli version 0.196

A simple query like this:
`select * from mysql.db20.table_stats limit 5;`
returns 5 rows BUT I can still see `select created from table_stats;` being executed inside mysql.

**Comment by findepi** [comment]
This is a known limitation, see https://github.com/prestodb/presto/issues/1112

Did you try to assess performance overhead incurred by lack of LIMIT in the query sent to mysql? If you did, please mention your findings in https://github.com/prestodb/presto/issues/1112.
