### ISSUE TITLE
Adding types using Plugin interface doesn't work as documentation is specified

### ISSUE THREAD

**Issue by dekobon** [prestodb/presto#10168]
As per the documentation [here](https://prestodb.io/docs/current/develop/types.html),  I created a new type and attempted to load it via the Plugin interface:

```java
public class MantaPlugin implements Plugin {
    private static Set<Type> mantaTypes =
            ImmutableSet.of(TimestampEpochSecondsType.TIMESTAMP_EPOCH_SECONDS);

    @Override
    public Iterable<ConnectorFactory> getConnectorFactories() {
        return Collections.singletonList(new MantaConnectorFactory());
    }

    @Override
    public Iterable<Type> getTypes() {
        return mantaTypes;
    }
}
```
However, when I startup Presto, I see this error:
```
java.lang.IllegalStateException: [NOT_EQUAL, EQUAL, GREATER_THAN_OR_EQUAL, HASH_CODE, LESS_THAN, BETWEEN, LESS_THAN_OR_EQUAL, GREATER_THAN] missing for timestamp epoch seconds
	at com.facebook.presto.metadata.MetadataManager.verifyComparableOrderableContract(MetadataManager.java:212)
	at com.facebook.presto.server.PluginManager.loadPlugins(PluginManager.java:143)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:118)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:67)
```

I'm attempting to use [this type](https://github.com/joyent/presto-manta/blob/partitions/src/main/java/com/joyent/manta/presto/types/TimestampEpochSecondsType.java) that is a near copy of `com.facebook.presto.spi.typeTimestampType`.

I would assume that this "just works" because everything works well when I create a `TypeRegistry` and manually add it. However, if I want to add this type globally in the "proper" way, it fails some sanity checks.

**Comment by findepi** [comment]
Hi @dekobon,

This exception just says that besides defining a type, you need to define standard operations on the type (NOT_EQUAL, EQUAL, GREATER_THAN_OR_EQUAL, HASH_CODE, LESS_THAN, BETWEEN, LESS_THAN_OR_EQUAL, GREATER_THAN).
See for example `com.facebook.presto.type.BigintOperators#hashCode`, `com.facebook.presto.type.BigintOperators#equal`, `com.facebook.presto.type.BigintOperators#notEqual`, ...
