### ISSUE TITLE
Jdbc for Query ID

### ISSUE THREAD

**Issue by imperio-wxm** [prestodb/presto#10191]
When I use jdbc to get data.

And I want to know job status, like Web UI.
What should I do?

**Comment by kokosing** [comment]
If you are using open source jdbc drivers then you can:
```
ResultSet rs = ...;
verify(rs.isWrappedFor(PrestoResultSet.class);
Strring queryId = rs.unwrap(PrestoResultSet.class).getQueryId();
```

**Comment by electrum** [comment]
There is also PrestoStatement.setProgressMonitor()

I filed an issue to document it: https://github.com/prestodb/presto/issues/10175
