### ISSUE TITLE
How to start multiple workers on same machine 

### ISSUE THREAD

**Issue by alokgogate** [prestodb/presto#10192]
How do you start multiple presto workers on the same physical machine? 
Which config are to be changed? 
Any example available

**Comment by kokosing** [comment]
I think you can start with `http-server.http.port=0`, notice that coordinator have to have port specified so workers could use it in `discovery.uri`

See https://github.com/prestodb/presto/issues/10123

**Comment by alokgogate** [comment]
can you elaborate on this?

**Comment by kokosing** [comment]
For coordinator you can have something like:

```
http-server.http.port=8080
discovery.uri=coordinator_host:8080
```

For workers:

```
http-server.http.port=0
discovery.uri=coordinator_host:8080
```

Please see https://prestodb.io/docs/current/installation/deployment.html#config-properties for more details

**Comment by electrum** [comment]
You can also configure each worker with a separate, unique port number.

**Comment by atronchi** [comment]
When setting the port to either 0 OR different ports per worker on the same host, and starting with `bin/launcher start`, any workers started after the first on the same host simply return 'Already running on <pid of first worker>', even though each worker is configured with its own data directory.  Is there some additional setting to indicate that we want multiple workers per host?

**Comment by anirudhbagri** [comment]
Can someone help me on how to configure this?
Currently, I have `config.properties` for coordinator, and I am running a server using `bin/launcher start`.

How can I add more workers to it?
Where can I specify the property file for other worker, and how do I start the worker?
I am doing everything inside the presto zip directory.
