### ISSUE TITLE
Improve rewrite of EXISTS subquery with single equality conjunct

### ISSUE THREAD

**Issue by losipiuk** [prestodb/presto#10216]
Currently queries with `EXISTS` with single equality conjunct like:
``` 
SELECT o_orderkey FROM orders WHERE EXISTS (SELECT 1 FROM nation WHERE o_orderkey = n_nationkey);
```
are rewritten to plan containing `count()` aggregation and `LEFT JOIN`.

E.g.
```
presto:sf1> explain select o_orderkey from orders where exists (select 1 from nation where o_orderkey = n_nationkey);
                                                                                     Query Plan
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 - Output[o_orderkey] => [o_orderkey:bigint]
     - RemoteExchange[GATHER] => o_orderkey:bigint
         - FilterProject[filterPredicate = (COALESCE("count", "count_11") > BIGINT '0')] => [o_orderkey:bigint]
             - CrossJoin => [o_orderkey:bigint, count:bigint, count_11:bigint]
                     Distribution: REPLICATED
                 - LeftJoin[("o_orderkey" = "n_nationkey")][$hashvalue, $hashvalue_13] => [o_orderkey:bigint, count:bigint]
                         Distribution: PARTITIONED
                     - ScanProject[table = tpch:tpch:orders:sf1.0, originalConstraint = true] => [o_orderkey:bigint, $hashvalue:bigint]
                             Cost: {rows: 1500000 (14.31MB), cpu: 15000000.00, memory: 0.00, network: 0.00}/{rows: 1500000 (28.61MB), cpu: 45000000.00, memory: 0.00, network: 0.00}
                             $hashvalue := "combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("o_orderkey"), 0))
                             o_orderkey := tpch:o_orderkey
                             tpch:o_orderstatus
                                 :: [[F], [O], [P]]
                     - LocalExchange[HASH][$hashvalue_13] ("n_nationkey") => n_nationkey:bigint, count:bigint, $hashvalue_13:bigint
                         - RemoteExchange[REPARTITION] => n_nationkey:bigint, count:bigint, $hashvalue_14:bigint
                             - Project[] => [n_nationkey:bigint, count:bigint, $hashvalue_18:bigint]
                                     $hashvalue_18 := "combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("n_nationkey"), 0))
                                 - Aggregate(FINAL)[n_nationkey] => [n_nationkey:bigint, count:bigint]
                                         count := "count"("count_12")
                                     - LocalExchange[HASH][$hashvalue_15] ("n_nationkey") => n_nationkey:bigint, count_12:bigint, $hashvalue_15:bigint
                                         - RemoteExchange[REPARTITION][$hashvalue_16] => n_nationkey:bigint, count_12:bigint, $hashvalue_16:bigint
                                             - Project[] => [n_nationkey:bigint, count_12:bigint, $hashvalue_17:bigint]
                                                     Cost: {rows: ? (?), cpu: ?, memory: ?, network: 0.00}
                                                     $hashvalue_17 := "combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("n_nationkey"), 0))
                                                 - Aggregate(PARTIAL)[n_nationkey] => [n_nationkey:bigint, count_12:bigint]
                                                         Cost: {rows: ? (?), cpu: 500.00, memory: ?, network: 0.00}
                                                         count_12 := "count"(*)
                                                     - TableScan[tpch:tpch:nation:sf1.0, originalConstraint = true] => [n_nationkey:bigint]
                                                             Cost: {rows: 25 (250B), cpu: 250.00, memory: 0.00, network: 0.00}
                                                             n_nationkey := tpch:n_nationkey
                 - LocalExchange[SINGLE] () => count_11:bigint
                         Cost: {rows: ? (?), cpu: 10.00, memory: ?, network: ?}
                     - RemoteExchange[REPLICATE] => count_11:bigint
                             Cost: {rows: ? (?), cpu: 10.00, memory: ?, network: ?}
                         - Aggregate => [count_11:bigint]
                                 Cost: {rows: ? (?), cpu: 10.00, memory: ?, network: 0.00}
                                 count_11 := "count"("expr_10")
                             - Values => [expr_10:boolean]
                                     Cost: {rows: 1 (10B), cpu: 0.00, memory: 0.00, network: 0.00}
                                     (null)
```

Simpler (and probably more performant) rewrite would facilitate `SEMI JOIN`. So rewritten plan is equivalent to plan for query

```
SELECT o_orderkey FROM orders WHERE o_orderkey IN (SELECT n_nationkey FROM nation);
```

cc: @findepi @sopel39 @kokosing

**Comment by kokosing** [comment]
Is this duplicate of https://github.com/prestodb/presto/issues/6384 or just part of it?

**Comment by losipiuk** [comment]
Part. Not requiring changes to semi join. Closing.

**Comment by sopel39** [comment]
Rewriting plan to semi join early in the planning might be a bad choice from a performance/memory point of view. `SemiJoin` is more or less just an implementation of an algebraic operator and there are other alternatives how plan can be executed. I would rather leave rewrite to `SemiJoin` as one of the last planning decisions. If you do this early, you might skip potentially better plans (e.g: with join sides flipped, join reordered, automatic broadcast vs distributed).

**Comment by findepi** [comment]
@sopel39 true, provided that we can do something smart with aggregation+leftouterjoin. And i don't think we can benefit much there.

**Comment by sopel39** [comment]
> true, provided that we can do something smart with aggregation+leftouterjoin

yet `EXISTS` doesn't need to be rewritten into `aggregation+leftouterjoin`, but rather `leftouterjoin+(subquery aggregation)` or `join+(subquery aggregation)` is used with filter

**Comment by atris** [comment]
I think a Semijoin would (mostly) beat a join every time, so the optimiser should try to rewrite an EXISTS query to Semijoin as a heuristic rather than a cost based decision.

@sopel39 Can you please help me in understanding the cases where a broadcast would be better than a semi join? I am trying to wrap my head around all cases where this can fail, so that we can ensure that we don't barf out on an unexpected case. Maybe not executing the transformation rule for those cases would be good enough?

**Comment by findepi** [comment]
@atris why a sem-join is better than a join?

**Comment by atris** [comment]
@findepi I specifically meant the EXISTS clause mentioned above, not as a generic rule (apologies, should have been move verbose).

My specific question was to understand if @sopel39 has any cases in mind where an EXISTS with single equality clause rewritten with a Semi Join would perform worse than a join + aggregation. My idea was to make the EXISTS rewrite to Semi Join as a generic rewrite rule rather than a cost based decision, if the majority of EXISTS with single equality clause benefit from it. If there is a sizeable number of queries that would be adversely affected, then I would want to go down the path of letting the cost evaluation decide if a semi join should be placed or not.

**Comment by sopel39** [comment]
@atris There are few reasons why rewrite to semi join early is not a good decision:
* semi joins cannot be reordered or it's sides flipped.
* partial aggregation below inner join can be beneficial as it might deduplicate rows in source stage.

Because of that I think that https://github.com/prestodb/presto/issues/6384#issuecomment-398660235 is a better rewrite.

**Comment by findepi** [comment]
> partial aggregation below inner join can be beneficial as it might deduplicate rows in source stage.

Good observation. For semi-join we currently don't deduplicate the build side before sending data over the wire. We could have partial aggregation before exchange for that. As usually with partial aggregation, it should be made adaptive, as its effectiveness will heavily depend on attributes of the data.

**Comment by atris** [comment]
@sopel39 Thanks, I see your point. I will work on 6384 then
@findepi Thanks for elaborating, thats a good point. Do we have a ticket for adding that functionality in partial aggregation?

**Comment by kokosing** [comment]
> Do we have a ticket for adding that functionality in partial aggregation?
https://github.com/prestodb/presto/issues/10305
