### ISSUE TITLE
Resource group about cpu control

### ISSUE THREAD

**Issue by imperio-wxm** [prestodb/presto#10212]
I got 3 params can control cpu time in doc.

```java
softCpuLimit
hardCpuLimit
cpuQuotaPeriod
```

Under the condition of my, `hardCpuLimit` is the max value, `softCpuLimit` can  elaxtic shrinkage, but not more than `hardCpuLimit`, `cpuQuotaPeriod` the period redistribution cpu time.

I have a presto cluster, about 10 workers and  I want control resource s.
This is my config of Resource group:
```java
{
  "rootGroups": [
    {
      "name": "offline",
      "softMemoryLimit": "30%",
      "hardConcurrencyLimit": 50,
      "maxQueued": 1000,
      "jmxExport": true
    },
    {
      "name": "online",
      "softMemoryLimit": "70%",
      "hardConcurrencyLimit": 200,
      "maxQueued": 1000,
      "jmxExport": true
    }
  ],
  "selectors": [
    {
      "user": "rt",
      "group": "online"
    },
    {
      "source": "etl",
      "queryType": "SELECT",
      "group": "offline"
    }
  ],
  "cpuQuotaPeriod": "1h"
}
```

Offline group often provide same large table query and take a long time, online group offer real-time query.

1. It is my understanding about 3 params correct?
2. I don't want to make large queries affect real-time query, How should I set the CPU time？

**Comment by raghavsethi** [comment]
1. Yes, it is broadly correct.
2. Presto enforces CPU restrictions by controlling the number of running queries. When a group exceeds its soft limit, it's concurrency is reduced (see InternalResourceGroup:canRunMore). When a group exceeds its hard limit, it is no longer eligible to run any more queries. The manager periodically regenerates quota for all resource groups (the rate is controllable via cpuQuotaPeriod config). So it is not currently possible to completely isolate large queries from affect small queries, given that we do not constrain CPU usage of queries after admission. That being said, Presto is configured by default to do local scheduling based on CPU utilization, so short queries will exit the system much more quickly than long ones. If you want to control how aggressively Presto favors short queries, you can bump up the `task.level-time-multiplier` config property (although I suspect the default value will work for you).

**Comment by imperio-wxm** [comment]
@raghavsethi  

There will be a big query run out of all the resources, and cannot continue to run the small query?
I can tolerate large query failure, but to ensure the new small query can running.

**Comment by imperio-wxm** [comment]
@raghavsethi  

And I have another question.

My config on 3 workers:
```java
query.max-memory=12GB
query.max-memory-per-node=2GB
```
According to the document, a query maximum using 12G memory in the whole cluster and each worker maximum using 2G memory.

However in my query, worker1 used 5.4G, worker2 used 2.8G and worker2 used 5.5G
Every worker's memory more than 2GB and 5.4+2.8+5.5 > 12G.

Is this normal?

**Comment by raghavsethi** [comment]
It's possible to momentarily exceed the query limits, but if this is happening for any significant period of time, that would be weird.
