### ISSUE TITLE
Query kill button is not working

### ISSUE THREAD

**Issue by nezihyigitbasi** [prestodb/presto#10223]
With the latest release I tried killing several queries with the `Kill` button in the query details page and it doesn't work.

**Comment by nezihyigitbasi** [comment]
@yingsu00 This is probably related to your latest changes. Can you please take a look?

**Comment by actgardner** [comment]
The `Kill` button on the Live Plan and Stage Performance tabs is still broken - PR to fix it is linked above.

**Comment by findepi** [comment]
Closing in favor of https://github.com/prestodb/presto/pull/10799 & https://github.com/prestodb/presto/pull/11245
