### ISSUE TITLE
cannot select numeric column, always error : column xxx cannot be resolved

### ISSUE THREAD

**Issue by dadancop** [prestodb/presto#10269]
cannot select numeric column, always error : column xxx cannot be resolved,
but no problem with character varying data type. I use postgres 9.3.
Below is my query : 
for example always get error : column ol.discount cannot be resolved.

sql = sql.append("select c.name as clientname, o.dateordered, bp.value as bpvalue, bp.name as bpname, l.address1 || coalesce(l.city,'') as address, " 
					  + "p.value as productcode, p.name as productname,ol.itemtype,ol.discount, cv.name as clientvendor, o.documentno, ol.qtyordered,ol.priceactual,o.linenetamt, "
					  + "o.docstatus, po.documentno as pono,po.qtyordered as poqty,po.docstatus as postatus, " 
					  + "ov.documentno as sovno, ovl.qtyordered as sovqty, ov.docstatus as sovstatus, "
					  + "msv.documentno as msvno, msv.movementqty as msvqty, msv.docstatus as msvstatus, " 
					  + "arv.documentno as arvno, arv.qtyinvoiced as arvqty, ovl.priceactualmigrate,arv.docstatus as arvstatus, "
					  + "mr.documentno as mrno, mr.movementqty as mrqty, mr.docstatus as mrstatus, " 
					  + "ms.documentno as msno, ms.movementqty as msqty, ms.docstatus as msstatus, "
					  + "ar.documentno as arno, ar.qtyinvoiced as arqty, ar.priceactual as arprice, ar.linenetamt as invoicetotal, ar.docstatus as arstatus, "
					  + "ar.trackingno, ar.koli, o.promotiontype, s.name as shipper, f.name as shipvia, u.name as salesman,o.validto "
					  + "from " + catalog + ".adempiere.c_order o inner join " + catalog + ".adempiere.c_orderline ol on "
					   + "o.c_order_id = ol.c_order_id inner join " + catalog + ".adempiere.c_bpartner bp on o.c_bpartner_id = bp.c_bpartner_id " 
					   + "left outer join " + catalog + ".adempiere.c_bpartner_location bpl on bpl.c_bpartner_location_id = o.c_bpartner_location_id " 
					   + "left outer join " + catalog + ".adempiere.c_location l on bpl.c_location_id = l.c_location_id "   
					   + "left outer join (select h.documentno, d.c_orderline_id,h.docstatus from " + catalog + ".adempiere.c_order h inner join " 
					   + catalog + ".adempiere.c_orderline d on h.c_order_id = d.c_order_id inner join " + catalog + ".adempiere.c_doctype dt " 
					   + "on dt.c_doctype_id = h.c_doctype_id where dt.docbasetype = 'POO' and h.docstatus not in ('RE','VO') ) po " 
					   + "on po.c_orderline_id = ol.link_orderline_id left outer join (select h.poreference,d.m_inoutline_id, d.c_orderline_id, h.documentno, d.movementqty, h.docstatus " 
					   + "from " + catalog + ".adempiere.m_inout h inner join " + catalog + ".adempiere.m_inoutline d on h.m_inout_id = d.m_inout_id " 
					   + "inner join " + catalog + ".adempiere.c_doctype dt on h.c_doctype_id = dt.c_doctype_id where dt.docbasetype = 'MMR' and " 
					   + "h.docstatus not in ('RE','VO')) mr on mr.c_orderline_id = po.c_orderline_id left outer join " 
					   + "(select d.c_orderline_id,h.poreference,d.m_inoutline_id,h.documentno,d.movementqty,h.docstatus from " + catalog 
					   + ".adempiere.m_inout h inner join " + catalog + ".adempiere.m_inoutline d on h.m_inout_id = d.m_inout_id " 
					   + "inner join " + catalog + ".adempiere.c_doctype dt on " 
					   + "dt.c_doctype_id = h.c_doctype_id where h.docstatus not in ('RE','VO') and dt.docbasetype = 'MMS') ms on "
					   + "ms.c_orderline_id = ol.c_orderline_id and ms.poreference = mr.poreference left outer join "
					   + "(select h.documentno,h.docstatus,d.priceactual,d.linenetamt, d.c_orderline_id,d.qtyinvoiced,h.trackingno,h.koli from " + catalog + ".adempiere.c_invoice h " 
					   + "left outer join " + catalog + ".adempiere.c_invoiceline d on h.c_invoice_id = d.c_invoice_id inner join " 
					   + catalog + ".adempiere.c_doctype dt on dt.c_doctype_id = h.c_doctype_id where h.docstatus not in ('RE','VO') "
					   + "and dt.docbasetype = 'ARI') ar on ar.c_orderline_id = ol.c_orderline_id " 
					   + "left outer join " + catalog + ".adempiere.ad_user u on u.ad_user_id = o.salesrep_id "
					   + "left outer join " + catalog + ".adempiere.m_product p on p.m_product_id = ol.m_product_id " 
					   + "left outer join " + catalog + ".adempiere.c_doctype dt on o.c_doctype_id = dt.c_doctype_id "
					   + "left outer join " + catalog + ".adempiere.ad_client c on c.ad_client_id = o.ad_client_id ");
	
					sql.append("left outer join " + db[i] + ".adempiere.c_order ov on ov.poreference = o.documentno left outer join "
					   + db[i] + ".adempiere.c_orderline ovl on ovl.c_orderline_id = ov.c_orderline_id and ovl.line = ol.line left outer join " 
					   + "(select d.c_orderline_id,h.poreference,h.m_shipper_id,h.m_freightcategory_id, d.m_inoutline_id,h.documentno,d.movementqty,h.docstatus from " + vendor[i] 
					   + ".adempiere.m_inout h inner join " + db[i] + ".adempiere.m_inoutline d on h.m_inout_id = d.m_inout_id "
					   + "inner join " + db[i] + ".adempiere.c_doctype dt on " 
					   + "dt.c_doctype_id = h.c_doctype_id where h.docstatus not in ('RE','VO') and dt.docbasetype = 'MMS') msv "
					   + "on msv.c_orderline_id = ovl.c_orderline_id left outer join " 
					   + "(select h.documentno,h.docstatus,d.priceactual,d.linenetamt, d.c_orderline_id,d.qtyinvoiced from " + db[i] + ".adempiere.c_invoice h " 
					   + "left outer join " + db[i] + ".adempiere.c_invoiceline d on h.c_invoice_id = d.c_invoice_id inner join " 
					   + db[i] + ".adempiere.c_doctype dt on dt.c_doctype_id = h.c_doctype_id where h.docstatus not in ('RE','VO') "
					   + "and dt.docbasetype = 'ARI') arv on arv.c_orderline_id = ovl.c_orderline_id " 
					   + "left outer join " + db[i] + ".adempiere.m_shipper s on s.m_shipper_id = msv.m_shipper_id " 
					   + "left outer join " + db[i] + ".adempiere.m_freightcategory f on f.m_freightcategory_id = msv.m_freightcategory_id "
					   + "left outer join " + db[i] + ".adempiere.ad_client cv on cv.ad_client_id = ov.ad_client_id "
					   + "left outer join (select max(c_bpartner_id) as c_bpartner_id,m_product_id from " + catalog + ".adempiere.m_product_po "
					   + "where iscurrentvendor = 'Y' group by m_product_id) pp on pp.m_product_id = ol.m_product_id "
					   + "left outer join " + catalog + ".adempiere.c_bpartner vendor on vendor.c_bpartner_id = pp.m_product_id where vendor.value = '"
					   + vendor[i] + "' and o.docstatus in ('CO','CL') and o.datetrx between date '" + sFromDate + "' and date '" + sToDate
					   + "' and o.issotrx = 'Y' and dt.docbasetype = 'SOO' ");

**Comment by sopel39** [comment]
Could you use shorter query to explain the problem and capture the issue?

**Comment by dadancop** [comment]
![screenshot_1](https://user-images.githubusercontent.com/30205877/37959268-eec97afc-31dc-11e8-8ec9-62dbe2e989ae.jpg)

ok. i have upload screenshot when i run from command line interface. every numeric column in my table cannot be resolved.

**Comment by sopel39** [comment]
I would guess postgresql `numeric` columns are not exposed in postgres connector. This is non-trivial because postges has unlimited precision, while Presto decimal has max precision of 38. You could try converting to other numeric types.

FYI: @findepi

**Comment by dadancop** [comment]
maybe i know the problem , my datatype of movementqty in postgres is numeric, but by presto is known as decimal which does not supported.
i just read this limitation 

Data types not supported

Columns with the following types are not visible in a table through Presto:

        DECIMAL
        DECIMAL with parentheses
        CHAR
        VARCHAR is not supported in ORC and RCBinary file formats.

what data type of number which i must used on postgres ?

**Comment by sopel39** [comment]
You could use explicit decimal with precision, scale or numeric types like integer, smallint, bigint, etc...
Floating points should also be supported

**Comment by dadancop** [comment]
ok.thanks you . i will try change to numeric(15,2)  later because many object depending on it...i think it will worked.

**Comment by findepi** [comment]
indeed, postgre's `numeric` cannot work, Presto doesn't have arbitrary precision lossless numeric type.
`numeric(15,2)` will work.

**Comment by dadancop** [comment]
thx, findepi. I have changed the datatype, and my query work perfectly.
