### ISSUE TITLE
Presto Rest API V2 Client

### ISSUE THREAD

**Issue by hakenmt** [prestodb/presto#10263]
Is the V2 REST API "/v2/statement" actually enabled in the current release version? [Here](https://github.com/prestodb/presto/wiki/Presto-v2-client-protocol ) it states to set `experimental.enable-client-protocol-v2=true` (I'm guessing in the config.properties file on each worker and coordinator), however, when I do this I get an error: 

Configuration property 'experimental.enable-client-protocol-v2' was not used
presto_coordinator |   at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:234)

Using version 0.197.

**Comment by kokosing** [comment]
It is still in progress, it does not fully work yet.
