### ISSUE TITLE
Can`t query mysql table using a uppercase name

### ISSUE THREAD

**Issue by devilcony** [prestodb/presto#10288]
happens when querying a mysql table with a uppercase name ,and mysql server is case sensitive
query like this: select * from mysql.test."MY_TEST"
the presto server returns this: Table 'mysql.test.my_test' does not exist

**Comment by findepi** [comment]
Hi @devilcony 
This is known limitation. Currently, all identifiers in Presto are lowercase.  See https://github.com/prestodb/presto/issues/3470 and https://github.com/prestodb/presto/issues/2863

**Comment by tooptoop4** [comment]
any update? hive metastore tables in mysql like DBS, PARTITIONS can't be queried. 

presto> select * from mysql.metastore.DBS;
Query 20180913_015448_00010_774as failed: line 1:15: Table mysql.metastore.dbs does not exist

**Comment by findepi** [comment]
@tooptoop4 this is a duplicate; please follow the original issue (and/or my recent PR: https://github.com/prestodb/presto/pull/11633)
