### ISSUE TITLE
Differentiate hive bucketing error from hive table corruption

### ISSUE THREAD

**Issue by elonazoulay** [prestodb/presto#10294]
Change the error message and error type for mismatched bucket counts.
To improve the clarity of the error message for users so that table corruption can be differentiated from bucket count mismatch.

**Comment by elonazoulay** [comment]
This is related to #8557

**Comment by electrum** [comment]
We already use `HIVE_PARTITION_SCHEMA_MISMATCH` with a message like `"Hive table ... bucketing ... does not match partition ... bucketing"`. The `HIVE_INVALID_BUCKET_FILES` error should only be for true cases of corruption.
