### ISSUE TITLE
json annotations on implementation classes from plugins

### ISSUE THREAD

**Issue by hgschmie** [prestodb/presto#10304]
To be able to use Google Auto Value (https://github.com/google/auto/tree/master/value) created beans  as value classes with Jackson, a little bit of json trickery is required to get jackson to serialize and deserialize these beans correctly. In a nutshell, a bean would look like this:

```java

@AutoValue
@JsonSerialize(as = MyTableHandle.class)
@JsonDeserialize(builder = MyTableHandle.Builder.class)
public abstract class MyTableHandle implements ConnectorTableHandle {

    public static Builder builder() {
        return Builder.builder();
    }

    public abstract Builder toBuilder();

    @JsonProperty
    public abstract SchemaTableName getSchemaTableName();

    @AutoValue.Builder
    public abstract static class Builder {

        @JsonCreator
        public static Builder builder() {
            return new AutoValue_MyTableHandle.Builder();
        }

        @JsonProperty("schemaTableName")
        public abstract Builder setSchemaTableName(SchemaTableName schemaTableName);

        public abstract MyTableHandle build();
    }
}
```
The json annotation trickery is required because the autogenerated bean looks like this:

```java
@Generated("com.google.auto.value.processor.AutoValueProcessor")
 final class AutoValue_MyTableHandle extends MyTableHandle {

  private final SchemaTableName schemaTableName;

  private AutoValue_MyTableHandle(
      SchemaTableName schemaTableName) {
    this.schemaTableName = schemaTableName;
  }

  @JsonProperty
  @Override
  public SchemaTableName getSchemaTableName() {
    return schemaTableName;
  }

  @Override
  public String toString() {
    return "MyTableHandle{"
        + "schemaTableName=" + schemaTableName
        + "}";
  }

  @Override
  public boolean equals(Object o) {
    if (o == this) {
      return true;
    }
    if (o instanceof MyTableHandle) {
      MyTableHandle that = (MyTableHandle) o;
      return (this.schemaTableName.equals(that.getSchemaTableName()));
    }
    return false;
  }

  @Override
  public int hashCode() {
    int h = 1;
    h *= 1000003;
    h ^= this.schemaTableName.hashCode();
    return h;
  }

  @Override
  public MyTableHandle.Builder toBuilder() {
    return new Builder(this);
  }

  static final class Builder extends MyTableHandle.Builder {
    private SchemaTableName schemaTableName;
    Builder() {
    }
    private Builder(MyTableHandle source) {
      this.schemaTableName = source.getSchemaTableName();
    }
    @Override
    public MyTableHandle.Builder setSchemaTableName(SchemaTableName schemaTableName) {
      if (schemaTableName == null) {
        throw new NullPointerException("Null schemaTableName");
      }
      this.schemaTableName = schemaTableName;
      return this;
    }
    @Override
    public MyTableHandle build() {
      String missing = "";
      if (this.schemaTableName == null) {
        missing += " schemaTableName";
      }
      if (!missing.isEmpty()) {
        throw new IllegalStateException("Missing required properties:" + missing);
      }
      return new AutoValue_MyTableHandle(
          this.schemaTableName);
    }
  }
}
```
so the tricky piece is that the generated class is not public (but package private). So, to be able to access the fields correctly, Jackson needs to be hinted to use the right methods from the (public) `MyTableHandle` class and not the introspected methods from the `AutoValue_MyTableHandle` class.

Unfortunately `JsonSerialize` and `JsonDeserialize` are not part of the jackson-annotations package but of jackson-databind. Which is not part of the exposed SPI. So my beans, when they get passed from the connector to the engine have these annotations but they come from a different class loader. And therefore, the object mapper within the presto engine does not recognize these annotations, does not obey them and the beans can not be serialized (or deserialized). 

Any chance to make the classes in `com.fasterxml.jackson.databind.annotation` part of the exposed presto SPI? Or the whole `jackson-databind` jar?

**Comment by hgschmie** [comment]
Well, it seems that this problem is not easily solvable with the Presto plugin classloader. 

When pulling only the databind.annotations package into the SPI, the classes in the annotation package have additional dependencies into other databind packages and in turn, even pulling the whole databind package does not work b/c it has references to jackson-core.

To get Google AutoValue beans to work, I had to pull all of jackson.core *and* jackson.databind into the SPI classes. Hardly ideal. 

There are similar issues when the beans would expose e.g. Guava classes. I guess the Plugin development guide should explicitly state that classes passed from plugins into the presto engine itself (anything referenced from the handle resolver) can only expose classes from the JDK, presto-spi, airlift slice and airlift units.

**Comment by findepi** [comment]
> To get Google AutoValue beans to work, I had to pull all of jackson.core and jackson.databind into the SPI classes. Hardly ideal.

@hgschmie was your conclusion that this cannot be fixed?
