### ISSUE TITLE
Allow plugin installation without unzipping

### ISSUE THREAD

**Issue by findepi** [prestodb/presto#10325]
Plugin is typically built into a zip file (i.e. when `<packaging>presto-plugin</packaging>` is used). The zip file is supposed to be unzipped to a folder under Presto server's `plugin/` directory.
Now, it would be simpler if the zip file could be just dropped into the `plugin/` directory, without unzipping.

**Comment by findepi** [comment]
> The plugin does need to be unpacked because you can load classes from a jar file inside of a zip file.

The way uber jar works is making a classpath out of jars in a jar. This should be the same for jars in a zip. Doesn't that work?

**Comment by dain** [comment]
That would require a different packaging of the plugin.   Basically, you have to unpack the nested jars so the class files end up at the top level zip. For example
Current, zip listing:
```
/foo.jar
/bar.jar
```
New, zip listing:
```
/foo.jar/META-INF/MANIFEST.MF
/foo.jar/com/foo/some/package/a.class
/foo.jar/com/foo/some/package/b.class
/bar.jar/META-INF/MANIFEST.MF
/bar.jar/org/bar/some/package/x.class
/bar.jar/org/bar/some/package/y.class
```
I believe this would require a custom class loader, and may cause problem with Java9+ modules.  Alternatively, you can squash all files into one jar, but then you have to figure out how to merge the META-INF directories, which is non-trivial in Java9+.

**Comment by findepi** [comment]
i don't want any change in zip packaging. Current packaging is very close to how spring boot executable jars are constructed (bunch of jars + Main class that bootstrap a sub-classloader from these jars).

**Comment by electrum** [comment]
How does it work if the jar is compressed inside the zip file? I don’t think you can get random access inside the zip file entry, so you need to uncompress the entry (jar file) and put it somewhere (or decompress every time).
