### ISSUE TITLE
RetainedSizeInBytes for VariableWidthBlock is high when it is de serialized.

### ISSUE THREAD

**Issue by Praveen2112** [prestodb/presto#10337]
When a VariableWidth Block or a Dictionary Block (whose Dictionary is a VariableWidthBlock) is de serialized , the retainedSize for those blocks are very high. The raw content of the serializedPage are stored in a slice. When we try to de serialize a VariableWidth block, we use `sliceInput.readSlice(blockSize)` to get the Slice for the block, but the retainedSize for the Slice which is used in VariableWidthBlock same as that of the slice which maintains the entire serialized page. So if n such VariableWidthBlock is present in a page, the resulting `retainedSizeInBytes` for a page is very high than the actual memory consumed. One work-around is to use `Slices.copyOf(sliceInput.readSlice(blockSize))` instead of referring the underlying slice but it will result in copying of data. 

This affects when loading data to the memory connector(memory.max-data-per-node = 10G). Say if I run 

> create table a as select * from b

the ratio between the retainedSizeInBytes/sizeInBytes for each page crosses 20. So even if my table b has 1GB of data in memory , I am not able to load it to the memory connector.

**Comment by nezihyigitbasi** [comment]
When a slice is deserialized for a `VariableWidthBlock` we get a view of the slice with `sliceInput.readSlice(blockSize);` (see `VariableWidthBlockEncoding`), so I guess in this case Presto is over accounting the slice retained size as the "base" slice is considered, instead of just the "view" we are interested in. As you noticed copying that "view" only will solve the issue, but we don't know how much the additional copying overhead will be. Another option can be using a `ReferenceCountMap` to de-dup these slices like we do in `SliceBigArray`.

**Comment by Praveen2112** [comment]
Moreover for DictionaryBlocks whose Dictionary is a Variable Width Block type , when we do a compacting we have make sure that the dictionary is also compacted. It again leads to wrong computation of retained size which in turn might trigger the compaction process which is not required (for PagesIndex operator). 

What if we could give a retained size for certain blocks instead of those blocks computing it ?

**Comment by electrum** [comment]
Maybe we could have a heuristic in the memory connector to compact if the ratio is too high? We don’t want to always compact, since dictionary blocks might actually be using less memory.

**Comment by Praveen2112** [comment]
Yes we can do that and the same could also be implemented for DictionaryBlock. When a Dictionary block is de serialized, we assume that 

>         // We always compact the dictionary before we send it. However, dictionaryBlock comes from sliceInput, which may over-retain memory.
>         // As a result, setting dictionaryIsCompacted to true is not appropriate here.

But when we invoke `compact` we are not compacting the dictionary in this case. What happens is that when we invoke `compact` (Correct me If I am wrong)

1. We check whether the Dictionary Block is compacted or not so we invoke `isCompact`
2. `isCompact` checks `uniqueId > 0` if not he tries to compute it by calling this method `calculateCompactSize`
3. Now this method iterates through the block and sets the `uniqueIds = dictionary.getPositionCount()` (because the Dictionary is compacted before serializing)
4. Now `isCompact` returns true so we don't do any compaction but `retainedSize` of the dictionary would be size of the base slice.

I think we should also check the ratio when we are compacting.

**Comment by dain** [comment]
I don't know how the memory connector works, but you should be aware that dictionaries can be (and normally are) shared across many blocks.  Compacting the blocks independently can result in a increase in memory.

**Comment by Praveen2112** [comment]
@dain The Dictionaries which are shared across many blocks is true when it is created from Orc or Parquet files. Does the above statement holds good when we are populating the dictionaries from a serialized pages ?

**Comment by dain** [comment]
@Praveen2112, I don't think that currently holds for dictionaries from serialized pages, but that might change with the pending rewrite of the `PartitionedOutputOperator`.

**Comment by Praveen2112** [comment]
@dain, Okay. The above problem is not only faced by the memory connector but also by the `PageIndexOperator`( When the PageIndexOperator's source is a `RemoteSourceOperator` this will be achieved when task-concurrency =1). In that operator if the memory consumed by it crosses a threshold we try to compact it. There are two problems here:
1. The signal that the memory consumed by the operator crosses the threshold is a false one , we are referring the same underlying slice n times. (Compacting is not required but we do it because of the false signal)
2. Then the PageIndexOperator  tries to compact the pages and if the pages has some DictionaryBlocks they will not be properly compacted because of the above issue.

So it might results in spilling or canceling the query even though there is resource available.

**Comment by sopel39** [comment]
Maybe we should also use `ReferenceCountMap` in `PagesIndex` to be smarter about double accounting of deserialized pages memory. This is a problem especially when there are many columns. Example affected plans are distributed sort and potentially others (e.g: window functions with task concurrency=1)

Related comment: https://github.com/prestodb/presto/pull/10633#issuecomment-389823680
