### ISSUE TITLE
(Failed to start presto nodes)java.net.ConnectException: Failed to connect to localhost/127.0.0.1:8080

### ISSUE THREAD

**Issue by rsajjan2** [prestodb/presto#10357]
Below is the snapshot of error, Please help me out
presto> select * from system.runtime.nodes;
Error running command: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:8080
I tried using local ip address and 10.0.2.2 yet same error

**Comment by findepi** [comment]
This basically means that presto is not running -- for whatever reason, see logs. Logs location depends on how you started Presto.

I'm closing this in favor of your question on SO https://stackoverflow.com/questions/49751143/prestodb-failed-to-launch-presto-server-and-no-nodes-running

**Comment by zzr1000** [comment]
you may connect presto like this : "presto --catalog system" , not giving the "--server" information ; the presto gives the default host and port information : localhost/127.0.0.1:8080

**Comment by patilharshal16** [comment]
> This basically means that presto is not running -- for whatever reason, see logs. Logs location depends on how you started Presto.
> 
> I'm closing this in favor of your question on SO https://stackoverflow.com/questions/49751143/prestodb-failed-to-launch-presto-server-and-no-nodes-running



> This basically means that presto is not running -- for whatever reason, see logs. Logs location depends on how you started Presto.
> 
> I'm closing this in favor of your question on SO https://stackoverflow.com/questions/49751143/prestodb-failed-to-launch-presto-server-and-no-nodes-running

By running presto one could solved this issue.
