### ISSUE TITLE
Missing comma between fields in select statement does not cause parsing error

### ISSUE THREAD

**Issue by puneetjaiswal** [prestodb/presto#10358]
A query like `select x,y z from test_table` does not throw parsing exception. (There is a comma missing between fields y and z and this should throw ParseException as the query is syntactically incorrect)

```
        SqlParser SQL_PARSER = new SqlParser();
        String query = "select x,y z from test_table";
        Statement st = SQL_PARSER.createStatement(query);
```
Can we fix the SQL grammar ?

**Comment by haozhun** [comment]
`select x,y z from test_table` is shorthand for `select x, y AS z from test_table`.

I agree this syntax rule is terrible because it hides errors/typos.

However, it is legitimate SQL syntax, and we've chosen to stick to that syntax here. https://en.wikipedia.org/wiki/Alias_(SQL)

**Comment by puneetjaiswal** [comment]
Thanks @haozhun  for looking into it quickly.

AFAI knew, 'AS' can be omitted for table alias but is mandatory for column aliases. Even your link has not shown dropping AS for column aliases.

Another example:
https://github.com/linkedin/pinot/blob/master/pinot-common/src/main/antlr4/com/linkedin/pinot/pql/parsers/PQL2.g4#L37

But again if it is decided to keep AS optional for column aliases, I guess I am fine with that.

Thanks.

**Comment by findepi** [comment]
@puneetjaiswal unfortunately i'm last to check the spec, but I think it's quite normal for SQL databases not to require "AS" for column aliases.
While this syntax leads to errors (as in this case), dropping it would lead to compatibility problems for others, not ideal either.

**Comment by electrum** [comment]
Here’s the SQL 92 grammar: https://ronsavage.github.io/SQL/sql-92.bnf.html#select%20sublist

Note the square brackets around the AS clause which means it is optional.

**Comment by puneetjaiswal** [comment]
@findepi / @electrum  - sounds good. Thanks :) !
