### ISSUE TITLE
presto-tests should not depend on presto-main test jar

### ISSUE THREAD

**Issue by kokosing** [prestodb/presto#10363]
Now `presto-tests` is using:
```
        <dependency>
            <groupId>com.facebook.presto</groupId>
            <artifactId>presto-main</artifactId>
        </dependency>

        <dependency>
            <groupId>com.facebook.presto</groupId>
            <artifactId>presto-main</artifactId>
            <type>test-jar</type>
        </dependency>
```
because of the usage of `presto-main` `test-jar` in `presto-tests`, tests from `presto-main` cannot access tests utilities from `presto-tests` (src/main). Dependency cycle.

I think all tests utilities should be in `presto-tests` (src/main) so tests from `presto-main` or any other module could use it without a dependency cycle.

I have not investigated this deeply, so I might not see all the dependency issues here. Any thoughts are welcome.

**Comment by findepi** [comment]
Or we could have a dedicated module for test-focused utilities (e.g. query runner, query assertions) to keep this separate from `presto-main`. And a dedicated module for engine's tests (`presto-tests`). The test utilities would be reused in connector tests.

**Comment by kokosing** [comment]
> Or we could have a dedicated module for test-focused utilities (e.g. query runner, query assertions) to keep this separate from presto-main. And a dedicated module for engine's tests (presto-tests). The test utilities would be reused in connector tests.

It sounds like a bomb and that would also mean almost no tests in `presto-main`. I am fine with the idea, this could be something where we could slowly and iteratively drive to.

**Comment by dain** [comment]
Before going further down the implementation path, can you layout what the final setup would look like.  I ask because my memory was benchmarks was moved out of tests for a reason (which I don't remember now), so my hope is as we get farther in the ultimate design, we can see if this is going to work (and hopefully remember the original issues).

**Comment by kokosing** [comment]
Moving benchmarks was not a good idea, see https://github.com/prestodb/presto/pull/10369#issuecomment-380352211. Sorry about that.

I am not sure how final layout should look like. Mostly because I do not know the root issue which `presto-tests` is solving.

What if we would do the simplest thing possible and just move test utilities and tests from `presto-tests` to `presto-main` `src/tests`. Then connectors tests would just use `presto-main` `test-jar` and `presto-tests` will be removed at all. Is there a reason why it is wrong approach?
