### ISSUE TITLE
Order by in array_agg error

### ISSUE THREAD

**Issue by thanhlv93** [prestodb/presto#10370]
Hello All,
I'm using presto and hive to query data. My Presto version is 0.187.
My query : 

> select enqueueJobLocation, max(workerQueueSize) as max, array_agg(timesys order by workerQueueSize) as timesys 
  from hs_tbl_worker_orc 
  group by enqueueJobLocation 
  order by max desc limit 5;

But I got an error message :  mismatched input 'order' expecting {'.', ')', ',', '[', 'AND', 'AT', 'BETWEEN', 'IN', 'IS', 'LIKE', 'NOT', 'OR', '=', NEQ, '<', '<=', '>', '>=', '+', '-', '*', '/', '%', '||'}

I dont know how to fix this error, Please tell me if you have any suggest. Thanks all.

**Comment by findepi** [comment]
https://prestodb.io/docs/current/release/release-0.190.html says 
> Add support for ORDER BY in aggregation functions.

please upgrade
