### ISSUE TITLE
Is there any parameter to control max bytes or max row for each page?

### ISSUE THREAD

**Issue by photogamerun** [prestodb/presto#10379]
I just to want to know is there any parameter in presto to controller max bytes or max row for each page?

**Comment by findepi** [comment]
It's not configurable: `com.facebook.presto.spi.block.PageBuilderStatus#DEFAULT_MAX_PAGE_SIZE_IN_BYTES`

**Comment by dain** [comment]
BTW the expected direction is for this property to be dynamically managed by the server, instead of statically configured.
