### ISSUE TITLE
Reading MapBlockEncoding makes expensive resolveOperator call per Block

### ISSUE THREAD

**Issue by wenleix** [prestodb/presto#10386]
We have seen queries spending a lot of time reading `MapBlockEncoding` since `resolveOperator` is expensive. Here is an example flame chart:

![screen shot 2018-04-03 at 15 54 54](https://user-images.githubusercontent.com/799346/38658115-88187a4e-3dd8-11e8-91bd-6e716e6f32c8.png)

Here is the `readEncoding` method:

https://github.com/prestodb/presto/blob/e62734ba19f0958e3b88f69a10ff9b17a4926325/presto-spi/src/main/java/com/facebook/presto/spi/block/MapBlockEncoding.java#L127-L138

We  have thought about three types of solutions:

## 1. Cache First Order Functions

A WIP PR can be found in https://github.com/prestodb/presto/pull/10381. A potential problem we are still generating `keyBlockNativeEquals` MethodHandle per each block.

Potentially, it will cause worse performance for later `seekKey` or repeatedly customized MethodHandles. We haven't seen any evidence this can be a major performance issue, though. 

## 2. Cache the 3 MethodHandles in MapBlockEncodingFactory

The issue with this approach is that `typeManager` is not a field in `MapBlockEncodingFactory`.  And resolve these operators requires `typeManager`. We cannot do this unless we make `typeManager` as a cache key, which is really weird. 

To go this way, we might need to add `typeManager` to the constructor of `MapBlockEncodingFactory`.

## 3. Store the 3 MethodHandles in MapType, and cache MapType

The issue with this approach is that `MapType` are in `spi.type`. So there are two alternatives:

* fetch these 3 MethodHandles from the `MapType` somehow, or
* it delegate the `seekKey` and `buildHashTable` to `MapType`.

Both doesn't look ideal.

----------------------------------------------------

Given the current solution space, my recommendation is to start with the first approach since caching first order functions is on the correct long term direction. If we have more evidence that the per-block  `keyBlockNativeEquals` is causing issue later, we can figure out the solution to it.

thoughts? @haozhun , @dain

**Comment by haozhun** [comment]
Summary of our in person discussion.

Option 1:

* It treats functions that take lambda as second class performance wise.

Option 2:

* Introducing cache is weird because TypeManager is passed in for every invocation (instead of in constructor). (#10390 fixes this)

Option 3 Alternative 1:

* `MapType` is in SPI. Introducing public methods for internal use can be problematic

Option 3 Alternative 2:

* MapType will need to understand the internal details of Map Blocks and access its internals directly.
