### ISSUE TITLE
TestMathFunctions.testRound() failure

### ISSUE THREAD

**Issue by nezihyigitbasi** [prestodb/presto#10398]
@findepi this failure looks related to https://github.com/prestodb/presto/commit/0f11ff6246b8b6a4f9166507e81b399336cd122c, any ideas? I cannot reproduce this locally. The entire log is [here](https://gist.github.com/nezihyigitbasi/38d9ae3ddc306240aba36c53a3039a3a). I saw this failure with https://github.com/prestodb/presto/pull/10395, which doesn't change any code path that will affect this test.

```
[ERROR] Tests run: 3924, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 787.309 s <<< FAILURE! - in TestSuite
[ERROR] testRound(com.facebook.presto.operator.scalar.TestMathFunctions)  Time elapsed: 0.925 s  <<< FAILURE!
com.facebook.presto.sql.analyzer.SemanticException: 
line 1:1: Could not choose a best candidate operator. Explicit type casts must be added.
Candidates are:
	 * round(tinyint,integer):tinyint
	 * round(tinyint,bigint):tinyint

	at com.facebook.presto.operator.scalar.TestMathFunctions.testRound(TestMathFunctions.java:764)

2018-04-13T23:53:55.901+0545	INFO	Thread-211	io.airlift.bootstrap.LifeCycleManager	Life cycle stopping...
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   TestMathFunctions.testRound:764->AbstractTestFunctions.assertFunction:94 Â» Semantic
[INFO] 
[ERROR] Tests run: 3924, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by findepi** [comment]
hm... we should probably include parameter types in the exception raised from `FunctionRegistry#matchFunction`.

Anyway -- 
My understanding is that: `round(tinyint,integer):tinyint` should be chosen if applicable (when second arg is coercible to integer), as this is the most specific function.
Otherwise `round(tinyint,bigint):tinyint` should be chosen  if applicable (when second arg is coercible to bigint).
Otherwise error.

Am i wrong?

**Comment by nezihyigitbasi** [comment]
I think you are right and that's what I expect. When I run this test locally (a few hundred times) it chooses consistently `round(tinyint,integer):tinyint` and the test passes. However, I hit this failure once in that PR and I am confused as I didn't expect any non-determinism in that code path.
