### ISSUE TITLE
Skip queries with TABLESAMPLE in verifier

### ISSUE THREAD

**Issue by nezihyigitbasi** [prestodb/presto#10417]
Verifier should skip queries with `TABLESAMPLE` as they are non-deterministic.

**Comment by mbasmanova** [comment]
There are a few other sources of non-determinism:

* LIMIT clause
* rand and random functions
* approx_distinct, approx_percentile functions
* array_agg, array_distinct, map_agg functions
* min_by, max_by (when sort-by column has duplicates)

**Comment by mbasmanova** [comment]
I think manually checking non-deterministic queries will always be time-consuming and labor-intensive. To be absolutely sure, one needs to understand what the query is doing and find a way to confirm that discrepancy comes only from non-determinism. However, flagging query as non-deterministic would help. We could then have a policy that deterministic queries must pass and results must match, but non-deterministic queries just need to pass and results may not match.

**Comment by caithagoras** [comment]
No longer related
