### ISSUE TITLE
presto does not seem to like numbers in table names

### ISSUE THREAD

**Issue by rookie7799** [prestodb/presto#10438]
Presto version 0.196

```
show tables;
 ------------------
 test_name
 test2_name
```

`select * from test_name;`
yields results, however,
`select * from test2_name; `
returns

> Query 20180418_175234_00045_rifw3 failed: Table 'db20.test2_name' not found

**Comment by sopel39** [comment]
which connector is it?

**Comment by rookie7799** [comment]
Mysql

**Comment by electrum** [comment]
Please run `SHOW TABLES` in MySQL itself and confirm that `test2_name` does not have any uppercase characters. If so, that is probably the issue (not the number).

**Comment by rookie7799** [comment]
Nobody else has this issue ?
