### ISSUE TITLE
can't access mssql table

### ISSUE THREAD

**Issue by unrealzhou** [prestodb/presto#10450]
I use presto-server-0.196 access SQL Server

[root@master2 presto]# ./presto196 --server master1:8081 --catalog sqlserver --schema dbo
```
presto:dbo> show tables;
         Table         
-----------------------
 msreplication_options 
 spt_fallback_db       
 spt_fallback_dev      
 spt_fallback_usg      
 spt_monitor           
 spt_values            
(6 rows)
```
only show the System Tables of master database in SQL Server, How to change Database? How to show the user-created tables?

**Comment by rschlussel2** [comment]
if you want to see tables in other schemas you can use the `use` command to switch schemas.  For example, if your schema were called "my_schema", you would run: `use sqlserver.my_schema;`
Additionally, when you start the cli you can specify "my_schema" as the schema you want to start in by setting
`--schema my_schema` instead of `--schema dbo`

to see available schemas in your sqlserver catalog you can run `show schemas`

**Comment by unrealzhou** [comment]
thanks rschlussel2

In MS SqlServer,there are many database of one instance,for example:
```
`SELECT Name FROM Master..SysDatabases`
master
SDAS_1
SDAS_2
SDAS_3
```

sqlserver.properties only set the server address, port and instance name,can't set the database name,for example:
cat sqlserver.properties
```
connector.name=sqlserver
connection-url=jdbc:sqlserver://192.168.8.22:1433
connection-user=sa
connection-password=123456
```

`./presto --server master1:8081 --catalog sqlserver --schema dbo`
use this command, default is 'master' database, I know use next command change catalog and schema:
`presto:sys> use sqlserver.dbo;`

but how to change Database ?  such as 'SDAS_1', not 'master'

**Comment by unrealzhou** [comment]
set "connection-url" property, add database name, can resolve the problem, for example:
```
[root@master1 catalog]# vim sqlserver.properties
connector.name=sqlserver
connection-url=jdbc:sqlserver://192.168.8.22:1433/SDAS_2
connection-user=sa
connection-password=dev2016
```

thanks

**Comment by Hubbitus** [comment]
It works only like (by https://groups.google.com/forum/#!topic/presto-users/C3xhdOguqRc):
```
connection-url=jdbc:sqlserver://abc:1433;databasename=SecretDatabase;
```
