### ISSUE TITLE
0.200 release notes

### ISSUE THREAD

**Issue by nezihyigitbasi** [prestodb/presto#10465]
Issue to track release notes for the next release.

**Comment by findepi** [comment]
```
Hive
----
* Fix reading min/max statistics for a column of type REAL in case of a partitioned table.
```

**Comment by sopel39** [comment]
```
Hive
----
* Make Presto read ORC files with UTF8 Bloom filter stream.
```

**Comment by electrum** [comment]
```
General Changes
---------------

* Allow including a comment when adding a column to a table with ``ALTER TABLE``.

**Comment by electrum** [comment]
```
MySQL Changes
-------------

* Avoid reading extra rows from MySQL at query completion.
  This typically affects queries with a ``LIMIT`` clause.

**Comment by haozhun** [comment]
@electrum @kokosing @sopel39 @mbasmanova @martint @nezihyigitbasi @findepi @wenleix 

## David Phillips
- [ ] all checked
-  04-20 10:37:54    d1540017f3 Add from_ieee754_32 and from_ieee754_64
-  04-23 09:42:23    2924d03b73 Allow including a comment when adding a column to a table
-  04-23 09:43:27    08fa7f304b Include type name in error message for invalid types
-  04-24 14:34:05    433d488e2a Prevent MySQL connector from reading rows after close
-  04-24 14:34:05    d0ec8ce979 Cleanup exception handling in JDBC connector
## Grzegorz Kokosiński
- [ ] all checked
-  04-20 00:10:17    673f6a6604 Make s3 fs rename fail if it is already renamed
-  04-20 00:11:04    c12daee0cf Use target path for table location
-  04-24 12:51:53    1c205c34e8 Update docker images for hive tests
-  04-24 12:51:53    a1d37b3f67 Cleanup docker containers before starting them
## Haozhun Jin
- [ ] all checked
-  04-20 12:39:17    19a3029d5b Remove singleton instance of block encodings
-  04-20 12:39:17    33bdb59ba7 Extract LiteralInterpreter.toExpression as LiteralEncoder class
-  04-20 12:39:17    4db3d6d98b Remove unused BlockEncoding.getFactory
-  04-20 12:39:17    8cebbc7b43 Make EffectivePredicateExtractor not a subclass of PlanVisitor
-  04-20 12:39:17    d0b987ab40 Clean up TestingBlockEncodingSerde
-  04-20 12:39:17    d406c7beb8 Formalize the concept of replacement block for serialization
-  04-20 12:39:17    f2f8d2df44 Remove TypeManager parameter from BlockEncodingFactory.readEncoding
-  04-20 12:39:17    fa594787eb Remove hack to serialize a Block without using BlockEncodingSerde
-  04-20 15:41:52    90a52a8282 Simplify Block serialization/deserialization
-  04-20 15:41:52    9f4cbdeeac Move TestColumnarArray/Map/Row to presto-main
-  04-20 15:41:52    fc3d662506 Rename methods to get nested Block in Array/Row/MapBlock
## Karol Sobczak
- [ ] all checked
-  04-20 02:48:54    f3c1f17ca0 Ignore BLOOM_FILTER_UTF8 ORC streams
-  04-20 02:57:42    e1ccc40282 Run Hive Glue test on Travis
-  04-20 07:20:10    6088cac2f9 Use MySQL, PostgreSQL and MSSQL images version in product tests
## Maria Basmanova
- [ ] all checked
-  04-20 12:12:13    108d60ca39 Add ST_GeometryType and tests
-  04-20 12:12:13    409e0fe3b7 Split GeometryType enum into two: GeometryType and GeometrySerializationType
## Martin Traverso
- [ ] all checked
-  04-24 13:47:51    480d0f271d Do not derive all grouping sets when traversing tree
## Nezih Yigitbasi
- [ ] all checked
-  04-23 08:43:00    0a3cf89e07 Remove unused method
## Piotr Findeisen
- [ ] all checked
-  04-20 03:52:49    11dc50ec3d Fix decoding min/max REAL value in Hive stats
-  04-23 00:31:44    261d4697c9 Include full path to password auth config file when not found
## Wenlei Xie
- [ ] all checked
-  04-20 10:27:32    4e881c8d11 Fix tests for BlockBuilder.appendStructure()
-  04-24 16:39:24    9c14131a5a Fix bing_tile_coordinates function to produce row block

**Comment by nezihyigitbasi** [comment]
Hive
-----
- Skip predicate pushdown for complex types in the optimized Parquet reader, which was previously causing query failures.

**Comment by arhimondr** [comment]
```
General
--------
* Add ST_GeometryType geospatial function
```

**Comment by ggilfb** [comment]
General 
-------
- Disable optimization for joins with empty tables as this could cause a query hang
