### ISSUE TITLE
Slow join to subquery in Cassandra on partition columns

### ISSUE THREAD

**Issue by gregdingle** [prestodb/presto#10476]
This is for presto 0.194 running on cassandra . 

I'm getting a slow or fast query for the same result depending on whether I hard code values or return them in a subquery. NOTE: the subquery itself is very fast. 

Below I pasted the a run of each query and an EXPLAIN.

```
=FAST QUERY=


presto:feeds> WITH feeds AS (
           ->   SELECT member_id, feed_id AS fid
           ->   FROM cassandra.feeds.feeds_by_id
           ->   WHERE member_id = 'eCfcSPIjQlK8nRbvxED6eg' AND feed_id IN (
           ->     'zrGO2MpAQoKdYL_5WxV7VA',
           ->     'w_SKb9a_Q-Wi00wgX-TGXw',
           ->     'undefined             ',
           ->     'qMMRvs0YSU6GB45atLDSQA',
           ->     'pT4WzPlTT0i7Qm8cLtnUGQ',
           ->     'pQPDNF8VTy-Dr72pU0K2FA',
           ->     'mSMAG2_PSpu4-7XbiCFC-g',
           ->     'iu_cX_X2TU28Zm2pKKHNMQ',
           ->     '_wq56BeWQ6a17Vj1z1xjfA',
           ->     'VSv7ivnDQEW4dzcjvezVOg',
           ->     'VFvSCRJASbCn9ATXTGZ0Dw',
           ->     'PDfftBjkQHS8iyfOLvzkYA',
           ->     'IjagIjQ1T1-92hARfUgbQA',
           ->     'HNsX8KyCRuive8mhciKhCQ',
           ->     'FKVTScX8QEmOX5f0zNuwvw',
           ->     'AcBOzQAWS5KBTrrJjZxCBQ',
           ->     'A7aBIb2iT7CVwK4mXBGplQ',
           ->     '4RRIGXyvRaqqlj1pOOkP7g'
           ->   )
           -> )
           -> SELECT count(*) FROM cassandra.feeds.feeditems_by_date items
           -> JOIN feeds
           -> ON (feeds.member_id = items.member_id AND feeds.fid = items.feed_id);
 _col0 
-------
  6986 
(1 row)

Query 20180424_144541_00238_z7duk, FINISHED, 1 node
Splits: 82 total, 82 done (100.00%)
0:01 [7K rows, 6.84KB] [9.01K rows/s, 8.79KB/s]


presto:feeds> explain WITH feeds AS ( SELECT member_id, feed_id AS fid FROM cassandra.feeds.feeds_by_id WHERE member_id = 'eCfcSPIjQlK8nRbvxED6eg' AND feed_id IN ( 'zrGO2MpAQoKdYL_5WxV7VA', 'w_SKb9a_Q-Wi00wgX-TGXw', 'undefined             ', 'qMMRvs0YSU6GB45atLDSQA', 'pT4WzPlTT0i7Qm8cLtnUGQ', 'pQPDNF8VTy-Dr72pU0K2FA', 'mSMAG2_PSpu4-7XbiCFC-g', 'iu_cX_X2TU28Zm2pKKHNMQ', '_wq56BeWQ6a17Vj1z1xjfA', 'VSv7ivnDQEW4dzcjvezVOg', 'VFvSCRJASbCn9ATXTGZ0Dw', 'PDfftBjkQHS8iyfOLvzkYA', 'IjagIjQ1T1-92hARfUgbQA', 'HNsX8KyCRuive8mhciKhCQ', 'FKVTScX8QEmOX5f0zNuwvw', 'AcBOzQAWS5KBTrrJjZxCBQ', 'A7aBIb2iT7CVwK4mXBGplQ', '4RRIGXyvRaqqlj1pOOkP7g' ) ) SELECT count(*) FROM cassandra.feeds.feeditems_by_date items JOIN feeds ON (feeds.member_id = items.member_id AND feeds.fid = items.feed_id);
                                                                                                                                                                                              
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 - Output[_col0] => [count:bigint]                                                                                                                                                            
         _col0 := count                                                                                                                                                                       
     - Aggregate(FINAL) => [count:bigint]                                                                                                                                                     
             count := "count"("count_21")                                                                                                                                                     
         - LocalExchange[SINGLE] () => count_21:bigint                                                                                                                                        
             - RemoteExchange[GATHER] => count_21:bigint                                                                                                                                      
                 - Aggregate(PARTIAL) => [count_21:bigint]                                                                                                                                    
                         count_21 := "count"(*)                                                                                                                                               
                     - InnerJoin[("member_id" = "member_id_0") AND ("feed_id" = "feed_id_1")][$hashvalue, $hashvalue_23] => []                                                                
                         - RemoteExchange[REPARTITION][$hashvalue] => member_id:varchar, feed_id:varchar, $hashvalue:bigint                                                                   
                             - ScanFilterProject[table = cassandra:cassandra:feeds:feeditems_by_date, originalConstraint = (("member_id" = CAST('eCfcSPIjQlK8nRbvxED6eg' AS varchar)) AND ("fe
                                     $hashvalue_22 := "combine_hash"("combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("member_id"), 0)), COALESCE("$operator$hash_code"("feed_id"), 0
                                     member_id := CassandraColumnHandle{connectorId=cassandra, name=member_id, ordinalPosition=0, cassandraType=TEXT, partitionKey=true, clusteringKey=false, 
                                     feed_id := CassandraColumnHandle{connectorId=cassandra, name=feed_id, ordinalPosition=1, cassandraType=TEXT, partitionKey=true, clusteringKey=false, inde
                         - LocalExchange[HASH][$hashvalue_23] ("member_id_0", "feed_id_1") => member_id_0:varchar, feed_id_1:varchar, $hashvalue_23:bigint                                    
                             - RemoteExchange[REPARTITION][$hashvalue_24] => member_id_0:varchar, feed_id_1:varchar, $hashvalue_24:bigint                                                     
                                 - ScanFilterProject[table = cassandra:cassandra:feeds:feeds_by_id, originalConstraint = (("member_id_0" = CAST('eCfcSPIjQlK8nRbvxED6eg' AS varchar)) AND ("fe
                                         $hashvalue_25 := "combine_hash"("combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("member_id_0"), 0)), COALESCE("$operator$hash_code"("feed_i
                                         member_id_0 := CassandraColumnHandle{connectorId=cassandra, name=member_id, ordinalPosition=0, cassandraType=TEXT, partitionKey=true, clusteringKey=f
                                         feed_id_1 := CassandraColumnHandle{connectorId=cassandra, name=feed_id, ordinalPosition=1, cassandraType=TEXT, partitionKey=false, clusteringKey=true
                                                                                                                                                                                              ````

=SLOW QUERY=

presto:feeds> WITH feeds AS (
           ->   SELECT member_id, feed_id AS fid
           ->   FROM cassandra.feeds.feeds_by_id
           ->   WHERE member_id = 'eCfcSPIjQlK8nRbvxED6eg'
           -> )
           -> SELECT count(*) FROM cassandra.feeds.feeditems_by_date items
           -> JOIN feeds
           -> ON (feeds.member_id = items.member_id AND feeds.fid = items.feed_id)
           -> ;
 _col0 
-------
  6986 
(1 row)

Query 20180424_143900_00229_z7duk, FINISHED, 1 node
Splits: 451 total, 451 done (100.00%)
0:23 [6.31M rows, 6.02MB] [278K rows/s, 271KB/s]

presto:feeds> explain WITH feeds AS ( SELECT member_id, feed_id AS fid FROM cassandra.feeds.feeds_by_id WHERE member_id = 'eCfcSPIjQlK8nRbvxED6eg' ) SELECT count(*) FROM cassandra.feeds.feeditems_by_date items JOIN feeds ON (feeds.member_id = items.member_id AND feeds.fid = items.feed_id);
                                                                                                                                                              Query Plan                      
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 - Output[_col0] => [count:bigint]                                                                                                                                                            
         _col0 := count                                                                                                                                                                       
     - Aggregate(FINAL) => [count:bigint]                                                                                                                                                     
             count := "count"("count_21")                                                                                                                                                     
         - LocalExchange[SINGLE] () => count_21:bigint                                                                                                                                        
             - RemoteExchange[GATHER] => count_21:bigint                                                                                                                                      
                 - Aggregate(PARTIAL) => [count_21:bigint]                                                                                                                                    
                         count_21 := "count"(*)                                                                                                                                               
                     - InnerJoin[("member_id" = "member_id_0") AND ("feed_id" = "feed_id_1")][$hashvalue, $hashvalue_23] => []                                                                
                         - RemoteExchange[REPARTITION][$hashvalue] => member_id:varchar, feed_id:varchar, $hashvalue:bigint                                                                   
                             - ScanFilterProject[table = cassandra:cassandra:feeds:feeditems_by_date, originalConstraint = ("member_id" = CAST('eCfcSPIjQlK8nRbvxED6eg' AS varchar)), filterPr
                                     $hashvalue_22 := "combine_hash"("combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("member_id"), 0)), COALESCE("$operator$hash_code"("feed_id"), 0
                                     member_id := CassandraColumnHandle{connectorId=cassandra, name=member_id, ordinalPosition=0, cassandraType=TEXT, partitionKey=true, clusteringKey=false, 
                                     feed_id := CassandraColumnHandle{connectorId=cassandra, name=feed_id, ordinalPosition=1, cassandraType=TEXT, partitionKey=true, clusteringKey=false, inde
                         - LocalExchange[HASH][$hashvalue_23] ("member_id_0", "feed_id_1") => member_id_0:varchar, feed_id_1:varchar, $hashvalue_23:bigint                                    
                             - RemoteExchange[REPARTITION][$hashvalue_24] => member_id_0:varchar, feed_id_1:varchar, $hashvalue_24:bigint                                                     
                                 - ScanFilterProject[table = cassandra:cassandra:feeds:feeds_by_id, originalConstraint = ("member_id_0" = CAST('eCfcSPIjQlK8nRbvxED6eg' AS varchar)), filterPr
                                         $hashvalue_25 := "combine_hash"("combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("member_id_0"), 0)), COALESCE("$operator$hash_code"("feed_i
                                         member_id_0 := CassandraColumnHandle{connectorId=cassandra, name=member_id, ordinalPosition=0, cassandraType=TEXT, partitionKey=true, clusteringKey=f
                                         feed_id_1 := CassandraColumnHandle{connectorId=cassandra, name=feed_id, ordinalPosition=1, cassandraType=TEXT, partitionKey=false, clusteringKey=true

=SUBQUERY=

presto:feeds>   SELECT member_id, feed_id AS fid
           ->   FROM cassandra.feeds.feeds_by_id
           ->   WHERE member_id = 'eCfcSPIjQlK8nRbvxED6eg'
           -> ;
       member_id        |          fid           
------------------------+------------------------
 eCfcSPIjQlK8nRbvxED6eg | zrGO2MpAQoKdYL_5WxV7VA 
 eCfcSPIjQlK8nRbvxED6eg | w_SKb9a_Q-Wi00wgX-TGXw 
 eCfcSPIjQlK8nRbvxED6eg | undefined              
 eCfcSPIjQlK8nRbvxED6eg | qMMRvs0YSU6GB45atLDSQA 
 eCfcSPIjQlK8nRbvxED6eg | pT4WzPlTT0i7Qm8cLtnUGQ 
 eCfcSPIjQlK8nRbvxED6eg | pQPDNF8VTy-Dr72pU0K2FA 
 eCfcSPIjQlK8nRbvxED6eg | mSMAG2_PSpu4-7XbiCFC-g 
 eCfcSPIjQlK8nRbvxED6eg | iu_cX_X2TU28Zm2pKKHNMQ 
 eCfcSPIjQlK8nRbvxED6eg | _wq56BeWQ6a17Vj1z1xjfA 
 eCfcSPIjQlK8nRbvxED6eg | VSv7ivnDQEW4dzcjvezVOg 
 eCfcSPIjQlK8nRbvxED6eg | VFvSCRJASbCn9ATXTGZ0Dw 
 eCfcSPIjQlK8nRbvxED6eg | PDfftBjkQHS8iyfOLvzkYA 
 eCfcSPIjQlK8nRbvxED6eg | IjagIjQ1T1-92hARfUgbQA 
 eCfcSPIjQlK8nRbvxED6eg | HNsX8KyCRuive8mhciKhCQ 
 eCfcSPIjQlK8nRbvxED6eg | FKVTScX8QEmOX5f0zNuwvw 
 eCfcSPIjQlK8nRbvxED6eg | AcBOzQAWS5KBTrrJjZxCBQ 
 eCfcSPIjQlK8nRbvxED6eg | A7aBIb2iT7CVwK4mXBGplQ 
 eCfcSPIjQlK8nRbvxED6eg | 4RRIGXyvRaqqlj1pOOkP7g 
(18 rows)

Query 20180424_144841_00240_z7duk, FINISHED, 1 node
Splits: 17 total, 17 done (100.00%)
0:00 [18 rows, 18B] [186 rows/s, 186B/s]
```

**Comment by kbajda** [comment]
@gregdingle what is your Presto version?

**Comment by gregdingle** [comment]
@kbajda @findepi Thank you for the help. I re-wrote the test cases above, converted to INNER JOIN and double checked same results, different speeds.

**Comment by gregdingle** [comment]
The key difference in the explain plans appears to be...

SLOW:
originalConstraint = ("member_id" = CAST('eCfcSPIjQlK8nRbvxED6eg' AS varchar)), filterPr ...

FAST:
originalConstraint = (("member_id" = CAST('eCfcSPIjQlK8nRbvxED6eg' AS varchar)) AND ("fe ...

**Comment by findepi** [comment]
So you basically say that your `feeds` subquery pulls only a couple of rows and you would like the query planner to use values from this few rows just as it would do with constants.
Did i understand now?

However, this is not possible -- planner cannot know that there is only just a couple of rows and it would be good to read them before executing the main query (planner doesn't execute subqueries).

For this to work you need to execute `feeds` query, read the results in some programming environment and then for each result, execute the main query, gathering results.

There is a related feature being work on -- the Dynamic Filtering -- which can apply such information on the fly, as query is executing. However, I don't think this is going to be immediately applicable to Cassandra connector, due to how Cassandra query is executed.

**Comment by kbajda** [comment]
@gregdingle Please give 0.197 (or higher) a try. 
According to https://prestodb.io/docs/current/release/release-0.197.html that release included
"Extend predicate inference and pushdown for queries using a <symbol> IN <subquery> predicate".

**Comment by gregdingle** [comment]
@findepi Thanks for all the explanation. That makes perfect sense.
