### ISSUE TITLE
Presto could not recognize new fields of a Mongodb collection

### ISSUE THREAD

**Issue by dulh** [prestodb/presto#10471]
Hi all,

I'm using v0.199 to connect to mongodb and I see issue: Presto won't update the mongodb table schema after the first query happens in Presto, even if mongodb table is added some new fields later. So in the 2nd query in Presto, it could not load any data of new fields of mongodb table. 

How to refresh the mongodb schema definition in Presto?

**Comment by miniway** [comment]
Currently there's no easy way to detect new field is added on the table, please refer https://prestodb.io/docs/current/connector/mongodb.html#table-definition-label

Also `addColumn` is not implemented yet in the mongodb plugin.

So you need to modify table definition manually.
