### ISSUE TITLE
how can i query the column that define use map?

### ISSUE THREAD

**Issue by xingnailu** [prestodb/presto#10480]
when i queried like this:  select * from t;  
the error is: 
Expected MAP column 'context.entry' entry to have two fields, but has 1 fields

i am new there. ~ thx

**Comment by xingnailu** [comment]
anybody can tell me : xingnailu20206@163.com .  thx

**Comment by ebyhr** [comment]
It seems the error is thrown at here. 
https://github.com/prestodb/presto/blob/b462a0176b97eebb41d50aa2c751ba2ee0d2f7a0/presto-hive/src/main/java/com/facebook/presto/hive/parquet/ParquetHiveRecordCursor.java#L1132
