### ISSUE TITLE
DECIMAL not handled in HiveCoercionPolicy

### ISSUE THREAD

**Issue by dain** [prestodb/presto#10482]
HiveCoercionPolicy does not handle DECIMAL at all.  This is needed for schema changes to and from decimal types.

**Comment by findepi** [comment]
@losipiuk is this what your https://github.com/prestodb/presto/pull/9422 is doing?

**Comment by findepi** [comment]
@dain this issue looks like a duplicate of https://github.com/prestodb/presto/issues/7658 . Let me close this.
