### ISSUE TITLE
Support for Parquet file format stats

### ISSUE THREAD

**Issue by piyushnarang** [prestodb/presto#10484]
While debugging some performance issues, I noticed that we have some useful stats counters that [track bytes read and time distributions](https://github.com/prestodb/presto/blob/master/presto-hive/src/main/java/com/facebook/presto/hive/FileFormatDataSourceStats.java#L24) to read various sized file chunks for formats like [ORC](https://github.com/prestodb/presto/blob/master/presto-hive/src/main/java/com/facebook/presto/hive/orc/HdfsOrcDataSource.java).

It would be nice to set this up for Parquet as well.

**Comment by nezihyigitbasi** [comment]
Fixed by #10545.
