### ISSUE TITLE
Mapping the part of the query to Presto stages

### ISSUE THREAD

**Issue by mnoumanshahzad** [prestodb/presto#10503]
I am trying to debug issues with some query perfomance.

Firstly, I can not understand how a ScanFilterAndProject operator reads in 3.30GB of data and output 36.24GB of data?

Secondly, how can I find out what part of the query was executed in this particular stage to find out what causes the explosion of this data? Or even better, what data am I reading in this stage? 

I am using Hive connector and my data is stored in S3. I have G1 garbage collector instead of MarkAndSweep and distributed-joins is disabled.

![image](https://user-images.githubusercontent.com/9784890/39311510-679e3268-496d-11e8-9532-bb6c28c42bc5.png)

Thanks in advance.

**Comment by electrum** [comment]
How big are the files on disk? A compression factor of 10x or more is common.

**Comment by dain** [comment]
On Apr 26, 2018, at 7:21 AM, Muhammad Nouman Shahzad <notifications@github.com> wrote:
> 
> I am trying to debug issues with some query perfomance.
> 
> Firstly, I can not understand how a ScanFilterAndProject operator reads in 3.30GB of data and output 36.24GB of data?

IIRC the input size is raw size from disk and the output size is decompressed size.  Also, some projections function can expand data size.

> Secondly, how can I find out what part of the query was executed in this particular stage to find out what causes the explosion of this data?

Run EXPLAIN on the query, or use the “Live Plan" view in the UI.

-dain
