### ISSUE TITLE
0.201 release notes

### ISSUE THREAD

**Issue by haozhun** [prestodb/presto#10507]
Issue to track release notes for the next release.

## Andrii Rosa          
- [x] all checked
-  04-27 06:20:46    22c1d74b5b Use loginUser instead of currentUser in SimpleHadoopAuthentication
-  04-27 06:20:46    52db596da0 Separate impersonation unrelated product tests into a new test job
-  04-27 06:20:46    7ff2d9129f Run impersonation tests for custom ORC/RCFILE writers
-  04-27 06:20:46    9fcbe8604c Execute impersonation test queries from a non default JDBC user
## Dain Sundstrom       
- [x] all checked
-  04-26 20:23:47    3026ba89a9 Short circuit Driver.firstFinishedFuture with one future
-  04-28 15:23:36    c614439489 Change ORC writer validation from boolean to percentage
-  04-30 09:47:08    21b4179feb Remove driver special handling for single operator
-  04-30 09:47:08    ca890d7195 Allow HashBuildOperator close to be called multiple times
-  04-30 11:16:03    820708cb2c Remove ORC min row count wtih min stripe size
## David Phillips       
- [x] all checked
-  04-27 13:02:42    19637793a2 Use direct Executor instead of ExecutorService
-  04-27 13:03:03    40aac82374 Fix warnings in ThriftHiveMetastore
-  04-30 11:56:47    eff14cf3ab Fix Hive $partitions table for null partition values
## Elon Azoulay         
- [x] all checked
-  04-27 11:05:59    9694349478 Add support for current_user
-  04-27 11:20:55    1580e55e73 Add positionIsNotDistinctFromRow to SimplePagesHashStrategy
-  04-27 11:20:55    2d501fc730 Pass Metadata and FeaturesConfig to JoinCompiler constructor
-  04-27 11:20:55    4369309241 Use typeEquals for Slice types in JoinCompiler
-  04-27 11:20:55    75451d9c26 Add varchar data to BenchmarkGroupByHash
-  04-27 11:20:55    ad869b555e Extract generateInputReference from InputReferenceCompiler
-  04-27 11:20:55    baad26e684 Use IS NOT DISTINCT FROM for GROUP BY
-  04-27 11:20:55    de14aa440e Pass config and metadata of LocalQueryRunner to JoinCompiler
-  04-27 11:20:55    e59d0269d2 Fix NaN handling in distinct from operator for double and real
## Haozhun Jin          
- [x] all checked
-  04-27 12:18:26    d54cf4fec8 Update to ASM 6.1.1
## James Sun            
- [x] all checked
-  04-26 17:26:25    a7b62bdf52 Update page retained size with instance size after compact
-  04-27 23:11:22    91b4bf4804 Handle NaN hash for real and double types
-  04-28 01:49:20    1ef397f43d Add benchmark for GroupedTopNBuilder
-  04-28 01:49:20    22e142dc98 Optimize TopNOperator with GroupedTopNBuilder
-  04-28 01:49:20    2b3dc4c768 Add benchmark for TopNRowNumberOperator
-  04-28 01:49:20    535d0664c3 Add Benchmark for TopNOperator
-  04-28 01:49:20    c2affb70af Optimize TopNRowNumberOperator with GroupedTopNBuilder
-  04-28 01:49:20    e86e6be5cf Introduce GroupedTopNBuilder
-  04-29 02:36:28    cb3a30e83a Fix dictionary start offset of columnar array and map
## Karol Sobczak        
- [x] all checked
-  04-27 06:44:32    dc41008be4 Use aggregates from order by expressions in order by scope
## Martin Traverso      
- [x] all checked
-  04-27 13:35:02    50d13df01d Update to aircompressor 0.10
## Nezih Yigitbasi      
- [x] all checked
-  04-26 22:06:41    002436da3d Account for ColumnEncodeOutput overhead in retained size
-  04-26 22:06:41    09c2763b55 Remove unnecessary toIntExact call
-  04-26 22:06:41    26f31f4dee Minor refactor of TestTableWriterOperator
-  04-26 22:06:41    2e645badd6 Change type of retainedSizeInBytes to long
-  04-26 22:06:41    b98a8937bb Add instance size to retained size calculations in various writers
-  04-26 22:06:41    c9eb03d8cf Add TableWriterInfo to keep track of peak writer memory usage
-  04-27 08:19:30    d7963cb41c Fix function reference in 0.200 release notes
-  04-27 13:37:19    4e5331a21a Fix potential overflow in BingTileFunctions::mapSize
-  04-27 13:37:35    778c9549b8 Update to Airlift 0.168
-  04-30 12:56:25    3adfcc9b11 Remove system pool
## Piotr Findeisen      
- [x] all checked
-  04-27 02:57:33    348ffbcbc3 Extend the username extraction to principal user matching rules
## Wenlei Xie           
- [x] all checked
-  04-26 19:25:33    43e156257a Remove maxBlockSizeInBytes in BlockBuilderStatus
-  04-26 19:25:33    e3dec0c0e0 Minor fix to TestHashAggregationOperator
## rongrong             
- [x] all checked
-  04-27 14:58:22    d5606ed20b Add session property prefer-partial-aggregation

**Comment by wenleix** [comment]
- General

* Improve performance of joins, aggregations and  table writing  that include structural types.

**Comment by findepi** [comment]
```
Security
--------

* Alter rules ``file`` :doc:`/security/built-in-system-access-control` for enforcing 
  match between authentication credentials and a chosen username to allow more
  fine-grained control and ability to define "superuser"-like credentials.
```

**Comment by sopel39** [comment]
```
General
_______

* Fix planning error when column names are reused in ORDER BY query
```

**Comment by elonazoulay** [comment]
Session
--------
* Add support for current_user

**Comment by dain** [comment]
```
Hive
----
Replace ORC writer stripe minimum row configuration ``hive.orc.writer.stripe-min-rows`` with stripe min data size ``hive.orc.writer.stripe-min-size``.
Change ORC writer validation config ``hive.orc.writer.validate`` switch to a sampling percentage ``hive.orc.writer.validation-percentage``.  This can reduce the time to discovery for corruption.
```
#10517 and #10518

**Comment by nezihyigitbasi** [comment]
General
--------
- System memory pool is now unused by default and it will eventually be removed completely. In other words, all memory allocations will now be served from the general/user memory pool. The old behavior can be restored with the `deprecated.legacy-system-pool-enabled` config option.

**Comment by highker** [comment]
```
General
--------

* Improve performance and memory usage for queries using :func: `row_number` followed by a filter on the row numbers generated.
* Improve performance and memory usage for queries using `ORDER BY` followed by a `LIMIT`

Hive
--------
* Fix optimized ORC writer writing incorrect data of type `map` or `array`.

**Comment by electrum** [comment]
```
Hive Changes
------------

* Fix ``SHOW PARTITIONS`` and the ``$partitions`` table
  for tables that have null partition values.

**Comment by rongrong** [comment]
General
--------
* Add session property prefer-partial-aggregation.

**Comment by arhimondr** [comment]
```
Hive Changes
------------
* Collect and store basic table statistics (rowCount, fileCount, rawDataSize, totalSize) on INSERT and CREATE TABLE AS SELECT
```

**Comment by arhimondr** [comment]
Hive Changes
------------

* Fix impersonation for the simple HDFS authentication.
