### ISSUE TITLE
not support "in array"

### ISSUE THREAD

**Issue by UPEMPEROR** [prestodb/presto#10509]
`select id from table where id in array[1,2,3];`

`mismatched input 'in' expecting {<EOF>, 'AND', 'EXCEPT', 'GROUP', 'HAVING', 'INTERSECT', 'LIMIT', 'OR', 'ORDER', 'UNION'}`

**Comment by yuokada** [comment]
Hi, @UPEMPEROR.
You can rewrite a query with func `contains`.
https://prestodb.io/docs/current/functions/array.html

```
Select id from table where contains(ARRAY[1,2,3], id) ;
```
