### ISSUE TITLE
Cannot use min_by with "timestamp with time zone" type

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#10529]
```
presto> select min_by(123, current_timestamp);
Query 20180430_192651_00000_rujhp failed: Unexpected response from http://127.0.0.1:52707/v1/task/20180430_192651_00000_rujhp.0.0?summarize
```
This fails due to
```
Caused by: java.lang.IllegalArgumentException: Unknown type row(timestamp with time zone,boolean,integer,boolean)
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:210)
	at com.facebook.presto.type.TypeDeserializer._deserialize(TypeDeserializer.java:43)
```
This is due to the following returning null:
```java
typeRegistry.getType(parseTypeSignature("row(timestamp with time zone)"));
```

**Comment by findepi** [comment]
The same happens for `time with time zone`, `interval year to month`, `interval day to second`.

**Comment by electrum** [comment]
The problem is that this is being treated as a `row(timestamp "with time zone")`, i.e., `timestamp` is the field name. This is probably the parsing code in `TypeSignature`.

**Comment by martint** [comment]
I've been thinking we should replace the hand-rolled TypeSignature parser with one based on the SQL grammar.

**Comment by electrum** [comment]
Doing that will be tricky since the parser depends on the SPI. There's also the problem that the parser depends on the ANTLR runtime (perhaps could solve with shading).
