### ISSUE TITLE
Query still exceeded local memory while Spill on disk enabled

### ISSUE THREAD

**Issue by BlueStalker** [prestodb/presto#10543]
we have a small cluster running on version 0.199, and with spill on disk enabled, the cluster has 18 workers, with 80G in JVM heap, and query.max-memory-per-node=20GB, reserved-system-memory = 40GB, so the 3 mem pool is:
reserve -> 20G, general 20G, and system 40G. With spill on disk enabled, we still see the following exceptions:

```
com.facebook.presto.ExceededMemoryLimitException: Query exceeded local memory limit of 20GB
	at com.facebook.presto.ExceededMemoryLimitException.exceededLocalLimit(ExceededMemoryLimitException.java:34)
	at com.facebook.presto.memory.QueryContext.updateUserMemory(QueryContext.java:122)
	at com.facebook.presto.memory.QueryContext$QueryMemoryReservationHandler.reserveMemory(QueryContext.java:269)
	at com.facebook.presto.memory.context.RootAggregatedMemoryContext.updateBytes(RootAggregatedMemoryContext.java:34)
	at com.facebook.presto.memory.context.ChildAggregatedMemoryContext.updateBytes(ChildAggregatedMemoryContext.java:33)
	at com.facebook.presto.memory.context.ChildAggregatedMemoryContext.updateBytes(ChildAggregatedMemoryContext.java:33)
	at com.facebook.presto.memory.context.ChildAggregatedMemoryContext.updateBytes(ChildAggregatedMemoryContext.java:33)
	at com.facebook.presto.memory.context.ChildAggregatedMemoryContext.updateBytes(ChildAggregatedMemoryContext.java:33)
	at com.facebook.presto.memory.context.SimpleLocalMemoryContext.setBytes(SimpleLocalMemoryContext.java:62)
	at com.facebook.presto.operator.OperatorContext$DecoratedLocalMemoryContext.setBytes(OperatorContext.java:637)
	at com.facebook.presto.operator.HashBuilderOperator.unspillLookupSourceIfRequested(HashBuilderOperator.java:553)
	at com.facebook.presto.operator.HashBuilderOperator.finish(HashBuilderOperator.java:476)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:363)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:281)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:687)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:275)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:975)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:492)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

It looks like the exception happened after unspilled the specific partition, I enabled some debug information, the memoryRetainedByRemainingPages is 30GB (> 20GB), which is the reason.

 Then, Presto right now doesn't support multiple tasks in a single stage running on a single node, which means, if I increase the num of partitions, the max number of partitions in a single stage is 18 (I have 18 nodes), so, there is no way to run this query on such a cluster.

My questions is that, does it make sense to enable multiple tasks in a single stage running on a single node, thus for this case, I can make more partitions to run this query.

**Comment by findepi** [comment]
Thanks for reporting this  issue.

Spill in Presto doesn't turn it into on-disk processing framework like map-reduce. In the ideal case, you can increase your query processing capacity by task-concurrency factor. Usual case is not ideal, because there is data skew, memory is used concurrently by different queries/stages/operators.

> if I increase the num of partitions, ...

What do you mean?

Also, what's the task concurrency?
Given your 18 machines had more memory, do you know  how high query.max-memory-per-node you would need for the query to pass without spill?

**Comment by BlueStalker** [comment]
Thanks for replying.
task concurrency is 16 as default. ( and I am testing only 1 query.)
I believe I got something wrong before. 
What I "thought" is from the exception thrown above in HashBuildOperator, it is because of the single partition of the data for join already go over with 20GB, and if we can have more partitions, then the problem is solved since when Spill on disk is enabled, it looks like the unspilling is done by partition and partition. 

And just realized the 20GB is Per Query per Node, and it is calculated accumulatively, so if we enable multiple partitions per stage per node, then without changing that 20GB settings, it will still go over that??

**Comment by findepi** [comment]
> f we can have more partitions, then the problem is solved since when Spill on disk is enabled, it looks like the unspilling is done by partition and partition.

Yes, unspilling is done partition by partition. There are `task.concurrency` many partitions, so you can try to decrease the size of individual partitions:
- make sure join is repartitioned (not replicated, aka broadcast)
- increase task concurrency 

Of course, this can't help if there is high skew and, for example, single join key has huge number of rows on the build side. 
(You can check that with something like `select count(*) from build_side;` and `select count(*) from build_side group by join_key order by 1 desc limit 10;`)

> And just realized the 20GB is Per Query per Node, 

Yes. And this means, if your query has something more than just one Join, all memory allocations on behalf of this query are limited in total to 20GB.
So, it may happen that something else (other Join or something else) is allocating so much memory that the Join doesn't fit under memory limit even when spilling.

**Comment by BlueStalker** [comment]
I thought "task.concurrency" is controlled the number of parallel running jobs per worker, and query.initial-hash-partitions is used to determine the number of partitions for distributed joins?

**Comment by findepi** [comment]
@BlueStalker you're right. task.concurrency controls the number of operators executing in parallel. Note, however, that to realize maximum concurrency, build side operators (`HashBuilderOperator`) build a partitioned hash table, where each operator builds one partition of that table. This is local partitioning and affects only build side, additional to distributed partitioning for build & probe sides alike. Now, due to how this partitioned hash table is organized in memory, spill operates on its partitions independently. As a result, if you have higher task concurrency, you have more `HashBuilderOperator` instances, more partitions in the partitioned hash table on the build side, which in turn usually means every partition is smaller.

What's the biggest partition size in your case, with task concurrency 16? Given your 18 machines had more memory, do you know how high query.max-memory-per-node you would need for the query to pass without spill?

**Comment by BlueStalker** [comment]
while trying to get the "query.max-memory-per-node" without spilling, it sounds like there are 2 "level" of partitions here? Let's say we have A and B join, and A is the build side, and B is probe side.

1. is query.initial-hash-partitions controls the total number of partitions we are going to build for each table? if I have 18 nodes and set the initial-hash-partitions = 18, then we have 18 partitions, with each partitioned join runs on one node? and this is the "global" partitioning regarding what I refer in Q2 below?

2.  while task.concurrency is actually meant task.parallelism, if in the whole cluster, I only have 1 above query (A join B) running, then "task.concurrency" is to define how many "local partitions" for A (builder side, again suppose we only have 1 stage), means how many (HashBuilderOperator) will have on each node for that query and stage? And when we talk the spill on disk for join, WE only talks  about the builder table "local" partitions, and there local partitions are being unspilled and joined 1 by 1?

**Comment by BlueStalker** [comment]
Anyway, I think one thing I am pretty sure, is since my real query is pretty complicated, there are multi stage has LJO, with enabled 35G as local memory limit, it still fails, because, a particular node has 2 stages trying to unspill together on specific node, a stage holds 20G in localmemcontext, and when another stage is trying to issue another 19G (in another stage), it goes over 30G..
Well, task.concurrency is definitely related with this, since I can give a very small value to make the concurrent tasks ( on the different stage ) to run in sequential order, but this doesn't make too much sense for presto.

So I think for the Spill to Disk, it really gives us benefit to have "chance" to run a bigger query (in terms of memory consumption), but I should still give a pretty reasonable (large) query.max-memory-per-node since multiple task on different stage can run in parallel,  and query.max-memory-per-node is really a limit per query per node.

While my question on the previous thread is still valid, it is still a bit confusing me that the concept of "local" partition, is it actually 2 level or just 1 level.

**Comment by findepi** [comment]
> So I think for the Spill to Disk, it really gives us benefit to have "chance" to run a bigger query (in terms of memory consumption), but I should still give a pretty reasonable (large) query.max-memory-per-node since multiple task on different stage can run in parallel, and query.max-memory-per-node is really a limit per query per node.

Yes, yes, yes! How much Spill helps depends on actual query, but it is never "unlimited".  If the docs give impression that Spill removes memory limits, we should definitely fix the docs -- there was no design goal to support "unlimited" spilling.

Regarding your questions (https://github.com/prestodb/presto/issues/10543#issuecomment-386702345) -- your understanding is correct. There is global (between the nodes) partitioning and then, there is local partitioning (to compute build side's hash table faster and also to be able to spill). 
Note that when doing join, probe side is globally partitioned but doesn't need to be locally partitioned. That is -- until there is spilling, in which case, probe side also becomes partitioned. Then we unspill one by one.
