### ISSUE TITLE
Presto must run on datanode?

### ISSUE THREAD

**Issue by lcykenan** [prestodb/presto#10559]
Presto must run on datanode?
Some query error: No available node

**Comment by nezihyigitbasi** [comment]
No, it's not a strict requirement. But, if you run Presto workers on the datanode that will help get better performance due to better data locality (less reads over the network). Can you please share the full stack trace and the Presto version that you are using?

**Comment by lcykenan** [comment]
@nezihyigitbasi  Can you please share the full stack trace and the Presto version that you are using?
Presto workers run on datanode No errors found afterwards
presto server version 0.187

**Comment by kbajda** [comment]
@lcykenan please share your Presto configuration files (config.properties and hive.properties).
There are certain properties that may cause you seeing this error if Presto is deployed outside of the Hadoop cluster.
