### ISSUE TITLE
Feature request for coordinator with one port with authentication and another without authentication

### ISSUE THREAD

**Issue by JMNDev** [prestodb/presto#10562]
This is a configuration/feature that I think is very usefull and import to introduce is the possibility of have one port of the coordinator node without security to use inside a controlled context and another different port to expose with authentication (LDAP or Kerberos).

Thank you

**Comment by electrum** [comment]
This is how it works today as authentication only happens on the HTTPS port.

**Comment by JMNDev** [comment]
Thank you @electrum for the response,  and sorry for the feature request.
I have done it, because I had think that enabling the HTTPS and LDAP authentication, that that authentication would be enforced also for the http port.

Its necessary any kind of special configuration for the authentication only for the https port ? 
Could you give me an example of configurations for Presto to enable the use case I have described in my feature request.

Thank you very much

**Comment by electrum** [comment]
No, we only support HTTPS for authentication, as otherwise passwords etc. would be sent in clear text over HTTP.

**Comment by JMNDev** [comment]
Makes sense thank you once again.
