### ISSUE TITLE
Extracting date from a timestamp like "2017-11-15T11:18:42.573Z"?

### ISSUE THREAD

**Issue by tapaswenipathak** [prestodb/presto#10567]
I had a column with timestamp `2017-11-15T11:18:42.573Z` format, searching in the [documentation](https://prestodb.io/docs/current/functions/datetime.html) figured out that `parse_datetime` parses the timestamp. Parsed the timestamp as `parse_datetime(field_name, 'YYYY-MM-DD''T''HH:mm:ss.SSS''Z') as date` which gave the timestamp in UTC format. To extract date out of the timestamp I `cast` it to `date`. The part of query looked like

`CAST(parse_datetime(field_name, 'YYYY-MM-DD''T''HH:mm:ss.SSS''Z') as date) as date, `

Is there any predefined/inbuilt function which can do this for me? I tried few different functions available [here](https://prestodb.io/docs/current/functions/datetime.html).

I also tried `from_iso8601_timestamp()` on the timestamp value, query was like
`CAST(from_iso8601_timestamp(field_name) as date) as date`, was doing this in [AWS Athena](https://aws.amazon.com/athena/) in [Mode](https://modeanalytics.com/), this returned an error as

> [Simba][AthenaJDBC](100071) An error has been thrown from the AWS Athena client. 

I read the [contributing guidelines](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md) before opening this issue, please feel free to close if such question issues are not supposed to be open here, I'll then try on SO, great if can get some information about this.

**Comment by nezihyigitbasi** [comment]
`from_iso8601_timestamp` should work, just tried this with the latest release:

```
select cast(from_iso8601_timestamp('2017-11-15T11:18:42.573Z') as date);
   _col0
------------
 2017-11-15
(1 row)
```

**Comment by findepi** [comment]
Looks this has been answered.

**Comment by bhrd** [comment]
@msparker23 - Only with a `T`, the timestamp is of ISO-8601 format. For your input `2019-01-29 08:55:29.867`, `SELECT CAST('2019-01-29 08:55:29.867' as TIMESTAMP)` should work.

**Comment by naveen09** [comment]
How about for "2019-07-17 14:31:01.000000000 +00:00 ?

**Comment by davidmason** [comment]
@avanibhatnagar I am having the same problem where I have a time zone specified but can't parse it. Did you learn anything about getting that working?
