### ISSUE TITLE
cannot create table in cassandra database

### ISSUE THREAD

**Issue by gopal9405** [prestodb/presto#10563]
![image](https://user-images.githubusercontent.com/33027182/39687092-493fa95c-51ea-11e8-91a9-ddb630b438bf.png)

**Comment by findepi** [comment]
@gopal9405 
Presto doesn't support setting column attributes (like PRIMARY KEY) when creating a table. 
There is WIP _related_ to this: https://github.com/prestodb/presto/pull/10553

**Comment by gopal9405** [comment]
@findepi 
I am grateful for your answer. 
Can you please tell me the exact syntax of the basic query ?

eg:  CREATE TABLE  cassandra.test.consumer (orderid varchar with ( primary_key = true ), orderstatus varchar );

**Comment by findepi** [comment]
https://github.com/prestodb/presto/pull/10553 is _related_. It doesn't provide support for defining primary keys in casssandra.
Also, AFAIK cassandra connector does not support `CREATE TABLE`. However, it does support `CREATE TABLE ... AS SELECT ...`

**Comment by gopal9405** [comment]
@findepi 
Thank you so much for your help
