### ISSUE TITLE
Presto Doing Complete Scan of Redshift Table on using Redshift Connector

### ISSUE THREAD

**Issue by iamnewneo** [prestodb/presto#10578]
Hi,

I integrated Redshift Connector with presto. When I execute simple select statements like:

`select * from redshift.public.some_table where date(created_date) = current_date - interval '10' day limit 100;`

Presto gets the entire table from Redshift and then does the filtering after that, filtering does not take place in redshift. How do I solve for this? I do not want to replicate all the data in presto everytime I run a query. What kind of architecture can I follow to incorporate Redshift and Presto together?

Thanks

**Comment by findepi** [comment]
You need to express your query predicate so that table column is not wrapped in a function call. E.g. `created_date > '2018-04-29'`. Then it will be possible to push down the condition to the connector
