### ISSUE TITLE
Cassandra semijoins

### ISSUE THREAD

**Issue by aandis** [prestodb/presto#10570]
Using presto (`v0.166`) with the cassandra connector.

```sql
select * from foo
where bar in (select 'bar');
```

ends up scanning the entire `foo` table. Any ideas on how to optimize this?

https://github.com/prestodb/presto/issues/4017 may be related.

**Comment by dain** [comment]
Do you literally mean the query above where the semijoin is to a constant table, or do you want a full query in the select?  The first one requires a constant folding optimizer for `IN` over a `VALUES` expression. 

I assume you really want `where bar in (select x from t)`.  Assuming the `t` has an index on `x`, Presto could perform an index join, but the Cassandra connector does not have an implementation of `ConnectorIndexProvider`.  This is typically not very difficult to implement.

**Comment by aandis** [comment]
@dain yes I meant a full subquery inside the `where` clause.

**Comment by aandis** [comment]
@dain when you say
> Assuming the t has an index on x

I assume you mean a cassandra index on `x` in table `t`? What about cases where the index doesn't exist?

**Comment by dain** [comment]
> I assume you mean a cassandra index on `x` in table `t`? What about cases where the index doesn't exist?

To do a semi join you need an index, so either you already have one, or you need to build one.  To build an index, you need to scan all of the data.

**Comment by dain** [comment]
If someone wants to implement index joins in the Cassandra connector, please open a PR.
