### ISSUE TITLE
New UDF proposal: folly::SpookyHashV2::hash

### ISSUE THREAD

**Issue by jaehyunp** [prestodb/presto#10586]
We have some FB internal usage for this proposed UDF (please see the Presto Dev group), but since the hash function itself is public, sharing this proposal here.

## NAME
FB_SPOOKY_HASH32_V2, FB_SPOOKY_HASH64_V2.

## ARGUMENT TYPES
Input: string
Output: 32-bit or 64-bit signed integers

## NULL HANDLING
If input is NULL, output NULL
Note that if input is an empty string, its hash value is not NULL and is well-defined.

## ERROR HANDLING
Since the operation is basically a series of bitwise operations, special error handling is probably unnecessary.

**Comment by electrum** [comment]
We will want these functions to have a similar signature to `xxhash64`:

* `spooky_hash32(binary)` -> `varbinary`
* `spooky_hash64(binary)` -> `varbinary`

We'll also want to add `to_big_endian_32` and `from_big_endian_32` to go along with the 32 bit version.

**Comment by jaehyunp** [comment]
ah yes, `varbinary` makes more sense.

**Comment by martint** [comment]
Here's the implementation for the underlying algorithm: https://github.com/airlift/slice/pull/102
