### ISSUE TITLE
Access to Hive tblproperties via Hive System table <table>$properties

### ISSUE THREAD

**Issue by chch-onjack** [prestodb/presto#10611]
Hi, it would be great if there was a way to query hive table properties directly from Presto. 
When I asked internally, I was told: 
"No, but it seems reasonable to add a system table to the Hive connector that provides this. Please file an issue on GitHub " ... so, there you go :)

**Comment by dain** [comment]
The idea would be to add something like `SELECT * FROM "hive_table$properties"` or `SELECT * FROM "hive_table$describe_formatted"`

**Comment by qqibrow** [comment]
@dain I would like to take this because we have similar requests. has anyone worked on this yet?

**Comment by qqibrow** [comment]
@electrum thank you for the insights! Let me take a look and I will reply back my init implementation.

**Comment by ddrinka** [comment]
I'd like to bump this request--it looks like there's some initial work done that's remained unmerged.  Our use case calls for access to partition-level details which would presumably build on #10793.

Specifically, we need the LOCATION of a partition.  In my head I imagined the query looking like:
```sql
SELECT *,"$path" FROM "table$partitions";
```

But as long as we have programmatic access to the LOCATION property I don't care what the query looks like.

Any reason the above PR is on hold?

**Comment by qqibrow** [comment]
Sorry for the long holding. there was one test failure and I will fix it now.
