### ISSUE TITLE
Allow coordinator put sql query into queue if there is no worker running

### ISSUE THREAD

**Issue by MichaelZhao9824** [prestodb/presto#10624]
Hi guys,

I was wondering if we can add the function to allow coordinator put sql query into queue if there is no worker running. Once coordinator detects worker's back, and then starts to execute the query in the queue.

Currently query-manager.initialization-required-workers cannot be set to 0. Thanks.

**Comment by findepi** [comment]
Implemented in https://github.com/prestodb/presto/pull/11734 > `Add required minimum number of workers to start query` commit.
