### ISSUE TITLE
NO examples of how to SELECT a column into an Array!

### ISSUE THREAD

**Issue by RSmithBothell** [prestodb/presto#10654]
Been looking for hours but not one example.

**Comment by dain** [comment]
You can aggregate a column into an array with the `array_agg` aggregate function:
```
select array_agg(x) from (values 1, 2, 3, 4) as t(x);
    _col0             
--------------
 [1, 2, 3, 4] 
(1 row)
```

In the future, please use the mailing list (or stackoverflow) for usage questions like this.
