### ISSUE TITLE
removal of slice from source code?

### ISSUE THREAD

**Issue by raananraz** [prestodb/presto#10661]
slice is using jol which is GPL which basically kills any chance of using it..
are there any plans to remove it / work around it?

**Comment by martint** [comment]
JOL is actually “GPL with classpath exception”: http://hg.openjdk.java.net/code-tools/jol/file/03064c057dc9/LICENSE

It’s is the same license as the JDK.

**Comment by martint** [comment]
No, Presto is licensed under Apache License: https://github.com/prestodb/presto/blob/master/LICENSE

**Comment by raananraz** [comment]
@martint - i will run this by legal but the jdk works as far as licensing since it's not embedded within the jar.
in our case, we generate a war that holds our app -> presto -> slice -> jol all under the same war file which basically means it can't be used..

you know otherwise?

**Comment by electrum** [comment]
The `"CLASSPATH" EXCEPTION TO THE GPL` from the JOL license is the important part, as that allows redistributing it with modules that are not *"derived from or based on"* JOL. This is the part to bring to your legal team's attention.

**Comment by raananraz** [comment]
thanks everyone! will do 👍 
on a different note - if it's not really needed in the project (i only saw 3 places it's used) maybe it would be best to simply remove it all together.

thanks again!!
