### ISSUE TITLE
`null` is considered a `distinct value` in Hive Metastore column statistics

### ISSUE THREAD

**Issue by arhimondr** [prestodb/presto#10674]
In optimizer code we assume that `number of distinct values` statistic doesn't include null.

**Comment by arhimondr** [comment]
Since Hive accounts nulls as a distinct value we need to follow this assumption when storing the statistics. The idea is to increment NDV by 1 before store, and than decrement it by one on read when the nulls count for a given column is greater than zero.

**Comment by findepi** [comment]
Since nulls are accounted separately, it sounds a bit strange that null is also considered among NDV. Is this behavior constant across hive versions?
I also wonder, if this behavior present when tools other than hive calc stats and store them in hive metastore? (e.g. impala, spark)

**Comment by rschlussel2** [comment]
How did you find this issue?  I ask because hive distinct values counts are estimates, so it wouldn't be surprising to see off-by-one counts for that reason.

**Comment by arhimondr** [comment]
We run the `analyze` command in the `Hive` on very small tables (few rows) in the product tests. Than we assert that the number of distinct values for a 2 rows table (a single all null row and a single all not null row) is equal to `2`

**Comment by findepi** [comment]
Ah, this. I thought the test expectations are set so due to flawed estimates algorithm  (i observed really poor estimates on small tables, ~10-100 rows, so i could be biased)

**Comment by arhimondr** [comment]
It is fixed
