### ISSUE TITLE
Allow connector in coordinator to communicate with the connector in worker

### ISSUE THREAD

**Issue by Praveen2112** [prestodb/presto#10680]
Presto's coordinator and worker communicate with each other over REST APIs. But the connector which are in the coordinator and worker are isolated. Is it possible to establish a communication between the connector in the coordinator and worker over the existing http-server ?

**Comment by dain** [comment]
Can you describe what you are trying to accomplish?

**Comment by Praveen2112** [comment]
We are creating a custom connector which is similar to raptor in which a part of the data is stored in each worker. In case of any failure in a worker we should make sure that the data should be replicated in other machines. We can also run some data manipulation tools which might re shuffle the data across the workers. For achieving these kind of control it would be better if the connector in coordinator  server is able to communicate with connector in the worker. ( We can also use a SystemTable in which we might write a function which might implement the above task. But if Presto gives a way for connectors to communicate with each other it might be helpful )
