### ISSUE TITLE
0.203 release notes

### ISSUE THREAD

**Issue by dain** [prestodb/presto#10689]
## Andrii Rosa          
- [x] all checked
-  05-23 08:51:45    c10376c7a2 Run different hive tests in separate travis branches
-  05-23 08:51:45    c346768372 Fix failing test in TestHiveClient
-  05-23 08:51:45    e03fba400b Rename test methods in AbstractTestHiveClient
-  05-23 12:37:31    71f7ef57d2 Run presto-main tests as a separate Travis job
-  05-29 07:00:01    32c3020004 Return empty list instead of null from the getPartitionedBy
-  05-29 07:00:01    4a4fbb4a37 Refactor HiveMetastore statistics related interfaces
-  05-29 07:00:01    5b9cdd9bdf Refactor enforceLayoutProcessor
-  05-29 07:00:01    6efaa261a6 Fix parameter names related to getting partition statistics from Hive
-  05-29 07:00:01    7b8e89b316 Check partitioned_by and bucketed_by before getting the layout
-  05-29 07:00:01    a49a78de21 Remove generics from HiveColumnStatistics
-  05-29 07:00:01    f3978ed0f9 Do not store NDV for Boolean in HiveColumnStatistics
## Dain Sundstrom       
- [x] all checked
-  05-24 10:59:35    2da712aaef Fix IntelliJ warnings in SqlQueryScheduler
-  05-24 15:58:35    40083af07a Move query submission to background thread
-  05-24 15:58:35    89adfb2e06 Move QueryId creation into explicit separate step
-  05-24 15:58:36    568449b8d0 Delay query submission until first data get call
-  05-24 18:25:13    34cea981c7 Delegate output operator blocking to output buffer
-  05-24 19:46:14    93b2be6825 Upgrade to Airlift 0.169
## David Phillips       
- [x] all checked
-  05-23 14:55:01    e96894a866 Remove time-based expiration of page function bytecode
-  05-23 22:14:24    b30c9ba15e Fix sending challenge for multiple authenticators
-  05-24 11:23:18    73417c299e Fix quoting in error message for SHOW PARTITIONS
-  05-24 11:23:18    7dceac2d4a Make identifier formatting methods public
-  05-24 16:56:36    31cca605ad Update to Drift 1.12
-  05-24 16:56:36    5034525c77 Remove incorrect SCM tag in POM
-  05-29 13:43:13    43858e96f7 Improve error message for Hive max open writers
## Grzegorz Kokosiński 
- [x] all checked
-   05-23 05:24:27    f38f8fb03c Check also hive metastore port when checking hadoop
-   05-27 21:45:33    a981087e62 Define all parameters in single place
## Haozhun Jin          
- [x] all checked
-  05-23 11:43:34    2cc00e4a61 Use join bridge manager for nested loop join operator
-  05-23 11:43:34    5c2b396a8b Move nested class in LookupJoinOperatorFactory as standlone class
-  05-23 11:43:34    b2e93cd280 Extract NestedLoopJoinPagesBridge interface
-  05-23 11:43:34    c1693e6d5e Templatize and rename LookupSourceFactoryManager
-  05-23 11:43:34    cf807d728f Templatize JoinBridgeLifecycleManager
-  05-25 23:03:00    77eaaa8024 Fix execution failure for distinct with effective aggregation filter
-  05-25 23:03:00    dfee34394f Move tests for distinct agg with filter to TestDistinctAggregations
## Jiexi Lin            
- [x] all checked
-  05-25 10:36:49    413e84b7be Support multiple ranges in ShardPredicate
-  05-25 10:36:49    87ccad7e35 Only add bucket number column to bucketed table
-  05-25 10:36:49    dc1c925ea0 Remove bucketed check in ShardPredicate
## Maria Basmanova      
- [x] all checked
-  05-25 13:47:17    763fc06063 Update PlanPrinter to distinguish between inner and left spatial joins
## Martin Traverso      
- [x] all checked
-  05-23 09:50:05    8fdb01337e Remove unnecessary use of Visitor
-  05-23 09:50:58    2501e88816 Remove support for legacy ORDER BY semantics
-  05-24 11:03:22    065e055734 Do one more pass of output symbols pruning before rewriting subqueries
-  05-24 11:03:22    1986e6055d Add Limit node output symbols pruning rule
-  05-24 11:03:22    65abd69254 Add PushLimitThoughProject tests
-  05-24 11:03:22    8a0549b672 Do not pushdown limit though identity projection
-  05-24 11:03:22    efc79f7c42 Add correlated subquery test where limit is above filter
## Nezih Yigitbasi      
- [x] all checked
-  05-23 14:30:55    94302f73bf Remove LocalMemoryContext::transferMemory method
-  05-23 20:14:30    29dc0b9370 Remove hardcoded query max memory in TestingPrestoServer
-  05-24 09:43:46    4c507125bb Fix complex type handling in optimized Parquet reader
-  05-25 15:45:14    f079cfacda Fix LocalFileRecordCursor timestamp parser
## Piotr Findeisen      
- [x] all checked
-  05-22 23:47:46    4f1cd22ea9 Fix rpm dependency
## Rebecca Schlussel    
- [x] all checked
-  05-24 14:19:07    97e4e16ae7 Add access control test for WITH query
-  05-24 14:19:07    df2532fa28 Only check column access once
## Wenlei Xie           
- [x] all checked
-  05-24 10:58:31    5c7a614c20 Correct offset calculation in MapBlockBuilder.buildHashTableStrict
-  05-29 11:14:53    8d66c6deef Update closedSlicesRetainedSize in ChunkedSliceOutput
-  05-29 16:25:10    ec6b04c949 Support LazyBlock in ColumnarArray/Map/Row

**Comment by nezihyigitbasi** [comment]
Hive
-----
* Fix complex type handling in the optimized Parquet reader. Previously, null values, optional fields, and Parquet backward compatibility rules were not handled correctly.

**Comment by findepi** [comment]
```
Server RPM
----------
* Declare the dependency on ``uuidgen``. The ``uuidgen`` is required during installation of Presto server RPM package
  and lack of it resulted in invalid config file being generated during installation.
```

**Comment by dain** [comment]
```
General
--------
* Fix out of memory error caused by missing pushback checks in data exchanges.
* Improve query creation reliability by delaying query start until client acknowledges query id.
* Add support for PEM encoded (PKCS #8) keystore and truststore to the HTTP client and server.

**Comment by rschlussel2** [comment]
```
General
--------
* Remove redundant calls to check column access permissions.  Excessive calls sometimes caused queries to timeout.
```

**Comment by haozhun** [comment]
```
General
-------
* Fixed query execution failure for queries with cross joins when bucketed execution is on.

**Comment by wenleix** [comment]
General
--------
* Fix a bug that causes :func:`map` raise duplicate key error on valid input in some situations.

**Comment by electrum** [comment]
```
General Changes
---------------

* Fix quoting in error message for ``SHOW PARTITIONS``.

Security Changes
----------------

* Fix sending authentication challenge when using at least two of the
  ``KERBEROS``, ``PASSWORD``, or ``JWT`` authentication types are configured.

Hive Connector Changes
----------------------

* Improve error message for max open writers.

Thrift Connector Changes
------------------------

* Fix retry of requests when the remote Thrift server indicates that the
  error is retryable.

**Comment by electrum** [comment]
Release notes: https://github.com/prestodb/presto/pull/10730
