### ISSUE TITLE
Remove reserved pool to utilize memory more efficiently

### ISSUE THREAD

**Issue by sopel39** [prestodb/presto#10738]
We need to preserve following condition:

```If all queries got blocked on memory than we can designate one query that will finish anyway```

Currently reserved pool is used for that and one memory-blocked query is promoted to that pool. 
However we could get rid of reserved pool if node memory managers kept enough memory in general pool for at least one (among the running ones) query to complete. This way cluster memory would be utilized more efficiently and also this would solve: https://github.com/prestodb/presto/issues/10512

In a very initial approach coordinator would arbitrarily designate such "promoted" query and node memory managers would make sure that there is enough headroom for it.

In more advanced approach coordinator could dynamically try to change "promoted" query to the one that uses more memory memory so that the headroom is lower (thus improving memory utilization).

What do you think? @findepi @dain @nezihyigitbasi

**Comment by nezihyigitbasi** [comment]
>However we could get rid of reserved pool if node memory managers kept enough memory in general pool for at least one (among the running ones) query to complete. 

By "kept" you mean keep idle and no other query can use it?

> In a very initial approach coordinator would arbitrarily designate such "promoted" query and node memory managers would make sure that there is enough headroom for it.

Regarding the "enough headroom for it", the headroom will be a constant, right? We don't know the peak amount of memory a query can consume, so we will use the value of `query.max-memory-per-node` as we do right now for sizing the reserved pool (or `query.max-total-memory-per-node` if the system pool is disabled).

**Comment by sopel39** [comment]
> By "kept" you mean keep idle and no other query can use it?

Yes. I think we can do that without explicit pool now, right?

> Regarding the "enough headroom for it", the headroom will be a constant, right? We don't know the peak amount of memory a query can consume

Only the max query memory per node is constant. Let's name query max memory as `QMX`. For query `q` let's name it's node (`n`) memory usage as `used_memory(q, n)`. Then headroom required for query `q` on node `n` is:
`headroom(q, n) = QMX - user_memory(q, n)`. 
Therefore `headroom` depends on current query memory usage.

On a cluster level we want query with lowest total headroom to be "reserved".

**Comment by cemcayiroglu** [comment]
@sopel39 what is going to be behavior when the headroom is left as free. Are going to pause other  running queries and let promoted query to run?

**Comment by sopel39** [comment]
The idea is that all queries should run concurrently until required headroom is available. Only currently "promoted" query can eat into headroom memory.
