### ISSUE TITLE
How to show hostname in cli

### ISSUE THREAD

**Issue by ufo22940268** [prestodb/presto#10749]
If i connect to presto server with this

`./presto --server example:8080 --catalog hive --schema default
`

then the console prompt will display like this

`presto:default>`

Does presto has a option to display hostname, the cli prompt i wish to display is like this:

`presto:example:default`

**Comment by ebyhr** [comment]
@ufo22940268 As far as I know, there's no option to show hostname. 
The prompt string is built on here.
https://github.com/prestodb/presto/blob/master/presto-cli/src/main/java/com/facebook/presto/cli/Console.java#L180-L188

**Comment by ufo22940268** [comment]
@ebyhr  thanks
