### ISSUE TITLE
json_extract_scalar to get JSON field from Mongodb

### ISSUE THREAD

**Issue by ludi1981** [prestodb/presto#10751]
Hi all,

Our developers put JSON text into Mongodb. And I tried to get the data from Mongodb.
This screenshot is the fields in Mongodb.
![presto1](https://user-images.githubusercontent.com/23447205/40907365-2e24f554-6816-11e8-901d-43e5caadab91.png)

The data field is JSON, but I'm not sure why it is a row type in presto client. The screenshot shows what are put into data field.
![presto2](https://user-images.githubusercontent.com/23447205/40907573-dee215fc-6816-11e8-8e5b-923f95bfa4b4.png)
Per screenshot, there are two elements: _class and text. But, I fail to get text. Please see screenshot:
![presto3](https://user-images.githubusercontent.com/23447205/40907738-53ca1c66-6817-11e8-8ca7-e941fead4262.png)

Howere, if I use $[1], it works.
![presto4](https://user-images.githubusercontent.com/23447205/40907804-89618008-6817-11e8-83be-f22fa5647639.png)

Is there a way to get the JSON field from Mongodb by using JSON path like "$.text"? Thanks.
Presto version is 0.202
Mongodb: 3.2.4

**Comment by findepi** [comment]
Would would `select data.text ...` show? 

(btw, don't paste images unless necessary. You can format text blocks as verbatim using triple backticks ```` ``` ````)

**Comment by ludi1981** [comment]
@findepi thank you for advise. Great! It works...

> presto:default> select identity,data.text from mongodb."ychat-message".message;
  identity  |                                                                                                                                                                                  
------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 47829      | 123                                                                                                                                                                              
            |                                                                                                                                                                                  
 47829      | 333                                                                                                                                                                              
 1          | NULL                                                                                                                                                                             
 47829      | 2222                                                                                                                                                                             
 47829      | 1                                                                                                                                                                                
 47829      | 2                                                                                                                                                                                
            |
