### ISSUE TITLE
Presto(AWS EMR) ODBC Error - Peer certificate cannot be authenticated with given CA certificates

### ISSUE THREAD

**Issue by cskbhatt** [prestodb/presto#10755]
When trying to connect from Tableau desktop on windows to Presto on EMR using https , Below error pops up
`[Simba][Presto] (1020) Error with HTTP API at https://xxx.xxx.com:443/v1/statement : Peer certificate cannot be authenticated with given CA certificates
`
Presto on EMR - 0.194
EMR - emr-5.13.0
Tableau Desktop - 10.2.8 (10200.17.1206.1553) 64-bit
Simba Driver - SimbaPresto1.1-64-bit

I added certs to the local trust store and also tried to configure .tdc file in Document\My Tableau Repository\Datasources but no luck

Is this a compatibility issue with presto, tableau or are there any other drivers I need to install to enable connection

Thank you again for any suggestions

**Comment by ahmokhtari** [comment]
Hi @cskbhatt 
Have you managed to find a solution for this? I'm suffering from the same error.
