### ISSUE TITLE
LocalProperties#normalize weakens local properties

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#10761]
The implementation of `LocalProperties#normalize` is a suspect as it seems to be treating all local properties as `constants`:

```
    /**
     * Normalizes the local properties by removing redundant symbols, but retains the original local property positions
     */
    public static <T> List<Optional<LocalProperty<T>>> normalize(List<? extends LocalProperty<T>> localProperties)
    {
        List<Optional<LocalProperty<T>>> normalizedProperties = new ArrayList<>(localProperties.size());
        Set<T> constants = new HashSet<>();
        for (LocalProperty<T> localProperty : localProperties) {
            normalizedProperties.add(localProperty.withConstants(constants));
            
----------> constants.addAll(localProperty.getColumns());
        }
        return normalizedProperties;
    }

```

`TestLocalProperties` illustrates the side effects.

* A constant, sorted-by, and grouped symbol becomes *just* grouped. (Constant implies sorted which implies grouped, but grouped is the weakest of the three.)

```
    @Test
    public void testNormalizeOverlappingSymbol()
    {
        List<LocalProperty<String>> localProperties = builder()
                .grouped("a")
                .sorted("a", SortOrder.ASC_NULLS_FIRST)
                .constant("a")
                .build();
        assertNormalize(
                localProperties,
                Optional.of(grouped("a")),
                Optional.empty(),
                Optional.empty());
```

* Sorted symbol becomes *just* grouped.

```
    @Test
    public void testNormalizeComplexWithLeadingConstant()
    {
        List<LocalProperty<String>> localProperties = builder()
                .constant("a")
                .grouped("a", "b")
                .grouped("b", "c")
                .sorted("c", SortOrder.ASC_NULLS_FIRST)
                .build();
        assertNormalize(
                localProperties,
                Optional.of(constant("a")),
                Optional.of(grouped("b")),
                Optional.of(grouped("c")),
                Optional.empty());
```

@martint @sopel39 @findepi @kokosing Is this a bug or am I missing something?

**Comment by martint** [comment]
Keep in mind that local properties are hierarchical. A set of properties like:

```C(a), G(a,b), G(b,c), S(c)```

Says:
* Within that stream, `a` is constant
* Within the constant value of `a`, data is grouped on `a` and `b` (so `a` is irrelevant)
* Within each (`a`,`b`) group, data is grouped by `b` and `c` (so `b` is irrelevant)
* Within each (`b`,`c`) group, data is sorted by `c` (so sorting on `c` is irrelevant, since all the values within a group (`b`,`c`) will have the same value of `c`)

**Comment by mbasmanova** [comment]
@martint Martin, thanks for explaining. Now the implementation of `LocalProperties#normalize` makes sense. Furthermore, it looks like I can't express both `grouped({unique, a})` and `grouped({unique, a, b})` using local properties.

**Comment by mbasmanova** [comment]
@martint @kokosing @sopel39 

To summarise, 

`G(unique), G(a), G(b), G(c)` says

* Data is grouped on `unique`
* Within each (`unique`) group, data is grouped on `a`
* Within each (`unique`, `a`) group, data is grouped on `b`
* Within each (`unique`, '`a', `b`) group, data is grouped on `c`

If `a`, `b`, `c` are source columns, than `AssignUniqueId` generates output satisfying `G(unique), G(a), G(b), G(c)` because `unique` has unique values, e.g. all top-level and nested groups are of size 1.

An inner or left hash join with probe stream satisfying `G(x), G(y), G(z), G(w)` generates output that also satisfies `G(x), G(y), G(z), G(w)`. 

Now, an aggregation with source satisfying `G(x), G(y), G(z), G(w)` can be executed in a streaming fashion as long as each grouping set is a prefix of `{x, y, z, w}`, right?

Martin, Grzegorz, Karol, do you think the reasoning above is correct?

**Comment by sopel39** [comment]
> If a, b, c are source columns, than AssignUniqueId generates output satisfying G(unique), G(a), G(b), G(c) because unique has unique values, e.g. all top-level and nested groups are of size 1.

So `G(a), G(b), G(c)` seems stronger than `G(a, b, c)` as `a` cannot be scattered across data set. 
Maybe adjust https://github.com/prestodb/presto/pull/10731/commits/96c2c8cb68dd8d1f8497f44c73d85bfd58a8ae37#diff-64cfd4c0cfe165b7dcc4934f126200e5R186 accordingly, e.g: add multiple cascading grouping properties for each column?

> An inner or left hash join with probe stream satisfying G(x), G(y), G(z), G(w) generates output that also satisfies G(x), G(y), G(z), G(w).

That seems true as join seems to increase group cardinality only (multiply consecutive probe rows).

> Now, an aggregation with source satisfying G(x), G(y), G(z), G(w) can be executed in a streaming fashion as long as each grouping set is a prefix of {x, y, z, w}, right?

Sounds reasonable. I think local property normalization deals with that as long as you try to match `G(grouping keys)` as you do in https://github.com/prestodb/presto/pull/10731/commits/96c2c8cb68dd8d1f8497f44c73d85bfd58a8ae37#diff-1c30b35c527867a7f6cb028a5e49bcf9R289

**Comment by mbasmanova** [comment]
@sopel39 Karol, thanks for your thoughts. I'm also thinking that we could use `G(unique), C(a), C(b), C(c)` to capture more of *uniqueness* of `unique` column produced by `AssignUniqueId`. I'll update `PropertyDerivations#visitAssignUniqueId`.
