### ISSUE TITLE
Optimization: add LIMIT for DISTINCT if all values are known

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#10772]
Consider the following query:
```
SELECT DISTINCT ds
FROM t
WHERE id = 4
```
If the table layout guarantees a fixed set of values for `ds`, we can add a limit node, allowing the query to complete once all possible values have been produced.

**Comment by kokosing** [comment]
> add a limit node, allowing the query to complete once all possible values have been produced.

Do you mean a new plan node with a matching operator? Do you want to put such a node before aggregation that calculates distinct values or instead of it?

**Comment by martint** [comment]
If I understand correctly, what you're suggesting is turning this:

```
- Aggregation [ds]
    - Filter: id = 4
        - TableScan [t]
```

into 

```
- Limit (# of unique values for ds)
    - Aggregation [ds]
        - Filter: id = 4
            - TableScan [t]
```

which should then optimize to

```
- DistinctLimit [ds] (# of unique values for ds)
    - Filter: id = 4
        - TableScan [t]
```

Unfortunately, it's not that easy. At the point where we look at the table layout there's no information about whether anything would be able to benefit from knowing the number of unique values for the fields produced by the scan. At the point where we look at the aggregation, there's no information about the maximum cardinality of the fields produced by its input subplan.

Implementing will probably require first having support for traits and/or propagating information about the max cardinality by stats, plus a new rule that can consider that when looking at the aggregation node. It's definitely not a beginner task.

**Comment by electrum** [comment]
No, just a normal limit node. If we know the query can produce at most 5 values, add a “limit 5” so it can stop early.

**Comment by sopel39** [comment]
> and/or propagating information about the max cardinality by stats

stats are inherently estimates, so probably something more solid would be needed.
