### ISSUE TITLE
Predicate push down  not working in window function in sub query

### ISSUE THREAD

**Issue by MichaelZhao9824** [prestodb/presto#10774]
Hi Guys,

We are using Presto 0.197 and got a view which has window function in sub query. It seems that the predicate not correctly been pushed down to the window function. But if we directly put predicate in sub query and it is working fine. Any idea?

Explain result for view access (predicate not push down to window function)：

- Output[logical_name, mac_addr, cable_mac_name, service_class_name, service_direction, service_octets_passed] => [cmts_host_name:varchar, cm_mac_addr:varchar, cmts_mdif_name:varchar, service_class_name:varchar, service_direction:bigint, expr_205:bigint]
                                            logical_name := cmts_host_name
                                            mac_addr := cm_mac_addr
                                            cable_mac_name := cmts_mdif_name
                                            service_octets_passed := expr_205
                                        - RemoteExchange[GATHER] => cmts_host_name:varchar, cm_mac_addr:varchar, cmts_mdif_name:varchar, service_class_name:varchar, service_direction:bigint, expr_205:bigint
                                            - Project[] => [cmts_host_name:varchar, cm_mac_addr:varchar, cmts_mdif_name:varchar, service_class_name:varchar, service_direction:bigint, expr_205:bigint]
                                                    expr_205 := (CASE WHEN ("expr_45" > BIGINT '0') THEN "expr_45" ELSE BIGINT '0' END)
                                                - Project[] => [cmts_host_name:varchar, cm_mac_addr:varchar, cmts_mdif_name:varchar, service_class_name:varchar, service_direction:bigint, expr_45:bigint]
                                                        expr_45 := ("service_octets_passed" - "lag")
                                                    - FilterProject[filterPredicate = ((("dt" >= 20180527) AND ("dt" <= 20180603)) AND ("cm_mac_addr" = CAST('78-23-ae-a4-bb-05' AS varchar)))] => [cmts_host_name:varchar, cmts_mdif_name:varchar, service_octets_passed:bigint, lag:bigint, service_direction:bigint, cm_mac_addr:varchar, service_class_name:varchar]
                                                        - Project[] => [cmts_host_name:varchar, cmts_mdif_name:varchar, dt:integer, expr:bigint, service_octets_passed:bigint, service_direction:bigint, cm_mac_addr:varchar, service_class_name:varchar, metrics_date:timestamp, lag:bigint]
                                                            - Window[partition by (cm_mac_addr, service_class_name, service_direction), order by (cm_mac_addr ASC_NULLS_LAST, service_class_name ASC_NULLS_LAST, metrics_date ASC_NULLS_LAST)][$hashvalue] => [cmts_host_name:varchar, cmts_mdif_name:varchar, dt:integer, expr:bigint, service_octets_passed:bigint, service_direction:bigint, cm_mac_addr:varchar, service_class_name:varchar, metrics_date:timestamp, $hashvalue:bigint, lag:bigint]
                                                                    lag := lag("service_octets_passed", "expr", "service_octets_passed") 
                                                                - LocalExchange[HASH][$hashvalue] ("cm_mac_addr", "service_class_name", "service_direction") => cmts_host_name:varchar, cmts_mdif_name:varchar, dt:integer, expr:bigint, service_octets_passed:bigint, service_direction:bigint, cm_mac_addr:varchar, service_class_name:varchar, metrics_date:timestamp, $hashvalue:bigint
                                                                        Cost: {rows: ? (?), cpu: ?, memory: 0.00, network: ?}
                                                                    - RemoteExchange[REPARTITION][$hashvalue_407] => cmts_host_name:varchar, cmts_mdif_name:varchar, dt:integer, expr:bigint, service_octets_passed:bigint, service_direction:bigint, cm_mac_addr:varchar, service_class_name:varchar, metrics_date:timestamp, $hashvalue_407:bigint
                                                                            Cost: {rows: ? (?), cpu: ?, memory: 0.00, network: ?}
                                                                        - ScanProject[table = hive:thor_datastore:hfc_servassure_ipdr_utilisation_stats, originalConstraint = true] => [cmts_host_name:varchar, cmts_mdif_name:varchar, dt:integer, expr:bigint, service_octets_passed:bigint, service_direction:bigint, cm_mac_addr:varchar, service_class_name:varchar, metrics_date:timestamp, $hashvalue_408:bigint]
                                                                                Cost: {rows: ? (?), cpu: ?, memory: 0.00, network: 0.00}/{rows: ? (?), cpu: ?, memory: 0.00, network: 0.00}
                                                                                expr := BIGINT '1'
                                                                                $hashvalue_408 := "combine_hash"("combine_hash"("combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("cm_mac_addr"), 0)), COALESCE("$operator$hash_code"("service_class_name"), 0)), COALESCE("$operator$hash_code"("service_direction"), 0))
                                                                                LAYOUT: thor_datastore.hfc_servassure_ipdr_utilisation_stats
                                                                                dt := HiveColumnHandle{name=dt, hiveType=int, hiveColumnIndex=-1, columnType=PARTITION_KEY}
                                                                                    :: [[20180329, 20180606]]
                                                                                service_class_name := HiveColumnHandle{name=service_class_name, hiveType=string, hiveColumnIndex=22, columnType=REGULAR}
                                                                                service_octets_passed := HiveColumnHandle{name=service_octets_passed, hiveType=bigint, hiveColumnIndex=24, columnType=REGULAR}
                                                                                service_direction := HiveColumnHandle{name=service_direction, hiveType=bigint, hiveColumnIndex=23, columnType=REGULAR}
                                                                                metrics_date := HiveColumnHandle{name=metrics_date, hiveType=timestamp, hiveColumnIndex=35, columnType=REGULAR}
                                                                                cm_mac_addr := HiveColumnHandle{name=cm_mac_addr, hiveType=string, hiveColumnIndex=8, columnType=REGULAR}
                                                                                cmts_host_name := HiveColumnHandle{name=cmts_host_name, hiveType=string, hiveColumnIndex=2, columnType=REGULAR}
                                                                                cmts_mdif_name := HiveColumnHandle{name=cmts_mdif_name, hiveType=string, hiveColumnIndex=6, columnType=REGULAR}
                                                                                HiveColumnHandle{name=hour, hiveType=int, hiveColumnIndex=-1, columnType=PARTITION_KEY}
                                                                                    :: [[0], [1], [2], [3], [4], [5], [6], [7], [8], [9], [10], [11], [12], [13], [14], [15], [16], [17], [18], [19], [20], [21], [22], [23]]

Directly apply the predicate in sub query:

- Output[logical_name, mac_addr, cable_mac_name, service_class_name, service_direction, metrics_date, service_octets_passed_cum, service_octets_passed, service_pkts_passed_cum] => [cmts_host_name:varchar, cm_mac_addr:varchar, cmts_mdif_name:varchar, service_class_name:varchar, service_direction:bigint, metrics_date:timestamp, service_octets_passed:bigint, expr_15:bigint, service_pkts_passed:bigint]
        logical_name := cmts_host_name
        mac_addr := cm_mac_addr
        cable_mac_name := cmts_mdif_name
        service_octets_passed_cum := service_octets_passed
        service_octets_passed := expr_15
        service_pkts_passed_cum := service_pkts_passed
    - RemoteExchange[GATHER] => cmts_host_name:varchar, cm_mac_addr:varchar, cmts_mdif_name:varchar, service_class_name:varchar, service_direction:bigint, metrics_date:timestamp, service_octets_passed:bigint, expr_15:bigint, service_pkts_passed:bigint
        - Project[] => [cmts_host_name:varchar, cm_mac_addr:varchar, cmts_mdif_name:varchar, service_class_name:varchar, service_direction:bigint, metrics_date:timestamp, service_octets_passed:bigint, expr_15:bigint, service_pkts_passed:bigint]
                expr_15 := ("service_octets_passed" - "lag")
            - Window[partition by (<cm_mac_addr>, service_class_name, service_direction), order by (cm_mac_addr ASC_NULLS_LAST, service_class_name ASC_NULLS_LAST, metrics_date ASC_NULLS_LAST)][$hashvalue] => [cmts_host_name:varchar, cmts_mdif_name:varchar, service_pkts_passed:bigint, expr:bigint, service_octets_passed:bigint, service_direction:bigint, cm_mac_addr:varchar, service_class_name:varchar, metrics_date:timestamp, $hashvalue:bigint, lag:bigint]
                    lag := lag("service_octets_passed", "expr", "service_octets_passed") 
                - LocalExchange[HASH][$hashvalue] ("cm_mac_addr", "service_class_name", "service_direction") => cmts_host_name:varchar, cmts_mdif_name:varchar, service_pkts_passed:bigint, expr:bigint, service_octets_passed:bigint, service_direction:bigint, cm_mac_addr:varchar, service_class_name:varchar, metrics_date:timestamp, $hashvalue:bigint
                        Cost: {rows: ? (?), cpu: ?, memory: 0.00, network: ?}
                    - RemoteExchange[REPARTITION][$hashvalue_44] => cmts_host_name:varchar, cmts_mdif_name:varchar, service_pkts_passed:bigint, expr:bigint, service_octets_passed:bigint, service_direction:bigint, cm_mac_addr:varchar, service_class_name:varchar, metrics_date:timestamp, $hashvalue_44:bigint
                            Cost: {rows: ? (?), cpu: ?, memory: 0.00, network: ?}
                        - ScanFilterProject[table = hive:thor_datastore:hfc_servassure_ipdr_utilisation_stats, originalConstraint = ((("dt" >= 20180602) AND ("dt" <= 20180603)) AND ("cm_mac_addr" = CAST('78-23-ae-a4-bb-05' AS varchar))), filterPredicate = ("cm_mac_addr" = CAST('78-23-ae-a4-bb-05' AS varchar))] => [cmts_host_name:varchar, cmts_mdif_name:varchar, service_pkts_passed:bigint, expr:bigint, service_octets_passed:bigint, service_direction:bigint, cm_mac_addr:varchar, service_class_name:varchar, metrics_date:timestamp, $hashvalue_45:bigint]
                                Cost: {rows: ? (?), cpu: ?, memory: 0.00, network: 0.00}/{rows: ? (?), cpu: ?, memory: 0.00, network: 0.00}/{rows: ? (?), cpu: ?, memory: 0.00, network: 0.00}
                                expr := BIGINT '1'
                                $hashvalue_45 := "combine_hash"("combine_hash"("combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("cm_mac_addr"), 0)), COALESCE("$operator$hash_code"("service_class_name"), 0)), COALESCE("$operator$hash_code"("service_direction"), 0))
                                LAYOUT: thor_datastore.hfc_servassure_ipdr_utilisation_stats
                                service_class_name := HiveColumnHandle{name=service_class_name, hiveType=string, hiveColumnIndex=22, columnType=REGULAR}
                                service_octets_passed := HiveColumnHandle{name=service_octets_passed, hiveType=bigint, hiveColumnIndex=24, columnType=REGULAR}
                                service_direction := HiveColumnHandle{name=service_direction, hiveType=bigint, hiveColumnIndex=23, columnType=REGULAR}
                                metrics_date := HiveColumnHandle{name=metrics_date, hiveType=timestamp, hiveColumnIndex=35, columnType=REGULAR}
                                cm_mac_addr := HiveColumnHandle{name=cm_mac_addr, hiveType=string, hiveColumnIndex=8, columnType=REGULAR}
                                service_pkts_passed := HiveColumnHandle{name=service_pkts_passed, hiveType=bigint, hiveColumnIndex=25, columnType=REGULAR}
                                cmts_host_name := HiveColumnHandle{name=cmts_host_name, hiveType=string, hiveColumnIndex=2, columnType=REGULAR}
                                cmts_mdif_name := HiveColumnHandle{name=cmts_mdif_name, hiveType=string, hiveColumnIndex=6, columnType=REGULAR}
                                HiveColumnHandle{name=hour, hiveType=int, hiveColumnIndex=-1, columnType=PARTITION_KEY}
                                    :: [[0], [1], [2], [3], [4], [5], [6], [7], [8], [9], [10], [11], [12], [13], [14], [15], [16], [17], [18], [19], [20], [21], [22], [23]]
                                HiveColumnHandle{name=dt, hiveType=int, hiveColumnIndex=-1, columnType=PARTITION_KEY}
                                    :: [[20180602], [20180603]]

I noticed there is  difference - ScanFilterProject vs ScanProject. The filter not passed correctly.

**Comment by electrum** [comment]
Can you provide a simple query that reproduces this? Or at least provide the query for the plan shown?

**Comment by MichaelZhao9824** [comment]
Hi @electrum ,

there is our view (I changed some names):


CREATE OR REPLACE VIEW
hive.AAA.CCC
AS
select
logical_name
,mac_addr
,cable_mac_name
,service_class_name
,COALESCE(TRY((case when service_octets_passed < 0 then 0 else service_octets_passed end) / service_pkts_passed), 0) as service_octects_per_pkt_passed --Calculates the amount of packets in each octect
,(cast((case when service_octets_passed < 0 then 0 else service_octets_passed end) as decimal(38,4)) / 1000000)  as service_megabytes_passed -- Calculates the megabytes downloaded for the given hour period
,dt
from
(
        select
        cmts_host_name as logical_name
        ,cm_mac_addr as mac_addr
        ,cmts_mdif_name as cable_mac_name
        ,service_class_name as service_class_name
        ,service_direction as service_direction
        ,metrics_date
        ,service_octets_passed as service_octets_passed_cum
        ,service_octets_passed   - lag(service_octets_passed , 1, service_octets_passed ) OVER (partition by cm_mac_addr,service_class_name, service_direction
                                                                                    ORDER BY cm_mac_addr,service_class_name,metrics_date ASC)
          AS service_octets_passed  --Window function to convert running counter into delta per time period.

        ,dt
        from hive.AAA.BBB

if you run the query which will scan all partition:

select logical_name
,mac_addr
,cable_mac_name
,service_class_name
,service_direction, service_octets_passed  from hive.AAA.CCC where  dt >= 20180421 and dt<= 20180423  and mac_addr = '1111111'

but if you run the query directly from table hive.AAA.BBB. there is very fast without any issue.

select
       logical_name
        ,mac_addr
        , cable_mac_name
        ,service_class_name
        , service_direction
        ,service_octets_passed   - lag(service_octets_passed , 1, service_octets_passed ) OVER (partition by cm_mac_addr,service_class_name, service_direction
                                                                                    ORDER BY cm_mac_addr,service_class_name,metrics_date ASC)
          AS service_octets_passed  --Window function to convert running counter into delta per time period.

        ,dt
        from hive.AAA.BBB
where  dt >= 20180421 and dt<= 20180423  and mac_addr = '1111111'
 

Thanks.

**Comment by kokosing** [comment]
Can you please try test it with a build on recent master, yesterday I spotted very similar problem that predicate from outer query was not propagated to subquery. Fix is here: https://github.com/prestodb/presto/commit/321130ac58518ead0d6a2a05c2e72260928f4755, and a test is here: https://github.com/prestodb/presto/commit/5a2ec50a7b424709f34eecd0a194396574a5c5e0.

**Comment by MichaelZhao9824** [comment]
@kokosing thanks a lot. will have a try

**Comment by MichaelZhao9824** [comment]
@kokosing I just completed the testing using the latest master branch but the problem is still not fixed. 
It still uses ScanProject instead of ScanFilterProject. Any ideas? Thanks.

- Output[logical_name, mac_addr, cable_mac_name, service_class_name, service_direction, service_octets_passed] => [cmts_host_name:varchar, cm_mac_addr:varchar, cmts_mdif_name:varchar, service_class_name:varchar, service_direction:bigint, expr_205:bigint]
        logical_name := cmts_host_name
        mac_addr := cm_mac_addr
        cable_mac_name := cmts_mdif_name
        service_octets_passed := expr_205
    - RemoteExchange[GATHER] => cmts_host_name:varchar, cm_mac_addr:varchar, cmts_mdif_name:varchar, service_class_name:varchar, service_direction:bigint, expr_205:bigint
        - Project[] => [cmts_host_name:varchar, cm_mac_addr:varchar, cmts_mdif_name:varchar, service_class_name:varchar, service_direction:bigint, expr_205:bigint]
                expr_205 := (CASE WHEN ("expr_45" > BIGINT '0') THEN "expr_45" ELSE BIGINT '0' END)
            - Project[] => [cmts_host_name:varchar, cm_mac_addr:varchar, cmts_mdif_name:varchar, service_class_name:varchar, service_direction:bigint, expr_45:bigint]
                    Cost: {rows: ? (?), cpu: ?, memory: ?, network: ?}
                    expr_45 := ("service_octets_passed" - "lag")
                - FilterProject[filterPredicate = ((("dt" >= 20180421) AND ("dt" <= 20180423)) AND ("cm_mac_addr" = CAST('78-23-ae-a4-bb-05' AS varchar)))] => [cmts_host_name:varchar, cmts_mdif_name:varchar, service_octets_passed:bigint, lag:bigint, service_direction:bigint, cm_mac_addr:varchar, service_class_name:varchar]
                    - Project[] => [cmts_host_name:varchar, cmts_mdif_name:varchar, dt:integer, expr:bigint, service_octets_passed:bigint, service_direction:bigint, cm_mac_addr:varchar, service_class_name:varchar, metrics_date:timestamp, lag:bigint]
                        - Window[partition by (cm_mac_addr, service_class_name, service_direction), order by (cm_mac_addr ASC_NULLS_LAST, service_class_name ASC_NULLS_LAST, metrics_date ASC_NULLS_LAST)][$hashvalue] => [cmts_host_name:varchar, cmts_mdif_name:varchar, dt:integer, expr:bigint, service_octets_passed:bigint, service_direction:bigint, cm_mac_addr:varchar, service_class_name:varchar, metrics_date:timestamp, $hashvalue:bigint, lag:bigint]
                                lag := lag("service_octets_passed", "expr", "service_octets_passed") 
                            - LocalExchange[HASH][$hashvalue] ("cm_mac_addr", "service_class_name", "service_direction") => cmts_host_name:varchar, cmts_mdif_name:varchar, dt:integer, expr:bigint, service_octets_passed:bigint, service_direction:bigint, cm_mac_addr:varchar, service_class_name:varchar, metrics_date:timestamp, $hashvalue:bigint
                                    Cost: {rows: ? (?), cpu: ?, memory: 0.00, network: ?}
                                - RemoteExchange[REPARTITION][$hashvalue_407] => cmts_host_name:varchar, cmts_mdif_name:varchar, dt:integer, expr:bigint, service_octets_passed:bigint, service_direction:bigint, cm_mac_addr:varchar, service_class_name:varchar, metrics_date:timestamp, $hashvalue_407:bigint
                                        Cost: {rows: ? (?), cpu: ?, memory: 0.00, network: ?}
                                    - ScanProject[table = hive:thor_datastore:hfc_servassure_ipdr_utilisation_stats, originalConstraint = true] => [cmts_host_name:varchar, cmts_mdif_name:varchar, dt:integer, expr:bigint, service_octets_passed:bigint, service_direction:bigint, cm_mac_addr:varchar, service_class_name:varchar, metrics_date:timestamp, $hashvalue_408:bigint]
                                            Cost: {rows: ? (?), cpu: ?, memory: 0.00, network: 0.00}/{rows: ? (?), cpu: ?, memory: 0.00, network: 0.00}
                                            expr := BIGINT '1'
                                            $hashvalue_408 := "combine_hash"("combine_hash"("combine_hash"(bigint '0', COALESCE("$operator$hash_code"("cm_mac_addr"), 0)), COALESCE("$operator$hash_code"("service_class_name"), 0)), COALESCE("$operator$hash_code"("service_direction"), 0))
                                            LAYOUT: thor_datastore.hfc_servassure_ipdr_utilisation_stats
                                            dt := HiveColumnHandle{name=dt, hiveType=int, hiveColumnIndex=-1, columnType=PARTITION_KEY}
                                                :: [[20180413], [20180415], [20180416], [20180417], [20180418], [20180419], [20180420], [20180421], [20180422], [20180423]]
                                            service_class_name := HiveColumnHandle{name=service_class_name, hiveType=string, hiveColumnIndex=22, columnType=REGULAR}
                                            service_octets_passed := HiveColumnHandle{name=service_octets_passed, hiveType=bigint, hiveColumnIndex=24, columnType=REGULAR}
                                            service_direction := HiveColumnHandle{name=service_direction, hiveType=bigint, hiveColumnIndex=23, columnType=REGULAR}
                                            metrics_date := HiveColumnHandle{name=metrics_date, hiveType=timestamp, hiveColumnIndex=35, columnType=REGULAR}
                                            cm_mac_addr := HiveColumnHandle{name=cm_mac_addr, hiveType=string, hiveColumnIndex=8, columnType=REGULAR}
                                            cmts_host_name := HiveColumnHandle{name=cmts_host_name, hiveType=string, hiveColumnIndex=2, columnType=REGULAR}
                                            cmts_mdif_name := HiveColumnHandle{name=cmts_mdif_name, hiveType=string, hiveColumnIndex=6, columnType=REGULAR}
                                            HiveColumnHandle{name=hour, hiveType=int, hiveColumnIndex=-1, columnType=PARTITION_KEY}
                                                :: [[0], [1], [2], [3], [4], [5], [6], [7], [8], [9], [10], [11], [12], [13], [14], [15], [16], [17], [18], [19], [20], [21], [22], [23]]

**Comment by kokosing** [comment]
Can you post an `EXPLAIN` for the query where predicate pushdown is working?

It looks like `com.facebook.presto.sql.planner.optimizations.PredicatePushDown` does not support `WindowNode`.

**Comment by MichaelZhao9824** [comment]
I got one with window function but not in sub query which is working fine 

- Output[logical_name, mac_addr, cable_mac_name, service_class_name, service_direction, metrics_date, service_octets_passed_cum, service_octets_passed, service_pkts_passed_cum] => [cmts_host_name:varchar, cm_mac_addr:varchar, cmts_mdif_name:varchar, service_class_name:varchar, service_direction:bigint, metrics_date:timestamp, service_octets_passed:bigint, expr_15:bigint, service_pkts_passed:bigint]
        logical_name := cmts_host_name
        mac_addr := cm_mac_addr
        cable_mac_name := cmts_mdif_name
        service_octets_passed_cum := service_octets_passed
        service_octets_passed := expr_15
        service_pkts_passed_cum := service_pkts_passed
    - RemoteExchange[GATHER] => cmts_host_name:varchar, cm_mac_addr:varchar, cmts_mdif_name:varchar, service_class_name:varchar, service_direction:bigint, metrics_date:timestamp, service_octets_passed:bigint, expr_15:bigint, service_pkts_passed:bigint
        - Project[] => [cmts_host_name:varchar, cm_mac_addr:varchar, cmts_mdif_name:varchar, service_class_name:varchar, service_direction:bigint, metrics_date:timestamp, service_octets_passed:bigint, expr_15:bigint, service_pkts_passed:bigint]
                expr_15 := ("service_octets_passed" - "lag")
            - Window[partition by (<cm_mac_addr>, service_class_name, service_direction), order by (cm_mac_addr ASC_NULLS_LAST, service_class_name ASC_NULLS_LAST, metrics_date ASC_NULLS_LAST)][$hashvalue] => [cmts_host_name:varchar, cmts_mdif_name:varchar, service_pkts_passed:bigint, expr:bigint, service_octets_passed:bigint, service_direction:bigint, cm_mac_addr:varchar, service_class_name:varchar, metrics_date:timestamp, $hashvalue:bigint, lag:bigint]
                    lag := lag("service_octets_passed", "expr", "service_octets_passed") 
                - LocalExchange[HASH][$hashvalue] ("cm_mac_addr", "service_class_name", "service_direction") => cmts_host_name:varchar, cmts_mdif_name:varchar, service_pkts_passed:bigint, expr:bigint, service_octets_passed:bigint, service_direction:bigint, cm_mac_addr:varchar, service_class_name:varchar, metrics_date:timestamp, $hashvalue:bigint
                        Cost: {rows: ? (?), cpu: ?, memory: 0.00, network: ?}
                    - RemoteExchange[REPARTITION][$hashvalue_44] => cmts_host_name:varchar, cmts_mdif_name:varchar, service_pkts_passed:bigint, expr:bigint, service_octets_passed:bigint, service_direction:bigint, cm_mac_addr:varchar, service_class_name:varchar, metrics_date:timestamp, $hashvalue_44:bigint
                            Cost: {rows: ? (?), cpu: ?, memory: 0.00, network: ?}
                        - ScanFilterProject[table = hive:thor_datastore:hfc_servassure_ipdr_utilisation_stats, originalConstraint = ((("dt" >= 20180602) AND ("dt" <= 20180603)) AND ("cm_mac_addr" = CAST('78-23-ae-a4-bb-05' AS varchar))), filterPredicate = ("cm_mac_addr" = CAST('78-23-ae-a4-bb-05' AS varchar))] => [cmts_host_name:varchar, cmts_mdif_name:varchar, service_pkts_passed:bigint, expr:bigint, service_octets_passed:bigint, service_direction:bigint, cm_mac_addr:varchar, service_class_name:varchar, metrics_date:timestamp, $hashvalue_45:bigint]
                                Cost: {rows: ? (?), cpu: ?, memory: 0.00, network: 0.00}/{rows: ? (?), cpu: ?, memory: 0.00, network: 0.00}/{rows: ? (?), cpu: ?, memory: 0.00, network: 0.00}
                                expr := BIGINT '1'
                                $hashvalue_45 := "combine_hash"("combine_hash"("combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("cm_mac_addr"), 0)), COALESCE("$operator$hash_code"("service_class_name"), 0)), COALESCE("$operator$hash_code"("service_direction"), 0))
                                LAYOUT: thor_datastore.hfc_servassure_ipdr_utilisation_stats
                                service_class_name := HiveColumnHandle{name=service_class_name, hiveType=string, hiveColumnIndex=22, columnType=REGULAR}
                                service_octets_passed := HiveColumnHandle{name=service_octets_passed, hiveType=bigint, hiveColumnIndex=24, columnType=REGULAR}
                                service_direction := HiveColumnHandle{name=service_direction, hiveType=bigint, hiveColumnIndex=23, columnType=REGULAR}
                                metrics_date := HiveColumnHandle{name=metrics_date, hiveType=timestamp, hiveColumnIndex=35, columnType=REGULAR}
                                cm_mac_addr := HiveColumnHandle{name=cm_mac_addr, hiveType=string, hiveColumnIndex=8, columnType=REGULAR}
                                service_pkts_passed := HiveColumnHandle{name=service_pkts_passed, hiveType=bigint, hiveColumnIndex=25, columnType=REGULAR}
                                cmts_host_name := HiveColumnHandle{name=cmts_host_name, hiveType=string, hiveColumnIndex=2, columnType=REGULAR}
                                cmts_mdif_name := HiveColumnHandle{name=cmts_mdif_name, hiveType=string, hiveColumnIndex=6, columnType=REGULAR}
                                HiveColumnHandle{name=hour, hiveType=int, hiveColumnIndex=-1, columnType=PARTITION_KEY}
                                    :: [[0], [1], [2], [3], [4], [5], [6], [7], [8], [9], [10], [11], [12], [13], [14], [15], [16], [17], [18], [19], [20], [21], [22], [23]]
                                HiveColumnHandle{name=dt, hiveType=int, hiveColumnIndex=-1, columnType=PARTITION_KEY}
                                    :: [[20180602], [20180603]]

**Comment by MichaelZhao9824** [comment]
Another one without window function in sub query which is working fine as well.


- Output[logical_name, mac_addr, cable_mac_name, service_class_name, service_direction] => [cmts_host_name:varchar, cm_mac_addr:varchar, cmts_mdif_name:varchar, service_class_name:varchar, service_direction:bigint]
        Cost: {rows: ? (?), cpu: ?, memory: 0.00, network: ?}
        logical_name := cmts_host_name
        mac_addr := cm_mac_addr
        cable_mac_name := cmts_mdif_name
    - RemoteExchange[GATHER] => cmts_host_name:varchar, cm_mac_addr:varchar, cmts_mdif_name:varchar, service_class_name:varchar, service_direction:bigint
            Cost: {rows: ? (?), cpu: ?, memory: 0.00, network: ?}
        - ScanFilter[table = hive:thor_datastore:hfc_servassure_ipdr_utilisation_stats, originalConstraint = ((("dt" >= 20180527) AND ("dt" <= 20180603)) AND ("cm_mac_addr" = CAST('78-23-ae-a4-bb-05' AS varchar))), filterPredicate = ("cm_mac_addr" = CAST('78-23-ae-a4-bb-05' AS varchar))] => [cmts_host_name:varchar, cmts_mdif_name:varchar, cm_mac_addr:varchar, service_class_name:varchar, service_direction:bigint]
                Cost: {rows: ? (?), cpu: ?, memory: 0.00, network: 0.00}/{rows: ? (?), cpu: ?, memory: 0.00, network: 0.00}
                LAYOUT: thor_datastore.hfc_servassure_ipdr_utilisation_stats
                service_class_name := HiveColumnHandle{name=service_class_name, hiveType=string, hiveColumnIndex=22, columnType=REGULAR}
                service_direction := HiveColumnHandle{name=service_direction, hiveType=bigint, hiveColumnIndex=23, columnType=REGULAR}
                cm_mac_addr := HiveColumnHandle{name=cm_mac_addr, hiveType=string, hiveColumnIndex=8, columnType=REGULAR}
                cmts_host_name := HiveColumnHandle{name=cmts_host_name, hiveType=string, hiveColumnIndex=2, columnType=REGULAR}
                cmts_mdif_name := HiveColumnHandle{name=cmts_mdif_name, hiveType=string, hiveColumnIndex=6, columnType=REGULAR}
                HiveColumnHandle{name=hour, hiveType=int, hiveColumnIndex=-1, columnType=PARTITION_KEY}
                    :: [[0], [1], [2], [3], [4], [5], [6], [7], [8], [9], [10], [11], [12], [13], [14], [15], [16], [17], [18], [19], [20], [21], [22], [23]]
                HiveColumnHandle{name=dt, hiveType=int, hiveColumnIndex=-1, columnType=PARTITION_KEY}
                    :: [[20180527], [20180528], [20180529], [20180530], [20180531], [20180601], [20180602], [20180603]]

**Comment by wagnermarkd** [comment]
@MichaelZhao9824, in some of your examples, pushing the predicate below the window would change the result of your query. When the window isn't in a subquery, then filter is applied before the windowing operation. That's why you're seeing a difference.

#12034 addresses pushing predicates through windows where applicable.
