### ISSUE TITLE
JDBC varchar maps to LONGNVARCHAR

### ISSUE THREAD

**Issue by s-b-u** [prestodb/presto#10778]
within com.facebook.presto.jdbc.ColumnInfo#getType, the type "varchar" is mapped to java.sql.Types.LONGNVARCHAR but com.facebook.presto.jdbc.PrestoResultSet#getNString is not supported.
Is this just a typo and java.sql.Types.LONGVARCHAR should be returned instead, or are there any other reasons.

**Comment by electrum** [comment]
We should probably just use VARCHAR. Feel free to send a pull request.

**Comment by findepi** [comment]
at the same time, it seems that `getNString` could be simply a supported operation

**Comment by electrum** [comment]
Agreed. I think we should do both.
