### ISSUE TITLE
Add function to return Nth instance of substring

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#10771]
Proposal:
```
strpos(string, substring, instance)
strrpos(string, substring)
strrpos(string, substring, instance)
```
The new variant of `strpos()` returns the Nth instance rather than the first. `instance` should be a positive number. Throws exception if it's 0 or negative.
`strrpos` with two parameters would return the position of the first instance from the back, or returns the Nth instance from the back. Throws exception if `instance` is 0 or negative.

Examples:
```
strpos('abc/xyz/foo/bar', '/', 1) = 4
strpos('abc/xyz/foo/bar', '/', 2) = 8
strpos('abc/xyz/foo/bar', '/', 3) = 12
strpos('abc/xyz/foo/bar', '/', 4) = 0
strrpos('abc/xyz/foo/bar', '/') = 12
strrpos('abc/xyz/foo/bar', '/', 1) = 12
strrpos('abc/xyz/foo/bar', '/', 3) = 4
strrpos('abc/xyz/foo/bar', '/', 4) = 0
```

**Comment by codope** [comment]
`StringUtils.ordinalIndexOf()` fails for the following case: `strpos('foobar', 'foobar', 1)`
So, I implemented the functionality without the util. I am almost done with the changes except for the test related to `position(a in b)` function. Do we need to keep it as part of the same test method? I think the two functions, `strpos` and `position`, are redundant and `strpos` is sufficient to cover `position` function.

**Comment by codope** [comment]
@electrum Could you please review the syntax and the pull request?

**Comment by codope** [comment]
@electrum Could you please review the syntax and the pull request?

**Comment by rongrong** [comment]
@codope For the PR, you need to rebase on top of the current master: `git pull --rebase upstream/master` You might also want to squash the commits into one with `git rebase -i`.
