### ISSUE TITLE
Query runs even though tasks are failed

### ISSUE THREAD

**Issue by ilfrin** [prestodb/presto#10781]
Observed when working with Presto on EC2. When a query that would normally takes under a minute to finish looses a node while executing (I manually terminated the EC2 instance when the query was running), then
* Presto Web UI immediately notices a worker is down and decreases the worker count
* New queries are handled normally
* The unfortunate running query runs for another 5 minutes (that's the default timeout) to end with "Too many error talking to node" error. 

The important bit is that as you observe the query details you can see that all tasks that are executing on that terminated node are immediately marked as "FAILED", so the query learns about the problem but still keeps running and waiting for the timeout on those nodes to fail. 

The timeout doesn't make sense in this case, even if the worker would rejoin the cluster, the tasks are failed, so the query has no chance of finishing successfully. 

So the grand question is: 
**If at least one of the tasks is FAILED shouldn't the query immediately abort and fail fast?** 

This seems like something to fix. Not a user friendly behaviour.

**Comment by dain** [comment]
That is the way it is supposed to work.  If the coordinator receives a response from a worker saying that a task is failed, an event if fired to the stage containing the task which fails the stage. Then an event is fired to the query and the query fails.  Then the query cancels all of the work.  

In the case of a hard crash of the worker, the coordinator does not get a "failed" message, and simply can not talk to the worker anymore.  This looks exactly like a worker in a long GC, so the coordinator waits until a timeout or until something responds on that port.

> The important bit is that as you observe the query details you can see that all tasks that are executing on that terminated node are immediately marked as "FAILED", so the query learns about the problem but still keeps running and waiting for the timeout on those nodes to fail.

That bit is interesting.  The whole system is listener based, so if something fails, teardown should be immediate.  If you can grab the query json document on the server for a query that has a failed task on the server but still running, I can likely fix this.

Also, do you know about the draining feature?

**Comment by sopel39** [comment]
> Also, do you know about the draining feature?

Could you elaborate?

**Comment by dain** [comment]
@sopel39 You can drain by sending a `PUT` with `SHUTTING_DOWN` to '/v1/info/state`. See https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/server/ServerInfoResource.java#L75

**Comment by findepi** [comment]
@dain 👍, we do that. 
This issue is about the situation when we don't do that -- when a node is taken offline un-nicely.

> In the case of a hard crash of the worker, the coordinator does not get a "failed" message, and simply can not talk to the worker anymore. This looks exactly like a worker in a long GC, so the coordinator waits until a timeout or until something responds on that port.

This would be perfectly understandable and this is what we expected to observe: query appearing to be running until some reporting/heartbeat timeout kicks in & kills it.
Yes, the web UI of the coordinator was showing _task_ failure immediately, yet query was still running. Thus coordinator had enough information to abort the query, yet it didn't connect the dots.

> The whole system is listener based, so if something fails, teardown should be immediate. If you can grab the query json document on the server for a query that has a failed task on the server but still running, I can likely fix this.

@ilfrin will you be able?
