### ISSUE TITLE
PREPARE / EXECUTE not working with INSERT INTO SELECT

### ISSUE THREAD

**Issue by agsax2002** [prestodb/presto#10809]
Hi. I was trying to follow code for executing a PREPARE statement with an EXECUTE clause, i.e. https://github.com/prestodb/presto/issues/5918

This works well when substituting a variable for a select query, but does not seem to work when using an insert into select statement, i.e.

```
PREPARE my_insert_query FROM
INSERT INTO my_table
SELECT *
FROM some_table
WHERE date = ?;
EXECUTE my_insert_query USING '2018-06-09';
EXECUTE my_insert_query USING '2018-06-10';
DEALLOCATE PREPARE my_insert_query;
```

On the first query, I am getting an error: "Query is gone (server restarted?)"
Then on the EXECUTE statement, I get the error: "Prepared statement not found: my_insert_query"

I have tried other permutations of this code, but to no avail. Am I missing something, or is this a real bug?

My whole intent is to use a PREPARE Statement to insert a variable for the date. Then I want to run insert statements on multiple dates with independent EXECUTE statements. I prefer running the dates in separate queries because running over a long series of days in one query uses too much memory (different issue). 

Thanks.

**Comment by agsax2002** [comment]
With further testing, this may be an issue related to https://github.com/prestodb/presto/issues/10049
My query has ~80 columns and is running into the Error running command: 500: Request header too large. Seems like an issue currently being working on.

**Comment by findepi** [comment]
If this works for a table with fewer columns but not with more columns, this must be https://github.com/prestodb/presto/issues/5759 . Protocol v2 is going to address this.
Also, you can use https://www.starburstdata.com/download/ (it contains https://github.com/prestodb/presto/pull/5868, which didn't make it into `master` because Protocol v2 was being planned)
