### ISSUE TITLE
Google Account Login

### ISSUE THREAD

**Issue by pranavoyo** [prestodb/presto#10805]
Is there a way/future scope to integrate Google account login for presto?

**Comment by raghavsethi** [comment]
Not sure what you mean exactly.. it's possible to write a plugin to do any sort of authentication you want but that would have to be configured by the deployment administrator.

**Comment by pranavoyo** [comment]
any guide/tutorial I can follow to write my custom plugin. I checked official doc and it does not help much.

**Comment by raghavsethi** [comment]
https://prestodb.io/docs/current/develop/system-access-control.html
This might also be helpful as an example implementation: https://prestodb.io/docs/current/security/ldap.html
