### ISSUE TITLE
How can I epoch the time ?

### ISSUE THREAD

**Issue by thanhlv93** [prestodb/presto#10811]
Hello All,
In postgrestSql I can using : 

> extract(epoch from '2018-06-06 09:52:00' )/300)::bigint*300  // 300 = 5 minutes
> extract(epoch from '2018-06-06 09:53:00' )/300)::bigint*300  // 300 = 5 minutes

and the result I received :  

> 2018-06-06 09:50:00
> 2018-06-06 09:55:00

But I cant  use "epoch"  with presto , I dont know how can I epoch the time with presto , Please tell me if you have any suggest .
Thank you.

**Comment by findepi** [comment]
@thanhlv93 in your examples there are unmatched parenthesis, which doesn't help.

i don't understand your question, what does it mean to "epoch the time"? 
If you have timestamp data and you want to round-down to whole 5-minutes, then https://stackoverflow.com/q/47066024/65458 might be helpful.

**Comment by thanhlv93** [comment]
Thanks @findepi , That is what I want . It's working perfect.
