### ISSUE TITLE
hive.information_schema.columns is null

### ISSUE THREAD

**Issue by yangjun616** [prestodb/presto#10829]
I use redash show all tables informations , by `SELECT table_schema, table_name, column_name
        FROM information_schema.columns
        WHERE table_schema NOT IN ('pg_catalog', 'information_schema')
`.

  But  when I upgrade presto from 0.150 to 0.198, it doesn't work. Then I find information_schema.columns null .is anything I ignore make this happends.
Anyone meet tha same questions?
thanks

**Comment by findepi** [comment]
What does the following print?
```
presto-cli --server http://your-prest-server:8080 --debug --execute "SELECT table_schema, table_name, column_name FROM hive.information_schema.columns WHERE table_schema NOT IN ('pg_catalog', 'information_schema')"
```

What does it print if you drop the `WHERE ...` part?

**Comment by findepi** [comment]
This has already been reported: #6972
