### ISSUE TITLE
Introduce JoinNode#matchMax

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#10830]
#10405 improved support for correlated no aggregation scalar queries. A query like

`SELECT name, (SELECT name FROM region WHERE regionkey = nation.regionkey) FROM nation`

is planned as a left join sandwiched between `AssignUniqueId` and `MarkDistinct` + `Filter`: 

- Filter if(is_distint, true, fail('Scalar sub-query has returned multiple rows'))
  - MarkDistinct (unique)
    - LeftJoin
      - AssignUniqueId (unique)
        - probe
      - build

The sole purpose of extra `AssignUniqueId`, `MarkDistinct` and `Filter` nodes is to verify at runtime that the scalar subquery returns zero or one row.

However, this check is expensive. The distributed plan includes a remote exchange between `MarkDistinct` and `LeftJoin`:

- Filter if(is_distint, true, fail('Scalar sub-query has returned multiple rows'))
  - MarkDistinct (unique)
    - RemoteExchange(hash(unique))
      - LeftJoin
        - RemoteExchange(hash(joinkey))
          - AssignUniqueId (unique)
            - probe
        - RemoteExchange(hash(joinkey))
          - build        

However, that remote exchange between `MarkDistinct` and `LeftJoin` is not needed, because the input to `MarkDistinct` is partitioned and grouped on `unique`. So, how can we avoid adding that exchange?

At the moment, I can't think of a way to derive necessary properties to skip the exchange. The main piece that's missing is ability to define *multiple* global properties.

`AssignUniqueId` can produce the necessary `partitioned_on(unique)` global property, but only if input to `AssignUniqueId` is not partitioned already. So, if we have

- Join
   - RemoteExchange (hash(joinkey))
      - AssignUniqueId (unique)

then `AssignUniqueId` produces `partitioned_on(unique)`, but it doesn't survive the exchange. If, after #10731, we have 

- Join
  - AssignUniqueId (unique)
    - RemoteExchange (hash(joinkey))

`AssignUniqueId` cannot produce `partitioned_on(unique)` because the input is already partitioned on `joinkey`.

Here is a snippet of the actual plan for reference (with changes from #10731):

```
        - FilterProject[filterPredicate = (CASE "is_distinct" WHEN true THEN true ELSE CAST("fail"(28, 'Scalar sub-query has returned multiple rows') AS boolean) END)] => [name:varchar(25), name_1:varchar(25)]
            - Project[] => [name:varchar(25), unique:bigint, name_1:varchar(25), is_distinct:boolean]
                - MarkDistinct[distinct=unique:bigint marker=is_distinct][$hashvalue] => [name:varchar(25), unique:bigint, name_1:varchar(25), $hashvalue:bigint, is_distinct:boolean]
*                    - LocalExchange[SINGLE] () => name:varchar(25), unique:bigint, name_1:varchar(25), $hashvalue:bigint
*                        - RemoteExchange[REPARTITION][$hashvalue_15] => name:varchar(25), unique:bigint, name_1:varchar(25), $hashvalue_15:bigint
*                            - Project[] => [name:varchar(25), unique:bigint, name_1:varchar(25), $hashvalue_21:bigint]
*                                    $hashvalue_21 := "combine_hash"(bigint '0', COALESCE("$operator$hash_code"("unique"), 0))
                                - LeftJoin[("regionkey" = "regionkey_0")][$hashvalue_16, $hashvalue_18] => [name:varchar(25), unique:bigint, name_1:varchar(25)]
                                        Distribution: PARTITIONED
                                    - AssignUniqueId => [name:varchar(25), regionkey:bigint, $hashvalue_16:bigint, unique:bigint]
                                        - RemoteExchange[REPARTITION][$hashvalue_16] => name:varchar(25), regionkey:bigint, $hashvalue_16:bigint
                                            - ScanProject[table = local:tpch:nation:sf0.01, originalConstraint = true] => [name:varchar(25), regionkey:bigint, $hashvalue_17:bigint]                                                    
                                    - LocalExchange[SINGLE] () => regionkey_0:bigint, name_1:varchar(25), $hashvalue_18:bigint
                                        - RemoteExchange[REPARTITION][$hashvalue_19] => regionkey_0:bigint, name_1:varchar(25), $hashvalue_19:bigint
                                            - ScanProject[table = local:tpch:region:sf0.01, originalConstraint = true] => [regionkey_0:bigint, name_1:varchar(25), $hashvalue_20:bigint]                                                  
```

Given these challenges, the proposal is to introduce `JoinNode#matchMax` property that says "Each probe row must produce no more then specified number of matches". Doing so would allow to eliminate the extra `AssignUniqueId`, `MarkDistinct` and `Filter` nodes as well as remote and local exchanges between `MarkDistinct` and `JoinNode` and corresponding hash generations.

Thoughts?

@kokosing @sopel39 @findepi @martint @dain

**Comment by findepi** [comment]
I like the idea.

Nit: what values of `matchMax` we will ever use? If this is `1` and `unlimited`, then a boolean flag (eg `enforceSingleMatch`) could probably be more useful.

**Comment by sopel39** [comment]
> Given these challenges, the proposal is to introduce JoinNode#matchMax property that says "Each probe row must produce no more then specified number of matches". Doing so would allow to eliminate the extra AssignUniqueId, MarkDistinct and Filter nodes as well as remote and local exchanges between MarkDistinct and JoinNode and corresponding hash generations.

Alternatively we could create plan with `MarkDistinct[all_probe_rows]` and then capture plan pattern of:
```
- MarkDistinct[all_probe_rows]
  - LeftJoin[...]
    - AssignUniqueId[unique] 
```
and rewrite it to:
```
- MarkDistinct[unique]
  - LeftJoin[...]
    - AssignUniqueId[unique] 
```
Basically we could have a `MarkDistinct` simplification rule that removes symbols of stream local properties are:
```
Grouped[unique], Constant[rest_probe_rows]
``` 
which is I believe what you did

**Comment by mbasmanova** [comment]
Piotr, Karol, thanks for sharing your thoughts.

@findepi 

> what values of matchMax we will ever use? If this is 1 and unlimited, then a boolean flag (eg enforceSingleMatch) could probably be more useful.

I can only think of `1` and `unlimited`. Agree, `enforceSingleMatch` would work and is simpler to implement.

Disclaimer: the credit for this idea goes to @dain

@sopel39 Karol, I considered this option, but...it sort of doesn't seem to work.

I couldn't find a plausible reason to put `all_probe_columns` into `MarkDistinct` in the first place, but let's assume we can figure this out. Here is what will happen. We start with:

```
- MarkDistinct[all_probe_rows]
  - LeftJoin[...]
    - AssignUniqueId[unique]  
```

Then, `AddExchanges` inserts `RemoteExchange` under the `LeftJoin`:

```
- MarkDistinct[all_probe_rows]
  - LeftJoin[...]
    - RemoteExchange (hash(joinkey))
       - AssignUniqueId[unique]  
```

`partitioned_on(unique)` property no longer propagates to `MarkDistinct` and `AddExchanges` inserts another exchange between `MarkDistinct` and `LeftJoin`:

```
- MarkDistinct[all_probe_rows]
  - RemoteExchange (hash(unique))
    - LeftJoin[...]
      - RemoteExchange (hash(joinkey))
         - AssignUniqueId[unique]  
```

Now, we need to remove the exchange in a rule that runs after `AddExchanges`. We run `PushUpAssignUniqueIdThroughRemoteExchange` to get to:

```
- MarkDistinct[all_probe_rows]
  - RemoteExchange (hash(unique))
    - LeftJoin[...]
       - AssignUniqueId[unique]  
         - RemoteExchange (hash(joinkey))
```

Then, we run a new rule that looks for `MarkDistinct` over `RemoteExchange` with partitioning scheme that's already satisfied for the source of the exchange and remove the exchange:

```
- MarkDistinct[all_probe_rows]
    - LeftJoin[...]
       - AssignUniqueId[unique]  
         - RemoteExchange (hash(joinkey))
```

Then, we run another new rule to drop all but `unique` columns from `MarkDistinct`.

Not impossible, but super complex. Is there any precedent for removing an exchange? Is this safe to do? How can we be sure that extra columns in `MarkDistinct` will be dropped eventually? If they won't we'll be hashing and comparing way more columns than necessary.

I like `JoinNode#enforceSingleMatch` better. 

* It is easy to reason about. 
* Supports more efficient execution: no need to generate `unique` column, no need to accumulate all of `unique` values in memory to produce `is_distinct`.
* Allows for simpler plans for humans to read and CBO to evaluate :-)

**Comment by sopel39** [comment]
> I couldn't find a plausible reason to put all_probe_columns into MarkDistinct in the first place, but let's assume we can figure this out. Here is what will happen. We start with:

Initially `MarkDistinct` was on all probe symbols (in the PR that introduced this correlated subqueries support), but we've later changed it to just be on `unique` as it is more performant.

> partitioned_on(unique) property no longer propagates to MarkDistinct and AddExchanges inserts another exchange between MarkDistinct and LeftJoin:

Since `MarkDistinct` is on all probe rows then `RemoteExchange (hash(joinkey))` is enough to satisfy `MarkDistinct` partitioning requirements (because it provides partitioning for subset of columns).

> Then, we run a new rule that looks for MarkDistinct over RemoteExchange with partitioning scheme that's already satisfied for the source of the exchange and remove the exchange:

This shouldn't be required

> I like JoinNode#enforceSingleMatch better.

Sounds good!

**Comment by mbasmanova** [comment]
@sopel39 Karol, thanks for the corrections. Looks like we don't need to remove an exchange. To make sure I understand this completely, the planning would go like this:

Start with 

```
- MarkDistinct[all_probe_columns]
  - LeftJoin[...]
    - AssignUniqueId[unique]  
```

Then, AddExchanges inserts RemoteExchange under the LeftJoin:

```
- MarkDistinct[all_probe_columns]
  - LeftJoin[...]
    - RemoteExchange (hash(joinkey))
       - AssignUniqueId[unique]  
```

`partitioned_on(unique)` property no longer propagates, but `partitioned_on(joinkey)` does. Hence, `AddExchanges` doesn't insert `RemoteExchange` between `MarkDistinct` and `LeftJoin`. 

Then, `PushUpAssignUniqueIdThroughRemoteExchange` runs:

```
- MarkDistinct[all_probe_columns]
  - LeftJoin[...]
     - AssignUniqueId[unique]  
       - RemoteExchange (hash(joinkey))
```

`AssignUniqueId` now produces `G(unique), C(probe_col1), C(probe_col2),..` local properties which propagate through the left join. A new `MarkDistinct` simplification rule (or changes to `AddLocalExchanges`) prunes distinct symbols to keep only `unique`.

This is not as bad as I originally thought. I still prefer `JoinNode#enforceSingleMatch` for efficiently and simplicity, but happy to be convinced otherwise.

**Comment by sopel39** [comment]
> This is not as bad as I originally thought. I still prefer JoinNode#enforceSingleMatch for efficiently and simplicity, but happy to be convinced otherwise.

For one thing you could use `G(unique), C(probe_col1), C(probe_col2),..` to prune aggregation keys too. However, I'm fine either way

**Comment by mbasmanova** [comment]
> For one thing you could use G(unique), C(probe_col1), C(probe_col2),.. to prune unused aggregation keys too. 

That's true. I can't figure out how to model this in the `AggregationNode` though. Do you have any ideas?

**Comment by kokosing** [comment]
Currently for correlated subqueries you have a filter like `Filter if(is_distint, true, fail('Scalar sub-query has returned multiple rows'))`. 
As I understand with `JoinNode:enforceSingleMatch` you are going to output a boolean symbol that would be `true` if it is first match and `false` otherwise. So it is rather `JoinNode:singleMatchSymbol`, am I right? Or are you going to inject the error message into the join node?

Do you see other options how `JoinNode:enforceSingleMatch` can be used than correlated subqueries?

**Comment by sopel39** [comment]
> I couldn't find a plausible reason to put all_probe_columns into MarkDistinct in the first place

Another reason is that only predicates that contain symbols from `MarkDistinctNode#distinctSymbols` can be pushed down through `MarkDistinct` node.

**Comment by mbasmanova** [comment]
@kokosing 

> Or are you going to inject the error message into the join node?

This is what I was thinking of doing. Do you see any issues with that?

> Do you see other options how JoinNode:enforceSingleMatch can be used than correlated subqueries?

No. That's the only use case I know of.

**Comment by mbasmanova** [comment]
@sopel39 

> Another reason is that only predicates that contain symbols from MarkDistinctNode#distinctSymbols can be pushed down through MarkDistinct node.

I see. Do you have a query where it matters?

**Comment by kokosing** [comment]
@mbasmanova 
>>Or are you going to inject the error message into the join node?

>This is what I was thinking of doing. Do you see any issues with that?

Outputting symbol seems to be more generic to me, it allows use it in more use cases. Because of that I find it more elegant. However, it is hard to reason if we do not see any other use case so far.
