### ISSUE TITLE
Add limit on maximum stages for a query

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#10867]
We should add a `query.max-stages` config property that is similar to `query.max-length` (max query text length) as a sanity check against queries that are unlikely to succeed (they will fail in weird ways or not render in the UI). These massive queries are usually generated as a list of `UNION ALL`, often as the result of users not being aware of `GROUPING SETS` (or `CUBE` / `ROLLUP`).

I'm not sure what a good default would be. `100` seems safe, but might fail some legitimate queries that used to work.

**Comment by codope** [comment]
@electrum This would be a good-to-have property. However, I have one thought. Users may set phased execution policy (say for some unweildy long running join queries). In that case, is 100 a safe max stages value? Should we have different values for different execution polilcies?

**Comment by codope** [comment]
Never mind. I misunderstood the property. I thought it was the max limit that we are going to set. After all, it's a cofigurable property so users can increase/decrease as per their requirements.

**Comment by cnuss** [comment]
I think it would be handy to have these be configurable at the resource group level.

**Comment by svkcemk** [comment]
Hi I just wanted to know what do you mean by query staging or query stages ?like in maxQueryLength you are checking if the current query length is more than the maxQueryLength then you are throwing PrestoException i.e QUERY_TEXT_TOO_LARGE.So, similar for query stages what is your expectation?

**Comment by haozhun** [comment]
Today, I saw a 1052-stage query.

In our cluster, "max-requests-queued-per-destination" is configured to 1000.

Presto coordinator long polls Presto workers for tasks status changes. Therefore, I see no way that a 1000-stage query can finish without hitting `Max requests queued per destination 1000 exceeded for HttpDestination[http://host:port]@4e7537ed,queue=1000,pool=DuplexConnectionPool@2aed66ae[c=250/250,a=250,i=0]` (unless most tasks finish really quickly).

When this happens, not only the query itself get killed, it also brings down other queries running at the same time.

As a result, I think this issue should be prioritized as a reliability fix.
