### ISSUE TITLE
Enable Bing Tile functions for zoom level 0

### ISSUE THREAD

**Issue by jwass** [prestodb/presto#10877]
Currently bing tile functions require zoom levels > 0. 

```
presto> select bing_tile_polygon(bing_tile(0,0,0));
Query 20180620_152255_00001_mptw6 failed: Zoom level must be > 0
```

Are there any objections to enabling zoom level 0 functions? One part of this would be that empty quadkey strings, which are currently forbidden, would be allowed and represent the one tile at zoom 0.

@mbasmanova

**Comment by mbasmanova** [comment]
@jwass What is this useful?

**Comment by jwass** [comment]
One way I wanted to use it is that `geometry_to_bing_tiles` will fail for geometries that go beyond the tile bounds (latitude +/- 85.05...) which I think is the right behavior. To guarantee a geometry can be tiled, I wanted to bootstrap it with `ST_Intersection(geometry, bing_tile_polygon(bing_tile(0,0,0)))` which will clip it to the valid tiling area... that might be useful for other things as well. IMO there's nothing really special about zoom 0 so the current behavior was surprising to me... but that might just be me.

**Comment by mbasmanova** [comment]
@jwass `bing_tile(0,0,0)` should be fine, but I'm not sure it is a good idea to interpret empty string as a quadkey for z0 tile.

**Comment by jwass** [comment]
I agree. Everything would almost just work, we'd just have to change the `> 0`  check on zoom levels to `>= 0`.

We'd have to have a special case to deal for quadkey at zoom 0 and I don't know of a good solution. Some users may be interpreting zoom level from the quad key length and a special case may cause some surprising behavior. Not sure.
