### ISSUE TITLE
Improve ST_ExteriorRing geospatial function error message

### ISSUE THREAD

**Issue by javainthinking** [prestodb/presto#10875]
select ST_asText(ST_ExteriorRing(ST_GeometryFromText('MULTIPOLYGON (((0 0, 4 0, 4 4, 0 4, 0 0), (1 1, 2 1, 2 2, 1 2, 1 1)), ((-1 -1, -1 -2, -2 -2, -2 -1, -1 -1)))')));

message: QueryError{message=com.esri.core.geometry.ogc.OGCMultiPolygon cannot be cast to com.esri.core.geometry.ogc.OGCPolygon, sqlState=null, errorCode=65536, errorName=GENERIC_INTERNAL_ERROR, errorType=INTERNAL_ERROR, errorLocation=null

**Comment by jwass** [comment]
See #10876 

```
presto> select ST_asText(ST_ExteriorRing(ST_GeometryFromText('MULTIPOLYGON (((0 0, 4 0, 4 4, 0 4, 0 0), (1 1, 2 1, 2 2, 1 2, 1 1)), ((-1 -1, -1 -2, -2 -2, -2 -1, -1 -1)))')));
Query 20180620_152136_00000_mptw6 failed: ST_ExteriorRing only applies to POLYGON. Input type is: MULTI_POLYGON
```

@mbasmanova
