### ISSUE TITLE
Support CSV storage format in Hive connector

### ISSUE THREAD

**Issue by mnmami** [prestodb/presto#10905]
I needed to query a CSV file stored in HDFS. The only option seemed to use the TEXTFILE format of Hive connector. I went like that:
`CREATE TABLE hive.default.person (nr INT, country VARCHAR, mbox_sha1sum VARCHAR, name VARCHAR, publishDate DATE, publisher INT) with (format = 'textfile', external_location = 'hdfs://host:54310/person.csv');`

The command looked like worked, but when I  `SELECT * FROM hive.default.person`, I get NULL values everywhere.

First, am I using the connector correctly i.e. to query CSV files? if yes, how to fix the NULL values?

**Comment by findepi** [comment]
For this you would need to define record and field delimiter or, in fact, use a CSV serde (`org.apache.hadoop.hive.serde2.OpenCSVSerde). It's currently not possible to express this when creating a table in Presto. You can create the table in Hive (make sure you can query it), and then you should be able to query it from Presto as well

**Comment by mnmami** [comment]
Any luck this gets enabled from within Presto? I would like to use Presto to query a 'data lake', so incorporating tweaking or touching individual systems is not appropriate.

**Comment by findepi** [comment]
I am not aware of anyone's roadmap containing this, but you can try to implement it yourself (depending on how comfortable you are with this). Have a look into `HiveStorageFormat` class, how JSON serde is handled. If you are able to modify the source & make a custom Presto build, you may be able to get it to work & make a PR.

**Comment by Sugaryou** [comment]
`org.apache.hadoop.hive.serde2.OpenCSVSerde` has a limitation(https://cwiki.apache.org/confluence/display/Hive/CSV+Serde): `This SerDe treats all columns to be of type String. Even if you create a table with non-string column types using this SerDe, the DESCRIBE TABLE output would show string column type. The type information is retrieved from the SerDe. To convert columns to the desired type in a table, you can create a view over the table that does the CAST to the desired type.`  I suggest that use textfile format and add an option to set delimiter. In hive, it is 
```sql
CREATE TABLE xxx(……)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe' 
WITH SERDEPROPERTIES (
  'field.delim'=',',
  'serialization.format'=',')
```

**Comment by mizhou901101** [comment]
> `org.apache.hadoop.hive.serde2.OpenCSVSerde` has a limitation(https://cwiki.apache.org/confluence/display/Hive/CSV+Serde): `This SerDe treats all columns to be of type String. Even if you create a table with non-string column types using this SerDe, the DESCRIBE TABLE output would show string column type. The type information is retrieved from the SerDe. To convert columns to the desired type in a table, you can create a view over the table that does the CAST to the desired type.` I suggest that use textfile format and add an option to set delimiter. In hive, it is
> 
> ```sql
> CREATE TABLE xxx(……)
> ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe' 
> WITH SERDEPROPERTIES (
>   'field.delim'=',',
>   'serialization.format'=',')
> ```
> 
> @kokosing

Thanks a lot this solved my problem.
In my case, I'm using AWS Glue to manually define a table whose storage type is CSV. By default, Glue picked org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat as Output format, and, picked org.apache.hadoop.hive.serde2.OpenCSVSerde as SerDe. I can query correctly with Presto on EMR, but failed to insert into the table. Presto was throwing the error message :

> Query 20190709_093538_00001_4d9k9 failed: Output format org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat with SerDe org.apache.hadoop.hive.serde2.OpenCSVSerde is not supported

Then I went back Glue to replace with org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe and inserting works for me then.

**Comment by isisgoliveira** [comment]
I have the same problem as @mizhou901101. I'm trying to create a table in Glue whose content will come from CSV's stored in S3. I was using output format like '`org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat`' and '`org.apache.hadoop.hive.serde2.OpenCSVSerde`' SerdeInfo and could not perform insert operations, getting the same error : 'HIVE_UNSUPPORTED_FORMAT: Output format org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat with SerDe org.apache.hadoop.hive.serde2.OpenCSVSerde is not supported.'
I tried changing SerdeInfo to `'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe`' and the table is created empty without my CSV content. Also, INSERT INTO also executes, but nothing is inserted.

I thought that would solve my problem, but it got worse :(
