### ISSUE TITLE
 Hive metadata for table <TableName> is invalid: Table descriptor contains duplicate columns 

### ISSUE THREAD

**Issue by jiteshv** [prestodb/presto#10911]

**Comment by kokosing** [comment]
Can share the `SHOW CREATE TABLE` output for this table from Hive?

**Comment by jiteshv** [comment]
Hi Grzegorz,

Thank you for your time.

Please find the details as under:

[cid:image001.png@01D40D5F.0C8A6E40]

Thanks,
Jit
T&O-TS-Mgmt EPC & Soln Svcs
DBS Bank Ltd
Mobile: (65) 90670580
Email: jitesh@dbs.com<mailto:jitesh@dbs.com>

Live More , Bank Less

**Comment by kokosing** [comment]
I am very sorry but I do not see anything except `[cid:image001.png@01D40D5F.0C8A6E40]`.
Can you please copy the text instead of using images?

**Comment by jiteshv** [comment]
Is there any site where I can upload the text?

Thanks,
Jit
T&O-TS-Mgmt EPC & Soln Svcs
DBS Bank Ltd
Mobile: (65) 90670580
Email: jitesh@dbs.com<mailto:jitesh@dbs.com>

Live More , Bank Less

**Comment by kokosing** [comment]
You can use https://gist.github.com/ for example.
