### ISSUE TITLE
Not all attributes of Mongo Collection are reflected in Presto

### ISSUE THREAD

**Issue by hemantvsn** [prestodb/presto#10917]
I'm using PRESTO 0.198 and it connects to underlying Mongo database.
I found that some attributes/columns of Mongo collection are not reflected in Presto

Main collection record
`
db.vessel_port_visits.findOne({fleetId : "59ca77facaee7c2ccbd281a5"})
{
	"_id" : ObjectId("5b16b5279e7964763270f818"),
	"number" : "9456135",
	"exitTimeMillis" : 1326276054000,
	"entryTimeMillis" : 1325980799000,
	"groupIds" : [
		"59ca77facaee7c2ccbd281a5"
	]
}
`

The resultant presto schema is 

`
>> desc mongodb.databaseName.collection

         Column          |   Type    | Extra | Comment 
--------------------------+-----------+-------+---------
 number                | varchar   |       |         
 exittimemillis           | double    |       |         
 entrytimemillis          | double    |       |         
(3 rows)

`

I cannot see the column 'groupIds' which is present in Mongo collection.
1 more thing to note is that groupIds is mostly empty array ie [] in most of the mongo records.

This is causing the queries which include 'groupIds' attribute to fail.
Is there a way to refresh the schema in PRESTO

**Comment by findepi** [comment]
Let me close this in favor of https://github.com/prestodb/presto/issues/10918
