### ISSUE TITLE
Add config property (not session property) to add execution time, and CPU time limits

### ISSUE THREAD

**Issue by raghavsethi** [prestodb/presto#10919]
This would function exactly like the `query_max_cpu_time` and `query_max_execution_time` session properties, but would be set in cluster configuration.

QueryManagerConfig is probably the right class to put these properties into.

**Comment by raghavsethi** [comment]
I'll assign it to myself but you can take that to mean that its yours to work on.

**Comment by sindhugudivada** [comment]
Is this the right place to get started ? https://prestodb.io/presto-admin/docs/current/contributing.html

**Comment by raghavsethi** [comment]
Oh no, that's for presto-admin, not presto. You probably just want our primary README.md

**Comment by codope** [comment]
@raghavsethi I am assuming query_max_run_time will still be a session property because it includes the queueing time as well. 
@sindhugudivada Have you started working on this issue?

**Comment by sindhugudivada** [comment]
@raghavsethi  I m looking into it. I will get back with questions if any.

**Comment by sindhugudivada** [comment]
@raghavsethi  I will update you soon today.

**Comment by ebyhr** [comment]
@raghavsethi QueryManagerConfig already has `query.max-cpu-time` and `query.max-execution-time`. Does this issue indicate same properites?

**Comment by raghavsethi** [comment]
@ebyhr Ah yes, you're right, I missed that before. Thanks!
