### ISSUE TITLE
Implement Spill to Disk for window functions

### ISSUE THREAD

**Issue by atris** [prestodb/presto#10929]
I wanted to check the status of spill-to-disk feature for window aggregates and if there is any interest in getting the feature for Presto.
Is there any near future plans for implementing this?

**Comment by kokosing** [comment]
What a nice coincidence, we talked about it today. There are no concrete plans for this that I would be aware of, but surely we are interested in it.

**Comment by atris** [comment]
@kokosing I would be happy to fire up a proposal for this. Can you point me to the existing implementation for joins and aggregates?

**Comment by kokosing** [comment]
You can start by looking at the usages of `com.facebook.presto.spiller.SpillerFactory`. Also see this: 
 - https://github.com/prestodb/presto/issues/5144
 - https://github.com/prestodb/presto/issues/5897

**Comment by findepi** [comment]
And also https://github.com/prestodb/presto/pull/8946

**Comment by rahul9269** [comment]
This came up today in our team discussion too.
@atris are you still working on it.

**Comment by atris** [comment]
Yes, I am working on this and will be posting a design proposal soon

**Comment by atris** [comment]
Should we resolve this?

**Comment by findepi** [comment]
I will take care of this.
