### ISSUE TITLE
select * from  xxxxx limit  300000 splits blocked

### ISSUE THREAD

**Issue by jackyfreezer007** [prestodb/presto#10925]
sql
```
select * from tmp.test  limit 300000
```
the table tmp.test has more then 80000000 lines

the query hang up
![snip20180627_28](https://user-images.githubusercontent.com/19622812/41966101-ddf15dac-7a30-11e8-82e6-08346411a89e.png)

**Comment by dain** [comment]
There is 32.1 MB of data in the output buffer.  The client should be reading data from this buffer to free up space.

**Comment by jackyfreezer007** [comment]
@dain thank you for your reply .Do you know how to slove this problem?

**Comment by dain** [comment]
The client should be reading data from the server.  What client are you using?
