### ISSUE TITLE
Writing to Hive table with ORC Bloom filter table-level properties creates ORC files without a bloom filter

### ISSUE THREAD

**Issue by sm186011** [prestodb/presto#10944]
Hi, I have two external tables, one with empty ORC table and other with CSV files, both tables pointing to s3 location.  I added table properties with bloom filter columns to orc table. 

After this, I did an insert-select to load the data from csv table to orc table.  I got the ORC files . After this I checked the ORC files using hive --orcdumptool . I didn't find any bloomfilter keyword in the output.  Does presto ignore the orc bloom filter property while loading the data using insert-select

**Comment by findepi** [comment]
see https://github.com/prestodb/presto/issues/7120

**Comment by avnersentinelone** [comment]
I've experienced same thing too on 0.214 using optimized orc writer (not optimized writer actually save bloom filter stream)
