### ISSUE TITLE
Misleading variable name: hasOrderBy

### ISSUE THREAD

**Issue by xumingming** [prestodb/presto#10949]
I was reading the presto code, find that the following `hasOrderBy` seems misleading, a correct name should be `notHasOrderBy`?
https://github.com/prestodb/presto/blob/c50646eb3b56d0bca1bab5e3a06f23d5a551343b/presto-main/src/main/java/com/facebook/presto/sql/planner/plan/AggregationNode.java#L73-L76

**Comment by kokosing** [comment]
The name is correct, it should rather `anyMatch` instead of `noneMatch` at the end. Can you post a PR with fix for that?

**Comment by xumingming** [comment]
sure

**Comment by xumingming** [comment]
hi @kokosing, after a second thought I still think the logic seems right, the variable name is wrong, especially from the error message:

https://github.com/prestodb/presto/blob/c50646eb3b56d0bca1bab5e3a06f23d5a551343b/presto-main/src/main/java/com/facebook/presto/sql/planner/plan/AggregationNode.java#L77

The message "ORDER BY does not support distributed aggregation" will pop up when:

```java
!hasOrderBy  // this should produce a result that this statement contains a ORDER BY?
&&
step != SINGLE // this means it is a distributed aggregation?
```
So I think the above `!hasOrderBy` should be replaced by `!notHasOrderBy`, hence the naming of `hasOrderBy` should be renamed to `notHasOrderBy` to match the error message and semantics.

**Comment by kokosing** [comment]
You are right

**Comment by kokosing** [comment]
Fixed
