### ISSUE TITLE
Adding a session property containing comma breaks the client

### ISSUE THREAD

**Issue by jBugReport** [prestodb/presto#10954]
Error message:
```
returned an invalid response: JsonResponse{statusCode=400, statusMessage=Bad Request, headers={content-length=[31], content-type=[text/plain], date=[...]}, hasValue=false} [Error: Invalid X-Presto-Session header]
```
To reproduce this problem you can run:
`set session A_SESSION_PROP='a,b';`
No more command will be run after this point.

It happens only when suggested session variable value contains comma (`,`).
This causes client to not execute any more command. Even you cannot not execute `RESET SESSION` command and you have to close the client and start again.

**Comment by findepi** [comment]
@electrum do you know, is it protocol's or client's fault?

**Comment by jBugReport** [comment]
This is a server/design issue.
Presto server accepts multiple `X-Presto-Session` headers. Java client send each session variable with one `X-Presto-Session` header line. However, Presto server is designed to accept multiple session variables in one `X-Presto-Session` header line as well. These variables are splitted naively by comma. This causes problem when session variable has comma inside.
One solution would be to disallow multiple session variable in one `X-Presto-Session` and remove splitting. The second one maybe is to use skip character during splitting so that someone can send a comma using `\,` for example.

**Comment by jBugReport** [comment]
I found this issue as a duplicate of:
https://github.com/prestodb/presto/issues/5169
