### ISSUE TITLE
Add elasticsearch connector

### ISSUE THREAD

**Issue by harbby** [prestodb/presto#10975]
Add connector to elasticsearch.

It supports

Querying a elasticsearch table with full support of Kudu scanner predicates and elasticsearch partitionings/splits
Inserting.
For powerful pushdown capabilities, you can take advantage of elasticsearch search and presto computing power

see: https://github.com/harbby/presto-runners/tree/master/presto-elasticsearch
If I can, I will create a PR and maintain her for a long time.

**Comment by findepi** [comment]
for the record, follow-up: https://github.com/prestodb/presto/pull/9459, https://github.com/prestodb/presto/pull/10999
