### ISSUE TITLE
Name based struct field mapping for ORC files

### ISSUE THREAD

**Issue by shreyasjoshis** [prestodb/presto#11001]
## Summary

Currently fields in structs are mapped to the underlying data based on the ordinal of the data field. This approach does not work in the case where the table schema changes to drop a field from the struct that is not the last field. Currently, such a change will cause all fields following the dropped field to be mis-aligned. 

### Current behavior
Consider the case of a struct `<a string, b string, c string>` being changed to `<a string, c string, d string>`. 
* The data of the deleted column `b` will be assigned to column `c`.
* The data from column `c` from the files which have data for column `b` will be assigned to column `d`.

### Desired behavior
* Data in the deleted column `b` should be ignored. 
* Column `c` should be  read correctly from files written before and after the schema change. 
* Column `d` should be null when reading files prior to the schema change and should be read in correctly from  the files written after  the schema change.

## Proposal

Similar to the `hive.orc.use-column-names` property, create a `hive.orc.use-struct-field-names` that maps to the underlying data based on field names rather than the position.

**Comment by dain** [comment]
What is the default behavior in Hive?

**Comment by shreyasjoshis** [comment]
> What is the default behavior in Hive?

The desired behavior is the default behavior in Hive. Here is an example:

**Create table**
```sql
DROP TABLE test_schema.test_tbl;
CREATE EXTERNAL TABLE `test_schema.test_tbl`(
`a` struct<f1:STRING, f2:STRING, f3:STRING >)
ROW FORMAT SERDE
'org.apache.hadoop.hive.ql.io.orc.OrcSerde'
STORED AS INPUTFORMAT
'org.apache.hadoop.hive.ql.io.orc.OrcInputFormat'
OUTPUTFORMAT
'org.apache.hadoop.hive.ql.io.orc.OrcOutputFormat';
```
**Insert data**
```sql
INSERT INTO test_schema.test_tbl SELECT named_struct('f1', 'f1val', 'f2', 'f2val', 'f3', 'f3val');
```

**Drop struct field f2**
```sql
DROP TABLE test_schema.test_tbl;
CREATE EXTERNAL TABLE `test_schema.test_tbl`(
`a` struct<f1:STRING, f3:STRING >)
ROW FORMAT SERDE
'org.apache.hadoop.hive.ql.io.orc.OrcSerde'
STORED AS INPUTFORMAT
'org.apache.hadoop.hive.ql.io.orc.OrcInputFormat'
OUTPUTFORMAT
'org.apache.hadoop.hive.ql.io.orc.OrcOutputFormat';
```

**Presto output**
Presto misinterprets the value of the deleted field `f2`  as the value for field `f3`

```sql
presto> select * from hive.test_schema.test_tbl;
          a
----------------------
 {f1=f1val, f3=f2val}
(1 row)
```

**Hive output**

Hive correctly ignores the deleted value and reports the value for field `f3` correctly.

```sql
hive> select * from test_schema.test_tbl;
{"f1":"f1val","f3":"f3val"}
```

**Comment by findepi** [comment]
@shreyasjoshis is Hive's behavior the same for Parquet?

> Similar to the `hive.orc.use-column-names` property, create a `hive.orc.use-struct-field-names` that maps to the underlying data based on field names rather than the position. 

Since this looks the same in Parquet, IMO we should have parallel properties for Parquet and ORC.

**Comment by findepi** [comment]
Related to: https://github.com/prestodb/presto/issues/10941, https://github.com/prestodb/presto/pull/10943

**Comment by shreyasjoshis** [comment]
> @shreyasjoshis is Hive's behavior the same for Parquet?

Yes Hive's behavior is the same for Parquet. Actually Presto already reads the fields correctly as well.


**Create table**

```sql
DROP TABLE test_schema.test_tbl;

CREATE EXTERNAL TABLE `test_schema.test_tbl`(
`a` struct<f1:STRING, f2:STRING, f3:STRING >)
STORED AS PARQUET;
```

**Insert data:**
```sql
INSERT INTO test_schema.test_tbl SELECT named_struct('f1', 'f1val', 'f2', 'f2val', 'f3', 'f3val');
```

**Drop struct field:**
```sql
DROP TABLE test_schema.test_tbl;

CREATE EXTERNAL TABLE `test_schema.test_tbl`(
`a` struct<f1:STRING, f3:STRING >)
STORED AS PARQUET;
```

**Current Presto output:**
```sql
presto> select * from hive.test_schema.test_tbl;
          a
----------------------
 {f1=f1val, f3=f3val}
(1 row)
```
**Hive output:**
```sql
hive> select * from test_schema.test_tbl;
{"f1":"f1val","f3":"f3val"}
```

**Comment by dain** [comment]
If the current behavior is not consistent with Hive, then this is a bug and not a feature request.

**Comment by dain** [comment]
@shreyasjoshis can you rewrite the description in the form of a bug report instead of a feature request?

**Comment by dain** [comment]
Oh wait, I see what you are doing.  Please repeat the experiment with the text format instead of Parquet. The Hive people added custom rules for Parquet which are not consistent with other formats.

**Comment by dain** [comment]
Also can you repeat the experiment with a Partitioned table.  You create the table with a partition and then change the column type of the table (and not the partition).

**Comment by shreyasjoshis** [comment]
Here's the experiment with a partitioned text file backed table. The key takeaway is that Hive does not map the struct values correctly.

**Create the table:**
```sql
DROP TABLE shreyasjoshis_test.test_tbl;

CREATE EXTERNAL TABLE `shreyasjoshis_test.test_tbl`(
`a` struct<f1:STRING, f2:STRING, f3:STRING >)
PARTITIONED BY (p STRING )
STORED AS TEXTFILE;
```

**Insert data:**

```sql
INSERT INTO shreyasjoshis_test.test_tbl
PARTITION (p='p1') SELECT named_struct('f1', 'f1val', 'f2', 'f2val', 'f3', 'f3val');
```

**Drop struct field from the table and not from the partition:**
```sql
SET hive.metastore.disallow.incompatible.col.type.changes=false;
ALTER TABLE `shreyasjoshis_test.test_tbl` REPLACE COLUMNS (`a` struct<f1:STRING, f3:STRING >);
```

**Hive output:**
```sql
hive> select * from shreyasjoshis_test.test_tbl;
OK
{"f1":"f1val","f3":"f2val"}	p1
```

**Presto output:**
```
Query 20180710_221254_07970_cgja2 failed: There is a mismatch between the table and partition schemas. The types are incompatible and cannot be coerced. The column 'a' in table 'shreyasjoshis_test.test_tbl' is declared as type 'struct<f1:string,f3:string>', but partition 'p=p1' declared column 'a' as type 'struct<f1:string,f2:string,f3:string>'.
```

**Comment by dain** [comment]
@shreyasjoshis so this is another form of implicit coercion at the partition->file level similar to #10943.  Since the behavior is different from Hive, we I'll mark this as a bug, and we should just change the behavior without a config flag.

**Comment by shreyasjoshis** [comment]
I'm going to pick this up, so I'll assign it to myself
