### ISSUE TITLE
All queries goes to queued state after executing heavy query in presto 0.198

### ISSUE THREAD

**Issue by sadeshjayraj** [prestodb/presto#11016]
Hi,
I am running heavy query on presto server 0.198. Meanwhile I am trying to execute new queries but all queries goes in queued status. 

All queries will get completed once heavy query execution get completed.

Why this is happening, though I am running heavy query it should allow another to run and get completed.

Regards,
Sadesh

**Comment by findepi** [comment]
Please see https://github.com/prestodb/presto/issues/10383#issuecomment-395722756 . Could you please retry with latest version and report new issue if the problem persists?
