### ISSUE TITLE
Do not require GRANT_SELECT if user has a SELECT privilege to table

### ISSUE THREAD

**Issue by kokosing** [prestodb/presto#11015]
The case:
 - users `A` and `B` has `SELECT` privilege to table `t`
 - user `A` creates view `v` that selects from `t`
 - user `B` has `SELECT` privilege to view `v`

Now, user `B` is unable to select from `v` because user `A` does not have `GRANT_SELECT` for `v` and so `B` is unable to read from `t` via `v` even though it has `SELECT` for `t`.

Is this a bug or feature? I still need to take a look into the spec.

To me `GRANT_SELECT` is useful when `B` would not have `SELECT` privilege for `t`, but here it sounds strange that it is required.

**Comment by dain** [comment]
We have been discussing this internally for a long time.  IIRC the current behavior is the specification defined behavior.  Specifically, a view is executed with the permissions of the owner of the view, and specifically with no rights inherited from the invoker.  

As an alternative to this model, we have discussed adding an extension for "execute as invoker".  This is similar to the Transact SQL execute as clause for stored procedures (https://docs.microsoft.com/en-us/sql/t-sql/statements/execute-as-clause-transact-sql?view=sql-server-2017).  

cc @electrum

**Comment by kokosing** [comment]
Thanks for reply. As long it is in line with the spec I am ok (but not happy) with this. 

Suggested extensions sounds interesting. Let's back to this once it becomes a bigger problem.
