### ISSUE TITLE
Supporting geospatial computation on different SRID

### ISSUE THREAD

**Issue by qqibrow** [prestodb/presto#11022]
@mbasmanova shall we support st_transform or add constructor to support computation on different SRID? similar to  postgis? https://postgis.net/docs/ST_Area.html  thanks!

**Comment by mbasmanova** [comment]
@qqibrow Would you share some more context for this question? What are you trying to achieve?

**Comment by mwkorver** [comment]
This would allow those with data in geographic to first transform to geometry before using functions such as buffer etc. where you typically want to use meter for radius.

**Comment by mbasmanova** [comment]
@mwkorver Mark, `ST_Buffer` use case did come up a few times. Do you have some ideas of how you would implement the `ST_Transform` and which spatial references it would support? I imagine that without changes to `ST_Buffer`, only spatial references that project on a plane would work.

Could you share any specific use cases for `ST_Buffer`? I've seen cases where it would be used in distance-within queries: 

```
SELECT *
FROM t, u
WHERE ST_Contains(t.geometry, ST_Buffer(u.geometry, radius))
```

For such queries, it is more efficient to use `ST_Distance`:

```
SELECT *
FROM t, u
WHERE ST_Distance(t.geometry, u.geometry) <= radius
```

I want to enable spatial joins for `great_circle_distance` which will allow to write distance-within-meters queries easily:

```
SELECT *
FROM t, u
WHERE great_circle_distance(t.lat, t.lon, u.lat, u.lon) <= radius
```

Also, @gaoxm is adding support for computations on a sphere (in meters): #11581 

CC: @jagill

**Comment by mwkorver** [comment]
@mbasmanova Buffer is useful to create some arbitrary area based on either a point or other geometry to run an ST_Contains on. Find all of the homes along some route, or all of the homes potentially impacted by a flood (river). My suggestion for implementing ST_Transform is to use Proj4. https://www.osgeo.org/projects/proj4/ there is Java port used on projects such as Geotrellis at https://trac.osgeo.org/proj4j/

**Comment by mbasmanova** [comment]
@mwkorver Most of the use cases operate on local geometries and therefore can be implemented using existing functions:

```
WITH road (
   SELECT ST_GeometryFromText('LINESTRING ...') as road_geometry
),
road_with_center(
    SELECT road_geometry, ST_Y(ST_Centroid(ST_Envelope(road_geometry))) as road_center_latitude
)
SELECT ...
FROM t
WHERE ST_Distance(ST_Point(t.longitude, t.latitude), road_geometry) <= distance_in_meters / (111195 * cos(radians(road_center_latitude)))
```

Of course, this is quite verbose and cumbersome and it would be nice to improve this syntax.

Furthermore, @gaoxm's work on SphericalGeometry will simplify these cases even further:

```
WITH road (
   SELECT ST_GeometryFromText('LINESTRING ...') as road_geometry
)
SELECT ...
FROM t
WHERE ST_Distance(to_spherical_geometry(ST_Point(t.longitude, t.latitude)), to_spherical_geometry(road_geometry)) <= distance_in_meters
```

What do you think? Would that be sufficient? If not, I feel that the effort to add support for projections would be substantial. Would you like to start a design document and/or a prototype? It might be useful to consider other libraries that offer that functionality, e.g. http://docs.geotools.org/stable/userguide/library/referencing/crs.html used by GeoSpark. Let me know.

**Comment by cvargas-geo** [comment]
This is really useful for geospatial processing, I've been having a problem in aws athena where it doesn't create consistent buffers across the globe because decimal degrees change with respect to latitude and longitude, this feature would really be appreciated

**Comment by cvargas-geo** [comment]
> distance_in_meters / (111195 * cos(radians(road_center_latitude))

Wow, this formula is very good to estimate my buffers without reference of meters !!!!! Although the shape is an elongated ellipse from south to north, it is much better than it was before!
