### ISSUE TITLE
How to downgrade presto server

### ISSUE THREAD

**Issue by sadeshjayraj** [prestodb/presto#11020]
Hello all,

Currently I am using 8 node presto cluster server,1- Coordinator and 7 workers.
Current presto version is 0.198.

I want to downgrade cluster server from 0.198 to 0.197.

Help me to know what are the pre-requisite and steps for cluster server upgrade, is it possible to do rolling upgrade.

Regards,

Sadesh Jayraj

**Comment by findepi** [comment]
Since Presto doesn't have internal mutable state, you can just replace your cluster with a different one, with different configuration.
Rolling upgrades are not supported. If you need to do rolling upgrades, you need 2 presto clusters and a load balancer at front.

**Comment by haozhun** [comment]
This is true as long as you don't use Raptor.
