### ISSUE TITLE
Support for IBM Power Series - LE platform

### ISSUE THREAD

**Issue by Ravion** [prestodb/presto#11027]
This is to enable presto to work on Power series. Already verified that Power series is LE (Little Endian). Hence the enforcement in PrestoServer code  ( code which asserts for X86 or AMD ) can be removed or can add PPC64LE ( Power series).
Also corresponding native Hadoop binaries need to be incorporated.

Best,
Ravi Shankar

**Comment by findepi** [comment]
There is already a PR for this https://github.com/prestodb/presto/pull/11006

**Comment by Ravion** [comment]
Tested and closed..
