### ISSUE TITLE
Add feature toggle that disables usage of parent preferred properties in AddExchanges 

### ISSUE THREAD

**Issue by sopel39** [prestodb/presto#11025]
This comes from user use case. Take a query for instance:
```
SELECT x, max(y)
FROM 
(SELECT x,y FROM a
 EXCEPT
 SELECT x,y FROM b)
GROUP BY x
```
Without `GROUP BY x` `EXCEPT` gets rewritten to aggregation over `x,y`, e.g:
```
- Project(first_source_symbols)
  - Filter(count_first_source > 0 && count_second_source == 0)
    - Aggregation[x,y](count(first_source_marker), count(second_source_marker))
      - Exchange[HASH][x,y]
        - first source
        - second source
```
However, because there is `GROUP BY x` the whole query will get rewritten to:
```
- Aggregation[x](...)
  - Project(first_source_symbols)
    - Filter(count_first_source > 0 && count_second_source == 0)
      - Aggregation[x,y](count(first_source_marker), count(second_source_marker))
        - Exchange[HASH][x]
          - first source
          - second source
```

The problem comes when `y` is skewed with respect to `x` (e.g: there is one `x` value for which number of distinct `y` values is unevenly large). This will cause  `- Aggregation[x,y]` to fail because of `query exceeds local node memory limit`.

We could solve this in two ways:
1. We could have some kind of correlation info with skewness, this is difficult though and could be addressed in long term
2. We could provide a session feature toggle to disable usage of parent preffered parittioning in `AddExchanges`. This could be a short term solution.

What do you think? @martint @findepi @kokosing @mbasmanova

**Comment by findepi** [comment]
> 2. We could provide a session feature toggle to disable usage of parent preffered parittioning in `AddExchanges`. This could be a short term solution.

Can you express this in a feature-oriented way?

**Comment by mbasmanova** [comment]
@sopel39 Karol, could you explain some more how/why `Exchange[HASH][x,y]` becomes `Exchange[HASH][x]`?

> a session feature toggle to disable usage of parent preffered parittioning in AddExchanges

My first thought is that it would be very hard to reason about how this flag affects the planning.

**Comment by sopel39** [comment]
> Can you express this in a feature-oriented way?

Basically the flag would explicitly insert HASH exchange for the symbols required by operator even if dowsntream operator require partitioning on subset of symbols.

> Karol, could you explain some more how/why Exchange[HASH][x,y] becomes Exchange[HASH][x]?

1. `Aggregation[x,y]` requires partitioning on `x,y`
2. `Aggregation[x]` requires partitioning on `x`
3. partitioning on `x` satisfied partitioning on `x,y`. 
3. `Aggregation[x,y]` utilizes parent required partitioning preference (partitioning on `x`) to avoid reshuffle.

> My first thought is that it would be very hard to reason about how this flag affects the planning.

This flag would be `false` by default and used only if queries start to fail with out of memory

**Comment by kokosing** [comment]
> Aggregation[x,y] requires partitioning on x,y
Aggregation[x] requires partitioning on x
partitioning on x satisfied partitioning on x,y.
Aggregation[x,y] utilizes parent required partitioning preference (partitioning on x) to avoid reshuffle.

Would it be possible to over partition the source with `x,y` partitioning this case? This way we would also avoid repartitioning.

**Comment by sopel39** [comment]
> Would it be possible to over partition the source with x,y partitioning this case? This way we would also avoid repartitioning.

Partitioning by `x,y` does not satisfy partitioning by `x`.
e.g: you can have data:
```
x|y
a|2
a|3
```
If you partition by `x,y` then `a` rows might land on different machines
