### ISSUE TITLE
Increase in query planning time

### ISSUE THREAD

**Issue by Praveen2112** [prestodb/presto#11024]
Hi, 
After this patch(#10994) was applied I just compared the planning time between latest presto(with the patch applied) and presto 0.149 and planning time in the latest version of Presto is still higher than Presto 0.149. So we tracked and found some changes that might speed up Presto planning time.

1. Removing `ValidateDependenciesChecker` from checker list when validating intermediate plan. 
This checker consumes more time for queries which have more number of joins involving wide table. The `TableScanNode` in a `RelationPlan` will have all the columns present in the table and the `JoinNode` will just consider all the symbols from the left and right relation even though a part of those columns are required in the query, this leads to increase in time. Moreover the `Analyzer` and `RelationPlanner` ensures that the dependencies are matched so adding this check to the intermediate plan might increase the query time.

2. Currently `InPredicate` can be serialized to `TupleDomain` only if the `InPredicate#getValue` is either a `SymbolReference` or a `Cast` but when converting a `InPredicate` to `TupleDomain` we don't check the type of `InPredicate#getValue` rather we extract it to `OrExpression` and when processing `OrExpression` we convert them to `TupleDomain.all` if `InPredicate#getValue` is a `FunctionCall` or a `AtTimeZone`. This might increase the time taken for `DomainTranslator.fromPredicate` so we change from

```            
if (!(node.getValueList() instanceof InListExpression)){ 
   return super.visitInPredicate(node, complement);
}
```
to 

```            
if (!(node.getValueList() instanceof InListExpression) ||(hasOnlySymbolReference(node.getValue()))){ 
   return super.visitInPredicate(node, complement);
}

private boolean hasOnlySymbolReference(Expression expression)
{
     if (expression instanceof Cast) {
         return hasOnlySymbolReference(((Cast) expression).getExpression());
     }
    else
        return expression instanceof SymbolReference;
}

```

Would there be any issues in implementing these for optimizing the planning time.

**Comment by kokosing** [comment]
AD. 1. This is very important validation. Especially when the new feature comes in it is typical this validation finds bugs around this feature. Is there any way to make it faster instead of removing?

AD. 2. Can you please post a PR with this change?

**Comment by Praveen2112** [comment]
@kokosing Thanks for the reply.

> AD. 1. This is very important validation. Especially when the new feature comes in it is typical this validation finds bugs around this feature. Is there any way to make it faster instead of removing?

If that is the requirement then we can have two separate implementation of `PlanSanityChecker.Checker`  for validating the dependencies. The `ValidateDependenciesChecker` can be used for validating the **final plan** and for validating the **intermediate plan** we can have another implementation which might have some short cuts to validate the dependencies like

a. We can skip the validation check for `TableScanNode` because from the `RelationPlanner` we get the `TableScanNode` which contains all the columns in that given table.

b. We can skip the validation check for JoinNode if this condition satisfies 
`JoinNode#getOutputSymbols#size =  JoinNode#getLeft#getOutputSymbols#size + JoinNode#getRight#getOutputSymbols#size`

Currently validating these two nodes are bit high when validating **intermediate** plan.


> AD. 2. Can you please post a PR with this change?

Yes I will post a PR with that change.
`

**Comment by kokosing** [comment]
AD. 1. Lets keep this as a last resort option, is there any way to optimize
that?

**Comment by Praveen2112** [comment]
One optimization that we can apply for `ValidateDependenciesChecker` is we can skip validating the `TableScanNode` because the same validation will be applied when we create a new `TableScanNode`.

**Comment by kokosing** [comment]
Great idea, would you like to create a PR with this or I should? Also one
can say that this dependency check for table scan node is not needed at all
because table scan node is a leaf of the plan and so does not have any
dependencies.

**Comment by Praveen2112** [comment]
Okay. I will create a PR for this change. And how about adding a new check for validating dependencies of an intermediate plan ?

**Comment by kokosing** [comment]
It looks like JoinNode is checking dependencies in the constructor as well. Have you noticed that during profiling?

**Comment by kokosing** [comment]
Please open for this a separate PR.

**Comment by kokosing** [comment]
But about profiling, did you notice that JoinNode constructor is also a problem?

**Comment by Praveen2112** [comment]
One of the previous version of JoinNode has a check like this
`checkArgument(inputSymbols.containsAll(outputSymbols), "Left and right join inputs do not contain all output symbols")` 
which increased the planning time but replacing with 

`checkArgument(new HashSet<>(inputSymbols).containsAll(outputSymbols), "Left and right join inputs do not contain all output symbols")`
doesn't show much of a performance difference.

Moreover removing the check for `TableScanNode` and for `JoinNode` didn't gave much of a difference. The main part of the validation code which takes more time for join is 

```          
List<Integer> rightSymbolIndexes = node.getRight().getOutputSymbols().stream()
    .filter(symbol -> node.getOutputSymbols().contains(symbol))
    .map(symbol -> node.getOutputSymbols().indexOf(symbol))
    .collect(toImmutableList());

boolean allLeftBeforeRight = node.getLeft().getOutputSymbols().stream()
    .filter(symbol -> node.getOutputSymbols().contains(symbol))
    .map(symbol -> node.getOutputSymbols().indexOf(symbol))
    .allMatch(leftIndex -> rightSymbolIndexes.stream()
        .allMatch(rightIndex -> rightIndex > leftIndex));
```

If we could just check the index of the first symbol from the right relation and the last symbol from the left relation and make sure that all left symbols are before right.

**Comment by kokosing** [comment]
> If we could just check the index of the first symbol from the right relation and the last symbol from the left relation and make sure that all left symbols are before right.

That sounds good to me.

**Comment by Praveen2112** [comment]
@kokosing  Can we replace the current validation code 

```
List<Integer> rightSymbolIndexes = node.getRight().getOutputSymbols().stream()
    .filter(symbol -> node.getOutputSymbols().contains(symbol))
    .map(symbol -> node.getOutputSymbols().indexOf(symbol))
    .collect(toImmutableList());

boolean allLeftBeforeRight = node.getLeft().getOutputSymbols().stream()
    .filter(symbol -> node.getOutputSymbols().contains(symbol))
    .map(symbol -> node.getOutputSymbols().indexOf(symbol))
    .allMatch(leftIndex -> rightSymbolIndexes.stream()
        .allMatch(rightIndex -> rightIndex > leftIndex));
```

With this implementation

```
Optional<Integer> lastLeftSymbolIndex = Optional.empty();
Optional<Integer> firstRightSymbolIndex = Optional.empty();
    if (node.getLeft().getOutputSymbols().size() < node.getRight().getOutputSymbols().size()) {
        lastLeftSymbolIndex = node.getLeft().getOutputSymbols().stream()
            .map(symbol -> node.getOutputSymbols().indexOf(symbol))
            .filter(index -> index >= 0)
            .reduce(BinaryOperator.maxBy(Integer::compareTo));
    }
    else {
        firstRightSymbolIndex = node.getRight().getOutputSymbols().stream()
            .map(symbol -> node.getOutputSymbols().indexOf(symbol))
            .filter(index -> index >= 0)
            .reduce(BinaryOperator.minBy(Integer::compareTo));
     }
            
    if (node.getOutputSymbols().size() == (node.getLeft().getOutputSymbols().size() + node.getRight().getOutputSymbols().size())) {
        if (lastLeftSymbolIndex.isPresent()) {
            checkState(node.getLeft().getOutputSymbols().size() == lastLeftSymbolIndex.get() + 1, "Not all left output symbols are before right output symbols");
         }
         else {
             checkState(node.getLeft().getOutputSymbols().size() == firstRightSymbolIndex.get(), "Not all left output symbols are before right output symbols");
          }
    }
    else {
        if (lastLeftSymbolIndex.isPresent()) {
            firstRightSymbolIndex = node.getRight().getOutputSymbols().stream()
                .map(symbol -> node.getOutputSymbols().indexOf(symbol))
                .filter(index -> index >= 0)
                .reduce(BinaryOperator.minBy(Integer::compareTo));
         }
         else {
             lastLeftSymbolIndex = node.getLeft().getOutputSymbols().stream()
                  .map(symbol -> node.getOutputSymbols().indexOf(symbol))
                  .filter(index -> index >= 0)
                  .reduce(BinaryOperator.maxBy(Integer::compareTo));
         }
         if (firstRightSymbolIndex.isPresent() && lastLeftSymbolIndex.isPresent()) {
                    boolean allLeftBeforeRight = lastLeftSymbolIndex.get() < firstRightSymbolIndex.get();
                    checkState(allLeftBeforeRight, "Not all left output symbols are before right output symbols");
          }
    }
```

**Comment by Praveen2112** [comment]
Okay :+1:
