### ISSUE TITLE
Dynamic loading Udfs？

### ISSUE THREAD

**Issue by imperio-wxm** [prestodb/presto#11038]
Now I write my own presto-udfs.jar.

In order to load my udfs to presto cluster, I must to `restart` all nodes. 
There is any way that I can load udf‘s jar when each node `still working`?

**Comment by dain** [comment]
There is currently no way to do that.  Implementing something that can dynamically load a plugin, wouldn't be too hard, but unloading a plugin would take a ton of work.  For Presto, we want every create to have a matched drop command, so this is the major blocker.  Also, functions currently live in a single global namespace, so you could never update your functions either.

**Comment by imperio-wxm** [comment]
@dain 

Hi, there is a problem now.
I want to add a new udf function to the production cluster. In order not to affect the online business, I have to restart node one by one. 

However when I restart a node that already has a query, this query will fail,this is intolerable.

Presto is not like MapReduce, some nodes fail to be reassigned to other nodes to recalculate.
How to get online a new udf function while ensuring uninterrupted queries.

**Comment by findepi** [comment]
> However when I restart a node that already has a query, this query will fail,this is intolerable.

@imperio-wxm you can decommission a node gracefully, see https://prestodb.io/docs/current/release/release-0.128.html

**Comment by dain** [comment]
How often are you adding UDFs?  We rarely add the and do this during normal downtimes for upgrades.

**Comment by hwb1992** [comment]
Udf should register in coordinator and worker.If i want to add a new udf, i should restart coordinator.But,it will affect query!

**Comment by Jay-ju** [comment]
> There is currently no way to do that. Implementing something that can dynamically load a plugin, wouldn't be too hard, but unloading a plugin would take a ton of work. For Presto, we want every create to have a matched drop command, so this is the major blocker. Also, functions currently live in a single global namespace, so you could never update your functions either.

why  is it difficult for unloading plugin? if just for udfs, we only need drop function ? any else other work? another question global namespace will bring some transaction problems？ so we can't update functions?

**Comment by hackeryang** [comment]
> > There is currently no way to do that. Implementing something that can dynamically load a plugin, wouldn't be too hard, but unloading a plugin would take a ton of work. For Presto, we want every create to have a matched drop command, so this is the major blocker. Also, functions currently live in a single global namespace, so you could never update your functions either.
> 
> why is it difficult for unloading plugin? if just for udfs, we only need drop function ? any else other work? another question global namespace will bring some transaction problems？ so we can't update functions?

Here is a video about dynamic udf, may be we can refer to the design about it: https://www.youtube.com/watch?v=hd12u-JtEHg
