### ISSUE TITLE
count(*)  function in 0.204/0.205 return error numbers !

### ISSUE THREAD

**Issue by xingnailu** [prestodb/presto#11034]
hi~ I have a EXTERNAL table in hive cluster.  and my query like :
```
    select count(*) from Table1  where p_day ='2018-07-10' and source = 'columnContext' limit 2000; 
```

when I update the  presto cluster to 0.204 , it return 2000+, but the really  number is 2w+ (at presto 0.192 before I do this update), I verify this query in hive cluster， also return 2w+

**Comment by xingnailu** [comment]
I replace the query with : 
select source, count(*) from table1 where p_day = '2018-07-10' and source like 'columnContext%' group by source limit 2000;
    it work well。

**Comment by findepi** [comment]
i am happy that you found a solution
