### ISSUE TITLE
Test Question -- Setting a Session Parameter In a Unit Test?

### ISSUE THREAD

**Issue by atris** [prestodb/presto#11039]
What is the best way to set a session parameter to disable a config before running a unit test? I am looking to disable a planner optimizer during a test run.

**Comment by dain** [comment]
Typically the thing you are testing needs a `Session`.  Normally, you can build this with `TestingSession.testSessionBuilder()`, and the returned builder has methods to set session properties.

**Comment by atris** [comment]
Thanks!
