### ISSUE TITLE
Loading CSV data

### ISSUE THREAD

**Issue by mundlapudi** [prestodb/presto#11055]
Hi Presto Team,

I have a standalong Presto Cluster and also a CSV file on a NAS storage. How can I load data into Presto? I saw example-http connector, can someone please point me to a document to load data from a file into PrestoDB? 

Note: I don't use Hadoop Cluster here

**Comment by findepi** [comment]
There is no tool dedicated for Presto that I am aware of.
You should be able to use some generic "CSV to SQL INSERTS" conversion tool (i found some online tool https://codebeautify.org/csv-to-sql-converter, but offline do exist as well, like sqoop).

HTH
