### ISSUE TITLE
Exception: javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)];

### ISSUE THREAD

**Issue by sadeshjayraj** [prestodb/presto#11058]
Hello All,

I am using PRESTO version o.198 .I am trying to execute query from presto CLI, but frequently I am facing below given  error. Same query configuration was working from last 2 month.But after server restart we are facing this issue.

Caused by: org.ietf.jgss.GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)

com.facebook.presto.spi.PrestoException: Failed to list directory

Please suggest.

**Comment by kokosing** [comment]
IIRC I got this error when I had something misconfigured related to Kerberos. Please check if paths are in configuration are correct, if files have proper permissions set, if keytab file is still valid, if principal used is correct.

**Comment by zhaiyuyong** [comment]
you need kinit
