### ISSUE TITLE
Test Issue: Not resolving STREAMING aggregation?

### ISSUE THREAD

**Issue by atris** [prestodb/presto#11057]
I am working on an optimization that adds a partial aggregate below a semijoin if the estimated number of output rows is more than the number of distinct values on the filteringsource side.

I am using the following query to test the same:

explain select count(*) from orders where orderkey IN (SELECT orderkey from lineitem);

--------------------------------------------------------------------------------
 - Output[_col0] => [count:bigint]                                              
         Cost: {rows: 1 (9B), cpu: 319521879.00, memory: 40500018.00, network: 2
         _col0 := count                                                         
     - Aggregate(FINAL) => [count:bigint]                                       
             Cost: {rows: 1 (9B), cpu: 319521879.00, memory: 40500018.00, networ
             count := "count"("count_13")                                       
         - LocalExchange[SINGLE] () => count_13:bigint                          
                 Cost: {rows: 1 (9B), cpu: 319521870.00, memory: 40500009.00, ne
             - RemoteExchange[GATHER] => count_13:bigint                        
                     Cost: {rows: 1 (9B), cpu: 319521870.00, memory: 40500009.00
                 - Aggregate(PARTIAL) => [count_13:bigint]                      
                         Cost: {rows: 1 (9B), cpu: 319521870.00, memory: 4050000
                         count_13 := "count"(*)                                 
                     - FilterProject[filterPredicate = "expr_8"] => []          
                             Cost: {rows: 1500000 (15.74MB), cpu: 319521870.00, 
                         - Project[] => [orderkey:bigint, expr_8:boolean]       
                                 Cost: {rows: 1500000 (15.74MB), cpu: 303021870.
                             - SemiJoin[orderkey = orderkey_1][$hashvalue, $hash
                                     Cost: {rows: 1500000 (28.61MB), cpu: 286521
                                 - ScanProject[table = tpch:tpch:orders:sf1.0, o
                                         Cost: {rows: 1500000 (12.87MB), cpu: 13
                                         $hashvalue := "combine_hash"(bigint '0'
                                         orderkey := tpch:orderkey              
                                         tpch:orderstatus                       
                                             :: [[F], [O], [P]]                 
                                 - LocalExchange[SINGLE] () => orderkey_1:bigint
                                         Cost: {rows: 1500000 (25.75MB), cpu: 16
                                     - RemoteExchange[REPARTITION - REPLICATE NU
                                             Cost: {rows: 1500000 (25.75MB), cpu
                                         - Project[] => [orderkey_1:bigint, $has
                                                 Cost: {rows: 1500000 (25.75MB),
                                                 $hashvalue_16 := "combine_hash"
                                             - Aggregate(STREAMING)[orderkey_1] 
                                                     Cost: {rows: 1500000 (12.87
                                                 - TableScan[tpch:tpch:lineitem:
                                                         Cost: {rows: 6001215 (5
                                                         orderkey_1 := tpch:orde
                                                                                
(1 row)

I added a test which verifies the following structure for the above query in a new unit test:

                anyTree(
                        semiJoin("ORDERS_ORDERKEY", "LINE_ORDERKEY", "SEMI_JOIN_RESULT",
                                anyTree(tableScan("orders", ImmutableMap.of("ORDERS_ORDERKEY", "orderkey"))),
                                        node(ExchangeNode.class,
                                                project(
                                                    aggregation(ImmutableMap.of(),
                                                            tableScan("lineitem", ImmutableMap.of("LINE_ORDERKEY", "orderkey"))))))));

However,the test expects the following structure for the given query:

- Output[_col0] => [count:bigint]
        Cost: {rows: 1 (9B), cpu: ?, memory: ?, network: ?}
        _col0 := count
    - Aggregate(FINAL) => [count:bigint]
            Cost: {rows: 1 (9B), cpu: ?, memory: ?, network: ?}
            count := "count"("count_13")
        - LocalExchange[SINGLE] () => count_13:bigint
                Cost: {rows: 1 (9B), cpu: ?, memory: ?, network: ?}
            - Aggregate(PARTIAL) => [count_13:bigint]
                    Cost: {rows: 1 (9B), cpu: ?, memory: ?, network: ?}
                    count_13 := "count"(*)
                - FilterProject[filterPredicate = "expr_8"] => []
                        Cost: {rows: 15000 (161.13kB), cpu: ?, memory: ?, network: ?}/{rows: 15000 (0B), cpu: ?, memory: ?, network: ?}
                    - Project[] => [orderkey:bigint, expr_8:boolean]
                            Cost: {rows: 15000 (161.13kB), cpu: ?, memory: ?, network: ?}
                        - SemiJoin[orderkey = orderkey_1][$hashvalue, $hashvalue_14] => [orderkey:bigint, $hashvalue:bigint, expr_8:boolean]
                                Cost: {rows: 15000 (292.97kB), cpu: ?, memory: ?, network: ?}
                            - ScanProject[table = local:tpch:orders:sf0.01, originalConstraint = true] => [orderkey:bigint, $hashvalue:bigint]
                                    Cost: {rows: 15000 (131.84kB), cpu: ?, memory: ?, network: ?}/{rows: 15000 (263.67kB), cpu: ?, memory: ?, network: ?}
                                    $hashvalue := "combine_hash"(bigint '0', COALESCE("$operator$hash_code"("orderkey"), 0))
                                    orderkey := tpch:orderkey
                                    tpch:orderstatus
                                        :: [[F], [O], [P]]
                            - Project[] => [orderkey_1:bigint, $hashvalue_14:bigint]
                                    Cost: {rows: 15000 (263.67kB), cpu: ?, memory: ?, network: ?}
                                    $hashvalue_14 := "combine_hash"(bigint '0', COALESCE("$operator$hash_code"("orderkey_1"), 0))
                                - Aggregate(FINAL)[orderkey_1] => [orderkey_1:bigint]
                                        Cost: {rows: 15000 (131.84kB), cpu: ?, memory: ?, network: ?}
                                    - LocalExchange[SINGLE] () => orderkey_1:bigint
                                            Cost: {rows: 15000 (131.84kB), cpu: ?, memory: ?, network: ?}
                                        - Aggregate(PARTIAL)[orderkey_1] => [orderkey_1:bigint]
                                                Cost: {rows: 15000 (131.84kB), cpu: ?, memory: ?, network: ?}
                                            - TableScan[local:tpch:lineitem:sf0.01, originalConstraint = true] => [orderkey_1:bigint]
                                                    Cost: {rows: 60175 (528.88kB), cpu: ?, memory: ?, network: ?}
                                                    orderkey_1 := tpch:orderkey

My questions here are:

1) Why is the project above Exchange in the expected output, whereas in the explain plan, it is (correctly) below Exchange?

2) Why does the output plan expect a Partial and Final aggregate, as opposed to a streaming aggregate?

Any inputs would be appreciated

**Comment by kokosing** [comment]
2. Try to use different column. See TpchMetadata (212 line) that shows that orderkey in lineitem is sorted. For such case streaming aggregation is prefered. This may also affect point 1.
