### ISSUE TITLE
DST handling in 'at TIME ZONE'

### ISSUE THREAD

**Issue by shrau94** [prestodb/presto#11070]
Hi,

I had a question regarding the date_format() in presto in a particular timezone.

`date_format(dateandtime at TIME ZONE 'America/Los_Angeles','%m/%d/%Y %r')`

I wanted to know whether this also handles DST (Daylight savings)?

**Comment by findepi** [comment]
It does. Bear in mind, however, that: https://github.com/prestodb/presto/issues/7122

HTH
