### ISSUE TITLE
information_schema queries are slow

### ISSUE THREAD

**Issue by MichaelChirico** [prestodb/presto#11078]
The following query timed out after 60 minutes for me:

```
select * from information_schema.columns where column_name like '%referral%';
```

`select count(*) from information_schema.tables` is about 46K; `select count(*) from information_schema.columns` also timed out.

This type of sluggishness is par for the course in my experience with `information_schema` queries (especially on `columns`).

I came across this article just now:

https://www.percona.com/blog/2011/12/23/solving-information_schema-slowness/

1. Is the root cause of the speed issue the same in both cases?
2. Is there a similar fix available for Presto?

We are currently running `0.187`. Is it possible this is related to https://github.com/prestodb/presto/issues/10222 as well? My guess is no since the query doesn't actually appear to be doing anything yet...

![screen shot 2018-07-19 at 11 47 03 am](https://user-images.githubusercontent.com/7606389/42920498-7a0ec692-8b49-11e8-8236-89d36081771f.png)

**Comment by kokosing** [comment]
>` select * from information_schema.columns where column_name like '%referral%';`

0.199 (https://prestodb.io/docs/current/release/release-0.199.html) contains `Improve the performance of queries that use LIKE predicates on the columns of information_schema tables.` 
Please try to update and rerun your query.

> Is the root cause of the speed issue the same in both cases?
Is there a similar fix available for Presto?

No. No.

In regards to hive connector. Information schema is just a view over the Hive Metastore. IIRC when you run `select count(*) from information_schema.tables` hive connector will request from Hive Metastore list of tables for each schema you have. When requesting `information_schema.columns` you will have number of request in line with number of tables (+ number of requests to retrieve the list of tables). If each request would take about 10ms, then we might expect that query would complete in 8mins (46K * 10ms). However it takes longer to process the results.

Notice that predicate pushdown should highly influence the query performance.
