### ISSUE TITLE
occasionally, many users' queries are queued at some time point at presto version 0.198，We have configured the resource_groups file

### ISSUE THREAD

**Issue by PennyAndWang** [prestodb/presto#11090]
At most time，presto runs very normally，occasionally   many users' queries are queued at some time point。I don't know why, does someone have the same problem?
By the way ,i can't reproduce the problem。

**Comment by findepi** [comment]
There were some bug fixes in resource groups and pools' configurations. Please check if the problem persists on a more recent version. If it does, please open a new issue.
