### ISSUE TITLE
Coordinator OOM when a query scans many partitions of a Hive table

### ISSUE THREAD

**Issue by haozhun** [prestodb/presto#11134]
TupleDomain shows up multiple times in a TableScanNode:

* `.tableLayout.layout.promisedPredicate` (bad; a discrete TupleDomain representing all partitions)
* `.tableLayout.layout.compactEffectivePredicate` (good; compacted [here](https://github.com/prestodb/presto/blob/0.206/presto-hive/src/main/java/com/facebook/presto/hive/HivePartitionManager.java#L167))
* `.currentConstraint` (bad; a discrete TupleDomain representing all partitions)

The `TaskUpdateRequest.fragment` contains the plan of a fragment, which contains the TableScanNode. It is transmitted to each task once.

Due to the **two** bad JSONs in the TableScan node, such a plan would be roughly 8.4MB.

Take a query with 16 scans of a table with 10000 partitions (without any partition filter) in a cluster of 500 workers. It takes up 8.4MB/JSON * 1 JSON/task * 500 workers * 16 stages = 70GB

70GB of JSON is generated in short succession, and handed to Jetty client, which provides little back pressure. This translates into many humongous allocations, and causes significant GC pressure. This could also fill up the heap, leading to OOM.

### `.currentConstraint`

Fix is easy. It is only used during planning, and does not need to be transported to workers. #11133

### `.layout.connectorHandle.promisedPredicate`

This is used in `getOrComputePartitions`, and is need for executing delete on Hive.

The cause has to do with iterative optimization. Let's take a look at [`PickTableLayout.planTableScan`](https://github.com/prestodb/presto/blob/0.206/presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PickTableLayout.java#L190)

* The first time it's called
  * `predicate` represents the user-provided predicate in the query. (In general, it represents the predicate from filters above.)
  * `node.currentConstraint` is `true`
  * The deterministic part of `predicate` is decomposed into a `TupleDomain` and an expression representing the remaining expression.
    * The expression representing the remaining expression is thrown out. (Is this a bug?)
    * The intersection of the `TupleDomain` and `node.currentConstraint` is stored in `simplifiedConstraint`. (I don't get what `simplified` is supposed to mean here.)
  * `HiveMetadata.getLayouts` is invoked with `simplifiedConstraint`. It returns a `TableLayoutResult`. 
  * For the purpose of this discussion, `TableLayoutResult` consists of roughly 3 parts: (1) `layout.predicate` (2) `unenforcedConstraint` (3) `layout.handle.promisedPredicate` (4) rest of `layout.handle`.
    * What `1` and `3` represents is not documented. Based on my understanding. They need to satisfy the following requirements. Take Universe = `{all tuples of partition column values in the table}`,
      * ~~`1 ∧ 2` must be equal to `simplifiedConstraint`~~ (This is incorrect)
      * ~~`1` must be equal to the list of partitions `4` physically represents.~~ (This is incorrect)
      * `3 ∧ 2` must be equal to `simplifiedConstraint`
      * `3` must be equal to the list of partitions `4` physically represents.
    * In the current implementation, `1` is implemented by reversing from `4`. This makes it a discrete TupleDomain. [here](https://github.com/prestodb/presto/blob/0.206/presto-hive/src/main/java/com/facebook/presto/hive/HiveMetadata.java#L1407)
    * In the current implementation, `3` is implemented by decomposing `simplifiedConstraint`. i.e. [here](https://github.com/prestodb/presto/blob/0.206/presto-hive/src/main/java/com/facebook/presto/hive/HiveMetadata.java#L1367) and [here](https://github.com/prestodb/presto/blob/0.206/presto-hive/src/main/java/com/facebook/presto/hive/HivePartitionManager.java#L154)
  * In the new `TableScanNode`, `node.currentConstraint` will be set to intersect of `1` and `simplifiedConstraint`, making it discrete.
    * Side question: why is the intersection with `simplifiedPredicate` necessary?
* In subsequent times it's called
  * `node.currentConstraint` is now discrete
  * This make `simplifiedConstraint` discrete
  * This then makes `3` discrete

I'm proposing to compute `1` by decomposing `simplifiedConstraint`, instead of by reversing from `4`. This will make it equivalent to `3`.

**Comment by kokosing** [comment]
> The expression representing the remaining expression is thrown out. (Is this a bug?)

It is used to create `resultingPredicate` at the end of the method.

> I don't get what simplified is supposed to mean here.

It was named that after the code in `AddExchnages`, now this variable in `AddExchanges` is named `newDomain`. It should be renamed here as well.

**Comment by haozhun** [comment]
I edited my original post to make it easier to read.

@kokosing I'm proposing to compute `1` by decomposing `simplifiedConstraint`, instead of by reversing from `4`. This will make it equivalent to 3.

**Comment by haozhun** [comment]
> > The expression representing the remaining expression is thrown out. (Is this a bug?)

> It is used to create resultingPredicate at the end of the method.

Should it also be included in the `Constraint` that is passed to `metadata.getLayouts`?

**Comment by kokosing** [comment]
> Should it also be included in the Constraint that is passed to metadata.getLayouts?

No. Constraint evaluates whole predicate once per whole "partition". In case of `WHERE random() > 0.5` you want to select rows randomly not partitions.

**Comment by haozhun** [comment]
> > Should it also be included in the Constraint that is passed to metadata.getLayouts?

> No. Constraint evaluates whole predicate once per whole "partition". In case of WHERE random() > 0.5 you want to select rows randomly not partitions.

In my post when I said "The deterministic part of predicate is decomposed into ...". Things like `random() > 1` is handled separately by `filterDeterministicConjuncts` and `filterNonDeterministicConjuncts` at the beginning and end of `planTableScan`.

In my question, I'm talking about the part that cannot be turned into a TupleDomain in `deterministicPredicate`.

**Comment by kokosing** [comment]
`PickTableLayout` is using only tuple domain part of the `Constraint` which is different to `AddExchanges` which is using also a `Constraint#predicate`. Evaluating expression per each partition in planner is expensive, because of that only `AddExchanges` does that today.

**Comment by haozhun** [comment]
> PickTableLayout is using only tuple domain part of the Constraint which is different to AddExchanges which is using also a Constraint#predicate. Evaluating expression per each partition in planner is expensive, because of that only AddExchanges does that today.

This makes sense. This should definitely have been documented.

Additionally, I have more questions for you, @kokosing.

1. Why do we intersect with `simplifiedConstraint` [here](https://github.com/prestodb/presto/blob/0.206/presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PickTableLayout.java#L223)? I don't understand why `currentConstraint` of `TableScan` should have anything to do with `simplifiedConstraint`. 

Take this example. Let's say in Hive connector, we run `SELECT * FROM t WHERE a=3 and ds='2000-01-01'`. The only partition key of `t` is `ds`. Why should the `currentConstraint` of `TableScan` include a predicate on `a`? That information is not relevant to the `TableScan` at all.

2. What do you think about the proposal at the end of the original post?

**Comment by kokosing** [comment]
1.
> Take this example. Let's say in Hive connector, we run SELECT * FROM t WHERE a=3 and ds='2000-01-01'. The only partition key of t is ds. Why should the currentConstraint of TableScan include a predicate on a? That information is not relevant to the TableScan at all.

See that information about predicate on `a` won't be included  in the `currentConstraint`, `intersects` with `layout` predicate will prune that. I think it is designed for other use case like `SELECT * FROM t WHERE t1=1` where layout would return information about two partitioning columns t1 and t2 (`t1=1, t2=?`), in this case `currentConstaint` would have more information that was needed. Actually, I do not think that having more information is a bad thing and we should not intersect domains here. For example information about about `t2` could be used by predicate pushdown and filter data on the other side of a join.

Let me fix this.

2. Sounds good to me.

**Comment by kokosing** [comment]
> See that information about predicate on a won't be included in the currentConstraint, intersects with layout predicate will prune that. I think it is designed for other use case like SELECT * FROM t WHERE t1=1 where layout would return information about two partitioning columns t1 and t2 (t1=1, t2=?), in this case currentConstaint would have more information that was needed. Actually, I do not think that having more information is a bad thing and we should not intersect domains here. For example information about about t2 could be used by predicate pushdown and filter data on the other side of a join.

Ah sorry. I confused the `intersects` method semantic. Most of the above is wrong, please ignore it.

I think, you are right `a =3` in your case will be handled anyway because it is part of `layout.getUnenforcedConstraint()`, so that `intersects` here seems to be not needed. Moreover, it could mislead because the semantic of `currentConstraint` seems to be unclear. One may thought that it describes the data that comes from the table scan, they could notice that it contains `a=3` and so the filter above with `a=3` is not needed, that would be a bug in your case.

**Comment by kokosing** [comment]
@haozhun Please see https://github.com/prestodb/presto/pull/11164

**Comment by wenleix** [comment]
> ### `.layout.connectorHandle.promisedPredicate`
> This is used in `getOrComputePartitions`, and is need for executing delete on Hive.

Note `MetadataDeleteNode` carries `layout`. Thus, `TableScanNode` doesn't need to transport it to worker.
