### ISSUE TITLE
Optimize execution of correlated subqueries with Equi - predicate

### ISSUE THREAD

**Issue by arhimondr** [prestodb/presto#11148]
Currently correlated scalar subqueries are translated to a LEFT JOIN. 

Since a LEFT JOIN  may return more than a single match for a single row from the probe (left) side table, the deduplication is needed. 

The deduplication is done by assigning unique ID for every row of a probe (left) side table, and than by doing aggregation removing all duplicates (MarkDistinct + FilterAndProject).

The deduplication algorithm is cpu consuming (2 additional projections over a probe table + aggregation over a probe table) and memory consuming (it require a probe table to fit in memory).

Instead of doing LEFT OUTER JOIN + DEDUPLICATION we can do "LEFT OUTER SEMI JOIN". The idea is to make the JOIN operator return no more than a single match. 

It can be done by taking one of the approaches:

1. Pass a flag to the LookupJoinOperator saying that no more than a single match is needed. With this approach extra matches will be filtered on the JOIN stage.
2. Pass a flag to the HashBuilderOperator, saying that no more that a single entry for a given key is needed. Effectively skipping extra entries. This approach is more efficient, but also more limited. It works only if the criteria is a simple equality on the join key with no extra filters.

**Comment by arhimondr** [comment]
CC: @martint @kokosing

**Comment by kokosing** [comment]
Should we close this in favor of #10830?

**Comment by arhimondr** [comment]
Yeah, let's close it. I didn't know someone is working on it.
