### ISSUE TITLE
ORDER BY using col #s fails and reports as "'column' cannot be resolved"

### ISSUE THREAD

**Issue by RSmithBothell** [prestodb/presto#11152]
Five CTEs, 
one CTE joining with each of the other four to make 4 queries unioned together.

More columns than represented here.

-- ==================================================
WITH common (a, b, c, d, e, f, g, h, i, j)
          AS       (select...)

,    dog  (p, q, r, s, w1, x1, y1, z1)
     AS      (select ...)

,   cat (p, q, r, s, w2, x2, y2, z2)
    AS    (select ...)

,   mouse (p, q, r, s, w3, x3, y3, z3)
    AS      (select ...)

,   cheese (p, q, r, s, w4, x4, y4, z4)
    AS           (select ...)

-- ------------------------------
SELECT a, b, c, d, e, f, g, h, i, j
         , w1 AS w
         , x1 AS x
         , y1, AS y
         , z1 AS z
FROM common
--
JOIN  dog
  ON   ...
 AND ...
AND ...
--
WHERE xxxx
--
UNION
--
SELECT a, b, c, d, e, f, g, h, i, j
         , w2 AS w
         , x2 AS x
         , y2, AS y
         , z2 AS z
FROM common
JOIN  cat
  ON   ...
 AND ...
AND ...
--
WHERE xxxx
--
UNION
--
SELECTa, b, c, d, e, f, g, h, i, j
         , w3 AS w
         , x3 AS x
         , y3, AS y
         , z3 AS z
FROM common
--
JOIN  mouse
  ON   ...
 AND ...
AND ...
--
WHERE xxxx
--
UNION
--
SELECT a, b, c, d, e, f, g, h, i, j
         , w4 AS w
         , x4 AS x
         , y4, AS y
         , z4 AS z
FROM common
--
JOIN  cheese
  ON   ...
 AND ...
AND ...
--
WHERE xxxx
--
ORDER BY 3, 2, 5

-- ==================================================

Error said the 11th column (w) was not resolved, which was the 1st column sourced from the 2ndary queries, (that column was the 4th column, (of 7), from the 2ndary queries).

**Comment by dain** [comment]
This is a pretty big query.  Can you come up with a minimal reproduction of your problem?

**Comment by kokosing** [comment]
> This is a pretty big query. Can you come up with a minimal reproduction of your problem?

The best if you would use TPCH, TPCDS or Memory Connector so we could reproduce it easily locally.

**Comment by atris** [comment]
@RSmithBothell Let us know if you have a shorted query which reproduces this and we will take a look ASAP.
