### ISSUE TITLE
Why coordinator take up a lot of memory

### ISSUE THREAD

**Issue by imperio-wxm** [prestodb/presto#11165]
My coordinator config：

```shell
coordinator=true
discovery-server.enabled=true
http-server.http.port=8080
node-scheduler.include-coordinator=false
query.max-memory-per-node=15GB
query.max-memory=115GB

-Xmx=46G
```

Use top:

```shell
49519 presto    20   0 63.6g  34g  52m S 718.7 54.8  64329:45 presto-server 
```
presto-server use 34g mem.

My understanding is that worker should occupy more memory. Coordinator is just scheduling tasks. Is this normal?

**Comment by nezihyigitbasi** [comment]
Coordinator can also allocate significant amount of memory depending on many factors (workload, cluster, etc.), so it's not unexpected. To see what is holding onto that memory you can get a heap dump on the coordinator.

**Comment by imperio-wxm** [comment]
@nezihyigitbasi  In my cluseter, 7 workers hold 18G mem, but coordinator use more than 40G mem. And my sql often need more network I/O.

We have lots of data need to be load, however calculation is not complicated, is it related to this?
