### ISSUE TITLE
Does Presto support add partition

### ISSUE THREAD

**Issue by photogamerun** [prestodb/presto#11174]
For example

in hive 
```
alter table my_partition_test_table if not exists add partition (p_hour='2017113003', p_city='573', p_loctype='MHA');
```

does presto support like this?

**Comment by findepi** [comment]
Please see https://github.com/prestodb/presto/pull/11249. Does this answer your needs?

**Comment by findepi** [comment]
Fixed by https://github.com/prestodb/presto/pull/11249
