### ISSUE TITLE
Optimize arbitrary() aggregation

### ISSUE THREAD

**Issue by cheparukhin** [prestodb/presto#11187]
I have a use case of removing duplicate rows from a large table by a unique key:

    SELECT
        unique_key,
        ARBITRARY(huge_column) AS huge_column
    FROM my_table
    GROUP BY unique_key

Presto puts `huge_column` in memory, while the only thing that needs to be remembered is `unique_key` as we can flush the values immediately. If `unique_key` is much smaller than `huge_column`, this makes a big difference in memory consumption.

Could this be optimised? If ARBITRARY is the only aggregation, values could be flushed right away without putting them in memory.

A more generic optimisation could be to decide whether to finish the iteration inside each aggregation function, i.e. return a value to indicate whether it's an intermediate or final result. In the latter case the result could be flushed right away:

    data State = Init | PartialState | Result
    reduce :: State -> Key -> Value -> State

cc @electrum

**Comment by dain** [comment]
This should be optimized to the RowNumberOperator with limit of 1.
