### ISSUE TITLE
Add JSON format for EXPLAIN

### ISSUE THREAD

**Issue by rschlussel** [prestodb/presto#11189]
I'd like to add a JSON format for explain to make explain plans machine parseable.  I would add the option to both explain and explain analyze.  And the implementation would b in PlanPrinter (just like how TEXT and GRAPHVIZ are implemented)

The motivation is that I want a machine analyzable way to easily compare estimated costs and stats for a query with the actual performance results.

**Comment by martint** [comment]
The plan IR is not stable, so any such output would be subject to backward-incompatible changes from version to version.

**Comment by rschlussel** [comment]
Yes, agreed. it's not about committing to the output having particular fields, etc.  it's that we want some way to get a representation that we can extract information from and analyze.  If the IR changes, the JSON would be different and that's ok.

**Comment by oneonestar** [comment]
Our team also like to have this feature. A machine readable explain analyze can help us better understand the type of query running in our cluster and figure out bottlenecks.

**Comment by rschlussel** [comment]
Currently there are json versions of the plan as part of the queryCompletedEvent for a query, so it should be pretty straightforward to add this format for EXPLAIN.

**Comment by patrickofriel-wk** [comment]
This would be extraordinarily useful

**Comment by chyikwei** [comment]
Is anyone working on this? I would like to claim this issue if possible.

**Comment by rongrong** [comment]
Currently we only support JSON format for `EXPLAIN (TYPE IO, FORMAT JSON)`. It would be great if you can help us to extend it to other types!

**Comment by chyikwei** [comment]
@rongrong thanks! Will check the reference commit you share.
