### ISSUE TITLE
Optimise StageStateMachine for memory

### ISSUE THREAD

**Issue by rajeshbalamohan** [prestodb/presto#11202]
```SqlQueryScheduler | SqlStageExecution| StageStateMachine::getStageInfo``` are frequently executed codepaths in presto.
There are couple of places where ImmutableList is called on top of immutable lists creating additional objects. 
Intention is to reduce the memory usage as size of tasks, operatorStats can be high in busy clusters.

**Comment by rajeshbalamohan** [comment]
This is w.r.t 202 version.

**Comment by findepi** [comment]
Closing in favor of the PR https://github.com/prestodb/presto/pull/11204. Let's keep discussion there.
