### ISSUE TITLE
A required class was missing while executing pl.project13.maven:git-commit-id-plugin:2.1.13:revision

### ISSUE THREAD

**Issue by xufei1006** [prestodb/presto#11220]
Hi guys:

I checkout the master branch code, try to compile it using maven.

![image](https://user-images.githubusercontent.com/26618143/43828919-57310882-9b30-11e8-9cfb-50ab29b8a53e.png)

I look at the pom.xml file, I couldn't even find where your guys use this plugin ? and why this exception happen ？

**Comment by findepi** [comment]
Are you running Maven using `./mvnw` script included in the repo?

**Comment by xufei1006** [comment]
It looks like, I downloaded a broken jackson-core jar, thank you anyway. Problem solved.
