### ISSUE TITLE
Optimise InternalResourceGroup::enforceLimits

### ISSUE THREAD

**Issue by rajeshbalamohan** [prestodb/presto#11277]
"InternalResourceGroup::enforceLimits" mainly makes use of elpasedTime for the queries. However, as a part of retrieving this field, it ends up computing the entire stage info which can be optimized. Here is the flamegraph for the same.

<img width="1073" alt="internalresourcegroup_enforcelimits" src="https://user-images.githubusercontent.com/323339/44146179-1d9b25c2-a0ac-11e8-9dac-f50f2d3a3019.png">

**Comment by dain** [comment]
@raghavsethi and I found the same thing last week.  We are working on a refactor of this system which should eliminate this issue.

**Comment by rajeshbalamohan** [comment]
Thanks for sharing the details @dain.
