### ISSUE TITLE
Presto WebUI  - authorization (security)

### ISSUE THREAD

**Issue by tooptoop4** [prestodb/presto#11298]
enable 2 roles (admin, user). Users in 'user' role can only see their queries on the WebUI whereas users in 'admin' role can see all queries on the WebUI. The reason for hiding other users queries is that they may have sensitive data: ie select * from persontbl where name = 'john smith' and address='123 smith st' + the UI reveals the count of rows returned by the query - thus allowing sensitive data to be revealed to other users.

**Comment by tooptoop4** [comment]
Also would be nice to have a config setting to disable WebUI altogether

**Comment by findepi** [comment]
There should be hooks in `SystemAccessControl` (or a new interface created specifically for this purpose) allowing to filter/control access in the UI.
The roles (be it "admin", "user" or anything) would be up to the implementation of the interface.

**Comment by tooptoop4** [comment]
https://github.com/prestodb/presto/issues/13301

**Comment by dipanjanmukherjee83** [comment]
Do we have any update how we can stop seeing each other quires from Presto-ui. 
Because of this we have got couple of security incidents in our environments.

**Comment by tooptoop4** [comment]
@dipanjanmukherjee83 use prestosql
