### ISSUE TITLE
QueryAssertions should not use the same runner to run the expected query

### ISSUE THREAD

**Issue by kokosing** [prestodb/presto#11310]
Tested query engine cannot be used a source of truth at the same time. Please see the below code from `com.facebook.presto.sql.query.QueryAssertions`:

```
    public void assertQuery(@Language("SQL") String actual, @Language("SQL") String expected, boolean ensureOrdering)
    {
        MaterializedResult actualResults = null;
        try {
            actualResults = runner.execute(runner.getDefaultSession(), actual).toTestTypes();
        }
        catch (RuntimeException ex) {
            fail("Execution of 'actual' query failed: " + actual, ex);
        }

        MaterializedResult expectedResults = null;
        try {
            expectedResults = runner.execute(runner.getDefaultSession(), expected).toTestTypes();
        }
        catch (RuntimeException ex) {
            fail("Execution of 'expected' query failed: " + expected, ex);
        }
```

**Comment by findepi** [comment]
The assumption is that `expected != actual`, i.e. they produce the same results but in a different manner. We should probably have a check these are indeed different.

**Comment by findepi** [comment]
The assumption is that `expected != actual`, i.e. they produce the same results but in a different manner (think: `actual` being a complex query and `exepcted` being VALUES or something).
We should probably have a check these are indeed different.

**Comment by martint** [comment]
This is intentional. “Expected” being a query is just for convenience. I could’ve used a list of java values directly, instead. It’s annoying to construct them, though.

One assumption is that something as basic as a values query or a simple select are being tested and validated elsewhere, so this is a perfectly fine approach .

**Comment by kokosing** [comment]
Thanks for explanation.
