### ISSUE TITLE
Comparison of False with NULL is incorrect

### ISSUE THREAD

**Issue by EvilPuppetMaster** [prestodb/presto#11323]
Comparing False with NULL appears to be correct. A comparison of anything with NULL should always be NULL. However
```
-> select false and null <> 1; -- expected NULL
 _col0 
-------
 false 
(1 row)
```

Other variations ARE working correctly:
```
-> select null <> 1; -- expected NULL
 _col0 
-------
 NULL  
(1 row)

-> select true and null <> 1; -- expected NULL
 _col0 
-------
 NULL  
(1 row)
```

**Comment by kokosing** [comment]
```
-> select false and null <> 1; 
 _col0 
-------
 false 
```

This is correct. `null` in SQL works as any value. Conjunction of `false` with any value will always return `false`.
