### ISSUE TITLE
Feature request: support for PRINTF or better string formatting

### ISSUE THREAD

**Issue by haonans** [prestodb/presto#11343]
There is no direct alternative in Presto to Hive's `PRINTF` and to achieve the same functionality, users have to do `CAST` and `||` themselvels. Here is an example/comparison between Hive's string formatting and Presto's :

In Hive, users can just do
```
PRINT('a=%s#b=%s#c=%s', a, b, c)
```
In Presto, users have to do something like
```
'a=' || COALESCE(CAST(a AS VARCHAR), 'null') || 'b=' || COALESCE(CAST(b AS VARCHAR), 'null') || 'c=' || COALESCE(CAST(c AS VARCHAR), 'null') 
```

Because `CAST(NULL AS VARCHAR)` returns`NULL` while `PRINTF('%s', NULL)` returns `'null'` and besides users have to split the format string themselves.

**Comment by martint** [comment]
Some comments:
* I'd probably name the function `format` or something similar to more closely convey its semantics (it doesn't really "print" anything).
* It'd be hard to implement the function as described in this issue. These are the current limitations:
    * Not have a type hierarchy. i.e., the function can't take "any" or "object" as the arguments. 
    * No implicit coercions from arbitrary types to VARCHAR, so it can't be modeled as `format(varchar...)`
    * Possibly (need to verify), functions can't have mixed varargs and non-varargs arguments (especially of different types)

**Comment by dain** [comment]
@martint I was thinking the same issue about coercions/casting.  @haonans would only supporting `%s` be good enough?

**Comment by martint** [comment]
Even with `%s`, you'd need to call it as follows due to lack of implicit casts between arbitrary types and varchar:

```
format('a=%s, b=%s, c=%s', cast(a as varchar), cast(b as varchar), cast(c as varchar)))
```

**Comment by haonans** [comment]
Doing `format` + `cast` is a lot better than doing `concat` + `cast` + `coalesce` since otherwise the string format is broken into pieces, which I think we should try to avoid.
