### ISSUE TITLE
Avoid making wild guesses when estimating filter cardinality

### ISSUE THREAD

**Issue by arhimondr** [prestodb/presto#11341]
Currently if some of the statistics are missing, we are making a wild guess, and assume that filter ration is a magic `0.9` constant. That is particularly deadly when trying to estimate the cardinality of a JOIN, and some of the statistics are missing.   For example if the ROW_COUNT statistic is present for both tables, we will estimate cardinality as a cross product first, and than we will try to apply an equality filter. And if some of the statistics (like NDV for one of the table) are missing, we will end up with INNER equi join cardinallity estimated as a cross product mulptiplied by 0.9 filter factor.

**Comment by mbasmanova** [comment]
CC: @findepi
