### ISSUE TITLE
[kafka] Schema Registry Integration

### ISSUE THREAD

**Issue by OneCricketeer** [prestodb/presto#11354]
Improvements over #11108 and related to #7391 (`kafka-avro-console-consumer` equivalent)

Confluent Platform is a very popular enterprise deployment of Apache Kafka. In the Big Data space, for example, Flink recently added Confluent Avro (De)Serializers to their streaming components to integrate with the [Confluent Schema Registry](https://www.confluent.io/confluent-schema-registry/). NiFi and Streamsets also offer streaming integrations with the registry. 

These byte payloads are implemented like so [Confluent :: Avro Wire Format](https://docs.confluent.io/current/schema-registry/docs/serializer-formatter.html#wire-format). The general idea of which is that you replace the "embedded JSON schema" with a 4 bit schema ID. On this deserialization, the ID is extracted, then an HTTP lookup is performed against the RESTful registry. [API Reference, see `GET /schemas/:id`](https://docs.confluent.io/current/schema-registry/docs/api.html). That request returns the JSON-encoded schema payload, from which you can pass to the Avro `Schema.Parser()`. [Deserializer Source code](https://github.com/confluentinc/schema-registry/blob/master/avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializer.java#L108-L125), though one would use [`KafkaAvroDeserializer`](https://github.com/confluentinc/schema-registry/blob/master/avro-serializer/src/main/java/io/confluent/kafka/serializers/KafkaAvroDeserializer.java) rather than that Abstract class

---

Proposal:

Enhance the Avro support to 

1. Change the "type" of Avro deserializer to differentiate the behavior of embedding the schema in the Kafka payload or looking it up elsewhere based on an ID. 
    - Optional: Be able to set the Avro "reader schema" explicitly for a given topic
2. Add an optional property such as `schema.registry.url` (which is what the  Deserializer class for the Confluent code uses) to define the URL(s) to perform a lookup against. 

Note: [Hortonworks Registry](https://github.com/hortonworks/registry) operates similarly and ingrates with their HDF environment, so the idea is that whichever platform is targeted for this ticket, it should be fairly easy to switch between the two with a few configurations.

**Comment by cricket007** [comment]
To Watch for Hive - https://github.com/apache/hive/pull/526
