### ISSUE TITLE
Reload EventListener Without Restarting Coordinator

### ISSUE THREAD

**Issue by VicoWu** [prestodb/presto#11369]
From the presto [document](https://prestodb.io/docs/current/develop/event-listener.html) and the source code,  I know that currently presto support only one active event listener and every time event listener was updated or re-loaded, we have to restart coordinator to let it take effect. I think below improvements were necessary:

1. ~**Support Multiple EventListeners**: Make presto support multiple event listeners, every time a event happened, we will traverse all event listeners~ (#9100)
2. **Reload EventListener without Restarting Coordinator**:Every time we want to replace the EventListener with a new one(for example a bug fix in the event listener), just replace the jar, and call the reload RestAPI to dynamically reload the new EventListener plugin. 

Any suggestions ?

**Comment by dain** [comment]
I believe you can do this yourself.  Simply write an event listener that loads child event listeners and add your own reload logic.

**Comment by findepi** [comment]
"Make Presto Support Multiple EventListeners" has already been reported as #9100. Let me edit this issue to cover only "Reload EventListener Without Restarting Coordinator" part.

**Comment by VicoWu** [comment]
@findepi  Thanks.  I just want to make sure what's the community opinion about whether or not it is worth doing this. so , What's your opinion?

**Comment by findepi** [comment]
About reloading when a jar is replaced? This is tricky. You can run into classloader issues (eg previous classloader not being unloaded for some reason).
Do you have a reason to replace event listener plugin very often? I guess this is not solely to bug fixes, are there other reasons?

**Comment by VicoWu** [comment]
@findepi  In practice, maybe we could expose an interface to make Coordinator reload the jar after we replaced the event listener jar. Anytime when I have some logic change, for example, the logic to process query created and query complete event, the change could take effect without restarting coordinator because coordinator is very critical while the event listener update is not;
I think a dedicated classloader for each event listener entry could resolve the classloader issues. 
Above is just my opinion.
Let's talk about and evaluate it together;
