### ISSUE TITLE
TEXTFILE storage impossible with embedded newlines in fields

### ISSUE THREAD

**Issue by MichaelChirico** [prestodb/presto#11383]
I think this is simply a bug inherited from Hive:

https://issues.apache.org/jira/browse/HIVE-11996

But thought I'd raise a ticket here anyway, if only to direct similarly-affected users to the root cause.

It seems that storing a table with `FORMAT = 'TEXTFILE'` that has some column that's (e.g.) `VARCHAR` containing embedded newlines (very common in free-form text fields) is currently impossible.

Workarounds include using other storage formats (e.g. `parquet`) but sometimes I/O is just more straightforward for `TEXTFILE` (no special tools needed, e.g.)

**Comment by electrum** [comment]
One alternative is to use the `JSON` format. This should be easy to write and supports escaping newlines within fields. In Presto, create the table with `format = 'JSON'` or `STORED AS JSON` in Hive. The Hive serde name is `org.apache.hive.hcatalog.data.JsonSerDe`.

**Comment by MichaelChirico** [comment]
Are there any benchmarks about performance among the various data types? Would be useful as the alternative I'm looking at now is indeed `parquet`, just more of a hassle to pin down the write libraries for it
