### ISSUE TITLE
Release notes for 0.210

### ISSUE THREAD

**Issue by findepi** [prestodb/presto#11391]
## Andrii Rosa
- [x] all checked
-  08-29 17:03:28    12c6a801d9 Add support for cross-realm Kerberos authentication
-  08-30 13:45:03    f35ff675bf Remove extra HdfsConfiguration#getConfiguration method
-  08-31 11:41:58    8d2b94c196 Refactor avro tests
-  08-31 11:43:00    7dc4568675 Remove user cpu time tracking
-  09-04 11:29:36    5021536aba Accept human-readable dates as TPCH column stats
-  09-04 11:30:56    1533e9420e Remove min/max intersection heuristics from equality stats calculator
-  09-04 11:30:56    3408678665 Do not assume expression normalization before FilterStatsCalculator
-  09-04 11:30:56    3561e38fae Extract isSingleValue(Expression) to simplify code
-  09-04 11:30:56    7f03a2277a Create VALUES with row values
-  09-04 11:30:56    8a91a10b1d Make cost-based decision when selecting Join distribution type
-  09-04 11:30:56    daffd838e7 Introduce partitioning switch in TPC-H connector
## Dain Sundstrom
- [x] all checked
-  08-31 12:52:46    110a27d334 Remove unused builder from PrincipalPrivileges
-  08-31 12:53:38    93036d64e2 Add test for FileSystem caching
## Grzegorz Kokosiński
- [x] all checked
-   08-29 23:24:49    84cbca3b86 Pass transactionHandle to checkCanSetCatalogSessionProperty
-   08-30 00:09:34    8fd010a7e2 Rename connectorId to catalogName in SPI
-   08-31 03:11:43    7097f5bb56 Rename BASIC_SQL test group to HIVE_PARTITIONING
-   08-31 03:13:02    8e751fd357 Fix queries against information_schema with uppercase names
-   08-31 11:30:58    422621470d Format pom.xml files
## Karol Sobczak
- [x] all checked
-  08-30 04:46:12    06e281ae6f Ensure global stream partitioning contains node partitioning columns
-  08-31 12:39:54    a36724f7d5 Remove redundant KerberosName#setRules call
-  09-04 02:25:01    b43b4a2da4 Add reslution of "hadoop-master" NetUtils#addStaticResolution
## Martin Traverso
- [x] all checked
-  08-29 17:08:26    63f992af7a Handle aliasing columns for table containing hidden columns
-  08-29 17:09:54    0decd76367 Add distinct grouping sets tests
-  08-29 17:09:54    3f8d5a8f0c Compute grouping sets during planning
-  08-29 17:09:54    5402584200 Simplify calculation of grouping operation
-  08-29 17:09:54    c134f2f468 Clean up computation of grouping expression candidates
## Piotr Findeisen
- [x] all checked
-  08-30 02:03:10    94930189c4 Use Optional instead of nullable Principal in access control SPI
-  08-30 02:03:26    de6e5141be Remove explicit array creation for varargs
-  08-30 02:03:26    fe0c7154fd Remove usages of deprecated parseTimestampInLocalTime
-  08-31 02:29:13    0724c0428e Update error messages in Avro-Kafka support with proper capitalization
-  08-31 02:29:13    0dd33bcad1 Disallow ALTER TABLE operations when Avro schema is set
-  08-31 02:29:13    0fd74e270b Use getFields to get the schema of tables
-  08-31 02:29:13    2e41c7a419 Extend metastore to get schema of non-metastore tables
-  08-31 02:29:13    440b4535b6 Add Avro schema url table parameter
-  08-31 02:29:13    75831d3268 Disable creating partitioned/bucketed tables when Avro schema set
-  08-31 02:29:13    9c3920fbf3 Disallow CTAS when Avro schema is set
-  08-31 02:29:13    b98215f7f2 Add documentation for Avro schema evolution in Hive connector
-  08-31 06:22:12    bd138f3798 Deallocate prepared statement on close
-  08-31 06:39:34    c4456959e5 Return a constructed exception from utility method instead of throwing it
-  09-04 01:37:12    bf35a8803d Fix schema checks in file-based access control
## Wenlei Xie
- [x] all checked
-  09-02 18:33:10    321078ed0c Use buffered bytes estimation from writer in DictionaryColumnManager
-  09-02 18:33:10    eb6028d8a8 Avoid writing huge stripes due to direct encode conversion
-  09-04 10:06:09    9751eb888b Minor fix in DictionaryCompressionOptimizer
-  09-04 10:06:09    ac567d474b Use buffered bytes to estimate compression ratio
-  09-04 10:06:09    bd1e2a7c6c Use long for ORC SliceWriter value count
-  09-04 10:06:09    c63e68dc24 Use index bytes estimation from writer in DictionaryColumnManager
-  09-04 23:54:51    ba1b787d21 Add row to row cast benchmark
-  09-04 23:54:51    ff8ee1bb23 Avoid Stream API in RowBlockBuilder constructor

**Comment by findepi** [comment]
```
SPI
---
* Principal is no longer nullable in `SystemAccessControl#checkCanSetUser`, it is `Optional<Principal>` now.
```

**Comment by martint** [comment]
```
* Fix planning failure when aliasing columns of tables containing hidden columns (#11385).
* Fix correctness issue when ``GROUP BY DISTINCT`` terms contain references to the same column using different syntactic forms (#11120).
```

**Comment by kokosing** [comment]
```
 * Fix queries against information_schema with uppercase names
```

**Comment by kokosing** [comment]
```
SPI
---
* Rename connectorId to catalogName
```

**Comment by kokosing** [comment]
```
SPI
---
* Pass ConnectorTransactionHandle to ConnectorAccessControl#checkCanSetCatalogSessionProperty
```

**Comment by findepi** [comment]
```
Hive
----
* Fix a security bug introduced in 0.209, when using `hive.security=file` allowing any user
  to execute `CREATE SCHEMA`, `DROP SCHEMA` and `ALTER SCHEMA ... RENAME TO` statements.
```

https://github.com/prestodb/presto/pull/11372

**Comment by arhimondr** [comment]
```
Hive
----
* Support cross-realm Kerberos authentication for the HDFS and for the Hive Metastore

General
---------
* Remove user cpu time tracking
* Make cost-based decision when selecting Join distribution type
* Remove min/max intersection heuristics from equality stats calculator
```

**Comment by wenleix** [comment]
```
General
---------------
Improve row to row case performance.

Hive
-----
Prevent ORC writer write huge stripes due to converting highly dictionary compressed columns to direct encoding.
```
