### ISSUE TITLE
Cannot access presto-admin commands on passwordless VPS

### ISSUE THREAD

**Issue by bradatefi** [prestodb/presto#11393]
Using Ubuntu 16.04 as either root or user with sudo access and PasswordAuthentication no

When typing a command such as 
# ./presto-admin catalog add cassandra
OR
# ./presto-admin catalog add cassandra -p <mypassword>
OR 
# ./presto-admin catalog add cassandra -I
(prompted for 'Initial value for env.password:')

Am always getting following response

Deploying cassandra.properties catalog configurations on: localhost 

Fatal error: [localhost] Needed to prompt for a connection or sudo password (host: localhost), but input would be ambiguous in parallel mode

Aborting."

**Comment by kokosing** [comment]
Does the user who is running presto-admin commands is able to do passwordless ssh connection to localhost?

**Comment by findepi** [comment]
@bradatefi please move this issue @ https://github.com/prestodb/presto-admin

**Comment by bradatefi** [comment]
Was able to log in as a non root user on Ubuntu 16.04 only when I changed the following settings in 'sshd_config' file PasswordAuthentication yes, ChallengeResponseAuthentication yes and issued password (eg '-p <password>') or '-I' after presto-admin command.  I have presto-server-0.149 in my user's home directory and have successfully run the commands '# bin/launcher start' and 'bin/launcher run'.  I have also been able to run the CLI by typing a command such as './presto --server localhost:8080 --catalog cassandra --schema default'.

I have a Scylla keyspace called 'mk', however when I try to access it with a command like this
presto:default> select * from cassandra.mk.leads;
In response I get "Catalog cassandra does not exist"

When I go into prestoadmin and type the following, 
# ./presto-admin catalog add cassandra -p <password>
I get the following:
"Warning: [localhost] sudo() received nonzero return code 42 while executing '( getent passwd presto >/dev/null || exit 42 ) && mkdir -p /etc/presto/catalog && chown presto:presto /etc/presto/catalog && chmod 755 /etc/presto/catalog '!
Fatal error: User presto does not exist. Make sure the Presto server RPM is installed and try again"

running the following command below gives "Warning: [localhost] Presto is not installed."
# ./presto-admin server start -p <password>

I feel like I am very close on this but I'm not quite able to connect Presto with my ScyllaDB keyspace and I'm not exactly sure which direction I need to go into.  Would moving to CentOS help solve the issue or is it possible to run this in Ubuntu 16.04?

**Comment by kokosing** [comment]
What do below commands return to you?
 - `getent passwd presto`
 - `sudo rpm -qa | grep -i presto`

**Comment by kokosing** [comment]
What about `getent passwd presto; echo $?`?

From what you said, it looks like presto-admin was right saying that: `User presto does not exist. Make sure the Presto server RPM is installed and try again"`. Have you installed Presto via presto-admin (see https://prestodb.io/presto-admin/docs/current/installation/presto-server-installation.html)?

**Comment by kokosing** [comment]
To install Presto on Ubuntu just follow the https://prestodb.io/docs/current/installation/deployment.html.
