### ISSUE TITLE
can presto achieve 1 billion data second response ? 

### ISSUE THREAD

**Issue by hiliuxg** [prestodb/presto#11409]
hi :
I have 1 billion rows ,about 10GB data in hdfs .  I want to implement second-level interactive query and analysis by complex sql like count(distinct )，group  by and so on  . Can presto cluster with  10 machines, by 64g memory of each chieve it ?  Somewhere config or  some other open source projects that can be combined with presto to improve performance ? 

I am very eager to hear your suggestions. thank you !

**Comment by dain** [comment]
Unfortunately, that is not something that can be answered without knowing the exact details of the application (data, queries, hardware, and so on), and even then you really need to just try it.  Other things you left off is, the concurrency, the execution time, and the percent of this data set scanned by each query.  Also, in Hive you have the added complexity of file formats and compression algorithms.  With some formats you can select out subsets of the columns efficiently, and in others you have to decode the whole row.

So, I’d just recommend trying it out on cloud provider like AWS.

-dain

**Comment by hiliuxg** [comment]
My machine configuration is 32 core 64 g and my file is in orc format . My requirement  is to use presto as a query engine for daily analysis  of  BI tools.  Let me thing again . Very grateful to answer my question .
