### ISSUE TITLE
Add possibility to set distributed_join session property on jdbc driver

### ISSUE THREAD

**Issue by Slav4ik** [prestodb/presto#11410]
My app uses both http connector and jdbc (for legacy)
In the http connector i can set my own session properties while in the jdbc connection im bound to a small finite group of properties.

Specifically, I need to abuse the distributed_join = false option when using the jdbc connector.

**Comment by rschlussel** [comment]
FYI the distributed_join session property is deprecated since 0.207 (it's been renamed).  You should use `join_distribution_type='PARTITIONED'` for `distributed_join=true` and `join_distribution_type='BROADCAST'` for `distributed_join=false`

**Comment by electrum** [comment]
There are two ways to set session properties in the JDBC driver. One way is to execute `SET SESSION` on the `Connection` before you run the query (on the same connection used for the query). The other way is to call a Presto-specific method:
```java
Connection connection = DriverManager.getConnection(...);
PrestoConnection pc = connection.unwrap(PrestoConnection.class);
pc.setSession("join_distribution_type", "BROADCAST");

**Comment by Slav4ik** [comment]
@rschlussel thank you! we know, yet we dont move to latest build so soon
@electrum the second solution seems great! thanks!
