### ISSUE TITLE
Presto connection to Hive gives error on select

### ISSUE THREAD

**Issue by tdcb** [prestodb/presto#11414]
I have set up two virtual machines. One with Teradata presto 203 (on redhat linux 7), and other with HDP 2.6 from the Kylo VM. When I run describe from presto on a managed table, it works fine. But select gives me an error. Please see the below log :

presto> use hive.toy_store;
USE
presto:toy_store> describe products;
       Column       |  Type   | Extra | Comment
--------------------+---------+-------+---------
 productcode        | varchar |       |
 productname        | varchar |       |
 productline        | varchar |       |
 productscale       | varchar |       |
 productvendor      | varchar |       |
 productdescription | varchar |       |
 quantityinstock    | varchar |       |
 buyprice           | double  |       |
 msrp               | double  |       |
 processing_dttm    | varchar |       |
(10 rows)

Query 20180904_150104_00021_zhvt9, FINISHED, 1 node
Splits: 19 total, 19 done (100.00%)
0:01 [10 rows, 746B] [13 rows/s, 998B/s]

presto:toy_store> select count(*) from products;

Query 20180904_150115_00022_zhvt9, FAILED, 1 node
Splits: 17 total, 0 done (0.00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20180904_150115_00022_zhvt9 failed: Failed to list directory: hdfs://sandbox.kylo.io:8020/app/warehouse/toy_store/products

--------------------------------------------------------------------------------

I have checked all permissions, modified the users - but none of them worked. I added the hive config properties as well to see if it works, but it did not.

Please suggest if I have missed on any properties to tap into.

**Comment by findepi** [comment]
This means that Presto can reach Hive Metastore and so it can show you the schema of the table. However, for some reason, Presto cannot reach the HDFS. Please make sure the HDFS is reachable from the machine running Presto.

**Comment by tdcb** [comment]
Thanks for the reply Piotr. I have disabled the firewalls on my Kylo vm. However, it still is unable to get through to the HDFS. Can you help me with a scenario that I can try ?

**Comment by tdcb** [comment]
I have enabled the firewall, explicitly opened ports 50010, 50020, 50090, 50070, 50075 and 1019. Hortonworks manual specifies these ports as being used by the server. Still no luck.

**Comment by tooptoop4** [comment]
core-site.xml on hadoop machine will have   something like, take the port bit and use further down:
  <name>fs.default.name</name>
    <value>hdfs://localhost:9000</value>

From host running hadoop:
nc -z localhost <port from above>
ie nc -z localhost 9000
If that works then try remotely from host running presto:
ie nc -z host_with_ hadoop <port from above>
ie nc -z host_with_ hadoop 9000

https://stackoverflow.com/questions/18322102/hadoop-connection-refused-on-port-9000
https://stackoverflow.com/questions/26216876/find-port-number-where-hdfs-is-listening

Next try webhdfs upload from the presto host

If these dont work its not presto issue

**Comment by tdcb** [comment]
Thanks mate. I got that it is my hadoop vm that is causing the pain. The connection to hdfs is being blocked for some reason, even though i tried out everything to enable ports (8020,50070) and infact disabling the firewall altogether. Will try again with another VM instead of the KYLO vm.

**Comment by JWenBin** [comment]
Your issue is the same with mine. But my hive works well, and I can select successfully in  hive.  Still confusing.......

**Comment by manna018** [comment]
same issue
