### ISSUE TITLE
WITH ORDINALITY column is unnamed

### ISSUE THREAD

**Issue by oneonestar** [prestodb/presto#11429]
```sql
presto> SELECT * FROM UNNEST(array[
     ->      CAST(ROW('a', 1) AS ROW(x varchar, y int)),
     ->      CAST(ROW('a', 1) AS ROW(x varchar, y int))
     ->      ]) WITH ORDINALITY;
 x | y | _col2
---+---+-------
 a | 1 |     1
 a | 1 |     2
(2 rows)
```

The additional ordinality column is an unnamed column, which is difficult to select.
@martint Do you know how we should name this column, according to the SQL specification?

Related PR: #11193 #10883

**Comment by martint** [comment]
The spec is very vague about it:

```
Let Nj, 1 (one) ≤ j ≤ NCV, and NORD be NCV+1 <column name>s that are not equivalent to one
another nor to CN, TEMP, or any other <identifier> contained in TP.
```
`NORD` is the *ordinality column* derived from the `WITH ORDINALITY` clause.

In Presto, we just choose to make it an anonymous column, since assigning a random name is not very useful, either.

**Comment by haozhun** [comment]
In case it's not obvious, you could do 

```
SELECT * FROM UNNEST(array[
     CAST(ROW('a', 1) AS ROW(x varchar, y int)),
     CAST(ROW('a', 1) AS ROW(x varchar, y int))
     ]) WITH ORDINALITY t(x,y,z);
```

**Comment by oneonestar** [comment]
@haozhun In our table, we have more than 40+ columns in a row. It will be very inconvenient to use column aliases to provide an identifier to the ordinality column.

@martint Is it possible to give a default alias name to the ordinality column, and throw an error then the alias name is duplicated? Although this will violate the standard, it will make the column easy to refer to. Especially after #10883 

---
Just some searching:
In **PostgreSQL**, they use the name _'ordinality'_ for the ordinality column.
Ref: https://paquier.xyz/postgresql-2/postgres-9-4-feature-highlight-with-ordinality/

In **BigQuery**, they use the name _'offset'_ for the ordinality column.
If the array contains the same identifier, they will return an error: "Duplicate table alias offset in the same FROM clause"

They also provide syntax for specifying the alias name:
{ UNNEST( array_expression ) | UNNEST( array_path ) | array_path }
       [ [ AS ] alias ] [ WITH OFFSET [ [ AS ] alias ] ]
Ref: https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax

**Comment by rongrong** [comment]
cc @kaikalur

**Comment by pakming** [comment]
Same issue - 60+ columns in the exploded table and it's hard to access the unnamed ordinality column.

**Comment by sarathdeevi** [comment]
Yes, this is still an issue, we would like to access the ordinality column with an alias to further use in queries.

**Comment by rongrong** [comment]
@pakming  @sarathdeevi did you guys try the `WITH ORDINALITY t(x, y, z)` solution? You can give the column names that way.

**Comment by sarathdeevi** [comment]
@rongrong yes, we did try, but that forces us to list all the columns present in the table, and then alias the ordinality column.
