### ISSUE TITLE
Have Configurable ACL Policies in S3 Filesystem

### ISSUE THREAD

**Issue by kash159** [prestodb/presto#11445]
We are in a situation where we have multiple accounts and files uploaded from Presto to S3 by one account is not readable by the other account due to object level ACL policies. I know that we can have a custom S3 credentials provider but it will break backwards compatibility with existing data. 

I think we can use the withCannedAcl method of the PutObjectRequest class in PrestoS3FileSystem.java file to help solve this problem. What does the community think? Happy to contribute back.

**Comment by electrum** [comment]
cc @nezihyigitbasi, @zhenxiao

**Comment by kash159** [comment]
@electrum @zhenxiao @nezihyigitbasi I did a PR here: https://github.com/prestodb/presto/pull/11491

**Comment by kash159** [comment]
Merged with #11491
