### ISSUE TITLE
ST_Collect (or Similar?)

### ISSUE THREAD

**Issue by voycey** [prestodb/presto#11451]
Is there anything that takes the place of ST_Collect? It would help us in moving over items from PostGIS verbatim.

For example I am trying to create a convex hull over a few billion points that are identified by a cluster_id:

    cid, lat, lng

A simple PostGIS query would be something like:

    SELECT c.cid, ST_ConvexHull(ST_Collect(c.cid)) as geom
	FROM c_clustered As c
	GROUP BY c.cid;

However any aggregations I try and use in Presto means I have to aggregate each.

I can see some functions and issues relating to:

    convex_hull_agg(Geometry) → Geometry

Returns the minimum convex geometry that encloses all input geometries. This function doesn’t support geometry collections.

    geometry_union_agg(Geometry) → Geometry

Returns a geometry that represents the point set union of all input geometries.

But lacking any documentation for how to actually use them or how to solve the aggregation problem - can you provide any pointers as to how I can work around the ST_Collect thing?

Thanks :)

**Comment by mbasmanova** [comment]
@voycey Dan, I think you can use `convex_hull_agg` aggregate function like so:

```
SELECT c.cid, convex_hull_agg(ST_Point(lng, lat)) as geom
FROM c_clustered As c
GROUP BY c.cid;
```

**Comment by voycey** [comment]
I think I tried this but it didn't like the fact that convex_hull_agg wasnt
aggregated or in the group, I'll try again tomorrow and let you know!

**Comment by voycey** [comment]
Never mind I was on 0.206 :( will upgrade and test!

Thanks Maria!

**Comment by mbasmanova** [comment]
`convex_hull_agg` function was added in 0.209: https://prestodb.io/docs/current/release/release-0.209.html

**Comment by mbasmanova** [comment]
@voycey Dan, I'm closing this issue assuming that `convex_hull_agg` function is sufficient for your use case. Feel free to reopen if there is anything else that remains unresolved.

**Comment by voycey** [comment]
Hi Maria,

There are some problems installing 0.210 on Google Dataproc but it does look like this will solve it - am investigating and will raise a ticket if I can't figure it out :) Thanks!

**Comment by voycey** [comment]
Hi Maria,

This is sorted now - works a treat!

**Comment by mbasmanova** [comment]
@voycey Thanks for the update, Dan. Happy to hear Presto is working for you :-)
