### ISSUE TITLE
See all properties for a query

### ISSUE THREAD

**Issue by thoralf-gutierrez** [prestodb/presto#11458]
Hello everybody,

I'm trying to help our users debug their queries and I am looking for a place where I can see all the properties used by a query (Presto defaults + config.properties + session properties). They can see the session properties in the query details page, I don't know how they could see the config.properties file and they can look at the Presto defaults in the Presto docs.

Is there a place where they are all avaliable together? Or at least session properties + what is in config.properties?

For example, Spark has something similar in its Spark UI in the [Environment tab](https://jaceklaskowski.gitbooks.io/mastering-apache-spark/spark-webui-environment.html).

Thanks!

**Comment by thoralf-gutierrez** [comment]
Nice! That's a great start and goes almost all the way. The only thing that could be missing is historical inspection after the fact.

Do you think it would make sense to, in a first instance, add the same information to the json query details api (`/v1/query/xyz`) and then maybe later to the UI? I could give it a shot if it is valuable.

**Comment by findepi** [comment]
How long would you like to be able to retrospect?
Usually, a person troubleshooting user's problem knows the cluster configuration and can compare it with customized session properties as visible in the web UI. In that case, knowing the diff (the customized session properties) is the more useful information... I don't yet understand why this approach isn't working in your case.

**Comment by thoralf-gutierrez** [comment]
I can think of many examples where the person helping debug wouldn't know the cluster configuration, such as when asking for help from other users (online or within the company) or when dealing with multiple clusters that are configured differently and you want to avoid the extra hop of figuring out the configuration for that particular cluster.

Though if this isn't something that resonates with more people I'll just make do with the existing limitations.

**Comment by findepi** [comment]
@raghavsethi would it be possible to stick `show session`-like information in the web UI without overloading the display for those that don't need this kind of "full" listing?

**Comment by raghavsethi** [comment]
The question is more about how to get all the information associated with the query, the Web UI is really a minor part of this whole project. Or we could create another page that is not linked to a query that just exposes all cluster configuration.

**Comment by zhangminglei** [comment]
@raghavsethi It's a good idea I think.

**Comment by raghavsethi** [comment]
Maybe, but it does not address @thoralf-gutierrez 's point about after-the-fact. Although the Spark page does not do that either.
