### ISSUE TITLE
ThriftIndexHandle toString has raw TupleDomain

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#11456]
It needs to properly convert the `TupleDomain` into a string, as `TupleDomain` does not have a `toString` method.

**Comment by findepi** [comment]
AFAIR, `TupleDomain` can be stringified only in the context of `Session`, that's why there is no `TupleDomain#toString` implemented.

**Comment by findepi** [comment]
@electrum maybe we try remove session from `com.facebook.presto.spi.type.Type#getObjectValue(ConnectorSession session, Block block, int position)`?

**Comment by mbasmanova** [comment]
@electrum David, 

> maybe we try remove session from com.facebook.presto.spi.type.Type#getObjectValue(ConnectorSession session, Block block, int position)?

The session is used only in 2 places: TimestampType and TimeType:

```
if (session.isLegacyTimestamp()) {
            return new SqlTimestamp(block.getLong(position, 0), session.getTimeZoneKey());
        }
        else {
            return new SqlTimestamp(block.getLong(position, 0));
        }
```

Can I change these to `return new SqlTimestamp(block.getLong(position, 0));`?

**Comment by findepi** [comment]
@mbasmanova Maria, i didn't check that, sorry..
- legacy timestamp is currently the default.  
- isn't this method used for returning data to the client? if so, the cited `if` is very important.

**Comment by mbasmanova** [comment]
@findepi @electrum  How about if I add `String toString(ConnectionSession session)` to `IndexHandle` and wherever else it would be needed to make things compile?

**Comment by electrum** [comment]
Handles are intended to be opaque references. They should not have methods. If we want to have a method that uses a handle, it should go somewhere else, like `ConnectorMetadata`.

The easiest thing to do is to simply remove it: #11610

**Comment by electrum** [comment]
I figured out how to add the constraint to the handle.
