### ISSUE TITLE
Predicate Pushdown for DECIMAL in JDBC connectors

### ISSUE THREAD

**Issue by rpwils** [prestodb/presto#11467]
From our experience we have not been able to perform any sql pushdown from presto to redshift.  Presto brings back the entire dataset then applies the filters.  Based on this closed issue it seems that it should work?
https://github.com/prestodb/presto/issues/10578

Can you help me understand if it in fact should work?

thanks!

**Comment by findepi** [comment]
Can you include your simplest possible example of a query along with table DDL?

**Comment by rpwils** [comment]
Here is a simple example, it seems numeric types do not allow predicate pushdown?
 CREATE TABLE obs.num_value
(
   num_value       numeric(38), 
   is_deactivated               varchar(16383)
);

select * from obs.num_value  where num_value = 2910849

**Comment by findepi** [comment]
Which version are you on?
I've recently witnessed a problem with pushdown for DECIMALs, but I don't remember if the fix was landed.

**Comment by rpwils** [comment]
we run this in EMR so the version of presto is 0.196
