### ISSUE TITLE
information_schema.hive_partitions feature

### ISSUE THREAD

**Issue by tooptoop4** [prestodb/presto#11466]
Would be great for presto to be able to query a table that has table_name, partition_pk, partition_name, partition_value. (i assume this can be derived from PARTITIONS in the hive metastore but without having to manage a separate mysql catalog connection)
ie tbl_accounts, 1, eod_dte, 20180806
 tbl_accounts, 2, eod_dte, 20180807
 tbl_accounts, 1, eod_seq, 1
 tbl_accounts, 2, eod_seq, 1

then user can do queries like:
 select * from tbl_accounts t
where eod_dte in (select max(partition_value) from information_schema.hive_partitions
where table_name = 'tbl_accounts' and partition_name = 'eod_dte' )

**Comment by kokosing** [comment]
It is provided as a dynamic system table in hive connector, you can query like:
```
select * from tbl_accounts$partitions;
```

**Comment by tooptoop4** [comment]
@kokosing where is documentation for it?

**Comment by kokosing** [comment]
https://prestodb.io/docs/current/release/release-0.199.html

```
Hive Changes
...
* Partitioned tables now have a hidden system table that contains the partition values. A table named example will have a partitions table named example$partitions. This provides the same functionality and data as SHOW PARTITIONS.
```

**Comment by tooptoop4** [comment]
Are there any other 'hidden system tables' i should know about? i can see how being only in release notes can get missed

**Comment by tooptoop4** [comment]
problem with $partitions is that it is only for 1 table so you can't easily say find me all tables with partition of 20180807
