### ISSUE TITLE
guice 'already configured' error making DistributedQueryRunner standalone.

### ISSUE THREAD

**Issue by vrdhn** [prestodb/presto#11470]
Hi,
  Trying to write a small program , and reduced it to :
```
public static void main (String[] args) throws Exception{
    Session session = testSessionBuilder()   .build();
    DistributedQueryRunner queryRunner = new DistributedQueryRunner(session, 4);
 ```
This is causing error:
```
1) A binding to java.util.Set<com.facebook.presto.spi.procedure.Procedure> was already configured at com.facebook.presto.connector.system.SystemConnectorModule.configure(SystemConnectorModule.java:74) (via modules: com.facebook.presto.server.ServerMainModule -> com.facebook.presto.connector.system.SystemConnectorModule -> com.google.inject.multibindings.Multibinder$RealMultibinder).
  at com.facebook.presto.connector.system.SystemConnectorModule.getKillQueryProcedure(SystemConnectorModule.java:85) (via modules: com.facebook.presto.server.ServerMainModule -> com.facebook.presto.connector.system.SystemConnectorModule -> com.google.inject.internal.RealMultibinder)
```
This worked till 0.199.
Is this an unsupported flow ? 
Should I be doing some more setup before building DistributedQueryRunner?
TIA

**Comment by dain** [comment]
Maybe start with https://github.com/prestodb/presto/blob/master/presto-hive/src/test/java/com/facebook/presto/hive/HiveQueryRunner.java#L197 as an example.  We only use that for testing, so it might need a bunch of tweaking.

**Comment by haozhun** [comment]
> Is this an unsupported flow ?

Using Presto as a library is not supported.

However, you should be able to tweak it to make it work, although you may need to make adjustments from time to time.

**Comment by vrdhn** [comment]
Ok Thanks a lot for the answers and pointers.
Regards
