### ISSUE TITLE
Document SHOW STATS syntax

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#11486]
SHOW STATS command can be used to look up statistics for a given partition, but it is missing from the documentation.

**Comment by mbasmanova** [comment]
CC: @arhimondr @rschlussel @arbass22

**Comment by findepi** [comment]
a side note: SHOW STATS is quite imperfect. It accepts `SHOW STATS FOR (query)` form, which has 2 problems:
- minor: requires parenthesis, which isn't consistent with EXPLAIN (and is less useful to type in CLI)
- accept only with simplest queries, effectively showing TableScan output stats, with pushdowned predicates applied
-- we wanted to extend that for any kind of queries, showing output stats for the OutputNode

Would that be helpful to you as a compliment to https://github.com/prestodb/presto/issues/11432?

**Comment by mbasmanova** [comment]
@findepi Piotr, I don't have a specific need right now, but I can see how it could be useful to show stats for arbitrary queries. This would allow troubleshooting stats propagation through non-trivial filters, aggregations, etc.

**Comment by findepi** [comment]
Exactly. Of course, this would have its own limits as well. Let me mention that, so that we don't have an illusion it will solve all our problems.
Eg. if a query has a partial aggregation, it always has a final one. So if we have wrong stats after partial but correct ones after final (it is inconceivable), SHOW STATS will show reasonable output. Still, optimizer can make decisions on the "partial level", choosing incorrectly.
Anyway, i do believe more flexible `SHOW STATS <query>` is useful, we just didn't implemented it.

**Comment by mbasmanova** [comment]
@findepi Piotr, 

> Still, optimizer can make decisions on the "partial level", choosing incorrectly.

I thought that the optimizer operates on a plan where aggregations haven't been split into partial and final yet. Is this not the case?

**Comment by findepi** [comment]
@mbasmanova -- today, correct.

**Comment by mbasmanova** [comment]
@findepi Piotr, I noticed that `SHOW STATS` query doesn't support `IN` and `BETWEEN`. Is this by design? How hard would it be to add support for these constructs?

```
presto> SHOW stats FOR ( SELECT * FROM t WHERE ds between '2018-08-29' and '2018-08-30' );
Query 20180919_005521_00197_s94mh failed: line 1:1: Only literals, column references, comparators, is (not) null and logical operators are allowed in WHERE of SHOW STATS SELECT clause

presto> SHOW stats FOR ( SELECT * FROM t WHERE ds in ( '2018-08-29' , '2018-08-30') );
Query 20180919_005534_00198_s94mh failed: line 1:1: Only literals, column references, comparators, is (not) null and logical operators are allowed in WHERE of SHOW STATS SELECT clause
```

**Comment by findepi** [comment]
@mbasmanova this comes from `com.facebook.presto.sql.rewrite.ShowStatsRewrite.Visitor#validateShowStatsWhereExpression` (of course). 
Looking at the code, i have no clue why IN or BETWEEN should be left out. I guess this is an omission. @kokosing  any idea?

**Comment by kokosing** [comment]
I guess this is an omission too. There is no reason why it should not work.
