### ISSUE TITLE
presto kudu connector 

### ISSUE THREAD

**Issue by AndyLeslie** [prestodb/presto#11482]
The version of presto  I installed is 0.189
When I add the kudu connector, I get an the error ,'com.facebook.presto.server.PrestoServer No factory for connector kudu',when running presto.

Thank you！
The following is kudu.properties configuration

connector.name=kudu

##                    [2001:db8::1], [2001:db8::1]:7051, 2001:db8::1
kudu.client.master-addresses=ta1:7051
kudu.schema-emulation.enabled=true
kudu.schema-emulation.prefix=

#######################
#######################

## Default timeout used for administrative operations (e.g. createTable, deleteTable, etc.)
kudu.client.default-admin-operation-timeout = 30s

## Default timeout used for user operations
kudu.client.default-operation-timeout = 300s

## Default timeout to use when waiting on data from a socket
kudu.client.default-socket-read-timeout = 300s

## Disable Kudu client's collection of statistics.
#kudu.client.disable-statistics=true

**Comment by kokosing** [comment]
https://github.com/prestodb/presto/pull/12031
