### ISSUE TITLE
Ability to hide passwords from catalog connector config files

### ISSUE THREAD

**Issue by tooptoop4** [prestodb/presto#11494]
Rather than have passwords (ie mysql, redshift or others) in plaintext could use a jceks to store the password like in below example:

https://mapr.com/blog/5-steps-to-remove-hive-metastore-password/

**Comment by findepi** [comment]
This has been discussed on the user group in the past: https://groups.google.com/d/topic/presto-users/X-K5vmkiWus/discussion
Would you be so good as to reply to @electrum's last question in that thread?
> Can you explain more about the problem you are trying to solve?

**Comment by tooptoop4** [comment]
We are trying to deploy Presto in large, highly regulated corporation (10k+ employees) which handles sensitive customer data. Problem is our 'enterprise security' team have to approve all new app deployments and they want to block our presto deployment due to the fact plaintext db passwords are visible in these properties files.

**Comment by tooptoop4** [comment]
gentle ping

**Comment by tooptoop4** [comment]
https://github.com/prestosql/presto/pull/1124

**Comment by hadoopstack** [comment]
i found this to be relevant to this thread.
hope it helps: 

Trino release notes: https://trino.io/docs/current/release/release-322.html
Github Code merge: https://github.com/trinodb/trino/pull/1521

**Comment by tooptoop4** [comment]
yet to try:
Trino release notes: https://trino.io/docs/current/release/release-322.html
Github Code merge: trinodb/trino#1521

**Comment by nineinchnick** [comment]
@tooptoop4 is this issue resolved now?
