### ISSUE TITLE
Optimize array_intersect 

### ISSUE THREAD

**Issue by wenleix** [prestodb/presto#11493]
Profiling against production workloads shows `array_intersect` over huge arrays can be very expensive due to sort, and takes about `6%` in the sample.

![screen shot 2018-09-14 at 4 53 42 pm](https://user-images.githubusercontent.com/799346/45579763-5f880400-b83f-11e8-9e11-c6595f39f057.png)

We should be able to optimize it with `TypedSet`.

**Comment by amitdesai03** [comment]
hi @wenleix , was looking to get involved in presto OSS. Found this begineer task.

From what it looks to me, TypedSet will grow to size of min(sizeof(array1),sizeof(array2)) which can be huge if both arrays are equally huge.

I have typically seen use of RoaringBitmap to solve intersect on large arrays. Its fast data structure with smaller memory footprint than hashsets.

https://github.com/RoaringBitmap/RoaringBitmap

First we generate bitmap from smaller array,
https://github.com/RoaringBitmap/RoaringBitmap/blob/master/roaringbitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java#L262

And than when we traverse second larger array, we check if pre-present
https://github.com/RoaringBitmap/RoaringBitmap/blob/master/roaringbitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java#L1387

Another probably faster way could be to form 2 roaring bitmaps from both arrays and perform intersect on it:
https://github.com/RoaringBitmap/RoaringBitmap/blob/master/roaringbitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java#L627

**Comment by yingsu00** [comment]
@amitdesai03 Hi Amit, the RoaringBitmap is definitely interesting, but we need to fix this soon so I will work on it using the TypedeSet for now. Please feel free to create a new issue and try the RoaringBitmap solution. Thank you!

**Comment by dain** [comment]
I wonder why this was written using sort in the first place.  Isn't the more natural solution to build a set out of the left elements, and then for each right element attempt to add it and if it was new, add that element to the output?  Also, this function can work without any copying using dictionary blocks like we did with the `ngram` function.

**Comment by wenleix** [comment]
@dain: `array_interasect` was added in February, 2015 in https://github.com/prestodb/presto/pull/2408, which is prior to `TypedSet` (May 2015). 

@cberner did suggested to use hash map to optimize optimize the function: https://github.com/prestodb/presto/pull/2408#discussion_r25380098 . However it ends up with using sort.

**Comment by tdcmeehan** [comment]
@yingsu00 fixed this with #11984
