### ISSUE TITLE
Presto cannot list the directory on HDFS

### ISSUE THREAD

**Issue by tdcb** [prestodb/presto#11507]
I am running an instance of Presto on a redhat VM, and a KYLO VM. When i try to connect from presto to HDFS, it fails stating :
Query 20180918_121838_00018_c3ptc failed: Failed to list directory: hdfs://**localhost**:8020/user/hive/warehouse/system.db/skills_csv_feed

The IP of my KYLO VM is 192.168.225.131.

Below is the hive.properties from presto catalog :
connector.name=hive-hadoop2
hive.metastore.uri=thrift://192.168.225.131:9083
hive.config.resources=/usr/chirag/presto/hadoopconf/core-site.xml,/usr/chirag/presto/hadoopconf/hive-site.xml

core-site.xml has the defaultFS defined as :
  <property>
    <name>fs.defaultFS</name>
    <value>hdfs://sandbox.kylo.io:8020</value>
  </property>

hive-site.xml has metastore uri as :
  <property>
    <name>hive.metastore.uris</name>
    <value>thrift://sandbox.kylo.io:9083</value>
    <description>IP address (or fully-qualified domain name) and port of the metastore host</description>
  </property>

If I list tables or schemas, it works. So the metastore is reachable with the parameters I have set. 

What other parameters can I check ?

**Comment by findepi** [comment]
i bet this is obsolete.

**Comment by trishabh5050** [comment]
I am facing the same issue.@tdcb -Did you get the answer to this.If yes please let me know
