### ISSUE TITLE
Allow configuring of Parquet writer settings

### ISSUE THREAD

**Issue by piyushnarang** [prestodb/presto#11512]
Currently, Presto uses the default values for Parquet's block size (128M) / page size (1M) settings while writing out data using the Parquet writer. It would be nice to expose these settings (similar to the `hive.orc.writer.*` configs: https://github.com/prestodb/presto/blob/master/presto-hive/src/main/java/com/facebook/presto/hive/OrcFileWriterConfig.java) so that users can configure them to be different from by the Parquet library defaults.

**Comment by piyushnarang** [comment]
Thoughts @nezihyigitbasi / others ?

**Comment by piyushnarang** [comment]
Ok thanks @dain / @zhenxiao, I'll take a stab at this over the next few days.

**Comment by zhenxiao** [comment]
the problem is resolved
