### ISSUE TITLE
Add ROWID support to get a ROW_NUMBER surrogate

### ISSUE THREAD

**Issue by leonpanokarren** [prestodb/presto#11546]
**What**
___
Introduce `ROWID` support that provides a unique reference to every row read from a dataset. This does not have to be **"`continuous`"** (i.e. `ROWID`s for a 1 billion row dataset don't have to range from 1 to 1B); it doesn't even have to be a number. As long as it is -  

1. **unique**, and **deterministic** _for each physical row read_, AND is 
2. **cheap** to compute

it can provide a terrific alternative to `ROW_NUMBER()` which is often used to achieve this featureset. 

**Why**
___
This can help address several use cases that need a unique identifier when the dataset doesn't have an (obvious) key like - 

1. debugging and tracing data back from downstream 
2. cases that need unique row references that currently use `row_number` or a similar proxy - but this ends up being very inefficient

**Comment by findepi** [comment]
There is `AssignUniqueId` internally used by the planner when rewriting the queries, so technically it looks feasible.

@martint how this could look like from SQL language perspective?

**Comment by darrenfu** [comment]
What is the downsides of adopting row_number() instead?

We also have a privacy need to implement a deterministic random function. This rowid would definitely help as the hashkey to generate a deterministic random value. 

Need to reopen this issue.
