### ISSUE TITLE
SHOW STATS column projection

### ISSUE THREAD

**Issue by arbass22** [prestodb/presto#11543]
The SHOW STATS command accepts column projections in the form SHOW STATS FOR (SELECT column1 FROM table), however they are not applied.  We should probably implement this or disallow it.

**Comment by kokosing** [comment]
True, it should either error out or support them.

**Comment by kokosing** [comment]
@atris Would you like to fix this?

**Comment by findepi** [comment]
Superseded by https://github.com/prestodb/presto/issues/11551
