### ISSUE TITLE
Support spherical space computation in geospatial functions

### ISSUE THREAD

**Issue by gaoxm** [prestodb/presto#11580]
The current ST_* geospatial functions in Presto, such as ST_Distance, ST_Length, ST_Area, ST_Centroid, etc., assume the input Geometry objects are in a cartesian plane and don't support computation in spherical space. E.g. ST_Distance, ST_Area don't return results in meters and square meters when the input geometries represent shapes on the earth surface and contain points in lat/lon pairs.
This issue tracks the work of adding geospatial functions that support spherical space computation on geometry objects composed of lat/lon values. The whole process contains two phases:
1. Add a new SQL type SphericalGeometry to represent geometry objects composed of lat/lon values. Also add conversion functions between SphericalGeometry and Geometry.
2. Add the "spherical-space-version" of ST_* functions that operate on SphericalGeometry objects and return accurate results from spherical space computation. E.g. `ST_Distance(spherical_geometry_a, spherical_geometry_b)` will return results in meters, `ST_Area(spherical_geometry)` will return results in m^2, etc.

**Comment by mbasmanova** [comment]
#12315 introduced ST_Area for spherical geography type. Thank you @ochalouhi 

CC: @zhenxiao
