### ISSUE TITLE
Function

### ISSUE THREAD

**Issue by wpspombosousa** [prestodb/presto#11597]
Alguém pode me ajudar?
quero criar uma função para transformar Data ('2011-10-07') em formato de semana (sexta)
no MYSQL

**Comment by yuokada** [comment]
Could you use English?

**Comment by martint** [comment]
Take a look at the datetime function documentation (https://prestodb.io/docs/current/functions/datetime.html). In particular, `date_format` and `format_datetime`. By the way, this is Presto, not MYSQL, so if you're looking for help on how to do it in MYSQL you should ask here: https://dev.mysql.com/community/.
