### ISSUE TITLE
Make ST_Distance return null when one or both arguments are empty geometries

### ISSUE THREAD

**Issue by gaoxm** [prestodb/presto#11600]
According to SQL/MM Part 3 spec, `ST_Distance` should return `null` if either input is an empty geometry: http://jtc1sc32.org/doc/N1101-1150/32N1107-WD13249-3--spatial.pdf

The current implementation of GeoFunctions.stDistance() in Presto ultimately goes here in Esri, which returns NaN (the version used in Presto returns 0.0D / 0.0): https://github.com/Esri/geometry-api-java/blob/ecaedf4dd5acf00607023bcf9604380c0731e376/src/main/java/com/esri/core/geometry/OperatorDistanceLocal.java#L44-L45

We should fix this and make it return null in case either input is empty.

- with @mbasmanova

**Comment by pettyjamesm** [comment]
Looks like this issue can be closed since https://github.com/prestodb/presto/pull/11602 was merged.
