### ISSUE TITLE
Invalid result for min/max aggregation over floating point

### ISSUE THREAD

**Issue by findepi** [prestodb/presto#11622]
As stated in https://github.com/prestodb/presto/issues/8836#issuecomment-324999652:
```
select max(a) from (values nan(), 1.0) t(a); -- NaN
select max(a) from (values 1.0, nan()) t(a); -- 1.0
```

Related: https://github.com/prestodb/presto/issues/8836, https://github.com/prestodb/presto/issues/11621, https://github.com/prestodb/presto/pull/8841

**Comment by findepi** [comment]
@ebyhr you fixed https://github.com/prestodb/presto/issues/8836. Would you like to fix this one too?

**Comment by ebyhr** [comment]
@findepi Yes, I will send the PR later!
