### ISSUE TITLE
Cannot load file from presto plugin code (system-access-control plugin)

### ISSUE THREAD

**Issue by gray-eb** [prestodb/presto#11629]
My question mainly boils down to this: Is it possible to load a file from the classpath within a Presto plugin? I have an xml file in the resources folder, but I can't seem to load it.

I'm working on configuring a presto-ranger plugin for SSL. Basically, I need an xml file to be available to the application so that it can be loaded by the ranger specific plugin code, but I can't seem to make this happen.

The code that loads the configuration I need is as follows:

` 
Configuration conf = new Configuration();
`
`
in = this.getFileInputStream(this.mSslConfigFileName);               
`
`
 if (in != null) {
      conf.addResource(in);
}
`

where this.mSslConfigFileName is a path to the xml file which contains the SSL config, and this.mSslConfigFileName is pulled from access-control.properties.

Is there a specific way to make resources available within a plugin? Is it possible to load this xml file?

**Comment by findepi** [comment]
It is possible but you may need to set up Thread context class loader (TCCL) first. Use `ClassLoaderSafeConnectorMetadata` (or other `ClassLoaderSafeConnector*` as needed) to do this.

BTW user group is a better place for this kind of questions. 
I am closing this one, but you can still comment here if you need further clarification on this topic.
