### ISSUE TITLE
Add ${prefix} before table names for TPC-DS queries in Benchto

### ISSUE THREAD

**Issue by wenleix** [prestodb/presto#11652]
This is done for queries in TPCH: https://github.com/prestodb/presto/blob/83b8c96ebbb8e98425aab0a679618853e767e407/presto-benchto-benchmarks/src/main/resources/sql/presto/tpch/q01.sql#L13

But not for TPC-DS:

https://github.com/prestodb/presto/blob/83b8c96ebbb8e98425aab0a679618853e767e407/presto-benchto-benchmarks/src/main/resources/sql/presto/tpcds/q01.sql#L8

Add `${prefix}` makes it easier when wants to run benchmarks over table with prefix.

**Comment by sopel39** [comment]
We don't use `${prefix}` internally anymore. Is there a specific use case that you are trying to address?

For different benchmarks we use different schemas (e.g: `100GB_ORC`)
