### ISSUE TITLE
Query Details skew visualisation is misleading

### ISSUE THREAD

**Issue by ilfrin** [prestodb/presto#11668]
![image](https://user-images.githubusercontent.com/6389448/46665826-2c7a2b80-cbc5-11e8-823d-521faad31a0f.png)

![image](https://user-images.githubusercontent.com/6389448/46665908-78c56b80-cbc5-11e8-89a0-0859f27aebe6.png)

As you can see on the attached images, the two columns suggest graphically that they are drastically different - that the skew is large, but in fact as you look at the tooltip actual values it isn't, they are the same ballpark figures. 

cc @raghavsethi

**Comment by raghavsethi** [comment]
Yes this is a KP. What heuristic would you suggest that would work in more cases?

**Comment by findepi** [comment]
@raghavsethi thoughts?
