### ISSUE TITLE
Bucketed Sort Files Should Utilize a Configurable Temporary Location

### ISSUE THREAD

**Issue by ddrinka** [prestodb/presto#11664]
I'm inserting rows into a bucketed sorted table located in S3.  To perform the sort, "sort files" are created and uploaded to a temporary directory adjacent to the table location.  These files are then retrieved and reintegrated into output files which are uploaded to the table location in S3.

It appears that is process will always take place on a single node.  As such, I'm not sure these sort files need to utilize HDFS storage.  The Presto S3 Filesystem driver doesn't appear to support streaming multipart uploads, so the storage space for the entire reintegrated file will already have to be available on the local node, so I'm already going to have to consider local storage space.  It would be much more efficient for my use case for the sort files to remain local throughout.

Said a different way, the current flow is as follows:
- Upload sort files to S3
- Download sort files from S3
- Create a temporary output stream in /tmp based on sort files
- Upload file from /tmp to S3

I propose the following flow, at least as a configuration option:
- Write sort files to /tmp
- Create a temporary output stream in /tmp based on sort files
  - Delete sort files as they're integrated to avoid doubling up on space?
- Upload file from /tmp to S3

**Comment by electrum** [comment]
Thanks for raising this issue. I had not considered S3 when I wrote that feature. Making it write the files to local disk (or another Hadoop file system) should be easy enough.

We could also change `TempFileReader` to take a `onClose` action that runs when the iterator is exhausted to delete the file immediately. Note that this will not help in the (likely common) case where all of the streams have the full range of values.

I filed a separate issue to track streaming for S3 writes: #11675
