### ISSUE TITLE
Can not add partitions for existing data to external table in presto ?

### ISSUE THREAD

**Issue by qli-aa** [prestodb/presto#11666]
Presto-0.206

1.CREATE table with partitioned_by, then insert data, queries partitions works

2.CREATE table with external_location and partitioned_by (map to existing data with partitions), then queries partitions does not work, I checked the hive metastore, there is no partitions meta for external table. How can I add it automatically or manually ?

Like HiveSQL, ALTER TABLE ADD PARTITION (p='xxx') LOCATION 'xxx';

**Comment by dain** [comment]
There is no equivalent of that in Presto yet.  We could add a stored procedure for to add partitions (this would be similar to the procedure for creating new empty partitions https://github.com/prestodb/presto/blob/master/presto-hive/src/main/java/com/facebook/presto/hive/CreateEmptyPartitionProcedure.java)

**Comment by ddrinka** [comment]
This would be super helpful for us.  We're using Athena to create our partitions in AWS Glue, but it introduces race conditions with the metastore cache.  It would be really great to have this functionality in Presto directly.

**Comment by ddrinka** [comment]
Also see #11174

**Comment by dain** [comment]
Presto doesn't have a metastore cache enabled by default anymore, so there shouldn't be any problems on our side.  That said, I agree we should have a way to do this in Presto directly.
