### ISSUE TITLE
Non deterministic functions seems to be not working

### ISSUE THREAD

**Issue by Tradunsky** [prestodb/presto#11674]
Hi,
I've created a function that generates UUID.
```@Description("Returns varchar representation of generated GUID")
    @ScalarFunction(value = "generateGUID", deterministic = false)
    @SqlType(StandardTypes.VARCHAR)
    public static Slice generateGUID() {
        final String uuid = UUID.randomUUID().toString();
        return Slices.utf8Slice(uuid);
    }
```

There is a case when it is not working as expected:
SELECT generateUUID(), name from person;

the output is:
```
c461e758-aa47-4a9a-b68a-7fa5123940da | Rick
c461e758-aa47-4a9a-b68a-7fa5123940da | Nick
```

I expecting generateGUID() function result would not be cached, if so it is not really non deterministic. What I really trying to catch is how the function rand() works fine in the same example?

Furthermore, deterministic function behaves as deterministic when you put it into temporary table values like this:
```
SELECT *
   FROM (
       VALUES
           (deterministicGenerateGUID()), (deterministicGenerateGUID())
   ) AS t
```

However, when it comes to testing, following test fails as soon as UUIDs are the same (putting @ScalarFunction(value = "generateGUID", deterministic = true)) and passes when they are different (@ScalarFunction(value = "generateGUID", deterministic = false)):
``` 
    @Test
    public void testGuidIsNotDeterministicFunctionEndToEnd() throws Exception {
        MaterializedResult result = getQueryRunner().execute(Utils.createSession(),
                "select generateGUID(), label from (values row('a'), row('b')) t(label) ");

        assertNotNull(result);
        final List<MaterializedRow> rows = result.getMaterializedRows();
        String generatedGuidForARecord = (String) rows.get(0).getField(0);
        String generatedGuidForBRecord = (String) rows.get(1).getField(0);

        assertNotEquals(generatedGuidForARecord, generatedGuidForBRecord);
    } 
```

The implementation of the function:
```
    @Description("Returns varchar representation of generated GUID")
    @ScalarFunction(value = "generateGUID", deterministic = false)
    @SqlType(StandardTypes.VARCHAR)
    public static Slice generateGUID() {
        final String uuid = UUID.randomUUID().toString();
        return Slices.utf8Slice(uuid);
    }
```

**Comment by haozhun** [comment]
This is a known issue. https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/sql/planner/DeterminismEvaluator.java

cc @martint since the code from 2013 says you should fix it.   :laughing:

**Comment by Tradunsky** [comment]
@haozhun Thank you for the quick replay!

**Comment by Tradunsky** [comment]
@haozhun Despite that hardcoded values, the function works as expected since 0.211 version of presto.

I had 0.198.

Closing the issue as far as it works in my case. Thanks to the community!
