### ISSUE TITLE
Query exceeded max memory size when like operate

### ISSUE THREAD

**Issue by zhaiyuyong** [prestodb/presto#11683]
```
select * from a.table_1 where pt='2018-10-09' and id like '%123456' limit 10;
```

```
Query 20181010_060653_03859_wve7n failed: Query exceeded max memory size of 500GB
```

**Comment by findepi** [comment]
Have a look at query JSON in the Web UI. It will show you where all the memory allocations were accounted.

**Comment by zhaiyuyong** [comment]
![image](https://user-images.githubusercontent.com/4199724/46720201-71c05b00-cca2-11e8-9a8d-8c6ed2a273a7.png)

**Comment by findepi** [comment]
@zhaiyuyong i see you found the json (https://user-images.githubusercontent.com/4199724/46720753-fc558a00-cca3-11e8-9630-5ed64c8f1b84.png). 
now you need to find the operator that has mem allocations.

**Comment by zhaiyuyong** [comment]
@findepi 
![image](https://user-images.githubusercontent.com/4199724/46722528-450f4200-cca8-11e8-99b9-b6be4dceee28.png)

**Comment by findepi** [comment]
This might be incorrect accounting of the memory. What is Presto version? What is the file format?

**Comment by zhaiyuyong** [comment]
file format:ORC
presto version:0.203

**Comment by zhaiyuyong** [comment]
@nezihyigitbasi could you provide an id of the issue？

**Comment by tsuxia** [comment]
Was wondering if this issue should be closed or not?
