### ISSUE TITLE
Support optionally refreshable file-based authorization

### ISSUE THREAD

**Issue by jyates** [prestodb/presto#11687]
Sometimes we need to add or retract user authorization very quickly - less than an hour - but don't want to disrupt user queries to update the authZ specification with a coordinator restart. Instead, we should be able to configure a refresh period in which the coordinator periodically reloads the on-disk configuration.

**Comment by jyates** [comment]
Patch coming shortly. Tried to making it somewhat general so it can be used across other ACL mechanisms easily.

**Comment by jyates** [comment]
Yup, just got caught up with internal stuff. Should have patch up later this week

**Comment by kokosing** [comment]
Fixed with: https://github.com/prestodb/presto/pull/11769
