### ISSUE TITLE
ConnectorAccessControl#checkCanCreateTable should accept properties of the to-be-created table

### ISSUE THREAD

**Issue by findepi** [prestodb/presto#11685]
For example, `hive.non-managed-table-creates-enabled` is implemented in `com.facebook.presto.hive.HiveMetadata#createTable` while this logic should probably belong more to `ConnectorAccessControl`

**Comment by dain** [comment]
@findepi is that the only use case?  If so, would this change make the end user behavior significantly better?

**Comment by findepi** [comment]
It just struck me today that `hive.non-managed-table-creates-enabled` is very much like `hive.allow-drop-table`, but in code they are not implemented together.
Admittedly, I don't have any other use cases in mind. I would just view this as a cleanup refactor.

**Comment by dain** [comment]
I would prefer not to expose properties to the access control because this would allow implementations to hack around the SQL security design and make decision on these extra properties (just like we don't expose session to security implementations).  Also for this use case, this seems like any other validation check we have on new tables in the Hive connector.  In this case, they user specified a property that isn't supported in that installation.

**Comment by kokosing** [comment]
`ConnectorFactory` gets config properties and then it could pass it to `Connector` and so to `ConnectorAccessControl`.

How would `ConnectorAccessControl` know that a table is `non-managed-table` vs `managed-table`?

**Comment by findepi** [comment]
> Also for this use case, this seems like any other validation check we have on new tables in the Hive connector. In this case, they user specified a property that isn't supported in that installation.

@dain If i understand you correctly, you mean something like that: "this warehouse does not use external tables" and such use makes a lot of sense to me. For this use-case, current impl is the best.

I was thinking about different use-case though: "only this, this and this user can create external tables, for security reasons". For this use-case, passing table properties would be needed.

I am closing this now, as the proposed change is clearly debatable. I will reopen when i can back this with real-life requirements.

**Comment by dain** [comment]
@findepi I think that is still possible since the `createTable` call on the metadata gets the session which contains the identity, so the connector can still make that check, it just can't do it during the analysis phase.
