### ISSUE TITLE
issue with "not in (select....)"

### ISSUE THREAD

**Issue by sophiewsmith** [prestodb/presto#11703]
I've recently experienced an issue where the "not in" function isn't working when combined with a select statement? It works when followed by a list of values, but not when followed by a select statement. However, the "in" command seems to work fine with both a list and a select statement. This hadn't been an issue before so I'm wondering if it's a bug or some recent change.

Examples:

The following query is not working successfully - it will pull 0 values no matter what:

select * from table1 where industry_sector not in (select industry from table2)

The following types of queries are still working successfully:

select * from table where industry_sector not in ('Medical', 'Legal')
select * from table1 where industry_sector in (select industry from table2)

**Comment by findepi** [comment]
@electrum answered this on the user group. Please continue discussion there.
