### ISSUE TITLE
Extending REST API

### ISSUE THREAD

**Issue by shlomialfasi** [prestodb/presto#11710]
I created a new connector which provides a set of new API's that I want to expose by REST.
Currently (according to my understanding) the REST code must be reside in the presto-main module where the jaxrs binder is handled.

Is there any other alternative where I can add this code in my own module without changing presto-main?

**Comment by dain** [comment]
There are no extension points for that in Presto.  Normally extra information or commands for a connector are exposed via system tables or procedures in the connector.

**Comment by electrum** [comment]
In particular, see `Connector.getSystemTables()` and usages of that in existing connectors.

**Comment by rschlussel** [comment]
Closing, as the question was answered.
