### ISSUE TITLE
Slow tests in prest-tests

### ISSUE THREAD

**Issue by dain** [prestodb/presto#11712]
There are a small number of tests that dramatically increase runtime of presto-tests.  Specifically `testLargeIn` adds almost 3 minutest to just the presto-tests module:

Method | Class | Time(ms)
------------ | ------------- | ------------- 
testLargeIn | com.facebook.presto.tests.TestQueryPlanDeterminism | 146,173
testLargeIn | com.facebook.presto.tests.TestTpchDistributedQueries | 21,769
testLargeIn | com.facebook.presto.tests.TestDistributedSpilledQueries | 21,531

Here are the top 20 methods, which are almost 8 minutes of the build time:

Method | Class | Time(ms)
------------ | ------------- | ------------- 
testLargeIn | com.facebook.presto.tests.TestQueryPlanDeterminism | 146,173
testTableSampleBernoulli | com.facebook.presto.tests.TestQueryPlanDeterminism | 31,907
testEnvironment1 | com.facebook.presto.execution.resourceGroups.db.TestEnvironments | 23,696
testSelectorResourceEstimateBasedSelection | com.facebook.presto.execution.TestQueues | 23,604
testResourceGroupManagerWithTooManyQueriesScheduled | com.facebook.presto.execution.TestQueues | 22,388
testLargeIn | com.facebook.presto.tests.TestTpchDistributedQueries | 21,769
testHighCardinalityIndexJoinResult | com.facebook.presto.tests.TestDistributedQueriesIndexed | 21,562
testLargeIn | com.facebook.presto.tests.TestDistributedSpilledQueries | 21,531
testShutdown | com.facebook.presto.tests.TestGracefulShutdown | 21,448
testHighCardinalityReducedIndexProbeKey | com.facebook.presto.tests.TestDistributedQueriesIndexed | 21,398
testLeftJoinWithEmptyInnerTable | com.facebook.presto.tests.TestDistributedSpilledQueries | 13,954
testLeftJoinWithEmptyInnerTable | com.facebook.presto.tests.TestTpchDistributedQueries | 13,707
testStartWhenPreAllocationClears | com.facebook.presto.execution.TestMemoryAwareExecution | 13,115
testEnvironment2 | com.facebook.presto.execution.resourceGroups.db.TestEnvironments | 12,949
testReservedPoolDisabled | com.facebook.presto.memory.TestMemoryManager | 12,794
testClientTagsBasedSelection | com.facebook.presto.execution.TestQueues | 12,340
testScalarSubquery | com.facebook.presto.tests.TestQueryPlanDeterminism | 11,698
testWindowsDifferentPartitions | com.facebook.presto.tests.TestQueryPlanDeterminism | 11,598
testUnionWithJoin | com.facebook.presto.tests.TestTpchDistributedQueries | 10,566
testJoinAggregations | com.facebook.presto.tests.TestDistributedSpilledQueries | 10,357

**Comment by findepi** [comment]
Some thoughts.

The problem with `testLargeIn` is that ... i saw it catching some real problems. It's kind of a stress tests for a connector. Maybe it should be moved to `AbstractTestIntegrationSmokeTest`?

The problem with `TestQueryPlanDeterminism` is ... -- i don't recall it helping me. I would consider obliterating this test class, unless someone finds it helpful.

In general, the problem is that some (many?) tests are repeated unnecessarily many times, without improving coverage. Related https://github.com/prestodb/presto/issues/6910 and https://github.com/prestodb/presto/issues/8150

**Comment by haozhun** [comment]
I'm pretty sure the "large in" tests didn't take nearly as long when they were first introduced: #3709. @raghavsethi 

A lot of things have changed between then and now, making it really hard to find out where the regression is. And I don't know how complicated the fix would be.

I don't think @dain is suggesting removing the test (but didn't exclude that possibility either). `LargeIn` is a query that a user can total write and submit to Presto in production. As a result, it could be worth fixing.

**Comment by dain** [comment]
I'm not suggesting that we remove any of these, just that we should look to see if we can improve the code or tests.  

BTW you can see the test timings for any module by opening `target/surefire-reports/index.html` and clicking on `Times` in the `Info` section.
