### ISSUE TITLE
Bad type signature for row(...)

### ISSUE THREAD

**Issue by ilkerc** [prestodb/presto#11715]
Have a type of ROW (e.g row(a varchar, b bigint)). Having an exception while trying to parse the type signature.
```
TypeSignature.parseTypeSignature("row(a varchar, b bigint)")
```
throws a Bad type signature exception.

Anyone having the same issue? (Using presto jdbc connector 0.190. Also tried latest (0.212), same result)

**Comment by haozhun** [comment]
This was fixed in 0.205. 0cc07ac9272c99c1bd1d6ec788069f79e360f48b

I just confirmed that it works in trunk.
