### ISSUE TITLE
Support multiple conventions in PolymorphicScalarFunction

### ISSUE THREAD

**Issue by haozhun** [prestodb/presto#11723]
For context, "convention" here means how the function (at execution time) would like to have its input represented, and how it would present the output. For example, 1. the function may or may not want to have a session passed in; 2. the function may use one of the `NullConvention` for each of the arguments (with different capabilities and performance implications); 3. the function may return a primitive or boxed value (again, leads to different capabilities and performance implications)

Previous changes were made to add the concept of Choice to `ScalarFunctionImplementation` and `ParametricScalarImplementation`. But the changes wasn't made to `PolymorphicScalarFunction`. We need this change before we can merge #11263.

* `ScalarFunctionImplementation` is how we represent functions that are fully instantiated in Presto. They are ready to be executed by the engine.
* `SqlScalarFunction` is the abstract class one need to extend to add a new function to Presto. This cannot be executed, but it has interface that would return a `ScalarFunctionImplementation`. One can think of it as a "factory" or "template".
  * There are many function implementations in Presto that directly extends this abstract class. But there are also more convenient ways.
  * 1. You can put many simple annotated functions in a single class. e.g. `MathFunctions`
  * 2. You can have an annotated class, representing a single complex function. e.g. `JoniRegexpReplaceLambdaFunction`
  * Both 1 and 2 gets processed by an annotation processor. The annotation processor will synthesize a `ParametricScalarImplementation`, which is a subclass of `SqlScalarFunction`.
  * 3. You can use `PolymorphicScalarFunctionBuilder` to describe a function. The builder will then produce a `PolymorphicScalarFunction`, which is also a subclass of `SqlScalarFunction`. Personally, I find this name confusing. I just see it as a convenient tools for writing Decimal function. It is a programmatic way of doing something similar to what the annotation framework would let you do. In addition, this mechanism provides some additional functionality needed for Decimal function. e.g. `DecimalInequalityOperators`.

Put concretely, You need put the following three fields in `PolymorphicScalarFunction` in a class. And have `PolymorphicScalarFunction` hold onto a list of objects of that new class instead of those 3 fields directly. This would allow multiple entries of these fields.

```
    private final boolean nullableResult;
    private final List<ArgumentProperty> argumentProperties;
    private final List<MethodsGroup> methodsGroups;
```

As you make changes to `PolymorphicScalarFunction`, you'll also need to change `PolymorphicScalarFunctionBuilder` and its callers. You'll migrate users of `PolymorphicScalarFunctionBuilder` as you would likely be changing its interface.

In order to make sure that having multiple entries of the fields actually works, you'll also need to add test that contains dummy testing functions.

**Comment by wenleix** [comment]
The context is really nice-written introduction to the Scalar Function framework. It might be worthy putting into Wiki (https://github.com/prestodb/presto/wiki) or other documents so it can help more general community developers :)
