### ISSUE TITLE
date_trunc with from_iso8601_timestamp, return error value

### ISSUE THREAD

**Issue by jackchongs** [prestodb/presto#11728]
Hi, 
    When I run the following two sql statement,  retun different value, my sql client defaut timezone is Asia/Hong_Kong.  Is this a bug ? 

select  date_trunc('day', from_iso8601_timestamp('2016-09-09T16:00:00.00Z')  )

select  date_trunc('day', timestamp '2016-09-10 00:00:00'  AT TIME ZONE 'Asia/Hong_Kong' )

**Comment by findepi** [comment]
@jackchongs what do they print?

what do they print once you execute `set session legacy_timestamp = false;` in your session?

**Comment by haozhun** [comment]
Legacy timestamp behavior in Presto is very messed up. However, you'll not run into that as long as you stick to using `TIMESTAMP WITH TIME ZONE` all along, and never go through a timestamp without time zone.

However, the correct result for the two following expression are supposed to be different in the new behavior.

```
select date_trunc('day', timestamp '2016-09-09 16:00:00 Z')
select date_trunc('day', timestamp '2016-09-10 00:00:00 Asia/Hong_Kong')
```

The first should return `2016-09-09` and the latter should return `2016-09-10` regardless of user zone.

What you want seems to be something like

```
select date_trunc('day', timestamp '2016-09-09 16:00:00 Z' AT TIME ZONE 'Asia/Hong_Kong')
select date_trunc('day', timestamp '2016-09-10 00:00:00 Asia/Hong_Kong' AT TIME ZONE 'Asia/Hong_Kong')
```
