### ISSUE TITLE
Add distribution type to explain for semi join

### ISSUE THREAD

**Issue by rschlussel** [prestodb/presto#11737]
For regular joins we print the distribution type in the explain plan.  Add this for semi joins too.

**Comment by Praveen2112** [comment]
Is this issue is still open ? Can I raise a PR for this ?

**Comment by gozingdown** [comment]
I'm going to work on this issue. Thanks.

**Comment by gozingdown** [comment]
[Pull request](https://github.com/prestodb/presto/pull/11782) created.

**Comment by findepi** [comment]
https://github.com/prestodb/presto/pull/11782 merged
