### ISSUE TITLE
Connector always get null filled unspecified columns when insert

### ISSUE THREAD

**Issue by hellium01** [prestodb/presto#11766]
When we use insert column list in presto:

```INSERT INTO TABLE (c1, c2) SELECT * FROM TABLE2```

We fill in null values for columns that are defined in the table but not in the column list, i.e. if the table have `(c1, c2, c3)`, the above command will insert null to `c3`. This behavior is desirable for some connectors but not for others. For example, for connectors to MySQL, unspecified columns should get default value instead of null.

**Comment by hellium01** [comment]
cc @electrum, @tdcmeehan

**Comment by kokosing** [comment]
Presto does not support default values yet. This could be implemented inside the mysql connector but that would make this connector to become incoherent with others connectors, but maybe it is the way to go (to behave like a RDBMS that connector is exposing).

**Comment by hellium01** [comment]
The current problem is if the underlying table in the connector has default value defined, we will always insert NULL which can cause inconsistency in behavior. In such case, we should at least let connector handle the missing columns in its own way. 

Supporting default will definitely need more things.

**Comment by hellium01** [comment]
It is true for JDBC connector or any other connectors utilizing MySQL( for example some connectors facebook internally uses). For other connectors, as long as they can have default and the table creation is not fully controlled by presto, the problem is same?
