### ISSUE TITLE
PartitionedOutputOperator reports incorrect output data size

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#11770]
PartitionedOutputOperator reports the input data size as the output data size. However, output data size might be larger due to loss of run-length and/or dictionary encodings.

**Comment by yingsu00** [comment]
For dictionary and RLE blocks, the number of positions(rows) does not change for shuffling case. The question is if this is correct for replicated case. Should it report rows * #partitions instead? @mbasmanova
