### ISSUE TITLE
Display column stats as part of EXPLAIN ANALYZE VERBOSE

### ISSUE THREAD

**Issue by sopel39** [prestodb/presto#11774]
It would be useful if column stats are part of `EXPLAIN ANALYZE VERBOSE` output. Sometimes people have basic stats gathered, but column stats missing for some partitions. Plain explain doesn't show that it's the case (it will show some cost based on number of rows). However queries will plan incorrectly due to the lack of column stats.

If detailed column stats are too much for `EXPLAIN ANALYZE VERBOSE` then we could just have the information if column stats are missing or not.

CC: @arhimondr @mbasmanova

**Comment by findepi** [comment]
Alternatively (or additionally), we could have more information in `EXPLAIN VERBOSE` / `EXPLAIN (TYPE CBO)` or something like that.

**Comment by kokosing** [comment]
`EXPLAIN ANALYZE VERBOSE` this sounds very similar to `DESCRIBE FORMATTED`.
I like `EXPLAIN (TYPE CBO)` much more.
