### ISSUE TITLE
CBO: choose join distribution type for a semi join

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#11789]
Currently, CBO chooses join distribution type for inner, left, right and full joins. However, semi joins can also benefit from automatic selection of a broadcast join.

CC: @rschlussel @arhimondr @findepi @sopel39

**Comment by rschlussel** [comment]
The reason for not doing this earlier was that for semi joins we need to know whether there was a delete node in the plan to figure out whether it can be partitioned, and that didn't translate easily to the iterative optimizer.  So the main work for this would probably be adding more complex pattern matching.

**Comment by arhimondr** [comment]
We can have just 2 different rules. First will enforce that REPLICATED is chosen for `DELETE` queries. The second will come into play if the distribution type is not yet set (by the first rule), and do the cost based magic.

**Comment by martint** [comment]
Without the optimizer being able to consider multiple plans simultaneously, that would be sensitive to the order in which rules are applied.

**Comment by arhimondr** [comment]
The rule that enforces replicated JOIN for DELETE won't be conditional. No mater if the distribution for semi-join is set - it will overwrite one if delete node is detected downstream. The rule for detecting semi joib type based on CBO will be conditional. It will be applied only to the SemiJoin nodes that have no distribution type set. This will work exactly the same way as `DetermineJoinDistributionType`. It also doesn't change anything if the distribution type was already set.

**Comment by findepi** [comment]
How would such enforcement Rule for Semi Join under Delete look like?
It would probably need to match Delete node and then recursively traverse the sources to find all Semi Join nodes, right?
If this is the way, it should probably be implemented as an ordinary PlanOptimizer.

**Comment by arhimondr** [comment]
The enforcement rule should remain a recursive rewriter.
