### ISSUE TITLE
Reducing PartitionOutputOperator memory copying

### ISSUE THREAD

**Issue by yingsu00** [prestodb/presto#11809]
Currently the partition output operator makes one extra copy of the input and materialize the blocks again. We will eliminate this extra copy and fill the partitioned buffer and serialize them on the fly.

**Comment by dain** [comment]
@yingsu00: @raghavsethi, @martint, @electrum and I discussed this for a long time.  My memory is that getting this implemented cleanly will be difficult, so I'd like to see the work in progress as this is being built.  Specifically, my concerns were that this change can be a big abstraction breaker for the Block interface.
