### ISSUE TITLE
Does presto cache tables of Hive

### ISSUE THREAD

**Issue by JobsChang** [prestodb/presto#1182]
I use hive as metastore of presto, when I drop table from hive, but it seems still exist in Presto. My operating are as follews:
1. create table in presto;
2. drop table in hive;
3. recreate the same table that dropped in step 1 in presto, then error happened, it tells that the table is already existed.

Does presto cache tables of hive locally? If so, how long does it Synchronize data and  how do I get rid of this feature?
Thx!

**Comment by electrum** [comment]
Related #1540
