### ISSUE TITLE
presto cli error message is confusing

### ISSUE THREAD

**Issue by hgschmie** [prestodb/presto#11827]
In a schema, where no table `foo` exists, if I issue this query:

```
select * from foo;
```

the cli responds with

```
select * from foo;
Query is gone (server restarted?)
```

In the log, this exception is logged:

<img width="1318" alt="screen shot 2018-10-31 at 14 05 46" src="https://user-images.githubusercontent.com/39495/47818885-22f06900-dd16-11e8-8b17-576e1eb44649.png">

I would have expected a more meaningful error message (and I think the CLI did that in the past) such as "table 'foo' is unknown".

This is using presto 0.213

**Comment by hgschmie** [comment]
Digging into this a bit more with charles-proxy, I see this:

First request:

```
OST /v1/statement HTTP/1.1
X-Presto-User: hschmiedehausen
User-Agent: StatementClientV1/0.213
X-Presto-Source: presto-cli
X-Presto-Catalog: owl
X-Presto-Schema: data
X-Presto-Time-Zone: America/Los_Angeles
X-Presto-Language: en-US
X-Presto-Session: owl.tenantid=9101
X-Presto-Transaction-Id: NONE
X-Presto-Client-Capabilities: PATH
Content-Type: text/plain; charset=utf-8
Content-Length: 17
Host: localhost:9004
Connection: Keep-Alive
Accept-Encoding: gzip
```

This one looks good, all the session properties are there....

and then 

```
GET /v1/statement/20181031_212438_00036_vevhy/1 HTTP/1.1
X-Presto-User: hschmiedehausen
User-Agent: StatementClientV1/0.213
Host: localhost:9004
Connection: Keep-Alive
Accept-Encoding: gzip
```

all the session properties are gone. The actual error then is caused by code in our connector that tries to log a queryCreated event that expects a session to be there (and does not find one).

This behaved differently in 0.205. 

Also, I feel that a failure in the event listener should not cause the `/v1/statement`  to return a 500.

**Comment by anusudarsan** [comment]
looks related to the fix recently merged. https://github.com/prestodb/presto/pull/11792

**Comment by findepi** [comment]
i thought the same. @hgschmie i think Presto 0.213 already contains https://github.com/prestodb/presto/pull/11792 . Are you using CLI 0.213 as well?

**Comment by findepi** [comment]
Fixed.
