### ISSUE TITLE
Presto DB -> com.facebook.presto.server.PrestoServer	No factory for connector kafka java.lang.IllegalArgumentException: No factory for connector kafka

### ISSUE THREAD

**Issue by SivaSamrajS** [prestodb/presto#11825]
I am not able to connect to the kafka from Presto DB server and server starting is failing. Below is my kafka.properties. under etc/catalog

connector.name=kafka  
kafka.nodes=192.168.1.5:9092  
kafka.table-names=tpch.customer,tpch.orders,tpch.lineitem,tpch.part,tpch.partsupp, 
tpch.supplier,tpch.nation,tpch.region  
kafka.hide-internal-columns=false 

=========

My Classpath also loads the kafka: 
![image](https://user-images.githubusercontent.com/44653636/47819313-1d2f6d80-dd80-11e8-9638-de828720b5c7.png)

Please suggest, anything i did wrong.

**Comment by findepi** [comment]
- would you mind sharing the startup exception?
- please don't paste images of console transcripts, paste console transcripts as text instead (wrapped in ```` ``` ... ``` ````)

**Comment by khpraful** [comment]
Make sure there are no trailing or leading whitespaces. I was facing similar issue and after getting rid of trailing whitespaces it started to work.
