### ISSUE TITLE
query failing early causes presto to lose its session

### ISSUE THREAD

**Issue by hgschmie** [prestodb/presto#11830]
This is related to #11827 

In SqlQueryManager, lines 405ff (release 0.203) there is an error path that gets entered when execution fails early (in my case, `queryExecutionFactory.createQueryExecution()` throws a SemanticException. However, my session contains a number of catalog specific properties, which are still unresolved. Inspecting with a debugger shows me:

<img width="584" alt="screen shot 2018-10-31 at 14 55 39" src="https://user-images.githubusercontent.com/39495/47821182-13285300-dd1d-11e8-8224-4f1a57be580b.png">

The error path never resolves those. As a result, the session that gets passed down as part of the `QueryInfo` object (which gets created by the `FailedQueryExecution`) and then handed to my event listener with a `QueryCreatedEvent` does not have those properties resolved. My event listener, which relies on these being present now fails. 

on the happy path, those values get resolved in the transaction context in beginTransaction in the Session object. This is never called on the error path.

**Comment by findepi** [comment]
Fixed by https://github.com/prestodb/presto/pull/11864
