### ISSUE TITLE
Spatial Join Not Used for ST_Within

### ISSUE THREAD

**Issue by anoopj** [prestodb/presto#11835]
Presto query planner [currently uses](https://github.com/prestodb/presto/blob/56360c397c26e8abfbf2b4f650e82372c6324859/presto-main/src/main/java/com/facebook/presto/sql/planner/LocalExecutionPlanner.java#L1676-L1701) geospatial joins only for some operators like` ST_Contains`, `ST_Intersects` and `ST_Distance`. Some operators like `ST_Within` don't use the geospatial joins, so it ends up doing a cartesian join and post-filter, which is very slow.

I'm not an expert in geospatial, but from the [ESRI Geometry API code](https://github.com/Esri/geometry-api-java/blob/bc4769aa254e82a33b0959abc15ff146886ce932/src/main/java/com/esri/core/geometry/ogc/OGCGeometry.java#L315-L317) (which Presto uses internally), `ST_Within` seems to be the inverse of` ST_Contains`. 

Is there a reason why `ST_Within` can't use geospatial joins as well?  I can send a pull request if we agree. 

(cc @mbasmanova )

**Comment by mbasmanova** [comment]
@anoopj Anoop, you are correct. Since `ST_Within(a, b) = ST_Contains(b, a)`, Presto could use spatial joins for `ST_Within` as well. Looking forward to a pull request.

**Comment by anoopj** [comment]
Fixed with https://github.com/prestodb/presto/pull/11944
