### ISSUE TITLE
Add ability to pass Kerberos impersonation Credential in jdbc driver

### ISSUE THREAD

**Issue by devanshsoni9** [prestodb/presto#11845]
Hi
We are testing Kerberos constrained delegation with the presto jdbc driver. However according to our tests, the presto driver does not support impersonation.

I have a service which takes in a dbUser and we want the service run-as user to impersonate the db user while connecting to presto db.
I see that [presto jdbc](https://prestodb.io/docs/current/installation/jdbc.html) driver does not have any such property which some other jdbc drivers support (e.g. [denodo](https://community.denodo.com/docs/html/browse/6.0/vdp/developer/access_through_jdbc/connecting_to_virtual_dataport_using_kerberos_authentication/connecting_to_virtual_dataport_using_kerberos_authentication), [sqlserver](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-kerberos-integrated-authentication-to-connect-to-sql-server?view=sql-server-2017), [impala](https://www.simba.com/products/Impala/doc/JDBC_InstallGuide/content/jdbc/im/authenticating/delegatedkerberos.htm) ) to pass in the impersonation credentials. 

On the other hand, I was able to get it working for Postgres jdbc driver by attaching it to the Subject's private credentials. Like this
```
protected Connection createConnection(final GSSCredential impersonatedUserCredential)
            throws PrivilegedActionException {
        this.serviceSubject.getPrivateCredentials().add(impersonatedUserCredential);
        return Subject.doAs(this.serviceSubject, (PrivilegedExceptionAction<Connection>) () -> {
            Properties driverProperties = new Properties();
            driverProperties.put("jaasLogin", "true");
            driverProperties.put("jaasApplicationName", this.targetUserName);
            driverProperties.put("user", this.targetUserName);
            return DriverManager.getConnection(POSTGRES_CONNECTION_URI, driverProperties);
        });
    }
```

However, when I try to attach the impersonated Credentials/ticket in presto, it does not pick up the impersonation ticket from the Subject and the final connection ends up being a simple kerberos connection instead of a Keberos delegation. This is my code for presto connection

```
  @Override
    protected Connection createConnection(final GSSCredential impersonatedUserCredential)
        throws PrivilegedActionException {
        this.serviceSubject.getPrivateCredentials().add(impersonatedUserCredential);
       return Subject.doAs(this.serviceSubject, (PrivilegedExceptionAction<Connection>) () -> {
            Properties driverProperties = new Properties();
         // native presto driver properties
            driverProperties.put("user", "db-user");
            driverProperties.put("SSL","true");
            driverProperties.put("SSLTrustStorePath", "prestoTrustStore");
            driverProperties.put("SSLTrustStorePassword","password");
            driverProperties.put("KerberosRemoteServiceName","presto");
            driverProperties.put("KerberosPrincipal","my-service-principal");
            driverProperties.put("KerberosUseCanonicalHostname", "false");
            driverProperties.put("KerberosConfigPath","krb5.conf");
            driverProperties.put("KerberosKeytabPath","my-service-runas.keytab");

            return DriverManager.getConnection(PRESTO_CONNECTION_URI, driverProperties);
        });
    }
```

The final result should be a logged in session to presto db with the current user as db-user. Instead it ends up creating a connection with my-service-principal as the current user.

To verify this I looked at the presto server logs I was connecting to ([presto-issue-git.txt](https://github.com/prestodb/presto/files/2544310/presto-issue-git.txt)). From the presto server logs it is evident that the users getting added to the auth list is MY-SERVICE-PRINCIPAL-NAME, when it is supposed to be db-user had the connection been a kerb delegation authorized connection. I also verified using wireshark logs. From wireshark I observed that instead of using the already logged in Kerberos Context from the Subject passed into Subject.doAs() method, the driver is creating new Kerberos Login Context. Also, it is not attaching the impersonation ticket when requesting for a service ticket to presto server from KDC (Ticket Granting Service). One more issue is that for some reason the driver is requesting for the service ticket from KDC 3 times while establishing a single connection instead of just one. 

I wanted to know if there is some other way which I am not able to understand for achieving Kerb delegation for the presto jdbc driver. Also, do you plan to support a driver property to allow passing a impersonation credential.

**Comment by dain** [comment]
I'm not really sure what you are trying to do, so maybe I can point you at the code and you can tell us what isn't working.

The JDBC Kerberos authentication starts here:

https://github.com/prestodb/presto/blob/master/presto-jdbc/src/main/java/com/facebook/presto/jdbc/PrestoDriverUri.java#L170

This code extracts the properties from the connection information.  Then this gets passed all the way down to the SpnegoHandler, which does the actual authentication here:

https://github.com/prestodb/presto/blob/master/presto-client/src/main/java/com/facebook/presto/client/SpnegoHandler.java#L150
