### ISSUE TITLE
Resource groups docs could clarify how cpu limits work

### ISSUE THREAD

**Issue by EvilPuppetMaster** [prestodb/presto#11848]
Hi,

I've been trying to figure out how to use the cpu limits in resource groups but the docs here https://github.com/prestodb/presto/blob/master/presto-docs/src/main/sphinx/admin/resource-groups.rst don't give much detail.

One quick addition that will help a lot would be to point out that the units required for `softCpuLimit` and `hardCpuLimit` must be specified as durations. I initially used percentages, as per the mem limits, and which is consistent with how this works in some other DBs. This actually caused the service to fail to start which took a while to debug as the error messages just complained that something wasn't a valid duration but didn't say what.

Once I figured out they must be specified as durations, I still couldn't really figure out how they work. I tried setting a cpuQuotaPeriod of `15m`, with a `softCpuLimit` of '7m' and a `hardCpuLimit` of `12m`. I wasn't sure if this applied to wall time or cumulative time across all cpus, but I assumed that all three settings (quota, soft, hard) would refer to the same type of time. So I thought this should mean that anyone who uses more than about 50% (7m) of cpu would have a penalty against queuing more queries, and that if a query used 80% (12m) it would be blocked until the next 15m. 

In practice, it doesn't seem like this is how it worked at all. When I tested, I ran a query that took ~3m elapsed time, and use 18m cumulative cpu. And then my next queries seemed to queue for about 15m real time before being run. I wasn't really sure what to expect, but if the limits are based on wall time cpu, I would have expected this query not to be limited at all. While if they were all based on cumulative cpu time, I would have expected to see blocking once the query reached 12m cumulative... but as far as I can tell there was no blocking during the running of the query.

In any case, I'm probably assuming wrong about how this all works, and it would be helpful to add some more detail to the resource groups docs to explain how it works in practice.

Regards
Tom

**Comment by ankitdixit** [comment]
@raghavsethi I felt the same when i started reading about resource groups. 
I would like to add more details to the writeup, can i pick this up?

**Comment by raghavsethi** [comment]
Please go ahead.
