### ISSUE TITLE
Can a query use resources dynamically ?

### ISSUE THREAD

**Issue by radunicolae** [prestodb/presto#11850]
Hi,

We have a elastic cluster that adds or removes nodes depending on the CPU load on the cluster. The issue is that once a resource hungry query is issues, the cluster deploys new nodes but the query wont use the new nodes. Is there any way to make a query aware of the new resources ?

Thank you!

**Comment by nezihyigitbasi** [comment]
>  the cluster deploys new nodes but the query wont use the new nodes

Are the new workers properly registered to the coordinator? If yes, I would expect them to receive load. You can check that by querying the system catalog: `select * from system.runtime.nodes`.

**Comment by radunicolae** [comment]
Hi, 
Thank you for your quick replies
@nezihyigitbasi yes, the nodes are properly configured, we are using and auto scaling group from AWS with a custom AMI, the new nodes are able to register with the coordinator without any intervention.
@dain yes, the query is fully running, it takes the autoscaler about 5 minutes to detect the load and an additional 2-3 minutes to deploy a new node, by that time the query is well on its way. A new query will be able to use all the nodes in the cluster  but the old one is stuck with what it got when it started.
