### ISSUE TITLE
IS DISTINCT FROM bug with ObjectIdFunctions

### ISSUE THREAD

**Issue by dickson-conde** [prestodb/presto#11869]
I'm getting the error:

`com.facebook.presto.metadata.OperatorNotFoundException: 'IS DISTINCT FROM' cannot be applied to ObjectId, ObjectId`

when trying to select from a view that pulls data from a MongoDB connector despite 'IS DISTINCT FROM' not being used in the view. I'm assuming there's some background logic that happens with joins/aggregations that uses the 'IS DISTINCT FROM' command.

The select works in presto version .188 but does not work in version .203 when testing a presto upgrade.

**Comment by dain** [comment]
Originally `IS DISTINCT FROM` was automatically generated, but with the introduction of types like `ROW`, it is not longer possible so it must be manually provided.  When this was changed someone missed the Postgres `objectid` type.  The function should be added to https://github.com/prestodb/presto/blob/master/presto-mongodb/src/main/java/com/facebook/presto/mongodb/ObjectIdFunctions.java.  I would look at https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/type/VarcharOperators.java#L244 for an example

**Comment by electrum** [comment]
With the exception of array, map, and row, all of the operators are the same. Does it make sense to require every type to implement the same boilerplate? The `INDETERMINATE` operator seems to have the same problem.

Related, we should implement `XX_HASH_64` for `ObjectId`.

**Comment by dain** [comment]
@electrum If possible, I'd like the automatic generation behavior back also.

**Comment by findepi** [comment]
The fix is available in Presto 303 release.

**Comment by az-stripe** [comment]
@findepi Is the `303` a typo? Or are releases numbered in some other way, in addition to the `0.203` format?

**Comment by findepi** [comment]
@az-stripe you can get it from https://prestosql.io/download.html

**Comment by az-stripe** [comment]
@findepi !!!! what is the difference between http://prestodb.github.io/ and https://prestosql.io/ , i've only ever seen the former

**Comment by rongrong** [comment]
@az-stripe prestosql is a fork from prestodb at around release 215/216. the prestosql release starts from 300.

**Comment by findepi** [comment]
@az-stripe , @rongrong is right. (thanks @rongrong for clarifying the version numbers!)
prestosql can be seen as a fork from prestodb... Or vice versa -- especially if you consider the fact that all top contributors (https://github.com/prestodb/presto/graphs/contributors) are there 🚀
