### ISSUE TITLE
Cannot declare function with return type of decimal without scale

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#11863]
Calling this function will fail at runtime in `FunctionRegistry.doGetSpecializedFunctionKey()` due to `SignatureBinder` trying to match against `decimal(8,0)`.
```java
@ScalarFunction("test")
@SqlType("decimal(8)")
public static long test()
{
    return 0;
}
```

**Comment by cemcayiroglu** [comment]
@electrum I can take this if you are not working on it?
