### ISSUE TITLE
Why query `system.jdbc.columns` so slow.

### ISSUE THREAD

**Issue by archongum** [prestodb/presto#11879]
# env
- presto 0.210
- jdk1.8
- dbeaver 5.2.4
- DataGrip 2018.2.4

# dbeaver
When query from a 'new' table - hasn't been queried in current connection - say
`select * from t_sales_bill` or `select bill_id from t_sales_bill`
it will automatically run the sql below to query all columns in `t_sales_bill` table AND **SO SLOW**(cost 36s)!! It happen whenever you query from a 'new' table and so wasting time!
```sql
SELECT TABLE_CAT, TABLE_SCHEM, TABLE_NAME, COLUMN_NAME, DATA_TYPE,
  TYPE_NAME, COLUMN_SIZE, BUFFER_LENGTH, DECIMAL_DIGITS, NUM_PREC_RADIX,
  NULLABLE, REMARKS, COLUMN_DEF, SQL_DATA_TYPE, SQL_DATETIME_SUB,
  CHAR_OCTET_LENGTH, ORDINAL_POSITION, IS_NULLABLE,
  SCOPE_CATALOG, SCOPE_SCHEMA, SCOPE_TABLE,
  SOURCE_DATA_TYPE, IS_AUTOINCREMENT, IS_GENERATEDCOLUMN
FROM system.jdbc.columns
WHERE TABLE_CAT = 'platform_data' AND TABLE_SCHEM LIKE 'platform_data' ESCAPE '\' AND TABLE_NAME LIKE 't_sales_bill' ESCAPE '\' AND COLUMN_NAME LIKE '%' ESCAPE '\'
ORDER BY TABLE_CAT, TABLE_SCHEM, TABLE_NAME, ORDINAL_POSITION
```
![dbeaver-single-table](https://user-images.githubusercontent.com/20929338/48205921-13bd8b00-e3a8-11e8-9e64-bdfe64d48101.png)

# DataGrip
DataGrip has the same problem like dbeaver but not so bad but BAD.

DataGrip will query the whole metadata in `system.jdbc` when  connection started.
![snipaste20181108_223350](https://user-images.githubusercontent.com/20929338/48206383-40be6d80-e3a9-11e8-978f-403aa78a9631.png)

![datagrip-init](https://user-images.githubusercontent.com/20929338/48206728-01dce780-e3aa-11e8-9ed9-6808eada0557.png)

So, it's like 'once for all' not when you need it. BUT it took 55s to query `system.jdbc.columns`!

# SO
- Why query `system.jdbc.columns` so slow? 
- Any better database tools for presto?

**Comment by archongum** [comment]
If just run `select * from system.jdbc.columns`, you would kill it from WebUI before the result show up....

**Comment by kokosing** [comment]
It looks like your query is slow because `dbeaver` has a bug. This is very typical bug.

Please take a look at the query:
```
SELECT TABLE_CAT, TABLE_SCHEM, TABLE_NAME, COLUMN_NAME, DATA_TYPE,
  TYPE_NAME, COLUMN_SIZE, BUFFER_LENGTH, DECIMAL_DIGITS, NUM_PREC_RADIX,
  NULLABLE, REMARKS, COLUMN_DEF, SQL_DATA_TYPE, SQL_DATETIME_SUB,
  CHAR_OCTET_LENGTH, ORDINAL_POSITION, IS_NULLABLE,
  SCOPE_CATALOG, SCOPE_SCHEMA, SCOPE_TABLE,
  SOURCE_DATA_TYPE, IS_AUTOINCREMENT, IS_GENERATEDCOLUMN
FROM system.jdbc.columns
WHERE TABLE_CAT = 'platform_data' AND TABLE_SCHEM LIKE 'platform_data' ESCAPE '\' AND TABLE_NAME LIKE 't_sales_bill' ESCAPE '\' AND COLUMN_NAME LIKE '%' ESCAPE '\'
ORDER BY TABLE_CAT, TABLE_SCHEM, TABLE_NAME, ORDINAL_POSITION
```

And specifically predicates: `TABLE_SCHEM LIKE 'platform_data' ESCAPE '\' ` and `TABLE_NAME LIKE 't_sales_bill' ESCAPE '\'`. Notice that your object names contains `_`, in pattern for `LIKE` operator `_` means any character and in your case it should be escaped. These predicates should look like: `TABLE_SCHEM LIKE 'platform\_data' ESCAPE '\' ` and `TABLE_NAME LIKE 't\_sales\_bill' ESCAPE '\'`. 

Can you please rerun your query but with properly escaped `LIKE` patterns literals? That would be: 
```
SELECT TABLE_CAT, TABLE_SCHEM, TABLE_NAME, COLUMN_NAME, DATA_TYPE,
  TYPE_NAME, COLUMN_SIZE, BUFFER_LENGTH, DECIMAL_DIGITS, NUM_PREC_RADIX,
  NULLABLE, REMARKS, COLUMN_DEF, SQL_DATA_TYPE, SQL_DATETIME_SUB,
  CHAR_OCTET_LENGTH, ORDINAL_POSITION, IS_NULLABLE,
  SCOPE_CATALOG, SCOPE_SCHEMA, SCOPE_TABLE,
  SOURCE_DATA_TYPE, IS_AUTOINCREMENT, IS_GENERATEDCOLUMN
FROM system.jdbc.columns
WHERE TABLE_CAT = 'platform\_data' AND TABLE_SCHEM LIKE 'platform\_data' ESCAPE '\' AND TABLE_NAME LIKE 't\_sales\_bill' ESCAPE '\' AND COLUMN_NAME LIKE '%' ESCAPE '\'
ORDER BY TABLE_CAT, TABLE_SCHEM, TABLE_NAME, ORDINAL_POSITION
```

**Comment by archongum** [comment]
@kokosing Result shows up in a second! 
How can I fit this automatic query, changing it to the one like yours? It determined by presto-jdbc or dbeaver? 
(BTW, any database tools for presto recommend?)

**Comment by kokosing** [comment]
It is a bug in dbeaver, I guess that they are using JDBC API to retrieve the list of columns, but they do not escape `_` character. Can you please file a ticket to them?

**Comment by kokosing** [comment]
Oh I noticed that you already created one: https://github.com/dbeaver/dbeaver/issues/4587

**Comment by findepi** [comment]
Let me close this in favor of https://github.com/dbeaver/dbeaver/issues/4587
