### ISSUE TITLE
ClusterMemoryLeakDetector

### ISSUE THREAD

**Issue by hustnn** [prestodb/presto#11883]
com.facebook.presto.memory.ClusterMemoryLeakDetector    Memory leak detected. The following queries are already finished, but they have memory reservations on some worker node.

We are using presto 0.212. When we found this, what is the next step to find out the root cause of memory leak happens?

Thanks.

**Comment by nezihyigitbasi** [comment]
First, to make it clear, a "leak" in this context means incorrect memory accounting. When that happens in the server logs you should see the query ids for the queries with incorrect memory accounting/leak. Then, on the coordinator you can look at the `v1/cluster/memory` endpoint to see which operators of that query has memory allocations. Rest of the process is to investigate &  try to understand how memory can be leaked while executing that query shape, which is the non-trivial part & requires knowledge of Presto internals/source.
