### ISSUE TITLE
Speed up querying through Kafka Connector

### ISSUE THREAD

**Issue by franz-see** [prestodb/presto#11896]
Hi,

I am new to PrestoDB. And im using it to query my kafka cluster. 

I have it running and tried to query it via 

```
select * 
  from my_topic 
 where my_mapped_field = 'some_value' 
 limit 5;
```

And it has been running now for 1000 seconds and it's still not finished yet.

Is there a way I can speed this up (like saving kafka data into my prestodb server, or tuning parameters, or modifying my query, etc)?

Thanks,
Franz

**Comment by findepi** [comment]
Hi
I don't know the answer. However, the user group (https://groups.google.com/d/forum/presto-users) is much better a  place for this kind of inquiries. I encourage you to close this issue and try asking there.

**Comment by findepi** [comment]
i see you already asked on Slack.
