### ISSUE TITLE
Adding efficient index-join support for a custom SPI connector

### ISSUE THREAD

**Issue by rzeyde-varada** [prestodb/presto#11899]
Dear Presto maintainers,

We would like to add index join support to our (Varada) SPI connector, following the examples at #1202 ([TpchConnectorIndex](https://github.com/prestodb/presto/blob/3060c65a1812c6c8b0c2ab725b0184dbad67f0ed/presto-tests/src/main/java/com/facebook/presto/tests/tpch/TpchConnectorIndex.java)) and #9095 ([ThriftConnectorIndex](https://github.com/prestodb/presto/blob/3060c65a1812c6c8b0c2ab725b0184dbad67f0ed/presto-thrift-connector/src/main/java/com/facebook/presto/connector/thrift/ThriftConnectorIndex.java)). 
If we understand correctly, we need to implement [ConnectorIndex::lookup(RecordSet recordSet)](https://github.com/prestodb/presto/blob/86e24d99a7ade8ed2c28aa6a2eac481d3cad59ae/presto-spi/src/main/java/com/facebook/presto/spi/ConnectorIndex.java#L18) interface for our specific connector. In order to achieve maximal concurrency during the lookup, we would like to apply it concurrently over all possible splits of the indexed table, as shown below:

![screen shot 2018-11-12 at 11 55 20](https://user-images.githubusercontent.com/44966813/48339902-e60b6700-e671-11e8-9b26-48b270c1a90b.png)

For example, when we perform an index join between “Left” and “Right” tables, we would like to run lookup(L<sub>i</sub>) concurrently over all the splits of the “Right” table ({R<sub>1</sub>...R<sub>k</sub>}).

Since both “Left” and “Right” tables are handled by our connector (so we can retrieve their splits using our SplitManager), and each split has a local index (so each lookup can be computed efficiently), we would benefit from running the n*k lookups in parallel.
However, current ConnectorIndex interface allows concurrent execution only on the “Left” splits, which can be problematic when the “Left” table is much smaller than the “Right” one - since the naive implementation of lookup() will result in almost serial execution and low worker utilization.

One possible solution (after looking at the [ThriftIndexPageSource implementation](https://github.com/prestodb/presto/blob/3060c65a1812c6c8b0c2ab725b0184dbad67f0ed/presto-thrift-connector/src/main/java/com/facebook/presto/connector/thrift/ThriftIndexPageSource.java)) is to implement the concurrent lookups of the “Right” table splits at the ConnectorIndex level (similar to how it’s done by [ThriftConnectorIndex::lookup()](https://github.com/prestodb/presto/blob/3060c65a1812c6c8b0c2ab725b0184dbad67f0ed/presto-thrift-connector/src/main/java/com/facebook/presto/connector/thrift/ThriftConnectorIndex.java#L64) method).
However, we would like to explore a more general solution, by allowing scheduling the “local” joins of (L<sub>i</sub>, R<sub>j</sub>) in parallel e.g. by the coordinator, or as a result of a pre-processing stage (similarly to [ThriftIndexedTpchService::getIndexSplitsSync()](https://github.com/prestodb/presto/blob/3060c65a1812c6c8b0c2ab725b0184dbad67f0ed/presto-thrift-testing-server/src/main/java/com/facebook/presto/connector/thrift/server/ThriftIndexedTpchService.java#L57) method). 
To support this, we suggest using both the **index splits** and the **probe splits** from the SplitManager to generate all possible split pairs, so their processing will be distributed among all Presto worker threads, to maximize the system’s throughput.

Please let us know if there is a better/simpler way to increase the concurrency of the index join operator for our use-case, or if there is any misunderstanding in the analysis above.

**Comment by dain** [comment]
I didn't really follow your proposal for the "more general solution", but it sounds like a pretty big change to Presto (e.g., index splits are currently local machine only).  Also, it is possible that the impact of running a lot more drivers could really negatively effect the query performance, so it would take a lot of investigation.  If I were you, I'd copy the design of the Thrift connector and just do it in the connector, where you can completely understand the performance and constraints of the actual data source.

**Comment by mbasmanova** [comment]
@rzeyde-varada Roman,

> However, current ConnectorIndex interface allows concurrent execution only on the “Left” splits, which can be problematic when the “Left” table is much smaller than the “Right” one - since the naive implementation of lookup() will result in almost serial execution and low worker utilization.

Is this the only problem with current implementation. If so, is CBO not helping here?

**Comment by rzeyde-varada** [comment]
>  If I were you, I'd copy the design of the Thrift connector and just do it in the connector, where you can completely understand the performance and constraints of the actual data source.

Thanks @dain !We will proceed
