### ISSUE TITLE
can not insert data into existing partition

### ISSUE THREAD

**Issue by qli-aa** [prestodb/presto#11922]
Presto-0.212

reproduce issue:
1.create partitioned table in hive or presto
2.add a partition into the table in Hive (because presto doesn't support add partition)
3.run `insert into table_1 select fields from table_2 where partition_key=partition_value` in presto
   then query failed 'Error moving data files'
   if I drop partition in Hive, then re-run the query, it succeed
looks like, if I want to insert data into partition table in presto , the partition I want to insert data must not  exist

**Comment by qli-aa** [comment]
happened with Hive managed table and external table

**Comment by dain** [comment]
There are 3 distinct error messages that start with `Error moving data files`.  Can you post the full stack trace?

**Comment by rschlussel** [comment]
Closing for now.  @qli-aa feel free to reopen if you can provide the additional information
