### ISSUE TITLE
Max retry attempts and max wait time for hive metastore client should be configurable

### ISSUE THREAD

**Issue by VicoWu** [prestodb/presto#11939]
I find the when `ThriftHiveMetastore` trying to connect to hive metastore, it always using the default `DetryDriver` whose max retry attempts is `DEFAULT_RETRY_ATTEMPTS` whose value is `10`  and max retry time is `DEFAULT_MAX_RETRY_TIME` whose value is `30s`;  All that user could setup currently is the timeout by `hive.metastore-timeout`, but for example, when I want to set the `hive.metastore-timeout` to `3` minutes and want it to retry for `10` attempts when timeout happened, that is , waiting for 3 * 10 = 30 minutes when hive metastore didn't respond or unstable, it is impossible because it is restricted by `DEFAULT_MAX_RETRY_TIME` which cannot be configured;
 I think it is necessary to make it configurable in the catalog configuration files; 

@dain @findepi  what's your opinion ? If you think it is necessary , I will do that.

**Comment by dain** [comment]
cc @electrum

**Comment by VicoWu** [comment]
@electrum  would you please give some comment about this? We have conducted this modification in our prod environment and presto is now more robust for hive metastore instability;
