### ISSUE TITLE
presto-postgresql: create view support

### ISSUE THREAD

**Issue by bruth** [prestodb/presto#11936]
Hi! I tried creating a view against a Postgres connector, however I get the message:

```
This connector does not support creating views
```

I know this typically means support has not been implemented yet. However looking at the "connector limitations" on the [postgresql connector docs](https://prestodb.io/docs/current/connector/postgresql.html), it doesn't list `create view` so I wanted to check which one is incorrect?

In any case, what is the path forward to get support? I am happy to contribute where possible (not a Java developer myself). Thank you.

**Comment by mingfang** [comment]
please reopen this issue.
view support for Postgres is critical
