### ISSUE TITLE
PLANNING state take long time

### ISSUE THREAD

**Issue by imperio-wxm** [prestodb/presto#11947]
What meaning of `PLANNING ` on web ui？

When I run 10 query,and 10 query be PLANNING state for a long time( 20s ), after that running so fast(each query take less then 10 s).

Actually query run time is 10s, but in PLANNING state waste 20s, return all result  will be 10s + 20s = 30s.

E.g:
![image](https://user-images.githubusercontent.com/8111349/48755764-7deffd00-ecd1-11e8-820e-d1e426e3c999.png)

![image](https://user-images.githubusercontent.com/8111349/48755794-8fd1a000-ecd1-11e8-82dd-516c3b10db45.png)

![image](https://user-images.githubusercontent.com/8111349/48755812-995b0800-ecd1-11e8-998f-c2137b2c4134.png)

> Run query so fast, but plan so slow(4.76+6.25=11.01s).

I found this [issue](https://github.com/prestodb/presto/issues/10700), and it fix in the latest version?

**Comment by Praveen2112** [comment]
Planning time depends on the type of query you are running (query with too many joins, how many columns are being selected, etc) and it also partially depends on the connector you are using. What is your presto version ? There was a patch in 0.211 which reduces the query time involving too many joins.

**Comment by imperio-wxm** [comment]
@Praveen2112  

My presto vesion: 0.149 
And use cassandra connector, Basically similar to the above issue, When I use lot of params in `in` grammar to find partition key, plan state cost time more than process.

**Comment by findepi** [comment]
> My presto vesion: 0.149

Please do upgrade. I doubt anyone else in the community runs 0.149, so you probably won't get help without upgrading.  Please open a new issue if the problem persists.

**Comment by imperio-wxm** [comment]
@findepi  

Not the reason for the presto version,I use version=0.213 plan state still cost more time with cassandra connector.

My partition key is time(2018-11-20 00:01). When I query all day data must be like this: `time in (2018-11-20 00:01,2018-11-20 00:02,2018-11-20 00:03.........)`

In find this code in `presto-cassandra/src/main/java/com/facebook/presto/cassandra/NativeCassandraSession.java`

![image](https://user-images.githubusercontent.com/8111349/48816120-e1cf0000-ed7b-11e8-8feb-1e636e94743f.png)

Will it traverse all the partition keys in the `in` grammar even partition has no data?
