### ISSUE TITLE
Hive's query results are different from Presto's

### ISSUE THREAD

**Issue by guozygeorage** [prestodb/presto#11941]
They have the same data source

For exampe , The format of the table is parquet ,
but Presto sql  search_word = '童鞋'  is no result,
Presto sql  search_word liek '童鞋%'  have result,
Hive both have result.

I don't know the reason. I hope you can help me solve it. Sometimes this can appear
Thank you very much 

Presto version :0211
Hive version: hive-1.1.0-cdh5.10.2、

Hive image 
![image](https://user-images.githubusercontent.com/12857628/48596764-67763880-e995-11e8-90e8-646dfd7e33d5.png)

Presto image
![image](https://user-images.githubusercontent.com/12857628/48596790-7c52cc00-e995-11e8-9fde-02ac9bef13a4.png)

@qqibrow @findepi @facebook-github-bot @zpao

_Originally posted by @guozygeorage in https://github.com/prestodb/presto/pull/11515#issuecomment-439273262_

**Comment by yangjun616** [comment]
I used to meet the same question, then i rebuild the table use  solve the problem.
presto sql :
CREATE TABLE orders_by_date
COMMENT 'Summary of orders by date'
WITH (format = 'ORC')
AS
SELECT .......

I think it may be the format reason,using ORC fromat may help you

**Comment by dain** [comment]
@guozygeorage can you run `SHOW CREATE TABLE` on your test table?  I'd like to know what format you are using.  The problem you are seeing is created by the filtering system using statistics in the files to skip the data.  Either the statistics in the file are bad, or the code in Presto the processes the statistics is bad.

**Comment by dain** [comment]
@nezihyigitbasi and @zhenxiao, is there a way to validate the statistics in existing Parquet files?  If we are confident the statistics in the file are correct, then there is likely a place in the Presto Parquet reader that is comparing using `java.util.String`.

@guozygeorage  Can you try creating copying the table in Presto with `CREATE TABLE test WITH (format = 'Parquet') AS SELECT * FROM tmp.tmp_srch_to_category_guozy` and rerun the test to see if you get a similar error?

**Comment by guozygeorage** [comment]
I creating copying the table in Presto with CREATE TABLE tmp.tmp_srch_to_category_guozy_test WITH (format = 'Parquet') AS SELECT * FROM tmp.tmp_srch_to_category_guozy  ,  the results are normal.
@dain

**Comment by zhenxiao** [comment]
wired. what's the compression and encoding you are using for the old (not working) and new(working) Parquet tables?

**Comment by nezihyigitbasi** [comment]
https://github.com/apache/parquet-mr/tree/master/parquet-tools

**Comment by guozygeorage** [comment]
@zhenxiao 
Hive's compression and encoding  is SNAPPY (org.apache.hadoop.io.compress.SnappyCodec)

**Comment by zhenxiao** [comment]
I think Parquet Snappy is supported pretty well
yep, as @nezihyigitbasi suggested, either use parquet-tools to validate stats, or maybe share the not working data, we could debug

**Comment by guozygeorage** [comment]
I  use parquet-tools to validate stats,the results are as follows.
![image](https://user-images.githubusercontent.com/12857628/49412601-f19d0a00-f7a7-11e8-99c2-54704997b83a.png)

![image](https://user-images.githubusercontent.com/12857628/49412636-16917d00-f7a8-11e8-9da0-97f3ef8be4d5.png)

The results have corresponding data.And then I provide the source data, so you can see.
[20181204_013919_01631_952ch.zip](https://github.com/prestodb/presto/files/2642026/20181204_013919_01631_952ch.zip)

Then I created three new tables with the same data,format is textfile、parquet、orc , they have different results.
![image](https://user-images.githubusercontent.com/12857628/49413430-db447d80-f7aa-11e8-8ced-d90ffce5ed30.png)


@zhenxiao @nezihyigitbasi @dain

**Comment by guozygeorage** [comment]
Here is the parquet file.
[000000_0.zip](https://github.com/prestodb/presto/files/2651204/000000_0.zip)

**Comment by qqibrow** [comment]
@zhenxiao @nezihyigitbasi @guozygeorage 

I checked that parquet file, the stats doesn't look correct. 

the stats of that file is:
```
{
[search_word] BINARY=min: , max: ~~~~~~毅雅切尔西短靴~~~~~~~, num_nulls: 0, 
[cid2] INT32=min: 273, max: 472, num_nulls: 0, 
[cname2] BINARY=min: 个护清洁, max: 鞋靴箱包, num_nulls: 0, 
[cname2_count] INT64=min: 1, max: 1391642, num_nulls: 0, 
[total_score] DOUBLE=min: 0.90016, max: 1308792.14392, num_nulls: 0
}
```
however,  if you use presto to calculate stats:
```
presto:default> select min(search_word), max(search_word), min(cid2), max(cid2), min(cname2), max(cname2), min(cname2_count), max(cname2_count), min(total_score), max(total_score) from test_parquet_error;
 _col0 |              _col1              | _col2 | _col3 |  _col4   |  _col5   | _col6 |  _col7  |       _col8        |       _col9
-------+---------------------------------+-------+-------+----------+----------+-------+---------+--------------------+--------------------
       | 󾠮 朗欣特全盖熏蒸足浴足疗按摩器 |   273 |   472 | 个护清洁 | 鞋靴箱包 |     1 | 1391642 | 0.9001587161945394 | 1308792.1439215275
(1 row)
```
You can see the max value in parquet stats is different while the others are the same. 

That's why you get empty result of query `select * from test_parquet_error where search_word = '童鞋'`,  presto parquet reader use stats to skip block, incorrect stats in parquet will lead to wrong result.


I don't understand how come the stats could be incorrect though.

**Comment by nezihyigitbasi** [comment]
I agree with @qqibrow's conclusion. I stepped through the code and Presto skips the block due to the stats in the Parquet file. The min for that column is empty while the max is "~~~~~~毅雅切尔西短靴~~~~~~~". @guozygeorage how is this Parquet file written? It's probably a bug in the writer.

**Comment by guozygeorage** [comment]
Hive -e "create table as seelct * from ..."   .The Parquet file was written with Hive SQL.

**Comment by nezihyigitbasi** [comment]
Which version of Hive did you use?

**Comment by nezihyigitbasi** [comment]
OK I see it's hive-1.1.0-cdh5.10.2

**Comment by nezihyigitbasi** [comment]
With the info we have right now I don't think it's a Presto issue. I suspect it's a writer issue where the writer is creating the Parquet file with incorrect stats. Therefore, I recommend you to reach out to the Cloudera folks as you are using their distribution of Hive.

**Comment by guozygeorage** [comment]
If there is a problem with the parquet of Hive, Hive SQL queries will appear as normal results. Is this normal?

**Comment by nezihyigitbasi** [comment]
I think that's a good question for the Cloudera team as well, maybe Hive is working around this incorrect stats issue while Presto does not.

**Comment by zhenxiao** [comment]
nice catch, @qqibrow 
@guozygeorage Hive returns normal results, as Hive does not use Parquet file statistics to speedup Parquet scanning. as @nezihyigitbasi said, Presto requires Parquet statistics to be correct, or Presto might skip wrong data.

**Comment by guozygeorage** [comment]
How to survive Parquet statistics to be correct？This is parquet bug?

**Comment by zhenxiao** [comment]
either a Parquet bug or Hive one. The Parquet statistics is incorrect. The problem is in Parquet generation side
