### ISSUE TITLE
Build failed cause by goal pl.project13.maven:git-commit-id-plugin:2.1.13

### ISSUE THREAD

**Issue by zuhuanchen** [prestodb/presto#11956]
[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.1.13:revision (default) on project presto-root: Execution default of goal pl.project13.maven:git-commit-id-plugin:2.1.13:revision failed: A required class was missing while executing pl.project13.maven:git-commit-id-plugin:2.1.13:revision: com/fasterxml/jackson/core/type/TypeReference
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>pl.project13.maven:git-commit-id-plugin:2.1.13
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/zuhuanchen/.m2/repository/pl/project13/maven/git-commit-id-plugin/2.1.13/git-commit-id-plugin-2.1.13.jar
[ERROR] urls[1] = file:/Users/zuhuanchen/.m2/repository/org/slf4j/slf4j-jdk14/1.5.6/slf4j-jdk14-1.5.6.jar
[ERROR] urls[2] = file:/Users/zuhuanchen/.m2/repository/org/slf4j/jcl-over-slf4j/1.5.6/jcl-over-slf4j-1.5.6.jar
[ERROR] urls[3] = file:/Users/zuhuanchen/.m2/repository/org/apache/maven/reporting/maven-reporting-api/2.2.1/maven-reporting-api-2.2.1.jar
[ERROR] urls[4] = file:/Users/zuhuanchen/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.1/doxia-sink-api-1.1.jar
[ERROR] urls[5] = file:/Users/zuhuanchen/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.1/doxia-logging-api-1.1.jar
[ERROR] urls[6] = file:/Users/zuhuanchen/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar
[ERROR] urls[7] = file:/Users/zuhuanchen/.m2/repository/commons-cli/commons-cli/1.2/commons-cli-1.2.jar
[ERROR] urls[8] = file:/Users/zuhuanchen/.m2/repository/org/codehaus/plexus/plexus-interactivity-api/1.0-alpha-4/plexus-interactivity-api-1.0-alpha-4.jar
[ERROR] urls[9] = file:/Users/zuhuanchen/.m2/repository/backport-util-concurrent/backport-util-concurrent/3.1/backport-util-concurrent-3.1.jar
[ERROR] urls[10] = file:/Users/zuhuanchen/.m2/repository/org/codehaus/plexus/plexus-utils/1.5.15/plexus-utils-1.5.15.jar
[ERROR] urls[11] = file:/Users/zuhuanchen/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[12] = file:/Users/zuhuanchen/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[13] = file:/Users/zuhuanchen/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.11/plexus-interpolation-1.11.jar
[ERROR] urls[14] = file:/Users/zuhuanchen/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.2.3/jackson-databind-2.2.3.jar
[ERROR] urls[15] = file:/Users/zuhuanchen/.m2/repository/joda-time/joda-time/2.0/joda-time-2.0.jar
[ERROR] urls[16] = file:/Users/zuhuanchen/.m2/repository/com/google/guava/guava/15.0/guava-15.0.jar
[ERROR] urls[17] = file:/Users/zuhuanchen/.m2/repository/com/intellij/annotations/9.0.4/annotations-9.0.4.jar
[ERROR] urls[18] = file:/Users/zuhuanchen/.m2/repository/org/eclipse/jgit/org.eclipse.jgit/3.4.1.201406201815-r/org.eclipse.jgit-3.4.1.201406201815-r.jar
[ERROR] urls[19] = file:/Users/zuhuanchen/.m2/repository/com/jcraft/jsch/0.1.50/jsch-0.1.50.jar
[ERROR] urls[20] = file:/Users/zuhuanchen/.m2/repository/com/googlecode/javaewah/JavaEWAH/0.7.9/JavaEWAH-0.7.9.jar
[ERROR] urls[21] = file:/Users/zuhuanchen/.m2/repository/org/apache/httpcomponents/httpclient/4.1.3/httpclient-4.1.3.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[project>com.facebook.presto:presto-root:0.214-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]
[ERROR]
[ERROR] -----------------------------------------------------
[ERROR] : com.fasterxml.jackson.core.type.TypeReference
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException

master presto with maven version 3.6.0 and default maven settings

**Comment by dain** [comment]
I would guess that you got a bad checkout.  Try updating to the latest commit (fad950912543107f1d1eb71a2471e9c515726634) which successfully built on travis (https://travis-ci.org/prestodb/presto/builds/458590102).

**Comment by findepi** [comment]
@zuhuanchen i hope you resolved your problem already. Hence closing the issue.

In case you did not, please provide more info -- your environment, which commit you're building, and the command you run (eg `./mvnw` vs `mvn`)

**Comment by zuhuanchen** [comment]
> @zuhuanchen i hope you resolved your problem already. Hence closing the issue.
> 
> In case you did not, please provide more info -- your environment, which commit you're building, and the command you run (eg `./mvnw` vs `mvn`)

Mac OS 10.10.5
commit d7ae9113dd3fcbb2831ecc05e39c58d230c67ca0 (HEAD -> master, origin/master, origin/HEAD)
./mvnw clean install -DskipTests=true -Dmaven.test.skip=true -Dcheckstyle.skip=true -Dcheckstyle.skipExec=true -Dmaven.gitcommitid.skip=true

**Comment by findepi** [comment]
you can use `air.check.skip-all` to skip checkstyle & co. I never needed to set `maven.gitcommitid.skip` though. E.g
```
./mvnw clean install -TC2 -DskipTests -Dmaven.javadoc.skip=true -Dair.check.skip-all=true
```
what Java do you have?

**Comment by zeromem** [comment]
I have the same problem.
macOS MoJave 10.14.2, git 2.19.2, Java 1.8.0_151 , use ./mvnw .
commitid 378969278dfdec171b45c016b179ee3061be107c (release-0.219)

[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.1.13:revision (default) on project presto-root: Execution default of goal pl.project13.maven:git-commit-id-plugin:2.1.13:revision failed: A required class was missing while executing pl.project13.maven:git-commit-id-plugin:2.1.13:revision: com/fasterxml/jackson/core/type/TypeReference
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>pl.project13.maven:git-commit-id-plugin:2.1.13
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/zeromem/.m2/repository/pl/project13/maven/git-commit-id-plugin/2.1.13/git-commit-id-plugin-2.1.13.jar
[ERROR] urls[1] = file:/Users/zeromem/.m2/repository/org/slf4j/slf4j-jdk14/1.5.6/slf4j-jdk14-1.5.6.jar
[ERROR] urls[2] = file:/Users/zeromem/.m2/repository/org/slf4j/jcl-over-slf4j/1.5.6/jcl-over-slf4j-1.5.6.jar
[ERROR] urls[3] = file:/Users/zeromem/.m2/repository/org/apache/maven/reporting/maven-reporting-api/2.2.1/maven-reporting-api-2.2.1.jar
[ERROR] urls[4] = file:/Users/zeromem/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.1/doxia-sink-api-1.1.jar
[ERROR] urls[5] = file:/Users/zeromem/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.1/doxia-logging-api-1.1.jar
[ERROR] urls[6] = file:/Users/zeromem/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar
[ERROR] urls[7] = file:/Users/zeromem/.m2/repository/commons-cli/commons-cli/1.2/commons-cli-1.2.jar
[ERROR] urls[8] = file:/Users/zeromem/.m2/repository/org/codehaus/plexus/plexus-interactivity-api/1.0-alpha-4/plexus-interactivity-api-1.0-alpha-4.jar
[ERROR] urls[9] = file:/Users/zeromem/.m2/repository/backport-util-concurrent/backport-util-concurrent/3.1/backport-util-concurrent-3.1.jar
[ERROR] urls[10] = file:/Users/zeromem/.m2/repository/org/codehaus/plexus/plexus-utils/1.5.15/plexus-utils-1.5.15.jar
[ERROR] urls[11] = file:/Users/zeromem/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[12] = file:/Users/zeromem/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[13] = file:/Users/zeromem/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.11/plexus-interpolation-1.11.jar
[ERROR] urls[14] = file:/Users/zeromem/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.2.3/jackson-databind-2.2.3.jar
[ERROR] urls[15] = file:/Users/zeromem/.m2/repository/joda-time/joda-time/2.0/joda-time-2.0.jar
[ERROR] urls[16] = file:/Users/zeromem/.m2/repository/com/google/guava/guava/15.0/guava-15.0.jar
[ERROR] urls[17] = file:/Users/zeromem/.m2/repository/com/intellij/annotations/9.0.4/annotations-9.0.4.jar
[ERROR] urls[18] = file:/Users/zeromem/.m2/repository/org/eclipse/jgit/org.eclipse.jgit/3.4.1.201406201815-r/org.eclipse.jgit-3.4.1.201406201815-r.jar
[ERROR] urls[19] = file:/Users/zeromem/.m2/repository/com/jcraft/jsch/0.1.50/jsch-0.1.50.jar
[ERROR] urls[20] = file:/Users/zeromem/.m2/repository/com/googlecode/javaewah/JavaEWAH/0.7.9/JavaEWAH-0.7.9.jar
[ERROR] urls[21] = file:/Users/zeromem/.m2/repository/org/apache/httpcomponents/httpclient/4.1.3/httpclient-4.1.3.jar
[ERROR] urls[22] = file:/Users/zeromem/.m2/repository/org/apache/httpcomponents/httpcore/4.1.4/httpcore-4.1.4.jar
[ERROR] urls[23] = file:/Users/zeromem/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar
[ERROR] urls[24] = file:/Users/zeromem/.m2/repository/commons-codec/commons-codec/1.4/commons-codec-1.4.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[project>com.facebook.presto:presto-root:0.219.1-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] : com.fasterxml.jackson.core.type.TypeReference
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException

**Comment by chundongwang** [comment]
I ran into this and puzzled for a little bit so I guess it worth sharing here. I went ahead and cleared my maven repository (`~/.m2/repository`) and run `./mvnw clean install` and it worked.

In case you don't want to wait for `rm -rf`, you can simply change the name of your maven repository to something else.
