### ISSUE TITLE
Add rand(seed) function

### ISSUE THREAD

**Issue by archongum** [prestodb/presto#11968]
`new Random(seed).nextDouble()`

**Comment by archongum** [comment]
seed is a String would be better.
```java
    @Description("rand(String seed)")
    @ScalarFunction("rand")
    @SqlType(StandardTypes.DOUBLE)
    public static double randomWithSeed(@SqlType(StandardTypes.VARCHAR) Slice seed)
    {
        return new Random(seed.toStringUtf8().hashCode()).nextDouble();
    }
```

**Comment by findepi** [comment]
Wouldn't that always produce the same value? Do you mean to compute some kind of a hash of `seed`?

**Comment by dain** [comment]
@archongum, can you describe your high level goal for a function like this?

**Comment by martint** [comment]
If the goal is to produce a deterministic sequence of random numbers, this wouldn't be sufficient. It would be necessary to enumerate splits and rows in a deterministic order and well-defined partitioning. 

Since Presto is a distributed system, using `new Random(seed)` on every worker/split would result in repeated sequences within the same query. The implementation would need to be based on something like SplittableRandom.

See previous discussion in https://github.com/prestodb/presto/pull/3179

**Comment by archongum** [comment]
@dain I get it now.
I think I want to generate a unique 0 to 1 double number for a input object(for me String it is). In the case, the function name is not `rand(seed)` maybe `uniq_double(x, 0, 1)`?
For example,
```
select rand('a1'), rand('a2');
-- _col0, _col1
-- 0.8957974435711011	0.895707846897735
```
But according to above result, `String.hashCode()` is not the perfect seed by noting 0.895797.. is very close to 0.895707.. It would be find if inputs aren't sequential.
To improve:
1. with random: write a better hashCode() function
2. without random: ??

**Comment by dain** [comment]
After you generate this `double` value what will you do with it?  My guess is you are interested in a stable hash for sampling.  In that case I would use the built in xxhash functions.  Something like:
```
  SELECT from_big_endian_64(xxhash(to_utf8('mystring')))
```
This will get you a stable uniformly distribute hash value of the string.  The output value is a signed 64bit integer value.

**Comment by rschlussel** [comment]
closing this issue. @archongum feel free to reopen if @dain's suggestion isn't what you're looking for.

**Comment by jinqishen0725** [comment]
What a terrible solution here. Is it uniform distributed? What is the range of from_big_endian_64? Not to say it is very ugly.
