### ISSUE TITLE
array_intersect returns wrong results

### ISSUE THREAD

**Issue by yingsu00** [prestodb/presto#11978]
ARRAY_INTERSECT would skip 0-value if the arrays contain both NULL and 0-value:

Correct:
select ARRAY_INTERSECT(array[ 0], array[0])
-- [0]

Wrong:
select ARRAY_INTERSECT(array[ 0, null], array[0])
-- [null]

Correct:
select ARRAY_INTERSECT(array[ 0, 0, 1, 2], array[0, 0, 1, 2])
--[0,1,2]

Wrong:
select ARRAY_INTERSECT(array[ 0, 1, 2, null], array[0, 1, 2, null])
--  [null,1,2]

Wrong:
select ARRAY_INTERSECT(array[ 0, 0, 1, 2, null], array[0, 0, 1, 2, null])
--  [null,1,2]

Wrong:
select ARRAY_INTERSECT(array[ 0, 1, 2, null], array[0, 1, 2])
-- [null,1,2]

Correct:
select ARRAY_INTERSECT(array[ 0, 0], array[0, 0, null])
-- [0]

Wrong:
select ARRAY_INTERSECT(array[ 0, 0, null], array[0, 0, null])
--[null]

This is because it used type.equalTo() when advancing the indexes with same array value, and it doesn't distinguish between 0 and NULL.

**Comment by findepi** [comment]
This looks related to https://github.com/prestodb/presto/issues/11963
