### ISSUE TITLE
ARRAY_DISTINCT returns wrong results

### ISSUE THREAD

**Issue by yingsu00** [prestodb/presto#11977]
ARRAY_DISTINCT can't distinguish null from 0-value (e.g. 0 for INTEGER or false for BOOLEAN) when there're 2 elements in the array. Examples:

Correct
select ARRAY_DISTINCT(array[null, 0, 1])
-- [null,0,1]

Correct
select ARRAY_DISTINCT(array[null, 0, 0])
-- [null,0]

Wrong
select ARRAY_DISTINCT(array[null, 0]) 
-- [null]

correct
select ARRAY_DISTINCT(array[null, true])
-- [null,true]

Correct
select ARRAY_DISTINCT(array[null, false, false])
-- [null,false]

wrong
select ARRAY_DISTINCT(array[null, false])
-- [null]

The problem was because it used type.equalTo() to compare the elements when the cardinality of array is two, and type.equalTo() doesn't check for nullness.

**Comment by findepi** [comment]
I think this is basically the same as https://github.com/prestodb/presto/issues/11963 and should be fixed by https://github.com/prestodb/presto/pull/11979
