### ISSUE TITLE
Cannot escape '_' (underscore) in like statement.

### ISSUE THREAD

**Issue by danielcweeks** [prestodb/presto#1198]
Escaping the underscore in a like statement results in no records being matched.

Example:
`select * from mytable where category like '%\_common';`

Will not match any results.  Without the `\`, it will match `_uncommon`.

Escaping doesn't appear to be working properly.

**Comment by hellopower** [comment]
How can I input a quote?  I try '\ ' to escape, but failed.

`select '\'' ESCAPE '\'  from test`

**Comment by electrum** [comment]
@hellopower in standard SQL, single quotes are escaped by doubling them: `SELECT 'it''s great'`

**Comment by dlamblin** [comment]
Why is there no documentation within presto's SQL doc about LIKE?
This page mentions it, but that's it. https://prestodb.io/docs/current/functions/regexp.html

**Comment by electrum** [comment]
We should document it here: https://prestodb.io/docs/current/functions/comparison.html

**Comment by oaustegard** [comment]
It's been 2.5 years plus and no movement on documenting LIKE and the wildcards it uses...

**Comment by rongrong** [comment]
@oaustegard do you want to submit a PR?

**Comment by oaustegard** [comment]
Might have to - meanwhile found the Test cases for the LIKE syntax - so that helps: https://github.com/prestodb/presto/blob/9aa8f80edf946d26760012d9da4c1b34cff25eb7/presto-main/src/test/java/com/facebook/presto/sql/TestExpressionInterpreter.java#L1223
