### ISSUE TITLE
Does presto support Mycat?

### ISSUE THREAD

**Issue by Greed2nd** [prestodb/presto#11994]
- I create a catalog properties file in etc/catalog named mycat.properties. 
```
connector.name=mysql
connection-url=jdbc:mysql://***.***.126.116:8066
connection-user=root
connection-password=root
```
- Then,I use Presto CLI excute my query SQL : select * from mycat.TESTDB.table, but it return "ResultSet is from UPDATE. No Data." 
Does it support Mycat like Mysql？Thanks for your help.

**Comment by dain** [comment]
You can name your catalog anything, so `mycat` should work.  I don't recognize that error message; maybe it is from the mysql driver itself.  Can you run the cli with the `--debug` option and post the stack trace?

**Comment by lidong0223** [comment]
> You can name your catalog anything, so `mycat` should work. I don't recognize that error message; maybe it is from the mysql driver itself. Can you run the cli with the `--debug` option and post the stack trace?

Thanks for your reply.
Let me show you  the stack trace .`select * from testdb.TESTDB.product_barcode`
![testdb](https://user-images.githubusercontent.com/30827455/49269623-d5942280-f4a0-11e8-9d84-3e5a751e09ec.png)

**Comment by ebyhr** [comment]
The error message seems the same as this topic on stackoverflow.
https://stackoverflow.com/questions/32682916/mysql-java-sql-sqlexception-resultset-is-from-update-no-data

**Comment by success110** [comment]
@Greed2nd 
ResultSet is from UPDATE. No Data. 
Help, how to solve this problem? Have you solved it?
