### ISSUE TITLE
Presto down on all worker suddenly 

### ISSUE THREAD

**Issue by AlaaMonem89** [prestodb/presto#11997]
Hi how are you ?
Please help me with the recommendation configuration for presto workers and coordinator.
assume i have 512G memory on each server

**Comment by AlaaMonem89** [comment]
The workers  be down when some query run on it please I need to force to kill like these query

**Comment by dain** [comment]
We will need more information before someone can help.  Do you know why they crashed?  Did you get anything printed in the logs?  Do you have a stack trace?

**Comment by rschlussel** [comment]
closing this issue.  Reopen if you can provide more information @AlaaMonem89
