### ISSUE TITLE
presto return error when I query a sql from hive

### ISSUE THREAD

**Issue by cylovefree** [prestodb/presto#11991]
## presto
version:0.184
## hive
version:2.1.1

My hive create table sql like this
```
CREATE EXTERNAL TABLE test(country varchar(32), ext map<string,string>)
partitioned by(dayid INT)
ROW FORMAT SERDE 'org.apache.hive.hcatalog.data.JsonSerDe'
STORED AS TEXTFILE;
``` 
And My presto sql like this
```
select ext from test where dayid = 20181127;
```
And presto return error like this
```
Query 20181128_074858_00011_a74ve failed: com.facebook.presto.hive.$internal.org.codehaus.jackson.JsonParseException: Unexpected character ('e' (code 101)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.ByteArrayInputStream@5b5d177a; line: 1, column: 759]
```
Does presto not support the hive map type colum or I mistake some config?

Thanks a lot for your help!

**Comment by dain** [comment]
That error message means that one of the files contains invalid JSON.  Unfortunately, the error message does not contain the file name, but it does contain the position `line: 1, column: 759`.  Do you have a lot of files?  You can filter files using the hidden `"$path"` (note the quotes are required due to the `$`) column.

**Comment by cylovefree** [comment]
> That error message means that one of the files contains invalid JSON. Unfortunately, the error message does not contain the file name, but it does contain the position `line: 1, column: 759`. Do you have a lot of files? You can filter files using the hidden `"$path"` (note the quotes are required due to the `$`) column.

Thanks for your reply!
My hive table include files mapping from hdfs, so I will check those file which contain the invalid json column.
And I'm confused about the "filter files using the hidden `"$path"", could you give me the doc link or description about the "$path" usage in presto.
Thanks a lot!

**Comment by findepi** [comment]
@cylovefree this would be like this:
```
select ext, "$path" from test where dayid = 20181127;
```
of course, this won't show up for a failed query, so you would need to modify your condition to narrow down your condition to identify which files are good.

Btw, could you please share the full stacktrace with us? (run CLI with `--debug`). Usually, the full stacktrace contains the name of the file being read.

**Comment by cylovefree** [comment]
> @cylovefree this would be like this:
> 
> ```
> select ext, "$path" from test where dayid = 20181127;
> ```
> of course, this won't show up for a failed query, so you would need to modify your condition to narrow down your condition to identify which files are good.
> 
> Btw, could you please share the full stacktrace with us? (run CLI with `--debug`). Usually, the full stacktrace contains the name of the file being read.

Thanks for your reply.
And I found my row data table contain the invalid json type, that may be the reason.
I will close this issue.
Thank you for your help!
