### ISSUE TITLE
Enhance QueryCompleted event and query UI to include prepared sql for EXECUTE statements

### ISSUE THREAD

**Issue by sshardool** [prestodb/presto#12009]
Currently for any EXECUTE statement any of the query life-cycle events do not contain information about the query used in the corresponding PREPARE statement .  
Similarly the query UI does not display the sql of the prepared statement when displaying an Execute statement. 
 
Theoretically it may be possible to lookup the prepared statement sql from the statement name used in the corresponding Execute but in practice its quite cumbersome to do this and also assumes that events will be logged in a form that can be queried easily in future. 

I believe logging the actual prepared statement sql is at least as important and useful as the Execute statements. For investigating query behavior or tracking performance a of a query over a period of time I almost always have to locate the corresponding prepared statement for the investigation to be meaningful.

I propose the following enhancements:
1. Capture the prepared statement sql as part of the QueryCompletedEvent
2. Display prepared statement sql along with the EXECUTE statements in the presto UI, at least on the Query Details page (query.html)

I am looking into making this enhancement, appreciate any suggestions.

**Comment by aweisberg** [comment]
@findepi Please be careful when selecting what issue is closed.

**Comment by findepi** [comment]
@aweisberg i understand you might be new to GitHub -- this is how GitHub works, it was not my deliberate action.
Please be careful when making a blame or assumptions.
