### ISSUE TITLE
Feature Request: CIDR support

### ISSUE THREAD

**Issue by joshgodsiff** [prestodb/presto#12012]
Hey, I noticed an `IPADDRESS` data-type has been added. My company works with IP addresses a lot, so this is really helpful to us. 😄

It would be awesome if there was also support for equivalent CIDR types - for example: `1.0.0.0/8`

Similarly, it would be nice to be able to query based on CIDR: for example, `SELECT some_ip_column FROM blah WHERE some_ip_column IN 1.0.0.0/8` or something similar.

**Comment by martint** [comment]
This seems reasonable, but we'd do it using functions instead co-opting the SQL `IN` operator with that behavior. We may also need to introduce a CIDR type to make it possible to do something like:

```
contains(<cidr>, <ip address>)
```

Alternatively, we could break up the cidr into its components (address + mask size) and do something like:

```
contains(<prefix address>, <mask size>, <ip address>)
```

**Comment by ssaumitra** [comment]
I see that IPPREFIX datatype for CIDR and `is_subnet_of` documented in https://prestodb.io/docs/current/functions/ip.html should do what's being requested. So the following query should just work
```
SELECT
    is_subnet_of(IPPREFIX '1.0.0.0/8', IPADDRESS '1.0.0.10')
FROM my_table
```
CC. @rongrong
