### ISSUE TITLE
Create separate user and system level timeouts

### ISSUE THREAD

**Issue by elonazoulay** [prestodb/presto#12010]
Add a session property to have 2 timeouts (system defined, user defined) instead of one. 
The use case for this is to facilitate debugging issues where the system timeout is exceeded and filter out queries where the users set their timeout too low.

Created the issue before working on this feature to gather comments and ideas.

**Comment by findepi** [comment]
Do you mean to have settings that helps Presto works correctly while being under debugger, with breakpoints set?

**Comment by elonazoulay** [comment]
That's a great idea! I would manually set all timeout settings and there are often issues (ex. new timeout configs). I would like to create an issue for that as well.

This issue is for a different timeout - it's to differentiate between system timeout and user timeout (not greater than system timeout) set as a session property. Different error codes would be returned so that you can look at query logs and determine whether the user set their timeout too low.

We have a use case where users lower their timeout below the default value (in client code for example) and queries timeout when data size grows.

**Comment by findepi** [comment]
> We have a use case where users lower their timeout below the default value (in client code for example) and queries timeout when data size grows.

Which particular timeouts do you mean?

**Comment by elonazoulay** [comment]
The "query_max_execution_time" system property that's used to get max query execution time.

**Comment by raghavsethi** [comment]
@findepi The idea is that admins can set some timeouts, and users can set a different set of timeouts. In the case where the user sets timeouts, the query fails with a user error, otherwise with an insufficient resources error. This is similar to the previous PR with kill vs pre-empt. This simplifies resource management using the session property configuration manager.

**Comment by raghavsethi** [comment]
We have users who set their own timeouts as a way to limit their resource consumption, limit the amount of data produced, or to do best-effort work. For these use cases, we want the queries to fail with a different error code.
