### ISSUE TITLE
java.lang.UnsupportedOperationException: com.facebook.presto.spi.type.DoubleType

### ISSUE THREAD

**Issue by santosh-kore** [prestodb/presto#12016]
I'm using latest Presto Server Version `presto-server-0.214`...

Hive Create Table Query:

```
create external table some_table_name(col1 double,col2 double) partitioned by (col3 string)  stored as parquet location 's3://<some location>';
```

The parquet file's schema is:

```
       {
		"field_name": "col1",
		"name": "col1",
		"numpy_type": "float64",
		"pandas_type": "float64"
	}, {
		"field_name": "col2",
		"name": "col2",
		"numpy_type": "float64",
		"pandas_type": "float64"
	}

```

Hive table created successfully but Presto throws below error,

`java.lang.UnsupportedOperationException: com.facebook.presto.spi.type.DoubleType`

Also tried setting ```hive.parquet.use-column-names=true``` but no luck...

**Comment by mbasmanova** [comment]
@santosh-kore Could you paste the full stack trace?

**Comment by mbasmanova** [comment]
@santosh-kore Looks like float64 columns are processed as long columns. What's the output of `desc some_table_name`? What column types is shows?

CC: @zhenxiao

**Comment by santosh-kore** [comment]
@mbasmanova Ohh i thought `float64` is `double` in hive... and in presto `desc some_table_name` output is,

```
                 Column                 |  Type   |     Extra     | Comment 
-----------------------------+---------+---------------+--------------------	
 col1   								| double  |               |         
 col2                					| double  |               |         

```

**Comment by nezihyigitbasi** [comment]
@santosh-kore This is a schema mismatch issue. You can confirm that with the parquet-tools and compare the schema in the parquet file and the table schema (that you get with `DESC`).

**Comment by ajayMaletira** [comment]
hey guys, i still see the issue? i am able to query from hive but presto keeps complaining about double.
