### ISSUE TITLE
a different search result between hive and presto ,a big serious problem

### ISSUE THREAD

**Issue by hiliuxg** [prestodb/presto#12026]
the sql like this :
select count(1) from temp.test_xxx  where dt = '2018-12-05' ;

use hive  to run result like this :
![image](https://user-images.githubusercontent.com/39675622/49589178-aea78600-f9a3-11e8-8914-5efe3c14aa07.png)

use presto to run result like this :
![image](https://user-images.githubusercontent.com/39675622/49589250-deef2480-f9a3-11e8-9e0f-0670b47fbe80.png)

the files on hdfs like this :
![image](https://user-images.githubusercontent.com/39675622/49589309-047c2e00-f9a4-11e8-91fb-f8c2067750cf.png)

may be the reason for the different is because there are secondary directories under the dt partition and the secondary directory is generated because of the 'union all' keyword in the sql when hive insert

this is a big serious problem , because i do not know whether there is a secondary directory under dt partition and i need to run twice sql ,one in hive and one in presto to confirm the result is right .  Hope to fixing this problem, or reporting an exception directly.

**Comment by martint** [comment]
What version of Hive did you use to generate the data in those directories?

**Comment by qqibrow** [comment]
If secondary directory is the root cause, try set `hive.recursive-directories = true` in `hive.properties`.

**Comment by hiliuxg** [comment]
> What version of Hive did you use to generate the data in those directories?
apache-hive-1.1.0  ,the new version do not generate the secondary directories ?

**Comment by hiliuxg** [comment]
> If secondary directory is the root cause, try set `hive.recursive-directories = true` in `hive.properties`.

it works ,thanks !  Why not set this configuration to true by default ?

**Comment by qqibrow** [comment]
> > If secondary directory is the root cause, try set `hive.recursive-directories = true` in `hive.properties`.
> 
> it works ,thanks ! Why not set this configuration to true by default ?

Not sure about that. @martint Shall we consider set `hive.recursive-directories = true` as default?

**Comment by martint** [comment]
Is that the default behavior in Hive now? It wasn't when we first added this option, so we decided to keep it disabled by default. See https://github.com/prestodb/presto/issues/7873

**Comment by nezihyigitbasi** [comment]
Looks like the Hive config that was disabling recursive listing by default has been removed in HIVE-11582 saying that the config is redundant after MAPREDUCE-1501. The `mapred.input.dir.recursive` config used by that MapReduce patch still defaults to false (and also the default in Hadoop [trunk](https://github.com/apache/hadoop/blob/trunk/hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-core/src/main/java/org/apache/hadoop/mapred/FileInputFormat.java#L223) is still false).
