### ISSUE TITLE
Presto not able query Hive partition external table

### ISSUE THREAD

**Issue by SivaSamrajS** [prestodb/presto#12025]
I have created the External table on hive from hadoop path with year and month partitions.
I have connected the hive with presto. I am able to query the data in hive, but the same table is not returning the data with presto(returning 0 rows). 
Presto: 0.213
`presto:retaildemov2> select * from customer;
 customer_id | account_num | lname | fname | mi | address1 | address2 | address3 | address4 | city | state_province | postal_code | country | customer_region_id | phone1 | phone2 | birthdate | marital_sta
-------------+-------------+-------+-------+----+----------+----------+----------+----------+------+----------------+-------------+---------+--------------------+--------+--------+-----------+------------
(0 rows)`

`num_cars_owned       | integer   |               |
 fullname             | varchar   |               |
 event_ts             | timestamp |               |
 year                 | varchar   | partition key |
 month                | varchar   | partition key |`

**Comment by findepi** [comment]
When you create external table, you need to define all the partitions. 
You can do this in Hive, by running `msck repair table <table-name>;`

**Comment by shlomialfasi** [comment]
Can the msck repair command run from Presto?

**Comment by nezihyigitbasi** [comment]
> Can the msck repair command run from Presto?

No, it's a hive command.

**Comment by prabakarankrishnan** [comment]
I also facing same problem. MSCK repair I did. I am able to query in Hive. But still presto not able to access...

**Comment by yuzhu** [comment]
i have noticed that after msck repair, i needed to run a select query in hive before presto can pick up the change and show results for select queries.. no idea why though..

**Comment by friendofasquid** [comment]
Hello from 2021.

At some point, looks like Presto has added `system.sync_partition_metadata` which should remove the need to run `msck repair` in Hive / Spark / Athena.
