### ISSUE TITLE
is there any way to get the cluster memory information from restful api?

### ISSUE THREAD

**Issue by wususu** [prestodb/presto#12022]
Hello, I am searching a way to get the Memory usage information of cluster
/v1/status only can get the coordinator node's memory usage info, is there any way to get other node's?
thxs

**Comment by nezihyigitbasi** [comment]
Workers also have the `/v1/status` endpoint. When you run a query and look at its details you will see the list of workers that ran the tasks of that query. If you click on a worker you will see its heap usage and other details. Many of these details are retrieved from the `/v1/status` endpoint on that particular worker.

If you want to get details about which queries/operators use how much memory on a worker or across the entire cluster, then you can use  (note that this memory usage info is tracked by Presto itself),:
- `/v1/cluster/memory` => coordinator's view of cluster memory usage (with query/operator details).
- `/v1/memory/{pool_id}` => info about a worker's memory pool (with query/operator details). `pool_id` can be general/reserved/system.

**Comment by wususu** [comment]
It help me a lot,thx
