### ISSUE TITLE
Always use `toIntExact` provided by `Math`

### ISSUE THREAD

**Issue by wenleix** [prestodb/presto#12037]
Presto uses `Math.toIntExact` in most places, but `StrictMath.toIntExact` in a few places, which seems to be accidental mistakes.

`StrictMath.toIntExact`  directly delegates to `Math.toIntExact`. We should always use `Math.toIntExact` to avoid confusion (and probably add a checkstyle rule? )

**Comment by martint** [comment]
`StrictMath` conveys specific semantics about floating point operations. In cases where strict semantics may be needed, the right thing is to use `StrictMath`'s version. Even if the method delegates to `Math.toIntExact` *currently*, that might change in the future. As a sidenote, don't rely on what the JDK source code says. Sometimes (though not in this case), methods are intrinsified by the VM, so what you see may not be what you get.

**Comment by martint** [comment]
Huh.. I didn't realize `toIntExact` in `StrictMath` was for converting from long->int. That doesn't make a lot of sense, since it doesn't involve floating point at all, and the semantics for that conversion are well-defined.
