### ISSUE TITLE
Reject @BeforeMethod annotations on tests without `singleThreaded=true`

### ISSUE THREAD

**Issue by findepi** [prestodb/presto#12044]
`@BeforeMethod` in a class that is not `@Test(singleThreaded=true)` is usually (always?) a bug. Example: https://github.com/prestodb/presto/pull/12042#issuecomment-446007770
We should automatically find & reject them.
This can be done with some TestNG listener or something.

**Comment by electrum** [comment]
I think this would need to be done using a custom Checkstyle rule. Adding a listener would require adding a new test dependency to every module.

**Comment by DDFaller** [comment]
if the the error weren't resolved, could i make these changes?
