### ISSUE TITLE
Port Parquet-1178, Parquet-1396 to Presto-Parquet

### ISSUE THREAD

**Issue by shangxinli** [prestodb/presto#12048]
I open this issue to track the porting of https://issues.apache.org/jira/browse/PARQUET-1178 and https://issues.apache.org/jira/browse/PARQUET-1396 that are needed for parquet encryption and modular encryption. 

Currently, the code of Parquet-1178 and Parquet-1396 are not ready yet. Hence this issue is open for tracking purpose first. Once it is ready, I will start porting. 

For the details of parquet-encryption, reader can refer the design of Parquet-1178 and Parquet-1396.

**Comment by ryanrupp** [comment]
As part of this are you looking to upgrade the version of `parquet-mr` used? Not sure what porting meant in this case but if it it was cherry picking out those changes somehow I just wanted to link the Iceberg plugin which discussed upgrading the old version of the parquet library being used, see - https://github.com/prestodb/presto/pull/11767#issuecomment-432838204

**Comment by shangxinli** [comment]
We are not very clear whether or not upgrading parquet-mr version is mandatory because the code for  Parquet-1178 and Parquet-1396 are still under construction. Yes, the porting means cherry picking. Since the Parquet-1178 and Parquet-1396 will be on top of the newest version of Parquet-format and Parquet-mr, upgrading Parquet-format will be mandatory and upgrading parquet-mr will be preferable if not mandatory(not sure mandatory yet as mentioned above). 

Since this task won't be a trivial task, I just want to open an issue earlier to bring the discussion to the community. While we are working on Parquet-1178 and Parquet-1396, we will keep an eye on this task to make the porting feasible. 

The reason why we need this task is that once column access control is enforced on the table data, Presto is required to support encryption to read the data as a query engine.

**Comment by zhenxiao** [comment]
thanks @shangxinli for tracking it
@ryanrupp I think it is a good idea to upgrade parquet-mr
since Presto is using its own optimized Parquet Reader, and no longer depending on parquet-mr to read Parquet files, when the column level encryption features are implemented in Parquet, we have to implement similarly in Presto's own Parquet Reader. upgrade parquet-mr might not resolve all problem

**Comment by shangxinli** [comment]
I have the change now and it can work with the tests that I have. Once Parquet-1.11.0 release and Parquet-1178 checked in, I will create pull request.

**Comment by VladimirRybalko** [comment]
@shangxinli 
There is still no columnar encryption functionality in Presto? 
Is this PR going to be merged with the main branch?

**Comment by shangxinli** [comment]
Once the parquet is upgraded, I will make PRs. Currently, we are blocked on parquet version upgrade.

**Comment by shangxinli** [comment]
I would like to reopen this issue as the code change has been ready.
