### ISSUE TITLE
Verifier: sort arrays before comparing

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#12049]
To avoid false positives when comparing query results Verifier rounds floating point values: `checksum(round(c, 3))`. Similar technique is necessary for array types to avoid flagging arrays that differ only in the order of the elements. E.g. Verifier should use `checksum(array_sort(c))` instead of `checksum(c)`.

CC: @nezihyigitbasi @ggreg @zaynoon

**Comment by rongrong** [comment]
What we do in validator is to provide both. The problem with only use sorted result is that arrays are only sometimes treated as set, but other times order actually matters (for example, if the query actually has an `array_sort`.

**Comment by mbasmanova** [comment]
@rongrong I think the goal for the Validator should be to perform as much verification as possible while reporting minimum false positives. At the moment, there are too many false positives. Hence, I think reducing these should be the priority.

**Comment by rongrong** [comment]
The problem with only compute a checksum for sorted array is it might hide errors. When the expected output should be ordered and the checksum does not match without sorting, it's actually a correctness issue that would be hidden if you only report the sorted checksum. Unless we could know from analyzing the query whether the result should be ordered, we can not safely assume `array_sort(a)` is equivalent to `a`.

**Comment by rongrong** [comment]
I agree with all the problems you mentioned. We should try to reduce false positives (or false negatives?). In validator we compute error margins for doubles. We can port all those improvements to verifier. I was only pointing out that we should not blindly remove checksum of the original array and replace it with a sorted one.

**Comment by mbasmanova** [comment]
@rongrong 

> we should not blindly remove checksum of the original array and replace it with a sorted one.

We can compute two checksums: `checksum(c)` and `checksum(array_sort(c))`. The question is what to do when sorted checksums match, but unsorted don't. We could report SUCCESS with extra information that clarifies that certain array columns match only when sorted. Would that work?

**Comment by mbasmanova** [comment]
@rongrong I thought about this some more and came to a conclusion that it is reasonable to compute checksums on sorted arrays only. Verifier already uses order-insensitive checksum and applies to individual columns independently. When these checksums match there is a high change the underlying data also matches, but it is not a guarantee. Here is an example where checksums match, but the data doesn't.

```
WITH a AS (
    SELECT * FROM (
        VALUES 
            (1, 'x'),
            (2, 'y')
    ) AS t(id, name)
),
b AS (
    SELECT * FROM (
        VALUES 
            (2, 'x'),
            (1, 'y')
    ) AS t(id, name)
)
SELECT checksum(id), checksum(name) FROM a
UNION ALL
SELECT checksum(id), checksum(name) FROM b
```

Therefore, I believe we can continue aiming for the Verifier to provide high-confidence results - match or not - but make it a non-goal to provide a guarantee. With that in mind, we currently have high confidence "match" results, but very low confidence "don't-match" results. Starting to apply checksum to sorted arrays will keep "match" results as high-confidence and improve confidence of "don't-match" results.

**Comment by martint** [comment]
The fact that it currently is order-insensitive in some cases Is because it was (is?) impossible to do it any other way with current presto limitations. 

Instead of or in addition to calculating individual column checksums, it should calculate a checksum of the entire row.

The goal of the verifier is to be as precise as possible, so we should be trying to move in that direction, not relaxing it.

**Comment by mbasmanova** [comment]
@martint 

> The goal of the verifier is to be as precise as possible, so we should be trying to move in that direction, not relaxing it.

Martin, this doesn't seem to be practical. At least at this point. We are seeing way too many false negatives, e.g. Verifier reports "results mismatch", but upon manual inspection it turns out that this is due to non-determinism in the query. Do you think Verifier should detect and reject non-deterministic queries? If not, how do you suggest we handle these?

**Comment by martint** [comment]
We can certainly improve the verifier to produce an explanation about why the results are different. That’s one of the reasons we had listed the verifier in the internal roadmap at FB — but it was never high enough priority or sparked enough interest for someone to tackle it.

Btw, the verifier currently has a mechanism to try to detect non-deterministic queries (if results don’t match, it runs the control query a few times and sees if results change). If it deems the query is not deterministic it reports that in the results. Also, it’s important not to confuse what the verifier (in the Presto codebase) does vs how the information is presented in the internal FB UIs and tools.

Ultimately, the verifier is trying to answer the question: “are the results of executing this query consistent with the semantics of the query, and if not, what’s likely to be broken?”. We should use that as framing when thinking about changing or improving it.

**Comment by dain** [comment]
One big issue with the verifier is the "non-deterministic" checker, does not work for `INSERT` queries.  The checker is currently only retrying the check sum query and does not rerun the insert query each time.

**Comment by caithagoras** [comment]
Addressed by recent verifier changes
