### ISSUE TITLE
PrestoS3FileSystem breaks read-after-wrtite strict S3 consistency

### ISSUE THREAD

**Issue by sopel39** [prestodb/presto#12046]
Method: `com.facebook.presto.hive.s3.PrestoS3FileSystem#create`
will check for file existence when `overwrite==false`. File existence check will break read-after-write strict S3 consistency per S3 doc:
```
Amazon S3 provides read-after-write consistency for PUTS of new objects in
your S3 bucket in all regions with one caveat. The caveat is that if you make a
HEAD or GET request to the key name (to find if the object exists) before
creating the object, Amazon S3 provides eventual consistency for read-after-write. 
```

The existence check itself is weak as the file might be created while data is gathered in staging directory for upload.

I propose to remove the check of use `LIST` S3 request instead that does not break `read-after-write` consistency.

FYI: @findepi

**Comment by nezihyigitbasi** [comment]
Just curious, does this weakening of the consistency guarantee break/cause any trouble for any Presto user right now? Even if it does not, I think this is nice to have.

BTW, I think we should specify a small `maxKeys` value for the listing operation, so that it doesn't hurt performance (by default a list operation can return up to 1K results).

**Comment by sopel39** [comment]
> Just curious, does this weakening of the consistency guarantee break/cause any trouble for any Presto user right now? Even if it does not, I think this is nice to have.

It does. For example when Hive SerDe is used for data write, `com.facebook.presto.hive.s3.PrestoS3FileSystem#create` is called with `override=false` which triggers `GET` S3 request.

Fortunately, optimized ORC writer uses default `FileSystem#create` method, which uses `override=true`. Therefore for optimized writer consistency should not be broken.

> BTW, I think we should specify a small maxKeys value for the listing operation, so that it doesn't hurt performance (by default a list operation can return up to 1K results).

Good idea
