### ISSUE TITLE
create table fail when just drop table with hiveconnector immediately

### ISSUE THREAD

**Issue by xiefu5hh** [prestodb/presto#12058]
I use the hiveconnector to create  tables for tempory use,so when I need to recreate it，I drop the table and create it immediately.
the drop sql is execute success,but when I create it ,it was error ,error note was the table is already exists.
It is the Consistency problem? how to avoid this?

**Comment by dain** [comment]
When a drop table is sent to Presto, it immediately executes the drop on the Hive metastore, so you should not get an error recreating the table.  Can you post the full stack trace from the error message?  If you are using the Presto CLI make sure to run it with the `--debug` flag to get the full stack.

**Comment by xiefu5hh** [comment]
> When a drop table is sent to Presto, it immediately executes the drop on the Hive metastore, so you should not get an error recreating the table. Can you post the full stack trace from the error message? If you are using the Presto CLI make sure to run it with the `--debug` flag to get the full stack.

I check the uri,the drop query is success,but get error table exists when I recreate it. I think the debug mode has no more infomation. Does the drop query design has the consistency problem?

**Comment by dain** [comment]
We will need the stacktrace and error message to help you.  The "drop" happens in the Hive metastore process, which is maintained by the Apache Hive project.  IIRC, you can get errors like these when using S3 for the storage, since it has eventual consistency for deletes.
