### ISSUE TITLE
Cannot obtain exact count of query stats such as startedQueries because SqlQueryManagerStats uses CounterStat()

### ISSUE THREAD

**Issue by satoshihirose** [prestodb/presto#12069]
I would like to get exact count of submittedQueries which is submitted in certain time window like 1 min, 5 min etc and same as whole another stats.

Stats such as queuedQueries and runningQueries are using AtomicInteger so it provides exact count of them.
On the other hand, another stats such as submittedQueries and startedQueries are using CounterStat, CounterStat is using DecayCounter in Airlift so they don't provide exact number of them.
https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/execution/SqlQueryManagerStats.java
https://github.com/airlift/airlift/blob/master/stats/src/main/java/io/airlift/stats/CounterStat.java

DecayCounter provides a value which is reduced by 1/e in a certain time window.
I think my concern will be resolved if there is an implementation of a counter provides a value which turns into 0 when a certain time passes.

Anybody has any comment about this idea?
I will implement it if I could not find such implementation.

**Comment by dain** [comment]
If you add a custom even listener via the plugin apis, you should be able to add any stats you want.

**Comment by satoshihirose** [comment]
I will try to figure out how to implement the demand with custom event listener.
Thanks for your comment.
