### ISSUE TITLE
MinDuration in Connector configs are not working

### ISSUE THREAD

**Issue by zhenxiao** [prestodb/presto#12075]
MinDuration in presto-main is guarding properties' minValue as expected
while, seems for connector properties, it is not working
e.g. in Hive Connector, we could set:
hive.dfs.connect.timeout=0s
with Hive Connector launched with no problem, although it has a MinDuration guard

Interestingly, Hive Connector has a small number of checkArguments to make sure some of the properties require a minValue, e.g. hive.dfs-timeout

**Comment by electrum** [comment]
I tried changing the config in `HiveQueryRunner` and it failed as expected:
```
3) Error: Invalid configuration property hive.dfs.connect.timeout: {io.airlift.units.MinDuration.message} (for class com.facebook.presto.hive.HiveClientConfig.dfsConnectTimeout)
```
(the error message is bad but that's a bug in the `MinDuration` validator)

**Comment by zhenxiao** [comment]
Hi @electrum when I tried in HiveQueryRunner, the MinDuration is working as expected.
But when I tried to launch it in local debug cluster or small cluster, seems it is not guarding as expected.
I tried putting:
hive.dfs.connect.timeout=0s
in hive.properties, then a small Presto cluster could launch with no problem.

Find similar behavior for other connectors too.

**Comment by zhenxiao** [comment]
CC @nezihyigitbasi when we discuss similar issues for Elasticsearch connector.
When using *QueryRunner, the MinDuration is working as expected, but when using it to launch clusters, it is not guarding MinDuration

**Comment by electrum** [comment]
Ugh, this is probably some sort of class loader issue. Let me dig into this.
