### ISSUE TITLE
Introduce log() function conforming to SQL 2016

### ISSUE THREAD

**Issue by findepi** [prestodb/presto#12085]
Follow up of https://github.com/prestodb/presto/issues/9939

- [ ] remove `deprecated.legacy-log-function` feature toggle
- [ ] add back the `log()` function as it was before https://github.com/prestodb/presto/pull/10069 but with the arguments swapped: `log(base, value)`

**Comment by Praveen2112** [comment]
@findepi I have raised the PR (#12127) which adds back the log() function with arguments swapped
