### ISSUE TITLE
Incorporate WorkProcessor in operators

### ISSUE THREAD

**Issue by sopel39** [prestodb/presto#12096]
Issue for effort to support:
* cross operator lazy pages (starting from source operators)
* cleanup/simplify contract between operators via WorkProcessor pipelines
* provide base for further improvements (e.g: on stack rows without Page materialization, Graal)

The advantage of cross operator lazy pages is that we can avoid IO when queries are highly selective. This requires that significant processing happens in source stage, but this becomes more and more the case with improvements like CBO ("broadcast joins") or grouped execution.

Stages are:
- [x] **Stage 1**

* base `PageProcessor` on `WorkProcessor`

- [ ] **Stage 2**
* internally base `ScanFilterAndProject` on `WorkProcessor`. The pipeline would look like follows:
```
split singleton -> [flatMap] -> pages source
                -> [transform] -> page processor 
                -> [transform] -> merge pages
```
or if split is cursor based
```
split singleton -> [flatMap] -> cursor source -> [transform] -> merge pages
```
* internally base `FilterAndProject` on `WorkProcessor`. The pipeline would look like follows:
```
page buffer -> [transform] -> page processor -> [transform] -> [merge pages]
```

- [ ] **Stage 3**
* create interface for operators that are based on `WorkProcessor` pipelines
* create standarized abstract operator class for operators that internally are based on `WorkProcessor` pipelines
* combine operators that are based on `WorkProcessors` via dedicated "gluing" operator
* base `TopNOperator` on `WorkProcessor` pipelines (fast data exploration!)

**Comment by nezihyigitbasi** [comment]
> provide base for further improvements (e.g: on stack rows without Page materialization, Graal)

Can you give details about the "Graal" plans?
