### ISSUE TITLE
Query will failure with Internal error when partition only have a empty file

### ISSUE THREAD

**Issue by rockxsj** [prestodb/presto#12128]
First of all my file store in AWS S3.
The bug could by reproducted by create a external table and add some partitions to it. If some partitions only have one empty file and then you query these partitions, you will get a Internal error. 
:(

**Comment by findepi** [comment]
What is the file format of  your table?

**Comment by dain** [comment]
Can you post the error message and stacktrace you get  when run the cli with `--debug`?
