### ISSUE TITLE
Questions about "order by rand()"

### ISSUE THREAD

**Issue by daikon12** [prestodb/presto#12134]
Question:

 When I add "order by rand()" in SQL, only one query will run, and the other will be queued at the same time; But if I remove  "order by rand()" from the same SQL ,all the query will run at the same time。What is the reason for this phenomenon？

without   "order by rand()" ：
![image](https://user-images.githubusercontent.com/8246136/50442869-d737f580-093b-11e9-8110-177b5a73d1b1.png)

with  "order by rand()"：
![image](https://user-images.githubusercontent.com/8246136/50442898-fa62a500-093b-11e9-840e-d9b4f854deb8.png)

Any relevant ideas are welcome！

**Comment by sopel39** [comment]
`order by` requires storing all data in cluster memory for sorting purposes. It could be that query max memory per node is too low.

**Comment by daikon12** [comment]
> `order by` requires storing all data in cluster memory for sorting purposes. It could be that query max memory per node is too low.

Yes ， you are right,  `order by` requires storing all data in cluster memory. but there are 12 nodes in  my presto cluster ,  and query max memory per node is 60GB , which I think is enough  for  the table  . Is that the only factor ? Is there any other reason.

**Comment by daikon12** [comment]
> `order by` requires storing all data in cluster memory for sorting purposes. It could be that query max memory per node is too low.

@sopel39 
Yes ， you are right, order by requires storing all data in cluster memory. but there are 12 nodes in my presto cluster , and query max memory per node is 60GB , which I think is enough for the table . Is that the only factor ? Is there any other reason.

**Comment by daikon12** [comment]
> Did you check the `softMemoryLimit` value in your resource groups config (assuming you are using resource groups)?

@nezihyigitbasi 
Yes ,  I make a configuration in the way of resource groups .   I'm confused that just  Very few resources are needed when I query " show schema " . Excuse me, Do you agree ? But the query " show schema " will be queued until "order by"   is finished , that is strange.

**Comment by rongrong** [comment]
The `/v1/resourceGroupState` might give you more information about why the queries are queued.

**Comment by daikon12** [comment]
> The `/v1/resourceGroupState` might give you more information about why the queries are queued.
@rongrong 
Hi , I  have read the class ResourceGroupStateInfoResource  on your suggestion. But I am still not clear , It just  gets the info of  resourcegroup 。 the query " show schema " will be queued until "order by" is finished  ， then It turn into running and finished quickly。

Excuse me,  Could you be more specific about your opinion ,Thank you

**Comment by rongrong** [comment]
Presumably the `SHOW SCHEMAS` query is queued because it's in the same resource group as the  `SELECT` query. If without `ORDER BY` the query would run but with it it's queued, it's likely that the resource group has exceeded it's soft memory limit as @nezihyigitbasi mentioned. The ResourceGroupInfo would give you details about the resource group to confirm this assumption. For more information regarding to how to configure / tune resource groups, you can read this: https://prestodb.io/docs/current/admin/resource-groups.html
