### ISSUE TITLE
Redis Connector: support specify key prefix for each table

### ISSUE THREAD

**Issue by xumingming** [prestodb/presto#12144]
Currently, Redis connector support the following two configs to indirectly specify the table key prefix:

* redis.key-prefix-schema-table
* redis.key-delimiter

But it constains the prefix to be the format of `schema-name:table-name`,  there are cases where the prefix is predefined, then we want to analyze the data in it, then we may not have the structure of `schema-name:table-name` in the key, supporting specify the prefix will be convenient. And the existing prefix mechanism will be a special case of the new mechanism.

**Comment by mbasmanova** [comment]
CC: @avasilevskiy 

@xumingming James, I don't understand this use case. What do you mean by "the prefix is predefined" and "we may not have the structure of schema-name:table-name in the key"? Could you clarify?
