### ISSUE TITLE
Clarify documentation for redis.key-prefix-schema-table config

### ISSUE THREAD

**Issue by xumingming** [prestodb/presto#12142]
The following doc is not so accurate:

```
redis.key-prefix-schema-table

If true, only keys prefixed with the schema-name:table-name are be scanned for a table, and all other keys will be filtered out. If false, all keys are scanned.

This property is optional; the default is false.
```

the actual key prefix will be scanned is not `schema-name:table-name` , instead the prefix required is: `schema-name:table-name:` , and if the schema-name is default schema, the prefix is: `table-name:` .

**Comment by linuxfshacker** [comment]
Fixed by PR #13899
