### ISSUE TITLE
Presto worke node crashed due to some unknown reason

### ISSUE THREAD

**Issue by hustnn** [prestodb/presto#12159]
After crash, I check the server log, can only found some unexpected character shown below. Anybody know the reason?

"^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@"

**Comment by nezihyigitbasi** [comment]
This itself isn't helpful. Can you share the stderr/stdout of the Presto process (you can upload them as gists)?

**Comment by hustnn** [comment]
@nezihyigitbasi .

I found some JVM error information shown below. It seems related to code gen. Is this useful?

---------------  T H R E A D  ---------------

Current thread (0x00007ebfe47f6000):  JavaThread "C2 CompilerThread4" daemon [_thread_in_vm, id=90880, stack(0x00007ebfe31fb000,0x00007ebfe32fb000)]

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x00007ebfe04e6028

Registers:
RAX=0x00000000ffffffff, RBX=0x00007ebfe04e6028, RCX=0x0000000000000001, RDX=0x00007f1d8c0a0340
RSP=0x00007ebfe32f6730, RBP=0x00007ebfe32f6770, RSI=0x00007ebfe568a390, RDI=0x00007ebfe04e6028
R8 =0x0000000000000000, R9 =0x0000000000000000, R10=0x00007ebf53718868, R11=0x00007ebfb4dedbca
R12=0x00007ebfe04e6028, R13=0x00007f1d8c0a0340, R14=0x00007f1d8c0a0340, R15=0x00007ebfe47f6000
RIP=0x00007f1d90dcb7ac, EFLAGS=0x0000000000010206, CSGSFS=0x0000000000000033, ERR=0x0000000000000004
  TRAPNO=0x000000000000000e

Top of Stack: (sp=0x00007ebfe32f6730)
0x00007ebfe32f6730:   00007ebfe32f6800 709e8b901f5aea00
0x00007ebfe32f6740:   00007ebfe32f6790 00007ebfe04eb8e0
0x00007ebfe32f6750:   00007ebfe04e6028 00007f1d8c0a0340
0x00007ebfe32f6760:   00007ebfe568a390 00007ebfe47f6000
0x00007ebfe32f6770:   00007ebfe32f67a0 00007f1d90dcbcc9
0x00007ebfe32f6780:   00007ebfe04eb8e0 00007ebfe04eb8e0
0x00007ebfe32f6790:   00007ebfe32f6b60 00007f1d8c0a0340
0x00007ebfe32f67a0:   00007ebfe32f6830 00007f1d90f2d310
0x00007ebfe32f67b0:   00007ebc3b9c10c0 00007ebfe568a390
0x00007ebfe32f67c0:   00000001e32f6890 00007ebc00000000
0x00007ebfe32f67d0:   00007ebfe5302f80 00007ebc3b9c10c0
0x00007ebfe32f67e0:   00007f1d912e8d4f 00007f1d8c0a0340
0x00007ebfe32f67f0:   00007ebfe47f6480 709e8b901f5aea00
0x00007ebfe32f6800:   00007ebfb458c110 00007ebfe47f6000
0x00007ebfe32f6810:   00007ebfe04eb8e0 00007f1d8c0a0340
0x00007ebfe32f6820:   00007ebfe568a390 00007ebfe32f6b60
0x00007ebfe32f6830:   00007ebfe32f69a0 00007f1d90f2d799
0x00007ebfe32f6840:   00007ebfe47f6000 00007ebfb4dee350
0x00007ebfe32f6850:   00007ebfe54c6620 0000000000000000
0x00007ebfe32f6860:   00007ebf537197c8 00007ebf00000001
0x00007ebfe32f6870:   00007ebfe04eb8e0 00000000000000ef
0x00007ebfe32f6880:   00007ebfe32f68d0 00007f1d90bb9ef6
0x00007ebfe32f6890:   00007ebfe32f68e0 00007ebfe32f6b60
0x00007ebfe32f68a0:   00007ebfe47f6900 00007ebfe04eb8e0
0x00007ebfe32f68b0:   00007ebfe32f9b08 00007ebfb4dee350
0x00007ebfe32f68c0:   00007ebfe47f6000 00000000000000ef
0x00007ebfe32f68d0:   00007ebfe32f6940 00007f1d90bd12ed
0x00007ebfe32f68e0:   00007ebfe32f6930 00007f1d911ca8cc
0x00007ebfe32f68f0:   00007ebfe47f6000 717a23b300000003
0x00007ebfe32f6900:   00007ebfe32f6980 709e8b901f5aea00
0x00007ebfe32f6910:   00007ebfe47f6000 000000000000004a
0x00007ebfe32f6920:   000000000000004a 00007ebfe04eb8e0

Instructions: (pc=0x00007f1d90dcb7ac)
0x00007f1d90dcb78c:   01 c3 66 90 55 b8 ff ff ff ff 48 89 e5 41 57 41
0x00007f1d90dcb79c:   56 49 89 d6 41 55 41 54 53 48 89 fb 48 83 ec 18
0x00007f1d90dcb7ac:   44 8b 27 83 f9 01 41 0f 94 c2 41 83 f8 01 41 0f
0x00007f1d90dcb7bc:   94 c3 41 83 f9 01 44 89 e2 41 0f 94 c7 01 c2 78

Register to memory mapping:

RAX=0x00000000ffffffff is an unknown value
RBX=
[error occurred during error reporting (printing register info), id 0xb]

Stack: [0x00007ebfe31fb000,0x00007ebfe32fb000],  sp=0x00007ebfe32f6730,  free space=1005k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0x63e7ac]
V  [libjvm.so+0x63ecc9]
V  [libjvm.so+0x7a0310]
V  [libjvm.so+0x7a0799]
V  [libjvm.so+0x7a0a85]
V  [libjvm.so+0x7a0d3a]
V  [libjvm.so+0x4261e8]
V  [libjvm.so+0x426493]
V  [libjvm.so+0x426bb3]
V  [libjvm.so+0x44baec]
V  [libjvm.so+0x450d0d]
V  [libjvm.so+0x451f1a]
V  [libjvm.so+0x455450]
V  [libjvm.so+0x456731]
V  [libjvm.so+0x456dee]
V  [libjvm.so+0x456f61]
V  [libjvm.so+0x43478c]
V  [libjvm.so+0x35b02b]
V  [libjvm.so+0x56bd6e]
V  [libjvm.so+0x407be2]
V  [libjvm.so+0x4082d5]
V  [libjvm.so+0x56b6be]
V  [libjvm.so+0x56c289]
V  [libjvm.so+0x8fc101]
V  [libjvm.so+0x8ed184]
V  [libjvm.so+0x8ed5f4]
V  [libjvm.so+0x8ef6e2]
V  [libjvm.so+0x404ab0]
V  [libjvm.so+0x56c309]
V  [libjvm.so+0x8fc101]
V  [libjvm.so+0x8ed184]
V  [libjvm.so+0x8ed5f4]
V  [libjvm.so+0x8ef6e2]
V  [libjvm.so+0x404ab0]
V  [libjvm.so+0x56c309]
V  [libjvm.so+0x8fc101]
V  [libjvm.so+0x8ed184]
V  [libjvm.so+0x8ed5f4]
V  [libjvm.so+0x8ef6e2]
V  [libjvm.so+0x404ab0]
V  [libjvm.so+0x4ac74a]
V  [libjvm.so+0x403fb8]
V  [libjvm.so+0x4b55f6]
V  [libjvm.so+0x4b655a]
V  [libjvm.so+0xa788a2]
V  [libjvm.so+0x8beb82]
C  [libpthread.so.0+0x7e25]  start_thread+0xc5

Current CompileTask:
C2:-1735494545 4271184       4       com.facebook.presto.$gen.BigintBigintDoubleApproxPercentileGroupedAccumulator_20190103_023103_968899::addInput (191 bytes)

**Comment by dain** [comment]
> Current thread (0x00007ebfe47f6000): JavaThread "C2 CompilerThread4" daemon

This is a JVM internal error during JIT compilation.  I suggest trying a different JVM version.

**Comment by nezihyigitbasi** [comment]
This is part of the error emitted by the JVM on crashes (in this particular case it's a `SIGSEGV`). This may be a JVM bug and as @dain suggests trying a newer JVM version may help. If you share the entire error log (or even better the entire hs_err_pid file) maybe we can tell whether we have seen this crash before and give more info.

**Comment by hustnn** [comment]
@nezihyigitbasi @dain 

The complete hs_err_pid file is here. (https://gist.github.com/hustnn/5869539f20df2512e534ae45fabc1f5c)

The jdk version we are using is not quite old in my mind.

**Comment by nezihyigitbasi** [comment]
I haven't seen this before. You can try a later JVM version to see whether it helps. If you can reproduce it you can also report it to the relevant JVM mailing lists.

**Comment by hustnn** [comment]
@nezihyigitbasi I see. Thanks.

**Comment by hustnn** [comment]
Close first. Suspect it is jvm issue.
