### ISSUE TITLE
TestHiveFileSystemS3 is flaky when run for different code versions

### ISSUE THREAD

**Issue by findepi** [prestodb/presto#12153]
Test data setup for `TestHiveFileSystemS3` uses predefined bucket location (`<test-bucket>/presto_test_external_fs`). It is correctly only when it is idempotent, as concurrent test runs will try to update the same location.

https://github.com/prestodb/presto/blob/a443bb7a1db30997431ea7f082ce3fa330cdfa50/presto-hive-hadoop2/bin/run_hive_s3_tests.sh#L19-L21

However, the setup recently changed to 

https://github.com/prestodb/presto/blob/43bd519052ba4c56ff1f4fc807075637ab5f4f10/presto-hive-hadoop2/bin/run_hive_s3_tests.sh#L19-L24

Now the tests running in different code branches will create different data set. This is no longer safe, leading to flaky tests.

**Comment by findepi** [comment]
@sameer2086 can you please take a look into that? I suggest that we use a different location in `run_hive_s3_tests.sh` now. Something like `<test-bucket>/v2/presto_test_external_fs`.

**Comment by sameer2086** [comment]
Thanks for reporting the issue @findepi. The approach sounds good to me. 

The current prefix naming scheme will create the new table at an additional level of depth. From S3 key point of view, this would be ok. However, in AWS console, the user would see the two presto_test_external_fs logical directories:
```
test-bucket -> presto_test_external_fs
test-bucket -> v2 -> presto_test_external_fs
```
How about we create a new table-name for s3 select pushdown with `<test-bucket>/presto_test_external_fs_s3_select_pushdown`?
```
test-bucket -> presto_test_external_fs
test-bucket -> presto_test_external_fs_s3_select_pushdown
```

**Comment by sameer2086** [comment]
@findepi, requesting review of https://github.com/prestodb/presto/pull/12157.

**Comment by findepi** [comment]
The problem will be fixed internally, as per https://github.com/prestodb/presto/pull/12157#issuecomment-451421348.
