### ISSUE TITLE
Push down SemiJoin+Filter through Join

### ISSUE THREAD

**Issue by findepi** [prestodb/presto#12154]
Semi Join:
```
SELECT custkey, totalprice FROM orders o JOIN customer c USING (custkey)
WHERE orderkey IN (SELECT orderkey FROM lineitem WHERE partkey = 638);
```
uses the plan:
```
- SemiJoin+Filter
  - InnerJoin
    - orders
    - customer
- Filter[partkey = 638]
   - lineitem
```

whereas it the following would be better:
```
- InnerJoin
  - customer
  - SemiJoin+Filter
     - orders
     - Filter[partkey = 638]
       - lineitem
```

Currently, CBO can correctly estimate the number of rows retained by SemiJoin+Filter. If the SemiJoin+Filter was pushed down below the join, `ReorderJoins` would be able to reorder the joined table, putting the filtered `orders` as the build side.

**Comment by kokosing** [comment]
Isn't this a cost-based decision? The suggested plan can be worse if the inner join is row filtering.

**Comment by sopel39** [comment]
`SemiJoin+Filter` can be treated as a "filtering" operator, which we always pushdown.
`SemiJoin+Filter` can break existing partitioning though (e.g: for bucketed execution) so in order to be on safe side we could push it down only when it's broadcasted
