### ISSUE TITLE
Add stats to tpch, tpcds for other scale factors

### ISSUE THREAD

**Issue by findepi** [prestodb/presto#12163]
tpch (and sometimes tpcds) are used to try out CBO.
however, both provide stats for some scale factors only (currently: sf0.01, sf1, sf3000 in both cases).

- [ ] provide stats for more scale factors that are likely to be used, eg sf10, sf100
- [ ] produce a user-visible warning (ie via `WarningCollector`) when a schema without stats is used

**Comment by kokosing** [comment]
>  provide stats for more scale factors that are likely to be used, eg sf10, sf100

We used to have statistics that were scaled from sf1, but that was introducing an error. Would you like to restore that or extend what we have now to other scale factors?

**Comment by findepi** [comment]
> statistics that were scaled from sf1, but that was introducing an error.

that could be counter-productive.
