### ISSUE TITLE
date_format returns incorrect week for the last day of 2018

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#12167]
Monday 12/31/2018 is the 53rd week of 2018, but parsing a unixtime from that day asking for the week number using %v gives 01:

```
> SELECT FROM_UNIXTIME(1546285458), DATE_FORMAT(FROM_UNIXTIME(1546285458), '%v')

2018-12-31 11:44:18.000 | 01
```

CC: @haozhun

**Comment by rschlussel** [comment]
I don't know what the expectation is from the sql perspective, but this is the defined behavior for joda: http://joda-time.sourceforge.net/field.html#weekyear

**Comment by findepi** [comment]
This is (surprisingly) the expected behavior.
