### ISSUE TITLE
Add option to limit writers per query

### ISSUE THREAD

**Issue by zaynoon** [prestodb/presto#12169]
At the moment the max numbers of writers that a query can use is determined by the number of servers in the cluster. This creates incidents where a query authored on one cluster will unexpectedly fail on a smaller cluster due to the lower number of workers. 

Having an option to impose a limit on how many writers might be utilized will allow consistency across clusters with different sizes and provide consistent experience for our users.

**Comment by mbasmanova** [comment]
@zaynoon Ahmed, could you answer Rongrong's questions?

**Comment by mbasmanova** [comment]
@rongrong Rongrong, this issue just came up again. A user saw that their query was failing with `Exceeded limit of 100 open writers for partitions/buckets`, but then succeeded. When a query writes to a bucketed table, Presto creates one writer per bucket. If a query produces 5 dynamic partitions each with 8,192 buckets, Presto needs 40,960 writers. With 100 writers per node limit, this requires 410 heathy workers in the cluster. Hence, the query would succeed on a large cluster, but fail on a smaller one.
