### ISSUE TITLE
Discussion : Push down Regular expression to Connector 

### ISSUE THREAD

**Issue by Praveen2112** [prestodb/presto#12178]
Presto pushes the filter predicate to the connector using `TupleDomain` and currently `TupleDomain` captures the filter predicate in a `ValueSet` and currently it supports for >,>=,<,<=,=,!= operatiors. For new connectors like elastic-search or even for existing presto-base-jdbc connector it would be better if we could capture the like predicate i.e the regular expression and enforce it at the connector layer itself instead of performing at the query engine layer.

For adding support the above proposal we might have a custom implementation of  `ValueSet` for  the regular expression and pass it via `TupleDomain` to the connector. But the problem is when we try to create a TupleDomain for a filter predicate like this `columnA = '123' and columnA like '1%'` we might not be sure on which Domain to maintain. 

Is there is any other way by which we could capture the regular expression and push it down to the connector ? Would there be any serious issue if we try to implement the same ?

**Comment by kokosing** [comment]
As already you noticed with `columnA = '123' and columnA like '1%' ` example, regular expressions do not fit well `ValueSet`. I think it would be better (still not perfect) to extend the `Domain` to contain new field - a list of regular expressions.

There couple problems with that:
 - all the places that touch `Domain` would need to be updated, to not skip such predicate.
 - all methods like `intersects`, `contains` etc. would not be supported in case when `Domain` would contain regular expressions. That makes me think that regular expressions does not fit `TupleDomain` at all and would require new entity.

Side note: `columnA like '1%'` is equivalent to `columnA > '1'`

**Comment by electrum** [comment]
I think @martint has a short term plan to add expanded pushdown for connectors.

**Comment by sopel39** [comment]
> I think @martint has a short term plan to add expanded pushdown for connectors.

What is expanded pushdown @martint ?
