### ISSUE TITLE
Travis CI failure due to auth to dockerhub

### ISSUE THREAD

**Issue by cbanek** [prestodb/presto#12175]
Pulling docker image [prestodb/centos6-oj8:10]
Pulling docker image [prestodb/hdp2.6-hive:10]
Error response from daemon: unauthorized: authentication required
The command "if [[ -v PRODUCT_TESTS_BASIC_ENVIRONMENT ]]; then

I've hit this problem twice when running the Travis CI job on my PR.

Link to Travis Job: https://travis-ci.org/prestodb/presto/builds/474668982

The PRODUCT_TESTS_BASIC_ENVIRONMENT=true job fails due to the above error about pulling a docker image from what looks like dockerhub.   This just started happening yesterday for me, and worked fine before then.  Has something changed on the permissions of the docker images?

Looks like this is happening during a docker compose:

Larger relevant snippet from job:
`
docker-compose version 1.17.1, build 6d101fb
docker-py version: 2.5.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:38 2017
 OS/Arch:      linux/amd64
Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:41:20 2017
 OS/Arch:      linux/amd64
 Experimental: false
Docker compose containers stopped: [multinode]
Docker compose containers stopped: [multinode-tls]
Docker compose containers stopped: [multinode-tls-kerberos]
Docker compose containers stopped: [singlenode]
Docker compose containers stopped: [singlenode-cassandra]
Docker compose containers stopped: [singlenode-hdfs-impersonation]
Docker compose containers stopped: [singlenode-kafka]
Docker compose containers stopped: [singlenode-kerberos-hdfs-impersonation]
Docker compose containers stopped: [singlenode-kerberos-hdfs-impersonation-cross-realm]
Docker compose containers stopped: [singlenode-kerberos-hdfs-impersonation-with-wire-encryption]
Docker compose containers stopped: [singlenode-kerberos-hdfs-no-impersonation]
Docker compose containers stopped: [singlenode-ldap]
Docker compose containers stopped: [singlenode-mysql]
Docker compose containers stopped: [singlenode-postgresql]
Docker compose containers stopped: [singlenode-sqlserver]
Pulling docker image [prestodb/centos6-oj8:10]
Pulling docker image [prestodb/hdp2.6-hive:10]
Error response from daemon: unauthorized: authentication required
The command "if [[ -v PRODUCT_TESTS_BASIC_ENVIRONMENT ]]; then
  presto-product-tests/bin/run_on_docker.sh \
    multinode -x quarantine,big_query,storage_formats,profile_specific_tests,tpcds,cassandra,mysql_connector,postgresql_connector,mysql,kafka,avro
fi
" exited with 1.
`

**Comment by cbanek** [comment]
Looks like this didn't repro just now for my latest build - I'll close this one tomorrow if I don't see it coming up again.  Anyone else see this?

**Comment by ryanrupp** [comment]
This was due to a Docker Hub outage, see [here](https://status.docker.com/pages/533c6539221ae15e3f000031)

**Comment by cbanek** [comment]
Sweet thanks @ryanrupp I'll close it.
