### ISSUE TITLE
HashTable for base MapBlock is not updated when referencing the hashtable on the sliced MapBlock

### ISSUE THREAD

**Issue by yingsu00** [prestodb/presto#12187]
PR #11791 (commit 23de11f7d3), which lazily builds the hashtables for maps, introduced a regression for the case where the MapBlock is created through `AbstractMapBlock.getRegion()`. The hashtables built on the MapBlock region were not updated in the original MapBlock, thus causing repeated hashtables build on the same base MapBlock.

**Comment by mbasmanova** [comment]
@yingsu00 Could you give an example of a query that would be affected? Does the query fail or return incorrect results?

**Comment by yingsu00** [comment]
This regression happens on dereferencing an array of maps, for example:
select 
    array_of_maps[1]['key1'],
FROM t

where array_of_maps is of type ARRAY<MAP<STRING,DOUBLE>>

It is performance regression that could block users' pipeline if the the data amount is large.

**Comment by yingsu00** [comment]
Fixed with https://github.com/prestodb/presto/pull/12198
