### ISSUE TITLE
Joni regex matcher hang when we use some pattern and string.

### ISSUE THREAD

**Issue by kaka11chen** [prestodb/presto#12191]
When we used presto to do regex match, we found some case will hang.
I write some simple codes to test this case:
```
import org.jcodings.specific.UTF8Encoding;
import org.joni.Matcher;
import org.joni.Option;
import org.joni.Regex;

public class Demo {
    public static void main(String[] args) {
        byte[] str = "m1666666654656dsffddfssubscribeaaaaa_3499_g415780803".getBytes();
        byte[] pattern = "^([a-z0-9]+)+$".getBytes();

        Regex regex = new Regex(pattern, 0, pattern.length, Option.NONE, UTF8Encoding.INSTANCE);
        Matcher matcher = regex.matcher(str);
        int result = matcher.search(0, str.length, Option.DEFAULT);
        System.out.println("result: " + result);
    }
}
```
However, re2j regex lib is OK.
I have created a issue on the Joni lib: https://github.com/jruby/joni/issues/39

**Comment by kaka11chen** [comment]
I think it is an exponential backtracking case.

**Comment by kaka11chen** [comment]
So a method to avoid user input this type's regex is set query.max_run_time to some value?  I read the source code quickly, JONI regex lib should can be interrupted when presto which use thread mode. Is it correct?

**Comment by mbasmanova** [comment]
@kaka11chen Qi, as a workaround, you can configure Presto to use RE2J via `regex-library` configuration property.

https://prestodb.io/docs/current/admin/properties.html

**Comment by kaka11chen** [comment]
@mbasmanova Thanks.
