### ISSUE TITLE
Can`t return data when using specified column with mysql

### ISSUE THREAD

**Issue by devilcony** [prestodb/presto#12207]
**Env:**
presto 0.215/0.163
mysql 5.7.24
**Table structure:**
d_config_activity
![image](https://user-images.githubusercontent.com/3895260/50958002-9d99e980-14fa-11e9-848f-b96cce7393f0.png)
d_config_activity_goods
![image](https://user-images.githubusercontent.com/3895260/50958026-b0acb980-14fa-11e9-90dd-5a37de37f273.png)

**Descriptions:**
Get inconsistent reaults when using different columns or different version of presto.
1. Query column activity_id,return correct resault
select b.activity_id from mysql_daam.daam.d_config_activity a inner join mysql_daam.daam.d_config_activity_goods b on a.id=b.activity_id;
![image](https://user-images.githubusercontent.com/3895260/50958887-b1dee600-14fc-11e9-9eb9-28a8b0af1a46.png)

2. Query column goods_code,return 0 rows,wrong
select b.goods_code from mysql_daam.daam.d_config_activity a inner join mysql_daam.daam.d_config_activity_goods b on a.id=b.activity_id;
![image](https://user-images.githubusercontent.com/3895260/50958797-7b08d000-14fc-11e9-828f-de3489a8bb13.png)

3. Query with presto_0.168,return correct resault
select b.goods_code from mysql_daam.daam.d_config_activity a inner join mysql_daam.daam.d_config_activity_goods b on a.id=b.activity_id;
![image](https://user-images.githubusercontent.com/3895260/50958622-1e0d1a00-14fc-11e9-867d-f920a959faef.png)

The catalog configs are same in the two version of presto.

**Comment by ebyhr** [comment]
I couldn't reproduce this issue... Could you share the ddl of d_config_activity and d_config_activity_goods on mysql (not presto)?

**Comment by devilcony** [comment]
The ddl in mysql:
CREATE TABLE `d_config_activity` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `activity_name` varchar(255) DEFAULT NULL ,
  `start_date` date DEFAULT NULL ,
  `end_date` date DEFAULT NULL ,
  `url` varchar(255) DEFAULT NULL ,
  `bu_id` int(11) DEFAULT NULL ,
  `type_id` int(11) DEFAULT NULL ,
  `add_user` varchar(255) DEFAULT NULL ,
  `create_time` datetime DEFAULT NULL ,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `d_config_activity_goods` (
  `id` int(11) NOT NULL AUTO_INCREMENT ,
  `goods_name` varchar(255) DEFAULT NULL ,
  `goods_code` varchar(255) DEFAULT NULL ,
  `material_business_cd` varchar(255) DEFAULT NULL ,
  `activity_id` int(11) DEFAULT NULL ,
  `add_user` varchar(255) DEFAULT NULL ,
  `create_time` datetime DEFAULT NULL ,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by ebyhr** [comment]
Hmm... it works with mysql 5.7.25. Is there no error or warning message on presto server log?

**Comment by devilcony** [comment]
No warning or error messges...
Here is the stage info(select b.goods_code),seems records have been filtered, output 0 row:
![image](https://user-images.githubusercontent.com/3895260/51591090-00da4180-1f27-11e9-9767-2f1113add64c.png)

This is the ok stage info(select b.goods_name/b.activity_id):
![image](https://user-images.githubusercontent.com/3895260/51591057-eacc8100-1f26-11e9-856b-c2b8cc077d69.png)

**Comment by devilcony** [comment]
I tried some other sqls,the results are very weired...

1、select goods_code from mysql_daam.daam.d_config_activity_goods
182 rows
2、select activity_id from mysql_daam.daam.d_config_activity_goods
182 rows
3、select goods_code,activity_id from mysql_daam.daam.d_config_activity_goods
0 rows
4、select goods_code,activity_id,goods_name from mysql_daam.daam.d_config_activity_goods
182 rows
5、select activity_id,id from mysql_daam.daam.d_config_activity_goods
182 rows
6、select goods_code,id from mysql_daam.daam.d_config_activity_goods
182 rows
7、select goods_name,activity_id from mysql_daam.daam.d_config_activity_goods
182 rows

**Comment by devilcony** [comment]
The type of column goods_code is varchar(255),but values are integer like 12345.
I insert a row with goods_code='1003776abc',then return the right rows:
![image](https://user-images.githubusercontent.com/3895260/51593000-08e8b000-1f2c-11e9-9aaa-6e2ec9e3bd20.png)

Seems like a type issue in ScanFilterAndProjectOperator
I tried to debug but cant debug into line 242:
`CursorProcessorOutput output = cursorProcessor.process(operatorContext.getSession().toConnectorSession(), yieldSignal, cursor, pageBuilder);`
