### ISSUE TITLE
Implement missing stats rules and cost calculators

### ISSUE THREAD

**Issue by arhimondr** [prestodb/presto#12202]
Currenty the stats model does not have rules for every PlanNode possible. 

For example, we can come up with simple rules that can handle (or at least partially handle) `WindowNode`, `TopNRowNumberNode`, `SampleNode`, `SortNode`, and `IntersectNode`.

Ideally it would be nice to have a test, that verifies that every plan node has an associated rule and cost calculator. If there's a node that cannot be easily estimated (`IndexJoinNode`, `IndexSourceNode`, `UnnestNode`)  - an explicit stubs that return `unknown` can be added. If some of the nodes are implicitly assumed to not be in the plan at the moment when the cost model is invoked (`MarkDistinctNode`, `DistinctLimitNode`, `GroupIdNode`, `ApplyNode`, `LateralJoinNode`) - an explicit stub that throws an exception can be added. This should protect us from unwanted CBO efficiency regressions in case something is changed in the plan (new type of a node added, order of rules changed, etc.)

CC: @findepi , @sopel39 , @rschlussel , @picrinite , @mbasmanova

**Comment by ssaumitra** [comment]
Is anyone still working on this issue? If not, I would like to start on the remaining parts after Vic's commit.
CC: @picrinite
