### ISSUE TITLE
Join Reorder in Spatial Join

### ISSUE THREAD

**Issue by qqibrow** [prestodb/presto#12215]
Problem:
In broadcast mode, the spatial join optimizer doesn't reorder join order for performance. 

e.g, 
```
select area_name, count(*) 
from sfmap join trips on st_contains(sfmap.geofence, trips.dropoff_point)
group by 1 order by 2 DESC
``` 
spatial join will put the larger table trips on the build side. 

This might be able to optimize based on parameters of st_contains function. e.g, 
st_contains(A, B) does it imply the dimension of A is less than dimension of B?  I cannot speak for all, but it is true for 90% of our user cases. 

@mbasmanova what do you think?

**Comment by findepi** [comment]
What about making it cost- (or at least stats-) -based decision?

**Comment by mbasmanova** [comment]
@qqibrow It would be useful to enhance the optimizer to swap spatial join sides automatically.

> st_contains(A, B) does it imply the dimension of A is less than dimension of B?

`st_contains(A, B)` does not imply that `dim(A) < dim(B)`. While point-in-polygon might be the most common use case, polygon-in-polygon joins are still possible. For point-in-polygon, `dim(A) = 2` (polygons are 2-dimensional) and `dim(B) = 1` (points are 1-dimensional) and `dim(B) < dim(A)`. For polygon-in-polygon join, `dim(A) = dim(B) = 2`.  All reasonable `st_contains(A, B)` joins should have `dim(B) <= dim(A)`.

For efficiency, you'd want to use the smaller dataset as the build side, e.g. you need to consider cardinality and sizes of the join sides (not necessarily dimensions). 

Would you like to work on this?

**Comment by qqibrow** [comment]
@findepi @mbasmanova thanks for replying!

@mbasmanova I notice there is a SpatialJoinCostEstimator, how it is working at this time? Isn't the join reorder its functionality? 

In our case, some table stats are not accurate because we use a customized table input format. I am trying to work out a solution for both internal and open source.

**Comment by mbasmanova** [comment]
@qqibrow I'm busy with the release, hence, delay in responses. I'll look into this once the release is complete.

**Comment by mbasmanova** [comment]
@qqibrow 

> I notice there is a SpatialJoinCostEstimator, how it is working at this time? Isn't the join reorder its functionality?

I don't see `SpatialJoinCostEstimator`. Flipping of join sides is implemented in `DetermineJoinDistributionType`. The logic is to estimate the cost of two join versions, original and with flipped sides, and choose the one with least cost.
