### ISSUE TITLE
Enhance Verifier to identify which column has checksum mismatch

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#12211]
Running the Verifier with the new configuration property `run-teardown-on-result-mismatch=false` made it a lot easier to investigate result-mismatch failures. Thank you, @shixuan-fan . Still, the process is quite time consuming and labor intensive, particularly, for result-mismatch failures. At a lot of clicks and time is spent in figuring out which columns have a mismatch and whether there is row count mismatch present as well. Small enhancements to the Verifier can help automate this process.

(1) Update checksum queries to include count(*) - this will allow for comparing row counts
(2) Update checksum queries to include column aliases, e.g. x_checksum, y_checksum. 
(3) Update error message to include column names which have different values. Together with (1) and (2) this will allow for us to quickly see which columns have a mismatch and whether row count match or not.

Here is an example of a checksum query used today:

```
SELECT
  "checksum"(user_id)
, "checksum"(region_prediction)
, "checksum"(country_from_ip)
, "checksum"(region_from_ip)
, "checksum"(age)
, "checksum"(gender)
, "checksum"(data)
, "checksum"(country_prediction)
, "checksum"(ds)
FROM
  local_atn3oxygen.tmp_verifier_b9af7e6a04744e459d05df573358c0a1
```  

Here is how it needs to change.

```
SELECT
count(1) as row_count,
  "checksum"(user_id) as user_id_checksum,
, "checksum"(region_prediction) as region_prediction_checksum,
, "checksum"(country_from_ip) as country_from_ip_checksum,
, "checksum"(region_from_ip) as region_from_ip_checksum,
, "checksum"(age) as age_checksum,
, "checksum"(gender) as gender_checksum,
, "checksum"(data) as data_checksum,
, "checksum"(country_prediction) as country_prediction_checksum,
, "checksum"(ds) as ds_checksum
FROM
  local_atn3oxygen.tmp_verifier_b9af7e6a04744e459d05df573358c0a1
```  

CC: @zaynoon @caithagoras @rongrong

**Comment by caithagoras** [comment]
I'll put a plan for all the verifier issues and post in the Presto team group shortly.

**Comment by caithagoras** [comment]
Query 2 looks similar to what we're doing today in the validator (except for floating point and array handling). It makes sense to me.

**Comment by caithagoras** [comment]
Resolved
