### ISSUE TITLE
Optimization should be disabled for functions that return constant value but returned results are not serializable to magic literal

### ISSUE THREAD

**Issue by hellium01** [prestodb/presto#12213]
For example, if a function is added to return JsonPath object today, and if we use it ` function_create_constant_json_path()`,  it will cause following stacktrace:

```
  java.lang.IllegalArgumentException: object.getClass (class com.facebook.presto.operator.scalar.JsonPath) and type.getJavaType (class io.airlift.slice.Slice) do not agree
	at com.facebook.presto.sql.planner.LiteralEncoder.toExpression(LiteralEncoder.java:124)
	at com.facebook.presto.sql.planner.LiteralEncoder.toExpression(LiteralEncoder.java:210)
	at com.facebook.presto.sql.planner.iterative.rule.SimplifyExpressions.rewrite(SimplifyExpressions.java:56)
	at com.facebook.presto.sql.planner.iterative.rule.TestSimplifyExpressions.assertSimplifies(TestSimplifyExpressions.java:141)
```
We should disable the optimization here and leave the function as an expression. The RowExpression optimizer will pick up the function and optimize it later.

**Comment by martint** [comment]
Is there an example query where this is an issue?

**Comment by hellium01** [comment]
Currently there is no function returns such but some facebook internal function indeed need to return something like JsonPath. In the PR: https://github.com/prestodb/presto/pull/12214/files, there is an example where this will fail in current code.

**Comment by hellium01** [comment]
Currently, if we run `regex_extract(..., (CAST '$.x' AS JsonPath))`, it will work but if we have a `regex_extract(..., functionCreateJsonPath(...))`, it will fail due to the above problem.

**Comment by findepi** [comment]
To avoid discussing same topic in two places, let me close the issue and continue the discussion @ https://github.com/prestodb/presto/pull/12214
