### ISSUE TITLE
use ALLOW FILTERING in scylladb secondary indexes

### ISSUE THREAD

**Issue by rlcyf** [prestodb/presto#12227]
create index on user_plus_record (id);
    select id,name from user_plus_record  where id=22;

Query 20190115_155013_00062_fnvnv failed: Cannot execute this query as it might involve data filtering and thus may have unpredictable performance. If you want to execute this query despite the performance unpredictability, use ALLOW FILTERING

remove secondary indexes,exec statement is normal
    ``` drop index user_plus_record_id_idx;```
    ``` select id,name from user_plus_record  where id=22;```

**Comment by kokosing** [comment]
Do you access scylladb with Presto Cassandra connector?

**Comment by hugesswnn** [comment]
> Do you access scylladb with Presto Cassandra connector?

yes!

**Comment by ajitpratap0** [comment]
We are also facing the same issue, any fixes planned for the same?
