### ISSUE TITLE
Presto create temporaryPath is not correct

### ISSUE THREAD

**Issue by photogamerun** [prestodb/presto#12222]
in this code 

HiveWriteUtils
```
public static Path createTemporaryPath(HdfsContext context, HdfsEnvironment hdfsEnvironment, Path targetPath)
    {
        // use a per-user temporary directory to avoid permission problems
        String temporaryPrefix = "/tmp/presto-" + context.getIdentity().getUser();

        // use relative temporary directory on ViewFS
        if (isViewFileSystem(context, hdfsEnvironment, targetPath)) {
            temporaryPrefix = ".hive-staging";
        }

        // create a temporary directory on the same filesystem
        Path temporaryRoot = new Path(targetPath, temporaryPrefix);
        Path temporaryPath = new Path(temporaryRoot, randomUUID().toString());

        createDirectory(context, hdfsEnvironment, temporaryPath);

        return temporaryPath;
    }
```

from the commitment  // create a temporary directory on the same filesystem
we know targetPath is parent path and temporaryPrefix is children

so I write a test code 

![image](https://user-images.githubusercontent.com/16651123/51109375-0e5d4080-1830-11e9-8afd-e1557d1ef5be.png)

if temporaryPath is started with '/' it will ignore parent path

if not it's correct

**Comment by findepi** [comment]
You are right that when `temporaryPrefix` is an absolute path then the line
```
Path temporaryRoot = new Path(targetPath, temporaryPrefix);
```

will make `temporaryRoot` the same as `temporaryPrefix`.
This is intentional.
