### ISSUE TITLE
joda-to-java bridge causing excessive CachedDateTimeZone$Info objects

### ISSUE THREAD

**Issue by elonazoulay** [prestodb/presto#12235]
While testing we found that 8ac4b8466a7db96d9941e27cecf7aaf64c85bfaf causes 180gb heaps to fill up with 145-150gb of org.joda.time.tz.CachedDateTimeZone.

It looks like it's due to https://github.com/airlift/joda-to-java-time-bridge/commit/bebbce575864bb4bbc56be6f799cd8acae65c8d9: the JdkBasedZoneInfoProvider creates CachedDateTimeZone for all non fixed zones (in the static block).

@haozhun would you have more context about this?

**Comment by martint** [comment]
How many time zones are there? What's the GC root for those instances? Could it possibly be the DynamicClassloaders that get created for each compiled filter/project?

**Comment by findepi** [comment]
> causes 180gb heaps to fill up with 145-150gb of `org.joda.time.tz.CachedDateTimeZone`

@rschlussel on slack wrote `org/joda/time/tz/CachedDateTimeZone$Info` not `org/joda/time/tz/CachedDateTimeZone`. I updated the description.

**Comment by nezihyigitbasi** [comment]
Unfortunately, although we got a few heap dumps yourkit wasn't able to open them saying there were too many objects in those dumps. So, we are still trying to root cause the issue.

**Comment by dain** [comment]
I have thoroughly dug into theCachedDateTimeZone, and I see that there is a problem with garbage generation from cache thrashing. If you feed 10M random mills into CachedDateTimeZone.getInfo(instant), you will get a ton cache collisions in the 512 entry info cache array. Each time you get a collision, the code builds a new CacheInfo chain, so you generate a ton of garbage.
