### ISSUE TITLE
Support Parquet v2 format dictionary filtering (RLE_DICTIONARY)

### ISSUE THREAD

**Issue by ryanrupp** [prestodb/presto#12248]
When Parquet files are generated with the v2 format RLE_DICTIONARY is used (instead of PLAIN_DICTIONARY for v1). My understanding is some pages can be dictionary encoded but if there's too many unique values and the dictionary grows too large in size it will eventually fall back to plain encoding (see https://github.com/prestodb/presto/issues/4778). Previously, with the old version of the Parquet library there wasn't access to `EncodingStats` where it can be detected if this fallback behavior had to occur or not. Therefore, this change - https://github.com/prestodb/presto/pull/4779 - fixed the correctness to only work with `PLAIN_DICTIONARY` until the Parquet library could be updated and `EncodingStats` could be used. In https://github.com/prestodb/presto/pull/12247 parquet-mr is being upgraded to 1.10.0 which means the `EncodingStats` can be used once it's merged. Specifically, `EncodingStats.hasNonDictionaryEncodedPages` can be checked.

[Here's](https://github.com/apache/parquet-mr/blob/63b45f7244f0dcf1a05c94a30a7f860973e307d2/parquet-hadoop/src/main/java/org/apache/parquet/filter2/dictionarylevel/DictionaryFilter.java#L429) the equivalent filtering handling in parquet-mr which also has the fallback logic if `EncodingStats` isn't available (e.g. on a V1 file).

**Comment by ryanrupp** [comment]
Relevant Presto code [here](https://github.com/prestodb/presto/blob/0bfe80b2540727341c0a33207b3f5dc58ca30aa2/presto-parquet/src/main/java/com/facebook/presto/parquet/predicate/PredicateUtils.java#L164)

**Comment by zhenxiao** [comment]
thank you for working on it, @ryanrupp I will take a look at the PRs
CC @nezihyigitbasi @highker

**Comment by highker** [comment]
@ryanrupp the PR is in the wrong repo. Could you send out a PR on top of prestodb repo?

**Comment by zhenxiao** [comment]
Hi @ryanrupp I left some comments in:
https://github.com/prestosql/presto/pull/251

I think to make it working in prestodb repo, we need to upgrade Parquet first:
https://github.com/prestodb/presto/pull/12247

Ping me if you have any questions

**Comment by ryanrupp** [comment]
Fixed by dfcc669fe3d1b13b8777b561808c531826d29ca1
