### ISSUE TITLE
Optimization: valuesAtQuantiles qdigest functions

### ISSUE THREAD

**Issue by blrnw3** [prestodb/presto#12245]
I noticed that [these quantile functions on a qdigest](https://github.com/prestodb/presto/blob/2d044948b75d5c945f6e4c09573ba78e5c966ff0/presto-main/src/main/java/com/facebook/presto/operator/scalar/QuantileDigestFunctions.java#L68) compute the percentile values by looping over the provided percentiles array argument and calling the underlying [airlift qdigest method](https://github.com/airlift/airlift/blob/master/stats/src/main/java/io/airlift/stats/QuantileDigest.java#L412) `getQuantile` (singular).

However, the airlift qdigest object has a [plural version of this method](https://github.com/airlift/airlift/blob/master/stats/src/main/java/io/airlift/stats/QuantileDigest.java#L362) `getQuantiles` which seems to be more efficient because it only traverses the qdigest tree once for a given array of quantiles.

I haven't had a chance to quantify this optimisation yet, but wanted to gauge whether there'd be any opposition to a pull request on this topic?

Thanks

**Comment by mbasmanova** [comment]
CC: @mehrdad-honarkhah @tdcmeehan

**Comment by blrnw3** [comment]
Thanks for the detailed reply! I'll have a look at implementing it this week and see what kind of real-world speed-up it produces

**Comment by tdcmeehan** [comment]
I agree with @mehrdad-honarkhah, and we'll be happy to review a pull request for this optimization.

Please be aware, the plural version of the function [validates that the quantiles are sorted in ascending order](https://github.com/airlift/airlift/blob/master/stats/src/main/java/io/airlift/stats/QuantileDigest.java#L364).  To preserve compatibility with `approx_percentile` and existing users of `values_at_quantiles`, we don't want to introduce that validation to the `values_at_quantiles` function.  I think it would also be worthwhile to port this over to `approx_percentile`, as it does the same thing currently.

**Comment by blrnw3** [comment]
I did some perf testing on this and interestingly found no measurable difference in the two approaches. I tested on the TPCH data on several scale factors, evaluating 20 percentiles with the two approaches outlined in the issue summary. It seems the qdigest building is so dominant that extracting the percentiles has trivial cost, regardless of how it is done.
