### ISSUE TITLE
Release notes for 0.217

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#12257]
## Andrii Rosa
- [x]  01-30 12:04:01    373375db1e Improve error message for unsupported reduce_agg state type
## Elon Azoulay
- [x]  02-04 10:56:13    16b032f864 Add too many stages warning
## Grzegorz Kokosiński
- [x]   01-25 04:11:32    0052bd769d Make hive temporary staging directory location configurable
- [x]   01-25 04:11:32    527d84cfe2 Fix formatting
- [x]   01-25 04:11:32    7a59eccef5 Make use of hive temp staging directory configurable
- [x]   01-25 04:13:58    cc70970d7e Extend JdbcSplit with additional predicate field
- [x]   01-25 04:15:21    9976a0082a Add support for getTableStatistics to base-jdbc connector
- [x]   01-25 04:16:59    e0705cf5df Allow JDBC connector to define procedure
- [x]   01-25 04:18:38    6cdd76d06a Add suppressed exceptions to exception that is thrown
- [x]   02-01 01:55:02    b32d105439 Handle S3 empty directories as directories
## James Sun
- [x]  01-27 16:24:10    336b6713d4 Update Drift to 1.15
- [x]  01-28 10:56:43    50793b10d3 Minor exception message corrections
## Jiexi Lin
- [x]  02-01 12:54:53    258d0da341 ANALYZE statement: Parser
- [x]  02-01 12:54:53    26c75dc604 Move getPartitionLocation to MetastoreUtil
- [x]  02-01 12:54:53    8c14729ced ANALYZE statement: Analyzer, planner and execution
- [x]  02-01 12:54:53    8e83321ade Validate no partition value is null when making partition name
- [x]  02-01 12:54:53    a66a850d6c Fix partition column range statistics for empty partitions
- [x]  02-01 12:54:53    cca4e4a628 ANALYZE statement: Implement ANALYZE in Hive connector
- [x]  02-01 12:54:53    ddfc832922 Add error message on column count mismatch when making partition name
## Maria Basmanova
- [x]  01-28 08:39:02    66440a10d9 Add SphericalGeography type
## Mayank Garg
- [x]  01-31 13:34:29    29b83557b4 Add counter for POST requests to statement resource
## Nezih Yigitbasi
- [x]  01-25 16:00:23    6fbf1acc3f Simplify creation of succinct Duration instances
- [x]  01-25 16:00:39    18a93ff79b Report top memory consumers when local memory limit is exceeded
- [x]  01-30 08:46:14    1ccae67860 Add Elasticsearch connector
- [x]  02-01 18:52:26    8907ffdcfb Log details around OOM decisions in ClusterMemoryManager
- [x]  02-04 16:23:22    cdc01c0f24 Add peak task user memory usage to query stats
- [x]  02-05 16:51:30    b62e4bbbe1 Remove system pool entirely
## Raghav Sethi
- [x]  01-26 14:40:57    c2e0ec5885 Add spilled data to query stats, CLI, and Web UI
- [x]  02-04 15:54:29    1a51c839b0 Update node list on workers
- [x]  02-04 15:54:29    97db27216f Stop DiscoveryNodeManager in tests
- [x]  02-04 15:54:56    e32e311927 Only fire change events when node set actually changes
- [x]  02-04 15:55:19    3fd70aca2e Add test for DiscoveryNodeManager listener
- [x]  02-04 16:02:44    1630408e2b Change PlanPrinter to use a unified approach to constructing output
- [x]  02-04 16:02:44    24771e5b9b Move stat and estimate rendering to TextRenderer
- [x]  02-04 16:02:44    de2a775911 Change PlanNodeStats from a union class to hierarchy
- [x]  02-04 16:02:45    55a4f8683f Add JSON plan representation to enrich live plan view
- [x]  02-04 16:02:46    a71fecc303 Fix name conflict by renaming StageDetail
- [x]  02-04 16:02:46    be55fdcf35 Change live plan to fit within the container and add zoom
- [x]  02-04 16:02:46    c0be190423 Fix label positioning for pipelines in StageDetail
- [x]  02-04 16:02:46    fda9e1bb4f Simplify live plan by showing transferred data in edge labels
- [x]  02-04 16:02:47    009e8cfd60 Clean up rendering for live plan and embedded plan
- [x]  02-04 16:02:47    1dbe95624e Simplify stage skew histograms
- [x]  02-04 16:02:47    a08875957d Change aborted and canceled stage state color
- [x]  02-04 16:02:48    ed5582ebbd Change scroll behavior to zoom only when query is completed
- [x]  02-04 18:01:02    e8787d10c8 Fix starvation while waiting for minimum number of workers
## Rebecca Schlussel
- [x]  01-25 12:01:00    36260337fb Extract PlanNodeWithCost
- [x]  01-25 12:01:00    443b1835ae Use costs to choose semi-join distribution type
- [x]  01-25 12:01:00    6f9d1c72d6 Fix typo in DetermineJoinDistributionType
- [x]  01-25 12:01:00    7d4b32dc1f Extract computation of join cost without output
- [x]  01-25 12:01:00    cf29e3835a Change how JoinMatcher prints distribution type
- [x]  01-30 14:11:04    569a811fd1 Fix Elasticsearch connector pom
- [x]  01-31 11:55:33    834a4af2b2 Remove null check for boolean
- [x]  01-31 11:55:33    a683e76a82 Add option not to delete target directory on failure
- [x]  02-04 13:05:44    63d4f46215 Remove unused argument from selectUnionPartitioning()
- [x]  02-04 13:05:44    740a610df1 Minor refactor of AddExchanges.visitUnion()
- [x]  02-04 13:05:44    d37c740ee2 Don't consider SINGLE distribution for union partitioning
## Shixuan Fan
- [x]  01-25 12:10:15    2d77fd066d Support boolean type in EXPLAIN IO
- [x]  01-30 17:32:45    2eafd8681f Remove extra remote exchange in window function
- [x]  02-01 10:10:03    4004b0fde0 Support grouped execution for window function
## Wenlei Xie
- [x]  01-25 10:47:07    e3f2f53686 Refactor setting distribution for plan fragment
- [x]  01-26 15:05:22    1c71e31933 Support compiling RowExpression write to output block
- [x]  01-26 15:05:22    3e927f8880 Implement PROVIDED_BLOCKBUILDER return place convention
- [x]  01-26 15:05:22    7cec6d3f5d Add output block to RowExpressionCompiler.Context
- [x]  01-26 15:05:22    afc3b3e16c Introduce ReturnPlaceConvention for scalar function
- [x]  01-26 20:03:15    50e856c016 Add approx_distinct for boolean
- [x]  01-28 15:17:40    1e7691554e Decide dynamic lifespan schedule at plan time
- [x]  01-28 15:17:40    4a72784264 Rename StageExecutionStrategy to StageExecutionDescriptor
- [x]  01-28 15:17:40    bff1a790c6 Minor method rename in StageExecutionDescriptor
- [x]  01-30 20:46:04    e81d1d6394 Fix creating empty non-bucketed Hive partition
- [x]  01-31 15:06:31    63df5ce9bb Allow function implementation choices to have different dependencies
- [x]  02-04 18:28:25    eb011ec82f Fix sequence encodings in Checkpoints.getStreamCheckpoints
## rongrong
- [x]  01-28 12:28:46    2a3adb0503 Be explicit in constant handling when collecting partitionChannels
- [x]  01-28 12:28:46    801347e3c6 Propagate partition properties for full outer join

**Comment by wenleix** [comment]
General
---------------------
Add approx_distinct for boolean

**Comment by shixuan-fan** [comment]
#12238 
```
General
-------
* Support boolean type in EXPLAIN IO
```

**Comment by nezihyigitbasi** [comment]
```
General
--------
* Add :doc:`/connector/elasticsearch`.
```

**Comment by rongrong** [comment]
#12013 
```
General
---------
* Propagate partition properties for full outer join.
```

**Comment by raghavsethi** [comment]
```rst
General Changes
---------------
* Fix slow query planning performance for queries submitted when cluster did not have the required number of workers available.
* Show amount of data spilled in CLI.

Web UI Changes
--------------
* Improve live plan view to contain more information about each node. For example, table scans now show the name of table being scanned.
* Add the ability to zoom when viewing plan for completed queries.
* Change live plan to show data transfer statistics as edge labels.
* Change stage skew histograms to make it easier to identify low skew.
* Show spilled data on query details page.

**Comment by mbasmanova** [comment]
General
--------

**Comment by elonazoulay** [comment]
```
General
--------
* Add configuration property "query.stage-count-warning-threshold".
* Add TOO_MANY_STAGES warning when the number of stages exceeds this threshold.
```

**Comment by jessesleeping** [comment]
```
General
-------
* Add ANALYZE statement to the engine which allows collecting table statistics on demand. 

Hive
-------
* Add support for ANALYZE statement in the Hive connector. Users can specify a list of 
partitions to analyze via WITH properties of the ANALYZE statement.

SPI change
-------
* Add new SPIs for ANALYZE statement. By default, running ANALYZE statement in connector 
that does not implement these SPIs throws USER_ERROR with error code NOT_SUPPORTED. 
```

**Comment by nezihyigitbasi** [comment]
@kokosing can you please provide some release notes for your commits?

**Comment by findepi** [comment]
@nezihyigitbasi at least some of @kokosing 's changes have release notes @ https://prestosql.io/docs/current/release/release-301.html
except for `Handle S3 empty directories as directories`  which was mentioned in https://prestosql.io/docs/current/release/release-302.html
HTH

**Comment by kokosing** [comment]
```
Hive Connector Changes
---------------------------
* Add hive.temporary-staging-directory-enabled configuration property and temporary_staging_directory_enabled session property to control whether a temporary staging directory should be used for write operations.
* Add hive.temporary-staging-directory-path configuration property and temporary_staging_directory_path session property to control the location of temporary staging directory that is used for write operations. The ${USER} placeholder can be used to use a different location for each user (e.g., /tmp/${USER}).
* Allow creating tables with the external_location property pointing to an empty S3 directory.

Base-JDBC Connector Library Changes
-----------------------------------------
* Add support for defining procedures.
* Add support for providing table statistics.
```

@findepi Thanks.
