### ISSUE TITLE
Presto download link

### ISSUE THREAD

**Issue by hensg** [prestodb/presto#12261]
The link in documentation [presto deployment](https://prestodb.github.io/docs/current/installation/deployment.html) to download presto 0.216 is returning 404.

Link: https://repo1.maven.org/maven2/com/facebook/presto/presto-server/0.216/presto-server-0.216.tar.gz

**Comment by cricket007** [comment]
Can you access https://repo1.maven.org/maven2/com/facebook/presto/presto-server/0.216/ at all?
