### ISSUE TITLE
mvn clean install fails with non-resolvable parent pom

### ISSUE THREAD

**Issue by gkiffney** [prestodb/presto#12282]
Darwin IDXC02T22MHG8WL 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

./mvnw clean install
`
Downloaded: https://repo.maven.apache.org/maven2/org/apache/ant/ant/1.9.4/ant-1.9.4.jar (2.0 MB at 1.6 MB/s)
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.facebook.presto:presto-elasticsearch:[unknown-version]: Could not find artifact com.facebook.presto:presto-root:pom:0.216-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 4, column 13
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.facebook.presto:presto-elasticsearch:[unknown-version] (/Users/gkiffney/presto/presto-elasticsearch/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.facebook.presto:presto-elasticsearch:[unknown-version]: Could not find artifact com.facebook.presto:presto-root:pom:0.216-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 4, column 13 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException`

**Comment by nezihyigitbasi** [comment]
Can you pull in the latest master and try again? This should have been fixed by https://github.com/prestodb/presto/pull/12281.

**Comment by gkiffney** [comment]
Fixed, thanks!
