### ISSUE TITLE
Issue when trying to access AWS Glue catalog

### ISSUE THREAD

**Issue by scraly** [prestodb/presto#12286]
Hi,

I've deployed a Presto (not in a AWS EMR cluster) and then when I connect to a Cassandra cluster, everything it's working but I have issue with AWS Glue catalog.

```$ presto --server localhost:8080 --catalog hive
presto> select table_schema, table_name from information_schema.tables;
Query 20190131_160441_00011_tz4jt failed: Access denied (Service: AWSSecurityTokenService; Status Code: 403; Error Code: AccessDenied; Request ID: eaf68f55-2571-11e9-83d4-b5f2a4710d4e)
```

How can I access to a AWS Glue catalog and tables through Presto?

Thanks

**Comment by nezihyigitbasi** [comment]
@scraly to understand the specifics more info is needed here. It may be an aws role issue, and in that case https://github.com/prestodb/presto/pull/10864 may help.
/cc @rentaow
