### ISSUE TITLE
how to pass dynamical parameter value to presto query in command line

### ISSUE THREAD

**Issue by kiranps11** [prestodb/presto#12296]
how to pass dynamical parameter value to presto query in command line

**Comment by mbasmanova** [comment]
@kiranps11 I don't understand the question. Could you explain a bit more?

**Comment by kiranps11** [comment]
Hello @mbasmanova ,
My query is like : select * from table_a where dat='${date_value}' and the date_value will be a variable .
I need to pass the $date_value to presto in command line .

**Comment by kokosing** [comment]
Is:

```
cat << EOF | presto-cli
select * from table_a where dat='${date_value}';
EOF
```

Good enough for you?
