### ISSUE TITLE
when do you support hadoop3 or cdh6?

### ISSUE THREAD

**Issue by wuxiansen** [prestodb/presto#12323]
hello，How to connect cdh6 or hive-hadoop3 ？

**Comment by findepi** [comment]
You can just use `hive-hadoop2` plugin for that. It's reported that this just works.

There is an ongoing effort (see eg https://github.com/prestosql/presto/pull/203 and https://github.com/prestosql/presto/pull/198) to support Hive 3.1 explicitly.
