### ISSUE TITLE
Timeline UI page is broken

### ISSUE THREAD

**Issue by sopel39** [prestodb/presto#12361]
Timeline.html file explicitly has:
```
    <script src="vendor/d3/d3-3.3.4.js"></script>
...
```
but it was removed in https://github.com/prestodb/presto/commit/e2aa9e139ea48430ad5446fcff786b7979aa8638

Therefore splits UI page no longer works

FYI: @raghavsethi

**Comment by tooptoop4** [comment]
why is this closed? i am facing the issue in prestodb v0.220 ---> GET https://xxx/ui/vendor/d3/d3-3.3.4.js net::ERR_ABORTED 404 (Not Found)

**Comment by tooptoop4** [comment]
@sopel39 @raghavsethi gentle ping

**Comment by sopel39** [comment]
This is fixed in https://github.com/prestosql/presto/pull/283

**Comment by tooptoop4** [comment]
but this is prestodb issue and that is prestosql fix
