### ISSUE TITLE
too many open partitions bucketing

### ISSUE THREAD

**Issue by ramrock2008** [prestodb/presto#12390]
Hello, I'm running presto CTAS query with partitioning and bucketing and running into following error: "Maximum number of partitions allowed to write: 100"

Here is the select query:

> CREATE table ctas_dest_bucketcount32
WITH (partitioned_by=ARRAY['date'],bucketed_by=ARRAY['eventid'],bucket_count=32) 
AS 
(
    SELECT eventid ,
           date(myeventtime) date
    FROM ctas_source
    WHERE date(myeventtime)>= date '2018-07-01'
      AND date(myeventtime)< date '2018-09-01' 
)

I have made sure the unique number of partition keys are less than 100. 
 > select count(distinct( date(myeventtime))) from ctas_source WHERE date(myeventtime)>= date '2018-07-01' AND date(myeventtime)< date '2018-09-01'  --> Returns 62

the column I used for bucketing is highly cardinal and contains more than 6 million unique rows.
>  select count(distinct(eventid)) from ctas_source --> returns 6.3 Million rows

When I look at this code module, https://github.com/prestodb/presto/blob/master/presto-hive/src/main/java/com/facebook/presto/hive/HivePageSink.java , it seems the bucketing columns may also play a role in determining the dynamic partioning count

Can you please provide simple explanation of how bucketing columns/bucket count add to the max number of partitions or max number of wrtiers

**Comment by wenleix** [comment]
For bucketed table, you can roughly think the following:
```
   #partitions * #buckets <= 100 * #nodes
```

Also, is the error message "max number of open files" or "max number of partitions"? -- if latter we might need to update the error message to clarify it :)

**Comment by ramrock2008** [comment]
Thanks. The error message is "too many open partitions" and not related to too many open files.
