### ISSUE TITLE
Why not use column statistics to filter some orc files like Hive?

### ISSUE THREAD

**Issue by dinglianYuan** [prestodb/presto#12424]
When querying a SQL, why not use column statistics to filter some orc files like Hive? Are there any enthusiasts who answered this question?

**Comment by ryanrupp** [comment]
This is already supported for ORC (min/max + bloom filter) and Parquet files (min/max + dictionary), is there anything you're seeing that made you think this isn't working? For reference, ORC this logic takes place   [here](https://github.com/prestodb/presto/blob/master/presto-orc/src/main/java/com/facebook/presto/orc/TupleDomainOrcPredicate.java)

**Comment by highker** [comment]
Yes, we support ORC stats

**Comment by dinglianYuan** [comment]
Thank you very much. This is my mistake. I didn't see this part in the source code before.
