### ISSUE TITLE
use elasticsearch connector have error

### ISSUE THREAD

**Issue by victor-wzq** [prestodb/presto#12449]
java.lang.NoClassDefFoundError: com/fasterxml/jackson/annotation/Nulls
i compile elasticsearch connector and run the launcher .and then accept this error

**Comment by nezihyigitbasi** [comment]
@aibaozi1 can you please share the entire stacktrace?

/cc @zhenxiao

**Comment by zhenxiao** [comment]
@aibaozi1 did not see this error before. let me know ur entire stacktrace. I'd be happy to debug.
