### ISSUE TITLE
Guidance to implement clickhouse connector

### ISSUE THREAD

**Issue by zeeshanabid94** [prestodb/presto#12440]
Hey guys!

We were recently looking at looker as our BI tool but as it turns out presto does not support clickhouse. Clickhouse has JDBC drivers and Presto has a extendable interface to support any JDBC driver.

I have gone through the presto developer docs. I would appreciate it if there were other sources of guidance that any one knows.

Thank you!

**Comment by ebyhr** [comment]
Hi, you can develop JDBC based library very easily. `presto-mysql` or `presto-postgresql` codes would help you.

**Comment by spaghettifunk** [comment]
I opened a PR aiming to solve this problem. Happy to get feedback and help on this.

**Comment by zeeshanabid94** [comment]
Hey! I already made a connector for clickhouse. Would you like to review my plugin, give feedback and eventually merge that into this repo?

**Comment by spaghettifunk** [comment]
@zeeshanabid94 of course! send me the link and i'll check it out! My team and I needs to have Clickhouse working with Presto ASAP :)

**Comment by zeeshanabid94** [comment]
Great! I'll send you the link to the repo tomorrow.

**Comment by highker** [comment]
@spaghettifunk , @zeeshanabid94 could you discuss which PR you wanna proceed with? We can review once you have reached a consensus.

**Comment by highker** [comment]
Let's use #9620 to track the ticket.

**Comment by huynhphuong10284** [comment]
> Great! I'll send you the link to the repo tomorrow.

Please share for this friend.
