### ISSUE TITLE
Why query results are transmitted between workers?

### ISSUE THREAD

**Issue by dinglianYuan** [prestodb/presto#12466]
My Presto cluster has three machines, a coordinator(machine 1) and two workers(machine 2&3). When I query an SQL, machine 2 sends a request to machine 3 to get the query results, and Coordinator gets all the query results from machine 2. Why? I think Coordinator should get query results from machine 2 and 3, respectively.

**Comment by highker** [comment]
Could you be more specific? Query, setting, session...

**Comment by dinglianYuan** [comment]
Presto has a configuration item 'optimizer.force-single-node-output', whose default value is true. When changed to false, the coordinator will get the result data directly from each work. Is it more efficient to get results from one node?

**Comment by highker** [comment]
This is the original PR #8962. I briefly skimmed through the code; I guess with the exchange, the last piece of work will be done on the coordinator, which is not ideal.

**Comment by dinglianYuan** [comment]
Thank you!
I have another question. 
When Presto transfers results, it uses JSON structure and uses Jackson for serialization. But there are better options, such as Protobuf structure and Kryo serialization. Now the data returned by a single response is about 30MB, but it takes about 4 seconds to deserialize the responsebody into a String. Is there a better way to improve the performance of deserialization?

**Comment by highker** [comment]
#12342 added afterburner for json serde. #12363 added smile encoding. We expect to have more efficient serde in the future. Kryo is an option.
