### ISSUE TITLE
SELECT 1 / 0 -> DIVISION_BY_ZERO  v.s. SELECT 1.0 / 0 -> Infinity

### ISSUE THREAD

**Issue by cps333** [prestodb/presto#12468]
`SELECT 1 / 0` throws error

`SELECT 1.0 / 0` returns Infinity

Is this intentional?

**Comment by Praveen2112** [comment]
`SELECT 1 / 0` will be treated as `INTEGER` operation and division by 0 will throw an exception while `SELECT 1.0/0` will be treated as `DOUBLE` where it will return Infinity. But IIRC in the latest presto version these will be treated as `DECIMAL` in which division by 0 is prohibited. (This might result in `Infinity` `select cast(1.0 as DOUBLE)/0;`)
