### ISSUE TITLE
Error make integration of Presto using Kerberos authentication.

### ISSUE THREAD

**Issue by hellooops** [prestodb/presto#12476]
i'm make presto kerberos authentications now with reference to Presto 0.217 Documentation.
when i run the commands, it is wrong as:
`[root@presto ~]# ./presto \
> --server https://presto.ka.com:7778 \
> --krb5-config-path /etc/krb5.conf \
> --krb5-principal presto@HADOOP.COM \
> --krb5-keytab-path /usr/krbconfig/presto.keytab \
> --krb5-remote-service-name presto.ka.com \
> --keystore-path /usr/krbconfig/presto2keystore.jks \
> --keystore-password ***\
> --catalog hive \
> --schema demo
presto:demo> sdf;
Error running command: Authentication failed: Unauthorized
presto:demo> `
I can't find any reference of this Error.
I need your help.
thanks

**Comment by wenleix** [comment]
Is this the same issue as https://github.com/prestodb/presto/issues/12485 ?

**Comment by mwiewior** [comment]
The same issue, presto 0.222: Authentication failed: Unauthorized seems to be different from #12485
