### ISSUE TITLE
Kerberos authentication based Presto Configuration issue

### ISSUE THREAD

**Issue by hellooops** [prestodb/presto#12485]
I'm make configuration of Presto kerberos authentication according to the Presto 0.217 documentation.
I've built a KDC on the vm.
but when i execute 
```
$~/presto 
--server localhost:7778 
--krb5-config-path /etc/krb5.conf 
--krb5-principal krbtgt/HADOOP.COM@HADOOP.COM 
--krb5-keytab-path /usr/krbconfig/presto.keytab 
--krb5-remote-service-name presto 
--keystore-path /usr/krbconfig/prestokeystore.jks 
--keystore-password ****** 
--catalog hive --schema demo
Presto:demo> show tables;
```

on the server command, I got an error says:
`Error running command: java.io.IOException: unexpected end of stream on Connection{localhost:7778, proxy=DIRECT hostAddress=localhost/127.0.0.1:7778 cipherSuite=none protocol=http/1.1}`

I'm working on the configuration for several days, but still can't make it.

I need your help...
thanks

**Comment by mwiewior** [comment]
Use https in the server URL, so --server https://localhost:7778.
