### ISSUE TITLE
How to promote the speed?

### ISSUE THREAD

**Issue by panglei1984** [prestodb/presto#12494]
This is my computation performance,just 254K rows/s and 24.8MB/s.
But I saw some performace in internet,it can reach 78.7M rows/s and 16.9GB/s(2 nodes).
Please how to promote the speed,or how to positioning the bottleneck.
By the way,what's the meaning of these two unit？
thanks
---------------------------------------------------------------------------
presto:default> select count(*) from xxx;
  _col0
----------
 12240537
(1 row)

Query 20190319_031105_00594_3sem3, FINISHED, 12 nodes
Splits: 63,327 total, 63,327 done (100.00%)
0:48 [12.2M rows, 1.17GB] [254K rows/s, 24.8MB/s]

**Comment by tooptoop4** [comment]
@panglei1984  how much memory/cores are in your presto cluster, how many nodes? is your table hive, cassandra, other?

**Comment by mbasmanova** [comment]
CC: @oerling
