### ISSUE TITLE
Support row level security

### ISSUE THREAD

**Issue by Phelodas** [prestodb/presto#12491]
Opening a new issue as #8980 and #10996 are not Row Level Security specific although there are lots of good points there. 

The issue will track supporting row level security as a paradigm in Presto.

Design is [here](https://docs.google.com/document/d/1XCkBPf9fLXqYZqYxoJXBxo7tx98-TV1CzgzUGZoIKEE/edit?usp=sharing)

The link discusses a short term solution which may be subsumed when we have Connectors participating in query optimization

**Comment by wenleix** [comment]
cc @rongrong , @elonazoulay
