### ISSUE TITLE
Update Elasticsearch Connector docs for Search Guard

### ISSUE THREAD

**Issue by nezihyigitbasi** [prestodb/presto#12502]
We should document the config for Search Guard support (https://github.com/prestodb/presto/pull/12422) in the Elastic Search connector.

**Comment by nezihyigitbasi** [comment]
@TempleZhou Can you please help us with this issue given that you are the author of the Search Guard PR? We should document the Search Guard config properties in the `presto-docs/src/main/sphinx/connector/elasticsearch.rst` file.

**Comment by TempleZhou** [comment]
OK, I will create PR soon.

**Comment by TempleZhou** [comment]
The PR: [#12508](https://github.com/prestodb/presto/pull/12508)

**Comment by TempleZhou** [comment]
I have updated the PR.

**Comment by wenleix** [comment]
Resolved by https://github.com/prestodb/presto/pull/12508
