### ISSUE TITLE
Support FNV hash functions

### ISSUE THREAD

**Issue by rongrong** [prestodb/presto#12500]
https://en.wikipedia.org/wiki/Fowler%E2%80%93Noll%E2%80%93Vo_hash_function

There are different flavors of this hash function. We'd like to introduce
`bigint fnv64(binary)`
`bigint fnv32(binary)`

**Comment by wenleix** [comment]
Similar to spooky hash (https://prestodb.github.io/docs/current/functions/binary.html#spooky_hash_v2_32), we should just have `fnv32` and `fnv64` .

**Comment by codope** [comment]
@rongrong I would like to pick up this task. Would you recommend adding this hash function to [Slice](https://github.com/airlift/slice) library and then import in `scalar/VarbinaryFunctions.java`? Or should i just directly add the function in `scalar/VarbinaryFunctions.java`?

**Comment by rongrong** [comment]
It makes sense to introduce this to airlift Slice to me. @electrum What do you think?

**Comment by rongrong** [comment]
@codope Let's just add this to Presto directly.

**Comment by codope** [comment]
@rongrong I have not started yet but I think it'd be better to add this to Airlift. I'll work on it next week. Let me know if it's urgent then I'll simply add it to Presto first.

**Comment by gastonar** [comment]
@codope Have you been able to make some progress with these functions? I was thinking of adding them directly to Presto.

**Comment by codope** [comment]
@gastonar Yes, it is in progress.

**Comment by rongrong** [comment]
@codope could you please ping airlift to get this merged? If they are not responsive feel free to directly write the function in Presto. Thanks!

**Comment by codope** [comment]
@rongrong  I have pinged the team. Let's wait till this week. If that diff is not merged, I'll add the function to Presto directly.

**Comment by codope** [comment]
Update: Waiting for the latest version of Slice to be released on [maven central](https://mvnrepository.com/artifact/io.airlift/slice).

**Comment by rongrong** [comment]
@codope are you still working on this?

**Comment by codope** [comment]
@rongrong sorry, the work is paused on this. I have asked for the latest version of slice on maven as per [this comment](https://github.com/airlift/slice/issues/114#issuecomment-526786655). Let's wait one more week. If still no progress, I will add the function directly in Presto.

**Comment by rongrong** [comment]
@codope It's been a while, do you want to finish this off?
