### ISSUE TITLE
kudu connector for sercurity

### ISSUE THREAD

**Issue by xiaoyunancy** [prestodb/presto#12537]
My kudu cluster is enable sercurity.
When I use presto kudu connector. I found a error:

`Couldn't find a valid master in (xxx:7051). Exceptions received: [org.apache.kudu.client.NonRecoverableException: Server requires Kerberos, but this client is not authenticated (missing or expired TGT), org.apache.kudu.client.NonRecoverableException: Server requires Kerberos, but this client is not authenticated (missing or expired TGT), org.apache.kudu.client.NonRecoverableException: Server requires Kerberos, but this client is not authenticated (missing or expired TGT)]`

I found something in presto document

```
Known limitations
Only lower case table and column names in Kudu are supported
Using a secured Kudu cluster has not been tested.
```

**Comment by xiaoyunancy** [comment]
@electrum

**Comment by wenleix** [comment]
cc @rongrong , @elonazoulay . Is this issue you are familiar with ? :)

**Comment by xiaoyunancy** [comment]
Thanks,I have resloved this problem.
two way:
1,on presto worker,use kinit to register kerberos
2,in initial KuduClient import sercurity,just like
`KuduClient kuduClient = Subject.doAs(subject,
                (PrivilegedExceptionAction<KuduClient>) () -> new KuduClient.KuduClientBuilder(config.getMasterAddresses()).build());`

**Comment by dukeshiny** [comment]
> Thanks,I have resloved this problem.
> two way:
> 1,on presto worker,use kinit to register kerberos
> 2,in initial KuduClient import sercurity,just like
> `KuduClient kuduClient = Subject.doAs(subject, (PrivilegedExceptionAction<KuduClient>) () -> new KuduClient.KuduClientBuilder(config.getMasterAddresses()).build());`

hello,Can you select data from kudu table in presto ?

**Comment by xiaoyunancy** [comment]
> > Thanks,I have resloved this problem.
> > two way:
> > 1,on presto worker,use kinit to register kerberos
> > 2,in initial KuduClient import sercurity,just like
> > `KuduClient kuduClient = Subject.doAs(subject, (PrivilegedExceptionAction<KuduClient>) () -> new KuduClient.KuduClientBuilder(config.getMasterAddresses()).build());`
> 
> hello,Can you select data from kudu table in presto ?

yes,I can

**Comment by shanenleen** [comment]
> Thanks,I have resloved this problem.
> two way:
> 1,on presto worker,use kinit to register kerberos
> 2,in initial KuduClient import sercurity,just like
> `KuduClient kuduClient = Subject.doAs(subject, (PrivilegedExceptionAction<KuduClient>) () -> new KuduClient.KuduClientBuilder(config.getMasterAddresses()).build());`

kinit didn't work for me. Can you elaborate more on these steps.

**Comment by liyubin117** [comment]
I have resolved the problem, make some simple configuration to achieve kerberos authentication automatelly at a long run time
please see at follows:
https://github.com/prestodb/presto/pull/13968
