### ISSUE TITLE
do not alter table in hive 

### ISSUE THREAD

**Issue by firewaternottogther** [prestodb/presto#12536]
ALTER TABLE xwj_test1 RENAME COLUMN name TO name1;
presto err:
Query 20190327_075810_00002_2rqrf failed: Access Denied: Cannot rename a column in table test.xwj_test1
I'm dying for your help

**Comment by firewaternottogther** [comment]
this is serious problem .

**Comment by ebyhr** [comment]
Did you  set `allow-rename-column` in your property like below? The default value is false.
hive.properties
```
hive.allow-rename-column=true
```

**Comment by firewaternottogther** [comment]
> Did you set `allow-rename-column` in your property like below? The default value is false.
> hive.properties
> 
> ```
> hive.allow-rename-column=true
> ```

**Comment by firewaternottogther** [comment]
@ebyhr  
thank you very much。You also know which ones default to false.I hope you can tell me some.

**Comment by ebyhr** [comment]
@firewaternottogther Below properties' default value are all false.
```
hive.allow-add-column
hive.allow-drop-column
hive.allow-drop-table
hive.allow-rename-table
hive.allow-rename-column
```

If you want to confirm other default value, you can see it from server log during start.
```sh
2019-03-28T07:59:56.792+0545	INFO	main	Bootstrap	PROPERTY                                           DEFAULT                                           RUNTIME                                                     DESCRIPTION
2019-03-28T07:59:56.793+0545	INFO	main	Bootstrap	hive.allow-rename-column                           false                                             true                                                        Allow Hive connector to rename column
```

**Comment by firewaternottogther** [comment]
@ebyhr
thank you very much too. I've got the logic. 
but i have some question. If I add a column, but presto doesn't support update, how do I add what I want to the column.

**Comment by ebyhr** [comment]
@firewaternottogther I'm sorry, but I couldn't understand the situation. Could you share some example?

**Comment by firewaternottogther** [comment]
@ebyhr 
Thank you for your reply. I am very excited to see the master's reply.
The purpose of adding a field is to add a column of what I want to express.
example:
postgres syntax rules:
alter table student add column age text;
update student set age=tm.age from temporary tm where student.name=tm.name;

Can presto be implemented,Or another way to do it.Again, the goal is to add the desired content to the new field.

**Comment by ebyhr** [comment]
@firewaternottogther I see, thank you for providing the info. I think you need to create new table and swap it.

```sql
create table student_tmp as
 select
 a.*
 , b.age as age 
 from student a
  left outer join temporary b
  on a.name = b.name
;
alter table student rename to student_old;
alter table student_tmp rename to student;
drop table student_old;
```

**Comment by firewaternottogther** [comment]
@ebyhr  
thanks. It's a neat trick.perfect.

**Comment by firewaternottogther** [comment]
@

**Comment by wenleix** [comment]
@firewaternottogther  I close the issue since it looks like the problem solved. Feel free to reopen it if any problem raised in the future.
