### ISSUE TITLE
Window ordering when no ordering clause is specified

### ISSUE THREAD

**Issue by cyprnose** [prestodb/presto#12551]
Consider following query:

```
with test (a, b, c) as (
      (VALUES (0, 5, 50),
              (0, 3, 30),
              (0, 4, 40),
              (0, 1, 10),
              (1, 8, 80),
              (1, 7, 70)
      )
  ),
test_ordered AS (
  SELECT * FROM test ORDER BY a, b
)
SELECT
  a,
  array_agg(c) OVER(PARTITION BY a) sequence
FROM test_ordered
```

Can I assume that the ordering for window function be the same as the one in output of `test_ordered` when window ordering cluase for window function is not specified?

So the expected output always be:

> 0 | [10, 30, 40, 50]
> 0 | [10, 30, 40, 50]
> 0 | [10, 30, 40, 50]
> 0 | [10, 30, 40, 50]
> 1 | [70, 80]
> 1 | [70, 80]
> 

This what I found in SQL spec:

> If WD has no window ordering clause, then the window
> ordering is implementation-dependent, and all rows are peers. Although the window ordering of peer rows
> within a window partition is implementation-dependent, the window ordering shall be the same for all
> window structure descriptors that are order-equivalent. It shall also be the same for any pair of windows
> W1 and W2 such that W1 is the ordering window for W2.

However I didn't find any details in presto documentation.

Edit: I refer to Athena (Presto 0.172 if I'm not wrong)

**Comment by wenleix** [comment]
@cyprnose : 0.172 is an ancient version :) . Does the issue still appear on latest version ? Thanks!

**Comment by cyprnose** [comment]
@wenleix Thanks for answering!

Actually there is no issue. All queries I've tried similar to the aforementioned, work as expected (I mean queries with window function without ordering clause). But due to SQL specification (which says that in such case ordering is "implementation-dependent") and the fact that presto/athena docs says nothing about this, I don't know if I can rely on such solution. Which basically holds me from using it for "prod" application.

The question is: is it always true that when no ordering clause is specified the order of rows for window function is exactly the same as given by retrieved rows (eg. in example I've provided: is `ORDER BY` in `test_ordered` guarantees the ordering for WF?)

The only clue I've found is for Informix db which says:

> The database server sorts the rows in each window partition according to the sort key (or multiple sort keys) in the window ORDER clause. If you specify no ascending (ASC) or descending (DESC) order, ASC is the default. If no ORDER clause is specified, the order of the qualifying rows is the order in which the rows were retrieved.

(https://www.ibm.com/support/knowledgecenter/en/SSGU8G_12.1.0/com.ibm.sqls.doc/ids_sqs_2584.htm)

**Comment by rschlussel** [comment]
If the order isn't specified, Presto doesn't guarantee that it will be in any particular order (and, since it's not semantically required by your query presto could remove the initial order by entirely: https://github.com/prestodb/presto/issues/7613)

**Comment by rschlussel** [comment]
@cyprnose Feel free to reopen the issue if we haven't addressed your question.

**Comment by cyprnose** [comment]
@rschlussel Sure, thank you for the answer, it was very helpful!
