### ISSUE TITLE
if ES field names are in Pascal Case, Camel case or in the uppercase then presto is not able to map

### ISSUE THREAD

**Issue by shubham-agarwal-ngi** [prestodb/presto#12562]
If we are giving the value in the camel case, pascal case or in the uppercase of the name or in  jsonPath fields then the presto is not able to map and showing the NULL values for that particular fields.

Please advice.

**Comment by raghavsethi** [comment]
By ES, do you mean Elasticsearch?

**Comment by shubham-agarwal-ngi** [comment]
hi raghavsethi,

yes, ES means Elastic search

**Comment by raghavsethi** [comment]
And can you clarify what you mean by map? If you do DESCRIBE, does Presto show the columns? Are you confident that the values are non null?

@TempleZhou @zhenxiao could one of you take a look at this?

**Comment by shubham-agarwal-ngi** [comment]
Hi Raghav,

Let me tell you with an example,

Case 1:
This is the table definition in case of elastic search.
{
	"tableName": "dummy",
	"schemaName": "es",
	"host": "0.0.0.0",
	"port": 0000,
	"clusterName": "clustername",
	"index": "dummy",
	"type": "user",
	"columns": [{
		"name": "Gender",
		"type": "varchar",
		"jsonPath": "Gender",
		"jsonType": "varchar",
		"ordinaryPosition": "0"
	}]
}

In Elastic search index, the mapping also with the same name "Gender" and let say I have 10 records in the elastic search.
If I hit the select query using the presto for elastic search and then we get the 10 records with the NULL values of "Gender" fields.

Case 2:
This is the table definition in case of elastic search.
{
	"tableName": "dummy",
	"schemaName": "es",
	"host": "0.0.0.0",
	"port": 0000,
	"clusterName": "clustername",
	"index": "dummy",
	"type": "user",
	"columns": [{
		"name": "gender",
		"type": "varchar",
		"jsonPath": "gender",
		"jsonType": "varchar",
		"ordinaryPosition": "0"
	}]
}
In Elastic search index, the mapping also with the same name "gender" and let say I have 10 records in the elastic search.
In case 2, we get the 10 number of records with the valid values for gender fields.

Now my question is,
If we are giving the value in the camel case, pascal case or in the uppercase of the name or in jsonPath fields then why the presto is  showing the NULL values for that particular fields.

please advice.

**Comment by jwfcps** [comment]
The code forces field names to lowercase, the diff I posted in https://github.com/prestodb/presto/issues/12642 includes fixing this, as well as "fixing" nested fields.

**Comment by zhenxiao** [comment]
@shubham-agarwal-ngi sorry for the late reply
Seems we have a bug in resolving Elasticsearch upper case field names. 
@jwfcps could you please submit separate PRs, or separate commits? One for resolving upper case field names, another one for fixing nested fields? I will take a review
