### ISSUE TITLE
User defined databases has not listed while using presto MsSql Connector

### ISSUE THREAD

**Issue by shubham-agarwal-ngi** [prestodb/presto#12561]
Hi,
I have added sqlserver connector and am able to fetch default schemas present in it. I do not see the schemas that was created by me.

------
Here is sqlserver connector configuration

connector.name=sqlserver
connection-url=jdbc:sqlserver://xyz:2048
connection-user=zyx
connection-password=yxz

show schemas from sqlserver;

         Schema          
-------------------------
 db_accessadmin          
 db_backupoperator       
 db_datareader           
 db_datawriter           
 db_ddladmin             
 db_denydatareader       
 db_denydatawriter       
 db_owner                
 db_securityadmin        
 dbo                     
 guest                   
 information_schema      
 nt service\reportserver 
 rsexecrole              
 sys

Regards
Shubham Agarwal

**Comment by ebyhr** [comment]
I could list non-system schema. Could you please share the below query result in sqlserver?
```sql
select name from sys.schemas;
```

**Comment by wsjz** [comment]
so how to solve the problem?
