### ISSUE TITLE
FR : return gzipped result sets

### ISSUE THREAD

**Issue by aadant** [prestodb/presto#12576]
Does it make sense to gzip result sets from presto at the http-server level ?

MySQL for example enables compression in its protocol. It would reduce the traffic.

**Comment by aadant** [comment]
actually zstd and lz4 should be great too

**Comment by nezihyigitbasi** [comment]
> Does it make sense to gzip result sets from presto at the http-server level ?

Compressing the result sets will result in less network traffic between the clients and the Presto coordinator, but will cause the coordinator to spend more CPU cycles for compressing the results, so it's a trade off, and whether it makes sense or not depends on what you want to accomplish. In my experience though CPU and memory are more scarce resources than network for Presto coordinators, so I haven't seen many people using compression for results. 

The framework Presto uses should be able to return compressed responses already if the client provides the right HTTP headers, please give it a try and if that doesn't work we can dig in to see what's going on. For example, to get the available nodes in a cluster as gzipped compressed data:

```
curl -H "Accept-Encoding: gzip" http://coordinator:8080/v1/node  | gunzip
```

**Comment by aadant** [comment]
Thanks, I test it and it is actually a little bit slower but not much. It might still be interesting when network is limited or maxed out.

This works too and it is transparent to the user :

` accept_encoding_header = 'Accept-Encoding'
  accept_encoding_value = 'gzip'
  conn=prestodb.dbapi.connect(
              host='localhost',
              port=self.port,
              user='user',
              catalog='hive',
              schema='default',
              http_headers={ accept_encoding_header: accept_encoding_value }
        )
`

Would this protocol https://github.com/prestodb/presto/wiki/Presto-v2-client-protocol be faster ?
