### ISSUE TITLE
declare InternalCommunicationConfig but never use it.

### ISSUE THREAD

**Issue by frankzye** [prestodb/presto#12636]
https://github.com/prestodb/presto/blob/cfb3d8bab09a9e40adae40c60e32fd5ec0fccb66/presto-main/src/main/java/com/facebook/presto/server/ServerMainModule.java#L190

**Comment by rongrong** [comment]
Thanks for spotting this @frankzye. Do you want to help us fix this? cc @nezihyigitbasi

**Comment by frankzye** [comment]
sure, how to contribute?
