### ISSUE TITLE
Detach Node from LateralJoinNode and ApplyNode

### ISSUE THREAD

**Issue by highker** [prestodb/presto#12665]
`originSubquery` in `LateralJoinNode` and `ApplyNode` is a hacky workaround only for displaying informative error messages:
https://github.com/prestodb/presto/blob/53aceb04a712d6f9b5dfb2222376b799c85a5ce8/presto-main/src/main/java/com/facebook/presto/sql/planner/plan/LateralJoinNode.java#L69

The goal is to:
- Come up with a better solution to display the error message.
- Detach AST (`sql.tree`) dependency from `LateralJoinNode` and `ApplyNode`.

**Comment by curcur** [comment]
1. Do we still need to keep the same level of error information? If yes, I still need to get the node information somewhere

2. Is the main goal to detach dependency by removing Node from  LateralJoinNode and ApplyNode?

**Comment by highker** [comment]
1. Yes. We don't need the entire Node. Some abstraction of error info would be great. 
2. Yes.

**Comment by curcur** [comment]
#12718
