### ISSUE TITLE
Unable to access Transaction info in an Exception Handler

### ISSUE THREAD

**Issue by zhaotao1986** [prestodb/presto#12675]
### Problem:
      
Every code path, when it needs transaction info, and transaction exists, it should get it. Now at least one path can't.

### Reproduce:
      
Reading the codes can show it's obviously wrong.
      To reproduce locally: 
1. build any version of Presto
2. set a breakpoint in SqlQueryManager.java, the line in the first pic below
3. in IDEA, click to run RaptorQueryRunner.main()
4. open a termal, input
    $ XXX/presto-cli/target/presto-cli-0.217-SNAPSHOT-executable.jar
    presto> select * from raptor.t.sadfaeetdfadsf; // anything that doesn't exist
5.   check at that breakpoint, transaction info is null. 

### Effect:
      
RaptorV2 deployment. RaptorV2 deleting garbage depends on that line in first pic below; if it cannot access transaction,  RaptorV2 cannot even run. So not a corner case bug, a critical one.

RaptorV1 is also incorrect, but not that critically affected, incorrect for years anyway.

### Concerns:

It's said that Session is immutable, there can be multiple Sessions. So please find a way that doesn't disturb the current design, meanwhile solve it.
      Keep in mind that a fix is not only for this one code path, should be for all paths. Every path should be able to access transaction info.

### Details:

SqlQueryManager.java,  this exception handler:
![image](https://user-images.githubusercontent.com/7345416/56067312-8eac1880-5d2f-11e9-9d3e-ed1bfb28956c.png)
That line cannot get transaction info. 

Because transaction info is created in QueryStateMachine.java,  
![image](https://user-images.githubusercontent.com/7345416/56067801-586f9880-5d31-11e9-891b-ca56ab1e576b.png)
it creates a new Session, but SqlQueryManager still uses the old Session.

Another issue not currently my concern now, but also worth changing:
`session.getTransactionId().ifPresent(transactionManager::fail); `
should be inside "finally" like
`queryTracker.expireQuery(queryId);
`

**Comment by highker** [comment]
You need a `START TRANSACTION` to set the transaction.
