### ISSUE TITLE
StatementSplitter return wrong result

### ISSUE THREAD

**Issue by taideli** [prestodb/presto#12681]
hi, all,
   i have a text contains multi sql statement(include partial statement) : 
```sql select * from aa; select a, b from; select c, d from cc ```
when i new a StatementSplitter with this sql, i got the spliter with completeStatements contains two sql (select * from aa;    select a, b from;) and partialStatement is select c, d from cc

Thank you so much for your help.

**Comment by rschlussel** [comment]
What's the issue?  A semicolon marks the end of a statement, so the StatementSplitter takes the parts that end in a semicolon and adds it to the complete statements.  If there's no semicolon at the end, then whatever is left over is considered a partial statement. The partial statement is used e.g. if you're entering your query in the cli over multiple lines.

The StatementSplitter doesn't do any parsing, so it won't tell you whether the statements are syntactically valid (e.g. your second statement is not).

**Comment by taideli** [comment]
your reminder makes me understand that i have misunderstood about it's function.
 
thanks for your kindly help very much~
