### ISSUE TITLE
Suggested UDF: ENTROPY

### ISSUE THREAD

**Issue by atavory** [prestodb/presto#12700]
I'd like to write entropy.

Motivation
------------

[Entropy](https://en.wikipedia.org/wiki/Entropy_(information_theory)) is a measure of disorder and uncertainty. 

Say you have a number of web pages, each accessed by approximately 100 visits last month. The visits of one page might be "organized", in the sense that all 100 accesses came from a small number of users, while the visits of another page might be "disorganized", in the sense that the 100 accesses were distributed over many more users. In this case, entropy quantifies how "disorganized" the accesses are, by taking a column of counts per user (summing up to about 100, in this example), and giving a single number.

Entropy is also used as the basis of several other calculations in machine learning and statistics.

Possible inputs and output
------------------------------

  entropy(BIGINT) -> DOUBLE
  entropy(INT) -> DOUBLE

Description
------------

Compute the normalized entropy of a series of counts.  The input is assumed
 to be a column of counts of each value's occurrence . The entropy is normalized in the sense that
 the counts are first normalized so that the sum of all counts equals one
 (i.e., it is converted to a probability distribution).  Any NULLs in the
 column are ignored.  If the column contains negative values then NULL is
 returned.  If the total count of entries of in the column is zero then zero
 is returned.

 Note that the entropy is computed using base-2 log.

Implementation (WIP)
------------------------

[`EntropyAggregation.java`](https://github.com/atavory/presto/blob/master/presto-main/src/main/java/com/facebook/presto/operator/aggregation/EntropyAggregation.java)
[`EntropyState.java`](https://github.com/atavory/presto/blob/master/presto-main/src/main/java/com/facebook/presto/operator/aggregation/state/EntropyState.java)
[`TestEntropyAggregation.java`](https://github.com/atavory/presto/blob/master/presto-main/src/test/java/com/facebook/presto/operator/aggregation/TestEntropyAggregation.java)

**Comment by rongrong** [comment]
I believe `ENTROPY` and `MAP_ENTROPY` are facebook Hive UDFs. Are they available in open source? Is there general use cases for these functions outside of Facebook? I don't have a math background so please help me understand the use case better so we can figure out:
* Should this function be in presto-facebook or presto open source
* What's the API of this function

Thanks!

**Comment by atavory** [comment]
@rongrong 

Thanks for your comment! I've updated the first comment based on your feedback. Please let me know if I can clarify anything else further.
