### ISSUE TITLE
Sorted checksum for array columns causing checksum queries to fail in Verifier

### ISSUE THREAD

**Issue by caithagoras** [prestodb/presto#12703]
Following up on https://github.com/prestodb/presto/issues/12623
cc @mayankgarg1990 @mbasmanova 

### Cause
The failure occurred when we sort an orderable array column, `checksum(array_sort(array_column))`, in order to disregard the ordering when verifying the column.

In SQL spec, `NULLs` are generally treated as unknown. For example in Presto, `SELECT row(1, null) < row(2, null)` is `True` because the order can be determined at position 0, but `SELECT row(1, null) < row(1, null)` throws because null comparison happens at position 1.

In the checksum query, the  `array_column` can be an `Array(Row)` with some of the rows containing `null` elements, causing `array_sort` to throw.

### What columns are impacted?
- Array columns with element types `ARRAY` or `ROW`.
- Array columns with element type `Map`, and with `ARRAY` or `ROW` nested in the key type or the value type.

### Solution 1
Cast the column to `ARRAY(JSON)` before sorting
```
checksum(array_sort(CAST(array_column AS ARRAY(JSON))))
```

### Solution 2
Only cast to `ARRAY(JSON)` as a fallback
```
COALESCE(
    checksum(array_sort(array_column)),
    checksum(array_sort(CAST(array_column AS ARRAY(JSON))))
)
```

Other thoughts?

**Comment by mayankgarg1990** [comment]
```
SELECT ARRAY_SORT(CAST(ARRAY[ROW(100, 0), ROW(2, 1)] AS ARRAY(JSON)));
Query failed: line 1:8: Unexpected parameters (array(json)) for function array_sort. Expected: array_sort(array(E)) E:orderable, array_sort(array(T), function(T,T,integer)) T
SELECT ARRAY_SORT(CAST(ARRAY[ROW(100, 0), ROW(2, 1)] AS ARRAY(JSON)))
```

Is Json orderable?

Do you think we should use the sort method only if the element is a primitive type - number or string?

**Comment by caithagoras** [comment]
@mayankgarg1990 You're right, JSON is not orderable. In that case, I don't have a good solution except for falling back to a regular checksum.
```

**Comment by wenleix** [comment]
> You're right, JSON is not orderable. In that case, I don't have a good solution except for falling back to a regular checksum.

You can use `json_format` to make it to be varchar, which is sortable then :D , i.e. 
```
   array_sort(transform(json_array, x -> json_format(x)))
```

**Comment by caithagoras** [comment]
Fixed
