### ISSUE TITLE
Verifier failed handle floating point columns with sums close to 0

### ISSUE THREAD

**Issue by caithagoras** [prestodb/presto#12704]
In one of the production query, a columns mismatch on a floating point column `f` where `sum(f) = 0` on the production cluster while `sum(f) ~= ±1e-12` on the test cluster. The data contains positive values and their negates which should exactly cancels each other, and the discrepancy results from the order of execution of `sum` aggregation.

It looks like we attempt to handle those cases in which on the control and test sum are exactly 0 and thus relative error is meaningless but the absolute margin we tolerate is basically 0.
https://github.com/prestodb/presto/blob/master/presto-verifier/src/main/java/com/facebook/presto/verifier/checksum/FloatingPointColumnValidator.java#L148-L154

### Solution
We need to introduce some sort of absolute error margin so that we allow verification to pass when
```
difference < absolute_error_margin
```

In addition, we might want to add a checksum column for floating point columns to double-check those cases.
```
sum(abs(f))
```

**Comment by caithagoras** [comment]
cc @mayankgarg1990 @mbasmanova @nezihyigitbasi

**Comment by mayankgarg1990** [comment]
I am on board with the solutions.

**Comment by caithagoras** [comment]
Fixed
