### ISSUE TITLE
split_to_map clarification in documentation

### ISSUE THREAD

**Issue by MichaelChirico** [prestodb/presto#12708]
Just discovered `split_to_map`, excellent for mapping my Spark work back to Presto when needed!

However, as I noted for Spark/Hive:

https://github.com/apache/hive/pull/553

https://github.com/apache/spark/pull/23888

The documentation can lead/has led to some confusion. Hive/Spark's `str_to_map` uses _regular expression_ delimiters, but, IINM, [Presto's implementation uses fixed character matching](https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/operator/scalar/SplitToMapFunction.java#L64):

```
int entryEnd = string.indexOf(entryDelimiter, entryStart);
// ...
int keyEnd = keyValuePair.indexOf(keyValueDelimiter);
```

This is fine, of course -- and in fact, I probably prefer the Presto version -- but I think that given the difference vs. Spark/Hive, it definitely needs to be documented more precisely, esp. since `split_to_map` was explicitly suggested as an homage to `str_to_map` in #2544

**Comment by shixuan-fan** [comment]
@mayankgarg1990 Looks like you recently touched `SplitToMapFunction`, can you help here?

**Comment by MichaelChirico** [comment]
@shixuan-fan see #12709 😄
