### ISSUE TITLE
difference between prestosql & prestodb

### ISSUE THREAD

**Issue by aeoles** [prestodb/presto#12711]
I wanna known the difference between [prestodb](https://prestodb.github.io/) & [prestosql](https://prestosql.io) , i have got confused

**Comment by kokes** [comment]
See https://github.com/prestosql/presto/issues/380

**Comment by nezihyigitbasi** [comment]
@aeoles I have replied to your question in the user group, let us know if you have additional questions.

**Comment by aeoles** [comment]
thanks everyone!!
