### ISSUE TITLE
presto v0.218 ConnectorManager removeConnectorInternal should remove AnalyzeProperty

### ISSUE THREAD

**Issue by yunhuizhu** [prestodb/presto#12722]
presto v0.218 ConnectorManager removeConnectorInternal should remove AnalyzeProperty to use metadataManager.getAnalyzePropertyManager().removeProperties(connectorId);because addConnectorInternal method add AnalyzeProperty。

**Comment by yingsu00** [comment]
This was already fixed by https://github.com/prestodb/presto/pull/12575

**Comment by yingsu00** [comment]
Closing as it's fixed
