### ISSUE TITLE
Suggested UDF: PRECISION_RECALL

### ISSUE THREAD

**Issue by atavory** [prestodb/presto#12732]
Introduction
--------------

In pattern recognition, information retrieval and binary classification, precision (also called positive predictive value) is the fraction of relevant instances among the retrieved instances, while recall (also known as sensitivity) is the fraction of relevant instances that have been retrieved over the total amount of relevant instances. Both precision and recall are therefore based on an understanding and measure of relevance. (From the [Wikipedia entry](https://en.wikipedia.org/wiki/Precision_and_recall).)

Possible Inputs and Outputs
--------------------------------

`precision_recall(bigint, double, boolean) → map(double,double)`
`precision_recall(bigint, double, boolean, double) → map(double,double)`
`precision_recall(bigint, real, boolean) → map(real,real)`
`precision_recall(bigint, real, boolean, double) → map(real,real) `

* The first argument is the number of bins for calculation. The bins are equally-spaced thresholds between 0 and 1.
* The second argument is the predicted outcome.
* The third argument is the actual outcome.
* The optional last argument is an instance weight.

Illegal and Null Values
---------------------------------

* If the number of bins is smaller than 1 or NULL, the result is NULL.
* If a prediction is NULL, it is counted as a wrong prediction.
* If an outcome is NULL, the instance is ignored.
* If an outcome is not between 0 or 1, the result is NULL.
* If the weight is negative, the result is NULL.

Implementation (WIP)
---------------------------

[`PrecisionRecallAggregation.java`](https://github.com/atavory/presto/blob/master/presto-main/src/main/java/com/facebook/presto/operator/aggregation/PrecisionRecallAggregation.java)
[`PrecisionRecallState.java`](https://github.com/atavory/presto/blob/master/presto-main/src/main/java/com/facebook/presto/operator/aggregation/state/PrecisionRecallState.java)

**Comment by wenleix** [comment]
cc @rongrong
