### ISSUE TITLE
Query Stages

### ISSUE THREAD

**Issue by dchida1** [prestodb/presto#12737]
Getting this error when am extracting the data from Presto to tableau.
**"[Teradata][Presto] (1060) Presto Query Error: Query stages (126) exceeded maximum stage limit of 100 (131079)."**
I have seen a solution to add "**query.max-stages**" property and i don't know where to add that. Can anyone please help me.
Thanks in advance

**Comment by nezihyigitbasi** [comment]
This means the query has 126 stages while the Presto coordinator you are hitting is configured to allow a max of 100 stages. The related _session property_ is `query_max_stage_count`, which you can set as a session property, and there is probably a way to do it through the client/driver you are using (please consult the documentation for the client/driver). 

The related _config property_ is `query.max-stage-count` and that can be set on the Presto side, so if you have control over the Presto deployment you can set this config in the `etc/config.properties` file with a high enough value.

**Comment by dchida1** [comment]
Thank You nezi

**Comment by memeplex** [comment]
Hi @nezihyigitbasi , as reported in https://github.com/prestodb/presto/issues/14687 I'm unable to get that property to suppress the warning as one would expect. Do you have any idea why? Thanks.
