### ISSUE TITLE
Transaction expired?

### ISSUE THREAD

**Issue by rmgpinto** [prestodb/presto#12748]
I'm running 3 statements in a transaction:
```
START TRANSACTION
CREATE TABLE table_tmp AS ... (takes 16-20mins)
ALTER TABLE table RENAME TO table_bkp
ALTER TABLE table_tmp RENAMT to table
COMMIT
```

However, when the `COMMIT` is executed, I get the following error:

`com.facebook.presto.spi.PrestoException: Unknown transaction ID: 541b7fbb-6fdc-44f4-87f2-3dd5e57adc33. Possibly expired? Commands ignored until end of transaction block`

Any ideas why?

**Comment by nezihyigitbasi** [comment]
Can you please share the entire stack trace? For that you should start presto-cli with `--debug`.

**Comment by rmgpinto** [comment]
I get this:
`2019-05-01T08:44:31.582Z	INFO	transaction-idle-check	com.facebook.presto.transaction.InMemoryTransactionManager	Removing expired transaction: aede0f63-c010-46a3-9c34-5e2411864e93`

I've searched for this message, and I tweaked `transaction.idle-timeout` to `30m`. All good now, thanks.

**Comment by prakharjain-vogo** [comment]
@rmgpinto  can you tell me where did you add `transaction.idle-timeout` parameter?

**Comment by rmgpinto** [comment]
Hi, I've decided not to use transactions.

**Comment by prakharjain-vogo** [comment]
any idea where to set this parameter, I have tried config.properties, but it doesn't seems to work. 
I am using Presto EMR 5.29.0

And my config.properties looks like this:

coordinator=true
node-scheduler.include-coordinator=false
discovery.uri=http://ip-172-31-36-35.ap-south-1.compute.internal:8889
http-server.threads.max=500
discovery-server.enabled=true
sink.max-buffer-size=1GB
query.max-memory=6452.0MB
query.max-memory-per-node=4256312590B
query.max-total-memory-per-node=5107575108B
query.max-history=40
query.min-expire-age=30m
query.client.timeout=30m
query.stage-count-warning-threshold=100
query.max-stage-count=150
http-server.http.port=8889
http-server.log.path=/var/log/presto/http-request.log
http-server.log.max-size=67108864B
http-server.log.max-history=5
log.max-size=268435456B
log.max-history=5

I am also getting above error when creating a table in hive. Small table with less files in S3 was created but large tables which take more than 1m to scan data is throwing same error.
