### ISSUE TITLE
Join triggers "Nulls fraction should be within [0, 1]" error on Hive/Parquet tables

### ISSUE THREAD

**Issue by talnicolas** [prestodb/presto#12751]
Hi, I am trying to run a simple join between two tables like so:

`SELECT * FROM table_one A JOIN table_two B ON A.USER_KEY=B.USER_KEY ;`

and this always result in:

`Query [...] failed: Nulls fraction should be within [0, 1] or NaN, got: -1.606566858743409E-9`

I am able to run a select * separately successfully on both tables (both relying on Parquet files). Couldn't find anything in existing issues or google, does anybody know where this could come from?

Thanks!

**Comment by rschlussel** [comment]
cc: @arhimondr @highker  

@talnicolas: Thanks for reporting this error! What version of Presto are you running? Can you show us the output of `SHOW STATS` for each of the two tables you're joining?
