### ISSUE TITLE
OrcCorruptionException on big output

### ISSUE THREAD

**Issue by Ohadbasan** [prestodb/presto#12779]
I'm running a pretty heavy (relatively to my cluster) presto query
the presto 

```presto --execute "some query" --output-format CSV --catalog 'hive' --user presto > data.csv```

after several minutes of running I get a crash of 
```OrcCorruptionException(orcDataSourceId, "Could not decompress all input (output buffer too small?)");```

scanning the file in the error with orc-tools shows a valid file.
in addition, I have simplified my query (removed some joins) but made sure that this file is still being scanned. no error appeared the query executed as expected.

Presto CLI 0.210
and Presto-server-0.210

thank you

**Comment by rschlussel** [comment]
What's the simplest query you have that can reproduce this issue and what's the query that doesn't? Feel free to substitute dummy table/column names, but it's hard to figure out what might be causing the difference between the two queries without knowing what each is doing.
