### ISSUE TITLE
Mysql connector doesn't support JSON. 

### ISSUE THREAD

**Issue by raisanjeet07** [prestodb/presto#12806]
In Mysql Serve, One table has datatype as JSON. While trying to import data of that table in another table, getting an error as 
Query 20190514_130215_00010_p4fyq failed: Data truncation: Data too long for column 'attributes' at row 1
.

**Comment by ebyhr** [comment]
This is a known limitation. I have the prototype, so I will submit it later.
```
presto:test> desc mysql.test.test_json;
 Column | Type | Extra | Comment 
--------+------+-------+---------
 c1     | json |       |         
(1 row)

presto:test> select * from mysql.test.test_json;
    c1     
-----------
 {"key":1} 
(1 row)
```
