### ISSUE TITLE
Style check doesn't catch unused imports

### ISSUE THREAD

**Issue by arhimondr** [prestodb/presto#12817]
https://github.com/prestodb/presto/pull/12807/commits/ac537ec18e08272411096abbd696ad13846b29f5

**Comment by rschlussel** [comment]
@arhimondr can you add more description to this issue? I guess the style check didn't catch the particular import for that commit, but for most imports it does, right?

**Comment by arhimondr** [comment]
I haven't checked that. It looks so. It might be specific for static imports of the enum values that are used in the `switch` statement, where import is not required.
