### ISSUE TITLE
Tests failing due to float precision

### ISSUE THREAD

**Issue by jagill** [prestodb/presto#12834]
On master (13e1d0bc30), `mvn clean test -pl :presto-geospatial` is failing for me on three tests.  Two seem to be due to float precision:
```
[ERROR] Failures:
[ERROR]   TestGeoFunctions.testGreatCircleDistance:819->AbstractTestFunctions.assertFunction:96 expected [2886.448973436703] but found [2886.4489734367016]
[ERROR]   TestSphericalGeoFunctions.testDistance:139->assertDistance:151->AbstractTestFunctions.assertFunction:96 expected [2886448.973436703] but found [2886448.9734367016]
```

They are tested with `assertFunction`, which ultimately calls `assertEqual`, which is generally a bad choice for floats.  Do we have a similar function with something like `assertAlmostEqual(..., precision)`?

cc: @tdcmeehan

**Comment by tdcmeehan** [comment]
I don't think there's an overload for floats or decimals which take in a delta, but there definitely should be.

**Comment by rschlussel** [comment]
The statistics assertions use https://github.com/prestodb/presto/blob/3060c65a1812c6c8b0c2ab725b0184dbad67f0ed/presto-tests/src/main/java/com/facebook/presto/tests/statistics/MetricComparisonStrategies.java.  Could be useful for other things too.
