### ISSUE TITLE
Broadcast join cannot be enabled if probe side is a bucketed table

### ISSUE THREAD

**Issue by wenleix** [prestodb/presto#12837]
To reproduce on `HiveQueryRunner`, first set session properties: 

```sql
set session distributed_join=false;
set session join_distribution_type='BROADCAST';
```

The following explain query 
```sql
explain (type distributed) 
select * from tpch_bucketed.orders join tpch.customer on orders.custkey = customer.custkey
```

doesn't use broadcast join:

```
......
 Fragment 2 [SOURCE]
     Output layout: [custkey_0, name, address, nationkey, phone, acctbal, mktsegment, comment_1, $hashvalue_74]
     Output partitioning: hive:buckets=11, hiveTypes=[bigint] [custkey_0]   <----!!!!
     Stage Execution Strategy: UNGROUPED_EXECUTION
     - ScanProject[table = TableHandle{connectorId=hive, connectorHandle=HiveTableHandle{schemaName=tpch, tableName=customer, analyzePartitionValues=O
             Estimates: {rows: 1500 (294.29kB), cpu: 287855.00, memory: 0.00, network: 0.00}/{rows: 1500 (294.29kB), cpu: 589210.00, memory: 0.00, net
             $hashvalue_74 := "combine_hash"(bigint '0', COALESCE("$operator$hash_code"("custkey_0"), 0))
             LAYOUT: tpch.customer
......
```

However, broadcast join can be used if probe side table is non-bucketed:
```sql
explain (type distributed)
 select * from tpch.orders join tpch.customer on orders.custkey = customer.custkey
```

Plan:
```
......
 Fragment 2 [SOURCE]
     Output layout: [custkey_0, name, address, nationkey, phone, acctbal, mktsegment, comment_1, $hashvalue_74]
     Output partitioning: BROADCAST []    <---- !!!!!
     Stage Execution Strategy: UNGROUPED_EXECUTION
     - ScanProject[table = TableHandle{connectorId=hive, connectorHandle=HiveTableHandle{schemaName=tpch, tableName=customer, analyzePartitionValues=O
             Estimates: {rows: 1500 (294.29kB), cpu: 287855.00, memory: 0.00, network: 0.00}/{rows: 1500 (294.29kB), cpu: 589210.00, memory: 0.00, net
             $hashvalue_74 := "combine_hash"(bigint '0', COALESCE("$operator$hash_code"("custkey_0"), 0))
             LAYOUT: tpch.customer
......
```

**Comment by wenleix** [comment]
Ah, actually I remembered... This is a feature, not a bug.

**Comment by rschlussel** [comment]
@wenleix why was this reopened?

**Comment by wenleix** [comment]
@rschlussel : Partitioned exchange is always better without exchange materialization and recoverable grouped execution. However, these two can change the game:

- Partitioned join in the exchange materialization context will introduce another write/read round
- Replicated join spread more data, but don't have to materialize the exchange.

The tradeoff is now interesting :)

**Comment by rschlussel** [comment]
why would it introduce another exchange materialization?  In this context the two tables are already partitioned on the join key, so there is no repartitioning.

**Comment by wenleix** [comment]
@rschlussel : 

So think about `A JOIN B`, where `A` is already partitioned and `B` is small.

Assuming we run the query with exchange materialization enabled, then the exchange over `B` will be materialized (in order to have recoverability) 

However, if we  broadcast `B`, we don't need to materialize `B` to have recoverability :)

**Comment by rschlussel** [comment]
1. if b is small the materialization should be insignificant compared to materialization of A
2. It seems like a hacky solution to the problem of not wanting to materialize b. we happen to have this capability of not materializing for broadcast join, so we force things into that instead of enabling partitioned joins with one much smaller side to only materialize one side. It would be better to have a way to keep b in memory just like for broadcast, but still do a partitioned join.
