### ISSUE TITLE
Presto recurses the root directory of partition

### ISSUE THREAD

**Issue by zhenxiao** [prestodb/presto#1285]
Hi,

Just found that Presto has different behavior with Hive in a case:

if we have:

/table/partition/file1
/table/partition/directory/file2

and the hive metastore points partition to /table/partition

Hive will process only /table/partition/file1

While, Presto will recursively processing all files in any subdirectories, it will process both file1 and file2

The code for this is in Presto's AsyncRecursiveWalker:

if (isDirectory(status)) {
  recursiveWalk(status.getPath(), callback, taskCount, future);
}

Is this an expected behavior? That we would like Presto to recursively processing subdirectories? Any reason why we need AsyncRecursiveWalker?

Having a non-recursive walker Presto will have the same result as Hive:

 if (isDirectory(status)) {
  continue;
}

Thanks,
Zhenxiao

**Comment by chizar** [comment]
Dain, 

Could you please clarify. It was just replaced by non-recurcive behavior?  or it is configurable?

**Comment by dain** [comment]
There is a configuration option `hive.recursive-directories` the default is `false`

**Comment by ThatiK** [comment]
What if i want recursive nature to be enabled. If at all i need to use `hive.recursive-directories=true` ,  in which file do I need to insert this.

**Comment by zhenxiao** [comment]
in call coordinator and workers' 
etc/catalog/hive.properties

**Comment by ThatiK** [comment]
I am new to Presto. I need to set few hive properties at run time of presto query like in .hiverc or as part of query rather than setting it in etc/catalog/hive.properties file. Is there a way in presto in doing so? I am currently using emr-sandbox for presto.

**Comment by zhenxiao** [comment]
In Presto, I think only session properties could be set during runtime (per session), we do not have a session property for hive.recursive-directories yet. You need to config it in etc/catalog/hive.properties, and then restart the Presto cluster to deploy these configs. 

Maybe we could think of adding a new session property for it? What do u think? @dain @electrum

**Comment by ThatiK** [comment]
Cool, thank you for the reply. Can you let me know how I can restart presto cluster alone in aws presto sandbox.

**Comment by zhenxiao** [comment]
oh, little knowledge about the aws sandbox. maybe ask aws guys?

**Comment by vnatrajan** [comment]
sudo restart presto-server   -> invoke on each node

**Comment by ideal-hp** [comment]
Thank you very useful

**Comment by tdevi-cn** [comment]
> In Presto, I think only session properties could be set during runtime (per session), we do not have a session property for hive.recursive-directories yet. You need to config it in etc/catalog/hive.properties, and then restart the Presto cluster to deploy these configs.
> 
> Maybe we could think of adding a new session property for it? What do u think? @dain @electrum

Do we have a session property for this.
