### ISSUE TITLE
Bottle neck issue, when one greedy query runs everybody has to wait.

### ISSUE THREAD

**Issue by victorbartel** [prestodb/presto#12858]
Hi,

After upgrading from Presto 0.187(hosted by EMR 5.11.0) to Presto 0.203 (hosted by EMR 5.11.0 EMR 5.16.0), we have noticed that query management in newer Perso has completely changed. In 0.203 any "greedy" query becomes a true bottle neck for the rest of the users. Because when one slow query takes all resources, all other will line up in the waiting queue until the first query terminates. Presto 0.187 was doing the work in a different manner, the things were lining up only when several greedy queries were running up but none of them had 100% of available runners/workers/memory. 

It may be related to the new way of managing resource groups, which became always enabled (in 0.19*), but it's just an assumption.

Do you know how can we improve the situation and shift back to the previous behavior without having only one blocking query at the time?

Many thanks.

**Comment by shixuan-fan** [comment]
@mayankgarg1990 Is this something you may be able to help with?

**Comment by victorbartel** [comment]
I found the reason [here](https://github.com/prestodb/presto/issues/10383#issuecomment-394102263). Well done. Will introduce resource groups. Many thanks.
