### ISSUE TITLE
ConcurrentHashSet: Guava vs. JDK 8

### ISSUE THREAD

**Issue by wenleix** [prestodb/presto#12864]
Priori to JDK 8, we use Guava's `newConcurrentHashSet`.
JDK 8 provides `ConcurrentHashMap.newKeySet`

Do we want to switch to use JDK's ConcurrentHashSet ?

**Comment by tdcmeehan** [comment]
According to the Javadoc of `newConcurrentHashSet`, the returned set is itself backed by a `ConcurrentHashMap`:

https://google.github.io/guava/releases/16.0/api/docs/com/google/common/collect/Sets.html#newConcurrentHashSet(java.lang.Iterable)

Technically, `newKeySet` returns a `KeySetView`, which allows you to retrieve the map that is backing it, but I don't think it matters.

**Comment by wenleix** [comment]
There are also discussions in Guava community: https://github.com/google/guava/issues/3181 . Also refers to https://stackoverflow.com/questions/32054517/concurrenthashmap-newkeyset-vs-collections-newsetfrommap
