### ISSUE TITLE
Is presto  Support dynamic switching of data sources?

### ISSUE THREAD

**Issue by BBenQi** [prestodb/presto#12877]
I want to dynamic switch data sources by Java，is there any method to do this?

**Comment by ebyhr** [comment]
Hi, I couldn't imagine the detail. Could you please give us the example?

**Comment by BBenQi** [comment]
i wannt to use mysql，Normally i would write
 `connector.name=mysql
connection-url=XXbc:mysql://server1:3306
connection-user=root
connection-password=admin`
to `mysql.properties` 。

but i want to change `connection-url` or `connection-password` in java code

**Comment by ebyhr** [comment]
I see. Currently, such feature isn't supported. As you already know, you can prepare several mysql.properties. Also even if you edit the url and password using Java, you still need to restart Presto cluster.

**Comment by BBenQi** [comment]
thanks very mush!
