### ISSUE TITLE
Plans cannot be printed on unit test failure when they contain original expressions

### ISSUE THREAD

**Issue by rschlussel** [prestodb/presto#12885]
Discovered while writing unit tests for #12773.

Usually when planner tests fail it will print the plan so you can see what went wrong. However, in this case the Filter node contained an OriginalExpressions because PredicatePushDown does not yet support row expressions.  So, instead I got an exception in the RowExpressionFormatter with the message "OriginalExpression cannot appear in a RowExpression tree"

cc: @highker

**Comment by highker** [comment]
Yes, I'm aware of this. I vaguely remember @hellium01 fixed this in a pending PRl @hellium01, could you help confirm?

**Comment by highker** [comment]
Resolved by one of the commits from #12747
