### ISSUE TITLE
add support compression codec zstd

### ISSUE THREAD

**Issue by melin** [prestodb/presto#12893]
add support compression codec zstd

**Comment by ebyhr** [comment]
Hi, in my understanding, `zstd` is already supported. Did you get some error? Which version are you using?

**Comment by melin** [comment]
hive table file format is parquet, using zstd compression encoding,  the prompt not support zstd, in 0.217 version. 

hadoop-apache2  not support zstd
```
 <dependency>
                <groupId>com.facebook.presto.hadoop</groupId>
                <artifactId>hadoop-apache2</artifactId>
                <version>2.7.4-5</version>
            </dependency>
```

**Comment by ebyhr** [comment]
I see. This is just information, but [prestosql/presto](https://github.com/prestosql/presto) uses hadoop 3.2.0-2 and you can access the parquet table compressed by zstd.

**Comment by melin** [comment]
![image](https://user-images.githubusercontent.com/1145830/58936180-c4a2d180-87a1-11e9-9ed8-816756513921.png)

**Comment by mbasmanova** [comment]
@melin Seems like you are running PrestoSQL build. If that's the case, then you should file an issue at https://github.com/prestosql/presto/issues

**Comment by melin** [comment]
> Seems like you are running PrestoSQL build. If that's the case, then you should file an issue at

using prestodb，the patch has been obtained from prestosql and the problem has been resolved

**Comment by dyno** [comment]
the support for zstd in prestodb is only about orc format.
https://github.com/prestodb/presto/blob/master/presto-parquet/src/main/java/com/facebook/presto/parquet/ParquetCompressionUtils.java#L50
https://github.com/trinodb/trino/blob/master/lib/trino-parquet/src/main/java/io/trino/parquet/ParquetCompressionUtils.java#L52 this shows trino support it.
