### ISSUE TITLE
(presto-elaticsearch): handling of object fields

### ISSUE THREAD

**Issue by knikel** [prestodb/presto#12890]
In Elasticsearch objects (*not* nested fields) when stored look as follows:

```json
{
  "settings": {
    "option_a": 1,
    "option_b": true
  }
}
```

The fields within the `settings` object can be selected when querying through specifying `["settings.option_a", "settings.option_b"]` as fields in the source. I cannot figure out how to output such fields within a `presto` table since they always resolve to `NULL`, whether I try `settings.option_a` or `option_a` and `settings` as `jsonPath` (this actually throws an error: `Query XXX failed: For input string: "{optiona_a=1}")`. I can see however that the data gets returned from Elasticsearch in the form of `settings={option_a=1}` objects in the `ElasticsearchRecordCursor` class, but it cannot be unpacked correctly.

What's the correct way of requesting such fields with the current `presto-elasticsearch` implementation? How can I have the value of `settings.option_a` inside the cell?

cc @zhenxiao

**Comment by ebyhr** [comment]
Hi, this is related to nested field issue. https://github.com/prestodb/presto/issues/12642
I could access the object after applying https://github.com/prestodb/presto/issues/12642#issuecomment-482396694. The configuration will be like this
```json
    {
      "name": "settings",
      "type": "row(option_a integer,option_b boolean)",
      "jsonPath": "settings",
      "jsonType": "varchar",
      "ordinalPosition": "1"
    }
```

**Comment by knikel** [comment]
Thanks, @ebyhr 👏.
