### ISSUE TITLE
Problem accessing /v1/statement

### ISSUE THREAD

**Issue by niraj8241** [prestodb/presto#12894]
I am trying to query presto using presto-cli over https. But somehow i am getting the below error:

`update handshake state: finished[20]
upcoming handshake states: server change_cipher_spec[-1]
upcoming handshake states: server finished[20]
main, WRITE: TLSv1.2 Handshake, length = 64
main, READ: TLSv1.2 Change Cipher Spec, length = 1
update handshake state: change_cipher_spec
upcoming handshake states: server finished[20]
main, READ: TLSv1.2 Handshake, length = 64
check handshake state: finished[20]
update handshake state: finished[20]
*** Finished
verify_data:  { 122, 174, 185, 187, 24, 88, 26, 175, 85, 87, 17, 15 }
***
%% Cached client session: [Session-1, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA]
main, setSoTimeout(30000) called
main, WRITE: TLSv1.2 Application Data, length = 624
main, READ: TLSv1.2 Application Data, length = 14112
main, called close()
main, called closeInternal(true)
main, SEND TLSv1.2 ALERT:  warning, description = close_notify
main, WRITE: TLSv1.2 Alert, length = 48
main, called closeSocket(true)
Error running command: Error starting query at https://example.com:8443/v1/statement returned an invalid response: JsonResponse{statusCode=500, statusMessage=Server Error, headers={cache-control=[must-revalidate,no-cache,no-store], connection=[close], content-length=[13900], content-type=[text/html;charset=iso-8859-1]}, hasValue=false} [Error: <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 500 Server Error</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /v1/statement. Reason:
<pre>    Server Error</pre></p><h3>Caused by:</h3><pre>java.lang.RuntimeException: Authentication error
        at com.facebook.presto.server.security.PasswordAuthenticator.authenticate(PasswordAuthenticator.java:71)
        at com.facebook.presto.server.security.AuthenticationFilter.doFilter(AuthenticationFilter.java:90)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
        at io.airlift.http.server.TraceTokenFilter.doFilter(TraceTokenFilter.java:64)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
        at io.airlift.http.server.TimingFilter.doFilter(TimingFilter.java:52)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:674)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)
`

My config.properties

`coordinator=true
node-scheduler.include-coordinator=false
http-server.http.port=8080
discovery-server.enabled=true
discovery.uri=http://xx.xx.xx.xx:8080
query.max-memory=1PB
query.max-memory-per-node=1433MB
query.max-total-memory-per-node=1433MB
http-server.allow-external-connection-on-http=true
http-server.authentication.type=PASSWORD
http-server.https.enabled=true
http-server.https.port=8443
http-server.https.keystore.path=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.201.b09-0.amzn2.x86_64/jre/lib/security/cacerts
http-server.https.keystore.key=xxxxxxxxxxx`

My /etc/password-authenticator.properties
`password-authenticator.name=ldap
ldap.url=ldaps://example.com:636
ldap.user-bind-pattern=uid=${USER},ou=PrestoUsers,ou=Groups,dc=example,dc=com
ldap.user-base-dn=dc=example,dc=com`

I have verified LDAPS using ldapwhoami and ldapsearch and it works fine with the password i provide and it is the same password i am using for presto.

What am I doing wrong here?

Presto Version: Presto CLI 0.208-x.0.10

**Comment by niraj8241** [comment]
Closing the issue as i managed to fix it. The root cause was that i was not using Ldap FQDN in authenticator.properties file.

**Comment by SadikHajar** [comment]
SELECT * FROM pokes;
Error running command: Error starting query at http://localhost:8080/v1/statement returned an invalid response: JsonResponse{statusCode=405, statusMessage=HTTP method POST is not supported by this URL, headers={cache-control=[must-revalidate,no-cache,no-store], content-length=[399], content-type=[text/html;charset=iso-8859-1], date=[Sun, 27 Oct 2024 10:54:50 GMT], server=[Jetty(9.3.z-SNAPSHOT)]}, hasValue=false} [Error: <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 405 HTTP method POST is not supported by this URL</title>
</head>
<body><h2>HTTP ERROR 405</h2>
<p>Problem accessing /v1/statement. Reason:
<pre>    HTTP method POST is not supported by this URL</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.3.z-SNAPSHOT</a><hr/>

</body>
</html>
]
