### ISSUE TITLE
The presto client don't read any records while read a hive table with bucket

### ISSUE THREAD

**Issue by fabricor** [prestodb/presto#12907]
presto 0.220, hive 3.

**Comment by fabricor** [comment]
the ddl is as follows:

+----------------------------------------------------+
|                   createtab_stmt                   |
+----------------------------------------------------+
| CREATE TABLE `ordertest`(                          |
|   `id` int,                                        |
|   `money` double,                                  |
|   `order_name` string,                             |
|   `details` string)                                |
| ROW FORMAT SERDE                                   |
|   'org.apache.hadoop.hive.ql.io.orc.OrcSerde'      |
| STORED AS INPUTFORMAT                              |
|   'org.apache.hadoop.hive.ql.io.orc.OrcInputFormat'  |
| OUTPUTFORMAT                                       |
|   'org.apache.hadoop.hive.ql.io.orc.OrcOutputFormat' |
| LOCATION                                           |
|   'hdfs://hadoop-c:8020/warehouse/tablespace/managed/hive/ordertest' |
| TBLPROPERTIES (                                    |
|   'bucketing_version'='2',                         |
|   'transactional'='true',                          |
|   'transactional_properties'='default',            |
|   'transient_lastDdlTime'='1546049714')            |
+----------------------------------------------------+

**Comment by fabricor** [comment]
the structure of the hdfs file is as follows:

**Comment by fabricor** [comment]
the structures of the hdfs files are as follows:

$ hadoop fs -ls hdfs://hadoop-c:8020/warehouse/tablespace/managed/hive/ordertest
Found 1 items
drwxrwxrwx+  - hive hadoop          0 2018-12-29 10:15 hdfs://hadoop-c:8020/warehouse/tablespace/managed/hive/ordertest/delta_0000001_0000001_0000
$ hadoop fs -ls hdfs://hadoop-c:8020/warehouse/tablespace/managed/hive/ordertest/delta_0000001_0000001_0000
Found 2 items
-rwxrwxrwx+  3 hive hadoop          1 2018-12-29 10:15 hdfs://hadoop-c:8020/warehouse/tablespace/managed/hive/ordertest/delta_0000001_0000001_0000/_orc_acid_version
-rwxrwxrwx+  3 hive hadoop        871 2018-12-29 10:15 hdfs://hadoop-c:8020/warehouse/tablespace/managed/hive/ordertest/delta_0000001_0000001_0000/bucket_00000


and Please refer to the attachments, you can get the contents of these files.


[hdfs file.zip](https://github.com/prestodb/presto/files/3259693/hdfs.file.zip)

**Comment by mbasmanova** [comment]
@fabricor Could you clarify what the issue is? Is it that `SELECT * FROM ordertest` query returns nothing?
