### ISSUE TITLE
Carbondata integration

### ISSUE THREAD

**Issue by dbyad** [prestodb/presto#12913]
Hi,

I was trying to integrate presto with carbondata by following the steps as described in the carbondata official page:
https://carbondata.apache.org/quick-start-guide.html

I am unable to access schemas through carbondata catalog with the below error message:

Query 20190607_131452_00001_qz7gx failed: Access Denied: Cannot show schemas

Attaching the server.log of presto.

The issue arise with presto-0.219 version whereas the same process with carbondata.properties file in etc/catalog & set of JARs generated in carbondata build works fine with presto-0.217 version.

Anyone aware of the issue & has any workaround for this is mot welcome !!
[presto_cd_219.log](https://github.com/prestodb/presto/files/3265995/presto_cd_219.log)

**Comment by ebyhr** [comment]
Hi, unfortunately the connector isn't managed in this repository. It's developed under https://github.com/apache/carbondata/tree/master/integration/presto. You can ask about it in this mailing list user@carbondata.apache.org . I can reproduce it easily, so other people may have the same issue.

**Comment by mbasmanova** [comment]
@dbyad Were you able to resolve this issue following @ebyhr advice? Is there anything left to be resolved in this repo?

**Comment by dbyad** [comment]
Hi,

I am unable to send a mail to the given address - user@carbondata.apache.org.

However, the issue still remains unresolved.

**Comment by mbasmanova** [comment]
@ajantha-bhat Is this something you could help with?

**Comment by mbasmanova** [comment]
@dbyad Have you tried submitting a question to http://apache-carbondata-user-mailing-list.3231.n8.nabble.com/ ?

**Comment by ajantha-bhat** [comment]
@dbyad : Hi, This is related to carbondata-presto integration. you can ask in our carbondata community.

you have to subscribe to mailing list first. find details in https://carbondata.apache.org/

Also currently carbondata supports presto 0.217 version only. Later version support is not yet provided.

**Comment by ajantha-bhat** [comment]
![Screenshot from 2019-07-09 22-00-54](https://user-images.githubusercontent.com/5889404/60906668-4c926480-a295-11e9-85ed-7088451ec384.png)
