### ISSUE TITLE
JDBC shows wrong timestamp

### ISSUE THREAD

**Issue by blcksrx** [prestodb/presto#12922]
Recently I found this issue that presto JDBC shows wrong datetime and timestamp that related to Time Zone while!
Here is the description of this issue:
This is the output of **timedatectl** on one of the nodes:
```
     Local time: Mon 2019-06-10 13:06:27 +0430
  Universal time: Mon 2019-06-10 08:36:27 UTC
        RTC time: Mon 2019-06-10 08:36:27
       Time zone: Asia/Tehran (+0430, +0430)
 Network time on: yes
NTP synchronized: yes
 RTC in local TZ: no
```
And this is the output of **presto-cli** on this node:
```
presto> SELECT CURRENT_TIMESTAMP;
                _col0                
-------------------------------------
 2019-06-10 13:07:16.036 Asia/Tehran 
(1 row)

Query 20190610_083715_00090_926xh, FINISHED, 1 node
Splits: 17 total, 17 done (100.00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

```

But this is the **JDBC** output(I use presto JDBC on Datagrip!):
```
2019-06-10 08:40:42
```
In addtion, this is interesting about this and that is in the output of presto JDBC of this code are same!
```
SELECT CURRENT_TIMESTAMP;
SELECT CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Tehran';
SELECT CURRENT_TIMESTAMP AT TIME ZONE 'UTC';
```

**Comment by ebyhr** [comment]
As far as I checked quickly, it's converted by DataGrip. When I used java code using JDBC, I got the same result as presto cli.

**Comment by blcksrx** [comment]
I tried to changed jvm options to set the default on my local timezone but it doesn't work.

**Comment by blcksrx** [comment]
@JetBrains please cooperate us with this issue.

**Comment by ebyhr** [comment]
This stackoverflow link is related https://stackoverflow.com/questions/53494527/datagrip-presto-jdbc-timezone-displays-incurrect-even-after-setting-duser-time

**Comment by blcksrx** [comment]
I think I should do this, Thanks.
