### ISSUE TITLE
Cast json object to row not working

### ISSUE THREAD

**Issue by radsimu** [prestodb/presto#12949]
https://prestodb.github.io/docs/current/functions/json.html shows the following example for casting json to row:

SELECT CAST(JSON '{"v1":123,"v2":"abc","v3":true}' AS ROW(v1 BIGINT, v2 VARCHAR, v3 BOOLEAN));

it is not working

**Comment by ebyhr** [comment]
Hi, which version are you using (presto-server & presto-cli)? I could get the result correctly with latest version.

**Comment by radsimu** [comment]
It is actually happening in AWS Athena, which uses Presto version 0.172

**Comment by ebyhr** [comment]
Casting JSON to ROW was released in version 0.185, so getting the error looks natural. 
https://prestodb.github.io/docs/current/release/release-0.185.html

**Comment by mbasmanova** [comment]
@radsimu Did @ebyhr answer your question? It looks like Athena is running older version of Presto that doesn't support casting JSON to ROW. Is there anything else that needs to be addressed here? If not, perhaps, close the issue.

**Comment by radsimu** [comment]
Yep, no issue here
