### ISSUE TITLE
Release notes for 0.222

### ISSUE THREAD

**Issue by mayankgarg1990** [prestodb/presto#12945]
## Andrii Rosa          
- [x] all checked
-  05-31 11:47:43    7bd1426548 Fix bug in intermidiated data writes stats collection
-  05-31 11:47:43    effeaa6237 Refactor PlanFragment
-  06-12 08:01:11    eb472088be Hide list of tasks in query details by default
-  06-12 08:01:39    ac732e460b Optimize divideUnsignedLong
-  06-12 08:01:39    d6b7e18030 Fix decimal division
-  06-12 13:21:47    b075d24a04 Produce Hive splittable bucketed splits
-  06-19 07:35:27    1be91cd1ef Increase methods visibility in AbstractTestHiveClient
## James Sun            
- [x] all checked
-  05-31 14:40:37    5e3ca2ca15 Replace airlift/bytecode with presto-bytecode
-  05-31 14:40:37    d21cddb7c4 Remove unused bytecode dependency from presto-tpcds
-  05-31 14:40:37    ffa7155fa1 Bring back presto-bytecode
-  06-02 00:08:22    60bc6916e8 Update properties.rst
-  06-03 10:32:25    c26b36549b Rename hostAddress to host in Elasticsearch connector documentation
-  06-05 18:07:50    2270eac0cc Replace all apiNote with Experimental annotation in SPI
-  06-10 23:29:50    3649386bd6 Rename LogicalRowExpressions::TRUE/FALSE to TRUE/FALSE_CONSTANT
-  06-17 16:17:42    4705a17147 Apply connector-specified optimization in PlanOptimizers
-  06-17 16:17:42    8ca6d09d76 Move PlanNode to SPI
-  06-17 16:17:42    99f65a072b Remove unused newSymbol methods
-  06-17 16:17:42    a7eaec6952 Make PlanVisitor::visitPlan public
-  06-17 16:17:42    cbbeaf5d1f Introduce VariableAllocator
-  06-17 16:17:42    e32ae3aeb2 Introduce ConnectorPlanOptimizer
-  06-17 16:17:42    f5a322150c Remove unused Symbol in PlanBuilder
-  06-18 13:53:29    4cb105dc69 Fix connector session creation in ApplyConnectorOptimization
-  06-18 13:53:29    95b739423b Force ConnectorManager to load all optimizers before PlanOptimizers
-  06-18 20:54:51    c40e7e6236 Remove TODO in TranslateExpressions
-  06-19 23:36:43    8b6591190d Remove unused SymbolsExtractor::extractUniqueVariable
-  06-21 10:54:33    25e4358fe1 Allow configuring the Glue catalog id
## Maria Basmanova      
- [x] all checked
-  06-04 10:40:27    acd5460573 [GeoSpatial] Add xxHash64 operator to Bing Tiles
-  06-05 07:38:27    192de04109 Introduce pushdownFilter SPI
-  06-05 07:38:27    76ea27ef63 Implement pushdownFilter in Hive connector
-  06-14 12:19:22    6c56cf9f0e Add PushdownSubfields optimizer rule
-  06-17 10:51:59    eee67f9ced Reduce visibility of HivePageSource methods
-  06-20 10:51:57    160c5d5610 Remove unused nullVector variables from StreamReaders
-  06-20 10:51:57    fca65f8c80 Remove unused getProgress method from OrcRecordReader
-  06-21 10:33:45    808d05f172 information_schema should not fail for illegal storage format
-  06-21 13:41:30    03518e9873 Convert TupleDomain into executable filter
## Masha Basmanova      
- [x] all checked
-  05-30 07:39:40    f65d4d9d84 prepare for next development iteration - 0.222-SNAPSHOT
## Rebecca Schlussel    
- [x] all checked
-  06-05 05:27:35    0ade68b2a4 Add OptimizerAssert for writing optimizer unit tests
-  06-05 05:27:35    7522570c17 Fix formatting in PredicatePushDown
-  06-05 05:27:35    a805a4421a Minor cleanup of RuleAssert
-  06-05 05:27:35    f7e4f80449 Fix incorrect partitioned join after PredicatePushDown
-  06-06 14:39:11    cbeb31eabc Limit the number of concurrent plan sections
-  06-13 09:23:28    dc7fea2dd8 Add release notes for 0.221
## Rongrong Zhong       
- [x] all checked
-  06-16 16:21:27    548fb438ad Create correct identity translation for PropertyDeriviations
-  06-20 09:07:45    fd7eb40daf Fix type mismatch in AddExchanges.Rewriter.visitUnnest
## Shengpei Zhang       
- [x] all checked
-  06-07 13:50:16    b6db7d149d Avoid using containsAll for tasks in SqlStageExecution
## Shixuan Fan          
- [x] all checked
-  06-06 14:55:08    0b702a16dd Remove use_rewindable_split_source from hive session properties
-  06-06 14:55:08    1f5081ac57 Support recoverable grouped execution planning
-  06-06 14:55:08    36ce7467f6 Static import Iterables#getOnlyElement in SqlQueryScheduler
-  06-06 14:55:08    3c7f6f5305 Support recoverable grouped execution
-  06-06 14:55:08    4f9905e60f Add failedTasks in QueryCompletedEvent
-  06-06 14:55:08    6a00bf2aa2 Support bucket-to-node update in DynamicLifespanScheduler
-  06-06 14:55:08    7b86ee786f Rename TestTableFinisher to TestingTableFinisher
-  06-06 14:55:08    7f5e3dad37 Remove unused field in HiveClientConfig
-  06-06 14:55:08    824ac7eec7 Update task info when task fails
-  06-06 14:55:08    a5ecbb1681 Change commitGranularity to lifespanCommitRequired
-  06-06 14:55:08    ae7116f1b0 Add session for DROP TABLE in testGroupedExecution
-  06-06 14:55:08    cf8e9a47c3 Add onTaskFailed in LifespanScheduler
-  06-17 12:49:27    40e4dd7a5a Support grouped execution for eligible table scans
-  06-21 15:02:48    431137089a Use getLocationService() in AbstractTestHiveClient
## Timothy Meehan       
- [x] all checked
-  06-04 17:58:46    c13b606fb3 Add Experimental annotation in SPI
-  06-07 14:47:08    63d06d44b1 Add function assertion with delta for numeric functions
-  06-07 14:47:08    f9bacf168a Add merge_hll
-  06-13 11:17:37    f9c77c579d Add bitwise shift operations
-  06-14 11:05:55    6dc1e7c506 Add UncheckedBlock
-  06-14 11:05:55    a77f9d6be7 Remove check on assert keyword
-  06-14 11:05:55    aa2c584a4c Add block flattening/memory reuse benchmark
-  06-14 11:05:55    c0fce9445c Add BlockFlattener
## Wenlei Xie           
- [x] all checked
-  05-31 13:56:35    8064bd751f Add totalLifespans to StageExecutionDescriptor
-  05-31 13:56:35    d2759f7595 Show completed and total lifespans on Web UI
-  05-31 14:04:18    55bec7e56c Remove outdated comment in SourcePartitionedScheduler#assignSplits
-  05-31 14:04:18    a006812fdd Minor refactor to SourcePartitionedScheduler
-  06-03 23:44:10    8e0bf9b3dc Make StageScheduler notify all tasks are scheduled
-  06-12 16:09:54    c6b118a63f Fix checkArgument message in AggregationMetadata
-  06-19 17:40:06    94e0be5b80 Remove partitionId from Metadata#commitPartition
-  06-19 17:40:06    e93e87c594 Use Experimental annotation for experimental SPI in Metadata
-  06-20 10:41:43    dc28ac3b8c Avoid binding to hive catalog in TestHiveIntegrationSmokeTest
## Yi He                
- [x] all checked
-  06-06 17:14:22    8fa6ac23e1 Add RowExpressionSymbolInliner
-  06-13 18:55:46    0c0ce7da12 Modify RowExpressionSymbolInliner to RowExpressionVariableInliner
-  06-13 18:55:46    21a35915a5 Replace Expression with RowExpression in Aggregation
-  06-13 18:55:46    27afc0e599 Consolidate conversion from OrderBy expression to OrderingScheme
-  06-13 18:55:46    ee7b43e539 Add back validation of aggregation call in TypeValidator
-  06-14 00:20:45    3715504d22 Fix SymbolToSymbolTranslator
-  06-14 00:20:45    a4db28f9a4 Inline SymbolToSymbolTranslator
-  06-18 13:58:38    122bdb733b Replace Expression in Assignments to RowExpression
-  06-18 13:58:38    27c35db739 Allow type coercion in DependencyChecker
-  06-18 13:58:38    2f4cd759bc Move toVariableReference method into PlannerUtils
-  06-18 13:58:38    3f32b82ab5 Extract ApplyNode::isSupportedSubqueryExpression to utility
-  06-18 13:58:38    57f8a33cc9 Remove unused getOutputSymbols
-  06-18 13:58:38    7bcfa2993b Move identity functions into AssignmentUtils
-  06-18 13:58:38    8d73c5fcf2 Translate row expresion before fragment it in TestCostCalculator
-  06-18 13:58:38    8fb01b585e Catch exception in test unsupported subquery
-  06-18 13:58:38    a93a639eab Remove OriginalExpression before plan assertion
-  06-18 13:58:38    ad7382b444 Remove unused assertPlan
-  06-18 13:58:38    c801fd79fa Fix RowExpressionVerifier cast assertion
-  06-18 16:24:49    184e9f8956 Move out isExpression check from SymbolsExtractor
-  06-18 16:24:49    489aa75e25 Move translateExpressions to local query runner as a generic util
-  06-18 16:24:49    c4da00f586 Add type coercion comments for DependencyChecker
-  06-18 16:24:49    d5baf41210 Minor PlanFragmenter style fixes
## Yuan M               
- [x] all checked
-  06-03 23:23:13    a56ba49c09 override hashcode and equals in FunctionMetadata
-  06-08 10:30:49    a359e14c16 Throw exceptions for unsupported scalar function annotation
-  06-19 17:28:13    6165aeed67 Move ValuesNode to SPI
-  06-19 17:28:13    cacdf22a7c Remove pushdownFilter interface
-  06-19 17:30:52    5c445c7313 Revert "Remove pushdownFilter interface"
-  06-19 17:30:52    5db223d84f Revert "Move ValuesNode to SPI"
## aweisberg            
- [x] all checked
-  05-31 19:36:02    6ad0511b70 Short circuit block creation for null data streams in orc
-  05-31 19:36:02    997e8aa4cd Add benchmark for reading a null data stream
-  06-18 13:01:46    ea90243bd6 Enable tuple domain extraction for subfields
## mayankgarg1990       
- [x] all checked
-  06-04 11:44:48    9e13faf5ec Change jar version to work with branch based release model
## rongrong             
- [x] all checked
-  06-08 16:54:05    39e2244198 Add VariableReferenceExpression to AssignUniqueId
-  06-08 16:54:05    49233872c7 Add VariableReferenceExpression to TableScanNode
-  06-08 16:54:05    4a76160457 Add VariableReferenceExpression to MarkDistinctNode
-  06-10 11:26:11    887094f3c3 Change WindowNode's windowFunctions to use VariableReferenceExpression
-  06-10 11:26:16    34a72391d7 Add getOutputVariables to pass through PlanNodes
-  06-10 11:26:16    3c3c86f57b Change output to VariableReferenceExpression in MetadataDeleteNode
-  06-10 11:26:16    4298b2bb4c Use VariableReferenceExpression in TableFinishNode
-  06-10 11:26:16    6e8b1db83e Change outputSymbol to VariableReferenceExpression in ExplainAnalyzeNode
-  06-10 11:26:16    88b8805883 Add VariableReferenceExpression to RowNumberNode
-  06-10 11:26:16    a8bb2c55f4 Add VariableReferenceExpression to TopNRowNumberNode
-  06-10 11:26:16    b38694322e Add VariableReferenceExpression to ValuesNode
-  06-10 11:26:17    145f963b7d Use VariableReferenceExpression in DeleteNode
-  06-10 11:26:17    1493c139e0 Add VariableReferenceExpression to RemoteSourceNode
-  06-10 11:26:17    250fa70166 Use VariableReferenceExpression in StatisticsWriterNode
-  06-10 11:26:17    92445eeea4 Use VariableReferenceExpression in RelationPlan
-  06-10 11:26:17    ac27b3bf30 Change hash symbol to variable
-  06-10 11:26:17    cf391bbbf0 Add VariableReferenceExpression to OutputNode
-  06-10 11:26:18    8fdb273cfe Change StatisticAggregations to use VariableReferenceExpression
-  06-10 11:26:18    a2b385f963 Change SymbolMapper to take a map of string as constructor parameter
-  06-10 11:26:18    a70b6bdb47 Change SetOperationNode to use VariableReferenceExpression
-  06-10 17:06:54    e7dc62c152 Change AggregationNode.aggregation to use VariableReferenceExpression
-  06-10 17:07:08    189db422cd Change Aggregation.mask to VariableReferenceExpression
-  06-10 17:07:09    deb21187c9 Change EquiJoinClause to use VariableReferenceExpression
-  06-10 17:07:57    f0c1b9223c Change OrderingScheme to use VariableReferenceExpression
-  06-10 17:08:01    c94abe1076 Use VariableReferenceExpression in partitioning and exchanges
-  06-10 17:08:02    266c529fd3 Change correlation to use VariableReferenceExpression
-  06-10 17:08:02    3d05ba9e21 Change rowCount, fragment and tableCommitContext in TableWriterNode to VariableReferenceExpression
-  06-10 17:08:02    47eaa2afe2 Change partitionBy to VariableReferenceExpression
-  06-10 17:08:02    62a13fe405 Change column assignments to use VariableReferenceExpression
-  06-10 17:08:02    7212df9302 Implement getOutputVariables for IndexJoinNode
-  06-10 17:08:02    7ee6759aa0 Change partition symbols to VariableReferenceExpression in SpatialJoinNode
-  06-10 17:08:03    0628799bc4 Change UnnestNode to use VariableReferenceExpression
-  06-10 17:08:03    26bad68207 Change SemiJoinNode to use VariableReferenceExpression
-  06-10 17:08:03    4c090723e8 Change grouping set to use VariableReferenceExpression
-  06-10 17:08:03    64d3becf3b Change TranslationMap to use VariableReferenceExpression
-  06-10 17:08:03    dc140d22df Change Assignments to use VariableReferenceExpression
-  06-10 17:11:44    47a727efbb Change LambdaCaptureDesugaringRewriter to allocate variable
-  06-10 17:11:50    022e7e7576 Change HashComputation to use VariableReferenceExpression
-  06-10 17:11:50    45140a31d5 Change stats to use VariableReferenceExpression
-  06-10 17:11:50    7013517a44 Remove outputSymbols from ValuesNode
-  06-10 17:11:50    d8b8a0d733 Make PlanNode.getOutputVariables abstract
-  06-10 17:11:51    1c8010defc Change ProjectOffPushDownRule to use VariableReferenceExpression
-  06-10 17:11:51    91e5d906ea Change PlanFragment to use VariableReferenceExpression
-  06-10 17:11:51    96592bc900 Change PredicatePushDown to use outputVariables
-  06-10 17:11:51    98848f3d7e Remove outputSymbols from TableScanNode
-  06-10 17:11:51    bb243660e7 Remove outputSymbols from OutputNode
-  06-10 17:11:51    ee95b37ec4 Remove outputSymbols from DeleteNode
-  06-10 17:11:52    2d6e2ce1ee Change ValidateDependenciesChecker to use variables
-  06-10 17:11:52    2fa095d2b1 Change RvalueMatcher to use VariableReferenceExpression
-  06-10 17:11:52    a63aad012a Change PruneUnreferencedOutputs to use variables
-  06-10 17:11:52    a8bf2a97f8 Remove usage of PlanNode.getOutputSymbols
-  06-10 17:11:52    c1ab1f9418 Remove RowNumberNode.getRowNumberSymbol
-  06-10 17:11:52    eb30777383 Change PhysicalOperation to use VariableReferenceExpression
-  06-10 17:11:52    ef9e0957b6 change SortExpressionExtractor to use VariableReferenceExpression
-  06-10 17:11:53    5e1b38d4dc Remove Symbol from PlanNode

**Comment by shixuan-fan** [comment]
```
General
-------
* Add support for recoverable grouped execution. By setting session property ``recoverable_grouped_execution`` to ``true``, the engine run grouped execution in recoverable mode if possible.
* Add grouped execution support for ScanFilterProject-only queries. This is controlled by session property ``grouped_execution_for_eligible_table_scans``.
```

**Comment by wenleix** [comment]
```
General 
--------
* Show completed and total lifespans on Web UI
```

**Comment by wenleix** [comment]
For @arhimondr :

```
General
---------
* Fix incorrect results when dividing certain decimal numbers.

Hive
--------------------
Improve query execution time over bucketed table where each bucket is large. 
```

**Comment by highker** [comment]
```
Bytecode
---------
* Backport bytecode library deleted in version 0.193

Hive
---------
* Allow configuring the Glue catalog ID

SPI
---------
* Add `ConnectorPlanOptimizer` interface to allow connectors to participate query plan optimization (e.g., filter pushdown). The interface exposes part of the query plan to the connector to rewrite. The optimized plan will be accepted by the engine in execution. This releases allows connectors to access filter and table scan. More operations (union, project, aggregation, join, etc) will be available in the coming releases. The usage of `ConnectorPlanOptimizer` is similar to `PlanOptimizer` in presto-main. The interface is marked as experimental for now. It is not ideal to use the inferface in production until it is stable.
* Rename `LogicalRowExpressions::TRUE/FALSE` to `TRUE/FALSE_CONSTANT` to avoid collision with `java.lang.Boolean.TRUE/FALSE`.

**Comment by rschlussel** [comment]
```
General
--------
* Fix query failure for certain join queries with "Equi criteria are empty, so INNER join should not have PARTITIONED distribution type"
* Add config property ``max-concurrent-materializations`` and session property ``max_concurrent_materializations`` to limit the number of plan sections that will run concurrently when using materialized exchanges.
```

**Comment by mbasmanova** [comment]
```
Hive Connector Changes
-------------------------
* Prevent failures for `information_schema` queries when a table has an invalid storage format. (#12973)
```

**Comment by gastonar** [comment]
```
General
--------
* Allow scalar merge of an array of HyperLogLogs (#12870)
* Add function assertions with delta, so numeric functions with error can be tested (#12870)
* Add bitwise shift operations, including arithmetic shift right, logical shift right, and shift left (#12888)
```

**Comment by curcur** [comment]
General
--------
* Override `hashcode` and `equals` in FunctionMetadata so that FunctionMetadata can be compared directly
* Change `checkArgument(false)` to throw unsupported exception for unsupported scalar function annotation
* Revert changes committed by accident

**Comment by hellium01** [comment]
All my changes are refactoring that will not affect user.
