### ISSUE TITLE
Where is source code for com.facebook.presto.teradata.functions.DateFormat class?

### ISSUE THREAD

**Issue by loversInJapan** [prestodb/presto#12970]
I pulled the latest version today and compile and this error occurs:Error:(18, 46) java: cannot find symbol   symbol:   class DateFormat   location: package com.facebook.presto.teradata.functions.

**Comment by loversInJapan** [comment]
@electrum sorry to bother, would you please checkout this issue, it's so obvious. Or is there any mistake that I made?

**Comment by mbasmanova** [comment]
@loversInJapan Which version are you using? Could you be using a version of PrestoSQL, in which case, try reporting an issue in https://github.com/prestosql/presto/issues/

**Comment by electrum** [comment]
@loversInJapan Please join me on the community Slack and I can help you there (I'm `david` on Slack): https://prestosql.io/community.html

**Comment by loversInJapan** [comment]
> @loversInJapan Which version are you using? Could you be using a version of PrestoSQL, in which case, try reporting an issue in https://github.com/prestosql/presto/issues/

I pulled the master branch. And I checkout to the release-0.211 branch, these is also missed the class.

**Comment by mbasmanova** [comment]
@loversInJapan I can compile latest version without any errors. Travis also seems to be able to compile and run tests successfully. Are you getting a compile time error? How do you compile? `mvn install -DskipTests -T1C` or something else? Could you share the error message in full? Which file fails to compile? Do you need to do `mvn clean` first?

**Comment by loversInJapan** [comment]
well, I can compile and run it in Intellij IDEA. The com.facebook.presto.teradata.functions. DateFormat.java is still missing, but the com.facebook.presto.teradata.functions.DateFormat.class generated in target folder. I don't know how to fix it or is it suppose to be like this?

**Comment by mbasmanova** [comment]
@loversInJapan `DateFormat.java` is auto-generated from `DateFormat.g4`. Once you run the `mvn install` command you should see `DateFormat.java` in `./presto-teradata-functions/target/generated-sources/antlr4/com/facebook/presto/teradata/functions/` folder.

```
mbasmanova-mbp1:presto mbasmanova$ find . -name DateFormat.java
./presto-teradata-functions/target/generated-sources/antlr4/com/facebook/presto/teradata/functions/DateFormat.java
mbasmanova-mbp1:presto mbasmanova$ head ./presto-teradata-functions/target/generated-sources/antlr4/com/facebook/presto/teradata/functions/DateFormat.java
// Generated from com/facebook/presto/teradata/functions/DateFormat.g4 by ANTLR 4.7.1
package com.facebook.presto.teradata.functions;
import org.antlr.v4.runtime.Lexer;
import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.Token;
import org.antlr.v4.runtime.TokenStream;
import org.antlr.v4.runtime.*;
```
