### ISSUE TITLE
Having clause in correlated subquery cannot reference outer query attribute

### ISSUE THREAD

**Issue by bgedik** [prestodb/presto#12972]
Consider the following query:

    SELECT * FROM customer WHERE EXISTS (
        SELECT COUNT(*) FROM transaction 
        GROUP BY transaction.customer_id 
        HAVING transaction.customer_id = customer.id);

This is giving the following error: 
``
Query 20190619_162521_08871_c8pm8 failed: line 1:172: '(transaction_sequence.customer_id = customer_sequence.id)' must be an aggregate expression or appear in GROUP BY clause
``

This example works for MariaDB/MySQL, PostgreSQL, MS SQL Server, and Oracle 12c. It is surprising that it fails for Presto.

The error is due to `customer_sequence.id`, which is an attribute referenced from the outer query. If I replace it with a constant, it works. Also, if I move the filter to the WHERE clause, it also works:

    SELECT * FROM customer WHERE EXISTS (
        SELECT COUNT(*) FROM transaction
        WHERE transaction.customer_id = customer.id
        GROUP BY transaction.customer_id;

So it seems like there is a problem in handling of outer query attribute references in the having clause.

**Comment by mbasmanova** [comment]
@bgedik Would you like to debug this and propose a fix?

**Comment by bgedik** [comment]
I would have liked to spend time on it, but unfortunately it is not possible at this time. This issue is not blocking me (I have a workaround), but I wanted to report it for the benefit of the community.

I am sure the issue can be fixed easily by someone who is knowledgeable about the Presto code base. Based on a quick look, it seems to me that this is a problem with the validation that is being done in `AggregationAnalyzer.java`.

**Comment by mbasmanova** [comment]
@bgedik Thanks for reporting.

**Comment by pengbomuzzy** [comment]
#14270
