### ISSUE TITLE
limit less than system, then presto cluster can not work 

### ISSUE THREAD

**Issue by Svti** [prestodb/presto#12971]
TOO_MANY_STAGES	Number of stages in the query (71) exceeds the soft limit (50). If the query contains multiple DISTINCTs, please set the 'use_mark_distinct' session property to false. If the query contains multiple CTEs that are referenced more than once, please create temporary table(s) for one or more of the CTEs.

**Comment by mbasmanova** [comment]
@Svti Do you have a question or reporting a bug?

**Comment by Svti** [comment]
> @Svti Do you have a question or reporting a bug?

 it is a bug , when it happened , the cluster does not work

**Comment by Svti** [comment]
@mbasmanova it is a bug , when it happened , the cluster does not work

**Comment by mbasmanova** [comment]
@Svti John, do you have any additional context? Which query triggers this error? What do you mean by `cluster doesn't work`? Have you tried the suggestion in the error message?

**Comment by Svti** [comment]
@mbasmanova  i don't modify the linux system default limit before i deploy the presto ,then i do a big query , the query plan will read 1 million rows , then  the query task show a yellow triangle on the presto gui. then the query failed . when it happend , all of my other queries show failed . when i do  another new query , it show failed also .

version: 0.221
jdk:1.8.0_211

**Comment by Svti** [comment]
@mbasmanova  i  tried the suggestion in the error message , is it ok. but  when  i don't modify the linux system default limit before i deploy the presto  , it should not crash ？  i have many query task on the presto ,  all of query will be failed .
