### ISSUE TITLE
presto hive

### ISSUE THREAD

**Issue by Zoomtoo** [prestodb/presto#12981]
版本：presto-0.221
问题：我在集群部署了presto并且配置了Hive连接器，我通过命令行终端可以连接Hive,并且可以查看到Hive中的表信息，但无法查看表中的数据（查看表数据为空）。
详细问题，请看下图：
hive连接器配置
connector.name=hive-hadoop2
hive.metastore.uri=thrift://yunhe.bigdata-master.yhwx:9083
hive.config.resources=/home/yhwx/presto-server-0.221/etc/core-site.xml,/home/yhwx/presto-server-0.221/etc/hdfs-site.xml

presto查询情况：
![image](https://user-images.githubusercontent.com/33661840/59826340-b4295400-9368-11e9-80a3-2cfb0e34d307.png)
hive中的查询结果：

![image](https://user-images.githubusercontent.com/33661840/59826489-ff436700-9368-11e9-8ce9-8dce9178b888.png)

请问是哪里出了问题？

**Comment by highker** [comment]
# Here is the result from Google translate just in case:

Version: presto-0.221
Problem: I deployed presto in the cluster and configured the Hive connector. I can connect to the Hive through the command line terminal, and can view the table information in the Hive, but cannot view the data in the table (the table data is empty).
For detailed questions, please see the picture below:
Hive connector configuration
Connector.name=hive-hadoop2
Hive.metastore.uri=thrift://yunhe.bigdata-master.yhwx:9083
Hive.config.resources=/home/yhwx/presto-server-0.221/etc/core-site.xml, /home/yhwx/presto-server-0.221/etc/hdfs-site.xml

Presto query situation:
![image](https://user-images.githubusercontent.com/33661840/59826340-b4295400-9368-11e9-80a3-2cfb0e34d307.png)
The query result in hive:

![image](https://user-images.githubusercontent.com/33661840/59826489-ff436700-9368-11e9-8ce9-8dce9178b888.png)

Is there a problem?

**Comment by highker** [comment]
@Zoomtoo, could you do more debugging and make sure there is no config issue? For example, could you create a table, say `test3` using presto-cli with some values in it (`CREATE TABLE ... VALUES ...`)? Then check both presto-cli and hive-cli can see the new table and the data. 

Let use know the detail steps and results based on the above approach.

**Comment by Zoomtoo** [comment]
> @Zoomtoo, could you do more debugging and make sure there is no config issue? For example, could you create a table, say `test3` using presto-cli with some values in it (`CREATE TABLE ... VALUES ...`)? Then check both presto-cli and hive-cli can see the new table and the data.
> 
> Let use know the detail steps and results based on the above approach.

I now use presto and hive to build the table, and then there is a situation, they can only check the table created by themselves, but can not check the table created by the other party, presto check the hive table is still the result is empty, hive check presto built Table, direct error, the error is as follows:
![image](https://user-images.githubusercontent.com/33661840/59837158-55bba000-937f-11e9-9166-c1c7ab13cb24.png)
![image](https://user-images.githubusercontent.com/33661840/59837090-3cb2ef00-937f-11e9-9447-f79649a23750.png)

**Comment by rongrong** [comment]
What's the `CREATE TABLE` statement? Can you also run `SHOW CREATE TABLE` from both sides? Seems like Presto and Hive have different ideas about the table metadata.

**Comment by Zoomtoo** [comment]
> What's the `CREATE TABLE` statement? Can you also run `SHOW CREATE TABLE` from both sides? Seems like Presto and Hive have different ideas about the table metadata.

Tt2 is the table I created with presto, then I execute "show crate table tt2" with presto and hive respectively, with the following output:
![image](https://user-images.githubusercontent.com/33661840/59911427-7569cb80-9446-11e9-82f1-d12ad9546b16.png)

![image](https://user-images.githubusercontent.com/33661840/59911469-8fa3a980-9446-11e9-9f8f-ffa3500e3355.png)

**Comment by VlasovArtem** [comment]
I faced the same issue, and I think it is related to the properties for enabling transactions in hive-site.xml. List of the properties that cause the problem:

- hive.txn.manager=org.apache.hadoop.hive.ql.lockmgr.DbTxnManager
- hive.support.concurrency=true
- hive.enforce.bucketing=true
- hive.exec.dynamic.partition.mode=nonstrict
- hive.compactor.initiator.on=true
- hive.compactor.worker.threads=1

Example of CREATE TABLE query in hive 
`CREATE TABLE test(test int) STORED AS ORC TBLPROPERTIES('transactional'='true','transactional_properties'='default');`

Also, I found out that the structure of the folders on HDFS are different:
ORC table created without properties above 
![Screenshot 2019-07-11 at 15 34 05](https://user-images.githubusercontent.com/3629440/61051394-93956c80-a3f1-11e9-96d3-7784f5bd8db8.png)
ORC table created with properties above
![Screenshot 2019-07-11 at 15 34 28](https://user-images.githubusercontent.com/3629440/61051435-a7d96980-a3f1-11e9-925a-6492958efc37.png)

Unfortunately, I was not able to track down the code line where it happens.
