### ISSUE TITLE
feature req - resource-groups for ldap group rather than username

### ISSUE THREAD

**Issue by tooptoop4** [prestodb/presto#12986]
https://prestodb.github.io/docs/current/admin/resource-groups.html has example of  "user": "bob",

Ideally could avoid hardcoding individual usernames and instead reference "ldapGroup": "CN=My_cn_Name,OU=myou1,OU=myou2,DC=mysubdom1,DC=mysubdom2,DC=mydomain,DC=com"

**Comment by shixuan-fan** [comment]
The requested feature seems like a principal in Hive connector.

@mayankgarg1990 Not sure if you are the best person to answer this. Feel free to redirect.

**Comment by rongrong** [comment]
I think "User" here is just the user field from http header so you can pass in ldap group as users if that serves you better. Another way to have more flexible resource group configuration is to use `clientTags`, which is a set of strings client can pass to server to use for identification.

**Comment by tooptoop4** [comment]
@rongrong to clarify with example: userMary, userBob, UserSam are part of ldap group 'LegalTeam'. userTim, userAmy, UserJane are part of ldap group 'AccountingTeam'. I want resourceGroupA for all users in LegalTeam and resourceGroupB for all users in AccountingTeam. But I want to specify 'LegalTeam'/'AccountingTeam' ldap groups in resourceGroup file, I don't want to hardcode the 6 usernames in the resourceGroup file, and I want any new user that joins the AccountingTeam (ie next month) to automatically be allocated to resourceGroupB. Note: all 6 users connect to Presto via JDBC with their own ldap username/password and Presto allows them to connect because both AccountingTeam/LegalTeam are in ldap.group-auth-pattern. So i guess this is an extension of that 'user to ldap group' lookup that i assume happens with ldap.group-auth-pattern, but this time not just for connecting to presto but for allocation to resourceGroups.
