### ISSUE TITLE
Add a faster HyperLogLog merge aggregation function

### ISSUE THREAD

**Issue by gyson** [prestodb/presto#12988]
The built-in `merge(HyperLogLog) -> HyperLogLog` is slower than our expectation and becomes bottleneck for some of our interactive queries. 

Then we looked into its implementation and applied several optimisation to make it faster, which resulted a new merge function: `merge_p4(HyperLogLog) -> P4HyperLogLog`. Note that merged result is `P4HyperLogLog` instead of `HyperLogLog`.

The new merge function is more than 10 times faster than built-in one and consumes less memory as well. We have made this new merge function available as a UDF at [sortable/presto-hyperloglog][1]. The repo explains why new merge function is faster and provides a benchmark result to show how fast it could be.

Would Presto be interested to add this new merge function into built-in hyperloglog function family?

[1]: https://github.com/sortable/presto-hyperloglog

**Comment by shixuan-fan** [comment]
@tdcmeehan : Assigned to you since you worked with @gastonar recently on HyperLogLog.

**Comment by tdcmeehan** [comment]
This is a really interesting function, but it seems very specific to a particular use case.  Presto already supports the ability to add custom functions via a plugin as you have done, and I think this is too specific to be added to Presto generally.  In the future, when we add namespaces for functions, it may be a good candidate for a hypothetical `datasketches` namespace, but in the meantime we only have a single global namespace, and we need to be judicious for the functions we add.

Did you investigate serializing these HLLs as `P4HyperLogLog`s?  If the bulk of the performance improvements come from avoiding the need to switch from sparse to dense, then simply casting to `P4HyperLogLog` when you serialize means that when you merge, you're already only taking in `P4HyperLogLog`s.  If you can bear the increased space requirements, it may be a good way to go here.

CC: @rongrong  @wenleix

**Comment by gyson** [comment]
Thanks for you suggestion. Serializing these HLLs as `P4HyperLogLog` would take too much space because majority of our HLLs are currently in sparse format.

We would continue to use it via UDF plugin.
