### ISSUE TITLE
Elasticsearch Connector does not support username and password

### ISSUE THREAD

**Issue by psyking841** [prestodb/presto#13001]
Our ES cluster is hosted in the cloud and requires username and password to connect. I typically use URL of form "https://username:password@es_host:1234" to connect. I read the doc but I don't see how to pass in the username and password to the table definition json. Do I miss anything in the doc? Or it is just the current version of Presto ES connector does not support username and password connection.

**Comment by yingsu00** [comment]
@zhenxiao will you be able to answer? Thanks!

**Comment by zhenxiao** [comment]
sorry for the late reply. Did not try username and password in Presto ES connector before
@TempleZhou do you have any hints?

**Comment by psyking841** [comment]
So, I don't think I have missed anything, it is just the "host" field in table definition does not support HTTP authentication in above form. My current workaround is to setup a proxy, and have the Presto server talk to the proxy what appends "username" and "password" to the HTTP Authentication header.

**Comment by zhenxiao** [comment]
get it. nice workaround. We could either file a task to support it, or maybe add this workaround in the doc?

**Comment by psyking841** [comment]
@zhenxiao Thanks for your comments. A little bit digging into the issue on my side and I realized the cloud ES service we are using does not support port 9300, the RPC port (Maybe that is the reason our cloud provider has the authentication header?), which is used by Presto ES plugin. Actually it does take me a while to figure out Presto only does not use port 9200, the RESTful API port, so I DO recommend to add documentation for ES plugin for that Presto only talks to the RPC port(i.e. 9300 by default).

Again, that being said, even I setup the proxy, since the cloud ES service does not support port 9300 I can't do anything unless Presto also support the REST api port. Therefore, I might just close this ticket.

**Comment by zhenxiao** [comment]
Hi @psyking841 to improve parallelism and execution efficiency, Presto Elasticsearch Connector bypass Elasticsearch REST api, directly talking to Elasticsearch via Java api (we do not want to scan all data via one single Presto split, we'd like to parallel read Elasticsearch shards from different search nodes, which REST api does not expose). Do you think it is helpful to add special note for the port number in Elasticsearch Connector documentation?

**Comment by psyking841** [comment]
@zhenxiao 
Yes, I think letting people know Presto ES plugin only works with Java API is definitely helpful. Because ES service from some cloud provider (at least that I am using) does not support Java API so I would just give up using their ES service...

**Comment by psyking841** [comment]
I am closing this ticket, because I have decided to go for a private cluster that does not require username password in the URL header.
