### ISSUE TITLE
Unrecognized VM option 'ExitOnOutOfMemoryError'

### ISSUE THREAD

**Issue by mohsen74** [prestodb/presto#13011]
I try to start presto 0.221 with 'bin/launch run' but when I try it I get 

> Unrecognized VM option 'ExitOnOutOfMemoryError'
   Did you mean 'OnOutOfMemoryError=<value>'?
   Error: Could not create the Java Virtual Machine.
   Error: A fatal exception has occurred. Program will exit.

my jvm.config file is like this:
`-server
-Xmx2G
-XX:-UseBiasedLocking
-XX:+UseG1GC
-XX:G1HeapRegionSize=32M
-XX:+ExitOnOutOfMemoryError
-XX:+ExplicitGCInvokesConcurrent
-XX:+UseGCOverheadLimit
-XX:+HeapDumpOnOutOfMemoryError
-XX:ReservedCodeCacheSize=512M
-Djdk.attach.allowAttachSelf=true
-Djdk.nio.maxCachedBufferSize=2000000
`
and my java version is :
openjdk version "1.8.0_03-Ubuntu"
OpenJDK Runtime Environment (build 1.8.0_03-Ubuntu-8u77-b03-3ubuntu3-b03)
OpenJDK 64-Bit Server VM (build 25.03-b03, mixed mode)

**Comment by yingsu00** [comment]
Hi @mohsen74 Presto requires Java 8 Update 151 or higher (8u151+), 64-bit. Could you try to upgrade it and try again?
