### ISSUE TITLE
PartitionedOutputOperator Optimizations

### ISSUE THREAD

**Issue by yingsu00** [prestodb/presto#13015]
PartitionedOutputOperator takes about 10% of the total CPU of all Facebook warehouse workloads. This issue discusses  the performance improvement on this operator. We first introduces how this operator works currently, then we discuss the design of the new implementation. 

# Background

Currently the PartitionedOutputOperator works as follows:

1. Building step: Each destination partition has a PageBuilder. When a page comes in, the destination of each row is calculated using the XxHash64 on the partitioning columns. The rows are appended to each destination to the PageBuilder. 

2. Serialization step: If any of the  PageBuilder's size is larger than the defined max page size, it will be split into several pages that fit into the limit, then each of these pages will be serialized to a SerializedPage, which then will be enqueued to the OutputBuffer.

There are at least two memory copies, one in the building step, then another one in the Serialization step. The building step can be shown as the following pseudocode:

```javascript
for (int position = 0; position < page.getPositionCount(); position++) {
    int partition = partitionFunction.getPartition(partitionFunctionArgs, position);
    for (int channel = 0; channel < sourceTypes.size(); channel++) {
        Type type = sourceTypes.get(channel);
        type.appendTo(page.getBlock(channel), position, pageBuilders[partition].getBlockBuilder(channel));
    }
}
```
The code processes the data in a row-based fashion, not fully utilizing the JVM’s capability to generate CPU friendly assembly code, which usually requires processing the data in columnar batch mode in tight loops. It’s also using type.appendTo() which is virtual interface method, and going over the same row column by column would usually be megamorphic calls, and thus incurs the virtual function dispatch cost.  GC wise, the pageBuilder produces mid-long lived garbage, because it takes many rounds (incoming pages) to reach the target size (1MB), and then this memory is discarded after copying to the SerializedPage.  Further more, the PageBuilder starts with very small number of entries and it will take quite a few iterations to grow to a stable size, and during this period it needs to grow and copy the data multiple times. All these increases the GC pressure.

The building step is quite CPU expensive. The CPU profile for the QoN query shows that the writing to the BlockBuilders is one of the top costly functions. In the following profile, appendRow, writeLong, getLong are all from it.

```
ns percent samples top
---------- ------- ------- ---
40640000000 31.65% 4064 zError
8800000000 6.85% 880 _platform_memmove$VARIANT$Haswell
6240000000 4.86% 624 read
4480000000 3.49% 448 com.facebook.presto.orc.reader.DoubleStreamReader.scan
3440000000 2.68% 344 com.facebook.presto.operator.PartitionedOutputOperator$PagePartitioner.appendRow
3150000000 2.45% 315 com.facebook.presto.spi.block.LongArrayBlockBuilder.writeLong
2910000000 2.27% 291 com.facebook.presto.spi.block.LongArrayBlock.getLong
2900000000 2.26% 290 io.airlift.slice.BasicSliceInput.available
2460000000 1.92% 246 __psynch_cvwait
1850000000 1.44% 185 [unknown_Java]
1660000000 1.29% 166 inflateCodesUsed
1650000000 1.28% 165 com.facebook.presto.spi.type.AbstractLongType.appendTo
1470000000 1.14% 147 SpinPause
1310000000 1.02% 131 com.facebook.presto.orc.QualifyingSet.getEnd
1290000000 1.00% 129 CollectedHeap::array_allocate(KlassHandle, int, int, Thread*)
1280000000 1.00% 128 com.facebook.presto.spi.type.DoubleType.appendTo
1130000000 0.88% 113 com.facebook.presto.orc.reader.DoubleStreamReader.ensureValuesCapacity
1130000000 0.88% 113 com.facebook.presto.operator.HashGenerator.getPartition
880000000 0.69% 88 com.facebook.presto.spi.block.LongArrayBlockBuilder.closeEntry
830000000 0.65% 83 com.facebook.presto.spi.block.LongArrayBlockEncoding.readBlock
820000000 0.64% 82 com.facebook.presto.spi.Page.getBlock
```

In the flushing step, the content of the built pages is copied to the final SerializedPage. This is not a simple memory copy. It goes through the writeBlock() function in the BlockEncodings, which would call sliceOutput.writeXXX() for every value. The sliceOutput is DynamicSliceOutput, which checks the capacity of the slice for each value being copied. This is capacity check is not free (JMH results shown later). This is unnecessary, because the capacity check only needs to be done once per loop because we already know the target size.

# Design

The proposed idea is to avoid the building step, and directly copy the input page data into a set of buffers that conforms to the SerializedPage format.  When the target size is reached, we can do a simple memory copy to stitch these buffers to the final Serialized Page. The buffers maintained by the operator live throughout the Driver’s lifespan. We may need to grow these buffers from an initial size, this can be done by adding disjoint fixed size buffers to previous ones, to avoid repeating memory allocations and copies.

The steps of the proposed repartitioning operation are as follows:

```
For each incoming page
    Populate the top level row numbers for each destination partition
    Decode the blocks by peeling off the Dictionary or RLE wrappings
        For each partition 
            poplulate nested level row numbers for nested blocks like ArrayBlock
            calculate row sizes
            calculate how many rows can fit the buffers before reaching the limit. This is based on the result of step 1 and 2.
            Append the rows to the buffers block by block
            If the size limit is reached (e.g. 1MB for a destination), flush the buffer for this partition.
```

## Block Encoding Buffers

For different kinds of blocks, the encoding format is similar. For example, a LongArrayBlock would be serialized to the following format:

* positionCount (4 bytes)
* hasNull? (1 byte)
* null values if any (the smallest bytes that holds positionCount bits)
* non-null values (8 * positionCount bytes)

An ArrayBlock is written recursively with the raw block coming first:

* The serialized raw block (n bytes)
* positionCount (4 bytes)
* offsets (4 * (positionCount + 1) bytes)
* hasNull? (1 byte)
* null values if any (the smallest bytes that holds positionCount bits)

Other kind of blocks has similar structures. Because we don’t know how many incoming pages there will be, we need to maintain separate buffers for each of these entities and grow them if necessary. These buffers will be managed by a BlockEncodingBuffers object. For example, LongArrayBlockEncodingBuffers has a buffer for nulls and a buffer for long values. The object of this class has analogous structure with the blocks. E.g. the ArrayBlockEncodingBuffers would contain a nested BlockEncodingBuffers of the raw element type, in addition to its null and offsets buffers. For each destination partition and column combination, we create a BlockEncodingBuffers object. 

These buffers are expandable. This is because we cannot pre-determine the length of each buffer for each column. The current implementation will allocate it with an initial size and grow it as necessary by allocating a larger size and do array copies. In the future, we will maintain a buffer pool of fixed size buffers in each PartitionedOutputOperator. Whenever a block runs out of space, we request another buffer from the buffer pool and link it to the end of the current buffer. This way there is no memory copy and extra allocation required. The buffers would be released to the buffer pool whenever a flush happens. When flush happens, the state of the buffers is also reset. Because each SerializedPage has limited size (e.g. 1MB), the buffers in the buffer pool would gradually grow to this size and remain at the same level during the lifetime of the operator.

## The fomat of the buffers

When writing into a buffer, there’re a few choices:

* Raw byte array
* SliceOutput in Airlift
    * BasicSliceOutput
    * DynamicSliceOutput
* Custom SliceOutput that wraps the raw byte array

To compare the performance of these buffer formats, I created a set of JMH benchmarks that simulate the PartitionedOutputBehavior. The benchmark reads data at designated positions and copy them into the buffer in tight loops. For all three options, enough initial size was allocated to avoid memory growth. The following table shows the SliceOutput are 2x slower than raw byte[] for no null cases, and over 3x slower for with nulls cases.

Contains nulls?   | FALSE | FALSE | FALSE | TRUE | TRUE | TRUE
-----------------|-------|--------|--------|------|-------|-------
Column count | 1 | 2 | 4 | 1 | 2 |4
copyLongPagesToByteArrayBuffer |	80 |	143 |	309 |	95 |	200 |	440
copyLongPagesToBasicSliceOutput |	128 |	277 |	673 |	332 |	682 |	1,480
copyLongPagesToDynamicSliceOutput |131 |	292 |	891 |	348 |	703 |	1,503

Let’s first look at the case when there’re no nulls. By collecting CPU profiles, we found the differences mainly come from

1. **slice**.setLong() calls checkIndexLength() and this part takes about 20% of the BasicSliceOutput.writeLong(). checkIndexLength() results in 3 comparisons and jumps for each value added to the slice. Again this can be avoided if we know the number of values to be added in advance.
2. The perfasm result shows the access of the slice field takes 25% of total CPU. The reason behind it is unknown yet, but it seems to match with the aync-profiler result.

Now let’s look at the case when there’re nulls. We’d like first to explain a JVM optimization. Looking at the following code:

```
for (int j = 0; j < positionCount; j++) {
    int position = positions[j];
    long longValue = block.getLong(positions[j]);
    ByteArrayUtils.setLong(longValueBuffer, longBufferIndex, longValue);
    if (!block.isNull(position)) {
           longBufferIndex += ARRAY_LONG_INDEX_SCALE;
        } 
    }
```

The block.isNull block can be optimized to a *conditional move (cmovne instruction)*. Branching and jumping are avoided, and code can be compiled into a tight loop and unrolled. This optimization does not work on the SliceOutput in the following way. This is because the writeLong() function contains complex capacity checking logic and is hard to be optimized away. The performance difference is about 3x, with and without this JVM optimization.

```
for (int j = 0; j < positionCount; j++) {
    int position = positions[j];
    long value = block.getLong(position);
    sliceOutput.writeLong(value);
    if (!block.isNull(position)) {
        sliceOutput.writeLong(value);
    }
}
```

So we decided to directly manage the byte[] as the buffers in BlockEncodingBuffers objects.

## Decoding the Blocks

For a given column, the blocks could be plain block like VariableWidthBlock, or a DictionaryBlock of VariableWidthBlock, or a RunLengthEncodedBlock of VariableWidthBlock. The blocks coming in could alternating from these formats. We need to peel off the Dictionary or RLE wrapper and create the BlockEncodingBuffers based on the underlying plain block only. This is done through the BlockFlattener.

At the same time, we need to acquire the ColumnarArray object for ArrayBlock, ColumnarMap for MapBlock, and ColumnarRow for RowBlock. Through the ColumnarXXX objects we expose the nested raw blocks and offsets, which is necessary because the Block interface does not expose these internal states. But they are required by the PartitionedOutputOperator in presto-main package. This way we don’t have to modify the SPI Block interface.

The flattening and ToColumnarXXX process is done once per incoming block, not per batch within each block. This is because these processes are quite expensive and we don’t want to repeat it for every batch. The results of the decoding will be kept in the tree structure and fed to the BlockEncodingBuffers in a recursive manner. The mapping information in DictionaryBlock or RLE is used while populating the row numbers for nested level of Blocks.

## Calculating the row sizes

There're two ways for adding the values to buffers. One way is to calculate the row sizes, and add to the buffer only for the rows that fit. The other way is to check if the buffers need to be flushed for every row it adds. We chose the first method because 1)  the second way requires us to do a size check for every value added inside of the loop. 2)  calculating row sizes can be done fairly fast. For fixed length types this can be simplified to a simple division. If all columns are fixed length, we can get the size really fast.

We pass in an int[] sizesInBytes to this function to avoid memory allocation in each nested level. For nested level, accumulateRowSizes() takes an offsets array for the top level rows and accumulate the sizes for the nested rows.

## Computation of destination partitions

There’re a couple of future optimizations we can try:

1. Calculating the hashes in a batched way instead of row by row. This shows 15% gain over the row by row calculation.
2. We may consider other hash functions and range reduction functions. Existing hash function uses XxHash64 and it’s quite expensive, however all we needed is just uniform distribution in [1, partitionCount] and partitionCount is just a few hundreds. There could be some optimizations for this part.

## Appending values to buffers

 To read from the block, we have two choices: 

1. Directly access the raw arrays at specified positions
2. Access the values through the Block.getXXX() interface

We made JMH benchmarks to compare the two choices:

Contains Null	| FALSE | FALSE | FALSE | TRUE | TRUE | TRUE
---------------|--------|-------|--------|-------|------|-------
Number of column s |	1	|2|	4|	1|	2|	4
copyLongPagesToByteArrayBuffer|	80.1|	142.5|	308.6|	95.4|	199.6|	439.9
copyLongValuesToByteArrayBuffer|	60.2|	120.7|	272.1|	81.7|	175.8|	405.7
diff|	33%|	18%|	13%|	17%|	14%|	8%

Reading from Block.getLong() could be over 30% slower than directly reading from raw array when there is no nulls. The CPU profile shows the difference comes from the boundary check in the getLong() method. 

```
public long getLong(int position)
{
    checkReadablePosition(position);
    return getLongUnchecked(position + arrayOffset);
}

private void checkReadablePosition(int position)
{
    if (position < 0 || position >= getPositionCount()) {
        throw new IllegalArgumentException("position is not valid");
    }
}
```
The checkReadablePosition() was compiled into two comparison and jump instructions. By removing it the performance of the two is about the same. This lead to Tim’s UncheckedBlock change in https://github.com/prestodb/presto/pull/12792 

In the new PartitionedOutputOperator, we expect most calls are monomorphic, because we call BlockFlattener for every Block at the beginning to peel off the Dictionary and RLE wrappings, so there won’t be megamorphic calls on DictionaryBlock, RunLengthEncodedBlock and the plain Blocks on the same getXXX() methods. There could be different types of data represented by the same kind of Block, e.g. Double and Bigint are both represented by LongArrayBlock, therefore calling the same getter (e.g. getLong()) on these types resolve to the same Block implementation. Int128ArrayBlock and LongArrayBlock could be calling getLong() at the same time, but it was done in a block by block manner and the case is not very common. Block.getObject() could be a problem and it is implemented by multiple Blocks, but the new PartitionedOutputOperator does not use it. 

We also studied the performance for two different ways to add the values to the buffer: 1) loop over channels then partitions 2)  Loop over partitions then channels. For 1) the reads are local i.e. reading from the same array/block over and over while the writes are scattered. For 2) the reads are scattered but the writes are local. We didn't see enough difference to make us favor one over another.

## Flushing

When the size limit for each destination is met, we flush the data to a BasicSliceOutput then wrap it to SerializedPage. We used BasicSliceOutput because the operations are a few number of bulk copies and the overhead of boundary checking can be neglected. The flushing happens in the following steps

1. Allocate a new byte[] of precisely the the total of the buffers sizes
2. Write the headers and copy the buffers from the BlockEncodingBuffers in predefined order to the byte[] allocated in step 1.
3. Wrap the byte[] as a SerializedPage
4. Enqueue the SerializedPage to OutputBuffer.

CC: @oerling @mbasmanova @tdcmeehan @nezihyigitbasi

**Comment by mbasmanova** [comment]
The new optimized repartitioning operator is available starting with 0.227 release of Presto. Use `optimized_repartitioning` session property or the `experimental.optimized-repartitioning` configuration property to opt-in.

https://prestodb.io/docs/current/release/release-0.227.html
