### ISSUE TITLE
Does presto support add partiton for table of hive

### ISSUE THREAD

**Issue by groobyming** [prestodb/presto#13021]
When  I  execute the “ALTER TABLE ... add partition...”  statement in   presto-cli，then got the error！
![image](https://user-images.githubusercontent.com/34335395/60253914-85c6ee00-98ff-11e9-9206-2edbf6b7a693.png)

**Comment by ebyhr** [comment]
ALTER TABLE ADD PARTITION isn't implemented in Presto. 
https://prestodb.github.io/docs/current/sql/alter-table.html

If you are using [prestosql/presto](https://github.com/prestosql/presto), you can use `system.create_empty_partition` and  `system.sync_partition_metadata` command to add partitions. 
https://prestosql.io/docs/current/connector/hive.html

**Comment by groobyming** [comment]
@ebyhr Thanks，It's working for me
