### ISSUE TITLE
How to use Presto Configuration parameters dynamically

### ISSUE THREAD

**Issue by PranayMunshi1982** [prestodb/presto#13038]
Hi team,

I am writing one application to optimize the Presto, and show the recommendations after running each query based on cluster stats. I want to use 
Presto config properties dynamically from my Java program. I know I can place Presto configuration properties inside “etc/config.properties” file, but in order to take advantage of properties I need to restart the presto server. What I want I should be able to pass these properties dynamically with Presto Query and there should be no need to restart the presto server.

Please do let me know how can I pass the configuration properties dynamically without restarting the Presto server.
I used to do these kind of task with Apache IMPALA and APACHE HIVE but I am not getting any clue for Presto.

I am referring to below configuration properties - 

https://prestosql.io/docs/current/admin/properties.html

**Comment by findepi** [comment]
Since you're referring to prestosql, then https://github.com/prestosql/presto/issues is the right place to report issues.

**Comment by rongrong** [comment]
Many configuration properties listed in the list you referred to are not dynamically configurable. Some of these configurations need substantial amount of work to make them dynamically changeable. The configurations that you can "dynamically change" are session properties. You can find all of them via `SHOW SESSION`. If a configuration can be overwritten by a session property, it normally has a very similar session property name.

**Comment by rongrong** [comment]
The corresponding Presto documentation for properties is here: https://prestodb.github.io/docs/current/admin/properties.html

**Comment by PranayMunshi1982** [comment]
Thanks @rongrong for quick reply. I want to dynamically change the SESSION properties from JAVA code. 
How can I do that, Can I get any example for the same?

**Comment by rongrong** [comment]
How do you connect to Presto server in your java code now? I can give you more specific pointers if you let me know what Presto client you are using right now. Thanks!

**Comment by PranayMunshi1982** [comment]
I am connecting to Presto using JDBC.

JDBC_DRIVER="com.facebook.prsto.jdbc.PrestoDriver";
DB_URL="jdbc:presto//localhost:port/hive/schemaname";
PrestoDriver pd = new PrestoDriver();
Properties props = new Properties();
props.setProperty("user","name");

PrestoConnection connection = (PrestoConnection) pd.connect(DB_URL,props);
PrestoStatement stmt = (PrestoStatement) connection.createStatement();

stmt.executeQuery(sql);


Thanks @rongrong

**Comment by rongrong** [comment]
Then `connection.setSessionProperty` should work.

**Comment by PranayMunshi1982** [comment]
Thanks @rongrong for your quick help. This is really helping and worked for me.
I can see 91 session properties( by SHOW SESSION) but I am not sure which property I can tweak for my query performance and overall cluster level performance. 
What should be the criteria to choose session property.

**Comment by rongrong** [comment]
This totally depends on your queries. I encourage you to read through them and try to understand what they do. Feel free to ask any questions if particular session property is hard to understand. If you have a particular problem to solve, you can also describe that so we can give suggestions.

**Comment by PranayMunshi1982** [comment]
@rongrong 
I am going thru the session properties, but I want to understand the performance impact of these properties. E.g. when I read "enable_intermediate_aggregations" session properties, its description says Enable the use of intermediate aggregations. Here it doesnt' say anything about performance impact on other parts of execution. 

And I want to know one more thing about presto i.e. Is there any phases takes place while firing the query, like we have in MapReduce. MapReduce has shuffle phase, sort phase, reduce phase etc. 
Does presto break query execution in phases?

**Comment by rongrong** [comment]
> @rongrong
> I am going thru the session properties, but I want to understand the performance impact of these properties. E.g. when I read "enable_intermediate_aggregations" session properties, its description says Enable the use of intermediate aggregations. Here it doesnt' say anything about performance impact on other parts of execution.
> 
> And I want to know one more thing about presto i.e. Is there any phases takes place while firing the query, like we have in MapReduce. MapReduce has shuffle phase, sort phase, reduce phase etc.
> Does presto break query execution in phases?

Here's the explanation of what does adding intermediate aggregation do in java doc (copied from `AddIntermediateAggregations.java`.
```
/**
 * Adds INTERMEDIATE aggregations between an un-grouped FINAL aggregation and its preceding
 * PARTIAL aggregation.
 * <p>
 * From:
 * <pre>
 * - Aggregation (FINAL)
 *   - RemoteExchange (GATHER)
 *     - Aggregation (PARTIAL)
 * </pre>
 * To:
 * <pre>
 * - Aggregation (FINAL)
 *   - LocalExchange (GATHER)
 *     - Aggregation (INTERMEDIATE)
 *       - LocalExchange (ARBITRARY)
 *         - RemoteExchange (GATHER)
 *           - Aggregation (INTERMEDIATE)
 *             - LocalExchange (GATHER)
 *               - Aggregation (PARTIAL)
 * </pre>
 * <p>
 */
```
When disabled, we would run partial aggregation on each task, and shuffle the partial aggregation result to next stage, which does a local exchange, and do final aggregation. Intermediate aggregation is the stage we add at both source and destination where we would combine the partial aggregation result locally (for example, if you have 4 tasks running on a worker, we'd merge them, and shuffle one row, rather than 4). At destination, we will also do similar things. I think this would be helpful for performance if you have many tasks per query per worker.

If your workload doesn't have too many query shapes, it might worth just trying them out. You can run `EXPLAIN (TYPE DISTRIBUTED) QUERY` to see the query plan and reason about whether it makes sense. Alternatively, if you implemented an `EventListener` on `QueryCompletionEvent`, you can export query stats to help you do post analysis.

Presto execute queries in stages, and data are shuffled in memory between stages. You can hit coordinator UI and look at the live query plan while queries are running to get a better understanding of what stages look like.

**Comment by PranayMunshi1982** [comment]
Thank you @rongrong for help.
Actually I want to optimize presto. And my approach is to run a TPC-DS query with presto SESSION-PROPERTIES with certain values. Then I'll run the same query with tweaked/updated session properties. 
In the same way I'll run the query 2 to 3 times. I'll compare the Execution STATS. 

In the same way I want to run other TPC-DS queries. 

But I am too much confused about choosing the "SESSION-PROPERTIES" as there are 91 properties.

How to choose SESSION-PROPERTIES and based on query type?
