### ISSUE TITLE
NPE when launch Presto 0.192 on Yarn 2.7.3

### ISSUE THREAD

**Issue by ChenShuai1981** [prestodb/presto#13050]
I'm trying to run Presto on Yarn, and found coordinator & worker containers start and shutdown several times. 

Then in the server.log I found the NPE error, after checking the TimeZoneKey source code I suspect the "zone-index.properties" file was NOT loaded correctly, then I checked the container files, for example, container_1562134619433_0004_01_000002/app/install/presto-server-0.192/lib/presto-spi-0.192.jar, after unjar I can find "com/facebook/presto/spi/type/zone-index.properties". There it is !! 

So I want to ask what's the root cause of this problem? How to fix it so that I can continue my try. Thanks a lot!

BTW, I can launch Presto in standalone mode and query well.

server.log
> Caused by: java.lang.NullPointerException
	at java.util.Properties$LineReader.readLine(Properties.java:434)
	at java.util.Properties.load0(Properties.java:353)
	at java.util.Properties.load(Properties.java:341)
	at com.facebook.presto.spi.type.TimeZoneKey.<clinit>(TimeZoneKey.java:66)
	... 70 more

TimeZoneKey.java
```
static {
        try (InputStream in = TimeZoneIndex.class.getResourceAsStream("zone-index.properties")) {
            // load zone file
            // todo parse file by hand since Properties ignores duplicate entries
            Properties data = new Properties()
            {
                @Override
                public synchronized Object put(Object key, Object value)
                {
                    Object existingEntry = super.put(key, value);
                    if (existingEntry != null) {
                        throw new AssertionError("Zone file has duplicate entries for " + key);
                    }
                    return null;
                }
            };
            data.load(in);  // --> line 66
```

**Comment by rongrong** [comment]
I don't have much background with Yarn. So just sharing how would I look into this one step further. Here's the code in `Properties.java:434`:
```
                    inLimit = (inStream==null)?reader.read(inCharBuf)
                                              :inStream.read(inByteBuf);
```
So if it's a NPE, it seems to suggest that inStream is not initialized, nor did reader. So I'd try to figure out why inStream is not initialized properly by looking into `TimeZoneIndex.class.getResourceAsStream`.
