### ISSUE TITLE
map_top_n udf proposal

### ISSUE THREAD

**Issue by avk49** [prestodb/presto#13062]
**Description**:
This function takes a map as input and returns the top n keys based on their values as a map. This feature is used frequently in a lot of scenarios so having a udf would help write simpler queries in short time. 

_map_top_n(map(K, V), integer n) -> map(K, V)_

```
SELECT map_top_n(MAP(ARRAY[1, 2, 3, 4], ARRAY[120, 930, 200, 301]), 2); -- {2 -> 930, 4 -> 301}
SELECT map_top_n(MAP(ARRAY[1, 2, 3, 4], ARRAY['abc', 'abcd', 'efg', 'aaa']), 2); -- {2 -> 'abcd', 3 -> 'efg'}
SELECT map_top_n(null, 2); -- null
SELECT map_top_n(MAP(ARRAY[1, 2, 3], ARRAY[200, 100, 100]), 2); -- {1 -> 200, 2 -> 100}
SELECT map_top_n(MAP(ARRAY[1, 2], ARRAY[200, 100]), 4); -- {1 -> 200, 2 -> 100}
```

**Comment by rongrong** [comment]
From the examples I can say that you mean top N by key, but the name is ambiguous and doesn't say that explicitly. Overall, I think a generalized version of the problem is that there's no function that keeps a state while iterate through map entries. I can think of similar use cases like `map_top_n_by_key`, `map_top_n_by_value`, `map_bottom_n_by_key`, `map_bottom_n_by_value`, and `map_take_my_comparator_and_get_top_n`. So at the very least introducing some version of the last one would be more helpful. cc @wenleix

**Comment by wenleix** [comment]
One thought is 
```sql
map_min_by(map, (k, v) -> ..., n)
map_max_by(map, (k, v) -> ..., n)
```

To get the top-n map entires based on the lambda evaluation result. The simplest case would be `(k, v) -> v` to retrieve the top-n by value.  What do you think @highker ?

**Comment by avk49** [comment]
Thanks @rongrong  and @wenleix for feedback. Just to make sure; the suggestion is something like
`map_filter_n(map, (k,v) -> ..., n)`  ->

where the user's lambda function will decide whether its key or value & ascending or descending order.

**Comment by rongrong** [comment]
I'm wondering can you use `map_from_entries(slice(array_sort(map_entries(map), v -> ...), 1, n))` to achieve this? For example, your first case will be:
```
select map_from_entries(slice(array_sort(cast(map_entries(MAP(ARRAY[1, 2, 3, 4], ARRAY[120, 930, 200, 301])) as array(row(key integer, value integer))), (r1, r2) -> if(r1.value < r2.value, 1, if(r1.value=r2.value, 0, -1))), 1, 2))
```
I'm wondering what's the performance implications of this. Is it bad enough to worth implementing a function to optimize this.

**Comment by avk49** [comment]
Yes that definitely works ! But just curious as to why not have a udf similar to map_filter exclusively for handling maps.

**Comment by rongrong** [comment]
`map_filter_n` is a very strange concept. The lambda is not really defining the filter, but a sorting order. So what you really want is `map_first_n(map, (k1, v1, k2, v2) -> ..., n)`, which is basically massaging all parameters in `map_from_entries(slice(array_sort(map_entries(map), v -> ...), 1, n))` into one function. I'm not sure how appealing is that. Once we support SQL expression functions (#9613), this can be added as a SQL expression function instead.
A more generic need for map with lambda function is probably a `map_reduce` similar to the array `reduce` function. It allows you to keep a state while looping through entries. Though in this case the state would be quite complicated. It's unlikely to have an implementation with lambda that's more readable or performant than converting to array, sort, slice then convert back.
