### ISSUE TITLE
Presto Build Fail on Windows . Presto core success, but plugins fail

### ISSUE THREAD

**Issue by hankedang** [prestodb/presto#13088]

**Comment by hankedang** [comment]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.10:analyze-only (default) on project presto-memory-context: Dependency problems found

**Comment by aweisberg** [comment]
As far as I know there aren't many (any?) people deploying on Windows. If you want to build you can build on a VirtualBox VM or download the compiled artifacts.

I don't see this changing unless there is someone with the bandwidth to champion Windows. Even then if the overhead to the project is high it's a tough sell if there isn't enough demand to justify whatever the overhead might be of making Windows a supported platform on the majority of developers who are only concerned with Linux and MacOS.

**Comment by sunyaf** [comment]
how to fix it

**Comment by hankedang** [comment]
> how to fix it

build with linux or mac
