### ISSUE TITLE
Presto monitoring

### ISSUE THREAD

**Issue by Bruce2jiang** [prestodb/presto#13095]
How to monitor Presto

**Comment by Bruce2jiang** [comment]
please

**Comment by tooptoop4** [comment]
Jmx catalog especially query manager table, v1/cluster api, system.runtime.queries

**Comment by Bruce2jiang** [comment]
Can you be more specific?

**Comment by Bruce2jiang** [comment]
example :v1/cluster api

**Comment by Bruce2jiang** [comment]
v1/cluster api  ， In this way, my colleagues think it has a performance impact on the primary node

**Comment by Bruce2jiang** [comment]
Please persuade him

**Comment by Bruce2jiang** [comment]
@tooptoop4  v1/cluster api ， In this way, my colleagues think it has a performance impact on the primary node ,Please persuade him
