### ISSUE TITLE
Introduce TableWriterMergeOperator

### ISSUE THREAD

**Issue by arhimondr** [prestodb/presto#13098]
Recently fault-tolerance mechanisms were introduced for grouped execution: https://github.com/prestodb/presto/pull/12529.

If the Presto node participating in the query becomes unresponsive - Presto can reschedule the task from the unresponsive node to a different node. However it is not guaranteed that the unresponsive node won't finish the execution. Thus the same data can be written more than once.

To ensure correctness the partial commit operation was introduced: https://github.com/prestodb/presto/pull/12787, https://github.com/prestodb/presto/pull/12800

The `TableWriterOperator` produces the meta information about the list of files to be committed, and the `TableCommitContext` that contains the "id" (lifespan) and the stage id of the data written. Based on that id pair (lifespan + stage) the coordinator keeps on copy of the written data, and commits only a single set of files per lifespan discarding the data written by other (failed) workers. This is similar to the atomic commits protocol in MapReduce. [1]

To improve the commit latency, the `TableFinishOperator` commits as soon as the node has finished writing. TableFinishOperator knows that the node has finished execution by the assumption that the node will exactly 1 `TableCommitContext` right after the writing is finished. This works for bucketed table writes, as TableWriter concurrency is fixed to 1 in this case. 

However, if the TableWriter concurrency is higher than 1 (more than a single `TableWriterOperator` is running per node) that assumption no longer holds. Every `TableWriterOperator` will produce its own TableCommitContext that makes it impossible to know if the node has finished writing or no.

Currently recoverable grouped execution is not supported if the table writer concurrency is higher than one.

The proposal is to merge the TableWriterOperator output into a single one before sending it to the coordinator. So it will be guaranteed that a single writer node will produce only a single TableCommitContext.

The TableWriterMergeOperator will collect all Fragments (that are used to store the file name to commit) into a single list, accumulate the row count and the column level statistics. And once all TableWriterOperators are done - it will send the merged TableCommitContext to the coordinator, indicating that the writing is finished for a given lifespan on the given node.

Current implementation:

![before](https://user-images.githubusercontent.com/5570988/61337864-0db85d80-a805-11e9-885c-1ee65a87b6ce.png)

Proposed implementation:

![after](https://user-images.githubusercontent.com/5570988/61337869-15780200-a805-11e9-8c77-ebafd08c3497.png)

Proposed implementation will introduce a new plan node `TableWriterMergeNode` and a new operator `TableWriterMergeOperator`.

[1] [MapReduce: Simplified Data Processing on Large Clusters](https://static.googleusercontent.com/media/research.google.com/en//archive/mapreduce-osdi04.pdf)

**Comment by arhimondr** [comment]
CC: @wenleix @rschlussel @shixuan-fan @tdcmeehan @highker

**Comment by jaystarshot** [comment]
@arhimondr  I was thinking if CTE materialization can be used with presto-on-spark. Turns out that the coordinator distribution is not supported there (since it needs a driver for tablefinish operator), wondering if you had any leads to fixing this.

**Comment by rschlussel** [comment]
presto-on-spark already materializes intermediate results as part of the exchange, so we shouldn't need to do the table writes, just create the proper dependencies between plan fragments (you might be able to do this with an iterative optimizer/the IterativePlanFragmenter)

**Comment by jaystarshot** [comment]
I see makes sense, not sure if we can add a single fragment as a dependency to two or more fragments currently.

**Comment by rschlussel** [comment]
Plan fragments will each get packaged up into a Spark RDD for execution.  We keep a mapping of plan fragments (by id) to RDDs https://github.com/prestodb/presto/blob/master/presto-spark-base/src/main/java/com/facebook/presto/spark/execution/AbstractPrestoSparkQueryExecution.java#L799-L802.   When creating the subplan maybe we can duplicate the plan fragment and then we can check in the fragment map there is an existing RDD we can reuse rather than packaging up this new plan fragment into a new RDD.  If you reuse an existing RDD, the computation it does will not be repeated.

(We could even extend to do this with things that we didn't explicitly make into a CTE, if we have some canonicalization for plan fragments so that we can identify ones that are semantically equivalent, we could use those as the map keys)

**Comment by jaystarshot** [comment]
Oh so that means spark is managing the scheduling and not us. I think it might work if we just pass correct dependencies. Agreed that can be the common subquery extension.
