### ISSUE TITLE
Fix code bug in HA in presto 

### ISSUE THREAD

**Issue by rajeshbalamohan** [prestodb/presto#13105]
StaticHiveCluster.java

https://github.com/prestodb/presto/blob/master/presto-hive/src/main/java/com/facebook/presto/hive/metastore/thrift/StaticHiveCluster.java#L69

This would end up missing the first entry in the configuration. So if there are 2 HMS instances provided, it would always end up using just 1.

**Comment by ryanrupp** [comment]
I think this is correct although confusing at first glance. `subList` ends up creating a view of the same list so when `Collections.shuffle` is used it's just intended here to randomize the non-default providers, so anything beyond the first entry, leaving the first entry alone as the "default" which then always gets tried first on the subsequent iteration of the connections. The comment above mentions this behavior how it favors the default one then just randomizes after that to try to connect - https://github.com/prestodb/presto/blob/master/presto-hive/src/main/java/com/facebook/presto/hive/metastore/thrift/StaticHiveCluster.java#L59

**Comment by rajeshbalamohan** [comment]
Yes, thanks @ryanrupp . If there are 2 metastores configured and if the first one errors out, it would always end up trying the first one (with exception, timeout etc) before trying out the second one.

It would be good to shuffle from (0-n) instead. Even better, if we can track the bad HMS and add to the end of the list after shuffling.
