### ISSUE TITLE
Release notes for 0.223

### ISSUE THREAD

**Issue by varungajjala** [prestodb/presto#13103]
Issue to track release notes for next release

**Comment by varungajjala** [comment]
## Akshay Pall          
- [ ] all checked
-  07-02 15:49:39    336e625d5b Add CNF/DNF conversion methods to LogicalRowExpressions
## Andrii Rosa          
- [ ] all checked
-  07-11 14:02:06    417e5b9c6c Improve error message when $bucket column is not available
-  07-15 09:48:05    8e6b74f02f Fix hardcoded catalog name in testIgnoreTableBucketing()
-  07-17 14:01:16    1e3f420e67 Always keep bucketed execution on for temporary tables
-  07-17 14:01:16    56829b4a96 Improve error messages when exchange materialization is misconfigured
## Greg Leclercq        
- [ ] all checked
-  06-21 16:12:54    6c986eb556 prepare for next development iteration - 0.223-SNAPSHOT
## James Sun            
- [ ] all checked
-  06-21 19:05:31    7c5b800b3d Fix connector optimizer registration in PlanOptimizers
-  06-21 19:05:31    a4339f0270 Revert "Force ConnectorManager to load all optimizers before PlanOptimizers"
-  06-23 17:30:11    7372ae6f08 Add empty Hive connector plan optimizer
-  06-24 11:27:38    2cb1aff6f2 Add missing Override annotation in FilterNode
-  06-24 11:27:38    c37dbd5693 Move ValuesNode to SPI
-  06-27 17:47:56    8d5939e814 Lazily construct error message for CheckState
-  06-28 10:41:26    d9f83f866e Support multibyte character in data_format function
-  07-01 18:14:28    459295db39 Move HashGenerationOptimizer below translateExpressions
-  07-10 08:53:16    7518a70d01 Fix long-to-int cast in LiteralInterpreter
-  07-12 15:40:07    fe6ad34b8e bump kafka version to 1.1.1
-  07-16 13:04:02    3ad698f63f Prevent special serde conflict with symbol names
-  07-16 13:04:02    cbe20f5939 Fix variable expression serde
## Ke                   
- [ ] all checked
-  06-26 18:33:08    bcf0a18e3d Unify PlanBuilder::join with only RowExpression
-  07-01 18:24:37    3f65287633 Add sanity checker to check no expression left after optimization
-  07-01 18:24:37    9c851ef838 Translate expressions in TestPlannerWarnings
## Leiqing Cai          
- [ ] all checked
-  07-01 14:03:37    2e7b3877e8 Upgrade to testing-mysql-server 8.0.12-5
-  07-09 14:33:32    8e3510a142 Support table property override in QueryRewriter
-  07-10 11:16:39    03d70ad6fd Fix variable name in Verifier
## Maria Basmanova      
- [ ] all checked
-  06-27 06:25:18    efea1636f1 Fix a typo in the description of a session property
-  07-01 08:17:29    0b40fc1709 Extract helper method to create BucketAdaptation from BucketConversion
-  07-01 08:17:29    0f4c7ab3d0 Remove unused method from OrcRecordReader
-  07-01 08:17:29    24ba07963e Refactor BenchmarkBatchStreamReaders
-  07-01 08:17:29    517f80bf15 Rename OrcPageSource to OrcBatchPageSource
-  07-01 08:17:29    5f560675fc Move getPhysicalHiveColumnHandles into HiveUtil
-  07-01 08:17:29    66187c0c93 Rename OrcRecordReader to OrcBatchRecordReader
-  07-01 08:17:29    6a927e35ee Move TupleDomain compaction logic into TupleDomainOrcPredicate
-  07-01 08:17:29    7b776f68d3 Extract AbstractOrcRecordReader and StreamReader
-  07-01 08:17:29    86b1b15018 Fold BenchmarkOrcDecimalReader into BenchmarkBatchStreamReaders
-  07-01 08:17:29    88a41bf937 Add hive.pushdown-filter-enabled configuration property
-  07-01 08:17:29    93f0381e95 Rename HivePageSourceFactory to HiveBatchPageSourceFactory
-  07-01 08:17:29    a571785d5a Extract helper method to parse partition key string into an object
-  07-01 08:17:29    c4d37b7f8f Rename StreamReader to BatchStreamReader
-  07-01 08:17:29    e9f878911d Introduce SelectiveStreamReader
-  07-01 08:17:29    ea0591f5c9 Extend OrcTester to support multi-column files
-  07-01 08:17:29    f6e19fa82e Rename *Decimal* to *ShortDecimal* in BenchmarkBatchStreamReaders
-  07-03 16:15:40    a19aba0638 Move RowExpressionNodeInliner to SPI
-  07-09 07:09:56    303cecacf7 Remove unnecessary StreamReader.close method
-  07-09 07:09:56    be749f6197 Remove unused systemMemoryContext variable from XxxBatchStreamReader
-  07-11 13:04:05    27e21e1ab4 Disable PushdownSubfields rule
-  07-16 15:47:14    44e005a26a Fix memory accounting in LongDictionaryBatchStreamReader
-  07-16 15:47:14    903e19c46e Add LongSelectiveStreamReader
-  07-16 15:47:14    d326587df4 Fix memory accounting in BooleanSelectiveStreamReader
-  07-16 15:47:14    ff246d108c Add TupleDomainFilter for DATE type
## Rebecca Schlussel    
- [ ] all checked
-  06-25 13:56:53    84b98dc03b add example of UNNEST for a MAP column to docs
-  06-26 11:37:23    2e6a224b33 Restore d3.js for timeline view
-  06-27 15:42:22    0ce469539e Remove temporary table from TableScanNode
-  06-27 15:42:22    811fdd8968 Require explicit tupledomain.all() in tableScan constructor
-  07-01 09:08:27    442bf5095e Add documentation on how to use `USING`
-  07-18 14:21:30    36a189a6ac Make BlockFlattener tests single threaded
-  07-18 14:32:38    cec6438021 Add release notes for 0.222
## Shixuan Fan          
- [ ] all checked
-  06-21 18:17:50    2809973fc3 Improve testIllegalStorageFormatDuringTableScan
-  07-03 11:17:25    70eab87b4f Remove ValuesNode verification in ApplyConnectorOptimization
-  07-03 11:42:16    11dc6f7a69 Run recoverable grouped execution test in a separate build
-  07-03 11:42:16    e86a7e12de Add new stage state FINISHED_TASK_SCHEDULING
-  07-03 11:42:16    fef6e76620 Improve TestHiveRecoverableGroupedExecution
-  07-03 13:07:21    701071000b Remove unused import in ApplyConnectorOptimization
## Timothy Meehan       
- [ ] all checked
-  07-15 16:52:48    cb7820053b Fix bitwise operations documentation
## Wenlei Xie           
- [ ] all checked
-  06-26 13:24:45    0f8cddb36e Add support for missing sequence IDs in flat maps
-  06-26 13:25:26    9c2ea6dc32 Minor fixes for Classification ROC related UDFs
-  06-28 11:31:37    cade04608f Do not throw when exception happens in JdbcPageSink::abort
-  07-02 14:40:07    36c9e91a5c Move histogram tests to the right "aggregation" package
-  07-09 11:09:47    960414950e Fix udf demo in doc
## Yi He                
- [ ] all checked
-  06-24 14:26:08    2895b26e02 Remove unused toRowExpression
-  06-24 14:26:08    3bdf3ef842 Use variable to get from assignment in isCountOverConstant
-  06-24 14:26:08    4ad4f30638 Use ExpressionVariableInliner in InlineProjections
-  06-24 14:26:08    64636173b3 Use variable in IndexKeyTracer
-  06-24 14:26:08    649c1d1890 Remove Assignment::get symbol
-  06-24 14:26:08    843298a9e0 Remove unused ExpressionSymbolInliner
-  06-24 14:26:08    d22d28e3c5 Use variable instead of symbol when look up existing constant
-  06-24 15:11:29    bd0718aa24 Update drift to com.facebook.drift 1.19
## cem cayiroglu        
- [ ] all checked
-  06-26 16:45:27    f499eebc29 Adding long polling for task info Task info updates are causing coordinator to overload in large clusters.
## yingsu00             
- [ ] all checked
-  07-09 16:09:54    6b153bf059 Make HiveQueryRunner logging succinct

**Comment by hellium01** [comment]
Dependency:
* Updated drift to com.facebook.drift 1.19

Otherwise, the other changes are not direct user related.

**Comment by shixuan-fan** [comment]
Nothing from my side.

**Comment by rschlussel** [comment]
```
Web UI Changes
-----------------
* Fix splits timeline view.
```

**Comment by highker** [comment]
```
General
-----------------
* Fix a bug that a connector may not optimize query plan even an optimizer is specified.
* Support multibyte characters in ``date_format`` function.

Kafka
-----------------
Update Kafka version from 0.8.2.2 to 1.1.1.
```

**Comment by cemcayiroglu** [comment]
General
-----------------
* Experimental flag added to enable long polling for task info Task info updates to reduce cpu load on coordinator

**Comment by arhimondr** [comment]
My changes are simple error message improvements
