### ISSUE TITLE
How to choose Presto Session Properties and its values

### ISSUE THREAD

**Issue by PranayMunshi1982** [prestodb/presto#13115]
Hi Team,
I want to optimize the Presto, I have to perform optimization at run time means without restarting the Presto Server so for this reason I am using Presto Session Properties. I can set session properties when I am firing the query. 

I've couple of questions below
**I've come across 91 session properties, out of that I want to use some of them but
(1) I don't know how to choose their values, whether it should be 'true' or 'false' for particular query, or value of session property should be 10 or 100. 
(2) How to decide these values looking at 'query'?**
(3) I want some detail description of below session properties. Where can I found detail about below properties. 

 
following are session properties with current and default values which I want to use for optimization - 

- dictionary_aggregation                                                     | false                    | false                

distributed_index_join                                                           | false                  | false                
distributed_join                                                                     |                          |                      
distributed_sort                                                                     | true                  | true                 

enable_intermediate_aggregations                                       | false                 | false                
execution_policy                                                                    | all-at-once       | all-at-once          
initial_splits_per_node                                                            | 8                      | 8                    
join_distribution_type                                                         | PARTITIONED      | PARTITIONED          
join_reordering_strategy                     | ELIMINATE_CROSS_JOINS | ELIMINATE_CROSS_JOINS
max_drivers_per_task                                                             |                          |                      
max_reordered_joins                                                              | 9                       | 9                    
optimize_hash_generation                                                     | true                  | true                 
push_aggregation_through_join                                            | true                  | true                 
push_partial_aggregation_through_join                                | false                 | false                
push_table_write_through_union                                           | true                 | true                 
query_priority                                                                         | 1                     | 1                    
redistribute_writes                                                                  | true                | true                 

spill_enabled                                                                           | false                 | false                
split_concurrency_adjustment_interval                                   | 100.00ms              | 100.00ms             

task_concurrency                                                                     | 16                    | 16                   
task_share_index_loading                                                        | false                 | false                
task_writer_count                                                                    | 1                     | 1                    
writer_min_size                                                                       | 32MB                  | 32MB                 

hive.bucket_execution_enabled                                             | true                  | true                 
hive.force_local_scheduling                                                   | false                 | false                
hive.hive_storage_format                                                       | ORC                   | ORC                  
hive.insert_existing_partitions_behavior                                 | APPEND                | APPEND               

hive.orc_bloom_filters_enabled                                              | false                 | false                
hive.orc_max_buffer_size                                                       | 8MB                   | 8MB                  
hive.s3_select_pushdown_enabled                                         | false                 | false                

@rongrong
@dain

**Comment by shixuan-fan** [comment]
Have you checked the description of session properties under `SHOW SESSION`?

**Comment by PranayMunshi1982** [comment]
yes @shixuan-fan I've checked the description but it is not enough to make any decision. I am looking for some detail description.

**Comment by shixuan-fan** [comment]
I don't have full knowledge of these session properties and I think it would be a heavy commitment for one to explain all the details beyond description without much context about the specific problems you are trying to solve and to which point you have questions and your understanding so far.

For example, `distributed_index_join: Distribute index joins on join keys instead of executing inline`. Why are you interested in this property, what's your current understanding and what more do you want to know about this?

**Comment by PranayMunshi1982** [comment]
Thank you @shixuan-fan. I can understand that it is very difficult for single person to describe me all this properties in detail. I am looking for documentation where I can understand all these properties. 

I am trying to decide session properties at run time means when I am firing query( I am using JDBC). 
How to decide their value, what things I should keep in mind before setting any value. Means I should look at query, cluster configuration, partitioning and bucketing, Joins before setting these values. 

In case of 'distributed_index_join' if I set its value as true then how it will impact the performance, How much resource it is going to take on cluster, network traffic. Before setting this should I check data distribution, join size, table description and need to run analyze table or run the show stats.
I am looking for flow/steps which going to take place during the execution after setting up true or false.

Thanks once again.

**Comment by shixuan-fan** [comment]
https://prestodb.github.io/docs/current/admin/properties.html is a good start but I guess you might have already discovered this. We also realized that we didn't do a good job in documenting every thing. We might need to rethink how to formulate the documentation workflow. cc @aweisberg 

Most of the time the default setting would be the best bet because we choose these values carefully, but I could understand that you want to be more thoughtful around this.

**Comment by PranayMunshi1982** [comment]
Thanks @shixuan-fan. You are right I've already covered the mentioned properties. And above properties requires restart of Presto Server that's why I want to use Session Properties.

**Comment by xingnailu** [comment]
I have the same problem, Do you have some experience to share?? @PranayMunshi1982

**Comment by PranayMunshi1982** [comment]
Hi @xingnailu, Presently I am executing queries and setting session properties using Presto Benchmark driver. 
I am using session properties in combination with other session properties and analyzing the performance parameter, whether it is improving the performance or degrading the performance.
