### ISSUE TITLE
Release notes for 0.224

### ISSUE THREAD

**Issue by varungajjala** [prestodb/presto#13129]
## Andrii Rosa          
- [x] all checked
-  07-29 08:41:50    1c1108fb46 Check remote exchange partitioning when planning Union
-  07-31 09:30:22    5f08613bee Add Planning Time in Query Details Page
-  07-31 11:09:28    376e2102aa Compact effective predicate early
-  07-31 11:09:28    9eb86b6c0a Static import unmodifiableMap in TupleDomain
-  07-31 11:09:28    a8e5bd143b Move compaction method to TupleDomain
-  07-31 13:29:39    9f64df300b Change hive thread pool naming
-  07-31 13:29:39    a95f0846da Create zero-row file in parallel
-  07-31 14:15:33    1943709f55 Compact effective predicate for partitioned table
## James Sun            
- [x] all checked
-  07-25 10:02:20    70c31b498c Fix CPU time and Scheduled time in PlanPrinter
-  07-25 17:45:27    6c7e444f6d Add support for row subscript
-  07-26 13:39:43    013100f3a8 Add support for row subscript
-  07-26 13:39:43    182f4e6e12 Revert "Add support for row subscript"
-  07-30 12:07:48    47e95d73ed Add RemoveRedundantIdentityProjections after connector optimizer
-  07-30 22:18:45    3db65341fe Fix query failure for certain collated join
## Ke                   
- [x] all checked
-  07-27 14:22:11    7732c36c73 Add header for extra credential
-  07-27 14:22:11    8513d23d79 Add support for extra credential in Presto CLI
-  07-27 14:22:11    cd1e9b3d57 Add support for extra credential in JDBC driver
-  07-27 14:22:11    da161af7ec Add credentials in Identity and ConnectorIdentity
## Leiqing Cai          
- [x] all checked
-  07-25 13:38:02    c7f90b1471 Export the reason of skipping test cases in Verifier
-  07-25 14:11:25    5879904c4b Rename PrestoAction to JdbcPrestoAction
-  07-25 14:11:25    685cde4f4b Support resubmitting certain verification failures
-  07-25 14:11:25    915065b824 Extract PrestoAction interface
-  07-25 14:11:25    ab6d35f649 Use PostConstruct annotation to start VerificationManager
-  07-25 14:11:25    ffb68b88cd Remove stateful field QueryStats in DataVerification
## Maria Basmanova      
- [x] all checked
-  07-18 17:11:38    44b59c3fe5 IN predicate for strings
-  07-23 10:16:08    358d9fd9f1 Replace session-based arguments with session argument in createOrcPageSource
-  07-23 10:16:08    5845abbe1f Add SelectiveStreamReader.getBlockView
-  07-23 10:16:08    f17d1d8966 Introduce filter functions
-  07-25 09:58:19    3cb676a459 Add support for partition and hidden columns to OrcSelectivePageSource
## Rebecca Schlussel    
- [x] all checked
-  07-23 14:27:09    c2694708dd Secure nextUri with a slug
-  07-25 12:09:12    3bad1c64f0 Add release notes for 0.223
-  07-30 07:45:23    22c4cfd8e9 Refactor HivePartitionManager.getPartitions()
-  07-30 07:45:23    806bf9afb9 Make HivePartitionResult return list
-  07-30 07:45:23    b0d64c3b74 Remove unused code
-  07-30 07:45:23    f5246e48f2 Add config to limit buckets for grouped execution
-  07-30 07:54:13    c043d2c486 Disable TestHiveRecoverableGroupedExecution
-  07-30 08:01:31    9175fa004c Handle race in QueryStateTimer
## Rongrong Zhong       
- [x] all checked
-  07-19 17:06:39    30fe4f9ce1 Add NOTICES file
-  07-19 17:06:39    446416e1d8 Modify t-digest for Presto Remove unnecessary functions for Presto t-digest needs.
-  07-19 17:06:39    b463cd0b9a Add tdigest serialization documents
-  07-19 17:06:39    c5035a0dc2 Add implementation of T-Digest This commit copied the original code as it is intentionally. Refactoring will be done in future commits.
-  07-30 17:05:30    27260b62b4 Pass session to JdbcClient#toWriteMapping
-  07-30 18:28:07    16e751ac87 Remove unused class SymbolToInputRewriter
-  07-30 18:28:07    23ec96ecf1 Remove Symbol from QueryPlanner
-  07-30 18:28:07    46ac33d273 Remove Symbol from TaskTestUtils
-  07-30 18:28:07    50a663fc0f Remove Symbol from TransformQuantifiedComparisonApplyToLateralJoin
-  07-30 18:28:07    51780f3115 Remove Symbol from Partitioning
-  07-30 18:28:07    61dac58083 Remove reference to Symbol in LocalExecutionPlanner
-  07-30 18:28:07    62ea7330b6 Remove PlanBuilder.symbol
-  07-30 18:28:07    70010a8268 Remove Symbol from RelationPlanner
-  07-30 18:28:07    7fb29f59c5 Remove Symbol from TestSimpleFilterProjectSemiJoinStatsRule
-  07-30 18:28:07    81d9d35fa7 Remove Symbol from TestEffectivePredicateExtractor
-  07-30 18:28:07    d7bf06d00a Remove OutputSymbol from NodeRepresentation
-  07-30 18:28:07    de21d2cefc Remove Symbol from TestPhasedExecutionSchedule
-  07-30 18:28:07    e265ed17b9 Remove Symbol from PredicatePushDown
## Shixuan Fan          
- [x] all checked
-  07-25 12:32:16    a752478f0f Support virtual bucketing on $path for hive unbucketed table
-  07-25 12:32:16    af21005970 Support recoverable grouped execution for writing unpartitioned table
-  07-25 12:32:16    e4afe593f2 Static import Streams#stream and Math#max in BackgroundHiveSplitLoader
## Varun Gajjala        
- [x] all checked
-  07-18 16:46:46    2b00ad17f6 prepare for next development iteration - 0.224-SNAPSHOT
## Yi He                
- [x] all checked
-  07-23 19:58:22    7545741123 Fix accidental removal of nested type only cast
-  07-26 18:08:06    1b55942ef6 Remove typeOnly optimization from SqlToRowExpressionTranslator
-  07-26 18:08:06    ad86f2363c Optimize away coercible cast on constant
-  07-26 18:08:06    fb70e12b0a Allow optimize Array/RowType constant
## rongrong             
- [x] all checked
-  07-26 18:58:29    48d11a5796 Change SymbolsExtractor to VariablesExtractor
-  07-26 18:58:29    57da82c3ce Remove unused methods in UnaliasSymbolReferences
-  07-26 18:58:30    0067a7ecb6 Remove RelationPlan.getSymbol
-  07-26 18:58:30    17283ddd89 Remove unused method in Assignments
-  07-26 18:58:30    3164094e02 Remove Symbol from LambdaCaptureDesugaringRewriter
-  07-26 18:58:30    3737bc06ca Change TypeProvider to use String instead of Symbol
-  07-26 18:58:30    428f915e42 Change TupleDomain<Symbol> to TupleDomain<String>
-  07-26 18:58:30    715cd5bf2e Remove SymbolToInputParameterRewriter
-  07-26 18:58:30    72db27ac29 Remove StatisticAggregations.getGroupingSymbols
-  07-26 18:58:30    7402277481 Remove unused method in PushProjectionThroughUnion
-  07-26 18:58:30    8d1ab2bd58 Remove unused variables in ReorderJoins
-  07-26 18:58:30    a542ea723e Change SymbolAllocator to PlanVariableAllocator
-  07-26 18:58:30    b18ff4e3d3 Change TypeProvider.get to take Expression
-  07-26 18:58:30    ee4cbd5381 Change VariableAllocator.toVariableReference to take Expression

**Comment by rschlussel** [comment]
```
Security Fixes
--------------
* Fix security issue with nextUri protocol

Hive Connector Fixes
----------------------
* Add config property ``hive.max-buckets-for-grouped-execution`` and session property ``max_buckets_for_grouped_execution`` to limit how many buckets a query can access and still take advantage of grouped execution.  If more than the configured number of buckets * partitions are queried, then the query will run without grouped execution.
```

**Comment by shixuan-fan** [comment]
```
General
-------
* Add support for recoverable grouped execution for writing unpartitioned table

Hive
----
* Add support for grouped execution for queries that have no joins and aggregations and read from and unbucketed table.
```

**Comment by highker** [comment]
```
Raptor
--------------
* Fix query failure on colocated joins when one table has empty data.

General
--------------
* Add support for index-based access to row-type field with the subscript.
* Fix mis-swapped CPU time and scheduled time in query plan.
```

**Comment by caithagoras** [comment]
```
Verifier Changes
----------------
* Add the reason of test cases being skipped in output event.
```

**Comment by hellium01** [comment]
General
--------------
* Fix correctness bug on queries contain nested coercible type cast since release 0.220.

**Comment by arhimondr** [comment]
```
General
-------
* Display Planning Time in Query Details Page
```

```
Hive
----
* Improve performance of the insert into a bucketed table for the case when some buckets are empty
```
