### ISSUE TITLE
Unsupported time zone

### ISSUE THREAD

**Issue by silverguo** [prestodb/presto#13139]
Hi,

When I use `at_timezone` to convert datetime from UTC to local, I found some time zones are still not supported, for example,

```
NOT_SUPPORTED: Time zone not supported: Europe/Saratov
```

Thanks!

**Comment by rschlussel** [comment]
What's the query you're running?  Are you sure you're not including extra whitespace or something in the timezone name?  That time zone works for me.
```
presto> select now();
                    _col0                    
---------------------------------------------
 2019-07-29 08:58:12.500 America/Los_Angeles 
(1 row)

presto> select at_timezone(now(), 'Europe/Saratov');
                 _col0                  
----------------------------------------
 2019-07-29 19:58:23.865 Europe/Saratov 
(1 row)
```

**Comment by silverguo** [comment]
@rschlussel Oh, I found I was in an old version of presto with a stale joda time package.

Thanks for your help!

**Comment by btsperes** [comment]
hey @silverguo, I'm facing the same issue on Presto. Could you please guide me to upgrade joda time package? Many thanks

**Comment by silverguo** [comment]
> hey @silverguo, I'm facing the same issue on Presto. Could you please guide me to upgrade joda time package? Many thanks

Hi @btsperes , something similar like,
https://github.com/prestodb/presto/blob/816efa9cec39c7f8ca68808dc23f1bef3a289193/pom.xml#L56
Depends on your build tool.

But if you use the latest version of presto, you might not have this issue.
