### ISSUE TITLE
Array form of approx_pecentile with accuracy specified

### ISSUE THREAD

**Issue by tdcmeehan** [prestodb/presto#13143]
From the documentation, the following forms of `approx_percentile` are exposed:

* `approx_percentile(x, percentage) → [same as x]`
* `approx_percentile(x, percentages) → array<[same as x]>`
* `approx_percentile(x, w, percentage) → [same as x]`
* `approx_percentile(x, w, percentage, accuracy) → [same as x]`
* `approx_percentile(x, w, percentages) → array<[same as x]>`

The following form should also be exposed:

* `approx_percentile(x, w, percentages, accuracy) → [same as x]`

I.e. the signature should feature the value, the weight, an array of percentages, and an accuracy parameter.

**Comment by prongs7** [comment]
I can pick this up. Can raise a PR in the next 1-2 days.
