### ISSUE TITLE
Presto Benchmark. Elements for suite.json.

### ISSUE THREAD

**Issue by PranayMunshi1982** [prestodb/presto#13149]
Hi friends,
I am running presto benchmark driver "presto-benchmark-driver.jar". It requires "suite.json' as config files to run the particular query on a particular schema. 
I can see two JSON elements in suite.json i.e. **1. file_formats 2. legacy_orc.** 

Here I am not able to understand the difference between two. Why we have these two elements, what is the significance of these two?

I can put required detail in first element and run the benchmark. 
When should I go for 'file_formats' and when should I go for 'legacy_orc'?
Which JSON attribute I should put in which JSON element?

Do we have more JSON elements for 'suite.json' in order to run benchmark?

**Comment by rongrong** [comment]
Does the documentation here provide the answer you want? https://prestodb.github.io/docs/current/installation/benchmark-driver.html

**Comment by PranayMunshi1982** [comment]
Thank you @rongrong. I am following this only. 
But I've received solution from @dain .
