### ISSUE TITLE
 Insufficient active worker nodes.

### ISSUE THREAD

**Issue by sushilrbs** [prestodb/presto#13164]
Hi,
    I was trying to connect Presto to MongoDB cluster.  We have installed Presto on 3 servers. 1 server is working as coordinator and other servers are working as a worker node. Here are their config.properties value
--------------
coordinator
--------------
coordinator=true
node-scheduler.include-coordinator=false
http-server.http.port=8080
query.max-memory=50GB
query.max-memory-per-node=1GB
query.max-total-memory-per-node=2GB
discovery-server.enabled=true
discovery.uri=http://11.13.64.65:8080

worker 1
--------------
coordinator = false 
http-server.http.port=8080
query.max-memory=50GB
query.max-memory-per-node=1GB
 discovery.uri=http://11.13.64.65:8080

worker 2
--------------
coordinator = false 
http-server.http.port=8080
query.max-memory=50GB
query.max-memory-per-node=1GB
 discovery.uri=http://11.13.64.65:8080

I connected via CLI and tried to run below command
 select count(*) from mongodb.testdb.emp;
and getting below error

Query 20190731_114705_00001_3z96f failed: Insufficient active worker nodes. Waited 5.00m for at least 1 workers, but only 0 workers are active

Please help me on this

**Comment by tooptoop4** [comment]
How many workers are shown presto webui? @sushilrbs
