### ISSUE TITLE
 Failed to initialize connection pool: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Unrecognized connection property

### ISSUE THREAD

**Issue by qinzl1** [prestodb/presto#13188]
HikariPool seem can not init presto jdbc
I use sreamsets  JDBC Query Consumer  (https://streamsets.com/documentation/datacollector/3.9.x/help/datacollector/UserGuide/Origins/JDBCConsumer.html#concept_qhf_hjr_bs) 
Has anyone used this tool

**Comment by rschlussel** [comment]
It seems like the jdbc driver is trying to pass a property to Presto that isn't used.  You could see if there is a way to not pass that property.

Also, see discussion here: https://github.com/prestodb/presto/issues/9254

**Comment by qinzl1** [comment]
@rschlussel 
ths，the UI tool have some special configuration items need config
