### ISSUE TITLE
Add SelectiveStreamReader for columns of type DOUBLE

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#13191]
Master issue: #12585 

A new reader, DoubleSelectiveStreamReader, will implement SelectiveStreamReader interface and allow extracting data for columns of type DOUBLE.

The new reader will be similar to readers for BOOLEAN and BYTE types. The output block will be an instance of `LongArrayBlock`. The reader will use `TupleDomainFilter#testDouble` filter API and accumulate values that pass the filter into an array of longs (`long[] values`). It will use `java.lang.Double#doubleToLongBits` to convert double values into long values (see `DoubleType#writeDouble`).

The original reader for DOUBLE type is `DoubleBatchStreamReader`. The relevant logic is in `readBlock` method.

For testing:
- Unit test will go into `TestSelectiveOrcReader` (see AbstractTestOrcReader#testDoubleSequence for a similar test for the original reader). 
- Integration test will go into `TestHivePushdownFilterQueries`. 
- A benchmark will go into `BenchmarkSelectiveStreamReaders` (the benchmark for original readers is `BenchmarkBatchStreamReaders`).

PRs for BOOLEAN and BYTE readers: #12991 and #13174 

CC: @bhhari @tdcmeehan @oerling @yingsu00

**Comment by sayhar** [comment]
I'm on this.

**Comment by sayhar** [comment]
Here's working code with tests: https://github.com/sayhar/presto/tree/double_reader

Still needs cleanup:
- Testing code copies a static function that probably shouldn't be copied
- Comments sprinkled within
- Need to benchmark to make sure that inlining a function actually gives gains
