### ISSUE TITLE
Document SQL support for elasticsearch connector

### ISSUE THREAD

**Issue by murphyke** [prestodb/presto#13202]
I was wondering if the elasticsearch connector supports DML, but the documentation page doesn't address SQL support for this connector.  Is it true that the answer to this particular question is "No"? The source code doesn't include the word "delete" ....

**Comment by rschlussel** [comment]
@zhenxiao do you know the answer?

**Comment by zhenxiao** [comment]
Hi @murphyke , currently, Elasticsearch connector does not support createTable, add column, and related DMLs. If you have a use case for it, we could consider adding the support :)

**Comment by murphyke** [comment]
> if you have a use case

Not really. Thanks, though.
