### ISSUE TITLE
Lots of Major GC in raptor tests

### ISSUE THREAD

**Issue by rschlussel** [prestodb/presto#13223]
travis presto-raptor tests have lots of major gc ( >3K lines logged of major gc compared to ~300 for the presto-tests build).  

After https://github.com/prestodb/presto/pull/13173 the test sometimes fails due to exceeding log length.  The "hanging" tests always happen after tons of major gc activity.  I think rather than disabling the thread dump when tests aren't making progress we should figure out how to reduce the gc activity. 

https://api.travis-ci.org/v3/job/571431072/log.txt is an example failure

Here are the running tests from that time: 
```
2019-08-13T12:56:20.814-0500 WARNING No test started or completed in 8.00m. Running tests:
	com.facebook.presto.raptor.integration.TestRaptorIntegrationSmokeTestBucketed running for 18.87m
	com.facebook.presto.raptor.integration.TestRaptorDistributedQueries::testLargeIn running for 8.05m
	com.facebook.presto.raptor.integration.TestRaptorDistributedQueriesBucketed::testLargeIn running for 8.05m
	com.facebook.presto.raptor.integration.TestRaptorIntegrationSmokeTestWithOptimizedWriter running for 17.90m
	com.facebook.presto.raptor.backup.TestFileBackupStore running for 21.55m
	com.facebook.presto.raptor.integration.TestRaptorIntegrationSmokeTest running for 18.87m
	com.facebook.presto.raptor.integration.TestRaptorIntegrationSmokeTestBucketedWithOptimizedWriter running for 18.40m
	com.facebook.presto.raptor.integration.TestRaptorDistributedQueries running for 21.55m
	com.facebook.presto.raptor.integration.TestRaptorDistributedQueriesBucketed running for 21.49m
	com.facebook.presto.raptor.integration.TestRaptorIntegrationSmokeTestMySql running for 18.37m.

```

I've seen the largeIn test in previous logs.  I haven't dug into why it would cause full GC, but I think we should disable it for raptor.  It's already disabled for jdbc tests due to h2 not being able to handle it #4685, and I notice the raptor query runner is also based on h2.

The other thing that concerns me from that list is `TestFileBackupStore`.  All the other tests are classes that represent a lot of tests, but why is TestFileBackupStore running for so long when it's only 2 tests?

@highker what do you think? Any ideas what could be causing the heavy GC activity?

**Comment by rschlussel** [comment]
The running tests during  https://api.travis-ci.org/v3/job/566175028/log.txt are exactly the same (this was from when the time limit was set to 5m rather than 8m) 

```
	com.facebook.presto.raptor.integration.TestRaptorIntegrationSmokeTestBucketed running for 15.15m
	com.facebook.presto.raptor.integration.TestRaptorDistributedQueries::testLargeIn running for 5.03m
	com.facebook.presto.raptor.integration.TestRaptorDistributedQueriesBucketed::testLargeIn running for 5.03m
	com.facebook.presto.raptor.integration.TestRaptorIntegrationSmokeTestWithOptimizedWriter running for 14.18m
	com.facebook.presto.raptor.backup.TestFileBackupStore running for 17.71m
	com.facebook.presto.raptor.integration.TestRaptorIntegrationSmokeTest running for 15.15m
	com.facebook.presto.raptor.integration.TestRaptorIntegrationSmokeTestBucketedWithOptimizedWriter running for 14.66m
	com.facebook.presto.raptor.integration.TestRaptorDistributedQueries running for 17.71m
	com.facebook.presto.raptor.integration.TestRaptorDistributedQueriesBucketed running for 17.65m
	com.facebook.presto.raptor.integration.TestRaptorIntegrationSmokeTestMySql running for 14.66m.

**Comment by highker** [comment]
We have about 1.7K GC lines after #13237. @rschlussel, do we believe that is good for now?
