### ISSUE TITLE
woker lost one after another，when cluster load is heavy

### ISSUE THREAD

**Issue by ImTangYun** [prestodb/presto#13238]

**Comment by ImTangYun** [comment]
-server
-Xms32G
-Xmx32G
-XX:+UseG1GC
-XX:+ParallelRefProcEnabled
-XX:ParallelGCThreads=20
-XX:+ExplicitGCInvokesConcurrent
-XX:MaxMetaspaceExpansion=2G
-XX:+HeapDumpOnOutOfMemoryError
-XX:OnOutOfMemoryError=kill -9 %p
-XX:+PrintGCDetails
-XX:+PrintGCDateStamps
-XX:+PrintGCTimeStamps
-XX:+UseGCLogFileRotation
-XX:NumberOfGCLogFiles=30
-XX:GCLogFileSize=10m
-XX:+HeapDumpOnOutOfMemoryError

**Comment by ImTangYun** [comment]
num     #instances         #bytes  class name
----------------------------------------------
   1:       5604077    23258512608  [B
   2:       5655100    10527962824  [I
   3:       2927799     9619493640  [J
   4:       5571398      356569472  io.prestosql.spi.block.VariableWidthBlock
   5:       5583793      312692408  io.airlift.slice.Slice
   6:       2862876      160321056  io.prestosql.spi.block.LongArrayBlock
   7:        108240      154553776  [Lio.prestosql.spi.block.Block;
   8:        110136       52880744  [Z
   9:        237086       45926152  [C
  10:        108918       37309952  [Ljava.lang.Object;
  11:         89140       25893976  [Ljava.lang.String;
  12:          1356       11796880  [D
  13:        457751       10986024  java.util.concurrent.atomic.AtomicLong
  14:         83268        8659872  java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask
  15:        166836        8008128  org.antlr.v4.runtime.atn.ATNConfig
  16:        156731        7523088  java.util.Hashtable$Entry
  17:        230645        7380640  java.lang.String
  18:         83680        7363840  io.prestosql.operator.PageBufferClientStatus
  19:          3338        6380000  [Lorg.antlr.v4.runtime.dfa.DFAState;
  20:        130430        6260640  java.util.concurrent.ConcurrentHashMap$Node
  21:        107459        6017704  io.prestosql.spi.Page
  22:        180759        5784288  io.airlift.units.DataSize
  23:          1818        5522536  [Ljava.nio.ByteBuffer;
  24:         24229        4080560  java.lang.Class
  25:         79336        3808128  io.airlift.stats.DecayCounter
  26:         46185        3694800  io.prestosql.spi.block.VariableWidthBlockBuilder
  27:         56575        3620800  io.prestosql.spi.block.LongArrayBlockBuilder
  28:         48622        3500784  org.joda.time.chrono.ZonedChronology$ZonedDateTimeField
  29:         15393        3325640  [Ljava.util.HashMap$Node;
  30:         20672        3307520  java.lang.reflect.Method
  31:        102228        3271296  io.prestosql.spi.block.BlockBuilderStatus
  32:         10391        3158864  io.prestosql.operator.OperatorStats
  33:         94940        3038080  io.airlift.units.Duration
  34:         59595        2860560  java.util.HashMap$Node
  35:          2407        2791552  [Ljava.util.Hashtable$Entry;
  36:         57276        2291040  java.util.ArrayList

**Comment by ImTangYun** [comment]
anyone knows the reason or solution?

**Comment by viczhang861** [comment]
Could you provide more information? are workers lost within a few minutes? how many?what is your cluster size?

**Comment by ImTangYun** [comment]
when load is high,it is easy to lost, it is a rand time when to lost,our cluster have size of about 100
