### ISSUE TITLE
I connected hive 3.1 times incorrectly

### ISSUE THREAD

**Issue by majiajue** [prestodb/presto#13252]
version:presto-server-317

setting：
```
connector.name=hive-hadoop2
hive.metastore.uri=thrift://slave1:9083
hive.config.resources=/home/bigdata/installed/presto/presto-server-317/etc/catalog/hadoop/core-site.xml,/home/bigdata/installed/presto/presto-server-317/etc/catalog/hadoop/hdfs-site.xml
```

![image](https://user-images.githubusercontent.com/128642/63263988-9327a580-c2bc-11e9-9b7d-0ca6bae8ddb0.png)

I have configured in hive -site.xml:

```
hive.support.concurrency=false;
hive.txn.manager=org.apache.hadoop.hive.ql.lockmgr.DummyTxnManager;
hive.enforce.bucketing=false;
hive.exec.dynamic.partition.mode=strict;
hive.compactor.initiator.on=false;
hive.compactor.worker.threads=0;
```
Could you please help to solve it?

**Comment by findepi** [comment]
Presto 3xx releases are maintained at https://github.com/prestosql/presto. 
Also, there is the `#troubleshooting` channel on Presto Community Slack (https://prestosql.io/community.html)
