### ISSUE TITLE
one presto on yarn question 

### ISSUE THREAD

**Issue by Xuchaojing** [prestodb/presto#13259]
hi， 
when i deployed presto YARN-Based cluster. i found i cannot configure kafka connector in this cluster. So is there some solutions?

**Comment by shixuan-fan** [comment]
I'm not familiar with kafka connector, but you might want to provide more information (what errors you see, what you've tried) so that other people could help.

**Comment by Xuchaojing** [comment]
thanks shixuan-fan, these days, i have readed the presto-yarn sourcecode, i found there was not the properties options for users to set the kafka schemas files(or any other connectors which using out-setting schema file, cause i write a  oss connector ----- which uses out-setting defined schemas). so i added some properties in the source code to meet my needs.
