### ISSUE TITLE
issue with double division

### ISSUE THREAD

**Issue by pi88dian88** [prestodb/presto#13256]
Before we used presto 0.187, and the below expression result is 0.033.
presto:default> select round(1.0/30, 3)
 _col0
------
 0.033

Now when upgraded to presto 0.221, the expression result is 0.0.
 _col0
------
 0.0

**Comment by rongrong** [comment]
On 0.224 I got the following (same as what you have for 0.187).
```
> select round(1.0/30, 3);
 _col0
-------
 0.033
(1 row)
```

**Comment by ajaygeorge** [comment]
I am seeing the same issue in the latest master.
This seems like an issue in the way parsing is happening and seems to be broken from release `0.198` with this commit `Parse decimal literals as DECIMAL by default`  #10130

@pi88dian88 Starting server with `-Dparse-decimal-literals-as-double=true` seems to be resolving the issue.

**Comment by owenlynch** [comment]
@ajaygeorge  Thanks for that tip:`-Dparse-decimal-literals-as-double=true`
It also resolves the issue reported in #13150 Where multiplying by a decimal literal causes IllegalArgumentException.
