### ISSUE TITLE
Feature Request: array function returning combinations of an array

### ISSUE THREAD

**Issue by lwahedi** [prestodb/presto#13267]
Sometimes you need to create combinations of size n from an array. For example:
Given 
['a', 'b', 'c', 'd'] 
We might want:
[(a, b), (a, c), (a, d), (b, c) (b, d), (c, d)]

This is similar to but not identical to ngrams, which will only take sequential combinations. 

This has already been implemented in prestosql:
[Requested here](http://github.com/prestosql/presto/issues/714) 
Tagging @nielkod who filed the original request. 
[Implemented here](http://github.com/prestosql/presto/pull/718) 
This has already been implemented in prestosql. 

Tagging @nielkod who made the initial request but is also waiting for it here.

**Comment by rongrong** [comment]
Seems reasonable. Do you want to implement this in PrestoDB or port that from PrestoSQL?

**Comment by lwahedi** [comment]
Created this pr, https://github.com/prestodb/presto/pull/13283
Not sure how to link it to this issue.
