### ISSUE TITLE
performance - select * from hive.information_schema.columns  takes 90seconds

### ISSUE THREAD

**Issue by tooptoop4** [prestodb/presto#13263]
hive.information_schema.columns has 12k rows spanning 1474 distinct tables, I can't work out why it takes 90seconds to do select * from hive.information_schema.columns

**Comment by shixuan-fan** [comment]
My wild guess is that it might be due to metastore latency in `get_table`.

**Comment by tooptoop4** [comment]
how about ancoption to provide underyling metastore db creds to speed up?
