### ISSUE TITLE
Error  when prestoServer

### ISSUE THREAD

**Issue by dashuai0227** [prestodb/presto#13285]
i want to start prestoServer，but Error occurred .The information is as follows：

iotdb@slave02:/usr/local/presto/presto-server-0.200/bin$ ./launcher run 
Presto requires an Oracle or OpenJDK JVM (found Private Build)
iotdb@slave02:/usr/local/presto/presto-server-0.200/bin$ java -version 
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~16.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
iotdb@slave02:/usr/local/presto/presto-server-0.200/bin$ 

Please give me the right explanation. thanks

**Comment by tooptoop4** [comment]
upgrade presto from 0.200 version to 0.224. https://github.com/prestodb/presto/commit/988f0f2e7bd0a33b2d0d2585cb70eab078fb226c#diff-7744bcf6ae8b3ba4d34755c26beafaa1 was fixed in 0.211

**Comment by dashuai0227** [comment]
> upgrade presto from 0.200 version to 0.224. [988f0f2#diff-7744bcf6ae8b3ba4d34755c26beafaa1](https://github.com/prestodb/presto/commit/988f0f2e7bd0a33b2d0d2585cb70eab078fb226c#diff-7744bcf6ae8b3ba4d34755c26beafaa1) was fixed in 0.211

thanks ，let me try
