### ISSUE TITLE
Prevent queries from being run on http-server.http.port

### ISSUE THREAD

**Issue by tooptoop4** [prestodb/presto#13298]
I have:
http-server.http.port=4321
discovery-server.enabled=true
discovery.uri=http://dns:4321
http-server.authentication.type=PASSWORD,CERTIFICATE
http-server.https.enabled=true
http-server.https.port=6789
http-server.https.keystore.path=keystore.jks
http-server.https.keystore.key=keystorepass

Queries on port 6789 (http-server.https.port) are nice and secure, requiring correct credentials and certs. But queries on port 4321 (http-server.http.port) are insecure, anyone can just enter someone else's username and supply no password then can query anything.

Additionally not sure why so many ports are being listened on, the bottom 3 i understand why (comments on the right) but not the top 3:
sudo netstat -anp | grep 32725
tcp        0      0 0.0.0.0:36439               0.0.0.0:*                   LISTEN      32725/java -- no idea what this port is for
tcp        0      0 0.0.0.0:23161               0.0.0.0:*                   LISTEN      32725/java -- no idea what this port is for
tcp        0      0 0.0.0.0:18599               0.0.0.0:*                   LISTEN      32725/java -- no idea what this port is for

tcp        0      0 0.0.0.0:19581               0.0.0.0:*                   LISTEN      32725/java ---> io.airlift.jmx.JmxAgent
tcp        0      0 0.0.0.0:4321                0.0.0.0:*                   LISTEN      32725/java --> discovery.uri and http
tcp        0      0 0.0.0.0:6789                0.0.0.0:*                   LISTEN      32725/java --> https

**Comment by aweisberg** [comment]
I thought about this a bit more. Maybe the right answer here is that if HTTPS is enabled we change the default for HTTP to disabled. If the user then adds config requesting HTTP also be enabled then we respect that and run the insecure HTTP interface.

**Comment by rschlussel** [comment]
I agree. queries on http can already be disabled using `http-server.http.port`. But maybe we should make this the default if https is enabled.
