### ISSUE TITLE
Prevent webUI from starting

### ISSUE THREAD

**Issue by tooptoop4** [prestodb/presto#13301]
Just want to use Presto for JDBC, have no interest in the WebUI because:
1. Can monitor using other means like jmx exporter, event-listener
2. Deploying a webUI in a large regulated enterprise requires lengthy security review (eg Penetration Test, Vulnerability Scan) and issues pop-up like: why is there no authorization level for admins vs regular users, why is React library using old version....etc

This feature is about introducing a new config flag (webUIEnabled), that when set to false prevents the webUI from starting and only allows JDBC connections

**Comment by y1275963** [comment]
Hi, would like to work on this issue, can you assign it to me?

**Comment by tooptoop4** [comment]
@y1275963 u can raise pr
