### ISSUE TITLE
Add RowExpressionMatcher

### ISSUE THREAD

**Issue by hellium01** [prestodb/presto#13317]
Currently, we frequently need to verify if two `RowExpression` can match each other, or a `RowExpression` can match a certain pattern. `RowExpression` is our internal representation of `Expression`. It has `functionaHandle` and `Type` resolved.   `equals` method implemented on `RowExpression` will only works for very simple cases. It does not handle:
1) `LambdaExpression` can have generated argument name. For example, (x, y) -> x+ y and (x1, y1) -> x1+ y1 should be considered same.
2) `ConstantExpression` can have complex value types. For example, comparing `RowType` and `ArrayType` may need some extra efforts. 
3) For tests, we sometimes want to match a variable with a pattern or an alias. 
4) For tests, we might want to simplify comparison parameteric types such as `VARCHAR` types with different length. 

We need a utility to match two `RowExpression` with all above in consideration.  

A similar example is `ExpressionVerifier` that was used for `Expression`. However, we need to keep the design more generic so that we can reuse the code for both pattern matching (useful for tests) and exact matching (useful for deduplicate sub expressions for example). It will be used in many code path later so also make sure it is well tested.

**Comment by duyquangnguyenhac** [comment]
Can I claim this issue, James

**Comment by highker** [comment]
@duyquangnguyenhac, the issue will be resolved by #13338 by @swapsmagic.
