### ISSUE TITLE
can not use mongodb,failed: Table has no columns

### ISSUE THREAD

**Issue by wwwwwwchun** [prestodb/presto#13326]
when i set the mongodb.properties file under the catalog folder,and reboot the presto,
but when i exec commd select * from mongodb.gf.car1206 limit 10;
the preto rerutn error:
presto> select * from mongodb.gf.carTrack1206;
Query 20190903_104404_00003_jwyig failed: Table has no columns: TableHandle {connectorId='mongodb', connectorHandle='car1206', layout='Optional.empty'}
how can i reslove this problem?
i find in the docs ,the docs do not told me where json file shoud i do.

**Comment by ESKoda** [comment]
Verifique se a estrutura no mongodb tem letras maiúsculas, pois o presto não entende letras maiúsculas
Estou com o mesmo problema!
