### ISSUE TITLE
can not start launcher,when exec the commnd,the system return errors No such file or directory

### ISSUE THREAD

**Issue by wwwwwwchun** [prestodb/presto#13325]
hello,
i use presto-server-0.224,when i start the server,the process dose not start,
my command is "./launcher run",then system retern the err:"ERROR: [Errno 2] No such file or directory"
[root@db bin]# ./launcher run
ERROR: [Errno 2] No such file or directory
how can i reslove this problem?
thanks

**Comment by gongkang** [comment]
我也碰到这个问题了，你是怎么解决的？

**Comment by wwwwwwchun** [comment]
the java env is not set,set your java env,and logging out the system

**Comment by gongkang** [comment]
> the java env is not set,set your java env,and logging out the system

tks
