### ISSUE TITLE
presto MongoDB Connector can not select collection's name is capital letter

### ISSUE THREAD

**Issue by wwwwwwchun** [prestodb/presto#13333]
presto MongoDB Connector can not select collection's name is capital letter,
when i select Lowercase letters's collection,the result is ok,
but when i select capital letter's collection,the result is null,can not resurn any data,
how can i do to reslove problem?
thanks

**Comment by tchunwei** [comment]
I am having same issue too, both database (schema) and collection do not work with capital letter name.

**Comment by zhangzhaohuazai** [comment]
I also found that presto0.279 is case-insensitive to collections：
![image](https://user-images.githubusercontent.com/28680957/221789408-518a7aa4-8ad4-4c3d-bb9e-379bdab974ac.png)
![image](https://user-images.githubusercontent.com/28680957/221789466-36e55b9c-783c-487a-a1cc-98bc118d19d3.png)
