### ISSUE TITLE
Upgrade kudu client to 1.10.0

### ISSUE THREAD

**Issue by qwalker** [prestodb/presto#13359]
Sometimes the kudu connector throws exception of "Invalid call sequence ID in scan request"，and it's said it's a issue of kudu client and it's resolved in 1.9.0:
https://issues.apache.org/jira/browse/KUDU-1868

**Comment by qwalker** [comment]
Hi, How can I get this issue resolved quickly? It's a real issue in our production presto and it should be a safe change, and it's already upgraded in the other 'PrestoSql' repository.

**Comment by SandishKumarHN** [comment]
I will work on this

**Comment by SandishKumarHN** [comment]
@qwalker  here is the PR https://github.com/prestodb/presto/pull/14992

**Comment by elharo** [comment]
This was merged a while back
