### ISSUE TITLE
Query 20190910_093618_00004_2ad6f failed: No nodes available to run query

### ISSUE THREAD

**Issue by ajithsharma87** [prestodb/presto#13368]
Hello , 

  I am getting error Query 20190910_093618_00004_2ad6f failed: No nodes available to run query when trying to retrieve the data from hive , i have configured the multinode cluster with 1 coordinator node and 2 worker nodes 

Regards
AJITH SHARMA

**Comment by rschlussel** [comment]
Can you confirm that your cluster has 2 worker nodes registered. e.g logging into the webui or running select * from system.runtime.nodes.  This usually means your cluster isn't configured correctly and the coordinator doesn't know about the worker nodes.

**Comment by ajithsharma87** [comment]
Hello, 
   I am able to see as 2 active worker nodes on the webui.. do we have to configure the hive connector properties even on the worker nodes? 
ThanksAjith 
 
  On Wed, Sep 11, 2019 at 0:34, Rebecca Schlussel<notifications@github.com> wrote:   
Can you confirm that your cluster has 2 worker nodes registered. e.g logging into the webui or running select * from system.runtime.nodes. This usually means your cluster isn't configured correctly and the coordinator doesn't know about the worker nodes.

**Comment by ajithsharma87** [comment]
Also please let me know where should i  specify the worker node name in the coordinator node configuration , briefly update me about the coordinator and the worker node configuration

**Comment by rschlussel** [comment]
yes, you should configure the hive connector on the worker nodes too. 

You don't need to specify the worker node name in the coordinator configuration.  workers announce themselves to the coordinator (that's what the discovery.uri property is used for in the worker configuration).

**Comment by ajithsharma87** [comment]
Yes I have configured the hive connector on all the worker node and also have specified the coordinator node on the discovery uri in the worker node configuration...why is it still giving as nodes not found? 

 
 
  On Wed, Sep 11, 2019 at 20:08, Rebecca Schlussel<notifications@github.com> wrote:   
yes, you should configure the hive connector on the worker nodes too.

You don't need to specify the worker node name in the coordinator configuration. workers announce themselves to the coordinator (that's what the discovery.uri property is used for in the worker configuration).

**Comment by ajithsharma87** [comment]
hello , 
   Is it a bug in the cluster based installation? since things are working fine in the single node setup  
ThanksAJITH SHARMA 
    On Thursday, September 12, 2019, 11:12:19 PM GMT+5:30, Rebecca Schlussel <notifications@github.com> wrote:  
 
 
That's a different error, so it sounds like the first issue is resolved and now you're encountering another problem. What's the full stacktrace?

For your config files, I assume the config properties running into each other without spaces/newlines or comma separation or anything is just the way you printed it here, right? otherwise, that should be fixed

I also see two conflicting properties: hive.hdfs.authentication.type=NONEhive.hdfs.authentication.type=KERBEROS

Also, make sure your hadoop is configured to allow impersonation: https://prestodb.github.io/docs/current/connector/hive-security.html#configuring-hadoop-impersonation

**Comment by rschlussel** [comment]
Since you say it's working on the single node set up, it sounds like your worker nodes aren't configured correctly.  Make sure you've followed all the steps here: https://prestodb.github.io/docs/current/connector/hive-security.html#configuring-hadoop-impersonation.  Have you distributed the keytab file to all nodes in the cluster?

**Comment by ajithsharma87** [comment]
Hello,
     I have distributed keytab on all the nodes also did kdestroy and did kinit once again... Still giving same error , not able to access the hdfs through impersonation
Thanks
 
 
  On Wed, Sep 18, 2019 at 20:11, Rebecca Schlussel<notifications@github.com> wrote:   
Since you say it's working on the single node set up, it sounds like your worker nodes aren't configured correctly. Make sure you've followed all the steps here: https://prestodb.github.io/docs/current/connector/hive-security.html#configuring-hadoop-impersonation. Have you distributed the keytab file to all nodes in the cluster?
