### ISSUE TITLE
we want to install mysql connector 

### ISSUE THREAD

**Issue by ajithsharma87** [prestodb/presto#13378]
hello 
 
   I am planning to implement the mysql connectorin the single node cluster , is it  required to have mysql installed on the machine which i am implementing the connector? 

Thanks
AJITH SHARMA

**Comment by ajithsharma87** [comment]
Error running command: java.io.IOException: unexpected end of stream on Connection{ipfavpapp02.amr.corp.intel.com:1433, proxy=DIRECT hostAddress=ipfavpapp02.amr.corp.intel.com/10.64.88.56:1433 cipherSuite=none protocol=http/1.1}

when connecting to mysql from the CLI , i have configured the mysql connector

**Comment by bigdatashiva** [comment]
yes, mysql has to installed on the machine.
