### ISSUE TITLE
presto configuration in Superset

### ISSUE THREAD

**Issue by bigdatashiva** [prestodb/presto#13380]
Hi All, 

Can anyone please suggest me how to configure presto in apache superset.
like what is the syntax/format for SQLAlchemy URI and other parameters.
Please do respond as soon as you see this message.

am accessing cassandra from presto and the same am trying to configure thru presto in apache superset.

**Comment by play-io** [comment]
`presto://<hostname>:<port>/<catalog_name>/<keyspace>`
Eg. `presto://presto:8080/cassandra/trxkeyspace`

**Comment by bharath0208** [comment]
@play-io What do you mean by keyspace is it the schema. 

Also any idea on how we can implement our presto JDBC driver in the superset. We have modified the JDBC code and created our own presto driver.   I wanted to use this driver instead of the default one
