### ISSUE TITLE
is there any way to get the cluster cpu information ?

### ISSUE THREAD

**Issue by jlfsdtc** [prestodb/presto#13383]
Hello, I am searching a way to get the CPU usage information of cluster
/v1/cluster only can get the  totalCpuTimeSecs, is there any way to get other mess?
like use core number 
thxs

**Comment by rongrong** [comment]
At Facebook we gather those information from the machines directly.

**Comment by jlfsdtc** [comment]
i think so.
just want use restful api to get them , be lazy :)

**Comment by cemcayiroglu** [comment]
could you more details about your use case? CPU usage is very general term.

**Comment by y1275963** [comment]
would like to get assigned. can you assign to me

**Comment by jlfsdtc** [comment]
@cemcayiroglu For example:  CPU cores number,and CPU usage
