### ISSUE TITLE
REST service data response variations

### ISSUE THREAD

**Issue by calvaradocl** [prestodb/presto#13390]
Hello,

I'm using Presto 0.220 on EMR with Hive in order to query a small S3 repository (it just has around 4K data rows). But when querying over the REST API (on /v1/statement), I'm getting different data responses in the JSON payload provided by the GET request, but when I look up the query info on the UI, the returned rows number is the one expected, I don't know if there is a way to set-up how many rows are returned, because it's random, this gets worse when running parallel queries to presto.

I appreciate any feedback on this, thanks.

**Comment by calvaradocl** [comment]
Yes, using nextUri until receiving the data results, is there a next uri when the results are returned? In my case I'm not getting one.

**Comment by cemcayiroglu** [comment]
Could you provide some samples?
