### ISSUE TITLE
hive connector read from .csv.zip files (not gz/gzip)

### ISSUE THREAD

**Issue by tooptoop4** [prestodb/presto#13427]

**Comment by shixuan-fan** [comment]
Sorry I'm trying to understand. Is this a feature request?

**Comment by tooptoop4** [comment]
yes

**Comment by tooptoop4** [comment]
Apache Drill supports this: https://github.com/apache/drill/pull/1879/files    https://issues.apache.org/jira/browse/DRILL-5674
it makes use of:
import java.util.zip.ZipEntry;
 import java.util.zip.ZipInputStream;
 import java.util.zip.ZipOutputStream;
