### ISSUE TITLE
Support percentile_cont and percentile_disc

### ISSUE THREAD

**Issue by ghost** [prestodb/presto#13423]
Please add support for the SQL standard functions percentile_cont & percentile_disc already supported by most major SQL databases

- https://issues.apache.org/jira/browse/HIVE-16255
- https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#percentile_cont

**Comment by shixuan-fan** [comment]
cc @rongrong I think this makes sense, does it sound reasonable to you?

**Comment by rongrong** [comment]
SQL spec defines this as `<inverse distribution function>` in `10.9 <aggregation function>`. Very reasonable request. Though Presto currently don't support any ordered set function. The implementation is non-trivial.

**Comment by rongrong** [comment]
The implementation can probably use changes from #7682.

**Comment by silvia-lara** [comment]
Commenting to open this issue again. This would be a great feature to have, the workarounds are just too messy.

**Comment by vnemec-vendavo** [comment]
yep. I do not like the workarounds either.
