### ISSUE TITLE
Mongodb case sensitive collection support

### ISSUE THREAD

**Issue by ludi1981** [prestodb/presto#13421]
Hi All,

presto 0.202 can't get the meta data of Mongodb collections if this is a camel case schema. By searching, I found this was fixed. URL: https://github.com/prestodb/presto/pull/6993 

Does someone know which version fixed this? I don't see this fix in release notes from version 0.203 to 0.225. 

Thansk,
Dillon

**Comment by tooptoop4** [comment]
That PR was never merged

**Comment by ludi1981** [comment]
> That PR was never merged

ok. thanks.
