### ISSUE TITLE
How to use SSL in JDBC Driver

### ISSUE THREAD

**Issue by lordk911** [prestodb/presto#13435]
hi,all
   I'm using presto 0.217 , My ETL-TOOL need to connect presto with JDBC , and it's need password must be not empty. I found that ,when use password with jdbc ,presto need to enable SSL. I've sucessfully started presto cluster with SSL。
but I can't connect the clusert with CLI and JDBC .
when I try to connect with cli :
```
./presto --server https://10.8.130.51:8787 --keystore-path /home/devuser/presto-0.217/etc/keystore.jks --keystore-password 123456

presto> select * from elasticsearch.shakespeare.line limit 10;
Error running command: javax.net.ssl.SSLPeerUnverifiedException: Hostname 10.8.130.51 not verified:
    certificate: sha256/1ZyrznU2QoH6w8pvYEiVu9LDvn8nDMTJWPtxKrTqcFE=
    DN: CN=*.gaojihealth.com, OU=Unknown, O=Unknown, L=Unknown, ST=Unknown, C=Unknown
    subjectAltNames: []
```
Please Help!

**Comment by shixuan-fan** [comment]
Can you run cli with `--debug` to get the full stacktrace? It looks like the hostname of the server is not verified, maybe you need to set truststore as well?
