### ISSUE TITLE
JDBC Driver - low performance of getColumns method

### ISSUE THREAD

**Issue by bohyn** [prestodb/presto#13456]
Reading columns metadata by using Presto JDBC driver's method PrestoDatabaseMetaData.getColumns() method is very slow.

We have Presto (0.225) connected to Hive catalog with hundreds of tables. This particular problem was observed with Spotfire as a JDBC client. By looking at the driver source, calling getColumns() method for one table results in executing following query over "system.jdbc.columns" view:

`SELECT TABLE_CAT, TABLE_SCHEM, TABLE_NAME, COLUMN_NAME, DATA_TYPE,
  TYPE_NAME, COLUMN_SIZE, BUFFER_LENGTH, DECIMAL_DIGITS, NUM_PREC_RADIX,
  NULLABLE, REMARKS, COLUMN_DEF, SQL_DATA_TYPE, SQL_DATETIME_SUB,
  CHAR_OCTET_LENGTH, ORDINAL_POSITION, IS_NULLABLE,
  SCOPE_CATALOG, SCOPE_SCHEMA, SCOPE_TABLE,
  SOURCE_DATA_TYPE, IS_AUTOINCREMENT, IS_GENERATEDCOLUMN
FROM system.jdbc.columns
WHERE TABLE_SCHEM LIKE 'test_schema' ESCAPE '\' AND TABLE_NAME LIKE 'test_table' ESCAPE '\'
ORDER BY TABLE_CAT, TABLE_SCHEM, TABLE_NAME, ORDINAL_POSITION`

According to my observations, the query actually goes over all tables in meta catalog, even when there is a filter for _TABLE_NAME_. When I execute this query manually from CLI, it usually fails on some complete unrelated problem with metadata of other table (which is ok, as that other table has incorrect reference to external Avro schema, but I'd expect it shouldn't be examined at all as it should be filtered out by _TABLE_NAME_ param) after quite a long time (~30 minutes).

When I change that query to use "=" operators instead of "LIKE" for comparison of _TABLE_NAME_ and _TABLE_SCHEM_, the performance increases rapidly. Isn't this more a problem of query optimizer?

I believe filtering on _TABLE_NAME_ and _TABLE_SCHEM_ using "LIKE" operator should prevent touching metadata discovery of tables, that are excluded by this filter, but I have an impression the behaviour is opposite.

**Comment by Yogaflre** [comment]
**I have the same experience.**
Why not use "=" ?

**Comment by bohyn** [comment]
I guess "=" is nut used, because in Java SQL DatabaseMetaData, the getColumns method is defined in a way, that schema, table and column can be specified using "patterns": https://docs.oracle.com/javase/7/docs/api/java/sql/DatabaseMetaData.html#getColumns(java.lang.String,%20java.lang.String,%20java.lang.String,%20java.lang.String)

That means, partial match should be supported.

**Comment by Yogaflre** [comment]
Thanks for your explanation.
Do you have any ideas to solve the current problem?
