### ISSUE TITLE
How long will QUERY DETAILS records remain?

### ISSUE THREAD

**Issue by imperio-wxm** [prestodb/presto#13454]
I found that after a long time or more query records, the old page could not be viewed.

![image](https://user-images.githubusercontent.com/8111349/65663075-6491ad00-e068-11e9-82ff-e17647490c7f.png)

**Comment by rschlussel** [comment]
The query.min-expire-age query.max-history configuration prooperties set how long queries will be kept around for.  Queries will be removed when query.min-expire-age is reached and there are more than query.max-history queries in the query history. The default values are 15 minutes and 100 queries respectively.

**Comment by imperio-wxm** [comment]
@rschlussel 

Thanks for your reply.

If I increase the parameter, will it put pressure on the coordination node or web ui?

**Comment by rschlussel** [comment]
Depends how much you increase it, the load and capacity of your machines, etc. but increasing these numbers too much could definitely put pressure on the coordinator.  I'm not sure where that cutoff would be.  If you're looking to keep all query history, you could also implement an EventListener and log the execution information to a database.  See https://prestodb.io/docs/current/develop/event-listener.html and the interface https://github.com/prestodb/presto/blob/master/presto-spi/src/main/java/com/facebook/presto/spi/eventlistener/EventListener.java

**Comment by imperio-wxm** [comment]
Thanks, this helper is great.
