### ISSUE TITLE
windows platform maven building is not supported

### ISSUE THREAD

**Issue by Fnck** [prestodb/presto#13470]
1. mvnw command can't run in windows
2. when using mvn command, the presto-maven-plugin will generate service descriptor, and can't recognize the windows fold separator.

**Comment by Fnck** [comment]
I would like to change the preso-maven-plugin to adapt windows platform, but the code seems not open-sourced.

**Comment by Fnck** [comment]
The function com.facebook.presto.maven.ServiceDescriptorGenerator#findImplementationsOf should use the common file separater(System.getProperty("file.separator")), not use the '/' explicitly

**Comment by hardzhang** [comment]
Requirements
    Mac OS X or Linux
