### ISSUE TITLE
Row type must have at least one parameter

### ISSUE THREAD

**Issue by rajeshd3v** [prestodb/presto#13547]
I'm getting the below error when i tried to execute the query "**_select * from information_schema.columns;_**"

data source **mongodb**

```

presto:default> select * from information_schema.columns;

Query 20191014_101110_00022_s7xsz, FAILED, 1 node
Splits: 17 total, 0 done (0.00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20191014_101110_00022_s7xsz failed: java.lang.IllegalArgumentException: Row type must have at least one parameter
```

Thanks in advance. 🙏

**Comment by rajeshd3v** [comment]
i had mongodb version 4+ and then after scratching my head for the two days i downgraded mongodb version to 3.4. Eureka ! now i'm leaving early from my office.

**Comment by cfga** [comment]
Hitting this problem right now. Don't have the option of downgrading mongo, though. Is there any workaround or plan to fix this? Happens only on one of the three collections I have.

**Comment by cfga** [comment]
Might try to debug this soon, but maybe it is a problem already known to someone
