### ISSUE TITLE
LIKE operator not working with [] square brackets

### ISSUE THREAD

**Issue by victorflorintsev** [prestodb/presto#13555]
I'm slightly new to presto but it looks like the square brackets in the LIKE operator do not work as expected. This would be nice to have so I thought I'd start an issue.

`CREATE TABLE test (first_name VARCHAR(30));`
`INSERT INTO test VALUES ('abc'), ('dan'), ('cPk'), ('c$k'), ('C$k'), ('C$S');`
`SELECT * FROM test WHERE first_name LIKE '[cC][pP$][kKsS]';`

Expected: Returned all the rows except the first two

Actual: 0 records returned

**Comment by rongrong** [comment]
That's not how LIKE operator works. What you want is probably `regexp_like`: https://prestodb.github.io/docs/current/functions/regexp.html

**Comment by victorflorintsev** [comment]
That's how it works in SQL Server. 

For anyone wondering how to actually structure it to make this work similar here is a guide: (There is no other documentation on the internet)

Query:

     SELECT * FROM test
     WHERE regexp_like(first_name, '^[cC][pP\$][sSkK]$')

Query / Pattern Explanation:

     regexp_like finds rows that match the pattern: '^[cC][pP\$][sSkK]$'

     ^ is beginning of line,

     $ is end,

     Anything in [ ] means it must match one and only one of those characters inside the [ ],

     The / is an escape so that instead of "end of line" the $ is interpreted as a literal $ character.
