### ISSUE TITLE
Company or Vendor that provide Enterprise Support for Presto?

### ISSUE THREAD

**Issue by thammuio** [prestodb/presto#13563]
Is there any Vendor or Company that provides enterprise support for Presto?

**Comment by findepi** [comment]
The information about available Enterprise support options was obliterated from project website in https://github.com/prestodb/prestodb.github.io/pull/39/files.
So I recommend you check out the prestosql website for enterprise support options: https://prestosql.io/resources.html#support

**Comment by vijaymann** [comment]
[That page ](https://prestosql.io/resources.html#support) needs editing/overhaul - [Qubole ](https://www.qubole.com/developers/presto-on-qubole/) offers enterprise support for a managed Presto offering across AWS, Azure and GCP.
