### ISSUE TITLE
Remove NullableValue class

### ISSUE THREAD

**Issue by highker** [prestodb/presto#13585]
`RowExpression` now is in SPI. It's time to replace `NullableValue` with `ConstantExpression`.

https://github.com/prestodb/presto/blob/3060c65a1812c6c8b0c2ab725b0184dbad67f0ed/presto-spi/src/main/java/com/facebook/presto/spi/predicate/NullableValue.java#L25

Need to evaluate the hash function difference
```java
    @Override
    public int hashCode()
    {
        int hash = Objects.hash(type);
        if (value != null) {
            hash = hash * 31 + (int) type.hash(Utils.nativeValueToBlock(type, value), 0);
        }
        return hash;
    }

**Comment by cemcayiroglu** [comment]
https://github.com/prestodb/presto/pull/13596

**Comment by rongrong** [comment]
Should we add a `@deprecated` first and wait for a few releases before actually removing this?
