### ISSUE TITLE
Parquet metadata length in in hive catalog could increase HDFS/S3 read speed

### ISSUE THREAD

**Issue by rdettai** [prestodb/presto#13599]
When reading a parquet file, you first need to read the footer and for this you need to read its length, that are the 4 bytes just before the final PAR1 magic number. This is done like this:

https://github.com/prestodb/presto/blob/947b5b90bbf8c4d66dcff5432cd9625c115e6918/presto-parquet/src/main/java/com/facebook/presto/parquet/reader/MetadataReader.java#L92

This incurs an extra network call to hdfs/s3 that could be avoided if the footer length was stored in the hive catalog.

Do you think it is worth it having this data duplicated to the catalog?

**Comment by ryanrupp** [comment]
I was probably going to log an enhancement issue to cache Parquet metadata as a change was recently done to support this for ORC metadata see https://github.com/prestodb/presto/pull/13501

**Comment by ryanrupp** [comment]
Logged #13921
