### ISSUE TITLE
i have some question for hive bucket table

### ISSUE THREAD

**Issue by fengfengaaa** [prestodb/presto#13621]
![image](https://user-images.githubusercontent.com/29369246/67757726-507e0880-fa77-11e9-8359-d60ff3f8bd41.png)
i want to read multi file per bucket and merge it

**Comment by shixuan-fan** [comment]
What do you mean by "merge it"? 

Bucket number is a hive table property, and iirc each bucket would be one file in its partition directory. So I'm not sure I understand what you want to achieve.

**Comment by fengfengaaa** [comment]
now multi file per bucket ,i want to query it. and query result is merged

**Comment by shixuan-fan** [comment]
I'm not entirely sure what you are trying to achieve. You might want to provide a high level goal and more context. 

Could you provide the `SHOW CREATE TABLE` result for your table?

Right not per my understanding, your "bucket" is actually across multiple partitions given the layout of the screen shot. So they are actually different buckets: bucket 1 in partition 0606, bucket0 in partition 0609 and bucket 0 in partition 0610.

**Comment by fengfengaaa** [comment]
this is presto show create table 
![image](https://user-images.githubusercontent.com/29369246/67911524-ddcd7400-fbc1-11e9-997a-20aa0e990ec7.png)

**Comment by shixuan-fan** [comment]
Ah interesting so your table is actually not partitioned, then I'm not sure why they are writing to different directories, but I guess it might be by intention. Why is there only 3 files when the table should have 4 buckets? Is the table written by Presto as well?

Also, you could just do copy paste and use markdown, it would be easier to check than a screenshot :)

**Comment by fengfengaaa** [comment]
the table create by hive, We have our own design for the hive table，your means only create table by presto the multi file per bucket is Effective

**Comment by shixuan-fan** [comment]
Oh okay. I'm not sure I understand your statement but I'm only familiar with the settings where each bucket contains one file =/
