### ISSUE TITLE
Questions for more nodes vs. single node

### ISSUE THREAD

**Issue by datavisorfrankhe** [prestodb/presto#13622]
Hello,
I am using EC2 to test presto and I really hope to see the difference between more nodes and one node, please see below output:

Query 20191029_160545_00014_bi7xd, FINISHED, 1 node
Splits: 49 total, 49 done (100.00%)
0:02 [1.62M rows, 0B] [688K rows/s, 0B/s]

Query 20191029_160842_00017_bi7xd, FINISHED, 2 nodes
Splits: 81 total, 81 done (100.00%)
0:02 [1.62M rows, 0B] [666K rows/s, 0B/s]

I wondered if this is correct, in my opinion, I think if I added one node, the speed should be doubled, but if you look at output, for 1 node, it is 688k rows/s and 666k rows/s

Does this mean the analyzing speed is not changed even if we increase node? But the splits is indeed doubled. Wondered why rows per second has no change.

Thanks

**Comment by rongrong** [comment]
Depending on the query shape you might or might not be able to benefit from more nodes. Without knowing your query shape and data pattern it's hard to say why you don't benefit from adding another machine.

**Comment by datavisorfrankhe** [comment]
select FLOOR(score*10), count(*) from mysql.data.detectedusers group by FLOOR(score*10);

Do you think group count can benefit from multi nodes?
