### ISSUE TITLE
why presto CLI requries keystore and password

### ISSUE THREAD

**Issue by th3333** [prestodb/presto#13640]
According to https://prestodb.github.io/docs/current/security/cli.html, when using presto CLI, it requires:

  --keystore-path /tmp/presto.jks \
  --keystore-password password \

The question is why a client needs to have the jks and password (which should be a secret on the presto server side, right?)

**Comment by SolidBrave** [comment]
I don't get it either, it would have to be the Truststore, on the client side. 

The KeyStore belongs to the server and contains the server certificate and the private key. As a client, the server presents its certificate to me and I compare it with the certificates in my Truststore.
