### ISSUE TITLE
presto kerberos configuration

### ISSUE THREAD

**Issue by anuhewa** [prestodb/presto#13641]
Hi All ,

I am trying to config kerberos on presto cordinator
i am using company Active directory as kdc and not MIT kdc

My configuration as below
I have below user configured on KDC

I am getting below error
Kindly help

my presto config

[root@host1 etc]# cat config.properties
coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=808x
query.max-memory=400GB
query.max-memory-per-node=32GB
query.max-total-memory-per-node=40GB
discovery-server.enabled=true
discovery.uri=http://host1.dc.COMPANY.com:808x
http-server.https.enabled=true
http-server.https.port=8443
http-server.https.keystore.path=/datan1/presto/presto-server-0.226/etc/keystore/keystore/presto.keystore.jks
http-server.https.keystore.key=password
http-server.authentication.type=KERBEROS
http.server.authentication.krb5.service-name=sys_presto
http.server.authentication.krb5.principal-hostname=COMPANY.COMPANY.COM
http.server.authentication.krb5.keytab=/datan1/presto/presto-server-0.226/etc/sys_presto.keytab
http.authentication.krb5.config=/etc/krb5.conf
[root@host1 etc]#

[root@host1etc]# cat /etc/krb5.conf
[libdefaults]
default_realm = COMPANY.COMPANY.COM
dns_lookup_kdc = true
dns_lookup_realm = false
ticket_lifetime = 86400
renew_lifetime = 604800
forwardable = true
default_tgs_enctypes = rc4-hmac des3-hmac-sha1 arcfour-hmac des-hmac-sha1 des-cbc-md5 des-cbc-crc
default_tkt_enctypes = rc4-hmac des3-hmac-sha1 arcfour-hmac des-hmac-sha1 des-cbc-md5 des-cbc-crc
permitted_enctypes = rc4-hmac des3-hmac-sha1 arcfour-hmac des-hmac-sha1 des-cbc-md5 des-cbc-crc
udp_preference_limit = 1
kdc_timeout = 9000
ignore_acceptor_hostname = true
[realms]
COMPANY.COMPANY.COM = {
kdc = host2.COMPANY.COMPANY.com
admin_server = host2.COMPANY.COMPANY.com
}

=====================================================
client side connect

[root@host1 presto_client]# ./presto   --server https://host1.dc.company1.com:8443   
--krb5-config-path /etc/krb5.conf   
--krb5-principal sys_presto@COMPANY.COMPANY.COM   
--krb5-keytab-path /datan1/presto/presto-server-0.226/etc/sys_presto.keytab   
--krb5-remote-service-name sys_presto 
--keystore-path /datan1/presto/presto-server-0.226/etc/keystore/keystore/presto.keystore.jks   
--keystore-password password   --catalog catalog1   --schema dbname;
error as below

1) Configuration property 'http.server.authentication.krb5.principal-hostname' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:233)

1 error
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Configuration property 'http.server.authentication.krb5.principal-hostname' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:233)

1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:159)
        at com.google.inject.internal.InternalInjectordiCreator.build(InternalInjectorCreator.java:106)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:240)
        at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:128)
        at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:74)
kindly assist

Regards
Anushke

**Comment by Aniruddd** [comment]
I am also facing the same issue.

**Comment by SolidBrave** [comment]
i fixed this problem on my side:

http.server.authentication.krb5.principal-hostname

ist not the real property. If you go trough the debug you find the emtpy property:

http.authentication.krb5.principal-hostname

the documentation seems to have a mistake here.
