### ISSUE TITLE
MongoCommandException: Command failed with error 166: 'Namespace ... is a view, not a collection'

### ISSUE THREAD

**Issue by pomykalamichal** [prestodb/presto#13753]
Hi,
we would like to simplify queries run via Presto as most of the data in our Mongo are nested json objects.
To avoid using json function operations (https://prestodb.io/docs/current/functions/json.html) we would like to use dedicated views created in MongoDB. 

After creation of the dedicated views by using https://docs.mongodb.com/manual/reference/method/db.createView/  and adding view definition in mongo schema we gets error : MongoCommandException: Command failed with error 166: 'Namespace XYZ is a view, not a collection'. 

Is there any option to read MongoDB views in Presto, the same as it is e.g. for PGSQL db ? 
Could you be so kind and share your recommendations, workarounds, if any?

**Comment by yingsu00** [comment]
@pomykalamichal How did you create the view? Was it through presto-mongodb connector?

**Comment by pomykalamichal** [comment]
View was created via robo 3T and mentioned command in previous post. Additionally I can read the data with no errors.

**Comment by pomykalamichal** [comment]
Hi, does any one can help with above problem?

**Comment by pomykalamichal** [comment]
resolved by : https://github.com/prestosql/presto/issues/2156
