### ISSUE TITLE
Relax struct coercion policy in Hive connector

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#13750]
Allow for name changes of fields as long as their types match. E.g. change the rule from

```
        // Rule:
        // * Fields may be added or dropped from the end.
        // * For all other field indices, the corresponding fields must have
        //   the same name, and the type must be coercible.
```

to

```
        // Rule:
        // * Fields may be added or dropped from the end.
        // * For all other field indices, field type must be coercible.
```

See com.facebook.presto.hive.HiveCoercionPolicy#canCoerceForStruct

CC: @rongrong @highker @wenleix @rschlussel @arhimondr

**Comment by mbasmanova** [comment]
CC: @kaikalur

**Comment by mbasmanova** [comment]
from @rongrong 

---
field name should be an identifier which should not be case sensitive. So that should be a bug. As for coercion, according to SQL spec:

```
Row type RT2 is a subtype of data type RT1 if and only if RT1 and RT2 are row types of the same degree and, in every n-th pair of corresponding field definitions, FD1n in RT1 and FD2n in RT2, the <field name>s are equivalent and the <data type> of FD2n is a subtype of the <data type> of FD1n.
```

Seems like the current coercion behavior is correct (minus the case sensitivity).

**Comment by arhimondr** [comment]
>  the <field name>s are equivalent

e.g: `field_name` is equivalent to `'FIELD_NAME'`. I remember that from the SQL spec.
