### ISSUE TITLE
Unnest Optimizations

### ISSUE THREAD

**Issue by yingsu00** [prestodb/presto#13751]
UnnestOperator is the top 5 operator in terms of CPU consumption in Facebook workload. A recent optimization on UnnestOperator uses DictionaryBlock instead of copying the blocks and tremendously improved the performance. However there’re still optimization opportunities. In this issue we discuss the two improvements on unnest, namely vectorized execution and bulk copy of the Blocks.

### Vectorized execution
The current implementation constructs the output blocks in the row-by-row manner:

```
for each incoming row
    for each replicated column
        append the repeated values by adding ids to the DictionaryBlock
    for each unnest column
        append the unnested  values by adding ids to the DictionaryBlock if possible. 
        Otherwise append the value to BlockBuilder.
    if there is ordinality column
        append the oridinality to the BlockBuilder
```

We can see that the Block construction is done row by row.  As a key principles of vectorized execution, we want to optimize the operations in a column by column manner, which uses tight loops and allows the CPU parallelize the work as much as possible. An example of such loop of building the replicated block is like this:

```
    public Block buildOutputBlock(int[] maxEntries, int offset, int length, int totalEntries)
    {
        int[] ids = new int[totalEntries];

        int fromPosition = 0;
        for (int i = 0; i < length; i++) {
            int toPosition = fromPosition + maxEntries[offset + i];
            Arrays.fill(ids, fromPosition, toPosition, sourcePosition++);
            fromPosition = toPosition;
        }

        return new DictionaryBlock(totalEntries, source, ids);
    }

```
This allows the JVM to generate CPU friendly loops. The JMH benchmark shows at least 3x improvement for cases where no null needs to be inserted for all data types.

### Computation of maxEntries array and batch size
To make the above loop possible, we pre-compute the max cardinalities for all columns for each row after unnesting and keep it in the maxEntries array in the operator. We also compute the entry counts for each unnester and keep them in separate arrays in each unnester. This way the memory can be accessed sequentially and the computation can be reused. The size of these arrays should require little memory overhead, since they’re only for top level rows and should be always less than 1024 per block.  

We then compute the batch size, ie. top level row count that can fit into the next output blocks. Right now we limit the nested row count for each batch 1000. The batch size is at least 1. This means the unnested row count for each block migth be over 1000. For example, if an array contains 10000 rows, then unnested row count would be 10000. Although this is over the 1000 rows we still have to output the whole top level row which translates into 10000 unnested rows. 

### Special optimization for deciding if nulls are needed

There’re some cases where nulls are needed, for example: 

```
SELECT numbers, animals, n, a
FROM (VALUES(ARRAY[2, 5], ARRAY['dog', 'cat', 'bird']),
             (ARRAY[7, 8, 9], ARRAY['cow', 'pig'])
) AS x (numbers, animals)
CROSS JOIN UNNEST(numbers, animals) AS t (n, a);

```
THe output should be like this:

```
  numbers  |     animals      |  n   |  a
-----------+------------------+------+------
 [2, 5]    | [dog, cat, bird] |    2 | dog
 [2, 5]    | [dog, cat, bird] |    5 | cat
 [2, 5]    | [dog, cat, bird] | NULL | bird
 [7, 8, 9] | [cow, pig]       |    7 | cow
 [7, 8, 9] | [cow, pig]       |    8 | pig
 [7, 8, 9] | [cow, pig]       |    9 | NULL
(6 rows)

```
Special handling is required when we need to insert nulls to the unnested blocks. This involves doing special checks within the tight loop. However, when there are no nulls required, we can simply get a Block view instead of building a new DictionaryBlock:

```
    public Block buildOutputBlockWithoutNulls(int outputPositionCount)
    {
        Block output = source.getRegion(sourcePosition, outputPositionCount);
        sourcePosition += outputPositionCount;
        return output;
    }
```

Here the outputPositionCount is the number of output rows for the unnest block. 

For the case where null needs to be added, we wrote simple loop to construct the DictionaryBlock more efficiently:

```
protected Block buildOutputBlockWithNullsByDictionary(int[] maxLengths, int offset, int length, int outputPositionCount, int nullIndex, int[] lengths)
    {
        verify(nullIndex != NULL_NOT_FOUND, "nullIndex is -1");

        int position = 0;
        int[] ids = new int[outputPositionCount];
        for (int i = 0; i < length; i++) {
            int curEntries = lengths[offset + i];
            for (int j = 0; j < curEntries; j++) {
                ids[position++] = sourcePosition++;
            }

            int curMaxEntries = maxLengths[offset + i];
            for (int j = curEntries; j < curMaxEntries; j++) {
                ids[position++] = nullIndex;
            }
        }

        return new DictionaryBlock(outputPositionCount, source, ids);
    }
```

This loop can be optimized to highly performant machine code by the JVM, fully utilizing the parallel streamlined execution power of the CPU with unrolled loops. This method is 3x faster than the row-by-row implementation.

There’re several cases we can do additional optimizations to decide if nulls is required:

1. When there is only one unnest column (except Array of Row case), no null is needed. 
2. When there’re multiple columns, but the cardinalities for them are the same for the current batch.
3. For a single Array of Row unnest column case, if the row block doesn't contain any nulls, then no null is needed.
For these cases, we don’t need to do the null check at all and can just use the fast code path shown above.

### Inserting nulls using bulk copy
For the cases where null is required in the output block, but there were no nulls in the underlying nested block, we need to insert null to the nested output block. There’re two ways of doing this:
1) Use special id, e.g. -1 to identify null in DictionaryBlock
2) Copy the blocks and insert nulls.

Currently DictionaryBlock doesn’t support the logic in 1). To make it happen, we need to change all getId() and getIds() call to handle the special values. While the size of the callsites is manageable (about 50), the performance implication need to be studied carefully. 

The original implementation uses PageBuilder/BlockBuilder to copy the blocks for this case. We have known that BlockBuilder is not super efficient for this purpose. I did some JMH benchmark to compare the cost of copying blocks using 
1) PageBuilder/BlockBuilder
2) Bulk copy using tight loops

```
@Benchmark
    public void copyBlockByAppend(BenchmarkData data)
    {
        LongArrayBlockBuilder longArrayBlockBuilder = new LongArrayBlockBuilder(null, POSITIONS_PER_PAGE);
        for (int i = 0; i < BLOCK_COUNT; i++) {
            Block block = data.blocks.get(i);
            int positionCount = block.getPositionCount();

            for (int j = 0; j < positionCount; j++) {
                BIGINT.appendTo(block, j, longArrayBlockBuilder);
            }

            Block outputBlock = longArrayBlockBuilder.build();
        }
    }
```

2:

```
@Benchmark
    public void copyBlockByLoop(BenchmarkData data)
    {
        for (int i = 0; i < BLOCK_COUNT; i++) {
            Block block = data.blocks.get(i);
            int positionCount = block.getPositionCount();

            long[] values = new long[positionCount];
            for (int j = 0; j < positionCount; j++) {
                values[j] = block.getLong(j);
            }

            boolean[] valueIsNull = copyIsNulls(block);

            Block outputBlock = new LongArrayBlock(positionCount, Optional.of(valueIsNull), values);
        }
    }
```

The results shows over 4x gain in 2) over 1)

    Benchmark                             (primitiveNullsRatio)  Mode  Cnt     Score     Error  Units
    BenchmarkCopyBlock.copyBlockByAppend                    0.0  avgt   30  6272.811 ± 255.866  us/op
    BenchmarkCopyBlock.copyBlockByAppend                    0.2  avgt   30  8548.040 ± 306.015  us/op
    BenchmarkCopyBlock.copyBlockByLoop                      0.0  avgt   30  1511.379 ± 303.105  us/op
    BenchmarkCopyBlock.copyBlockByLoop                      0.2  avgt   30  1753.673 ± 209.173  us/op

So we decided to use the first way to copy data and insert nulls. This applies to primitive types like boolean, smallint, integer, bigint, etc. To insert one null, we just need to first copy all the positions over then put the null at the end of the block. 

For VariableWidthBlock, ArrayBlock, MapBlock and RowBlock, we can get hold of the underlying elements block or the raw slice, and then construct the offsets array. It doesn’t need to do deep copy of the nested structure.  To do this, we need to convert the ArrayBlock, MapBlock and RowBlock into the ColumnarXXX objects but the cost of conversion is very worthwhile. 

### Experimental Results
We optimized the JMH  benchmark to include more tests. For all tests the new implementation shows 2.3x- 10.8x gain.

**Comment by yingsu00** [comment]
https://github.com/prestodb/presto/pull/13746

**Comment by mbasmanova** [comment]
@yingsu00 Thanks for the detailed write up. CC: @prestodb/aria
