### ISSUE TITLE
Expand bucket pruning to predicates with fixed number of matching values

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#13763]
When table is bucketed, an equality filter on bucketed-by column(s) will trigger bucket pruning and allow Presto to scan only matching files. E.g. the following query will scan only one file.

`SELECT * FROM t WHERE x = 5`

This optimization can be expanded to more sophisticated predicates, e.g. `x IN (5, 7, 10)` or `x = 5 OR x = 6 or x = 10`, e.g. any predicate for which only fixed number of values match.

**Comment by FernandaCG** [comment]
Hi! Can I work on this?

**Comment by mbasmanova** [comment]
@FernandaCG This improvement has just landed: #13804

If you are interested in working on table scan optimizations, consider one of these: #13848, #13431, #13351

CC: @prestodb/aria

**Comment by mbasmanova** [comment]
Fixed in #13804
