### ISSUE TITLE
Change default s3 storage class for hive connector

### ISSUE THREAD

**Issue by ishaan1995** [prestodb/presto#13770]
https://prestodb.io/docs/current/connector/hive.html#hive-configuration-properties

Referring to this documentation, could not find a way to configure storage class for s3 paths.

AWS recently added Amazon S3 Intelligent-Tiering (https://aws.amazon.com/s3/storage-classes/) which is optimized for cost.

Is this currently supported?

I am using presto with hive as metastore.

**Comment by arpit1997** [comment]
@ishaan1995 No its not currently supported.Since this is a good feature to support as per your conversation with @aweisberg on slack channel, I am picking this up. Have a working version ready. Will try sending a PR this week.

**Comment by aweisberg** [comment]
Feel free to add me as a reviewer.
