### ISSUE TITLE
Incorrect results for not (NaN between A and B)

### ISSUE THREAD

**Issue by bhhari** [prestodb/presto#13807]
Consider a table with a double column with some NaN values.The following queries return inconsistent results. `not (val between 1 and 3)` when used as a filter excludes NaN rows, but when used as a projection returns `true`. 

```
presto:tpch> select * from nan;
 val
-----
 NaN
(1 row)

presto:tpch> select * from nan where not (val between 1 and 3);
 val
-----
(0 rows)

presto:tpch> select not (val between 1 and 3) from nan;
 _col0
-------
 true
(1 row)

```

**Comment by bhhari** [comment]
cc : @mbasmanova  @rongrong  @kaikalur

**Comment by mbasmanova** [comment]
CC: @highker @wenleix @arhimondr

**Comment by kaikalur** [comment]
OK. To simplify, I just made it a < and I see a somewhat related issue. Evaluating using NaN seems to be messed up:

select not(x < 2), x < 2 from test_sreeni_temp;
 _col0 | _col1        
-------+-------
 false | false

**Comment by mbasmanova** [comment]
@kaikalur Sreeni, do you happen to know what would be the right behavior?

**Comment by kaikalur** [comment]
Quick check in the spec doesn't find NaN at all. That's why I thought it would be just like NULL. I will read the spec more carefully and update it. We can look at Java semantics I suppose.
