### ISSUE TITLE
Verifier: improve column mismatch error for arrays, maps and structs

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#13809]
It would be helpful to provide a bit more information when there a column mismatch on a complex type column (array/map/struct). 

For arrays, 
- total number of elements (`sum(cardinality(a))`) (e.g. row count check at the column level)

For maps, 
- total number of elements (e.g. row count check at the column level)
- checksum of keys 
- checksum of values

For structs,
- checksums of individual subfields

CC: @caithagoras @mayankgarg1990 @rongrong @prestodb/aria

**Comment by oerling** [comment]
Also, maps/arrays of doubles/floats should be compared with the same semantic as top level floats/doubles.  It happens repeatedly that results of aggregations are returned inside maps/arrays and that these have a couple of trailing bits that are noisy due to nondeterministic order of aggregation.

**Comment by caithagoras** [comment]
@mbasmanova @oerling Those are great proposals. Will look into those but cannot promise a deliver date as of now.
