### ISSUE TITLE
Optimize TupleDomainFilter for NOT IN

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#13843]
TupleDomainFilters for IN predicates are optimized to use hash tables for lookups and offer O(1) performance, but NOT IN filters are not optimized and give O(n) performance. Yet, there is no reason why IN predicate optimization couldn't apply to NOT IN. We could extend BytesValues and BigintValues to add a flag indicating that this is a NOT filter and add logic to com.facebook.presto.orc.TupleDomainFilterUtils#toFilter to set this flag.

See com.facebook.presto.orc.TupleDomainFilter.BytesValues and com.facebook.presto.orc.TupleDomainFilter.BigintValues#BigintValues

CC: @prestodb/aria

**Comment by kewang1024** [comment]
Do we want to create new class that extends BytesValues/BigintValues or we just add the flag to BytesValues/BigintValues class @mbasmanova

**Comment by kewang1024** [comment]
Also for BigintValues, now we have BigintValuesUsingHashTable and BigintValuesUsingBitmask, do we only extend the function to BigintValuesUsingHashTable?

**Comment by mbasmanova** [comment]
@kewang1024 Ke, I'd start by adding a flat to BytesValues and BigintValuesXxx classes.
