### ISSUE TITLE
Investigate often stuck test TestDistributedSpilledQueries::testLimitWithJoin

### ISSUE THREAD

**Issue by caithagoras** [prestodb/presto#13859]

**Comment by aweisberg** [comment]
Similar to https://github.com/prestosql/presto/issues/1337 (great issue number!) and https://github.com/prestosql/presto/issues/1951.

Apparently not resolved there yet either.

**Comment by caithagoras** [comment]
Do we have any clue yet?

**Comment by aweisberg** [comment]
Sorry for the delay on this. I have tried to reproduce it locally a couple of times by running it in a loop. I just started it in Travis to see if it reproduces there. If it does I will see if I can debug the container. We'll need to ask Travis to enable debug mode for the repository.
