### ISSUE TITLE
Presto sql not able to infer schema for tiny int.

### ISSUE THREAD

**Issue by rahulsingh978** [prestodb/presto#13908]
Presto MySQL not able to infer the schema for tinyint and inferring it as smallint.

**Comment by mahengyang** [comment]
what do you mean?

In `com.facebook.presto.plugin.jdbc.StandardReadMappings`, following code show mysql type to java type mapping:

```
        int columnSize = type.getColumnSize();
        switch (type.getJdbcType()) {
            case Types.BIT:
            case Types.BOOLEAN:
                return Optional.of(booleanReadMapping());

            case Types.TINYINT:
                return Optional.of(tinyintReadMapping());

            case Types.SMALLINT:
                return Optional.of(smallintReadMapping());

            case Types.INTEGER:
                return Optional.of(integerReadMapping());
```

**Comment by rahulsingh978** [comment]
> what do you mean?
> 
> In `com.facebook.presto.plugin.jdbc.StandardReadMappings`, following code show mysql type to java type mapping:
> 
> ```
> int columnSize = type.getColumnSize();
> switch (type.getJdbcType()) {
>     case Types.BIT:
>     case Types.BOOLEAN:
>         return Optional.of(booleanReadMapping());
> 
>     case Types.TINYINT:
>         return Optional.of(tinyintReadMapping());
> 
>     case Types.SMALLINT:
>         return Optional.of(smallintReadMapping());
> 
>     case Types.INTEGER:
>         return Optional.of(integerReadMapping());
> ```

I am using mysql connector in poresto an d trying to run the query in which one of the column is tinyint in mysql table but when i run "describe table <table-name>" in presto console it reads that column as small int.

**Comment by rahulsingh978** [comment]
i beg your pardon, the question is different.
there is one collumn in mysql table "inventory" of the type smallint(5) unsigned
so when i run a query like "select sum(inventory) as t from table1;" iw works fine
but when i run the same query in presto
"select sum(inventory) as t from table1;" or "select inventory as t from table1;" it gives this error -> 
Query 20200103_110045_00012_9sbb5, FAILED, 2 nodes
Splits: 18 total, 0 done (0.00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20200103_110045_00012_9sbb5 failed: '65535.0' in column '1' is outside valid range for the datatype SMALLINT.

when i run "describe table1" in presto it gives the below output for the same column:
inventory  | smallint.


please tell me a workaround for this

**Comment by mahengyang** [comment]
the problem is `unsigned` not `smallint(5)`, presto deal `int`, `smallint`, `tinyint` as `signed`, leads to `outside valid range`, I will make a PR later for `unsigned` bug. 

you have to change your column type to `smallint` for now

**Comment by rahulsingh978** [comment]
> the problem is `unsigned` not `smallint(5)`, presto deal `int`, `smallint`, `tinyint` as `signed`, leads to `outside valid range`, I will make a PR later for `unsigned` bug.
> 
> you have to change your column type to `smallint` for now

I there no work around without changing it  smallint ? since it would be difficult to change the existing datatype as its in production environment.
