### ISSUE TITLE
PyHive + Apache Superset not working with Presto and Kerberos

### ISSUE THREAD

**Issue by elukey** [prestodb/presto#13910]
Hi!

The PyHive package (https://github.com/dropbox/PyHive) is a very convenient way to use Hive and Presto from Python. It is used in Apache Superset, and at Wikimedia Foundation we are currently exploring the use of Presto as backend for Superset dashboards. The main issue is that PyHive seems abandoned, and the original authors didn't create a PyPi release for version 0.6.2, to allows Kerberos Authentication between Superset and Presto.

I opened https://github.com/apache/incubator-superset/issues/8794 to Superset upstream, but up to now we didn't find a good replacement for PyHive.

Since Presto and Superset seem a really nice combination of tools for data visualization, I am wondering if you have any suggestion about how to proceed.

A simple solution could be to contact Dropbox and ask if they are planning to avoid supporting PyHive in the future or if it is only a temporary problem (due to maintainers leaving etc..). I tried to find a way to contact Dropbox but besides pinging in github random people I didn't find any good solution :)

**Comment by Hammond95** [comment]
I don't think this is an issue for this repo, but I am also facing some problems with pyHive for newer versions of Hive and Presto.

**Comment by elukey** [comment]
It would be great to find an alternative, this is why I was asking in here if anybody could help..

**Comment by ottomata** [comment]
[Impyla](https://github.com/cloudera/impyla) seems to be fairly active, and IIRC (once connected), the interface isn't that different than PyHive.  Perhaps they could be swapped out?

**Comment by elukey** [comment]
This was fixed in PyHive 0.6.2 :)
