### ISSUE TITLE
Using Presto for low latency realtime-analytics use case

### ISSUE THREAD

**Issue by dharakk** [prestodb/presto#13937]
We are using Presto on top of realtime storages for low latency realtime-analytics use-cases. For this, queries are aggressively and completely pushed down to underlying storages (pinot/ares/cassandra) and changes were required to get the time spent in presto down to 10-100 ms. This issue represents those changes in a manner that is generic and useful to the community. 
(More details on the realtime setup in the slides here: https://github.com/prestodb/presto/wiki/Presto-Meetup-Nov-2019)

**Comment by mbasmanova** [comment]
CC: @highker @shixuan-fan @sachdevs @oerling
