### ISSUE TITLE
Connector predicate pushdown throws exception on any unenforced constraint

### ISSUE THREAD

**Issue by dima-vm** [prestodb/presto#13943]
When using predicate pushdown presto-main throws exception on any unenforced constraint except for TRUE_CONSTANT.

Exception is thrown at line [157 in WindowFilterPushDown](https://github.com/prestodb/presto/blob/release-0.229/presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/WindowFilterPushDown.java#L157
), at castToExpression() call -- it expects an OriginalExpression, while actually has a CallExpression.

Example of metadata code to reproduce the issue.
```java
public class TestMetadata implements ConnectorMetadata {

	@Override
	public boolean isPushdownFilterSupported(ConnectorSession session, ConnectorTableHandle tableHandle) {
		return true;
	}

	@Override
	public ConnectorPushdownFilterResult pushdownFilter(
			ConnectorSession session,
			ConnectorTableHandle tableHandle,
			RowExpression filter,
			Optional<ConnectorTableLayoutHandle> currentLayoutHandle) {

		ConnectorTableLayoutHandle tableLayoutHandle = new ConnectorTableLayoutHandle() {};
		ConnectorTableLayout tableLayout = new ConnectorTableLayout(tableLayoutHandle);

		// Notice we return original filter here as unenforced constraint
		return new ConnectorPushdownFilterResult(tableLayout, filter);
	}
}
```

**Comment by dima-vm** [comment]
CC: Hi @highker I see you worked on that lines, do you have any ideas?

**Comment by highker** [comment]
@dima-vm, `pushdownFilter` will be deprecated, please use `ConnectorPlanOptimizerProvider` and `ConnectorPlanOptimizer` interfaces. There are existing examples in the repo like jdbc or pinot connectors.
