### ISSUE TITLE
how to determine whether the PrepareStatement precompilation in Presto is actually executed？

### ISSUE THREAD

**Issue by wangwei216** [prestodb/presto#13958]
1. Hello, first of all, my purpose is to encapsulate a set of Client APIs that can support PHP, but Presto does not officially support the corresponding functions, so here we can only try to do it ourselves, I used https://github.com/360d-io-labs/PhpPrestoClient

2. When I did not execute the PREPARE statementXXX FROM request "my own SQL", I directly added the [X-Presto-Prepared-Statement] field to the request header when I executed the EXECUTE request and the value was statementXXX = "I "Our own SQL" can directly return the results I want. So, does the PrepareStatement precompilation provided by you have no effect? If there is an effect, why can I still get the result when I do not execute PREPARE? Is this a bug? I hope to get your answer, thank you

this is my php code：
###  $this->prestoPrepareStatement   👍:  statement = select count(identify) as totalNum, real_region_name, provider from user where real_region_name = ? and provider = ? 
            $this->headers = array(
                "X-Presto-User: " . $this->prestoUser,
                "X-Presto-Catalog: " . $this->prestoCatalog,
                "X-Presto-Schema: " . $this->prestoSchema,
                "X-Presto-Language: ".$this->prestoLanguage,
                "X-Presto-Time-Zone: ".$this->prestoTimeZone,
                "X-Presto-Added-Prepare: ".$this->prestoAddPrepare,
                "X-Presto-Prepared-Statement: ".$this->prestoPrepareStatement,
                "Content-Type: ".$this->contentType,
                "X-Presto-Source: ".$this->prestoSource,
                "Connection: ".$this->prestoConnection,
                "User-Agent: " . $this->userAgent);
            \curl_setopt($this->connectionSession, CURLOPT_URL, $this->url);
            \curl_setopt($this->connectionSession, CURLOPT_HTTPHEADER, $this->headers);
            \curl_setopt($this->connectionSession, CURLOPT_RETURNTRANSFER, 1);
            \curl_setopt($this->connectionSession, CURLOPT_POST, 1); 
            \curl_setopt($this->connectionSession, CURLOPT_POSTFIELDS, $this->request);
            $this->result = \curl_exec($this->connectionSession);
            $httpCode2 = \curl_getinfo($this->connectionSession, CURLINFO_HTTP_CODE);

**Comment by rongrong** [comment]
I think populate `X-Presto-Prepared-Statement` and run `PREPARE` has the same effect. They both record the prepare statement for later use. The statement in head `X-Presto-Prepared-Statement` will be recorded in session. The execution of `PREPARE` statement will also record the value in session according to https://prestodb.io/docs/current/sql/prepare.html

**Comment by wangwei216** [comment]
1. How can I use preparestatement in Presto in PHP? I used to refer to [https://github.com/360d-io-labs/phpprestoclient] 

2. At present, Presto does not support precompiling of PHP queries

**Comment by rongrong** [comment]
I'm not familiar with https://github.com/360d-io-labs/phpprestoclient. It's probably easier to get answers from that repo.
