### ISSUE TITLE
test-hive-pushdown-filter-queries-basic Travis job fails sporadically

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#13952]
@aweisberg noticed that test-hive-pushdown-filter-queries-basic https://github.com/prestodb/presto/blob/master/presto-hive/pom.xml#L504 is unreliable in Travis?

```
https://travis-ci.org/prestodb/presto/jobs/634863030?utm_medium=notification&utm_source=github_status

Looks like it's kind of out of memory

2020-01-09T13:08:33.977-0600	INFO	Service Thread	com.facebook.airlift.stats.JmxGcMonitor	Major GC: application 240ms, stopped 1926ms: 1.95GB -> 1.60GB

It finished on my laptop in only 14 minutes, also doing a bunch of major GCs.
```

CC: @rschlussel @prestodb/aria

**Comment by mbasmanova** [comment]
@bhhari Bhavani, would you take a look?

**Comment by aweisberg** [comment]
I split them and increased the memory limit to 5gb and they got fast. https://travis-ci.org/prestodb/presto/builds/634968801?utm_source=github_status&utm_medium=notification

Seems like maybe all our tests could be going faster if we used the memory available?

**Comment by aweisberg** [comment]
To be precise, splitting them made them fast and reliable. That run didn't have the increased memory limit due to my error. Testing that now.

**Comment by mbasmanova** [comment]
Duplicate of #13965
