### ISSUE TITLE
Replace FileSystemContext with HdfsContext

### ISSUE THREAD

**Issue by highker** [prestodb/presto#14011]
`FileSystemContext` in presto-raptor can now be replaced by `HdfsContext` given `presto-hive-metastore` has been separated into a standalone module.

**Comment by fvcortes** [comment]
I would like to try this.

Is the goal here to replace the use of FileSystemContext in presto-raptor by HdfsContext (present in presto-hive-common) ?

**Comment by highker** [comment]
@fvcortes, yes. Feel free to proceed.
