### ISSUE TITLE
presto : failed: Only '\N' supported as null specifier, was ''

### ISSUE THREAD

**Issue by khaledammar** [prestodb/presto#1401]
I'm new to Presto. I managed to install Presto on a local Ubuntu cluster of 1 coordinator and 6 workers. There is an HDFS and Hive already installed on the cluster. I have a table created by the "create external table" command and pointing to a csv file in the DFS. 

I can connect to the schema and describe the table from presto but I cannot get any results. I got the below error message. 

**Note:** _I have read some where that this error might be related to using Parquet format. I did not specify Parquet option while creating/loading the table. I'm not sure if this could be the default though!_

presto:testProperty> describe company;

```
Column    |  Type   | Null | Partition Key 
```

--------------+---------+------+---------------

 pk           | bigint  | true | false         

 name       | varchar | true | false         

(2 rows)

Query 20140616_221410_00013_xr6fi, FINISHED, 2 nodes
Splits: 2 total, 2 done (100.00%)
0:00 [2 rows, 279B] [18 rows/s, 1.28KB/s]

presto:testProperty> select pk from company;

Query 20140616_221432_00014_xr6fi, FAILED, 6 nodes
Splits: 27 total, 0 done (0.00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20140616_221432_00014_xr6fi failed: Only '\N' supported as null specifier, was ''

---

**More info:**

I noticed this error comes from [presto-hive/src/main/java/com/facebook/presto/hive/HiveRecordSet.jav](https://github.com/facebook/presto/blob/6c89c76d5b2b6c6780be7afe756af1c51d2a820b/presto-hive/src/main/java/com/facebook/presto/hive/HiveRecordSet.java)a: 

   String nullSequence = split.getSchema().getProperty(SERIALIZATION_NULL_FORMAT);
   checkState(nullSequence == null || nullSequence.equals("\N"), "Only '\N'    supported as null specifier, was '%s'", nullSequence);$

so I created my schema and tables with the following commands to ensure a correct value for serialization_null_value but it did not work either !

create database testProperty
with DBPROPERTIES ('serialization.null.format' = '\N');

create external table testProperty.COMPANY (
        PK BIGINT  NOT NULL  , 
        name VARCHAR(128)  
  )
ROW FORMAT DELIMITED 
FIELDS TERMINATED BY '~' 
location '<path>/Company.csv'
TBLPROPERTIES ('serialization.null.format' = '\N');

Thanks,
-K

**Comment by cawallin** [comment]
@khaledammar -- sorry for the delay in response. Is this still an issue for you? I'm pretty sure that \N is the default null format for Hive, so you shouldn't have to specify it.  It's hard to tell the exact issue without seeing your data, can you share a gist with the table if it isn't too big?

**Comment by losipiuk** [comment]
Closing. This is really old and A-LOT has changed in the codebase since 2014. @khaledammar please reopen if you still see the problem in your flow.
