### ISSUE TITLE
PreparedStatement getMetaData method implementation

### ISSUE THREAD

**Issue by jessicashelton-wk** [prestodb/presto#14029]
I am looking for a way to parse column data from an executed EXPLAIN statement resultSet. 

There is support for the preparedStatement, implemented after this issue was posted: https://github.com/prestodb/presto/issues/4566. However, support was never added for the getMetaData method in order to actually retrieve the column data. It would be great if this could be implemented.

As an alternative, it would be nice if support for JSON format was added to the explain statement. If this is not doable, it would be great if there was better separation between the column aliases/names in the explain output. Right now they are separated by a comma and trailing space, however commas and spaces are valid in column alias. If the column aliases could be in double quotes, like: ```- Output["regionkey", "_col1"] => [regionkey:bigint, count:bigint]``` rather than ```- Output[regionkey, _col1] => [regionkey:bigint, count:bigint]``` it would allow for much easier parsing.

Thank you!

**Comment by HY-Stars** [comment]
Has the getMetadata Method support been implemented ?

**Comment by HY-Stars** [comment]
Can this be implemented as the code has already existed for this #2770 Implement JDBC PreparedStatement.getMetaData.

**Comment by mbasmanova** [comment]
Folks, is there anything else needed to be done here? If not, let's close this issue.

FYI, there is a related, but probably different issue #14686

**Comment by jessicashelton-wk** [comment]
@mbasmanova looks like this is good to close, thank you!
