### ISSUE TITLE
Add a scale_qdigest function

### ISSUE THREAD

**Issue by tdcmeehan** [prestodb/presto#14058]
It would be useful to add a function which scales quantile digests according to a new weight.  One example use case would be to add a decaying weight to daily summary values, which are then merged into a single digest.

The proposed scalar function signature is as follows

`scale_qdigest(qdigest, w) -> qdigest`

We can also consider a similar function for t-digest.  We may need to add support for fractional weights in these digests.

CC: @rongrong @mehrdad-honarkhah

**Comment by TrongDucNguyen** [comment]
Should the compression parameter k be affected by w.
Say k = k * w, then the new digest is valid. However, as k changes, it can't me merged into other digest anymore, which is against what we want.
If we keep k as it was, then the digest may be come invalid, that is the error bound is not guarantee anymore.
