### ISSUE TITLE
Introduce new IPADDRESS / IPPREFIX functions

### ISSUE THREAD

**Issue by rongrong** [prestodb/presto#14061]
We can introduce the following functions related to IP address:
* `IP_SUBNET_RANGE(IPPREFIX) -> ARRAY<IPADDRESS>`: return an array of [min, max] of the ip prefix's range
* `IS_SUBNET_OF(IPPREFIX, IPPREFIX) -> boolean`: returns true if second `IPPREFIX` is a subnet of first `IPPREFIX`
* `IS_SUBNET_OF(IPPREFIX, IPADDRESS) -> boolean`: returns true if `IPADDRESS` is in `IPPREFIX`

We can introduce the following as sql functions:
* `IP_SUBNET_MIN(IPPREFIX) -> IPADDRESS`
* `IP_SUBNET_MAX(IPPREFIX) -> IPADDRESS`

**Comment by rongrong** [comment]
We can potentially change `IP_SUBNET_MIN` and `IP_SUBNET_MAX` to SQL functions once we have static SQL function support.

**Comment by NikhilCollooru** [comment]
Fixed as part of #14090
