### ISSUE TITLE
REDUCE does not work when elements of array are DOUBLE

### ISSUE THREAD

**Issue by dusanvukic** [prestodb/presto#14066]
`SELECT REDUCE(ARRAY [1.0,2.0,3.0], 0, (s, x) -> s + x, s -> s);`
_Query 20200206_083548_02600_ms79w failed: SignatureBinder.iterativeSolve does not converge after 4 iterations._

All is fine when elements are INTEGER:
`SELECT REDUCE(ARRAY [1,2,3], 0, (s, x) -> s + x, s -> s);`
_6_

(version 0.222)

**Comment by rongrong** [comment]
The default parsing option for strings with decimal point is decimal. If you want the array to be parsed as double, use `set session parse_decimal_literals_as_double = true`.
