### ISSUE TITLE
Classify ORC bad format as an External Error

### ISSUE THREAD

**Issue by bhhari** [prestodb/presto#14179]
If there is a mismatch between the table schema (double) and stream descriptor type (long) we and the select has no filters, we return a LazyBlock which on loading results in "unsupported type double" as the StreamReader that is created is Long but the outputtype is double.
Since this is a unchecked exception we classify this an INTERNAL_ERROR, but this should be of a EXTERNAL error caused due to Malformed ORC file.

**Comment by viczhang861** [comment]
Part of https://github.com/prestodb/presto/issues/13935
