### ISSUE TITLE
'Enable failure detector in tests' is causing flaky tests

### ISSUE THREAD

**Issue by kewang1024** [prestodb/presto#14170]
It seems that commit '3eef1b02da Enable failure detector in tests' is causing tests like `TestMemoryWorkerCrash` to be flaky. 
After reverting this change, trunk goes back to normal. I think it may be related to this change.
@rschlussel Can you help take a look?  Thanks!

**Comment by rschlussel** [comment]
Can you share the stack trace from a failed run.  I can easily turn off the failure detector for that test, but I'm curious where specifically it was failing.
