### ISSUE TITLE
 Failed connecting to Hive metastore: [localhost:9083]

### ISSUE THREAD

**Issue by pengbomuzzy** [prestodb/presto#14250]
I followed the README.md and went into hive and ran -
`SHOW TABLES FROM hive.default;` but got 
`Query 20200316_041146_00013_r6g3w failed: Failed connecting to Hive metastore: [localhost:9083]`.

I don't have my own hive metastore so I used 
`-Dhive.metastore.uri=thrift://localhost:9083`, is there anything I'm missing?

BTW, ` SELECT * FROM system.runtime.nodes;` works, which means presto runs correctly I guess.

**Comment by pengbomuzzy** [comment]
I set up a hive metastore by installing hive on my machine and tried -
`hive --service metastore -p 9083`  
(you need `sudo` sometimes) and it works.

**Comment by kshru9** [comment]
> I set up a hive metastore by installing hive on my machine and tried -
> `hive --service metastore -p 9083`
> (you need `sudo` sometimes) and it works.

Hi @pengbomuzzy 
When I tried running `hive --service metastore -p 9083` on my hive-metastore docker image, It shows following error, any workaround for this? Thanks in advance

![image](https://user-images.githubusercontent.com/45987734/126026917-4b2ce8ab-e505-49be-82e2-e680192fe8db.png)
