### ISSUE TITLE
Wrong results for queries with join over unnest.

### ISSUE THREAD

**Issue by yingsu00** [prestodb/presto#14257]
We recently observed some query returns wrong results for queries that have joins over unnest, and unnest produces multiple level of nested DictionaryBlocks and some of them is a view (i.e. the idsOffset is non-zero). For such blocks, the BlockFlattener would calculate the mappings wrong, such that the OptimizedPartitionedOutputOperator would shuffle wrong rows. For more details please see the fix https://github.com/prestodb/presto/pull/14245

**Comment by yingsu00** [comment]
Closed by #14245

**Comment by mbasmanova** [comment]
CC: @prestodb/aria
