### ISSUE TITLE
Make presto-orc a common library

### ISSUE THREAD

**Issue by highker** [prestodb/presto#14284]
`presto-orc` as a common library can serve for other compute engines to reader/write ORC files. Making the module a common library, which has "almost no" dependency to presto codebase, can benefit larger community.

### ~~Phase 1: Drop dependency on `presto-memory-context` and `presto-hive-common` (done)~~
This can be done very common abstraction. Both memory tracking and hive common are generic enough to have common interfaces.

- `presto-hive-common`: #14336
- `presto-memory-context`: #14345

### ~~Phase 2: Move `presto-array` to a separate repo (done)~~
`presto-orc` and `presto-main` both depend on it: #14418

### ~~Phase 3: Remove connector-related interfaces (from `presto-spi`) from `presto-orc` (done)~~
- `com.facebook.presto.spi.ConnectorSession`  #14375
- `com.facebook.presto.spi.security.ConnectorIdentity` no need

### ~~Phase 4: Remove or refactor misc SPI depenenencies (5 days) (done)~~
- Error types and codes #14486, #14490, #14498
- `Subfield`
- `Experimental`
- `predicate.Utils`
- `com.facebook.presto.spi.function.SqlFunctionProperties`

### ~~Phase 5: Move `type` and `block` package to the common repo (5 days) (done)~~
- `com.facebook.presto.spi.Page`
- `com.facebook.presto.spi.block.*`
- `com.facebook.presto.spi.type.*`
#14457

### ~~Phase 6: Abstract common interfaces provided by `ConnectorContext` (done)~~
This step might require further breakdown.

**Comment by yingsu00** [comment]
As a separate but related work item, how do we make our dependency on Airlift, specifically Slice/SliceInput/SliceOutput? They're essential to writer performance and also a lot of other operators. We need to fork it to allow some optimization work to happen. Can we make it covered by this issue? 
cc @prestodb/aria @biswapesh

**Comment by highker** [comment]
> We need to fork it to allow some optimization work to happen. Can we make it covered by this issue?

That will be left to whoever to make the change. @sunnar will take over the work. The purpose of this issue is to make sure presto-orc has minimum dependency from Presto codebase. We only expect Page, Block, Type, Domain, Predicate, and SqlFunctionProperties to be the only ones.
