### ISSUE TITLE
Get query string by QueryId

### ISSUE THREAD

**Issue by ertanyildiz** [prestodb/presto#14285]
Hey! I am developing a connector using `PRESTO SPI`. I just need to get the query string that user executes on Presto. I can get `queryId` but no query string supplied from SPI.

**Comment by pigxuyu** [comment]
presto connector can not get  query string, but you can get the scan columns for the connector.

Maybe there's a temporary solution, you can get the full query string and queryId from AST, then write to external storage, connector get from external storage.
