### ISSUE TITLE
EMR Ranger Presto Plugin issues 2.1.0-SNAPSHOT

### ISSUE THREAD

**Issue by suryadevarauday** [prestodb/presto#14293]
We have Ranger 2.1.0-SNAPSHOT installed on EMR 5.29 and the presto Plugin is working if we create a ranger policy with schema = * and Presto Catalog = * (or) hive but if i have the schema's added seperatly like default / inter* / schemaname* it' throwing an error like below.

$ presto-cli --catalog hive
presto> SHOW SCHEMAS;
Query 20200325_135650_00001_d8mxn failed: Access Denied: Cannot access catalog hive

**Comment by suryadevarauday** [comment]
https://github.com/prestosql/presto/issues/1076

**Comment by iammehrabalam** [comment]
@suryadevarauday I am also facing this issue.  
Did u solve this issue?

Presto version: 332
Ranger version:  2.1.0-SNAPSHOT (build from master)

**Comment by suryadevarauday** [comment]
Yeah i was able to solve this by adding in "all - catalog" policy name on presto (ranger)

**Comment by findepi** [comment]
> Presto version: 332

@iammehrabalam 
Presto 3xx releases are maintained at https://github.com/prestosql/presto.
Also, there is the `#troubleshooting` channel on Presto Community Slack (https://prestosql.io/slack.html)

**Comment by AvianshKumar** [comment]
> Yeah i was able to solve this by adding in "all - catalog" policy name on presto (ranger)

can you please elaborate?
