### ISSUE TITLE
Support TVF in Presto

### ISSUE THREAD

**Issue by BlueStalker** [prestodb/presto#14294]
TVF, aka Table-Valued Function is widely used by various analytics engines, across RDMS, warehouse, etc. This issue was opened for discussion on how to support TVF in presto. Some significant working items are:
1. Parser/Planner Changes, we need to make some extension on [CREATE FUNCTION](https://github.com/prestodb/presto/issues/13254) to be able to return TABLE.
2. Runtime execution support of table function by using the TABLE keyword.

Meanwhile, we compose an initial requirement [doc](https://docs.google.com/document/d/1IiQ3-n1pJF1c-eNXF0-gYPpKYOfWsemxuWMzS3coeZQ) on the TVF support for the streaming SQL use cases.

This issue is opened for all the community members to discuss the solution.

**Comment by rongrong** [comment]
The [CREATE FUNCTION](https://github.com/prestodb/presto/issues/13254) syntax is primarily useful for SQL functions, i.e., functions defined in SQL. SQL table function is only one type of TVF. A generic framework to execute TVF is a way bigger undertake than supporting a restricted subset of TVF written in SQL. We can potentially inline SQL TVF, thus not changing the Presto runtime. But supporting generic TVF execution is totally different thing. So it's worth figuring out what kind of TVF to support first.
