### ISSUE TITLE
how to run on linux with no intellij 

### ISSUE THREAD

**Issue by wlgclrh** [prestodb/presto#14311]
I try to compile on the linux, but i didn't use intellij to run the server,  how i can run the server with jar file.  i know you run the server by bin/launcher.py,  but when i building the project, there is no laucher.py on the bin directory but only check_webui.sh. so how can i start the server with no intellij. i just only want to run with command jar -cp or jar -jar.  
look forward your reply. thanks
![PY(W820(H1 YLWL@UKWPI try to compile on the linux, but i didn't use intellij to run the server,  how i can run the server with jar file?
M](https://user-images.githubusercontent.com/31975136/77976218-eff93d00-732e-11ea-9588-6cab42345359.png)
![3V8Y%O@4FBP(SVE9@{F8GAK](https://user-images.githubusercontent.com/31975136/77976235-03a4a380-732f-11ea-83d5-41358ec1affe.png)

**Comment by rschlussel** [comment]
The server jar will be in presto-server/target.  From there you can follow the docs for deploying presto. or if you're looking for an rpm deployment that will be in presto-server-rpm/target
