### ISSUE TITLE
druid query "select count(distinct column) from table"

### ISSUE THREAD

**Issue by mqiang** [prestodb/presto#14357]
I used a local druid 0.17.0 version, and loaded its sample dataset.Then i found a issue.
when I executed "select count(distinct cityName) from wikipedia",
I found it executed "select count(cityName) from wikipedia", rather than "count(distinct)"

@zhenxiao 
Really appreciate your work, wish you can help on this issue.

**Comment by zhenxiao** [comment]
hi @mqiang 
I fixed some druid bugs in recent commits. Could you please take a try of latest master branch? Or, we might have to wait till 235 release

**Comment by mqiang** [comment]
@zhenxiao

**Comment by mqiang** [comment]
Thanks for your work.
After my trying, I found some issues and fixed some of it by myself, and i will show you all what I changed, maybe some are not the best code.

1.issues: if table filed name is 'count',then exec 'select * from table' will be failed

/presto-druid/src/main/java/com/facebook/presto/druid/DruidQueryGenerator.java
@@ -257,7 +263,7 @@ public class DruidQueryGenerator
             node.getOutputVariables().forEach(outputColumn -> {
                 DruidColumnHandle druidColumn = (DruidColumnHandle) (node.getAssignments().get(outputColumn));
                 checkArgument(druidColumn.getType().equals(DruidColumnHandle.DruidColumnType.REGULAR), "Unexpected druid column handle that is not regular: " + druidColumn);
-                selections.put(outputColumn, new Selection(druidColumn.getColumnName(), TABLE_COLUMN));
+                selections.put(outputColumn, new Selection("\\\""+druidColumn.getColumnName()+"\\\"", TABLE_COLUMN));
             });
             return new DruidQueryGeneratorContext(selections, tableHandle.getTableName());
         }

/presto-druid/src/test/java/com/facebook/presto/druid/TestDruidQueryGenerator.java
@@ -54,7 +54,9 @@ public class TestDruidQueryGenerator
             String expressions = planNode.getOutputVariables().stream().map(v -> outputVariables.get(v.getName())).filter(v -> v != null).collect(Collectors.joining(", "));
             expectedDQL = expectedDQL.replace("__expressions__", expressions);
         }
-        assertEquals(druidQueryGeneratorResult.getGeneratedDql().getDql(), expectedDQL);
+        String generateDQL = druidQueryGeneratorResult.getGeneratedDql().getDql();
+        generateDQL = generateDQL.replaceAll("\\\\\"","");
+        assertEquals(generateDQL, expectedDQL);
     }


2.if a filed is float type, query will throw UnsupportedOperationException

/presto-druid/src/main/java/com/facebook/presto/druid/DruidBrokerPageSource.java
@@ -140,7 +140,7 @@ public class DruidBrokerPageSource
                             type.writeDouble(blockBuilder, value.doubleValue());
                         }
                         else if (type instanceof RealType) {
-                            type.writeDouble(blockBuilder, value.doubleValue());
+                            type.writeLong(blockBuilder, value.longValue());

                         }

3.eg:'select count(1) from table group by cityName', after planing,it will exec 'select count(1) from table group by cityname', but no filed called 'cityname'. So i add a param into DruidQueryGeneratorContext.class to record all fields in this table， and groupByColumns mapping origin field from it rather than from selections

/presto-druid/src/main/java/com/facebook/presto/druid/DruidQueryGenerator.java
@@ -236,7 +236,13 @@ public class DruidQueryGenerator
                         variable,
                         new Selection(druidExpression.getDefinition(), druidExpression.getOrigin()));
             });
-            return context.withProject(newSelections);
+
+            Map<VariableReferenceExpression, Selection> allSelections = context.getSelections().entrySet().stream()
+                    .filter(item -> !newSelections.containsKey(item.getKey()))
+                    .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue));
+
+
+            return context.withProject(newSelections, allSelections);
         }

/presto-druid/src/main/java/com/facebook/presto/druid/DruidQueryGeneratorContext.java
@@ -39,6 +39,7 @@ import static java.util.Objects.requireNonNull;
 public class DruidQueryGeneratorContext
 {
     private final Map<VariableReferenceExpression, Selection> selections;
+    private final Map<VariableReferenceExpression, Selection> allSelections;
     private final Set<VariableReferenceExpression> groupByColumns;
     private final Set<VariableReferenceExpression> hiddenColumnSet;
     private final Set<VariableReferenceExpression> variablesInAggregation;
@@ -52,6 +53,7 @@ public class DruidQueryGeneratorContext
     {
         return toStringHelper(this)
                 .add("selections", selections)
+                .add("allSelections", allSelections)
                 .add("groupByColumns", groupByColumns)
                 .add("hiddenColumnSet", hiddenColumnSet)
                 .add("variablesInAggregation", variablesInAggregation)
@@ -79,7 +81,8 @@ public class DruidQueryGeneratorContext
                 0,
                 new HashSet<>(),
                 new HashSet<>(),
-                new HashSet<>());
+                new HashSet<>(),
+                new LinkedHashMap<>());
     }
 
     private DruidQueryGeneratorContext(
@@ -90,7 +93,8 @@ public class DruidQueryGeneratorContext
             int aggregations,
             Set<VariableReferenceExpression> groupByColumns,
             Set<VariableReferenceExpression> variablesInAggregation,
-            Set<VariableReferenceExpression> hiddenColumnSet)
+            Set<VariableReferenceExpression> hiddenColumnSet,
+            Map<VariableReferenceExpression, Selection> allSelections)
     {
         this.selections = new LinkedHashMap<>(requireNonNull(selections, "selections can't be null"));
         this.from = requireNonNull(from, "source can't be null");
@@ -100,6 +104,7 @@ public class DruidQueryGeneratorContext
         this.groupByColumns = new LinkedHashSet<>(requireNonNull(groupByColumns, "groupByColumns can't be null. It could be empty if not available"));
         this.hiddenColumnSet = requireNonNull(hiddenColumnSet, "hidden column set is null");
         this.variablesInAggregation = requireNonNull(variablesInAggregation, "variables in aggregation is null");
+        this.allSelections = new LinkedHashMap<>(requireNonNull(allSelections, "selections can't be null"));
     }
 
     public DruidQueryGeneratorContext withFilter(String filter)
@@ -113,10 +118,12 @@ public class DruidQueryGeneratorContext
                 aggregations,
                 groupByColumns,
                 variablesInAggregation,
-                hiddenColumnSet);
+                hiddenColumnSet,
+                allSelections);
     }
 
-    public DruidQueryGeneratorContext withProject(Map<VariableReferenceExpression, Selection> newSelections)
+    public DruidQueryGeneratorContext withProject(Map<VariableReferenceExpression, Selection> newSelections,
+                                                  Map<VariableReferenceExpression, Selection> newAllSelections)
     {
         return new DruidQueryGeneratorContext(
                 newSelections,
@@ -126,7 +133,8 @@ public class DruidQueryGeneratorContext
                 aggregations,
                 groupByColumns,
                 variablesInAggregation,
-                hiddenColumnSet);
+                hiddenColumnSet,
+                newAllSelections);
     }
 
     public DruidQueryGeneratorContext withLimit(long limit)
@@ -143,7 +151,8 @@ public class DruidQueryGeneratorContext
                 aggregations,
                 groupByColumns,
                 variablesInAggregation,
-                hiddenColumnSet);
+                hiddenColumnSet,
+                allSelections);
     }
 
     public DruidQueryGeneratorContext withAggregation(
@@ -191,7 +200,8 @@ public class DruidQueryGeneratorContext
                 newAggregations,
                 newGroupByColumns,
                 variablesInAggregation,
-                newHiddenColumnSet);
+                newHiddenColumnSet,
+                allSelections);
     }
 
     public DruidQueryGeneratorContext withVariablesInAggregation(Set<VariableReferenceExpression> newVariablesInAggregation)
@@ -204,7 +214,8 @@ public class DruidQueryGeneratorContext
                 aggregations,
                 groupByColumns,
                 newVariablesInAggregation,
-                hiddenColumnSet);
+                hiddenColumnSet,
+                allSelections);
     }


         if (!groupByColumns.isEmpty()) {
             String groupByExpression = groupByColumns.stream()
-                    .map(expression -> selections.containsKey(expression) ? selections.get(expression).getDefinition() : expression.getName())
+                    .map(expression -> selections.containsKey(expression) ? selections.get(expression).getDefinition() :
+                            allSelections.get(expression).getDefinition())
                     .collect(Collectors.joining(", "));
             query = query + " GROUP BY " + groupByExpression;


public Map<VariableReferenceExpression, DruidColumnHandle> getAssignments()
@@ -305,7 +317,8 @@ public class DruidQueryGeneratorContext
                 aggregations,
                 groupByColumns,
                 variablesInAggregation,
-                hiddenColumnSet);
+                hiddenColumnSet,
+                allSelections);
     }


4. eg:'select * from table', then pushDown param in DruidQueryGenerator.GeneratedDql.toQuery() will be false, and exec failed, 'com.facebook.presto.server.TaskUpdateRequest could not be converted to JSON'
I change pushDown to true, then it will exec success.But i don't know how to fix elegantly,wish you can solve this issues.

**Comment by mqiang** [comment]
```
Thanks for your work.
After my trying, I found some issues and fixed some of it by myself, and i will show you all what I changed, maybe some are not the best code.

1.issues: if table filed name is 'count',then exec 'select * from table' will be failed

/presto-druid/src/main/java/com/facebook/presto/druid/DruidQueryGenerator.java
@@ -257,7 +263,7 @@ public class DruidQueryGenerator
             node.getOutputVariables().forEach(outputColumn -> {
                 DruidColumnHandle druidColumn = (DruidColumnHandle) (node.getAssignments().get(outputColumn));
                 checkArgument(druidColumn.getType().equals(DruidColumnHandle.DruidColumnType.REGULAR), "Unexpected druid column handle that is not regular: " + druidColumn);
-                selections.put(outputColumn, new Selection(druidColumn.getColumnName(), TABLE_COLUMN));
+                selections.put(outputColumn, new Selection("\\\""+druidColumn.getColumnName()+"\\\"", TABLE_COLUMN));
             });
             return new DruidQueryGeneratorContext(selections, tableHandle.getTableName());
         }

/presto-druid/src/test/java/com/facebook/presto/druid/TestDruidQueryGenerator.java
@@ -54,7 +54,9 @@ public class TestDruidQueryGenerator
             String expressions = planNode.getOutputVariables().stream().map(v -> outputVariables.get(v.getName())).filter(v -> v != null).collect(Collectors.joining(", "));
             expectedDQL = expectedDQL.replace("__expressions__", expressions);
         }
-        assertEquals(druidQueryGeneratorResult.getGeneratedDql().getDql(), expectedDQL);
+        String generateDQL = druidQueryGeneratorResult.getGeneratedDql().getDql();
+        generateDQL = generateDQL.replaceAll("\\\\\"","");
+        assertEquals(generateDQL, expectedDQL);
     }


2.if a filed is float type, query will throw UnsupportedOperationException

/presto-druid/src/main/java/com/facebook/presto/druid/DruidBrokerPageSource.java
@@ -140,7 +140,7 @@ public class DruidBrokerPageSource
                             type.writeDouble(blockBuilder, value.doubleValue());
                         }
                         else if (type instanceof RealType) {
-                            type.writeDouble(blockBuilder, value.doubleValue());
+                            type.writeLong(blockBuilder, value.longValue());

                         }

3.eg:'select count(1) from table group by cityName', after planing,it will exec 'select count(1) from table group by cityname', but no filed called 'cityname'. So i add a param into DruidQueryGeneratorContext.class to record all fields in this table， and groupByColumns mapping origin field from it rather than from selections

/presto-druid/src/main/java/com/facebook/presto/druid/DruidQueryGenerator.java
@@ -236,7 +236,13 @@ public class DruidQueryGenerator
                         variable,
                         new Selection(druidExpression.getDefinition(), druidExpression.getOrigin()));
             });
-            return context.withProject(newSelections);
+
+            Map<VariableReferenceExpression, Selection> allSelections = context.getSelections().entrySet().stream()
+                    .filter(item -> !newSelections.containsKey(item.getKey()))
+                    .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue));
+
+
+            return context.withProject(newSelections, allSelections);
         }

/presto-druid/src/main/java/com/facebook/presto/druid/DruidQueryGeneratorContext.java
@@ -39,6 +39,7 @@ import static java.util.Objects.requireNonNull;
 public class DruidQueryGeneratorContext
 {
     private final Map<VariableReferenceExpression, Selection> selections;
+    private final Map<VariableReferenceExpression, Selection> allSelections;
     private final Set<VariableReferenceExpression> groupByColumns;
     private final Set<VariableReferenceExpression> hiddenColumnSet;
     private final Set<VariableReferenceExpression> variablesInAggregation;
@@ -52,6 +53,7 @@ public class DruidQueryGeneratorContext
     {
         return toStringHelper(this)
                 .add("selections", selections)
+                .add("allSelections", allSelections)
                 .add("groupByColumns", groupByColumns)
                 .add("hiddenColumnSet", hiddenColumnSet)
                 .add("variablesInAggregation", variablesInAggregation)
@@ -79,7 +81,8 @@ public class DruidQueryGeneratorContext
                 0,
                 new HashSet<>(),
                 new HashSet<>(),
-                new HashSet<>());
+                new HashSet<>(),
+                new LinkedHashMap<>());
     }
 
     private DruidQueryGeneratorContext(
@@ -90,7 +93,8 @@ public class DruidQueryGeneratorContext
             int aggregations,
             Set<VariableReferenceExpression> groupByColumns,
             Set<VariableReferenceExpression> variablesInAggregation,
-            Set<VariableReferenceExpression> hiddenColumnSet)
+            Set<VariableReferenceExpression> hiddenColumnSet,
+            Map<VariableReferenceExpression, Selection> allSelections)
     {
         this.selections = new LinkedHashMap<>(requireNonNull(selections, "selections can't be null"));
         this.from = requireNonNull(from, "source can't be null");
@@ -100,6 +104,7 @@ public class DruidQueryGeneratorContext
         this.groupByColumns = new LinkedHashSet<>(requireNonNull(groupByColumns, "groupByColumns can't be null. It could be empty if not available"));
         this.hiddenColumnSet = requireNonNull(hiddenColumnSet, "hidden column set is null");
         this.variablesInAggregation = requireNonNull(variablesInAggregation, "variables in aggregation is null");
+        this.allSelections = new LinkedHashMap<>(requireNonNull(allSelections, "selections can't be null"));
     }
 
     public DruidQueryGeneratorContext withFilter(String filter)
@@ -113,10 +118,12 @@ public class DruidQueryGeneratorContext
                 aggregations,
                 groupByColumns,
                 variablesInAggregation,
-                hiddenColumnSet);
+                hiddenColumnSet,
+                allSelections);
     }
 
-    public DruidQueryGeneratorContext withProject(Map<VariableReferenceExpression, Selection> newSelections)
+    public DruidQueryGeneratorContext withProject(Map<VariableReferenceExpression, Selection> newSelections,
+                                                  Map<VariableReferenceExpression, Selection> newAllSelections)
     {
         return new DruidQueryGeneratorContext(
                 newSelections,
@@ -126,7 +133,8 @@ public class DruidQueryGeneratorContext
                 aggregations,
                 groupByColumns,
                 variablesInAggregation,
-                hiddenColumnSet);
+                hiddenColumnSet,
+                newAllSelections);
     }
 
     public DruidQueryGeneratorContext withLimit(long limit)
@@ -143,7 +151,8 @@ public class DruidQueryGeneratorContext
                 aggregations,
                 groupByColumns,
                 variablesInAggregation,
-                hiddenColumnSet);
+                hiddenColumnSet,
+                allSelections);
     }
 
     public DruidQueryGeneratorContext withAggregation(
@@ -191,7 +200,8 @@ public class DruidQueryGeneratorContext
                 newAggregations,
                 newGroupByColumns,
                 variablesInAggregation,
-                newHiddenColumnSet);
+                newHiddenColumnSet,
+                allSelections);
     }
 
     public DruidQueryGeneratorContext withVariablesInAggregation(Set<VariableReferenceExpression> newVariablesInAggregation)
@@ -204,7 +214,8 @@ public class DruidQueryGeneratorContext
                 aggregations,
                 groupByColumns,
                 newVariablesInAggregation,
-                hiddenColumnSet);
+                hiddenColumnSet,
+                allSelections);
     }


         if (!groupByColumns.isEmpty()) {
             String groupByExpression = groupByColumns.stream()
-                    .map(expression -> selections.containsKey(expression) ? selections.get(expression).getDefinition() : expression.getName())
+                    .map(expression -> selections.containsKey(expression) ? selections.get(expression).getDefinition() :
+                            allSelections.get(expression).getDefinition())
                     .collect(Collectors.joining(", "));
             query = query + " GROUP BY " + groupByExpression;


public Map<VariableReferenceExpression, DruidColumnHandle> getAssignments()
@@ -305,7 +317,8 @@ public class DruidQueryGeneratorContext
                 aggregations,
                 groupByColumns,
                 variablesInAggregation,
-                hiddenColumnSet);
+                hiddenColumnSet,
+                allSelections);
     }


4. eg:'select * from table', then pushDown param in DruidQueryGenerator.GeneratedDql.toQuery() will be false, and exec failed, 'com.facebook.presto.server.TaskUpdateRequest could not be converted to JSON'
I change pushDown to true, then it will exec success.But i don't know how to fix elegantly,wish you can solve this issues.
```

**Comment by zhenxiao** [comment]
nice. thank you @mqiang could you please submit your changes as 3 commits and 1 Pull request to Presto? I'd love to review and work with you to merge them

**Comment by mqiang** [comment]
> nice. thank you @mqiang could you please submit your changes as 3 commits and 1 Pull request to Presto? I'd love to review and work with you to merge them

I have submit my change in https://github.com/prestodb/presto/pull/14432 .
pease help to review it
