### ISSUE TITLE
Implement JDBC PreparedStatement.getMetaData

### ISSUE THREAD

**Issue by HY-Stars** [prestodb/presto#14442]
Please implement PreparedStatement for getMetaData which has already been implemented here - https://github.com/prestosql/presto/pull/2770

**Comment by mbasmanova** [comment]
@HY-Stars Would you like to contribute a cross-port?

**Comment by HY-Stars** [comment]
@mbasmanova This has been implemented with the 0.236 JDBC Driver. I was testing this implementation and encountered a new issue with DatabaseMetadata.getClientInfoProperties #14686 so did not close this issue yet.

https://prestodb.io/docs/current/release/release-0.236.html
DBC Changes:
Add support for PreparedStatement#getMetaData.

**Comment by mbasmanova** [comment]
Fixed in #14460 by @adamjshook
