### ISSUE TITLE
Bug with outputting single quote

### ISSUE THREAD

**Issue by mchades** [prestodb/presto#14462]
when I want to use backslash to output single quote by function `regexp_replace` ,the result is:
```
presto:default> select regexp_replace('\'','','');
Query 20200430_093552_00034_8xzcd failed: line 1:32: mismatched input '''. Expecting: ',', <expression>
select regexp_replace('\'','','')
```

but when use double quote
```
presto:default> select regexp_replace('\''','','');
 _col0
-------
 \'
(1 row)
```

without backslash:
```
presto:default> select regexp_replace('''','','');
 _col0
-------
 '
(1 row)
```

how dose presto lexer work？Is this a bug?

**Comment by rschlussel** [comment]
As you've discovered, in sql the way to escape a quote is to double it up.

**Comment by mbasmanova** [comment]
@mchades Did @rschlussel answered your question? If so, let's close this issue.
