### ISSUE TITLE
Severe performance regression due to memory allocation tracking

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#14478]
https://github.com/prestodb/presto/commit/a64e5d876f4d87df63f33e7a39665834cc6c67d3 (part or 0.234 release) introduced 2-3x performance regression due to ThreadMXBean::getThreadAllocatedBytes() being very slow: https://bugs.openjdk.java.net/browse/JDK-8207266

CC: @viczhang861 @prestodb/aria @aweisberg

**Comment by viczhang861** [comment]
Let's change the default value to false as a temporary solution.

**Comment by aweisberg** [comment]
Given the severity I think we need to do something about the 0.234 release so that people who download it aren't impacted. Can we re-release 0.234 with this option disabled? @caithagoras

**Comment by caithagoras** [comment]
@mbasmanova @aweisberg Sure. Let's cherry-pick the fix.
