### ISSUE TITLE
date_parse function error

### ISSUE THREAD

**Issue by smilly2** [prestodb/presto#14488]
sql: select date_parse('19890416','%Y%m%d') 

Query failed (#20200506_093338_00718_29rgt): Cannot parse "19890416": Illegal instant due to time zone offset transition (Asia/Shanghai)

**Comment by armsword** [comment]
what is your presto version?

update joda-time version to 2.10.5 will resolve the problem, Release 0.223 has solved the problem

**Comment by armsword** [comment]
update this in the pom.xml:
`<dep.joda.version>2.10.5</dep.joda.version>`

**Comment by smilly2** [comment]
thank you
