### ISSUE TITLE
test user allow-deny rule

### ISSUE THREAD

**Issue by nambastha** [prestodb/presto#14568]
I'm using presto-spi System Access Control for allowing and denying access. I want to add few users and give them allow-deny access. This is just for testing(local setup), so I don't have Kerberos. Any link which I can follow which can guide me in doing this.

**Comment by rschlussel** [comment]
are you using the built in file based system access control?  there are some examples in the documentation about how to use it: https://prestodb.io/docs/current/security/built-in-system-access-control.html
