### ISSUE TITLE
Syntax for creating DWRF tables with encrypted columns

### ISSUE THREAD

**Issue by rschlussel** [prestodb/presto#14598]
#  Requirements 
* specify encryption algorithm per-table
* specify the columns to be encrypted, including the option of only encrypting subcolumns of a row type
* Different columns can have different encryption keys
* ideally don't require specifying all columns if you want to encrypt everything in the table with a single key

# Proposal 
Specify all this information as table properties for the Hive connector (any other connector using DWRF format can also take the same approach).
 
* encryption_algorithm - the encryption algorithm
* encryption_columns - a list of column groups sharing a key
* encryption_keys -  a list of keys for each group.

if the encryptions is empty then there should be a single encryption key and it gets applied to all columns in the table otherwise encryption_keys should have the same number of entries as the number of groups of encryption columns

I also considered making the encryption columns and keys into a single map property, but maps are actually kind of annoying to write in sql because you basically write out the two key and values arrays separately anyway, so I thought this might be better.

## Example 

1. encrypt specific columns with 2 different keys
```
CREATE TABLE 
c1 bigint,
c2 ROW(subcol1 bigint, subcol2 varchar),
c3 VARCHAR,
c4 VARCHAR
WITH (
encryption_algorithm = 'AES_CTR_128',
encryption_columns= ARRAY[ ARRAY ['c1', 'c2.subcol1'] ,  [ARRAY ['c4']],
encryption_keys = ARRAY['key1', 'key2'])
```
2. encrypt the whole table
```
CREATE TABLE 
c1 bigint,
c2 ROW(subcol1 bigint, subcol2 varchar),
c3 VARCHAR,
c4 VARCHAR
WITH (
encryption_algorithm = 'AES_CTR_128',
encryption_keys = ARRAY['key1'])
```

**Comment by rschlussel** [comment]
@rongrong @mayankgarg1990 @zzhao0 @zhenyuy-fb

**Comment by mayankgarg1990** [comment]
For the columns, instead of relying on arrays - should we add the settings to the columns itself - 

```
c2 VARCHAR WITH ('encryption_key' = '....', 'encryption_algorithm' = 'AES...'),
```

This way it is easier to know which columns use which key

**Comment by rschlussel** [comment]
I like that. That was the original idea, but I was worried about how to encrypt the whole table.  But we can just have the properties as either column or table properties (and throw an exception if someone tries to specify both).   We'd need to also add a column property encrypted_subcolumns in case you only want to encrypt one field of a row type column.

**Comment by mayankgarg1990** [comment]
After thinking about this a bit and taking a look at the discussion at https://issues.apache.org/jira/browse/HIVE-21848 the following is my proposal to move ahead with this:

1. encrypt specific columns with different keys

```
CREATE TABLE 
  c1 bigint,
  c2 ROW(subcol1 bigint, subcol2 varchar),
  c3 VARCHAR,
  c4 VARCHAR
WITH (
  dwrf_encryption_algorithm = 'AES_CTR_128',
  encrypt_columns= ARRAY[ ARRAY ['key1', 'c1,c2.subcol1'] ,  [ARRAY ['key2', 'c4']]
)
```

2. encrypt the whole table

```
CREATE TABLE 
  c1 bigint,
  c2 ROW(subcol1 bigint, subcol2 varchar),
  c3 VARCHAR,
  c4 VARCHAR
WITH (
  dwrf_encryption_algorithm = 'AES_CTR_128',
  encrypt_table = 'key1'
)
```

**Comment by zzhao0** [comment]
dwrf currently has encryption provider concept that tries to abstract way the actual encryption logic from the format. In the context of fb, we will use crypto service as the provider. Does presto (as OSS compute engine) need to provide way for user to specify encryption provider?

Similarly, is it sufficient if we only expose string as the key. Say if we have to integrate with KMS at some point, then string may not be sufficient.

**Comment by mayankgarg1990** [comment]
I missed the encryption provider. For KMS - while I haven't played with it - but looking at the ORC proposal which already uses KMS - a string seems to be working - can you share what kind of concerns you have with string not being sufficient for the key
