### ISSUE TITLE
Presto default date is not appearing correctly

### ISSUE THREAD

**Issue by sam007jat** [prestodb/presto#14607]
presto> select date '0001-01-01';
Expected result: '0001-01-01'
Actual result: '0001-01-02'

Day is increasing by one in this case. 

Can anyone help me on this that how can i resolve this?

If i run the above query on presto-cli then result comes as '0001-01-01' which is expected but when i run same query via SQL workbench then result comes as '0001-01-02' which is actual result.

**Comment by rschlussel** [comment]
sounds like it could be some kind of time zone conversion issue.  Do you know the timezones for the clients and the presto cluster?  Also, does the issue happen only with really old dates, or also recent dates?

**Comment by rschlussel** [comment]
Not enough information, so closing this issue.
