### ISSUE TITLE
presto cli return result

### ISSUE THREAD

**Issue by lucasaytt** [prestodb/presto#14600]
presto> select name from dw.dw_presto;
 result 
--------
 true   
(1 row)

**Comment by lucasaytt** [comment]
query a table have not data, return a result column when query this table have not result column

**Comment by rschlussel** [comment]
I have never seen Presto return result data that doesn't exist, so it seems like your table does have data in it.  How did you create this table? what connector are you using? what makes you think that the result should be zero rows?

**Comment by lucasaytt** [comment]
now it is resolved,because i add the query log event,change the queryStat cause the issue

**Comment by lucasaytt** [comment]
thanks
