### ISSUE TITLE
Error executing query when executing set session join_distribution_type='broadcast'

### ISSUE THREAD

**Issue by ahlag** [prestodb/presto#14651]
We are trying to execute the `set session join_distribution_type='broadcast'`, however there is an error regarding the execution of with the jdbc connector. Is there a workaround for us to execute, for example `pc.setSession("join_distribution_type", "BROADCAST");` in the jdbc java files?

I believe this would be the place.
PrestoStatement.java:567:
```
    private PrestoConnection connection()
            throws SQLException
    {
        PrestoConnection connection = this.connection.get();
        connection.setSession("join_distribution_type", "BROADCAST");
        if (connection == null) {
            throw new SQLException("Statement is closed");
        }
        if (connection.isClosed()) {
            throw new SQLException("Connection is closed");
        }
        return connection;
    }

```

**Comment by mbasmanova** [comment]
> however there is an error

What is the error?

**Comment by mbasmanova** [comment]
This question might has been answered in https://github.com/prestodb/presto/issues/11410

**Comment by mbasmanova** [comment]
Copying @electrum's answer here for convenience:

----
There are two ways to set session properties in the JDBC driver. One way is to execute `SET SESSION` on the `Connection` before you run the query (on the same connection used for the query). The other way is to call a Presto-specific method:
```java
Connection connection = DriverManager.getConnection(...);
PrestoConnection pc = connection.unwrap(PrestoConnection.class);
pc.setSession("join_distribution_type", "BROADCAST");

**Comment by ahlag** [comment]
Ok! Thank you for helping! That solves the problem.
