### ISSUE TITLE
Need help compiling Presto

### ISSUE THREAD

**Issue by okaybrian** [prestodb/presto#14666]
I am new to Presto and was trying to build the project. I saw the following:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project presto-main: Compilation failure
[ERROR] /home/briany/presto/presto-main/src/main/java/com/facebook/presto/transaction/InMemoryTransactionManager.java:[587,46] incompatible types: inference variable T has incompatible bounds
[ERROR]     lower bounds: com.google.common.util.concurrent.ListenableFuture<? extends capture#1 of ? extends java.lang.Object>,java.lang.Object
[ERROR]     lower bounds: com.google.common.util.concurrent.ListenableFuture<? extends java.lang.Object>
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :presto-main
[briany@brianlinux presto]$

The offending source code is:

584  private synchronized ListenableFuture<?> abortInternal()
585        {
586            // the callbacks in statement performed on another thread so are safe
587            return nonCancellationPropagating(Futures.allAsList(Stream.concat(
588                    functionNamespaceTransactions.values().stream()
589                            .map(transactionMetadata -> finishingExecutor.submit(() -> safeAbort(transactionMetadata))),
590                    connectorIdToMetadata.values().stream()
591                            .map(connection -> finishingExecutor.submit(() -> safeAbort(connection))))
592                    .collect(toList())));
593        }

**Comment by mbasmanova** [comment]
Could you provide the output of `mvn -v`? Here is mine:

```
$ mvn -v
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T15:39:06-04:00)
Maven home: /opt/homebrew/Cellar/maven/3.5.0/libexec
Java version: 1.8.0_181, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.4", arch: "x86_64", family: "mac"
```

**Comment by okaybrian** [comment]
Thanks for getting back.
In fact I downloaded a newer version and use Java 11.
With option -DSkipTests, it compiled.

mvn -v
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/lib/apache-maven-3.6.3
Java version: 11.0.7, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-11-openjdk-11.0.7.10-4.el7_8.x86_64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-1062.18.1.el7.x86_64", arch: "amd64", family: "unix"

**Comment by mbasmanova** [comment]
@okaybrian Thank you for the update. Glad to hear you were able to compile Presto successfully.
