### ISSUE TITLE
Implement DatabaseMetadata.getClientInfoProperties 

### ISSUE THREAD

**Issue by HY-Stars** [prestodb/presto#14686]
Please implement DatabaseMetadata.getClientInfoProperties 

Below is the error using 0.236 JDBC Driver related to the Data source metadata :
Data source meta data Info:
Client info Properties:
Cannot obtain info: com.facebook.presto.jdbc.NotImplementedException: Method DatabaseMetadata.getClientInfoProperties is not yet implemented

The Connector encountered a Java exception: java.lang.NullPointerException
at com.facebook.presto.jdbc.internal.guava.collect.Maps.fromProperties(Maps.java:1360)
at com.facebook.presto.jdbc.PrestoDriverDriverUri.mergeConnectionProperties(prestoDriverUri.java:297)
at com.facebook.presto.jdbc.PrestoDriverUri.<init>(PrestoDriverUri.java:95)
at com.facebook.presto.jdbc.PrestoDriverUri.<init>(PrestoDriverUri.java:87)
at com.facebook.presto.jdbc.PrestoDriver.getPropertyInfo(PrestoDriver.java:107)
at com.ibm.is.cc.jdbc.CC_JDBCMetadataHelper.logDriverAttributes(CC_JDBCMetadataHelper.java:170)
at com.ibm.is.cc.jdbc.CC_JDBCConnection.connect(CC_JDBCConnection.java:831)

Looks like this has been implemented here although with a slightly different method 

https://github.com/mattyb149/pdi-presto-jdbc/blob/master/src/main/java/org/pentaho/community/di/plugins/database/presto/delegate/DelegateConnection.java

@adamjshook

**Comment by mbasmanova** [comment]
@HY-Stars Would you like to contribute this improvement? What's the use case that is impacted by not having this?

**Comment by HY-Stars** [comment]
Thank You @mbasmanova. Because DatabaseMetadata.getClientInfoProperties standard JDBC specification is not implemented by the Presto JDBC driver the Client Application connector that we are using is calling this method from the Presto JDBC Driver to get the Metadata Properties from Presto DB Server and as a result the transaction breaks with the above error message with the Connector.

Below are the Properties that should be implemented:

Details about getClientInfoProperties: https://docs.oracle.com/javase/7/docs/api/java/sql/DatabaseMetaData.html#getClientInfoProperties()

ResultSet getClientInfoProperties()
                                  throws SQLException
Retrieves a list of the client info properties that the driver supports. The result set contains the following columns
NAME String=> The name of the client info property
MAX_LEN int=> The maximum length of the value for the property
DEFAULT_VALUE String=> The default value of the property
DESCRIPTION String=> A description of the property. This will typically contain information as to where this property is stored in the database.
The ResultSet is sorted by the NAME column

Returns:
A ResultSet object; each row is a supported client info property
Throws:
SQLException - if a database access error occurs
Since:
1.6

**Comment by mbasmanova** [comment]
@adamjshook Do you already have plans to implement this? If not, would you like to consider this fix?

**Comment by adamjshook** [comment]
@mbasmanova I can work on it, but some pointers on implementation details would be helpful.  Is there a means to get the client info properties already through SQL or some other API? If not, what would you recommend?

**Comment by mbasmanova** [comment]
@adamjshook Thank you, Adam. I think you can start by checking out com.facebook.presto.jdbc.ConnectionProperties#allProperties and com.facebook.presto.jdbc.PrestoDriver#getPropertyInfo

```
    @Override
    public DriverPropertyInfo[] getPropertyInfo(String url, Properties info)
            throws SQLException
    {
        Properties properties = new PrestoDriverUri(url, info).getProperties();

        return ConnectionProperties.allProperties().stream()
                .map(property -> property.getDriverPropertyInfo(properties))
                .toArray(DriverPropertyInfo[]::new);
    }
```

**Comment by adamjshook** [comment]
@mbasmanova

As I look more into this, I think the client info properties that are supported are `ApplicationName`, `TraceToken`, `ClientTags`, and `ClientInfo`, which are used in [startQuery](https://github.com/prestodb/presto/blob/e34525404c016e0cdd88bf2682d4efddf393d7c8/presto-jdbc/src/main/java/com/facebook/presto/jdbc/PrestoConnection.java#L670).  While it seems like you can set whatever you want, these four are ultimately what are used by the connection and IMO should be returned by this `getClientInfoProperties`.

We could create a basic `ResultSet` of these four properties, but that begs the question of how to create an arbitrary `ResultSet`.  Alternatively, I could make a table through the system JDBC connector using an `InMemoryResultSet`, e.g. `system.jdbc.client_info_properties`, and then query it in `PrestoDatabaseMetaData`.  Thoughts?

**Comment by mbasmanova** [comment]
@adamjshook Maybe just 

```
        return select("SELECT\n" +
                "    *\n" +
                "FROM (\n" +
                "    VALUES\n" +
                "        ('ApplicationName', 20, 'default-value', 'description'),\n" +
                "        ('TraceToken', 15, 'default-value', 'description')        \n" +
                ") AS t(name, max_len, default_value, description)");
```

**Comment by adamjshook** [comment]
@mbasmanova Didn't think about that!  Very nice.  I'll open a PR soon.
