### ISSUE TITLE
sleep function not registered

### ISSUE THREAD

**Issue by fgwang7w** [prestodb/presto#14690]
![image](https://user-images.githubusercontent.com/32091981/85233899-b4669000-b3be-11ea-8edc-9c37e31b1068.png)
This function is to simulate a long running query without changing the application logic, and may help to check how the application behaves during some load peaks.

-----------------

Proposed solution:
Define scalar function for sleep in DateTimeFunctions.

**Comment by shixuan-fan** [comment]
I'm not a huge fan of this function but I could also see it could fit into some integration test scenarios. Any thoughts on this? @rongrong

**Comment by rongrong** [comment]
Spec didn't seem to mention a `sleep` function. And introducing this in production doesn't sound like a good idea. If we want this for testing, we can introduce such function and only register it for test environment.

**Comment by nabaskes** [comment]
Hi, thread necromancy here but:

Did anyone ever do this or come up with any solution to do something similar?  Currently we are trying to test behavior in some surrounding infrastructure when Presto times out, and there doesn't seem to be an easily reproduceable way to get timeouts.
