### ISSUE TITLE
Support query level scan bytes limits

### ISSUE THREAD

**Issue by fgwang7w** [prestodb/presto#14701]
Propose Solution:
Enforce query scan not to scan the size of data over the limit by query.max-scan-physical-bytes in SqlQueryManager

**Comment by mbasmanova** [comment]
@fgwang7w Are you proposing to limit the amount of data scanned on a single node or on all nodes that process a given query?

**Comment by fgwang7w** [comment]
> @fgwang7w Are you proposing to limit the amount of data scanned on a single node or on all nodes that process a given query?

Hi Maria, thanks for your feedback, the fix is to ensure a threshold to limit the input data size at query level. A new system variable 'query.max-scan-physical-bytes' will be defined to guard inside query manager

**Comment by mbasmanova** [comment]
Sounds good. It is not clear to me how this will be enforced in a distributed setting though. Feel free to send a WIP PR or describe the design in details here.

**Comment by fgwang7w** [comment]
pr:`14739`

**Comment by fgwang7w** [comment]
> Sounds good. It is not clear to me how this will be enforced in a distributed setting though. Feel free to send a WIP PR or describe the design in details here.

sure, please help review the PR#14739 and let me know if you have any questions. thanks~

**Comment by mbasmanova** [comment]
@fgwang7w George, a proper syntax for linking to issues and PRs is #<number>, not pr:`number` or issue:`number`. The latter syntax is for documentation.

**Comment by fgwang7w** [comment]
> @fgwang7w George, a proper syntax for linking to issues and PRs is #, not pr:`number` or issue:`number`. The latter syntax is for documentation.

thanks, updated
