### ISSUE TITLE
Some queries that end in User Error cause queuedQueries metric to be inaccurate

### ISSUE THREAD

**Issue by jeremy-degroot** [prestodb/presto#14705]
I recently discovered that the queued queries metric reported through JMX by our Presto cluster is wildly inaccurate: reported value of nearly 4k when the Cluster Overview UI shows 0 queued queries.

After a restart to zero it out, it seems like the inaccuracies in reported queuedQueries value track with queries that end in User Error. Looking at the source, it seems plausible that the query was cancelled before it triggered the queryStarted() method of QueryManagerStats, and thus the counter is not getting decremented.

Please let me know if I can be of any further help in addressing this problem
![Screen Shot 2020-06-23 at 11 40 55 AM](https://user-images.githubusercontent.com/2699748/85425532-4ac5bd80-b547-11ea-90ea-3eb8e345ffb5.png)

**Comment by tdcmeehan** [comment]
@jeremy-degroot thanks, this is indeed a bug.  Do you want to submit a pull request to fix this issue?

**Comment by jeremy-degroot** [comment]
Yes, I'd be interested in trying to fix it. 
This would be my first Presto contribution, anything I should know aside from what's in the community guidelines and README before I attempt it?

**Comment by tdcmeehan** [comment]
@jeremy-degroot nope, that covers it.
