### ISSUE TITLE
Help Required for getting min and max in table

### ISSUE THREAD

**Issue by hitesh1907nayyar** [prestodb/presto#14703]
Hi All,

Require your help please. 

I have a table name wqmram and i want to calculate the min and max value for a column name s6 by month wise. Min value should not be zero as i want minimum value which is above zero.

I have written the below query:
SELECT min(s6) AS Mins6,
         max(s6) AS Maxs6,
         partition_0,
         partition_1
FROM wqmram 
WHERE cast(s6 AS decimal(30,2)) != 0.00
GROUP BY  partition_0,partition_1
ORDER BY  partition_0,partition_1;

partition_0 is year and patition_1 is month. I get the results as below which is wrong:

  | Mins6 | Maxs6 | partition_0 | partition_1
-- | -- | -- | -- | --
1 | 1017 | 996 | 2019 | 11
2 | 1002 | 994 | 2019 | 12
3 | 00.09 | 958 | 2020 | 01
4 | 00.01 | 997 | 2020 | 02
5 | 100 | 999 | 2020 | 03
6 | 100 | 999 | 2020 | 04
7 | 1 | 99 | 2020 | 05
8 | 1000 | 998 | 2020 | 06

If you see the above result then minimum values are coming greater than maximum values and that too they are wrong. 

Can somebody please let me know what is the issue ?

**Comment by j-penson** [comment]
Looks like you need to convert s6 from a string to a numeric data type, similar to how you have done in the WHERE clause.

**Comment by hitesh1907nayyar** [comment]
Thanks ! I was able to solve this.
