### ISSUE TITLE
Result is wrong for function classification_fall_out for version 0.237 and earlier

### ISSUE THREAD

**Issue by viczhang861** [prestodb/presto#14731]
The numerator of formula should be false positive for classification aggregate function https://prestodb.io/docs/current/functions/aggregate.html

**Comment by mbasmanova** [comment]
CC: @kaikalur @rongrong @caithagoras

**Comment by fornaix** [comment]
I think it's a mistake only in the document. The numerator of formula is false positive for `classification_fall_out` in code.
But the definition of false-positive and false-negative in code seem incorrect.
I will try to make a pr to fix them later.

**Comment by mbasmanova** [comment]
CC: @atavory
