### ISSUE TITLE
Presto + Alluxio Cluster

### ISSUE THREAD

**Issue by xumingming** [prestodb/presto#14745]
Alluxio as a BigData Cache layer is very useful to reduce query latency, current Presto user can use Alluxio Cluster in two ways:

* Use a alluxio:// location when creating the table.
* Use Alluxio Catalog Service

"Use a alluxio:// location when creating the table" will need the user to know that, there is an Alluxio in the process, We think as a cache, user should not need to care about the concrete cache software used.

"Alluxio Catalog Service" on the other hand is not quite mature, its metadata is not fully synced with underlying hive metastore, need to do metadata sync manually.

Recently Presto supported Alluxio client side local cache, the client side local cache is good, but miss some features we want:

* Data Expiration
* Monitoring
* Tiered Storage
* More control over the caches

So we want to implement an Alluxio Cluster based presto-cache, Is there anyone interested in this feature too?

**Comment by mbasmanova** [comment]
CC: @jainxrohit

**Comment by jainxrohit** [comment]
cc: @apc999

**Comment by jainxrohit** [comment]
@xumingming Thanks. We recently published a blog which has more details on things like monitoring:
https://prestodb.io/blog/2020/06/16/alluxio-datacaching

Can you please provide more details on the request for Tiered storage and control on cache?

**Comment by apc999** [comment]
@xumingming thanks for the interests. Another feature you can take a look, to make Alluxio transparent to users, is https://docs.alluxio.io/ee/user/stable/en/operation/Transparent-Uri.html  let me know if this works for you
