### ISSUE TITLE
Optimize Hive Connector's file path filtering merchanism

### ISSUE THREAD

**Issue by xumingming** [prestodb/presto#14746]
Currently Hive Connector hive a merchanism to filter the file path to be scanned:

```java
    private Iterator<HiveFileInfo> getLocatedFileStatusRemoteIterator(Path path, PathFilter pathFilter)
    {
        try (TimeStat.BlockTimer ignored = namenodeStats.getListLocatedStatus().time()) {
            return Iterators.filter(new FileStatusIterator(path, listDirectoryOperation, namenodeStats), input -> pathFilter.accept(input.getPath()));
        }
    }
```

The filtering is using PathFilter, which only have the path, dropped the information which is available in `HiveFileInfo` e.g. `HiveFileInfo#isDirectory()`, I'd suggest we do the filtering using HiveFileInfo:

```java
public interface HiveFileInfoFilter
{
    boolean accept(HiveFileInfo file);
}
```

If you guys are ok with this, I'd be happy to contribute a patch to optimize this.

**Comment by mbasmanova** [comment]
CC: @yingsu00 @bhhari @oerling @sujay-jain @jbroll 

@xumingming I don't understand the optimization you propose. Would you explain?

**Comment by xumingming** [comment]
@mbasmanova 
Internally, we have a feature to filtering the files to be scanned based on filename patterns, e.g. `*.csv`, `*.parquet` etc. So we need to only filter on the concrete file path not the directory path, the logic is something like:

```java
if (isDirectory) {
    return true;
} else {
    // apply the actual filtering logic
}
```

So we need to know whether current path is a directory or not.  And since the output the HiveFileIterator is HiveFileInfo, I think it make sense to filtering on `HiveFileIterator`.

**Comment by mbasmanova** [comment]
CC: @kewang1024 @highker @jainxrohit 

> we have a feature to filtering the files to be scanned based on filename patterns, e.g. *.csv, *.parquet etc.

Why would that be useful? How do you create the files? In Hive, each directory stores all the files that belong to a given partition. I don't understand how a single directory can have files of different formats.

**Comment by xumingming** [comment]
The feature is useful when the files are uploaded by user manually or by other program rather than managed by Hive, it is not a so common use case, but it is useful when user need it.

**Comment by mbasmanova** [comment]
@xumingming James, the change you propose might be ok. Would you submit a PR so we can see what are the actual changes? Also, would you explain how you are going to use the new API? Are you going to maintain a private patch that uses a different implementation of the HiveFileInfoFilter?

**Comment by xumingming** [comment]
@mbasmanova ok, I will submit a PR recently. After the filtering mechanism is optimized, our private fork of Presto will plugin in a piece of code in BackgroundSplitLoader, which will construct a HiveFileInfoFilter using the following logic:

```java           
            List<String> patterns = <Get the filename pattern from Hive Metastore>
            hiveFileInfoFilter = new FilePatternHiveFileInfoFilter(patterns);
```

And this pattern will be passed along into HiveFileIterator.

**Comment by mbasmanova** [comment]
@xumingming Got it. Thanks for explaining. Looking forward to a PR.
