### ISSUE TITLE
Hive Connector: Ignore empty files when scanning files

### ISSUE THREAD

**Issue by xumingming** [prestodb/presto#14759]
Currently if the table(external table) are created as format e.g. Parquet, and there is an empty file(zero length) in the directory, an error will occur:

```
oss://xxxxxx/xxxx/empty_file is not a valid Parquet File
```

For the ease of use, we can safely skip all the empty files to avoid this error, how do you guys think? (The empty file use case will not occur if the files are managed by Hive, but could occur if the files are uploaded by user or any other program, when using Object Store Services).

**Comment by mbasmanova** [comment]
@xumingming Do you have a full stack trace? Does the error come Parquet reader. It might be reasonable to not fail on empty files, but return empty Page.

CC: @bhhari @oerling @jbroll @sujay-jain

**Comment by mbasmanova** [comment]
CC: @zhenxiao

**Comment by zhenxiao** [comment]
hi @xumingming @mbasmanova I feel if a Hive connector table with metadata specified as Parquet format, all files should be Parquet format. empty files seems invalid cases. Am not convinced to have ParquetReader skip non-parquet-empty files. What do you think?

**Comment by mbasmanova** [comment]
@zhenxiao We had a similar discussion about empty ORC files. Hive connector currently fails to read these. This is correct behavior I think. At the same time, looks like there are use cases where empty files do show up in the directory and cause failures that are disruptive to the users.

**Comment by xumingming** [comment]
Yeah I agree from "strict" perspective, it is totally right to throw exceptions for empty files which are illegal for format like ORC, Parquet. This issue arise most when the files are uploaded by user, or generated by other programs, we have use cases that data is generated by some other services, the service will generate empty file when there is no data. Push the service to fix the issue will require long time, during this time the old data can't be used.

**Comment by zhenxiao** [comment]
get it. sure. how about an idea of:
1. having a configurable hive property to skip empty files, default to be false
2. for ORC, Parquet, RCFile, and other cursors to skip empty file when scanning
what do you think? @xumingming @mbasmanova

**Comment by xumingming** [comment]
@zhenxiao So you mean for ORC/Parquet/RCFile, we auto-skip empty files; For other format we respect the newly added flag?

**Comment by mbasmanova** [comment]
Having an hive.skip-emply-files configuration flag with default value of false sounds good to me. By default, queries fail to scan empty files. When flag is set, queries succeed.

**Comment by xumingming** [comment]
OK, sounds good to me :)
