### ISSUE TITLE
[ElasticSearch Connector] Add support for ip/ip_range data types

### ISSUE THREAD

**Issue by canob** [prestodb/presto#14806]
Hi,

It is possible to support ip data type in ElasticSearch Connector (IPADDRESS data type in Presto)?

PrestoDB has data types and functions that PrestoSQL hasn't, like IP_PREFFIX, that are perfect for work with subnets/CIDR in queries, but lack for example the ip/IPADDRESS data type in ElasticSearch Connector, which PrestoSQL has (alongside with long | BIGINT for example, which is the other data type that PrestoSQL has for ElasticSearch Connector, and PrestoDB hasn't)

https://prestodb.io/docs/current/connector/elasticsearch.html#data-types
https://prestosql.io/docs/current/connector/elasticsearch.html#data-types

Is it possible to add support for this in PrestoDB? Because without this, I cannot query ElasticSearch ip type fields, :-S

Even better, maybe it is possible to add support (using IP_PREFFIX data type in PrestoDB, or something similar) to ip_range data type in ElasticSearch:
https://www.elastic.co/guide/en/elasticsearch/reference/current/range.html

For your evaluation.

Thanks in advance.

Regards,
Alejandro
.

**Comment by mbasmanova** [comment]
CC: @zhenxiao

**Comment by mbasmanova** [comment]
@canob Alejandro, would you like to contribute these enhancements?

**Comment by canob** [comment]
Hi @mbasmanova Maria, how are you?

I would love to contribute to adding this functionality, but I don't have enough necessary development knowledge, so I was asking if someone would be able to port it from the PrestoSQL project if there were more interested PrestoDB users.

**Comment by mbasmanova** [comment]
CC: @jagill

**Comment by agrawalreetika** [comment]
I would like to work on this. I will look into porting it from PrestoSQL, as this is already available there.

**Comment by agrawalreetika** [comment]
PR for this support is merged. We are good to close to this issue :)
