### ISSUE TITLE
[JDBC] Implement ResultSet.getStatement() API

### ISSUE THREAD

**Issue by chdw** [prestodb/presto#14804]
In my code, I pass only resultSet into my method, without statement object

I try to call rs.getStatement() to get some infos, but it throw a NotImplementedException.

Can this method be implemented in the next release?

**Comment by mbasmanova** [comment]
@chdw Would you like to contribute this enhancement?

CC: @adamjshook

**Comment by adamjshook** [comment]
@mbasmanova I can take a look at it.  Seems like we'd just want to pass in the `Statement` when the `PrestoResultSet` is created and return it in `getStatement`? Any catches here?

**Comment by mbasmanova** [comment]
This could be as simple as that.
