### ISSUE TITLE
Presto 0.234.1 is not accepting dynamically refreshing Access Tokens for accessing GCS

### ISSUE THREAD

**Issue by hmanju2k7** [prestodb/presto#14832]
We are using Presto 0.234.1 version. We are delegating a ServiceAccountCredentail with user email and passing the access token to Presto via Extra Credential. Everything is working as expected until the first token expires.

But after the default 1hr expiry of the AccessToken, Presto is not taking the new Access Token that is passed using the Extra Credential and throwing invalid-token error when trying to access the GCS bucket.

Properties used in **Hive.properties**:
hive.metastore-refresh-interval=1m
connector.name=hive-hadoop2
hive.metastore-cache-ttl=20m
hive.metastore.uri=thrift://xxxxxxx:xxx
hive.gcs.use-access-token=true
hive.hdfs.impersonation.enabled=true

**Comment by mbasmanova** [comment]
CC: @mayankgarg1990

**Comment by beinan** [comment]
I think this one will be fixed by this commit in presto-hadoop-apache2 https://github.com/prestodb/presto-hadoop-apache2/commit/3640920cfae094c823cefa2b73329ae3eea50cae

We also need to update the pom file in presto project once the next version of presto-hadoop-apache2 is released

**Comment by mbasmanova** [comment]
CC: @zhenxiao

**Comment by mbasmanova** [comment]
Per @beinan comment, this is fixed in PR #43 CC: @jainxrohit

**Comment by zhenxiao** [comment]
I think we need a new presto-hadoop-apache2 release to get this fixed @caithagoras @jainxrohit

**Comment by caithagoras** [comment]
acked. I'll start the release.

**Comment by caithagoras** [comment]
@zhenxiao 2.7.4-8 is now available from Maven.

**Comment by zhenxiao** [comment]
thank you, @caithagoras
