### ISSUE TITLE
Port OFFSET from prestosql

### ISSUE THREAD

**Issue by rongrong** [prestodb/presto#14837]
Feature is blogged: https://prestosql.io/blog/2020/02/03/beyond-limit-presto-meets-offset-and-ties.html

PrestoSQL issue: https://github.com/prestosql/presto/issues/1

**Comment by fgwang7w** [comment]
hi I can take this issue and fix it into the next release

**Comment by rongrong** [comment]
@fgwang7w Thanks for working on this!
