### ISSUE TITLE
Guidelines for contributing to the project

### ISSUE THREAD

**Issue by kosuruvarunkumar** [prestodb/presto#14864]
Hello, I am very new to this project and am very willing to join in the contributor's list. As I am new to this environment, I do not know the understandings required to make code contributions. And as I cannot send a private message to any of the core committers, I am creating this issue, along with that if people add comments to this, this could be helpful to the people who wish to contribute here.
The questions that I have are:
- How to have a good solid understanding of the codebase which would help in triaging the issues?
- What theoretical concepts are required?
- Where to and how to start with the contributions in code(to be precise but not limited)?

As a new member of the group, any suggestions will be very helpful.
I m sorry for repeating if this is addressed somewhere else.

Thank you

**Comment by aweisberg** [comment]
Hi, 

Welcome!
If you want to get started contributing you could pick up a [beginner task](https://github.com/prestodb/presto/issues?q=is%3Aopen+is%3Aissue+label%3Abeginner-task).
There is a paper [Presto SQL on everything](https://research.fb.com/publications/presto-sql-on-everything/).

Instructions for getting started with development are here https://github.com/prestodb/presto#presto-

Also useful is [Presto Development Guidelines](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines) and [Review and Commit guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines).

This is a question best asked in [Slack](https://join.slack.com/t/prestodb/shared_invite/enQtNTQ3NjU2MTYyNDA2LTYyOTg3MzUyMWE1YTI3Njc5YjgxZjNiYTgxODAzYjI5YWMwYWE0MTZjYWFhNGMwNjczYjI3N2JhM2ExMGJlMWM) and not in an issue (issues are for task tracking).
