### ISSUE TITLE
Add session property to capture HIVE_PARTITION_NOT_READABLE as warnings

### ISSUE THREAD

**Issue by highker** [prestodb/presto#14870]
Before throwing `HIVE_PARTITION_NOT_READABLE` errors, we will check a session property. The session property can convert the error into warnings so that the query can still run by ignoring the offline partition.

Use `WarningCollector` to collect the warnings.

**Comment by Naveen007** [comment]
@highker Do we need this session property only to control "ignoring offline partitions" or all cases of "hive partitions not readable"

**Comment by highker** [comment]
The exception is only created at one place: https://github.com/prestodb/presto/blob/3060c65a1812c6c8b0c2ab725b0184dbad67f0ed/presto-hive/src/main/java/com/facebook/presto/hive/HiveNotReadableException.java#L34

So, it will be a catch on this exception and collect the warning.

**Comment by Naveen007** [comment]
But there is a class PartitionOfflineException that is being thrown before the Hive partition not readable one. 
 if (!isOfflineDataDebugModeEnabled(session)) {
                    // verify partition is online
                    verifyOnline(tableName, Optional.of(partName), getProtectMode(partition), partition.getParameters());

                    // verify partition is not marked as non-readable
                    String partitionNotReadable = partition.getParameters().get(OBJECT_NOT_READABLE);
                    if (!isNullOrEmpty(partitionNotReadable)) {
                        throw new HiveNotReadableException(tableName, Optional.of(partName), partitionNotReadable);
                    }
                }

**Comment by highker** [comment]
There is still case when a partition is online but not readable. We wanna provide the option to raise a warning when a partition is online but not readable.

**Comment by Naveen007** [comment]
Ok So this session property will control ignoring the non-readable but online partitions. I was confused since the initial comment said "the query can still run by ignoring the offline partition".
