### ISSUE TITLE
remove Limit/TopN/Sort/DistinctLimit when relation is know to single row or less rows than requested

### ISSUE THREAD

**Issue by fgwang7w** [prestodb/presto#14897]
port https://github.com/prestosql/presto/issues/759 to remove unnecessary sort exchange operations in queries

**Comment by mbasmanova** [comment]
CC: @rschlussel @rongrong @kaikalur

**Comment by mbasmanova** [comment]
@fgwang7w George, are you planning to work on this?

**Comment by fgwang7w** [comment]
> @fgwang7w George, are you planning to work on this?

Yes I am actively working on this item now. Will be available for review this week.

**Comment by fgwang7w** [comment]
> @fgwang7w George, are you planning to work on this?

Hi Maria, please help review the commit for this issue when you have a chance. Thanks!
