### ISSUE TITLE
Missing registration for system.sync_partition_metadata

### ISSUE THREAD

**Issue by fabiocbr75** [prestodb/presto#14946]
Hello,
I use PrestoDb (version 230) on AWS EMR (6.0) but the only way to add partition directly in presto (without using Hive) is the system.create_empty_partition function.
Can you add the system.sync_partition_metadata (present in prestosql) to synchronize the prestodb partition with s3 bucket?

Thanks
Fabio

**Comment by mbasmanova** [comment]
CC: @jamesgpearce 

@fabiocbr75 Would you like to port the relevant changes from prestosql?

**Comment by fabiocbr75** [comment]
I'm sorry but I don't have the java skill to do that (I'm a .net developer).

F.

**Comment by ClarenceThreepwood** [comment]
I'll work on this
