### ISSUE TITLE
Support session-based temporary SQL function

### ISSUE THREAD

**Issue by rongrong** [prestodb/presto#14951]
We've recently introduced SQL function support in Presto. The current implementation uses external databases (MySQL) to store SQL functions which can be shared and used by different users. Sometimes we do not want / need the SQL functions to be shared, so we also want to introduce the support of session based temporary SQL Functions. We can do this by:
* Attaching function definitions with a session.
* Adding a session based `FunctionNamespaceManager`.

**Comment by rongrong** [comment]
For syntax support in CLI, we can consider either extending the SQL syntax to add a `TEMPORARY` keyword as in `CREATE TEMPORARY FUNCTION xxx`, or make it implicit as how `FunctionNamespaceManager`s are set up, where the session based `FunctionNamespaceManager` will be assigned a function "catalog" to manage, and functions created in that "catalog" will be only visible for the session it's created in. Open for discussion.

**Comment by rongrong** [comment]
cc @kaikalur

**Comment by kaikalur** [comment]
The notion of session is a bit nebulous. For a CLI, it's clear but I'm not sure we have that in other clients. If we have a StartSession and EndSession commands for all clients, then temporary can be implemented cleanly.

**Comment by ingomueller-net** [comment]
Does #15033 not solve this?
