### ISSUE TITLE
Column Access Checks should only check used columns

### ISSUE THREAD

**Issue by rschlussel** [prestodb/presto#15023]
Currently we perform access control checks for all columns referenced in a query, even if some aren't used and would later be removed by column pruning.  For example, if a user runs the query `SELECT x FROM (SELECT * from my_table)`, we will check select permissions for all columns in my_table, even though the user only accesses column x.  This causes friction when people want to add new restrictions on certain columns, because users who are using the `SELECT x FROM (SELECT *...` pattern suddenly see their queries start to fail even though they aren't really using the sensitive column.

Here are 2 possible solutions

1. keep the column access checks during analysis.  Add a column pruning rule that operates on statements.  Run at the end of analysis, then go through and gather all the columns used and check column access

2. Move column access control checks to the beginning of planning.  Immediately after the logical plan is built, run column pruning rules.  Then run column access control checks for the output columns of all of the table scans.  Then do optimization. We can't move column access checks after optimization because some of our rules might be too smart and leak data about the restricted columns (e.g. no matching partitions or some table layout that enforces a constraint and therefore restricted columns are no longer necessary).

**Comment by rschlussel** [comment]
@highker @rongrong @kaikalur

**Comment by Vayu** [comment]
> We can't move column access checks after optimization because some of our rules might be too smart and leak data about the restricted columns

Does Presto use restricted data in the query plan? Partition values, column stats, table sizes are public in Hive Metastore

**Comment by Vayu** [comment]
Few similar use-cases which are most commonly occurring.

Already mentioned subquery projection
```
SELECT columnB FROM  (
    SELECT * FROM table WHERE columnA = 'xxx'
)
```
Should request permissions for columnA, and columnB

Projection of a CTE
```
WITH cte1 AS (
    SELECT * FROM table WHERE columnA = 'xxx'
)
SELECT columnB FROM cte1
```
Should request permissions for columnA, and columnB

Projection of a CTE, with added derived column (and same for sub-query)
```
WITH cte1 AS (
    SELECT
       *,
       columnC = 'beep' AS is_beep
    FROM table WHERE columnA = 'xxx'
)
SELECT columnB, is_beep FROM cte1
```
Should request permissions for columnA, columnB and columnC

**(Less Important)** Projection of a CTE, with added derived and unused column (and same for sub-query)
```
WITH cte1 AS (
    SELECT
       *,
       columnC = 'beep' AS is_beep
    FROM table WHERE columnA = 'xxx'
)
SELECT columnB FROM cte1
```
Should request permissions for columnA, columnB


**(Less Important)** Unused CTE
```
WITH cte1 AS (
    SELECT
       *
    FROM table WHERE columnA = 'xxx'
)
SELECT columnX FROM other_table
```
Should request permissions for columnX from "other_table" and nothing from "table"

**Comment by rschlussel** [comment]
@kaikalur suggests that during analysis we can tell which columns get referenced, so instead of doing any pruning, just collect only columns that get referenced and use those.

**Comment by prithvip** [comment]
Fixed by https://github.com/prestodb/presto/pull/15269
