### ISSUE TITLE
Cannot download prest-druid on version lastest and version 0.237.2

### ISSUE THREAD

**Issue by tuongtd88** [prestodb/presto#15038]
I have problem with this issue: presto-druid: Could not resolve dependencies for project com.facebook.presto:presto-druid:presto-plugin:0.241-SNAPSHOT: Failed to collect dependencies at org.apache.druid:druid-processing:jar:0.17.0 -> org.apache.druid:druid-core:jar:0.17.0 -> org.hyperic:sigar:jar:1.6.5.132: Failed to read artifact descriptor for org.hyperic:sigar:jar:1.6.5.132: Could not transfer artifact org.hyperic:sigar:pom:1.6.5.132 from/to apache.snapshots (https://repository.apache.org/snapshots): Connection reset

Please help me

**Comment by beinan** [comment]
I just checked out the latest master and run `./mvnw clean install -DskipTests=true`.  I'm afraid I cannot reproduce the error on my laptop.  It looks like a network connection issue.

A couple of tips you can try:
1.  Using newer version of maven. (there is a better retry mechanism after maven 3.6.1)
2. Setup a proxy or vpn 
3. adding -Dhttps.protocols=TLSv1.2. -- https://stackoverflow.com/questions/34170811/maven-connection-reset-error

**Comment by tuongtd88** [comment]
Thanks @beinan,

But I problem in here, I couldn't find hyperic in this link https://repository.apache.org/snapshots/org

**Comment by beinan** [comment]
> Thanks @beinan,
> 
> But I problem in here, I couldn't find hyperic in this link https://repository.apache.org/snapshots/org

Sorry for misunderstanding the problem.  Yep, you're right ,it's not in https://repository.apache.org/snapshots/org

Looks like my mvn downloaded it from https://repository.jboss.org

`Downloading: https://repo.maven.apache.org/maven2/org/hyperic/sigar/1.6.5.132/sigar-1.6.5.132.pom
Downloading: https://repository.apache.org/snapshots/org/hyperic/sigar/1.6.5.132/sigar-1.6.5.132.pom
Downloading: https://repository.jboss.org/nexus/content/repositories/thirdparty-uploads/org/hyperic/sigar/1.6.5.132/sigar-1.6.5.132.pom
Downloaded: https://repository.jboss.org/nexus/content/repositories/thirdparty-uploads/org/hyperic/sigar/1.6.5.132/sigar-1.6.5.132.pom (1.5 kB at 1.8 kB/s)
Downloading: https://repo.maven.apache.org/maven2/org/hyperic/sigar/1.6.5.132/sigar-1.6.5.132.jar
Downloading: https://repository.apache.org/snapshots/org/hyperic/sigar/1.6.5.132/sigar-1.6.5.132.jar
Downloading: https://repository.jboss.org/nexus/content/repositories/thirdparty-uploads/org/hyperic/sigar/1.6.5.132/sigar-1.6.5.132.jar
Downloaded: https://repository.jboss.org/nexus/content/repositories/thirdparty-uploads/org/hyperic/sigar/1.6.5.132/sigar-1.6.5.132.jar (429 kB at 1.5 MB/s)`

**Comment by tuongtd88** [comment]
Thanks @beinan.

I resloved this problem. Thank you very much.
