### ISSUE TITLE
Query xxxx failed: Found string, expecting union 

### ISSUE THREAD

**Issue by veselamanolova** [prestodb/presto#15041]
The error message: **"Query xxxx failed: Found string, expecting union"** appears when executing a select statement for a table created as shown in the example below:

`create table dbo.pr_date( 
 mbr_brth_dt_sk timestamp
) 
with ( external_location = 'xxxx');`

If table is dropped and recreated changing the column name from **mbr_brth_dt_sk** to  **mbrbrth_dt_sk**  or **brth_dt_mbr_sk** select  issue is not observed.

**Comment by mbasmanova** [comment]
@veselamanolova Would you share the select query that fails?

**Comment by mbasmanova** [comment]
Would you also share a stacktrace? You can get it by running presto cli with --debug option.

**Comment by veselamanolova** [comment]
![SelectWithDebug](https://user-images.githubusercontent.com/50833263/90513580-8b693e00-e168-11ea-9753-91e8b937a994.png)
![tableColumnType](https://user-images.githubusercontent.com/50833263/90513593-902df200-e168-11ea-90d3-ea169131e347.png)

**Comment by findepi** [comment]
@veselamanolova Presto 3xx releases are maintained at https://github.com/prestosql/presto.
Also, there is the `#troubleshooting` channel on Presto Community Slack (https://prestosql.io/slack.html)
