### ISSUE TITLE
Multiline CSVs support using Hive

### ISSUE THREAD

**Issue by sido420** [prestodb/presto#15062]
I am fairly new to Presto and not sure if this a bug, FR, or a usability issue.

I have been trying to import CSVs with multiple lines in cells, but multiple lines (within a cell) are treated as new records by Presto.
```
CREATE TABLE dbname."tablename" (
  "MultilineCell" varchar,
 "ID" varchar,
 "AnotherValue" varchar
) WITH (format = 'CSV', csv_separator=',', csv_quote='"', csv_escape='\',  partitioned_by = ARRAY['ID', 'AnotherValue']);
```
Imports are done by copying CSVs directly into HDFS directories. Also, I have double checked CSV file ie. values are separated by commas and enclosed with ".

If you run this INSERT for the above table, Presto would create 3 new records.
```
insert into dbname."tablename" values ('"ewrew
rerew    
rewrew434213"', '1','name2');
```

**Comment by mbasmanova** [comment]
> Presto Server: presto-server-340

I believe you are using PrestoSQL, not PrestoDB. CC: @findepi

**Comment by findepi** [comment]
@sido420  Presto 3xx releases are maintained at https://github.com/prestosql/presto.
Also, there is the `#troubleshooting` channel on Presto Community Slack (https://prestosql.io/slack.html)

thanks @mbasmanova for heads up!
