### ISSUE TITLE
GROUP BY not consistent with IS DISTINCT FROM for NaN

### ISSUE THREAD

**Issue by martint** [prestodb/presto#1508]
In 0.73:

```
presto> select nan() is distinct from nan();
 _col0 
-------
 true 
```

```
presto:datascience> select distinct a/a FROM (VALUES (0.0), (0.0)) x (a);
 _col0 
-------
   NaN 
   NaN 
```

But in master (0.74):

```
presto> select nan() is distinct from nan();
 _col0 
-------
 true  
```

```
presto> select distinct a/a FROM (VALUES (0.0), (0.0)) x (a);
 _col0 
-------
   NaN 
```

The behavior in 0.74 is inconsistent. NaNs should not group together if they are distinct from each other.

We should actually change the behavior to make NaN work like nulls: 

```
NaN = NaN => false
NaN IS NOT DISTINCT FROM NaN => true
```

**Comment by cberner** [comment]
Just discussed with @dain and @electrum. The problem is that `select nan() is distinct from nan();` should return false

**Comment by martint** [comment]
We should be able to fix this once https://github.com/prestodb/presto/pull/6091 is merged

**Comment by electrum** [comment]
This test case should produce a single row:
```
presto:di> select * from (values nan(), nan(), nan()) group by 1;
 _col0                
-------
   NaN 
   NaN 
   NaN 
(3 rows)
