### ISSUE TITLE
How presto can show Chinese in the query results support ?

### ISSUE THREAD

**Issue by mana6666** [prestodb/presto#15102]
presto verson : 302

cannot get the chinese result in correct form according to issue#3417.
the error is :
io.prestosql.spi.PrestoException: invalid input length 39
	at io.prestosql.operator.scalar.VarbinaryFunctions.fromHexVarchar(VarbinaryFunctions.java:134)

**Comment by rongrong** [comment]
Seems like you are using a different Presto. Sorry about this confusion. You can open an issue at https://github.com/prestosql/presto for PrestoSQL related questions, or give PrestoDB a try ;) Thanks!

**Comment by findepi** [comment]
@mana6666  Presto 3xx releases are maintained at https://github.com/prestosql/presto.
Also, there is the `#troubleshooting` channel on Presto Community Slack (https://prestosql.io/slack.html)
