### ISSUE TITLE
how to return chinese ?

### ISSUE THREAD

**Issue by mana6666** [prestodb/presto#15118]
verson 310.
hive+presto.
using the same sql,
i can get correct form chinese in hive sql and hive terminal.

but i can't get correct form in presto terminal.

my catalog/hive.properties is like this:

connector.name=hive-hadoop2
hive.metastore.uri=thrift://localhost:9083
hive.config.resources=/opt/hive/conf/hive-site.xml

hive-site.xml is :
<configuration>
    <property>
        <name>system:java.io.tmpdir</name>
        <value>/tmp/hive/java</value>
    </property>
    <property>
        <name>system:user.name</name>
        <value>${user.name}</value>
    </property>
    <property>
        <name>javax.jdo.option.ConnectionURL</name>
        <value>jdbc:mysql://localhost/metastore?createDatabaseIfNotExist=true&amp;useUnicode=true&amp;characterEncoding=UTF-8</value>
    </property>
    <property>
        <name>javax.jdo.option.ConnectionDriverName</name>
        <value>com.mysql.jdbc.Driver</value>
    </property>
    <property>
        <name>javax.jdo.option.ConnectionUserName</name>
        <value>hive</value>
    </property>
    <property>
        <name>javax.jdo.option.ConnectionPassword</name>
        <value>hive</value>
    </property>
    <property>
        <name>hive.mapred.supports.subdirectories</name>
        <value>true</value>
    </property>
     <property>
        <name>mapreduce.input.fileinputformat.input.dir.recursive</name>
        <value>true</value>
    </property>
    <property>
        <name>hive.metastore.warehouse.dir</name>
        <value>alluxio://localhost:19998/iptvqoe/data</value>
        <description>location of default database for the warehouse</description>
    </property>

</configuration>

**Comment by findepi** [comment]
@mana6666  Presto 3xx releases are maintained at https://github.com/prestosql/presto.
Also, there is the `#troubleshooting` channel on Presto Community Slack (https://prestosql.io/slack.html)
