### ISSUE TITLE
Presto cannot read parquet files

### ISSUE THREAD

**Issue by spachari** [prestodb/presto#15150]
I am getting the following error:

Error opening Hive split s3a://prod/etl/db/table_name/part-00005-0b412c25-813f-4309-91e3-9aeaf805e68e-c000.snappy.parquet (offset=0, length=268435456) using org.apache.hadoop.mapred.SequenceFileInputFormat: s3a://prod/etl/db/table_name/part-00005-0b412c25-813f-4309-91e3-9aeaf805e68e-c000.snappy.parquet not a SequenceFile

I have not seen this type of error before, does Presto not work with parquet files? Or is it a version issue, please let me know.

**Comment by zhenxiao** [comment]
hi, Presto could query parquet files.
From the error message, it seems the metastore stores the table using SequenceFile, so it is expecting SequenceFileInputFormat. But encountered parquet files.
This is probably a metastore incompatibility issue. Could you please update file inputformat to be Parquet?

**Comment by spachari** [comment]
Thanks, it works fine. Please close this issue.
