### ISSUE TITLE
add support for prometheus connector

### ISSUE THREAD

**Issue by fgwang7w** [prestodb/presto#15176]
add support for prometheus connector

**Comment by gtangthousandeyes** [comment]
hello @fgwang7w , just curious question. Is the prometheus plug-in ready to roll out? I see these in the presto documentation https://prestosql.io/docs/current/connector/prometheus.html but I do not see a prometheus-plugin in the master branch

**Comment by wadhahbenaissa** [comment]
hello @fgwang7w I was wondering if it's ready to rollout as well.

@gtangthousandeyes were you able to have this working with some sort of a workaround?

**Comment by gtangthousandeyes** [comment]
@wadhahbenaissa, yep got it working

**Comment by wadhahbenaissa** [comment]
@galemccommons I was wondering if you could please share your findings.

**Comment by fgwang7w** [comment]
@gtangthousandeyes It's currently under final approval in review process, I will give another push to make it in prestoDB soon

**Comment by iceted** [comment]
@gtangthousandeyes @wadhahbenaissa @fgwang7w I see its already available in presto 334: https://prestosql.io/docs/current/release/release-334.html

**Comment by wadhahbenaissa** [comment]
Hello guys again.
I was trying to deploy "presto" alongside "superset" on an AKS using helm charts using accordingly these charts https://github.com/helm/charts/tree/master/stable/presto and https://github.com/helm/charts/tree/master/stable/superset.

Prometheus still not working for me. I was trying as well to make use of elasticsearch connector by adding elasticsearch.properties with the content from this link https://prestosql.io/docs/current/connector/elasticsearch.html, to configmap-worker.yaml and configmap-coordinator.yaml (from the templates provided by the chart), but still elasticsearch is not being added to the list of catalogs (after accessing the presto container, `cd /usr/lib/presto/default/etc/catalog`, elasticsearch is not among the default catalogs. )

So, I was wondering if I can get your inputs on this regard.
Thanks a lot

**Comment by gtangthousandeyes** [comment]
hey @wadhahbenaissa, for my usecase, I was using PrestSQL 338 on AWS' EMR cluster. To get the prometheus working, you will need to add a `prometheus.properties` file at `/etc/presto/conf/catalog/` https://prestosql.io/docs/current/connector/prometheus.html. All the metrics collected by prometheus are their own tables stored in the `default` schema.
I hope this helps.

**Comment by findepi** [comment]
@wadhahbenaissa @gtangthousandeyes  Presto 3xx releases are maintained at https://github.com/prestosql/presto.
Also, there is the `#prometheus-connector` channel on Presto Community Slack (https://prestosql.io/slack.html)
