### ISSUE TITLE
Add a proxy endpoint for tasks

### ISSUE THREAD

**Issue by tdcmeehan** [prestodb/presto#15192]
In some setups, the coordinator may be configured with particular egress rules which allow it to be queried, but the workers may have more stringent restrictions.  In these cases, querying the worker endpoints for task information is not possible.  

It would be good to have an endpoint on the coordinator, which only supports `GET`s on task information, which proxies this information back from the workers (similar to how the `WorkerResource` currently works--this can be used as a reference).

The web UI can then be fixed to use the proxy endpoint, rather than redirecting directly to the worker TaskResource endpoints.

**Comment by pratikSethi** [comment]
@tdcmeehan Hi, can I give this a shot?

**Comment by tdcmeehan** [comment]
@pratikSethi please do.  Thank you.

**Comment by pratikSethi** [comment]
Awesome, thanks!
