### ISSUE TITLE
v0.241 Oracle Connector   logon denied

### ISSUE THREAD

**Issue by shigechuanqi** [prestodb/presto#15232]
After installing and configuring Oracle Connector, the execution query shows "ORA-01017: invalid username/password; logon denied"

https://github.com/prestodb/presto/blob/715704fd0c09f354cb518d6c24ebc30a3f49d6a9/presto-oracle/src/main/java/com/facebook/presto/plugin/oracle/OracleClientModule.java#L47

It seems that ORACLE parameters are not processed?

**Comment by brokenjacobs** [comment]
Seeing the same thing here. Our custom oracle connector from previous versions worked.

**Comment by brokenjacobs** [comment]
As a workaround... this worked for me. Change your jdbc uri to this format:
 jdbc:oracle:thin:[<user>/<password>]@//<host>[:<port>]/<service>

**Comment by shigechuanqi** [comment]
> 作为解决方法，这对我有用。将您的jdbc uri更改为以下格式：
> ` jdbc:oracle:thin:user/password@//<host>[:<port>]/<service>`

Thank you very much.

At present, it is also used in this way

**Comment by rahmanmd007** [comment]
I am using  Presto 0.265.1 and it is not working for me. 
I have tried both:
connector.name=oracle
connection-url=jdbc:oracle:thin:@example.net:1521/ORCLCDB
connection-user=root
connection-password=secret
When I used the above, I get ORA-01017 error
AND when I use the following I get 'Invalid URL Specified' Error. Can someone please help? 
connector.name=oracle
connection-url=jdbc:oracle:thin:user/password@//<host>[:<port>]/<service>

**Comment by jameskim0987** [comment]
The docs here helped me. http://www.orafaq.com/wiki/JDBC


`jdbc:oracle:thin:[<user>/<password>]@//<host>[:<port>]/<service>`

**Comment by rahmanmd007** [comment]
@jameskim0987 That worked.. Thanks!
