### ISSUE TITLE
The EventListener plugin does not receive events on abandoned queries

### ISSUE THREAD

**Issue by joeledwards** [prestodb/presto#15245]
Version: Starburst Presto 338-E.0 (not sure how this maps to the OS version)

Most events which result in a terminal state of `FAILED` for a query are also reported to the EventListener plugin. However, there are cases where a query fails and the EventListener never receives a notification.

My most recent observation involved four different queries, all of which ended up in `FAILED` state due to abandonment. Only half of them ended up reported to the EventListener.

When I looked for the failures in the server log, I noticed that those which made it to the EventListener were reported by a `dispatch-executor` thread; whereas those which were _not_ sent to the EventListener were reported by a `query-management` thread.

I suspect there are multiple paths which may lead to a query getting marked as `FAILED` due to timeout. However, it does not appear that the EventListener is correctly tied in to all of those paths.

*Skipped the EventListener*
`2020-09-29T13:26:36.221Z        INFO    dispatch-executor-4     io.prestosql.execution.QueryTracker     Failing abandoned query 20200929_131803_05143_67rk5`
`2020-09-29T13:26:36.222Z        INFO    dispatch-executor-4     io.prestosql.execution.QueryTracker     Failing abandoned query 20200929_131803_05144_67rk5`

*Sent to the EventListener*
`2020-09-29T15:48:29.251Z        INFO    query-management-4      io.prestosql.execution.QueryTracker     Failing abandoned query 20200929_152914_06058_67rk5`
`2020-09-29T15:48:28.251Z        INFO    query-management-3      io.prestosql.execution.QueryTracker     Failing abandoned query 20200929_153405_06113_67rk5`

**Comment by findepi** [comment]
@joeledwards  Presto 3xx releases are maintained at https://github.com/prestosql/presto.
There is the `#troubleshooting` channel on Presto Community Slack (https://prestosql.io/slack.html)
Incidentally, there is also `#starburst` channel there where you can ask any Starburst-specific questions.

**Comment by joeledwards** [comment]
I suspect this may still be an issue with the mainline.
