### ISSUE TITLE
Change warning to ignore unreadable partitions to be a digest

### ISSUE THREAD

**Issue by highker** [prestodb/presto#15285]
`PARTITION_NOT_READABLE` warning created in `HiveSplitManager` is to warn each unreadable partition. This is too excessive. For example:
```
Table my_table partition 'part1' is not readable: <REASON>
Table my_table partition 'part2' is not readable: <REASON>
Table my_table partition 'part5' is not readable: <REASON>
```

Ideally, in the partition batch loop, we collect what partitions are unreadable and summarize them in a single warning at the end. Something like
```
Table my_table has 3 out of 50 partitions: 'part1', 'part2', 'part5' not readable: <REASON>
```

**Comment by Moe82** [comment]
Hi, highker. Can I give this issue a shot?

**Comment by highker** [comment]
@Moe82, yes please.

**Comment by Moe82** [comment]
@highker Sorry is this is a dumb question, but how can I test the changes I made?

**Comment by Moe82** [comment]
@highker, quick question- do all partitions in partitionBatch that are not readable have the same value for partitionNotReadable (the reason)? Or could there be more than 1 reason?

In other words, could the output be:

Table my_table has 3 out of 50 partitions: 'part1', 'part2', 'part5' not readable: <REASON1>
Table my_table has 2 out of 50 partitions: 'part6', 'part7',  not readable: <REASON2>

Thank you.

**Comment by highker** [comment]
@Moe82, that is a good observation. In theory, it could be. Likely we could show something like 
```
Table my_table has 3 out of 50 partitions: 'part1', 'part2', ... not readable: REASON_A, 2 out of 50 partitions: 'part6', 'part7', not readable: REASON_B
```

Note that
- We don't need to enumerate all partitions for the same reason to be completely due to readability and memory concern on large number of unreadable partitions. Maybe two would be good enough. The extra ones could just use "..."
- Same for the number of reasons. Maybe we only need 2. The rest can be presented with "..."
In such case, we only need 2 X 2 = 4 units of space in the for loop to build the warning message.

I agree in this case, we would prefer Map rather than List.
