### ISSUE TITLE
Optimizing nulls in join should be the last optimizer rule

### ISSUE THREAD

**Issue by kaikalur** [prestodb/presto#15282]
We adde an optimization to filter out nulls in:

https://github.com/prestodb/presto/pull/14578

But that cause issues when the subsequent optimization rules push it down further. So we should make the (one of the) file optimization rules so no further pushdowns will happen.

**Comment by ssaumitra** [comment]
As discussed offline, adding null filtering as a last optimisation rule has a disadvantage that the filters won't be pushed down to the main table. Therefore adding the filters before optimiser starts.

**Comment by aaneja** [comment]
https://github.com/prestodb/presto/pull/18938 fixes the issues observed around de-referencing. See test cases added with the [new rule](https://github.com/prestodb/presto/pull/18938/commits/4f8bc6ccd4a9626324e2b704e25eebf34814aab8#diff-68e1f723bdbf12a56f4a98f5212fa588c6d4ded0770068b465bfba336b55ef73R2461-R2501
)
