### ISSUE TITLE
Skip reading Parquet pages using Column Indexes feature of Parquet 1.11.x 

### ISSUE THREAD

**Issue by shangxinli** [prestodb/presto#15454]
PARQUET-1201 introduced Column Indexes feature. After the PR https://github.com/prestodb/presto/pull/14960, Presto should be able to use the Column Indexes to skip reading Parquet pages. This would be a significant performance booster. Here(https://blog.cloudera.com/speeding-up-select-queries-with-parquet-page-indexes/) is performance benchmarking data.

**Comment by shangxinli** [comment]
Updates: The task can be divided into 2 parts: reader and writer. The reader part code is working now and will be created PR shortly. The writer code is on the way.

**Comment by shangxinli** [comment]
Hi @zhenxiao @highker @vkorukanti, the code change is ready and @vkorukanti just had one round of review internally. I would like to ask for your suggestions how to proceed with the code review for this change, because it is a fairly large change. We all agree that we should have internal deployment in production before merging to open-source master branch, but we also don't want to have too much difference between our internal repo and open source repo. If we deploy to production first and then have code review in open source, for large changes like this it could cause the internal repo quite different with the open source one. 

Do you think it is a good idea that we can create a feature branch in the open source repo and have code reviews(expecting ~5 reviews) with you there? Then we take changes from there and deploy them. If there are changes needed during deployment, we also make changes in that feature branch.  After some time of the deployment, we request to merge to master. Merging to master should require the least time of review because we have reviewed the code and only conflicts and some sanity checks are needed. 

Let me know what do you think?

**Comment by JamesRTaylor** [comment]
Have you done any benchmarking on the read side in presto with this patch in place, @shangxinli?

**Comment by shangxinli** [comment]
https://github.com/prestodb/presto/pull/16963
