### ISSUE TITLE
Presto do not suuport select item as Integer?

### ISSUE THREAD

**Issue by ghfengg** [prestodb/presto#15567]
SQL demo :   select item_name as 2  from xxxx
Error Message:Query 20201229_100552_00002_7e7z6 failed: line 1:29: mismatched input '2'. Expecting: <identifier>

**Comment by kaikalur** [comment]
This should not be allowed. The error message is correct. You can quote the 2 and it should work.

**Comment by rongrong** [comment]
According to SQL spec, the format should be `AS <identifier>`. The number "2" is not a valid identifier. According to the spec
```
An <identifier start> is any character in the Unicode General Category classes “Lu”, “Ll”, “Lt”, “Lm”, “Lo”, or “Nl”.
NOTE 126 — The Unicode General Category classes “Lu”, “Ll”, “Lt”, “Lm”, “Lo”, and “Nl” are assigned to Unicode characters that are, respectively, upper-case letters, lower-case letters, title-case letters, modifier letters, other letters, and letter numbers.
```
