### ISSUE TITLE
Presto don't support select item’s alias Chinese? #6496

### ISSUE THREAD

**Issue by ghfengg** [prestodb/presto#15579]
version:0.244.1

![image](https://user-images.githubusercontent.com/3355129/103529764-36348b80-4ec1-11eb-8946-f42eb86e13a0.png)

**Comment by rongrong** [comment]
You have to quote the identifier if it has unicode characters. so use `AS "ERP_NAME从"` instead.

**Comment by ghfengg** [comment]
> You have to quote the identifier if it has unicode characters. so use `AS "ERP_NAME从"` instead.

thanks~

**Comment by ghfengg** [comment]
> You have to quote the identifier if it has unicode characters. so use `AS "ERP_NAME从"` instead.

by the way，how can i support alias names without quotes？cutom parser?
