### ISSUE TITLE
Druid connector fails to identify tables with uppercase names.

### ISSUE THREAD

**Issue by aniruddhasanyal** [prestodb/presto#15587]
When trying to query druid tables with uppercase names, the query fails with the error: Table 'TABLE_NAME' does not exist. A similar issue was observed in MySql connector and the attribute option "case-insensitive-name-matching" was added for MySql connector catalogue file. I have tried using the same attribute for Druid catalogue and it doesn't seem to be working.

**Comment by rschlussel** [comment]
@zhenxiao @beinan can you help?

**Comment by beinan** [comment]
We don't have case-insensitive-name-matching implemented in druid connection I think. 

Just did some research on the behavior of druid and mysql.

According to Druid-SQL's doc https://druid.apache.org/docs/latest/querying/sql.html
> All identifiers are case-sensitive and no implicit case conversions are performed.

For mysql, as described in https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html
>  names are not case-sensitive in Windows, but are case-sensitive in most varieties of Unix.
Mysql also has a system variable which can make mysql to compare by lower case for the table names

We can also check the discussion here #2863  

I think the case insensitive matching should be something nice to have.

Looks like we might need something like https://github.com/prestodb/presto/pull/13087 for druid connector,  I might make it once I got a chance.

**Comment by owinbin** [comment]
we have the same problem too, and the way we solved it like #13087 for druid connector

**Comment by beinan** [comment]
> we have the same problem too, and the way we solved it like #13087 for druid connector

Really appreciate if you could send a PR for the change on druid connector.

**Comment by imjalpreet** [comment]
@beinan in case no one is working on this change, I can work on it for solving this in druid connector.

**Comment by beinan** [comment]
@imjalpreet feel free to send a PR to us, I can help review.  many thanks!

**Comment by imjalpreet** [comment]
@beinan I got caught up in some other work due to which this got delayed. Late last week I have raised a PR for this, can you help review the same?
