### ISSUE TITLE
Warn about disjunction OR operator in a join condition

### ISSUE THREAD

**Issue by kaikalur** [prestodb/presto#15605]
OR in a join condition is just inviting trouble and can have severe performance problems. So we should warn on that.

SELECT ... T1 JOIN T2 ON (T1.a = T2.x OR T1.b = T2.y)

**Comment by TszKitLo40** [comment]
I am new here and want to try this issue. But are there any same logic for me to refer?

**Comment by kaikalur** [comment]
Sorry all, looks like this is was a dupe of  15538 (also created by me lol). So closing this one and the other one is take. Sorry about that!
