### ISSUE TITLE
Add T-Digest function documentation

### ISSUE THREAD

**Issue by tdcmeehan** [prestodb/presto#15674]
We need to add formal documentation for T-Digest, similar to Q-Digest.

* `TDIGEST_AGG`
* `MERGE(TDIGEST)`
* `VALUE_AT_QUANTILE(...)`
* `QUANTILE_AT_VALUE(...)`
* `SCALE_TDIGEST`
* ` DESTRUCTURE_TDIGEST`

**Comment by amellnik** [comment]
#16911 is now merged and the documentation should be available in the next release, I think this can be closed.
