### ISSUE TITLE
[Cassandra Connector] Reduce the number of splits when the presto cluster is small

### ISSUE THREAD

**Issue by xumingming** [prestodb/presto#15729]
We have a scenario where Presto cluster is only one 16Core machine, and the cassandra table contains only several records, but Presto will calculate 385 splits for this table(it calculate the splits according to the token range), so the query is very slow.

So can we provide a session property to let user reduce the split count so the performance for small presto cluster can be better?

**Comment by xumingming** [comment]
I have an optimization, for small cassandra table, I calculate the splits manually split the whole token ring: (-2 ^ 63 -> 2 ^ 63 - 1) to very small number of splits(e.g. 1), it optimize the performance from 1min to 1 second. Don't know if the community is interested in this optimization?

**Comment by rohanpednekar** [comment]
@xumingming, what is the total row count for this Cassandra table? How often you interact with small Cassandra tables?  How many queries per month or week? Also, do you see similar behavior with other connectors? 

Thanks!

**Comment by xumingming** [comment]
total row count is 40, the performance issue mainly related to how Presto's Cassandra Connector generating splits, so it has nothing to do with other connectors.
