### ISSUE TITLE
Cross catalog S3 access bug 

### ISSUE THREAD

**Issue by ashishtadose** [prestodb/presto#15722]
We come across a bug that causes Presto hive catalog configured with S3 to inherit S3 access from another hive catalog configured with S3 access. 

This is caused by cached FileSystem references in JVM, they are identified by the bucket https://github.com/prestodb/presto-hadoop-apache2/blob/d5237d5068d4528c51bad4fbe8eb7bea24e155c6/src/main/java/org/apache/hadoop/fs/PrestoFileSystemCache.java#L109

So in a scenario where  bucket1 which should be accessed by catalog1 (because of configured S3 access) and not suppose to be accessed by catalog2(because configured IAM doesn't have access to that bucket), this issue will allow catalog2 access to bucket1 due to cached FS object at the bucket level.

**Comment by imjalpreet** [comment]
I have reviewed the implementation and a fix can be added for s3 similar to the one that has been implemented for GCS. 

I can implement the same and raise a PR soon.

**Comment by imjalpreet** [comment]
I have raised the PR to fix this https://github.com/prestodb/presto-hadoop-apache2/pull/46

Once the new version of presto-hadoop-apache2 is released, I will raise a PR for presto to bump up the version for the same.
