### ISSUE TITLE
Main task for statistical functions in presto hackathon

### ISSUE THREAD

**Issue by leepface** [prestodb/presto#15798]
A few people are currently doing a hackathon focused on adding some more statistical functionality to presto. This is just a main tracking task, from which we'll reference the various PRs.

## Distributions

| Distribution Function | PR | Peer reviewed | Tests passing | Merged | 
|----------------------|----|---------------|---------------|---------|
| Binomial | (#15812) | @leepface  | Yes | Yes |
| Cauchy | (#15818) | @leepface  | Yes |  Yes |
| Chi-squared | (#15799) | @leepface  | Yes  | Yes  |
| Continuous uniform | (#15813) | @leepface  |  |   |
| Discrete uniform | (#15810)  | @leepface   |  |   |
| Exponential | (wip) |  |  |   |
| F | (#15811)  | @leepface  |  |   |
| Gamma | (#15806)  | @leepface  |  |   |
| Geometric | (#15807)  | @leepface  |  |   |
| HyperGeometric | (#15821) | @leepface   |  Yes |   |
| Pareto | (wip) |  |  |   |
| Poisson | (#15814) | @leepface  |  | Yes  |
| Logistic | (#15808)  |  |  |   |
| LogNormalDistribution | (wip) |  |  |   |
| Student's t | (#15809)  |  | Yes |   |
| Weibull | (#15820) | @leepface  |  | Yes  |

## Scalar functions

- [ ] linear_interpolate (#15829)

## Aggregation functions
- [ ] one-sample t-statistic (#15817)
- [ ] paired t-statistic (#15817)
- [ ] two-sample t-statistic and ANOVA (proposal: #16916)
- [ ] weighted mean (wip)
- [ ] winsorized and trimmed mean (wip)

**Comment by nickstanisha** [comment]
Can confirm tests are passing for linear_interpolate as well

**Comment by dowi** [comment]
Tests are passing for my 3 additions :
https://github.com/prestodb/presto/pull/15810
https://github.com/prestodb/presto/pull/15807
https://github.com/prestodb/presto/pull/15813
