### ISSUE TITLE
Improve error message on out of local memory

### ISSUE THREAD

**Issue by aweisberg** [prestodb/presto#15815]
There are two potential improvements. First include the fragment IDs of fragments that are running at the node running out of memory, and how much memory each fragment is using if feasible.

The delta terminology is confusing because it's really how much it is attempting to allocate. Maybe update that, but keep in mind we may be pattern matching on this in several places so do a pass to make sure it isn't depended on.

**Comment by ankh6** [comment]
Hi @aweisberg I'd like to make my first contribution here. However I am not sure where to implement these changes.
Can you drop the path to the relevant module(s) ?

**Comment by aweisberg** [comment]
Check out https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/ExceededMemoryLimitException.java and https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/memory/QueryContext.java for how we end up generally getting to creating these exceptions. That will spider out into information about the tasks that make up the query execution and the task is a proxy for the fragment id which you would see when you explain plan.

**Comment by ankh6** [comment]
Hey @aweisberg
I ran the ./mvnw clean insall before implementing my changes. One build failed (perso-docs) and errors have been detected across multiple files (ReservedIdentifiers, SqlParser, TypeCalculation and UnscaledDecimal128Artithmetic)
I thought that my local branch might need to be updated. After fetching latest changes from presto/master branch, I still have these errors. Do you have any idea on how I can resolve this issue ?

![Screenshot from 2021-04-03 17-47-27](https://user-images.githubusercontent.com/79543964/113483755-56b2b880-94a5-11eb-8b1d-aebb76a3cc37.png)
![Screenshot from 2021-04-03 17-48-16](https://user-images.githubusercontent.com/79543964/113483756-574b4f00-94a5-11eb-997a-63644efa097d.png)
![Screenshot from 2021-04-03 17-48-35](https://user-images.githubusercontent.com/79543964/113483757-57e3e580-94a5-11eb-8b94-d3b0e72516d8.png)

**Comment by aweisberg** [comment]
Getting IntelliJ to build correctly even with the correct settings is sometimes hit or miss. @v-jizhang @dcharbon  you both went through this recently and also had some trouble? What did you eventually find worked?

What I usually recommend is making sure that you have the project set to the correct language level and JDK (8), right click on the project and select maven -> reload project, and if that doesn't work delete the IML and load the project again.

**Comment by pvliborio** [comment]
Hi @aweisberg, can I work in this issue?

**Comment by v-jizhang** [comment]
> Getting IntelliJ to build correctly even with the correct settings is sometimes hit or miss. @v-jizhang @dcharbon you both went through this recently and also had some trouble? What did you eventually find worked?
> 
> What I usually recommend is making sure that you have the project set to the correct language level and JDK (8), right click on the project and select maven -> reload project, and if that doesn't work delete the IML and load the project again.

I don't see this issue in my environment.

**Comment by aweisberg** [comment]
@ankh6 @pvliborio  I think @ankh6 ran into issues with IntelliJ and moved on. I think this is available to pick up still.

**Comment by aweisberg** [comment]
@arhimondr  seems to be doing this https://github.com/prestodb/presto/pull/16297
