### ISSUE TITLE
Query Result Cache

### ISSUE THREAD

**Issue by xumingming** [prestodb/presto#15832]
We want to develop the query result cache feature, don't know if community is interested. We find that when people use Presto with BI software(Tableau, PowerBI etc), the SQL send to Presto is usually repeated, same query get executed again & again, if we have query result cache, the query latency can be reduced to very small especially when the underlying data source is a slow data source.

**Comment by shixuan-fan** [comment]
This is an interesting feature :)

Internally, we have a frontend engine that would handle query result cache roughly by keeping (query text cache -> result) mapping, and handles cache invalidation as well. But our internal usage is mostly on Hive so it is a matter of consulting metastore.

How do we plan to handle cache invalidation in the engine? I'm guessing we would need some sort of table version concept, and do this check after semantic analysis?

**Comment by xumingming** [comment]
@shixuan-fan 

* We will use hash of the plan rather than query text as the key of the cache, since the query text might change.
* Cache invalidation will be handled by a CacheInvalidationHandler which allows different implementation, the default implementation might be time based, use need to specify a time duration, the cache will be invalidated after that.
* For data source that has metadata to indicate whether data has changed we can have CacheInvalidationHandler to check the metadata, only when the underlying data changes, we will invalidate the cache.

**Comment by shixuan-fan** [comment]
I see, so this would be a step after optimizer. Makes sense, thanks for clarifying :)

**Comment by himanshpal** [comment]
@xumingming - where do you plan to store the final cached results, will be it on coordinator or external storage like S3 ?

**Comment by xumingming** [comment]
@himanshpal it will be configurable, external storage like S3 will be a good choice.

**Comment by discipleforteen** [comment]
is it OK now?
