### ISSUE TITLE
MaxCompute Connector

### ISSUE THREAD

**Issue by xumingming** [prestodb/presto#15854]
MaxCompute(https://www.alibabacloud.com/product/maxcompute?gclid=EAIaIQobChMI1-mFm_LC7wIVQf3jBx1x5Q4CEAAYASAAEgKxr_D_BwE) is large-scale data warehousing solution of Alibaba Cloud. We'd like to contribute MaxCompute Connector to the Community.

**Comment by v-jizhang** [comment]
@xumingming You are very welcome to submit a PR and I will find a review for you. Thank you.

**Comment by skypan** [comment]
@xumingming Hi, Can you tell me that MaxCompute Connector has contributed ?? Now we want to use it
