### ISSUE TITLE
java.lang.NoClassDefFoundError: org/spark_project/guava/base/Preconditions

### ISSUE THREAD

**Issue by joaolealgh** [prestodb/presto#15931]
Hello. I'm new and I'm trying to work with Presto and Apache Spark and i'm using a connector to a PostgreSQL database, however, when i try to execute a simple query, i get the error in the attached file. I've tried the query using only Presto and it worked. I'm not sure what's the problem. Any ideas? If you need any more info of what i'm doing i can attach it. Thank you.
[error.txt](https://github.com/prestodb/presto/files/6298216/error.txt)

**Comment by joaolealgh** [comment]
I solved it by using spark 2.4.7 and hadoop 2.6

**Comment by rguillome** [comment]
HI @joaolealgh ,

Encounter this issue too and It shouldn't really be corrected by moving to spark 2.4.7.

Because spark-core dependency is not packages with `presto-spark-package`. I will reopen an issue and try a PR to add a correction
