### ISSUE TITLE
Adding the Gamma distribution (gamma_cdf + inverse_gamma_cdf)

### ISSUE THREAD

**Issue by Masha-Iris** [prestodb/presto#15961]
Adding the Gamma distribution, which is central to many statistical procedures (https://en.wikipedia.org/wiki/Gamma_distribution).

PR: #15960

The PR follows the diff template of: https://github.com/prestodb/presto/pull/11981/files

Both the function signature (name, input output type and meaning), and the test plan, are available in the PR.

== RELEASE NOTES ==

General Changes

Add gamma_cdf() and inverse_gamma_cdf() functions.
(this is the same structure as was used in the beta_cdf: https://prestodb.io/docs/current/release/release-0.215.html?highlight=beta_cds)

Adding probability distribution to native Presto unblocks building statistical procedures on top of it, specifically, unblocks the ability to calculate p-values and confidence intervals of relates tests.

**Comment by talgalili** [comment]
Done.

**Comment by talgalili** [comment]
Could someone please close this issue?

**Comment by yzhang1991** [comment]
@talgalili thanks for the contribution!!
