### ISSUE TITLE
Fix parameter names in `normal_cdf`

### ISSUE THREAD

**Issue by talgalili** [prestodb/presto#15999]
In  the [docs](https://prestodb.io/docs/current/functions/math.html) it says:

```
normal_cdf(mean, sd, v) → double
```

But in the [code](https://github.com/prestodb/presto/blob/a34cf433047ce9a5206cc4b510ff35ca11e45ca9/presto-main/src/main/java/com/facebook/presto/operator/scalar/MathFunctions.java#L671) it has:
```
    public static double normalCdf(
            @SqlType(StandardTypes.DOUBLE) double mean,
            @SqlType(StandardTypes.DOUBLE) double standardDeviation,
            @SqlType(StandardTypes.DOUBLE) double value)
    {
```

So standardDeviation should be changed to sd. And value to v (or v to value in the docs). The v vs value thing also happens in the beta distribution.

**Comment by devadathprabhu** [comment]
@talgalili / @rohanpednekar : Could you please assign this to me if this is open yet?

**Comment by talgalili** [comment]
Thanks @devadathprabhu 
I've already created a PR to fix this (and other, similar, issues) here:
https://github.com/prestodb/presto/pull/16090

If you could review/merge - that would be great!

**Comment by rohanpednekar** [comment]
@rongrong, can you please invite @devadathprabhu and @talgalili to PrestoDB org, so that I can assign them as reviewers? Thanks!

**Comment by talgalili** [comment]
PR merged/ Issue resolved.
