### ISSUE TITLE
Does presto support the dml or ddl sql authorization management for various databases.

### ISSUE THREAD

**Issue by MagicDevilZhang** [prestodb/presto#16024]
Does  presto support the dml or ddl sql authorization management for various databases.
We want to grant different authorization, like ' CREATE  / DROP / SELECT / INSERT / DELETE ', on some tables to various presto users.

**Comment by agrawalreetika** [comment]
@MagicDevilZhang  If you are looking for authorization checks with Presto Hive Connector, these are the supported options - https://prestodb.io/docs/current/connector/hive-security.html
You can check file-based authorization if that's something match your requirement in this - https://prestodb.io/docs/current/connector/hive-security.html#file-based-authorization
