### ISSUE TITLE
show COLUMNS of mysql,There is no synchronization about comment

### ISSUE THREAD

**Issue by DawnWLBD** [prestodb/presto#16049]
show COLUMNS of mysql,There is no synchronization about comment

**Comment by rohanpednekar** [comment]
Hi @DawnWLBD, can you pls provide DDLs, Versions, and steps you used to repro this issue and output? Thanks!

**Comment by DawnWLBD** [comment]
@rohanpednekar  
1、SQL:  SHOW COLUMNS FROM mysql.e6da.da_service_function；
2、presto versions: 0.238;
issue:  I found that the comment field is always empty. In fact, MySQL is not empty

**Comment by agrawalreetika** [comment]
Currently, the comment column in JDBC based connector is set to Null, I can add support for the column comment in metadata for Mysql.
