### ISSUE TITLE
Presto version on UI shows invalid 'GIT.COMMIT'

### ISSUE THREAD

**Issue by chalmagr** [prestodb/presto#16088]
![image](https://user-images.githubusercontent.com/4968250/118059581-8089b580-b356-11eb-918c-fb6701aeaf6b.png)

This issue also affects version 0.252 - was ok on 0.247 (not sure any version in between).

Did a little bit of digging and the META-INF/MANIFEST.MF file in presto-main shows the invalid version (below 247 vs 252)

![image](https://user-images.githubusercontent.com/4968250/118059715-ce062280-b356-11eb-86c5-2c05b278dc5b.png)

![image](https://user-images.githubusercontent.com/4968250/118059736-d9f1e480-b356-11eb-8ff6-c5fe4400718d.png)

**Comment by beinan** [comment]
@ChunxuTang I also saw this one in Twitter's build, could you help to fix?

**Comment by ChunxuTang** [comment]
Sure, confirmed the error in Twitter's build. Investigating it.

**Comment by ChunxuTang** [comment]
@beinan I tested it in the latest Presto and noticed that the issue has been resolved. Maybe we could safely close this issue?

**Comment by beinan** [comment]
@chalmagr feel free to reopen this issue if you're still seeing this one in the latest presto versions.  Thanks a lot for reporting this to us!
