### ISSUE TITLE
Which is the latest stable version?

### ISSUE THREAD

**Issue by nandahkrishna** [prestodb/presto#16200]
Hello, thank you for your work on Presto.

We recently bumped Presto to `0.254` at the [Homebrew](https://brew.sh) package manager in https://github.com/Homebrew/homebrew-core/pull/78570. One of our maintainers noted that the latest version mentioned at https://prestodb.io/download.html is `0.253.1`.

After some digging around, I found that the `0.253.1` release process, which was done after `0.254`, caused some files in the website repository (`version.js` and a few others) to be overwritten, i.e., the latest version went from being `0.254` in https://github.com/prestodb/prestodb.github.io/commit/44f56ceb40c8e1eb334aaddf29d92ec253a0f7c2 to `0.253.1` in https://github.com/prestodb/prestodb.github.io/commit/3b112b326e32d4fcc73d7be1dcd611c3d0cb2361.

We just want to clarify whether the latest version is `0.254` or `0.253.1` so that we may distribute the correct stable version to our users.

Also, should we be checking the downloads page (https://prestodb.io/download.html) or Maven to know which the latest stable release is? Earlier, we noticed sometimes that the downloads page showed an older version than the latest one on Maven, and we stuck to using the one mentioned on the page. Knowing where to check could help us update our `presto` Formula in the right manner and as soon as a new version is out.

Thanks!

**Comment by rohanpednekar** [comment]
@aweisberg, Do you think you can confirm this? Thanks.

**Comment by aweisberg** [comment]
This is a bug or lack of definition in the release process. When we are doing a hotfix release it's overwriting the new release on the web site. Why we ended up doing that I am not sure.

**Comment by aweisberg** [comment]
To clarify the highest version number is in Maven is the latest one. You can use Maven for that as it won't make the same mistakes as our web site publishing automation.

**Comment by nandahkrishna** [comment]
Thank you for clarifying! I'll update our version-checking logic to reflect this. Please feel free to close this issue.

**Comment by rohanpednekar** [comment]
Thanks @aweisberg and @samford for your help!
