### ISSUE TITLE
Report per-query bytes read from cache

### ISSUE THREAD

**Issue by highker** [prestodb/presto#16237]
One possible way is to leverage `HiveFileContext` to have a counter inside. The granularity could be even at per `read` call level. The per query or task-level tracking could be done at a higher level. This requires some tunneling from Alluxio. @apc999, do you think this is something doable in Alluxio to report the counters per read?

cc: @varungajjala, @yuanzhanhku

**Comment by yuanzhanhku** [comment]
I got some pointers from James. Presto is using AtomicLong as the counters. For example, here are some Operator level counters:
https://github.com/prestodb/presto/blob/01ba1dc71585f4aa9504fbaaff06ef7632a54cb2/presto-main/src/main/java/com/facebook/presto/operator/OperatorContext.java#L91

@apc999 Do you think it is fine to use AtomicLong as the counter and add it to the HiveFileContext?

**Comment by highker** [comment]
available now in runtime stats
