### ISSUE TITLE
presto-oracle connetor error !  I couldn't help it;

### ISSUE THREAD

**Issue by hzwcome** [prestodb/presto#16240]
If I follow the official line
`connector.name=oracle
connection-url=jdbc:oracle:thin:@10.xx.7.xx:1521/sid
connection-user=xx
connection-password=xx
`
`presto:xx> select * from oracle.xx.table;`
Will produce an error ：Query 20210610_073101_00001_45yuv failed: ORA-01017: invalid username/password; logon denied

I tried this method：https://github.com/prestodb/presto/issues/15232

If i change my jdbc uri to this format:
`jdbc:oracle:thin:user/password@//<host>[:<port>]/<service>`
`connection-url=jdbc:oracle:thin:user/xx@//10.xx.7.xx:1521/sid`
Will produce an error ：Query 20210610_072255_00001_bu6ir failed: Specifies an invalid Oracle URL
help me，plz！

**Comment by hzwcome** [comment]
my version is presto-0.254

**Comment by gfleg77** [comment]
The correct syntax for SID is:
connection-url=jdbc:oracle:thin:user/xx@10.xx.7.xx:1521:sid

**Comment by JtvDeemo** [comment]
I met the same issue. I tried both jdbc:oracle:thin:@host:1521:ORCL and jdbc:oracle:thin:@//host:1521/ORCL, but it remains the same ERROR: Query failed: ORA-01017: invalid username/password; logon denied.

**Comment by gfleg77** [comment]
> I met the same issue. I tried both jdbc:oracle:thin:@host:1521:ORCL and jdbc:oracle:thin:@//host:1521/ORCL, but it remains the same ERROR: Query failed: ORA-01017: invalid username/password; logon denied.

after "thin:" username and password  is missing from your connection string

**Comment by JtvDeemo** [comment]
> > I met the same issue. I tried both jdbc:oracle:thin:@host:1521:ORCL and jdbc:oracle:thin:@//host:1521/ORCL, but it remains the same ERROR: Query failed: ORA-01017: invalid username/password; logon denied.
> 
> after "thin:" username and password is missing from your connection string jdbc:oracle:thin:username/password@10.xx.7.xx:1521:sid

appreciate. I thought they are optional.

**Comment by hzwcome** [comment]
> @hzwcome The correct syntax for SID is: connection-url=jdbc:oracle:thin:user/[xx@10.xx.7.xx](mailto:xx@10.xx.7.xx):1521:sid

appreciate. I try it recenty and it works.
another Note: If your username or password contains special characters, wrap them in " "
