### ISSUE TITLE
Add ORC support for iceberg connector 

### ISSUE THREAD

**Issue by junyi1313** [prestodb/presto#16305]
For now, the iceberg connector only supports PARQUET file format. 

@ChunxuTang @beinan @zhenxiao do we have any plan or roadmap about this? 

We have already cherry-picked ORC support from Trino to presto-0.242.1 version and run for several months in our clusters.
I can open a PR to merge this feature to our presto iceberg connector as soon as possible.

Thanks.

**Comment by ChunxuTang** [comment]
@junyi1313 
That's very nice! Feel free to send a PR with this feature. I'll be very glad to help with the code review.

**Comment by junyi1313** [comment]
@ChunxuTang Thanks for your reply. I will send a PR very soon.
