### ISSUE TITLE
For SELECT from MV, do not validate the original SELECT query shape

### ISSUE THREAD

**Issue by gggrace14** [prestodb/presto#16330]
Right now, during SELECT from MV, we validate the original SELECT query shape in processMaterializedView(), which is not correct. What we should validate is the query shape of MV definition sql. We don't have restriction on the SELECT query against MV.
Current code: https://github.com/prestodb/presto/blob/cf2011ef6744fbba3325e02b6cc46cd15e644664/presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java#L1329

An example SELECT query against MV that fails validation: 20210624_071300_95326_i22mv.

**Comment by jainxrohit** [comment]
Fixed in the https://github.com/prestodb/presto/pull/16344
