### ISSUE TITLE
How to execute one query in multiple data source?

### ISSUE THREAD

**Issue by QianChenglong** [prestodb/presto#16360]
Same table in multiple MySQL database, how to execute one query in multiple database？

**Comment by xumingming** [comment]
Don't think it is in the problem domain that Presto solves.

**Comment by pratyakshsharma** [comment]
If you want to run the query at the same time from all the different tables, that is not possible. Presto can help you join different tables across data sources or databases. Can you clarify what you are looking for @QianChenglong
