### ISSUE TITLE
Parquet Dereference Pushdown issue

### ISSUE THREAD

**Issue by chliang71** [prestodb/presto#16364]
We encountered an issue on Presto 0.247 version, that the query returned incorrect when using **hive.parquet_dereference_pushdown_enabled**, we were also enabling **hive.parquet_use_column_names** all the time, which seems potentially related as well.

With some debugging seems that there are a couple places where column names were not handled properly. Specifically, I found two places below where it expects to match column name, e.g. msg, while it is using a different id e.g. msg_12, causing it to not match, and thus not finding the pushdown column at all. Both seem related **pushedDownSubfield.getRootName()**

[Here](https://github.com/prestodb/presto/blob/release-0.247/presto-hive/src/main/java/com/facebook/presto/hive/parquet/ParquetPageSourceFactory.java#L285): here pushedDownSubfield.getRootName() gots a 'msg_12', resulting columnIO = null, if using 'msg' it returned a column.

[Here](https://github.com/prestodb/presto/blob/release-0.247/presto-parquet/src/main/java/com/facebook/presto/parquet/ParquetTypeUtils.java#L277 ): here rootName was a 'msg_12', resulting in parentType = null, if using 'msg', it would find the parent type. This one is also from pushedDownSubfield.getRootName().

I did some hacky "fix" and my query seemed returning expected results, but can't say these are the only places that need to change. Still need to come up with a more proper fix. Seems to me Subfield kept the column name post annotating the id, which makes it not match original schema column name. I also tried disabling hive.parquet_use_column_names, but straight run into another error, seems a separate issue though.

@vkorukanti @zhenxiao ,would be great to have your thoughts here.

**Comment by vkorukanti** [comment]
@chliang71 I have seen in some cases columns get aliases with added suffixes like `_12` during the plan rewrite and in few other cases. If possible debug the place where we are creating the `Subfield` with `msg_12`. It is possible we are not referring to the underlying column and instead referring to the alias. Can you check if [this](https://github.com/prestodb/presto/pull/15469) patch is present in your fork? It fixed a similar issue, but not sure which release it went in.

**Comment by zhenxiao** [comment]
nice bring this up, @chliang71 
as @vkorukanti mentioned, I think we could take a look at `PushDownDereferences` which adds dereference pushdown, and generates `subfield` and `aliases`
nice if we could have both `parquet_use_column_names` and `parquet_dereference_pushdown_enabled` enabled

**Comment by chliang71** [comment]
Thanks @vkorukanti @zhenxiao !

I do see [this patch](https://github.com/prestodb/presto/pull/15469) in our branch and [in release-247 branch](https://github.com/prestodb/presto/blob/release-0.247/presto-hive/src/main/java/com/facebook/presto/hive/rule/HiveParquetDereferencePushDown.java#L341). I checked the create path of `Subfield`, it is from a Bean databind path, not created by pushdown code, so I assume the values are correct. Similarly, `aliases` names are generated by `PlanVariableAllocator` and directly passed down from planner logic, not generated by pushdown logic.

So far, I haven't yet seen signs of the variable values being wrong i.e. having `msg_12` here is probably correct. Now I'm more inclined to think that it is `msg_12` got misused. In the two places I mentioned, both seem to compare against original column names in schema. So looks to me `msg_12` is probably supposed to be just a **variable** in the plan, but these two places treat it is an actual **column name**.  Any thoughts?

**Comment by chliang71** [comment]
Another finding to mention is that, I did some comparing against previous 230 branch (which works fine), I saw the variable are indeed a bit different actually:
 in 247: `msg_12$_$_$env:string:-1:SYNTHESIZED:[msg_12.env]`
 in 230: `msg$_$_$env:string:12:REGULAR`
I know that in [this](https://github.com/prestodb/presto/commit/99c0d2a123f31586afd7f349633e98dcc123b2b4) commit, seems we changed to use SYNTHESIZED to represent pushdown fields, so the SYNTHESIZED vs REGULAR difference is expected, but the naming of `msg$_$_$env` vs `msg_12$_$_$env` likely makes a difference I think, will continue into where it diverged.

**Comment by vkorukanti** [comment]
>  I checked the create path of `Subfield`, it is from a Bean databind path, not created by pushdown code, so I assume the values are correct. Similarly, `aliases` names are generated by `PlanVariableAllocator` and directly passed down from planner logic, not generated by pushdown logic.

Probably you checked the place where the SplitInfo is deserizlied on the worker side (it is deserialized using JSON). Check the place in planner where `Subfield` with name `msg_12` is created (may be put a conditional breakpoint in Subfield constructor)

**Comment by chliang71** [comment]
Thanks @vkorukanti , good catch on the Subfield part! 

Looks like [this](https://github.com/prestodb/presto/blob/release-0.247/presto-hive/src/main/java/com/facebook/presto/hive/rule/HiveParquetDereferencePushDown.java#L141) is where `Subfield` was created in pushdown code path. But here `rowExpression` already has name = `msg_12`, also, for the problematic query, it has a join with another table on `msg`, and there is another variable expression `msg`, I wonder if it is correct to expect both of them to be `msg` in this case anyway.

**Comment by chliang71** [comment]
@vkorukanti @zhenxiao after some more debugging, I found making [this change](https://github.com/chliang71/presto/commit/9d5577369b287264bcbebcbef52629024adccbac) seemed to fix the query. Still need to run more testing, but would appreciate some early feedback to see if this is right direction. Thanks!!

Two main things in the change:
1. keeping the changes from [this patch](https://github.com/prestodb/presto/pull/15469) as well as what it removed, i.e. regularHiveColumnHandles comes from two sources, this way it keeps both `msg` and `msg_12`, mapping to same column handle.
2. when creating `Subfield`, use the value from regularHiveColumnHandles map. e.g. here key is `msg_12`, value seems the original columnHandle, so instead of using `msg_12`, use the name of the columnHandle

**Comment by vkorukanti** [comment]
@chliang71 The change makes sense. Thanks for fixing it!

**Comment by zhenxiao** [comment]
looks good. @chliang71 how about submit a PR?

**Comment by chliang71** [comment]
Thanks! Filed [PR](https://github.com/prestodb/presto/pull/16377 )
