### ISSUE TITLE
Add base table to materialized views mapping information in metastore

### ISSUE THREAD

**Issue by jzzhaofb** [prestodb/presto#16430]
Currently there exists no method in metastore that can be used to extract the mapping information of a base table to its corresponding materialized views. This function should be added to Metastore:

```
public Map<QualifiedObjectName, List<QualifiedObjectName>> getBaseTableToMaterializedViews()
{
        // Implementation
}
```

**Comment by jainxrohit** [comment]
@jzzhaofb can you fix the title and description

Get base to materialized view mapping from metastore

**Comment by jainxrohit** [comment]
Issue with description is: https://github.com/prestodb/presto/issues/16438
