### ISSUE TITLE
Druid connector issue

### ISSUE THREAD

**Issue by bjwanghua** [prestodb/presto#16495]
When I use Druid connector, the results are null. 
I found that in com.facebook.presto.druid.DruidBrokerPageSource, line 132, the get function of ArrayNode always returns null. Is this an issue of Druid connector?
![image](https://user-images.githubusercontent.com/39390022/126984638-b6793e73-47b1-4288-8c2d-441bdce782df.png)

![image](https://user-images.githubusercontent.com/39390022/126984610-ffef7cfc-23b1-49f1-b78b-b1002424ded2.png)

**Comment by rohanpednekar** [comment]
Hi @adamjshook, Do you think you can help us here?
