### ISSUE TITLE
Google sheets connector

### ISSUE THREAD

**Issue by rohanpednekar** [prestodb/presto#16516]
cc @chliang71

**Comment by chliang71** [comment]
Started PR https://github.com/prestodb/presto/issues/16516.

**Comment by chliang71** [comment]
@rohanpednekar @puneetjaiswal @zhenxiao @vkorukanti mind taking a look on the PR? Thanks!

**Comment by fabform** [comment]
Handy to [find google sheet id](https://fabform.io/a/how-to-find-google-sheet-id)

**Comment by dnskr** [comment]
The connector has been added but the doc page is not visible in [0.273.3 documentation](https://prestodb.io/docs/0.273.3/connector.html)
Is it possible to check why?

**Comment by backkem** [comment]
It seems the documentation was accidently removed here: https://github.com/prestodb/presto/commit/8319b30616d084383d6cdcc8f86de758b2e2c740

**Comment by agrawalreetika** [comment]
Thank you for bringing this up, corrected it here https://github.com/prestodb/presto/pull/20985

**Comment by agrawalreetika** [comment]
Since the Google Sheets connector has already been added to Presto, I will close this.
