### ISSUE TITLE
Materialized view should read only from base tables if too many partitions

### ISSUE THREAD

**Issue by jainxrohit** [prestodb/presto#16579]
In case too many partitions are not materialized, materialized view query should only read from base tables.
This is required to avoid building a very long query.

At the moment it check if materialized view not materialized. Here is the check
presto/presto-hive/src/main/java/com/facebook/presto/hive/HiveMetadata.java

Line 2321 in 2eeaf68

 if (materializedDataPredicates.getPredicateDisjuncts().isEmpty()) { 
Extend this to check if too many predicates are not materialized. If the size of predicates are greater than threshold, then return a new state.

Create a new state in the MaterializedViewStatus as MANY_NOT_MATERIALIZED (We can discuss the proper names with other as well).

Create a new configuration and session property in the HiveSessionProperties and HiveClientConfig to define the threshold.

Then in the statementAnalyzer:
https://github.com/prestodb/presto/blob/2eeaf68ed36768adb504617b0e41a30253a94b4a/presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java#L1354

Check if materialized view status is new state, return the materializedViewCreateSql in that case.

Create the test case in the TestHiveLogicalPlanner for this case.

**Comment by jainxrohit** [comment]
At the moment it check if materialized view not materialized. Here is the check
https://github.com/prestodb/presto/blob/2eeaf68ed36768adb504617b0e41a30253a94b4a/presto-hive/src/main/java/com/facebook/presto/hive/HiveMetadata.java#L2321

Extend this to check if too many predicates are not materialized. If the size of predicates are greater than threshold, then return a new state.

Create a new state in the MaterializedViewStatus as MANY_NOT_MATERIALIZED (We can discuss the proper names with other as well).

Create a new configuration and session property in the HiveSessionProperties and HiveClientConfig to define the threshold.

**Comment by jainxrohit** [comment]
cc: @highker @zacw7

**Comment by shrinidhijoshi** [comment]
Closing as PR is merged
