### ISSUE TITLE
The iceberg overlay table in hive can't be queried via presto.

### ISSUE THREAD

**Issue by TangYan-1** [prestodb/presto#16575]
I have tried to query iceberg tables with hiveCatalog, and it works well. I'm now trying to use iceberg with hadoop catalog and query from presto. I created a iceberg table using spark job, and create an overlay in hive. When I use presto/trino to query that table, it show the below error. 
1. 
spark3-shell --jars iceberg-spark3-runtime-0.11.1.jar
--conf spark.sql.catalog.hadoop_catalog=org.apache.iceberg.spark.SparkCatalog
--conf spark.sql.catalog.hadoop_catalog.type=hadoop
--conf spark.sql.catalog.hadoop_catalog.warehouse=/iceberg/warehouse
> spark.sql("CREATE TABLE hadoop_catalog.testdb.iceberg_table_in_hdfs (report string ,reporttime string,reporttype string, reportid string , reportversion bigint, day string ) USING iceberg PARTITIONED BY (day)")
2. beeline> CREATE EXTERNAL TABLE testdb.iceberg_table_in_hdfs (report string ,reporttime string,reporttype string, reportid string , reportversion bigint, day string )
STORED BY 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler'
LOCATION '/iceberg/warehouse/testdb/iceberg_table_in_hdfs'
TBLPROPERTIES (
'iceberg.mr.catalog'='hadoop',
'iceberg.mr.catalog.hadoop.warehouse.location'='/iceberg/warehouse');
3. presto:testdb> select * from iceberg_table_in_hdfs;
Query 20210805_085251_00012_vs7zn failed: Table is missing [metadata_location] property: testdb.iceberg_table_in_hdfs
io.prestosql.spi.PrestoException: Table is missing [metadata_location] property: testdb.iceberg_table_in_hdfs
at io.prestosql.plugin.iceberg.HiveTableOperations.refresh(HiveTableOperations.java:151)

**Comment by rohanpednekar** [comment]
Hey @TangYan-1 can you please try your use case with actual [Presto](https://prestodb.io/docs/current/installation.html) 
with Iceberg Connector https://prestodb.io/docs/current/connector/iceberg.html You may not face this issue. 
Please let us know the outcome.

**Comment by bitsondatadev** [comment]
Hey @TangYan-1 you're actually using Trino. Which is maintained on the [Trino github](https://github.com/trinodb/trino).

Moving to Presto likely won't solve the issue as it [is cherry-picked (or copied) from Trino](https://github.com/prestodb/presto/commit/f738ed3bed0ce290d3bc61e540b0a2cf89b527a1#diff-82c9d248342a9099b14f64a3be938f056c14e530159e24daec3d86c2067a8411). 

Currently the Hadoop Catalogs aren't being supported in Iceberg but you can follow [the fix here](https://github.com/trinodb/trino/pull/8444). 

Reach out to me if you have any questions!
