### ISSUE TITLE
Execute Presto's Remote Function in Alibaba Function Compute

### ISSUE THREAD

**Issue by xumingming** [prestodb/presto#16584]
Alibaba Function Compute is a `Function as a Service` service, user can execute functions on demand. Presto's Remote Function is another interesting feature that make users to put the UDF executables out of Presto itself. We are exploring to  support users to put UDF in Function Compute and then invoke it from Presto, how does it sounds like? We'd like to contribute to the community if community think it is valuable.

**Comment by tdcmeehan** [comment]
CC: @rongrong
