### ISSUE TITLE
Proposal: Support Hive Function In Presto

### ISSUE THREAD

**Issue by yulongfufu** [prestodb/presto#16592]
### Background :
Nowdays, most companies will use both Hive/Spark and Presto together. But Presto built-in functions have very different syntax and internal mechanism compared with Hive functions. This restricts presto usage and users need to maintain 2 forms of functions.  In this proposal, we present a method to execute Hive UDF/UDAF in Presto internal.
### 
### Some examples :
There are two kinds of hive function :
  - Hive built-in function : Exists inside the Presto and depends on the Hive JAR.
  - User-defined function : Exists in external storage, such as HDFS.
### 
Not only does this Feature enable Presto to support built-in Hive functions, we can also load the  user-defined Hive functions at run time (as long as you store the function information in your Hive Metastore). There are two modes of using HIVE UDF. 
  - Manual mode: You can explicitly specify the three-stage function name like  hive.default.functionName to call the HIVE function. 
Example : 
select hive.default.substr('facebook', 1);                                  Hive#substr
select substr('facebook', 1);                                                       Presto#substr
select hive.default.avg(customer_id) from table;                     Hive#substr
select avg(customer_id);                                                             Presto#substr
  - Auto mode:  You can only use the function name and Presto will search the appropriate function for you (If there are functions with the same name, Presto built-in function will be returned first. Certainly, you can use the Hive function by adding a blacklist in this case)
Example : 
select substr('facebook', 1);                                                        Presto#substr
select get_json_object('{"a", "b"}', '$.a');                                   Hive#get_json_object
select avg(customer_id) from table;                                           Presto#substr
select your_hive_aggregate_function(customer_id) from table;     Hive#your_hive_aggregate_function
### Framework:
- Overview : After submitting SQL, Presto will resolve the function by its name. If the Function is not a Presto built-in Function, Presto will search in Hive Metastore  at run time, then load and cache the hive function resources from remote(e.g. HDFS). After loading, Presto will convert the input type to Hive type and create the Function instance, then bridge the instance as  'Presto Type' to Hive function. At last the real execution of Hive Function will be called through reflection.
- Flow chart : 
![image](https://user-images.githubusercontent.com/86234715/129032858-5d20ec5f-dbad-42da-93e7-69c7b8e88e65.png)

### 
Look design doc for more details:  https://bytedance.feishu.cn/docs/doccnA5uuqTrBFIc1SiwrahulGh#
Reference #16478

**Comment by pratyakshsharma** [comment]
Closing as the support is available now.
