### ISSUE TITLE
Add ability to convert varbinary to varchar

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#1664]
We need a way to convert bytes to characters. This should support UTF-8 and ideally all other encodings (basically anything Java supports). Additionally, there are multiple ways to deal with invalid data, all of which should be available:
- raise an error
- return `null`
- ignore invalid bytes
- replace the character with
  - the Unicode "REPLACEMENT CHARACTER": http://www.fileformat.info/info/unicode/char/0fffd/index.htm
  - a user specified replacement character (or string)

**Comment by cberner** [comment]
Looks like we have `from_utf8` now. Shall we close this?
