### ISSUE TITLE
Issue running Presto in local

### ISSUE THREAD

**Issue by xiaolong** [prestodb/presto#16681]
After `git clone` and successfully building it (screenshot 1 below), when I try to run the server within IntelliJ, I ran into error `Error: Could not find or load main class com.facebook.presto.server.PrestoServer` (screenshot 2 below).  Anybody having a similar issue?  Thanks for your help in advance!

![image](https://user-images.githubusercontent.com/871574/131937636-0a698c0f-8ec5-40fc-b03a-d34255bf9f91.png)

![image](https://user-images.githubusercontent.com/871574/131938108-4161a082-c662-4786-a70e-7a4f46e775ad.png)

**Comment by nmahadevuni** [comment]
The classpath of module should be presto-main, not presto. Please change it and try again. For any such issues, please join slack at prestodb.slack.com by using instructions at https://prestodb.io/community.html and ask in channels there.
