### ISSUE TITLE
Quick Question Regarding Resource Group Configs

### ISSUE THREAD

**Issue by michael-romero** [prestodb/presto#16744]
aws emr-6.1.0
Presto 0.232

The presto docs mention:
> The resource groups and associated selection rules are configured by a manager which is pluggable. Add an etc/resource-groups.properties file with the following contents to enable the built-in manager that reads a JSON config file

I've been struggling finding where to place this `etc/resource-groups.properties` file, as it's quite vague. I created an `etc/` in the root presto folder `/etc/presto`, and also tried placing it in `etc/presto` itself. I eventually found an old presto slack message detailing `/var/lib/presto/data/etc/`, and when it's placed there, immediately works.

Is there any documentation or note that mentioned this directory?

Edit: Is `/var/lib/presto/data/etc` the normal directory presto uses in a default installation, while aws EMR has opted to use `/etc/presto` instead? Is this debacle caused by an EMR preference?

**Comment by imjalpreet** [comment]
@michael-romero By default the etc directory is located at `PRESTO_INSTALLATION_PATH/etc` and all the configuration files are located inside etc. It depends on EMR what they have set etc directory or where they have installed presto if they are using default location for etc directory. Based on your observation it is `/var/lib/presto/data/etc`. Most probably they would have modified from the default location.

**Comment by imjalpreet** [comment]
Presto documentation mentions creating the etc directory inside the installation directory since that is the expected default location: https://prestodb.io/docs/current/installation/deployment.html#configuring-presto

**Comment by michael-romero** [comment]
> @michael-romero By default the etc directory is located at `PRESTO_INSTALLATION_PATH/etc` and all the configuration files are located inside etc. It depends on EMR what they have set etc directory or where they have installed presto if they are using default location for etc directory. Based on your observation it is `/var/lib/presto/data/etc`. Most probably they would have modified from the default location.

Just a reference for future parties, I don't think the default is `/var/lib/presto/data/etc`, rather `etc/presto`!
