### ISSUE TITLE
I need to use Presto to access a database developed by our company. What should I do?  

### ISSUE THREAD

**Issue by liuyiyo** [prestodb/presto#16752]
I need to use Presto to access a database developed by our company. What should I do?

**Comment by fgwang7w** [comment]
hi @liuyiyo you may use presto built-in [connectors](https://prestodb.io/docs/current/connector.html) to access the data source that your company database beyongs to.

**Comment by pratyakshsharma** [comment]
@liuyiyo Hopefully you were able to use one of Presto's built-in connectors for your use case. Please feel free to reopen the issue if you have any more doubts.
