### ISSUE TITLE
Invalid cast to TDigest or QDigest should be caught by TRY

### ISSUE THREAD

**Issue by amellnik** [prestodb/presto#16913]
The [docs](https://prestodb.io/docs/current/functions/conditional.html#try) say that this should work for conversion errors, but attempting to cast an invalid VARBINARY or an invalid type like an integer to a TDigest fails even if it is wrapped in a TRY.  The same thing also happens for QDigest.

Things which currently don't work (throw an exception instead of returning null):

```
SELECT try(CAST(1 AS TDigest(DOUBLE)));
SELECT TRY_CAST(1 AS TDigest(DOUBLE));
```

**Comment by rongrong** [comment]
The doc is ambiguous. It can be read as "invalid cast or invalid function argument", or "invalid cast argument or invalid function argument". It supposed to mean the later. Updating the documentation to clarify the ambiguity. Thanks for opening the issue!
