### ISSUE TITLE
ORACLE connection issue: ORA-01017 Invalid Username/Password; Logon Denied

### ISSUE THREAD

**Issue by rahmanmd007** [prestodb/presto#17036]
Hi,
I am using Presto 0.265.1. While I am able to connect to other data sources without an issue, I am getting error connecting to Oracle.
I am using the following as advised by the documentation:
connector.name=oracle
connection-url=jdbc:oracle:thin:@<my_oracle_host_name>:<port_no>/<service_name>
connection-user=root
connection-password=secret

I have validate the credentials and other parameters and they are perfectly fine and I was able to log on using DBeaver SQL client. 

Is this a known issue? 
Do we have any workaround?
Please help.
Thank you in advance.

**Comment by rahmanmd007** [comment]
The following worked:
connector.name=oracle
connection-url=jdbc:oracle:thin:<user_name>/<pass>@//<host>:<port>/<service_name>

I hope it helps someone.

**Comment by jameskim0987** [comment]
The docs here helped me. http://www.orafaq.com/wiki/JDBC


`jdbc:oracle:thin:[<user>/<password>]@//<host>[:<port>]/<service>`
