### ISSUE TITLE
Schema Access Control

### ISSUE THREAD

**Issue by bing-h** [prestodb/presto#17066]
I use presto to query s3 data and create hive catalog, schemas and tables, I also want to control access schemas, I follow the presto docs "File Based System Access Control" ,use json file to describe schema relation with user, then I query with presto-cli `./presto --server ip:8889 --catalog hive  --user test`
but I got the error

```
presto:test_schema> show tables;
Query 20211203_124007_00036_t38aj failed: Access Denied: Cannot access catalog hive
```
"access-control.properties" file :
```
access-control.name=file
security.config-file=/usr/lib/presto/etc/rules.json
security.refresh-period=10s
```
'rules.json' file:
```
{
	"catalogs": [{
			"user": "admin",
			"catalog": "(hive|system)",
			"allow": "all"
		},
		{
			"catalog": "system",
			"allow": "none"
		}
	],
	"schemas": [{
		"schema": "hive.test_schema",
		"user": "test",
		"owner": true
	}]

}
```
What I should do to accomplish schema access control？

**Comment by agrawalreetika** [comment]
Hi @bing-h, 
If I understand correctly, you want test user to access test_schema under hive catalog and disable system catalog access to all except admin user.
Could you please try below JSON if this works fine: 
`{
	"catalogs": [
        {
			"user": "admin",
			"catalog": "system",
			"allow": "all"
		},
        {
            "catalog": "hive",
            "allow": "all"
        },
		{
			"catalog": "system",
			"allow": "none"
		}
	],
	"schemas": [
        {
		    "schema": "test_schema",
		    "user": "test",
		    "owner": true
	    }
    ]
}`

**Comment by bing-h** [comment]
> 
File Based Control Config with Schema can only control create,delete or alter schema operation according to Presto Docs

**Comment by agrawalreetika** [comment]
If you want to try out Ranger based authorization for Presto hive connector, you can look at this open PR #16999

**Comment by pratyakshsharma** [comment]
@bing-h Looks like your query was resolved. Please feel free to reopen or raise a new issue in case you have more questions.
