### ISSUE TITLE
Access Denied: Cannot create table test.t1 

### ISSUE THREAD

**Issue by gwnszbd** [prestodb/presto#17179]
hive2.properties:
hive.security=file
security.config-file=/opt/presto/presto-server-0.245/etc/hive-security.json
...

hive-security.json:
{
  "tables": [{
    "user": "abc",
    "schema": "test",
    "privileges": ["SELECT", "INSERT", "DELETE", "OWNERSHIP", "GRANT_SELECT"]
  },{
    "privileges": ["SELECT"]
  }],
  "sessionProperties": [{
    "allow": false
  }]
}

My requirement is that all users only have the select permission, and abc user have the table creation permission of the test database.When I use abc user to create a table, an error occurs :  "Access Denied: Cannot create table test.t1 ".
"create table test.t1 (id int)" or "create table test.t1 as select 1" the same error.
How should I set the create table permission?

**Comment by agrawalreetika** [comment]
@gwnszbd Could you please define the schema section in your hive-security.json and retry,
`
"schemas": [
    {
      "user": "abc",
      "schema": "test",
      "owner": true
    }
]
`

Ref : https://prestodb.io/docs/current/connector/hive-security.html#file-based-authorization

**Comment by gwnszbd** [comment]
> @gwnszbd Could you please define the schema section in your hive-security.json and retry, `"schemas": [ { "user": "abc", "schema": "test", "owner": true } ]`
> 
> Ref : https://prestodb.io/docs/current/connector/hive-security.html#file-based-authorization

3Q, that is right,It's working.
