### ISSUE TITLE
Query order is not respected during execution all the time

### ISSUE THREAD

**Issue by swapsmagic** [prestodb/presto#17302]
The query order to enter the cluster is not respected all the time due to the nature of multi threading with Dispatcher logic.
There are times when the first query submitted might end up getting queued and the second one runs if they are submitted almost same time with few milliseconds delay. And the reason for that happening is: If the thread handling the second query gets priority first.
And because of this nature, our existing test fails sometimes: [TestQueuedDb:testTwoQueriesAtSameTime](https://github.com/prestodb/presto/blob/49ae2871736f1c783860596768652755e8159ebd/presto-tests/src/test/java/com/facebook/presto/execution/resourceGroups/db/TestQueuesDb.java#L151)

**Comment by mbasmanova** [comment]
I also noticed that TestDistributedQueryResource.testGetAllQueryInfoForLimits is flaky and fails with timeout.

```
org.testng.internal.thread.ThreadTimeoutException: Method com.facebook.presto.resourcemanager.TestDistributedQueryResource.testGetAllQueryInfoForLimits() didn't finish within the time-out 60000
```

I'm disabling this test in https://github.com/prestodb/presto/pull/17400
