### ISSUE TITLE
Query details can't be render when the errorCode of the query is SYNTAX_ERROR

### ISSUE THREAD

**Issue by twoyang0917** [prestodb/presto#17322]
Query details can't be render correctly as you can see from below snapshot. Only impact those query failed due to SYNTAX_ERROR. My version is 0.269, no tested for the others.
![image](https://user-images.githubusercontent.com/3362750/154635316-0ad10b4f-1ebb-4908-b11f-ca5d9992b92b.png)

![image](https://user-images.githubusercontent.com/3362750/154635718-1f2cf6d0-a68f-483f-a48d-28e5a69f271a.png)

I think it's a bug. the reason is the query not be executed so there is no runtimeStats in queryStats. So below code will throw exception.

`if (Object.values(query.queryStats.runtimeStats).length == 0) return null;`
https://github.com/prestodb/presto/blob/master/presto-main/src/main/resources/webapp/src/components/QueryDetail.jsx

```
curl -X GET http://localhost:/v1/query/20220218_062434_00011_vpuq2 | jq .queryStats
{
  "createTime": "2022-02-18T06:24:34.377Z",
  "endTime": "2022-02-18T06:24:34.439Z",
  "waitingForPrerequisitesTime": "814.24us",
  "queuedTime": "62.83us",
  "elapsedTime": "62.05ms",
  "executionTime": "0.00ns",
  "runningTasks": 0,
  "totalDrivers": 0,
  "queuedDrivers": 0,
  "runningDrivers": 0,
  "completedDrivers": 0,
  "rawInputDataSize": "0B",
  "rawInputPositions": 0,
  "cumulativeUserMemory": 0,
  "cumulativeTotalMemory": 0,
  "userMemoryReservation": "0B",
  "totalMemoryReservation": "0B",
  "peakUserMemoryReservation": "0B",
  "peakTotalMemoryReservation": "0B",
  "peakTaskTotalMemoryReservation": "0B",
  "totalCpuTime": "0.00ms",
  "totalScheduledTime": "0.00ms",
  "fullyBlocked": false,
  "blockedReasons": [],
  "totalAllocation": "0B",
  "peakNodeTotalMemorReservation": "0B"
}
```

**Comment by twoyang0917** [comment]
I fixed it
```
-        if (Object.values(query.queryStats.runtimeStats).length == 0) return null;
+        if (!query.queryStats.hasOwnProperty('runtimeStats')) return null;
+        else if (Object.values(query.queryStats.runtimeStats).length == 0) return null;
+
```

**Comment by yuanzhanhku** [comment]
Thanks for reporting this issue. It should have been fixed in https://github.com/prestodb/presto/pull/17329.
