### ISSUE TITLE
Error: Invalid configuration property hive.metastore.uri: may not be null

### ISSUE THREAD

**Issue by zihaochen68** [prestodb/presto#17342]
Why must I configure hive.metastore.uri when I use iceberg connector and configure iceberg.catalog.type=HADOOP
This is my properties.
```
connector.name=iceberg
iceberg.catalog.type=HADOOP
iceberg.catalog.warehouse=hdfs://xxx
```
When I use Flink Iceberg, I don't have to configure it
thanx

**Comment by agrawalreetika** [comment]
Same as https://github.com/prestodb/presto/issues/19920

**Comment by tdcmeehan** [comment]
Closing as duplicate
