### ISSUE TITLE
Create warning for low maxStandardError approx_distinct

### ISSUE THREAD

**Issue by highker** [prestodb/presto#17364]
- Create a `PERFORMANCE_WARNING` for `approx_distinct` function with low `maxStandardError`
- The code is similar to the warning for `COUNT(DISTINCT ...)`
- The code is in `AggregationAnalyzer`
- The warning should also through for the low default value (in class `DefaultApproximateCountDistinctAggregation`)

**Comment by stevechuck** [comment]
I can have a crack at this

**Comment by tdcmeehan** [comment]
Fixed in #17433
