### ISSUE TITLE
Split value based On regex In Presto : 331

### ISSUE THREAD

**Issue by rpatid10** [prestodb/presto#17506]
Is there any way to split values based on regex in presto.
1. Minimum 6 digits should be there in first element of split.
2. If digit count of Digits  is less than 6 than need to consider some 0's as digit then split.
3. If digit count is  >= 6 then just need to split in 2 groups.
Below query is working as expected in Hive.
But I am not able to do the same using presto.

**Hive Query**

select low as original(regexp_replace(low,'(\\d{6,}?)(0+)$','$1|$2'),'\\|') Output_Value from test;

**OutPut**
+----------------+-----------------------+--+
| **original**  |               **output_value**      |
+----------------+-----------------------+--+
| 1234567890000  | ["123456789","0000"]  |
| 1234000000000  | ["123400","0000000"]  |
+----------------+-----------------------+--+

When I am trying to do same in prestro using below query:

select regexp_split('1234567890000','(\\d{6,}?)(0+)$','$1|$2'),'\\|') Output_Value from test;

In Output it's not splitting anything and giving same result as input i.e. 1234567890000

presto> SELECT regexp_split('1234567890000', '(\\d{6,}?)(0+)$');
      _col0      
-----------------
 [1234567890000] 
(1 row)

**Comment by ebyhr** [comment]
The right repository for version >= 300 is https://github.com/trinodb/trino
I found you already got the answer in the community Slack though.
