### ISSUE TITLE
mvn clean install -DskipTests in mac ARM64 platform error

### ISSUE THREAD

**Issue by KahnCheny** [prestodb/presto#17530]
com.google.protobuf:protoc:exe:osx-aarch_64:3.0.0
[ERROR] 
[ERROR]   Try downloading the file manually from the project website.
[ERROR] 
[ERROR]   Then, install it using the command: 
[ERROR]       mvn install:install-file -DgroupId=com.google.protobuf -DartifactId=protoc -Dversion=3.0.0 -Dclassifier=osx-aarch_64 -Dpackaging=exe -Dfile=/path/to/file
[ERROR] 
[ERROR]   Alternatively, if you host your own repository you can deploy the file there: 
[ERROR]       mvn deploy:deploy-file -DgroupId=com.google.protobuf -DartifactId=protoc -Dversion=3.0.0 -Dclassifier=osx-aarch_64 -Dpackaging=exe -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

com.google.protobuf:protoc: Must be version 3.18.0 or higher 
io.grpc:protoc-gen-grpc-java: Must be version 1.42.1 or higher 
<configuration>
                    <protocArtifact>com.google.protobuf:protoc:3.0.0:exe:${os.detected.classifier}</protocArtifact>
                    <pluginId>grpc-java</pluginId>
                    <pluginArtifact>io.grpc:protoc-gen-grpc-java:1.0.0:exe:${os.detected.classifier}</pluginArtifact>
 </configuration>

**Comment by v-jizhang** [comment]
aarch_64 release of protoc doesn't exist. To workaround, add the following to the file ~/.m2/wrapper/dists/apache-maven.../.../../conf/settings.xml
Inside section &lt;profiles&gt;:
  ```
   <profile>
      <id>apple-silicon</id>
      <properties>
        <os.detected.classifier>osx-x86_64</os.detected.classifier>
      </properties>
    </profile>
```

Inside section &lt;activeProfiles&gt;:
```
  <activeProfile>
      apple-silicon
    </activeProfile>
  </activeProfiles>
```
By default, section profiles and activeProfiles are commented out so please make sure the newly added codes are not.
