### ISSUE TITLE
Querying through superset on an all capitalized varchar doesn't work

### ISSUE THREAD

**Issue by pmartijena** [prestodb/presto#17603]
I am using PrestoDB setup with the elastic connector. It is being used through Apache Superset. I have a field, let's say it's called type, that is a varchar and happens to be capitalized in my database, e.g. "TEST".

Querying on this in Superset with an equals comparison does not work:

`type='TEST'
`
It returns no results.

Querying on this with lower, however, does work.
`lower(type)='test'`

Because I'm using superset, I don't have a way to lower the field when filtering. I'm curious why the first query does not match, and if I should be using a different data type than varchar or if this is a known problem that I can find a solution for.

**Comment by agrawalreetika** [comment]
Hi @pmartijena, Did you try the same query comparison from presto-cli, just to check if this is something to do with superset or prestodb?

**Comment by pmartijena** [comment]
Hi @agrawalreetika. We ended up being able to query it by making the strings lowercase in elasticsearch. It might be beneficial to add that to the documentation.

Thank you!
