### ISSUE TITLE
Default filter_and_project_min_output_page_row_count is too high for some environments

### ISSUE THREAD

**Issue by kaikalur** [prestodb/presto#17631]
For queries like

SELECT DISTINCT country FROM fact_table LIMIT 1000;

256 is too much as the results are lot fewer. But we never send the results out until the query completes (and if the user is unlucky, it might even timeout). This is due to the accumulation until 256 rows just to drop the precomputed hash variable. This is not desirable.

So we should make it smarter based on context or time.

**Comment by rohanpednekar** [comment]
Cloing as https://github.com/prestodb/presto/pull/17640 got merged!
