### ISSUE TITLE
druid has enabled authentication, how should presto be configured to connect to druid

### ISSUE THREAD

**Issue by admh** [prestodb/presto#17667]
Hello everyone, druid has enabled authentication, how should presto be configured to connect to druid?

Druid is an authentication configured according to the official documentation.
https://druid.apache.org/docs/latest/operations/security-overview.html

I see no official documentation on how to configure the username and password.
https://prestodb.io/docs/current/connector/druid.html
![image](https://user-images.githubusercontent.com/19163424/163988382-3a4e3b09-9352-4c2a-bacb-6322935dce25.png)

**Comment by imjalpreet** [comment]
@admh Below are the authentication configs for the Druid Connector:
1. `druid.authentication.type` : `NONE`, `BASIC` or `KERBEROS`
2. I think you would be using `BASIC`, so you would need below two additional configs
    a. 
`druid.basic.authentication.username` 
    b. `druid.basic.authentication.password`

Related Slack thread: https://prestodb.slack.com/archives/C07JH9WMQ/p1650364035646279

**Comment by admh** [comment]
works, thanks
