### ISSUE TITLE
[Question] How to use presto-native-execution?

### ISSUE THREAD

**Issue by zhanglistar** [prestodb/presto#17677]
Thanks in advance.

**Comment by rohanpednekar** [comment]
@majetideepak, @mshang816 and @highker, Can you guys please provide some guidance here?

**Comment by GithubZhitao** [comment]
Is this module new ?  I never see this module before. How to play with it ?

**Comment by zhanglistar** [comment]
> 

Yes, new, but not release, may be in deving.
