### ISSUE TITLE
CopyOnWriteConfiguration breaks copy constructor of Configuration

### ISSUE THREAD

**Issue by 7c00** [prestodb/presto#17736]
`CopyOnWriteConfiguration` extends Configuration and holds a Configuration instance inside itself. All read on write operations are delegated to the instance, while the internal attributes of `CopyOnWriteConfiguration` (like `finalParameters`, inherited from super class) are not synced. However [the copy constructor](https://github.com/apache/hadoop/blob/d346be9bd2d45d0b17ecf0c2b9d8466f00b47e0d/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/conf/Configuration.java#L841) will  copy these attributes. As a result, when we call create a Configuration like
```java
Configuration conf = new Configuration(copyOnWriteConfigration)
```
, we would not get a right result. This could cause bugs if a third party library does as this.

**Comment by 7c00** [comment]
As a quick fix, we could add an option to let user disable configuration cache.

**Comment by rschlussel** [comment]
@NikhilCollooru

**Comment by pratyakshsharma** [comment]
Closing this since we have a solution now via https://github.com/prestodb/presto/pull/18441
