### ISSUE TITLE
I found that hudiVersion was reverted in 0.272.1 ， who can share some reason about it?

### ISSUE THREAD

**Issue by ououseisei** [prestodb/presto#17741]
I found that hudiVersion was reverted in 0.272.1 ， who can share some reason about it?
Are there any problem in hudi 0.10.1?

-----------0.272-----------
<dep.hudi.version>0.10.1</dep.hudi.version>

-----------0.272.1
<dep.hudi.version>0.9.0</dep.hudi.version>

**Comment by ououseisei** [comment]
@[mshang816]

**Comment by ououseisei** [comment]
@mshang816

**Comment by ououseisei** [comment]
![Uploading 图片.png…]()
@mshang816
@varungajjala

**Comment by rohanpednekar** [comment]
CC @imjalpreet @agrawalreetika @pratyakshsharma

**Comment by mshang816** [comment]
@ououseisei Please see the comments in the PR https://github.com/prestodb/presto/pull/17706
In short, the Hudi changes broke one of our internal connectors so we revert it in the 272 release and keep investigating the issue on master.
