### ISSUE TITLE
Split doesn't start with zero

### ISSUE THREAD

**Issue by metalmensch** [prestodb/presto#17774]
Split doesn't return anything when the the zero element in the array is selected.

**Comment by rohanpednekar** [comment]
Could you please provide more details here? Presto version, Connector you are using, Query, and the details about the error or steps to repro this issue? 

CC @nmahadevuni

**Comment by metalmensch** [comment]
Sure!

Presto version 0.272.1
I use Daiquery to connect.

**Repro:**
SELECT SPLIT('first,second,third', ',')[0] 
this returns an error.

SELECT SPLIT('first,second,third', ',')[1] 
this returns 'first'

Split should start with zero.

**Comment by ClarenceThreepwood** [comment]
Arrays in all/most databases are 1-based. Quoting from ANSI standard

4.10.2 Arrays
An array is a collection A in which each element is associated with exactly one ordinal position in A. If n is
the cardinality of A, then the ordinal position p of an element is an integer in the range 1 (one) ≤ p ≤ n. If EDT
is the element type of A, then A can thus be considered as a function of the integers in the range 1 (one) to n
into EDT.
