### ISSUE TITLE
Feature Request: Add function to create a tdigest from its internal representation (inverse to destructure_tdigest)

### ISSUE THREAD

**Issue by amellnik** [prestodb/presto#17798]
If there's no concerns about adding this, @dizc is planning on implementing it in the next few days.  A few questions:

* `destructure_tdigest` returns results as a row.  A strict inverse would accept a row with the same structure as its input, but this doesn't seem very common.  Should the input be the row or its contents as separate arguments? 
* Is `structure_tdigest` an acceptable name or are there better options?  Maybe `construct_tdigest` or something along those lines?

cc @sdimmick & @tdcmeehan

**Comment by dizc** [comment]
> Should the input be the row or its contents as separate arguments?

I think this makes a lot of sense, and is likely clearer in terms of usage.

> Is structure_tdigest an acceptable name or are there better options? Maybe construct_tdigest or something along those lines?

Also agreed here - construct_tdigest is more descriptive and potentially less confusing as structure_tdigest can be ambiguous given the similar naming to structs.

**Comment by amellnik** [comment]
Closed via #17976
