### ISSUE TITLE
Download page links to non-existent 0.273.1 release notes

### ISSUE THREAD

**Issue by Stevoisiak** [prestodb/presto#17822]
## Issue

On the Presto download page (https://prestodb.io/download.html), there is a link to the 0.273.1 Release Notes (https://prestodb.io/docs/current/release/release-0.273.1.html) which leads to a 404 page.

The Presto documentation site (https://prestodb.io/docs/current/release.html) does not show any release notes for 0.273.1. The most recent release notes are for 0.273.

## Screenshots

![Presto download page](https://user-images.githubusercontent.com/1330770/171457992-e7010d0e-0018-41f9-a8d7-bd8cc9474580.png)

![404 file not found](https://user-images.githubusercontent.com/1330770/171456103-f9837fbb-22ad-4cdf-89f1-c9129cdd786f.png)

![Release notes as of 2022-06-01](https://user-images.githubusercontent.com/1330770/171457825-3116f11e-b140-4d0a-be65-a53d31b14ed7.png)

**Comment by agrawalreetika** [comment]
@Stevoisiak I don't see any release page as of now for presto-0.273.1 yet, I think that's the reason it's not listed on the release notes page. And because of the same reason link is broken on the download page too.
Ref - https://github.com/prestodb/presto/tree/master/presto-docs/src/main/sphinx/release

**Comment by rohanpednekar** [comment]
We recently release 0.273.2 and all URLs are now updated. can you see if you facing the same issue for **0.273.2**

https://prestodb.io/docs/current/release/release-0.273.2.html

**Comment by pratyakshsharma** [comment]
Closing due to long inactivity and the link works fine. 

@Stevoisiak Feel free to reopen in case of any more issues.
