### ISSUE TITLE
Address additional comments for PR 16416

### ISSUE THREAD

**Issue by yingsu00** [prestodb/presto#17869]
https://github.com/prestodb/presto/pull/16416 is waiting to be merged. As per offline discussion, we create this issue to track the nits issue in this PR.

**Comment by yingsu00** [comment]
cc @simmend @nmahadevuni @rongrong

**Comment by yingsu00** [comment]
@nmahadevuni Naveen do you have time to work on this in the next a few days?

**Comment by yingsu00** [comment]
Thanks @harshjk for submitting PR17917 to resolve this issue. This message just tracks the unresolved comments in PR https://github.com/prestodb/presto/pull/17917

1. EquivalenceClassProperty.java, move line 231-232 to the caller
2. EquivalenceClassProperty.java, remove unnecessary toString() on Expressions in the toString() method
3. KeyProperty.java Remove line 113 `requireNonNull(newKey, "newKey is null");`
4. Replace the builder classes in LogicalPropertiesImpl to static methods
5. RemoveRedundantAggregateDistinct.java, simplify apply() by replacing the streaming API to for loop. The current implementation is hard to read. Also, @rongrong mentioned to check match once here

**Comment by simmend** [comment]
Thanks all!

**Comment by rschlussel** [comment]
Commented on #17917, but one other thing to do is to refactor how the Property classes are constructed to make all the Property classes immutable.

**Comment by pratyakshsharma** [comment]
can we close this issue now that all the PRs are merged @yingsu00 ?
