### ISSUE TITLE
when will the native exectution engine be ready?

### ISSUE THREAD

**Issue by johndb2016** [prestodb/presto#17895]
we are eager to know the next thing about the native execution, like the pretissimo, so when will it be ready? i am wondering

**Comment by rohanpednekar** [comment]
Thanks for checking in!  It's under development and dates are not finalized yet. We will probably have it announced through the blog or release notes. So please stay tuned. 

Join our newsletter or Slack: [prestodb.slack.com](https://prestodb.slack.com/) or [sign up](https://join.slack.com/t/prestodb/shared_invite/enQtNTQ3NjU2MTYyNDA2LTYyOTg3MzUyMWE1YTI3Njc5YjgxZjNiYTgxODAzYjI5YWMwYWE0MTZjYWFhNGMwNjczYjI3N2JhM2ExMGJlMWM)
