### ISSUE TITLE
Iceberg can create table with TIMESTAMP WITH TIME ZONE but can't insert data

### ISSUE THREAD

**Issue by v-jizhang** [prestodb/presto#17891]
presto:userdb> DROP TABLE IF EXISTS t;
DROP TABLE
presto:userdb> CREATE TABLE t (d timestamp with time zone, b integer) WITH (format = 'PARQUET');
CREATE TABLE
presto:userdb> INSERT INTO t VALUES (TIMESTAMP '1969-12-01 00:00:00.000000 UTC', 10);
Query 20220616_023212_00019_bzdmf failed: line 1:23: Mismatch at column 1: 'd' is of type timestamp but expression is of type timestamp with time zone

**Comment by gupteaj** [comment]
PR https://github.com/prestodb/presto/pull/21096
