### ISSUE TITLE
Dead link found on the community page at Prestodb.io while looking to join as a contributor

### ISSUE THREAD

**Issue by gregsimons** [prestodb/presto#17936]
I wanted to signup to update some of the docs whilst working through a getting started guide and headed over to prestodb.io to see if I could find some contribution guidelines.

[Presto DB Community](https://prestodb.io/community.html)

The contribution guidelines state the following:

You will need to sign a [Contributor License Agreement](https://developers.facebook.com/opensource/cla) ("CLA") before it can be accepted into the repository.

The link above does not resolve. It would also be useful to show the contribution guidelines on the repository README.md

**Comment by tdcmeehan** [comment]
The CONTRIBUTING.md file gives this information, and it looks like the community page is out of date.  Would you like to submit a PR to correct that?  The repository is here: [prestodb/prestodb.github.io](https://github.com/prestodb/prestodb.github.io)

**Comment by pratyakshsharma** [comment]
The website is now revived and PR is raised to add contributing guidelines on README page.
