### ISSUE TITLE
can not start presto server

### ISSUE THREAD

**Issue by VegetableDog118** [prestodb/presto#17959]
Hi, we I start the server , I kpet getting this error

<img width="980" alt="image" src="https://user-images.githubusercontent.com/65802837/176469096-53b620a1-d266-425a-a17b-c7a5fe53e6ac.png">

But my node. environment is not null. Any help would be appreciated.

**Comment by agrawalreetika** [comment]
From error message looks like some issue with `node.properties` , could you please share config in this file for your setup?

**Comment by VegetableDog118** [comment]
Hi，this problem is solved but the new error is this:
<img width="1397" alt="image" src="https://user-images.githubusercontent.com/65802837/176695101-96e96407-0b06-47a8-aeba-5e9307d54174.png">
I am not sure why this uri is wrong:(

**Comment by VegetableDog118** [comment]
Also if i use ubutunu to deploy presto it says:
<img width="825" alt="image" src="https://user-images.githubusercontent.com/65802837/176695860-d69e6825-86bd-499a-9e88-4ea75d5e43e6.png">
Any help would be appreciated!

**Comment by agrawalreetika** [comment]
@VegetableDog118 Could you please share your `config.propertes`?

**Comment by VegetableDog118** [comment]
coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8080
query.max-memory=5GB
query.max-memory-per-node=1GB
query.max-total-memory-per-node=2GB
discovery-server.enabled=true
discovery.uri=http://zhuhaolin:8080


<img width="1316" alt="image" src="https://user-images.githubusercontent.com/65802837/176709918-467e43a6-a51c-410f-9ecf-cc38751b8617.png">

**Comment by z-bb** [comment]
I think you should add node.environment in node.properties

**Comment by agrawalreetika** [comment]
> coordinator=true node-scheduler.include-coordinator=true http-server.http.port=8080 query.max-memory=5GB query.max-memory-per-node=1GB query.max-total-memory-per-node=2GB discovery-server.enabled=true discovery.uri=http://zhuhaolin:8080
> 
> <img alt="image" width="1316" src="https://user-images.githubusercontent.com/65802837/176709918-467e43a6-a51c-410f-9ecf-cc38751b8617.png">

Add `-Djdk.attach.allowAttachSelf=true` in jvm.properties

**Comment by pratyakshsharma** [comment]
@VegetableDog118 Closing this ticket due to long inactivity. Feel free to reopen if you are still facing issues.
