### ISSUE TITLE
Unable to read to query Hive views with Presto & Trino

### ISSUE THREAD

**Issue by Oliver-GSN** [prestodb/presto#17986]
I have had issues trying to read Hive views using Presto or Trino.
I have tried different versions of both on EMR using Glue Data Catalog as the metastore (presto: 0.245.1-amzn-0, 338, 343. Trino: 360, 378).
The error a receive for some Presto versions is
java.sql.SQLException: Query failed (#20220624_160314_00014_4kmba): Table 'schema.table' not found at com.facebook.presto.jdbc.PrestoResultSet.resultsException(PrestoResultSet.java:1841)
For Trino I receive Hive views are not supported
For Trino, I couldn't use the [legacy or experimental](https://trino.io/docs/current/connector/hive.html#hive-views) solution to read views in any of the versions I used. When I tried to include this configuration the trino-server would not start and return a failed connection error.
The views I have been trying to query are supported by the legacy and experimental implementation, they aren't defined using HQL syntax but ANSI SQL. In fact, I can take any of the views' create view statement, remove the ` from it and use that to create the view using Presto.

**Comment by rohanpednekar** [comment]
Could you please use --debug option with presto-cli, reproduce the failure, and can you please post the stack trace you get?

**Comment by Oliver-GSN** [comment]
Sure

`An error occurred while calling o84.execute. : java.sql.SQLException: Query failed (#20220707_211759_00019_sd3vd): Table 'schema.table' not found at io.prestosql.jdbc.AbstractPrestoResultSet.resultsException(AbstractPrestoResultSet.java:1761) at io.prestosql.jdbc.PrestoResultSet.getColumns(PrestoResultSet.java:252) at io.prestosql.jdbc.PrestoResultSet.create(PrestoResultSet.java:54) at io.prestosql.jdbc.PrestoStatement.internalExecute(PrestoStatement.java:249) at io.prestosql.jdbc.PrestoStatement.execute(PrestoStatement.java:227) at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231) at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381) at py4j.Gateway.invoke(Gateway.java:259) at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133) at py4j.commands.CallCommand.execute(CallCommand.java:79) at py4j.GatewayConnection.run(GatewayConnection.java:209) at java.lang.Thread.run(Thread.java:750) Caused by: io.prestosql.spi.connector.TableNotFoundException: Table 'schema.table' not found at io.prestosql.plugin.hive.HiveMetadata.doGetTableMetadata(HiveMetadata.java:546) at io.prestosql.plugin.hive.HiveMetadata.getTableMetadata(HiveMetadata.java:528) at io.prestosql.plugin.hive.HiveMetadata.getTableMetadata(HiveMetadata.java:510) at io.prestosql.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.getTableMetadata(ClassLoaderSafeConnectorMetadata.java:220) at io.prestosql.metadata.MetadataManager.getTableMetadata(MetadataManager.java:515) at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:1217) at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:322) at io.prestosql.sql.tree.Table.accept(Table.java:53) at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27) at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:339) at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:2483) at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1526) at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:322) at io.prestosql.sql.tree.QuerySpecification.accept(QuerySpecification.java:144) at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27) at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:339) at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:349) at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1039) at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:322) at io.prestosql.sql.tree.Query.accept(Query.java:107) at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27) at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:339) at io.prestosql.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:308) at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:83) at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:75) at io.prestosql.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:256) at io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:182) at io.prestosql.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:757) at io.prestosql.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:123) at io.prestosql.$gen.Presto_343____20220704_153513_2.call(Unknown Source) at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125) at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69) at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:829)`

**Comment by bitsondatadev** [comment]
@Oliver-GSN, by looking at your stack trace, it seems like you are using PrestoSQL, which was [rebranded to Trino](https://trino.io/blog/2020/12/27/announcing-trino.html) some time ago.

Feel free to raise this on [the Trino GitHub](https://github.com/trinodb/trino).

**Comment by Oliver-GSN** [comment]
Sorry about that, got the stacktraces mixed. I updated my comment with the stacktrace I get using Presto version `0.245.1`

This Presto version can query basic views like mine that use ANSI SQL. I'll put a template of what I get when issuing the SHOW CREATE VIEW in Hive for the views. 

```
CREATE VIEW `schema`.`view` AS
select
	`table`.`col1`,
	`table`.`col2`,
	`table`.`col3`
from
	`schema`.`table`
where
	`table`.`datetime` = '20220623'
```

**Comment by bitsondatadev** [comment]
@Oliver-GSN, if you're experimenting with both I still recommend filing something in the Trino repo. Also, if you're still on PrestoSQL, I recommend updating to a more recent version of Trino and test of this is still an issue.

**Comment by Oliver-GSN** [comment]
I resolved the problem in Trino. I wasn't using the `hive.views-execution.enabled` configuration in `trino-connector-hive`.

Probably the problem is that the most recent Presto version supported by EMR 5 (EMR 5.36.0, Presto 0.267), does not support views. I can't test this, nor do I know from which version this basic support is available.
