### ISSUE TITLE
hdfs is not supported as the external filesystem.

### ISSUE THREAD

**Issue by Stevenscj** [prestodb/presto#18003]
Presto version : 0.273.3
Presto JDBC version : 0.273.3
Presto coordinator : 1 , worker : 2
Data Source : Hive

After the local cache configuration is added to the hive.properties file:

`
connector.name=hive-hadoop2
hive.metastore.uri=thrift://xx.xxx.xx.xx:9083
hive.config. resources=/data/hadoop/hadoop-3.3.3/etc/hadoop/core-site.xml, /data/hadoop/hadoop-3.3.3/etc/hadoop/hdfs-site.xml

cache.enabled=true
cache.type=ALLUXIO
cache.base-directory=fiLe:///data/cache/alLuxio
cache.alluxio.max-cache-size=6GB
`

When I open a table and get the data with DBeaver, an error occured below : 

SQL Error [16777221]: Query failed (#20220708_012108_00000_hcm7u): hdfs is not supported as the external filesystem.

**Comment by lglfa** [comment]
you can refer to [issue 17445](https://github.com/prestodb/presto/issues/17445)

**Comment by imjalpreet** [comment]
There is an ongoing PR #18040 which once merged should fix this issue.

**Comment by pratyakshsharma** [comment]
Guess we can close this ticket then? @imjalpreet

**Comment by humengyu2012** [comment]
Maybe we could upgrade the version of alluxio client https://github.com/prestodb/presto/pull/19594

**Comment by agrawalreetika** [comment]
Looks like upgrade was reverted as part of https://github.com/prestodb/presto/pull/20401

**Comment by agrawalreetika** [comment]
@twoyang0917 I see Alluxio has been upgraded to 307 recently on master as part of https://github.com/prestodb/presto/pull/20437/files, you can verify if this fixes the issue you had.

**Comment by agrawalreetika** [comment]
Awesome, thanks for confirming @twoyang0917. Will close this issue then.
