### ISSUE TITLE
about Prestissimo

### ISSUE THREAD

**Issue by LvLiangLiang-dev** [prestodb/presto#18112]
I want to install and use prestissimo. Can anyone tell me how to get the beta Prestissimo(presto on velox)？

**Comment by rohanpednekar** [comment]
@LvLiangLiang-dev 

It's not ready to use yet. It's under development. We will probably have it announced through the blog or release notes.

If you are interested in developing with us then please let us know and  join https://prestodb.slack.com/archives/C03DYLFBN06 

cc @majetideepak @aditi-pandit

**Comment by LvLiangLiang-dev** [comment]
I want to ask about the actual landing time of Presto native engine on Velox, because we want to reduce costs and increase efficiency. is there a specific time roadmap? tks

**Comment by ScrapCodes** [comment]
Hi @rohanpednekar , I am interested to work on or may be try out beta/alpha for prestissimo - please let me know how can I get involved !

**Comment by StevenMih** [comment]
Hi @ScrapCodes ,   @majetideepak is good to talk with regarding Prestissimo with is still under development WIP. If you're interested in joining the project development, he can point you to some starter issues and help you get involved! 
Also i suggest you joining the #presto-cpp channel in the presto slack if you haven't already: https://join.slack.com/t/prestodb/shared_invite/zt-1e895j77n-zdX2Z3~6tFDnmFSruztQOw

**Comment by StevenMih** [comment]
>

**Comment by majetideepak** [comment]
@ScrapCodes You can always pick open issues from https://github.com/prestodb/presto/issues. If you can share your area of interest/strengths, I can share other issues. Slack is definitely easier to discuss.
