### ISSUE TITLE
Presto integrated ranger error

### ISSUE THREAD

**Issue by chufa** [prestodb/presto#18200]
there are some steps:
1、Installed ranger-presto-plugin successfully；
./enable-presto-plugin.sh 
some message：
Property access-control.name updated successfully with : 'ranger'
Linking config files
Ranger Plugin for presto has been enabled. Please restart presto to ensure that changes are effective.
2、I will run the presto in idea
this is ranger plugin setting and all the config will be writen into presto project path

some errors：
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, java.lang.RuntimeException: java.lang.ClassNotFoundException: org.apache.ranger.authorization.presto.authorizer.RangerSystemAccessControl
  at org.apache.ranger.authorization.presto.authorizer.RangerSystemAccessControl.<init>(RangerSystemAccessControl.java:38)
  at org.apache.ranger.authorization.presto.authorizer.RangerSystemAccessControlFactory.lambda$create$0(RangerSystemAccessControlFactory.java:45)
  while locating org.apache.ranger.authorization.presto.authorizer.RangerSystemAccessControl

1 error

**Comment by agrawalreetika** [comment]
Hi @chufa,
You can use Ranger-Based Authorization for Hive connector by using the required configuration in your hive catalog configuration - https://prestodb.io/docs/current/connector/hive-security.html#hive-ranger-based-authorization
This is supported in presto-0.275 or later.
Let me know if you have any questions.

**Comment by chufa** [comment]
Thans

I have solved the problem, the presto spi implemented by ranger is io.prestsql.spi, and the presto I need to integrate is the facebook version, and this io.prestsql.spi implementation needs to be noted that the associated packages need to be changed to facebook dependencies package, otherwise the above error will be generated


        <dependency>
            <groupId>com.facebook.presto</groupId>
            <artifactId>presto-spi</artifactId>
        </dependency>

        <dependency>
            <groupId>com.facebook.airlift</groupId>
            <artifactId>bootstrap</artifactId>
        </dependency>

        <dependency>
            <groupId>com.facebook.airlift</groupId>
            <artifactId>log</artifactId>
        </dependency>

        <dependency>
            <groupId>com.facebook.airlift</groupId>
            <artifactId>configuration</artifactId>
        </dependency>

**Comment by pratyakshsharma** [comment]
I guess we can close this issue. 

@chufa Feel free to reopen in case you are still having any troubles.
