### ISSUE TITLE
Clickhouse plugin should be packed in tarball after 0.273

### ISSUE THREAD

**Issue by SamStayGold** [prestodb/presto#18217]
In version 0.273, a new Presto connector for Clickhouse was added as mentioned in [this relase note](https://prestodb.io/docs/current/release/release-0.273.html). 

However, the provided tarball did not include clickhouse connector in plugin directory by default. This connector was well documented in release note and connector docs, but when implemented，coordinator failed to start due to errors below：
`2022-08-23T19:17:46.901+0800	ERROR	main	com.facebook.presto.server.PrestoServer	No factory for connector clickhouse
java.lang.IllegalArgumentException: No factory for connector clickhouse
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:216)`

Just suggest presto-clickhouse connector to be packed into official relase tarballs so that it won't confuse end users. Thanks~

**Comment by agrawalreetika** [comment]
@SamStayGold Yes, I see presto-clickhouse is not added in presto-server assembly. Which is by its not getting added as a plugin in presto tar.
If you want to do it, you can add presto-clickhouse dependency in these 2 files and build presto project again, it will add presto-clickhouse in presto tar plugin.

https://github.com/prestodb/presto/blob/master/presto-server/src/main/assembly/presto.xml
https://github.com/prestodb/presto/blob/master/presto-server/pom.xml

**Comment by SamStayGold** [comment]
Many thanks! I have already built presto-clickhouse connector separately and got it running in test environment. Nice work~
