### ISSUE TITLE
Filters on Date not supported in Presto C++

### ISSUE THREAD

**Issue by pramodsatya** [prestodb/presto#18243]
In function toFilter() in presto-native-execution/presto_cpp/main/types/PrestoToVeloxQueryPlan.cpp, filters on Date are not supported. When running TPCH query 1 on the Presto C++ worker as a result, the following error appears:
Unsupported range type: DATE

**Comment by yingsu00** [comment]
@pramodsatya can you paste the stack trace please?

**Comment by pramodsatya** [comment]
This is the stack trace I got from Presto session > Query details > Error information:
VeloxUserError:  Unsupported range type: DATE

**Comment by aditi-pandit** [comment]
@pramodsatya : Please check if https://github.com/facebookexternal/presto_cpp/pull/633 helps you. I had written this code a while ago, but this didn't get checked in because of not having Parquet tests yet.

**Comment by pramodsatya** [comment]
Thank you so much @aditi-pandit, this PR fixed the issue
