### ISSUE TITLE
sortedCandidates is null or empty for ModularHashingNodeProvider for oracle connector

### ISSUE THREAD

**Issue by harsh9898** [prestodb/presto#18272]
Presto version : 0.268
Presto JDBC version : 0.268
Presto coordinator : 1 , worker : 1
Data Source : Oracle

When I am trying open a table and get the data with DBeaver, it's giving the following error :

SOL Error [65541]: Query failed (#20220901_125736_00006_unsxw): sortedCandidates is null or empty for ModularHashingNodeProvider

If someone figured out to resolve this then Please help with this one.

@Stevenscj Have you resolved this?

@ShaoyiZhang I deployed the credential to the worker node but still gave the error.

_Originally posted by @harsh9898 in https://github.com/prestodb/presto/issues/18002#issuecomment-1234462605_

**Comment by Sarfaraz-214** [comment]
@harsh9898 Adding `thrift.server.ssl.enabled=false` in `config.properties` under `<presto-server-dir>/etc/` has helped me resolve this issue. If you haven't tried it out, then I recommend you to try once.

**Comment by harsh9898** [comment]
Resolved this issue. It was giving this issue as oracle was not present as the data source in presto's config.properties file.

**Comment by sivavenkatgogineni** [comment]
@harsh9898 We are having exactly the same issue, what did you have to add to config.properties to fix it?

**Comment by baiqiubai** [comment]
> [@harsh9898](https://github.com/harsh9898) We are having exactly the same issue, what did you have to add to config.properties to fix it?

 We are having exactly the same issue. Did you solve this problem？
