### ISSUE TITLE
Native CI failing due to Decimal test failure

### ISSUE THREAD

**Issue by majetideepak** [prestodb/presto#18312]
Error:  Failures: 
Error:    TestHiveQueriesUsingJSON.testDecimalLiterals:16->TestHiveQueries.testDecimalLiterals:349->AbstractTestQueryFramework.assertQuery:149 For query: 
 SELECT * from (values decimal'123.12', decimal'-0.0004', NULL,CAST('922337203685477580' as DECIMAL(18,0)), decimal'1123', NULL)
not equal
Actual rows (up to 100 of 1 extra rows shown, 6 rows in total):
    [-17014118346046923173168730371588410.5724]
Expected rows (up to 100 of 1 missing rows shown, 6 rows in total):
    [-0.0004]

Error:    TestHiveQueriesUsingThrift.testDecimalLiterals:16->TestHiveQueries.testDecimalLiterals:349->AbstractTestQueryFramework.assertQuery:149 For query: 
 SELECT * from (values decimal'123.12', decimal'-0.0004', NULL,CAST('922337203685477580' as DECIMAL(18,0)), decimal'1123', NULL)
not equal
Actual rows (up to 100 of 1 extra rows shown, 6 rows in total):
    [-17014118346046923173168730371588410.5724]
Expected rows (up to 100 of 1 missing rows shown, 6 rows in total):
    [-0.0004]

**Comment by majetideepak** [comment]
The Presto Serializer changes in Velox need corresponding changes here in the deserialization code.

**Comment by spershin** [comment]
> The Presto Serializer changes in Velox need corresponding changes here in the deserialization code.

@majetideepak 
Do I understand correctly that Prestos serialization has been changed very recently?

**Comment by majetideepak** [comment]
@spershin yes, last week as part of this PR https://github.com/facebookincubator/velox/pull/2444
