### ISSUE TITLE
Documentation disappeared from site

### ISSUE THREAD

**Issue by ashleydaley** [prestodb/presto#18325]
The following page no longer exists: https://prestodb.io/docs/0.217/index.html

It only seems to work from v0.251 upwards. Is this normal culling of out of date pages? I like to use this as it is the version of Presto that AWS Athena uses so would very much like it available.

Is there another way to access it if not via the above link?

**Comment by imjalpreet** [comment]
@ashleydaley The older docs were archived recently. You can view them here: https://github.com/prestodb/prestodb.github.io/tree/source/archive

@rohanpednekar/@alileclerc can provide more context on the same.

**Comment by rohanpednekar** [comment]
Yes, we have archived old docs as a housekeeping task for faster deployment and better maintenance of Prestodb website.
