### ISSUE TITLE
Add JavaDoc for Life of a Query path

### ISSUE THREAD

**Issue by tdcmeehan** [prestodb/presto#18347]
Critical classes:

* QueuedStatementResource -- POST and GET methods
* QueuedStatementResource.Query
* DispatchManager
  * In particular, dependencies used in createQueryInternal should also be documented where their behavior is not obvious from a quick glance
* DispatchQueryFactory/LocalDispatchQueryFactory
* ResourceGroupManager
* ManagedQueryExecution/LocalDispatchQuery
* QueryExecution/SqlQueryExecution
* QueryExecutionFactory/SqlQueryExecutionFactory

**Comment by pratyakshsharma** [comment]
this is a great initiative and will go a long way in helping new users and contributors.
