### ISSUE TITLE
query kudu failed？？ Please help me！

### ISSUE THREAD

**Issue by snake-zhiqiang** [prestodb/presto#18356]
version:
0.270

Failed SQL:
select count(1) from kudu.default.issuedata_info_release;

Throw exception:
Query 20220916_061151_08330_8pfzk, FAILED, 3 nodes
Splits: 5 total, 1 done (20.00%)
0:30 [39.2K rows, 0B] [1.3K rows/s, 0B/s]
Query 20220916_061151_08330_8pfzk failed: org.apache.kudu.client.NonRecoverableException: cannot complete before timeout: ScanRequest(scannerId=null, tablet=42ff4e671464497e8a9bb877ab6b59b3, attempt=1, KuduRpc(method=Scan, tablet=42ff4e671464497e8a9bb877ab6b59b3, attempt=1, TimeoutTracker(timeout=30000, elapsed=30010), Trace Summary(0 ms): Sent(1), Received(0), Delayed(0), MasterRefresh(0), AuthRefresh(0), Truncated: false
 Sent: (c1af0b5ccf9f4ed9a6ef54f3047c4682, [ Scan, 1 ])))

When the query succeeds, the output is:
Query 20220916_061149_08329_8pfzk, FINISHED, 3 nodes
Splits: 5 total, 5 done (100.00%)
0:00 [78.3K rows, 0B] [1.37M rows/s, 0B/s]

What I wonder is that sometimes it's a quick success, but sometimes the query times out.

Remark:
I have one  coordinator,and it is also worker,In addition to,there has another tow workers.

Please help me！

**Comment by snake-zhiqiang** [comment]
anybody here？？？？？

**Comment by prabhacloud** [comment]
this seems to be a timeout issue where if the query ran over 30000 ms and successful if it runs under this duration. How long the successful runs took?

**Comment by snake-zhiqiang** [comment]
> this seems to be a timeout issue where if the query ran over 30000 ms and successful if it runs under this duration. How long the successful runs took?

Thanks,i had been found the issue.Due to someone started two presto servers on the same server.
