### ISSUE TITLE
Function 'array_sum' not registered

### ISSUE THREAD

**Issue by tangyuan59** [prestodb/presto#18405]
excuse me ,
i  have a question . when i use ""array_sum"  function to a array object, then my translater prompt  "Function 'array_sum' not registered" to me. how can i do solution it

**Comment by agrawalreetika** [comment]
Hi @tangyuan59,
Could you please let me know how are you trying it?
I tried on my setup its works fine for me.
![image](https://user-images.githubusercontent.com/7887476/192444491-318f154e-bcaf-4a50-83cd-afc5d7cb6f50.png)

**Comment by tangyuan59** [comment]
like this my data object is array(double)
![image](https://user-images.githubusercontent.com/54573307/192961929-1d5069fa-b6be-43b8-8555-5fa24c6cf2a8.png)
when i use array_sum function to it ,i will meet this error,
![image](https://user-images.githubusercontent.com/54573307/192962161-a831e6b8-2161-492b-b1ea-44c8dd5d89eb.png)

**Comment by tangyuan59** [comment]
like this
![image](https://user-images.githubusercontent.com/54573307/192963756-8bb55a5b-3878-47b8-ab5d-e57df5425309.png)
used to array(double)
![image](https://user-images.githubusercontent.com/54573307/192962821-f831ffbe-979d-456f-ba5b-45825f743edd.png)

**Comment by agrawalreetika** [comment]
Could you please just try the above query to verify if array_sum function is getting applied fine in your setup?

**Comment by tangyuan59** [comment]
OK，i will try it。thank you
