### ISSUE TITLE
when will prestissimo be ready for production use?

### ISSUE THREAD

**Issue by johndb2016** [prestodb/presto#18427]
We are eager to accelerate our presto with the native engine, so when it will be ready?

**Comment by rohanpednekar** [comment]
It's under development. We will probably have it announced through the blog or release notes.
 
@majetideepak is committer and good to talk regarding Prestissimo which is still under development WIP. 
If you're interested in joining the project development, he can point you to some starter issues and help you get involved!

I suggest you join the #presto-cpp channel in the presto slack if you haven't already: https://join.slack.com/t/prestodb/shared_invite/zt-1e895j77n-zdX2Z3~6tFDnmFSruztQOw
