### ISSUE TITLE
Improve hudi partition pruning

### ISSUE THREAD

**Issue by harris233** [prestodb/presto#18481]
When we use hudi connector to support hudi query, we find there is something wrong with hudi partition pruning.
`// Retrieve and prune partitions`
`List<String> partitions = hudiPartitionManager.getEffectivePartitions(session, metastore, table.getSchemaName(), table.getTableName(), layout.getTupleDomain());`
For example:
`sql: select * from hudi.db.table where log_date='20221012' and log_hour>='20';`
After partition pruning:
partitions: 
`log_date='20221012'/log_hour='00', log_date='20221012'/log_hour='01', log_date='20221012'/log_hour='02' ...
log_date='20221012'/log_hour='12'...log_date='20221012'/log_hour='23'`
It gets 24 partitions and creates some partitions we don't need.

When we use hive connector to do the same selection, it only gets 4 partitions.
So we can refer to the hive partition pruning to change hudi partition pruning logic.

**Comment by pratyakshsharma** [comment]
Closing this since the PR is already up and is under review. Let us continue the discussion there.
