### ISSUE TITLE
Add Date type filters support to native execution

### ISSUE THREAD

**Issue by majetideepak** [prestodb/presto#18515]
Queries with date filters throw the following error in native execution.
```
VeloxUserError:  Unsupported range type: DATE
```

The required changes are in this unmerged PR https://github.com/facebookexternal/presto_cpp/pull/633

**Comment by majetideepak** [comment]
CC: @aditi-pandit

**Comment by aditi-pandit** [comment]
I'll work on a PR for this. Thanks !

**Comment by aditi-pandit** [comment]
https://github.com/prestodb/presto/pull/18667
