### ISSUE TITLE
Add apache pinot query-options, presto unable to start 

### ISSUE THREAD

**Issue by Divyasam** [prestodb/presto#18550]
Trying to install presto on AKS (https://docs.pinot.apache.org/basics/getting-started/kubernetes-quickstart)

1) Error: Invalid configuration property pinot.query-options: may not be null (for class com.facebook.presto.pinot.PinotConfig.queryOptions)

2) Configuration property 'pinot.allow-multiple-aggregations' was not used
  at com.facebook.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:244)

3) Configuration property 'pinot.use-streaming-for-segment-queries' was not used
  at com.facebook.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:244)

**Comment by cliandy** [comment]
@Divyasam
For (2) and (3) these configs were removed in https://github.com/prestodb/presto/pull/18404, so they need to be removed from your presto configuration.

For (1), will follow up with a PR to fix this.

**Comment by Divyasam** [comment]
Hi @cliandy, 
I did remove 'pinot.allow-multiple-aggregations' and 'pinot.use-streaming-for-segment-queries' from my values yaml config for (2) and (3).
For (1), I did include 'pinot.query-options=enableNullHandling:false' in values yaml config. 
Query options reference: (https://docs.pinot.apache.org/users/user-guide-query/query-options)

These changes worked for me.

**Comment by cliandy** [comment]
@Divyasam awesome, glad things are working; saw another PR resolved the query options so should be good to remove that section as well.
