### ISSUE TITLE
Presto jdbc driver supports TLS 1.3 version?

### ISSUE THREAD

**Issue by lathasrikoyya** [prestodb/presto#18599]
Hi,

We need to support presto JDBC driver which supports TLS 1.2version and TLS 1.3 Version since TLS 1.0 and 1.1 versions are deprecated. We couldn't any documentation about presto which supports TLS 1.3 version. Could you please confirm the same whether presto latest drivers are supporting TLS 1.3 versions or not ? If Presto JDBC drivers provides support from which version It is supporting TLS 1.3 ?

**Comment by prestored** [comment]
Presto uses okhttp version 3.9.0 and As per the okhttp document version 3.5.0+ does support TLSv1.3  - [[[here](https://square.github.io/okhttp/changelogs/changelog_3x/#version-350)]
As per above info, I think presto JDBC driver should support TLSv1.3, you can try out latest presto JDBC driver.
Configuration reference - https://prestodb.io/docs/current/installation/jdbc.html#parameter-reference

**Comment by lathasrikoyya** [comment]
Thank you for your response @prestored . I am closing this issue.
