### ISSUE TITLE
[native] test native CI run is failing due to "No space left on device"

### ISSUE THREAD

**Issue by majetideepak** [prestodb/presto#18619]
Error:  Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.5.2:install (default-install) on project presto-spark-package: Failed to install artifact com.facebook.presto:presto-spark-package:tar.gz:0.279-SNAPSHOT: No space left on device -> [Help 1]
Error:  Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.4:single (bin) on project presto-verifier: Failed to create assembly: Error filtering file '/__w/presto/presto/presto-verifier/target/dependency/launcher/bin/launcher.properties': /__w/presto/presto/presto-verifier/target/archive-tmp/fileSetFormatter.1452627058.tmp/launcher.properties.1666742865.filtered (No such file or directory) -> [Help 1]

https://github.com/prestodb/presto/actions/workflows/test-native.yml

**Comment by mshang816** [comment]
@majetideepak do you have an example of such failed run ?
