### ISSUE TITLE
Build Presto UI with production optimization (minification etc)

### ISSUE THREAD

**Issue by na2hiro** [prestodb/presto#18736]
The JS code for Cluster Overview UI is built without optimization for production. I can observe in [dist/index.js file](https://github.com/prestodb/presto/blob/0a018198fe7b3b1073b00d845c24d24b8c8711a9/presto-router/src/main/resources/router_ui/dist/index.js) following:

* Code is not minified (big file size to download)
* No tree shaking (unused code elimination)
* Code sits inside `eval()`

That causes slow downloading and executing in order to render the UI.

I believe Webpack config with production flag would fix it

**Comment by ChunxuTang** [comment]
Hi @na2hiro, thanks for your suggestion!

I'll take a look at the UI code and minify the dist files.

**Comment by ChunxuTang** [comment]
The problem has been fixed.
@na2hiro Feel free to reopen it or create another ticket if you have any other ideas or suggestions.
