### ISSUE TITLE
Too many TGS_REQ From JDBC (for kerberos)

### ISSUE THREAD

**Issue by lurnagao-dahua** [prestodb/presto#18818]
Hi !

I found about five TGS_REQ from jdbc per second in one query .

Thank you very much for the answer！

**Comment by prestored** [comment]
Could you please clarify your question here? Are you facing an issue here?

**Comment by lurnagao** [comment]
> Could you please clarify your question here? Are you facing an issue here?

In function StatementClientV1#advance, each call to the JsonResponse.execute(QUERY_RESULTS_CODEC, httpClient, request) will sends a tgs_req to kdc :

public boolean advance()
    {
        while (true) {
          if (isClientAborted()) {
                return false;
            }
            ...
            JsonResponse<QueryResults> response;
            try {
                response = JsonResponse.execute(QUERY_RESULTS_CODEC, httpClient, request);
            }
            catch (RuntimeException e) {
                cause = e;
                continue;
            }

            if ((response.getStatusCode() == HTTP_OK) && response.hasValue()) {
                processResponse(response.getHeaders(), response.getValue());
                return true;
            }

            if (response.getStatusCode() != HTTP_UNAVAILABLE) {
                state.compareAndSet(State.RUNNING, State.CLIENT_ERROR);
                throw requestFailedException("fetching next", request, response);
            }
        }
    }

My understanding is that statementClientV1#advance loops through the Coordinator to get results
Sounds like there is no service ticket cache so the client does the auth everytime.

**Comment by lollipopman** [comment]
Thanks @lurnagao-dahua for fixing this issue, would you happen to know what commit fixed the logging verbosity?

**Comment by lurnagao-dahua** [comment]
Sorry, it has not been fixed and closed this as not planned.

**Comment by lollipopman** [comment]
> Sorry, it has not been fixed and closed this as not planned.

ah, that explains why I couldn't find when trawling through git log, thanks!
