### ISSUE TITLE
Presto view struct column with dash sign

### ISSUE THREAD

**Issue by thoithoi58** [prestodb/presto#18819]
Hi

I'm trying to create a AWS Athena view which using Presto as its engine. My configs are
```
{
    "originalSql": "SELECT * FROM tymebank_stages UNION ALL SELECT * FROM gotyme_stages UNION ALL SELECT * FROM tymex_stages",
      "catalog": "awsdatacatalog",
      "schema": "${GlueDatabase}",
      "columns": [
        {
          "name": "detail-type",
          "type": "varchar"
        },
        {
          "name": "detail",
          "type": "row(pipeline varchar,state varchar,stage varchar,execution-id varchar)"
        }
      ]
      }      
```
However whenever I run view preview, it return this error `Unknown type 'row("pipeline" varchar,"state" varchar,"stage" varchar,execution-id varchar)' for column 'detail' in view`. I try to recreate the table by removing the `-` sign in `execution-id` and the problem is fixed. Is there any way I can keep the `-` sign? Cause my data is huge so remove the dash sign in all data would take enormous of time.

Thanks!

**Comment by pratyakshsharma** [comment]
@imjalpreet can you suggest something here?

**Comment by thoithoi58** [comment]
I found the solution, just wrap the column with \"<column>"\. example "row(pipeline varchar,state varchar,stage varchar,\"execution-id\" varchar)".

closing this issue
