### ISSUE TITLE
[Native][Aggregate functions] Implement map_union_sum(x(K, V))

### ISSUE THREAD

**Issue by yzhang1991** [prestodb/presto#18857]
Ahana issue link: https://ahana-io.atlassian.net/browse/PDB-354

**Comment by yingsu00** [comment]
Are these issue Prestissimo or Velox?

**Comment by yzhang1991** [comment]
@yingsu00 The code should go to Velox but it's hard to manage GitHub issues in the Velox repo.

**Comment by yzhang1991** [comment]
https://github.com/facebookincubator/velox/pull/4476
