### ISSUE TITLE
find_first UDF cannot distinguish between NULL returned as a value and NULL returned because of no match

### ISSUE THREAD

**Issue by feilong-liu** [prestodb/presto#18899]
The find_first added in https://github.com/prestodb/presto/pull/18316 returns NULL if no match found. However, it cannot distinguish from the NULL returned as values.

For example, both `SELECT FIND_FIRST(ARRAY[NULL, 1], x->x is NULL) is NULL;` and `SELECT FIND_FIRST(ARRAY[1], x->x is NULL) is NULL;` returns true.

**Comment by kaikalur** [comment]
Let's just throw runtime error if the array has null
