### ISSUE TITLE
Presto reads the hive table encoded as utf8 and writes the hive table encoded as GBK to display as “？？？”

### ISSUE THREAD

**Issue by hff5570** [prestodb/presto#18890]
I use Presto readed the hive table encoded as utf8 and writes the hive table encoded as GBK to display as “？？？”,
<img width="809" alt="image" src="https://user-images.githubusercontent.com/104406233/210056357-b74c3662-895e-43fa-aa12-1532e6afde5b.png">

**Comment by prestored** [comment]
@hff5570 Can you please share the output of `select * from myhivetest.cfg_fund` ?

**Comment by tdcmeehan** [comment]
Looks like you're using Trino, please open an issue in trinodb/trino.  Thanks!
