### ISSUE TITLE
Presto Literal Interpreter wrongly interpreting fractional decimals

### ISSUE THREAD

**Issue by jaystarshot** [prestodb/presto#18918]
The literalInterpreter which is a visitor which visits a DecimalLiteral and converts it into a java **Number** object
Code
[ com.facebook.presto.sql.planner.LiteralInterpreter.LiteralVisitor#visitDecimalLiteral
](https://github.com/prestodb/presto/blob/6738e36f13601283ea2f7608bff1222f436dcf16/presto-main/src/main/java/com/facebook/presto/sql/planner/LiteralInterpreter.java#L219)
```
@Override
        protected Object visitDecimalLiteral(DecimalLiteral node, ConnectorSession context)
        {
            return Decimals.parse(node.getValue()).getObject();
        }
```

However Decimals.parse returns a `DecimalParseResult` which contains of an object and a **DecimalType**
This decimalType contains information like scale and precision. 
So "0.277" would be interpreted by Decimals.parse as 
```
Object = 277
DecimalType= {
     precision = x;
     scale = 3;
}
```
in literalInterpreter we are ignoring this scale thus we are wronly interpret this as 277 instead of 0.277.

**Comment by jaystarshot** [comment]
I tried to fix it but was stuck in what java Number class this decimalLiteral should represent.
Also Decimals.parse results in a Long and a BigInteger object, so we need to interpret them both in some way

**Comment by jaystarshot** [comment]
@martint  @Lukasz Osipiuk , since this was authored in [here](https://github.com/prestodb/presto/commit/ad2cc78922003c37d8bc0b187fc93c84cb26a809) . Do you have any leads?

**Comment by martint** [comment]
@jaystarshot, we no longer work on prestodb. We’ve made a lot of changes in Trino (https://github.com/trinodb/trino), so you might want to check out the code there to see if it fixes your issue. Or you can find me on the Trino slack if you want to discuss live and get more background on how that works.

**Comment by jaystarshot** [comment]
Closing this issue since this was a confusion on my side, the caller of the interpreter needs to handle fractional decimals
