### ISSUE TITLE
Provide Support for Keyword 'FETCH FIRST N ROWS ONLY' in Presto Query

### ISSUE THREAD

**Issue by sriramkotilil** [prestodb/presto#18935]
Currently Presto Query does not provide support for 'FETCH FIRST N ROWS ONLY' from a table. Currently in presto SQL Query similar functionality is available with the LIMIT Keyword. Creating this ticket to request for support for FETCH FIRST N ROWS ONLY keyword.

**Comment by skairali** [comment]
@sriramkotilil   We will soon come up with a PR for this issue

**Comment by skairali** [comment]
@sriramkotilil   This issue can be closed as the changes are in https://github.com/prestodb/presto/pull/18968

**Comment by sriramkotilil** [comment]
thanks @skairali . Closing issue.
