### ISSUE TITLE
Question: How to get a full list of presto functions from the code?

### ISSUE THREAD

**Issue by evyasonov** [prestodb/presto#18944]
How to get a full list of presto functions from the code of presto? (not by `show functions`)
Thanks in advance

**Comment by agrawalreetika** [comment]
@evyasonov `SHOW FUNCTIONS` should list all the functions I believe. Is there anything specific you are looking for?

**Comment by evyasonov** [comment]
@agrawalreetika 
I mean is it possible to get a list of presto function names without querying to presto or running presto? I need it for a testing purposes

**Comment by agrawalreetika** [comment]
@evyasonov I think most of the exsiting function would be under `presto-main/operator/scalar`, but I am not sure apart from looking in here or running `SHOW FUNCTIONS` there is any way to check list

**Comment by pratyakshsharma** [comment]
@evyasonov Does that help? In case you are looking for any more help from the community, let us know.

**Comment by evyasonov** [comment]
@agrawalreetika thank you for the answer! It's not exactly what I expected, but at least I doublechecked to make sure that it's not too complicated to get `show functions` output from the presto code itself.
