### ISSUE TITLE
hdfs is not supported as the external filesystem.

### ISSUE THREAD

**Issue by savani-ibm** [prestodb/presto#19026]
Presto-server 0.277
connector.name=hive-hadoop2
hive.metastore.uri=thrift://xx.xxx.xx.xx:9083
hive.config. resources=/data/hadoop/hadoop-3.3.3/etc/hadoop/core-site.xml, /data/hadoop/hadoop-3.3.3/etc/hadoop/hdfs-site.xml

cache.enabled=true
cache.type=ALLUXIO
cache.base-directory=fiLe:///data/cache/alLuxio
cache.alluxio.max-cache-size=6GB

We have installed Alluxio with no dir. On running any query on Presto, we see hdfs is not supported as the external filesystem.
I saw another issue opened for it. I wanted to know if there is a workaround or has this been fixed?

**Comment by majetideepak** [comment]
@savani-ibm We see a similar issue using S3 as well. A potential fix is here https://github.com/prestodb/presto/pull/18040 but has not been merged due to this comment https://github.com/prestodb/presto/pull/18040#issuecomment-1302206935

**Comment by savani-ibm** [comment]
@imjalpreet Any ideas on when would Alluxio add the fix to support HDFS and S3 as the external filesystem?

**Comment by apc999** [comment]
@savani-ibm  @majetideepak 
we are upgrading it from the Alluxio side to support hdfs/s3. you shall see this supported case soon
