### ISSUE TITLE
Add Maven dependency check for Common Vulnerability and Exposure (CVE)

### ISSUE THREAD

**Issue by wanglinsong** [prestodb/presto#19030]
This is necessary to ensure code quality and security.
Read https://owasp.org/www-project-dependency-check/ for more details.

**Comment by yzhang1991** [comment]
@wanglinsong Can you make a PR?

**Comment by Tejeshwarraju** [comment]
Please add this package so we continuously work and resolve common public CV's in timely manner. There a lot of security vulnerabilities open in the presto container which makes it unusable for us.

**Comment by wanglinsong** [comment]
This maven plugin will trigger build failure due to lots of CVE issues.
Should I just suppress them, for now, to NOT block the CI?
We then create separate issues to resolve them one by one or in batches.
@yzhang1991 @Tejeshwarraju

**Comment by yzhang1991** [comment]
It would be good to take a catalog of the failures and then suppress them. Open up separate issues for individual failures.

**Comment by wanglinsong** [comment]
https://github.com/prestodb/presto/security/dependabot

**Comment by wanglinsong** [comment]
PR is created https://github.com/prestodb/presto/pull/19047.
@Tejeshwarraju @yzhang1991
