### ISSUE TITLE
failure building presto native container

### ISSUE THREAD

**Issue by bikramSingh91** [prestodb/presto#19074]
I noticed that Velox's nightly job that builds presto-native container has started to fail:
https://app.circleci.com/pipelines/github/facebookincubator/velox/20329/workflows/ded539c0-f7f1-4d7b-814e-e834e4e886cf/jobs/127920

It seems to be failing at [this step](https://github.com/prestodb/presto/blob/5342eea0e42ba86df37b8a76e4d8f57dec8690eb/presto-native-execution/scripts/release-centos-dockerfile/Dockerfile#L57) and there was a recent change to it (https://github.com/prestodb/presto/pull/19035)
@Mionsz could you please take a look in case its related?
Thanks!

**Comment by Mionsz** [comment]
I will take a look at this - thanks for the info.

**Comment by Mionsz** [comment]
@bikramSingh91 yes you were right. I looked at the code and this made me realize that I sometimes make some stupid errors. I have added a PR with fix for this. This should allow to be usable by both types of users - ones with and without the ssh authentication for github:
[native] Fix for ssh-keyscan https://github.com/prestodb/presto/pull/19090

**Comment by mbasmanova** [comment]
@Mionsz Is this fixed now? I'm going to close the issue, but feel free to reopen if needed.

**Comment by Mionsz** [comment]
@mbasmanova thanks. yes this is fixed
