### ISSUE TITLE
presto cannot read hudi data where *.compaction.requested exist

### ISSUE THREAD

**Issue by cx707662950** [prestodb/presto#19107]
in method HudiSplitManager.getSplits-->getLatestFileSlicesBeforeOrOn-->isPendingCompactionScheduledForFileId,   I found with data file is doing compaction(state in REQUESTED or     COMPLETED,),  presto can't read any data,  is this a bug?

**Comment by wangxinalex** [comment]
found the same issue

**Comment by tdcmeehan** [comment]
Closing as duplicate
