### ISSUE TITLE
prestodb.io social icons in top right should be in full color

### ISSUE THREAD

**Issue by psbell-meta** [prestodb/presto#19179]
to match norms across similar websites, the social icons in the top right should either show colors, or show branded logo colors on mouse over at the least

**Comment by psbell-meta** [comment]
Will transfer issue to prestodb/prestodb.github.io once I have permissions

**Comment by rohanpednekar** [comment]
Discussed this item with @mcknightd earlier and the issue was background color of these social logos do not match the color of the hero header that we have today.

**Comment by steveburnett** [comment]
Looking at the icons in [prestodb.github.io/website/static/img](https://github.com/prestodb/prestodb.github.io/tree/source/website/static/img) the relevant icons appear to be transparent backgrounds. Maybe I'm misunderstanding the problem.

What needs to be done to resolve this?
