### ISSUE TITLE
Website should have an url redirect at /slack that redirects to latest Slack signup

### ISSUE THREAD

**Issue by psbell-meta** [prestodb/presto#19180]
For ease of invitation and consistency across future changes, we should have prestodb.io/slack redirect to slack signup, new links, articles, conference talks etc. can always reference this url which is easy to remember and share, and we can always ensure the redirect is to the correct page

**Comment by psbell-meta** [comment]
Will transfer issue to prestodb/prestodb.github.io once I have permissions

**Comment by rohanpednekar** [comment]
@mcknightd Do you think we can create this URL [prestodb.io/slack](http://prestodb.io/slack) and redirect to https://communityinviter.com/apps/prestodb/prestodb ?

**Comment by psbell-meta** [comment]
@mcknightd replaced with issue in proper repo https://github.com/prestodb/prestodb.github.io/issues/211

**Comment by mcknightd** [comment]
Yes, we can do this directly in the github editor pretty quickly. When you get time I'll walk you through it.
