### ISSUE TITLE
hive metastore cache is invalidate immediately

### ISSUE THREAD

**Issue by dwshmilyss** [prestodb/presto#19199]
Is there an API that can be invoked when hive metastore cache is used to invalidate the cache immediately. or when hive metastore was changed

**Comment by agrawalreetika** [comment]
@dwshmilyss I don't think any such API is available.
Refresh and TTL are controlled by catalog configuration - https://prestodb.io/blog/2021/02/04/raptorx#user-guide

**Comment by imjalpreet** [comment]
@dwshmilyss For now, there is a way to invalidate the cache via a JMX procedure but it will invalidate the whole cache. You can find more details in the documentation added as part of this PR: https://github.com/prestodb/presto/pull/19885

I have also created another issue to track the work for introducing a Presto Procedure that could do a more selective metastore cache invalidation: https://github.com/prestodb/presto/issues/20403
