### ISSUE TITLE
error queriyng on postgresql database

### ISSUE THREAD

**Issue by esubhashana** [prestodb/presto#19268]
when I trying to run select query on postgresql databse this error comes " SQL Error [65536]: Query failed (#20230327_060256_00024_tjeuy): DECIMAL precision must be in range [1, 38]"

**Comment by agrawalreetika** [comment]
@esubhashana Could you please share the full stack trace?
And also please share the DDL of the table and Query too.

**Comment by esubhashana** [comment]
@agrawalreetika this is my query "select* from mubasher_oms.m01_customer" .  I'm trying to query on EDB database using presto. But I used PostgreSQL connector for that. some of the queries working fine and some are not. The error message saying that the decimal precision going out of the range. But this queries working well in pgAdmin

**Comment by agrawalreetika** [comment]
Could you please share the DDL of your table?

**Comment by esubhashana** [comment]
CREATE TABLE IF NOT EXISTS ms.mer
(
    customer numeric(18,0) NOT NULL,
    account_id character varying(10) COLLATE pg_catalog."default",
    mtype numeric(2,0),
    customer_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    passport_number character varying(50) COLLATE pg_catalog."default",
    customer_id character varying(15) COLLATE pg_catalog."default",
    rrnumber character varying(100) COLLATE pg_catalog."default",
    reno character varying(100) COLLATE pg_catalog."default",
    _dob timestamp without time zone,
    tel character varying(50) COLLATE pg_catalog."default",
    ref_no character varying(50) COLLATE pg_catalog."default",
    _lice character varying(50) COLLATE pg_catalog."default",
    national_id character varying(50) COLLATE pg_catalog."default",
    cu_category numeric,
    mon_front_end numeric(1,0) DEFAULT 0,
    CONSTRAINT m_pk PRIMARY KEY (_id)
        USING INDEX TABLESPACE ev_ts
)   this is from original source and I cant get show cerate from presto because it gives same error as above

**Comment by imjalpreet** [comment]
Related Slack Thread: https://prestodb.slack.com/archives/CFNNEKQTX/p1679978971855629

**Comment by tdcmeehan** [comment]
Closing this as it was answered in the Slack thread, please open a new issue based on the outcome of that discussion.  Thank you!
