### ISSUE TITLE
[Authenticator plugin] Request for extraCredentials parameter support for customized password authenticator plugin

### ISSUE THREAD

**Issue by teeerrytan** [prestodb/presto#19289]
Hello team,

Currently, I am working on implementing a customized password authenticator plugin for my Presto project. Although I am aware that Presto supports the "**extraCredentials**" parameter for the JDBC connector, I am unsure of how to utilize this parameter in my plugin. Specifically, I would like to allow users to provide additional credentials for us to authenticate, such as "aws_access_key_id=myaccesskey,aws_secret_access_key=mysecretkey", in addition to their username and password.

If this feature is not currently supported, are there any plans to introduce it in the future?

Thank you for your assistance and support!

**Comment by tdcmeehan** [comment]
The extraCredentials are put into the `Identity` field of `Session` and may be used by plugins for authentication purposes.

**Comment by tdcmeehan** [comment]
Please reopen if this didn't fully answer your question, thanks!
