### ISSUE TITLE
Documentation for array function and map functions is ill formatted

### ISSUE THREAD

**Issue by piyushksx** [prestodb/presto#19329]
The documentation for functions `array_sort_desc`, `map_top_n_keys` and `map_top_n` is ill-formatted on the documentation pages:
https://prestodb.io/docs/current/functions/array.html
https://prestodb.io/docs/current/functions/map.html
![presto map](https://user-images.githubusercontent.com/40051253/230061942-78057dbe-5d4e-4a71-abbe-7daf5aabec36.png)
![presto array](https://user-images.githubusercontent.com/40051253/230061960-ba3ca06d-b033-4010-9b6c-3fad10cc4de1.png)

**Comment by piyushksx** [comment]
PR #19331 fixes this issue

**Comment by kidchemical** [comment]
Is any plans to update the description and examples? Can we update the description for the MAP_TOPN_XXX() functions to emphasize that the keys or values will be evaluated respectively to each function? Users have expressed that this is a bit unclear with the current description and provided example. 
<img width="741" alt="Screenshot 2023-07-12 at 11 35 06 AM" src="https://github.com/prestodb/presto/assets/59677741/85e9d227-fd0d-4035-af7b-2c43b64b9b72">
