### ISSUE TITLE
Getting Error as "Configuration property 'ldap.binddn' & 'ldap.bind-password' was not used"

### ISSUE THREAD

**Issue by vthorwat** [prestodb/presto#19467]
Hi Guys,

I am trying to configure **password-authenticator.properties** for presto where file contains below properties 

`password-authenticator.name=ldap`
`ldap.url=ldaps://adldap.rjil.ril.com:3269`
`ldap.user-bind-pattern=${USER}@ril.com`
`ldap.user-base-dn=DC=xxx,DC=com`
`ldap.bind-dn=CN=SVC_RTT,OU=SERVICE ACCT, DC=xxx,DC=com`
`ldap.bind-password=D$ve&9IL`
`ldap.group-auth-pattern=(&(objectClass=person)(sAMAccountName=${user})(|(CN=GALL--DEV--ADMINS,OU=DEVOU=GROUPS,OU=JIO_IT,OU=MEMBER SERVERS,DC=xxx,DC=com)))`

While starting presto with launcher i am getting below error 

<img width="1432" alt="Screenshot 2023-04-25 at 3 42 19 PM" src="https://user-images.githubusercontent.com/14247410/234248901-cb0c5344-af28-45a4-99c1-cfbe53da8588.png">

Anyone has faced this issue with the Latest presto - '0.280. version '

**Comment by prestored** [comment]
@vthorwat 
The properties you are using are not intended for presto and check below links that has the config where you need to enable https to use LDAP for authN.

https://github.com/prestodb/presto/blob/master/presto-product-tests/conf/presto/etc/singlenode-ldap.properties
