### ISSUE TITLE
TPC-DS Q54: Add support for casting decimal to integer

### ISSUE THREAD

**Issue by yzhang1991** [prestodb/presto#19518]
We observed the following error when running Q54 in the TPC-DS benchmark:
```
13:53:32 20:53:31.953 ERROR [pool-169-thread-1] i.p.b.d.l.LoggingBenchmarkExecutionListener - 
Query failed: q54 (1/3), execution error: Query failed (#20230426_205324_00760_d5pbt):
Invalid from type in casting:
DECIMAL(38,2) cast((presto.default.divide(sum, 50:DECIMAL(10,0))) as INTEGER)
```

This needs Prestissimo to support decimal to integer casting. Or we could rewrite the query to avoid this cast.

(Thanks @karteekmurthys, for the investigation and the writeup)

Integer to decimal casting was added in this issue: https://github.com/prestodb/presto/issues/19507 via this PR: https://github.com/facebookincubator/velox/pull/4383, which can be a good reference for this task.

**Comment by majetideepak** [comment]
PR here on the Velox side https://github.com/facebookincubator/velox/pull/5534

**Comment by yzhang1991** [comment]
There is a Velox PR for this already. Once the Velox PR lands, we can add the Prestissimo E2E test for this. @rrando901
