### ISSUE TITLE
TPC-DS Q02 and Q78: Support for ROUND(DECIMAL(38,2), INTEGER)

### ISSUE THREAD

**Issue by yzhang1991** [prestodb/presto#19519]
We have defined the `round` decimal function, but the signature expected here is `(Decimal, Integer)`.

<details><summary>Click here to expand the full error message</summary>
<p>
<pre>
Query failed: q02 (2/3), execution error: Query failed (#20230426_205601_00788_d5pbt):  Scalar function presto.default.round not registered with arguments: (DECIMAL(38,2), INTEGER). Found function registered with the following signatures:
13:56:02  ((DECIMAL(a_precision,a_scale)) -> DECIMAL(r_precision,r_scale))
13:56:02  ((double,integer) -> double)
13:56:02  ((bigint,integer) -> bigint)
13:56:02  ((smallint,integer) -> smallint)
13:56:02  ((integer,integer) -> integer)
13:56:02  ((tinyint,integer) -> tinyint)
13:56:02  ((real,integer) -> real)
13:56:02  ((tinyint) -> tinyint)
13:56:02  ((integer) -> integer)
13:56:02  ((bigint) -> bigint)
13:56:02  ((smallint) -> smallint)
13:56:02  ((real) -> real)
13:56:02  ((double) -> double)
</pre>
</p>
</details> 
<details><summary>The incoming plan has a integer as second argument:</summary>
<p>
<pre>
{
    "round<decimal(11,2)>": {
        "@type": "call",
        "sourceLocation": {
            "line": 39,
            "column": 4
        },
        "displayName": "round",
        "functionHandle": {
            "@type": "$static",
            "signature": {
                "name": "presto.default.round",
                "kind": "SCALAR",
                "typeVariableConstraints": [],
                "longVariableConstraints": [],
                "returnType": "decimal(11,2)",
                "argumentTypes": [
                    "decimal(10,2)",
                    "integer"
                ],
                "variableArity": false
            }
        }
    }
}
</pre>
</p>
</details> 

(Thanks @karteekmurthys, for the investigation and the writeup)

**Comment by karteekmurthys** [comment]
@yzhang1991 i'am working on this one. There are two round function definitions, Round(decimal) and round(decimal, integer), here second param is the number of decimal places you want to restrict the final value. We need to implement the second function type in velox.

**Comment by yzhang1991** [comment]
https://github.com/facebookincubator/velox/pull/4776

**Comment by yzhang1991** [comment]
Merged on June 20.
