### ISSUE TITLE
TPC-DS Q21: Could not communicate with the remote task

### ISSUE THREAD

**Issue by yzhang1991** [prestodb/presto#19520]
We still need an RCA for this failure.
<details><summary>Click to expand the full error message</summary>
<p>
<pre>
Query failed: q21 (3/3), execution error: Query failed (#20230426_171903_00134_d5pbt): Could not communicate with the remote task. The node may have crashed or be under too much load. This is probably a transient issue, so please retry your query in a few minutes. (10.128.8.202:8585)
10:20:04  17:20:04.412 INFO  [main] i.p.b.d.l.LoggingBenchmarkExecutionListener - Finished benchmark: presto/tpcds_sf100_parquet_varchar.cluster_small.run_72
10:20:04  java.util.concurrent.ExecutionException: org.springframework.web.client.HttpServerErrorException: 500 Internal Server Error
10:20:04  	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
10:20:04  	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
10:20:04  	at io.prestodb.benchto.driver.listeners.benchmark.BenchmarkStatusReporter.processCompletedFutures(BenchmarkStatusReporter.java:70)
10:20:04  	at io.prestodb.benchto.driver.execution.ExecutionDriver.executeBenchmarks(ExecutionDriver.java:128)
10:20:04  	at io.prestodb.benchto.driver.execution.ExecutionDriver.execute(ExecutionDriver.java:71)
10:20:04  	at io.prestodb.benchto.driver.DriverApp.main(DriverApp.java:80)
10:20:04  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:20:04  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
10:20:04  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:20:04  	at java.lang.reflect.Method.invoke(Method.java:498)
10:20:04  	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
10:20:04  	at java.lang.Thread.run(Thread.java:750)
</pre>
</p>
</details> 

If you are an Ahana employee, you can log in to https://ci.ahana.dev/job/oss-presto-pipelines/job/oss-release/job/pipeline-prestodb-benchto/61/consoleFull to check the full log for investigation.

**Comment by aditi-pandit** [comment]
Don't see this issue in pbench runs anymore.
