### ISSUE TITLE
Flaky test suite: presto-tests -P ci-only-resource-manager

### ISSUE THREAD

**Issue by miaoever** [prestodb/presto#19610]
This test suite turns to be flaky in the CI run, usually re-run helps to make it pass:

example failure: https://github.com/prestodb/presto/actions/runs/4931680148/jobs/8813964876?pr=19603#logs
```
Error:  Failures: 
Error:    TestDistributedClusterStatsResource.testClusterStatsLocalInfoReturn:214->waitForGlobalQueryViewInCoordinator:151 Timeout Global Query Count: 0 after 20000 ms
[INFO] 
Error:  Tests run: 5, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by mbasmanova** [comment]
CC: @majetideepak @tdcmeehan 

Tim, should we disable flaky tests?

**Comment by tdcmeehan** [comment]
Let me fix this test

**Comment by mbasmanova** [comment]
@tdcmeehan Thank you, Tim. Appreciate the help.

**Comment by swapsmagic** [comment]
Closing the issue given the fixes are merged.
