### ISSUE TITLE
Ci skips native tests:  Failed to execute goal maven-shade-plugin:3.1.1:shade on project presto-verifier

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#19636]
CI doesn't run native tests because of an error and shows status as "skipped" instead of "error" making it easy to miss.

https://
github.com/prestodb/presto/actions/runs/4954796801/jobs/8863620076?pr=19631

```
Error:  Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:3.1.1:shade (default) on project presto-verifier: Error creating shaded jar: Problem shading JAR /root/.m2/repository/it/unimi/dsi/fastutil/8.5.2/fastutil-8.5.2.jar entry it/unimi/dsi/fastutil/floats/Float2FloatRBTreeMap$1.class: java.io.IOException: No space left on device -> [Help 1]
```

<img width="962" alt="Screenshot 2023-05-12 at 7 25 00 AM" src="https://github.com/prestodb/presto/assets/27965151/5542fe9e-e92c-4d1d-9372-26fbfaded84f">

CC: @majetideepak @mshang816 @amitkdutta @vermapratyush

**Comment by mbasmanova** [comment]
The error seems to be:  java.io.IOException: No space left on device -> [Help 1]

Looks like we ran out of space on GitHub Actions machine.

@mshang816 Would you know how to fix this?

CC: @tdcmeehan

**Comment by mbasmanova** [comment]
CC: @isadikov @aditi-pandit

**Comment by mbasmanova** [comment]
Some context from @mshang816 

"i suppose it’s because the ccache occupied too much disk space (github action machine is quite limited) We had similar issue before the fix is to remove some unused space in the job."

**Comment by vermapratyush** [comment]
The logs from [this run](https://github.com/prestodb/presto/actions/runs/4951835769/jobs/8857342431?pr=19485) seems suspiciously large.
I have manually purged the logs, let's see if it is fixed.

**Comment by vermapratyush** [comment]
Rerunning a failed job: https://github.com/prestodb/presto/actions/runs/4956221622/jobs/8876527484
