### ISSUE TITLE
Refactor null handling and complex types for the native Parquet reader

### ISSUE THREAD

**Issue by yzhang1991** [prestodb/presto#19637]
sub task | Note | estimated weeks | prio(0-4) | estimated end time
-- | -- | -- | -- | --
Move read nulls out of prepareRead() | Group prepareNulls with other nulls handling logic | 1 | 1 | 4/30/23
Simplify rowsForPage |   | 2 | 1 | 4/30/23
Make rep/def reading not for the whole RG but just to the limit of a batch |   | 3 | 1 | 5/15/23
Remove SelectiveColumnReader::readsNullsOnly() | This was a hack for Parquet and can be removed | 1 | 1 |  
Remove the logic of presetting nulls |   | 1 | 1 | 5/30/23
Refactor the complex type read, removing the type checks |   | 4 | 1 | 5/31/23
Remove PageReader::visitorRows_ and other visitor related members |   | 1 | 1 | 6/1/23
Remove PageReader nulls arrays |    | 1 | 1 | 6/30/23
Simplify PageReader::prepareDataPage(). Too many hacks and if-else |   | 1 | 1 |  
Move functions from PageReader to Parquet Data and subtype ParquetData | PageReader is too big now and not typed. The type related decoding shall be in each typed ColumnReaders  | 1 | 2 |

**Comment by yingsu00** [comment]
This is not Presto issue, but Velox. Also the items in it may be more than what is just listed. Let's close it for now.
