### ISSUE TITLE
Flaky test: TestClusterSizeMonitor.testTimeoutWaitingForWorkers

### ISSUE THREAD

**Issue by vermapratyush** [prestodb/presto#19640]
The test `TestClusterSizeMonitor.testTimeoutWaitingForWorkers` fails with error message:
```
   TestClusterSizeMonitor.testTimeoutWaitingForWorkers:120 expected [true] but found [false]
```
Example job: https://github.com/prestodb/presto/actions/runs/4959088484/jobs/8872748341?pr=19607

**Comment by mbasmanova** [comment]
CC: @swapsmagic @tdcmeehan @majetideepak
