### ISSUE TITLE
Flaky CI job: continuous-integration/jenkins/pr-merge

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#19661]
This job is failing often. Can we fix or remove it?

> continuous-integration/jenkins/pr-merge — This commit cannot be built

CC: @amitkdutta @majetideepak

**Comment by mbasmanova** [comment]
CC: @tdcmeehan

**Comment by pranjalssh** [comment]
Cc @aditi-pandit This job is flaky a lot. Do you any insights?

**Comment by majetideepak** [comment]
@wanglinsong Can you please take a look?

**Comment by majetideepak** [comment]
Here is a failed PR and run
https://github.com/prestodb/presto/pull/19642
https://ci.ahana.dev/blue/organizations/jenkins/prestodb%2Fpresto/detail/PR-19642/2/pipeline

**Comment by wanglinsong** [comment]
That specific failure was cause by my manual repo scan, when adding a new repo (testing-mysql-server) into the org. That triggered lots unnecessary runs, then I canceled them.

**Comment by wanglinsong** [comment]
I could offer some options to rerun the pipeline
1. type 'rerun' in PR comment
2. ask someone having 'run' access to rerun it
3. ping me directly

**Comment by mbasmanova** [comment]
@wanglinsong If this pipeline cannot run reliably and requires re-runs, then let's not run it on PRs.

**Comment by majetideepak** [comment]
@wanglinsong let's enable it only on the master branch. I don't think this CI tests needs to be run on every PR.

**Comment by majetideepak** [comment]
@wanglinsong confirmed that this job is not part of a PR anymore. I looked at a recent PR https://github.com/prestodb/presto/pull/19682 and can confirm this as well.

**Comment by majetideepak** [comment]
Thanks @wanglinsong

**Comment by mbasmanova** [comment]
Thank you, @majetideepak  and @wanglinsong
