### ISSUE TITLE
Test failure: TestPrestoSparkNativeGeneralQueries#testUnionAll()

### ISSUE THREAD

**Issue by miaoever** [prestodb/presto#19665]
Test failure: TestPrestoSparkNativeGeneralQueries#testUnionAll() failed on VeloxRuntimeError: type_->kindEquals(vector.type()) Type mismatch: VARCHAR vs. INTEGER

**Comment by mbasmanova** [comment]
Might be related to https://github.com/facebookincubator/velox/pull/4921

**Comment by miaoever** [comment]
https://github.com/prestodb/presto/pull/19630 should fix this issue.
