### ISSUE TITLE
codeowners file has an error

### ISSUE THREAD

**Issue by davidradl** [prestodb/presto#19685]
If you go to this file https://github.com/prestodb/presto/blob/master/CODEOWNERS , you will see that there is an error saying 

```
Unknown owner on line 5: make sure @sdruzkin exists and has write access to the repository
/presto-orc @sdruzkin @prestodb/committers 
```

**Comment by tdcmeehan** [comment]
Once @sdruzkin accepts his invitation to the repo this will be fixed.

**Comment by davidradl** [comment]
@tdcmeehan other open source projects (Egeria and Atlas) have the new committer add their new line into the file as part of the process and to prove they have write access. My suggestion would be to adopt this process for Presto and avoid having errors on important pages as business-as-usual.

**Comment by sdruzkin** [comment]
> Once @sdruzkin accepts his invitation to the repo this will be fixed.

I did not see the invitation. Is it possible to send it again?

**Comment by tdcmeehan** [comment]
@davidradl great idea--we'll try this next time!

@sdruzkin either you have already accepted, since the codeowners file is now valid (indicating you already have write permissions), or it didn't require your approval.
