### ISSUE TITLE
Implement HIVE ACID table support

### ISSUE THREAD

**Issue by damiencarol** [prestodb/presto#1970]
HIVE 0.14 introduce ACID table.

Info in HIVE wiki : [Hive Transactions](https://cwiki.apache.org/confluence/display/Hive/Hive+Transactions)

These tables are not compatible with existing code because directory layout is different.
These tables will have subdirectories for different versions (bases) and addendum of the data.
##### More than words, an example

For example for a table `foo` : (command in HIVE)

```
0: jdbc:hive2://nc-h04:10000/casino> dfs -ls hdfs://nc-h04/user/hive/warehouse/casino.db/foo;
+----------------------------------------------------------------------------------------------------------------------------+--+
|                                                         DFS Output                                                         |
+----------------------------------------------------------------------------------------------------------------------------+--+
| Found 1 items                                                                                                              |
| drwxr-xr-x   - hduser supergroup          0 2014-11-12 14:53 hdfs://nc-h04/user/hive/warehouse/casino.db/foo/base_0000077  |
+----------------------------------------------------------------------------------------------------------------------------+--+
2 rows selected (0.065 seconds)
```

If I add some values OR modify it with _UPDATE_ or _DELETE_, I have that addendum directories :

```
0: jdbc:hive2://nc-h04:10000/casino> dfs -ls hdfs://nc-h04/user/hive/warehouse/casino.db/foo;
+-------------------------------------------------------------------------------------------------------------------------------------+--+
|                                                             DFS Output                                                              |
+-------------------------------------------------------------------------------------------------------------------------------------+--+
| Found 4 items                                                                                                                       |
| drwxr-xr-x   - hduser supergroup          0 2014-11-12 14:53 hdfs://nc-h04/user/hive/warehouse/casino.db/foo/base_0000077           |
| drwxr-xr-x   - hduser supergroup          0 2014-11-14 11:58 hdfs://nc-h04/user/hive/warehouse/casino.db/foo/delta_0000079_0000079  |
| drwxr-xr-x   - hduser supergroup          0 2014-11-14 11:58 hdfs://nc-h04/user/hive/warehouse/casino.db/foo/delta_0000081_0000081  |
| drwxr-xr-x   - hduser supergroup          0 2014-11-14 11:58 hdfs://nc-h04/user/hive/warehouse/casino.db/foo/delta_0000082_0000082  |
+-------------------------------------------------------------------------------------------------------------------------------------+--+
5 rows selected (0.017 seconds)
```

A quick fix could be to only use the last "base" of the table.
##### What is "ACID table" ?
1. A table with `transactional` table property set to value `true` (lower case is important)
##### What we can do, a simple algorithm
1. We can easily know if a table are ACID with `transactional` table property
2. If a HIVE table is ACID, we can consider only the last consolidated `base`

```
if (table have `transactional` property set to true)
{
  1. get list of directories like "base_???????" (7 digits)
  2. Only consider the last one instead of the root directory
}
```

**Comment by damiencarol** [comment]
@dain I saw more detailed info on the new ORC site: http://orc.apache.org/docs/acid.html

**Comment by francescopalmiotto** [comment]
IMHO supporting Hive ACID tables is a must-have feature.
AFAIK there's no query engine around that can query them, Presto could be the first!

**Comment by colino** [comment]
I agree, it will be very useful to support Hive ACID tables

**Comment by yuananf** [comment]
@dain We definitely need this one. Are you working on this?

**Comment by yuananf** [comment]
Any update on this issue?

**Comment by youxinren** [comment]
Very useful feature

**Comment by chandrasharma28** [comment]
Hello All, Any updates on enabling this feature?

**Comment by dain** [comment]
This is a very complicated feature and we haven't seen any usage of this in production installations, which is why we haven't put any time into this.

**Comment by vbsoni** [comment]
Hi, 

We are trying to implement a scenarios where,

Step1: One time full data will be loaded into HIVE Table.

Step2: New data will be inserted in to HIVE Table.

Step3: Rows will be deleted from HIVE Table.

Repeat step 2 and step 3 every 4 hours for 200 different tables.

Select data from HIVE table.

We have tried using presto and hive but hitting several errors.

Can anyone please guide us, what is the best way to do with presto + hive?

Regards,
Vicky

**Comment by sajjoseph** [comment]
Poking to see if anyone else is still waiting for  this feature. At my company, we started using Hive ACID and we are eagerly waiting for Presto to support this feature.

Thanks,
Saj

**Comment by oliversavio** [comment]
We'd love to have this feature as well. In the meantime does anyone know any workarounds.

**Comment by parisni** [comment]
There is no workaround right now.

Hive is becoming
Spark [see jira](https://issues.apache.org/jira/browse/SPARK-15348) not fully compliant with ACID tables, however, as a workaround, it is able to read after major compaction. By mean the resulting folder is as  @damiencarol  described 4 years ago.

@dain  this would be of great help if presto could read the base folder as describe in the @damiencarol  .

I am not sure if there is a clear documentation of how metastore, and full process works but if you need some help to implement that, I guess community should collect here some information

**Comment by cskbhatt** [comment]
Hello,  Is there any plan to resolve this issue?
We are migrating data from Oracle RDBMS to Hadoop and Hive ACID is key feature required to support ( CDC - Change Data Capture) 
It would be a great help if presto can read data from Hive ACID tables.  

Thank you

**Comment by dain** [comment]
@cskbhatt at FB we don't use ACID tables (our partitions are immutable), so we are unlikely to work on this any time soon.  We would welcome anyone from the community to drive this feature.

**Comment by kokosing** [comment]
@cskbhatt at Starburst we were asked several times for this, so it is possible that we might want to take this some day. However the time-frame is very unclear. If you like you can contact us to get to know more details about our plans for this feature.
