### ISSUE TITLE
PredicatePushdown rule adds un-needed ProjectNode's

### ISSUE THREAD

**Issue by aaneja** [prestodb/presto#19749]
While debugging poor join-orders for TPCDS Q-72, I observed that join-reordering was broken because of the presence of extra `ProjectNode`s that are added during predicate pushdown.
Consider this log snippet from [LogPlanTreeOptimizer](https://github.com/aaneja/presto/commit/2fe4e6c681ad852b1f0d1e6d8f1074d6eba9ef5f) (which logs a minimal plan tree at different stages of the optimization) for the query :

```
explain
SELECT ss_sold_date_sk
FROM store_sales,
    customer,
    date_dim
WHERE ("ss_sold_date_sk" = "d_date_sk")
    AND ss_sold_date_sk IS NOT NULL
    AND d_date_sk IS NOT NULL
    AND ("c_customer_sk" = "ss_customer_sk")
    AND c_customer_sk IS NOT NULL
    AND ss_customer_sk IS NOT NULL;
```

### Log snippet

```
2023-05-29T17:28:28.346+0530	INFO	Query-20230529_115825_00001_8jg8c-1387	com.facebook.presto.sql.planner.optimizations.LogPlanTreeOptimizer	------ Before predicatePushDown (right after connector optimization)
2023-05-29T17:28:28.347+0530	INFO	Query-20230529_115825_00001_8jg8c-1387	com.facebook.presto.sql.planner.optimizations.LogPlanTreeOptimizer	Plan :
join (INNER), Outputs([ss_sold_date_sk]):
    join (INNER), Outputs([ss_sold_date_sk]):
        scan (HiveTableHandle{schemaName=tpcds_sf100_orc, tableName=store_sales, analyzePartitionValues=Optional.empty}) Constraints [Current (Optional[{ss_sold_date_sk:bigint:0:REGULAR=com.facebook.presto.common.predicate.Domain@41397f63, ss_customer_sk:bigint:3:REGULAR=com.facebook.presto.common.predicate.Domain@41397f63}]), Enforced(Optional[{}])]
        scan (HiveTableHandle{schemaName=tpcds_sf100_orc, tableName=customer, analyzePartitionValues=Optional.empty}) Constraints [Current (Optional[{c_customer_sk:bigint:0:REGULAR=com.facebook.presto.common.predicate.Domain@41397f63}]), Enforced(Optional[{}])]
    scan (HiveTableHandle{schemaName=tpcds_sf100_orc, tableName=date_dim, analyzePartitionValues=Optional.empty}) Constraints [Current (Optional[{d_date_sk:bigint:0:REGULAR=com.facebook.presto.common.predicate.Domain@41397f63}]), Enforced(Optional[{}])]

2023-05-29T17:28:28.352+0530	INFO	Query-20230529_115825_00001_8jg8c-1387	com.facebook.presto.sql.planner.optimizations.LogPlanTreeOptimizer	------ After predicatePushDown (right after connector optimization)
2023-05-29T17:28:28.353+0530	INFO	Query-20230529_115825_00001_8jg8c-1387	com.facebook.presto.sql.planner.optimizations.LogPlanTreeOptimizer	Plan :
project, Assignments ({ss_sold_date_sk=ss_sold_date_sk}), Outputs ([ss_sold_date_sk]):
    join (INNER), Outputs([ss_sold_date_sk, d_date_sk]):
        project, Assignments ({ss_sold_date_sk=ss_sold_date_sk}), Outputs ([ss_sold_date_sk]):
            project, Assignments ({ss_sold_date_sk=ss_sold_date_sk}), Outputs ([ss_sold_date_sk]):
                join (INNER), Outputs([ss_sold_date_sk, ss_customer_sk, c_customer_sk]):
                    project, Assignments ({ss_sold_date_sk=ss_sold_date_sk, ss_customer_sk=ss_customer_sk}), Outputs ([ss_sold_date_sk, ss_customer_sk]):
                        filter (predicate = AND(not(IS_NULL(ss_sold_date_sk)), not(IS_NULL(ss_customer_sk))))
                            scan (HiveTableHandle{schemaName=tpcds_sf100_orc, tableName=store_sales, analyzePartitionValues=Optional.empty}) Constraints [Current (Optional[{ss_sold_date_sk:bigint:0:REGULAR=com.facebook.presto.common.predicate.Domain@41397f63, ss_customer_sk:bigint:3:REGULAR=com.facebook.presto.common.predicate.Domain@41397f63}]), Enforced(Optional[{}])]
                    project, Assignments ({c_customer_sk=c_customer_sk}), Outputs ([c_customer_sk]):
                        filter (predicate = not(IS_NULL(c_customer_sk)))
                            scan (HiveTableHandle{schemaName=tpcds_sf100_orc, tableName=customer, analyzePartitionValues=Optional.empty}) Constraints [Current (Optional[{c_customer_sk:bigint:0:REGULAR=com.facebook.presto.common.predicate.Domain@41397f63}]), Enforced(Optional[{}])]
        project, Assignments ({d_date_sk=d_date_sk}), Outputs ([d_date_sk]):
            filter (predicate = not(IS_NULL(d_date_sk)))
                scan (HiveTableHandle{schemaName=tpcds_sf100_orc, tableName=date_dim, analyzePartitionValues=Optional.empty}) Constraints [Current (Optional[{d_date_sk:bigint:0:REGULAR=com.facebook.presto.common.predicate.Domain@41397f63}]), Enforced(Optional[{}])]
```

### Observations

1.  The plan initially had constraints pushed down to the `scan` nodes
2.  After `PredicatePushdown` rule is applied, these constraints were pulled back up and re-added as `Filter` s. This is because [EffectivePredicateExtractor](https://github.com/prestodb/presto/blob/087f4ff9e866594923fa73f889445e0807df0dde/presto-main/src/main/java/com/facebook/presto/sql/planner/EffectivePredicateExtractor.java#L210-L214) pulls them out of TableScan node's `currentConstraint` (**Bug 1**). ~~IMO this is because we incorrectly store [these pushed down predicates](https://github.com/prestodb/presto/blob/ac3e41e09050fce14190394135c0706ab2a9f067/presto-hive/src/main/java/com/facebook/presto/hive/rule/HiveFilterPushdown.java#L450-L451) in  `TableNode`s `currentConstraint` instead of `enforcedConstraint`~~ Update: On furthur examination this looks like expected behavior
3.  Additionally, we observe that `ProjectNode`s were added during the pushdown of these extracted filters - in this case we have identity assignments that serve no-purpose (identity assignments & outputs). While we have a rule `RemoveRedundantIdentityProjections` that don't eliminate the ProjectNode's altogether (**Bug 2**) (see [gist](https://gist.github.com/aaneja/76c3e38890605ba850a6ca9088a7522d) for details on junk ProjectNode removal log)

### Result
Because of the extra ProjectNode's, [ReorderJoins](https://github.com/prestodb/presto/blob/9ba89b216e9f6db500389777d95ed7633c4f3d45/presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/ReorderJoins.java#L552-L562) is restricted to calculating 2-way join's and we get syntactic join order

**Comment by yingsu00** [comment]
@aaneja In my understanding, `PredicatePushdown` rule is to push the FilterNode as deep as possible, but it does not push the FilterNode into TableScanNode.  Take this simple query for example
```
select * from lineitem l, orders o where l.orderkey=o.orderkey and l.partkey < 10;
```
The input to is 
Output -> Filter (l.orderkey=o.orderkey and l.partkey < 10)
            -> Join 
                -> Scan right
                -> Scan left
And output is
Output -> Join 
            -> Filter( l.partkey < 10) ->  Scan right
            -> Scan left

`ApplyConnectorOptimizations` rule is ran after `PredicatePushdown`, in which `HiveFilterPushdown` would merge the FilterNode with TableScanNode.  At the stage of `PredicatePushdown`, the planner does not know the connector's capability on pushing down filter to TableScan yet. `HiveFilterPushdown` would determine if the FilterNode can be pushed into TableScan while running `ApplyConnectorOptimizations`. `HiveFilterPushdown.pushdownFilter` returns the `ConnectorPushdownFilterResult`, which contains `unenforcedConstraint` that cannot be pushed to TableScanNode. If `unenforcedConstraint` is empty, then the FilterNode would be removed and the TableScan can handle all filters.

So it seems to me adding the FilterNode in `PredicatePushdown` is ok, but the ProjectNode is bad. Have you verified if not adding identity projection helps? You had an internal PR doing that, what happens with it? Were there any bad consequences?

**Comment by aaneja** [comment]
>HiveFilterPushdown.pushdownFilter returns the ConnectorPushdownFilterResult, which contains unenforcedConstraint that cannot be pushed to TableScanNode. If unenforcedConstraint is empty, then the FilterNode would be removed and the TableScan can handle all filters.  

Yes, but [HiveFilterPushdown.pushdownFilter](https://github.com/prestodb/presto/blob/master/presto-hive/src/main/java/com/facebook/presto/hive/rule/HiveFilterPushdown.java#L450-L451) stores the filter in the TableNode's `currentConstraint` instead of the `enforcedConstraint`. Because of this, the [EffectivePredicateExtractor](https://github.com/prestodb/presto/blob/087f4ff9e866594923fa73f889445e0807df0dde/presto-main/src/main/java/com/facebook/presto/sql/planner/EffectivePredicateExtractor.java#L210-L214) re-calculates already pushed down filters when visiting the TableScan node and re-adds them.  

This, to me, is a bug

**Comment by aaneja** [comment]
>Have you verified if not adding identity projection helps? You had an internal PR doing that, what happens with it? Were there any bad consequences?  

So far with the fix #19766 I see
- Join space opens up and join order of plans for TCPH/TPCDS matches those of plans with filter pushdown/dynamic filtering turned off
- Basic smoke testing doesn't show correctness issues

I will do a full verifier pass and report back

**Comment by yingsu00** [comment]
> Yes, but [HiveFilterPushdown.pushdownFilter](https://github.com/prestodb/presto/blob/master/presto-hive/src/main/java/com/facebook/presto/hive/rule/HiveFilterPushdown.java#L450-L451) stores the filter in the TableNode's currentConstraint instead of the enforcedConstraint. Because of this, the [EffectivePredicateExtractor](https://github.com/prestodb/presto/blob/087f4ff9e866594923fa73f889445e0807df0dde/presto-main/src/main/java/com/facebook/presto/sql/planner/EffectivePredicateExtractor.java#L210-L214) re-calculates already pushed down filters when visiting the TableScan node and re-adds them.

When does this happen? Is it in PredicatePushdown that is invoked after HiveFilterPushdown has merged the filter node into table scan? If this is the case, then yes, it sounds like a bug that makes the planner doing repeating work. But I suspect there are many other cases (planner doing repeating work) like this . Will you be able to create a sub issue and submit a fix that push the predicate into enforcedConstraint instead of currentConstraint? If this doesn't expose more issues then it should be good.

cc @arunthirupathi @rschlussel

**Comment by aaneja** [comment]
Yes, the fix is [this](https://github.com/prestodb/presto/pull/19766/commits/5b6a7461c627f162fcaf308d40d1a9a2d4dbecb2) commit in #19766

**Comment by aaneja** [comment]
`Bug #2` was fixed by https://github.com/prestodb/presto/pull/19969
