### ISSUE TITLE
[raptor] Is there a mechanism for fragment result cache to cache the result of JoinNode 

### ISSUE THREAD

**Issue by Hwloser** [prestodb/presto#19790]
## Is there a mechanism for fragment result cache to cache the result of JoinNode 

![image](https://github.com/prestodb/presto/assets/54064811/7cb4edc7-eb23-46da-b2e3-4f9f7d3a133d)

## problems

In real production environments, most compurtations are repeated with JoinNode. If there is no cache for join calculations, simple group by quueries are make no sense.

**Comment by tdcmeehan** [comment]
Please re-open if you have further questions!
