### ISSUE TITLE
Refresh partition information in batches

### ISSUE THREAD

**Issue by martint** [prestodb/presto#1981]
Currently, the partition cache in CachingHiveMetastore is accessed via `getAll`, which does a single request to the metastore for each call. Once the entries are in the cache, though, the background refresh task fetches them one at a time.

We should update the implementation to batch the background requests to refresh based on time/count and issue a single request to the metastore.

**Comment by lvijay** [comment]
Based on comments in #1995, this can be closed, methinks.
