### ISSUE TITLE
Unify development and contribution documentation

### ISSUE THREAD

**Issue by tdcmeehan** [prestodb/presto#19834]
We have a few sources that help newcomers contribute to the project.

The following give higher level guidance on how to contribute:

* The [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md) file
* [The review and commit guidelines](../wiki/Review-and-Commit-guidelines)
* [This helpful document](https://docs.google.com/document/d/1PF2OkyRNQ7kgyLKK4aLqg78LSLjQxzTII6wg4yMTig8/edit#)

We also have the following code contribution guidelines that give more detailed help on how to build and write the code itself:

* The [README.md](../blob/master/README.md) file 
* [The Presto development guidelines](../wiki/Presto-Development-Guidelines)

We should consider either unifying the two classes of documentation into just two documents, or even consider flattening them into a single document (perhaps CONTRIBUTING.md).  The current situation is our documentation is spread out, which makes it difficult to ensure newcomers read all the appropriate documentation prior to contribution.  It also makes it difficult to know where to update the documentation when it needs to be updated.

**Comment by VishnuSanal** [comment]
Hi, is this still being worked upon? If not, I'd like to work on this. I'm a bit new here & looking forward to contributing. :)

**Comment by tdcmeehan** [comment]
Please go for it, I would eagerly await this contribution @VishnuSanal!
