### ISSUE TITLE
[native] Enable [-Werror,-Wreorder-ctor] compiler flags

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#19940]
It would be nice to catch errors like the following before merging the PR.

```
 error: field 'queryCtx_' will be initialized after field 'pool_' [-Werror,-Wreorder-ctor]
```

CC: @amitkdutta @vermapratyush @majetideepak

**Comment by majetideepak** [comment]
@mbasmanova we do treat warnings as errors in CI.
See https://github.com/prestodb/presto/blob/master/.circleci/continue_config.yml#L97

Did you see a PR that did not catch  the error you mentioned?

**Comment by mbasmanova** [comment]
@majetideepak Yes, there were 2 PRs that got merged, but later failed in internal CI. Here is a fix for these: https://github.com/prestodb/presto/pull/19941

**Comment by mbasmanova** [comment]
These 2 PRs are: https://github.com/prestodb/presto/pull/19906 and https://github.com/prestodb/presto/pull/19923

**Comment by majetideepak** [comment]
@mshang816 Agree. clang is probably better since it provides sanitizers.
We have an ongoing discussion on this for Velox. We can align with that effort.
https://github.com/facebookincubator/velox/discussions/5131

**Comment by majetideepak** [comment]
I enabled `-Wall` here https://github.com/prestodb/presto/pull/19945 and can see the reorder failure
https://app.circleci.com/pipelines/github/prestodb/presto/4078/workflows/ec91a99d-00bc-424d-95f3-acd0b2457869/jobs/7954
Let's add that.
We can switch the build to clang and keep one build for GCC for compatibility.
