### ISSUE TITLE
[Native][high-priority] ci/circleci: linux-presto-e2e-tests are failing with high rate

### ISSUE THREAD

**Issue by majetideepak** [prestodb/presto#19942]
The test failures seem to be due to Prestissimo node failures.
We need to investigate this issue as a priority.

**Comment by frankobe** [comment]
@majetideepak I am investigating the failure now

**Comment by frankobe** [comment]
I opened 4 PR runs to verify the robustness

https://github.com/prestodb/presto/pull/19946
https://github.com/prestodb/presto/pull/19947
https://github.com/prestodb/presto/pull/19948
https://github.com/prestodb/presto/pull/19949

**Comment by majetideepak** [comment]
Resolved by https://github.com/prestodb/presto/pull/19946
