### ISSUE TITLE
[Native] Add JWT for internal communication

### ISSUE THREAD

**Issue by ashokku2022** [prestodb/presto#19962]
Christian has created this issue on June 12 and working on it. It has also been tagged as Prestissimo Gap. June 19-23 he is on vacation.

https://github.com/prestodb/presto/issues/19861

@czentgr

**Comment by majetideepak** [comment]
@ashokku2022 Can we close this issue since https://github.com/prestodb/presto/issues/19861 is tracking this work?

**Comment by ashokku2022** [comment]
@majetideepak sure, let me close it, thanks for pointing out!
