### ISSUE TITLE
[native] Refactor registration of DWRF and Parquet readers in PrestoServer.cpp

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#19968]
DWRF and Parquet readers are used only by the Hive Connector, yet these are registered unconditionally in presto-native-execution/presto_cpp/main/PrestoServer.cpp even when HiveConnector is not registered. It would be nice to refactor this to move registration of DWRF and Parquet readers into HiveConnector registration.

CC: @majetideepak 

See https://github.com/prestodb/presto/pull/19966#issuecomment-1604274061

**Comment by majetideepak** [comment]
Resolved in https://github.com/prestodb/presto/pull/20321
