### ISSUE TITLE
Error while deploying Presto release on arm64

### ISSUE THREAD

**Issue by imjalpreet** [prestodb/presto#19981]
Error message: 
```
Caused by: java.lang.RuntimeException: library not found: /nativelib/Linux-aarch64/libhadoop.so
	at com.facebook.presto.hadoop.HadoopNative.loadLibrary(HadoopNative.java:88)
```

To fix this, we need to release a new version of https://github.com/prestodb/presto-hadoop-apache2 and upgrade the version in Presto. Latest changes in presto-hadoop-apache2 have added the native libs required for Linux and MacOS aarch64.

**Comment by majetideepak** [comment]
@wanglinsong FYI, an issue related to release.

**Comment by wanglinsong** [comment]
@tdcmeehan can you publish 2.7.4-12 into maven central?

**Comment by wanglinsong** [comment]
2.7.4-12 is released
