### ISSUE TITLE
[native] Protobuf headers included from velox cause build issues

### ISSUE THREAD

**Issue by czentgr** [prestodb/presto#20022]
Prestissimo requires the Protobuf package (CMakeLists.txt - `find_package(Protobuf REQUIRED)`).
The issue is that the system protobuf version can be upgraded to a version that causes link failures during the build

The protobuf dependencies changed for Mac users recently. This meant that protobuf v23 was the system protobuf. This version of protobuf introduced a new dependency on `abseil` objects resulting in link errors like these:
```
[ 92%] Building CXX object presto_cpp/main/CMakeFiles/presto_server.dir/PrestoMain.cpp.o
[ 92%] Linking CXX executable presto_server
Undefined symbols for architecture arm64:
  "absl::lts_20230125::log_internal::LogMessage::CopyToEncodedBuffer(std::__1::basic_string_view<char, std::__1::char_traits<char>>, absl::lts_20230125::log_internal::LogMessage::StringType)", referenced from:
      absl::lts_20230125::log_internal::LogMessage& absl::lts_20230125::log_internal::LogMessage::operator<<<48>(char const (&) [48]) in libvelox_dwio_dwrf_writer.a(ColumnWriter.cpp.o)
      absl::lts_20230125::log_internal::LogMessage& absl::lts_20230125::log_internal::LogMessage::operator<<<59>(char const (&) [59]) in libvelox_dwio_dwrf_writer.a(ColumnWriter.cpp.o)
      absl::lts_20230125::log_internal::LogMessage& absl::lts_20230125::log_internal::LogMessage::operator<<<19>(char const (&) [19]) in libvelox_dwio_dwrf_writer.a(ColumnWriter.cpp.o)
      absl::lts_20230125::log_internal::LogMessage& absl::lts_20230125::log_internal::LogMessage::operator<<<48>(char const (&) [48]) in libvelox_dwio_dwrf_writer.a(StatisticsBuilder.cpp.o)
      absl::lts_20230125::log_internal::LogMessage& absl::lts_20230125::log_internal::LogMessage::operator<<<59>(char const (&) [59]) in libvelox_dwio_dwrf_writer.a(StatisticsBuilder.cpp.o)
      absl::lts_20230125::log_internal::LogMessage& absl::lts_20230125::log_internal::LogMessage::operator<<<19>(char const (&) [19]) in libvelox_dwio_dwrf_writer.a(StatisticsBuilder.cpp.o)
      absl::lts_20230125::log_internal::LogMessage& absl::lts_20230125::log_internal::LogMessage::operator<<<48>(char const (&) [48]) in libvelox_dwio_dwrf_common.a(dwrf-proto-wrapper.cpp.o)
      ...
```

In theory, protobuf is needed by Velox and Velox can build its bundled version that removes the issue of system included versions that are not compatible with the build at this time. The system version can change at any time due to local dependencies on the system the build is run on.

The CMakeLists.txt of prestissimo, however, requires the protobuf package and therefore must rely on a system install to pass this check. Though it is not clear why it requires the header as it appears not to be using the library itself.
If no system protobuf is present and the velox bundled version is used (assuming the package check is bypassed) then the prestissimo build fails because it is not finding the bundled protobuf header files.

Error:
```
[817/837] Building CXX object presto_cpp/main/types/CMakeFiles/presto_types.dir/PrestoToVeloxQueryPlan.cpp.o
FAILED: presto_cpp/main/types/CMakeFiles/presto_types.dir/PrestoToVeloxQueryPlan.cpp.o 
ccache /Library/Developer/CommandLineTools/usr/bin/c++ -DBOOST_ATOMIC_DYN_LINK -DBOOST_ATOMIC_NO_LIB -DBOOST_CONTEXT_DYN_LINK -DBOOST_CONTEXT_NO_LIB -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_FILESYSTEM_NO_LIB -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_REGEX_DYN_LINK -DBOOST_REGEX_NO_LIB -DBOOST_SYSTEM_DYN_LINK -DBOOST_SYSTEM_NO_LIB -DBOOST_THREAD_DYN_LINK -DBOOST_THREAD_NO_LIB -DFMT_LOCALE -DFOLLY_HAVE_INT128_T=1 -DGFLAGS_IS_A_DLL=0 -I/Users/czentgr/gitspace/presto/presto-native-execution/. -I/Users/czentgr/gitspace/presto/presto-native-execution/velox -I/Users/czentgr/gitspace/presto/presto-native-execution/velox/velox/external/xxhash -I/Users/czentgr/gitspace/presto/presto-native-execution/_build/debug/velox -I/Users/czentgr/gitspace/presto/presto-native-execution/_build/debug -I/Users/czentgr/gitspace/presto/presto-native-execution/_build/debug/_deps/xsimd-src/include -isystem /opt/homebrew/include -isystem /usr/local/include/antlr4-runtime -isystem /usr/local/include -isystem /opt/homebrew/opt/openssl@1.1/include -isystem /usr/local/include/proxygen -isystem /Users/czentgr/gitspace/presto/presto-native-execution/_build/debug/_deps/gtest-src/googletest/include -isystem /opt/homebrew/opt/openssl@3/include -isystem /Users/czentgr/gitspace/presto/presto-native-execution/_build/debug/_deps/gtest-src/googletest -mcpu=apple-m1+crc -std=c++17 -fvisibility=hidden -Werror -Wno-nullability-completeness -Wno-deprecated-declarations -Wreorder -g -std=gnu++17 -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk -MD -MT presto_cpp/main/types/CMakeFiles/presto_types.dir/PrestoToVeloxQueryPlan.cpp.o -MF presto_cpp/main/types/CMakeFiles/presto_types.dir/PrestoToVeloxQueryPlan.cpp.o.d -o presto_cpp/main/types/CMakeFiles/presto_types.dir/PrestoToVeloxQueryPlan.cpp.o -c /Users/czentgr/gitspace/presto/presto-native-execution/presto_cpp/main/types/PrestoToVeloxQueryPlan.cpp
In file included from /Users/czentgr/gitspace/presto/presto-native-execution/presto_cpp/main/types/PrestoToVeloxQueryPlan.cpp:18:
In file included from /Users/czentgr/gitspace/presto/presto-native-execution/velox/velox/connectors/hive/HiveConnector.h:21:
In file included from /Users/czentgr/gitspace/presto/presto-native-execution/velox/velox/connectors/hive/HiveDataSource.h:22:
In file included from /Users/czentgr/gitspace/presto/presto-native-execution/velox/velox/dwio/common/BufferedInput.h:20:
In file included from /Users/czentgr/gitspace/presto/presto-native-execution/velox/velox/dwio/common/SeekableInputStream.h:23:
/Users/czentgr/gitspace/presto/presto-native-execution/velox/velox/dwio/common/wrap/zero-copy-stream-wrapper.h:31:10: fatal error: 'google/protobuf/io/zero_copy_stream.h' file not found
#include <google/protobuf/io/zero_copy_stream.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

It was suggested that the dependency on protobuf isn't really necessary but the inclusion of certain velox headers requires a system version which in turn makes it susceptible if the version changes exposing build issues.
Perhaps this issue can be resolved somehow and the dependency on protobuf be removed to get a more stable build environment. I would say that ideally the bundled velox version should be used to make is system independent.

FYI @majetideepak

**Comment by aditi-pandit** [comment]
Just my 2 cents... I agree that using the bundled velox version is the cleanest solution. 

@kgpai : wdyt ?

**Comment by majetideepak** [comment]
Prestissimo does not need protobuf afaik. The right fix is to prevent the header creep from Velox. I will fix this.
The other issue with ""absl::lts_20230125::log_internal::LogMessage::CopyToEncodedBuffer" should be solved by pinning the Velox protobuf version to protbuf@21 and bundling protobuf by default.

**Comment by czentgr** [comment]
@majetideepak the protobuf headers come from the inclusion of certain Velox headers from the hive connector.
The current stack is 
```
czentgr/gitspace/presto/presto-native-execution/presto_cpp/main/types/PrestoToVeloxQueryPlan.cpp
In file included from /home/czentgr/gitspace/presto/presto-native-execution/velox/velox/dwio/common/SeekableInputStream.h:23,
                 from /home/czentgr/gitspace/presto/presto-native-execution/velox/velox/dwio/common/BufferedInput.h:20,
                 from /home/czentgr/gitspace/presto/presto-native-execution/velox/velox/connectors/hive/HiveDataSource.h:22,
                 from /home/czentgr/gitspace/presto/presto-native-execution/velox/velox/connectors/hive/HiveConnector.h:21,
                 from /home/czentgr/gitspace/presto/presto-native-execution/presto_cpp/main/types/PrestoToVeloxQueryPlan.cpp:19:
/home/czentgr/gitspace/presto/presto-native-execution/velox/velox/dwio/common/wrap/zero-copy-stream-wrapper.h:31:10: fatal error: google/protobuf/io/zero_copy_stream.h: No such file or directory
   31 | #include <google/protobuf/io/zero_copy_stream.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
But I remembers I have seen it come from the TaskManager instead of the PrestoToVeloxPlanQuery but this is the current (fairly recent commit base) first failure.

You had mentioned before that the headers shouldn't leak. I didn't look into this because I was trying to find a solution for both problems - the pinning would take care of one and offers a way of fixing the other - which still could offer to also remove the headers.
Looks like you are investigating this now.

As for pinning my linked PR will do that and allow for knowing if it was bundled in case it is needed to make a CMake change in Prestissimo.
It still allows for a system version because that is how the CMake for resolving the dependency works which is fine. The build can be skipped if the system version matches the bundled version.

**Comment by majetideepak** [comment]
A recent change could have introduced a similar issue. I have a fix here https://github.com/facebookincubator/velox/pull/5788

**Comment by kgpai** [comment]
@aditi-pandit I was under impression that presto-native was dependent in some way on proto ; If @czentgr says that native doesnt depend on presto-native and this is just a header leak , then its something we should fix on Velox side ; I will have to look into how though as I am not sure at the moment whats causing it. 

In general though it would be great if we can extend resolve_dependency in Velox to also work for projects using Velox. This way we dependent projects can use vendored velox dependencies and if now download and install them locally for the build and we can avoid all the problems associates with global installs.

**Comment by majetideepak** [comment]
PRs to fix the header leak
https://github.com/facebookincubator/velox/pull/5781
https://github.com/prestodb/presto/pull/20370/files

**Comment by czentgr** [comment]
Issue is resolved. Closing.

**Comment by jaystarshot** [comment]
I had a new use case using protobuf, seems like the `abseil` linking errors also happen with v3.21. Not sure if this actually fixed the rc

**Comment by czentgr** [comment]
@jaystarshot Do you mean running `setup-adapters.sh install_gcs` and when the grpc dependency is built it runs into problems or at which point do you see this? While abseil is installed the additionally (re-)installed protobuf is of a version that doesn't use it (the version is the same as the protobuf install from the setup scripts).

**Comment by jaystarshot** [comment]
No its a bit complicated. I wanted to use grpc for my use case. I think currently there is no grpc library in velox.
Some gcs connector library is bringing in absl 2024x. GRPC libary has absl and proto as its dependencies.
Our proto version is pined at 3.2x and the grpc corresponding to that brings in absl version 2022x.  So I had to figure out which grpc version uses absl 2024x and then upgrade our proto to the corresponding grpc version (25.1).  
I think this is going to cause a mess in future
