### ISSUE TITLE
Potential bug in MERGE_HLL

### ISSUE THREAD

**Issue by ampampamp** [prestodb/presto#20041]
I believe this [line](https://github.com/prestodb/presto/blame/dee970509a04f1b9c05ceb3c7b33633b096a355a/presto-main/src/main/java/com/facebook/presto/operator/scalar/HyperLogLogFunctions.java#L80) should actually be written as:
```java
for (int i = firstNonNullIndex + 1; i < block.getPositionCount(); i++) {
```
Note the `+ 1`. I think we're _double-adding_ the first non-null HLL to the output since the loop is starting at the same index that the output initialized at (`firstNonNullIndex`) [two lines before](https://github.com/prestodb/presto/blame/dee970509a04f1b9c05ceb3c7b33633b096a355a/presto-main/src/main/java/com/facebook/presto/operator/scalar/HyperLogLogFunctions.java#L77C11-L77C11).

**Comment by amellnik** [comment]
For anyone else who's reading along, we can make this slightly more efficient by fixing this but it doesn't affect the output.

**Comment by ampampamp** [comment]
Closing this issue as this isn't really a bug since merging a sketch with itself does not change the answer.
