### ISSUE TITLE
Strict check of the s3 directory object content type.

### ISSUE THREAD

**Issue by bkyryliuk** [prestodb/presto#20310]
It would be great to relax the content type requirement for the folder here: https://github.com/prestodb/presto/blob/master/presto-hive/src/main/java/com/facebook/presto/hive/s3/PrestoS3FileSystem.java#L374C31-L374C31

Currently as I understand databricks unity creates the directory s3 objects with `application/octet-stream` metadata, not `application/x-directory` and that leads to the failure of creating the external delta tables and accessing those through presto.

Presto error msg:
```presto error: External location must be a directory```

I've confirmed that it is a root cause via copying the directory object and changing it's content type. Doing that and copying other files to it results in a successful creation of the external table and ability to query it.

Example
```
CREATE TABLE bogdankyryliuk.presto_delta_table_from_prod (number_of_rows INT)
WITH (external_location = 's3a://{bucket}/metastore/f3cba8bc-0d7d-47b8-b16c-ee9ec0682680/tables/60652537-cf0a-4ddb-8f18-3146838a90d0');
-- fails with presto error: External location must be a directory
```

**Comment by huhlig** [comment]
Can Confirm. S3 Browser when uploading also creates directories with `application/octet-stream` when uploading data which makes presto break with the same error as above.

**Comment by aaneja** [comment]
cc : @imjalpreet @agrawalreetika for visibility
