### ISSUE TITLE
Show release dates

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#20322]
It seems difficult to find out when a particular release was made and how often new releases are created.

Is there any reason a date is not displayed in https://prestodb.io/docs/current/release.html ?

CC: @tdcmeehan @majetideepak @amitkdutta @xiaoxmeng @aditi-pandit

**Comment by tdcmeehan** [comment]
I agree that seems like a good idea to add the information.  CC: @wanglinsong

**Comment by wanglinsong** [comment]
Yes, we can add date to this file.
There are usually 3 dates
1. release branch is created
2. artifacts are published to maven
3. release notes PR is merged and docs website is updated
Which data do we use?
@tdcmeehan

**Comment by mbasmanova** [comment]
Maybe the date of the last commit that was included in the release?

**Comment by tdcmeehan** [comment]
I think if one were determined, they could see the tag and infer the date of the last commit.  If I may be allowed to bikeshed, my preference is #2, since this is when the release artifacts are actually made available to the community.  Let's sync on this during the weekly release meeting.
