### ISSUE TITLE
Why REMOTE_TASK_MISMATCH?

### ISSUE THREAD

**Issue by colagy** [prestodb/presto#20371]
![image](https://github.com/prestodb/presto/assets/37213080/3bc0ab3f-2d47-442a-9ae2-56891b4a9166)

How the taskInstanceId changed?

**Comment by tdcmeehan** [comment]
My guess is this is more of a validation check, like a precondition that fails fast if something has gone drastically wrong in a potential future buggy code change.  We have other such checks all throughout the code that check preconditions, in particular for null references.

**Comment by tdcmeehan** [comment]
Please reopen if you have further questions, thanks!
