### ISSUE TITLE
TestQueryManager.testQueryCountMetrics is flaky

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#20447]
```
Error:  Failures: 
Error:    TestBrutalShutdown.testQueryRetryOnShutdown:83 expected [5] but found [3]
Error:    TestQueryManager.testQueryCountMetrics:253 expected [3] but found [4]
```

https://github.com/prestodb/presto/actions/runs/5719711593/job/15498182666?pr=20444

CC: @tdcmeehan @majetideepak

**Comment by mbasmanova** [comment]
Failing on another PR as well

```
Error:  Failures: 
Error:    TestQueryManager.testQueryCountMetrics:253 expected [3] but found [5]
[INFO] 
Error:  Tests run: 3024, Failures: 1, Errors: 0, Skipped: 0
```

https://github.com/prestodb/presto/actions/runs/5720225932/job/15499735367?pr=20446

**Comment by mbasmanova** [comment]
This CI job is marked as required. Flakiness is preventing PRs from being merged and slows down development process. Let's prioritize mitigating and fixing.

**Comment by mbasmanova** [comment]
The test failed on 3-rd re-run. Disabling in #20446

**Comment by imjalpreet** [comment]
I will have a look into this and fix the flakiness.

**Comment by tdcmeehan** [comment]
@mbasmanova I will be opening a topic on how to handle flaky tests in general in today's TSC meeting.  If you have suggestions on how the project can proactively remediate flaky tests, please consider attending.
