### ISSUE TITLE
Invalid error message for NestedLoopJoin in LocalExecutionPlanner

### ISSUE THREAD

**Issue by xumingming** [prestodb/presto#20465]
code: https://github.com/prestodb/presto/blob/0515f186a8d3bf3412dfef4335a707ad2f9b0f57/presto-main/src/main/java/com/facebook/presto/sql/planner/LocalExecutionPlanner.java#L2141-L2143

The code itself wants to make sure the strategy is UNGROUPED_EXECUTION, the error message say it should be GROUPED_EXECUTION.

**Comment by tdcmeehan** [comment]
Thanks for filing this @xumingming.  Would you like to submit a pull request to fix it?

**Comment by yhwang** [comment]
@xumingming as @tdcmeehan mentioned, if you'd like to have a PR to fix this, please go ahead! Just ignore the self-assigned from me. Otherwise, I am happy to help with this.
