### ISSUE TITLE
Add syntax level support for time travel

### ISSUE THREAD

**Issue by tdcmeehan** [prestodb/presto#20495]
Right now, [we only support time travel via system tables and system procedures.](https://prestodb.io/docs/current/connector/iceberg.html#time-travel)

The current support does not include a convenient way to select a particular snapshot or the ability to select a snapshot as of a particular timestamp.  Using system tables and system procedures to do this is not convenient, and it also is not safe per-user, since the system table alters the table for everyone, not just the current user.

[See Trino implementation,](https://trino.io/docs/current/connector/iceberg.html#time-travel-queries) which has syntax level support for going back to a particular snapshot via `FOR VERSION AS OF`, and to go back to a period in time without having to first fetch a snapshot id via `FOR TIMESTAMP AS OF`.  We should consider a similar feature for convenience of time travel.

**Comment by gupteaj** [comment]
PR https://github.com/prestodb/presto/pull/20991

**Comment by gupteaj** [comment]
Time travel syntax issue https://github.com/prestodb/presto/issues/21396

**Comment by gupteaj** [comment]
Iceberg connector PR https://github.com/prestodb/presto/pull/21425

**Comment by tdcmeehan** [comment]
Closed by #21425
