### ISSUE TITLE
Strictly enforce CoW in Iceberg connector

### ISSUE THREAD

**Issue by tdcmeehan** [prestodb/presto#20493]
Until prestodb/presto#20492 is complete, it's possible that if Presto attempts to read from V2, then it may silently read deleted data.  We should validate that the table is V1 and strictly enforce that only V1 table are being read.  Alternatively, we continue with partial V2 support, and simply fail if the table is MoR.

c.f. apache/iceberg#7169

**Comment by yingsu00** [comment]
We can fail the query if there is non-empty delete files. V2 tables without deletefiles should be fine.
