### ISSUE TITLE
Iceberg connector not able to drop tables with missing table metadata in Filesystem

### ISSUE THREAD

**Issue by imjalpreet** [prestodb/presto#20529]
## Your Environment

* Presto version used: 0.284-SNAPSHOT (master)
* Storage (HDFS/S3/GCS..): S3
* Data source and connector used: Iceberg with catalog type as Hive
* Deployment (Cloud or On-prem): Cloud

## Expected Behavior

Drop table should work and drop the table even if metadata/data doesn't exist in filesystem 

## Current Behavior

**"Table metadata is missing"** thrown in `com.facebook.presto.iceberg.HiveTableOperations#refreshFromMetadataLocation` when trying to check table properties https://github.com/prestodb/presto/blob/703e9429b8ce0a4bbec3ee6e361c0605bbf35a91/presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergHiveMetadata.java#L441-L446

## Possible Solution

Refactor current implementation to take into account such cases

## Steps to Reproduce

1. Create an iceberg table
2. Delete data from the filesystem
3. Try to drop the iceberg table

**Comment by tdcmeehan** [comment]
Can it be dropped through the Hive connector?

**Comment by tdcmeehan** [comment]
Additionally, if the metadata is missing, could a solution be to implement #20421 and then attempt to drop?
