### ISSUE TITLE
[Feature Request] Improve Iceberg documentation

### ISSUE THREAD

**Issue by yingsu00** [prestodb/presto#20543]
Create a top level section for "SQL Support ", which include
 - DDL, e.g. Create table, create schema
 - DML, e.g. alter table, schema
 - system functions
 - select 
 - view management.

Create a top level section for "Metadata Tables" and list all supported ones
Create a top level section for "Metadata Columns" that can be queried

## Presto Component, Service, or Connector
Presto documentation

**Comment by yingsu00** [comment]
cc @ChunxuTang @tdcmeehan

**Comment by yingsu00** [comment]
Reetika already added the metadata tables doc, but they are not showing up properly. @agrawalreetika will try to fix it and add other DDL DML documentations

**Comment by agrawalreetika** [comment]
For keeping track posting here,
Iceberg Metadata table documentation is added in https://github.com/prestodb/presto/pull/19732  - Will be available with 0.283
Table Properties documentation is added as part of https://github.com/prestodb/presto/pull/20015 - Will be available with 0.284
