### ISSUE TITLE
Make hive.metastore.uri Optional in case of Hadoop Catalog in Presto Iceberg Connector

### ISSUE THREAD

**Issue by agrawalreetika** [prestodb/presto#20579]
Currently using Hadoop Catalog with Presto Iceberg Connector requires the `hive.metastore.uri` property, even though it doesn’t rely on metastore for metadata when using Hadoop Catalog. 

As a workaround, you can provide a placeholder for `hive.metastore.uri`` property (Ex - hive.metastore.uri=thrift://localhost:9083) in the Iceberg catalog to use Hadoop Catalog.

This is to fix this behavior and make `hive.metastore.uri` property Optional when Hadoop Catalog is used for catalog in Presto Iceberg Connector

Issue details - https://github.com/prestodb/presto/issues/19920

**Comment by pratyakshsharma** [comment]
The issue is there with nessie catalog as well. We need to fix this for hadoop and nessie catalogs both.
