### ISSUE TITLE
[Native] Add e2e test for to_ieee754_64()

### ISSUE THREAD

**Issue by yzhang1991** [prestodb/presto#20589]
to_ieee754_64() was added in https://github.com/facebookincubator/velox/pull/4662

**Comment by yzhang1991** [comment]
Hi @pdabre12, did you get a chance to look at this issue?

**Comment by yzhang1991** [comment]
@pdabre12 oh! I didn't see that, thanks for pointing out

**Comment by pdabre12** [comment]
@yzhang1991 No worries, thank you.
