### ISSUE TITLE
[Native] Implement key_sampling_percent()

### ISSUE THREAD

**Issue by yzhang1991** [prestodb/presto#20592]
https://prestodb.io/docs/current/functions/string.html

**Comment by majetideepak** [comment]
As noted by Aditi here https://github.com/facebookincubator/velox/pull/8481#issuecomment-1926402896,
this is a SQL function https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/operator/scalar/sql/SimpleSamplingPercent.java and should only need the `from_ieee754_64` function.
