### ISSUE TITLE
[Iceberg] Read and write statistics from ANALYZE

### ISSUE THREAD

**Issue by ZacBlanco** [prestodb/presto#20614]
## Expected Behavior or Use Case

The Presto query optimizer uses both table and column-level statistics to create better query plans. Currently, Hive is one of the few connectors that supports storing column-level statistics through ANALYZE. Ideally, if using a combination of Hive and Iceberg, we should also be able to run `ANALYZE` to store the statistics into the Hive metastore.

In addition, the implementation should probably also make use of storing statistics into the iceberg table format defined by the Iceberg spec. However, the current version of the iceberg specification is lacking support for many statistic types. The only supported type currently is the NDV (number of distinct values) in the form of an [Apache DataSketches Theta Sketch](https://iceberg.apache.org/puffin-spec/#apache-datasketches-theta-v1-blob-type).

Regardless of Iceberg specification adoption, the Iceberg connector at minimum should be able to write and store statistics when configured with the hive metastore. Other metastore configurations could at least read the statistics supported by the table format.

## Presto Component, Service, or Connector

Iceberg Connector

## Possible Implementation

Write path
```
ANALYZE <table>;

- create aggregate table information
  - write supported stats in iceberg format
  - if hive metastore configured
    - store statistics in metastore
```

Read path
```
when calling `metadata.getTableStatistics`:
  - read statistics from iceberg format
  - if hive metastore configured
    - read statistics from HMS
    - combine with table-level statistics (overwrite configurable?)
  - return stats
```

## Example Screenshots (if appropriate):

N/A

## Context

This will help improve query plans and in general is useful for query performance.

cc: @tdcmeehan

**Comment by agrawalreetika** [comment]
Hi @ZacBlanco,
Here in case Read path while calling `metadata.getTableStatistics`,  do we get the stats from Iceberg FS as well as the HMS every time we query? 
Or the first attempt is made to get stats from HMS and Filestsystem is not checked for stats at all?

**Comment by agrawalreetika** [comment]
> We would query both locations for stats every time. The main reason is that the stats coming from the FS are generally going to be more up-to-date than the ones coming from HMS since they come from the table metadata directly. Ideally we get those every time. Then, the HMS stats for NDVs (and in the future, histograms) would be pulled from the HMS since Presto doesn't natively support storing Iceberg's NDV format
> 
> This is the current implementation in #20720

OK, Are we storing NDVs stats in HMS by getting/deriving from stats information stored in FS?

**Comment by ZacBlanco** [comment]
> Are we storing NDVs stats in HMS by getting/deriving from stats information stored in FS?

NDVs cannot be calculated from the stats stored in the FS. It needs to be calculated through the aggregation function in an `ANALYZE` query.

**Comment by yingsu00** [comment]
> NDVs cannot be calculated from the stats stored in the FS. It needs to be calculated through the `approx_distinct` aggregation function in an `ANALYZE` query.

Number of distinct values is already in the manifest file in 
 data_file field https://github.com/apache/iceberg/blob/master/format/spec.md#:~:text=111-,distinct_counts,-map%3C123%3A%20int but the Metrics class doesn't have it. The data_file field also has key_metadata as the implementation-specific key metadata for encryption but no field for histograms. I think we can ask the Iceberg community if they can add them. cc @tdcmeehan

**Comment by ZacBlanco** [comment]
> > NDVs cannot be calculated from the stats stored in the FS. It needs to be calculated through the `approx_distinct` aggregation function in an `ANALYZE` query.
> 
> Number of distinct values is already in the manifest file in data_file field https://github.com/apache/iceberg/blob/master/format/spec.md#:~:text=111-,distinct_counts,-map%3C123%3A%20int but the Metrics class doesn't have it. The data_file field also has key_metadata as the implementation-specific key metadata for encryption but no field for histograms. I think we can ask the Iceberg community if they can add them. cc @tdcmeehan

Thanks for bringing this up. I wasn't aware that the stats within each file could store the NDVs. That would require table writers to track and write them, which I'm not sure that our current implementation is capable of?

Also, in addition to the link @yingsu00 provided, Table statistics can also be stored in a Puffin file alongside the table. However, the [only valid statistic in the Puffin file is an Apache Datasketches Theta sketch](https://iceberg.apache.org/puffin-spec/#apache-datasketches-theta-v1-blob-type), which the connector can't yet generate from the `ANALYZE` query (I also have a PR which will eventually be used to support this in https://github.com/prestodb/presto/pull/20871).

**Comment by ZacBlanco** [comment]
Also, I took a closer look at the implementation because I recalled not seeing anything in the API about distinct values available when authoring this PR. -- the most current Iceberg release (1.3.1 as of writing) doesn't include the `distinct_counts` field in their `DataFile` implementation, even though it is defined in the spec [[1]], so supporting reading and writing NDVs in manifest files would require some more support from the Iceberg community or contributing ourselves.

[1]: https://github.com/apache/iceberg/blob/master/api/src/main/java/org/apache/iceberg/DataFile.java
