### ISSUE TITLE
Document Set Digest functions

### ISSUE THREAD

**Issue by tdcmeehan** [prestodb/presto#20615]
Presto has 1:1 compatibility for the following Set Digest functions: https://trino.io/docs/current/functions/setdigest.html

The Presto project should add documentation for these functions as well.

**Comment by Akanksha-kedia** [comment]
@tdcmeehan  Can i assignee this Document update in my name?

**Comment by steveburnett** [comment]
[PR 20676](https://github.com/prestodb/presto/pull/20676) has been merged. Can this be closed?

**Comment by tdcmeehan** [comment]
Yes--thanks!
