### ISSUE TITLE
Iceberg Schema evolution is not handled properly leading to wrong results

### ISSUE THREAD

**Issue by mderoy** [prestodb/presto#20621]
Presto is scanning tables using the column names rather than the column's field_id metadata.... this leads to wrong results when removing a column and adding a new column of the same name. Presto also does not write the field_id metadata when writing. This leads to wrong results both with the presto engine reading these evolved tables, but also in other engines reading these tables (since the field_id metadata is missing).

## Your Environment
* Presto version used: 0.281-cfbc6eb
* Storage (HDFS/S3/GCS..): Minio S3
* Data source and connector used: iceberg
* Deployment (Cloud or On-prem): onprem

## Expected Behavior
correct results scanning the table
correct results when engines like spark scan a presto created iceberg table

## Current Behavior
wrong results

## Possible Solution
- When scanning from a table, presto should be selecting based off the parquet field_id metadata, but is instead selecting based off the column name. This leads to wrong results when scanning evolved tables with reused column names
- When writing to the table, iceberg must write the field_id metadata in the same way spark and other engines do.

## Steps to Reproduce
```
create table iceberg.test.evotests (c1 int);
insert into iceberg.test.evotests values (1);
alter table iceberg.test.evotests add column c2 int;
insert into iceberg.test.evotests values (2,2);
alter table iceberg.test.evotests drop column c1;
insert into iceberg.test.evotests values (3);
alter table iceberg.test.evotests add column c1 int;
insert into iceberg.test.evotests values (4,4);
presto> select * from iceberg.test.evotests;
  c2  |  c1  
------+------
    3 | NULL 
 NULL |    1 
    2 |    2 
    4 |    4 
(4 rows)
```
In this case the results from spark-sql engine
```
create table demo.nyc.evotests(c1 int);
insert into demo.nyc.evotests values(1);
alter table demo.nyc.evotests add column (c2 int);
insert into demo.nyc.evotests values(2,2);
alter table demo.nyc.evotests drop column (c1);
insert into demo.nyc.evotests values(3);
alter table demo.nyc.evotests add column (c1 int);
insert into demo.nyc.evotests values(4,4);
select * from demo.nyc.evotests;
c2 | c1
2	NULL
3	NULL
4	4
NULL	NULL
```

**Comment by mderoy** [comment]
a more broken example where teh query fails due to the mismatch in type of the drop/added column
```
create table iceberg.test.evotest3 (c1 int);
insert into iceberg.test.evotest3 values (1);
alter table iceberg.test.evotest3 add column c2 int;
insert into iceberg.test.evotest3 values (2,2);
alter table iceberg.test.evotest3 drop column c1;
insert into iceberg.test.evotest3 values (3);
alter table iceberg.test.evotest3 add column c1 varchar;
insert into iceberg.test.evotest3 values (4, 'four');
presto> select * from iceberg.test.evotest3;

Query 20230821_213528_00031_5k2r8, FAILED, 1 node
Splits: 20 total, 0 done (0.00%)
[Latency: client-side: 379ms, server-side: 316ms] [0 rows, 0B] [0 rows/s, 0B/s]

Query 20230821_213528_00031_5k2r8 failed: com.facebook.presto.common.type.VarcharType
```

**Comment by agrawalreetika** [comment]
Hi @mderoy,
I tried the same sequence as you mentioned from Presto-0.283 using Presto iceberg connector. I am getting the same result as you mentioned for Spark -
![image](https://github.com/prestodb/presto/assets/7887476/dc5335b8-8ec1-4498-b66b-e9f2fdceffc5)

Which version of presto you are on? Could you please verify once with Presto-0.283?

**Comment by mderoy** [comment]
Thanks, If you ran the scenario with the latest presto and got the same output as spark we can close this.
