### ISSUE TITLE
[native] Failed to parse type [row("123" varchar,"456" varchar)]: 

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#20639]
```
assertQuery("SELECT cast(row(orderkey, comment) as row(\"123\" varchar, \"456\" varchar)) FROM orders");

Caused by: VeloxUserError:  Failed to parse type [row("123" varchar,"456" varchar)]: 
```

CC: @pratyakshsharma @aditi-pandit @amitkdutta @zacw7 

Unit test to repro:

```
TEST_F(TestTypeSignature, xxx) {
  assertRowSignature(
      "row(\"12\" bigint,b bigint,c bigint)",
      rowSignature(
          namedParameter("12", false, signature("bigint")),
          namedParameter("b", false, signature("bigint")),
          namedParameter("c", false, signature("bigint"))));
}
```

**Comment by mbasmanova** [comment]
@majetideepak Deepak, any chance you could help with this?

**Comment by kgpai** [comment]
@mbasmanova Heres how to only install 4.9.3 locally:

1. Uninstall antlr via brew : ` brew uninstall antlr` 
2. Run commands below : 
``` 
   source velox/scripts/setup-helper-functions.sh  
   function install_antlr {
  github_checkout antlr/antlr4 "4.9.3"
  cd runtime/Cpp
  cmake_install -DBUILD_TESTS=OFF
}
install_antlr
```

You can also just run scripts/setup-macos.sh , but it will install every dependency , so the above will be faster.

**Comment by mbasmanova** [comment]
Thank you, @majetideepak  and @kgpai, let me follow your instructions and redo the change with the original version of ANTLR.

**Comment by kgpai** [comment]
@majetideepak @mbasmanova I think the script just installs the antlr runtime and not antlr binary itself .

**Comment by kgpai** [comment]
Let me know if theres a better way @majetideepak , the way I resolved this was to : 
``` 
 1. Get. jar from https://repo1.maven.org/maven2/org/antlr/antlr4/4.9.3/ and download antlr4-4.9.3-complete.jar 
 2. Then run java -jar antlr4-4.9.3-complete.jar TypeSignature.g4
 ```
