### ISSUE TITLE
Oracle Connector failed, ORA-01017: invalid username/password; logon denied

### ISSUE THREAD

**Issue by yongbeima** [prestodb/presto#20657]
Friends,

The Oracle Connector shw me this error:
Query 20230825_025755_00002_jn7iw failed: ORA-01017: invalid username/password; logon denied

I use presto docker environment.
I follow this page https://prestodb.io/docs/current/connector/oracle.html to config my oracle Connector.

my *.properties file like this:

connector.name=oracle
connection-url=jdbc:oracle:thin:@example.net:1521:orcl
connection-user=user
connection-password=**shdj@ji#hj@34**

I guess this error come from my special character in connection-password,
how to fix this?

Thanks

**Comment by YorkWong** [comment]
In some situations, the connection-url has to include the user and password.
example: connection-url=jdbc:oracle:thin:user/password@example.net:1521:orcl

**Comment by yongbeima** [comment]
It is working after I change the config to this:

connection-url=jdbc:oracle:thin:user/"shdj@ji#hj@34"@example.net:1521:orcl

Thanks
