### ISSUE TITLE
Improve documentation of Presto Resource Groups

### ISSUE THREAD

**Issue by imjalpreet** [prestodb/presto#20688]
Currently, only File-based Resource Group Manager is documented. We should also document DB-based Resource Group Manager.

**Comment by Akanksha-kedia** [comment]
@imjalpreet Can I help in Documentation of this, if yes please help to assign me.

**Comment by steveburnett** [comment]
This should be closed as its accompanying PRs #20918 and #21057 are closed and merged, respectively.
