### ISSUE TITLE
[Native] - Queries with lambda functions failing with "Scalar function name not registered: presto.default.apply" against velox

### ISSUE THREAD

**Issue by mknegi** [prestodb/presto#20741]
**Failing Query:**
SELECT apply(0, x -> x + c1) FROM (VALUES 1) t(c1)

**Error Message**
```
2023-08-02T05:51:15.818-0600 ERROR remote-task-callback-10 com.facebook.presto.execution.StageExecutionStateMachine Stage execution 20230802_115115_00499_4ssae.0.0 failed
VeloxUserError: Scalar function name not registered: presto.default.apply, called with arguments: (INTEGER, FUNCTION).
java.lang.AssertionError: Execution of 'actual' query failed: SELECT apply(0, x -> x + c1) FROM (VALUES 1) t(c1)
```
**Expected output:** 
VALUES 1

**Comment by yzhang1991** [comment]
Checked with Aditi, `apply` is a UDF for testing in Java. Then we probably won't fix this since custom UDF is not yet supported in Prestissimo.

**Comment by aditi-pandit** [comment]
@mbasmanova, @pedroerp : Do you think we would implement the presto.default.apply function in Velox https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/operator/scalar/ApplyFunction.java ?

Supporting this function in Java seems more tractable to me than C++ (without any kind of codegen support ). Though I'm not an expert here, so would like to hear your thoughts.

**Comment by mbasmanova** [comment]
```
/**
 * This scalar function exists primarily to test lambda expression support.
 */
public final class ApplyFunction
```

Given this comment, what's the need for implementing this in Prestissimo?

**Comment by aditi-pandit** [comment]
@mknegi : Please disable this test.
