### ISSUE TITLE
Improve Comparison Operator and function Document for IN operator

### ISSUE THREAD

**Issue by Akanksha-kedia** [prestodb/presto#20760]
![image](https://github.com/prestodb/presto/assets/89628774/5d71ba04-ffff-49a1-9f46-26ee5311d85d)

![image](https://github.com/prestodb/presto/assets/89628774/4a74e556-7066-44d1-a447-ed796e4cefa4)

**Comment by Akanksha-kedia** [comment]
@tdcmeehan feel free to discussion and let me know can we work for improvement.

**Comment by tdcmeehan** [comment]
Could you elaborate on the precise nature of the enhancement?
