### ISSUE TITLE
Casting varchar containing UTF-8 characters to bigint yields unexpected results.

### ISSUE THREAD

**Issue by kevinwilfong** [prestodb/presto#20786]
Casting a Varchar containing non-numeric UTF-8 characters to a bigint can return numeric results.  E.g. cast('١٩٨٢' as bigint) yields 1982.

## Expected Behavior
I would expect casting non-numeric strings to fail.

## Current Behavior
I receive a numeric result.  This seems to be inherited from Java's Long.parseLong

## Steps to Reproduce
cast('١٩٨٢' as bigint)
returns 1982, I would expect it to fail

some other examples:
cast('৩৫' as bigint) => 35
cast('১৪১০' as bigint) => 1410
cast('๒๕๕๙' as bigint) => 2559

## Context
This is causing inconsistent results between Presto and other engines.

**Comment by mbasmanova** [comment]
CC: @aditi-pandit @majetideepak @bikramSingh91

**Comment by kevinwilfong** [comment]
and Thai and Eastern Arabic numerals, that probably explains it

**Comment by mbasmanova** [comment]
CC: @kagamiori
