### ISSUE TITLE
[native] presto_protocol-json-hpp.mustache needs updating to refer to new json location

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#20785]
PR #20619 moved json.hpp, but didn't update presto_protocol-json-hpp.mustache. As a result, 'make presto_protocol' command generates files that do not compile.

CC: @majetideepak @czentgr @amitkdutta

**Comment by majetideepak** [comment]
@czentgr is working on a fix here https://github.com/prestodb/presto/pull/20788/files
