### ISSUE TITLE
Flaky Test: com.facebook.presto.orc.metadata.statistics.TestMapColumnStatisticsBuilder.testAddMapStatisticsNoValues

### ISSUE THREAD

**Issue by ZacBlanco** [prestodb/presto#20807]
CI Run: https://github.com/prestodb/presto/actions/runs/6116066297/job/16600699444?pr=20776

**Comment by Akanksha-kedia** [comment]
@ZacBlanco [INFO] Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.49 s - in com.facebook.presto.orc.metadata.statistics.TestMapColumnStatisticsBuilder
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 11, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11.255 s
[INFO] Finished at: 2023-09-13T19:27:43+05:30
  


Can you provide more information abt error, steps to recreate the issue.

**Comment by ZacBlanco** [comment]
This was the log:

```
Error:  Failures: 
Error:  com.facebook.presto.orc.metadata.statistics.TestMapColumnStatisticsBuilder.testAddMapStatisticsNoValues
[INFO]   Run 1: PASS
Error:    Run 2: TestMapColumnStatisticsBuilder.testAddMapStatisticsNoValues » IllegalState There is no start record for test: com.facebook.presto.orc.metadata.statistics.TestMapColumnStatisticsBuilder::testAddMapStatisticsNoValues
[INFO] 
[INFO] 
Error:  Tests run: 594, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15:26 min
[INFO] Finished at: 2023-09-08T00:33:39Z
[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7:test (default-test) on project presto-orc: There are test failures.
Error:  
Error:  Please refer to /home/runner/work/presto/presto/presto-orc/target/surefire-reports for the individual test results.
Error:  Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
Error:  -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Error: Process completed with exit code 1.
```

I haven't looked into the cause. I just know that my code did not touch anything near this part of the codebase, so it should not have failed

**Comment by Akanksha-kedia** [comment]
Did you try second or multiple times

**Comment by ZacBlanco** [comment]
Yes after re-running the test passed

**Comment by ZacBlanco** [comment]
After looking closer, the failure seems to have come from a TestNG extension within Presto, but not the test itself. The error was generated on this line: https://github.com/prestodb/presto/blob/master/presto-testng-services/src/main/java/com/facebook/presto/testng/services/LogTestDurationListener.java#L177

**Comment by Akanksha-kedia** [comment]
Thanks, I'll look into it.

**Comment by rschlussel** [comment]
the code has been used for debugging test issues (in the past we've had issues where tests would just hang or some tests would run really long), but we probably shouldn't fail the test. Anyway, looks like the issue here is there were two tests in the class with the same name that must have run concurrently, so they shared an entry in this map https://github.com/prestodb/presto/blob/621f7b36898e518588bed97ea59454a9304e7037/presto-testng-services/src/main/java/com/facebook/presto/testng/services/LogTestDurationListener.java#L57.
