### ISSUE TITLE
[Discussion] Lead/Lag function's behavior when the offset is NULL

### ISSUE THREAD

**Issue by xumingming** [prestodb/presto#20835]
```java
// Presto TestLeadFunction.java
assertWindowQuery("lead(orderkey, null, -1) OVER (PARTITION BY orderstatus ORDER BY orderkey)",
        resultBuilder(TEST_SESSION, INTEGER, VARCHAR, INTEGER)
                .row(3, "F", null)
                .row(5, "F", null)
                .row(6, "F", null)
                .row(33, "F", null)
                .row(1, "O", null)
                .row(2, "O", null)
                .row(4, "O", null)
                .row(7, "O", null)
                .row(32, "O", null)
                .row(34, "O", null)
                .build());
```

In this test case, the offset is null, default value is specified as `-1`, but the expected value is `null` rather than `-1`, while in the doc([1]), it says that default value should be returned:

> If the offset is null or larger than the window, the default_value is returned, or if it is not specified null is returned.

`Lag` function has similar issue.

[1]. https://prestodb.io/docs/current/functions/window.html

**Comment by xumingming** [comment]
Related discussion in Velox: https://github.com/facebookincubator/velox/issues/6413

**Comment by tdcmeehan** [comment]
It seems reasonable that the behavior for null should match the behavior when unspecified.  Do you know what the spec says should be the behavior when null is specified for the offset?

**Comment by xumingming** [comment]
I'm not sure, on one hand Presto's doc(not implementation) aligns with Oracle([1]); on the other hand Trino decided to raise an error when offset is null([2]).

[1]. https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/LEAD.html#GUID-0A0481F1-E98F-4535-A739-FCCA8D1B5B77
[2]. https://github.com/trinodb/trino/issues/19003

**Comment by tdcmeehan** [comment]
CC: @kaikalur would like to hear your thoughts on this one.

**Comment by aditi-pandit** [comment]
@xumingming : The Oracle doc doesn't mention behavior if offset is null. It only says that if offset is unspecified then it is defaulted to 1. Velox also follows the same semantics and defaults to 1.

Interestingly, Duckdb returns the current row if offset is null:
```
select lead(orderkey, null, -1) over (partition by orderstatus order by orderkey ) from (values (1, 's'), (2, 's')) t(orderkey, orderstatus);
┌────────────────────────────────────────────────────────────────────────────┐
│ lead(orderkey, NULL, -1) OVER (PARTITION BY orderstatus ORDER BY orderkey) │
│                                   int32                                    │
├────────────────────────────────────────────────────────────────────────────┤
│                                                                          1 │
│                                                                          2 │
└────────────────────────────────────────────────────────────────────────────┘
```

So it seems like we now have atleast 3 options if offset is null :)
i) Use default value 
ii) Raise error
iii) Return current row

This is other than the present behavior to return null.

**Comment by xumingming** [comment]
@aditi-pandit I was referring to this sentence in Oracle doc:

> The optional default value is returned if the offset goes beyond the scope of the table. 

I was assuming null offset is a `offset goes beyond the scope of the table`, and yes, it didn't say it explictly.

**Comment by Akanksha-kedia** [comment]
@ Can someone help to assign me this issue, i also want to work on this.

**Comment by tdcmeehan** [comment]
@Akanksha-kedia thanks for offering to pick this up, but please note that there doesn't appear to be consensus yet on how to fix this issue.

**Comment by Akanksha-kedia** [comment]
Yes i just wanted to understand and contribute if any findings or any
further understanding we need to develop.Thanks

**Comment by xumingming** [comment]
@tdcmeehan @aditi-pandit I want to bring up this discussion again and get a conclusion this time.

I tried several databases for the `lead function + null offset` scenario and summarized the result here:

DB | Behavior
--- | ------
Trino | Return Null (see [1])
Presto(Current) | Return Null
PostgreSQL | Return Null (see [2])
Velox | Return Default Value (see [3])
MySQL | Raise error(see [4])
DuckDB | Return Current Row (See @aditi-pandit 's comment above)

And from the results above I'd vote for `Return Null` because Presto(Velox's origin?) & PostgreSQL goes this way. What do you think?

#### References
1. Trino Behavior: https://trino.io/docs/current/functions/window.html
2. PostgreSQL

```
postgres=# select lead(orderkey, null, -1) over (partition by orderstatus order by orderkey ) from (values (1, 's'), (2, 's')) t(orderkey, orderstatus);
 lead
------


(2 rows)
```

3. Velox Behavior: https://github.com/facebookincubator/velox/issues/6413
4. MySQL Behavior

```
mysql> select lead(orderkey, null, -1) over (partition by orderstatus order by orderkey ) from test;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'null, -1) over (partition by orderstatus order by orderkey ) from test' at line 1
```

**Comment by mbasmanova** [comment]
@xumingming Thank you for the research.

> I'd vote for Return Null because Presto(Velox's origin?) & PostgreSQL goes this way. 

Makes sense to me.

**Comment by Akanksha-kedia** [comment]
Yes +1

**Comment by tdcmeehan** [comment]
Makes sense to me too, let's update the documentation to make this more clear.

**Comment by xumingming** [comment]
Glad that we come to a conclusion, so the action is:

* Update Presto documentation to describe `lead/lag + null offset` behavior more clear, track it with this current issue.
* Update Lead/Lag implementation to match with this conclusion, issue: https://github.com/facebookincubator/velox/issues/6413

**Comment by xumingming** [comment]
Just a side note: I just realized that Trino changed the behavior recently(not released yet.): https://github.com/trinodb/trino/blob/master/docs/src/main/sphinx/functions/window.md?plain=1#L110
