### ISSUE TITLE
[Native] CTAS E2E roundtrip test

### ISSUE THREAD

**Issue by yzhang1991** [prestodb/presto#20848]
Write in C++ and read back in Java and see if result match.

**Comment by pdabre12** [comment]
@yzhang1991  Can you please describe the issue?

**Comment by yzhang1991** [comment]
@majetideepak can you help give some guidance on how the local roundtrip test can be done?

**Comment by majetideepak** [comment]
https://github.com/prestodb/presto/blob/master/presto-native-execution/src/test/java/com/facebook/presto/nativeworker/AbstractTestNativeTpchQueries.java 
should give a direction. Here, we use the Java worker to write and the Bative worker to read. 
We can create a similar test and use a Native worker to write CTAS and a Java worker to read,

**Comment by majetideepak** [comment]
@pramodsatya has been working with E2E tests lately. He can give further guidance.
