### ISSUE TITLE
Flaky Test: TestCreateViewVerification.testRunningInQueryBankMode

### ISSUE THREAD

**Issue by ZacBlanco** [prestodb/presto#20863]
CI Run: https://github.com/prestodb/presto/actions/runs/6178244989/job/16771602986?pr=20720#step:7:26425

**Comment by tdcmeehan** [comment]
CC: @ericyuliu

**Comment by rschlussel** [comment]
Those logs aren't available anymore and i can't reproduce the issue, so I don't know where/why the test failed when it was flaky. I'm adding logging to help with debugging if the issue is encountered again, but I think we should close the issue for now as there's not enough info as things stand.
