### ISSUE TITLE
Template for opening a Documentation request

### ISSUE THREAD

**Issue by Akanksha-kedia** [prestodb/presto#20879]
Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.2.5.RELEASE:repackage (default) on project presto-benchto-benchmarks: Execution default of goal org.springframework.boot:spring-boot-maven-plugin:1.2.5.RELEASE:repackage failed: Plugin org.springframework.boot:spring-boot-maven-plugin:1.2.5.RELEASE or one of its dependencies could not be resolved:

**Comment by tdcmeehan** [comment]
How did you encounter this error?

**Comment by Akanksha-kedia** [comment]
@tdcmeehan please review

**Comment by tdcmeehan** [comment]
The title doesn't match the contents of the issue, please edit and reopen or open a new issue clearly describing the problem.
