### ISSUE TITLE
[Iceberg] Introduce Rolling forward to snapshot with Presto Procedure on Iceberg Table

### ISSUE THREAD

**Issue by agrawalreetika** [prestodb/presto#20881]
The current existing pedicure `rollback_to_snapshot` (https://prestodb.io/docs/current/connector/iceberg.html#id2) in the Iceberg connector allows only rolling forward to an old snapshot but we can't roll forward to a different snapshot of ta Iceberg Table.

We can either introduce a new procedure that can roll-back and roll-forward to snapshot Or we can make API changes in the current procedure to support roll-forward as well.

**Detailed Scenarios -** 

```
presto> SELECT snapshot_id FROM iceberg_data.example_03."nyc_taxis$snapshots" ORDER BY committed_at;

     snapshot_id     
---------------------
 8024334964341481551 
 7403362082601095321 
 2277190760803302730 
(3 rows)
```

Query 20230627_095703_00010_nc43s, FINISHED, 1 node
Splits: 19 total, 19 done (100.00%)
0:02 [3 rows, 1.57KB] [1 rows/s, 844B/s]

```
presto> INSERT INTO iceberg_data.example_03.nyc_taxis VALUES (5, 1000379, 1.8, 15.32, 'N');
INSERT: 1 row
```

Query 20230627_095757_00012_nc43s, FINISHED, 1 node
Splits: 35 total, 35 done (100.00%)
0:05 [0 rows, 0B] [0 rows/s, 0B/s]

```
presto> SELECT snapshot_id FROM iceberg_data.example_03."nyc_taxis$snapshots" ORDER BY committed_at;
     snapshot_id     
---------------------
 8024334964341481551 
 7403362082601095321 
 2277190760803302730 
 2721650197513671833 
(4 rows)
```

Query 20230627_095806_00013_nc43s, FINISHED, 1 node
Splits: 19 total, 19 done (100.00%)
0:02 [4 rows, 2.1KB] [2 rows/s, 1.09KB/s]

```
presto> SELECT snapshot_id,committed_at FROM iceberg_data.example_03."nyc_taxis$snapshots" ORDER BY committed_at;
     snapshot_id     |        committed_at         
---------------------+-----------------------------
 8024334964341481551 | 2023-06-22 12:19:39.242 UTC 
 7403362082601095321 | 2023-06-22 19:00:22.942 UTC 
 2277190760803302730 | 2023-06-22 19:37:19.518 UTC 
 2721650197513671833 | 2023-06-27 09:57:59.089 UTC 
(4 rows)
```

Query 20230627_100113_00014_nc43s, FINISHED, 1 node
Splits: 19 total, 19 done (100.00%)
0:02 [4 rows, 2.1KB] [2 rows/s, 1.09KB/s]

```
presto> CALL iceberg_data.system.rollback_to_snapshot('example_03', 'nyc_taxis', 7403362082601095321);
CALL
```

```
presto> select * from iceberg_data.example_03.nyc_taxis;
 vendor_id | trip_id | trip_distance | fare_amount | store_and_fwd_flag 
-----------+---------+---------------+-------------+--------------------
         1 | 1000371 | 1.80          | 15.32       | N                  
         2 | 1000372 | 2.50          | 22.15       | N                  
         2 | 1000373 | 0.90          | 9.01        | N                  
         3 | 1000375 | 1.80          | 99.32       | Y                  
         1 | 1000374 | 8.40          | 42.13       | Y                  
(5 rows)
```

Query 20230627_100448_00016_nc43s, FINISHED, 1 node
Splits: 18 total, 18 done (100.00%)
0:01 [5 rows, 2.13KB] [6 rows/s, 2.78KB/s]

`presto> CALL iceberg_data.system.rollback_to_snapshot('example_03', 'nyc_taxis', 2721650197513671833);`
Query 20230627_100503_00017_nc43s failed: Cannot roll back to snapshot, not an ancestor of the current state: 272

**Comment by agrawalreetika** [comment]
Hong Wei Zhang, I have created this issue here. You can raise a PR here.

**Comment by Hank27-zhang** [comment]
@agrawalreetika I submitted a PR https://github.com/prestodb/presto/pull/21073, but I'm not able to assign the issue to me.

**Comment by agrawalreetika** [comment]
Closing this in favor of https://github.com/prestodb/presto/pull/23567
