### ISSUE TITLE
[Native] Incorrect results for empty grouping sets

### ISSUE THREAD

**Issue by mknegi** [prestodb/presto#20911]
## Expected Behavior
SELECT SUM(CAST(quantity AS BIGINT)) FROM lineitem WHERE quantity < 0 GROUP BY GROUPING SETS ((), ())

## Current Behavior
Query fails with the following differences:
```
java.lang.AssertionError: For query: 
 SELECT SUM(CAST(quantity AS BIGINT)) FROM lineitem WHERE quantity < 0 GROUP BY GROUPING SETS ((), ())
not equal
Actual rows (up to 100 of 0 extra rows shown, 0 rows in total):
    
Expected rows (up to 100 of 2 missing rows shown, 2 rows in total):
    [null]
    [null]
```

**Comment by aditi-pandit** [comment]
In this sql 
`SELECT SUM(CAST(quantity AS BIGINT)) FROM lineitem WHERE quantity < 0 GROUP BY GROUPING SETS ((), ())`

there are no input rows to the GroupId.

Since GROUPING SET {} is a global aggregation, the expectation is that there should be a single output row with NULL values. The GroupId operator in Velox doesn't generate that output.

**Comment by aditi-pandit** [comment]
`SELECT SUM(CAST(quantity AS BIGINT)) FROM lineitem WHERE quantity < 0 GROUP BY GROUPING SETS (()) `
gets planned as an aggregate function, and that correctly gives a single row with NULL values. 

The problem happens only when there are 2 empty grouping sets which is a bit contrived.

**Comment by yzhang1991** [comment]
@steveburnett This is another known issue that might need to be documented.

**Comment by aditi-pandit** [comment]
HashAggregation Java operator has some special logic for global aggregations for grouping sets that returns this row with NULLs for empty grouping sets
https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/operator/HashAggregationOperator.java#L622

The operator needs information about groupingSets from Aggregation Node for it. fields produceDefaultOutput and globalAggregationGroupIds 
https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/operator/HashAggregationOperator.java#L66

This logic is missing in C++ HashAgg.
