### ISSUE TITLE
Presto Connector : Cant connect to AWS S3 

### ISSUE THREAD

**Issue by akshithrajesh290** [prestodb/presto#20934]
I had followed the documentation provided by presto , but however I couldn't able to establish the connection , I tried the below configuration :

**hive.properties** is the file name

connector.name=hive-hadoop2
hive.metastore.uri=thrift:jdbc:mariadb://md7wf1g369xf22.cluz8hwxjhb6.us-east-2.rds.amazonaws.com:3306/organization5791930186914171?useSSL=true&enabledSslProtocolSuites=TLSv1,TLSv1.1,TLSv1.2&serverSslCert=/databricks/common/mysql-ssl-ca-cert.crt
hive.s3.endpoint=https://databricks-workspace-stack-3545e-metastore-bucket.s3-us-east-2.amazonaws.com
hive.s3.aws-access-key=
hive.s3.aws-secret-key= 

[](https://prestodb.io/docs/current/connector/hive.html#s3-configuration-properties)

Error :  
prestodb-arex       | 6) Error injecting constructor, java.lang.IllegalArgumentException: metastoreUri host is missing: thrift:jdbc:mariadb://md7wf1g369xf22.cluz8hwxjhb6.us-east-2.rds.amazonaws.com:3306/organization5791930186914171?useSSL=true&enabledSslProtocolSuites=TLSv1 

Can someone let em know the right way to connect S£ from presto ?

**Comment by agrawalreetika** [comment]
This looks duplicate to https://github.com/prestodb/presto/issues/20935
