### ISSUE TITLE
Presto Cant able to Connect to S3

### ISSUE THREAD

**Issue by akshithrajesh290** [prestodb/presto#20935]
had followed the documentation provided by presto , but however I couldn't able to establish the connection , I tried the below configuration :

hive.properties is the file name

connector.name=hive-hadoop2
hive.metastore.uri=thrift:jdbc:mariadb://md7wf1g369xf22.cluz8hwxjhb6.us-east-2.rds.amazonaws.com:3306/organization5791930186914171?useSSL=true&enabledSslProtocolSuites=TLSv1,TLSv1.1,TLSv1.2&serverSslCert=/databricks/common/mysql-ssl-ca-cert.crt
hive.s3.endpoint=https://databricks-workspace-stack-3545e-metastore-bucket.s3-us-east-2.amazonaws.com/
hive.s3.aws-access-key=
hive.s3.aws-secret-key=

Error :
prestodb-arex | 6) Error injecting constructor, java.lang.IllegalArgumentException: metastoreUri host is missing: thrift:jdbc:mariadb://md7wf1g369xf22.cluz8hwxjhb6.us-east-2.rds.amazonaws.com:3306/organization5791930186914171?useSSL=true&enabledSslProtocolSuites=TLSv1

Can someone let em know the right way to connect S£ from presto ?

**Comment by agrawalreetika** [comment]
Hi @akshithrajesh290 
Minimal you require HMS thrift URI to configure the connector. I see you have provided wrong configuration here.

You can find the hive connector configuration details here - https://prestodb.io/docs/current/connector/hive.html#configuration

**Comment by akshithrajesh290** [comment]
@agrawalreetika   I had gone through your medium Article :

[](https://medium.com/@reetikaagrawal/query-delta-table-using-presto-b4846d09d5c)

I want to connect to S3 using Delta Connector :

connector.name=delta
hive.metastore.uri=thrift://example.net:9083

So in  hive.metastore.uri what values do I need to provide so that I can establish the connection to S3 Bucket ?


I am bit confused with below configuration :

**connector.name**=delta
**hive.metastore.uri**=thrift:jdbc:mariadb://md7wf1g369xf22.cluz8hwxjhb6.us-east-2.rds.amazonaws.com:3306/organization5791930186914171?useSSL=true&enabledSslProtocolSuites=TLSv1,TLSv1.1,TLSv1.2&serverSslCert=/databricks/common/mysql-ssl-ca-cert.crt
**hive.s3.endpoint**=https://databricks-workspace-stack-3545e-metastore-bucket.s3-us-east-2.amazonaws.com
**hive.s3.aws-access-key**=
**hive.s3.aws-secret-key**=

**Comment by agrawalreetika** [comment]
@akshithrajesh290, 
In the case of the Delta table since Metadata is also stored in the Filesystem along with the metadata and Presto Delta connector allows us to query directly the Delta table location in the Query like given in 2nd example [here](https://prestodb.io/docs/current/connector/deltalake.html#examples)

So you can try the below configuration if you already don't have your tables registered in any metastore and see if that works (This may allow you to start the Presto server since there is no check for liveness  check for thrift uri and `hive.metastore.uri` is a required filed of the catalog)  -

```
connector.name=delta
hive.metastore.uri=thrift://localhost:9083
hive.s3.aws-access-key=<s3-access-key>
hive.s3.aws-secret-key=<s3-secret-key>
```

**Comment by akshithrajesh290** [comment]
@agrawalreetika  Thanks for the response 

for hive.metastore.uri=**thrift://localhost:9083**  I am using the metastore uri which I received from the databricks 

metastore_url = sc._jsc.hadoopConfiguration().get("javax.jdo.option.ConnectionURL")
print(metastore_url)


But I assure this might be wrong , so can you please let me know for S3 from where I can get the metastore url ?

This is where I got blocked

**Comment by agrawalreetika** [comment]
@akshithrajesh290 You will have to check your Databricks cluster, if you have metastore there then on which host you have your metastore service running that's where metadata would be stored for your tables.
You will have to provide the same here. I am not sure, about Databricks environment so not really sure about the exact place to find metastore host.

**Comment by akshithrajesh290** [comment]
@agrawalreetika  :  Thanks for your your immense help on this issue.

How about S3 bucket I guess in your medium article you had connected to S3 bucket using metastore.uri

So for S3 how can I connect from presto ? even for S3 we need metastore.uri if yes from where can I get that

**Comment by agrawalreetika** [comment]
As we discussed about this, we require a valid Metastore URI to configure in the Delta catalog.
@akshithrajesh290 if you don't have any further questions,  can we close this?

**Comment by rajesh-machan** [comment]
@agrawalreetika  Sure we can close the ticket,  Just a small request, if you have any document where we can connect to the S3 bucket with all the connector details  like  from where can we get the metadata from S3 and how can we configure that would be really  helpful 

Reached out to Databricks, and they are not supporting connecting to Databricks unity catalog with presto but supporting with Trino and it's still in the Beta Phase and not publicly available

**Comment by agrawalreetika** [comment]
@rajesh-machan, 
Thanks for confirming.
S3-related configuration details are documented here https://prestodb.io/docs/current/connector/hive.html#amazon-s3-configuration
If you are on s3, then you can register your existing Delta table to AWS Glue. And Use that as metastore for Presto Access.
