### ISSUE TITLE
Typo in bitwise_right_shift documentation (value, shift, digits) 

### ISSUE THREAD

**Issue by laithsakka** [prestodb/presto#20942]
https://prestodb.io/docs/current/functions/bitwise.html

bitwise_right_shift(value, shift, digits) → [same as value][#](https://prestodb.io/docs/current/functions/bitwise.html#bitwise_right_shift)
there is only two inputs to bitwise_right_shift digits is no input.

**Comment by laithsakka** [comment]
its not bug its typo. not sure how to change label

**Comment by tdcmeehan** [comment]
For simplicity let's consider a typo in docs to be a bug.

**Comment by steveburnett** [comment]
> For simplicity let's consider a typo in docs to be a bug.

Works for me!

**Comment by Akanksha-kedia** [comment]
hi team, can i work in this, if yes please assign me
