### ISSUE TITLE
describe table works but select give timeout exception any idea ? 

### ISSUE THREAD

**Issue by techgeekmaster99** [prestodb/presto#20999]
## Describe the problem you faced
Connected presto and pinot , Pinot is running on one of the Cloud's VM . presto is running in my local machine , all ports are enabled and verified still facing issue .
presto:default> DESCRIBE pinot.default.transcript;
  Column   |   Type    | Extra |  Comment
-----------+-----------+-------+-----------
 studentid | integer   |       | DIMENSION
 firstname | varchar   |       | DIMENSION
 lastname  | varchar   |       | DIMENSION
 score     | double    |       | METRIC
 gender    | varchar   |       | DIMENSION
 subject   | varchar   |       | DIMENSION
 timestamp | timestamp |       | TIME
(7 rows)

Query 20230929_174802_00027_nwnbt, FINISHED, 1 node
Splits: 19 total, 19 done (100.00%)
[Latency: client-side: 254ms, server-side: 242ms] [7 rows, 550B] [28 rows/s, 2.22KB/s]

presto:default> SELECT * FROM pinot.default.transcript;
Query 20230929_174813_00028_nwnbt failed: java.net.SocketTimeoutException: Connect Timeout

presto:default> SELECT * FROM transcript;
Query 20230929_175839_00029_nwnbt failed: java.net.SocketTimeoutException: Connect Timeout
* A clear and concise description of the problem.
* Was this working before or is this a first try?
* If this worked before, then what has changed that recently?  
* Provide table DDLs and `` EXPLAIN ANALYZE `` for your Presto queries.

## Environment Description

* Presto version used:
* Storage (HDFS/S3/GCS..):
* Data source and connectors or catalogs used:
* Deployment (Cloud or On-prem):
* [Pastebin](https://pastebin.com/) link to the complete debug logs:

## Steps To Reproduce

1.
2.
3.
4.

**Comment by tdcmeehan** [comment]
Please ask this question in the Presto Slack, thanks!  https://communityinviter.com/apps/prestodb/prestodb
