### ISSUE TITLE
FROM_UNIXTIME generate a timestamp that does not fit as int64_t milliseconds

### ISSUE THREAD

**Issue by laithsakka** [prestodb/presto#21025]
I need help with something, 
SELECT TO_UNIXTIME(FROM_UNIXTIME(3.87111e+37)) give me as output 9223372036854800. 
this number 9223372036854800 will overflow if we try to store it in int64_t as milliseconds.
presto shuffles serialize a timestamp as int64_t(millis).
is that a bug in FROM_UNIXTIME? or am i missing something

@mbasmanova

**Comment by mbasmanova** [comment]
CC: @tdcmeehan @aditi-pandit @kaikalur @amitkdutta

**Comment by laithsakka** [comment]
@tdcmeehan  thanks for responding i think the title and message is misleading, the output of to_unixtime is 9223372036854800 which means that FROM_UNIXTIME generated a time stamps that can represent 9223372036854800.
so the problem is in FROM_UNIXTIME, it should return the max time stamp that can be serialized to int64_t as milli instead,

**Comment by laithsakka** [comment]
updated title and text for clarifications,

**Comment by laithsakka** [comment]
vs (Velox implementation strict the output to the max possible)
FOLLY_ALWAYS_INLINE std::optional<Timestamp> fromUnixtime(double unixtime) {
  if (UNLIKELY(std::isnan(unixtime))) {
    return Timestamp(0, 0);
  }

  static const int64_t kMax = std::numeric_limits<int64_t>::max();
  static const int64_t kMin = std::numeric_limits<int64_t>::min();

  // On some compilers if we cast kMax to a double, we can get a number larger
  // than 'kMax'. This will allow 'unixtime' values > 'kMax'. The workaround
  // here is to use uint64_t to represent ('kMax' + 1), which can be represented
  // exactly as double. We then check if the difference with 'unixtime' <= 1.
  if (UNLIKELY((static_cast<uint64_t>(kMax) + 1) - unixtime <= 1)) {
    return Timestamp::maxMillis();
  }

  if (UNLIKELY(unixtime <= kMin)) {
    return Timestamp::minMillis();
  }

  if (UNLIKELY(std::isinf(unixtime))) {
    return unixtime < 0 ? Timestamp::minMillis() : Timestamp::maxMillis();
  }

  auto seconds = std::floor(unixtime);
  auto nanos = unixtime - seconds;
  return Timestamp(seconds, nanos * kNanosecondsInSecond);
}

**Comment by laithsakka** [comment]
9223372036854800 is the time in seconds when we conver that to milli we do 9223372036854800*1000

**Comment by laithsakka** [comment]
> Thanks for clarifying, but I think I still don't understand. `9223372036854800` doesn't overflow in 64 bits. Is the bug that `9223372036854800` is wrong? Do you have a concrete example of differing values between Velox and Presto Java that we can look at?

the example above FROM_UNIXTIME(3.87111e+37) is one.
this PR also has related context, In velox we restrict that any timestamp should not overflow when represents as milli in int64_t and i assume same is in presto?
https://l.workplace.com/l.php?u=https%3A%2F%2Fgithub.com%2Ffacebookincubator%2Fvelox%2Fpull%2F6836%2Ffiles&h=AT0TPTVLC7PorRgJP8dNPZ5fQ8haX35t8WxVMDuriaeSlUKaYhGhjR5jw9bdNg42U6g4SKaGST4s0jy6W-Gym9CWZf4N5hhTtldHy-phFh-QYILAtDaFpttKQ--Lab9sFrezuXjJoy3bAJpAWgqVSNgJXISrOo32du5PohKr2GCPm4PXEA

**Comment by laithsakka** [comment]
remove velox implementation because i do not think its correct also.

**Comment by laithsakka** [comment]
The condition under which we return    imestamp::maxMillis() is wrong even in Velox, we  should not be using kMax but rather TimeStamp::kMaxSeconds
basically if the unixTime is more than TimeStamp::MaxSeconds we shall return TimeStamp::max 
and if unixTime<TimeStamp::MinSeconds  we shall return TimeStamp::min

**Comment by tdcmeehan** [comment]
I am still finding it hard to understand what the bug is from the descriptions above.  Is the bug that there is an overflow?  Or is the bug that the range is being truncated?  If it's the former, there is no overflow--the result is truncated by `Math.round` per your code snippet.

**Comment by laithsakka** [comment]
@mbasmanova  any thoughts?

**Comment by mbasmanova** [comment]
@laithsakka 

Laith, I took a look into this. Here is what I'm seeing.

In Presto, timestamps are stored in memory as 64-bit integers, Java's long.

Max signed 64-bit integer is: 9,223,372,036,854,775,807

in Presto, from_unixtime(3.87111e+37) returns a Timestamp whose value is 9,223,372,036,854,775,807. This value can be shuffled fine.

In Presto to_unixtime(from_unixtime(3.87111e+37)) returns a double: 9.223372036854776E15. This is an approximation of timestamp's long value * 1000. This value can be shuffled fine as well because it is not a Timestamp, but a double.

In Velox, Timestamp::kMaxSeconds is 9223372036854775, which is a maximum number of seconds that can be represented in milliseconds using 64-bit integer, i.e. 9,223,372,036,854,775,000. (We are short of 807 milliseconds from absolute max.)

In Velox, Timestamp::maxMillis() is a Timestamp with 9223372036854775 second 807000000 nanoseconds. This matches max value in Presto.

Hope this helps.
