### ISSUE TITLE
[ARM][UBUNTU] library not found: /nativelib/Linux-aarch64/libhadoop.so

### ISSUE THREAD

**Issue by leosanqing** [prestodb/presto#21067]
## Your Environment

* Presto version used: 0.283
* Storage (HDFS/S3/GCS..): HDFS(Hadoop3.2)
* Data source and connector used: hive hudi
* Deployment (Cloud or On-prem): On-prem 
* [Pastebin](https://pastebin.com/) link to the complete debug logs: https://pastebin.com/FhGhVUiZ
## Current Behavior
When I use ` bin/launcher run` cmd to run presto server, It throws exceptions

## Possible Solution
I saw there has some PR to resolve this error like this(https://github.com/prestodb/presto-hadoop-apache2/pull/59), and this is merged into master, But I don't know  how to  package this and fix it.

**Comment by imjalpreet** [comment]
Duplicate to: https://github.com/prestodb/presto/issues/19981

**Comment by tdcmeehan** [comment]
Closing in favor of #19981
