### ISSUE TITLE
Query details UI missing tasks list

### ISSUE THREAD

**Issue by pranjalssh** [prestodb/presto#21081]
There is a recent regression in presto query UI where it does not print information for all tasks

## Your Environment

* Presto version used: 0.284-edge24

## Expected Behavior
Query details UI should print a list of tasks for each stage. Example of how it worked in previous presto versions:
![image](https://github.com/prestodb/presto/assets/14260275/503d6d39-8fa3-4fe9-93e6-26b77e0b2b70)

## Current Behavior
No list of tasks is printed, making it impossible to debug queries in Presto
![image](https://github.com/prestodb/presto/assets/14260275/4a69383a-6e4b-4f02-a14a-309a14f6ece6)

## Steps to Reproduce
Open query details UI using URL like: /ui/query.html?20231009_213130_04267_2vtkr

Couple PRs which might be related:

* https://github.com/prestodb/presto/pull/20833
* https://github.com/prestodb/presto/pull/20697

**Comment by pranjalssh** [comment]
Cc @yhwang

**Comment by yhwang** [comment]
I am able to reproduce the empty task list issue. The root cause is that the [reachable](https://www.npmjs.com/package/reactable) is incompatible with react v18. It has no update for 5+ years. Need to find another react table component to replace it.

**Comment by yhwang** [comment]
Suggestion from @pranjalssh 
Another UX enhancement: having a wider column for the `Host` column which has an IPv6 address

![image (2)](https://github.com/prestodb/presto/assets/1147320/08c93c0d-a544-4036-8173-5dcc9c0345b6)

**Comment by pranjalssh** [comment]
Thanks @yhwang for fixing!
