### ISSUE TITLE
Improve layout of table for statistics in docs

### ISSUE THREAD

**Issue by Akanksha-kedia** [prestodb/presto#21110]
column, description, notes.

Returns approximated statistics for the named table or for the results of a query. Returns NULL for any statistics that are not populated or unavailable on the data source.

Statistics are returned as a row for 
<img width="1040" alt="Screenshot 2023-10-11 at 3 50 30 PM" src="https://github.com/prestodb/presto/assets/89628774/12f6039c-c69a-44f6-a2b7-b6cd1ab715ec">
<img width="720" alt="Screenshot 2023-10-11 at 3 50 43 PM" src="https://github.com/prestodb/presto/assets/89628774/0eaecd17-9588-489b-8d38-614bd0e9c664">
each column, plus a summary row for the table (identifiable by a NULL value for column_name). The following table lists the returned columns and what statistics they represent. Any additional statistics collected on the data source, other than those listed here, are not included.

**Comment by steveburnett** [comment]
See PR #21112 .
