### ISSUE TITLE
Link to REST API documentation is Missing in Document

### ISSUE THREAD

**Issue by agrawalreetika** [prestodb/presto#21157]
I see there are REST API documentations for node, query, stage, statement & task present here https://github.com/prestodb/presto/tree/master/presto-docs/src/main/sphinx/rest but I couldn't find any link to locate these documents in Main Presto Docs or in any sub-pages.

https://prestodb.io/docs/current/

**Comment by steveburnett** [comment]
Recommend closing this issue, as PR #21183 addresses this and has been merged
