### ISSUE TITLE
Missing plugins document section from Presto Index Section

### ISSUE THREAD

**Issue by agrawalreetika** [prestodb/presto#21155]
Here https://github.com/prestodb/presto/blob/master/presto-docs/src/main/sphinx/index.rst Index page in document mentions about `plugins` content but which seems to be missing from the Presto document Index UI https://prestodb.io/docs/current/

<img width="318" alt="image" src="https://github.com/prestodb/presto/assets/7887476/1cf7d37c-779e-46f9-8033-36cc9c17ade7">

**Comment by steveburnett** [comment]
The plugin documentation files
https://github.com/prestodb/presto/blob/master/presto-docs/src/main/sphinx/index.rst
https://github.com/prestodb/presto/blob/master/presto-docs/src/main/sphinx/plugin.rst 
https://github.com/prestodb/presto/blob/master/presto-docs/src/main/sphinx/plugin/redis-hbo-provider.rst 
are all in master. When I build the docs locally from master, they are present. 
<img width="993" alt="Screenshot 2023-10-20 at 1 50 59 PM" src="https://github.com/prestodb/presto/assets/7013443/ed14f8a4-69f6-40ab-a2fd-a06a39c39f3c">


@wanglinsong , @tdcmeehan suggested you might be able to help us understand when these files are to be published into the [current documentation](https://prestodb.io/docs/0.283/). 

I do not understand the events between merging a docs PR into master and that documentation content being published in the current documentation for Presto. I'd personally like to understand this as part of the documentation process, and generally to understand this for contributors who contribute documentation. 

Could you explain 
* the steps involved
* who or what controls moving through those steps
* the time expected for those steps?

Thank you for your help!

**Comment by steveburnett** [comment]
> @wanglinsong , @tdcmeehan suggested you might be able to help us understand when these files are to be published into the [current documentation](https://prestodb.io/docs/0.283/).
> 
> I do not understand the events between merging a docs PR into master and that documentation content being published in the current documentation for Presto. I'd personally like to understand this as part of the documentation process, and generally to understand this for contributors who contribute documentation.
> 
> Could you explain
> 
> * the steps involved
> * who or what controls moving through those steps
> * the time expected for those steps?
> 
> Thank you for your help!

The missing documentation has been published with the 0.284 release. See [Plugins, in the current documentation](https://prestodb.io/docs/0.284/plugin.html). 

![Image](https://github.com/prestodb/presto/assets/7013443/22250763-2b73-4e49-98fc-f9d0671da390)

While I would still like to understand the events between merging a docs PR into master and that documentation content being published in the current documentation for Presto, the problem that this issue was opened about is solved and I think this issue can be closed.
