### ISSUE TITLE
Add support for NativeQueryRunner to firstly respect the value set in environment variables

### ISSUE THREAD

**Issue by kewang1024** [prestodb/presto#21162]
Internally many people have set IntelliJ with environment variables, https://github.com/prestodb/presto/pull/21017 changed that behavior.

So it's better that we add support for NativeQueryRunner to firstly respect the value set in environment variables so that people don't have to change their IntelliJ settings.

**Comment by ZacBlanco** [comment]
Closing now that #21163 was merged
