### ISSUE TITLE
[Native] Query with reduce_agg() failing with "!states->isNullAt(i) Lambda expressions in reduce_agg should not return null for non-null inputs" against velox

### ISSUE THREAD

**Issue by mknegi** [prestodb/presto#21179]
## Expected Behavior

```
Following query currently fails if run against the c++ worker:

select reduce_agg(x, 0, (x, y)->try(x+y), (x, y)->try(x+y)) from (values 2817, 9223372036854775807) AS T(x)

Error returned: VeloxUserError: !states->isNullAt(i) Lambda expressions in reduce_agg should not return null for non-null inputs

This Query was supposed to return NULL as try(x+y) would have resulted in overflow for bigint.
```

**Comment by aditi-pandit** [comment]
@mbasmanova : This new error seems "Lambda expressions in reduce_agg should not return null for non-null inputs" is intentional.

Just checking you want to document this case as well ?

**Comment by mbasmanova** [comment]
@aditi-pandit Aditi, I believe this is already documented:

https://facebookincubator.github.io/velox/functions/presto/aggregate.html#reduce_agg

"Throws an error if initialState is NULL or inputFunction or combineFunction returns a NULL."

**Comment by aditi-pandit** [comment]
@mbasmanova : From the Presto usage perspective, this is a regression in behavior as java eval supported functions returning null.

This would be called out in Prestissimo documentation. Was just checking with you that is okay.

@steveburnett

**Comment by mbasmanova** [comment]
@aditi-pandit 

> From the Presto usage perspective, this is a regression in behavior as java eval supported functions returning null.

Aditi, this is not a regression as Java eval is buggy. See https://github.com/facebookincubator/velox/issues/6434

**Comment by aditi-pandit** [comment]
@steveburnett : Please document reduce_agg in Prestissimo doc providing details about this behavior.

**Comment by tdcmeehan** [comment]
We can close this once documentation is added for this difference in behavior.
