### ISSUE TITLE
Make ParquetFileWriter final

### ISSUE THREAD

**Issue by Akanksha-kedia** [prestodb/presto#21217]
Making a class final in Java means that the class cannot be subclassed. This is particularly useful when you want to create a class with methods that should not be overridden, or to prevent inheritance for security or design reasons.

Here's what it would look like to make your ParquetFileWrite class final:

public final class ParquetFileWrite {
    // class content
}

In this case, no other class can extend ParquetFileWrite. This ensures that all instances of ParquetFileWrite have exactly the same behavior, which can make code easier to reason about and can prevent bugs that might be introduced by subclasses changing behavior. However, it also makes the class less flexible and can inhibit reuse of code through inheritance.

**Comment by tdcmeehan** [comment]
The contents of this issue look too generic to be useful.  Also, this specific change just isn't needed.  Please only raise issues for changes that actually require discussion.  If you want guidance, please reach out on Slack, in particular the #dev channel.
