### ISSUE TITLE
Refactored TestTimestampWithTimeZone tests

### ISSUE THREAD

**Issue by Akanksha-kedia** [prestodb/presto#21210]
## Your Environment

* Presto version used:
* Storage (HDFS/S3/GCS..):
* Data source and connector used:
* Deployment (Cloud or On-prem):
* [Pastebin](https://pastebin.com/) link to the complete debug logs:

## Steps to Reproduce

1.
2.
3.
4.

**Comment by tdcmeehan** [comment]
Please feel free to reopen with a more descriptive issue.  It is not possible to understand what this issue is about given the details above.
