### ISSUE TITLE
[Native] Unused node.memory_gb config property in Prestissimo

### ISSUE THREAD

**Issue by karteekmurthys** [prestodb/presto#21293]
node.memory_gb as per definition in the readme [here](https://github.com/prestodb/presto/blob/master/presto-native-execution/scripts/release-centos-dockerfile/README.md#prestissimo---runtime-configuration-and-settings) controls amount of system memory set for PrestoServer, but in practice this config is not used at all.

If there is no use of this config, is it safe to clean up the related code in 
presto-native-execution/presto_cpp/main/common/Configs.cpp ?

cc: @xiaoxmeng @mbasmanova 

## Your Environment

* Presto version used:
* Storage (HDFS/S3/GCS..):
* Data source and connector used:
* Deployment (Cloud or On-prem):
* [Pastebin](https://pastebin.com/) link to the complete debug logs:

## Steps to Reproduce

1.
2.
3.
4.

**Comment by karteekmurthys** [comment]
cc: @majetideepak

**Comment by majetideepak** [comment]
We removed this config here https://github.com/prestodb/presto/pull/20351
We can remove this config. I opened a PR here https://github.com/prestodb/presto/pull/21661
