### ISSUE TITLE
IGNORE NULLs in Window aggregates doesn't seem to work

### ISSUE THREAD

**Issue by aditi-pandit** [prestodb/presto#21304]
Window aggregate SQL support IGNORE NULLs clauses. It seems like the results with and without this clause are the same wrt NULLs in the input data.

Examples
Function array_agg(c) over (partition by a order by b rows between 1 preceding and current row)  with and without IGNORE NULLs retuns the same results.
```
presto:tiny> select a, array_agg(c) over (partition by a order by b rows between 1 preceding and current row) from (values (1, 1, 3), (1, 2, null), (1, 4, 2)) as t(a, b, c);
 a |   _col1   
---+-----------
 1 | [3]       
 1 | [3, null] 
 1 | [null, 2] 
(3 rows)
```

```
presto:tiny> select a, array_agg(c) ignore nulls over (partition by a order by b rows between 1 preceding and current row) from (values (1, 1, 3), (1, 2, null), (1, 4, 2)) as t(a, b, c);
 a |   _col1   
---+-----------
 1 | [3]       
 1 | [3, null] 
 1 | [null, 2] 
(3 rows)

```
## Expected Behavior
array_agg as a regular aggregate doesn't have any explicit IGNORE NULLs option so there isn't a basis for comparison. But the results I would've expected is 

```
presto:tiny> select a, array_agg(c) ignore nulls over (partition by a order by b rows between 1 preceding and current row) from (values (1, 1, 3), (1, 2, null), (1, 4, 2)) as t(a, b, c);
 a |   _col1   
---+-----------
 1 | [3]       
 1 | [3] 
 1 | [2] 
(3 rows)
```

Most other systems I checked like DuckDB error on IGNORE NULLs in aggregates. If we don't support any special behavior, then Presto should error as well.

**Comment by Akanksha-kedia** [comment]
Postgresql:

<img width="583" alt="Screenshot 2023-11-17 at 5 40 14 PM" src="https://github.com/prestodb/presto/assets/89628774/fe6db3e6-544c-4ba5-8556-d81d492305ed">

Mysql:
<img width="567" alt="Screenshot 2023-11-17 at 5 41 47 PM" src="https://github.com/prestodb/presto/assets/89628774/2edc90d1-ae3f-485f-b00e-77eee5fe2a6e">

**Comment by aditi-pandit** [comment]
@mbasmanova : Any thoughts ?

**Comment by mbasmanova** [comment]
@aditi-pandit Based on documentation, IGNORE NULLS applies only to Value functions:

https://prestodb.io/docs/current/functions/window.html#value-functions

```
Value functions provide an option to specify how null values should be treated when evaluating the function. Nulls can either be ignored (IGNORE NULLS) or respected (RESPECT NULLS). By default, null values are respected. If IGNORE NULLS is specified, all rows where the value expression is null are excluded from the calculation. If IGNORE NULLS is specified and the value expression is null for all rows, the default_value is returned, or if it is not specified, null is returned.
```

I wonder what the SQL standard says about that. Most aggregate functions ignore nulls anyway, hence, maybe it is considered Ok to ignore this clause, but I agree it is confusing.

CC: @kaikalur

**Comment by aditi-pandit** [comment]
@mbasmanova : Trying to research your question. What is the SQL version we are expected to follow in Presto ?

**Comment by mbasmanova** [comment]
@tdcmeehan 

> What is the SQL version we are expected to follow in Presto ?

Tim, do you know? I remember a discussion about upgrading Presto SQL to support SQL 2016, so I assume currently it supports something a bit earlier.

**Comment by tdcmeehan** [comment]
I don't think we officially target any particular version, but if it is present in any version (even a later version), then that is given weight and it's assumed that we would eventually desire to support that.

Based on my quick read on the spec, I think we should only be allowed to specify "null treatment" for:

1) The first or last value functions
2) The lead and lag functions

[See this note from the Postgres documentation as well](https://www.postgresql.org/docs/8.4/functions-window.html), who apparently made the deliberate decision to diverge slightly from the spec:

> Note: The SQL standard defines a RESPECT NULLS or IGNORE NULLS option for lead, lag, first_value, last_value, and nth_value. This is not implemented in PostgreSQL: the behavior is always the same as the standard's default, namely RESPECT NULLS. Likewise, the standard's FROM FIRST or FROM LAST option for nth_value is not implemented: only the default FROM FIRST behavior is supported. (You can achieve the result of FROM LAST by reversing the ORDER BY ordering.)

**Comment by aditi-pandit** [comment]
@tdcmeehan, @mbasmanova, @amitkdutta : Seems like we should error for IGNORE NULLS with Window aggregates then ? Though Meta is using such queries.

How do we typically proceed in such cases ?

**Comment by tdcmeehan** [comment]
This seems like a bug, and in my opinion this should a parsing failure if we attempt to use this clause over anything except value functions.  My recommendation would be to emit a warning that this clause does not work for aggregate and ranking window functions.  In the future, we can perhaps throw an error.  Perhaps we could also simply throw a parse error if native execution is enabled, since it appears this will error in Velox anyway.
