### ISSUE TITLE
update joda-time to 2.12.5

### ISSUE THREAD

**Issue by yhwang** [prestodb/presto#21300]
Currently, the version of joda-time is 2.12.2 and some tzdata updates have been added to the newer version. Here are the changes between 2.12.2 to 2.12.5:
```
2023b:
Lebanon delays the start of DST this year. 

2023a:
Egypt now uses DST again, from April through October.
This year Morocco springs forward April 23, not April 30.
Palestine delays the start of DST this year.
Much of Greenland still uses DST from 2024 on.
America/Yellowknife now links to America/Edmonton.
tzselect can now use current time to help infer timezone.
The code now defaults to C99 or later. Fix use of C23 attributes.
```

should the joda-time be updated to 2.12.5 to catch up the changes listed above?

## Expected Behavior or Use Case

When users use timestamps with the timezone and the times fall into the timezone that new rules are added, the correct DST rules can be properly handled. 

## Presto Component, Service, or Connector

joda-time is used in many components. But the version update should be transparent to those components using the joda-time.

## Possible Implementation

Update the version to 2.12.5 with a release note mentioning the JVM shall use 2023c tzdata to make sure the consistency between `joda-time` and `java.util.TimeZone`.

**Comment by yhwang** [comment]
If the decision is `yes`, then I can work on it.
Let me tag someone who reviewed similar PR before:
@jainxrohit @rschlussel @tdcmeehan 
Can you provide some suggestions/comments about this issue?

**Comment by tdcmeehan** [comment]
I think we should proceed, and additionally add some documentation on what cadence and how to pull in up to date TZ information.

**Comment by yhwang** [comment]
@tdcmeehan about the cadence, it should depend on whether there is any timezone update. The timeline of joda-time tzdata updates syncs with the IANA TZdata page. [Here is the subscription link for IANA TZdata](https://mm.icann.org/mailman/listinfo/tz-announce).
