### ISSUE TITLE
Add more Linear Regression functions to Presto

### ISSUE THREAD

**Issue by 8dukongjian** [prestodb/presto#21328]
## Expected Behavior or Use Case

Currently, Presto only has linear regression functions like REGR_INTERCEPT and REGR_SLOPE. Other systems like Databricks, DuckDB, Snowflake and Postgresql, have other functions such as REGR_AVGX, REGR_AVGY, REGR_COUNT, REGR_R2, REGR_SXX, REGR_SXY, and REGR_SYY. It would be worthwhile to add these functions to Presto.

![image](https://github.com/prestodb/presto/assets/31331967/1daff088-6ced-4fbe-b9b8-490ac3daee40)

**Comment by xumingming** [comment]
@tdcmeehan Can you take a look at this? For linear regression function, currently we only have `regr_intercept` and `regr_slope`, while other popular engines(Databricks, DuckDB, Snowflake and Postgresql) have a complete set of functions. We can contribute this part of code if agreed, and will add corresponding implementation in velox.

**Comment by tdcmeehan** [comment]
Agreed that this would be worthwhile, especially if you'll be contributing native versions in Velox.  Can you please add Github issues for each function?

**Comment by 8dukongjian** [comment]
@tdcmeehan Okay, I will contribute to presto first. Do you mean that every function needs to add an issue? These functions are related, I think it should be OK to put them in one issue.

**Comment by 8dukongjian** [comment]
fix in [#21627](https://github.com/prestodb/presto/pull/21627)

**Comment by 8dukongjian** [comment]
Fix in [#21630](https://github.com/prestodb/presto/pull/21630)

**Comment by 8dukongjian** [comment]
@tdcmeehan Would you review it?

**Comment by tdcmeehan** [comment]
Will review, thank you! @8dukongjian @xumingming

**Comment by kewang1024** [comment]
@8dukongjian Hi, we recently found a different behavior between presto java and presto c++ for those functions.

For example, for regr_avgx, 
```
create TABLE test_ke (name varchar, score double, score2 double, ds varchar) WITH 
(
    oncall = 'presto',
    partitioned_by = ARRAY['ds']
)

INSERT INTO test_ke
VALUES
    ('a', 1.1, NAN(), '2023-05-01'),
    ('a', NAN(), 1.0, '2023-05-01'),
    ('b', 0, 1, '2023-05-01'),
    ('b', 2.0, 1, '2023-05-01'),
    ('b', NAN(), NAN(), '2023-05-01'),
    ('c', NAN(), 1, '2023-05-01'),
    ('c', NAN(), 0, '2023-05-01'),
    ('c', NAN(), 2, '2023-05-01')

select regr_avgx(score, score2) FROM test_ke where ds = '2023-05-01' group by name 
In java, it returns
NULL
NULL
1

In cpp, it returns 
NaN
NaN
1
```
