### ISSUE TITLE
[Native] - Missing decimal signature for aggregate function approx_distinct() in velox

### ISSUE THREAD

**Issue by mknegi** [prestodb/presto#21331]
Query with aggregate function approx_distinct is failing with missing decimal signature in velox.

## Current Behavior

SELECT approx_distinct(CAST(custkey AS DECIMAL(18, 0))) FROM orders;

```
Output Against c++ Worker:
Query 20231106_150303_00058_nbggi failed: Aggregate function signature is not supported: presto.default.approx_distinct(DECIMAL(18, 0)). Supported signatures: (boolean) -> varbinary -> bigint, 
(boolean,double) -> varbinary -> bigint, (tinyint) -> varbinary -> bigint, (tinyint,double) -> varbinary -> bigint, 
(smallint) -> varbinary -> bigint, (smallint,double) -> varbinary -> bigint, (integer) -> varbinary -> bigint, 
(integer,double) -> varbinary -> bigint, (bigint) -> varbinary -> bigint, (bigint,double) -> varbinary -> bigint, 
(real) -> varbinary -> bigint, (real,double) -> varbinary -> bigint, (double) -> varbinary -> bigint, 
(double,double) -> varbinary -> bigint, (varchar) -> varbinary -> bigint, (varchar,double) -> varbinary -> bigint, 
(timestamp) -> varbinary -> bigint, (timestamp,double) -> varbinary -> bigint, (date) -> varbinary -> bigint, 
(date,double) -> varbinary -> bigint.

```

**Comment by aditi-pandit** [comment]
approx_distinct for DECIMAL is important as it is being used in ANALYZE for decimal columns.

Right now, running ANALYZE for such a table returns

`Aggregate function signature is not supported: presto.default.approx_distinct(DECIMAL(7, 2)). Supported signatures: (boolean) -> varbinary -> bigint, (boolean,double) -> varbinary -> bigint, (tinyint) -> varbinary -> bigint, (tinyint,double) -> varbinary -> bigint, (smallint) -> varbinary -> bigint, (smallint,double) -> varbinary -> bigint, (integer) -> varbinary -> bigint, (integer,double) -> varbinary -> bigint, (bigint) -> varbinary -> bigint, (bigint,double) -> varbinary -> bigint, (real) -> varbinary -> bigint, (real,double) -> varbinary -> bigint, (double) -> varbinary -> bigint, (double,double) -> varbinary -> bigint, (varchar) -> varbinary -> bigint, (varchar,double) -> varbinary -> bigint, (timestamp) -> varbinar`
