### ISSUE TITLE
404 on dockerhub / cant pull image

### ISSUE THREAD

**Issue by hbazan-pp** [prestodb/presto#21341]
Dockerhub is returning 404 on https://hub.docker.com/r/ahanaio/prestodb-sandbox
![image](https://github.com/prestodb/presto/assets/90913601/71a3898c-3ad5-4177-ad7d-7310013b6e02)

and getting similar error when pulling image:
![image](https://github.com/prestodb/presto/assets/90913601/62c80b0d-b13a-41e9-8726-617beef1accf)

## Your Environment
I don't think it is related to my environment in any way
## Expected Behavior
Image should be found and pulled

## Current Behavior
404 or access denied error

## Steps to Reproduce
`docker image pull ahanaio/prestodb-sandbox:0.284
`

**Comment by steveburnett** [comment]
The 404'd link https://hub.docker.com/r/ahanaio/prestodb-sandbox is present on the Presto website, on  https://prestodb.io/getting-started/ . When a solution to this 404 is found, that page may need to be updated.

**Comment by hbazan-pp** [comment]
but also docker image pull fails

**Comment by b-schmeling** [comment]
Having the same issue.

**Comment by fastali** [comment]
@steveburnett 
docker seems to have removed this account from the hub or perhaps user deleted the account themselves. what are you guys going to do about it?

**Comment by tdcmeehan** [comment]
Hello folks--can you please use the images found in Presto Foundation? https://hub.docker.com/repository/docker/prestodb/presto/tags?page=1&ordering=last_updated

**Comment by hamer101** [comment]
Just to mention, one has to specify the version to be pulled since getting just the latest results in 
> Error response from daemon: manifest for prestodb/presto:latest not found: manifest unknown: manifest unknown

**Comment by hbazan-pp** [comment]
> Hello folks--can you please use the images found in Presto Foundation? https://hub.docker.com/repository/docker/prestodb/presto/tags?page=1&ordering=last_updated

which one?
 prestodb/presto:0.284 (there's no latest tag) fails to start because there's no /opt/presto-server/etc/config.properties file
there's one named presto-sandbox (like the ahanaio one) but it has no tags at all so it fails to pull

**Comment by wanglinsong** [comment]
Docker hub ahanaio account is discontinued.
https://hub.docker.com/u/prestodb is the one used in OSS Presto (

**Comment by MasterOdin** [comment]
I've setup a fork of the `ahanaio/prestodb-sandbox` image as we were using them as part of our test suite: https://github.com/popsql/prestodb-sandbox, usable from `ghcr.io/popsql/prestodb-sandbox` from 0.281 onward. As a bonus, we publish both `linux/amd64` and `linux/arm64`, something that was lacking from the original images.
