### ISSUE TITLE
Use @TypeParameter to simplify set_union aggregation function

### ISSUE THREAD

**Issue by ZacBlanco** [prestodb/presto#21363]
With the merge of #21316 we can now simplify this aggregation function implementation by using @TypeParameter annotations in the serializer and state factory classes, which means the function can be entirely converted to using the [function annotation framework](http://prestodb.io/docs/0.284/develop/functions.html). This will simplify the implementation and improve maintainability.

**Comment by npochhi** [comment]
Hi! Would like to take this up. I'm assuming the hints provided [here](https://github.com/prestodb/presto/issues/21365#issuecomment-1807445722) would be super helpful for this issue as well.

**Comment by ZacBlanco** [comment]
> I'm assuming the hints provided [here](https://github.com/prestodb/presto/issues/21365#issuecomment-1807445722) would be super helpful for this issue as well.

That is correct

**Comment by tdcmeehan** [comment]
Fixed by #21378
