### ISSUE TITLE
Use @TypeParameter to simplify approx_most_frequent aggregation function

### ISSUE THREAD

**Issue by ZacBlanco** [prestodb/presto#21365]
With the merge of #21316 we can now simplify this aggregation function implementation by using @TypeParameter annotations in the serializer and state factory constructors, which means the function can be entirely converted to using the [function annotation framework](http://prestodb.io/docs/0.284/develop/functions.html). This will simplify the implementation and improve maintainability.

**Comment by sindhunaydu** [comment]
@ZacBlanco I would like to work on this, can you lmk which function needs to be updated with @TypeParameter? Thanks!

**Comment by ZacBlanco** [comment]
All the changes should be contained to the package here: https://github.com/prestodb/presto/tree/master/presto-main/src/main/java/com/facebook/presto/operator/aggregation/approxmostfrequent

You'll need to rewrite the aggregation function implementation inside of `ApproximateMostFrequent.java` using annotations [described by the developer docs](http://prestodb.io/docs/0.284/develop/functions.html), and then update the `ApproximateMostFrequentStateSerializer` and `ApproximateMostFrequentStateFactory` constructors need the `@TypeParameter` annotation added.

**Comment by sindhunaydu** [comment]
@ZacBlanco apologies for the delayed response. I fell ill. I dont think I will able to work on this right now. thanks!

**Comment by tdcmeehan** [comment]
This issue is still open.  See #21418 for a first attempt, and see #21712 which includes a test query that shows it failing for null inputs.
