### ISSUE TITLE
Documentation - update Google Tag Manager script in presto-docs

### ISSUE THREAD

**Issue by steveburnett** [prestodb/presto#21381]
Update Google Tag Manager script in presto-docs. 

```
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-K7GB6F0LBZ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-K7GB6F0LBZ');
</script>
```

replacing 
![image](https://github.com/prestodb/presto/assets/7013443/2a626c06-e862-45dc-b3c2-48280db2bbde)

**Comment by steveburnett** [comment]
I assumed this was in presto-docs as the screenshot is from View Source for the Presto docs (for example, on view-source:https://prestodb.io/docs/0.284/ ). I am not finding the googletagmanager script source in Presto repos to update this. 

@wanglinsong , can you help direct me to where this change needs to be made?

**Comment by wanglinsong** [comment]
https://github.com/prestodb/presto/blob/master/presto-docs/src/main/sphinx/conf.py#L128

**Comment by mcknightd** [comment]
Try to add this block to the [layout file](https://github.com/prestodb/presto/blob/master/presto-docs/src/main/sphinx/_templates/layout.html) 
`{% block extrahead %}

<script async src="https://www.googletagmanager.com/gtag/js?id=G-K7GB6F0LBZ"/script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-K7GB6F0LBZ');
</script>
{% endblock %}`
