### ISSUE TITLE
Keywords in Time Travel syntax for Presto 

### ISSUE THREAD

**Issue by gupteaj** [prestodb/presto#21396]
Presto issue for time travel feature - https://github.com/prestodb/presto/issues/20495
PR for time travel feature - https://github.com/prestodb/presto/pull/20991

Following time travel syntax is used in the above PR. In the PR review,  SQL-specification grammar issue was raised where Presto implementation differs from the SQL standards. This issue is created to decide keywords to be used in Presto implementation. 

Note - SQL standards support only `FOR SYSTEM_TIME AS OF`  syntax. Keyword `SYSTEM_VERSION` is not in the standards.

Presto PR for time travel : 

```
select * from tab1 FOR VERSION AS OF  < bigint type >
select * from tab1 FOR TIMESTAMP AS OF <timestamp with time zone type>

select * from tab1 FOR VERSION AS OF 8772871542276440693;
select * from tab1 FOR TIMESTAMP AS OF TIMESTAMP '2023-08-17 13:29:46.822 America/Los_Angeles';
```

## Expected Behavior or Use Case
SQL Standards 2011 - 

`FOR SYSTEM_TIME AS OF [<point in time 1>](https://jakewheat.github.io/sql-overview/sql-2011-foundation-grammar.html#point-in-time-1)`

For reference, the 2011 spec which introduced time-travel grammar can be found here: https://jakewheat.github.io/sql-overview/sql-2011-foundation-grammar.html#query-system-time-period-specification

### Iceberg references 

https://iceberg.apache.org/docs/latest/hive/#timetravel

```
SELECT * FROM table_a FOR SYSTEM_TIME AS OF '2021-08-09 10:35:57';
SELECT * FROM table_a FOR SYSTEM_VERSION AS OF 1234567;
```

https://iceberg.apache.org/docs/latest/spark-queries/#time-travel

```
-- time travel to October 26, 1986 at 01:21:00
SELECT * FROM prod.db.table TIMESTAMP AS OF '1986-10-26 01:21:00';

-- time travel to snapshot with id 10963874102873L
SELECT * FROM prod.db.table VERSION AS OF 10963874102873;

In addition, FOR SYSTEM_TIME AS OF and FOR SYSTEM_VERSION AS OF clauses are also supported:

SELECT * FROM prod.db.table FOR SYSTEM_TIME AS OF '1986-10-26 01:21:00';
SELECT * FROM prod.db.table FOR SYSTEM_VERSION AS OF 10963874102873;
```

https://github.com/apache/iceberg/issues/7000

following "undocumented" SQL syntax works in Spark 3.1 and 3.2:

`SELECT * FROM <your-db>.<your-table>.snapshot_id.<desired-snapshot-id>`

### Trino 
https://trino.io/docs/current/connector/iceberg.html#time-travel-queries

```
SELECT *
FROM example.testdb.customer_orders FOR VERSION AS OF 8954597067493422955

SELECT *
FROM example.testdb.customer_orders FOR TIMESTAMP AS OF TIMESTAMP '2022-03-23 09:59:29.803 Europe/Vienna'

```
### Databricks  
https://www.databricks.com/blog/2019/02/04/introducing-delta-time-travel-for-large-scale-data-lakes.html

```
SELECT count(*) FROM my_table TIMESTAMP AS OF "2019-01-01 01:30:00.000"

SELECT count(*) FROM my_table VERSION AS OF 5238
```
### Starburst 
https://www.starburst.io/blog/apache-iceberg-time-travel-rollbacks-in-trino/

```
SELECT custkey,name
FROM customer_iceberg FOR VERSION AS OF 5043425904354141100 where custkey = 2732;

SELECT custkey,name
FROM s3lakehouse.demo_tpch.customer_iceberg FOR TIMESTAMP AS OF TIMESTAMP '2022-09-18 07:18:09.002 America/New_York' where custkey = 2732;
```
### Dremio
https://docs.dremio.com/current/reference/sql/commands/apache-iceberg-tables/apache-iceberg-select/#time-travel-queries

```
Time travel query on an Iceberg table using a timestamp
SELECT count(*)
FROM my_table AT TIMESTAMP '2022-07-01 01:30:00.000'

Time travel query on an Iceberg table using a snapshot ID
SELECT *
FROM myTable AT SNAPSHOT '5393090506354317772'
```
### Cloudera 
https://docs.cloudera.com/cdw-runtime/1.5.1/iceberg-how-to/topics/iceberg-hive-time-travel.html

```
SELECT * FROM T 
FOR SYSTEM_TIME AS OF <TIMESTAMP>;

SELECT * FROM t 
FOR SYSTEM_VERSION AS OF <SNAPSHOT_ID>;

```
### Amazon Athena 
https://docs.aws.amazon.com/athena/latest/ug/querying-iceberg-table-data.html#querying-iceberg-time-travel-and-version-travel-queries

`SELECT * FROM iceberg_table FOR TIMESTAMP AS OF TIMESTAMP '2020-01-01 10:00:00 UTC'`

To execute a version travel query (that is, view a consistent snapshot as of a specified version), use FOR VERSION AS OF version after the table name in the SELECT statement, as in the following example.

`SELECT * FROM iceberg_table FOR VERSION AS OF 949530903748831860`

Note - The FOR SYSTEM_TIME AS OF and FOR SYSTEM_VERSION AS OF clauses in Athena engine version 2 have been replaced by the FOR TIMESTAMP AS OF and FOR VERSION AS OF clauses in Athena engine version 3.

## Possible Implementation
Some proposed options are 

1.  Use same syntax from PR  ( FOR TIMESTAMP AS OF / FOR VERSION AS OF ) - non-SQL standards
2.  FOR SYSTEM_TIME AS OF / FOR SYSTEM_VERSION AS OF could be additional alias to (1). e.g use (1) and (2) 
3. Use FOR SYSTEM_TIME AS OF from SQL standards and  version case,  FOR SYSTEM_VERSION AS OF
4.  USE FOR_SYSTEM_TIME AS OF , for version (snapshot id) case, use presto function SYSTEM_VERSION(<snapshot_id>) . e.g select * from tab1 FOR SYSTEM_TIME AS OF SYSTEM_VERSION(1234567890123)
5. USE FOR_SYSTEM_TIME AS OF, for version (snapshot id) , use table specific syntax without any keyword. e.g select * from tab1@1234567890123 ; or something like  select * from tab1.snapshot_id.1234567890123 ;

**Comment by ZacBlanco** [comment]
Thanks for this great write up! I'm glad you included all the current syntx support in other systems. Personally, I'm in the camp that we should do our best to support what's in the SQL spec, but also try to work with other existing syntaxes to make it easier for people coming from other systems to adopt Presto. 

For `VERSION`/`SYSTEM_VERSION` even though it's not in the spec I think there is wide enough support on other platforms to warrant inclusion. If we're trying to mimic support that others systems have I think it should be straightforward to allow `SYSTEM_TIME` to alias the `TIMESTAMP` keyword too. The same goes for `SYSTEM_VERSION`/`VERSION`.

That being said, I think we should support the following syntaxes:

```
% SQL Specification and support from Hive, Spark, Databricks, Cloudera, Trino, 
SELECT * FROM prod.db.table FOR (SYSTEM_TIME|TIMESTAMP) AS OF <timestamp>;
% Close modification of SQL specification support by Iceberg's Hive extensions , Cloudera, and Spark
SELECT * FROM prod.db.table FOR (SYSTEM_VERSION|VERSION) AS OF <snapshot ID>;
```

This amounts to supporting both cases (1) and (2) mentioned at the end of the issue description

**Comment by tdcmeehan** [comment]
Preferring the `SYSTEM_TIME` and `SYSTEM_VERSION` seems sensible, since this most closely follows the spec.  I think we can add support for `TIMESTAMP` and `VERSION`, but keep this as a small note in the docs and prefer the former syntax where possible.

**Comment by tdcmeehan** [comment]
CC: @hantangwangd @ChunxuTang @beinan @imjalpreet @agrawalreetika @s-akhtar-baig @yingsu00  -- any thoughts?

**Comment by hantangwangd** [comment]
Agree to use `SYSTEM_TIME|TIMESTAMP` and `SYSTEM_VERSION|VERSION`. Using a function to fully follow the spec makes the two statements somewhat uncoordinated, and more distant from other existing syntaxes.

**Comment by beinan** [comment]
When considering ecosystem compatibility and large amount of existing user in Trino and Databricks, utilizing 'FOR VERSION AS OF' and 'FOR TIMESTAMP AS OF TIMESTAMP' can be beneficial. These clauses can potentially lower migration costs for users who are transitioning their SQL workloads from Trino and Databricks platforms. Such syntax can simplify the adaptation process and enhance cross-compatibility, offering a smoother transition experience for existing users.

**Comment by ChunxuTang** [comment]
@hantangwangd Thanks for proposing the time travel syntaxes!

After reviewing the time travel syntaxes Iceberg and other SQL systems supported, I suggest supporting both `SYSTEM_TIME + SYSTEM_VERSION` and `TIMESTAMP + VERSION`, making the syntax less different from potential SQL standards, Iceberg, and other SQL systems.

**Comment by gupteaj** [comment]
Thanks for the feedback !! I have updated the PR.
