### ISSUE TITLE
https://prestodb.io is unstable

### ISSUE THREAD

**Issue by duanmeng** [prestodb/presto#21393]
The Presto website is unstable, I often could not access it.

<img width="1015" alt="image" src="https://github.com/prestodb/presto/assets/5107360/0bbd4f74-de8d-4a22-b17c-08a02cac9b49">

**Comment by agrawalreetika** [comment]
@alileclerc , Could you please help on this?

**Comment by alileclerc** [comment]
hi @duanmeng sorry to see you're having issues, we just cleared the caches so maybe this will help. A few questions to help us troubleshoot:

- How often has this happened?
- What country are you in?
- Are you using a VPN?

Please let us know if this happens again (you can send me a note at ali@prestodb.io or DM in Presto community slack). Thx for bringing it to our attention.

**Comment by duanmeng** [comment]
>we just cleared the caches so maybe this will help

@alileclerc It works, thanks.

>How often has this happened?
It has happened frequently recently since last month as far as I know.

>What country are you in?
China

>Are you using a VPN?
Yes, and I can access other sites smoothly.

**Comment by tdcmeehan** [comment]
Let us know if this is still an issue!

**Comment by xumingming** [comment]
Seems still not stable

**Comment by alileclerc** [comment]
> Seems still not stable

@xumingming can you share more details on what you're seeing? These will help:

How often has this happened?
What country are you in?
Are you using a VPN?

**Comment by xumingming** [comment]
@alileclerc Same as @duanmeng. It works now. As a comparison, trino.io seems always works.
