### ISSUE TITLE
[native] cmake failure: Objects of target "duckdb" referenced but no such target exists

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#21492]
Trying to build Prestissimo and getting this error. Wondering if there is a fix or workaround.

```
CMake Error at presto_cpp/main/types/tests/CMakeLists.txt:52 (target_link_libraries):
  Error evaluating generator expression:

    $<TARGET_OBJECTS:duckdb>

  Objects of target "duckdb" referenced but no such target exists.
```

CC: @majetideepak @pedroerp @assignUser

**Comment by mbasmanova** [comment]
CC: @kgpai

**Comment by mbasmanova** [comment]
Also, seeing other build errors:

```
In file included from /Users/mbasmanova/java/presto/presto-native-execution/velox/velox/external/md5/md5.cpp:28:
In file included from /usr/local/include/folly/Conv.h:124:
In file included from /usr/local/include/folly/Demangle.h:19:
In file included from /usr/local/include/folly/FBString.h:34:
/usr/local/include/fmt/format.h:1775:12: error: expected unqualified-id
  if (std::signbit(value)) {  // value < 0 is false for NaN so use signbit.
           ^
/Library/Developer/CommandLineTools/SDKs/MacOSX14.0.sdk/usr/include/math.h:171:5: note: expanded from macro 'signbit'
    ( sizeof(x) == sizeof(float)  ? __inline_signbitf((float)(x))        \
    ^
```

**Comment by assignUser** [comment]
>   $<TARGET_OBJECTS:duckdb>
>  Objects of target "duckdb" referenced but no such target exists.

Due to the change away from the amalgamation build the way presto uses duckdb has to be changed as I am pretty sure that just updating the related code to use `duckdb_static` won't work (it might though).

**Comment by assignUser** [comment]
@mbasmanova I can review a fix but I don't have the bw to fix it. You could try to just rename that target to duckdb_static and keep everything else as is. Or another version (which I think would be more likely to succeed due to includes being passed on) would be to replace the whole generator expression with `duckdb_static`.

**Comment by pedroerp** [comment]
I think @majetideepak was working on this?

**Comment by majetideepak** [comment]
I will take a look at this.

**Comment by majetideepak** [comment]
I have a PR to fix this here https://github.com/prestodb/presto/pull/21499
