### ISSUE TITLE
[native] Translate sink.max-buffer-size and driver.max-page-partitioning-buffer-size configs to Velox

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#21543]
Prestissimo needs to translate Presto's worker configs sink.max-buffer-size and driver.max-page-partitioning-buffer-size to corresponding Velox configs max_arbitrary_buffer_size  and max_page_partitioning_buffer_size.

See https://github.com/facebookincubator/velox/pull/8049

CC: @kewang1024 @spershin @majetideepak @aditi-pandit

**Comment by spershin** [comment]
I can handle this.

**Comment by mbasmanova** [comment]
Thank you, @spershin .
