### ISSUE TITLE
Delete PrestoQueryRunner 

### ISSUE THREAD

**Issue by kgpai** [prestodb/presto#21586]
[PestoQueryRunner in presto-native]( https://github.com/prestodb/presto/blob/master/presto-native-execution/presto_cpp/main/tests/PrestoQueryRunner.cpp) can be replaced with [PrestoQueryRunner in Velox](https://github.com/facebookincubator/velox/blob/main/velox/exec/fuzzer/PrestoQueryRunner.h) since there is duplicate functionality and presto-native depends on Velox.

## Presto Component, Service, or Connector
presto-native-execution

## Possible Implementation
Remove instances that use PrestoQueryRunner and instead replace them with Velox's implementation.

## Context
This reduces code duplication and improves (in a minor way) build and link times.

**Comment by kgpai** [comment]
cc: @duanmeng @mbasmanova

**Comment by mbasmanova** [comment]
CC: @aditi-pandit @kagamiori

**Comment by mbasmanova** [comment]
CC: @majetideepak
