### ISSUE TITLE
Presto release 0.285.1

### ISSUE THREAD

**Issue by wanglinsong** [prestodb/presto#21597]
Patch release with the following hotfix.

commit f7dc5383829ac1cbcece474297d144be7fe6ff19
Author: wangd <mingwbd@gmail.com>
Date:   Wed Dec 20 16:50:25 2023 +0800

    Fix bug for LIKE pattern with multiple-byte characters

**Comment by wanglinsong** [comment]
Cherry-picked the mentioned commit into branch [release-0.285](https://github.com/prestodb/presto/commits/release-0.285/) per discussion https://github.com/prestodb/presto/pull/21578#issuecomment-1864652865

**Comment by wanglinsong** [comment]
@tdcmeehan Please confirm.

**Comment by tdcmeehan** [comment]
Confirmed--thank you!

**Comment by wanglinsong** [comment]
The build failed unless https://github.com/prestodb/presto/pull/21428 is cherry-picked into branch release-0.285.

**Comment by wanglinsong** [comment]
https://repo1.maven.org/maven2/com/facebook/presto/presto-server/0.285.1/

**Comment by wanglinsong** [comment]
Will submit PR for release notes after 0.285 release notes PR (https://github.com/prestodb/presto/pull/21579) is merged.

**Comment by wanglinsong** [comment]
Published docker image to docker hub.

**Comment by wanglinsong** [comment]
Published presto-docs maven artifacts.

**Comment by steveburnett** [comment]
> Docs website is updated.

Verified that the docs on the website are updated, no problems visible.
