### ISSUE TITLE
Precision loss issue in the decimal type division.

### ISSUE THREAD

**Issue by weimingdiit** [prestodb/presto#21610]
## Your Environment

* Presto version used: 0.272

Expected Behavior

//presto
**select 0.015/30;    result:  0.0005**
select 0.0150/30;   result:  0.0005
select 0.01500/30;   result:  0.00050

//spark
select 0.015/30;  result:  0.000500
select 0.0150/30;  result:  0.0005000
select 0.01500/30;  result:  0.00050000

## Current Behavior
//presto
**select 0.015/30;    result:  0.001**

**Comment by Akanksha-kedia** [comment]
i would like to work on this.

**Comment by weimingdiit** [comment]
> i would like to work on this.

thanks

**Comment by tdcmeehan** [comment]
A more obvious reproduction is the following query (i.e. it's specific to decimal):

`select CAST(0.015 AS DECIMAL(4, 3))/CAST(30 AS DECIMAL(2,0))`

As far as I can tell this is a real bug and not related to decimal semantics.

**Comment by tdcmeehan** [comment]
CC: @weimingdiit

**Comment by weimingdiit** [comment]
> A more obvious reproduction is the following query (i.e. it's specific to decimal):
> 
> `select CAST(0.015 AS DECIMAL(4, 3))/CAST(30 AS DECIMAL(2,0))`
> 
> ~As far as I can tell this is a real bug and not related to decimal semantics.~
> 
> Update: Oh, I get it now. It's because floating point literals in expressions are interpreted as decimals. So 0.015 literal is `DECIMAL(4,3)` (four significant digits, 3 decimal places), which is the type that the output is as well since it subsumes the denominator's type which doesn't have any decimal places.
> 
> If you'd like floating point semantics, you can use the `parse-decimal-literals-as-double` system property or session property per our documentation: https://prestodb.io/docs/current/language/types.html#decimal
> 
> I don't think this is a bug, but perhaps it's a documentation issue--if so please feel free to suggest how to make this more obvious!

thanks @tdcmeehan ，You are right. The code logic is implemented like this, but without converting it to double, is there any room for optimization of this part of the logic?
![image](https://github.com/prestodb/presto/assets/23093701/4a6a4256-811e-4f1f-b348-a1fb6336f287)


Also, I am using parse_decimal_literals_as_double parameter which is valid

![image](https://github.com/prestodb/presto/assets/23093701/7ad5ad66-43f7-40dd-9d25-b88719535ce8)

**Comment by tdcmeehan** [comment]
You could manually cast it to give it more room for the decimal places.  It's rounding up, as expected for decimals.

**Comment by weimingdiit** [comment]
> You could manually cast it to give it more room for the decimal places. It's rounding up, as expected for decimals.

I see,thanks @tdcmeehan ,i will close this issue
