### ISSUE TITLE
Optimize Table Metadata calls for Iceberg tables

### ISSUE THREAD

**Issue by agrawalreetika** [prestodb/presto#21628]
From Presto, while making Metadata calls for getting a `Table` object using the Iceberg library fetches Table metadata from the Iceberg table filesystem which stores metadata on the storage. From Iceberg these calls are done from [IcebergAbstractMetadata.getIcebergTable](https://github.com/prestodb/presto/blob/master/presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergAbstractMetadata.java#L170)
We could reuse this Iceberg Table object on the Presto side to reduce the overhead of it.

## Expected Behavior or Use Case

Avoid redundant calls to getIcebergTable for a single query for same table

## Presto Component, Service, or Connector

Presto Iceberg Connector

## Possible Implementation

Avoid redundant calls to getIcebergTable for a single query for the same table.

# Example Screenshots (if appropriate):

**Environment:**
Presto cluster - Local Mac
Table Queries - tpch.tiny.region (5 rows)
Data source - S3

Currently Execution Time for simple SELECT Query (for fetching 5 rows) on tpch region table from Iceberg Native & Hive Catalogs,

**Iceberg Native Catalog -** 

`presto:hadoop_db> select * from region;`
[Catalog.loadTable](https://github.com/apache/iceberg/blob/apache-iceberg-1.4.1/api/src/main/java/org/apache/iceberg/catalog/Catalog.java#L326) is getting called **25 times** overall for getting Table metadata in the above Query.  Most of the time is spent in Planning.

**Execution Time -** 1.4m

![image](https://github.com/prestodb/presto/assets/7887476/eca48e1d-3dc8-4ecd-8501-74530b545578)

**Iceberg Hive Catalog -** 

`presto:tpch_tiny_iceberg_parquet_unpartitioned> select * from region;`
[IcebergHiveMetadata.getIcebergTable](https://github.com/prestodb/presto/blob/master/presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergHiveMetadata.java#L159) is getting called **16 times** overall for getting metadata in the above Query. Most of the time is spent in Planning.

**Execution Time -** 15s

![image](https://github.com/prestodb/presto/assets/7887476/e2cf97ce-a668-4e64-8377-1d82ff4ccc72)

## Context

- We could reduce query execution time drastically for both Hive and Native catalogs.
- This will also help in reducing FS calls rate.

**Comment by tailemanh** [comment]
Even if this metadata cache is useful, I still think we need a mechanism to ‘auto vacuum’ this cache (after 30m, 1h, etc...). I doubt this cache is worth the entire lifespan of the cluster
