### ISSUE TITLE
How presto handle kerberos auth for multi hadoop cluster 

### ISSUE THREAD

**Issue by lookingUpAtTheSky** [prestodb/presto#21623]
Hello, I have a question, if convenient please help me answer.
As we known, when we use Java kerberos API to auth, we need to set java.security.krb5.conf using System settings.
If we use presto for multi hadoop cluster, how presto handle this situation,  because multi hadoop cluster has multi krb5.conf, how one jvm handle this, thank you.

**Comment by lookingUpAtTheSky** [comment]
Hi @agrawalreetika Thank you for your reply,
i haven't tried defining all cluster's realms in same krb5.conf, because our production environment is not like this. Is it complicated, or is there anything to pay special attention to?
Besides, is there any ohere way to solve this?

**Comment by agrawalreetika** [comment]
@lookingUpAtTheSky I had tried connecting multiple Kerberised clusters from Presto in Past, and as I remember I picked up `krb5.conf` from one of the cluster and adding multiple clusters realms helped me

**Comment by lookingUpAtTheSky** [comment]
@agrawalreetika I had tried it and it works, thank you very much.
