### ISSUE TITLE
Improve CTE Materialization Execution Tests

### ISSUE THREAD

**Issue by jaystarshot** [prestodb/presto#21688]
The execution test for cte materialization for hive catalog [Test link](https://github.com/prestodb/presto/blob/master/presto-hive/src/test/java/com/facebook/presto/hive/TestCteExecution.java) does not test whether ctes are materialized and this test needs refactoring to do so

**Comment by misterjpapa** [comment]
I would like to contribute to this issue, although new to Presto. In looking at the existing tests the code is comparing the MaterializedResults from a MaterializedSession agains a RegularSession. Can someone elaborate on what to check for that a CTE have been materialized? Do we want to check the CTEInformationCollector off the Session has expected values or something else?

**Comment by jaystarshot** [comment]
Hi @misterjpapa, correct we can just check for `CTEInformation` which has a property **isMaterialized** for the materialized CTEs- [link](https://github.com/prestodb/presto/blob/e789515f75409983f3b4250ee7682623b5f46bc6/presto-spi/src/main/java/com/facebook/presto/spi/eventlistener/CTEInformation.java#L28)

**Comment by misterjpapa** [comment]
Running the tests in a debugger I see a CTEInformation is created with the isMaterialized set to true. Unfortunately the session object that is created in the helper function getMaterializedSession() during the tests is **not** the session that has the map with this CTEInformation. Instead the session with the CTEInformation need for the tests to check is a session object that is created in-line when the DispatchManager is creating an internal query. See the attached screenshot below. Looking at the MaterializedResult and the TestingPrestoClient with the returned data I don't see a easy way to get a reference to this particular session right now. 
<img width="1401" alt="Screenshot 2024-07-17 at 11 04 55 PM" src="https://github.com/user-attachments/assets/04823858-e83a-481c-9602-f54bbbd865ee">

**Comment by jaystarshot** [comment]
I see,  can we use CteInfo from the Explain plan like done [here](https://github.com/prestodb/presto/blob/d292e13cf3abbe50dd6ea0f7cdc9aa4449d973fd/presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestDistributedQueries.java#L1551)?
