### ISSUE TITLE
remove unneeded CircleCI tests from docs-only pull requests

### ISSUE THREAD

**Issue by steveburnett** [prestodb/presto#21689]
The tests 
* linux-presto-e2e-tests
* linux-spark-e2e-tests
* linux-build-and-unit-test
all appear to have no relevance to docs-only PRs such as [PR 21660](https://github.com/prestodb/presto/pull/21660), generally run considerably longer than the rest of the tests, and fail intermittently. 

Suggest that these tests be dropped from the tests run for documentation-only pull requests. 

## Expected Behavior or Use Case
These tests should not run when a pull request containing only content files in presto-docs is created. 

## Presto Component, Service, or Connector
None. 

## Context
Docs-only PRs would complete their required tests quicker and with less irrelevant system load.

**Comment by hainenber** [comment]
Hi Steve, can I be assigned to this one? Thanks!

**Comment by steveburnett** [comment]
> Hi Steve, can I be assigned to this one? Thanks!

Thank you!
