### ISSUE TITLE
Support for set returning functions (generate_series)

### ISSUE THREAD

**Issue by surjikal** [prestodb/presto#2169]
Set returning functions like `generate_series` are incredibly useful in Postgres. Would be neat to have them in presto!

Postgres Set Returning functions:
http://www.postgresql.org/docs/9.4/static/functions-srf.html

Consider the following use case:

I have a table of orders. An order has a timestamp and a total. I want to make a report of daily order totals. Also, let's say the store is closed on Mondays (i.e. there are no orders made on Mondays).

In order to get a continuous time series of totals, with all Mondays totalling to 0, I would generate a series of days, left join it with my orders table on timestamp (date trunc'd to day), and do `coalesce(total, 0)`.

**Comment by snarayananqubole** [comment]
generate_series is very very useful in practice. However, you can get quite
far using unnest http://prestodb.io/docs/current/sql/select.html

Example:
presto:default> SELECT i1
             -> FROM (
             ->   VALUES
             ->     (ARRAY[1,2,3,4,5])
             -> ) AS x (i)
             -> CROSS JOIN UNNEST(i) AS t (i1);
 i1
----
  1
  2
  3
  4
  5
(5 rows)

I presume if you had a function that could return an arbitrary array
[1,2,..n] then you could replicate generate_series functionality.

Thanks
Siva

**Comment by Himmetk** [comment]
so how can we generate series like for example 0,3,5,7......,99?

**Comment by chananelp** [comment]
Shorter version of "generate series like for example 0,3,5,7......,99?":
(no need the CROSS JOIN..)

`SELECT i1 FROM UNNEST(SEQUENCE(1,100,7)) AS t (i1)
`
