### ISSUE TITLE
[Bug] presto-benchto-benchmarks driver not started

### ISSUE THREAD

**Issue by AbhijitKulkarni1** [prestodb/presto#21718]
Presto benchto benchmarks not started after spring core version update to fix the vulnerabilities
Related to fix : https://github.com/prestodb/presto/pull/21528
Reverting the above fix the presto benchto benchmarks driver works fine.
## Your Environment

0.286-SNAPSHOT version
Hive connector with TPCH benchmark

## Expected Behavior

Presto Benchto Benchmark Driver should be up and Presto Driver loaded.

## Current Behavior

Teradata benchto DriverApp not started.

## Steps to Reproduce

1. Build the master branch 0.286-SNAPSHOT
2. Launch Presto and Benchto Service with TPCH benchmark
3. Launch the Presto Benchto Benchmark Driver with the commands as provided in the README.md of presto benchto benchmarks.
java -Xmx1g -jar presto-benchto-benchmarks/target/presto-benchto-benchmarks-*-executable.jar \
    --sql presto-benchto-benchmarks/src/main/resources/sql \
    --benchmarks presto-benchto-benchmarks/src/main/resources/benchmarks \
    --activeBenchmarks=presto/tpch --profile=presto-devenv
5. No logs printed on console to show Benchto is started.
6. After reverting the vulnerabilities fix we can see the Benchto Started with logs as shown below:
7.
     ____                  __    __
   / __ )___  ____  _____/ /_  / /_____
  / __  / _ \/ __ \/ ___/ __ \/ __/ __ \
 / /_/ /  __/ / / / /__/ / / / /_/ /_/ /
/_____/\___/_/ /_/\___/_/ /_/\__/\____/
--- The macro-benchmarking framework ---

16:24:16.081 INFO  [main] c.teradata.benchto.driver.DriverApp - Starting DriverApp v0.4 on ip-10-0-43-33 with PID 34269 (started by ubuntu in /home/ubuntu/presto286)
16:24:16.695 INFO  [main] o.h.validator.internal.util.Version - HV000001: Hibernate Validator 5.1.3.Final
16:24:17.349 INFO  [main] c.teradata.benchto.driver.DriverApp - Started DriverApp in 1.457 seconds (JVM running for 1.754)
16:24:17.349 INFO  [main] c.t.b.d.e.BenchmarkExecutionDriver - Running benchmarks(executionSequenceId=2024-01-17T16:24:17:349) with properties: BenchmarkProperties{sqlDirs=resources/sql, benchmarksDirs=resources/benchmarks, executionSequenceId=null, environmentName=PRESTO-DEVENV, graphiteProperties=GraphiteProperties{cpuGraphiteExpr=null, memoryGraphiteExpr=null, networkGraphiteExpr=null, graphiteResolutionSeconds=0, graphiteMetricsDelaySeconds=0, graphiteMetricsCollectionEnabled=false}, frequencyCheck=true, activeBenchmarks=[presto/tpch]}
16:24:17.351 INFO  [main] c.t.b.driver.loader.BenchmarkLoader - Searching for benchmarks in classpath ...
16:24:17.355 INFO  [main] c.t.b.driver.loader.BenchmarkLoader - Benchmark found: resources/benchmarks/presto/kafka.yaml
16:24:17.355 INFO  [main] c.t.b.driver.loader.BenchmarkLoader - Benchmark found: resources/benchmarks/presto/distributed_sort.yaml
16:24:17.355 INFO  [main] c.t.b.driver.loader.BenchmarkLoader - Benchmark found: resources/benchmarks/presto/tpcds.yaml
16:24:17.355 INFO  [main] c.t.b.driver.loader.BenchmarkLoader - Benchmark found: resources/benchmarks/presto/tpch.yaml
16:24:17.361 INFO  [main] c.t.b.driver.loader.BenchmarkLoader - Excluded Benchmarks:
16:24:17.361 INFO  [main] c.t.b.driver.loader.BenchmarkLoader -         | Benchmark Name | Data Source   | Runs | Prewarms | Concurrency |
16:24:17.399 INFO  [main] c.t.b.driver.loader.BenchmarkLoader - Recently tested benchmarks:
16:24:17.399 INFO  [main] c.t.b.driver.loader.BenchmarkLoader -         | Benchmark Name | Data Source   | Runs | Prewarms | Concurrency |
16:24:17.399 INFO  [main] c.t.b.driver.loader.BenchmarkLoader - Selected Benchmarks:
16:24:17.399 INFO  [main] c.t.b.driver.loader.BenchmarkLoader -         | Benchmark Name | Data Source   | Runs | Prewarms | Concurrency |
16:24:17.399 INFO  [main] c.t.b.d.e.BenchmarkExecutionDriver - Loaded 0 benchmarks
16:24:17.399 WARN  [main] c.t.b.d.e.BenchmarkExecutionDriver - No benchmarks selected, exiting...

## Context

This issue is blocker to use Benchto service and Bencto Driver to do macro benchmarking of supported benchmarks like tpch etc.

**Comment by Akanksha-kedia** [comment]
@AbhijitKulkarni1 is updated version of the spring core is not  compatible with the Benchto driver and Presto?

**Comment by AbhijitKulkarni1** [comment]
@Akanksha-kedia yes. As I can see the revert PR is merged into master branch.
