### ISSUE TITLE
[native] Output operators are missing in Stage Summary Page

### ISSUE THREAD

**Issue by kewang1024** [prestodb/presto#21741]
## Current Behavior
In same production query
CPP VS Java
<img width="486" alt="image" src="https://github.com/prestodb/presto/assets/50636602/10d25d84-5215-48dc-b41f-bc63bf32b0cc">

## Possible Reason

From debugging front end
<img width="1454" alt="image" src="https://github.com/prestodb/presto/assets/50636602/1c3f99ee-e278-47e7-9844-ead0421bcb9c">

The output operator should have the same planNodeId as its parent, [jsx logic ](https://github.com/prestodb/presto/blob/f4f434a243a3d126738f697415bd39b391232fa5/presto-main/src/main/resources/webapp/src/components/StageDetail.jsx#L390)
CPP's PartitionedOutput's planNodeId is **"root"**

CPP
```
"stageId": 1,
 "stageExecutionId": 0,
"pipelineId": 0,
"operatorId": 1,
"planNodeId": "185",
 "operatorType": "PartialAggregation",

"stageId": 1,
"stageExecutionId": 0,
"pipelineId": 0,
"operatorId": 2,
"planNodeId": "root",
"operatorType": "PartitionedOutput",
```
JAVA
```
"stageId": 1,
"stageExecutionId": 0,
"pipelineId": 0,
"operatorId": 1,
"planNodeId": "185",
"operatorType": "AggregationOperator",

"stageId": 1,
"stageExecutionId": 0,
"pipelineId": 0,
"operatorId": 2,
"planNodeId": "185",
"operatorType": "TaskOutputOperator",
```

**Comment by kewang1024** [comment]
Try to fix with https://github.com/prestodb/presto/pull/21742

**Comment by mbasmanova** [comment]
CC: @majetideepak @aditi-pandit @tdcmeehan
