### ISSUE TITLE
Drop `/v1/task` endpoint in favor of `/v1/task/async`

### ISSUE THREAD

**Issue by arhimondr** [prestodb/presto#21748]
Make `AsyncPageTransportServlet` respond to `/v1/task`.

**Comment by mbasmanova** [comment]
CC: @tdcmeehan @majetideepak

**Comment by mbasmanova** [comment]
CC: @amitkdutta @spershin

**Comment by tdcmeehan** [comment]
In keeping with RESTful semantics elsewhere in the project, can we keep the `/v1/task` endpoint but move the async code to use that endpoint?

**Comment by tdcmeehan** [comment]
Just to call it out explicitly: there is a very nice code cleanup opportunity here, in the form of:

* Removing `ExchangeClientConfig.asyncPageTransportEnabled` and finding all references to clean up code paths where it is not enabled.
* Removing `TaskResource#getResults` and any dependent code.

**Comment by mbasmanova** [comment]
@arhimondr Andrii, are you working on this?

**Comment by tdcmeehan** [comment]
There is no need for backwards compatibility--in Java, we will deploy the same version of the code for both the worker and the coordinator, so you can just change the endpoint name in one shot.  I imagine it is also true for C++ worker.

**Comment by spershin** [comment]
@tdcmeehan 

I was mostly concerned about other use cases - when some other software issues these requests to Presto (not sure if such exist). Then they can be broken.
