### ISSUE TITLE
Documentation added in #21057 doesn't accurately reflect the state of resource group management in Presto

### ISSUE THREAD

**Issue by orthoxerox** [prestodb/presto#21758]
According to https://github.com/prestodb/presto/pull/21057, Resource manager selector rules support a `userGroup` component.

However, Presto 0.285 doesn't actually support this selector: 
- https://github.com/prestodb/presto/blob/0.285.1/presto-resource-group-managers/src/main/java/com/facebook/presto/resourceGroups/db/SelectorRecord.java doesn't contain a member that represents this component.
- https://github.com/prestodb/presto/blob/0.285.1/presto-resource-group-managers/src/main/java/com/facebook/presto/resourceGroups/SelectorSpec.java doesn't have one either

## Your Environment

* Presto version used: 0.285
* Storage (HDFS/S3/GCS..): n/a
* Data source and connector used: n/a
* Deployment (Cloud or On-prem): on-prem
* [Pastebin](https://pastebin.com/) link to the complete debug logs: n/a

## Expected Behavior
When I configure a selector rule with a `userGroup` component (e.g., via `resource-groups.json`), all queries from users in said group must be run in the group specificed in the selector rule.

## Current Behavior
This selector doesn't fire.

## Possible Solution
Update the documentation to reflect the real status of this feature until it's actually implemented and released.

## Steps to Reproduce
1. Install presto 0.285 and configure the file resource group manager as shown on https://prestodb.io/docs/0.285/admin/resource-groups.html
2. Run a query as a user that is in the "admin" user group, but isn't "bob"
3. The query should run in the "admin" resource group, but runs in an ad-hoc "global.adhoc.other.${USER}" resource group

## Context

This is one of the features from the "other, very similar engine" that is missing in Presto.

**Comment by tdcmeehan** [comment]
@orthoxerox thanks for reporting this.  Would you like to open a PR to fix this issue?

**Comment by orthoxerox** [comment]
My employment contract doesn't allow me to contribute to FOSS projects without an explicit permission. :(

**Comment by Akanksha-kedia** [comment]
@orthoxerox would u mind if i look into this?

**Comment by Akanksha-kedia** [comment]
I have done changes

**Comment by steveburnett** [comment]
@Akanksha-kedia, please link this issue to the PR you made changes fixing this issue in, and then close this issue. Thanks!

**Comment by Akanksha-kedia** [comment]
where to close 
<img width="1260" alt="Screenshot 2024-03-30 at 11 21 29 AM" src="https://github.com/prestodb/presto/assets/89628774/06e4d20a-65d2-4352-8c11-6a193eb8cdd7">
