### ISSUE TITLE
INACTIVE node state of worker is not respected by coordinator.

### ISSUE THREAD

**Issue by spershin** [prestodb/presto#21762]
When worker returns INACTIVE as the node state - it is being ignored by the coordinator.
The coordinator still returns 'active' status in "select * from system.runtime.nodes;" query.
The queries continue to be scheduled at the worker.

"curl -k http://twshared36083.02.pnb2:7777/v1/info/state" from the worker returns INACTIVE.

Note that SHUTTING_DOWN state works: the node removed from the list of active nodes.

DiscoveryNodeManager has some code to deal with INACTIVE and it must have a bug.

**Comment by mbasmanova** [comment]
CC: @tdcmeehan @majetideepak

**Comment by tdcmeehan** [comment]
@spershin based on this code, my interpretation of INACTIVE is it's meant to convey a node which has a different version of Presto than what is being scheduled: https://github.com/prestodb/presto/commit/fa763cf4fc8ab35824ee6a169a85833ad0adaba4#diff-cd42a93bcd3f828779c6c7bc2dcf175cea53df3e136234e7877911959cbdb34dR229

I believe the NodeState was developed for graceful shutdown, and it's meant to provide a way to shut down and bring up new versions without causing scheduling issues (version mismatch between workers).  And I believe it's set from the coordinator, which doesn't allow one to set a node to `INACTIVE`: https://github.com/prestodb/presto/blob/0f6f9a4c48f9a2a32d87dd26fd36e0721093efd2/presto-main/src/main/java/com/facebook/presto/server/ServerInfoResource.java#L95

This makes me wonder how you discovered this issue?  Perhaps you can provide more context?

**Comment by spershin** [comment]
We have tried to change worker's state to INACTIVE inside a worker itself to signal to coordinator to stop sending queries to it.
Reporting INACTIVE from the worker had no effect.

**Comment by tdcmeehan** [comment]
@spershin looks like you can't do that without further changes (see above).

**Comment by tdcmeehan** [comment]
Coordinator changes are required.  INACTIVE was designed as a one-way signal from the coordinator to the worker--in order for the worker to self-report to the coordinator, a new design is needed.
