### ISSUE TITLE
Documentation pdf link

### ISSUE THREAD

**Issue by rohitadarsh16** [prestodb/presto#21760]
where is the link of pdf

**Comment by steveburnett** [comment]
Thanks for the question! The Presto documentation is not currently being delivered in PDF format. 

The current documentation is online at [https://prestodb.io/docs/](https://prestodb.io/docs/) .

**Comment by steveburnett** [comment]
Using your web browser, you can print, save, or export individual pages as PDF. For one example, [How to print web pages in Firefox](https://support.mozilla.org/en-US/kb/how-print-web-pages-firefox) shows how to save a page as a PDF using the Print dialog. If you use a different web browser, please check the documentation for your preferred web browser.
