### ISSUE TITLE
Combine window operators with same partition and ordering

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#2178]
Window functions that share the same partition and ordering can be executed by the same window operator. Currently, each window function is executed in a separate step, which requires moving and sorting all the data again.

The same operator can be shared even if the frame is different: this requires tracking the frame per function (or group of functions that use the same frame) rather than using a single frame for the entire operator.

**Comment by maciejgrzybek** [comment]
Isn't it a duplicate of #4359? I know this one was here earlier but since in the other one we have some discussion and example already, maybe #2178 should be closed?

**Comment by maciejgrzybek** [comment]
Closing duplicate.
