### ISSUE TITLE
[documentation] build PDF of Presto docs

### ISSUE THREAD

**Issue by steveburnett** [prestodb/presto#21805]
Build PDF of the Presto documentation and make it available for download from a link on the Presto site. 

## Expected Behavior or Use Case
Presto docs can be downloaded in PDF form from a link on the Presto site. 

## Presto Component, Service, or Connector
Documentation, website, build process. 

## Possible Implementation
* [make latexpdf](https://www.sphinx-doc.org/en/master/usage/quickstart.html#running-the-build)
* [rinohtype](https://www.sphinx-doc.org/en/master/faq.html) ([GitHub repo](https://github.com/brechtm/rinohtype))
* [Sphinx-Simple PDF](https://sphinx-simplepdf.readthedocs.io/en/latest/) 

are some potential options I found on a quick search but haven't evaluated yet. 

## Context
[Issue 21760](https://github.com/prestodb/presto/issues/21760) asked where is the link to download the PDF of the Presto documentation. Closed the issue as it doesn't exist at this time and opened this new issue to discuss how this might be implemented and to scope the effort needed to help decide if we should.

**Comment by hainenber** [comment]
Can I be assigned this one?
Gracias in advanced :D

**Comment by steveburnett** [comment]
> Can I be assigned this one? Gracias in advanced :D

Yes, thank you for volunteering! Done.

**Comment by steveburnett** [comment]
Closing because [PR 21883](https://github.com/prestodb/presto/pull/21883) addressed this.
