### ISSUE TITLE
Be able to query uppercase partitioned columns on delta tables

### ISSUE THREAD

**Issue by mblanco-denodo** [prestodb/presto#21828]
In Delta tables, NULL values are returned in partitioned uppercase columns. For example, for the following Delta table in S3:
![image](https://github.com/prestodb/presto/assets/136591152/c25f95a7-8764-4dcf-a5ac-69d31d3de78a)
a query like 
`select * from delta_uppercase_partitioned_test`
returns NULL values on the partitioned field BIRTH_YEAR
![image](https://github.com/prestodb/presto/assets/136591152/c819363a-6ca5-48cf-b050-6f6ebb37bb90)

## Expected Behavior or Use Case

Presto should be able to retrieve data from uppercase partitioned columns of delta tables, as this is a very common case.
## Presto Component, Service, or Connector

Delta Connector
## Possible Implementation

Through some debugging in the Delta connector source code, this behavior could be achieved by avoiding String.toLowerCase() conversions in the DeltaClient.getSchema() method. Additionally, we could make it configurable, via a new configuration property to allow old and new behavior as desired.
`delta.case-sensitive-partitions=true`

This solution was successfully tested on my local environment.

**Comment by mblanco-denodo** [comment]
As the changes are tested in my local environment, I could have a fix PR soon

**Comment by imjalpreet** [comment]
Fixed with https://github.com/prestodb/presto/pull/22596
