### ISSUE TITLE
[Doc] Document supported data types mapping in Iceberg connector 

### ISSUE THREAD

**Issue by agrawalreetika** [prestodb/presto#21848]
Document supported data types mapping in Iceberg connector from Iceberg to Presto & Presto to Iceberg similar to https://prestodb.io/docs/current/connector/mysql.html#type-mapping

## Expected Behavior or Use Case
To provide more concrete details to users 

## Presto Component, Service, or Connector
Presto Docs

## Possible Implementation
https://prestodb.io/docs/current/connector/mysql.html#type-mapping

## Context
To provide more concrete details to users

**Comment by sbabtiwa** [comment]
Hi @agrawalreetika, 

I am part of the IBM Open Source contributors coalition and am interested in working on this issue. Could I be assigned to it?
