### ISSUE TITLE
[Doc] Document all the currently supported SQL operation for Mysql connector 

### ISSUE THREAD

**Issue by agrawalreetika** [prestodb/presto#21850]
Document all the currently supported SQL operations for Mysql connector along with an example similar to https://prestodb.io/docs/current/connector/iceberg.html#sql-support

## Expected Behavior or Use Case
To provide more concrete details to users.
Once we have documentation for Mysql connector, we can document similar supported SQL operations for other JDBC connectors as well.

## Presto Component, Service, or Connector
Presto Docs

## Possible Implementation
https://prestodb.io/docs/current/connector/iceberg.html#sql-support

## Context
To provide more concrete details to users

**Comment by Akanksha-kedia** [comment]
hello @agrawalreetika @tdcmeehan based on documentation https://prestodb.io/docs/0.285.1/connector/mysql.html,
i have found 

![image](https://github.com/prestodb/presto/assets/89628774/0647efcd-84b0-4d7f-bb89-a3df92ed284c)
based on mentioned doc The connection-url defines the connection information and parameters to pass to the MySQL JDBC driver. The supported parameters for the URL are available in the [MySQL Developer Guide](https://dev.mysql.com/doc/connector-j/8.0/en/).

For example, the following connection-url allows you to configure the JDBC driver to interpret time values based on UTC as a timezone on the server, and serves as a [workaround for a known issue](https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-usagenotes-known-issues-limitations.html).


on testing : 
![image](https://github.com/prestodb/presto/assets/89628774/93daa912-a3ae-4c24-9bf5-71383050ecef)






connection-url=jdbc:mysql://example.net:3306?serverTimezone=UTC

**Comment by Akanksha-kedia** [comment]
AS per doc 👍 👍 
MySQL Connector Limitations[#](https://prestodb.io/docs/0.285.1/connector/mysql.html#mysql-connector-limitations)
The following SQL statements are not yet supported:

[DELETE](https://prestodb.io/docs/0.285.1/sql/delete.html)

[ALTER TABLE](https://prestodb.io/docs/0.285.1/sql/alter-table.html)

[CREATE TABLE](https://prestodb.io/docs/0.285.1/sql/create-table.html) ([CREATE TABLE AS](https://prestodb.io/docs/0.285.1/sql/create-table-as.html) is supported)

[GRANT](https://prestodb.io/docs/0.285.1/sql/grant.html)

[REVOKE](https://prestodb.io/docs/0.285.1/sql/revoke.html)

[SHOW GRANTS](https://prestodb.io/docs/0.285.1/sql/show-grants.html)

[SHOW ROLES](https://prestodb.io/docs/0.285.1/sql/show-roles.html)

[SHOW ROLE GRANTS](https://prestodb.io/docs/0.285.1/sql/show-role-grants.html)

testing 👍 
![image](https://github.com/prestodb/presto/assets/89628774/624cf8f8-33db-4ecf-b9c6-c382a72b73bf)
we need to update accordingly

**Comment by Akanksha-kedia** [comment]
if analysis looks gud please assign and i ll update based on analysis
