### ISSUE TITLE
ST_POINT() function Documentation is unclear

### ISSUE THREAD

**Issue by brookbi** [prestodb/presto#21878]
Can someone please document on this page whether to use (longitude, latitude) or (latitude, longitude) while running distance calculations? It's unclear to me for the ST_POINT() function listing

https://prestodb.io/docs/current/functions/geospatial.html

**Comment by steveburnett** [comment]
@mbasmanova and @jagill , I see that you had commits related to this file https://github.com/prestodb/presto/blob/master/presto-docs/src/main/sphinx/functions/geospatial.rst. Can you help? 

If you explain here how ST_POINT works to improve the existing docs, I'd be happy to open a docs PR to update this page if you'd like.

**Comment by brookbi** [comment]
It appears that ST_POINT() creates a geospatial point that’s then used for other calculations, like great circle distance, and it seems like it goes in (Longitude, Latitude) order but I’m not 100%On Feb 7, 2024, at 12:09 PM, Steve Burnett ***@***.***> wrote:﻿
@mbasmanova and @jagill , I see that you had commits related to this file https://github.com/prestodb/presto/blob/master/presto-docs/src/main/sphinx/functions/geospatial.rst. Can you help?
If you explain here how ST_POINT works to improve the existing docs, I'd be happy to open a docs PR to update this page if you'd like.

**Comment by mbasmanova** [comment]
> it goes in (Longitude, Latitude) order

That's right.

**Comment by steveburnett** [comment]
Thanks, I'll open a PR to update the docs. Thanks!

**Comment by steveburnett** [comment]
@brookbi , I was not able to add you as a reviewer to [PR 21880](https://github.com/prestodb/presto/pull/21880). Please review it and comment - there or here - if the edit solves your concern, or if you have comments.

**Comment by steveburnett** [comment]
@brookbi, @mbasmanova pointed out on [PR 21880](https://github.com/prestodb/presto/pull/21880) that the page https://prestodb.io/docs/current/functions/geospatial.html contains the following explanation: 

``Use ST_GeometryFromText and ST_GeomFromBinary functions to create geometry objects from WKT or WKB. In WKT/WKB, the coordinate order is (x, y). For spherical/geospatial uses, this implies (longitude, latitude) instead of (latitude, longitude).

The basis for the Geometry type is a plane. The shortest path between two points on the plane is a straight line. That means calculations on geometries (areas, distances, lengths, intersections, etc) can be calculated using cartesian mathematics and straight line vectors.``

Is this sufficient explanation for you? If not, what would help you?

**Comment by brookbi** [comment]
Hi Steve,This is fantastic - thanks for being so expeditious about everything. Amazing!On Feb 7, 2024, at 3:33 PM, Steve Burnett ***@***.***> wrote:﻿
@brookbi, @mbasmanova pointed out on PR 21880 that the page https://prestodb.io/docs/current/functions/geospatial.html contains the following explanation:
``Use ST_GeometryFromText and ST_GeomFromBinary functions to create geometry objects from WKT or WKB. In WKT/WKB, the coordinate order is (x, y). For spherical/geospatial uses, this implies (longitude, latitude) instead of (latitude, longitude).
The basis for the Geometry type is a plane. The shortest path between two points on the plane is a straight line. That means calculations on geometries (areas, distances, lengths, intersections, etc) can be calculated using cartesian mathematics and straight line vectors.``
Is this sufficient explanation for you? If not, what would help you?

**Comment by steveburnett** [comment]
@brookbi if this satisfies you, I'll close this issue and the associated PR. Let me know, please.

**Comment by brookbi** [comment]
Sounds good! Thank you On Feb 7, 2024, at 3:39 PM, Steve Burnett ***@***.***> wrote:﻿
@brookbi if this satisfies you, I'll close this issue and the associated PR. Let me know, please.

**Comment by steveburnett** [comment]
Closing, with thanks to @mbasmanova for helping resolve this issue.
