### ISSUE TITLE
CircleCI redundant header check

### ISSUE THREAD

**Issue by ZacBlanco** [prestodb/presto#21875]
Currently, there is a CircleCI check named `ci/circleci: header check` which uses a python script from the velox repo `check.py headers` to verify that license headers exist on a variety of file types. This check will run indiscriminately on all files - regardless of whether they are within `presto-native-execution`. It seems to only check files which were modified by the current PR.

There are a number of files which we explicitly ignore header checks on `mvn validate` such as in [query plan test resources](https://github.com/prestodb/presto/blob/master/presto-benchto-benchmarks/src/test/resources/sql/presto/tpch/). However, if these files are modified in a PR, we have no way to ignore them, so this specific CI check always fails. Adding logic to strip the headers for the tests is quite annoying. It would be better if this check either didn't run on the files covered by the maven checks, or if we could update some kind of ignore list. The tool used doesn't seem to have one.

**Comment by tdcmeehan** [comment]
This check is not required, so you can feel free to ignore it.  Let's ask about this in the #presto-cpp channel to get context on how and why this was added.

**Comment by majetideepak** [comment]
I will fix this.
