### ISSUE TITLE
Aggregate functions Max/Min return different results based on order of NaN for floating point types.

### ISSUE THREAD

**Issue by kgpai** [prestodb/presto#21877]
Aggregate functions Max/Min return different results based on when NaN is encountered in the input for floating point types. If Nan is the first value then irrespective of what the other values are the result is Nan. This seems wrong. 

## Expected Behavior
Max/Min shouldnt be sensitive to order of NaN and should return same result. 

## Current Behavior
```
presto:di> select max(x) from (values 4.0,nan(),null) T(x);;
 _col0
-------
   4.0
(1 row)

presto:di> select max(x) from (values nan(),4.0,null) T(x);
 _col0
-------
   NaN
(1 row)
```

## Possible Solution
The bug is likely here (https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/operator/aggregation/AbstractMinMaxAggregationFunction.java) where state is initially null and set to Nan and then subsequently all comparison against it fails.

**Comment by kgpai** [comment]
cc: @spershin @amitkdutta

**Comment by mbasmanova** [comment]
CC: @tdcmeehan @majetideepak @aditi-pandit @feilong-liu @mlyublena @kaikalur

**Comment by hainenber** [comment]
Hi, can I be assigned for this one? Thanks!

**Comment by mbasmanova** [comment]
> It seems that most systems treat NaN as higher any other floating point value

@tdcmeehan Tim, thank you for the references. Small correction: it appears that BigQuery doesn't treat NaN as greater than any other value. Both MIN and MAX in BigQuery are documented as returning NaN if any input is NaN.

"If the argument is NaN for any row in the group, returns NaN."

**Comment by Yuhta** [comment]
> If the argument is NaN for any row in the group, returns NaN.
I would say this make most sense.

**Comment by kgpai** [comment]
@Yuhta Only BigQuery does that though not the others (spark/presto etc..).

**Comment by spershin** [comment]
Folks, anyhow we resolve this, we better make all the min/max of doubles consistent:
`array_min`/`array_max` currently both return NaN when found at least one NaN element.
So, `min`/`max` should to the same and if not, then `array_min`/`array_max` should be changed accordingly.
Makes sense to double check `min_by`/`max_by` too.

**Comment by steveburnett** [comment]
However this is resolved, the docs should be checked if any update is needed to match the resolution of the issue. For example, http://prestodb.io/docs/current/functions/math.html.

**Comment by mlyublena** [comment]
> It seems that most systems treat `NaN` as higher any other floating point value[1](#user-content-fn-1-ec6222b3979b808243f5775dee62e4c4)[2](#user-content-fn-2-ec6222b3979b808243f5775dee62e4c4)[3](#user-content-fn-3-ec6222b3979b808243f5775dee62e4c4)[4](#user-content-fn-4-ec6222b3979b808243f5775dee62e4c4), which is not consistent with IEEE 754[5](#user-content-fn-5-ec6222b3979b808243f5775dee62e4c4). We should revisit to see if the Presto behavior is too incongruent from larger industry expectations. But it seems like we can separate out the small inconsistency in ordering of the `NaN` value in our min/max aggregation functions for now.
> 
> ## Footnotes
> 1. https://cloud.google.com/bigquery/docs/reference/standard-sql/aggregate_functions#max [↩](#user-content-fnref-1-ec6222b3979b808243f5775dee62e4c4)
> 2. https://docs.snowflake.com/en/sql-reference/data-types-numeric#special-values [↩](#user-content-fnref-2-ec6222b3979b808243f5775dee62e4c4)
> 3. https://spark.apache.org/docs/latest/api/sql/index.html#array_max [↩](#user-content-fnref-3-ec6222b3979b808243f5775dee62e4c4)
> 4. https://www.postgresql.org/docs/current/datatype-numeric.html#DATATYPE-NUMERIC-DECIMAL [↩](#user-content-fnref-4-ec6222b3979b808243f5775dee62e4c4)
> 5. https://en.wikipedia.org/wiki/NaN [↩](#user-content-fnref-5-ec6222b3979b808243f5775dee62e4c4)

One comment to the above: BigQuery actually treats NaNs as special values and for both min and max returns NaN if any of the inputs is NaN: https://cloud.google.com/bigquery/docs/reference/standard-sql/aggregate_functions#min

**Comment by mlyublena** [comment]
In addition to the various aggs and scalar functions listed above, can we make the behavior consistent across all functions + comparisons involving NaN? In particular how do we deal with comparisons and expressions of the sort:
```
x > nan()
order by <column_containing_nulls>
```
Note that for ORDER BY with nulls some systems allow specifying where NULLs get ordered with the NULLS FIRST/NULLS LAST construct.

**Comment by rschlussel** [comment]
I've been looking into the NaN inconsistency and commented on this issue (since it had the more relevant title) with my update https://github.com/prestodb/presto/issues/21936#issuecomment-1971708797.  Would appreciate any feedback so we can move forward.
