### ISSUE TITLE
FROM_UNIXTIME(double) implementation harbors double precision bug.

### ISSUE THREAD

**Issue by spershin** [prestodb/presto#21891]
## Your Environment
Presto cluster. Latest version.

## Expected Behavior
Query (see the reproduce' section) should return
```
    event_time     |        action_ts
-------------------+-------------------------
 1.7041507095805E9 | 2024-01-01 15:11:49.580
```

Machine-representable double for the `1.7041507095805E9` is `1704150709.58049988746643066406`.
`1704150709` goes to seconds and `0.580499887466` should be rounded to `580` milliseconds.
Because `580.499887466 < 580.5`.

## Current Behavior
Currently the query returns 
```
    event_time     |        action_ts
-------------------+-------------------------
 1.7041507095805E9 | 2024-01-01 15:11:49.581
```

The resulting timestamp gets `1704150709` seconds and `581` milliseconds.
It is because the function is implemented as `Math.round(unixTime * 1000);`
`unixTime * 1000` part loses precision in some corner cases.
In our case it pushes the resulting number to `1704150709580.500000000`,
which after rounding gives us `1704150709581`,
meaning `581` milliseconds.

## Possible Solution
Changing the existing code to
`(long)Math.floor(unixTime) * 1000 + Math.round((unixTime - Math.floor(unixTime)) * 1000)`
would avoid accumulating floating point error and will produce the right result.

## Steps to Reproduce
A table with a double column (in this example event_time).
Query to reproduce:
```
SELECT 
  event_time, 
  FROM_UNIXTIME(event_time) action_ts 
FROM 
  (
    SELECT 
      if(
        event_time is not null,
        1.7041507095805E9, 
        1.7E9
      ) as event_time 
    FROM 
      table1 
    LIMIT 
      1
  )
```

## Context
The issue was noticed when comparing Presto Native with Presto on real world data and query.

**Comment by mbasmanova** [comment]
CC: @tdcmeehan @aditi-pandit @majetideepak @kaikalur @feilong-liu @mlyublena

**Comment by mbasmanova** [comment]
CC: @duanmeng

**Comment by hainenber** [comment]
I made a PR to address this one. PTAL if you have time. Thanks!

**Comment by mbasmanova** [comment]
> Changing the existing code to
(long)Math.floor(unixTime) * 1000 + Math.round((unixTime - Math.floor(unixTime)) * 1000)
would avoid accumulating floating point error and will produce the right result.

@spershin I'm wondering why this works? 

Math.floor(unixTime) doesn't have any error, * 1000 doesn't either.

Why "Math.round((unixTime - Math.floor(unixTime)) * 1000)" doesn't have errors? Is this because "unixTime - Math.floor(unixTime)" is a smaller number, so that when it is * 1000 it is still fairly small and accurate?

**Comment by mbasmanova** [comment]
There are 2 more versions of from_unixtime and both have the same problem as they use Math.round(unixTime * 1000).

CC: @spershin @kgpai @tdcmeehan
