### ISSUE TITLE
Presto Hive Connector creates too many small splits

### ISSUE THREAD

**Issue by pranjalssh** [prestodb/presto#21911]
We have a table with wide columns(maps), and it takes a long time(3.6 min)
```
select count(1) from table
```
Meta internal query id: [20240212_231123_91020_7kizs](https://www.internalfb.com/intern/presto/query/?query_id=20240212_231123_91020_7kizs#op_perf)

Using session property `hive.file_splittable=false` makes the same query take 10s!

Meta internal query id: [20240212_230955_07056_7jgdp](https://www.internalfb.com/intern/presto/query/?query_id=20240212_230955_07056_7jgdp#op_perf)

This session property creates exactly 1 split from 1 file in table. If otherwise true, presto scheduler will create multiple splits from the same file.

This is because presto scheduler creates splits according to file sizes - but does not take into account if we read only selected columns from the file. This is an extreme case where we read no data, but just metadata. In general, we should be able to tune split sizes based on amount of data we select from the files - so we can have fewer splits and presto runs faster.

There is an orthogonal problem when Presto is slow to process a large number of splits - that needs to be looked at in future.

This issue focuses on increasing split sizes when possible so query can be run with fewer splits. There can be 2 ways to fix this:

1) Use column stats from metastore to find relative size of file that we will be reading - and make split sizes according to it, not the whole file size.

2) Make it adaptive. If workers report they didn't read too much from the files when processing splits - increase split sizes.

**Comment by mbasmanova** [comment]
CC: @tdcmeehan @majetideepak @aditi-pandit @pettyjamesm

**Comment by tdcmeehan** [comment]
For most table formats, I'll bet approach 1 is the way to go.  For example, Iceberg already stores column-level information on the size in bytes for each column per file, and it already knows what columns will be accessed from the file during planning time, so it should be possible to change Iceberg to avoid this edge case.  I imagine it's the same for Delta and Hudi.

For Hive, we'd need to build this inside of Presto.  I wonder if the partition stats in the Hive metastore are sufficient for us to consistently make a good determination on the split size (i.e. are we losing anything by not knowing it per file).

**Comment by mbasmanova** [comment]
> Use column stats from metastore to find relative size of file that we will be reading - and make split sizes according to it, not the whole file size.

I think this solution can be effective and seems not too hard to implement.

**Comment by kaikalur** [comment]
@pranjalssh this will be a great issue to fix as it helps current adhoc queries as well as prestissimo. So I say let's prioritize this

**Comment by pranjalssh** [comment]
Cc @rschlussel @agrawaldevesh

**Comment by kaikalur** [comment]
A related problem - if the hive table is badly laid out with a ton of tiny files with a few rows (happens quite a bit), we still produce a lot of splits.

It would be interesting to see if making splits span across files (I believe Spark already has something like that) will fix that issue as well.

**Comment by mbasmanova** [comment]
> It would be interesting to see if making splits span across files

That would be nice.

**Comment by kaikalur** [comment]
[heart]         Sreeni Viswanadha reacted to your message:
________________________________
