### ISSUE TITLE
Allow configuring HiveTableOperations retry parameters

### ISSUE THREAD

**Issue by ZacBlanco** [prestodb/presto#21967]
## Expected Behavior or Use Case

Currently the `HiveTableOperations` class uses a set of static parameters for retries when refreshing the table metadata. It would be good to make them configurable from the iceberg connector properties file.

https://github.com/prestodb/presto/blob/master/presto-iceberg/src/main/java/com/facebook/presto/iceberg/HiveTableOperations.java#L387-L392

## Presto Component, Service, or Connector

Iceberg Connector

## Possible Implementation

Add new field(s) to the Iceberg connector configuration.

## Context

It would be useful for users in the case they ever need to edit the retry configuration for their cluster or for decrease test times.

**Comment by steveburnett** [comment]
When this is worked on, please document new properties in [Configuration Properties](http://prestodb.io/docs/current/connector/iceberg.html#configuration-properties) of the [Iceberg Connector](http://prestodb.io/docs/current/connector/iceberg.html) doc.

**Comment by BVK21** [comment]
Hello @ZacBlanco  can you please assign this to me

**Comment by ZacBlanco** [comment]
@BVK21 this was actually closed already by #23174
