### ISSUE TITLE
[Presto UI] Heading content is hiding in Stages section of Query pages on Presto

### ISSUE THREAD

**Issue by agrawalreetika** [prestodb/presto#22070]
Heading content is hiding in the Stages section of Query pages on Presto

## Your Environment
* Presto version used: Current master (0.287-SNAPSHOT)

## Expected Behavior
The text should be visible

## Current Behavior
Header mouse hover text is hiding in the Stages on Query pages in Presto Console
![image](https://github.com/prestodb/presto/assets/7887476/cebefa4a-3570-423d-b8ea-6b4dffa8e19a)

## Steps to Reproduce
Run any Query on Presto -> Go to Presto UI console -> Go to Query Web Page -> Scroll down to Stages -> Mouse hover on Tasks header.
![image](https://github.com/prestodb/presto/assets/7887476/85f318a5-91b9-4e36-ace8-e705ab41f19a)

**Comment by efrancisworks** [comment]
I could not reproduce issue.

<img width="510" alt="version" src="https://github.com/prestodb/presto/assets/70411130/13b05072-922f-4001-8d80-dc8ce4511e98">
<img width="1153" alt="Ui-issue" src="https://github.com/prestodb/presto/assets/70411130/f333f0ac-8d83-4144-8253-28cbf70e760f">

**Comment by agrawalreetika** [comment]
Looks like this is not the issue anymore. In my current latest master, I can see UI fine -

![image](https://github.com/prestodb/presto/assets/7887476/52602ae4-2053-448c-922a-98d8f5f96968)
