### ISSUE TITLE
Improve Parquet reader performance

### ISSUE THREAD

**Issue by snarayanank2** [prestodb/presto#2217]
I was running some perf numbers against latest trunk. Used TPC-DS scale 1000 store_sales dataset and 10 c3.8xlarge worker nodes. Data lives in s3. The table was not partitioned.

The query used is of the form select <cols> from store_sales where ss_customer_sk=1000;

This filter chooses 500 odd rows from about 2.9 billion rows.
Total size of all files:
txt/gzip 126 GB
orc/snappy 105 GB
parquet/snappy 125 GB

Two things that stood out:
- Parquet reading is consistently slower than ORC at about 2x
- When selecting all 23 columns, parquet was slower than delimited .gz files

![image 2](https://cloud.githubusercontent.com/assets/5491710/5691026/78078862-9880-11e4-8ee4-1d294bbee9b5.png)

**Comment by zhenxiao** [comment]
@snarayananqubole I'd like to claim this one. We are working on adding vectorization support, lazy materialization, and row group skipping to Parquet reader.

**Comment by snarayananqubole** [comment]
Sounds good to me. Happy to rerun the test with your fixes.

**Comment by losipiuk** [comment]
Parquet reader improved over time. I am closing this one. @snarayanank2 please reopen if you are still seeing issues with performance.

**Comment by nezihyigitbasi** [comment]
Please give the new reader a try with your benchmarks (you should enable it with `hive.parquet-optimized-reader.enabled`). You can also experiment with `hive.parquet-predicate-pushdown.enabled`.
