### ISSUE TITLE
[DOC] Update JMX connector documentation

### ISSUE THREAD

**Issue by Akanksha-kedia** [prestodb/presto#22247]
To provide more accurate and detailed information to users about the SQL operations supported by the JMX connector in Presto. The current documentation mentions only two schemas (current and history), but the JMX connector actually provides three schemas (current, history, and information_schema). We need to update this information to maintain consistency and accuracy. Also add few examples for information_schema.

## Expected Behavior or Use Case
To provide more accurate and detailed information to users about the SQL operations supported by the JMX connector in Presto. The current documentation mentions only two schemas (current and history), but the JMX connector actually provides three schemas (current, history, and information_schema). We need to update this information to maintain consistency and accuracy.

## Presto Component, Service, or Connector
Presto Docs (JMX Connector)

## Possible Implementation
Update the JMX connector documentation to accurately reflect the available schemas and provide examples of SQL operations for each schema.

## Context
In the current documentation, it is stated that the JMX connector provides two schemas. However, in reality, it provides three schemas: current, history, and information_schema.

The current schema contains every MBean from every node in the Presto cluster. The history schema and the information_schema are also provided by the JMX connector.

Users can see all of the available schemas by running the SHOW SCHEMAS command:

SHOW SCHEMAS;
And they can see all of the available MBeans by running the SHOW TABLES command:

SHOW TABLES FROM jmx.current;
We need to update the documentation to accurately reflect these details and provide more concrete examples for users.

![image](https://github.com/prestodb/presto/assets/89628774/c113dc57-945b-48df-a380-ccd606992531)

**Comment by Akanksha-kedia** [comment]
@steveburnett

**Comment by Sreesruth** [comment]
hii, @Akanksha-kedia , @joshk @electrum @jvanzyl @oggy ,  i would like to work on this issue, thankyou.
