### ISSUE TITLE
SQL Grammar issue: rule queryNoWith contains an optional block with at least one alternative that can match an empty string

### ISSUE THREAD

**Issue by elharo** [prestodb/presto#22274]
[WARNING] warning(154): com/facebook/presto/sql/parser/SqlBase.g4:231:0: rule queryNoWith contains an optional block with at least one alternative that can match an empty string
[WARNING] /Users/elharo/presto/com/facebook/presto/sql/parser/SqlBase.g4 [231:0]: rule queryNoWith contains an optional block with at least one alternative that can match an empty string

**Comment by rschlussel** [comment]
Fixed by https://github.com/prestodb/presto/pull/22330
