### ISSUE TITLE
Iceberg table with Equality deletes returning incorrect number of rows

### ISSUE THREAD

**Issue by nmahadevuni** [prestodb/presto#22295]
After equality deletes are applied to the table, it is returning incorrect number of rows. The equality delete is simulated by calling the Iceberg API to add a parquet file with deleted rows and modifying the table's metadata. Querying the table after applying equality deletes is compared against the same query with a NOT IN query to eliminate the deleted rows manually. These two do not match.

The PR https://github.com/prestodb/presto/pull/22294 has a test case to reproduce this issue.

**Comment by tdcmeehan** [comment]
@nmahadevuni can you reproduce this with `iceberg.delete_as_join_rewrite_enabled` enabled and disabled?

**Comment by nmahadevuni** [comment]
> @nmahadevuni can you reproduce this with `iceberg.delete_as_join_rewrite_enabled` enabled and disabled?

@tdcmeehan Yes. I was able to reproduce with this config both disabled and enabled

**Comment by hantangwangd** [comment]
I think the difference is when we filter by `ss_sold_date_sk not in (...)` we have filter out the rows which has null value on `ss_sold_date_sk` as well, and when we query the table with equality delete files, we do not filter out the rows which has null value on `ss_sold_date_sk`.

As I investigated, the count of rows which meet the query predicate and have null value on `ss_sold_date_sk` is 489, exactly the difference between the two.

**Comment by nmahadevuni** [comment]
The issue is not with the equality delete reader in Iceberg as mentioned by @hantangwangd above. It seems the elimination of NULLs because of NOT IN used in the comparison is the problem. When NOT EXISTS is used, we get the correct result.
