### ISSUE TITLE
[Iceberg] Distinct value statistics are wrong when filters are applied

### ISSUE THREAD

**Issue by ZacBlanco** [prestodb/presto#22357]
When calling `getTableStatistics` with a filter on a partition column, the distinct value count and some other statistics are wrong.

## Your Environment

- Iceberg connector with `HADOOP` catalog configured
- Presto 0.286

## Expected Behavior

Stats should be correct, or at least a closer estimate. NDVs should never exceed row counts. See test cases below for exact scenarios.

## Current Behavior

Table statistics are incorrect when filters are pushed down to the table scan using the Iceberg connector with a `HADOOP` configured catalog.

## Possible Solution

- For fixing min/max, make sure predicates are applied properly in the table scan.
- For fixing distinct value counts, we don't have a good way to merge distinct counts from separate partitions
  - Iceberg partition statistics don't have a way to get better estimates through probabilistic data structures like HLL or theta sketch. Likely need to resort to some heuristic.
  - a simple heuristic to start could be to use the entire distinct count of the table, and multiple by the ratio of selected rows from the partition filters.
  - e.g. table with $R$ rows has $D$ distinct values. A query for a set of partitions returns $R_p$ rows, when all manifest row counts are added together. The returned distinct value count could be $\frac{R_p}{R}\cdot D$. This would assume a uniform distribution of distinct values across partitions.

## Steps to Reproduce

```sql
-- setup
CREATE TABLE t (i int) WITH (partitioning = ARRAY['i']);
INSERT INTO t VALUES 1, 2, 3, 4, 5, 6, 7, 7, 7, 7;
ANALYZE t;
```

We can see stats for the whole table are correct with min/max and distinct values.

```sql
presto:z> SHOW STATS FOR t;
 column_name | data_size | distinct_values_count | nulls_fraction | row_count | low_value | high_value
-------------+-----------+-----------------------+----------------+-----------+-----------+------------
 i           | NULL      |                   7.0 |            0.0 | NULL      | 1         | 7
 NULL        | NULL      | NULL                  | NULL           |      10.0 | NULL      | NULL
(2 rows)
```

Now, apply some filters to the table:

`i = 7`: _BUG_: This should show distinct_values_count = 1. min = 7, max = 7, row count should be 4.
```sql
presto:z> SHOW STATS FOR (SELECT * FROM t WHERE i = 7);
 column_name | data_size | distinct_values_count | nulls_fraction | row_count | low_value | high_value
-------------+-----------+-----------------------+----------------+-----------+-----------+------------
 i           | NULL      |                   7.0 |            0.0 | NULL      | 1         | 7
 NULL        | NULL      | NULL                  | NULL           |      10.0 | NULL      | NULL
```

`i < 7`: _BUG_: distinct values should be 6 here.
```sql
presto:z> SHOW STATS FOR (SELECT * FROM t WHERE i < 7);
 column_name | data_size | distinct_values_count | nulls_fraction | row_count | low_value | high_value
-------------+-----------+-----------------------+----------------+-----------+-----------+------------
 i           | NULL      |                   7.0 |            0.0 | NULL      | 1         | 6
 NULL        | NULL      | NULL                  | NULL           |       6.0 | NULL      | NULL
```

`i <= 7`: _Correct_ because this contains all rows.
```sql
presto:z> SHOW STATS FOR (SELECT * FROM t WHERE i <= 7);
 column_name | data_size | distinct_values_count | nulls_fraction | row_count | low_value | high_value
-------------+-----------+-----------------------+----------------+-----------+-----------+------------
 i           | NULL      |                   7.0 |            0.0 | NULL      | 1         | 7
 NULL        | NULL      | NULL                  | NULL           |      10.0 | NULL      | NULL
```

`i >= 7`: _BUG_: distinct values count should be 1. Other statistics are correct.
```sql
presto:z> SHOW STATS FOR (SELECT * FROM t WHERE i >= 7);
 column_name | data_size | distinct_values_count | nulls_fraction | row_count | low_value | high_value
-------------+-----------+-----------------------+----------------+-----------+-----------+------------
 i           | NULL      |                   7.0 |            0.0 | NULL      | 7         | 7
 NULL        | NULL      | NULL                  | NULL           |       4.0 | NULL      | NULL
```

`i > 7`: _Correct_. No files should be scanned here, so we shouldn't have any statistics.
```sql
presto:z> SHOW STATS FOR (SELECT * FROM t WHERE i > 7);
 column_name | data_size | distinct_values_count | nulls_fraction | row_count | low_value | high_value
-------------+-----------+-----------------------+----------------+-----------+-----------+------------
 i           | NULL      | NULL                  | NULL           | NULL      | NULL      | NULL
 NULL        | NULL      | NULL                  | NULL           |       0.0 | NULL      | NULL
```

## Context

Incorrect NDV counts affects query join plans and results in longer execution times.

**Comment by hantangwangd** [comment]
Seems min/max problem is caused by that in `PickTableLayout` we use `connectorTableLayout.getPredicate()` as current constraint to re-construct `TableScanNode`, however Iceberg connector maintains this constraint in its `connectorTableHandle` and do not fill the message to table layout when executing `IcebergAbstractMetadata.getTableLayout(..)` at the very beginning, so the message would be lost and eventually we got an `ALL` constraint from `TableScanNode` when thoroughly pushdown happens.

I notice we have filled the constraint to table layout when `pushdown_filter_enabled` is true, this different behavior has bother me a while, we can take the opportunity to unify their behaviors while fixing this problem.

**Comment by ZacBlanco** [comment]
FYI @hantangwangd I am actively working on this in https://github.com/prestodb/presto/pull/22395

**Comment by hantangwangd** [comment]
@ZacBlanco That would be great!
