### ISSUE TITLE
[Prestissimo] Very slow HashProbe for an expanding JOIN

### ISSUE THREAD

**Issue by aaneja** [prestodb/presto#22385]
For the query below, which has an expanding JOIN, we see poor performance against `tpcds_sf1000_parquet_varchar`

```
 with ss as (select SS_NET_PAID, SS_ADDR_SK ,SS_SOLD_DATE_SK, ss_item_sk from store_sales where SS_SOLD_DATE_SK<2451200 ) select sum(s1.ss_item_sk) from ss s1 , ss s2 where s1.ss_item_sk = s2.ss_item_sk;
 ```
 For the query [20240401_092330_00011_ikvfz](https://grafana.ibm.prestodb.dev/d/cc6a4ccf-2fc7-4220-8f4e-397b03061acf/query-detail-comparisons?orgId=1&from=now-90d&from=1710239927178&to=now&to=1710240771800&var-query1=20240401_092330_00011_ikvfz)
 The CTE `ss` matches 567M rows and 4.22 Gb is exchanged  from Stage 2 and Stage 3 -
 
![image](https://github.com/prestodb/presto/assets/1797669/2fb07348-601a-46bf-80fd-869f94c89fb7)
 
The JOIN is expanding and it produces 2.14T rows. The issue here is with the `HashProbe` operator is extremely slow, netting only a row transfer speed of 2.61K/s
 
![hash_probe_is_slow](https://github.com/prestodb/presto/assets/1797669/04dfcac7-5b34-4d1a-a3e1-2ad9504cb952)

The net effect is that the query takes 40 minutes to finish
Full query info JSON is attached
[simple_agg_on_self_join_20240401_092330_00011_ikvfz.json](https://github.com/prestodb/presto/files/14825656/simple_agg_on_self_join_20240401_092330_00011_ikvfz.json)

**Comment by aditi-pandit** [comment]
@anant.aneja: 

Do you have access to this cluster yet ? I am interested in knowing the count of rows per key.
`with ss as (select SS_NET_PAID, SS_ADDR_SK ,SS_SOLD_DATE_SK, ss_item_sk from store_sales where SS_SOLD_DATE_SK<2451200 ) select ss_item_sk, count(ss_item_sk) from ss group by ss_item_sk;`

We know there are perf issues with joins that have lots of chaining due to many rows/key.
ref https://github.com/facebookincubator/velox/issues/9078 (

**Comment by aditi-pandit** [comment]
@aaneja, @yzhang1991 : The underlying issue is fixed. Maybe we should validate this issue again.

**Comment by aaneja** [comment]
Yes, IMO the fix is working. I see much faster transfer rate for the HashProbe -
![image](https://github.com/prestodb/presto/assets/1797669/f8f43ff6-d5fc-4b76-9e9d-b786a338e72d)

JSON - 
[20240419_064353_00010_kbc2i.json](https://github.com/prestodb/presto/files/15035802/20240419_064353_00010_kbc2i.json)
