### ISSUE TITLE
Add examples to regular expression documentation

### ISSUE THREAD

**Issue by dain** [prestodb/presto#2241]
Each regular expression function should have a concise example.  The docs are here:

https://raw.githubusercontent.com/cberner/presto/extract_all/presto-docs/src/main/sphinx/functions/regexp.rst

**Comment by ronakshah94** [comment]
Hi, I want to have a look at this issue but the link appears to be broken. Any updates on this?

**Comment by cawallin** [comment]
The current docs as listed on the website are here: https://prestodb.io/docs/current/functions/regexp.html.

And the source code is here: https://raw.githubusercontent.com/facebook/presto/c244ebaa629638fc0035f38ddc1c07948dba5100/presto-docs/src/main/sphinx/functions/regexp.rst.

**Comment by electrum** [comment]
Fixed in #4477
