### ISSUE TITLE
CI Failing with docker-compose: command not found

### ISSUE THREAD

**Issue by ZacBlanco** [prestodb/presto#22413]
A number of CI actions seem to rely on docker-compose. However, it seems the actions which require it are failing intermittently due to the command not being installed.

[Example Logs](https://github.com/prestodb/presto/actions/runs/8541819821/job/23402074694)

```
Run presto-product-tests/bin/run_on_docker.sh singlenode -g hdfs_no_impersonation,avro
  presto-product-tests/bin/run_on_docker.sh singlenode -g hdfs_no_impersonation,avro
  shell: /usr/bin/bash -e {0}
  env:
    CONTINUOUS_INTEGRATION: true
    MAVEN_OPTS: -Xmx1024M -XX:+ExitOnOutOfMemoryError
    MAVEN_INSTALL_OPTS: -Xmx2G -XX:+ExitOnOutOfMemoryError
    MAVEN_FAST_INSTALL: -B -V --quiet -T 1C -DskipTests -Dair.check.skip-all --no-transfer-progress -Dmaven.javadoc.skip=true
    RETRY: .github/bin/retry
    JAVA_HOME_8.0.402_x64: /opt/hostedtoolcache/jdk/8.0.402/x64
    JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.402/x64
    JAVA_HOME_8_0_402_X64: /opt/hostedtoolcache/jdk/8.0.402/x64
presto-product-tests/bin/run_on_docker.sh: line 130: docker-compose: command not found
Error: Process completed with exit code 127.
```

I wonder if we added new CI machines or something was updated which skips installing `docker-compose`?

**Comment by imjalpreet** [comment]
Another related example: https://github.com/prestodb/presto/actions/runs/8530290590/job/23369147515#step:7:1

**Comment by imjalpreet** [comment]
I noticed this with Github CI only

**Comment by rschlussel** [comment]
https://github.com/orgs/community/discussions/116610#discussion-6453112 looks like we need to upgrade our docker command

**Comment by rschlussel** [comment]
Looks like this is going to become fully blocked in the next day or 2 https://github.com/actions/runner-images/issues/9692.  I have a PR where I've tried to change everything from docker-compose to docker compose, but I'm still seeing some failures https://github.com/prestodb/presto/pull/23360.  I don't really know a ton about configuring docker or about our test setup so if anybody has more knowledge here, please do jump in.

**Comment by rschlussel** [comment]
actually, got it working. https://github.com/prestodb/presto/pull/23360 is ready for review.
