### ISSUE TITLE
HiveColumnHandle checkArgument message is incorrect

### ISSUE THREAD

**Issue by elharo** [prestodb/presto#22457]
```
        checkArgument(hiveColumnIndex >= 0 || columnType == PARTITION_KEY || columnType == SYNTHESIZED || columnType == AGGREGATED, format("hiveColumnIndex:%d is negative, columnType:%s", hiveColumnIndex, columnType.toString()));
```

This condition can fail (correctly) when the hiveColumnIndex is not negative. Split this into multiple checks with different and correct error messages. 

The fix requires a test, and that test should be written and fail *before* the fix is written.

**Comment by TishyaaChaudhry** [comment]
I would like to work on this. Thanks

**Comment by elharo** [comment]
NVM, this check is corrct
