### ISSUE TITLE
Remove TestingHiveStorageFormat

### ISSUE THREAD

**Issue by elharo** [prestodb/presto#22476]
TestHiveIntegrationSmokeTest.TestingHiveStorageFormat is not needed. It just wraps a couple of fields that don't need to be wrapped. Refactor to remove it and the code gets simpler.

**Comment by AjaySDwivedi1** [comment]
I can work on this issue what file is it in?

**Comment by TishyaaChaudhry** [comment]
I would like to work on this please

**Comment by elharo** [comment]
Send a PR

**Comment by TishyaaChaudhry** [comment]
I run out of RAM when I try building the repo locally using `./mvnw clean install `. Are there any specific tests I can run to test my changes? Thanks

**Comment by tdcmeehan** [comment]
@TishyaaChaudhry you can submit a draft PR to kick off tests.
