### ISSUE TITLE
[docs] document noisy_approx_set_sfm_from_index_and_zeros

### ISSUE THREAD

**Issue by steveburnett** [prestodb/presto#22508]
Document the new function ``noisy_approx_set_sfm_from_index_and_zeros`` that was added in [PR 22426](https://github.com/prestodb/presto/pull/22426). 

## Expected Behavior or Use Case
Following the guidelines in [CONTRIBUTING.md](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md#designing-your-code), "All new language features, new functions, and major features have documentation added".

## Presto Component, Service, or Connector
Documentation. 

## Possible Implementation
Add documentation of the function to the appropriate page in [Functions and Operators](http://prestodb.io/docs/0.286/functions.html). 

## Context
[PR 22426](https://github.com/prestodb/presto/pull/22426).

**Comment by steveburnett** [comment]
@fazalmajid, would you be willing to take this issue on?

**Comment by fazalmajid** [comment]
@steveburnett Yes, I am planning to, but I am waiting for @jonhehir to first publish his documentation for the sfm functions to which this would be an addendum. That doc is complete but undergoing publication review for public release before it can be merged.

**Comment by jonhehir** [comment]
This was recently completed! See https://github.com/prestodb/presto/pull/22715. Thanks! cc @fazalmajid

**Comment by steveburnett** [comment]
Closing as Done, because @fazalmajid addressed this with #22799. Thanks!
