### ISSUE TITLE
DynamoDB connector

### ISSUE THREAD

**Issue by sotayamashita** [prestodb/presto#2253]
I try to create dynamoDB connector in my repository below:

https://github.com/sota0805/presto

**Comment by sota0805** [comment]
I try to create dynamoDB connector in my repository below:

https://github.com/sota0805/presto

**Comment by Zutai** [comment]
Anyone working on DynamoDB connector? I searched around, but did not find any such connector. Thus I decide to write one plugin for DynamoDB. Let me know if anyone want to work together.

**Comment by mishadoff** [comment]
Interested as well
