### ISSUE TITLE
[native] Delta table access via Symlink table using Hive Connector

### ISSUE THREAD

**Issue by agrawalreetika** [prestodb/presto#22580]
Delta table access via Symlink table using Hive Connector in Prestissimo

## Expected Behavior or Use Case
Delta table can be accessed using hive connector by registering them as a symlink tables in HMS. https://docs.delta.io/latest/presto-integration.html
This is to extend this same support for Prestissimo using Hive Connector.

## Presto Component, Service, or Connector
presto-native-execution

## Possible Implementation
Currenlty mapping for inputformat and serde are missing in Prestissimo to access symlink tables. We need to add that mapping in PrestoToVeloxConnector.cpp to successfully access Delta tables.

## Context
Delta table can be accessed using hive connector by registering them as a symlink tables in HMS. https://docs.delta.io/latest/presto-integration.html
This is to extend this same support for Prestissimo using Hive Connector.

**Comment by agrawalreetika** [comment]
CC @majetideepak Fyi

**Comment by aditi-pandit** [comment]
@tdcmeehan, @ZacBlanco 

@agrawalreetika : Do you have a prototype PR ?

**Comment by agrawalreetika** [comment]
We need just mapping of Symlink input format & serde in PrestoToVeloxConnector like https://github.com/agrawalreetika/prestodb/commit/8760651d721ce0dd9fb5251bb1f60e966e208999

Discussed about this with Deepak, he mentioned we should add test for this.
So I am open to get pointers around how do we write test for this? Since Presto hive connector Java doesn't support Creating symlink file.

**Comment by majetideepak** [comment]
@aditi-pandit This is similar to the Hudi change https://github.com/prestodb/presto/pull/19620.
 Reetika and I are looking into how we can test Delta similar to Hudi and add a generic testing framework for both Hudi and Delta/
