### ISSUE TITLE
TPC-H Native Execution, SQL22 Scalar function name not registered: presto.default.substring, called with arguments: (VARCHAR, BIGINT, BIGINT).

### ISSUE THREAD

**Issue by yixi-gu** [prestodb/presto#22590]
## Your Environment

* Presto version used: 0.287
* Storage: S3
* Data source and connector used: Hive 
* Deployment: Cloud

Query 20240422_142024_00013_rcwzn failed:  Scalar function name not registered: presto.default.substring, called with arguments: (VARCHAR, BIGINT, BIGINT).

**Comment by ZacBlanco** [comment]
The documentation states the function name is `substr`, not `substring`: https://prestodb.io/docs/current/functions/string.html#id5

**Comment by aditi-pandit** [comment]
@yixi-gu : We are tracking TPC-H query execution in Prestissimo using integration test https://github.com/prestodb/presto/blob/master/presto-native-execution/src/test/java/com/facebook/presto/nativeworker/AbstractTestNativeTpchQueries.java.

They are using SQL queries https://github.com/prestodb/presto/tree/master/presto-native-execution/src/test/resources/tpch/queries
