### ISSUE TITLE
[docs] Use a separate chapter or subchapter for describing Iceberg procedures

### ISSUE THREAD

**Issue by hantangwangd** [prestodb/presto#22608]
Currently we describe procedures and other SQLs mixed in the same chapter `SQL Support` in Iceberg, it doesn't seem to have a strong sense of hierarchy as we are planning to add more procedures. So maybe we should use a separate chapter or subchapter for describing procedures.

For reference, spark and trino all use a separate chapter to describe procedures as following:

https://iceberg.apache.org/docs/latest/spark-procedures/
https://trino.io/docs/current/connector/iceberg.html#procedures

## Expected Behavior or Use Case
Use a separate chapter or subchapter for describing Iceberg procedures

## Presto Component, Service, or Connector
Iceberg docs

## Possible Implementation
N/A

## Example Screenshots (if appropriate):
N/A

## Context
https://iceberg.apache.org/docs/latest/spark-procedures/
https://trino.io/docs/current/connector/iceberg.html#procedures

**Comment by hantangwangd** [comment]
cc @steveburnett 

Do you think this is necessary?

**Comment by steveburnett** [comment]
> cc @steveburnett
> 
> Do you think this is necessary?

Thanks for opening this discussion! I think this is a good idea. Examining the two examples you provide, I think the Trino example is a better fit for the current Presto doc than the Iceberg example. We can separate the subheading out to a separate page later if the subheading does not benefit us enough.

In the Iceberg doc I find:

* [Register Table](http://prestodb.io/docs/0.286/connector/iceberg.html#register-table)
* [Unregister Table](http://prestodb.io/docs/0.286/connector/iceberg.html#unregister-table)
* (in process) `expire_snapshots` procedure that you're adding in [PR 22609](https://github.com/prestodb/presto/pull/22609). 

I would be happy to have a subheading of Procedures on the Iceberg Connector page and move these procedures into that subheading.

**Comment by kiersten-stokes** [comment]
Good idea! We also have the `rollback_to_snapshot` procedure for Iceberg as well, which I think gets lost in the current documentation

**Comment by hantangwangd** [comment]
@steveburnett  thank you for the guidance. Then do you think it's better to make the change in a dedicated PR or directly make the change in PR #22609 ?

**Comment by steveburnett** [comment]
> Good idea! We also have the `rollback_to_snapshot` procedure for Iceberg as well, which I think gets lost in the current documentation

!!!

I overlooked `rollback_to_snapshot` when I skimmed the current Presto Iceberg doc just now for currently documented procedures so you're correct about `rollback_to_snapshot` getting lost. Thanks! So that's 3 existing and 1 soon to be there as content for the new subheading (or page).

**Comment by steveburnett** [comment]
> @steveburnett thank you for the guidance. Then do you think it's better to make the change in a dedicated PR or directly make the change in PR #22609 ?

@hantangwangd, I have a mild preference for a dedicated docs-only PR because I encourage smaller PRs when possible. That's only a mild preference in this case though.  

I will leave it to you: if you want to implement this change in your existing PR I support you doing so. If you choose to add this to your existing PR, please update PR 22609's Description and add "Fixes Issue 22608". 

If you want to focus on finishing and merging your existing PR, a separate docs-only PR could be done by you, me, or anyone. A docs-only PR for this should be tagged as a "Good First Issue".

**Comment by hantangwangd** [comment]
@steveburnett I agree with you. Leave this change to a separate docs-only PR seems better. And I will focus on the existing PR.

**Comment by steveburnett** [comment]
Edited title and added "good first issue" tag for visibility.
