### ISSUE TITLE
compile error: dependency-scope-maven-plugin:0.8:check

### ISSUE THREAD

**Issue by zhongxiaoyi738** [prestodb/presto#22624]
git clone https://github.com/prestodb/presto/tree/release-0.285

+ mvn -version
Apache Maven 3.8.8 (4c87b05d9aedce574290d1acc98575ed5eb6cd39)
Maven home: /var/jenkins_home/maven_home/apache-maven-3.8.8
Java version: 1.8.0_241, vendor: Oracle Corporation, runtime: /usr/local/jdk1.8.0_241/jre
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-1160.42.2.el7.x86_64", arch: "amd64", family: "unix"
+ mvn clean install -f ./presto-root/pom.xml -DskipTests

[INFO] presto-root ........................................ SUCCESS [ 27.314 s]
[INFO] presto-testng-services ............................. SUCCESS [  8.842 s]
[INFO] presto-common ...................................... SUCCESS [ 15.743 s]
[INFO] presto-spi ......................................... SUCCESS [  7.812 s]
[INFO] presto-plugin-toolkit .............................. SUCCESS [  2.898 s]
[INFO] presto-client ...................................... SUCCESS [  3.775 s]
[INFO] presto-parser ...................................... SUCCESS [ 10.764 s]
[INFO] presto-geospatial-toolkit .......................... SUCCESS [  8.140 s]
[INFO] presto-analyzer .................................... SUCCESS [  2.572 s]
[INFO] presto-bytecode .................................... SUCCESS [  3.473 s]
[INFO] presto-matching .................................... SUCCESS [  1.557 s]
[INFO] presto-memory-context .............................. SUCCESS [  1.467 s]
[INFO] presto-expressions ................................. SUCCESS [  2.022 s]
[INFO] presto-tpch ........................................ SUCCESS [  4.899 s]
[INFO] presto-thrift-api .................................. SUCCESS [  3.688 s]
[INFO] presto-function-namespace-managers ................. SUCCESS [  7.290 s]
[INFO] presto-main ........................................ FAILURE [ 34.614 s]
[INFO] presto-resource-group-managers ..................... SKIPPED
[INFO] presto-thrift-testing-udf-server ................... SUCCESS [  6.057 s]
[INFO] presto-tests ....................................... SKIPPED
[INFO] presto-atop ........................................ SKIPPED
[INFO] presto-hive-common ................................. SUCCESS [  3.419 s]
[INFO] presto-cache ....................................... SUCCESS [  7.734 s]
[INFO] presto-jmx ......................................... SKIPPED
[INFO] presto-record-decoder .............................. SKIPPED
[INFO] presto-kafka ....................................... SKIPPED
[INFO] presto-redis ....................................... SKIPPED
[INFO] presto-accumulo .................................... SKIPPED
[INFO] presto-cassandra ................................... SKIPPED
[INFO] presto-bigquery .................................... SKIPPED
[INFO] presto-blackhole ................................... SKIPPED
[INFO] presto-memory ...................................... SKIPPED
[INFO] presto-orc ......................................... SKIPPED
[INFO] presto-benchmark ................................... SKIPPED
[INFO] presto-parquet ..................................... SKIPPED
[INFO] presto-rcfile ...................................... SKIPPED
[INFO] presto-hive-metastore .............................. SKIPPED
[INFO] presto-tpcds ....................................... SKIPPED
[INFO] presto-testing-docker .............................. SUCCESS [  4.702 s]
[INFO] presto-hive ........................................ SKIPPED
[INFO] presto-hive-hadoop2 ................................ SKIPPED
[INFO] presto-iceberg ..................................... SKIPPED
[INFO] presto-i18n-functions .............................. SKIPPED
[INFO] presto-teradata-functions .......................... SKIPPED
[INFO] presto-example-http ................................ SKIPPED
[INFO] presto-local-file .................................. SKIPPED
[INFO] presto-base-jdbc ................................... SKIPPED
[INFO] presto-mysql ....................................... SKIPPED
[INFO] presto-oracle ...................................... SKIPPED
[INFO] presto-postgresql .................................. SKIPPED
[INFO] presto-prometheus .................................. SKIPPED
[INFO] presto-redshift .................................... SKIPPED
[INFO] presto-sqlserver ................................... SKIPPED
[INFO] presto-mongodb ..................................... SKIPPED
[INFO] presto-ml .......................................... SKIPPED
[INFO] presto-jdbc ........................................ SKIPPED
[INFO] presto-cli ......................................... SUCCESS [  5.996 s]
[INFO] presto-product-tests ............................... SKIPPED
[INFO] presto-pinot-toolkit ............................... SKIPPED
[INFO] presto-pinot ....................................... SKIPPED
[INFO] presto-benchmark-driver ............................ SUCCESS [  7.631 s]
[INFO] presto-password-authenticators ..................... SUCCESS [  7.870 s]
[INFO] presto-session-property-managers ................... SUCCESS [  3.305 s]
[INFO] presto-node-ttl-fetchers ........................... SUCCESS [  3.003 s]
[INFO] presto-cluster-ttl-providers ....................... SUCCESS [  2.947 s]
[INFO] presto-kudu ........................................ SKIPPED
[INFO] presto-singlestore ................................. SKIPPED
[INFO] presto-hana ........................................ SKIPPED
[INFO] presto-thrift-testing-server ....................... SKIPPED
[INFO] presto-thrift-connector ............................ SKIPPED
[INFO] presto-elasticsearch ............................... SKIPPED
[INFO] presto-druid ....................................... SKIPPED
[INFO] presto-hive-function-namespace ..................... SKIPPED
[INFO] presto-delta ....................................... SKIPPED
[INFO] presto-hudi ........................................ SKIPPED
[INFO] presto-clickhouse .................................. SKIPPED
[INFO] presto-server ...................................... SKIPPED
[INFO] presto-spark-common ................................ SUCCESS [  1.928 s]
[INFO] presto-verifier .................................... SKIPPED
[INFO] presto-testing-server-launcher ..................... SKIPPED
[INFO] presto-benchto-benchmarks .......................... SKIPPED
[INFO] presto-proxy ....................................... SKIPPED
[INFO] presto-benchmark-runner ............................ SKIPPED
[INFO] presto-spark-classloader-interface ................. SUCCESS [  5.056 s]
[INFO] presto-spark-base .................................. SKIPPED
[INFO] presto-spark ....................................... SKIPPED
[INFO] presto-spark-package ............................... SKIPPED
[INFO] presto-spark-launcher .............................. SUCCESS [  7.847 s]
[INFO] presto-spark-testing ............................... SKIPPED
[INFO] presto-thrift-spec ................................. SKIPPED
[INFO] presto-google-sheets ............................... SKIPPED
[INFO] presto-grpc-api .................................... SKIPPED
[INFO] presto-grpc-testing-udf-server ..................... SKIPPED
[INFO] presto-lark-sheets ................................. SKIPPED
[INFO] presto-test-coverage ............................... SKIPPED
[INFO] presto-native-execution ............................ SKIPPED
[INFO] presto-router ...................................... SKIPPED
[INFO] presto-open-telemetry .............................. SUCCESS [  2.502 s]
[INFO] redis-hbo-provider ................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:45 min
[INFO] Finished at: 2024-04-29T07:38:26Z
[INFO] ------------------------------------------------------------------------
[ERROR] **Failed to execute goal com.hubspot.maven.plugins:dependency-scope-maven-plugin:0.8:check (default) on project presto-main: Error resolving descriptor for artifact com.sun:tools:1.8**: Failed to read artifact descriptor for com.sun:tools:jar:1.8: Could not transfer artifact com.sun:tools:pom:1.8 from/to greeMavenMirror (https://nexus-di.gree.com/repository/maven-public/): transfer failed for https://nexus-di.gree.com/repository/maven-public/com/sun/tools/1.8/tools-1.8.pom, status: 500 Internal Server Error -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :presto-main

**Comment by ZacBlanco** [comment]
@zhongxiaoyi738 Make sure you're using Java 8

**Comment by ZacBlanco** [comment]
It looks like this could be a transient error with the mirror that your local machine/maven is configured to use.

> Could not transfer artifact com.sun:tools:pom:1.8 from/to greeMavenMirror (https://nexus-di.gree.com/repository/maven-public/): transfer failed for https://nexus-di.gree.com/repository/maven-public/com/sun/tools/1.8/tools-1.8.pom, status: 500 Internal Server Error -> [Help 1]

See if you can remove that mirror from the available list and try again

**Comment by zhongxiaoyi738** [comment]
com.sun:tools:1.8，is jdk's lib.

**Comment by elharo** [comment]
I occasionally see this. It's caused by a failure to connect over VPN to the local nexus repo configured in settings.xml.
