### ISSUE TITLE
Document types of $file_size and $file_modified_time

### ISSUE THREAD

**Issue by elharo** [prestodb/presto#22627]
On https://prestodb.io/docs/current/connector/hive.html I see

The Hive connector exposes extra hidden metadata columns in Hive tables. You can query these columns as a part of SQL query like any other columns of the table.

$path : Filepath for the given row data
$file_size : Filesize for the given row
$file_modified_time : Last file modified time for the given row

However this fails to say whether these are int32s or int64s. Add that detail. I'm pretty sure the correct answer is int64.

**Comment by aditi-pandit** [comment]
@steveburnett : $file_size and $file_modified_time are int64_t for Presto Native Engine. I recently added these in Velox.

ref
https://github.com/facebookincubator/velox/pull/8800
https://github.com/prestodb/presto/pull/21965

This would be compatible with Presto java. Though please confirm with Reetika as well.

**Comment by agrawalreetika** [comment]
@steveburnett : $file_size and $file_modified_time are int64_t for Presto Java as well.

**Comment by steveburnett** [comment]
Thanks @aditi-pandit and @agrawalreetika! I will open a doc PR to update the page.
