### ISSUE TITLE
[native] Prestissimo timezone not found using CAST if timezone is set in Presto CLI via Java option

### ISSUE THREAD

**Issue by czentgr** [prestodb/presto#22789]
## Your Environment

* Presto version used: 288-snapshot/latest
* Storage (HDFS/S3/GCS..):
* Data source and connector used:
* Deployment (Cloud or On-prem):
* [Pastebin](https://pastebin.com/) link to the complete debug logs:

Started CLI with timezone option
```
java -jar -Duser.timezone=America/LosAngeles  ~/gitspace/presto/presto-cli/target/presto-cli-*-executable.jar --server 127.0.0.1:8081
```

Local server is the `HiveExternalWorkerQueryRunner` for the native worker which is expected to use `-Duser.timezone=America/Bahia_Banderas` (`-06:00`) when started.
The machine system time zone is EDT (`-04:00`).

```
presto:default> CREATE TABLE sampletable ( "emp_name" varchar(20), "emp_location" varchar(20), "emp_id" integer, "dep_id" varchar(4), "u_id" integer ) WITH ( format = 'DWRF' );
CREATE TABLE
presto:default> INSERT INTO sampletable VALUES ('row1', 'here1', 1, 'row1', 1);
INSERT: 1 row

Query 20240520_195941_00008_gwgh8, FINISHED, 2 nodes
Splits: 2 total, 2 done (100.00%)
[Latency: client-side: 0:01, server-side: 0:01] [0 rows, 0B] [0 rows/s, 0B/s]

presto:default> select * from sampletable;
 emp_name | emp_location | emp_id | dep_id | u_id
----------+--------------+--------+--------+------
 row1     | here1        |      1 | row1   |    1
(1 row)

Query 20240520_195948_00009_gwgh8, FINISHED, 1 node
Splits: 2 total, 2 done (100.00%)
[Latency: client-side: 0:01, server-side: 0:01] [1 rows, 0B] [1 rows/s, 0B/s]

presto:default> SELECT emp_name, emp_location, CAST(emp_id AS varchar(10)) AS emp_id_str FROM sampletable;
```

The last select results in failure:
```
Query 20240520_200031_00010_gwgh8 failed: -04:00 not found in timezone database
```
Not specifying `-Duser.timezone` when starting the CLI results in no failure
```
 ~/presto $ java -jar  ~/gitspace/presto/presto-cli/target/presto-cli-*-executable.jar --server 127.0.0.1:8081
presto> use hive.default;
USE
presto:default> SELECT emp_name, emp_location, CAST(emp_id AS varchar(10)) AS emp_id_str FROM sampletable;
 emp_name | emp_location | emp_id_str
----------+--------------+------------
 row1     | here1        | 1
(1 row)

Query 20240520_201503_00012_gwgh8, FINISHED, 1 node
Splits: 2 total, 2 done (100.00%)
[Latency: client-side: 0:01, server-side: 394ms] [1 rows, 0B] [2 rows/s, 0B/s]

```

Further investigation revealed that the timezone database is used in the CAST expression eval (via `PrestoCastHooks` and `date::locate_zone`). A summary below:

Prestissimo originally receives the session timezone key and converts the timezone key received to the timezone in `toVeloxConfigs` and `velox::util::getTimeZoneName`.
In this case it received key `601` which maps to `-04:00`. 

In addition `legacy_timestamp` also defaults to true.
Later it then attempts to locate the timezone via
```
date::locate_zone(sessionTzName)
```
in the `PrestoCastHooks` constructor.

At this point the sessionTzName is `-04:00`. And such a timezone does not exist in the timezone map that is loaded into memory during `init_tzdb`.

The invalid timezone parsing was discussed in https://github.com/prestodb/presto/issues/21461 and this issue appears to be related.
The problem is that the time zone key is an offset and not an actual timezone name that can be found in the timezone database.

## Expected Behavior

Successful query execution
```
presto:default> SELECT emp_name, emp_location, CAST(emp_id AS varchar(10)) AS emp_id_str FROM sampletable;
 emp_name | emp_location | emp_id_str
----------+--------------+------------
 row1     | here1        | 1
(1 row)

Query 20240520_201503_00012_gwgh8, FINISHED, 1 node
Splits: 2 total, 2 done (100.00%)
[Latency: client-side: 0:01, server-side: 394ms] [1 rows, 0B] [2 rows/s, 0B/s]
```

## Current Behavior
An error occurs
```
presto:default> SELECT emp_name, emp_location, CAST(emp_id AS varchar(10)) AS emp_id_str FROM sampletable;

Query 20240520_200031_00010_gwgh8 failed: -04:00 not found in timezone database
```
for any CAST expression.

## Possible Solution

I'm not sure that the session timezone actually sent by the coordinator is correct. The timezone key provided is the system timezone and not the CLI set timezone. Setting the timezone on the CLI only seems to ensure that the session timezone is sent.
It doesn't seem correct that the system timezone key is sent.

## Steps to Reproduce

1. Start HiveExternalWorkerQueryRunner
2. Start Prestissimo worker
3. Start PrestoCLI with `-Duser.timezone=` set to some value
4. Run a query with a CAST expression (e.g. converting integer to varchar).

**Comment by tdcmeehan** [comment]
@czentgr it's because there's a typo in your `user.timezone` field.  Unfortunately, Java doesn't validate this value, and defaults to the system time when it's unknown.  `America/LosAngeles` is not a valid tzdata entry, but `America/Los_Angeles`, so if you just correct that value then it should be fixed.

**Comment by tdcmeehan** [comment]
Just to add, when Java defaults to your local system time, it defaults to `-04:00` instead of `GMT+4`, which then maps to 601.  This is non-standard and Java-specific as you noted.

**Comment by czentgr** [comment]
@tdcmeehan Thank you! I didn't notice the typo. This explains why it was using `-04:00` as the default. Which means it must have seen `EDT` and converted that into the offset. Similar things happen when one uses `PDT` (and these varieties), e.g.
```
-Duser.timezone=PDT
```

The conversion is from PDT to `-07:00` resulting in the same issue of timezone not found. 
I suppose the scenario is somewhat contrived because a normal user would use the `presto-cli` where it is not clear on how to pass JVM arguments as opposed to using the `java -jar` method. But I suppose users have been using this method to override the local timezone and hence an enhancement request to set the session timezone in the cli vai SET command also exists which could do timezone validation etc.
