### ISSUE TITLE
Add jenkins pipeline to build and publish Drift

### ISSUE THREAD

**Issue by ericyuliu** [prestodb/presto#22807]
Add a new pipeline for build and publish Drift
https://github.com/prestodb/drift

Similar to the [Airlift](https://ci.ahana.dev/job/oss-presto-release/job/airlift/job/pipeline-release-airlift/) pipeline in Jenkins, we are missing the same for Drift.

Currently, if changes are made in Drift, developers has no solution to publish them and consume them from Presto.

**Comment by wanglinsong** [comment]
1.38 is available now
https://repo1.maven.org/maven2/com/facebook/drift/drift-server/1.38/
