### ISSUE TITLE
Logo is missing in 0.287 Documentation

### ISSUE THREAD

**Issue by knu** [prestodb/presto#22817]
I see this piece of code in every HTML document under https://prestodb.io/docs/current/ (https://prestodb.io/docs/0.287/):

```html
<a href="#" title="Presto 0.287 Documentation" class="md-nav__button md-logo">
  <img src="_static/" alt=" logo" width="48" height="48">
</a>
```

I looked into presto-docs/src/main/sphinx/ but couldn't figure out how this could happen.

**Comment by ZacBlanco** [comment]
Thanks for pointing this out. My guess is this issue probably occurred due to a recent sphinx upgrade which broke the config. The logo url definition seems to be in `./presto-docs/src/main/sphinx/conf.py` in the `html_logo` variable. The recent change moved us from sphinx 5.X to 7.X.

**Comment by steveburnett** [comment]
Looking at an older version of the docs, for example [the 0.286 documentation](https://prestodb.io/docs/0.286/), I find 

```html
<a href="[#]" title="Presto 0.286 Documentation" class="md-nav__button md-logo">
        <img src="[_static/logo.png]" alt=" logo" width="48" height="48">
    </a>
```

The difference in the HTML output is 
```html
<img src="[_static/logo.png]"
```
and 
```html
<img src="_static/" 
```

@wanglinsong, could you look into this? 

Reproduce: 

https://prestodb.io/docs/current/

<img width="511" alt="Screenshot 2024-05-28 at 4 00 41 PM" src="https://github.com/prestodb/presto/assets/7013443/d91e5c1c-b7aa-4fc5-85a7-49a795eb3cf1">

contrast with 

https://prestodb.io/docs/0.286/

<img width="503" alt="Screenshot 2024-05-28 at 4 00 52 PM" src="https://github.com/prestodb/presto/assets/7013443/af4e0eac-2ce7-4ed3-96ad-2a85b34a7430">

**Comment by steveburnett** [comment]
Read through the [Sphinx Changelog](https://www.sphinx-doc.org/en/master/changes.html) and didn't see anything in particular. 

Editing my local [requirements.txt](https://github.com/prestodb/presto/blob/master/presto-docs/requirements.txt) and iterating up through sphinx versions from 5.x to 7.x, I found that html_logo is included in the build when ``sphinx==5.3.0``, but is not included when I set ``sphinx==6.0.0`` or above. 

``sphinx==5.3.0``
<img width="502" alt="Screenshot 2024-05-30 at 11 05 53 AM" src="https://github.com/prestodb/presto/assets/7013443/18e1dd2d-24fa-407d-96fb-9b80c74f93f8">

``sphinx==6.0.0``
<img width="489" alt="Screenshot 2024-05-30 at 11 06 39 AM" src="https://github.com/prestodb/presto/assets/7013443/74a0ed03-a93f-4c85-bf6f-b6327b312cb8">

So a workaround is to set ``sphinx==5.3.0`` in [requirements.txt](https://github.com/prestodb/presto/blob/master/presto-docs/requirements.txt). 

I'd like to find why our html_logo doesn't work with ``sphinx==6.0.0`` or above, but this is a start.

**Comment by ZacBlanco** [comment]
It looks like someone else had this issue and fixed it, but required them to modify the theme: https://github.com/bashtage/sphinx-material/issues/136

The current theme we are using is outdated and no longer maintained. It may be worth looking into a more actively maintained sphinx theme for the docs site.

**Comment by ZacBlanco** [comment]
I took a stab at updating our theme: https://github.com/prestodb/presto/pull/22887

This fixes the logo issue and also uses a newer and more maintained sphinx theme for our docs.
