### ISSUE TITLE
Presto silently converts NaN to zero when casting it to an INTEGER but throws when casting to BIGINT.

### ISSUE THREAD

**Issue by bikramSingh91** [prestodb/presto#22910]
Since NaN cannot be represented as an integer value, it would make sense to instead return a user error similar to how it does when casting to BIGINT.

```
SELECT CAST(NAN() AS INTEGER) ;  ---- 0
SELECT CAST(NAN() AS BIGINT) ;  ---- Error:  Unable to cast NaN to bigint
```

**Comment by rschlussel** [comment]
This needs to be fixed for all of the following casts
DOUBLE ->INTEGER
DOUBLE -> SMALLINT
DOUBLE  -> TINYINT.  
REAL -> BIGINT
REAL -> INTEGER
REAL -> SMALLINT
REAL -> TINYINT
