### ISSUE TITLE
Wrong timezone conversions for "America/Scoresbysund"

### ISSUE THREAD

**Issue by pedroerp** [prestodb/presto#22981]
The new Joda 2.12.6 release updates its internal timezone database to follow IANA's 2023d database. Presto currently uses 2.12.15:

https://github.com/prestodb/presto/blob/master/pom.xml#L58

2023d, among other things, updates the daylight savings transition for the "America/Scoresbysund" timezone. Until this gets fixed, any timezone conversions from this timezone for dates later than March 2024 will return wrong results.

On any linux distro with an updated tzdata:

```
$ TZ="America/Scoresbysund" date -d @1717027994
Wed May 29 11:13:14 PM -01 2024
```

In Presto:

```
presto> select date_format(from_unixtime(1717027994.0, 'America/Scoresbysund'), '%Y-%m-%d %r');
         _col0          
------------------------
 2024-05-30 12:13:14 AM 
```

Joda releases:

> https://www.joda.org/joda-time/changes-report.html#a2.12.7

IANA releases:

> https://data.iana.org/time-zones/tzdb/NEWS

**Comment by mbasmanova** [comment]
cc: @rschlussel @tdcmeehan

**Comment by elharo** [comment]
We really need to ditch joda time. In 2024 it isn't needed. I think I tried this a couple of years ago, and got blocked on the lack of support or reviews in presto-druid.

**Comment by elharo** [comment]
hanging joda version changes tzdata which must match deployed JVM tzdata
             Do not change this without also making sure it matches

**Comment by elharo** [comment]
https://www.oracle.com/java/technologies/tzdata-versions.html

I'm not sure how we can match the tzdata since it will be deplopyed across different JVMs.

**Comment by pedroerp** [comment]
> I'm not sure how we can match the tzdata since it will be deployed across different JVMs.

What is the story there? Is the timezone information got form Joda directly, or from the JVM? Not sure why both would be needed.

**Comment by elharo** [comment]
It probably depends on which chunk of code is running. There's an outstanding task to move away from Joda to java.time, and interestingly the PR i just sent out to do part of that seems to have uncovered a bug in the JDK.

**Comment by pedroerp** [comment]
Maintaining backwards compatibility will likely be an interesting challenge as you move away from joda. But regardless, in the short-term it would be nice if we could bump joda's version to align with results we get from the native engine.
