### ISSUE TITLE
Not able to build presto project

### ISSUE THREAD

**Issue by kkacstudent** [prestodb/presto#22988]
## Your Environment

* Presto version used: Latest github repo
* Storage (HDFS/S3/GCS..): local
* Data source and connector used: n/a
* Deployment (Cloud or On-prem): in-prem
* [Pastebin](https://pastebin.com/) link to the complete debug logs: https://pastebin.com/0JVf6XLX

## Expected Behavior
build should succeed

## Current Behavior
build fails

## Steps to Reproduce

1. git clone https://github.com/prestodb/presto.git
2. cd presto
3. ./mvnw clean install -DskipTests

## Context

java -version
java version "17.0.11" 2024-04-16 LTS
Java(TM) SE Runtime Environment (build 17.0.11+7-LTS-207)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.11+7-LTS-207, mixed mode, sharing)

16 GB Memory / 4 AMD vCPUs / 200 GB Disk / - Ubuntu 24.04 (LTS) x64

mvn -version
Apache Maven 3.9.7 (8b094c9513efc1b9ce2d952b3b9c8eaedaf8cbf0)
Maven home: /home/ubuntu1/.sdkman/candidates/maven/current
Java version: 17.0.11, vendor: Oracle Corporation, runtime: /home/ubuntu1/.sdkman/candidates/java/17.0.11-oracle
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "6.8.0-35-generic", arch: "amd64", family: "unix"

**Comment by agrawalreetika** [comment]
@kkacstudent Can you try using Java 8 and retry build - https://github.com/prestodb/presto?tab=readme-ov-file#requirements

**Comment by kkacstudent** [comment]
@agrawalreetika with java 8 too same problem faced.

**Comment by elharo** [comment]
```
[INFO] --- spotbugs-maven-plugin:3.1.10:spotbugs (spotbugs) @ presto-root ---
[WARNING] Error injecting: org.codehaus.mojo.spotbugs.SpotBugsMojo
com.google.inject.ProvisionException: Unable to provision, see the following errors:
 
1) Error injecting constructor, java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7
  at org.codehaus.mojo.spotbugs.SpotBugsMojo.<init>(Unknown Source)
  while locating org.codehaus.mojo.spotbugs.SpotBugsMojo
 
1 error
```

**Comment by elharo** [comment]
No idea why spotbugs failed for you, but try disabling it in pom.xml

**Comment by kkacstudent** [comment]
Seems like some dependencies were missing like python-venv, make etc. After running below command, seems to be working.

`sudo apt install build-essential python3.12-venv`

Would it be helpful to add these to the README.md build requirements?

**Comment by elharo** [comment]
I'm surprised those are required at all. But feel free to send a PR to update the instructions. If they're incomplete, that is a bug.

**Comment by kkacstudent** [comment]
Getting errors while building presto https://pastebin.com/Ziqh1Zvi

**Comment by ClarenceThreepwood** [comment]
Looks like you are trying to start PrestoServer. Are you setting up the IDE with these [steps](https://github.com/prestodb/presto/blob/master/README.md#building-presto:~:text=After%20opening%20the%20project%20in%20IntelliJ%2C%20double%20check%20that%20the%20Java%20SDK%20is%20properly%20configured%20for%20the%20project%3A)?
