### ISSUE TITLE
Flaky SingleStore tests

### ISSUE THREAD

**Issue by ClarenceThreepwood** [prestodb/presto#23006]
Several runs of SingleStore tests fail during setup
https://github.com/prestodb/presto/actions/runs/9496631864/job/26171464580?pr=22622
https://github.com/prestodb/presto/actions/runs/9491371374/job/26156661595?pr=22980

[INFO] Running TestSuite
2024-06-12T18:03:48.627-0600 INFO Missed environment variable: 'SINGLESTORE_LICENSE'
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Error:  
Cannot instantiate class com.facebook.presto.plugin.singlestore.TestSingleStoreDistributedQueries

[INFO] Running TestSuite
2024-06-13T02:53:59.151-0600 INFO Missed environment variable: 'SINGLESTORE_LICENSE'
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Error:  
Cannot instantiate class com.facebook.presto.plugin.singlestore.TestSingleStoreTypeMapping

**Comment by elharo** [comment]
Possibly related:

```
To execute unit tests you need to set up the environment variable 'SINGLESTORE_LICENSE' with SingleStore license value.
To get a free-tier license you need to create a free SingleStore account.
More details:
https://www.singlestore.com/blog/announcing-memsql-free-tier/
```

Related or otherwise, this makes me queasy. Executing the tests for this open source project should not require a license.
