### ISSUE TITLE
Getting error while building in intelli idea

### ISSUE THREAD

**Issue by kkacstudent** [prestodb/presto#23056]
## Your Environment

* Presto version used: latest
* Storage (HDFS/S3/GCS..):
* Data source and connector used:
* Deployment (Cloud or On-prem): on-prem
* [Pastebin](https://pastebin.com/) link to the complete debug logs: https://pastebin.com/Ziqh1Zvi

## Expected Behavior

The server should start

## Current Behavior

Errors: https://pastebin.com/Ziqh1Zvi

## Steps to Reproduce

1.
2.
3.
4.

**Comment by ZacBlanco** [comment]
Have you followed the exact steps outlined here? https://github.com/prestodb/presto/blob/master/README.md#user-content-building-presto

**Comment by pratyakshsharma** [comment]
@kkacstudent any updates here?
