### ISSUE TITLE
[docs] fix warnings in doc build for resource-groups.rst

### ISSUE THREAD

**Issue by steveburnett** [prestodb/presto#23102]
Two doc build errors are in text in [admin/resource-groups.rst](https://github.com/prestodb/presto/blob/master/presto-docs/src/main/sphinx/admin/resource-groups.rst) added in [PR 21057](https://github.com/prestodb/presto/pull/21057/). 

`/Users/steveburnett/Documents/GitHub/presto/presto-docs/src/main/sphinx/admin/resource-groups.rst:318: WARNING: undefined label: 'jdbc-java-connection'`

`/Users/steveburnett/Documents/GitHub/presto/presto-docs/src/main/sphinx/admin/resource-groups.rst:330: WARNING: undefined label: 'jdbc-parameter-reference'`

I can’t find where these two links should link to. 

## Expected Behavior
The two warnings are not generated in a doc build.

## Current Behavior
The following two errors appear in a local doc build. 

`/Users/steveburnett/Documents/GitHub/presto/presto-docs/src/main/sphinx/admin/resource-groups.rst:318: WARNING: undefined label: 'jdbc-java-connection'`

`/Users/steveburnett/Documents/GitHub/presto/presto-docs/src/main/sphinx/admin/resource-groups.rst:330: WARNING: undefined label: 'jdbc-parameter-reference'`

## Possible Solution
Revise the links in lines 318 and 330

_:ref:`the example  <jdbc-java-connection>`_
and 
_:ref:`the example <jdbc-parameter-reference>`_

to either link to the correct destination, or revise the text to remove the links entirely. 

## Steps to Reproduce

1. Follow the steps in [Building the Documentation](https://github.com/prestodb/presto/tree/master/presto-docs#building-the-documentation) to generate a doc build. 
2. Examine the output of the build process to find the two warnings. 

## Context
Builds on the doc build errors and warnings fix work in #23033, #23023, #22876, #22985.

**Comment by steveburnett** [comment]
@Akanksha-kedia can you work on this issue?

**Comment by imjalpreet** [comment]
@steveburnett I think the links are meant to point to the below sections:

`:ref:the example  <jdbc-java-connection>`: https://prestodb.github.io/docs/current/installation/jdbc.html#connection-parameters

`:ref:the example <jdbc-parameter-reference>`: https://prestodb.github.io/docs/current/installation/jdbc.html#parameter-reference

**Comment by Akanksha-kedia** [comment]
Sure i ll look into it and get back to you

**Comment by steveburnett** [comment]
This has been fixed in https://github.com/prestodb/presto/blob/master/presto-docs/src/main/sphinx/admin/resource-groups.rst. Closing this issue.
