### ISSUE TITLE
Iceberg table writer writes space to _x20 in column names in the Parquet file

### ISSUE THREAD

**Issue by yingsu00** [prestodb/presto#23129]
Using the IcebergQueryRunner, create table and insert would change the space in the column name to "_x20". For example, "two words" would be written as "two_x20words" in the Parquet file. This doesn't happen in Hive tables, where "two words" would just be written as "two words"

## Your Environment
N/A

## Expected Behavior
Iceberg table writer write space  as is. This is in alignment with Hive.

## Current Behavior
Iceberg table writer replaces space " " to "_x20". This is not desired.

## Steps to Reproduce
Start IcebergQueryRunner (Java). In presto cli, run the following

create table space2 ("two words" int) with (format='parquet');
insert into space2 values (1), (2), (3);

Then put a break point at com/facebook/presto/hive/parquet/ParquetPageSourceFactory.java line 207 
`MessageType fileSchema = fileMetaData.getSchema();` 

Repeat the same steps using HiveQueryRunner, and you will see the name is different.

## Screenshots (if appropriate)
![image](https://github.com/prestodb/presto/assets/33299678/35e20da5-bdc1-4abe-b7d2-0831d0d490df)

**Comment by karteekmurthys** [comment]
The Iceberg module sanitzes the column names if it has special characters. Check here:
org/apache/iceberg/parquet/TypeToMessageType.java

```

    for (NestedField field : schema.columns()) {
      builder.addField(field(field));
    }

    return builder.named(AvroSchemaUtil.makeCompatibleName(name));
  }
```
Further up the stack it reaches here in org/apache/iceberg/avro/AvroSchemaUtil.java:
```
private static String sanitize(char character) {
    if (Character.isDigit(character)) {
      return "_" + character;
    }
    return "_x" + Integer.toHexString(character).toUpperCase();
  }
```
It is coming from dependent java libraries.

**Comment by hantangwangd** [comment]
Seems Iceberg will sanitize all the characters that aren't allowed in Avro field names, including space " ". Referring to https://github.com/apache/iceberg/issues/216#issuecomment-502309454

**Comment by yingsu00** [comment]
So this is expected behavior. Closing for now. We will support reading such columns through name-id mapping in Velox. See https://github.com/facebookincubator/velox/issues/10085
