### ISSUE TITLE
[native] TestPrestoNativeIcebergTpcdsQueriesParquetUsingThrift.doDeletesAndQuery is failing

### ISSUE THREAD

**Issue by majetideepak** [prestodb/presto#23156]
[ERROR]   TestPrestoNativeIcebergTpcdsQueriesParquetUsingThrift.doDeletesAndQuery:399->verifyDeletes:390->AbstractTestQueryFramework.computeScalar:149->AbstractTestQueryFramework.computeActual:139 ? Runtime size <= capacity_ (18446744073709551499 vs. 1440) Split [Hive: file:/tmp/iceberg_data/HIVE/tpcds/store_sales/data/593eb530-2b2c-4b34-8bf9-caba66ad83d3.parquet 0 - 2071074] Task 20240709_152552_00114_sdniy.1.0.0.0 Operator: TableScan[0] 0
[INFO] 
[ERROR] Tests run: 132, Failures: 1, Errors: 0, Skipped: 0

The test started failing with this PR merge https://github.com/prestodb/presto/pull/23138

**Comment by zacw7** [comment]
looking

**Comment by zacw7** [comment]
The breaking change is https://github.com/facebookincubator/velox/pull/10261
@yingsu00 Could you please help fix this test?

**Comment by tanjialiang** [comment]
> I will fix this.

We are reverting https://github.com/facebookincubator/velox/pull/10261 @zacw7 identified, followed up by an advance PR.

**Comment by zacw7** [comment]
https://github.com/prestodb/presto/pull/23170 is merged and the test no longer fails. Closing the issue. Thanks!
