### ISSUE TITLE
Don't catch Throwable

### ISSUE THREAD

**Issue by elharo** [prestodb/presto#23166]
Catching Throwable is something you almost never want to do. See https://stackoverflow.com/questions/6083248/is-it-a-bad-practice-to-catch-throwable

We have many instances of this anti-pattern scattered throughout the code. Most of them can be improved by catching Exception instead. Some of them can catch more specific subclasses.

**Comment by Vaibhav-tech22** [comment]
@elharo I see this is still open. If this is open or not yet resolved, can you assign this to me

**Comment by elharo** [comment]
Just send PRs, I don't think it's one pR
