### ISSUE TITLE
NaN in coordinator UI on load

### ISSUE THREAD

**Issue by elharo** [prestodb/presto#23186]
When the coordinator UI first loads it shows "NaN" for a number of values until this is resolved with initial values a few seconds in.

My guess is that it starts with default values of zero for a number of variables, divides zero by zero, gets NaN, and loads that straight into the UI without checking. It should probably instead check for NaN and display an empty string or a no data message instead. Or maybe it should check for zero divisor before it even does the division.

<img width="1422" alt="Screenshot 2024-07-11 at 7 50 33 AM" src="https://github.com/prestodb/presto/assets/1005544/4c4f9bc9-e02d-4e98-b91c-1172723cf726">

**Comment by elharo** [comment]
suspect the issue is in the precisionRound function in utils.js which does not handle NaN

**Comment by hussein-mamane** [comment]
hello @elharo I am new to open source contributions but I am a solo programmer for years, I need some time to dig in the code about presto, this seems to be an easy if-else fix, can I have it and a week. Thank you.
