### ISSUE TITLE
The links for documents are invalid in presto homepage

### ISSUE THREAD

**Issue by hantangwangd** [prestodb/presto#23209]
The links for `Presto installation documentation` and `Presto documentation` are invalid in presto github homepage:

[Presto home page](https://github.com/prestodb/presto)

## Screenshots (if appropriate)

<img width="685" alt="404notfound" src="https://github.com/user-attachments/assets/fc3abec5-f71c-4009-803d-2756bc27172c">

**Comment by misterjpapa** [comment]
The incorrect domain is also referenced in the README.md file in the presto-product-tests project eg: the text **Hive connector documentation** references the url https://prestodb.github.io/docs/current/connector/hive.html). The same incorrect domain is mentioned in two other README.txt files eg: presto-spark-package and presto-server.

**Comment by hantangwangd** [comment]
@misterjpapa Yes, you are right, thanks for the information.

cc: @elharo @steveburnett

**Comment by steveburnett** [comment]
> The incorrect domain is also referenced in the README.md file in the presto-product-tests project eg: the text **Hive connector documentation** references the url https://prestodb.github.io/docs/current/connector/hive.html). The same incorrect domain is mentioned in two other README.txt files eg: presto-spark-package and presto-server.

Created #23227 to address these three additional corrections. Thanks!
