### ISSUE TITLE
Left align message

### ISSUE THREAD

**Issue by elharo** [prestodb/presto#23211]
This text should not be center aligned:

![image](https://github.com/user-attachments/assets/edf814d8-8ed1-4b33-ab9d-54f30a52938d)

**Comment by pranay911** [comment]
Hey @elharo Can you please assign this issue to me?

**Comment by pranay911** [comment]
Thanks!! @elharo can you please share me the steps of reproduction??

**Comment by Vaibhav-tech22** [comment]
Hi @elharo, Can you assign this to me? I would really like to work on this

**Comment by elharo** [comment]
First PR over the hill wins.
