### ISSUE TITLE
Implement hash function

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#2321]
Implement a generic `hash()` function that takes any number of arguments of any type and returns the hash of the values as a `BIGINT`. The type of the hash is system dependent and subject to change between releases. This function will be useful for things like bucketing or sampling where the result of the hash is not stored and is only used during the query.

This can be implemented using the `hash` method of `Block`, though we might want to augment that in the future with a 64-bit version.

**Comment by snarayananqubole** [comment]
We implemented such functionality recently. One of us from  Qubole will open a PR for it.

**Comment by shubham166** [comment]
Submitted PR - https://github.com/facebook/presto/pull/2397

**Comment by kokosing** [comment]
Closing, see: https://github.com/prestodb/presto/pull/2397#issuecomment-295008932
