### ISSUE TITLE
[docs] disable running unneeded tests for docs-only PRs

### ISSUE THREAD

**Issue by steveburnett** [prestodb/presto#23217]
#21716 (I think this is the correct PR to reference) was reverted because of unintended consequences - if a last commit in in a PR containing both code and doc changes contained doc files only,  incorrectly skipped circleci tests.

## Expected Behavior or Use Case
Doc-only PRs should skip circle-ci tests such as **ci/circleci: linux-presto-e2e-tests** and **ci/circleci: linux-build-and-unit-test**. 

## Presto Component, Service, or Connector
Documentation-only PRs and their automated testing. 

## Context
circle-ci tests such as **ci/circleci: linux-presto-e2e-tests** can take an hour to complete, and are irrelevant to a docs-only change.

**Comment by steveburnett** [comment]
@yhwang, could you take a look at this if you have time?

**Comment by yhwang** [comment]
Sure, I can work on this later this week. But if anyone wants to give it a try before this Wednesday, then please go ahead.
