### ISSUE TITLE
[Native] Clang format InsertNewlineAtEOF invalid argument error in CI job

### ISSUE THREAD

**Issue by karteekmurthys** [prestodb/presto#23221]
CI job:
https://app.circleci.com/pipelines/github/prestodb/presto/17874/workflows/49428eae-88f6-4ffd-b4c1-a9e0a1b9d523/jobs/70682

Error:
```
Ok   : CMakeLists.txt
Skip : Makefile
Ok   : presto_cpp/main/CMakeLists.txt
/root/project/presto-native-execution/.clang-format:75:1: error: unknown key 'InsertNewlineAtEOF'
InsertNewlineAtEOF: true
^~~~~~~~~~~~~~~~~~
Error reading /root/project/presto-native-execution/.clang-format: Invalid argument
error: `clang-format -style=file -lines=20:20 -lines=33:39 presto-native-execution/presto_cpp/main/PrestoMain.cpp` failed
Error: presto_cpp/main/PrestoMain.cpp
make: *** [Makefile:109: format-check] Error 1
```

If we add a new line in the PrestoMain.cpp file, on `make format-fix`, the new line is erased.

## Your Environment

* Presto version used:
* Storage (HDFS/S3/GCS..):
* Data source and connector used:
* Deployment (Cloud or On-prem):
* [Pastebin](https://pastebin.com/) link to the complete debug logs:

## Steps to Reproduce

1.
2.
3.
4.

**Comment by majetideepak** [comment]
Likely due to an older version of clang-format. I will fix the CI image.
```
clang-format --version
Ubuntu clang-format version 12.0.0-1ubuntu1
```
