### ISSUE TITLE
Presto Console web page returns 404

### ISSUE THREAD

**Issue by xhs** [prestodb/presto#23327]
config.properties
```
coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8080
query.max-memory=12GB
query.max-memory-per-node=8GB
discovery-server.enabled=true
discovery.uri=http://10.11.xx.xx:8080
```

jvm.config
```-server
-Xmx25G
-XX:+UseG1GC
-XX:G1HeapRegionSize=32M
-XX:+UseGCOverheadLimit
-XX:+ExplicitGCInvokesConcurrent
-XX:+HeapDumpOnOutOfMemoryError
-XX:+ExitOnOutOfMemoryError
-Djdk.attach.allowAttachSelf=true
```

log.properties
```
com.facebook.presto=INFO
```

node.properties
```
node.environment=production
node.id=ffffffff-ffff-ffff-ffff-ffffffffffff
node.data-dir=/var/presto/data
```

After starting Presto
```
$ ./bin/launcher status
Running as 1280329
```

Accessing Presto Console
```
$ curl -i http://localhost:8080/
HTTP/1.1 301 Moved Permanently
Date: Tue, 30 Jul 2024 09:09:46 GMT
Location: http://localhost:8080/ui/
Content-Length: 0

$ curl -i http://localhost:8080/ui/
HTTP/1.1 404 Not Found
Date: Tue, 30 Jul 2024 09:08:22 GMT
Cache-Control: must-revalidate,no-cache,no-store
Content-Type: text/html;charset=iso-8859-1
Content-Length: 235

<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /ui/. Reason:
<pre>    Not Found</pre></p>
</body>
</html>

$ curl -i http://10.11.xx.xx:8080/ui/                                                                                                                     
HTTP/1.1 404 Not Found                                                                                                                                                       
Date: Tue, 30 Jul 2024 15:28:28 GMT
Cache-Control: must-revalidate,no-cache,no-store
Content-Type: text/html;charset=iso-8859-1
Content-Length: 235

<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /ui/. Reason:
<pre>    Not Found</pre></p>
</body>
</html>
```

## Your Environment

* Presto version used: 0.288
* Storage (HDFS/S3/GCS..): N/A
* Data source and connector used: N/A
* Deployment (Cloud or On-prem): Cloud

## Expected Behavior

Open Presto Console web page

## Current Behavior

Presto Console web page returns 404

## Steps to Reproduce
As described above.

**Comment by yhwang** [comment]
Can you update the `discovery.uri=http://10.11.xx.xx:8080` to `discovery.uri=http://localhost:8080` in the config.properties and restart the server?

**Comment by xhs** [comment]
That would be impossible since it is a remote server but I get your point.

Accessing the discovery.uri gives the same result:
```
$ curl -i http://10.11.xx.xx:8080/ui/                                                                                                                     
HTTP/1.1 404 Not Found                                                                                                                                                       
Date: Tue, 30 Jul 2024 15:28:28 GMT
Cache-Control: must-revalidate,no-cache,no-store
Content-Type: text/html;charset=iso-8859-1
Content-Length: 235

<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /ui/. Reason:
<pre>    Not Found</pre></p>
</body>
</html>
```

**Comment by yhwang** [comment]
Actually, that configuration file is for the coordinator since you have `coordinator=true` there, so the URL is for the coordinator only. You can use localhost for it. However, for other workers, you need to specify the coordinator's IP address in the discovery.uri properly.

**Comment by yhwang** [comment]
I believe I found the root cause. we are missing the presto-ui-0.288.jar. syncing with release to figure out the solution

@wanglinsong in the presto-0.288 release tarball: https://repo1.maven.org/maven2/com/facebook/presto/presto-server/0.288/presto-server-0.288.tar.gz, presto-ui-0.288.jar is missing. can you help on this?

**Comment by yhwang** [comment]
@ZacBlanco any idea why the presto-ui-0.288.jar is missing from the release tarball

**Comment by ZacBlanco** [comment]
I just checked with @wanglinsong . We unfortunately had a flag passed to the release artifacts command which skipped the UI:

https://github.com/prestodb/presto-release-tools/blob/1e4e2fd472c3e5a038a0d33cd93fdabc9f82b60d/Jenkinsfile#L123

I think we will probably need to release a 0.288.1 to fix it?

**Comment by tdcmeehan** [comment]
@wanglinsong can we please cut a hotfix to include the UI?

**Comment by ZacBlanco** [comment]
Just to add some info to this thread, the official 0.288 image on dockerhub does seem to have the UI, but the official tarball does not. I ran the following command from my macos and the UI worked fine:

```sh
podman run -p 8080:8080 prestodb/presto:0.288
```

So, container-based deployments should be fine if using the official image. If using the official binary to build your own image for Presto the UI won't work for 0.288 until we get a patch out

**Comment by wanglinsong** [comment]
Releasing 0.288.1 to fix this.
