### ISSUE TITLE
Cassandra connector not using date range

### ISSUE THREAD

**Issue by csarcom** [prestodb/presto#2341]
My example query: 

SELECT floor(to_unixtime(time) / 360) \* 360 as interval, sum(sum)/1000/1000 FROM metrics_rollup60 WHERE name= 'bytes_sent.2747t.hd' and to_unixtime(time) >= to_unixtime(TIMESTAMP '2014-11-25 00:00') and to_unixtime(time) < to_unixtime(TIMESTAMP '2014-11-25 05:00') GROUP BY floor(to_unixtime(time) / 360) ORDER BY interval; 

I saw on server.log this query on cassandra: 

SELECT time,sum FROM store.metrics_rollup60 WHERE name in ('bytes_sent.2747t.hd') 

https://groups.google.com/forum/#!topic/presto-users/o6VhX6W8n5Y

**Comment by toyama0919** [comment]
Hello.

The Similar case occurred me too.

My case is presto => postgresql(redshift).

## table definition
```
   Column    |          Type          |                      Modifiers
-------------+------------------------+-----------------------------------------------------
 id          | bigint                 | not null default "identity"(326478, 0, '1,1'::text)
 customer_id | integer                |
 log_time    | bigint                 |
 log_date    | date                   |
 ip_address  | character varying(30)  |
 session_id  | character varying(256) |
 uuid        | character varying(100) |
 url         | character varying(256) |
```

* log_time is unixtime.

## pattern1(NG, full scan)
query on presto
```
select log_date,count(*) from store.public.access where log_time >= to_unixtime(timestamp '2015-01-04') group by log_date;
```

then running query in redshift.
``` 
SELECT "log_time", "log_date" FROM "public"."access"
``` 

## pattern2(OK, range scan)
query on presto
```
select log_date,count(*) from store.public.access where log_time >= 1420297200 group by log_date;
```


then running query in redshift.
```
SELECT "log_time", "log_date" FROM "public"."access" WHERE (("log_time" >= 1420297200))
``` 

## pattern3(NG, full scan)
query on presto
```
select log_date,count(*) from store.public.access where log_time >= (timestamp '2015-01-04') group by log_date;
```


then running query in redshift.
```
SELECT "log_time", "log_date" FROM "public"."access"
```
