### ISSUE TITLE
Windows Support: Checkstyle

### ISSUE THREAD

**Issue by kadaan** [prestodb/presto#2342]
Presto fails to build on Windows due to checkstyle enforcing that lines end in \n.  This is not the line separator in windows.  Can the checkstyle checks be changed to allow any of: \r\n, \n, \r?  Alternately, can a .gitattributes file be added which specifies that LF is the correct newline character by: text eol=lf

**Comment by ArturGajowy** [comment]
I think the latter (.gitattributes) would be a better solution. @electrum WDYT?

**Comment by findepi** [comment]
@kadaan, the repository doesn't contain source files with \r\n. If your git client creates such line endings upon checkout, it's a matter of your git client's configuration. Did you set `core.autocrlf`?

**Comment by blackhawkbigpunch** [comment]
Setting core.autocrlf to false bypassed the fail with maven-checkstyle-plugin issue in windows.

**Comment by findepi** [comment]
@blackhawkbigpunch thanks for sharing this
