### ISSUE TITLE
Incorrect and inconsistent behavior of Like with constant folding

### ISSUE THREAD

**Issue by kagamiori** [prestodb/presto#23450]
I see inconsistent behaviors between the two queries below.

Query1: select if(c2 like '' escape '', c0, c1)  from (values (true, false, 'T')) t(c0, c1, c2);
This query throws an exception "Escape string must be a single character".

Query2: select if('T' like '' escape '', c0, c1) from (values (true, false)) t(c0, c1);
This query returns `false` with no error.

Since Query1 and Query2 are semantically equivalent, I expect them to have the same behavior.

The different behavior is because Query1 takes this branch where the `isLikePattern()` method throws the exception.
https://github.com/prestodb/presto/blob/4f74f52f36709944ba9eea18b0559ec7dd691d36/presto-main/src/main/java/com/facebook/presto/sql/planner/RowExpressionInterpreter.java#L936-L937

On the other hand, Query2 takes this branch that doesn't call isLikePattern.
https://github.com/prestodb/presto/blob/4f74f52f36709944ba9eea18b0559ec7dd691d36/presto-main/src/main/java/com/facebook/presto/sql/planner/RowExpressionInterpreter.java#L912

I think Query1 has the correct behavior while Query2 needs to be fixed.

## Your Environment

* Presto version used: Presto-0.289
* Storage (HDFS/S3/GCS..):
* Data source and connector used:
* Deployment (Cloud or On-prem):
* [Pastebin](https://pastebin.com/) link to the complete debug logs:

**Comment by kagamiori** [comment]
cc @kaikalur @rschlussel @tdcmeehan

**Comment by tdcmeehan** [comment]
I think all we need to do is add this validation:

https://github.com/prestodb/presto/blob/04138bc26a4fc801630fe936463d89d071d00c0a/presto-main/src/main/java/com/facebook/presto/type/LikeFunctions.java#L124

To right after this line as well:

https://github.com/prestodb/presto/blob/04138bc26a4fc801630fe936463d89d071d00c0a/presto-main/src/main/java/com/facebook/presto/type/LikeFunctions.java#L151
