### ISSUE TITLE
Round bytes to Gigabytes in error messages

### ISSUE THREAD

**Issue by elharo** [prestodb/presto#23564]
Saw this lately:

com.facebook.presto.spi.PrestoException: TaskUpdate size of 860492511 Bytes has exceeded the limit of 524288000 Bytes

No major problem. The error is accurate and expected given what I was doing. It's just hard to read. It would be easier to read if such large numbers were rounded to gigabytes and/or megabytes before being shown to users. E.g.

com.facebook.presto.spi.PrestoException: TaskUpdate size of 8 GB has exceeded the limit of 5 GB.

start looking in presto-main/src/main/java/com/facebook/presto/server/remotetask/HttpRemoteTask.java around line 885 for the relevant code

**Comment by misterjpapa** [comment]
https://github.com/prestodb/presto/pull/23606 was merged, we can close this issue now.

**Comment by elharo** [comment]
Thanks. FYI you can add
```fixes #23564```
to the PR description and then Github links the PR to the issue and autocloses the issue when the PR merges
