### ISSUE TITLE
Presto 0.289 cannot be downloaded from Maven central

### ISSUE THREAD

**Issue by tdcmeehan** [prestodb/presto#23648]
While successfully uploaded, the Presto sever distribution is too large and cannot be downloaded.  https://repo1.maven.org/maven2/com/facebook/presto/presto-server/0.289/presto-server-0.289.tar.gz returns a 503 error.

It seems we have tripped over an imaginary limit.  According to Sonatype, [the limit is 1GB](https://central.sonatype.org/publish/publish-portal-upload/), however our packages have regularly exceeded 1GB for years.  0.289 is around 2GB, so it seems 2GB is the real hard limit.

We should aim to reduce the Presto distribution size to 1GB or less.

There are multiple potential solutions to this problem:

1) The Presto distribution has a lot of redundancy between plugins.  Each plugin's dependencies are repeated, resulting in hundreds of megabytes of duplication.  If the generated TAR used hard links, then we could cut the distribution size to well under half, and give us many more years of breathing room.

We cannot do this right now because we use the Maven assembly plugin, which simply does not support the creation of hard links.  We used to use the Maven Provision plugin, which does support this, but we migrated off of it in #12698.  We could investigate moving back onto the Provisio plugin to solve this problem.

2) We can start to offload dependencies from the core distribution of Presto and let individual users of dependencies package it manually.  While this might be inconvenient for users, most dependencies are updated slowly, and can be lazily upgraded.  #23647 removes some not commonly used plugins from our distribution.

In either case, after fixing this issue, we should add a Presto-side check that ensures the artifacts don't grow past the stated limit in Sonatype, 1GB, and the solution should bring us to well below 1GB.

**Comment by pratyakshsharma** [comment]
> which simply does not support the creation of hard links

Curious, what is meant by hard links?

**Comment by tdcmeehan** [comment]
@pratyakshsharma  see here: https://stackoverflow.com/a/185903
