### ISSUE TITLE
UDF proposal - COMPRESS

### ISSUE THREAD

**Issue by miaekim** [prestodb/presto#23695]
COMPRESS function already exists in MySQL. https://dev.mysql.com/doc/refman/8.4/en/encryption-functions.html#function_compress 
can we use this function in Presto?

**Comment by tdcmeehan** [comment]
If the goal is storage savings, and if Presto is being used over distributed storage with Parquet or ORC, then it's likely the data files are already compressed.

If it's still needed for some reason, a compress function can be implemented yourself using the [functions SPI](https://prestodb.io/docs/current/develop/functions.html).
