### ISSUE TITLE
Parquet does not support timestamp. See HIVE-6384

### ISSUE THREAD

**Issue by mfirry** [prestodb/presto#2371]
I'm trying to use presto with Cloudera CDH 5.3.1 (which uses hive-0.13.1+cdh5.3.1+308) with Parquet
I get this `Parquet does not support timestamp. See HIVE-6384` but it appears that the timestamp issue was solved on HIVE-6394.

**Comment by mfirry** [comment]
news on this?

**Comment by yuananf** [comment]
fixed by #3493
