### ISSUE TITLE
Bloom filter join / where comparator support

### ISSUE THREAD

**Issue by FlxRobin** [prestodb/presto#2372]
Joins at large, distributed, data sets are fairly common these days. Big improvements have been made in executing them better in a distributed fashion. I however think this is still too limited and not fast enough.

For analytics purposes an "estimate" within a given/known error bound is often very acceptable (for example approx_distinct in Presto) and can improve performance a lot.

This should be an option for join-queries as well. We can achieve this by using [BloomFilters](http://en.wikipedia.org/wiki/Bloom_filter), reducing complexity of join queries and thus improving speed.

It would work something like this:
1. One side of the JOIN is selected regularly
2. The temporary results are streamed into a configurable bloomfilter
3. The bloom filter is then used to serve as a comparator between the <element> and <list_of_elements>

Syntax could look like the ones below, just a few initial ideas:

``` sql
# Syntax option 1: "JOIN"-style syntax with PROBABILISTIC keyword, error bound is 1%
WITH input_pool AS (
  SELECT distinct user_id FROM users WHERE  1=1 /** Logic here */
)
SELECT count_if(event_type='login') AS logins /** More statistics */ FROM user_stats PROBABILISTIC (0.01) JOIN input_pool ON (user_stats.user_id=input_pool.user_id);
```

``` sql
# Syntax option 2: "IN"-style
SELECT count_if(event_type='login') AS logins /** More statistics */ FROM user_stats WHERE user_stats.user_id PROBABILISTIC (0.01) IN (SELECT distinct user_id FROM users WHERE  1=1 /** Logic here */)
```

I would love to hear your thoughts on this. Thanks!

I actually just noticed I used the wrong account to post this issue, under RobinUS2 I do apply to the contributing license, apologies for that.

**Comment by cberner** [comment]
There's some experimental support for this already. I added it way back in version 0.61, but it should still work. Let me know how it works for you, if you try it out!

https://prestodb.io/docs/current/release/release-0.61.html

**Comment by FlxRobin** [comment]
Thank you @cberner for your reply! It looks like this only works when I materialize a table with that sampling method? In that case this might be difficult as we would need to recreate those tables at a fairly high frequency, with a lot of data movement. 

Do I understand that correctly, or did I miss something?

**Comment by cberner** [comment]
You should be able to use it inline, without materializing the table. Something like:

```
select count(*) 
from my_table tablesample poissonized (1) rescaled 
approximate at 95.0 confidence;
```

However, it looks like there's a bug, because I get a null pointer exception in the `LocalExecutionPlanner`. A patch would be welcome, if you track it down!

**Comment by RobinUS2** [comment]
I wanted to give you an update, I have build a plugin which implements the BloomFilters above:
https://github.com/RobinUS2/presto-bloomfilter

Would be great to hear your thoughts!
