### ISSUE TITLE
Round function returns incorrect results for large floats

### ISSUE THREAD

**Issue by HeidiHan0000** [prestodb/presto#23763]
## Steps to Reproduce

```
SELECT
    c0 AS value,
    "round"(c0, 1) AS rounded
FROM (
    VALUES
        (CAST(1E19 AS REAL))
) t(c0);
```

## Expected Behavior

```
 value  |    rounded    
--------+---------------
 1.0E19 | 1.0E19
(1 row)
```
## Current Behavior

```
 value  |    rounded    
--------+---------------
 1.0E19 | -8.4467441E18 
(1 row)
```
Issue only occurs when casting to real and using scientific notation.

**Comment by hantangwangd** [comment]
It seems that this is a bug caused by the implementation of `MathFunctions.roundFloat(...)`, which does not properly handle situations when input data exceeding long value. Have submit a PR the fix this issue. See #23765
