### ISSUE TITLE
Migrate Presto C++ CI jobs off of CircleCI

### ISSUE THREAD

**Issue by tdcmeehan** [prestodb/presto#24023]
The jobs [found here](https://github.com/prestodb/presto/tree/master/.circleci) all need to be migrated to Github Actions, as our CircleCI account will be suspended at the end of this year.

## Expected Behavior or Use Case
We remove all critical CircleCI jobs

## Presto Component, Service, or Connector
CI

## Possible Implementation
See previous attempts:

* https://github.com/prestodb/presto/pull/23938
* https://github.com/prestodb/presto/pull/21545

We are obtaining funding for larger runners to accomadate the CI needs of these jobs.  We expect to have sufficient funding by end of year.

## Context
Our CircleCI account will be defunct by EOY and we need to migrate to a different CI runner.

**Comment by tdcmeehan** [comment]
The bare minimum should be:

1) C++ code compiled and we see this signal in CI.
2) Unit tests are run and we see this signal in CI.

**Comment by czentgr** [comment]
I'm refactoring the jobs from the PR that did the conversion about a year ago. Some changes are needed.

The build only run on the standard runner takes about 1h and 20mins: https://github.com/czentgr/presto/actions/runs/12263436897

I'm working on the other build and tests.

**Comment by czentgr** [comment]
MacOS job took longer because it builds the dependencies from scratch. It took 2h 20mins.
https://github.com/czentgr/presto/actions/runs/12265660174/job/34222218315

**Comment by czentgr** [comment]
After upgrading to Xcode 15 to be able to use Clang 15 (the minimum eventually) the build time was reduced by 1/3.
https://github.com/czentgr/presto/actions/runs/12269784844/job/34233919551

Now only 1:40h which is somewhat similar to the Linux build.
