### ISSUE TITLE
Parquet reader doesn't support projection pushdown past the first level

### ISSUE THREAD

**Issue by colinmarc** [prestodb/presto#2508]
Nested structs are included wholesale, but it would be more efficient to only read the fields needed for the query.

**Comment by dvryaboy** [comment]
Hi @zhenxiao and @colinmarc , I have a few days to spend on this -- can you confirm that this issue is still valid? I know @zhenxiao put a bunch of changes into the parquet reader recently.

**Comment by zhenxiao** [comment]
@dvryaboy I think the issue is valid. When reading complex types in parquet Map/Array/Struct, say a ROW type(the corresponding struct type in Hive):
p3:struct<m1:int, m2:double>
Now reading p3.m1 will scanning both m1 and m2, ideal case would be scanning m1 only.
My recent code changes are for primitive types. Primitive types in Parquet does not having this problem.
Also, let's always keep @dain in the loop for any file formats issues, eg. Parquet, ORC.

**Comment by dvryaboy** [comment]
Thanks, @zhenxiao . @dain , after spending some time today looking at the codebase, I'm getting the impression that this is not a parquet-specific issue; HiveColumnHandle does not have a notion of nesting, and identifies the datum needed via a column index, which doesn't let one address a sub-struct. So if we change the planner to push projection down, it does not currently have a way, that I see, to tell RecordCursors which substructs to return -- the only get a list of top-level columns to return.

I can see a couple of ways of telling the cursor what to project:
  1. add a new Projector concept that is passed to the Cursor during initialization, similar to how predicates are passed down using TupleDomains. 
  1. modify HiveColumnHandle to have something more complex than an int to indicate what needs to be returned. This seems a little cleaner, but involves far more surgery. 
  1. stick this info into something else, like TupleDomain. That might be easiest to implement but seems gross.

Then there's the question of what exactly the cursor would return, given a projection. Again, a few options.
  1. Return the top-level type, but only fill in the required fields; set the rest to null. This has the nice benefit of leaving all the subsequent code untouched (so, easier to implement) but wastes a bunch of computation and memory overhead in allocating objects, derefencing things, having operators in the plan whose sole job is doing what we already did inside the cursor, etc. Still, saving the IO.
  1. Return just the requested substructs, which is certainly going to result in faster queries, but probably involves some hairy code -- if the storage layer supports projections, you expect one type to come back, if not, another, and your whole plan is different depending on the storage capabilities. I haven't looked at how amenable the Presto planner is to that sort of thing. Seems like it would involve quite a lot of repiping.

I've only looked at the code today, so it's totally possible (likely, even) that I'm missing easier approaches. Please let me know what you think -- especially if i'm wrong and there is in fact already a vehicle for communicating nested projections.

**Comment by ebuildy** [comment]
Since this issue is still opened, do you advice to not use nested schema with PrestoDB ? (I know Apache Drill cannot read Hive struct already).

**Comment by zhenxiao** [comment]
we have a Pull Request to resolve this problem, which could significantly improve Parquet struct performance:
https://github.com/prestodb/presto/pull/5547

@ebuildy you could apply the patch, and try it.

**Comment by ebuildy** [comment]
Thanks you @zhenxiao , I will.

**Comment by drknexus** [comment]
@ebuildy @zhenxiao Do you have any updates on this issue?

**Comment by zhenxiao** [comment]
I have 2 patches with 2 slightly different methods, each could resolve the problem independently:
https://github.com/prestodb/presto/pull/6675
https://github.com/prestodb/presto/pull/5547

We are using it in production. You are welcome to try them.
I am discussing with @martint , and rebasing the code with a cleaner design. Hope to commit it soon.

**Comment by Yaliang** [comment]
Hey, @zhenxiao. Is there any update on this issue?

**Comment by zhenxiao** [comment]
The 2 PRs are still pending for review. Uber has been running these in production for ~ 1 year. It is stable. You are welcome to apply these patches to your Presto

**Comment by dotcomputercraft** [comment]
@zhenxiao - Are these PRs going to be merge in the future?  Are these PRs are ready for 0.185 of presto?

**Comment by jiangzhx** [comment]
@zhenxiao  
i readed all your paper, it's great .
any progress from your last update ?
can i get your email for more detail discuss.
https://eng.uber.com/presto/
https://www.slideshare.net/zhenxiao/presto-uber-hadoop-summit2017

**Comment by zhenxiao** [comment]
Hi, @jiangzhx 
with @kgalieva 's fix 👍 https://github.com/prestodb/presto/pull/9156
Now the new parquet reader is rock solid
take a try for the latest code

**Comment by mixermt** [comment]
Hi @jiangzhx , @kgalieva 
Is this fix was merged to master ? 
I feel pretty lost in this maze of issues related to same topic.
I'm using 0.208 for my test and I see that presto still reads all nested fields and not only the fields needed for the query.
More details of my heavy test: #11326

**Comment by zhenxiao** [comment]
The issue is resolved with the following commits:
https://github.com/prestodb/presto/commit/d45962c68b0e7f788b544fc3fefc4ca4d135f36f
https://github.com/prestodb/presto/commit/bd0c3e217f464985cb36641ffae769a5565e532b
https://github.com/prestodb/presto/commit/871dbf3f7cb917ace5a4b5aed6499ab368ada1f2
https://github.com/prestodb/presto/commit/009eb3f0ab34dfb5ee853da2acf702c0a84f9741
https://github.com/prestodb/presto/commit/a444c048cbc66df50f06986206651d0316fdf354
https://github.com/prestodb/presto/commit/04ed142e96e23a087dd541713ab40150ed278694
https://github.com/prestodb/presto/commit/7d4a89246fce33b759cf5c3d88fadc796a8d49ca
https://github.com/prestodb/presto/commit/99c0d2a123f31586afd7f349633e98dcc123b2b4
