### ISSUE TITLE
Aggregate window functions are very slow.

### ISSUE THREAD

**Issue by stagraqubole** [prestodb/presto#2517]
Here are two queries for comparison:
Q1: With window functions:

``` sql
    select ss_store_sk, ss_quantity - min(ss_quantity) over (partition by ss_store_sk) from store_sales_10_orc; 
```

Q2: Without window functions:

``` sql
    select store_sales_10_orc.ss_store_sk, store_sales_10_orc.ss_quantity -  min_store_quantity.quantity
    from store_sales_10_orc 
    join
        (select ss_store_sk, min(ss_quantity) quantity from store_sales_10_orc group by ss_store_sk)
        min_store_quantity
    on
    store_sales_10_orc.ss_store_sk = min_store_quantity.ss_store_sk
```

Q1 takes around 500sec while Q1 finishes in around 100sec in same setup.

On profiling, AggregateWindowFunction.accumulate method lights up. A lot of time is spent in creating new pageBuilder for every frame.

This is against 0.90 but it should exist in master too as the code is same for  AggregateWindowFunction.accumulate

**Comment by electrum** [comment]
What is the average number of rows per partition? The current implementation is not optimized for small groups (as you have found). Is the performance better for higher cardinality partitions?

**Comment by stagraqubole** [comment]
~500k rows per group and ~50groups. For most the window queries I had tried, group by counter parts were faster.
Tried same exercise for scale 50 which had ~2m rows per group and had similar difference in performance.

**Comment by maciejgrzybek** [comment]
Tested on the most recent master (HEAD = 8c6cf92c5d2ebf2507f82311857a98a8bf0e6883), right after 170 release. Data set - `tpcds.sf10`.
Results:
```sql
with x as (select ss_store_sk, ss_quantity - min(ss_quantity) over (partition by ss_store_sk) from store_sales) select count(*) from x where ss_store_sk > -999999999999999;
```
takes ~15s on my laptop, while
```sql
with x as (select store_sales.ss_store_sk, store_sales.ss_quantity - min_store_quantity.quantity from store_sales join (select ss_store_sk, min(ss_quantity) quantity from store_sales group by ss_store_sk) min_store_quantity on store_sales.ss_store_sk = min_store_quantity.ss_store_sk) select count(*) from x where ss_store_sk > -999999999999999;
```
takes ~35s.

I'm closing this because it seems not relevant anymore.
