### ISSUE TITLE
Implement split_to_map

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#2544]
Implement a function similar to Hive's str_to_map that splits a string on delimiter1 and delimiter2 and returns a map

**Comment by cberner** [comment]
@electrum, @dain, and @martint thoughts on the name?

**Comment by monkey-mas** [comment]
Hi @cberner , I'd be interested in working on it! Which class do you think the function could be added to?

**Comment by Downchuck** [comment]
Checking if anyone has a similar interest: I could really have used an option to overwrite or append with another delimiter, on duplicate keys. Currently it simply throws an error. Hive's str_to_map overwrites by default, and I needed to create a custom function do do an append with delimiter.
