### ISSUE TITLE
VerifyError for long queries

### ISSUE THREAD

**Issue by jackowayed** [prestodb/presto#2568]
We're seeing a VerifyError for long queries on Presto 0.97.

I chatted with dain about this in IRC ~a week ago when we were on 0.77 and he thought upgrading might help, but it has not. This is the exact same error we were seeing on 0.77. (Though now the error directly comes through to the CLI and web console, instead of us having to go to the worker logs for it!)

Here's the full output after running the query from the CLI: https://www.dropbox.com/s/xekws31ztj0s7ym/presto_verify_error.txt?dl=0

Our query is quite long. It's:

SELECT  case  when ((created_at) \* 1000.0 >= 1238457600000 and (created_at) \* 1000.0 < 1238544000000) then '1238457600000,1238544000000,false,true'
<... 99 more cases>
end  as bucket0, count(1) as metric_0
 FROM table  where ((((((created_at) \* 1000.0 >= 1238457600000) and ((created_at) \* 1000.0 < 1247097600000)))) and (true)) group by 1 limit 1000

We haven't set `compiler.interpreter-enabled`, so it should be on the default of true.

Would love to know how we might fix or mitigate this.

**Comment by dain** [comment]
Can you reproduce it with a small query or does this only happen when you have more than 100 cases?

One thing to note is the expression is compiled into a single method and a java method can only have 64K byte codes, so you just might have too much stuff.

**Comment by jackowayed** [comment]
For now we're only seeing it for pretty big long queries, so that's likely the issue.

Presumably the interpreter doesn't have that limitation? How much slower is it, and would there be some way to get the interpreter to kick in sooner and avoid these queries from just breaking? Thanks for the quick reply.
