### ISSUE TITLE
Wrong value returned by getTableTypes()

### ISSUE THREAD

**Issue by damiencarol** [prestodb/presto#2687]
Currently **PrestoDatabaseMetaData.getTableTypes()** use:

``` sql
SELECT DISTINCT table_type AS TABLE_TYPE
FROM information_schema.tables
ORDER BY TABLE_TYPE
```

Which returns:

```
 TABLE_TYPE
------------
 BASE TABLE
(1 row)
```

This break consistency with major RDBMS (MySQL, SQL Server, other I think). Plus Java doc talk about **TABLE** value and not **BASE TABLE** value.

There are no simple fix as JDBC client should use this values to filter tables in method **getTables**.
The current behavior breaks aggregate detection in Pentaho BI tool.

Ref:
https://github.com/facebook/presto/blob/master/presto-jdbc/src/main/java/com/facebook/presto/jdbc/PrestoDatabaseMetaData.java#L1001

**Comment by rschlussel** [comment]
@electrum was this fixed by 615d8bdfc40bab81d521850055ebf873ab4a77d2
