### ISSUE TITLE
API to list queries

### ISSUE THREAD

**Issue by atalmadge** [prestodb/presto#2694]
It would be really helpful to have an API to list the queries and get back some basic information such as source, user, query id, sql, basic stats, cancelation url, etc.

This information could then be surfaced in UIs + CLIs to make it easier for users to manage their queries.

Thanks!

**Comment by yuananf** [comment]
select * from system.runtime.queries

**Comment by electrum** [comment]
As @yuananf says, this is provided by the System connector: https://prestodb.io/docs/current/connector/system.html

If you need additional information not present here, please let us know.

**Comment by martint** [comment]
That's not sufficient. We need to be able to expose the cancellation URL and other pieces of information not available via that table in a stable and supported way.

**Comment by andytinycat** [comment]
Surely what you're looking for is the REST API the current UI uses?

https://raw.githubusercontent.com/facebook/presto/master/presto-docs/src/main/sphinx/rest/query.rst

(Not sure why this section of the docs doesn't appear on the main website - but it's part of this repository)

**Comment by electrum** [comment]
We should add a SQL command to kill a query by ID.

**Comment by yuananf** [comment]
@electrum actually I implemented this function, but it was a bit hack, may I make a pull request?
