### ISSUE TITLE
Add single-page release notes / changelog

### ISSUE THREAD

**Issue by mstorus** [prestodb/presto#2830]
It is very difficult to search through https://prestodb.io/docs/current/release.html since each release has its own page.

![10 release notes presto 0 101 documentation-1](https://cloud.githubusercontent.com/assets/1182738/7423834/bed3199e-ef4e-11e4-88bf-5f4b67685060.jpg)

https://github.com/facebook/presto/tree/50081273a9e8c4d7b9d851425211c71bfaf8a34e/presto-docs/src/main/sphinx/release

For example, trying to find which version a feature was added in is very difficult.

Please add a single page changelog / release notes.

**Comment by cberner** [comment]
We usually just use site search on Google for that. For example, `orc site:prestodb.io/docs/current/release` does that work for you? Please re-open if not

**Comment by mstorus** [comment]
It seems non-ideal to rely on a 3rd party search indexer to grep through the changelog

**Comment by electrum** [comment]
@mstorus thanks for the feedback. We will come up with something. Maybe we should start putting multiple releases per chapter, since the list of releases is growing ever longer.

**Comment by damiencarol** [comment]
Could sphinx add a search engine interface ?

**Comment by mstorus** [comment]
Is there a simple way to just concatenate all the `release-x.xx.rst` files together?
