### ISSUE TITLE
Improvements to client protocol

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#2860]
- [ ] Presto needs to know when clients have finished fetching results for a query
- [ ] Need a way to send binary values to client
- [ ] Fix serialization of structural types in map keys. For example, `map<array<bigint>, varchar>`

**Comment by sopel39** [comment]
Is this issue still valid? Those point seem very specific. Are they related to some other issues/requirements? Could you elaborate a bit?

**Comment by cberner** [comment]
Yep, it's still valid. The first point is so that the server can clean up old queries that the client has finished reading, the second and third are cleanups/fixes for the way values are transported
