### ISSUE TITLE
date_format using %w (day of week) returns incorrect values (1-7, not 0-6)

### ISSUE THREAD

**Issue by andytinycat** [prestodb/presto#2875]
When using `date_format`, with the %w specifier (for day of week), we get incorrect values:

```
presto:default> select date_format(date_parse('2015-05-03 11:00', '%Y-%m-%d %H:%i'), '%w');
 _col0
-------
 7
(1 row)
```

According to the documentation:

```
%w	Day of the week (0 .. 6), where Sunday is the first day of the week
```

2015-05-03 was a Sunday, so we should expect this to return 0, not 7. Also, 7 is out of range of the values expected according to the documentation.

Testing with a date known to be a Monday:

```
presto:default> select date_format(date_parse('2015-05-04 11:00', '%Y-%m-%d %H:%i'), '%w');
 _col0
-------
 1
(1 row)
```

Is this a documentation bug, or an actual bug?

(Presto version is 0.101)

**Comment by andytinycat** [comment]
Looking at the test suite:

```
String dateTimeLiteral = "TIMESTAMP '2001-01-09 13:04:05.321'";
assertFunction("date_format(" + dateTimeLiteral + ", '%W')", VARCHAR, "Tuesday");
assertFunction("date_format(" + dateTimeLiteral + ", '%w')", VARCHAR, "2");
```

This is a documentation bug. Would you like a PR?

**Comment by haozhun** [comment]
Looks like a real bug because we follow mysql's definition of format strings in `date_format`. @dain, do you have any insight on this?

**Comment by cberner** [comment]
We should make this work exactly like MySQL

**Comment by yuananf** [comment]
It seems joda is using Monday as the first day of week.

Should day_of_week function also change the behavior? 
MySQL's result is 1 for'2015-05-03'
```
mysql> select DAYOFWEEK(timestamp '2015-05-03');
+-----------------------------------+
| DAYOFWEEK(timestamp '2015-05-03') |
+-----------------------------------+
|                                 1 |
+-----------------------------------+
1 row in set (0.00 sec)
```
while presto's result is 7
```
presto:orc> select day_of_week(timestamp '2015-05-03');
 _col0 
-------
     7 
(1 row)

Query 20150527_083532_00015_vvwhd, FINISHED, 1 node
Splits: 1 total, 1 done (100.00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]
```

**Comment by electrum** [comment]
`day_of_week` is defined to return the ISO day, so it is correct. The MySQL functions have (or should have) different behavior.
