### ISSUE TITLE
Optimize Hive connector to only analyze the first ~1000 partitions during planning

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#2898]
`MetadataManager.getLayout()` ends up fetching all the partition names from Hive for a table during planning. The Hive connector needs to be upgraded to the new TableLayout API and then made to not fetch all the partition names during planning, if there are a very large number of partitions

**Comment by martint** [comment]
It should already be fetching only the names of partitions that match the parts of the predicate that can be pushed down into the getlayouts call. I'm not sure we can do better than that, since the metastore api doesn't have a way to paginate the results.

**Comment by electrum** [comment]
Did it used to fetch partitions during planning if there were no predicates? There clearly seems to be a regression

**Comment by electrum** [comment]
If we don't have any predicates for partitions, we shouldn't need to fetch them at all during planning. The get_partition_names call can also take a limit, but we have never used it.

**Comment by martint** [comment]
Yes, it used to fetch them regardless of predicate or not. The values were used to derive a predicate to push up the plan and into the other side of joins.

**Comment by cberner** [comment]
For queries with no predicate, it shouldn't need to fetch them all though. SELECT * LIMIT 10 queries, spend a minute in planning and a few hundred milliseconds in execution.

**Comment by dain** [comment]
The point of this task is to cut off tables with an insane number of partitions.  Pulling in a few thousand partitions isn't a big deal but when people have 100K+ partitions, it can take minutes in planning.  For those cases, I think  we should just say the table covers "all".

**Comment by martint** [comment]
@cberner, agreed, but unfortunately there's no way to distinguish between that and a "select * from t join u on ... limit 10"

**Comment by martint** [comment]
@dain I don't think there's any way in the metastore app to be able to tell there are a lot of partitions without asking for them. I don't think the call that takes predicates has a limit or pagination mechanism

**Comment by dain** [comment]
@martint https://github.com/apache/hive/blob/0af6cb42725659740a022044c6cc464ef1cf4e6b/metastore/if/hive_metastore.thrift#L942
