### ISSUE TITLE
Connect to Hive with specified user name

### ISSUE THREAD

**Issue by Downchuck** [prestodb/presto#2957]
Allow the Hive user name to be set in Presto config.

Per this discussion:
https://groups.google.com/forum/#!topic/presto-users/88IO51gIkk0

**Comment by yuananf** [comment]
I think using hadoop superuser to start presto cluster will avoid this problem.

**Comment by cawallin** [comment]
This is possible now with HDFS impersonation: hive.hdfs.impersonation.enabled from https://prestodb.io/docs/current/connector/hive-security.html#hdfs-authentication. If that doesn't solve your problem, please re-open this issue.
