### ISSUE TITLE
[ERROR] [...] The package com.facebook.presto.sql.planner.plan collides with a type

### ISSUE THREAD

**Issue by hgschmie** [prestodb/presto#3022]
```
drwxr-xr-x+ 33 hschmiedehausen  staff  1122 Jun  2 09:30 ./presto-main/src/main/java/com/facebook/presto/sql/planner/plan
-rw-r--r--+ 1 hschmiedehausen  staff  1418 Jun  2 09:30 ./presto-main/src/main/java/com/facebook/presto/sql/planner/Plan.java
```

This is legal but it seems that the new eclipse compiler in Eclipse Mars is broken in that respect. Bug against the eclipse compiler filed at https://bugs.eclipse.org/bugs/show_bug.cgi?id=469317

**Comment by rschlussel** [comment]
Closing since it's not a Presto issue.

**Comment by electrum** [comment]
Making Eclipse compiler work (using `-P eclipse-compiler`) on my list. It seems that Eclipse bug is still open, so we will need to rename a few things :(
