### ISSUE TITLE
Distribute modules separately

### ISSUE THREAD

**Issue by Downchuck** [prestodb/presto#3030]
Currently, all modules are built and distributed with each presto release. That's working fine for the current fast-pace development of Presto.

I'd like to see the plugin modules (e.g. Kafka, PostgreSQL) built and distributed independently, to reduce build times and download times.

**Comment by dain** [comment]
This has been in the plans for a long time, and with 2-3 new connectors pending code review, we may need to finally implement

**Comment by martint** [comment]
One reason we haven't yet done it is that since the SPI hasn't settled enough to be able to guarantee backward compatibility, it's easier for us to maintain if they are in the same codebase.
