### ISSUE TITLE
Add mechanism to select which plugins are enabled at runtime

### ISSUE THREAD

**Issue by martint** [prestodb/presto#3044]
Currently, any plugin that's bundled in the presto package is automatically enabled at runtime. Only connectors can be mounted selectively, but every type and function provider is registered automatically.

**Comment by dain** [comment]
I think the problem is not with plugins but with functions and types.  We should split the registration of types and functions, from enabling the use of the types and functions.  So we would end up with a function/type library and then users would select which items to enable from the library.
