### ISSUE TITLE
Replace tabs with spaces when showing query text in UI

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#3056]

**Comment by kokosing** [comment]
@electrum I want to take this task, but can you elaborate a little bit more about the issue? When I browse UI I see query not formatted at all is summary section (query printed as a single line) so there is no tabs at all?

**Comment by electrum** [comment]
This tasks is for the query detail page when the original query has tabs in it.

**Comment by kokosing** [comment]
I think that to solve this issue I need to use parser to format the query, because I cannot just replace all the tabs to spaces as tabs could take part in query, like:

```
select * from t wher v = '\t'
```
