### ISSUE TITLE
Any Tutorial / Example for writing a Presto-ElasticSearch connector ?

### ISSUE THREAD

**Issue by sumanth232** [prestodb/presto#3057]
I want to write an ElasticSearch connector to perform JOINS in ElasticSearch using Presto.
Can anyone pls suggest on how to start. Any guidance will be of lot of help.

**Comment by Downchuck** [comment]
ElasticSearch has several Java clients available -- use the scroll method for large result sets:
https://www.elastic.co/guide/en/elasticsearch/guide/master/scan-scroll.html

Crate.io has an SQL adapter on top of the ElasticSearch code base, which could be of some help.

**Comment by sumanth232** [comment]
Crate does not support JOINs. 
Its mentioned in the FAQ -  https://crate.io/docs/faq/

```
Q: Does Crate support JOINs?

Not yet. JOINs are on our roadmap and we try to do them the right way in usual quality and well performing.
For a lot of use cases there are other ways to achieve the same result as with JOINs. The best way to start is to take a look at the ARRAY and OBJECT data types to denormalise your data.
```

**Comment by dain** [comment]
I would start by forking the https://github.com/facebook/presto/tree/master/presto-example-http plugin, and adapting it to be able to read from elastic search.  Last time I used elastic search the apis were all REST based so the presto-example-http plugin should be pretty close to what you need.  Once you get that working, you’ll want to work on getting predicate push down working, but I’d start by just getting it to read at all.

-dain

**Comment by sumanth232** [comment]
@dain , Can you please give me a brief on what exactly is a ConnectorSplitManager, split and a partition? I have gone through the ExampleSplitManager but could not get what exactly is it used for.

**Comment by dain** [comment]
In the legacy SPI that the example connector implements, a table is logically divided in partitions and partitions are divided into splits.  A partition can provide a `TupleDomain` which describes the bounds of the values present in the partition which Presto can use to skip sections of the table that can not match the filter predicate.  A split is simply a part of a partition. 

Presto will enumerate and filter the partitions and then enumerate the splits for the partitions.  Then Presto reads data in parallel from splits.    

If your system does not support parallel reading, simply return a single Partition and a single Split.  If your system has a more sophisticated physical layout, you will want to use the new TableLayouts SPI so that Presto can take advantage of the data organization.

**Comment by sumanth232** [comment]
I wrote a basic connector with the necessary classes implemented. I also added a .properties file in 'etc/catalog'

but I get this error : 
'''
2015-06-25T19:16:22.214+0530	INFO	main	com.facebook.presto.metadata.CatalogManager	-- Loading catalog etc/catalog/elasticsearch.properties --
2015-06-25T19:16:22.215+0530	ERROR	main	com.facebook.presto.server.PrestoServer	No factory for connector elasticsearch
java.lang.IllegalArgumentException: No factory for connector elasticsearch
'''

The problem is here : 
'''
private void loadPlugin(URLClassLoader pluginClassLoader)
            throws Exception
    {
        ServiceLoader<Plugin> serviceLoader = ServiceLoader.load(Plugin.class, pluginClassLoader);
        List<Plugin> plugins = ImmutableList.copyOf(serviceLoader);

        if (plugins.isEmpty()) {
            log.warn("No service providers of type %s", Plugin.class.getName());
        }

        for (Plugin plugin : plugins) {
            log.info("Installing %s", plugin.getClass().getName());
            installPlugin(plugin);
        }
    }
'''

**Comment by sumanth232** [comment]
The above problem solved after I added a file with the name 'com.facebook.presto.spi.Plugin' in the 'META-INF/services' directory : 
```
presto/presto-elasticsearch/src/main/resources/META-INF/services/com.facebook.presto.spi.Plugin
```

But, I observed that for the other connectors (except tpch), the same file is present in a different directory : 
```
presto/presto-kafka/target/classes/META-INF/services/com.facebook.presto.spi.Plugin
presto/presto-raptor/target/classes/META-INF/services/com.facebook.presto.spi.Plugin
...
...
kafka and raptor do not have a 'src/main/resources/META-INF/services' directory at all
```

**Comment by sumanth232** [comment]
Pls tell me how to accurately implement these 3 function in the 'RecordCursor' interface while writing a connector
```
    long getTotalBytes();

    long getCompletedBytes();

    long getReadTimeNanos();
```

Please help ... pls..pls..pls..

**Comment by electrum** [comment]
Those functions are only for stats. If they don't mean anything for your connector or that info is not available just return 0.

**Comment by sumanth232** [comment]
Does Presto support dynamic coulmns, for datastores which contain JSON documents.
In the Example connector, all the columns are hardcoded in 'example-metadata.json', where as new columns can be added in the csv doc. How to handle newly added columns in the csv (or new properties in JSON docs in elasticsearch indices) ? Any suggestions will be of great help.
Thanks.

**Comment by RobinUS2** [comment]
What's the status on this one? Any progress made? Thanks!

**Comment by sumanth232** [comment]
@RobinUS2 , here is a basic version of the connector. It needs to be developed further and optimised.
https://github.com/facebook/presto/pull/3240

**Comment by corneversloot** [comment]
Slightly off topic but still relevant for people looking into this topic; we have released a first version of a JDBC driver for Elasticsearch called [sql4es](https://github.com/Anchormen/sql4es). It supports most common SQL statements and can be use from any system supporting the JDBC interface.

**Comment by ebuildy** [comment]
Should not be better to have a connector to Apache Lucene instead Elasticsearch HTTP API ?

BTW you could use Hive external table elastisearch (via elasticsearch-hadoop official hive connector) and query it from PrestoDB.

**Comment by corneversloot** [comment]
Well, first of all the driver uses the transport API and not the HTTP one. I think you actually do want to use Elasticsearch because it provides distributed query execution and high availability.

The Hive connection you mention should work I think although I must admit i have never used it.

**Comment by rohanarora0921** [comment]
@sumanth232 Are you still working on this? Any progress?

**Comment by eulalie367** [comment]
https://github.com/albertocsm/presto/tree/master/presto-elasticsearch

**Comment by dzen** [comment]
I found this other fork today : https://github.com/ebyhr/presto

**Comment by findepi** [comment]
This issue is obsolete now, closing.

As to the elasticsearch connector, if the above mentioned implementations are applicable to general audience, it would be valuable to have one in presto codebase.
