### ISSUE TITLE
Add max size setting for Hive over S3

### ISSUE THREAD

**Issue by Downchuck** [prestodb/presto#3067]
PrestoDB notes how much data is being read to execute a query, the Hive adapter can read data from a remote source, such as Amazon S3. Presto could cancel a query if the total size read reaches a configurable limit, avoiding unwanted costs for complex or poorly optimized queries.

**Comment by electrum** [comment]
This is an interesting idea, and I definitely understand the usefulness, but it will be difficult to implement with the current connector API, since workers reading from S3 only know about the small split that they are processing.

**Comment by Downchuck** [comment]
The cli appears to get some kind of live metrics: they may delayed, they
may be loose, but it's sufficient for the use case, exiting early.
I don't think there's a reasonable way to write in code to exactly limit
the bytes read, given the distributed nature of the workers. Doesn't seem
necessary to be exact. Just near-enough.

**Comment by snarayananqubole** [comment]
We're discussing doing something very similar. Have the client cancel queries if certain limits are hit based on live metrics.
