### ISSUE TITLE
Add Teradata's nPath to Presto?

### ISSUE THREAD

**Issue by zhenxiao** [prestodb/presto#3081]
where Teradata already have the nPath:
http://developer.teradata.com/aster/articles/aster-npath-guide

could be useful to add it into Presto

**Comment by damiencarol** [comment]
IMHO SQL:2003 define it more well.
Analytic Functions are present in many RDBMS. Why define another syntax not in SQL standard?

**Comment by electrum** [comment]
nPath allows pattern matching, which is difficult or impossible (at least without the latest `VALUE_OF` which we have yet to implement).

Oracle 12 adds `MATCH_RECOGNIZE`, which was proposed for the SQL standard though it was not (yet?) added. The Oracle version seems to be more complete than nPath, so the Oracle version would seem to be the better one to add, but if there a good reasons and sufficient demand, we could consider adding both.

http://docs.oracle.com/database/121/DWHSG/pattern.htm
http://www.cs.ucla.edu/classes/winter15/cs240B/notes/row-pattern-recogniton-11.pdf

**Comment by KBP-TDC** [comment]
Aster nPath is patented and that's an issue. If there is an alternative algorithm that we can legally use, that would be great.

**Comment by electrum** [comment]
I filed #5850 for `MATCH_RECOGNIZE`.
