### ISSUE TITLE
Include views in SHOW TABLES list

### ISSUE THREAD

**Issue by damiencarol** [prestodb/presto#3133]

**Comment by vainfucker** [comment]
I would like to take this one

**Comment by vainfucker** [comment]
I'm planning to add additional column `view_definition` to `SHOW VIEWS` output.
Does it makes sense? 
Cons that output might be a bit overwhelmed.

**Comment by electrum** [comment]
We should actually include views in the output of `SHOW TABLES`, since they are the same from a user's perspective (it is a queryable relation). For comparison, MySQL, PostgreSQL and JDBC `DatabaseMetaData.getTables()` all return views when listing tables.

**Comment by electrum** [comment]
We also need an easy way to see the view text without querying `information_schema`. Perhaps `SHOW CREATE VIEW`?

**Comment by damiencarol** [comment]
Yes, `SHOW CREATE VIEW` is a good candidate.
I agree that instead of using `SHOW VIEWS`, we could use `SHOW TABLES`.
@electrum what do you think of the syntax of MySQL ? http://dev.mysql.com/doc/refman/5.0/en/show-tables.html 
Should we add the `FULL` feature?

**Comment by vainfucker** [comment]
Actually SHOW TABLES already returns views among tables.
I was also thinking about SHOW CREATE VIEW statement. I might be useful.
And the FULL feature also make sense for me.
If you agree with adding that futures i would like to do that.

**Comment by vainfucker** [comment]
Should i add `FULL` keyword as well?

**Comment by vainfucker** [comment]
Should i add the `FULL` keyword as well?

**Comment by martint** [comment]
SHOW CREATE VIEW is weird syntax in my opinion. I would rather go with SHOW VIEW or DESCRIBE VIEW

**Comment by dain** [comment]
SHOW CREATE x renders the command to recreate the object.  DESCRIBE x shows
the schema.

On Jun 20, 2015, at 11:51 AM, Martin Traverso <notifications@github.com>
wrote:

SHOW CREATE VIEW is weird syntax in my opinion. I would rather go with SHOW
VIEW or DESCRIBE VIEW

—
Reply to this email directly or view it on GitHub
<https://github.com/facebook/presto/issues/3133#issuecomment-113804147>.

**Comment by electrum** [comment]
It is analogous to SHOW CREATE TABLE which shows the SQL to create the table. I've found this to be very useful in MySQL (and wrote a similar one for Oracle).

**Comment by igorbarinov** [comment]
:+1: for view in mysql

**Comment by maciejgrzybek** [comment]
@electrum: Since views are included in the `show tables` list, shouldn't this be closed or renamed to be in line with @vainfucker PR?

**Comment by cawallin** [comment]
Closing because views are included in SHOW TABLES, and https://github.com/prestodb/presto/pull/3140 adds support for SHOW CREATE VIEW.
