### ISSUE TITLE
Optimize CREATE TABLE AS SELECT

### ISSUE THREAD

**Issue by arhimondr** [prestodb/presto#3146]
1. Plans for the queries, which have static "false" predicate (e.g. `CREATE TABLE nation_copy AS SELECT * FROM nation WHERE 0=1`), should be rewritten in a way that they will not produce any TableWriterNode's.
2. In TableWriterOperator we should create page sink only when at least one row arrived. Now page sink is created in constructor. It causes empty files creation for Hive tables. It will prevent from empty files creation in the cases, when the output is empty, but we can't determine it on a planning phase.

**Comment by gazing-star** [comment]
I ran the query with Presto version 0.115, and verified that this does NOT result into creating empty files any more. What remains to be done is the code optimization (i.e. taking care of the TableWriterNode's that are being created). In light of the re-designing of the optimizer, I assume that this will be taken care of soon?
