### ISSUE TITLE
Rename query.initial-hash-partitions 

### ISSUE THREAD

**Issue by haozhun** [prestodb/presto#3198]
`query.initial-hash-partitions` now controls the number of partitions for arbitrary partitioning (which is implemented for table writing). We should probably rename it. What is a good name?

**Comment by cberner** [comment]
Maybe `query.target-partitions` or `query.default-partitions`? @electrum or @martint thoughts?

**Comment by electrum** [comment]
Max partitions? Since it will be at most this (limited if fewer nodes and not multi scheduling). Right?

**Comment by haozhun** [comment]
If source partitioned, I suppose it can go over this number?
