### ISSUE TITLE
cpu-time limits for queries

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#3251]
we should support cpu-time based limits on queries, similarly to how memory limits work.

This should go in `ClusterMemoryManager.process()` and work similarly to how the memory limit is enforced. You can get the total CPU time for the query from `QueryExecution.getQueryInfo().getQueryStats()`, but you may want to add a method to get it directly from a `QueryExecution` similar to `getTotalMemoryReservation()`

**Comment by yangyangyyy** [comment]
I'll be working on this one
