### ISSUE TITLE
Predict upper limit on memory usage for queries

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#3254]
All queries are given the default maximum for distributed memory usage. We should analyze the query plan to determine if they will actually use this much (a scan-filter-project query will never hit it for example), and reduce the limit for that query. This will make it easier to predict when the cluster will run out of memory

**Comment by pvam** [comment]
@cberner any updates on this?

**Comment by cberner** [comment]
I don't think anyone is actively working on it
