### ISSUE TITLE
Hive columns with varchar(x) or char(x) data types are ignored

### ISSUE THREAD

**Issue by rogersmarin** [prestodb/presto#3257]
Apologies if this is a known issue, I was unable to find out if this was previously reported or not.

I have an external hive table with columns defined as varchar(255) and char(1) and presto seems to be ignoring them. Presto is not able to find these columns when included in a query, similarly when doing a DESCRIBE on the table all other columns are shown except these.

I am running hive 0.13.1 and presto 0.110.

**Comment by cawallin** [comment]
Presto does not currently support types with integer parameters (see pending PR #2478, which adds support for VARCHAR(x)). The behavior you see is expected: DESCRIBE does not return columns of types that Presto does not support.  The list of supported types is here: https://prestodb.io/docs/current/language/types.html.

**Comment by rogersmarin** [comment]
Thanks for the update, now this is just a thought as I'm not sure if this is feasible or not but we have quite a few hive tables with varchar and char columns using integer parameters.

In the case of VARCHAR(X) and CHAR(X) would it be worthwhile/ feasible to treat them as VARCHARs?.

Similarly I'm assuming hive decimal data types with integer parameters are not supported, could these be treated as DOUBLES?

**Comment by kyleburke** [comment]
Is there any way for Presto to handle hive columns that are strings? Hive has a STRING data type but Presto is not resolving my STRING columns in Hive either?

**Comment by BigDataDaddy** [comment]
Is this issue resolved?  The current doc for Presto 0.146 here: https://prestodb.io/docs/current/language/types.html seems to indicate that VARCHAR now supports an  optional integer length parameter, like VARCHAR(256).

**Comment by cawallin** [comment]
VARCHAR(X) is fixed now for Hive and will be available in 0.147. We're working on support for VARCHAR for all of the connectors, I believe that VARCHAR(X) will also be available in 0.147 for the Redis and Kafka connectors.
