### ISSUE TITLE
Cassandra connector make describe statement more verbose

### ISSUE THREAD

**Issue by nataliya-aio** [prestodb/presto#3374]
It would be very helpful if describe statement returned information on columns that are parts of rowkeys of a table and their order and columns that are indexed in Cassandra.

**Comment by electrum** [comment]
Currently, `DESCRIBE` is an alias for `SHOW COLUMNS` which is effectively a query that returns a list of columns. It is similar to running a query like `SELECT name, type, ... FROM ...`, so there isn't a good way to have it return connector specific information. But this would be useful, so we should think about how to make `DESCRIBE` or a variant of it allow that.

**Comment by nataliya-aio** [comment]
Thank you. Otherwise, it could maybe be returned as a result of select statement?
