### ISSUE TITLE
Add start_time to system.runtime.nodes

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#3406]
This should be a `timestamp` of when the node started. It can be added to the announcement as a property like `node_version` in `ServerMainModule`, then pulled out in `DiscoveryNodeManager` and added to `PrestoNode`.

**Comment by nezihyigitbasi** [comment]
claiming this one if no one is working on it.

**Comment by nezihyigitbasi** [comment]
apparently someone is working on it, so not claiming it.
