### ISSUE TITLE
How presto can show Chinese in the query results support ?

### ISSUE THREAD

**Issue by phoenixhadoop** [prestodb/presto#3417]
Hi,friends
    I eagerly want to know how presto can support in the query results show Chinese, thank you very much.

**Comment by haozhun** [comment]
Are you referring to presto CLI? Presto works with Unicode data.

**Comment by phoenixhadoop** [comment]
Thank you for your quick answer.Yes,I use CLI.How to support Chinese ?

**Comment by haozhun** [comment]
Do you want Chinese in query output? We already have that.
Do you want Chinese in error message, etc? This is not on our road map.

**Comment by phoenixhadoop** [comment]
I want Chinese in query output,thanks.How to configure presto?

**Comment by phoenixhadoop** [comment]
I am using presto-0.86.

**Comment by haozhun** [comment]
Presto always supports Chinese output in query output. No configuration is required if you terminal can otherwise display Chinese (UTF8-encoded) properly. We do have a known issue with not aligning double-wdith characters properly. But this inconvenience does not stop you from using it.

```
presto:di> select from_utf8(from_hex('E98791'));
 _col0
-------
 金
(1 row)

Query 20150805_001811_00006_pkekm, FINISHED, 1 node
http://localhost:8080/v1/query/20150805_001811_00006_pkekm?pretty
Splits: 1 total, 1 done (100.00%)
CPU Time: 0.0s total,     0 rows/s,     0B/s, 100% active
Per Node: 0.0 parallelism,     0 rows/s,     0B/s
Parallelism: 0.0
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

presto:di> select * from (values '金');
 _col0
-------
 金
(1 row)

Query 20150805_001814_00007_pkekm, FINISHED, 1 node
http://localhost:8080/v1/query/20150805_001814_00007_pkekm?pretty
Splits: 1 total, 1 done (100.00%)
CPU Time: 0.0s total,     0 rows/s,     0B/s, 0% active
Per Node: 0.0 parallelism,     0 rows/s,     0B/s
Parallelism: 0.0
0:00 [0 rows, 0B] [0 rows/s, 0B/s]
```

**Comment by phoenixhadoop** [comment]
OK,Tomorrow  will try it.Thank you very much.I go to sleep now.good night.

**Comment by phoenixhadoop** [comment]
My presto-0.86 do not have the function from_utf8 and the sql:select * from (values '金'); could not execute.Help please.

**Comment by dain** [comment]
Please upgrade to the latest release.

**Comment by rschlussel** [comment]
Closing.  If you have more questions about using Presto, you can email presto-users@googlegroups.com
