### ISSUE TITLE
Common table expression (WITH) executed multiple times

### ISSUE THREAD

**Issue by RobinUS2** [prestodb/presto#3431]
We we're trying to optimize a few queries which basically have the issue that there is one (or multiple) results of a WITH-statement that can be reused to speedup the results of other subqueries and the final result.

I wrote an example query (see below) where the `expensive_input_data` would take the majority of the time of the query (time & resources like CPU). The top_a, top_b and top_c are only examples and could in reality have very different logic.

Currently I attempt to re-use the results of that in 3 sub queries. From my point of view it should only run once, and then stream the results into the other subqueries. 

What we see however (version 0.114) is that it is executed once for every sub query that depends on it (in this example 3 times). 

Is there a way we can optimize by rewriting the query? If not, how can we improve the source code to support these kind of use cases? Can we trick the execution plan to distributed the results to the splits? Is there something that needs to be coded (happy to do so if you can point out the major steps and what syntax we need to "hint" for this)?

```
WITH expensive_input_data 
AS 
  ( 
           SELECT   cola, 
                    colb, 
                    colc, 
                    count(1) AS c 
           FROM     my_table 
           JOIN     other_table 
           ON       ( 
                             my_table.id=other_table.parent_id) 
           WHERE    1=1 
                    /** expensive filter etc */ 
           GROUP BY 1, 
                    2, 
                    3 ), top_a 
AS 
  ( 
           SELECT   cola   AS k, 
                    sum(c) AS c 
           FROM     input_data 
           GROUP BY 1 
           ORDER BY 2 DESC 
           LIMIT    10 ), 
  top_b 
AS 
  ( 
           SELECT   colb   AS k, 
                    sum(c) AS c 
           FROM     input_data 
           GROUP BY 1 
           ORDER BY 2 DESC 
           LIMIT    10 ), 
  top_c 
AS 
  ( 
           SELECT   colc   AS k, 
                    sum(c) AS c 
           FROM     input_data 
           GROUP BY 1 
           ORDER BY 2 DESC 
           LIMIT    10 ) 
  SELECT * 
  FROM   top_a 
  UNION 
  SELECT * 
  FROM   top_b 
  UNION 
  SELECT * 
  FROM   top_c;
```

Thanks for looking into this!

**Comment by KBP-TDC** [comment]
Can you try a brute-force approach to save the common subquery output into a new (temporary) table and then reuse it x3? I don't know of any better way today in Presto.

**Comment by RobinUS2** [comment]
Thanks @KBP-TDC for your reply. We have tested that, and yes it does work, but it is not very flexible as it will cause a lot of overhead and unnecessary pressure on the metastores (from Hive).

It feels to me that this shouldn't be too hard to accomplish looking at the streaming data that is already in place.

**Comment by dain** [comment]
In the latest release, you should be able to do this in a transaction like this;
```sql
start transaction;
-- materialize "with" clauses from above
create expensive_input_data as select ...;
create top_b as select ...;
create top_c as select ...;

select ....;

rollback;
```
With this Presto will not write the tables to the metastore at all.  If you want to create a table and commit in the transaction, simply drop the tables at the end.

**Comment by RobinUS2** [comment]
That sounds like a much better workaround 👍  thanks!
