### ISSUE TITLE
how to calculate the number of splits

### ISSUE THREAD

**Issue by zhuqunzhou** [prestodb/presto#3448]
in my project,i used presto to read data from hive. hive data is orc format.now i have l lot of files（about ten files of 100M size）,when i query ,i need ten seconds to select data from a table.i find that ,presto probably each 30M size a split。i think set litter size of each size of split is effective,but i don't know how to set。（any other ways to optimize my presto config） thanks very much.

**Comment by cberner** [comment]
You can change the split size with the "hive.max-split-size" config property

**Comment by dain** [comment]
Unfortunately, for ORC that may not help. The minimum parallelization size for ORC is an ORC stripe which is typically 100MB, so I would guess each file contains a single stripe and therefore will run on a single core.

-dain
