### ISSUE TITLE
Feature request : inmemory temp table support in Presto

### ISSUE THREAD

**Issue by puneetjaiswal** [prestodb/presto#3499]
This is a follow up request from @electrum's reply to this post https://groups.google.com/forum/#!topic/presto-users/5I480n_1nPc

Creating this issue to track development for this task.

It will be great if Presto could provide a way to save output of a query as inmemory temp table. 
Something like this (from spark)

`DataFrame teenagers = sqlContext.sql("SELECT * FROM people WHERE age >= 13 AND age <= 19");`
`teenagers.registerTempTable("teenagers");`

Now we can slice and dice teenagers table.

`DataFrame teensFromSF = sqlContext.sql("SELECT * FROM teenagers WHERE city = 'san fransokyo' ")`

**Comment by DuskoV** [comment]
+1

**Comment by cawallin** [comment]
@puneetjaiswal -- it's not exactly a temp table, but you can store intermediate results in the memory connector (https://prestodb.io/docs/current/connector/memory.html). Does that work for you?

**Comment by Downchuck** [comment]
@puneetjaiswal I believe Spark treats that more like a temporary view, and doesn't access data until the data is requested, by running something like collect().

That said, it sounds like you're looking for "CREATE TEMPORARY VIEW" or "CREATE TEMPORARY TABLE" on a per-session basis.

**Comment by anusudarsan** [comment]
I am currently looking into adding support for session-level temporary tables.  Assigning this issue to me

**Comment by aromero-pm** [comment]
@anusudarsan do you have any new comments on session-level temporary tables in Presto? Thanks for any update.

**Comment by kdonavin** [comment]
Seconding @aromero-pm years later. I still think this is a good idea. Any chance this will get done in the future, @anusudarsan?

**Comment by findepi** [comment]
@kdonavin for your information, @anusudarsan now works on https://github.com/prestosql/presto/ repo, you can find her there.
You can also reach her on [Presto Community slack](https://prestosql.io/slack.html).
