### ISSUE TITLE
Add a way to specify the HDFS user that the Hive connector uses

### ISSUE THREAD

**Issue by cawallin** [prestodb/presto#3541]
As discussed in #3512.

We run hive as the hive user and presto as root. We get an error when writing to `/user/hive/warehouse`:
```
presto:default> CREATE TABLE nation_hive AS SELECT \* FROM tpch.tiny.nation;

Query 20150901_174721_00004_b6ivj, FAILED, 4 nodes
Splits: 10 total, 9 done (90.00%)
0:07 [25 rows, 0B] [3 rows/s, 0B/s]

Query 20150901_174721_00004_b6ivj failed: Failed to rename hdfs://master/tmp/presto-root/79f16b4f-3388-4f97-a083-aa1b2544d7f3 to hdfs://master/apps/hive/warehouse/nation_hive
```

And in the server log:
```
com.facebook.presto.spi.PrestoException: Failed to rename hdfs://master/tmp/presto-root/79f16b4f-3388-4f97-a083-aa1b2544d7f3 to hdfs://master/apps/hive/warehouse/nation_hive
at com.facebook.presto.hive.HiveWriteUtils.renameDirectory(HiveWriteUtils.java:358)
...
Caused by: org.apache.hadoop.security.AccessControlException: Permission denied: user=root, access=WRITE, inode="/apps/hive/warehouse":hive:hdfs:drwxrwxr-x
at org.apache.hadoop.hdfs.server.namenode.DefaultAuthorizationProvider.checkFsPermission(DefaultAuthorizationProvider.java:257)
...
```

The directories in HDFS:
```
[root@cwallin-vsphere-presto-cwallin-1-master prestoadmin]# sudo -u hdfs hadoop fs -ls /tmp/
Found 2 items
drwx-wx-wx - hive supergroup 0 2015-08-31 13:56 /tmp/hive
drwxr-xr-x - root supergroup 0 2015-09-01 10:47 /tmp/presto-root
[root@cwallin-vsphere-presto-cwallin-1-master prestoadmin]# sudo -u hdfs hadoop fs -ls /apps/hive/
Found 1 items
drwxrwxr-x - hive hdfs 0 2015-09-01 10:47 /apps/hive/warehouse
```

It's unclear the best way to write to the database location (/user/hive/warehouse); Cloudera recommends mode 1777 for /user/hive/warehouse, but that's not necessarily the default, and we can't force people who use Presto to change permissions on that directory (some setups of Hive even have permissions for that directory locked down: http://spryinc.com/blog/locking-down-default-warehouse-hive). A workaround for the above issue is to add the following property to jvm.config: `-DHADOOP_USER_NAME=USER`, where USER is a user that has permission to write to /user/hive/warehouse (the `hive` usually works, since most of the time hive is started via the `hive` operating system user).

Note: before working on this, determine how Hive handles this, how it works in other tools, how is it "supposed" to work, etc. It seems like the recommended way to handle folder permissions for non-Hive-managed tables is external tables, but then you have to add partitions explicitly.

**Comment by cawallin** [comment]
Possible via https://prestodb.io/docs/current/connector/hive-security.html#hdfs-authentication

**Comment by cawallin** [comment]
This is still an issue with HDFS authentication turned on. With -DHADOOP_USER_NAME=hdfs, the following fails:
```
> presto --server localhost:8080 --catalog hive --schema cwallin --user hive --debug
presto:cwallin> create table check_owner(a bigint);
Query 20170422_053839_00034_ehjq9 failed: Failed to create directory: hdfs://hadoop-master:8020/tmp/presto-hive/d6e4bad7-3245-47fb-98ec-b68ea17609f7

=========   TECHNICAL DETAILS   =========
[ Error message ]
Failed to create directory: hdfs://hadoop-master:8020/tmp/presto-hive/d6e4bad7-3245-47fb-98ec-b68ea17609f7

[ Session information ]
ClientSession{server=http://localhost:8080, user=hive, clientInfo=null, catalog=hive, schema=cwallin, timeZone=UTC, locale=en_US, properties={}, transactionId=null, debug=true, quiet=false}

[ Stack trace ]
com.facebook.presto.spi.PrestoException: Failed to create directory: hdfs://hadoop-master:8020/tmp/presto-hive/d6e4bad7-3245-47fb-98ec-b68ea17609f7
	at com.facebook.presto.hive.HiveWriteUtils.createDirectory(HiveWriteUtils.java:495)
	at com.facebook.presto.hive.HiveWriteUtils.createTemporaryPath(HiveWriteUtils.java:482)
	at com.facebook.presto.hive.HiveLocationService.forNewTable(HiveLocationService.java:57)
	at com.facebook.presto.hive.HiveMetadata.createTable(HiveMetadata.java:694)
	at
... 
Caused by: org.apache.hadoop.security.AccessControlException: Permission denied: user=hive, access=WRITE, inode="/tmp/presto-hive/d6e4bad7-3245-47fb-98ec-b68ea17609f7":presto:hadoop:drwxr-xr-x
```

**Comment by sudhirsrepo** [comment]
Hey @cawallin , I am also facing same permission issue. Is there any work around available ?

`
com.facebook.presto.spi.PrestoException: Failed to create directory: hdfs://master-node:8020/tmp/presto-ec2-user/50fc2d5d-c0c6-42e9-8240-3308df37a478
	at com.facebook.presto.hive.HiveWriteUtils.createDirectory(HiveWriteUtils.java:482)
	at com.facebook.presto.hive.HiveWriteUtils.createTemporaryPath(HiveWriteUtils.java:469)
......
.......
Caused by: org.apache.hadoop.security.AccessControlException: Permission denied: user=presto, access=EXECUTE, inode="/tmp/presto-ec2-user/50fc2d5d-c0c6-42e9-8240-3308df37a478":mapred:hadoop:drwxrwx---

`

**Comment by jangorecki** [comment]
I don't use presto anymore but I think this feature is highly valuable.
