### ISSUE TITLE
Decimal support in TPCH

### ISSUE THREAD

**Issue by sopel39** [prestodb/presto#3557]
Hi Guys,

As you know we have been working on decimal type for some time. We have implemented decimal using both `long` primitive (for short decimals) and `Slice` (for long decimals). We would like to benchmark decimal type using presto benchmarking mechanism. In order to do so it would be best to use decimal types in TPCH connector. We propose to introduce additional schemas in TPCH connector. We would have three schemas families: one using short decimals (precision <= 17), one using long decimals (precision > 17) and one using double types for numeric TPCH columns. Such approach would enable us to test decimal performance using in memory TPCH connector and in hive connector. It would also enable us to check compatibility with TPCH test suite, since all required types would be supported.

CC: @martint @losipiuk @cberner

**Comment by kokosing** [comment]
Is this still valid?

**Comment by sopel39** [comment]
It is

**Comment by kokosing** [comment]
@atris Would you take a look?

**Comment by atris** [comment]
Ack, will do

**Comment by atris** [comment]
Please see #11166
