### ISSUE TITLE
string(varchar) operation in ORCFile Table, runs too slow

### ISSUE THREAD

**Issue by Sartner** [prestodb/presto#3583]
hello~~

I have a presto cluster with 9 servers, one of them is the coordinator without worker
each server have 16 cpu cores and 128g ram (32g give to presto);

when I execute the SQL, it runs too slow(below 200M/s)
select count(distinct a_string_column) from T_an_ORCFile_table_with_a_billion_rows;

an other TextFile table with the same data, runs well (more than 4GB/S)

both of the table without compression

My presto conf is:
task.max-memory=16GB
query.max-memory=128GB
query.max-memory-per-node=16GB
optimizer.optimize-hash-generation=true
task.writer-count=8

**Comment by dain** [comment]
How do they compare in rows per second?  

In the case of a text file, Presto must read 100% of the file, select out the column you are performing distinct on, and then discard the data.  With ORC, Presto only reads the one column.  Additionally, ORC files are gzip compressed which typically makes them 4-10x smaller.  Given both of these, 200MB of ORC may contain more column values than 4GB of text data.

**Comment by Sartner** [comment]
i have run the sql for 30s

in ORCFile table
0:33 [ 258M rows, 3.25GB] [7.71M rows/s, 99.4MB/s]

in TextFile table
0:30 [ 819M rows,  102GB] [26.9M rows/s, 3.36GB/s]

**Comment by dain** [comment]
One other thing that happens with ORC is because the compression is so much better than text, you can end up with less files.  So you end up having more cores than you have splits.  If you run the CLI with the --debug option it will show you the stats per node and the number of CPUs you are using.

**Comment by Sartner** [comment]
But how to solve the problem?
Now, I have no choice but to keep the table in two types(ORC and TextFile), and select these two tables in my java program.

**Comment by Sartner** [comment]
@martint  @joshk  @electrum  @dsp 
do you have any idea?

**Comment by dain** [comment]
My guess that ORC is compressing the data so much that it all ends up in a small number of small files.  Presto parallelizes the based file chunks based on size.  If your ORC files are much smaller than the TEXT files you are comparing against, there will be less parallel workers applied to the data.  You can verify this by running the queries in the Presto CLI with the `--debug` option, which will print the number of nodes and splits in the query.  Unfortunately there is currently nothing that can be done to speed up this kind of file other than to rewrite the file in another format like RCFile.
