### ISSUE TITLE
Better BI tool compatibility, ignore auto-commit settings.

### ISSUE THREAD

**Issue by dmoore247** [prestodb/presto#3592]
Pentaho BA server blows up when creating a table data source.

I believe that the JDBC driver code throws SQL Not supported exception when auto-commit is being turned off (after looking at code with Cristina).

I think for better tool compatibility it would be good to ignore auto commit settings since there really is only one mode.

<img width="1440" alt="screen shot 2015-09-11 at 2 45 25 pm" src="https://cloud.githubusercontent.com/assets/1122251/9823364/d1d9da38-5893-11e5-8b47-f4ccac922560.png">

**Comment by dmoore247** [comment]
My driver is from the .101T release.

The responsible source code:
https://github.com/facebook/presto/blob/d81c2f6fc6dd614492012d233a397afd743af712/presto-jdbc/src/main/java/com/facebook/presto/jdbc/PrestoConnection.java
   
 @Override
    public void setAutoCommit(boolean autoCommit)
            throws SQLException
    {
        checkOpen();
        if (!autoCommit) {
            throw new SQLFeatureNotSupportedException("Disabling auto-commit mode not supported");
        }
    }

**Comment by cawallin** [comment]
@dmoore247  -- I was looking into this more, and I think you will quickly run into other issues after turning auto-commit mode to false. Presto does not support transactions, and thus does not support commit()/rollback() in the JDBC connection (which presumably Pentaho uses if it's turning auto-commit mode to false).

**Comment by xerial** [comment]
@cawallin Now that presto can use begin transaction statement, does it make any sense to revisit this issue?  I found R/JDBC also tries to use `setAutoCommit(false)`

**Comment by cawallin** [comment]
@xerial Sure, I don't have that much context on this any more but it seems reasonable.

**Comment by kokosing** [comment]
`Connection::setAutoCommit` is implemented since 0.189 (November 2017).
