### ISSUE TITLE
audit `new Duration` callsites

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#3599]
It's not safe to call `new Duration` with a value derived from `System.currentTimeMillis()` as that clock can move backwards. All calls to `new Duration` should be using a value derived from `System.nanoTime()`

**Comment by petroav** [comment]
I'll claim this if no one is working on it.

**Comment by martint** [comment]
Go for it!

**Comment by petroav** [comment]
Closing since fix was merged.
