### ISSUE TITLE
Hive connector: sort bucketed tables not handled correctly

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#3603]
User on mailing list reported that reading from a sort bucketed table does not work properly: https://groups.google.com/forum/#!topic/presto-users/PjohcRjcbZw

We need a test for this case in `AbstractTestHiveClient`

**Comment by taklwu** [comment]
is this still an open issue?

**Comment by haozhun** [comment]
We never got a reproduce of this issue. Unfortunately, the information available in the mailing list was quite limited.

**Comment by electrum** [comment]
Closing this since there is no reproduction.
