### ISSUE TITLE
Support DISTINCT for aggregate window function parameters

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#3626]

**Comment by maciejgrzybek** [comment]
E.g.
```sql
presto:default> select count(distinct x) over() from (values (1), (1), (2), (2)) t(x);
Query 20160720_164935_00013_ewdnz failed: line 1:1: DISTINCT in window function parameters not yet supported: "count"(DISTINCT "x") OVER ()
```

**Comment by maciejgrzybek** [comment]
Given https://github.com/prestodb/presto/pull/7788 is merged, please be advised that this task would require changes in `AccumulatorCompiler` as it's stated in `generateAddInputWindowIndex` method:
```// TODO: implement masking based on maskChannel field once Window Functions support DISTINCT arguments to the functions.```.
Therefore, it may not be `intermediate-task` anymore IMO.
