### ISSUE TITLE
Passwords with diactric characters are not parsed correctly

### ISSUE THREAD

**Issue by grepwood** [prestodb/presto#3648]
I had a connector with a password containing the letter ö. Via native MySQL client, I was able to connect with the username and password supplied in the .properties file, but PrestoDB could not access anything.

**Comment by dain** [comment]
Presto uses the java.util.Properties (http://docs.oracle.com/javase/7/docs/api/java/util/Properties.html) class to parse this file.  You should be able to encode unicode characters using the Java escape form (e.g. `\u0009` for a tab)

**Comment by martint** [comment]
java.util.Properties uses ISO 8859-1 encoding by default. We might want to change the loader to decode the files with UTF-8.
