### ISSUE TITLE
presto 0.119 can not get table info from mysql database.

### ISSUE THREAD

**Issue by yuananf** [prestodb/presto#3677]
We face the same problem as
https://groups.google.com/forum/#!topic/presto-users/fY_p3uwhWHM

**Comment by kokosing** [comment]
@martint I think we can close it as a duplicate of #3763

**Comment by rraghuram64** [comment]
Hello

Did you solve the issue ?

I actually defined the file mysql.properties in /presto/etc/catalog and when I try to see the tables in mysql it says there is no catalog with the name.

Could you please help me with this.

Thanks
