### ISSUE TITLE
Autocomplete in CLI is slow

### ISSUE THREAD

**Issue by cosinequanon** [prestodb/presto#3722]
If there are a lot of tables to match then the CLI blocks for a long time trying to figure out all the possibilities. If there are 200k tables then this takes about 30 seconds, we should try and reduce how long this takes.

**Comment by rschlussel** [comment]
Seems like this is due to #3723.  Reopen if this issue is different.

**Comment by cosinequanon** [comment]
I think it's a different issue, in the one you linked it's that the results don't go through a pager, which they should. this one is about the CLI hanging if there are a lot of choices, it's a separate issue

also, i can't reopen this issue http://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github (i think)
