### ISSUE TITLE
Improve and simplify failure detector model and config

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#3736]
The failure detector uses the `failure-detector.threshold` config, which is very difficult to reason about as it's the area under an exponentially decayed curve. We should use a model which is easier to understand and replace this config. Also, the failure detector doesn't have an HTTP timeout which means that it misses "failures" where the worker is stuck in a full GC.

I would suggest switching to model to timeout the HTTP requests (should be configurable) and then have a simple interval (probably 1min by default to match `exchange.min-error-duration`) after which the node is considered failed.

**Comment by martint** [comment]
This is a bit more complicated. One of the goals of the current implementation is to deal with cases where only *some* requests fail, maybe intermittently. It checks for the ratio of failures vs total requests to account for the fact that some may fail and some may succeed in a given period of time.

I believe what we need is something along the lines of what's described in the "Phi accrual failure detector" paper (http://www.jaist.ac.jp/~defago/files/pdf/IS_RR_2004_010.pdf), where the goal is to be able to compute what's the probability that a given node is down or unreachable based on recently observed successes/failures.

**Comment by cberner** [comment]
:+1:
