### ISSUE TITLE
RFC - JSON serialization of maps in query results

### ISSUE THREAD

**Issue by raghavsethi** [prestodb/presto#3755]
## Underlying issue
When a client talks to the Presto server to fetch query results, the server produces a JSON document in response. Presto serializes maps to JSON objects, which are only allowed to have string keys. When a map contains complex (list, map, row) keys, Presto currently uses `toString` on the key. For example:

    MAP(ARRAY[ARRAY(1,2), ARRAY(3,4)], ARRAY[ARRAY['a'], ARRAY['b']])

is JSON serialized as

    { "[1, 2]": "a", "[3, 4]": "b"}

Today, when Presto CLI encounters such a JSON document, it fails with a cryptic error message. We considered hacking the client to invert the `toString`. However, given how brittle this is for recovering complex type information, we decided against it.

## Solution
The solution we are considering is serializing all Presto maps to *lists* of key-value objects, i.e.

    MAP(ARRAY[ARRAY(1,2), ARRAY(3,4)], ARRAY[ARRAY['a'], ARRAY['b']])

will be JSON serialized as

    [ {"key": [1,2], "value": "a" }, {"key": [3,4], "value": "b" } ] 

### Challenges
This will break existing clients, and will prevent older clients from talking to servers running newer versions of Presto.

## Proposed Rollout Strategy
We expect that only a small subset of users require the ability to deal with complex key types in maps, while many (if not all) users will experience pain from having to perform a coordinated upgrade of each Presto cluster and all clients.

We believe that our proposed strategy will cause the least pain for our users as a whole while keeping the Presto API simpler and more consistent in the long run.

### Step 1
Add support for the new map serialization format to Presto CLI and presto-client, such that they can deal with both formats.

### Step 2
The server starts to serialize maps that contain complex keys in the new format, while maintaining the old serialization format for other maps.

This will break community clients that rely on Presto maps being represented as JSON objects, but *only when* the result map includes a complex key.

### Step 3
We wait for a period of time for community client to support the new map serialization format.

### Step 4
We change server functionality to serialize all maps as lists of key-value objects.

### Step 5
Remove support for the old format from Presto CLI and presto-client

## Feedback required

We would love to understand the following from our community:

- Should we have Step 2 at all? Do you think the benefits of having clients support this hybrid format outweigh the complexity cost?
- How do community clients currently deal with JSON objects containing complex keys?
  - Will your client break if it receives different JSON object types as Presto maps?
  - Does your client use Presto type information to parse the received JSON, or does it rely on the structure of the JSON itself?
- How long should we wait between Step 2 and Step 4?
- All comments and suggestions are welcome

**Comment by pnowojski** [comment]
Why in Step 2 are you considering mixed support of maps? Why can't client introduce to server, which version it supports and server would respond always in older or newer version - never mixed? I think that's more common way of solving such issues, because it preserves backward compatibility in the transition period. 

Support for older version could be preserved at least as long, as the maintenance cost remains low. For example if this code is not being changed/refactored often, then the old version could be dropped on first major code refactor. Or at least the decision to terminate/keep support for the old version could be postponed until such refactor.

**Comment by losipiuk** [comment]
+1 for @pnowojski proposal. We already have protocol version support in the urls. Let's just create new (v2) protocol which differs on how maps are serialized to client.

**Comment by frsyuki** [comment]
We had another problem with JSON. JSON can't serialize NaN. Presto serializes NaN using String (`"NaN"`). So we needed to handle unexpected string value in double column.

How about using [MessagePack](http://msgpack.org/) as a drop-in replacement of JSON? MessagePack can use any objects as keys of maps, and can serialize NaN.

For backward compatibility, Presto can return MessagePack only when a client sends `Accept: application/x-msgpack` header. [jackson-dataformat-msgpack](https://github.com/komamitsu/jackson-dataformat-msgpack) is a library to use MessagePack with Jackson annotations.

**Comment by komamitsu** [comment]
https://github.com/komamitsu/jackson-dataformat-msgpack is already merged into https://github.com/msgpack/msgpack-java/tree/v07-develop/msgpack-jackson. So I recommend to use `org.msgpack:jackson-dataformat-msgpack`.

BTW, https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/deser/std/StdKeyDeserializer.java doesn't support complex types as a key. So we need handle MessagePacked record that has a complex key without `org.msgpack:jackson-dataformat-msgpack` for now.

**Comment by raghavsethi** [comment]
Closing this, as we will need to have a larger discussion about breaking API changes in the future.
