### ISSUE TITLE
Implement CREATE TABLE LIKE

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#3771]
This should copy the columns and table properties from the old table and create a new table with the given name and the same columns and table properties.

Example: `CREATE TABLE my_new_table (LIKE my_old_table)`

**Comment by cberner** [comment]
@suyucs is going to work on this

**Comment by martint** [comment]
The proper syntax is `CREATE TABLE <table name> (LIKE <table name>)`

**Comment by martint** [comment]
Technically speaking, it supports multiple LIKE clauses and it can be interleaved with regular column definitions, but let's not worry about that for now

**Comment by martint** [comment]
The relevant part of the SQL grammar is:

```
<table definition>
  : CREATE <table scope>? TABLE <table name> <table contents source>
      (WITH <system versioning clause>)?
      (ON COMMIT <table commit action> ROWS)?
  ;

<table contents source>
  : <table element list>
  | <typed table clause>
  | <as subquery clause>
  ;

<table element list>
  : <left paren> <table element> ( <comma> <table element> )* <right paren>
  ;

<table element>
  : <column definition>
  | <table constraint definition>
  | <like clause>
  ;

<like clause>
  : LIKE <table name> <like options>?
  ;
```

**Comment by electrum** [comment]
I think we should also support the common non parenthesized form, just like we do for AS SELECT.

**Comment by martint** [comment]
I'd rather we didn't try to jam that in for now. The semantics of LIKE are different from AS SELECT. For instance, you can do:

```
CREATE TABLE foo (
    xxx VARCHAR,
    LIKE bar,
    yyy BIGINT
)
```

Trying to support the non parenthesized form will require some contortions in the grammar, potentially introduce ambiguities or make it harder to add the full syntax later.
