### ISSUE TITLE
Delete all content from unpartitioned table

### ISSUE THREAD

**Issue by haozhun** [prestodb/presto#3776]
Run `delete from an_unpartitioned_table`, it should either fail or delete all content. Right now, it completes but doesn't do anything.

**Comment by zhenxiao** [comment]
may I claim this one?
seems like delete is optimized to metadataDelete, and in metadataDelete it only deletes partitions
I think exposing partitions in connector is not in the plan, is it?
How about drop the table and delete the data, then create an empty table?

**Comment by electrum** [comment]
This a correctness issue. We need to fix it before releasing the new delete code.

**Comment by haozhun** [comment]
@zhenxiao Your understanding of how delete works right now is correct. Sorry the title was misleading. When I filed the task, I didn't have anything concrete in my mind on which direction the fix should be (make the unpartitioned delete work, or make it fail loudly). It seems like there is no easy solution to make the unpartitioned delete work. Therefore, I implemented a fix to make it fail loudly.

The concept of partition was removed from presto-main in #2628. If you are wondering whether we want to reintroduce it, the answer is know. If I misunderstood your question, feel free to ask again.

**Comment by zhenxiao** [comment]
@haozhun thank you for the explanation. Sure. Will ping you when I have other questions.

**Comment by dain** [comment]
To implement this, can't we just walk the directory and delete the data files like we do in the rollback methods?

**Comment by haozhun** [comment]
@dain If we are going to implement that, should we implement row-by-row delete instead.

**Comment by haozhun** [comment]
@zhenxiao Go ahead and implement it if you are still interested. What @dain suggested seems to be a good solution.

**Comment by zhenxiao** [comment]
Thanks @dain @haozhun. sure. I will do it following @dain 's suggestion

**Comment by dain** [comment]
Make sure to skip the hidden files.  IIRC they start with `.` or `_`.

**Comment by zhenxiao** [comment]
@haozhun @dain get a PR:
https://github.com/facebook/presto/pull/3794
Your comments are appreciated
