### ISSUE TITLE
Update hive-hadoop2 to latest Hadoop client

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#3787]
We are currently using Hadoop 2.2.0. Current version is 2.7.1.

**Comment by dzakarov** [comment]
I think this ticked will be a good addition to presto. 
RIght now this feature https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-hdfs/TransparentEncryption.html is not supported, presto gets encrypted file content and throws exception in case of binary formats like orc.

**Comment by dzakarov** [comment]
I was able to build presto-hadoop-apache2 with hadoop 2.7.1 dependencies, and it seems working with ecrypted hdfs.

**Comment by electrum** [comment]
This was fixed a while back.
