### ISSUE TITLE
Handling null value from json data.

### ISSUE THREAD

**Issue by jhsbeat** [prestodb/presto#3826]
We're using PrestoDB as a log analytics storage using **AWS S3**.
The log data is stored S3 as a **json** string in the form like below: 

```
{"a": "something", "b": null, "c": { "d": "something", "e": null } }
```

The problem is that PrestoDB recognize the value of the key "c['e']" as a **'null' string** not a **real null value**. It only occurs in nested objects not the first level key such as "b".
So the records are not shown in the results of a query such as `where c['e'] IS NULL` but are shown in the results of `where c['e'] = 'null'` or `b IS NULL`.
Is there any **recommendation** for handling this issue or any **plan** to improve the case of theses situation?

Updated:
We're using Hive-JSON-Serde for handling json nested objects. https://github.com/rcongiu/Hive-JSON-Serde

**Comment by mmerchant** [comment]
Ran into the same situation. Were you able to find a resolution @jhsbeat ?

**Comment by milescrawford** [comment]
To anyone else who comes along, @jhsbeat's update also worked for me - the hive serde seems to respect null and casing, whereas the default lowercases everything and converts literal json `null` to a string `'null'`.

How this can be the desirable default behavior is beyond me, but at least there is an option.
