### ISSUE TITLE
Large IN lists substantially slower than unioned smaller lists

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#3836]
```
SELECT a, b, sum(c) FROM t WHERE a IN (... ~500 values ...) GROUP BY 1, 2

Elapsed 4.42m
CPU Time 1.69d
```

vs

```
SELECT a, b, sum(c) FROM t WHERE a IN (... ~100 values ...) GROUP BY 1, 2
UNION ALL
SELECT a, b, sum(c) FROM t WHERE a IN (... ~100 values ...) GROUP BY 1, 2
UNION ALL ...

CPU Time 1.51h
Elapsed 23.01s
```

The column `a` is a `bigint` and the values are all larger than 32-bit. The cutoff is around 100, but can be higher: in one test one of the unioned lists had 101 values.

These should both be generating using `HASH_SWITCH` in `InCodeGenerator`, so it might be a JVM issue due to the larger switch size or code size. We should benchmark for different sizes and compare it to the Fastutil set.

Another idea for optimization is that using a Fastutil set, we can skip hashing and use direct comparison for certain types if all the values are unique.

**Comment by raghavsethi** [comment]
Interesting.. I was wondering why we settled on the 1000 cutoff for the Fastutil set.

**Comment by electrum** [comment]
There is a bytecode size limit, so we can't do much larger. But we should benchmark if the hash switch is ever faster.

**Comment by cawallin** [comment]
Fixed by https://github.com/prestodb/presto/pull/3953
