### ISSUE TITLE
Regex improvements

### ISSUE THREAD

**Issue by ghost** [prestodb/presto#3859]
We are creating this issue in order to explore and find an alternative to the current regular expression library used by the regexp_ functions. It is intended to overcome the computing overhead when worst case backtracking is involved. Other regular expression libraries such as RE2 has attempted to avoid the slowdown present in the backtracking based regex libraries.

For this purpose, we have explored RE2J as a starting point for RE2 based regular expression library. Our early tests are mostly regarding the feature completeness of RE2J and the performance difference between regexp_ functions  with RE2J and regexp_ functions with JONI.

**1. Feature comparison**

We used Java Pattern class as the basis for feature comparison for syntax supported by RE2J. There are few features in Pattern class that we haven't tested/verified yet (eg. unicode, POSIX character classes). Below is the list of features supported by Pattern class and RE2J support. 

Regular expression feature | RE2J support | Pattern |  Matching text | Non matching text	
------------------- | --- | --- | --- | ---
**Characters**||||	
x     The character x | Y |	a |	a | bcdefghijklmnopqrstuvwxyz
**Character classes** ||||
[abc]     a, b, or c (simple class) |	Y |	[abc] |	ababab |	defg
[^abc]     Any character except a, b, or c (negation) | Y |   [^abc] | def | abc
[a-zA-Z]     a through z or A through Z, inclusive (range) | Y |	[a-zA-Z] |	abzABZ | 90876
[0-9]	  | Y |  [0-9] |	123456789 |	abcdefghijk
[^0-9] | Y |  [^0-9] |  123.456.789 | 123456789
**Predefined character classes** ||||	
.     Any character (may or may not match line terminators) |	Y | . | 123456789 |
\d     A digit: [0-9] | Y | \d | 908 |  abcdefghijk
\D     A non-digit: [^0-9] |	Y	|\D	|ababab	|85974
\s     A whitespace character: [ \t\n\x0B\f\r]	|Y	|\s	|a word is 4 chars	|awordis4chars
\S     A non-whitespace character: [^\s]	|Y	|\S	|awordis4chars	
\w     A word character: [a-zA-Z_0-9]	|Y	|\w	|these_words_ match	|?[]\#$% $%^ ()
\W     A non-word character: [^\w]	|Y	|\W	|?[]\#$% $%^ ()	|these_words_do_not_match
**Boundary matches** ||||
^     The beginning of a line	|Y	|^Rain	|Raining is the weather today|	Is it Raining today
$     The end of a line	|Y	|rain$	|The weather today is rain|	The rain weather today is
\b     A word boundary	|Y	|\brain\b	|The rain weather today is	|The raining weather today is
\B     A non-word boundary	|Y	|\Brain	|The rain weather today is	|The rain weather today is
\A     The beginning of the input	|Y	|\ARaining	|Raining is the weather today	|The weather is today.(newline) Raining is the weather tomorrow
**Greedy quantifiers**	||||	
X?     X, once or not at all | Y |	a?b	| abcdefg	
X*     X, zero or more times	|Y	|(ab)*	|bcdefgh	
X+     X, one or more times	|Y	|a+	|aaabcdefg	|hijklmn
X{n}     X, exactly n times|	Y	|a{4}	|aaaabcdefg	|aaabcdefg
X{n,}     X, at least n times	|Y	|a{4,}	|aaaaabcdefg	|aaabcdefg
X{n,m}     X, at least n but not more than m times	|Y	|a{4,5}	|aaaaabcefg	|aaaaaabcefg
**Logical operators**	||||	
XY     X followed by Y	|Y	|ab	|abcdefgh	|acbdefgh
X\|Y     Either X or Y	|Y	|a\|b	|a	|z

Java Pattern supports perl style syntax for named capturing group ((?<name>X)     X, as a named-capturing group), whereas RE2 supports python style syntax for named capturing groups ((?P<name>X)).

Command used to test the features: 
`./presto-cli --server localhost:8080 --catalog jmx --schema jmx --execute  "select regexp_like('abcdefghijklmnopqrstuvwxyz', 'a')"`

**2. Time comparison**

Our time comparison shows slowdown for RE2J as expected when compared to JONI, but it does not drastically slow down as JONI does (some cases JONI takes longer than 30 hours). As RE2J lacks the faster DFA based engine of RE2, once DFA engine is implemented, we expect the performance to be better than it is currently. 
 * Our testbed and dataset includes 11 nodes (24 HT threads, 24GB RAM, ~2TB disk space) and datasets size upto 132GB (770MB ORC compressed size). 
 * The datasets contain single column hive tables and are of two types : **A** = row length of 10 and 10 billion rows, and **B** = row length of 65K and 1538461 rows. 
 * The regex patterns tested were mainly Haozun's patterns.
 * Dataset was custom generated. 
 * Time in the table below is in seconds.  

Table | Pattern | Matches | JONI | RE2J
--- | --- |  --- | --- | ---
A | [a-z]\* | 10bill | 117 | 298
B | [b-z]\*a | 1538461 | 66 | 175
B | [a-z]\*(hg_[a-z_]+\_tag\|auto_[a-z]+\_tag) | 1538461 | 78 | 220
A | [a-z]\*(hg_[a-z_]+\_tag\|auto_[a-z]+\_tag)[a-z]\* | 10bill | 138  | 658
B | [a-z]\*(rep_ad_\|rep_)((ad_)[a-z]+)  | 1538461 | 70 |  248
A | [a-z]\*(rep_ad_\|rep_)((ad_)[a-z]+)[a-z]\*  |  10bill  |  170 | 490
B | [a-z]\*://(?:[wW]{3}\\.)?([^:/]\*)  |  1538461 |	63 |	221
A | [a-z]\*://(?:[wW]{3}\\.)?([^:/]\*)[a-z]\*  |  10bill	 |  122  | 496
B | [a-z]\*(\\w+ )?\\w+(\\.\\w+)+( \\w+)? |  1538461 |  57 |	206
A | (\\w+ )?\\w+(\\.\\w+)+( \\w+)? |  10bill | 166 | 570
||||
A | [g-z]\* |  10bill  | 163 |  565
B | [c-z]\*b |  1538461 | 8 | 13
B | [a-z]\*(no_[a-z_]+\_tnz\|aupt_[a-z]+\_ijk) |  1156991 | **109260(~30hrs)** |	1090
A | [a-z]\*(no_[a-z_]+\_tnz\|aupt_[a-z]+\_ijk)[a-z]\* | 0 |  2460 | 1578
B | [a-z]\*(not\_pq_\|rlm_)((ak_)[a-z]+)  | 0 |  **>35 hours** | 	1375
A | [a-z]\*(not_pq_\|rlm_)((ak_)[a-z]+)[a-z]\* | 0  | 1907  | 1320
B | [a-z]\*://(?:[mM]{3}\\.)?([^:/]\*) | 1538461  |  151 | 378
A  | [a-z]\*://(?:[mM]{3}\\.)?([^:/]\*)[a-z]\*  |  10bill | 343 | 1354
||||
A | [a-z]\*6 |  0 |   141 | 820
B | [b-z]*6 | 0 |  39 | 	558
||||
B | (.+)*p | 1538461 | **>24 hrs**  | 472

Time was obtained by running regexp_.. functions as: 
`time ./presto-cli --server master:8090 --catalog hive --session regex="JONI" --execute "select count(regexp_like(value, '[a-z]*6')) from regex.A"`
`time ./presto-cli --server master:8090 --catalog hive --session regex="RE2J" --execute "select count(regexp_like(value, '[a-z]*6')) from regex.A"`

To obtain the matched count: 
`./presto-cli --server master:8090 --catalog hive --session regex="JONI" --execute "select count(*) from regex.simple_short_10000000000 where regexp_like(value, '[a-z]*6')=true;` 

**3. Changes required to Presto and RE2J**

We have created a prototype of dual mode of regexp_ .. functions based on the value of SESSION variable. The code changes will require review (particularly the SESSION variable setting implementation).

The major changes to Presto are:
* Addition of a new class GenericRegexpPattern that switches between RE2J and JONI based on the value of a SESSION variable called "regex"
*  ConnectorSession that can be used to access value of "regex" SESSION variable. (The "regex" SESSION variable need to be declared in other parts of presto ?)
* The original functions in RegexFunctions now only redirect calls to GenericRegexpPattern object, where each regexp_ function operation is performed by JONI or RE2J.

Our tests with RE2J in presto showed a thread contention in part where RE2J attempts to share regex matching objects (Machine.class) between threads. As Presto creates a large number of threads (in our machine: 32 x 4 = 128), the contention slowed down the RE2J matching. Therefore, we removed the caching of Machine objects.

The major change to RE2J is:
* Removal of Machine caching to avoid thread contention in Presto node.

Please provide your comments and suggestions.

**Comment by cberner** [comment]
This all sounds great! My only feedback is that I think it would be better to split the regexp_* functions into two sets of functions (maybe regexp_* and extended_regexp_*), rather than toggle the library via a session property.

**Comment by martint** [comment]
@cberner, no, we don't want users to have rewrite their queries in order to choose one implementation over the other. The idea with the session property is that we can turn it on gradually for testing. Once we're satisfied with the new implementation, we remove the property/config/old regex implementation.

**Comment by kkc00** [comment]
Thanks @cberner and @martint for the comments. Our use of SESSION variable will definitely require review. We will put up the code changes for review soon in coming days. In the meantime, we will update the issue post above with performance numbers and other details. Also, if you find anything we might need to include in the above issue post, please let us know.

**Comment by kkc00** [comment]
I have updated the above issue post (Section 2 - Time comparison) with the test numbers that compare performance of JONI+presto and RE2J+presto(includes the above mentioned change to RE2J). Generally, RE2J is slower than JONI, but RE2J does not take hours to process any pattern, whereas there are multiple cases where JONI slows down by a lot and take more than 30 hours. The slowdown of RE2J in other cases is expected as it currently only uses NFA matching engine. Once there is support for DFA and other faster engines of RE2, the performance  should improve. 

Please let us know your comments and suggestions.

**Comment by rschlussel** [comment]
Fixed by https://github.com/prestodb/presto/pull/5319
