### ISSUE TITLE
PageTooLargeException at Pages fetch

### ISSUE THREAD

**Issue by miniway** [prestodb/presto#3861]
I encountered PageTooLargeException with a simple query like `select * from tab` having hundreds of `bigint` columns. 

`PartitionBuffer.getPages` returns from queued pages to the max size. But the size calculation is based on the Page's memory bytes not from encode bytes.

A quick solution is considering pages encoding margin and making `sink.max-buffer-size` a bit smaller than `exchange.http-client.max-content-length`. Or using applying the margin `long maxBytes = maxSize.toBytes() * 0.9`

Otherwise it needs to calculate encoded pages size more accurately. I've built and tested this idea,

https://github.com/miniway/presto/commit/d93e4cc1e2b2d5492eb78187cb17ca0f82904fd0#diff-40bc792c679d741860824ecb5a6b2f94L96

**Comment by electrum** [comment]
We've started seeing this frequently, too, and will look at this soon.

**Comment by hikoz** [comment]
It occurs since v0.123.
Only with ORC.
It's hardly occur if you append simple conditions like "where id is not null".

**Comment by miniway** [comment]
Closing as there's several options to resolve it
