### ISSUE TITLE
Facing build issue for presto-hive on ppc64 little endian 

### ISSUE THREAD

**Issue by gundun** [prestodb/presto#3862]
Hi ,

I am trying to build presto from source using release 0.123 on ppc64 little endian architecture. 
I am facing below issue while building presto-hive:

[ERROR] Caused by: java.lang.ExceptionInInitializerError
[ERROR] at com.facebook.presto.hive.HdfsEnvironment$$FastClassByGuice$$a9f55374.newInstance(<generated>)
[ERROR] at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
[ERROR] at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)
[ERROR] at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:108)
[ERROR] at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
[ERROR] at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:269)
[ERROR] at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
[ERROR] at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1066)
[ERROR] at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
[ERROR] at com.google.inject.Scopes$1$1.get(Scopes.java:65)
[ERROR] at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
[ERROR] at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
[ERROR] at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
[ERROR] at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:107)
[ERROR] at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
[ERROR] at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:269)
[ERROR] at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
[ERROR] at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
[ERROR] at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1066)
[ERROR] at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
[ERROR] at com.google.inject.Scopes$1$1.get(Scopes.java:65)
[ERROR] at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
[ERROR] at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
[ERROR] at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
[ERROR] at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1059)
[ERROR] at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
[ERROR] at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
[ERROR] at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
[ERROR] at com.google.inject.Guice.createInjector(Guice.java:96)
[ERROR] at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:242)
[ERROR] at com.facebook.presto.hive.HiveConnectorFactory.create(HiveConnectorFactory.java:119)
[ERROR] at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:155)
[ERROR] at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:141)
[ERROR] at com.facebook.presto.server.testing.TestingPrestoServer.createCatalog(TestingPrestoServer.java:231)
[ERROR] at com.facebook.presto.tests.DistributedQueryRunner.createCatalog(DistributedQueryRunner.java:219)
[ERROR] at com.facebook.presto.hive.HiveQueryRunner.createQueryRunner(HiveQueryRunner.java:84)
[ERROR] at com.facebook.presto.hive.HiveQueryRunner.createQueryRunner(HiveQueryRunner.java:52)
[ERROR] at com.facebook.presto.hive.TestHiveIntegrationSmokeTest.<init>(TestHiveIntegrationSmokeTest.java:61)
[ERROR] ... 34 more
[ERROR] Caused by: java.lang.RuntimeException: failed to load Hadoop native library
[ERROR] at com.facebook.presto.hadoop.HadoopNative.requireHadoopNative(HadoopNative.java:58)
[ERROR] at com.facebook.presto.hive.HdfsEnvironment.<clinit>(HdfsEnvironment.java:31)
[ERROR] ... 72 more
[ERROR] Caused by: java.lang.RuntimeException: library not found: /nativelib/Linux-ppc64/libhadoop.so
[ERROR] at com.facebook.presto.hadoop.HadoopNative.loadLibrary(HadoopNative.java:88)
[ERROR] at com.facebook.presto.hadoop.HadoopNative.requireHadoopNative(HadoopNative.java:47)
[ERROR] ... 73 more

I have run the same test case on x86_64 platform and it was there was no issues on that architecture.
Can you please provide pointers on resolving the above mentioned issue.

Thanks & Regards,
Naresh. G

**Comment by electrum** [comment]
We don't have native libraries for that architecture and thus cannot support it. Are there any publicly available ppc64 machines (such as a cloud provider) that we could use to build the native libraries?

**Comment by borcean** [comment]
@electrum The OSL would be happy to provide a `ppc64le` build machine. We are currently waiting on approval from IBM.

**Comment by gundun** [comment]
thanks electrum and borcean for the info, we will get back to you soon.

**Comment by electrum** [comment]
What Linux distribution are you using, and what JVM and version are you using (and where did you get it)?

**Comment by gerrith3** [comment]
Hi IBM now has a program using its Power Development Program to allow any open source developer to use our ppc64le based cloud. There is a little bit of overhead but there is no cost for open source development.  (BTW, this resource is in addition to that provided by OSL - using either is an option).

To start, register for the service here: https://www-304.ibm.com/partnerworld/wps/ent/pdp/web/MyProgramAccess?registerosd

and then press the "Please register me as an Open Source Developer" link.

Identify yourself as an Open Source developer and your project, then include the link to any defects you want to test to get your account open (e.g. this defect). That should give you the ongoing ability to access VMs for open source development purposes.
