### ISSUE TITLE
Correctly handle modification operations for Hive external tables

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#3893]
My understanding is that Hive external tables are basically read-only views of externally managed data. Creating or dropping an external table or partition merely modifies the metadata in the Hive metastore. Given this assumption, it seems that INSERT or DELETE operations should not be allowed for external tables.

**Comment by nezihyigitbasi** [comment]
@electrum, do we still want this behaviour? Hive supports inserting/deleting to/from external tables, so they are not totally read-only in that sense. If we still want this I will be happy to work on it.

**Comment by electrum** [comment]
@nezihyigitbasi I think Hive's behavior here is a bug. We still want this behavior.

**Comment by nezihyigitbasi** [comment]
@electrum How do we want to keep track of the type of the table (managed, external, etc.)? Add a new property to `HiveTableProperties`?

**Comment by nezihyigitbasi** [comment]
I guess an easier way is to put checks in the `HiveMetadata::beginInsert`/`HiveMetadata::beginDelete` methods.

**Comment by jcap** [comment]
@electrum curious about the bug comment. I don't see much in the way of Hive indicating this is a problem. We were surprised to see this addition to the change logs.

**Comment by electrum** [comment]
@jcap please the the discussion here: https://github.com/prestodb/presto/pull/5416
