### ISSUE TITLE
Intervals "millisecond", "week" and "quarter" not supported

### ISSUE THREAD

**Issue by rafalpas** [prestodb/presto#3908]
According to documentation https://prestodb.io/docs/current/functions/datetime.html following units are supported in interval functions: 
millisecond, second , minute, hour, day, week, month, quarter, year.

But only a subset of them is supported by the 'interval' operator: 
IntervalLiteral.java: YEAR, MONTH, DAY, HOUR, MINUTE, SECOND

This means that millisecond, week and quarter are missing. Consider adding support for these missing units in the interval operator.

**Comment by yangyangyyy** [comment]
I'll be working on this one.

**Comment by haozhun** [comment]
* We support YEAR, MONTH, DAY, HOUR, MINUTE, SECOND for `Literal`s. We didn't document what we support.
* We document and support the above 6 plus MILLISECOND, WEEK, and QUARTER for `date_add`, `date_diff`, `date_trunc`, and `extract`.

@dain I suppose we don't intend to support MILLISECOND, WEEK, and QUARTER. But we should improve our documentation?

**Comment by MichaelJAndy** [comment]
+1 I don't think the documentation is specific enough to say that these values whilst using the INTERVAL function specifically isn't supported.  
We're currently running on 0.147 and looking at the docs it seems that `week` is supported.

**Comment by sanatanmishra** [comment]
+1

Are there any updates on this issue?

**Comment by ashrodan** [comment]
+1

**Comment by shixuan-fan** [comment]
AFAIK there is no update yet, and I think it might be a good beginner task if anyone is interested.
