### ISSUE TITLE
Presto CLI doesnot throw explicit error if server is not accessible

### ISSUE THREAD

**Issue by ebuildy** [prestodb/presto#3917]
Running Presto CLI:

```
./presto --server toto:8081
```

Where toto doesnt resolve, when I run a Presto query:

```
presto> show catalogs;
Error running command: null
```

Instead of have an explicit message saying "Presto API is not accessible!"

(could save time for people like me who make typos such as loalhost ^^)

**Comment by raghavsethi** [comment]
Closed for now, because the fix is pretty ugly. If this comes up more frequently we can re-open.

**Comment by electrum** [comment]
We should keep this open even if there's not a simple fix.

**Comment by cawallin** [comment]
This will be fixed by https://github.com/prestodb/presto/pull/5445, when that gets in. (cc @fiedukow)
