### ISSUE TITLE
Use implicit coercions in INSERT into SELECT clause.

### ISSUE THREAD

**Issue by losipiuk** [prestodb/presto#3922]
Currently presto requires that: 
 * target table columns 
 * columns returned by query, to be inserted

have exactly same type. No implicit coercions are used even if they are defined.

**Comment by rschlussel** [comment]
I'm looking into this.

**Comment by martint** [comment]
This has already ven fixed: https://github.com/prestodb/presto/pull/4998

**Comment by rschlussel** [comment]
didn't realize.  Closing this then.
