### ISSUE TITLE
Support setting comments on tables and columns

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#3961]
Unfortunately, there is no standard syntax, so we should look at what PostgreSQL and Oracle do here. We should allow it for both creating tables and adding columns, plus a way to update existing objects.

**Comment by electrum** [comment]
Support for comments on columns: https://github.com/facebook/presto/pull/4296

**Comment by cpcloud** [comment]
Both oracle and postgres have `COMMENT ON COLUMN <relation>.<field> IS 'The comment'`.

**Comment by cpcloud** [comment]
There's no way to add these at the `CREATE` stage and there's nothing in the SQL standard that specifies what the syntax should be.

**Comment by electrum** [comment]
This is done for column comments but not table comments.

**Comment by yuananf** [comment]
I can take this.

**Comment by rongrong** [comment]
@yuananf We need to support table comment quite urgently so I will work on it. If you could help on updating comments that would be great!

**Comment by MichaelChirico** [comment]
+1 for this :)
