### ISSUE TITLE
Large number of ATNConfig objects in heap

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#3989]
We've seen heap dumps with 22+ million ATNConfig objects, which appeared to be stored in Antlr's cache. We should investigate whether this is a bug, or an issue with the complexity of our grammar

**Comment by miniway** [comment]
http://stackoverflow.com/questions/28017135/why-antlr4-parsers-accumulates-atnconfig-objects 
We might have to call `Recognizer.clearDFA()` periodically
4th comment seems to refer https://groups.google.com/forum/#!topic/antlr-discussion/8Yu-Tdh4gq4

**Comment by miniway** [comment]
I try calling clearDFA as a workaround https://github.com/miniway/presto/commit/44b9ac34196db6d01e99ecc0fbad33f92ba1eb40
