### ISSUE TITLE
HBase Support

### ISSUE THREAD

**Issue by rawls238** [prestodb/presto#3992]
I've noticed a few tickets around HBase support but don't see anything that indicates that it is currently supported. If one doesn't exist, I would be happy to start working on one but wanted to see if I was missing something.

**Comment by cawallin** [comment]
There currently isn't an HBase connector.  At Teradata, @akshatnair did a prototype of connecting to HBase via a JDBC connection to Apache Phoenix, but it only had a single connection to HBase so it was pretty slow. The tricky part of making a performant HBase connector will be figuring out how to handle parallel connections to HBase. Let us know how it goes, and we're happy to help if you need some pointers!

**Comment by rawls238** [comment]
awesome thanks!

**Comment by spragues-trulia** [comment]
Christina alluded to this link in the presto-users google group today so figured i'd have look.  Yeah, I think there's  interest but hard to say who's got the time to actually do it.  Damien Carol as well commented on the mail thread perhaps he has a vested interest too.
Sadly, i'm not a java/scala guy so there's not much i can physically do to help with coding but i can sure as heck help with testing!

**Comment by darionyaphet** [comment]
Apache Phoenix could execute SQL by it's JDBC implement . Maybe can use JDBC connect to access HBase . But sometimes Phoenix is very slow and join operation will make some trouble .

**Comment by BigDataDaddy** [comment]
Is there any progess or direction on this issue or an HBase connector in general?

**Comment by petroav** [comment]
It's not on the [roadmap wiki](https://github.com/prestodb/presto/wiki/Roadmap) and I haven't seen any mentions of such work on the mailing list so I don't think anyone is working on such a connector at the moment.

**Comment by raghuvineel** [comment]
@akshatnair @cawallin 

Hi, 
I am having a similar requirement of connecting presto to hbase using phoenix. But I am having hard time because of dependency issues. I could somehow build the source provided in guthub for presto-phoenix plugin, but I am facing missing classes etc during making connection. Could you please provide some pointers on it? Any help would be great!

regards,
Vineel.

**Comment by cawallin** [comment]
Vineel -- what branch are you using? @akshatnair put together a prototype about a year ago, but Presto has changed so much since then that it would require a lot of effort to rebase it on the current Presto master.

**Comment by raghuvineel** [comment]
Hi Christina,

Thanks for the response. I somehow managed to connect the same. There were so many dependency problems I had to resolve. And in my environment HBase is based on 1.1.2 and presto 0.133. Presto is using guava-18.0. HBase is trying to access a class from guava, Stopwatch() which became protected from guava-13.0. Hence it was failing. HBase 1.3.0 has no such code, but HBase 1.3.0 jars are not available in maven. Hence I rebuilt guava-18.0 by making the protected constructor to public and used the same.

Now I am able to successfully connect to Hbase from presto using phoenix plugin. May be I will upload my pom.xml with all dependencies here, but again guava-18.0 has to be somewhat customized to make it work.

Presto-0.133
HBase 1.1.2
Zookeeper 3.4.6

Thanks and regards,
Vineel.

**Comment by Vialentino** [comment]
Hi Vineel, I'm approaching the same problem as yours: do you have some pronto code to use?

**Comment by electrum** [comment]
The Presto SPI doesn't require Guava. Plugins have a separate class loader. It was designed this way for exactly this sort of problem, where connectors need incompatible versions of libraries than the Presto core.

**Comment by raghuvineel** [comment]
@Vialentino 

HI. Sorry for the delayed response. I had downloaded the source code from github and built using maven. All you need is configure pom.xml properly with all dependencies. Below is the pom.xml file I have used. You can download the source code for presto-phoenix plugin from this link. https://github.com/PayWithMyBank/presto-phoenix.

Just replace the pom.xml with the one below and build using maven (below command)

**_mvn clean install -Dcheckstyle.skip=true -DskipTests=true -Dair.check.skip-enforcer=ture -Dair.check.skip-duplicate-finder=true_**

Once you are done with the build, you have the required jar files inside folder **target**. You can copy this whole folder into presto/plugins and you should be able to connect from presto to Hbase.

Before trying that, you have to replace guava-18.0 in the plugin with customized one. That is, you have to build guava-18.0 similar like above, by downloading source from github and changing the constructor of the class StopWatch as public.  This is the hack we tried to make it work for us. May be some latest versions of Hbase doesnt require this class at all. If you want, I have customized guava-18.0.jar already built.

  <?xml version="1.0" ?> 
- <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion> 
- <parent>
  <groupId>com.facebook.presto</groupId> 
  <artifactId>presto-root</artifactId> 
  <version>0.135</version> 
  </parent>
  <artifactId>presto-phoenix</artifactId> 
  <description>Presto - Apache Phoenix Connector</description> 
  <packaging>presto-plugin</packaging> 
- <dependencies>
- <dependency>
  <groupId>com.google.protobuf</groupId> 
  <artifactId>protobuf-java</artifactId> 
  <version>2.5.0</version> 
  <scope>runtime</scope> 
  </dependency>
-  
- <dependency>
  <groupId>org.antlr</groupId> 
  <artifactId>antlr</artifactId> 
  <version>3.1.1</version> 
  <scope>runtime</scope> 
  </dependency>
- <dependency>
  <groupId>commons-configuration</groupId> 
  <artifactId>commons-configuration</artifactId> 
  <version>1.6</version> 
  <scope>runtime</scope> 
  </dependency>
- <dependency>
  <groupId>commons-lang</groupId> 
  <artifactId>commons-lang</artifactId> 
  <version>2.6</version> 
  <scope>runtime</scope> 
  </dependency>
- <dependency>
  <groupId>commons-beanutils</groupId> 
  <artifactId>commons-beanutils</artifactId> 
  <version>1.7.0</version> 
  <scope>runtime</scope> 
  </dependency>
- <dependency>
  <groupId>commons-collections</groupId> 
  <artifactId>commons-collections</artifactId> 
  <version>3.2.1</version> 
  <scope>runtime</scope> 
  </dependency>
- <dependency>
  <groupId>commons-digester</groupId> 
  <artifactId>commons-digester</artifactId> 
  <version>1.8</version> 
  <scope>runtime</scope> 
  </dependency>
- <dependency>
  <groupId>commons-logging</groupId> 
  <artifactId>commons-logging</artifactId> 
  <version>1.2</version> 
  <scope>runtime</scope> 
  </dependency>
-  
- <dependency>
  <groupId>junit</groupId> 
  <artifactId>junit</artifactId> 
  <version>4.12</version> 
  <scope>runtime</scope> 
  </dependency>
-  
- <dependency>
  <groupId>org.apache.hbase</groupId> 
  <artifactId>hbase-annotations</artifactId> 
  <version>1.1.2</version> 
  <scope>runtime</scope> 
  </dependency>
-  
- <dependency>
  <groupId>org.apache.hbase</groupId> 
  <artifactId>hbase-protocol</artifactId> 
  <version>1.1.2</version> 
  <scope>runtime</scope> 
  </dependency>
-  
- <dependency>
  <groupId>org.apache.httpcomponents</groupId> 
  <artifactId>httpclient</artifactId> 
  <version>4.2.5</version> 
  <scope>runtime</scope> 
  </dependency>
-  
- <dependency>
  <groupId>org.apache.httpcomponents</groupId> 
  <artifactId>httpcore</artifactId> 
  <version>4.2.4</version> 
  <scope>runtime</scope> 
  </dependency>
-  
- <dependency>
  <groupId>org.apache.zookeeper</groupId> 
  <artifactId>zookeeper</artifactId> 
  <version>3.4.6</version> 
  <scope>runtime</scope> 
  </dependency>
-  
- <dependency>
  <groupId>org.codehaus.jackson</groupId> 
  <artifactId>jackson-jaxrs</artifactId> 
  <version>1.9.13</version> 
  <scope>runtime</scope> 
  </dependency>
-  
- <dependency>
  <groupId>org.slf4j</groupId> 
  <artifactId>slf4j-log4j12</artifactId> 
  <version>1.7.5</version> 
  <scope>runtime</scope> 
  </dependency>
-  
- <dependency>
  <groupId>commons-io</groupId> 
  <artifactId>commons-io</artifactId> 
  <version>2.4</version> 
  <scope>runtime</scope> 
  </dependency>
- <dependency>
  <groupId>com.facebook.presto</groupId> 
  <artifactId>presto-base-jdbc</artifactId> 
  </dependency>
- <dependency>
  <groupId>io.airlift</groupId> 
  <artifactId>configuration</artifactId> 
  </dependency>
- <dependency>
  <groupId>com.google.guava</groupId> 
  <artifactId>guava</artifactId> 
  </dependency>
- <dependency>
  <groupId>com.google.inject</groupId> 
  <artifactId>guice</artifactId> 
  </dependency>
- <dependency>
  <groupId>org.apache.hbase</groupId> 
  <artifactId>hbase-server</artifactId> 
  <version>1.1.2</version> 
  <scope>runtime</scope> 
- <exclusions>
- <exclusion>
  <groupId>com.yammer.metrics</groupId> 
  <artifactId>metrics-core</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>commons-cli</groupId> 
  <artifactId>commons-cli</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>commons-configuration2</groupId> 
  <artifactId>commons-configuration2</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>com.github.stephenc.high-scale-lib</groupId> 
  <artifactId>high-scale-lib</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>commons-codec</groupId> 
  <artifactId>commons-codec</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>commons-httpclient</groupId> 
  <artifactId>commons-httpclient</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>commons-io</groupId> 
  <artifactId>commons-io</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>commons-lang</groupId> 
  <artifactId>commons-lang</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>commons-logging</groupId> 
  <artifactId>commons-logging</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>log4j</groupId> 
  <artifactId>log4j</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>org.apache.avro</groupId> 
  <artifactId>avro</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>org.apache.avro</groupId> 
  <artifactId>avro-ipc</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>org.apache.zookeeper</groupId> 
  <artifactId>zookeeper</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>org.apache.thrift</groupId> 
  <artifactId>libthrift</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>org.jruby</groupId> 
  <artifactId>jruby-complete</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>org.mortbay.jetty</groupId> 
  <artifactId>jetty</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>org.mortbay.jetty</groupId> 
  <artifactId>jetty-util</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>org.mortbay.jetty</groupId> 
  <artifactId>jsp-2.1</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>org.mortbay.jetty</groupId> 
  <artifactId>jsp-api-2.1</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>org.mortbay.jetty</groupId> 
  <artifactId>servlet-api-2.5</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>org.codehaus.jackson</groupId> 
  <artifactId>jackson-core-asl</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>org.codehaus.jackson</groupId> 
  <artifactId>jackson-mapper-asl</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>org.codehaus.jackson</groupId> 
  <artifactId>jackson-jaxrs</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>org.codehaus.jackson</groupId> 
  <artifactId>jackson-xc</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>org.slf4j</groupId> 
  <artifactId>slf4j-api</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>org.slf4j</groupId> 
  <artifactId>slf4j-log4j12</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>stax</groupId> 
  <artifactId>stax-api</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>tomcat</groupId> 
  <artifactId>jasper-compiler</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>tomcat</groupId> 
  <artifactId>jasper-runtime</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>org.jamon</groupId> 
  <artifactId>jamon-runtime</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>com.google.protobuf</groupId> 
  <artifactId>protobuf-java</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>com.google.code.findbugs</groupId> 
  <artifactId>jsr305</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>com.sun.jersey</groupId> 
  <artifactId>jersey-core</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>com.sun.jersey</groupId> 
  <artifactId>jersey-json</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>com.sun.jersey</groupId> 
  <artifactId>jersey-server</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>javax.xml.bind</groupId> 
  <artifactId>jaxb-api</artifactId> 
  </exclusion>
  </exclusions>
  </dependency>
- <dependency>
  <groupId>org.apache.phoenix</groupId> 
  <artifactId>phoenix-core</artifactId> 
  <version>4.4.0-HBase-1.1</version> 
- <exclusions>
- <exclusion>
  <groupId>org.apache.phoenix</groupId> 
  <artifactId>phoenix-hadoop-compat</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>org.antlr</groupId> 
  <artifactId>antlr</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>org.antlr</groupId> 
  <artifactId>antlr-runtime</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>jline</groupId> 
  <artifactId>jline</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>org.codehaus.jackson</groupId> 
  <artifactId>jackson-core-asl</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>org.codehaus.jackson</groupId> 
  <artifactId>jackson-mapper-asl</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>sqlline</groupId> 
  <artifactId>sqlline</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>net.sourceforge.findbugs</groupId> 
  <artifactId>annotations</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>org.apache.commons</groupId> 
  <artifactId>commons-csv</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>org.iq80.snappy</groupId> 
  <artifactId>snappy</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>com.google.code.findbugs</groupId> 
  <artifactId>jsr305</artifactId> 
  </exclusion>
- <exclusion>
  <groupId>org.apache.hadoop</groupId> 
  <artifactId>hadoop-core</artifactId> 
  </exclusion>
  </exclusions>
  </dependency>
-  
- <dependency>
  <groupId>com.facebook.presto</groupId> 
  <artifactId>presto-spi</artifactId> 
  <scope>provided</scope> 
  </dependency>
- <dependency>
  <groupId>io.airlift</groupId> 
  <artifactId>slice</artifactId> 
  <scope>provided</scope> 
  </dependency>
- <dependency>
  <groupId>javax.inject</groupId> 
  <artifactId>javax.inject</artifactId> 
  <scope>provided</scope> 
  </dependency>
- <dependency>
  <groupId>com.fasterxml.jackson.core</groupId> 
  <artifactId>jackson-annotations</artifactId> 
  <scope>provided</scope> 
  </dependency>
- <dependency>
  <groupId>com.fasterxml.jackson.core</groupId> 
  <artifactId>jackson-core</artifactId> 
  <scope>provided</scope> 
  </dependency>
- <dependency>
  <groupId>com.fasterxml.jackson.core</groupId> 
  <artifactId>jackson-databind</artifactId> 
  <scope>provided</scope> 
  </dependency>
  </dependencies>
  </project>

**Comment by damiencarol** [comment]
https://github.com/prestodb/presto/issues/6010

**Comment by damiencarol** [comment]
I plan to track my connector initiative here https://github.com/prestodb/presto/issues/6010

**Comment by vinceprignano** [comment]
Any updates here?

**Comment by danielhaviv** [comment]
Anyone tried to use HBaseStorageHandler?
