### ISSUE TITLE
Error is thrown while building presto-docs

### ISSUE THREAD

**Issue by supareek** [prestodb/presto#4002]
I get the following error while building the project. Everything else gets built except the docs project.
Is this related to some kind of proxy configuration?

[INFO] presto-docs ........................................ FAILURE [04:53 min]
[INFO] presto-verifier .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 07:51 min
[INFO] Finished at: 2015-11-20T11:25:21+05:30
[INFO] Final Memory: 313M/1698M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.4:single (docs) on project presto-docs: Execution docs of goal org.apache.maven.plugins:maven-assembly-plugin:2.4:single failed: Plugin org.apache.maven.plugins:maven-assembly-plugin:2.4 or one of its dependencies could not be resolved: Failed to collect dependencies at org.apache.maven.plugins:maven-assembly-plugin:jar:2.4 -> org.apache.maven.shared:file-management:jar:1.1: Failed to read artifact descriptor for org.apache.maven.shared:file-management:jar:1.1: Could not transfer artifact org.apache.maven.shared:file-management:pom:1.1 from/to central (https://repo.maven.apache.org/maven2): Connection reset -> [Help 1]

**Comment by petroav** [comment]
Hmm, strange, I just did `mvn clean install -pl presto-docs` and it worked. What do you get from `mvn -v`? Can you run `mvn` in verbose mode so we can get more info?
