### ISSUE TITLE
when does PrestoPreparedStatement support executeQuery, not just throw NotImplementedException("PreparedStatement", "executeQuery")

### ISSUE THREAD

**Issue by oscarLM** [prestodb/presto#4003]

**Comment by kokosing** [comment]
I suppose that this is handled by https://github.com/facebook/presto/pull/3097 pull request. Hope it well get in soon.

**Comment by cawallin** [comment]
https://github.com/prestodb/presto/pull/3097 was merged, closing this ticket. If you still have issues, feel free to re-open.
