### ISSUE TITLE
presto-cli (batch mode) exits with '0' when query fails

### ISSUE THREAD

**Issue by kokosing** [prestodb/presto#4016]
Typically when db cli tool fails to execute a query proper exit status is returned. Presto returns always 0.

See exit status section in http://www.postgresql.org/docs/9.3/static/app-psql.html

```
$ cat f
select 1/0;
$ presto-cli --server localhost:8080 -f f
Query 20151123_135624_00623_5hmgt failed: / by zero

$ echo $?
0
$ cat f | presto-cli --server localhost:8080
presto> select 1/0;
Query 20151123_135643_00624_5hmgt failed: / by zero

presto> 
$ echo $?
0
```

**Comment by nezihyigitbasi** [comment]
There is a related PR in review #3463

**Comment by kokosing** [comment]
Fixed with https://github.com/prestodb/presto/pull/9227
