### ISSUE TITLE
ORC reader with predicate push down reads too much unnecessary data

### ISSUE THREAD

**Issue by bograd** [prestodb/presto#4064]
The query "select l_linenumber from lineitem where l_shipdate < date '1991-01-01'" reads a lot from disk even though it returns null and profile says it processed nothing:
"  "rawInputDataSize" : "0B",
    "rawInputPositions" : 0,
    "processedInputDataSize" : "0B",
    "processedInputPositions" : 0,
    "outputDataSize" : "9B",
    "outputPositions" : 1
"
I am reading actual data read from /proc/.../io
I sorted on l_shipdate so it should be able to quickly filter out all ORC files and read almost nothing.
However it reads 3GB on this TPC-H SF 100G database.
Lowering orc_max_buffer_size to 1MB reduces this to 1GB which is still a lot. I have about 400 ORC files.

**Comment by bograd** [comment]
After further examination it looks like date predicate pushdown is not working

**Comment by dain** [comment]
How did you verify that date predicate specifically isn't working?  

If you run `explain` on your query you will see the constraints pushed down to the reader.  After that it is up to the ORC reader logic to skip as much as possible.  The best way to do this is to run Presto in an IDE and debug https://github.com/facebook/presto/blob/master/presto-orc/src/main/java/com/facebook/presto/orc/TupleDomainOrcPredicate.java#L52

**Comment by dain** [comment]
If this is still an issue, please reopen with more information.
