### ISSUE TITLE
Column 'table_name' cannot be resolved

### ISSUE THREAD

**Issue by aahaselgrove** [prestodb/presto#4069]
I am trying to execute a left join, but receive the above error. I believe it occurs because I am trying to use a renamed (by the 'as' keyword) aggregate column as part of the condition for the 'on' statement. I have found SQL samples online which can do this (eg. http://www.sqlteam.com/forums/topic.asp?TOPIC_ID=160475), but I seem to be unable to achieve a similar result with presto. Subsituting date_trunc('minute', start_time) produces the same result as if the left join was excluded.

Sample query:

 select 
    date_trunc('minute', start_time) as timestamp,
    count(1) as requests
 from table_name
 left join (
   select a.date
   from (
     select date_add('minute', -(a.a + (10 \* b.a) + (100 \* c.a) + (1000 \* d.a)), date_trunc('day', now())) as date
     from (select 0 as a union all select 1 union all select 2 union all select 3 union all select 4 union all select 5 union all select 6 union all select 7 union all select 8 union all select 9) as a
     cross join (select 0 as a union all select 1 union all select 2 union all select 3 union all select 4 union all select 5 union all select 6 union all select 7 union all select 8 union all select 9) as b
     cross join (select 0 as a union all select 1 union all select 2 union all select 3 union all select 4 union all select 5 union all select 6 union all select 7 union all select 8 union all select 9) as c
     cross join (select 0 as a union all select 1 union all select 2 union all select 3 union all select 4 union all select 5 union all select 6 union all select 7 union all select 8 union all select 9) as d
     cross join (select 0 as a union all select 1 union all select 2 union all select 3 union all select 4 union all select 5 union all select 6 union all select 7 union all select 8 union all select 9) as e
   ) a
   where a.date > date '2015-11-22'
   and a.date < date '2015-11-28'
 ) dates
 on table_name.timestamp = dates.date
 where start_time > date '2015-11-22'
 and start_time < date '2015-11-28'
 group by date_trunc('minute', start_time)
 order by timestamp

**Comment by yuananf** [comment]
```count(1) as requests,```
the ```,```should be removed

**Comment by Dimpl** [comment]
Thanks, have updated accordingly. Doesn't change the issue, I have more columns in the select statement, but removed them as they weren't relevent to the issue.

**Comment by yuananf** [comment]
As far as I can see, the error shows that you are selecting a column named ```table_name```, but this column can not be found in any related table, please check your sql first.

**Comment by Dimpl** [comment]
My understanding is that, for the 'on' clause, you use 'first_table_name'.'column_name' = 'second_table_name'.'column_name' to describe the two columns by which you match up data when performing the join. The table 'table_name' definitely exists, and as you can see from the query, the 'timestamp' column definitely exists too.

**Comment by yuananf** [comment]
I created a table ```table_name``` like yours, and the sample query runs fine.

**Comment by Dimpl** [comment]
I'm working through airpal, but I don't think that should make a difference (?)
