### ISSUE TITLE
PostgreSQL connector 'describe table' reports 'Table has no supported column types' inappropriately

### ISSUE THREAD

**Issue by brian-rickman** [prestodb/presto#4082]
**In psql:**

```
test=> create table test3 (c1 BIGINT, c2 UUID);
CREATE TABLE
test=> insert into test3 values(1, 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11');
INSERT 0 1
```

**In Presto:**

Correct:

```
presto:default> select * from postgresql.public.test3;
 c1
----
  1
(1 row)

Query 20151203_164637_00022_nqyb5, FINISHED, 1 node
Splits: 2 total, 2 done (100.00%)
0:07 [1 rows, 0B] [0 rows/s, 0B/s]
```

Bug:

```
presto:default> describe postgresql.public.test3;

Query 20151203_164658_00024_nqyb5, FAILED, 2 nodes
Splits: 2 total, 0 done (0.00%)
0:06 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20151203_164658_00024_nqyb5 failed: Table has no supported column types: public.test
```

**Comment by akshatnair** [comment]
Is this specific case due to UUID types in column?

**Comment by brian-rickman** [comment]
I think it happens with any type that Presto does not support.  I reproduced it with the 'money' type:

create table test4 (c1 bigint, c2 money);

**Comment by albertocsm** [comment]
AFIK @brian-rickman is correct. if the column type does not fall into this [switch](https://github.com/harunurhan/presto/blob/master/presto-base-jdbc/src/main/java/com/facebook/presto/plugin/jdbc/BaseJdbcClient.java#L420), the column just gets ignored. 
wouldnt it be better to just fall back to varchar in this case and just return the value as string?

at the very least, it would help to do it for the jdbcType returned (by PG) for UUIDs (not sure what that is). 
this could be done in BaseJdbcClient or in PostgreSqlClient if jdbcType is specific to PG

**Comment by cerebrotecnologico** [comment]
I'm interested in this fix. My database uses UUIDs as the keys, so without UUID support in Postgres I can't use Presto (unless I define a view with a CAST).
What is required to get this into the next release asap?

**Comment by albertocsm** [comment]
waiting for PR #4174 to be reviewed & merged...

**Comment by pwistrand** [comment]
Is this moving forward? We have a similar issue with the postgresql interval data type not being supported.

**Comment by albertocsm** [comment]
#4174 that addresses the problem has been reviewed and some changes were suggested.
to be honest, i still haven't found the strength to shave that yak...

**Comment by findepi** [comment]
In the configuration as originally reported `describe` no longer fails, unsupported columns remain ignored.

```
presto> describe postgresql.public.test3;
 Column |  Type  | Extra | Comment
--------+--------+-------+---------
 c1     | bigint |       |
(1 row)
```

what @albertocsm's reported in a comment ...
> this behaviour is even worse if one table in the schema has only unsupported type columns (eg.: all columns are UUIDs). in that case, Presto's current version (0.130) is totally incapable to query or describe any table in the schema.

.. also has been fixed (https://github.com/prestodb/presto/pull/9435)
