### ISSUE TITLE
data from hive table available only after msck repair

### ISSUE THREAD

**Issue by Liorba** [prestodb/presto#4109]
Hello all,
I have a table in hive that points to data in S3.
when I try to query it for new data 
`select * from tbl where date>date'2015-12-01'`
the data is not available for querying, only after I connect to hive and run 
`msck repair table tbl`
the data is available in both hive and and presto
i'm using external metastore and perso v0.125 (emr 4.2.0 distribution)

and my my hive.properties are as follows:

```
hive.s3.connect-timeout=2m
hive.s3.max-backoff-time=10m
hive.s3.max-error-retries=50
hive.metastore-refresh-interval=1m
hive.s3.max-connections=500
hive.s3.max-client-retries=50 
connector.name=hive-hadoop2
hive.s3.socket-timeout=2m
hive.metastore.uri=thrift://ip-10-86-161-119.eu-west-1.compute.internal:9083
hive.metastore-cache-ttl=20m
hive.s3.staging-directory=/tmp/
hive.s3.use-instance-credentials=true`
```

any way to go around that?

**Comment by thanhlv93** [comment]
@Liorba Did you fixed this issue ?

**Comment by findepi** [comment]
This is how Hive works, so this should be the expected behavior. Please also see a newer issue on the same subject https://github.com/prestodb/presto/issues/12025
