### ISSUE TITLE
UDF to shorten and format numbers

### ISSUE THREAD

**Issue by amitna1r** [prestodb/presto#4130]
Could you create a UDF to shorten and format numbers (using suffixes like B - billion, M - million, K - thousand, etc).

Examples of functionality:
1000000 would become 1M
and
123456 would become 123K

It can be done using a CASE statement, but a UDF would be cleaner.

**Comment by yuananf** [comment]
Is this what you want?
http://stackoverflow.com/questions/4753251/how-to-go-about-formatting-1200-to-1-2k-in-java

**Comment by amitna1r** [comment]
:+1: 
 Yes! :)

**Comment by yuananf** [comment]
I'll try this one

**Comment by dain** [comment]
There is code in the CLI to do this https://github.com/facebook/presto/blob/master/presto-cli/src/main/java/com/facebook/presto/cli/FormatUtils.java and in js in the UI https://github.com/facebook/presto/blob/master/presto-main/src/main/resources/webapp/query.html#L414
Hopefully we can keep these implementation aligned.

**Comment by amitna1r** [comment]
@yuananf, any updates on this? This would be super useful

**Comment by yuokada** [comment]
@dain @martint (CC:  @yuananf ) It seems 1 year has passed since the last update, I  want to solve this issue. Can I have a try?

**Comment by amitna1r** [comment]
@yuokada , please go ahead

**Comment by yuokada** [comment]
@electrum Can I implement in either UDF or native function?

**Comment by electrum** [comment]
Presto doesn't have "UDF", only functions,
which can be built into the engine or provided by plugins. This should be built in.

**Comment by yuokada** [comment]
> This should be built in.

Ok, like this?
https://github.com/prestodb/presto/pull/6437

**Comment by yuokada** [comment]
I have some questions.

1. need to support negative value?  
    `formatCount` isn't support negative value. So, this one too.
  https://github.com/prestodb/presto/blob/master/presto-cli/src/main/java/com/facebook/presto/cli/FormatUtils.java
1. need to support Datatype `Decimal`?  
    I thins that this function need not precision.

**Comment by yuokada** [comment]
@electrum Could you review this WIP PR (#6437)?

**Comment by amitna1r** [comment]
Hey guys, any updates on this? 
cc: @yuokada , @electrum, @martint, @dain

**Comment by yuokada** [comment]
I will restart at next week.

**Comment by MichaelChirico** [comment]
@yuokada any luck/progress? 😬

**Comment by yuokada** [comment]
@MichaelChirico Sorry, I send a PR.
https://github.com/prestodb/presto/pull/10419

@dain or @electrum Could you assign a reviewer?

**Comment by MichaelChirico** [comment]
謝る必要ないよ！thank you for your time :)
