### ISSUE TITLE
System catalogue unavailable when only coordinator online

### ISSUE THREAD

**Issue by lloydpick** [prestodb/presto#4132]
If you try and access the system schema tables, when only the coordinator is online you get...

```
Query 20151209_173707_00026_dwqtx failed: No worker nodes available
```

I would perhaps have expected to be at least listed the coordinator rather than an error?

```
SELECT * FROM system.runtime.nodes;
               node_id                |          http_uri           |   node_version    | coordinator | active
--------------------------------------+-----------------------------+-------------------+-------------+--------
  495c6d0b-6703-5a60-9b41-5dae4b446fc3 | http://192.168.202.108:8081 | presto-main:0.117 | true        | true
(1 rows)
```

(Ultimately you can't access any data from any of the `system` tables when only the coordinator is online though)

**Comment by petroav** [comment]
I think this behavior makes sense. If you just had a coordinator up, then the system is unusable, it is undefined. You shouldn't give the user the illusion that they can send queries by making the system catalog query-able. This is just my opinion, not sure if this behavior is intentional or not. The FB folks can chime in and clarify.

**Comment by cawallin** [comment]
There is a configuration related to this: `node-scheduler.include-coordinator=true`. When set to true, you can treat the coordinator as both a worker and a coordinator. With this config set, you'll be able to run schema queries (and any queries, for that matter) with a single node.  For a production cluster, that's probably a bad idea, but if you're just trying Presto out this config will work.

**Comment by petroav** [comment]
Right, so with `node-scheduler.include-coordinator=true`, you no longer just have a coordinator, you have a coordinator and a worker. They just happen to be living in the same process. In this case, the system is defined and the `system` catalog is available.

**Comment by dabansal** [comment]
No worker nodes available -- we are also getting this error intermittently. I have made sure that .properties file is available in all the nodes. Can this error come when hardware resources aren't enough for number of queries getting executed.

Exact error message is:
RESPONSE --> {"id":"20170816_111721_01180_c5tn3","infoUri":"http://ec2-52-91-204-246.compute-1.amazonaws.com:8080/query.html?20170816_111721_01180_c5tn3","stats":{"state":"FAILED","queued":false,"scheduled":false,"nodes":0,"totalSplits":0,"queuedSplits":0,"runningSplits":0,"completedSplits":0,"userTimeMillis":0,"cpuTimeMillis":0,"wallTimeMillis":0,"processedRows":0,"processedBytes":0},"error":{"message":"No worker nodes available","errorCode":65541,"errorName":"NO_NODES_AVAILABLE","errorType":"INTERNAL_ERROR","failureInfo":{"type":"com.facebook.presto.spi.PrestoException","message":"No worker nodes available","suppressed":[],"stack":["com.facebook.presto.util.Failures.checkCondition(Failures.java:85)","com.facebook.presto.sql.planner.SystemPartitioningHandle.getNodePartitionMap(SystemPartitioningHandle.java:149)","com.facebook.presto.sql.planner.NodePartitioningManager.getNodePartitioningMap(NodePartitioningManager.java:105)","com.facebook.presto.execution.scheduler.SqlQueryScheduler.lambda$null$0(SqlQueryScheduler.java:140)","java.util.HashMap.computeIfAbsent(HashMap.java:1126)","com.facebook.presto.execution.scheduler.SqlQueryScheduler.lambda$new$1(SqlQueryScheduler.java:140)","com.facebook.presto.execution.scheduler.SqlQueryScheduler.createStages(SqlQueryScheduler.java:241)","com.facebook.presto.execution.scheduler.SqlQueryScheduler.\u003Cinit\u003E(SqlQueryScheduler.java:131)","com.facebook.presto.execution.SqlQueryExecution.planDistribution(SqlQueryExecution.java:388)","com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:252)","com.facebook.presto.execution.QueuedExecution.lambda$start$1(QueuedExecution.java:62)","java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)","java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)","java.lang.Thread.run(Thread.java:748)"]}}}
