### ISSUE TITLE
Switch all hashing to 64bit hashes

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#4133]
There's a major performance cliff in GROUP BY (and presumably JOIN) queries with > ~10B distinct groups. This is because our hashes only have 32bits of entropy. We should switch `Type.hash` to return a `long` and all other hashes should be 64bit (implementations of `OperatorType.HASH_CODE`, `CombineHashFunction`...etc)

**Comment by cberner** [comment]
Here's a benchmark which shows that at 1T groups performance is nearly 100x worse than 1B groups:
https://github.com/cberner/presto/blob/a20d38a3b0d0ad326b9e9591771a379fd3dcef16/presto-main/src/test/java/com/facebook/presto/operator/BenchmarkGroupByHash.java

**Comment by fiedukow** [comment]
I'm currently working on that.

**Comment by fiedukow** [comment]
It is resolved by #4960.

**Comment by cberner** [comment]
Awesome, thanks!
