### ISSUE TITLE
TimeZone should be customizable for connection

### ISSUE THREAD

**Issue by maciejgrzybek** [prestodb/presto#4224]
The values for the `Timestamp` column are adjusted to your local time zone on retrieval.  If you retrieve the value of the timestamp while you are accessing it from a different timezone you will get unexpected results.
By default the timezone is set according to the JVM's settings from when your connection to Presto is established.
Presto does not currently allow the timezone setting to be overridden due to the fact `PrestoResultSet` does a conversion. It does not provide any easy way to retrieve the timestamp values from the Presto tables without a timezone adjustment.

Wouldn't it nice to have a way to overwrite the timezone via `ClientSession`? Or even using properties in the `ClientSession`?

**Comment by maciejgrzybek** [comment]
This would be very useful for external databases while fetching timestamps.
A good example of an issue caused by adjusting a timestamp is a following test case:
```java
write_timestamp_to_external_db(timestamp); // without counter-adjustment on write
ResultSet rs = connection.createStatement().executeQuery("select ts from external_db.table"); // on presto
Timestamp ts = rs.getTimestamp(1); // adjusted ts
assertThat(ts).isEqualTo(timestamp); // fails
```

**Comment by cawallin** [comment]
It is possible to set the TimeZone via the connection: see https://prestodb.io/docs/current/release/release-0.66.html ("The time zone of the session can be set on a per-query basis using the X-Presto-Time-Zone HTTP header, or via the PrestoConnection.setTimeZoneId(String) method in the JDBC driver.")
