### ISSUE TITLE
Implement EXPLAIN ANALYZE

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#4226]
This should work similarly to Postgresql (http://www.postgresql.org/docs/9.4/static/sql-explain.html), by executing the query, recording stats, and then rendering the stats along with the plan.
A first pass at implementing this could probably be to render similarly to `EXPLAIN (TYPE DISTRIBUTED)` with the stage & operator stats inserted

**Comment by sopel39** [comment]
@cberner are you going to work on this? If this is not a priority task for you then we would be happy to to work on this.

**Comment by cberner** [comment]
Yep, I've got a working prototype (https://github.com/cberner/presto/tree/explain). This is the first step: https://github.com/facebook/presto/pull/4300

I'd love to collaborate on it, as there are tons of improvements that could be made which I probably won't have time for though.

A good one to start with (which shouldn't conflict too much with my commits) would be refactoring the way that the scan-filter-project optimization works. Right now it's done in the `LocalExecutionPlanner`, but this means that multiple `PlanNode`s are merged into a single operator, and so the stats for some of the plan nodes are missing when I render the plan and stats. To fix this we need to introduce a new `ScanFilterProjectNode` and do the merging as a `PlanOptimizer`. Then the `LocalExecutionPlanner` would just look for that node

**Comment by sopel39** [comment]
@cberner OK, I will look at this refactor

**Comment by sopel39** [comment]
@cberner Do you think that merging `PlanNodes` nodes in `PlanOptimizer` is the natural place for it? At first it looks so, but wouldn't such `ScanFilterProjectNode` be artificial entity only for the sake of stats? I wonder if that change wont introduce additional complexity in other parts of code (e.g. rewrite rules). Maybe it's better to just account for it when formatting explain?

FYI: @kokosing @martint

**Comment by cberner** [comment]
Ya, I think that's the right place for it. Discussed the design with @martint, and we'd like to move away from having optimizations like this in the `LocalExecutionPlanner`. Instead they should be done in optimizers and then `LocalExecutionPlanner` should just create the necessary factories.

**Comment by martint** [comment]
@cberner, however, I'm not sure I would do it within the current optimization framework. This is the direction we're going with the new optimizer, but making these kinds of changes to the current one would add a lot of unnecessary complexity, as @sopel39 pointed out.

**Comment by cberner** [comment]
@martint it could be run last, so that we don't need to add handling to predicate push down...etc. I'm fine waiting until the new framework too though

**Comment by cberner** [comment]
@sopel39 something else you could work on is tracking peak memory usage for stages. We have this already at the query level (see `QueryStateMachine`), but I don't think we have it for stages. If we track it for stages we can then render it as part of the EXPLAIN ANALYZE to indicate which stage of the query took the most memory

**Comment by sopel39** [comment]
@cberner sure, I will look at it

**Comment by sopel39** [comment]
@cberner so are you going to finish working on `explain analyze` without displaying stats for all `PlanNodes` (e.g. not for Filter and Scan nodes, but only for Project node since that can be deduced)? We will need `explain analyze` when working on subqueries to see which plan is selected and how it performs?

**Comment by cberner** [comment]
Yes, I'm going to just skip the stats for any node where it's missing

**Comment by sopel39** [comment]
@cberner Peek memory for stages in: https://github.com/facebook/presto/pull/4339/. Do you have some other features on your mind?

**Comment by cberner** [comment]
Great! Not at the moment. What do you guys need displayed in the EXPLAIN ANALYZE plan?

**Comment by sopel39** [comment]
I think displaying what is currently visible on Presto page would be great plus CPU usage, network tx/rx, disk ios.

FYI: @pnowojski @losipiuk

**Comment by sopel39** [comment]
@cberner Would you like code review on your commit: https://github.com/cberner/presto/commit/4cba1380102c1da7c01f0c273a1d5b83577450fe?

**Comment by cberner** [comment]
Not yet. It still has a bunch of bugs (doesn't work on CREATE TABLE AS SELECT or INSERT at the moment). I'll put up a PR when it's ready though, and then ya, that'd be great!

**Comment by cberner** [comment]
Network tx/rx would definitely be cool! We don't track that at all right now, so if you want to work on that the place to start would be to figure out how to track it in the Exchanges and SharedBuffers. Let me know if you need pointers on where to start

**Comment by dain** [comment]
It will be much easier to simply sum the page sizes moving thought the exchanges than to attempt to measure network traffic.

**Comment by sopel39** [comment]
OK, thanks for hint.

**Comment by sopel39** [comment]
@cberner Could you give me an update on your status of `EXPLAIN ANALYZE` work? I would be happy to take over if it is still a lot of work since `EXPLAIN ANALYZE` support is one of the features for our Q1 roadmap.

We also have a plan to display additional statistics. Please review the list:
1. Partition/Split pruning stats for `TableScanOperator`. This might require additional methods/parameters in `Connector`, `ConnectorMetadata` or `ConnectorSplitManager` interface. Do you have some vision how this should be designed? Since I think it's a stats design question we will probably create some issue with a design sketch.
2. Number of input/output rows/pages for each operator (I think this is already partially implemented in your patch and the stats are there).
3. Measure network traffic. Number of rows/bytes produced by TaskOutputOperator/consumed by ExchangeOperator. The stats should be there already.

FYI: @ilfrin

**Comment by cberner** [comment]
I don't think it's too much more work. I haven't been working on it, as I was waiting for @dain's changes for distribution support to land. I'm going to rebase it now and finish it up, but I'm on vacation next week, so it probably won't happen 'til later in the month.

Could you elaborate on (1) a bit? Do you mean stats on how much data was skipped due to predicate push-down?
For (2), yes I would definitely like to see that too and I tried to implement it. The problem I ran into is that some `PlanNode`s turn into multiple `Operator`s. For example, an aggregation can become a `ProjectOperator` -> `HashAggregationOperator` and I didn't find an easy way to map that into an "input" and "output" for the whole `PlanNode` as the ordering was lost. So ya, it would be great if you worked on that!
(3), ya this would be awesome to have. Another thing to consider is how to get this information from connectors, as a `TableScanOperator` is likely to do remote reads

**Comment by sopel39** [comment]
For (1) that's what we would ideally like to know. I understand that currently there is no way to get this information from connectors. Therefore some additional interface or methods are required. This could also be a good starting point for connector statistics. We would like to propose some design for this feature.

For (2) I don't exactly understand what do you mean by lost ordering. I imagine that whenever you translate `Node` into some operators, it should always be known what is the input and output operator for that `Node`. Then you could provide statistics from that operators as statistics for the `Node`. I am right?

I think stats for `TableScanOperator` are similar to (1). It could be part of some new statistics interface for connectors.
It should be possible to aggregate inner-Presto traffic statistics based on stats for `TaskOutputOperator` and `ExchangeOperator`, right?

**Comment by sopel39** [comment]
@cberner I understand there was still problem with how to map `ProjectFilterScanOperator` into `PlanNodes`. I believe it is quite simple really. `TableScanNode` would have input stats from `ProjectFilterScanOperator`. `ProjectNode` would have output stats and `FilterNode` would be difference. Do you consider it to be too hacky? :)

**Comment by cberner** [comment]
Re "lost ordering": I forget the exact issue I ran into, but if you look at the `LocalExecutionPlanner` it adds a number of extra operators. For example, `enforceLayout` which made it difficult to figure out the input/output for the whole plan node. I would hope that this isn't too hard, but it wasn't easy which is why I skipped it. Let me know if you need more information to figure out how to implement it!

Re "inner-Presto traffic": Yep, this should be pretty straight forward

Re mapping `ScanFilterProjectOperator`: what about the cost which is estimated from the wall time? There's no way to figure that out

**Comment by sopel39** [comment]
Hi. I have fixed a number of issues that I have commented in your WIP commit. Those include reporting for plan nodes that produce multiple operators and reporting ScanFilterProject. I am still working on how to make ExplainAnalyzeOperator wait for TaskInfos that have final numbers. I will make pull request out of those changes for you to see with further explanation.

I didn't know about `enforceLayout` so I will check what could be a problem too.

**Comment by sopel39** [comment]
I have published a pull required https://github.com/cberner/presto/pull/2 that fixes various issues that I have found in EXPLAIN ANALYZE path. The patch doesn't support INSERT, DELETE, CREATE, but I believe support for those can be added later.

If you have an example what was the problem with `enforceLayout` that would be great.

Issues fixed:
- reporting for `ScanFilterProject` operator: I have added support for this directly in `PlanPrinter` without additional plan node. Number of filtered rows along with input rows is printed.
- reporting for plan nodes that produce multiple operators: I think that operators for given plan node can be ordered by `opreratorId`. Using this one can specify which operator was input or output for a given plan node. I take advantage of this when reporting stats for plan nodes.
- reported stats were not final: I have made `ExplainAnalyzeOperator` to work in a separate stage. This way I can wait for other stages to complete before reporting analysis. There was also a problem that explain operator required coordinator only distribution while some other operators require fixed distribution.

**Comment by cberner** [comment]
I've fixed a bunch of this locally in my branch, will take a look at that PR too

Re: stats not being final. That fix isn't sufficient. A stage can transition to a finished state before all the stats are collected. For example, a LIMIT query, the top stage will finish early and cancel the underlying stage which moves it directly to a done state.

**Comment by cberner** [comment]
Re `operatorId` for ordering: I looked into this more to see why I didn't use `operatorId` and the problem is that ids are only unique in a pipeline, but a `PlanNode` can span multiple pipelines. For example:
```
select * from (values 1) t(x) join (values 1) t2(y) on x = y;
```
This results in both `LookupJoinOperator` and `HashBuilderOperator` with `operatorId=2` and `planNodeId=17`

**Comment by sopel39** [comment]
Is the problem with finished stages is that stage states are stored on coordinator (so there is instant access), but `TaskStats` are fetched? So maybe and additional/only condition should be checking that all tasks from upstream stages are done.

Plain `operatorId` is not enough as you say. However, is is possible to determine that two operators come from different pipelines. Having `pipelineId, operatorId, planNodeId` and `operatorType` it should be possible to write special rules that compute stats for specific plan node types. An easier approach might be to make sure that `planNodes` do not span across pipelines. In such case `HashBuilderOperator` could have assigned its source `planNodeId`.

**Comment by sopel39** [comment]
I have modified https://github.com/cberner/presto/pull/2 according to my comments (waiting for `TaskStats` to be done and bind `JoinNode` to single pipeline (there are other cases which have to be modified, e.g. Union, I haven't verified them)

**Comment by sopel39** [comment]
Making `planNodes` to not span across pipelines is too native. Maybe we could store some operator topology information in stats?

**Comment by sopel39** [comment]
@cberner What do you think about adding `planNodeInputOperator` and `planNodeOutputOperator` to `OperatorStats`? Those would be set in `LocalExecutionPlanner`. I think it's easier than storing operators topology and we don't have to write special rules for every plan node in `PlanPrinter` (which would be mimicking `LocalExecutionPlanner`)

**Comment by cberner** [comment]
Yes, stage stats are on the coordinator and are an aggregation of the task stats. It might be possible to wait for all the task stats to arrive, but I'm not sure. @nileema is working on a refactoring of how stats are collected, so I'll check with her today to see if that will provide a way to know when they're consistent.

Requiring PlanNodes to be in only a single pipeline doesn't sound like a good idea to me

**Comment by cberner** [comment]
What would the `inputOperator` and `outputOperator` be set to? I think you can already get this by looking at the order of the operator summaries in a pipeline

**Comment by cberner** [comment]
I discussed with @dain, and it looks like there's a straightforward way to do this. Local exchanges and joins are the only things that span pipelines, and both of them follow a simple rule: the "output" operator will not be the last operator in its pipeline. So we should be able to reconstruct the pipeline topology easily, by looking at all the operators for a plan node and then using that rule to determine which is the output and which are in the inputs

**Comment by cberner** [comment]
Also, noting another optimization we'll want to add:
We should add a "consume input" plan node which can run distributed. Otherwise, EXPLAIN ANALYZE could add a lot of cost to the query. For example, if you run it on a SELECT *, it will pull all the rows to the coordinator, and instead we should plan it as TableScan -> ConsumeInput -> ExplainAnalyze, with the first two running in one stage, and only the ExplainAnalyze running on the coordinator

**Comment by sopel39** [comment]
I could work on operators stats reporting. Do you want to work on `ConsumeInput` operator?

**Comment by cberner** [comment]
I'm working on cleaning up the prototype that I have and getting it up for review. I can take a look at the ConsumeInput after that, if I have time though

**Comment by cberner** [comment]
First part of this is up for review here: https://github.com/facebook/presto/pull/4586

**Comment by cberner** [comment]
Second part is up for review here: https://github.com/facebook/presto/pull/4618

**Comment by sopel39** [comment]
We are planning to add skewness metrics for `EXPLAIN ANALYZE`. This would be useful for developers and analysts to figure potential query performance problems.

There are two skewness metrics that we were thinking on:

**Operators input skewness: concurrent operators for the same plan node might receive different number of rows.**

Assume that there are 3 machines. Assume that 1 machine processes 50% of rows and 2 other process 25% of rows each. We can say that 50% of rows utilized 1/3 of resources. Other 50% of rows utilized 2/3 of resources. We can report such metric using quantiles. For example:
```
[0.16, 0.16, 0.33, 0.33]
 0   25%   50%   75%  100%
```
This is the proposal for reporting operator skewness.

**Hash collisions: concurrent operators (join, group) for the same plan node might produce different number of collisions in hash tables**

Assume that there are 3 machines. Assume that each machine processes equal number of rows. We can compute that each machine should produce `n` collisions total if the hash function has constant distribution. It happens however that 1st machine produces `2*n` collisions, 2nd machine `n` collisions and 3rd machine `0.5n` collisions. We can say 33% of rows has `2.0` collisions ratio, 33% of rows has `1.0` collisions ratio and 33% of rows has `0.5` collisions ratio. We can report such metric using qu
qantiles. For example:
```
[2.0, 1.0, 0.5]
0  33%  66%  100%
```

For simplicity I assumed quantiles: `0%, 33%, 66%, 100%`. I think that we should actually use: `0%, 25%, 50%, 75%, 100%` or even denser quantiles.

@martint @cberner @pnowojski @ilfrin: tell me how you like this reporting idea? Do you think there is some better way of reporting skewness that would also be readable from CLI?

**Comment by martint** [comment]
Reporting percentiles is a very good idea. It's one of the things I want add to the web-based visualization of query execution, too.

We may also want to show mean and standard deviation of those metrics. It can make it easier to spot problems at a glance.

**Comment by pnowojski** [comment]
@sopel39 think also about `ParallelHashBuilder` which also can suffer from data skew.
