### ISSUE TITLE
Implement element_at for maps

### ISSUE THREAD

**Issue by cosinequanon** [prestodb/presto#4228]
It should have the signature `element_at(x<K,V>, K) -> V` and allow you to have queries like this:

```
select
  element_at(m, 'foo'), -- 'bar'
  element_at(m, 'na'), -- NULL
from (
  values
    (map(array['foo'], array['bar']))
) as t(m)
```

**Comment by electrum** [comment]
I'm not sure I like duplicating an existing operator, though it does make it more consistent.

**Comment by electrum** [comment]
What is the rationale for not using the operator?

**Comment by cosinequanon** [comment]
My initial idea was to call this `map_get`, @cberner suggested to reuse the name. I honestly don't care too much what it is called.

> What is the rationale for not using the operator?

Not sure I understand, are you asking why I can't do `m['foo']`?

**Comment by dain** [comment]
Yes, why not use the array index operator.  This gives the results you expect:
```sql
select
  m['foo'], -- 'bar'
  m['na'] -- NULL
from (
  values
    (map(array['foo'], array['bar']))
) as t(m)
```

**Comment by cosinequanon** [comment]
It would be nice to not have to use syntax in certain scenarios. For example, if you are generating code it makes it easier if everything is can be expressed as a function. More specifically it came up via this https://github.com/prestodb/RPresto/pull/41
