### ISSUE TITLE
View is stale immediately after creation

### ISSUE THREAD

**Issue by yuanxiang250** [prestodb/presto#4232]
Presto version is  presto-server-0.123  user
My config ：
connector.name=hive-cdh5
hive.metastore.uri=thrift://HADOOP1:9083
1. I  operated CREATE VIEW  view_nginx_log AS 
2. CREATE OR REPLACE VIEW  view_nginx_log AS 
   SELECT   ip,...  USER,
   TIME,...line_no
   FROM
   (SELECT  ip, ..  USER,
     TIME,..url_extract_parameter(url,'lineNo') AS line_no
   FROM
     txt_nginx 
   WHERE DATE = '20151224' 
     AND HOUR = '15' 
   UNION
   ALL 
   SELECT  ip, .....url_extract_parameter(url,'lineNo') AS line_no  
   FROM
   orc_nginx_log);
3. select \* from view_nginx_log
   show me a error: 【Query 20151224_093318_00023_wvykb failed: View 'hive.default.view_nginx_log' is stale; it must be re-created】

I  drop the view and re-created ，see the same error。
i think 
【USER, TIME】  sources of errors

**Comment by electrum** [comment]
Views work by storing the query text along with the names and types of the result columns for the query. When querying the view, we re-analyze the stored query and throw the "is stale" error if the result columns don't match those stored for the view. Clearly, these should be the same immediately after creating the the view (assuming the underlying table definitions are not changing).

Are you able to reproduce this if you remove some columns from the view? Is there a single column that is causing the problem?

If you are able to help debug this, put a breakpoint on the `isViewStale` method in `StatementAnalyzer` and see why the columns are different.

**Comment by electrum** [comment]
I notice that one of your columns is uppercase: `SELECT USER`. If you make that `SELECT user` (do that for all columns), does it fix the problem?

**Comment by yuanxiang250** [comment]
yes fixed  when  i use “ SELECT user ”





At 2015-12-29 01:30:30, "David Phillips" <notifications@github.com> wrote:


I notice that one of your columns is uppercase: SELECT USER. If you make that SELECT user (do that for all columns), does it fix the problem?

**Comment by electrum** [comment]
Simple reproduction:
```
presto> create view test_view_uppercase as select X from (select 123 X);
CREATE VIEW
presto> select * from test_view_uppercase;
Query 20160906_221506_21044_4xh5v failed: line 1:15: View 'test_view_uppercase' is stale; it must be re-created
select * from test_view_uppercase

**Comment by findepi** [comment]
Supposedly, fixed by https://github.com/prestodb/presto/pull/6049
