### ISSUE TITLE
Remove identity casts in optimizer

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#4259]
Redundant identity casts will prevent partition pruning. These need to be removed before the `AddExchanges` optimizer which is when `Metadata.getLayouts()` is called with the constraint (and thus passed to the connector). It also needs to happen before `PredicatePushDown`. `SimplifyExpressions` is probably a good place to put it.

**Comment by maciejgrzybek** [comment]
@zachyee will be working on this task.
