### ISSUE TITLE
Pre-Gregorian date strings parsed as Julian

### ISSUE THREAD

**Issue by oggy** [prestodb/presto#4321]
Or that is my best interpretation of what I'm seeing, which is that around certain dates, casting a string to a date, and selecting the result, gives unintuitive results.

```
presto:default> select cast('1582-10-14' as date);
   _col0    
------------
 1582-10-04 
(1 row)

Query 20160112_193559_00064_xbcft, FINISHED, 1 node
Splits: 1 total, 1 done (100.00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]
```

The following day is fine:

```
presto:default> select cast('1582-10-15' as date);
   _col0    
------------
 1582-10-15 
(1 row)

Query 20160112_193601_00065_xbcft, FINISHED, 1 node
Splits: 1 total, 1 done (100.00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]
```

Note the 14th parses as the 4th, and all preceding days have a similar offset until Feb 29 1500, when the gap shrinks by another day. Both these dates represent anomalous moments in most of the world's calendars. Oct 4 was the switch to the Gregorian calendar when 11 days were skipped, and Feb 29 was the last century leap year before new rules around such years were introduced with the calendar switch.

Generally speaking, I don't have strong objections as to which calendar is used if it keeps implementation simpler. However it does seem like a bug when a date is entered as 1000-01-01, and can't be queried using that date.

**Comment by anusudarsan** [comment]
Tried this on the latest version (0.177) and it seems to be fixed

``presto> select cast('1582-10-14' as date);
   _col0    
------------
 1582-10-14 
(1 row)

presto>  select cast('1582-10-15' as date);
   _col0    
------------
 1582-10-15 
(1 row)`` Can we close this issue?

**Comment by oggy** [comment]
Nice, thanks!
