### ISSUE TITLE
Add header to allow setting read-only mode for autocommit

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#4329]
We should have a header named something like `X-Presto-Read-Only` that starts the autocommit transaction in read-only mode. Clients can use this to improve safety and performance if they will only be running selects. The request to `StatementResource` should fail if this is set during a transaction or is used with `START TRANSACTION`.

**Comment by martint** [comment]
What's the use case? Can't those clients just use regular transactions in read-only mode if they want that advanced behavior?

**Comment by electrum** [comment]
We actually want to set this flag for most clients. In many environments it should be the default.

For example, reporting interfaces will always be reading, never writing. Read only mode can provide some safety if someone makes a report that does "drop table" or has a SQL injection vulnerability.

Having a header keeps it simple and avoids the two extra round trips to start and end the transaction, and avoids lots of abandoned transactions like we already see with abandoned queries.

**Comment by electrum** [comment]
Another consideration is JDBC allows setting read only with autocommit.

**Comment by electrum** [comment]
When this is implemented, we should not allow calling procedures in read-only mode, since the expected use of procedures is to modify some system or connector state.

`CallTask` needs a check for this, which probably requires another method isReadOnly() added to QueryStateMachine that delegates to some additional methods in TransactionManager and TransactionMetadata.
