### ISSUE TITLE
Make retry policy when reading/writing to HDFS adaptive

### ISSUE THREAD

**Issue by martint** [prestodb/presto#4333]
Queries that have been running for longer (i.e., non-interactive) should do more retries when encountering errors reading and writing to HDFS.

**Comment by electrum** [comment]
This is difficult to do everywhere, especially for file formats that use the Hive readers. We actually already have retry logic in `HiveUtil.createRecordReader()`. I think these two places would cover most cases:

* File opens in `HivePageSourceProvider` on the call to `pageSourceFactory.createPageSource()` (no need to wrap `getHiveRecordCursor()` as the important implementations already have retry).
* The read call in `HdfsOrcDataSource`.

**Comment by raghavsethi** [comment]
Just having different timeouts seems to address this problem to a large extent. Closing until we can prove that additional changes are required.
