### ISSUE TITLE
Use same window operator for same partitioning and ordering

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#4359]
Consider a query like this:

``` sql
SELECT
  sum(length(value)) OVER (ROWS BETWEEN 1 PRECEDING AND 3 PRECEDING),
  sum(length(value)) OVER (ROWS BETWEEN 2 PRECEDING AND 4 PRECEDING)
FROM src;
```

It produces a plan like this:

```
- Project => [sum:bigint, sum_4:bigint]                                                                                                       
    - Window[] => [length:bigint, sum:bigint, expr_2:bigint, expr_3:bigint, sum_4:bigint]                                                     
            sum_4 := sum("length")                                                                                                            
        - Project => [length:bigint, sum:bigint, expr_2:bigint, expr_3:bigint]                                                                
                expr_2 := 2                                                                                                                   
                expr_3 := 4                                                                                                                   
            - Window[] => [length:bigint, expr:bigint, expr_0:bigint, sum:bigint]                                                             
                    sum := sum("length")                                                                                                      
                - Exchange[GATHER] => length:bigint, expr:bigint, expr_0:bigint                                                               
                    - Project => [length:bigint, expr:bigint, expr_0:bigint]                                                                  
                            length := "length"("value")                                                                                       
                            expr := 1                                                                                                         
                            expr_0 := 3                                                                                                       
                        - TableScan[...] => [value:varchar]                                       
```

These could be collapsed to use a single operator. This will require execution changes to `WindowNode`, `WindowOperator`, `WindowPartition`, etc., to combine the frame with the function call, rather than using a single frame for the entire node.

This should probably build on #4358.

**Comment by maciejgrzybek** [comment]
@electrum: Let me think aloud:
Should we compute ranges (parts of frames) of functions operating on the same partitioning and order and pass them to `WindowOperator`?
E.g. in the query you provided (BTW I think:
```sql
SELECT
  sum(length(value)) OVER (ROWS BETWEEN 3 PRECEDING AND 1 PRECEDING),
  sum(length(value)) OVER (ROWS BETWEEN 4 PRECEDING AND 2 PRECEDING)
FROM src;
```
makes more sense), we should pass 3 ranges: 4-3 _preceding_ (part of second function), 3-2 _preceding_ (both functions), 2-1 _preceding_ (part of first only).
So in `QueryPlanner` we should compute set difference and intersection (of frames) for the windows of the same order and partitioning and pass them with function call assigned to the execution as a one operator.
Then in execution we call function depending on the range (for each row decide which function's range covers given row).

**Comment by mattsfuller** [comment]
I don't think you need to do something that complex.
Can the WindowOperator simply track the beginning and end for each frame on the same data?

**Comment by maciejgrzybek** [comment]
Right, this would be simpler to keep just `Collection<Range>` without differentiating intersections.
So, we would pass to the operator something like `Map<Range, FunctionCall>` (high-level speaking) for all `Windows` with the same _partition_ and _order_.

@electrum: I'd like to work on that, could you please assign me to this ticket?

**Comment by maciejgrzybek** [comment]
Closing because #6009 got merged.
Created a follow-up issue (#6681), to merge windows across non-window nodes as current implementation cannot solve that problem.
