### ISSUE TITLE
Add support for cassandra 3.+

### ISSUE THREAD

**Issue by reikje** [prestodb/presto#4364]
To be able to work with Cassandra 3.+ the `cassandra-driver-core` dependency need to be upgraded in `presto-cassandra`. Currently there is only a release candidate (3.0.0-rc1). I tried building presto against it but there are some breaking changes.

`com.datastax.driver.core.ColumnMetadata` - removed `getIndex()` method
`com.datastax.driver.core.LocalDate` - removed `getTime()`
`com.datastax.driver.core.policies.RetryPolicy` - new Interface method added `close()`

see: http://datastax.github.io/java-driver/upgrade_guide/

A typical error that you will see running an older version of `cassandra-driver-core` against a 3.x cluster: `All host(s) tried for query failed (tried: /xx.xx.xx.xx:9042 (com.datastax.driver.core.exceptions.InvalidQueryException: unconfigured table schema_keyspaces)`

**Comment by electrum** [comment]
Does the new driver work with old clusters?

**Comment by reikje** [comment]
Yes.
Am 19.01.2016 5:39 nachm. schrieb "David Phillips" <notifications@github.com

**Comment by bannmann-incub8** [comment]
For the record, as of today the final 3.0 release is available on Maven Central:
```xml
<dependency>
    <groupId>com.datastax.cassandra</groupId>
    <artifactId>cassandra-driver-core</artifactId>
    <version>3.0.0</version>
</dependency>
```

**Comment by nemothekid** [comment]
I've added support for Cassandra 3.x into Presto-136. 

Rundown of the changes:
* Update `datastax.version` to 3.0.0
* Add new interface methods to `BackoffRetryPolicy`
* Rename `getTime()` -> `getMillisSinceEpoch()` (base class changed)
* Change method of finding if an index is indexed (Cassandra 3.0 changed the 2i API)
* Other test changes

The full changes can be found in here (https://github.com/ChannelMeter/presto/commit/77d2fff3180b43fe08eae6db0f416715e25bd346), in my [cassandra3](https://github.com/ChannelMeter/presto/tree/cassandra3) branch.

I'll open a PR, however I need to confirm that the new code & driver still works with Cassandra 2.x

**Comment by nemothekid** [comment]
Actually, I take that back, `com.datastax.driver.core.LocalDate` seems to have broken timestamp columns.

**Comment by martint** [comment]
This is done.
