### ISSUE TITLE
error msg print into STDOUT instead of STDERR

### ISSUE THREAD

**Issue by linehrr** [prestodb/presto#4374]
this can be easily reproduced by killing the Presto coordinator while the query is running.
error msg then will be printed into the STDOUT and escape the check of the STDERR, which makes our custom controller thinks the query runs successfully and stores the results.
instead, it failed and the result data is just something like:

> Lost connection to node ...

we tested this on v0.131 and v0.132
no clue if this was fixed in v0.133

**Comment by electrum** [comment]
Are you using --execute to run the query?

**Comment by linehrr** [comment]
@electrum 
yes we always use --execute "<query>"
does this issue only happen on --execute ?

**Comment by cawallin** [comment]
I just checked, and when using --execute on 0.170, error messages are printed to stderr as expected. Please re-open if you're still having issues.
