### ISSUE TITLE
Multiple entries with same key:

### ISSUE THREAD

**Issue by udayabaski** [prestodb/presto#4386]
Hi,

   I use presto oracle plugin.

I connect to the command line as below.

./presto --server localhost:8080 --catalog oracle --schema <schema_name>

presto:<schema>> select \* from <table>;
Query 20160120_234810_00002_mpatk failed: Multiple entries with same key: addr_type_cd=JdbcColumnHandle{connectorId=oracle, columnName=ADDR_TYPE_CD, columnType=varchar} and addr_type_cd=JdbcColumnHandle{connectorId=oracle, columnName=ADDR_TYPE_CD, columnType=varchar}

Is there anything wrong with the configuration?

Thanks,
Baskar.S

**Comment by cawallin** [comment]
@udayabaski the Presto oracle plugin is located at https://github.com/marcelopaesrech/presto-oracle, not in this repository -- please ask your question there
