### ISSUE TITLE
Presto monitoring

### ISSUE THREAD

**Issue by pnowojski** [prestodb/presto#4391]
We are trying to figure out best way to track/monitor some performance metrics of our Teradata/Presto cluster. For simplicity we can now assume that we are talking only about presto cluster. On our testing environments we have setup collectd to capture jmx stats and store them into graphite, from where those stats are being read and displayed by grafana. It's a nice setup, gives great graphs, but it is troublesome to setup and we are looking for some replacement in production environments. Especially to cover cases "client X is asking as why query Q on Presto runs slowly" and we wants to login into cluster and do some monitoring - check memory/cpu usages, some buffers usage (for example our internal teradata connector for presto expose via JMX some internal buffer usage which is important for us). And we want to monitor those stats over time.

In presto there is a nice jmx connector, but it doesn't hold history - it presents only momentary data. Have you ever thought about accessing and plotting those data for lets say last 24 hours? We were brainstorming and we have thought about dozens of solutions. Some of them:
1. using external simple tool to run from crontab every 10 seconds, that would dump chosen jmx stats to some file(s) which we could analyze later on
2. temporarily re-configuring collectd on the client's cluster, so it would transmit it data to our graphite/grafana
3. query presto-jmx connector once every 10 seconds about specified metrics store those values into:
   - (a) some side MySQL/SQLite database
   - (b) write those dumps in some presto-memory connector (which would store all data into memory)
   
   For example lets say that we want to dump MBean `jmx.jmx."java.lang:type=operatingsystem"`. We would create table exactly the same as this `jmx.jmx."java.lang:type=operatingsystem"`, but with added some `timestamp` column for every dump. Then we could ask MySQL ( (a) ) or this presto-memory connector ( (b) )  
   
   `SELECT timestamp, openfiledescriptorcount, maxfiledescriptorcount
   FROM presto-memory.jmx."java.lang:type=operatingsystem";`
   
   But this approach has some drawbacks. First of all it requires much more complicated setup: additional MySQL database and some crontab job that would constantly dump data from presto-jmx to the MySQL. 
4.  Yet another idea, is to add functionality to presto-jmx (or fork it) so that it would aggregate and store in memory chosen jmx stats by itself. Basically you would specify in jmx.properties file, which MBeans you want to dump every X seconds and every presto node would do it in the background (it could do some aggregation of older results to have some upper bound on memory usage). Then you could query this jmx stat in similar way as in third solution, but without the need of external MySQL and crontab job, because everything would be done by the connector itself.

This 4th solution would also be the most user friendly and valuable for the community, but maybe someone has another idea? Maybe this problem has already been solved in some other way by someone in the community?

**Comment by pnowojski** [comment]
I allow myself to paste @martint 's answer from private message:

> At FB, we have a monitoring system that can pull jmx stats and send them to store, expose them via dashboards, etc. This would be similar to option 2). Some of the options above are not mutually exclusive.
>
> In general, I think we need at least two mechanisms: 
> 1. a low level interface designed for more sophisticated users or complex integrations
> 2. an out of the box, simpler mechanism for casual or less sophisticated use. 
>
> The current jmx interface satisfies 1), IMO, it’s fairly generic and integrates well with a bunch of other tools. For 2), I think the 4th option you listed is the cleanest and better fits the “out of the box” requirement

**Comment by yuananf** [comment]
I believe this will be helpful https://github.com/xerial/presto-metrics

**Comment by pnowojski** [comment]
@yuananf presto-metrics is just an overlay on presto API that allows to retrieve `momentary` jmx stats? If so that doesn't help us. We need historical data, like CPU/memory usage on cluster during query executed couple of hours ago.

**Comment by nezihyigitbasi** [comment]
At Netflix we have an open-source system called [Atlas](https://github.com/Netflix/atlas) that helps us push these monitoring data (similar to option 2) and let us slice/dice those data and also expose them with dashboards.

**Comment by electrum** [comment]
One problem with #4 is the in memory aspect: if the JVM or machine restarts, you lose the history, and that's often when you need it most (what happened before the crash).

Maybe use a local embedded database of some sort (H2, leveldb, text files, etc.)

**Comment by pnowojski** [comment]
@nezihyigitbasi as I understand you have some custom made simple script/thing that pushes jmx data produced by presto to Atlas?

@electrum maybe we can limit ourselves at beginning with simple in memory solution, by providing optional implementation of such class:

```
public class JmxStatsHolder
{
    private final List<String> tables;
    private final Map<String, EvictingQueue<List<Object>>> tablesRows = new HashMap<>();

    public JmxStatsHolder(int evictionLimit, String... tableNames)
    {
        tables = ImmutableList.copyOf(tableNames);
        for (String tableName : tableNames) {
            tablesRows.put(tableName, EvictingQueue.create(evictionLimit));
        }
    }

    public List<String> listTables()
    {
        return tables;
    }

    public synchronized void addRow(String tableName, List<Object> row)
    {
        checkArgument(tablesRows.containsKey(tableName));
        tablesRows.get(tableName).add(row);
    }

    public synchronized List<List<Object>> getRows(String tableName, boolean[] selectedColumns)
    {
        if (!tablesRows.containsKey(tableName)) {
            return ImmutableList.of();
        }
        return selectColumns(tablesRows.get(tableName), selectedColumns);
    }

    private List<List<Object>> selectColumns(Collection<List<Object>> rows, boolean[] selectedColumns)
    {
        ...
    }
}
```

This implementation keeps the data in memory. Later if there will be such need, we can add alternative version which would use some embedded db. `Later` because any embedded db will be more complicated (serialization, rotation, eviction, etc).

Besides, writing history touches more general topic - that presto doesn't have unified way to store any meta data.

**Comment by nezihyigitbasi** [comment]
@pnowojski we have a separate jvm running on all presto nodes, and those jvms collect & publish various metrics to Atlas.

**Comment by martint** [comment]
@pnowojski yes, let's start with in-memory. It's a step up from what we have today, anyway.

**Comment by kokosing** [comment]
As I understand it is implemented as `jmx.history`.
