### ISSUE TITLE
Leverage transaction support in Hive connector to model INSERT OVERWRITE

### ISSUE THREAD

**Issue by martint** [prestodb/presto#4413]
A DELETE followed by an INSERT in a transaction should defer the call to the metastore to delete the table until after the temporary data for the insert has been generated. This helps reduce the time gap between the partitions being deleted and the new ones being registered and protect against issues where the delete executes successfully but the insert fails due to query execution errors.

**Comment by electrum** [comment]
We could also write them in same format and then just update the table location, so there would never be a gap, then delete the old data (normally the metastore does that on drop).

Though no matter what the strategy, it is inherently racey since the metastore only has unconditional updates.

**Comment by linqerli** [comment]
do you have a plan to develop this feature

**Comment by martint** [comment]
Yes, we're currently working on it.

**Comment by linqerli** [comment]
could you give me the commit number ? I want see the progress in time

**Comment by dain** [comment]
The code is in review here #5818
