### ISSUE TITLE
Support aggregations for intervals

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#4417]
Both interval types should support these aggregations:
- [ ] `sum`
- [ ] `avg`
- [ ] `approx_percentile`
- [ ] `corr`
- [ ] `covar_pop` 
- [ ] `covar_samp` 
- [ ] `regr_intercept`
- [ ] `regr_slope`
- [ ] `stddev_samp` (and `stddev`)
- [ ] `stddev_pop`
- [ ] `var_samp` (and `variance`)
- [ ] `var_pop`
- [ ] `geometric_mean`

**Comment by electrum** [comment]
Except for `sum` and `avg`, it should be possible to re-use the existing aggregation implementation by simply adding another `@InputFunction` method that converts the interval to a long or double.

**Comment by martint** [comment]
var_samp and var_pop don't make sense for intervals. They'd require a type that represents Interval^2
