### ISSUE TITLE
dynamically load Guice modules at runtime

### ISSUE THREAD

**Issue by kietly** [prestodb/presto#4422]
Is there a way to load Guice Module at runtime in Presto? One way is using ServiceLoader as describe in the link. I saw Presto uses it for loading plugin.

https://thedet.wordpress.com/2011/01/23/guice-2-0-multibinder-java-serviceloader-plugin-mechanism/

**Comment by cawallin** [comment]
Thanks for the suggestion! This issue is a duplicate of https://github.com/prestodb/presto/issues/2445, closing this one.
