### ISSUE TITLE
Documentation: Hive connector page does not mention S3 properties

### ISSUE THREAD

**Issue by ghost** [prestodb/presto#4425]
https://prestodb.io/docs/current/release/release-0.57.html

mentions two properties for the Hive connector:
hive.s3.aws-access-key=AKIAIOSFODNN7EXAMPLE
hive.s3.aws-secret-key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

These are not mentioned in the current (0.134) Hive connector page. In the unit tests for the Hive connector there is a third property mentioned:
hive.hadoop1.s3.writableBucket

I can't find where this is used in the code.

**Comment by haozhun** [comment]
The `writableBucket` property is defined in `TestHiveClientS3`. They are test only.

**Comment by rschlussel** [comment]
Documentation is here https://prestodb.io/docs/current/connector/hive.html#amazon-s3-configuration
