### ISSUE TITLE
Presto can't access Hive External Table

### ISSUE THREAD

**Issue by ghost** [prestodb/presto#4433]
Hi,

I have create Hive External table on top of Hbase table. When I try to run presto commands, like select count(*) from Hive_tables, I dont get any result.

Version - 
HBase - 0.96
Persto - 0.134
CDH - 5.5.1

Output for select count(*) 
##  _col0

```
 0
```

(1 row)

Help Appreciated.

Thanks.

**Comment by petroav** [comment]
Presto has no native support for HBase and so cannot read tables stored in HBase.
