### ISSUE TITLE
__HIVE_DEFAULT_PARTITION__ Partition location does not exist

### ISSUE THREAD

**Issue by pnowojski** [prestodb/presto#4460]
I was getting following error:

```
presto:books> select * from books limit 1;
Query 20160201_124411_00054_ztksp, FAILED, 8 nodes
Splits: 36 total, 0 done (0.00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]
Query 20160201_124411_00054_ztksp failed: Partition location does not exist: hdfs://CLOUD14HD01/orc_tables_1/books/year_published=__HIVE_DEFAULT_PARTITION__
```

I have fixed it by manually creating empty directory:
`sudo -u hdfs hadoop fs -mkdir /orc_tables_1/books/year_published=__HIVE_DEFAULT_PARTITION__`

Is this a known issue? Or am I doing something wrong? It looks like a bug that should be pretty easy to fix - not handled non existing `NULL` partition?

Steps to reproduce:
1. http://docs.aws.amazon.com/ElasticMapReduce/latest/DeveloperGuide/query-impala-generate-data.html
2. in hive 

```
set hive.exec.dynamic.partition.mode=nonstrict;

CREATE TABLE books(
  id bigint,
  isbn string,
  genre string,
  date_published date,
  publisher string,
  price double)
PARTITIONED BY (
  year_published int)
CLUSTERED BY (
  id)
SORTED BY (
  id ASC)
INTO 8 BUCKETS
ROW FORMAT SERDE
  'org.apache.hadoop.hive.ql.io.orc.OrcSerde'
STORED AS INPUTFORMAT
  'org.apache.hadoop.hive.ql.io.orc.OrcInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.orc.OrcOutputFormat'
LOCATION
  '/orc_tables/books'
TBLPROPERTIES ('orc.compress'='ZLIB');

CREATE EXTERNAL TABLE books_txt
(id BIGINT, isbn STRING, category STRING, date_published DATE, publisher STRING, price FLOAT )
                ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' LOCATION '/data/books/';

INSERT into table books partition (year_published) select *, year(date_published) from books_txt;
```

However I'm guessing that it can be easier reproduce without the need to generate data.

**Comment by electrum** [comment]
This error means there is a partition with a location that does not exist in HDFS. Unless I'm missing something, that's a bug in whatever created the partition (location should always exist).

What happens when you query it in Hive?

**Comment by damiencarol** [comment]
MSCK REPAIR TABLE <foo> ?????

**Comment by pnowojski** [comment]
I don't know the specification, if that's indeed incorrect situation (missing NULL partition directory, even if its empty). I have created this table using Hive 1.2.1 with quoted commands from the issue. And yes, this tables i readable from Hive:

```
hive> msck repair table books;
OK
Partitions missing from filesystem:	books:year_published=__HIVE_DEFAULT_PARTITION__
Time taken: 0.544 seconds, Fetched: 1 row(s)
hive> select * from books limit 1;
OK
784	2-97845-682-5	JUVENILE-NONFICTION	1970-05-17	Groupe Albin Michel	106.98999786376953	1970
Time taken: 0.21 seconds, Fetched: 1 row(s)
```
and it still fails in Presto:
```
presto:apple_benchmark_orc_1> select * from books limit 1;

Query 20160202_133122_00060_pyu6v, FAILED, 3 nodes
Splits: 1 total, 0 done (0.00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20160202_133122_00060_pyu6v failed: Partition location does not exist: hdfs://CLOUD14HD01/orc_tables_1/books/year_published=__HIVE_DEFAULT_PARTITION__
```

It still looks for me like a missing feature/bug in presto in handling dynamically created partitions in hive.

**Comment by damiencarol** [comment]
I don't know. Presto use infos from metastore. If the partition is missing in HIVE (it is the case here). Presto just can't find it. That's all.
It could be a bug in HIVE.

**Comment by pnowojski** [comment]
Partition is missing, so is msck repair table reporting, but this seems to be consistent with this description:
https://cwiki.apache.org/confluence/display/Hive/LanguageManual+DML#LanguageManualDML-DynamicPartitionInserts
of how inserting dynamic partition works. Partition is created once first value for this partition is found. Since in this aws books data set there are no NULL values, directory `year_published=__HIVE_DEFAULT_PARTITION__` wont' be created.

We can either handle it on our side or I can always fill a bug/question to Hive about whether it is a bug or a feature.

**Comment by electrum** [comment]
What happens when you query it in Hive? Does Hive silently ignore the missing directory? Maybe it has special logic to skip it?

**Comment by damiencarol** [comment]
We have the same version of HIVE in prod (1.2.1). I made the same queries and we have no pb.
I think there are a pb with you data table loading
I can reproduce your bug when creating data in HIVE BUT removing the *__HIVE_DEFAULT_PARTITION__* dir manualy in HDFS.
For me there are no bug in HIVE or Presto.

**Comment by damiencarol** [comment]
@electrum Yes, HIVE silently ignore the pb :)

**Comment by findepi** [comment]
This is probably obsolete.

**Comment by ebuildy** [comment]
This is not a bug related to PrestoDB or Hive, this means when you have inserted data, you didnt include the field ``year_published `` hence Hive creates a kind of dummy partition.
