### ISSUE TITLE
JDBC driver to implement DatabaseMetadata.getTypeInfo

### ISSUE THREAD

**Issue by the6campbells** [prestodb/presto#4552]
The 0.137 JDBC driver currently does not implement DatabaseMetadata.getTypeInfo. A dynamic SQL application that attempts to harvest that information will not be able to do so. Is this on the roadmap of improvements for the JDBC driver?

**Comment by petroav** [comment]
@the6campbells Teradata is going to release a free enterprise ready JDBC driver at the end of March that will support `DatabaseMetadata#getTypeInfo()`.

**Comment by the6campbells** [comment]
Will this mean that the driver downloaded with Presto builds will include this driver or only if persons download from teradata.com?

**Comment by cawallin** [comment]
@the6campbells You will need to download it from www.teradata.com/presto

**Comment by electrum** [comment]
We will add this to the project JDBC driver as well. The Teradata driver is a fork/rewrite for Java 6, but the project one will always be for the version of Java used by Presto (and thus won't work with some legacy applications).

**Comment by the6campbells** [comment]
The driver available with the Presto 0.160 is still missing the method

**Comment by ebd2** [comment]
@the6campbells: Have you looked at the Teradata driver that @cawallin linked? The Teradata driver is a totally different (closed-source) codebase, and so features in it are not necessarily implemented in the open-source driver.

**Comment by ebd2** [comment]
Oh, and if you go to that site, you need to click on the part of the link that reads "Download Presto Drivers", if you click on the "»" link, it takes you to the wrong page. I notified our IT people, but it looks like they haven't gotten around to fixing it yet :-(

This direct link might also work: https://site.teradata.com/Microsite/Q216driverspresto/LP/.ashx, but it might also expire in the future. http://www.teradata.com/presto should remain valid for the foreseeable future.

**Comment by the6campbells** [comment]
@ebd2 - I'm aware of the TD driver. The "issue" is that persons who use Presto on AWS EMR or pull a copy from the Presto site are very likely to use the presto driver vs the one on the TD web site. So what is the plan for the TD contributions to roll into the driver from the Presto site?

**Comment by dain** [comment]
The TD driver contains proprietary code licensed from a third party, so they can't contribute the code to Presto.

What I would like to have is a test suite that can verify any JDBC (or ODBC) driver for Presto, so that we can assure they all return consistent results for metadata (so people don't have to code to a particular implementation).

**Comment by brian-rickman** [comment]
Teradata has contributed com.facebook.presto.tests.jdbc.JdbcTests to the community.  This test covers:

connection.getMetaData().getSchemas()
connection.getMetaData().getTables()
connection.getMetaData().getColumns()
connection.getMetaData().getTableTypes()

in a way that is intended to be driver independent.  We will be expanding this test over time, but would welcome contributions from the community as well.
