### ISSUE TITLE
projecting MAX(time type) returns unexpected result

### ISSUE THREAD

**Issue by the6campbells** [prestodb/presto#4555]
Presto is sourcing data from Postgres where a table has a TIME data type.

The highest value in the set of rows in that table is 23:59:30

<null>
00:00:00
12:00:00
23:59:30

When Presto computes select max( C1 ) from T1 it returns 12:00:00

**Comment by the6campbells** [comment]
Min (C1) is wrong it returns 22:59:30.

**Comment by harunurhan** [comment]
I was just trying to reproduce this.
Here's my test table on MySQL:

```
mysql> describe test_time_aggr;
+-------+------+------+-----+---------+-------+
| Field | Type | Null | Key | Default | Extra |
+-------+------+------+-----+---------+-------+
| c1    | time | YES  |     | NULL    |       |
+-------+------+------+-----+---------+-------+


mysql> select * from test_time_aggr;
+----------+
| c1       |
+----------+
| 00:00:00 |
| 12:00:00 |
| 23:59:30 |
+----------+
3 rows in set (0.00 sec)
```

max(c1) and min(c1) produces the **same and correct** results both from presto and directly mysql.

Here's results from presto:

```
presto:test> select max(c1) from test_time_aggr;
    _col0     
--------------
 23:59:30.000 
(1 row)


presto:test> select min(c1) from test_time_aggr;
    _col0     
--------------
 00:00:00.000 
(1 row)
```

**Comment by electrum** [comment]
Can you show the PostgreSQL CREATE TABLE and INSERT? It might be obvious but that will make it quicker to reproduce and fix.

**Comment by the6campbells** [comment]
create table TTM ( RNUM integer  not null , CTM time(3)) ;
insert into TTM(RNUM, CTM) values ( 0, NULL);
insert into TTM(RNUM, CTM) values ( 1, TIME '00:00:00.000');
insert into TTM(RNUM, CTM) values ( 2, TIME '12:00:00.000');
insert into TTM(RNUM, CTM) values ( 3, TIME '23:59:30.123');

**Comment by harunurhan** [comment]
@the6campbells I tried it also on PostgreSQL but still same.
After create and insert:
```
presto:test> describe ttm;
 Column |  Type  | Comment 
--------+--------+---------
 rnum   | bigint |         
 ctm    | time   |         
(2 rows)

presto:test> select * from ttm;
 rnum |     ctm      
------+--------------
    0 | NULL         
    1 | 00:00:00.000 
    2 | 12:00:00.000 
    3 | 23:59:30.123 
(4 rows)
```


Results are correct, see below.
```
presto:test> select max(ctm) from ttm;
    _col0     
--------------
 23:59:30.123 
(1 row)

presto:test> select min(ctm) from ttm;
    _col0     
--------------
 00:00:00.000 
(1 row)
```
