### ISSUE TITLE
Feature request: Explain format want 「JSON」

### ISSUE THREAD

**Issue by toyama0919** [prestodb/presto#4566]
Hello :blush: 
I want fetch schema by sql.

Schema information can get Explain syntax.
But this format only 「TEXT」 AND 「GRAPHVIZ」.

https://github.com/facebook/presto/blob/efb49f119c568c05db9820430ea104e33d43718a/presto-docs/src/main/sphinx/sql/explain.rst

These format parse is very difficult.
I want format 「JSON」.
This means that can get schema from program.

※PS
PrestoPreparedStatement(JDBC) have getMetaData method.
getMetaData return ResultSetMetaData.
ResultSetMetaData have schema information, can get by Explain.

https://github.com/facebook/presto/blob/master/presto-jdbc/src/main/java/com/facebook/presto/jdbc/PrestoPreparedStatement.java#L255

**Comment by electrum** [comment]
We are adding prepared statements which will provide this more directly (and will be supported by JDBC as you mention).

**Comment by toyama0919** [comment]
Thank you for reply :blush: 
I expect it.

**Comment by rschlussel** [comment]
closing since prepared statements have been implemented and I created a different issue to track adding a JSON EXPLAIN format and the description there is clearer #11189.
