### ISSUE TITLE
Tableau connector feature request

### ISSUE THREAD

**Issue by aadim** [prestodb/presto#4575]
Presto web service connector can help creating Tableau extracts but the incremental update is not available. As fas as I understand we need to specify the list of fields that can be used to detect data change in order to make an incremental update before connecting to the web service data. In case of Presto connector we don't have this field list available before executing the query.

I suggest adding an additional list of text fields to the connector HTML page where we can optionally define incremental fields names. These names must match with output columns in the query.

**Comment by electrum** [comment]
@nezihyigitbasi do you know anything about this?

**Comment by nezihyigitbasi** [comment]
Yep the current web connector doesn't support incremental updates and it seeme like the Tableau API supports it (there is a [sample connector] capable of doing that(https://community.tableau.com/thread/179272)).
