### ISSUE TITLE
Distinct limit optimizer should apply to GROUP BY with ARBITRARY aggregation

### ISSUE THREAD

**Issue by dain** [prestodb/presto#4578]
The following query should be executed efficiently using the distinct limit operator;

``` sql
SELECT clerk, ARBITRARY(comment) 
FROM orders 
GROUP BY 1 
LIMIT 10;
```

The optimizer will need to be expanded to recognize this pattern and the operator will need to be expanded to support extra "non-distinct" columns.

**Comment by zhenxiao** [comment]
Is anyone working on it? may I take a try?

**Comment by dain** [comment]
I don't think so.  Go for it!

**Comment by erichwang** [comment]
UPDATE: this is not easy to do without major modifications to aggregations or the distinct limit operator due to null handling. We should resume this work when we can infer that the streams are non-null.
