### ISSUE TITLE
Cumulative Memory in UI should be converted to appropriate unit

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#4583]
Rather than always showing `GB`, it should be rounded to `TB`, `PB`, etc.

Example:

```
1,030,350.798GB seconds
```

**Comment by haozhun** [comment]
@electrum  This is a decision @raghavsethi and I made deliberately because it makes more sense to think about this as

    a few thousand seconds (multiplied by) 10-100 gigabytes (multiplied by) 10-200 machines

not

    a few seconds (multiplied by) a few petabytes

Therefore, we believed it's most useful to always use `GB seconds` as the unit.

**Comment by findepi** [comment]
I think `Cumulative Memory` is now converted to units. Therefore i am closing this as done.
