### ISSUE TITLE
Fast decimal proposal

### ISSUE THREAD

**Issue by sopel39** [prestodb/presto#4600]
We are planning to implement high performance decimals version so that decimals can be set as a default type for fixed point literals.
Here is our fast decimals proposal: https://github.com/facebook/presto/wiki/Fast-Decimal-Type. Please take a look.

FYI: @martint @dain @electrum @ilfrin @losipiuk @kokosing

**Comment by sopel39** [comment]
@martint @dain Could you take a look at the document? Basically in order to implement fast decimal we have to pass output `Slice` argument to scalar functions. Our benchmarks show that this is the only way to achieve `Slice` based decimal performance comparable with `BIGINT` (for smaller numbers).

To give you an idea take a look at an example `fastDecimalSum` operator. It would have signature: `void fastDecimalSum(Slice a, Slice b, Slice result)`. The operator doesn't have to instantiate `Slice` as a result, which greatly improves performance. In this approach, a set of temporary accumulator variables: `a1, .., aN` would be allocated before processing rows. Those would store intermediate calculation results. For instance sum of columns: `column1, column2, ... columnN` could be calculated as: `decimalSum(column1, column2, accumulator); decimalSum(column2, accumulator, accumulator); ...; decimalSum(columnN, accumulator, accumulator);`. `accumulator` would then store total sum result. We want to introduce such mechanism in Presto.

**Comment by cberner** [comment]
@sopel39 can you take a look at the way I optimized `ArrayConcatFunction`? It would allow you to have scratch space for a `Slice` which might work just as well as an out variable, and is already integrated into all the compilers.
I considered going with the out variable route you're proposing, but decided against it because it introduces a lot of complexity around how to invoke a function with an out variable.

**Comment by martint** [comment]
@cberner, that might not be sufficient if we want to optimize across function invocations.

**Comment by cberner** [comment]
It certainly might not, but I think it's worth benchmarking first

**Comment by sopel39** [comment]
@cberner. Yes, we want to optimize across function invocations. An example expression:
`(dec_col_a + dec_col_b) * (dec_col_c + dec_col_d)`.
Expression compiler would need to allocate two `Slice` accumulators for intermediate results: `acc_1`, `acc_2`.
Then the expression can be compiled into:
```
decimal_add(dec_col_a, dec_col_b, acc_1);
decimal_add(dec_col_c, dec_col_d, acc_2);
decimal_mul(acc_1, acc_2, result);
```
We want to introduce such feature into Presto.

**Comment by sopel39** [comment]
@cberner @martint: ping, are you OK with such feature in Presto?

**Comment by ilfrin** [comment]
@martint @dain per our conversation yesterday, please let us know if this path is acceptable. thank you. 
cc @cberner

**Comment by ilfrin** [comment]
bump :)

**Comment by losipiuk** [comment]
@martint can we go with implementation following @sopel39 proposal? Decimal performance is important to us as we want to make it default type ultimately. 
On the other hand we do not want to rework everything if you decide whole approach is wrong.

Sorry for being pain in the ass but this very important for us.

cc: @ilfrin

**Comment by martint** [comment]
I finally had time to review and think about this more (sorry for the delay). Here's my take on it:

For an expression like: `(a + b) * (c + d)`

The "out variable" approach would be expressed as:

```
Slice accumulator1 = ...
Slice accumulator2 = ...
Slice result = ...

add(a, b, accumulator1)
add(c, d, accumulator2)
multiply(accumulator1, accumulator2, result)

... do something with result...
```

The "instance methods" approach would be expressed as:

```
AddFunction add1 = ...
AddFunction add2 = ...
MultiplyFunction multiply = ...

Slice result = multiply.call(add1.call(a, b), add2.call(c, d))
```
 
Both approaches are very similar. The main difference boils down to clarity of who "owns" the lifecycle of the accumulators. The out-variable approach is a lot cleaner on this front -- there's no ambiguity about who's should/should not hold on to mutable objects and for how long. Also, it allows the code generator to reuse accumulators if it decides they are "dead" (analogous to register allocation in a traditional compiler)

I'm ok with this proposal, but watch out for some complexity implementing it:
- Where do the accumulators get allocated (they need to be fields in the processor) and who provides the instances
- What extra annotations do we need (at a minimum, something that indicates an argument is an "out" argument)
- Making the bytecode generator handle this new calling convention and making sure it fits seamlessly in expressions that mix both conventions.

**Comment by sopel39** [comment]
Thanks for comment @martint. You mentioned that:
> Where do the accumulators get allocated (they need to be fields in the processor) and who provides the instances

After discussion with @losipiuk and @arhimondr we argue that accumulators shouldn't be fields in `Processor`, but rather local variables in generated `process()` method. This is because JVM will optimize code and use stack for locally allocated accumulator. See: https://github.com/Teradata/presto/blob/fast_decimal/presto-main/src/test/java/com/facebook/presto/operator/scalar/DecimalBenchmark.java#L116
If I use preallocated accumulator there (from: https://github.com/Teradata/presto/blob/fast_decimal/presto-main/src/test/java/com/facebook/presto/operator/scalar/DecimalBenchmark.java#L87), then the performance drops by 25%. Memory address of local accumulator is always directly accessible from CPU registers. Also such accumulators make continuous space and do not trash CPU cache.

**Comment by martint** [comment]
That's even better, yes (as long as they are kept outside the loop).

**Comment by sopel39** [comment]
Impelemented

**Comment by kokosing** [comment]
Congrats!
