### ISSUE TITLE
Add nondeterministic identity UDF for testing

### ISSUE THREAD

**Issue by dain** [prestodb/presto#4655]
It would be helpful for testing and diagnosing problems to have an identity function that is marked as nondeterministic.  This function would need to be a parametric nullable function.  There is documentation on how to write a parametric function here:

https://github.com/facebook/presto/blob/master/presto-docs/src/main/sphinx/develop/functions.rst#parametric-scalar-functions

Also, the `element_at` function can be used as an example:

https://github.com/facebook/presto/blob/master/presto-main/src/main/java/com/facebook/presto/operator/scalar/ArrayElementAtFunction.java

The function should be named `nondeterministic` and marked as hidden. `DeterminismEvaluator` needs to be updated as well.

**Comment by lvijay** [comment]
is this still relevant now that presto has lambda support?
