### ISSUE TITLE
Migrate array less_than operator to new framework

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#4674]
See https://github.com/cberner/presto/commit/b0f94c381f61465779f909ed6592dfcd8fdbd01a for an example of how this is done. The code is in `ArrayLessThanOperator.java`

**Comment by cberner** [comment]
Pallavi is going to work on this

**Comment by pallavia7** [comment]
Created pull request https://github.com/prestodb/presto/pull/4883

**Comment by cpcloud** [comment]
I think this can be closed.

**Comment by haozhun** [comment]
@idemura This should be a simple enough task as your first task. It will also give you an understanding of how Presto implements sql functions.
