### ISSUE TITLE
Migrate array less_than_or_equal operator to new framework

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#4675]
See https://github.com/cberner/presto/commit/b0f94c381f61465779f909ed6592dfcd8fdbd01a for an example of how this is done. The code is in `ArrayLessThanOrEqualOperator.java`

**Comment by cberner** [comment]
Slavik is going to work on this

**Comment by viatk** [comment]
Implemented in https://github.com/prestodb/presto/pull/4827
