### ISSUE TITLE
launcher.py not compatible with python 3 and above

### ISSUE THREAD

**Issue by nika11** [prestodb/presto#4678]
When running launcher, the launcher.py raised a couple of errors. It seems like the launcher was written with python 2, which is not compatible with python 3. Is there a new version for the launcher?
- error
  ./launcher start
  File "/usr/local/presto/presto-server-0.139/bin/launcher.py", line 150
    except OSError, e:
  
  ./launcher start
  File "/usr/local/presto/presto-server-0.139/bin/launcher.py", line 269
    print 'Started as %s' % pid

**Comment by electrum** [comment]
The launcher was written to be compatible with Python 2.4, since (I believe) that's the version shipped in CentOS 5 and maybe other Linux distributions. Is there a way to make it compatible with ancient 2.4 and 3.0+?

**Comment by nika11** [comment]
By following the link http://python-future.org/automatic_conversion.html, I can convert the launcher.py to be compatible with Python 2 and 3 both. However, there still has one issue after used the 'futurize' utility described in the link:
Traceback (most recent call last):
  File "./launcher.py", line 451, in <module>
    main()
  File "./launcher.py", line 421, in main
    node_properties = load_properties(o.node_config)
  File "./launcher.py", line 49, in load_properties
    for line in load_lines(f):
  File "./launcher.py", line 58, in load_lines
    for line in file(f, 'r').readlines():
NameError: name 'file' is not defined

The reason is Python 3 doesn't support file(). Somehow, the utility missed to replace it. Then I manually replace file() with open() and the launcher.py can work now.

**Comment by harunurhan** [comment]
@nika11  I have this port which I am able to run with  both Python 3.4.4 and 2.6.6
https://gist.github.com/harunurhan/fdd54613ee1f27b49135

But I am not sure if it works with 2.4

**Comment by nika11** [comment]
I haven't tried with 2.4. However, it seems like the converter just did a syntax conversion not functional change. I assume it should be ok.

**Comment by damiencarol** [comment]
encoutered this bug here.
> $ python -V
> Python 3.6.0

>  bin/launcher start
>  File "/home/dcarol/presto-server-0.166/bin/launcher.py", line 38
>    except OSError, e:
>                  ^
> SyntaxError: invalid syntax

**Comment by djKooks** [comment]
I'm also facing with same bug.
```
$ python --version
Python 3.5.1
$ bin/launcher start
  File "/Users/kwangin/utils/presto-server-0.185/bin/launcher.py", line 38
    except OSError, e:
                  ^
SyntaxError: invalid syntax
```
Is there any updates?

**Comment by jthompson6** [comment]
This needs to be fixed in airlift, not this repo.

I made a PR:  airlift/airlift#614.

**Comment by ChethanUK** [comment]
is this issue still a problem?

**Comment by rschlussel** [comment]
It looks like this has been fixed and the issue just wasn't closed.  Are you still encountering problems?

**Comment by ChethanUK** [comment]
No, In my old docker file I had
```
ENV PYTHON2_DEBIAN_VERSION 2.7.13-2
RUN apt-get update && apt-get install -y --no-install-recommends \
		python="${PYTHON2_DEBIAN_VERSION}" \
	&& rm -rf /var/lib/apt/lists/* \
    && cd /usr/local/bin \
	&& rm -rf idle pydoc python python-config 
```

So, before removing just wanted to ask.

Why there is no official Docker Image?
