### ISSUE TITLE
Add support for DATE in ParquetRecordReader

### ISSUE THREAD

**Issue by dain** [prestodb/presto#4697]
`ParquetRecordReader` does not support `DATE` but `ParquetPageSource` does?  This can cause a lot of confusion for end users, so we should figure how to add support for `ParquetRecordReader` until `ParquetPageSource` replaces it entirely.

**Comment by dain** [comment]
@zhenxiao or @nezihyigitbasi  can one of you handle this?

**Comment by zhenxiao** [comment]
I could take a look

**Comment by nezihyigitbasi** [comment]
Both `ParquetHiveRecordCursor` and `ParquetPageSource` support `DATE`s now, so closing.
