### ISSUE TITLE
Queueing System v2

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#4742]
Goals:
* More control over resources used by a queue
* Better QoS guarantees
* More easily extensible 

Key Concepts:
* Resource Group: a resource group "owns" queries, accrues resource usage from those queries, and is roughly analogous to a "queue" in the current system. Limits are placed on groups, but do not cause query failure, instead new queries become queued (or are rejected if too many are queued).
* Selection Rule: a rule that routes a given query to a resource group.

Details:
* Resource groups may either be "top-level" or be a child of another group. 
* They may be created dynamically, just like queues are today (via the `${USER}` syntax), and the object that manages resource groups will be pluggable. 
* Resources in a resource group can be given a "sharing weight" which is used to divide resources between children, if the parent runs out of the resource. 
* Configurable queuing strategy per resource group? (fifo, lifo, priority queue)
* It is an error to set any limit higher than the limit of the parent group, and the limits may be adjusted at runtime.
* Limits on memory do not include "system" memory, and may be set lower than "query.max-memory". However, doing so will not cause the query to fail, as noted above.
* Limits on query concurrency and query queue depth act like they do today.

Limits can be placed on:
* Memory
* Concurrency
* CPU usage in a given interval. Soft and hard limit. Allowed concurrency degrades linearly to 0 between the soft and hard limit.
* Queued queries

The selection rules will also be pluggable, and will ship with a default implementation similar to the current queueing rules.

Resource groups will be displayed in the coordinator web UI.

Main differences from current system:
* Queues are now called "resource groups"
* Resource groups have an explicit parent, rather than an implicit one inferred from the queuing rules
* Resource groups form a tree, rather than a DAG
* Rule system is pluggable, instead of the whole queueing system

Explicit non-goals:
* Throttle, prioritize or otherwise modify the behavior of queries once they start executing
* Limiting based on network, or IO to/from connectors (these would be nice to have, but require significant work outside the queueing system)

**Comment by nezihyigitbasi** [comment]
@cberner this is awesome. Here are some features that I think may be nice to have, what do you think?
* Support modifying queue configuration during runtime (without coordinator restart).
* Show in the web ui the resource group that a query belongs to.
* It sounds useful to me to also have hard limits on memory/runtime/datasize (?) per resource group that causes queries in that group to fail if they go above these limits. This may be useful if both interactive and batch workloads share the same cluster and with this we can configure separate queues to define separate hard limits for resource usage.
* Be able to set the relative priority of splits (`priorityLevel` in `PrioritizedSplitRunner`) for queries across resource groups.

**Comment by cberner** [comment]
Definitely yes to the first two!

I think we do need a way to change hard limits on resource usage, but to avoid scope creep I don't plan to address that in this iteration. See the "Explicit non-goals" section :) 
Same for the last point, definitely a good feature, but it's probably big enough to be a whole project to implement priorities to differentiate background vs latency sensitive workloads

**Comment by cberner** [comment]
A bit more progress here: https://github.com/prestodb/presto/pull/5021

**Comment by cberner** [comment]
Initial refactoring: https://github.com/prestodb/presto/pull/5037

**Comment by RobinUS2** [comment]
Very interesting stuff. For our use case we need to have more granular controls which miss today. The updating of these queues through API will also help reduce the amount of presto restarts, which now need to occur fairly frequently.

**Comment by cberner** [comment]
Note to address from code review comments: should have a flag to enable JMX export for a group or groups

**Comment by cberner** [comment]
Also, we should log the resource group in the completion event, and provide it in the query info

**Comment by cberner** [comment]
This is mostly done now, and I've filed separate tasks for the two pieces which still need work
