### ISSUE TITLE
Presto Schema not correct when we use  "avro.schema.url"  properties  to create table in hive  .

### ISSUE THREAD

**Issue by 3h-william** [prestodb/presto#4756]
HiveMetaStore provide "client.get_schema" to get correct table schema from hive.
Presto only use "client.get_table" to get the "org.apache.hadoop.hive.metastore.api.Table" and then get  the MColumnDescriptor from this "Table" instance.

In our cases, we  use "avro.schema.url"  to create table , and update the schema file in hdfs.
Then this problems happened. 
When we run  "describe table" command in Presto ,the schemas is not correct . 
But we run   same command in hive, its correct.
This because Hive use "get_schema" function to get correct schema. 

Hive will do some special process in "get_schema" , such as bellow codes:

```
try {
      tbl = get_table_core(db, base_table_name);
    } catch (NoSuchObjectException e) {
      throw new UnknownTableException(e.getMessage());
    }
    if (null == tbl.getSd().getSerdeInfo().getSerializationLib() ||
      hiveConf.getStringCollection(ConfVars.SERDESUSINGMETASTOREFORSCHEMA.varname).contains
      (tbl.getSd().getSerdeInfo().getSerializationLib())) {
      ret = tbl.getSd().getCols();
    } else {
      try {
        Deserializer s = MetaStoreUtils.getDeserializer(hiveConf, tbl, false);
        ret = MetaStoreUtils.getFieldsFromDeserializer(tableName, s);
      } catch (SerDeException e) {
        StringUtils.stringifyException(e);
        throw new MetaException(e.getMessage());
      }
    }
```

**Comment by findepi** [comment]
There are two issues here.
- showing correct table schema -- i think this is fixed by https://github.com/prestodb/presto/pull/11289
- loading schema file from HDFS -- this is covered by https://github.com/prestodb/presto/issues/11548 as well, so let me close this one.
