### ISSUE TITLE
Migrate array_slice to new framework

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#4757]
See https://github.com/cberner/presto/commit/b0f94c381f61465779f909ed6592dfcd8fdbd01a for an example of how this is done. The code is in `ArraySliceFunction.java`

**Comment by cberner** [comment]
There should be tests in `TestArrayOperators`, if not add some

**Comment by cberner** [comment]
You can also do `RowToJsonCast.java` as a second one

**Comment by cberner** [comment]
As a more advanced task you can do `ArrayIntersectFunction.java` also, and then do performance optimizations for it. Take a look at `ArrayConcatFunction.java` which uses an instance variable to reduce memory allocations. The Presto engine will guarantee that your function is called in a single threaded fashion, so you should be able to cache the `leftPositions` and `rightPositions` arrays and reuse them to avoid allocation. Also for the `resultBlockBuilder` you can use an instance level `PageBuilder` like `ArrayConcatFunction.java` does

**Comment by cberner** [comment]
@geraint0923 is going to work on this

**Comment by cpcloud** [comment]
Looks like this has already been done.
