### ISSUE TITLE
Customized INSERT support for Amazon Redshift

### ISSUE THREAD

**Issue by LanceNorskog** [prestodb/presto#4767]
Amazon Redshift is a parallelized OLAP-oriented version of Postgres 8.0 operated as a service by Amazon Web Services. Redshift uses the Postgres syntaxes and JDBC protocol, but behaves very much like Hive. 

Using Hadoop infrastructure to prepare data for Redshift is a not-totally-obscure use case for Presto, especially Presto on EMR (Amazon's hosted Hadoop). The problem is that Redshift does not support the standard SQL INSERT syntax at network speed. The preferred method is to save table data into CSV files into S3 and tell Redshift to read from those. I have measured speed differences up to 100x between the two approaches.

For Presto to save data to Redshift tables at an acceptable speed, it needs a variant of the customized Postgres driver that coordinates a) writing temp files to S3, b) telling Redshift to load from those files, and c) deleting the temp files.

**Comment by LanceNorskog** [comment]
Is this an utterly terrible idea? What are the gotchas?

**Comment by electrum** [comment]
Do they have a JDBC driver that does this?

**Comment by electrum** [comment]
It probably wouldn't be difficult to make a Redshift connector using presto-base-jdbc (the base of the MySQL and PostgreSQL connectors) that works like this.

**Comment by lance-edmodo** [comment]
AWS has a special JDBC driver for Redshift but it does not give any support for this.

**Comment by LanceNorskog** [comment]
Closing. Redshift has faster INSERT now. I haven't tested how well it works for Presto.
