### ISSUE TITLE
Parquet dictionary-based filters can cause incorrect results

### ISSUE THREAD

**Issue by rdblue** [prestodb/presto#4778]
The Parquet read path will push predicates to the file format level and will avoid reading row groups based on column dictionaries. In some cases, Parquet will decide that dictionary encoding isn't optimal and will fall back to non-dictionary encoding for later pages. The current filter detects this case and doesn't filter the row group based on the dictionary, but the detection logic is flawed. This can cause Parquet to skip row groups when the dictionary can't match a predicate, even though later pages don't use the dictionary and do match, which results in incorrect query results.

*Details*: The fallback detection logic assumes that there are 3 encodings per column (for repetition, definition, and dictionary) and a 4th encoding (plain) indicates the column fell back to plain encoding. However, in some cases there are only 2 encodings listed because the repetition and definition levels use the same encoding. This happens for columns that are both required and not nested or for columns that have nesting and are optional.

*Work-around*: Turn off predicate push-down for Parquet with session property `parquet_predicate_pushdown_enabled` or Hive catalog property "hive.parquet-predicate-pushdown.enabled".

**Comment by nezihyigitbasi** [comment]
@dain @martint Can you please take a look when you have time as this is a correctness issue?

**Comment by cawallin** [comment]
Fixed in https://github.com/prestodb/presto/pull/4779
