### ISSUE TITLE
JDBC driver connection.getMetaData().getColumns(...) returns unexpected values

### ISSUE THREAD

**Issue by brian-rickman** [prestodb/presto#4797]
I ran across this while comparing the output from Simba's implementation of a JDBC driver for Presto to that of the open source driver.  Having consulted the JDBC documentation and Simba, I believe the open source driver is returning the wrong value for the following output columns: `type number`, `size`, `buffer length`, `decimal digits`, `nullable`, `is nullable`.

The Java code executed was: `connection.getMetaData().getColumns("hive", "default", "nation", null)`

## Here are the values the open source driver returns:
Column name (1) | type number (5) | size (7) | buffer length (8)| decimal digits (9) | nullable (11) | is nullable (18)
------------------- | ---------------- | ------ | ---------------- | ------------------ | ---------- | -------------- 
n_nationkey    | -5                 | 0      | 0                  | 19                   | 2           |
n_name          | -16               | 0      | 0                  |                        | 2           |
n_regionkey   | -5                 | 0      | 0                  | 19                   | 2           |
n_comment    | -16               | 0      | 0                  |                        | 2           |

## Here are the values that I believe are correct:
Column name (1) | type number (5) | size (7) | buffer length (8)| decimal digits (9) | nullable (11) | is nullable (18)
------------------- | ---------------- | ------ | ---------------- | ------------------ | ---------- | -------------- 
n_nationkey    | -5                 | 19    | 20                 | 0                   | 1           | YES
n_name          | 12               | 2048 | 2048             |                       | 1           | YES
n_regionkey   | -5                 | 19    | 20                 | 0                    | 1           | YES
n_comment    | 12               | 2048 | 2048             |                       | 1           | YES

## This is my test table:
    presto:default> describe hive.default.nation;
       Column    |  Type   | Comment
    -------------+---------+---------
    n_nationkey | bigint  |
    n_name      | varchar |
    n_regionkey | bigint  |
    n_comment   | varchar |
    (4 rows)

**Comment by electrum** [comment]
Thanks for looking at this! Some of these values were difficult to figure out and involved a lot of research including looking at what other drivers return, so it's good to have a second opinion.

**Comment by electrum** [comment]
Presto currently has no knowledge of nullability anywhere and certainly no way of communicating that to the driver. This doesn't mean that everything allows nulls, however, since you might have a connector that disallows nulls for a specific column, and thus attempting to insert into that table could fail. Thus, we return unknown:

NULLABLE: columnNullableUnknown - nullability unknown
IS_NULLABLE: empty string --- if the nullability for the column is unknown

**Comment by electrum** [comment]
The Javadoc for `getColumns()` says "BUFFER_LENGTH is not used", so 0 seems reasonable. Do you have other documentation or references for this field?

**Comment by electrum** [comment]
Where does 2048 come from for "COLUMN_SIZE"? Given those fields are unbounded-varchar values, they could definitely be larger than 2048.

I believe that we interpreted "COLUMN_SIZE" to only be valid for non-numeric types with a length (like varchar) and the JDBC code wasn't updated after the recent varchar changes, so it always returns 0.

**Comment by electrum** [comment]
Looking at this again, I do think we are handling numerics incorrectly. For example a `decimal(19,2)` should be
  COLUMN_SIZE = 19
  DECIMAL_DIGITS = 2

**Comment by electrum** [comment]
Regarding the data type of varchar, we return `LONGNVARCHAR` since that our varchar can hold international characters and be of any length. However, I'm open to changing it to `VARCHAR` since that is likely better from a compatibility standpoint.

**Comment by brian-rickman** [comment]
For `VARCHAR` columns, Simba uses 2048 for `BUFFER_LENGTH` and `COLUMN_SIZE`.  I will ask why they use this specific value.

I agree 0 is OK for `BUFFER_LENGTH` since the doc says it is unused.

If Presto doesn't know about the nullability of columns, then returning `UNKNOWN` is correct.

I understand your reason for using `LONGNVARCHAR`.  I would not want to break applications that store international characters, so perhaps it is best to leave this as-is.  It would be nice if the text description (`TYPE_NAME`) matched the enum used.  Right now it has `VARCHAR`.

Looks like this has narrowed down to only `TYPE_NAME`, `COLUMN_SIZE`, and `DECIMAL_DIGITS` needing adjustment.

**Comment by brian-rickman** [comment]
Simba is getting the value for `NULLABLE` by querying information_schema.columns:

    presto:default> describe hive.information_schema.columns;
          Column      |  Type   | Comment
    ------------------+---------+---------
     table_catalog    | varchar |
     table_schema     | varchar |
     table_name       | varchar |
     column_name      | varchar |
     ordinal_position | bigint  |
     column_default   | varchar |
     is_nullable      | varchar |
     data_type        | varchar |
     comment          | varchar |

    presto:default> select column_name, data_type, is_nullable from hive.information_schema.columns where table_catalog='hive' and table_name='nation' ;
     column_name | data_type | is_nullable
    -------------+-----------+-------------
     n_nationkey | bigint    | YES
     n_name      | varchar   | YES
     n_regionkey | bigint    | YES
     n_comment   | varchar   | YES

So is the value in this table wrong?

**Comment by electrum** [comment]
I think "type_name" is the name of the database type, as the database calls it, so it's correct since it is the "varchar" type in Presto.

**Comment by electrum** [comment]
The Javadoc for `TYPE_NAME` says "Data source dependent type name", so "varchar" seems correct, as that is what the type is called in Presto.

As far as using `VARCHAR` (12) vs `LONGNVARCHAR` (-16), I picked the latter because it seems to be the most technically correct type. However, from a compatibility standpoint, especially for existing JDBC applications, using the former could be better, so I'm fine going either way. Anything written specifically for Presto will understand what is supported.

Have you look at what other drivers, like for MySQL and PostgreSQL, return when used with a Unicode character set?

**Comment by electrum** [comment]
The `is_nullable` column in `information_schema.columns` is as correct-as-possible given the SQL standard only allows "YES" or "NO" for that column.

I recommend using the `system.jdbc` tables for the JDBC driver. These were added relatively recently (sometime last year) to remove all the complexity and decision making from the driver.

**Comment by electrum** [comment]
I also agree that we should have both drivers return the same metadata. We should also document why specific values are returned, given all the confusion around exactly what the various fields mean.

**Comment by brian-rickman** [comment]
I have not yet tried getColumns() in other systems with Unicode character sets, but I will add that to my to-do list.

Using the tables in `system.jdbc` will greatly simplify this task.  Thank you.

**Comment by ebd2** [comment]
I've also been in touch with Simba about the VARCHAR vs LONGNVARCHAR questions. They went with VARCHAR because historically, there hasn't been a consistent SQL mapping to LONGNVARCHAR.  Their postgresql driver does the same, for example. According to them, applications generally understand this mapping and they haven't run into i18n issues resulting from this choice.

**Comment by cawallin** [comment]
It looks like this PR covers most, if not all of this issue: https://github.com/prestodb/presto/pull/5564. @brian-rickman can you confirm?

**Comment by brian-rickman** [comment]
@cawallin I agree that PR covers it.
