### ISSUE TITLE
Comprehensive VARCHAR(x) implementation roadmap

### ISSUE THREAD

**Issue by arhimondr** [prestodb/presto#4813]
We did some invistigation of what have to be done in order to support the parametrized VARCHAR type system-wide.

In order to support the bounded VARCHAR we need to get done the next things

**Support VARCHAR(x) in Presto connectors**
1. JDBC connectors (MySQL, Postgree)
   - Return correct type for the VARCHAR(x) columns
   - Truncate values longer that the type in Metadata
   - Use the `Varchar.createUnboundedVarcharType()` explicitly for unbounded columns
2. Blackhole connector
   - Handle VARCHAR(x) columns
3. Cassandra connector
   - Check if cassandra has bounded VARCHAR columns
   - Use the `Varchar.createUnboundedVarcharType()` explicitly for unbounded columns
4. Raptor connector
   - Implement VARCHAR(x) support. Now all the columns are unbounded.
5. TPCH connector
   - Return VARCHAR columns as bounded VARCHAR(x) with the correct length. Airlift modifications might be required.
6. Hive connector
   - Varchar(x) is already supported. Values longer than `x` are already truncated. #4781 
   - Elimitate all the usages of the `VarcharType.VARCHAR` constant. Use explicit varchar type constructors instead.
   - Mostly all the usages of the `VarcharType.VARCHAR` constant are the `writeSlice`, `getSlice` and etc. invocations. Type object refference must be used in such places instead.
7. ExampleHTTP, JMX, Kafka, Redis connectors
   - Check whether it is possible to return VARCHAR type smaller than `unboundedVarchar`. For example for Redis column possibly VARCHAR(~64000) can be returned
   - Use the `Varchar.createUnboundedVarcharType()` explicitly for unbounded columns
   - Elliminate all the usages of the `VarcharType.VARCHAR`. Mostly all of them are `writeSlice`, `getSlice`, etc. method invocations.
8. System, Information schema tables
   - Return columns of correct VARCHAR(x) type.

**Functions and operators must accept VARCHAR(x) instead of unparametrized VARCHAR. Proper return type must be calculated instead of returning the unbounded VARCHAR**
1. StringFunctions
2. Approximate Count/Sum/Avarage/Set operators
3. ArrayJoin operator
4. RegexpFunctions
5. ColorFunctions
6. ConcatFunction
   - add support for literal variables calculation for variable arity functions
7. DateTimeFunctions
8. JsonFunctions, JsonOperators
9. MathFunctions
10. UrlFunctions
11. VarbinaryFunctions
12. LikeFunctions
13. TeradataDateFunctions, TeradataStringFunctions

After the operators and function refactoring support for unparametrized singnature for VARCHAR type must be removed.

**Other changes**
1. Use the `Varchar.createUnboundedVarcharType()` explicitly in Property declarations instead of `VarcharType.VARCHAR` constant
2. Check all the other `VarcharType.VARCHAR` constant usages. Replace it with more precise VARCHAR type or `Varchar.createUnboundedVarcharType()`.
3. Check all the other `StandardTypes.VARCHAR` constant usages. Generally at this step it should be used only for the base type for VARCHAR and in TypeRegistry methods.

As a **final step** the `VarcharType.VARCHAR` constant must be removed.

**Comment by arhimondr** [comment]
@dain @martint @electrum 
This is going to be a very big change. Only the `VarcharType.VARCHAR` is used in over thatn 1200 places. Is it better to separate this change in a several PR, or it is better to put all the changes into single consistent PR?

**Comment by electrum** [comment]
This type of change almost always needs to be done in small parts. Otherwise it's too hard to review, and you have to keep rebasing as things change.

**Comment by arhimondr** [comment]
@electrum Does this plan looks good to you?
If it does, from what do you think it is better to start?

**Comment by ilfrin** [comment]
+@martint @dain what's your opinion on this plan?

**Comment by martint** [comment]
This looks like a good plan. Let's try to do it in small steps as much as possible to make it easier to review and integrate.

I would probably focus on 6, 5, 1, 2, 4 and the functions first.

**Comment by ilfrin** [comment]
cool, thanks, we'll plan this out.

**Comment by cawallin** [comment]
VARCHAR support is in, closing.
