### ISSUE TITLE
format_datetime/parse_datetime docs incorrectly reference Java's SimpleDateTimeFormat

### ISSUE THREAD

**Issue by martint** [prestodb/presto#4817]
The documentation for format_datetime indicate the functions use Java's SimpleDateTimeFormat syntax. In reality, the implementation uses JodaTime's DateTimeFormat, which supports a different syntax.

Java: http://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
JodaTime: http://joda-time.sourceforge.net/apidocs/org/joda/time/format/DateTimeFormat.html

**Comment by yinghai** [comment]
Fixed in https://github.com/prestodb/presto/pull/5184
