### ISSUE TITLE
Presto allows modification of the metadata of other users' tables

### ISSUE THREAD

**Issue by nezihyigitbasi** [prestodb/presto#4848]
When I drop a table that is created by another user Presto fails with `Unable to drop ... owner of the table is different from session user`.  However, it's possible to do add/rename column and rename table on those tables.  What does the sql standard say about that, should those ops be denied too? If we should not allow these ops, I will be happy to provide a fix.

**Comment by dain** [comment]
That check in `com.facebook.presto.hive.HiveMetadata#dropTable` is legacy from when we didn't have security.  It should be removed or moved to `NoAccessControl`.  To move it we would have to add `HiveMetastore` to `NoAccessControl` so it could access the table metadata.  

@electrum what approach do you want to take?

**Comment by electrum** [comment]
I agree, we should remove the check now that we have security.

**Comment by nezihyigitbasi** [comment]
How about the `allowRenameColumn` and `allowRenameTable` checks in `HiveMetadata`? `allowRenameTable` is already in `NoAccessControl` so we can remove it, and I think we can move the other one to `NoAccessControl` too.

**Comment by nezihyigitbasi** [comment]
Just to confirm, do we want to remove the check below or move it to `NoAccessControl`?

```
if (!session.getUser().equals(table.getOwner())) {
    throw new PrestoException(PERMISSION_DENIED, format("Unable to drop table '%s': owner of the table is different from session user", table));
}
```

**Comment by electrum** [comment]
@nezihyigitbasi yes, we should move the check there. That whole module is legacy now that we have real security.

**Comment by nezihyigitbasi** [comment]
regarding the other part of my question, should we support the same check (whether the table belongs to the session user) for add/rename column and rename table operations?
