### ISSUE TITLE
Provide query size upper bound via max number of splits 

### ISSUE THREAD

**Issue by billonahill** [prestodb/presto#4868]
Our users have no idea how large the data is they're trying to query and they submit massive queries and wonder why they take a long time or fail. There have been discussions about how to support an upper bound based on data size, but that's hard to accurately measure.

I suggest adding a session property for the max number of splits (a proxy of data input size). The default could be `Long.MAX_VALUE` but an admin could dial that down. A user who hits that would get an error but could increase it as a session property if they know what they're doing.

**Comment by nezihyigitbasi** [comment]
Related #3733.
