### ISSUE TITLE
Presto support "lateral view explode"?

### ISSUE THREAD

**Issue by litao-buptsse** [prestodb/presto#4884]
I have a hive table with field type array<struct<f1:int,f2:string>>, I will use "lateral view explode" to process it in hive. But I found presto doesn't support "lateral view explode".
Does presto will support it in the future and how do I process the complex field right now?

**Comment by youngwookim** [comment]
https://prestodb.io/docs/current/migration/from-hive.html

> Presto supports UNNEST for expanding arrays and maps. Use UNNEST instead of LATERAL VIEW explode().

HTH

**Comment by litao-buptsse** [comment]
@youngwookim Thank you

**Comment by ivryan** [comment]
Do you have any suggestion to extract fields of exploded array of struct without explicitly write field by field in the query?
eg: select a.id,x.*
from table1
cross join unnest(my array of struct) t(x)

I.
