### ISSUE TITLE
Is Cassandra Thrift required?

### ISSUE THREAD

**Issue by ChrisFeldmeier** [prestodb/presto#4894]
Does Prestodb require Cassandra with Thrift to connect or is this optional?

**Comment by tzach** [comment]
@ChrisFeldmeier please reopen
Look like Presto do use Thrift on some cases (not all!)
See https://github.com/scylladb/scylla/issues/1139#issuecomment-231578297 for more details

**Comment by dain** [comment]
All connectors are optional.  If you don't want one, you can just delete it from the distribution.

**Comment by cawallin** [comment]
The Cassandra connector for Presto uses CQL if you are selecting less than cassandra.limit-for-partition-key-select partition keys (by default 200), but if you are selecting more than that, it uses Thrift to figure out how data is partitioned on Cassandra.

I'm going to close this issue.

**Comment by tzach** [comment]
@cawallin Thanks for clarifying this
