### ISSUE TITLE
Add skip CPU check regex to verifier

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#4911]
This should work similarly to `skipCorrectnessRegex` in `VerifierConfig`, but skip the CPU comparison between control and test. It should probably default to `(?i)(?s).*LIMIT.*`

**Comment by yinghai** [comment]
Hi, @cberner, I started working on this and I'm pretty new. Just to clarify, CPU comparison is to compare the CPU time between control and test?

**Comment by cberner** [comment]
yep
