### ISSUE TITLE
Support a pluggable authentication mechanism

### ISSUE THREAD

**Issue by nezihyigitbasi** [prestodb/presto#4914]
To support authenticating users against different systems it would be nice if Presto could support a pluggable authentication mechanism. A use case where this can be useful is to have IAM role support for S3 accesses (see #2640). A custom S3 authentication module will then authenticate the user using his/her IAM role and pass the principal back to Presto, which should be passed all the way down to the filesystem. /cc @martint based on our brief discussion at the meetup.

**Comment by dain** [comment]
Views in SQL execute as the owner if the view.  How would this work in this scenario where you do not have credentials for the view owner?

**Comment by nezihyigitbasi** [comment]
I think it should fail. If a user creates a view using an IAM role, another user shouldn't be able to access that view without providing the _same_ role. Otherwise every user will be able to access all the views that are created using different roles. What do you think?

**Comment by nezihyigitbasi** [comment]
I don't think we need this anymore (since we got #5667 in), so closing.
