### ISSUE TITLE
Remove usages of query stats for verifying input rows in tests

### ISSUE THREAD

**Issue by nileema** [prestodb/presto#4964]
Currently `QueryStats` are not guaranteed to be correct (updated) on query completion. We use query stats in `HivePartitioningTest.getProcessedLinesCount`  to get the input positions. 

Right now we do not have a reliable way to get this information, so we should possibly remove these tests.

**Comment by kokosing** [comment]
I will fix this.

**Comment by petroav** [comment]
@nileema I've played around with `QueryStats` and observed that intermittently it doesn't get updated correctly for a query. When I run into such a scenario it doesn't matter how long I wait, the stats never get updated. I was about to start investigating this. Is this a known bug? Or rather, do you know what the solution is and just haven't gotten around to implementing it?
