### ISSUE TITLE
Why presto become slower?

### ISSUE THREAD

**Issue by zhuqunzhou** [prestodb/presto#4967]
When i merge the small `hdfs` files into one `hdfs` file,I find `presto` become slower.

I search the `presto` task detail on `presto` `8080` web page,i find the `Bytes/s` and `Rows/s` become very slow.

I use `lzo` to compress my data.

Why?And if i change the compression format is useful?

**Comment by RobinUS2** [comment]
It sounds like there's fewer splits (~ files) than hosts, meaning that the query is too small to use the full concurrency of the cluster you have.

**Comment by zhuqunzhou** [comment]
@RobinUS2 ,Thank you.
I guess,Once i merge the small files,the number of splits is fileSize/min(max-split-size).But,if there are a lot of small files,each file will has one split at least,right?

So,when i set smaller max-split-size,i will have more splits? And is there any problem of more splits?

Thanks!

**Comment by electrum** [comment]
I don't think that lzo files are splittable.

**Comment by zhuqunzhou** [comment]
@electrum , @RobinUS2 , which files are splittable?Now,i want to speed up the search of big files,how i should to do??

Thank you!

**Comment by electrum** [comment]
We recommend using ORC or RCFile with the binary serde.

**Comment by zhuqunzhou** [comment]
@electrum ,My data are all from flume,but flume not recommended for use hive-sink in production,so i should store the data into hdfs,and create a external table.
If i change the data type to ORC type,i need to create a job,and the job's task is to use sql like 'insert into table(orc table) select * from old table' to change the file type.But my change type job's speed is slower than data into hdfs.  So ...
What am I to do?
Thank you!
