### ISSUE TITLE
Fix scheduling so that bucketing on Hive tables can be re-enabled

### ISSUE THREAD

**Issue by haozhun** [prestodb/presto#4973]
#4970 needs to be rolled back. Tests are available in #4972.

**Comment by haozhun** [comment]
It would also be worth double-checking that insertion into list bucketed and sort bucketed table is rejected

**Comment by haozhun** [comment]
Also add tests and verify correctness when empty bucket should exist

**Comment by johnnyaug** [comment]
Until that's fixed, is there a way to insert into Hive bucketed tables in Presto? Or should I just insert using Hive? Would very much like to see that fixed.

**Comment by haozhun** [comment]
This has been fixed a long time ago.
