### ISSUE TITLE
Handle hive.orc.use-column-names for empty files

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#4991]
The Hive ORC writer creates the output file lazily. If there are no rows, the `close()` method creates a file without any columns (newer Hive versions create a zero byte file). This causes issues for `hive.orc.use-column-names`.

We should fix the column handling code to account for these "empty" files.

Additionally, for non-bucketed tables, the writer code could delete the file if no rows written, since the files have no purpose.

**Comment by dain** [comment]
I think @haozhun's latest code fixes this

**Comment by kadaan** [comment]
How recent was this change done?

**Comment by haozhun** [comment]
I don't think I did anything with this. But I believe I definitely need to double check this for the correctness of bucket writer.

**Comment by kadaan** [comment]
I have the fix for this.  It is small and I will submit it after testing.
