### ISSUE TITLE
[presto-cli] shutdown hook cannot cancel the running query occasionally

### ISSUE THREAD

**Issue by nezihyigitbasi** [prestodb/presto#5005]
The shutdown hook added in #3521 sometimes cannot cancel the query properly. I have tracked down the problem to the following two issues:
- In `StatementClien.advance()` loop, if an interrupt is received in the `httpClient.execute()` call  in the exception handler I see that we correctly receive an `InterruptedIOException`, but the interrupt flag is somehow not set (a bug somewhere else?), so the query doesn't get canceled and the loop just goes on.
- In `StatementClient.close()` we do an async http call and there is probably a race where the main thread closes the http client (in `QueryRunner.close()`) and the other thread doing the http call fails silently (we are not checking the status of this call).

For the first problem I currently handle `InterruptedIOException` as a special case and close the client (and also interrupt the main thread). For the second one I just do a synch. http call to get rid of the race. With these changes I cannot reproduce this problem anymore. 

@electrum any thoughts?

**Comment by electrum** [comment]
`InterruptedIOException` is weird: most of the time it's just a normal `IOException`, but sometimes it needs to be treated as `InterruptedException`. So that could be why the flag isn't set.

Those fixes sound reasonable, though we want a reasonable timeout (like 2-5 seconds) if the server is unreachable, so either use `executeAsync` with a timeout waiting for the response future, or set request timeout for the HTTP client to be lower (or both).

**Comment by electrum** [comment]
I just set the connect and request timeout to 5 seconds in #5007 (the default request timeout is 5 minutes which is way too long for the CLI).

**Comment by electrum** [comment]
So using a regular `execute()` should be fine here.

**Comment by nezihyigitbasi** [comment]
@electrum awesome, thanks. Will create a PR shortly.

**Comment by brian-rickman** [comment]
I've noticed that it is impossible to cancel a query once it starts returning data to the client.  This is easy to reproduce in the cli with a query like "select * from tpch.sf1000.lineitem".  If I press CTRL-C immediately after submitting the query, it is canceled properly.  If I wait until the query starts returning data and then hit CTRL-C, the client acts as if the query was canceled, but I can see in the web UI that Presto is still executing it.  The server continues processing the query until a timeout occurs.

Is that likely to be related to this issue or should I file a new ticket for it?

**Comment by nezihyigitbasi** [comment]
@brian-rickman I have an open PR (#4720) for that.
