### ISSUE TITLE
testSelectPartitionedHiveTableDifferentFormats is flaky

### ISSUE THREAD

**Issue by raghavsethi** [prestodb/presto#5019]
Just ran this test on my box 200 times, and saw no failures. However, Travis keeps randomly failing on this test. I'm also not sure what it's really meant to test.

**Comment by raghavsethi** [comment]
cc @arhimondr

**Comment by kokosing** [comment]
@raghavsethi This https://github.com/prestodb/presto/pull/4981 addresses your issue.

Here is an explanation of what this test does (copied from my discussion with @nileema):
```

the main idea behind this tests was to have a coverage for partition pruning

[6:36] 
Using query stats gave information how much data was read

[6:39] 
so when you had partitions A (1kB) and B (1kb), you do a query `select * from t where t.c = A` , then you could check with query stats how much data was read, if 1kB then test assumed that only partition A was read (B was pruned).
```
