### ISSUE TITLE
Map type literal syntax

### ISSUE THREAD

**Issue by cpcloud** [prestodb/presto#5065]
When writing literal `MAP`s with more than a few fields, my queries become very difficult to read, especially if the values of the map are complex.

```
MAP(ARRAY[<all of the keys>], ARRAY[<all of values values>])
```

Even if I break up the keys and values into separate lines, when reading the query I have to manually associate which key maps to which value.

Is there room for a literal syntax for `MAP`s in Presto?

After perusing the SQL standard, I can't find anything that says "Don't add custom syntax" (of course, this doesn't mean we _should_ add it), but I would love to get thoughts on making it easier to read more complex map constructions.

Personally, I'm a fan of the syntax of Python's [dictionary views](https://docs.python.org/2/reference/expressions.html#displays-for-sets-and-dictionaries):

``` sql
SELECT {'a': SUM(stuff), 'b': AVG(other_stuff)}
```

But I'd settle for anything that makes complex maps more readable.

**Comment by martint** [comment]
We've talked about it in the past, and we're not against adding new syntax as long as:
- it doesn't conflict with anything else in the SQL language
- has a similar syntactic "feel" to other constructs
- has consistent semantics with other constructs

We haven't done a thorough analysis of alternatives or settled on a specific syntax, though.

(FWIW, we'll add lambda expression syntax in the near future even though it's not in the standard: `SELECT transform(ARRAY[1,2,3,4], x -> x * 2)`)

**Comment by martint** [comment]
One additional option that doesn't require special syntax (introducing a function `map` that takes a variable number of arguments of type ROW(K,V) and returns a MAP(K,V))

`map(('a', 1), ('b', 2), ('c', 3))`

**Comment by brian-rickman** [comment]
I like this option.  Much easier to read.

**Comment by cpcloud** [comment]
@brian-rickman

> I like this option. Much easier to read.

Check out the other proposed syntaxes in #5133. I'll post those options here too.

**Comment by brian-rickman** [comment]
Thanks.  I'd be OK with anything that puts each key/value pair together, i.e. key:value, (key,value),  key=>value, key->value, key=value.  I find the  current system of parallel arrays difficult.  Among the choices listed in #5133, I'd be inclined to go with whatever was easiest to implement.

**Comment by cpcloud** [comment]
Most of them are easy to implement. I think the decision will boil down to core devs + community desires.

**Comment by cberner** [comment]
I would be in favor of map(('key', 1), ('key2', 2)). That seems the most
standard as it doesn't involve special syntax

**Comment by cpcloud** [comment]
Are there any examples of variadic functions that use the new UDF framework?

**Comment by cberner** [comment]
Variadic functions can't be implemented purely using annotations at the
moment. They have to be implemented using byte code generation, like
ArrayConstructor

**Comment by cpcloud** [comment]
@cberner Would it be worth it and feasible to add the ability to implement variadic functions using annotations?

**Comment by cberner** [comment]
If we can find a performant way to do it, definitely! However, making it perform well it non-trivial. If we went the Java route of allowing things like:
```
@SqlType("bigint")
public static long greatest(SqlType("bigint") long...)
```
It would result in the arguments being packed into an array which would have major performance implications, especially when the number of arguments is small

**Comment by raghavsethi** [comment]
@cberner @cpcloud What's the status of this discussion/PR? Are we going to move forward, or can we close both?

**Comment by martint** [comment]
We should keep open. It's not super high priority, but it's something we may want to add at some point.
