### ISSUE TITLE
Add support for filtered aggregation syntax

### ISSUE THREAD

**Issue by martint** [prestodb/presto#5085]
From the SQL spec:

```
<aggregate function> ::= <...> [ <filter clause> ]

<filter clause> ::=  FILTER <left paren> WHERE <search condition> <right paren>
```

> A `<filter clause>` shall not contain a `<query expression>`, a `<window function>`, or an outer reference.
> 
> 2) Let `T` be the argument source of AF.
> 3) a) If `<filter clause>` is specified, then the `<search condition>` is effectively evaluated for each row of `T`. Let `T1` be the collection of rows of `T` for which the result of the `<search condition>` is `True`.

The following query:

``` sql
SELECT agg(x) FILTER (WHERE f(y))
FROM t
```

is semantically equivalent to this query if the aggregation ignores nulls:

``` sql
SELECT agg(if(f(y), x))
FROM t
```

If the aggregation is sensitive to nulls, the filter need to be applied before the values are fed into the aggregation function. This could be achieved via the "masking" mechanism supported by aggregation operators.

**Comment by martint** [comment]
This is now supported.

**Comment by aewhite** [comment]
Is this feature documented anywhere? I only found it because https://stackoverflow.com/questions/55504820/presto-filter-array-of-rows-inside-aggregation
