### ISSUE TITLE
Feature request: SHOW SCHEMAS [ LIKE pattern ]

### ISSUE THREAD

**Issue by erwa** [prestodb/presto#5092]
Hive supports [`SHOW DATABASES LIKE 'PATTERN';`](https://cwiki.apache.org/confluence/display/Hive/LanguageManual+DDL#LanguageManualDDL-ShowDatabases). It would be nice if Presto supported something similar: `SHOW SCHEMAS LIKE 'PATTERN';`. I see that [SHOW TABLES](https://prestodb.io/docs/current/sql/show-tables.html) already supports a `[ LIKE pattern ]` clause, so hopefully it won't be too hard to extend that to `SHOW DATABASES` as well.

**Comment by harunurhan** [comment]
I will try this, also it is not mentioned here but I suppose we wouldn't need `SHOW CATALOGS LIKE 'PATTERN'` since it is unlikely to have as many catalogs as schemas.

**Comment by electrum** [comment]
It's fine to have it for both (and makes it more consistent).

**Comment by yuananf** [comment]
fixed by #5097
