### ISSUE TITLE
Redshift support

### ISSUE THREAD

**Issue by Huangsir** [prestodb/presto#5140]
Does presto will support redshift?

**Comment by harunurhan** [comment]
I have never tried but you can connect to redshift via postgresql connector. However you may face performance issues and problems.

https://groups.google.com/forum/?hl=en#!searchin/presto-users/redshift/presto-users/Pj-ta_FO0OQ/hLZw8Bs0aMQJ

**Comment by Huangsir** [comment]
thanks~
