### ISSUE TITLE
Getting different plans for the same join query

### ISSUE THREAD

**Issue by nezihyigitbasi** [prestodb/presto#5147]
For the same query that involves multiple joins I get two different plans. [Here](https://gist.github.com/nezihyigitbasi/a082fed4e65b8149a7e375c93547bac6) is the first plan, and [here](https://gist.github.com/nezihyigitbasi/0243875115b58fb49716d1b25901875a) is the second plan. In the first plan two fragments do the join while in the second plan only a single fragment does the join.

**Comment by nezihyigitbasi** [comment]
I still see this issue with the latest master, any plans to address this? /cc @martint @cberner

**Comment by cberner** [comment]
I don't think anyone at Facebook is actively working on this. We've seen various cases where the planner is non-deterministic, mainly due to things like relying on iteration order of collections

**Comment by ArturGajowy** [comment]
@nezihyigitbasi @cberner #6771 should have fixed that, at least for all queries from AbstractTestQueries. Please reopen this issue if there are still cases where this happens.

**Comment by ArturGajowy** [comment]
@nezihyigitbasi I ran `TestQueryPlansDeterministic` tested with
```
select a.nationkey from nation a, nation b, nation c , nation d where a.nationkey = c.nationkey and a.nationkey = b.nationkey and a.nationkey = d.nationkey
```
(same as your query % table and column names) and it passed, so I'm pretty sure that is fixed.
