### ISSUE TITLE
Add functions which convert time/timestamp to different timezone

### ISSUE THREAD

**Issue by geraint0923** [prestodb/presto#5162]
Currently Presto has `AT TIME ZONE` syntax take a time/timestamp and a string or time interval **literal** to convert the time/timestamp. We don't need to change the semantics of `AT TIME ZONE`.

Instead, we only need to rename the existing functions. make them public, and update DesugaringOptimzer to rewrite `AT TIME ZONE` as renamed functions.

**Comment by tglstory** [comment]
I will attempt this.

**Comment by tglstory** [comment]
So as of right now, `AT TIME ZONE` converts a time/timestamp which is in zone `A` to the same time, but in a different zone `B`. Isn't this already converting time/timestamp to a different timezone? what exactly needs to be achieved for this issue?

**Comment by geraint0923** [comment]
Yeah, `AT TIME ZONE` has already worked, and it is translated into internal functions `at_timezone` in
https://github.com/prestodb/presto/blob/c7bf63a2138c2e61f0edb307cefbf6b35fba25c2/presto-main/src/main/java/com/facebook/presto/operator/scalar/DateTimeFunctions.java#L217, but it is hidden, and only used internally.

What needs to be done is to rename these functions and open these functions to all SQL users.

@martint Could you please suggest a new name for these functions? Thanks!

**Comment by tglstory** [comment]
got it. I'll get to work when the new names are suggested.

**Comment by hoodja** [comment]
I just stumbled on the need for this, and I'm willing to give it a try. Is there a place to review project norms, guidelines, or setup instructions? (I'm a noob)

**Comment by findepi** [comment]
@martint can we make `at_timezone` public?
(for the record, some people are already using it anyway https://stackoverflow.com/a/52446806/65458 ...)

**Comment by dain** [comment]
@findepi, I think we should and document it.  Alternatively, we could allow expressions in that place of the grammar, but I'm sure of the implications of a change like that.

**Comment by MrPanchoso** [comment]
Why isn't this function in the documentation then? Spent a good 10-15 minutes before figuring this one out.
