### ISSUE TITLE
Kafka order by _partition_offset

### ISSUE THREAD

**Issue by 0x0ece** [prestodb/presto#5177]
In the Kafka connector it would be nice if the order by _partition_offset desc could be "pushed down", relying on the fact that Kafka partitions are ordered.

Example use case, reading the latest 10 messages in Kafka:

```
select * from mytable order by _partition_offset desc limit 10;
```

Any plan to support that? Thank you! E.

**Comment by jeffreybreen** [comment]
A subtlety is that you'll only be able to push down the ORDER BY if the clause includes both `_partition_id` and `_partition_offset`. (And is ascending? Not sure...) To be fair, this is probably what people intend if they're specifying such a sort, but it's not what's given as an example.

As written, that query could include records from multiple partitions so you would actually need to do the sort. I think the best you can count on in that scenario would be an optimized merge-join based on the fact that the subsets (partitions) are sorted (by offset).

**Comment by ecesena** [comment]
I fully agree, and probably supporting the simpler case where the user specifies both `_partition_id` and `_partition_offset` is enough to start.

My example was kind of desired. The expectation is that you push down the limit to all partitions, then you sort, then you limit again. Here the result isn't particularly significant, but the push down of the limit can have a big performance impact.

**Comment by electrum** [comment]
@martint could this be done somehow with table layouts, so the TopN operator would just do a merge sort?

**Comment by martint** [comment]
@electrum, yes, if the connector indicates the outputs are sorted by that column (within each partition) and if the TopN operator is updated to support it (plus, all the required planner changes to choose that variant of the operator, etc).

**Comment by martint** [comment]
Actually, the TopN operator probably doesn't even need to change. The optimizer just needs to be made aware of the properties and instead of producing a final TopN over a partial TopN for each partition, it would produce a final TopN over a Limit.
