### ISSUE TITLE
Integrate resource groups into web UI & provide an API

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#5194]
Follow up from https://github.com/prestodb/presto/issues/4742

**Comment by go2starr** [comment]
Suggestions:

1. Filter the main presto landing page (active queries) to only those queries running in a given resource group
2. Resource group stats (active/queued queries, capacity, etc.)
3. Resource group (recent) history; queries run w/ start/end/usage info

**Comment by nezihyigitbasi** [comment]
@cberner are you still working on this?

**Comment by cberner** [comment]
@nezihyigitbasi not really. I've been doing a bunch of other things. If you're interested, free feel to take it on! Otherwise, I'll get to it eventually, but that might be next year

**Comment by nezihyigitbasi** [comment]
Another related PR is #6483, which provides a read-only REST interface to the resource groups (+ reloadable `FileResourceGroupConfigurationManager`)
