### ISSUE TITLE
Convert JDBC type BLOB to Presto type VARBINARY in JDBC connector

### ISSUE THREAD

**Issue by youngwookim** [prestodb/presto#5248]
As of now, Presto skip the columns which are BLOB in JDBC connector with Oracle database. If Presto convert the BLOB to VARBINARY, It would be useful to handle database's binary types.

**Comment by sajjoseph** [comment]
I created an oracle connector where BLOB is converted to VARBINARY. A PR request will be created shortly. If you are still in search of this capability, check the code base here - [https://github.com/sajjoseph/presto/tree/master/presto-oracle](https://github.com/sajjoseph/presto/tree/master/presto-oracle)

**Comment by youngwookim** [comment]
@sajjoseph, Sounds good to me! Thanks for your efforts.
