### ISSUE TITLE
Support pluggable query event listeners

### ISSUE THREAD

**Issue by martint** [prestodb/presto#5254]

**Comment by haowu-alation** [comment]
Hi, I have a few questions:
1. When is this ticket going to be done approximately? Or totally no idea?
2. After this feature is added, to log all presto queries, the Presto users need to write a pluggable query event processor (logger) by theirselves and rebuild the Presto from source code? 
3. If 2 is true, is there any default built-in all-query logger to use without rebuild the Presto from source?

**Comment by raghavsethi** [comment]
Working on it here: https://github.com/prestodb/presto/pull/5372
When it is done, you will be able to drop in your own logging stuff without having to rebuild Presto.
