### ISSUE TITLE
Secure JDBC connection with Presto

### ISSUE THREAD

**Issue by sumitkulkarni** [prestodb/presto#5292]
Hi, I want to create secure JDBC connection with presto. Please help me out on this. 
Where should I put code to authenticate user and password which is coming from presto-jdbc driver? 
Which is the better way to do this?

**Comment by electrum** [comment]
The JDBC driver does not yet support security.

**Comment by akshatnair** [comment]
For now you can use the free JDBC drivers that are available on http://teradata.com/presto. Until security options are added to the open source JDBC version you can get it with these new drivers.
These drivers are free but not open sourced.

**Comment by sumitkulkarni** [comment]
Ok thank you.
