### ISSUE TITLE
How to solve protocol message was too large?

### ISSUE THREAD

**Issue by zhuqunzhou** [prestodb/presto#5301]
I use `presto` to search data(`orc` format) from `hdfs`.But i get an exception:

    com.facebook.presto.spi.PrestoException: 
    Error opening Hive split hdfs://xxx.snappy (offset=22717665, length=4543533): 
    Protocol message was too large.  May be malicious.  
    Use CodedInputStream.setSizeLimit() to increase the size limit. 
 
And how i to change the size limit.Rebuild the presto source and add `CodedInputStream.setSizeLimit()`?

**Comment by maciejgrzybek** [comment]
This should be posted on mailing list, not as an issue on Github.

**Comment by KamalNayak07** [comment]
I am also facing the same issue.  if you found any fix. please let me know.
