### ISSUE TITLE
Remove presto-hive-hadoop2/conf/files/words

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#5310]
The Hive `create-test.sql` script first needs to create a table with 100 rows, which is then used to create the other test tables. The only way to do this in Hive (that I know of) is to load an existing file from disk. The file `/usr/share/dict/words` was chosen rather arbitrarily as something that existed by default in a known location on most Linux distributions and had a sufficient number of lines. It definite should not be checked into the Presto source tree.

**Comment by electrum** [comment]
@sopel39 if you want to take this, it will balance out the added / deleted lines stats :)

**Comment by sopel39** [comment]
https://github.com/prestodb/presto/pull/5326
Damn, I thought I will be 3rd largest contributor. It wasn't intentional though :)
