### ISSUE TITLE
Support for char type in Presto

### ISSUE THREAD

**Issue by sopel39** [prestodb/presto#5320]

**Comment by sopel39** [comment]
FYI: @martint @ilfrin @arhimondr 

We plan to add support for `CHAR(x)` type to Presto. There are some implementation choices and proposed roadmap.

How we should represent char types internally? Should char be fixed length or variable length as `VARCHAR`?
We opt for variable length like varchar. Otherwise fixed length `CHAR` would have to account for non-ASCII characters. Therefore `CHAR(x)` would have to allocate `4*x` bytes of memory.

Should there be support for ASCII only `CHAR`? Such char could be fixed length. ASCII chars are typically used as enum values (e.g. values: `Y`, `N).

The roadmap is as follows:
- Add char type to core Presto.
- Add char type operators
- Allow char to be coerced to varchar. Coercion from char to varchar trims trailing spaces (e.g. like Postgres)
- Add support for char in Hive
- Add missing function for char type
- Add support for MySQL and Postgres

**Comment by maciejgrzybek** [comment]
I suggest implementing operators after coercion because when coercion is done you can parallelize other tasks.
Char with coercion will be a fully usable type (not best performing but usable) and could be harmlessly added to connectors even without native operators.

**Comment by maciejgrzybek** [comment]
I see description was changed and became aligned with my comment (https://github.com/prestodb/presto/issues/5320#issuecomment-220403502) which made it outdated.

**Comment by losipiuk** [comment]
@martint please give this a read and let us know what you think. We can chat over hangout/slack/... to discuss details.

**Comment by sopel39** [comment]
Here are more details about proposed `CHAR` type (based on https://mariadb.com/kb/en/sql-99/07-character-strings/):

Unbounded char:
`CHAR = CHAR(1)`

There should be some maximum char length. It shouldn’t be too long because it will be impossible to process such rows in JDBC client or CLI. 

Example expressions:
```
q: CAST('a' AS CHAR(5))
r: 'a    '  <- char of fixed length 5
```
```
q: CAST(CAST('a' AS CHAR(5)) AS VARCHAR(10))
r: 'a    '  <- varchar(10), value has length 5
```
```
NO PAD
q: CAST('a' AS CHAR(10)) = CAST('a' AS CHAR(5))
r: FALSE
```
```
PAD SPACES
q: CAST('a' AS CHAR(10)) = CAST('a' AS CHAR(5))
r: TRUE
```
```
PAD SPACES
q: CAST('a' AS VARCHAR(5)) = CAST('a ' AS VARCHAR(10))
r: TRUE
```

@martint could you review this issue?

**Comment by martint** [comment]
The proposal looks good in general.

One question:

> Return VARCHAR with trailing spaces for CHAR columns in Hive connector (might be Teradata only)

Is this even necessary? Why not skip it and add proper support for CHAR once the engine understands that type (i.e., the item "Return CHAR columns from HIVE connector as Presto CHAR type.")


> Unbounded char:
> CHAR = CHAR(1)

To clarify, CHAR without length is not *unbounded*. It's syntactic sugar for length = 1 (unlike how `varchar` vs `varchar(n)` are really different types).

From the spec:

```
<character string type>` ::=
    CHARACTER [ <left paren> <character length> <right paren> ]
  | CHAR [ <left paren> <character length> <right paren> ]
  ...

<character length> ::=
  <length> [ <char length units> ]

<char length units> ::= CHARACTERS | OCTETS
```

> 5) If `<length>` is omitted, then a `<length>` of 1 (one) is implicit.
> 6) If `<char length units>` is specified, then the character repertoire of the explicit or implicit character set of the character string type shall be UCS.

**Comment by losipiuk** [comment]
>Return VARCHAR with trailing spaces for CHAR columns in Hive connector (might be Teradata only)
>>Is this even necessary? Why not skip it and add proper support for CHAR once the engine understands that type (i.e., the item "Return CHAR columns from HIVE connector as Presto CHAR type.")

Yeah. We might skip that. Depending on how fast development will go. And even if we decide to do that step we may not put it in master and just keep it on our temporary release fork.

**Comment by cberner** [comment]
@sopel39 I spent a while discussing this with @martint, @dain, and @electrum. There seem to be a variety of issues that make this hard to implement the semantics around padding and coercions. Could you schedule a meeting with us to discuss how this will work?

**Comment by sopel39** [comment]
What earliest time tomorrow suites you? I would also like @fiedukow to join.

**Comment by sopel39** [comment]
@cberner @martint How about meeting at 8AM tomorrow (10th August)? Would that suite you?

**Comment by sopel39** [comment]
@cberner @martint How about meeting at 8AM tomorrow (10th August)? Would that suite you?

FYI: @fiedukow

**Comment by cberner** [comment]
@sopel39, @martint is at the Teradata meetup in LA until very late tonight, and then I'm on vacation Thurs & Fri. How about 8:30am Pacific Time next Monday (Aug 15th)?

**Comment by fiedukow** [comment]
8.30 AM Pacific Time Aug 15th seems ok for me. @sopel39 is now on vacation till 22 Aug. We can continue without him or wait for him - whatever you prefer.

**Comment by cberner** [comment]
Either way is fine for me. What @martint and I wanted to discuss is mainly how much `char(x)` and collation functionality you guys need and how to fit it into Presto, as it is looking like a fairly complicated feature to implement. If you have enough context about that then the 15th seems good, otherwise we can wait for @sopel39.

**Comment by fiedukow** [comment]
I think we can go with 15th than.

**Comment by cberner** [comment]
Sounds good to me

**Comment by sopel39** [comment]
Impelemetned
