### ISSUE TITLE
OVER ... ROWS between UNBOUNDED PRECEDING AND n PRECEDING returns incorrect results

### ISSUE THREAD

**Issue by ebd2** [prestodb/presto#5322]
The same issue applies to OVER(... ROWS BETWEEN n FOLLOWING AND UNBOUNDED FOLLOWING).

The actual behavior is:
```
presto:tiny> select nationkey, sum(regionkey) over (rows between unbounded preceding and 2 preceding) from nation limit 5;
```
 nationkey | _col1 
-----------|-------
         0 |     0 
         1 |     0 
         2 |     0 
         3 |     1 
         4 |     2 

The expected behavior is that this matches the behavior of the following:
```
presto:tiny> select nationkey, sum(regionkey) over (rows between 3 preceding and 2 preceding) from nation limit 5;
```
 nationkey | _col1 
-----------|-------
         0 | NULL  
         1 | NULL  
         2 |     0 
         3 |     1 
         4 |     2 

Postgresql matches the expected behavior and returns NULL for the first two rows. The removal of the first row.

The part of the SQL 2011 standard addressing the window clause is 7.11. The following references are in the General Rules section of that part.

In the case when the first row is the current row (nationkey == 0), the first row (nationkey == 0) should be removed from the window frame per rule 5.b.ii.2.C.II, and is specifically covered by Note 223.

In the case when the second row is the current row (nationkey == 1), the first row (nationkey == 0) should be removed from the window frame per the same rule. The current/second row (nationkey == 1) is removed per Note 223 as above.

**Comment by electrum** [comment]
Fixed by 8ee399d66887f2980a55dc3d043972983dfbd091
