### ISSUE TITLE
suspicious  output_data_size and raw_input_data_size of  presto 0.145 ,it may be a bug?

### ISSUE THREAD

**Issue by VIPchengcheng** [prestodb/presto#5330]
I have run the same sql in presto 0.118 and 0.145 respectively. to our surprise , the performance of 0.145 is much worse than 0.118 for this SQL. I checked details of SQL execution carefully, found two suspicious points in 0.145.  pls check the attachment "difference-0.118-0.145.jpg" for details.
1.  output_data_size of 0.145 is so bigger than raw_input_data_size of 0.145 , also is so bigger than output_data_size of 0.118, and I found that the output of stage have duplicated columns in 0.145.  (Output layout: [brand_id, uid_0, brand_id, $hashvalue_362, $hashvalue_362);  I guess duplicate columns  is the reason why Output_data_size is so huge;
2. raw_input_data_positions is the same ,but raw_input_data_size is too different;
   Do you known these issues ?how to solve them?

![difference-0 118-0 145](https://cloud.githubusercontent.com/assets/18230274/15433767/447fd948-1ee6-11e6-9f08-b2e1ad1597e7.jpg)

**Comment by cawallin** [comment]
@VIPchengcheng Sorry for the late response. If this is still an issue for you, can you try against the most recent version of Presto (0.170)? There have been a lot of performance improvements since 0.145. Feel free to re-open if you're still having issues.
