### ISSUE TITLE
Parsing time-stamp

### ISSUE THREAD

**Issue by balajeeu** [prestodb/presto#5354]
Is it possible parse time stamp '28-JAN-16 11.45.46.421000000 PM' in presto.
I tried it with following query
`select date_parse('28-JAN-16 11.45.46.421000000 PM','%d-%b-%Y %l.%i.%s.%f %p');`
Error
`Invalid format: "28-JAN-16 11.45.46.421000000 PM" is malformed at "000 PM"`
I get this time stamp format from oracle db.

**Comment by christingh** [comment]
have comparable performance to benchmarkAddExactSliceSmallDecimalWithCondition and benchmarkAddExactSliceSmallDecimal. This confirms that it is possible to have fast dual (as long or four integers) representation of decimals in Slice.
benchmarkAddExactSliceSmallDecimal is about twice as fast as benchmarkAddExactSliceSmallDecimalNoAccumulator. This ,!

**Comment by maciejgrzybek** [comment]
@balajeeu We don't support submicrosecond precision, nor MySQL and PostgreSQL do.
Frankly, we only process up to milliseconds parsed from the string, everything beyond them is truncated.

@martint: Should we extend parsing to at least not error out for nanoseconds (behave the same way we behave currently for microseconds - truncate them but allow as an input)?

**Comment by balajeeu** [comment]
@maciejgrzybek  It would be great if you allow the input and truncate the nanoseconds

**Comment by maciejgrzybek** [comment]
I think the only way to achieve this currently is to change parsing dates. It's simple change but let's @martint speak about it. If he agrees, I can prepare patch momentarily.

**Comment by martint** [comment]
`date_parse` is meant to be compatible with MySQL. If that's how it behaves, then I think it's a reasonable change.

**Comment by maciejgrzybek** [comment]
@martint:
```sql
mysql> select str_to_date('1970/02/03 11:12:13.123456789', '%Y/%m/%d %h:%i:%s.%f');
+----------------------------------------------------------------------+
| str_to_date('1970/02/03 11:12:13.123456789', '%Y/%m/%d %h:%i:%s.%f') |
+----------------------------------------------------------------------+
| 1970-02-03 11:12:13.123456                                           |
+----------------------------------------------------------------------+
1 row in set, 1 warning (0.00 sec)
```

I'll prepare patch.

**Comment by electrum** [comment]
MySQL parses this but it issues a warning:
```
mysql> show warnings;
+---------+------+---------------------------------------------------------------------+
| Level   | Code | Message                                                             |
+---------+------+---------------------------------------------------------------------+
| Warning | 1292 | Truncated incorrect datetime value: '1970/02/03 11:12:13.123456789' |
+---------+------+---------------------------------------------------------------------+
1 row in set (0.00 sec)

**Comment by maciejgrzybek** [comment]
@electrum Then you claim we shouldn't support it or maybe just log a warning as well?
I think is better to allow nano-seconds, especially it we allow microseconds which we truncate anyway.
I believe we should trigger a warning anytime we truncate time.

So, my takeaway is:
1. warning when precision > milliseconds is given (resulting in truncation)
2. allow nanoseconds

Thoughts?

**Comment by maciejgrzybek** [comment]
Assigning @electrum for above questions.

**Comment by maciejgrzybek** [comment]
Closing since #5534 is merged.
