### ISSUE TITLE
Support WINDOW clause

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#5362]
The standard `WINDOW` clause allows defining named windows which window functions can reference:

``` sql
SELECT x, sum(x) OVER w
FROM (VALUES (1), (2), (3)) AS t (x)
WINDOW w AS (ORDER BY x);
```

Additionally, a window specification can reference and modify a named window:

``` sql
SELECT x, sum(x) OVER (w ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING)
FROM (VALUES (1), (2), (3)) AS t (x)
WINDOW w AS (ORDER BY x);
```

See the SQL standard for full details.

**Comment by maciejgrzybek** [comment]
Isn't it a duplicate of https://github.com/prestodb/presto/issues/3305 (better described though)?

**Comment by ptkool** [comment]
Please assign this issue to me.

**Comment by maciejgrzybek** [comment]
@ptkool There's a PR for this feature already. It's here: https://github.com/prestodb/presto/pull/5712

**Comment by ptkool** [comment]
@maciejgrzybek Ok. I was going by the fact that no one was assigned to this issue. Is there any easy way to determine if an issue has an existing PR? I am interested is contributing.

**Comment by maciejgrzybek** [comment]
@ptkool We try to link PRs with issues. You may see links between my comment from May 25th.
"This was referenced on Jul 20 [...]"

Unfortunately, it's not possible to assign issues to people outside of prestodb organization (https://github.com/prestodb).

**Comment by Sevi7** [comment]
Could this functionality be released? It is part of the SQL standard and it is something you expect to have when you use window functions
