### ISSUE TITLE
Support ORDER BY in ARRAY_AGG

### ISSUE THREAD

**Issue by cpcloud** [prestodb/presto#5370]
```sql
SELECT ARRAY_AGG(x ORDER BY x) AS x_sorted
SELECT ARRAY_AGG(x ORDER BY y) AS x_by_y
```

PostgreSQL has this as well: https://www.postgresql.org/docs/9.4/static/sql-expressions.html#SYNTAX-AGGREGATES

**Comment by martint** [comment]
Duplicate of https://github.com/prestodb/presto/issues/3890

**Comment by cpcloud** [comment]
whoops! sorry for the dupe.
