### ISSUE TITLE
Change reserved memory graph in Web UI to free memory

### ISSUE THREAD

**Issue by raghavsethi** [prestodb/presto#5371]
Instead of displaying total "user" memory on the cluster in the new Web UI, it is more useful to display free distributed memory in the general pool & system pool, along with min local memory on a node for general & system.

**Comment by haozhun** [comment]
I'm not sure whether this is something we want

**Comment by raghavsethi** [comment]
To be clear, I'm not suggesting replacement. I'm suggesting adding some more sparklines.
