### ISSUE TITLE
why data size between 0.118 and 0.143 is so different?

### ISSUE THREAD

**Issue by VIPchengcheng** [prestodb/presto#5376]
```
  I  have run a sql in presto 0.118  and 0.143 respectively.The details of results is below. I  found the  data size in different presto version have large gap. Is  the way  of computing data size between  0.118 and 0.147  different? Can you help me  resolve the confusion? 
```

details:
version         |   0.143        |     0.118
Query State |  FINISHED  |   FINISHED
Source         | presto-jdbc |   presto-jdbc
Elapsed        |   7.36 m      |    12.55 m
CPU Time     |   24.67 m    |    9.39 h
Rows             |    634M       |    329B
Data Size       |    1.78G      |     18.02TB

**Comment by cawallin** [comment]
@VIPchengcheng Sorry for the late response. If this is still an issue for you, can you try against the most recent version of Presto (0.170)? There have been a lot of performance improvements since 0.143. Feel free to re-open if you're still having issues.
