### ISSUE TITLE
Question about lazy loading

### ISSUE THREAD

**Issue by kajibutest** [prestodb/presto#5427]
Sorry if this is the wrong place to ask questions. I'm a newbie to ORC file format and I'm familiarizing myself with the lazy loading feature provided by Presto.

If I'm reading the code right, it comes down to the following: With lazy loading I can load the entire column where the query key is, examine its values, and only load the other columns if there is a hit for the query within the current row group.

My question is: For the other columns, is there a way to only load a fraction of them corresponding to the actual row hit by the query, or do I have to load the entire column for the current row group I'm in?

The reason why this is important to me is because my data contains a few integer key columns and a fat value column (MBs). Hive ORC writer enforces a minimum of 1000 rows per row group if I want to keep column statistics for predicate pushdown. There is no problem for me to load key columns in entirety because they are tiny, but I'd really want to avoid loading the entire fat value column for the row group, which translates into O(1000) MBs, just to find the one row that matches the query.

In production my ORC files would be in S3 so this would be costly for both bandwidth and memory.

Is there a way to enable lazy loading to load only a fraction of the column (eg, one row) for fat columns?

Thanks.

**Comment by ebd2** [comment]
Hi! There's a Google group for presto here: https://groups.google.com/forum/#!forum/presto-users. That's a great starting point for questions, including technical ones. I'd suggest posting this question there. Both developers and users will see it there.

This is a great question, by the way. I don't know the answer, but somebody on the group probably does and might have a different approach that addresses your use case. If not, you should definitely open an issue.
