### ISSUE TITLE
Do not use external tables for inserts in product tests

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#5443]
External tables should be treated as readonly. We need to fix this before #5416 is landed.

**Comment by kokosing** [comment]
@electrum do you need someone from Teradata to help you with it?

**Comment by electrum** [comment]
@kokosing yes, please

**Comment by ilfrin** [comment]
@electrum @martint @dain is this blocking the release?

**Comment by martint** [comment]
No, we'll merge this change after 0.148 goes out.

**Comment by ilfrin** [comment]
Good, thanks @martint I wanted to be sure we're not blocking anything. Btw is there anything we can do to help the release?

**Comment by kokosing** [comment]
@electrum Once I finish my current work, I will take care of this issue. Hope it will happen this week.

**Comment by electrum** [comment]
@ilfrin The last release blocker should be #5452. As part of fixing the other interval stuff, I found that negative interval literals are not parsed correctly (thus a correctness issue).

**Comment by cawallin** [comment]
Fixed in https://github.com/prestodb/presto/pull/5462.
