### ISSUE TITLE
MongoPageSink should not use Type.getObjectValue

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#5451]
`getObjectValue()` is for use by engine to get a JSON serializable object to send over the REST API. Connectors should read values by methods such as `Type.getLong`.

Ideally, no type implementations would be in the SPI: instead, connectors would ask for types using `TypeManager` (as they must do today for parametric types like `array`).

**Comment by electrum** [comment]
cc @miniway

**Comment by miniway** [comment]
I see, I'll take care of it.
