### ISSUE TITLE
Support for ANSI 2011 ?

### ISSUE THREAD

**Issue by vishnudxb** [prestodb/presto#5454]
Hi 

Does Presto support ANSI 2011 ?

**Comment by damiencarol** [comment]
@vishnudxb what feature ?

**Comment by vishnudxb** [comment]
@damiencarol  I haven't get a chance to tried it, It's a general question, whether it's support ANSI 2011?

**Comment by KBP-TDC** [comment]
Presto supports many features from 2011 spec but not all of them.
Please check out our docs at https://prestodb.io/docs/current/
Also, in the future, please use our mailing list (https://groups.google.com/forum/#!forum/presto-users) rather than GitHub issues to ask questions. Thanks!

**Comment by vishnudxb** [comment]
Thanks for the info!
