### ISSUE TITLE
SplitConcurrencyController creates too many splits in a worker node

### ISSUE THREAD

**Issue by xerial** [prestodb/presto#5466]
We have observed sudden spikes of the number of blocked splits in worker nodes. This is because SplitConcurrencyController takes care about only the shared buffer utilization regardless of the number of already blocked splits or CPU usage:
https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/execution/SqlTaskExecution.java#L192

![image](https://cloud.githubusercontent.com/assets/57538/16164467/28ae515a-3493-11e6-842b-f504f64b63e2.png)

This causes slow down of queries. Ideas for avoiding this problems are: 
- Allow setting a hard limit on the number of splits in a worker. Current max-splits-per-node parameter is used as a soft limit when building distributed plans. 
- Use a utilization metric that also considers the number of running/blocked splits in a worker.

Any thought?

**Comment by cberner** [comment]
Including blocked splits in the utilization metric sounds like the right thing to do here

**Comment by ssquan** [comment]
Does this issue already been fixed?
