### ISSUE TITLE
Expression value should be calculated after adding coercion

### ISSUE THREAD

**Issue by yuananf** [prestodb/presto#5470]
This seems to be a bug, which causes tpcds query 21 to get wrong result.

Here are some examples:
```
presto:default> select 3/4 between 0.6 and 1.5;
 _col0 
-------
 false 
(1 row)

presto:default> select 0.1 between 2/3 and 3.0/2.0;
 _col0 
-------
 true  
(1 row)

presto:default> select 2/3 > 1.0/2.0;
 _col0 
-------
 false 
(1 row)
```

**Comment by martint** [comment]
This is expected behavior. `2 / 3` is performed as integer division, so it returns 0. To get the result you expect, try `2.0 / 3` or `2 / 3.0` or `2.0 / 3.0`

**Comment by yuananf** [comment]
I'm not sure. Is there any standard about this kind of query?

I just tested them in mysql, and the results are quite different:
```
mysql> select 3/4 between 0.6 and 1.5;
+-------------------------+
| 3/4 between 0.6 and 1.5 |
+-------------------------+
|                       1 |
+-------------------------+
1 row in set (0.00 sec)

mysql> select 0.1 between 2/3 and 3.0/2.0;
+-----------------------------+
| 0.1 between 2/3 and 3.0/2.0 |
+-----------------------------+
|                           0 |
+-----------------------------+
1 row in set (0.00 sec)

mysql> select 2/3 > 1.0/2.0;
+---------------+
| 2/3 > 1.0/2.0 |
+---------------+
|             1 |
+---------------+
1 row in set (0.00 sec)
```

Besides, the following two queries generated different results:
```
presto:default> select 3/4 * 1.0 > 0.5;
 _col0 
-------
 false 
(1 row)


presto:default> select 1.0 * 3/4 > 0.5;
 _col0 
-------
 true  
(1 row)
```

**Comment by martint** [comment]
> I'm not sure. Is there any standard about this kind of query?

ANSI SQL leaves the scale for division up to the implementor.

> `select 3/4 * 1.0 > 0.5;`

This evaluates as `((3 / 4)  * 1.0) > 0.5` => `(0 * 1.0) > 0.5` => `0.0 > 0.5`

> `select 1.0 * 3/4 > 0.5;`

This evaluates as `((1.0 * 3) / 4) > 0.5` => `(3.0 / 4) > 0.5` => `0.75 > 0.5`

**Comment by yuananf** [comment]
Oh, I checked the standard, you are right.
> 41) Subclause 6.27, “numeric value expression”:
  a) When the declared type of both operands of the addition, subtraction, multiplication, or division
operator is exact numeric, the declared type of the result is an implementation-defined exact numeric type.
  b) When the declared type of both operands of the division operator is exact numeric, the scale of the result is implementation-defined.
  c) When the declared type of either operand of an arithmetic operator is approximate numeric, the declared type of the result is an implementation-defined approximate numeric type.
  d) Whether to round or truncate when performing division is implementation-defined.

And SQLServer division also behaves like presto.
Thanks for explaining. I'll be careful when using such kind of query.
