### ISSUE TITLE
Compilation error for presto-main

### ISSUE THREAD

**Issue by ArchaB** [prestodb/presto#5532]
When I try to build presto-main using the command 'mvn test', the package fails with the following compilation error

**[ERROR] /prestodb/presto/presto-main/src/main/java/com/facebook/presto/sql/analyzer/ExpressionAnalyzer.java:[106,43] cannot find symbol
  symbol:   class IntervalDayTimeType
  location: package com.facebook.presto.spi.type
[ERROR] /prestodb/presto/presto-main/src/main/java/com/facebook/presto/sql/analyzer/ExpressionAnalyzer.java:[106,1] static import only from classes and interfaces
[ERROR] /prestodb/presto/presto-main/src/main/java/com/facebook/presto/sql/analyzer/ExpressionAnalyzer.java:[107,43] cannot find symbol
  symbol:   class IntervalYearMonthType
  location: package com.facebook.presto.spi.type
.
.
.**

Tried to check the presto-spi jar which it uses. 

**[DEBUG]   com.facebook.presto:presto-spi:jar:0.148-SNAPSHOT:compile (selected for compile)**

and classpath set during debug to **/root/.m2/repository/com/facebook/presto/presto-spi/0.148-SNAPSHOT/presto-spi-0.148-SNAPSHOT.jar**

The presto-spi-0.148-SNAPSHOT.jar at this location did not have all the classfiles (eg. IntervalDayTimeType.class, IntervalYearMonthType.class) which are actually present in the presto-spi package. 

I edited the presto-spi-0.148-SNAPSHOT.jar (at **/root/.m2/repository/com/facebook/presto/presto-spi/0.148-SNAPSHOT/**) and copied the required class files into it in the mentioned location. 
But when I try to rebuild presto-main, it overwrites the presto-spi-0.148-SNAPSHOT.jar with the same old version resulting the package to fail again with the above mentioned compilation error. 

Any help will be appreciated.

**Comment by electrum** [comment]
Can you show the full Maven command you used? You usually need to install the entire project as a first step: `mvn clean install -DskipTests`

After that, you will be able to build individual modules. If you don't build the project first, you are likely to either be missing the dependencies or will pull some random snapshot (which can have an error like the one you encountered).

**Comment by ArchaB** [comment]
Thanks a lot. That helped to resolve the issue faced.
presto-main now fails in test execution though.

Failure seen:
**[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.14:test (default-test) on project presto-main: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.14:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ?
[ERROR] Command was/bin/sh -c cd /prestodb/presto/presto-main && /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.91-0.b14.el7_2.ppc64le/jre/bin/java -Duser.timezone=Asia/Katmandu -Xmx2g -Xms2g '-XX:OnOutOfMemoryError=kill -9 %p' -XX:+HeapDumpOnOutOfMemoryError -jar /prestodb/presto/presto-main/target/surefire/surefirebooter8080364878203893566.jar /prestodb/presto/presto-main/target/surefire/surefire5471722457506807474tmp /prestodb/presto/presto-main/target/surefire/surefire_02331414755341994724tmp
[ERROR] -> [Help 1]**

The container runs on the VM with 13GB RAM
