### ISSUE TITLE
presto can't insert data

### ISSUE THREAD

**Issue by junming4** [prestodb/presto#5579]
presto can't insert data,but presto doc say can insert ,why?
![qq 20160706122501](https://cloud.githubusercontent.com/assets/7088615/16607532/940518f4-4374-11e6-805f-4ffbf0693bea.png)

**Comment by electrum** [comment]
Insert isn't supported yet for that connector. Unfortunately, the error message is bad.

For now, you can use CREATE TABLE AS with that connector to write data.

**Comment by junming4** [comment]
OK，I would like to know if the "insert" feature is included in the development plan.

**Comment by petroav** [comment]
@junming4 Looking at the roadmap wiki (https://github.com/prestodb/presto/wiki/Roadmap), I can see a couple of items related to INSERT.

**Comment by electrum** [comment]
There is a PR for this: https://github.com/prestodb/presto/pull/4235

**Comment by junming4** [comment]
THINKS

**Comment by cawallin** [comment]
This issue is a duplicate of https://github.com/prestodb/presto/issues/4218
