### ISSUE TITLE
GROUP BY alias does not work.

### ISSUE THREAD

**Issue by javainthinking** [prestodb/presto#5582]
presto:default> select count(cname), cid as id from ss_dev.course_rt group by id;
Query 20160705_122534_00018_ej4np failed: line 1:63: Column '"id"' cannot be resolved
select count(cname), cid as id from ss_dev.course_rt group by id

**Comment by javainthinking** [comment]
Change the code for this issue:
https://github.com/prestodb/presto/pull/5581

**Comment by electrum** [comment]
See discussion in #5581

**Comment by electrum** [comment]
Closing this so that we can keep the discussion in one place.
