### ISSUE TITLE
Migration doc for Hive is outdated about outer join

### ISSUE THREAD

**Issue by wxiang7** [prestodb/presto#5584]
In [latest presto doc](https://prestodb.io/docs/current/migration/from-hive.html), it says Hive is not following ANSI SQL when doing outer join.

More specifically, migration doc says 

> Hive will first apply any constant filters in the ON clause then perform the join

This is a bug for Hive, however it was already fixed in [HIVE-1534](https://issues.apache.org/jira/browse/HIVE-1534), [HIVE-3381](https://issues.apache.org/jira/browse/HIVE-3381), [HIVE-9743](https://issues.apache.org/jira/browse/HIVE-9743)

**Comment by rschlussel** [comment]
fixed by https://github.com/prestodb/presto/pull/7599
