### ISSUE TITLE
how to hit presto console using putty

### ISSUE THREAD

**Issue by Shubhamjain6197** [prestodb/presto#5592]

**Comment by petroav** [comment]
I'm not sure what you mean. I thought PuTTY was an SSH client so once you're connected to the machine that has the Presto CLI you can just start it. Here is the relevant documentation https://prestodb.io/docs/current/installation/cli.html

**Comment by Shubhamjain6197** [comment]
hi,
thanks for reply, i am saying i want to open presto cli using putty..


Warm Regards
*Shubham Jain*

**Comment by maciejgrzybek** [comment]
@Shubhamjain6197 Did @petroav's answer work for you? If yes, please close the issue. Otherwise, could you describe more what's the problem?
