### ISSUE TITLE
Floating points should be formatted using scientific notation

### ISSUE THREAD

**Issue by maciejgrzybek** [prestodb/presto#5593]
Following specs:

> An `<approximate numeric literal>` ANL consists of an `<exact numeric literal>` (called the `<mantissa>`), the letter 'E' or 'e', and a `<signed integer>` (called the `<exponent>`).

**Comment by maciejgrzybek** [comment]
@martint Should we always return approximate numbers using scientific notation as described above?
Java's Float/Double `toString()` method formats number in scientific notation when the value is less than 10^-3 or is greater than 10^7.
Postgres does something similar, e.g.:
```sql
test=# select real'0.0001';
 float4 
--------
 0.0001
(1 row)
```
but
```sql
test=# select real'0.00001';
 float4 
--------
  1e-05
(1 row)
```

MySQL, on the other hand is rounding numbers and seems to never use scientific notation, e.g:
for number `123456789f` returns `123457000`, for `1234567.89f` returns `1234570`. But, for `0.0000001f` returns `0.0000001`.

**Comment by maciejgrzybek** [comment]
@martint: gently reminder

**Comment by martint** [comment]
I think it's fine to show them to users in that way, but that's a client rendering issue more than anything. From the point of view of the SQL parser, any literal that's not in scientific notation should be interpreted as decimal, though.
