### ISSUE TITLE
Make RowType fields available in SPI?

### ISSUE THREAD

**Issue by zhenxiao** [prestodb/presto#5601]
Currently, RowType is in presto-main, not in presto-spi
To better handle nested fields in Parquet(or ORC), need to get fields for a RowType, and RowField. Is it possible to put RowType in presto-spi? Or, is there other ways to make Parquet or ORC aware of RowType and RowFields?
@martint @dain @cberner @electrum @erichwang

**Comment by cberner** [comment]
Could you provide more details about why it's needed? The current implementation doesn't need it, and it can support reading and writing them

**Comment by zhenxiao** [comment]
When we are trying to implement Nested Schema Evolution, and Nested Column Pruning in https://github.com/prestodb/presto/pull/5547, we need to get RowFields of a RowType, and use each RowField name to look up the corresponding parquet type in parquet file schema. There is no RowType information in SPI, then Parquet files could not get RowFields.

**Comment by cberner** [comment]
You should be able to get that information by calling `getTypeSignature().getParameters()` which is on `Type` in the SPI

**Comment by zhenxiao** [comment]
Thank you, @cberner Correct me if I get misunderstanding. if I have a RowType struct:
RowType<Integer ColumnA, Double ColumnB>

My understanding is getTypeSignature().getParameters() will return <Integer, Double>, will it return ColumnA and ColumnB?

**Comment by cberner** [comment]
yes, it should return a list of the fields which can be accessed as `NamedTypeSignature` I believe

**Comment by zhenxiao** [comment]
oh, get it. Thank you

**Comment by cberner** [comment]
Np. Please re-open if you end up needing this
