### ISSUE TITLE
hive.bucket-execution forces bucketed execution even when not needed

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#5602]
JOIN'ing a bucketed table on a key other than the bucketing key still results in a bucketed execution plan, which forces all splits for a bucket to be read by a single worker. This makes stragglers a much bigger problem and skew'ing buckets will execute much more slowly. Instead, we should only take advantage of bucketing when it will help the query (JOIN'ing/GROUP'ing on the bucket key)

**Comment by cberner** [comment]
Discussed this with @erichwang, and he's going to fix it by implementing multiple table layouts for the Hive connector and having the exchanges optimizer only pick the bucketed layout when it will help the plan

**Comment by martint** [comment]
>  by implementing multiple table layouts for the Hive connector

I'm not sure that's the best way to model it. There aren't multiple physical layouts for Hive tables (which is what that feature is meant to capture). Instead, the layout should describe the bucketing properties and the exchanges optimizer should ignore them if they don't help.

**Comment by cberner** [comment]
That sounds reasonable. I'll leave it to the two of you to decide how best to model it, since I'm not very familiar with the table layout code

**Comment by dain** [comment]
@martint, IIRC for Raptor if you have bucketing, the engine must use it

**Comment by electrum** [comment]
@dain, I think that's only true for writing (which I assume is true for Hive as well)

**Comment by erichwang** [comment]
After chatting with @haozhun, I think this is actually a scheduling problem, not a layout handling problem. How we choose to schedule our splits should be based on plan, not the layout. @haozhun will be working on this.
