### ISSUE TITLE
Java version requirements controversy

### ISSUE THREAD

**Issue by scorta-d** [prestodb/presto#5631]
The preinstall script in rpm return incorrect java version for OpenJdk.

```
java_version() {
# The one argument is the location of java (either $JAVA_HOME or a potential
# candidate for JAVA_HOME.
JAVA="$1"/bin/java
"$JAVA" -version 2>&1 | grep "java version" | awk '{ print substr($3, 2, length($3)-2); }'
}
java_vendor() {
# The one argument is the location of java (either $JAVA_HOME or a potential
# candidate for JAVA_HOME).
# Returns the java vendor name. eg: Oracle Corporation
JAVA="$1"/bin/java
"$JAVA" -XshowSettings:properties -version 2>&1 | grep "java.vendor =" | awk '{ print $3 " " $4; }'
}
```

Correct version check should be like this:

```
"$JAVA" -XshowSettings:properties -version 2>&1 | grep "java.version = "
```

Documentation for Presto does not mention Oracle Java at all.

If Oracle Java is a critical requirements, then Presto should not start on OpenJdk. Like it does not start on IBM Java because of `java.vendor`
Also If Oracle Java is a critical requirement it should be explicitly stated in Documentation.
OpenJdk java.vendor is also Oracle.

Controversy between documentation and rpm preinstall script at least.

**Comment by cawallin** [comment]
See this PR and discussion: https://github.com/prestodb/presto/pull/5541
