### ISSUE TITLE
HTTPS port is hardcoded

### ISSUE THREAD

**Issue by dzakarov** [prestodb/presto#5642]
Currently HTTPS port is hard coded and value 443 does not allowed for ordinary user, 
What about introducing jdbc url parameter say jdbc:presto://host:8443/catalog/schema?protocol=https
.src/main/java/com/facebook/presto/jdbc/PrestoConnection.java
```
        String scheme = (address.getPort() == 443) ? "https" : "http";
        List<NameValuePair> kv = null;
        try {
            if (uri != null) {
                kv = URLEncodedUtils.parse(uri, "ASCII");
                if (kv.contains(new BasicNameValuePair("protocol", "https"))) {
                    scheme = "https";
                }
            }
        } catch (Exception e) {
            
        }

```

**Comment by fmeiser** [comment]
Hi,

there exists already a PR #5411 for additional properties for connections.

**Comment by fmeiser** [comment]
PR #6078 introduced the parameter secure  to force a secure connection on none HTTPS ports.
