### ISSUE TITLE
Ambiguous declarations for concat() function

### ISSUE THREAD

**Issue by martint** [prestodb/presto#5662]
The concat function allows the following forms:

```
concat(array(T), array(T))
concat(T, array(T))
concat(array(T), T)
```

This causes problems when one of the arguments is `array[]`.

If `T` is `array(U)` in the second form, the invocation looks like `concat(array(U), array(array(U))`. A call like `concat(array[1,2], array[])` is ambiguous, since `array[]` is a valid value for `array(T)` and `array(array(U))`. A similar issue happens for the third form.

We should consider removing the second and third forms of the function and replacing them with `prepend` and `append`, respectively.

**Comment by aaronshan** [comment]
It not only happen for a literal (i.e. the query contains exactly ARRAY[]), If you use array_remove and array_intersect, maybe you will get ARRAY[]
```
presto:default> select arr1 = ARRAY[],arr2 = ARRAY[] from (values (array_remove(ARRAY['a'], 'a'), array_intersect(ARRAY['a'], ARRAY['b']))) as t(arr1, arr2);
 _col0 | _col1
-------+-------
 true  | true
(1 row)

Query 20160714_092119_00020_6pxur, FINISHED, 1 node
Splits: 1 total, 1 done (100.00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]
```

And when you use concat(arr1, arr2), if arr1 or arr2 is null, it will also get error result.
```
presto:default> select concat(arr1, arr2) from (values (ARRAY[5, NULL], null)) as t(arr1, arr2);
Query 20160714_093751_00028_6pxur failed: line 1:8: Could not choose a best candidate operator. Explicit type casts must be added.
Candidates are:
	 * concat(array(integer),array(integer)):array(integer)
	 * concat(array(integer),integer):array(integer)
	 * concat(array(integer),array(array(integer))):array(array(integer))

select concat(arr1, arr2) from (values (ARRAY[5, NULL], null)) as t(arr1, arr2)
```

**Comment by martint** [comment]
Yes, `NULL` has the same issue, since it's a valid "value" for any type.
