### ISSUE TITLE
No nodes available to run query.Union all Bug?

### ISSUE THREAD

**Issue by zhuqunzhou** [prestodb/presto#5663]
I added a config item `hive.force-local-scheduling=true` in `hive.properties`.

I find sometimes throw the exception `com.facebook.presto.spi.PrestoException: No nodes available to run query`..Normal sql(like `select * from table where ...`) `presto` works ok,but if i have `union all` in the sql,it will throw the Exception.

Here is my exception sql:`with t as (select  row_number() over(order by logtime desc) as r , *     from    ( (select  id,,logtime from skynet_12888  where  dt in ('20160525')  )  UNION ALL  (select  id,logtime from skynet_all_12888  where  dt in ('20160525')  ) ) ) select  * from    t where   t.r >= 1 and t.r < 21`.

The "exception" sql works ok before i add the `hive.force-local-scheduling=true` config item.

Here is my normal sql:`with t as (select  row_number() over(order by logtime desc) as r , *     from    (select  id,,logtime from skynet_12888  where  dt in ('20160525','20160526'......) ) select  * from    t where   t.r >= 1 and t.r < 21`.

`presto` v0.143

Thank you.

**Comment by KBP-TDC** [comment]
@zhuqunzhou Is it possible that your cluster has few nodes / resources and when time comes to schedule a split, there are no nodes available that have it locally?
CC: @cberner @dain

**Comment by dain** [comment]
This exception is thrown from a few different code paths.  Can you post a stack trace?
