### ISSUE TITLE
Add Hive system table for partitions

### ISSUE THREAD

**Issue by cpcloud** [prestodb/presto#5665]
The use case for this was to be able to look at a set of tables' partitions and identify the earliest common partition among them.

**Comment by electrum** [comment]
The tricky part here is that each Hive table has a different set of partition columns and types. It might make sense to have a separate partition table per table. For example, table `foo` would have a partition table `"foo.$partitions"`.

**Comment by cpcloud** [comment]
So, I actually just want a quick way to get the retention property. I can get partitions with `SHOW PARTITIONS`, which works well already AFAICT. If I know the retention, I can quickly calculate the earliest partition using date arithmetic.

**Comment by electrum** [comment]
The concept of retention is specific to Facebook's Hive installation. (The open source Thrift metastore has a `retention` field for `Table` but it's not used by anything.)

**Comment by cpcloud** [comment]
Oh, I didn't know that. What about being able to access the information that's specified inside the `WITH` clause?

**Comment by cpcloud** [comment]
Even though retention is specific to Facebook, I think accessing properties that are set in the `WITH` clause is generally useful, no?

**Comment by electrum** [comment]
I agree it's useful. We need to decide on exactly how.

**Comment by afranzi** [comment]
@electrum Is not this `system table for partitions` already supported?
