### ISSUE TITLE
Additional CPU cycles introduced by ShortArrayBlock, IntArrayBlock and LongArrayBlock in exchange

### ISSUE THREAD

**Issue by fmeiser** [prestodb/presto#5684]
With the introduction of `ByteArrayBlock`, `ShortArrayBlock`, `IntArrayBlock `and `LongArrayBlock ` @dain also changed the encoding of theses blocks.
Earlier the data is written directly as a package to the `SliceOutput`. After the changes, each nonnull value is transmitted individually.
In exchanges the `OutputStreamSliceOutput` is used and the implementation of `OutputStreamSliceOutput` uses `LittleEndingDataOutputStream` which is slow for writting single values.
On my machine `LittleEndingDataOutputStream` has a 20 - 60ns overhead per value compared to `BasicSliceOutput`.

**Comment by electrum** [comment]
Thanks for investigating this! Can share how you measured this? Linux Perf?

**Comment by fmeiser** [comment]
With JMH I tested two versions of writing and encoding a `LongArrayBlock` with 10.000 longs.

Version with `OutputStreamSliceOutput`

```
Benchmark                                         Mode  Cnt       Score       Error  Units
BenchmarkLongArrayBlock.baselineLengthAllNonNull  avgt   10  274800,141 ? 23335,880  ns/op
BenchmarkLongArrayBlock.baselineLengthAllNull     avgt   10   56122,133 ?   761,584  ns/op
BenchmarkLongArrayBlock.baselineLengthMixed       avgt   10  253437,721 ?  1793,496  ns/op
```

Version with `BasicSliceOutput`

```
Benchmark                                         Mode  Cnt       Score      Error  Units
BenchmarkLongArrayBlock.baselineLengthAllNonNull  avgt   10   96678,062 � 1868,409  ns/op
BenchmarkLongArrayBlock.baselineLengthAllNull     avgt   10   37394,058 �  504,059  ns/op
BenchmarkLongArrayBlock.baselineLengthMixed       avgt   10  168899,893 �  256,159  ns/op
```

The current overhead is lower because I have `ByteArrayOutputStream` replaced by `FastByteArrayOutputStream`. The final overhead is doubled for decoding the values.

**Comment by fmeiser** [comment]
@dain Do you have time to create a new version of airlift/slice, so that the problem is fixed?

**Comment by dain** [comment]
Slice should be updated in the next release.

**Comment by fmeiser** [comment]
Fixed with release 153
