### ISSUE TITLE
Impossible to query data from kerberized hadoop cluster and non-kerberized hive.

### ISSUE THREAD

**Issue by scorta-d** [prestodb/presto#5691]
## Steps to reproduce
- Create hive connector to kerberized cluster
- Create hive connector to non-kerberized cluster
- Run SQL against kerberized cluster 
- Run SQL against non-kerberized cluster 
## Expected result
- Both queries return data
## Actual result
- Non-kerberized query fails with exception

This happens because of this code:

```
public class KerberosHadoopAuthentication
        implements HadoopAuthentication
{
    static {
        // In order to enable KERBEROS authentication method for HDFS
        // UserGroupInformation.authenticationMethod static field must be set to KERBEROS
        // It is further used in many places in DfsClient
        Configuration configuration = new Configuration(false);
        configuration.set("hadoop.security.authentication", "kerberos");
        UserGroupInformation.setConfiguration(configuration);

        // KerberosName#rules static field must be initialized
        // It is used in KerberosName#getShortName which is used in User constructor invoked by UserGroupInformation#getUGIFromSubject
        KerberosName.setRules("DEFAULT");
    }
```

After loading of this class no data read is possible from non-kerberized hadoop cluster.

The proper way is probably modification of given code, but there is a workaround.
Plugins are loaded before connectors, so if we create a udf and put it into hadoop-hive plugin directory, this may help.
## Workaround
- Create simple plugin and put similar code into the init section  with a small addition:

```
import static org.apache.hadoop.fs.CommonConfigurationKeys.IPC_CLIENT_FALLBACK_TO_SIMPLE_AUTH_ALLOWED_KEY;

...
        Configuration configuration = new Configuration(false);
        configuration.set("hadoop.security.authentication", "kerberos");
        configuration.setBoolean(IPC_CLIENT_FALLBACK_TO_SIMPLE_AUTH_ALLOWED_KEY,true); 
        UserGroupInformation.setConfiguration(configuration);

```

This way both connectors should be able to read data from kerberized and non-kerberized cluster.

**Comment by maciejgrzybek** [comment]
@arhimondr would you have a look on that?

**Comment by arhimondr** [comment]
Hadoop libraries use statically defined settings when connecting to HDFS. As an another workaround different hadoop connectors can be used (`presto-hive-cdh5` and `presto-hive-hadoop2`), so they are loded in a separate class loaders. But when the same connector is used for multiple catlogs the static context of a hadoop libraries is shared. @dzakarov the setting you suggested(`IPC_CLIENT_FALLBACK_TO_SIMPLE_AUTH_ALLOWED_KEY`) looks better to me though. Would you like to open a Pull Request?

**Comment by arhimondr** [comment]
@dzakarov Thanks for investigating the problem and opening so descriptive issue
