### ISSUE TITLE
Document S3 custom credentials providers

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#5703]
We should add documentation for #5667. Maybe add a section to the Hive connector docs about S3 and add a sub-section for this.

**Comment by electrum** [comment]
Looks like the documentation is covered (at least partially) by #5701

**Comment by nezihyigitbasi** [comment]
Created a PR. I think some of the s3 filesystem properties documented in #5701 (which are all in hive security docs)  can be moved to the new section that this PR adds. /cc @electrum

**Comment by nezihyigitbasi** [comment]
this has been merged.

**Comment by cdw9bf** [comment]
Hi @nezihyigitbasi , sorry to bring up this old issue but I see in the documentation that it is possible to use the user as a decider for which IAM role to use (`...for a specific use case (e.g., bucket/user specific credentials)`). Does this mean that the user name is passed into the credential provider when it is initiated or would they have to be statically set in the configuration file? 

The reason I ask this is that we are looking to move Presto off of EMR clusters and will need to run our own implementation of the assume-role operations provided by EMRFS. I've tried to get the user information out of the arguments passed into the credential provider but have not had any success.

**Comment by nezihyigitbasi** [comment]
@cdw9bf When we implemented this feature, per-user custom credentials support was also in mind, but we eventually used per-bucket IAM roles in our deployment (where the bucket is already in the `URI` that we pass to the constructor of the custom credentials provider), so it's possible that this feature doesn't even support per-user custom credentials. 

We already have the current session user at the point where we get a filesystem instance ([here](https://github.com/prestodb/presto/blob/master/presto-hive/src/main/java/com/facebook/presto/hive/HdfsEnvironment.java#L67) is the code), so it is probably not that difficult (although will probably be hacky) to pass the user info down to the filesystem level.
