### ISSUE TITLE
Allow expressions in simple CASE statements

### ISSUE THREAD

**Issue by cpcloud** [prestodb/presto#5706]
Currently Presto fails to parse the following query:

``` sql
SELECT
  CASE TRUE OR FALSE
    WHEN TRUE THEN TRUE
    ELSE NULL
  END
```

because more complex expressions are not allowed in the parser. Should we allow them through? You can get around this by wrapping parentheses around the `TRUE OR FALSE` in this case, but I think we should allow an expression here.

**Comment by cpcloud** [comment]
I've implemented this, and no tests break. I've also added a small test that fails on master and passes with my change. Should I submit a PR?

**Comment by kokosing** [comment]
Yes, please submit PR.
