### ISSUE TITLE
Presto install error

### ISSUE THREAD

**Issue by mkolplk321** [prestodb/presto#5722]
I have checkout the presto and try to build it. When I test to execute "mvn clean install" , the error was occured.

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:
2.16:check (default) on project presto-spi: You have 26960 Checkstyle violations
. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :presto-spi

Can you help me?

**Comment by electrum** [comment]
Does "git status" show any changes? Can you show the full output from the build?

**Comment by maciejgrzybek** [comment]
Are you trying to build on Windows maybe? If yes, this could be a known issue. Some similar discussion from a few days ago: https://github.com/prestodb/presto-jdbc-java6/issues/15
