### ISSUE TITLE
Add more data types tests for JDBC connectors 

### ISSUE THREAD

**Issue by maciejgrzybek** [prestodb/presto#5726]
As of discussion on https://github.com/prestodb/presto/pull/5702 and as suggested by @akshatnair (here: https://github.com/prestodb/presto/pull/5702#issuecomment-234168477 + @raghavsethi's comment here: https://github.com/prestodb/presto/pull/5702#issuecomment-233751088), we should work on at least SOME coverage of data types in testing of JDBC connectors.

**Comment by maciejgrzybek** [comment]
@ShanBai6 will take care of this.

**Comment by findepi** [comment]
`TestPostgreSqlTypeMapping` looks quite decent today.
