### ISSUE TITLE
“delete” will failed “select” 

### ISSUE THREAD

**Issue by linqerli** [prestodb/presto#5734]
https://groups.google.com/forum/#!topic/presto-users/V5oB6CXVB7A

I see Even if hive deletes the hdfs files a day later, “Select” will still failed in presto . because presto will call hive metastore many times to get partitions name or object during the process of execution and analysis of a "select" sql;
1. SQL1: "Select \* from A " start running , and get all partition names (p1,p2,p3...p10) from hive metastore in coordinator which will be stored in HiveTableLayoutHandle.partitions .
2. SQL2: "Delete A where dt=p1", comming and finished. p1 will be removed from metastore and hdfs.
3. SQL1: "Select \* from A " , get org.apache.hadoop.hive.metastore.api.partition objects of p1,p2,....p10 from hive metastore by HiveSplitManager.getPartitionMetadata ,
   now presto will throw exception because hive metastore return null for p1 (if partitionCache in CachingHiveMetastore is expired. or it has no data because of frist time， or cache is disabled by hive.metastore-cache-ttl=0s, which also is configured  in some of your clusters );
   
   plese check code of HiveSplitManager.getPartitionMetadata
   
   Iterable<List<HivePartition>> partitionNameBatches = partitionExponentially(hivePartitions, minPartitionBatchSize, maxPartitionBatchSize);
       Iterable<List<HivePartitionMetadata>> partitionBatches = transform(partitionNameBatches, partitionBatch -> {
           Optional<Map<String, Partition>> batch = metastore.getPartitionsByNames(
                   tableName.getSchemaName(),
                   tableName.getTableName(),
                   Lists.transform(partitionBatch, HivePartition::getPartitionId));
   
   if (!batch.isPresent()) {
               throw new PrestoException(HIVE_METASTORE_ERROR, "Partition metadata not available");
   }
   .................
   if (partitionBatch.size() != partitions.size()) {
               throw new PrestoException(INTERNAL_ERROR, format("Expected %s partitions but found %s", partitionBatch.size(), partitions.size()));
   }

**Comment by linqerli** [comment]
is there any one deal with this bug

**Comment by haozhun** [comment]
#6067 will fix this.
