### ISSUE TITLE
Performance degradation for a specific query from 0.139 to 0.149

### ISSUE THREAD

**Issue by nezihyigitbasi** [prestodb/presto#5779]
I am seeing a performance degradation of 10-15% for a limit query when I test `0.149` against  `0.139`. There are a few differences in the plans produced by these versions. I see that the plan in `0.149` has two additional project operators in stage 0 and 1 applying the same projection while `0.139` don't have those. Also I see that the filter expressions differ quite a bit, but not sure whether that will affect the performance much.

[Here](https://gist.github.com/nezihyigitbasi/aa9c222c644c86f9163a83a5c9800443) is the query, the plan in [0.139](https://gist.github.com/nezihyigitbasi/ce0cb2914c9c8635bb737ad8161237f2) and the plan in [0.149](https://gist.github.com/nezihyigitbasi/7965d784633cda268c2763d85617a6ed). Any insights appreciated.

**Comment by nezihyigitbasi** [comment]
@dain @martint any ideas?

**Comment by dain** [comment]
Looking at the query plans I would expect the plans to be the sam speed.  The 149 plan has a better filter clause (eliminating the duplicate expressions on application_type), but it has extra 2 projections.  In both cases, I would expect the extra work to account for near zero CPU usage.  In 149 you can run EXPLAIN ANALYZE, and that should show the CPU usage for the extra projections.  If the usage is ~10% we have found the problem.  If not, the problem is likely within an operator implementation, which will be harder to find.

-dain

**Comment by nezihyigitbasi** [comment]
thanks @dain. Here is the explain analyze output. For fragment 2 the cost is almost 0, for fragment 1 it's 50%, but the total cpu cost of this stage is negligible, and for fragment 0 the cost is significant but it's hard to compare that against version 0.139. I guess the perf diff is probably not related to these extra projections, but probably due to individual operator implementations. 

```
 Fragment 1 [SINGLE]
     Cost: CPU 31.62ms, Input 40 (911B), Output 10 (149B)
     Output layout: [user]
     Output partitioning: SINGLE []
     - Output[Query Plan] => [user:varchar]
             Cost: 0.00%, Output: 10 rows (149B)
             Query Plan := user
         - Project => [user:varchar]
                 Cost: 50.00%, Output: 10 rows (149B)
             - TopN[10 by (sum DESC_NULLS_LAST)] => [sum:bigint, user:varchar]
                     Cost: 50.00%, Output: 10 rows (239B)
                 - RemoteSource[2] => [sum:bigint, user:varchar]
                         Cost: 0.00%, Output: 40 rows (911B)

 Fragment 2 [HASH]
     Cost: CPU 1.18s, Input 41018 (1.65MB), Output 40 (911B)
     Output layout: [sum, user]
     Output partitioning: SINGLE []
     - TopN[10 by (sum DESC_NULLS_LAST)] => [user:varchar, sum:bigint]
             Cost: 0.64%, Output: 40 rows (911B)
         - Project => [user:varchar, sum:bigint]
                 Cost: 0.64%, Output: 253 rows (6.20kB)
             - Aggregate(FINAL)[user] => [user:varchar, $hashvalue:bigint, sum:bigint]
                     Cost: 73.49%, Output: 253 rows (8.43kB)
                     sum := "sum"("sum_10")
                 - RemoteSource[3] => [user:varchar, sum_10:bigint, $hashvalue:bigint]
                         Cost: 25.22%, Output: 41018 rows (1.65MB)

 Fragment 3 [SOURCE]
     Cost: CPU 1.60h, Input 249658 (8.55MB), Output 41018 (1.65MB)
     Output layout: [user, sum_10, $hashvalue_11]
     Output partitioning: HASH [user]
     - Aggregate(PARTIAL)[user] => [user:varchar, $hashvalue_11:bigint, sum_10:bigint]
             Cost: 0.05%, Output: 41018 rows (1.65MB)
             sum_10 := "sum"("expr")
         - Project => [user:varchar, $hashvalue_11:bigint, expr:bigint]
                 Cost: 99.95%, Output: 249658 rows (8.55MB)
```

**Comment by fmeiser** [comment]
Maybe your problem is related to #5719

**Comment by martint** [comment]
@nezihyigitbasi, do you see this issue in newer versions?

**Comment by nezihyigitbasi** [comment]
I didn't have a chance to look at newer versions unfortunately.
