### ISSUE TITLE
Presto is slower for oracle connector

### ISSUE THREAD

**Issue by surendraGaddam99** [prestodb/presto#5790]
Hi,

I tried to  execute sql queries on presto server using oracle connector but they are taking more time i.e 40 to 50 secs for query execution.

My observations on presto-cli 0.77 using presto server 0.77 with oracle connector
Query execution time observed on Presto CLI is 40 to 50 secs.

My observations on presto-cli 0.147 using presto server 0.147 with oracle connector
Query execution time observed on Presto CLI is 40 to 50  secs.

![image](https://cloud.githubusercontent.com/assets/19906954/17400847/ee51d7ac-5a67-11e6-8d66-18429a1e244b.png)

So upgrading to presto server from 0.77 to 0.147 didnt solved my issue of  query execution speed.
For Mysql connector i can see queries getting executed within 5 secs very fast.

I have used below shown oracle plugin for creating oracle connector.
https://github.com/marcelopaesrech/presto-oracle

Is there any way we can increase query execution speed for this oracle connector so that queries executes faster same as mysql connector.

Thanks
Surendra

**Comment by cawallin** [comment]
You need to file an issue with that github project, then. I'm going to close this issue.
