### ISSUE TITLE
Aggregation on double column may return nondeterministic results

### ISSUE THREAD

**Issue by kokosing** [prestodb/presto#5798]
Let:

```
CREATE OR REPLACE VIEW revenue AS
  SELECT
    l_suppkey as supplier_no,
    sum(l_extendedprice * (1 - l_discount)) as total_revenue
  FROM
    lineitem
  WHERE
    l_shipdate >= DATE '1996-01-01'
    AND l_shipdate < DATE '1996-01-01' + INTERVAL '3' MONTH
GROUP BY
  l_suppkey;
```
then the below query returns 0 or 1 depending on internal query tasks execution order. While `0` is an incorrect result for below query.

```
SELECT
  count(*)
FROM
  revenue
WHERE
  total_revenue = (SELECT max(total_revenue) FROM revenue)
```

IMO it could be acceptable that aggregation on double can have slight result error, but non deterministic error for the same query on the same input is unacceptable.

Solving this issue will make TPC-H query 15 to pass.

My intuition tells that different execution order of tasks for aggregate FINAL and PARTIAL may produce different results.

One way to solve above query is to make Presto to populate VIEW only once per query and the redistribute results to all the stages (operators) which are reading that view. In that way query should be executed much faster. Such approach requires deeper analysis as it is possibility it may lead query to deadlock

**Comment by kokosing** [comment]
Here is a reproduction test:
https://github.com/Teradata/presto/commits/feature_double_aggregation_bug ,
https://github.com/Teradata/presto/commit/17c6cd82ea52539a994e810046e65f477ec71b7c

**Comment by dain** [comment]
The Presto engine can decide to divide up the rows into an arbitrary number of segments, independently aggregate these and then independently aggregate the results.  This is for a number of reasons, like increasing parallelism for a query to reduce wall time, or reducing parallelism to reduce resource usage by a query (a.k.a., to prioritize another query).  Additionally, we may add additional levels of aggregation to efficiently span the query out to more nodes.  The final query plan and actual execution will depend on a number of factors that will change from query to query.  Even if we could nail some of these down to reduce variance in calculations over approximate datatypes, I don't think we should make any guarantees here so this should not be a bug.

If you want consistent results, you will need to change total_revenue to a exact type either in the source table or by casting before calling `sum`.

**Comment by kokosing** [comment]
Ok, sounds good to me.

@dain Thanks for such detailed explanation.
