### ISSUE TITLE
Comparison operators should operate only on a single type T

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#5800]
Currently you can define comparison operators like: `EQUAL(T,U)` for example, `EQUAL(bigint, double`. This creates a number of problems, such as it breaks constant folding, since "equals" is no longer the same as "interchangable". Also, it doesn't really make sense from a type theory perspective, where there should be a "equatable" type class that defines a `EQUAL(T,T)` method.
1) we should change `EQUAL(varchar(x), varchar(y))` to `EQUAL(varchar(x), varchar(x))`, and all other comparisons.
2) same for `decimal`
3) we should add validation that comparisons must have the form `op(T,T)`

**Comment by sopel39** [comment]
I think that the `CHAR` type case shows that `op(char(x), char(x))` operators are not enough. If we want to account for char lengths, then `op(char(x), char(y))` are required. Maybe we should separate meaning of "equal" and "interchangeable". Two values might be logically equal but not strictly equal (e.g: not interchangeable).

Maybe we should add `isEquivalent(Type A, Type B)` method to `TypeRegistry`? It would return true only if values from type `A` can be replaced with equal values from type `B`? This method would return false for `char(x), char(y)`, but true for `varchar(x), varchar(y)` or `decimal(p1,s1), decimal(p2,s2)`.

Additionally, If we force decimal operators to take the same types, then there would be an extra unnecessary coercion performed. Also a runtime exception will be thrown if coercion result exceeds max decimal value. Without this extra coercion, broader decimal values can be compared.

FYI: @fiedukow @losipiuk

**Comment by sopel39** [comment]
Another issue is: https://github.com/prestodb/presto/pull/5501/files/88ccad2c435599edf5b35542f89a88c7da11d4d5#r73861850. I think that `equalTo` from `Type` class is misused in JOIN case. I think that ideally type comparison semantic should be pluggable in `TypeRegistry` and moved out of SPI. However I think it might be extremely difficult to do. However, block versions of `equalTo` and `compareTo` that operate on different types should probably be pluggable via `TypeRegistry`.

**Comment by cberner** [comment]
One issue with introducing an "interchangable" operator is deciding when to use it. For example, given x is `varchar(1)`, y is `varchar(2)` and `x = y`. Should it resolve to `EQUAL(x, y)` or `INTERCHANGABLE(CAST(x as varchar(2)), y)`.

I'm going to look through the SQL spec to see if it addresses this issue of comparison. If one of you could as well, that would be great!

**Comment by sopel39** [comment]
From my understanding of CHAR case, `EQUAL(x, y)` should be used. Otherwise you loose length information and cannot between distinguish `CHARs` with different lengths.

So do you think that introducing such `strictEquals(x,y)/INTERCHANGABLE(x,y)` is a good way forward? We would be happy to work on that since this involves a lot of our code base.

**Comment by cberner** [comment]
I'm not sure. I was discussing this with @martint yesterday, and it's not clear whether that's the right thing to do, or just to allow `EQUAL(x, y)` and fix the code base to support that

**Comment by cberner** [comment]
Depends on https://github.com/prestodb/presto/pull/5778
