### ISSUE TITLE
java.lang.VerifyError with a query

### ISSUE THREAD

**Issue by nezihyigitbasi** [prestodb/presto#5802]
Below query fails with a `java.lang.VerifyError: Bad type on operand stack` with master build (9db10aa)
```Sql
select a.orderkey from (
            (select orderkey from tpch.sf100.lineitem limit 100) a 
            join 
            (select orderkey from tpch.sf100.lineitem limit 100) b 
            on a.orderkey
);
```

**Comment by AlekseiS** [comment]
Fixed as part of https://github.com/prestodb/presto/pull/6229
"join on" condition is invalid in this query
