### ISSUE TITLE
Unable to read Hive tables created by Presto due to permission errors

### ISSUE THREAD

**Issue by suvodeep-pyne** [prestodb/presto#5840]
When presto creates a Hive table with SQL standard permissions enabled, the tables are created with the privilege "ALL" granted to the user creating the table. While this seems correct, this doesn't work with Hive since ALL needs to be translated to its constituent privileges - SELECT, UPDATE, INSERT, DELETE (see: org.apache.hadoop.hive.ql.security.authorization.plugin.sqlstd.SQLPrivilegeType)

When you grant Hive privileges through the Hive CLI or Beeline, granting ALL translates to granting the above 4 privileges individually which works correctly with the Hive SQL standard auth.

**Comment by martint** [comment]
This is already fixed
