### ISSUE TITLE
Support pattern matching via MATCH_RECOGNIZE

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#5850]
Pattern matching allows a number of use cases that are difficult or impossible to do otherwise. This is specified in SQL:2016 as `MATCH_RECOGNIZE` in *4.17 Row pattern matching*.

Oracle has had an implementation of this for a while and very likely matches the standard [1] [2] [3].

1. http://docs.oracle.com/database/121/DWHSG/pattern.htm
2. http://www.oracle.com/ocom/groups/public/@otn/documents/webcontent/1965433.pdf
3. http://www.oracle.com/technetwork/issue-archive/2013/13-nov/o63asktom-2034271.html

**Comment by brianrreed** [comment]
It would be nice if this were added. This is a common use case for IoT.
