### ISSUE TITLE
Add Travis config for CI-only tests

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#5864]
Some connectors, such as PostgreSQL, disable the distributed tests unless the `ci` profile is activated. We should add those to the Travis build matrix.

**Comment by maciejgrzybek** [comment]
CC: @ArturGajowy

**Comment by ArturGajowy** [comment]
I think that's a lot of additional build time which could easily block the build queue.

This sounds like a good candidate for nightly builds, on which I'm working ATM. See:
- #5928 Allow running product tests with arbitrary/downloaded artifacts
- [sample build](https://travis-ci.org/ArturGajowy/presto-checks-master/builds/154788769) in the prototype nightly builds repo

**Comment by ArturGajowy** [comment]
@electrum WDYT?

**Comment by electrum** [comment]
If we run them separately, it shouldn't increase the build time. That's why I suggested adding them to the matrix. If we have a problem with not enough slots, we can pay Travis to increase it.

Though longer term, there's more benefit to reorganizing the tests. Many of the distributed tests are for the engine and don't test additional paths or cases for connectors. The idea with smoke tests is that they provide full coverage for connectors. Unfortunately, that's not true today.

**Comment by ArturGajowy** [comment]
>If we have a problem with not enough slots, we can pay Travis to increase it.

This solves the problem for the prestodb repo, but makes things worse for the other forks... I'd say we should avoid that if we can.

Also, not running those tests at all did not seem to cause a lot of harm so far (I might not have a full view, though). Then why not run them nightly and track how often they fail to see how much value running them every build would bring?
