### ISSUE TITLE
Index joins are disabled if followed by a filter

### ISSUE THREAD

**Issue by erichwang** [prestodb/presto#5887]
There was a regression added in 0.148 that disables index joins if there are filters applied after the join: introduced in this commit:
https://github.com/prestodb/presto/commit/983091db830e7ae58baa8f632ee407586ddd1112

Instead of disabling index joins, we should turn the filter into an explicit filter node after the index join (until index joins properly support inherent filtering).

**Comment by joy-yao** [comment]
https://github.com/prestodb/presto/commit/d63731891c7e0e75145e79699566341f91f7c9da
