### ISSUE TITLE
Product tests should fail if -t doesn't match any tests

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#5891]
I was trying to run all SQL tests in a directory and tried a couple of ways:
```
presto-product-tests/bin/run_on_docker.sh singlenode -t sql-tests/testcases/window_functions
presto-product-tests/bin/run_on_docker.sh singlenode -t sql-tests/testcases/window_functions*
```
I assume both of these didn't match anything:
```
===============================================
tempto-tests
Total tests run: 0, Failures: 0, Skips: 0
===============================================
```
However, I think it would better to fail loudly and as early as possible. Otherwise, it's easy to have a typo and think you ran the tests.

**Comment by kokosing** [comment]
I will take care of that.

**Comment by kokosing** [comment]
@electrum 
```
presto-product-tests/bin/run_on_docker.sh singlenode -t window_functions
```

should work with the newest release. Your issue is related with https://github.com/prestodb/tempto/issues/132, which was fixed recently
