### ISSUE TITLE
Allow running all product tests in a directory

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#5892]
It would be helpful if something like this worked:

```
presto-product-tests/bin/run_on_docker.sh singlenode -t sql-tests/testcases/window_functions
```

And even better if I can specify multiple directories.

The same goes for Java based tests: allow specifying an entire class or multiple classes or packages.

**Comment by kokosing** [comment]
I will take care of that.

**Comment by kokosing** [comment]
It should work that with the new tempto release:

Try:
```
presto-product-tests/bin/run_on_docker.sh singlenode -t window_functions,limit
```
