### ISSUE TITLE
Reduce Raptor metadata queries in execution path

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#5919]
Running a simple query like `SELECT * FROM orders` executes 7 metadata queries, some of them duplicates. We could fix this with caching, though we should consider some SPI changes that would improve all connectors that don't otherwise need caching. In particular, I think we could ask for the table handle first and skip the view check if that succeeds.

**StatementAnalyzer: Metadata.getView()**

```
SELECT schema_name, table_name, data FROM views WHERE (schema_name = ? OR ? IS NULL) AND (table_name = ? OR ? IS NULL) ORDER BY schema_name, table_name
```

**StatementAnalyzer: Metadata.getTableHandle()**

```
SELECT t.table_id, t.distribution_id, d.bucket_count, t.temporal_column_id FROM tables t LEFT JOIN distributions d ON (t.distribution_id = d.distribution_id) WHERE t.schema_name = ? AND t.table_name = ?
SELECT t.schema_name, t.table_name, c.column_id, c.column_name, c.ordinal_position, c.data_type FROM tables t JOIN columns c ON (t.table_id = c.table_id) WHERE t.table_id = ? ORDER BY c.ordinal_position
```

**StatementAnalyzer: Metadata.getTableMetadata()**

```
SELECT t.schema_name, t.table_name, c.column_id, c.column_name, c.ordinal_position, c.data_type FROM tables t JOIN columns c ON (t.table_id = c.table_id) WHERE t.table_id = ? ORDER BY c.ordinal_position
```

**StatementAnalyzer: Metadata.getColumnHandles()**

```
SELECT t.schema_name, t.table_name, c.column_id, c.column_name, c.data_type FROM tables t JOIN columns c ON (t.table_id = c.table_id) WHERE t.table_id = ? ORDER BY c.ordinal_position
```

**InputExtractor: Metadata.getTableMetadata()**

```
SELECT t.schema_name, t.table_name, c.column_id, c.column_name, c.ordinal_position, c.data_type FROM tables t JOIN columns c ON (t.table_id = c.table_id) WHERE t.table_id = ? ORDER BY c.ordinal_position
```

**DistributedExecutionPlanner: SplitManager.getSplits()**

```
SELECT node_id, node_identifier FROM nodes
```

**Comment by buremba** [comment]
It would be great for short-running concurrent queries. Also, if a query references multiple Raptor tables, that number can be quite high. (7 * number of referenced tables)
