### ISSUE TITLE
InterleavedBlock.getRegion does not update sizeInBytes

### ISSUE THREAD

**Issue by dain** [prestodb/presto#5926]
When transporting pages between machines, `PageSplitterUtil` breaks pages up into smaller units to reduce buffer requirements.  The logic is pretty simple, repeatably split into two pages using `getRegion` util the pages are smaller than a limit.  This does not work with the new `InterleavedBlock` code because `getRegion` does not return a block with an updated `sizeInBytes`.  The means that if we encounter a page with a large `InterleavedBlock`, we move the data one row at a time.

**Comment by martint** [comment]
This is already fixed
