### ISSUE TITLE
Typo in mongodb connector document.

### ISSUE THREAD

**Issue by javainthinking** [prestodb/presto#5941]
https://prestodb.io/docs/current/connector/mongodb.html

Typo at section:

**mongodb.required-replica-set**  -> mongodb.cursor-batch-size

Limits the number of elements returned in one batch. A cursor typically fetches a batch of result objects and stores them locally. If batchSize is 0, Driver’s default will be used. If batchSize is positive, it represents the size of each batch of objects retrieved. It can be adjusted to optimize performance and limit data transfer. If batchSize is negative, it will limit of number objects returned, that fit within the max batch size limit (usually 4MB), and cursor will be closed. For example if batchSize is -10, then the server will return a maximum of 10 documents and as many as can fit in 4MB, then close the cursor.

**Comment by maciejgrzybek** [comment]
Closing since #5962 is merged.
