### ISSUE TITLE
how to write a new connector

### ISSUE THREAD

**Issue by yuliman** [prestodb/presto#5961]
I want to write a new connector to joins in a new database using Presto.Can
anyone please suggest on how to start.Now I start by forking presto-example-http plugin,but
I just know little about presto.How can write a connector to a new database of nosql.
Any guidance will be of lot of help.

**Comment by maciejgrzybek** [comment]
@yuliman mailing list is probably much better place for such a question given you may get much better response there. Have a look here: https://groups.google.com/forum/#!forum/presto-users

But I can give you my two cents:
* have a look at https://prestodb.io/docs/current/develop.html
* read code of other connectors (Hive, JDBC-based, e.g. MySQL/PostgreSQL).
* start with writing `ConnectorMetadata` and see if you can `show tables`, `show schemas`, `show columns from` from your connector.

**Comment by yuliman** [comment]
thanks a lot.
