### ISSUE TITLE
Presto reads tables incorrectly if two Hive tables are created at the same location.

### ISSUE THREAD

**Issue by naveenmahadevuni** [prestodb/presto#5965]
I created two Hive tables at the same location. Hive reads the two tables independently, but presto reads all data files even if only one table is queried. Below is the reproducible case.

```
--FROM HIVE

CREATE TABLE test1 (col1 INT, col2 INT) 
stored as orc
LOCATION '/apps/hive/warehouse/test1';

insert into test1 values(1,2);
insert into test1 values(3,4);

-- Returns count of 2
select count(*) from test1;

CREATE TABLE test2 (col1 INT, col2 INT) 
stored as orc
LOCATION '/apps/hive/warehouse/test1';

insert into test2 values(1,2);
insert into test2 values(3,4);

-- Returns count of 2
select count(*) from test2;
```
```
-- FROM PRESTO
-- Returns count of 4 for test1 table where as Hive returns the correct count of 2.
presto> select count(*) from hive_dsn.default.test1;
 _col0
-------
     4
(1 row)
```

**Comment by naveenmahadevuni** [comment]
An update to my previous comment. Hive returns the count correctly, but when I select *, hive also returns incorrect number of rows.

hive> select * from test2;
OK
1       2
3       4
1       2
3       4
Time taken: 0.107 seconds, Fetched: 4 row(s)
hive> select * from test1;
OK
1       2
3       4
1       2
3       4
Time taken: 0.054 seconds, Fetched: 4 row(s)

**Comment by haozhun** [comment]
From your description, it looks like
* Hive returned `count` incorrectly
* Hive returned content of the table correctly.
* Presto returned `count` correctly.
* Presto returned content of the table correctly.

I suggest that you file an issue with Hive to figure out why Hive returns `count` incorrectly.

**Comment by nmahadevuni** [comment]
Hive folks say the behavior is undefined, because count can be computed from statistics. I have asked if they can document it. Closing this issue.

**Comment by GuoPhilipse** [comment]
@naveenmahadevuni  have u found any PR for solving the same location issue?

**Comment by naveenmahadevuni** [comment]
@Guo

> @naveenmahadevuni have u found any PR for solving the same location issue?

There is no solution for this. We should not create two tables at the same location.

**Comment by GuoPhilipse** [comment]
Thanks naveenmahadevuni !
















在 2020-03-31 15:23:59，"naveenmahadevuni" <notifications@github.com> 写道：

@guo

@naveenmahadevuni have u found any PR for solving the same location issue?

There is no solution for this. We should not create two tables at the same location.
