### ISSUE TITLE
View creation fails if source table name contains quotes

### ISSUE THREAD

**Issue by jpavlick** [prestodb/presto#5968]
I've been creating views using the hive connector (referencing tables coming from the mongodb connector) and it works fine except for tables that have numbers/reserved words in them. Example

```
CREATE VIEW content as select * from mongodb."222".articles;
Query failed: Formatted query does not parse
```

I noticed that there is a previous issue with this - https://github.com/prestodb/presto/issues/2074 - but it was a long time ago. I'm running Presto 0.147 on AWS. Please let me know if there's a workaround for this or if more information is needed. Thanks for the help!

**Comment by nimahajan** [comment]
Have same issue. I have a mysql database with - in its name. So I have to use quotes. If I replace that name with other normal string, it works.
