### ISSUE TITLE
Add support for a "distinct from" operator

### ISSUE THREAD

**Issue by martint** [prestodb/presto#5969]
This is needed to support all operations that rely on distinct semantics. Currently, many of them are implemented using EQUALS operators or just don't allow use in those contexts (e.g., arrays containing nulls).

This is a prerequisite for:
* https://github.com/prestodb/presto/issues/3568
* https://github.com/prestodb/presto/issues/4075
* https://github.com/prestodb/presto/issues/3569

**Comment by haozhun** [comment]
Here are examples that use @IsNull annotation for scalar function/opreator implementation: https://github.com/prestodb/presto/pull/5323/commits/e0457c29993c18becd7f4a894428f712bf7fe978. It also shows you how to work with arrays and maps in Presto.

Here are some other related code that you can look at: `BigintOperators`, `DoubleOperators`, `ArrayEqualOperator`, and `MapEqualOperator`.

**Comment by idemura** [comment]
Working on this.
