### ISSUE TITLE
Move Plan Assertion framework from test to main

### ISSUE THREAD

**Issue by erichwang** [prestodb/presto#5979]
Currently the plan assertion lib (package com.facebook.presto.sql.planner.assertions) is in the presto-main module tests. We should move it up to main so that other projects that depend on Presto can also use it to assert plan structures.

**Comment by kokosing** [comment]
Plan assertion framework was designed to test `LogicalPlanner` and all optimization rules. All of these classes are in `presto-main`

Can you please explain a bit more your motivation. Do you mean other presto module or external project?

If the latter maybe using `test-jar` as dependency would work for you: https://maven.apache.org/guides/mini/guide-attached-tests.html

**Comment by erichwang** [comment]
I was thinking of using the assertion framework to test some of the plans generated when used in conjunction with certain connectors. I guess I will try the test-jar dependency first.
