### ISSUE TITLE
Presto stats planning time is including queueing time

### ISSUE THREAD

**Issue by erichwang** [prestodb/presto#5980]
I noticed this when Presto was reporting super long planning times, but it looks like this was just because the queues are really full.

**Comment by cberner** [comment]
I don't think this is accurate. I reviewed the code and it looks correct (queueing time is not included). Also, see the email I sent you of our query logs which shows that lots of queries have longer planning time than queueing time

**Comment by erichwang** [comment]
@cberner, are you sure? i've seen that total planning time is always longer than queueing time.

Actually, if you look at com.facebook.presto.execution.QueryStateMachine#transitionToStarting and every other method there, it looks like totalPlanningTime is always created from the beginning of the query?

**Comment by cberner** [comment]
Ah, yes I see. I thought you meant the planning time in `QueryCompletedEvent`

**Comment by cberner** [comment]
@dain can you take a look? The way planning time and queued time are handling in that class doesn't seem to make sense

**Comment by dain** [comment]
I have no idea why it is written that way, but is should be rewritten like how `finishingTime` is calculated using a `finishingStartNanos`.

**Comment by haozhun** [comment]
@idemura Do you want to try this one?
