### ISSUE TITLE
How to dynamically set catalog properties 

### ISSUE THREAD

**Issue by surendraGaddam99** [prestodb/presto#5982]
Hi,

Is there any way to set the presto catalog connection properties dynamically ?
presto-server-0.77/etc/catalog/oracle.properties 

connector.name=oracle
connection-url=jdbc:oracle:thin:@xxxx.com:1521:xxxx
connection-user=AF310ST1
connection-password=test123

Is it possible to dynamically set these catalog values from application to which presto is connected.
Suppose user wants to connect to some other schema eg: AA360ST2 then any way to set the catalog parameter dynamically ?

Thanks
Surendra

**Comment by petroav** [comment]
@surendraGaddam99 I'm afraid any changes to catalog property files will not be loaded by Presto automatically. You'll have to restart the Presto process for these changes to be picked up.

**Comment by miniway** [comment]
This might not be recommend or work at future release. But what I'm doing now with the following codes
```
            Announcer announcer ... ;
            ServiceAnnouncement announcement = announcer.getServiceAnnouncements().get(...);
            Map<String, String> properties = Maps.newHashMap(announcement.getProperties());
            // fill or change properties
            announcer.removeServiceAnnouncement(announcement.getId());
            announcer.addServiceAnnouncement(
                    serviceAnnouncement(announcement.getType())
                            .addProperties(properties)
                            .build());
            announcer.forceAnnounce(); // optional
```

**Comment by yuananf** [comment]
This is discussed in #2445

**Comment by surendraGaddam99** [comment]
Hi,

Suppose i have 3 presto  catalog properties files which got loaded during presto server start 
oracle1.properties  ,oracle2.propertie ,oracle3.properties 

From airpal application there is one dropdown for list of schemas .
based on user selection of particular schema i need to connect to particular catalog properties file dynamically.

Somewhere in the airpal application code can i set the prestocatalog value dynamically using presto API based on user selection. Is this scenario possible ? any suggestions ?

Thanks
Surendra

**Comment by rschlussel** [comment]
See #2445 for discussion of adding support for dynamically loaded catalogs.  airpal questions should be asked to the airpal project.

**Comment by ramveer93** [comment]
there is [this](https://github.com/prestodb/presto/pull/12605) pull request for this issue, once it merged it should be available with code
