### ISSUE TITLE
Change from FixedWidthBlock to LongArrayBlock

### ISSUE THREAD

**Issue by Praveen2112** [prestodb/presto#5988]
Hi,
In previous presto version (0.147) the BigInt data type was represented by FixedWidthBlock(Slice) but in the current version it was represented by LongArrayBlock. Any reasons for switching from Slice to Long Array ?

**Comment by buremba** [comment]
It's probably because JVM can take advantage of JIT optimizations for long[] but has limited support for Slice which is often represented as byte[] and uses Unsafe to access data inside the buffer.

**Comment by erichwang** [comment]
Exactly what @buremba said, we saw major performance improvements for read and writing from long[] vs Slice in most operators.

**Comment by dain** [comment]
Once Java 9 is out, we will likely move all of this to varhandles http://openjdk.java.net/jeps/193
