### ISSUE TITLE
presto can't resolved json type

### ISSUE THREAD

**Issue by zousss** [prestodb/presto#5989]
my postgresql 9.4 table has json type column , but i can't select it from presto and i don't know why,maybe  it's a bug?
one record of search_info column from PG:
{"多功能":3039,"断电":23277,"早餐":11214,"自动":23277,"迷你":2669,"家用":1756,"双层":742,"厨房":6243}
execute on presto:
select search_info from myTable limit 3;
Column '"search_info"' cannot be resolved

**Comment by Bennyelg** [comment]
Anything new regarding this issue?

**Comment by stewartpark** [comment]
This also happens on MySQL catalogs. Any resolution for this?
