### ISSUE TITLE
presto catalog properties 

### ISSUE THREAD

**Issue by surendraGaddam99** [prestodb/presto#5990]
Hi,

Is there any way to set the presto catalog connection properties dynamically ?
presto-server-0.77/etc/catalog/oracle.properties

connector.name=oracle
connection-url=jdbc:oracle:thin:@xxxx.com:1521:xxxx
connection-user=AF310ST1
connection-password=test123

Thanks
Surendra

**Comment by petroav** [comment]
You already posted this question in https://github.com/prestodb/presto/issues/5982. Please avoid duplicating discussions.
