### ISSUE TITLE
Use async for RaptorPageSink finish

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#5993]
The `finish()` method in `ConnectorPageSink` is synchronous. If it takes a long time, which can happen for Raptor if there are many shards to copy to the backup store (which uses a fixed size thread pool), this can tie up all worker threads. Making this async would prevent writes from interfering with other operations.

**Comment by AlekseiS** [comment]
Uploaded a PR: https://github.com/prestodb/presto/pull/6204

**Comment by AlekseiS** [comment]
Merged
