### ISSUE TITLE
Support transparent query retries

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#6006]
Currently when a query fails the client observes this immediately. However, any query where the client has not observed results yet (like INSERTs) can be retried transparently by Presto. Additionally, we may want to automatically adjust some of the query settings to make the query succeed. For example, if distributed joins are turned off and the query ran out of memory, they could be turned on for the second attempt.
One challenge is handling the `QueryId` as currently it's passed back to the client, and changing it in the middle of the query execution would be disruptive. I would suggest introducing a new identifier like "execution id" which identifies the execution of the query. Most places where QueryId is currently used would then use this new id. This also would allow us to have the client provide the "query id" in the future, which is something that we want to do.
The retry logic itself will probably need to go in a new abstraction separating the query from a particular execution of the query, but might also go in `SqlQueryManager`.

**Comment by stagraqubole** [comment]
Hi @geraint0923 @cberner, is this feature planned for near future?
