### ISSUE TITLE
Implement HBase connector

### ISSUE THREAD

**Issue by damiencarol** [prestodb/presto#6010]
Throw an issue here as I'm working on it and will push a PR soon.

Plan to have a production ready plugin for the end of the year.

Main design choices:
- Tables defined in JSON configuration files (like kafka/redis/mongodb connector)
- Split aligned to region with HBase key pruning
- parallelism aligned to region to scale
- Manage configuration file for HBase (auto-updater)

**Any advices, questions or tips are welcomes (specialy if you had started a plugin like me)**

**Comment by adamjshook** [comment]
@damiencarol You may find some of the work for Apache Accumulo helpful, currently sitting in https://github.com/prestodb/presto/pull/5030.

**Comment by damiencarol** [comment]
@adamjshook yeah, I'm reading the PR code right now

**Comment by adamjshook** [comment]
@damiencarol I'm happy to answer any questions or give you any pointers on some BigTable-esque optimizations I've built to improve query times.

**Comment by damiencarol** [comment]
@adamjshook did your connector run in production ? also did you implemented insert/update/delete ?

**Comment by adamjshook** [comment]
@damiencarol Yes, it's been in production since March/April or so.  `INSERT` is supported, but we use the Java APIs and some tools I've built for higher throughput.  Presto doesn't support `UPDATE` (as far as I know), but you can issue another `INSERT` statement that shares the same Accumulo row ID and it effectively acts as an update.  I haven't implemented `DELETE` yet -- haven't had a use case come up to drive the effort of implementing it.

**Comment by damiencarol** [comment]
First naive version here #6037 .
Please be kind with me, it is a work in progress.

**Comment by yxydde** [comment]
what the progress ?

**Comment by nemo326** [comment]
what the progress now,please ? ~~~

**Comment by GrigorievNick** [comment]
Any news about this part?

**Comment by JamesRTaylor** [comment]
There's a PR for an Apache Phoenix connector here [1] which would allow you
to read an HBase table.

[1] https://github.com/prestodb/presto/pull/10536

**Comment by ganeshjothikumar** [comment]
@JamesRTaylor Is it fair to say the Presto -> HBase (through Phoenix connector) is fairly nascent and probably not widely used in large production systems. Looking at doing something like this for a fairly ;arge first class production system. So hence wanted to know how hardened this is and current usage.

**Comment by willshen** [comment]
What's the latest on this PR (i.e., is it moving forward)?

**Comment by ShawshankLin** [comment]
what the progress now??

**Comment by Crossoverrr** [comment]
https://github.com/analysys/presto-hbase-connector
