### ISSUE TITLE
Is this a  presto  exception bug ? 

### ISSUE THREAD

**Issue by VIPchengcheng** [prestodb/presto#6018]
I  found a bug in the CachingHiveMetastore.class.  In the addPartitions method, when partition already exists, the error will be catched by  AlreadyExistsException and continue to throw TableNotFoundException instead of  partition already existing exception. 

fix this steps:
     1.    add new class under the package " com.facebook.presto.hive ", the  class name is PartitionAlreadyExistsException. the details is as followings:
![partitionalreadyexistsexception](https://cloud.githubusercontent.com/assets/18230274/18202230/5d06c168-7141-11e6-85cc-813bafdebb54.png)
 
    2.  add code in HiveErrorCode.class.   The details is as followings:

![errorcode](https://cloud.githubusercontent.com/assets/18230274/18202345/1a5ba792-7142-11e6-9a54-37112015ab7e.png)

  3.  modify the method of "addPartitions method"  in CachingHiveMetastore.class.
![addpartition](https://cloud.githubusercontent.com/assets/18230274/18202407/53826380-7142-11e6-8120-4623c8b04051.png)

**Comment by haozhun** [comment]
This code has moved to `ThriftHiveMetastore` in trunk. It has been fixed to throw the proper exception type as well.
