### ISSUE TITLE
Support English month suffix formatter for MySQL date functions

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#6025]
`date_format` and `date_parse` should support `%D`

**Comment by yuananf** [comment]
I can take this one.

**Comment by cberner** [comment]
You'll need to modify DateTimeFunctions.dateFormat() and DateTimeFunctions.dateParse()

You can add tests to TestDateTimeFunctions.java

**Comment by thezhangwei** [comment]
Hi, sorry for the late response.
It seems like [DateTimeFunctions](https://github.com/prestodb/presto/blob/f4884849f646148f3deebd0d4f3549c9124dcb9f/presto-main/src/main/java/com/facebook/presto/operator/scalar/DateTimeFunctions.java#L975) is very tightly coupled with [Joda-time](https://github.com/JodaOrg/joda-time).
It pretty much just delegates everything to it, which doesn't support something like %D.
The fact that Presto doesn't support %D at this point seems to be a side affect of this design choice.

One thing I thought about is to extend the Joda [DateTimeFormatterBuilder](https://github.com/JodaOrg/joda-time/blob/909046aa9aab5fae75e2152fd6ded722a4d5aba2/src/main/java/org/joda/time/format/DateTimeFormatterBuilder.java#L71) in Presto:
Slapping a level on top of it, just to handle the %D case. It sounds kind of ugly, but I'm not seeing a better option... ;)

@cberner Am I missing sth? Just want to make sure we are seeing the same picture before making the change.

Thanks,

**Comment by electrum** [comment]
You need to create a custom `DateTimeParser` and `DateTimePrinter` and append them to `DateTimeFormatterBuilder` using `append(printer, parser)`.

**Comment by electrum** [comment]
http://stackoverflow.com/a/17236321
