### ISSUE TITLE
Support for Cassandra UDT

### ISSUE THREAD

**Issue by EdwinGuo** [prestodb/presto#6047]
When I query cassandra cf that with UDF, the presto query cli will complain: Query ***\* Failed, CassandraType is null, due to there is support for Cassandra UDF yet: https://github.com/prestodb/presto/blob/master/presto-cassandra/src/main/java/com/facebook/presto/cassandra/CassandraType.java

**Comment by thecubed** [comment]
Here's me and a coworker's quick hack to make Presto 0.152 not fail on UDT. 
This does not add support for the UDT, but rather allows Presto to emit a string (`[Cassandra UDT not supported]`) in place of the UDT until such support is added by the Presto maintainers.

https://github.com/thecubed/presto/commit/56241b6942837ddfa8f37b63f75ef6fec90a862b

This probably shouldn't be a PR unless it gets cleaned up and tested some more. If anyone has suggestions, please let me know.

**Comment by ttaranov** [comment]
I'm wondering whether it would be better to try serialize UDT to json string somehow rather than throwing errors

**Comment by electrum** [comment]
That seems reasonable to me.

**Comment by corrius** [comment]
I have created a pull request with a fix for this, serializing the UDT as json strings.
As this is my first pr to an OS project I would thank any feedback you can provide.

I will improve the tests in the following days.

**Comment by dain** [comment]
If the UDTs are have a well known schema, you should be able to map them to a ROW type (e.g., a struct).

**Comment by corrius** [comment]
But if I understand the Cassandra connector correctly, lists, maps and sets are also serialized into String, should we then also map these into their type, rather than serialize them as a String?

**Comment by cawallin** [comment]
Yes, they should ideally be mapped to the actual type.

**Comment by corrius** [comment]
Ok, I will look into it, could you point me to another connector which maps collections so I can use it as reference? I am completely new to Presto.
Thanks

**Comment by cawallin** [comment]
Great! Take a look at HiveType (especially getTypeSignature), referenced by HiveMetadata#getTableMetadata.
