### ISSUE TITLE
v1/statement does not always return single-line results

### ISSUE THREAD

**Issue by apleweghostery** [prestodb/presto#6074]
I am using the REST API to run queries and fetch results. Sometimes, when I get to the final URI and I've run a query that returns a single result line, there is no "data" element. For instance:

{
  "id" : "20160908_163608_00035_2xz9i",
  "infoUri" : "http://*.*.*.*:8889/query.html?20160908_163608_00035_2xz9i",
  "columns" : [ {
    "name" : "Tag Count",
    "type" : "bigint",
    "typeSignature" : {
      "rawType" : "bigint",
      "typeArguments" : [ ],
      "literalArguments" : [ ],
      "arguments" : [ ]
    }
  } ],
  "stats" : {
    "state" : "FINISHED",
    "queued" : false,
    "scheduled" : true,
    "nodes" : 20,
    "totalSplits" : 5526,
    "queuedSplits" : 0,
    "runningSplits" : 0,
    "completedSplits" : 5526,
    "userTimeMillis" : 87230,
    "cpuTimeMillis" : 96444,
    "wallTimeMillis" : 2569867,
    "processedRows" : 946656771,
    "processedBytes" : 233689170567,
    "rootStage" : {
      "stageId" : "0",
      "state" : "FINISHED",
      "done" : true,
      "nodes" : 1,
      "totalSplits" : 1,
      "queuedSplits" : 0,
      "runningSplits" : 0,
      "completedSplits" : 1,
      "userTimeMillis" : 60,
      "cpuTimeMillis" : 64,
      "wallTimeMillis" : 67,
      "processedRows" : 5525,
      "processedBytes" : 49725,
      "subStages" : [ {
        "stageId" : "1",
        "state" : "FINISHED",
        "done" : true,
        "nodes" : 20,
        "totalSplits" : 5525,
        "queuedSplits" : 0,
        "runningSplits" : 0,
        "completedSplits" : 5525,
        "userTimeMillis" : 87170,
        "cpuTimeMillis" : 96380,
        "wallTimeMillis" : 2569800,
        "processedRows" : 946656771,
        "processedBytes" : 233689170567,
        "subStages" : [ ]
      } ]
    }
  }
}

Here is the result from the same query, run a few minutes later:

{
  "id" : "20160908_172614_00037_2xz9i",
  "infoUri" : "http://*.*.*.*:8889/query.html?20160908_172614_00037_2xz9i",
  "columns" : [ {
    "name" : "Tag Count",
    "type" : "bigint",
    "typeSignature" : {
      "rawType" : "bigint",
      "typeArguments" : [ ],
      "literalArguments" : [ ],
      "arguments" : [ ]
    }
  } ],
  "data" : [ [ 946656771 ] ],
  "stats" : {
    "state" : "FINISHED",
    "queued" : false,
    "scheduled" : true,
    "nodes" : 20,
    "totalSplits" : 5522,
    "queuedSplits" : 0,
    "runningSplits" : 0,
    "completedSplits" : 5522,
    "userTimeMillis" : 87620,
    "cpuTimeMillis" : 97046,
    "wallTimeMillis" : 2655658,
    "processedRows" : 946656771,
    "processedBytes" : 234086455040,
    "rootStage" : {
      "stageId" : "0",
      "state" : "FINISHED",
      "done" : true,
      "nodes" : 1,
      "totalSplits" : 1,
      "queuedSplits" : 0,
      "runningSplits" : 0,
      "completedSplits" : 1,
      "userTimeMillis" : 30,
      "cpuTimeMillis" : 56,
      "wallTimeMillis" : 58,
      "processedRows" : 5521,
      "processedBytes" : 49684,
      "subStages" : [ {
        "stageId" : "1",
        "state" : "FINISHED",
        "done" : true,
        "nodes" : 20,
        "totalSplits" : 5521,
        "queuedSplits" : 0,
        "runningSplits" : 0,
        "completedSplits" : 5521,
        "userTimeMillis" : 87590,
        "cpuTimeMillis" : 96990,
        "wallTimeMillis" : 2655600,
        "processedRows" : 946656771,
        "processedBytes" : 234086455040,
        "subStages" : [ ]
      } ]
    }
  }
}

We are using Presto as hosted by AWS. My understanding is they simply deploy the latest stable release unmodified. I have saved off the full query.htm? JSON for both queries, I can post them here after scrubbing sensitive data. 

Thanks!

**Comment by apleweghostery** [comment]
Here are the query detail outputs for the "bad" and "good' runs:
[presto_bad_run.txt](https://github.com/prestodb/presto/files/462732/presto_bad_run.txt)
[presto_good_run.txt](https://github.com/prestodb/presto/files/462733/presto_good_run.txt)

Let me know if you'd like any of the task logs.

Thanks!

**Comment by electrum** [comment]
How do you define "final uri"? Are you fetching all the "nextUri" links?

**Comment by apleweghostery** [comment]
Yes, that's correct. The JSON messages posted above are from following the final "nextUri" links. So, the first run of the query resulted in the final JSON message with a missing "data" element, and the second run resulted in the final JSON message that included the "data" element with the expected results.

**Comment by dain** [comment]
Which client are you using?  Do you have a stack trace?

**Comment by apleweghostery** [comment]
I've written my own client in C#. I'm happy to post the code here.

**Comment by dain** [comment]
So the server will only return a `data` when there is data available.  This protocol uses medium pooling, where the server holds the response for a short period when there is no data and then sends the updated stats.  This keeps the connection "fresh" while pacing out client requests, which makes writing clients easier since you don't need to introduce client side request delays (to avoid DDoSing the server).

**Comment by apleweghostery** [comment]
Ah, so I don't have to program in a delay. That's good to know. However, for the JSON response above I accessed them several minutes after the query finished running (again, same query in both instances). Is there a reason why the first message would be missing the "data" element, i.e. is it possible to poll "wrong" and force the API to return a "final" response before data is available?

**Comment by dain** [comment]
No. When you request the `nextUri` it acknowledges receipt of the response previous response (i.e., the one you got the `nextUri` from).  

@electrum can you post a link to your client REST API notes?

**Comment by apleweghostery** [comment]
For reference, here is the documentation I used when writing my client: https://github.com/prestodb/presto/blob/master/presto-docs/src/main/sphinx/rest.rst

**Comment by apleweghostery** [comment]
Also, if it helps I've observed this behavior using Postman to post queries to v1/statement and then manually following the "nextUri" links.

**Comment by electrum** [comment]
https://github.com/prestodb/presto/wiki/HTTP-Protocol

**Comment by apleweghostery** [comment]
O.k., I think I found the issue on my side -- the API can return "data" in any of the intermediate steps. I'm not checking the intermediate results. For instance, I just ran a query and manually clicked "nextUri" twice:

http://*.*.*.*:8889/v1/statement/20160909_213033_00135_2xz9i/1  <-- "data" element was here
http://*.*.*.*:8889/v1/statement/20160909_213033_00135_2xz9i/2 < -- no "data" element

I don't know if this is anywhere in current documentation, but I expected the last "nextUri" in the chain to always have the "data" element attached.

**Comment by dain** [comment]
@electrum can you clarify that section?  

@apleweghostery, the reason for this is the query might take hours (or even days) before any results are produced, but we want to know if the client is still alive (and if not we kill off the query saving resources).

**Comment by apleweghostery** [comment]
Yeah, makes sense. If I'd paid closer attention to the source, I would have picked up on this too...

**Comment by apleweghostery** [comment]
Thanks a million for your time!
