### ISSUE TITLE
how  to change the data source

### ISSUE THREAD

**Issue by yuliman** [prestodb/presto#6080]
Does anyone know how to change the data source itself in TPCH to my own data source
in the class of TestHiddenColumns?Is the dataSource of TPCH produced by the class of  
TableScanNode?What should I do to achieve?

**Comment by maciejgrzybek** [comment]
@yuliman I'd suggest asking such questions on mailing list: presto-users@googlegroups.com
But let me answer this shortly here:
In general you cannot easily provide your own data source. You'd need to write a connector (similar to TPCH).
Other way, much easier is to use something we do in product tests: use Hive connector to store data. Have a look at e.g. `TestAllDatatypesFromHiveConnector`. But it depends what you need.
Other possibility would be to use `InMemory` connector which is coming (https://github.com/prestodb/presto/pull/5809).
