### ISSUE TITLE
how to get shell retun code？

### ISSUE THREAD

**Issue by zhengguilin** [prestodb/presto#6084]
eg：

meitun_etl@KFK01:bin$/opt/presto/bin/presto --server hc:9980 --catalog hive --schema  default --execute "select \* from tt"
Query 20160909_091217_03555_6cpfp failed: line 1:15: Table hive.default.tt does not exist
select \* from tt

meitun_etl@KFK01:bin$echo $?
0

**Comment by nezihyigitbasi** [comment]
There is an open PR (#3463) for this.

**Comment by cawallin** [comment]
Duplicate of #4016 which has a better description, closing this issue.
