### ISSUE TITLE
Difference between java presto jdbc   and presto server setup using catalog files under etc folder

### ISSUE THREAD

**Issue by surendraGaddam99** [prestodb/presto#6095]
Hi ,

I am new to presto DB .  Have some confusion on presto jdbc and presto server setup.

Need help on in which scenario i have to use presto jdbc code as shown below.
And under which scenario i have to use catalog files setup  under ./presto-server-0.77/etc/catalog

```
   Class.forName("com.facebook.presto.jdbc.PrestoDriver");
    config.getDataSourceFactory().setUrl("jdbc:presto://linadv360pt3.ams.com:8080");
    config.getDataSourceFactory().setDriverClass("com.facebook.presto.jdbc.PrestoDriver");
    config.getDataSourceFactory().setUser("af360st1");
    config.getDataSourceFactory().setPassword("advantage");
    config.getDataSourceFactory().setDefaultCatalog("oracle");
```

Need help on presto jdbc and presto server catalog files setup. which one to use when ?

Thanks
Surendra

**Comment by cawallin** [comment]
@surendraGaddam99 Sorry for the late reply, but you need to use the Presto JDBC code on the client side, and need the Presto server catalog files wherever you're running your Presto server.
