### ISSUE TITLE
Character string casts and type system discussions

### ISSUE THREAD

**Issue by sopel39** [prestodb/presto#6112]
We have investigated SQL standard and how coercions and comparisons should be defined.
The problem, potential solutions and notes are gathered in this document: https://docs.google.com/document/d/1cPzYKZ9K-nI3MkUL7ArSkcQtL7mqz0L0PmLXa_zhxSk/edit?usp=sharing
Please have a look @cberner and @martin
We think we should discuss our way forward with the type system, so it's worth having a hangout again.

FYI: @losipiuk @ilfrin

**Comment by cberner** [comment]
When I looked into how character types were handled in Postgres is seemed to deviate very significantly from the spec. Could you review how other popular SQL databases handle these types? Many areas of the spec related to character types seem poorly thought out to me, so unless there's a broad consensus among other databases I'm not sure we need to follow the spec

**Comment by the6campbells** [comment]
If you plan to support other vendors (Microsoft SQL Server, DB2, Netezza, Vertica, ....) then you will find they follow fixed length char semantics. Hive team seem to have used MySQL or Postgres as their reference point vs considering the standard.  If you deviate, ensure your docs are clear in what your fixed length character semantics are. That way, at least your intent is public vs folks stumble into issues and be unsure whose defect it is (consuming apps, presto local engine or presto-database connector ...)

**Comment by dain** [comment]
There is a project to implement support for fixed length character comparisons (with padding rules).
