### ISSUE TITLE
Increase in time for AddExchanges and AddLocalExchanges Optimizer

### ISSUE THREAD

**Issue by Praveen2112** [prestodb/presto#6121]
Hi,
There is an increase in time for the following two optimizers (AddExchanges and AddLocalExchanges) in the latest version (0.152) when compared with the presto 0.147. When profiled it , we found that the increase in time was due to the following operation **ImmutableMap.copyOf(requireNonNull(symbolTypes, "symbolTypes is null"));**

When we skipped the copy operation  , the time taken for these optimizers reduced drastically.

**Comment by dain** [comment]
How much time did this save?  Also can you give the file and line number of this code (I can't seem to find it)

**Comment by electrum** [comment]
Do you have an example query that has a big speed difference? I would guess
this only affects very complex or specific types of queries.

**Comment by martint** [comment]
It's probably the one in ExpressionAnalyzer. We've had a few of these in the past. It's likely that the map that's being passed around is not already an ImmutableMap, so if there are a lot of fields/expressions/plan nodes, this can get quite expensive.

**Comment by geraint0923** [comment]
@Praveen2112 Could you please try #6128 to see if it can solve your issue? Thanks!

**Comment by Praveen2112** [comment]
@dain we got an improvement upto 10x (from 1.23 seconds to 0.1 seconds) for complex queries.The change has to be done in ExpressionAnalyzer (Line 170)

@martint Any reasons for having an ImmutableMap in ExpressionaAnalyzer. For analyzing an expression having a single column(SymbolReference) it is taking around 2 seconds for the copy operation.

@geraint0923 I think it will increase the Query planning time further because we will again to a ImmutableMap copy in ExpressionAnalyzer

**Comment by Praveen2112** [comment]
@electrum 
[table_schema(1).zip](https://github.com/prestodb/presto/files/476100/table_schema.1.zip)

[query.txt](https://github.com/prestodb/presto/files/476101/query.txt)

**Comment by martint** [comment]
If the map is already an instance of ImmutableMap, copyOf is a no-op. The change we just merged should help, since it makes all those calls pass an ImmutableMap.

**Comment by Praveen2112** [comment]
@martint @geraint0923 #6128 solves the issue and can the same be implemented for PredicatePushDownOptimizer ?

**Comment by geraint0923** [comment]
@Praveen2112 I don't think we could apply the same optimization to `PredicatePushDown` since `symbolAllocator` in that optimizer is used to not only get the symbol-type map but also add some new symbol-type pairs (change the symbol-type map, and re-copy is needed).

**Comment by Praveen2112** [comment]
@geraint0923 "If the map is already an instance of ImmutableMap, copyOf is a no-op" apart from this is there is any reason for using ImmutableMap in Expression Analyzer. Why cant we just refer the HashMap created in SymbolAllocator instead of performing a deep copy? Anyway SymbolAllocator is not shared by multiple queries.
In case of complex queries , the number of entries in SymbolAllocator goes upto 15,000. It is a bit expensive operation to perform a deep copy each time.
