### ISSUE TITLE
Increase in time for TransformUncorrelatedInPredicateSubqueryToSemiJoin

### ISSUE THREAD

**Issue by Praveen2112** [prestodb/presto#6129]
Hi,
TransformUncorrelatedInPredicateSubqueryToSemiJoin optimizer looks for InPredicate expressions with sub-queries and optimizes it,  but why are we visiting project node in this optimizer. It acts as an over head increases the time taken for this optimizer even if the queries doesnt have a sub query. When we skip the visitProject method , the time taken for this optimizer reduces from 0.5 seconds to 0.07 seconds

**Comment by kokosing** [comment]
Project node is visited as it may contain IN predicate with a subquery as well as FilterNode or any other node containing expression. Anyway I think processing time could be easily optimized. Can you please share the test query where you noticed mentioned speed up?

I can take care of this next week, or if you want to you can post a PR for this.

**Comment by Praveen2112** [comment]
In the TransformUncorrelatedInPredicateSubqueryToSemiJoin optimizer the time taken could be reduced if we call **replaceInPredicateInAssignments** method only if there is IN predicate with sub-query in the project node.

**Comment by kokosing** [comment]
@Praveen2112 see https://github.com/prestodb/presto/pull/6164

**Comment by Praveen2112** [comment]
Thanks a lot @kokosing 
Same changes can also be applied to the filter node.(To rewrite filter only if there is inPredicate mapping)
