### ISSUE TITLE
Error while starting presto server : No factory for connector 

### ISSUE THREAD

**Issue by surendraGaddam99** [prestodb/presto#6134]
Hi,

I am getting No factory for connector exception .Need help to resolve this.
Where to configure connector factory for af360st1.

My presto server connection details for schema af360st1.

$ cat etc/catalog/af360st1.properties

connector.name=af360st1
connection-url=jdbc:oracle:thin:@xxxx.ams.com:1521:xxx
connection-user=af360st1
connection-password=xxxxx

2016-09-17T07:46:42.037-0700    ERROR   main    com.facebook.presto.server.PrestoServer No factory for connector af360st1
java.lang.IllegalArgumentException: No factory for connector af360st1
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:148) ~[guava-16.0.1.jar:na]
    at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:97) ~[presto-main-0.77.jar:0.77]
    at com.facebook.presto.metadata.CatalogManager.loadCatalog(CatalogManager.java:92) ~[presto-main-0.77.jar:0.77]
    at com.facebook.presto.metadata.CatalogManager.loadCatalogs(CatalogManager.java:52) ~[presto-main-0.77.jar:0.77]

Thanks
Surendra

**Comment by akshatnair** [comment]
What is this connector af360st1?

**Comment by electrum** [comment]
You probably want connector.name=oracle

The connector name is the name of the connector provided by the connector factory, not the catalog. You can have multiple catalogs using the same connector name.

**Comment by surendraGaddam99** [comment]
Thanks a lot .
I changed connector name to oracle . That resolved issue 'No factory for connector exception'.

$ cat etc/catalog/af360st1.properties
connector.name=oracle
connection-url=jdbc:oracle:thin:@xxxx.ams.com:1521:xxx
connection-user=af360st1
connection-password=xxxxx

$ cat etc/catalog/aa360st1.properties
connector.name=oracle
connection-url=jdbc:oracle:thin:@xxxx.ams.com:1521:xxx
connection-user=aa360st1
connection-password=xxxxx

$ cat etc/catalog/ah360st1.properties
connector.name=oracle
connection-url=jdbc:oracle:thin:@xxxx.ams.com:1521:xxx
connection-user=ah360st1
connection-password=xxxxx

Now i got connected to aa360st1,af360st1,ah360st1 at the same time in presto server.
How to restrict user to particular schema .

My Application  Dropdown contains values aa360st1,af360st1,ah360st1.
When user selects aa360st1 only tables in aa360st1 can be queried and accessed.

Thanks
Surendra

**Comment by electrum** [comment]
Are you using Presto to join to other data sources (like Hive)?

**Comment by surendraGaddam99** [comment]
I am using Presto to connect to Oracle DB having different schemas aa360st1 ,af360st1,ah360st1.

Thanks
Surendra

**Comment by electrum** [comment]
If you're only using Presto to connect to Oracle, just use Oracle directly. It will be much faster.

**Comment by surendraGaddam99** [comment]
I am using presto as it is a query engine .
My application is Airpal Query tool which uses presto DB query engine and has to be connected to Oracle .

Thanks
Surendra
