### ISSUE TITLE
Query stays queued when username has a '.'

### ISSUE THREAD

**Issue by nezihyigitbasi** [prestodb/presto#6137]
I configured the resource manager to create adhoc queues for each user and when a user has a name with `.` in it the resource manager throws an exception saying `Invalid resource group id`, but the query stays queued on the coordinator.

**Comment by nezihyigitbasi** [comment]
The issue is in `InternalResourceGroupManager::submit()` where the `selectGroup()` call is wrapped in a try-catch to catch only `PrestoException`s to fail the query. Either we can catch `Throwable` or change `ResourceGroupId` to throw a `PrestoException` on invalid resource group id (and create an error code for that). What do you think @cberner?

**Comment by cberner** [comment]
@nezihyigitbasi I think we may want to just find a way to allow "." in resource group ids, I'll take a look at the code to see how easy that is (I think it should be pretty easy, as that constraint was only there to make the config file format easier)
