### ISSUE TITLE
Cleanup CatalogSchemaTableName

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#6145]
- The serialization does not correctly handle identifiers in the name. The easiest fix is to remove the Jackson annotations, since the class doesn't need to be serialized.
- The class should also be `final`.
- The constructor arguments need null checks.

**Comment by paulrevere4** [comment]
@electrum Can I take this one?

**Comment by electrum** [comment]
Go for it!

**Comment by paulrevere4** [comment]
PR is out, #6439.

**Comment by martint** [comment]
Fixed
