### ISSUE TITLE
How to upstream lib changes done for presto-mysql

### ISSUE THREAD

**Issue by ArchaB** [prestodb/presto#6152]
While porting presto-mysql on ppc64le, The package failed with the error

**[ERROR] Caused by: java.util.MissingResourceException: Resource '5-5-9/Linux-ppc64le/mysqld' not found
[ERROR] at com.mysql.management.util.Streams.getResourceAsStream(Streams.java:124)**

As part of providing the support. Edited the **mysql-connector-mxj-db-files-5.0.12.jar** created when the package builds.
Changes done were to create a 'Linuz-ppc64le' folder in the jar and copy the ppc64le compatible mysql and mysqld file into it. 

What process do I need to follow to upstream the change so that ppc64le support is always provided ?

**Comment by nezihyigitbasi** [comment]
You can open a pull request to the presto project, please see [this](https://help.github.com/articles/creating-a-pull-request/) for more info.

**Comment by electrum** [comment]
This is part of MySQL MXJ: https://downloads.mysql.com/archives/c-mxj/

Unfortunately, it has been discontinued. I see two options here:

1. Fork MXJ as-is and release a new version with the additional binaries. It would need to be released under a different Maven groupId.
2. Move the MySQL binaries and logic for managing the server inside of https://github.com/airlift/testing-mysql-server in the same way as is done for https://github.com/airlift/testing-postgresql-server

**Comment by electrum** [comment]
Actually, there might be a simpler way. MXJ is split into two artifacts: `mysql-connector-mxj` and `mysql-connector-mxj-db-files`. We could add an additional artifact dependency to `testing-mysql-server` that contains the new binary. That would allow us to keep using the existing MXJ logic for managing the server. Alternatively, we could replace the `db-files` artifact with a new one that contains only the binaries we care about (and possibly update to a newer version of MySQL).

**Comment by ArchaB** [comment]
The pom.xml file does have the dependency mentioned
  <dependency>
    <groupId>io.airlift</groupId>
    <artifactId>testing-mysql-server</artifactId>
    <version>0.1</version>
  </dependency>

@electrum , could you please explain more on the line in your reply 
**'We could add an additional artifact dependency to testing-mysql-server that contains the new binary. '**
What would the dependency refer to ? Will it be a local file? or do I need to upstream the jar at a location from which any project would be able to clone it?

**Comment by ArchaB** [comment]
@electrum .. Gentle Reminder

**Comment by electrum** [comment]
It could either be another Maven dependency or it could be downloaded as part of the build. See here for an example of the latter, which downloads and repacks the PostgreSQL binaries:

https://github.com/airlift/testing-postgresql-server

**Comment by ArchaB** [comment]
Thanks
