### ISSUE TITLE
Decrease in time for Query Execution

### ISSUE THREAD

**Issue by Praveen2112** [prestodb/presto#6153]
Hi,
These are the Query time line for a query when it is executed
a. For the first time
query-execution-14  com.facebook.presto.event.query.QueryMonitor    TIMELINE: Query 20160921_104017_00051_wh28p :: Transaction:[477a7814-884a-46e9-af51-0304a98edde5] :: elapsed 6783ms :: planning 225ms :: scheduling 504ms :: running 0ms :: finishing 6558ms :: begin 2016-09-21T03:40:17.412-07:00 :: end 2016-09-21T03:40:24.195-07:00

b.Second time
query-execution-23  com.facebook.presto.event.query.QueryMonitor    TIMELINE: Query 20160921_105721_00058_wh28p :: Transaction:[741d82fa-2076-45b0-85dd-8049e3438e4f] :: elapsed 3029ms :: planning 213ms :: scheduling 48ms :: running 0ms :: finishing 2816ms :: begin 2016-09-21T03:57:21.692-07:00 :: end 2016-09-21T03:57:24.721-07:00

There is a reduction in the Scheduling time from 504 ms to 48 ms  which is because of the caching of the generated code.

Apart from Caching the compiled code are we caching any other things for a given query 

Thanks in Advance

**Comment by dain** [comment]
There is caching of metadata in the Hive connector, which can speed up scheduling time.  One important thing to consider is that, scheduling time is the time from planning completion until all splits have been scheduled, and this can be effected by lots of stuff like load from other queries. 
 
BTW, the more interesting part of these timelines is the change in finishing time.  My guess is you have warmed up the system and everything is running faster in the second case.

**Comment by Praveen2112** [comment]
Thanks Dain.
We are using a custom connector which gives the pages from memory ( data is already cached ) and server if not loaded when executed these query(One query running at a time). When the same query with a change in the filter condition(instead of colA > 10 we changed it to colA >20) is executed, there is similar decrease in finishing time , when it is ran for the second time.

When profiled,  we get a increase in time when the **filter** method (Generated code)is processing on the first page for each splits. Is there exists any part which are lazily evaluated in **filter** method ?
