### ISSUE TITLE
Presto and S3.

### ISSUE THREAD

**Issue by blondowski** [prestodb/presto#6162]
Not sure if this is an issue or working as intended.

I created a table in Hive that points to S3 bucket.
create table snowplow (blah, blah, blah) 
STORED AS PARQUET
LOCATION 's3://bucket/snowplow/';

I can query it in Hive:
hive> select count(*) from snowplow;
Query ID = hadoop_20160915185932_f360dd31-9d07-4332-8128-6147d573679b
Total jobs = 1
Launching Job 1 out of 1

Status: Running (Executing on YARN cluster with App id application_1473948339975_0013)

---

```
    VERTICES      MODE        STATUS  TOTAL  COMPLETED  RUNNING  PENDING  FAILED  KILLED  
```

---

Map 1 .......... container     SUCCEEDED     26         26        0        0       0       0  
## VERTICES: 02/02  [==========================>>] 100%  ELAPSED TIME: 201.66 s   

OK
25436768
Time taken: 205.838 seconds, Fetched: 1 row(s)

But when I go to Presto, it doesn't work:
presto-cli --catalog hive --schema default
presto:default> select count(*) from snowplow;
##  _col0 

```
 0 
```

(1 row)

Query 20160915_190407_00075_cvwb5, FINISHED, 1 node
Splits: 1 total, 1 done (100.00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

**Comment by rschlussel** [comment]
Is the hive connector configured to be able to access s3?

You should set the following in your hive.properties file:
hive.s3.aws-access-key=XXXX
hive.s3.aws-secret-key=XXXX
