### ISSUE TITLE
Update product-tests README for new Mac Docker

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#6170]
Docker is now natively supported on Mac, so the VirtualBox / Docker Toolbox instructions should be updated.

I think the steps are
- Install Docker for Mac: download the DMG, copy to Applications, run the Docker application to install.
- Increase Docker memory: click the Docker icon in the menu bar, choose Preferences, increase memory slider to 4 GB.

Everything after that seems to work automatically (no need to use `docker-machine` or `eval`).

**Comment by electrum** [comment]
Docker for Mac vs. Docker Toolbox: https://docs.docker.com/docker-for-mac/docker-toolbox/

**Comment by maciejgrzybek** [comment]
Closing because https://github.com/prestodb/presto/pull/6602 is merged.
