### ISSUE TITLE
Product tests fail if port 1080 is already used

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#6182]
When using Docker for Mac (not the older Docker Toolbox), product tests fail if port 1080 is used (which it always is for my SSH SOCKS proxy):

```
$ presto-product-tests/bin/run_on_docker.sh singlenode -g string_functions
...
Creating network "common_default" with the default driver
Creating common_hadoop-master_1

ERROR: for hadoop-master  Cannot start service hadoop-master: driver failed programming external connectivity on endpoint common_hadoop-master_1 (de2e876324560dff95b69e8cf4079aca9e9dab8d1e0f7db0039178e7a367b878): Error starting userland proxy: Bind for 0.0.0.0:1080 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
```

My random guess, knowing nothing about Docker, is that the old Docker setup used an isolated network for containers but the new way does bridging or uses the host network. 

If so, we should pick a different port for this, since using port 1080 is very common.

**Comment by kokosing** [comment]
@electrum I will try to take care of this, but I cannot promise you any ETA for this. Since I am using linux and typically I don't need a socks proxy, testing of this change will require more time for me.

**Comment by maciejgrzybek** [comment]
Fix: https://github.com/prestodb/presto/pull/6271

**Comment by kokosing** [comment]
Closing as fix is merged.
