### ISSUE TITLE
Distinct sum aggregation may produce incorrect results for empty grouping sets

### ISSUE THREAD

**Issue by pnowojski** [prestodb/presto#6191]
`AbstractTestQueries::testGroupingSetsWithMultipleDistinctAndUnion` fails for some configurations with `task_concurrency` higher then 1:

```
SELECT linenumber, COUNT(DISTINCT linenumber), SUM(DISTINCT suppkey) FROM (SELECT * FROM lineitem WHERE linenumber%2 = 0 UNION ALL SELECT * FROM lineitem WHERE linenumber%2 = 1) GROUP BY GROUPING SETS ((linenumber), ())
not equal
Actual 8 rows:
    [3, 1, 5050]
    [null, 7, 30300]
    [7, 1, 5050]
    [1, 1, 5050]
    [4, 1, 5050]
    [6, 1, 5050]
    [5, 1, 5050]
    [2, 1, 5050]
Expected 8 rows:
    [1, 1, 5050]
    [2, 1, 5050]
    [3, 1, 5050]
    [4, 1, 5050]
    [5, 1, 5050]
    [6, 1, 5050]
    [7, 1, 5050]
    [null, 7, 5050]
```

Simplified query:
```
> set session task_concurrency=8;
> SELECT a, SUM(DISTINCT b) FROM (SELECT * FROM (VALUES (0,1), (0,2)) t(a,b) UNION ALL SELECT * FROM (VALUES (1,1), (1,2)) t(a,b)) GROUP BY GROUPING SETS ((a), ());
  a   | _col1 
------+-------
    0 |     3 
 NULL |     6 
    1 |     3 
```

To reproduce this, number of workers must be greater then 1, task_concurrency must be greater then 1, query must contain an empty grouping set AND there must be union AND aggregation function must be sum distinct. It seems like multiple partial aggregations of empty grouping set are incorrectly combined in final aggregation, effectively multiplying  result.

CC @kokosing

**Comment by electrum** [comment]
@raghavsethi Is this part of what you are working on fixing?

**Comment by pnowojski** [comment]
Btw, I have noticed @raghavsethi commits in this area, but this bug is present both after and before recent changes in `GROUPING SETS` made by @raghavsethi . If someone is already working on a fix for that, it would be great, because I hardly know where to start looking for this bug :) If this is something new, I can try to fix it and any advice where to start would be welcome.

**Comment by raghavsethi** [comment]
Let me try to isolate the issue.

**Comment by raghavsethi** [comment]
@geraint0923 Could you also take a look? Might be related to your aggregation pushdown stuff or to the changes I made to that.

**Comment by raghavsethi** [comment]
@geraint0923 never mind, seems to be related to local parallel, not distributed exchanges.

**Comment by raghavsethi** [comment]
@pnowojski I'm curious how you got this test to fail? It's been broken ever since local parallel

**Comment by pnowojski** [comment]
@raghavsethi as a part of spill in aggregation and join work I have added new test which uncovered this bug.
