### ISSUE TITLE
Array element_at should return null if not found

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#6202]
The main point of having a separate function (aside from negative indexes) rather than `[]` is to allow accessing a position that may not exist. This makes it consistent with the map version of the function.

Zero is a special case that is never valid (in either direction), so we should keep the behavior of throwing an error for that. It avoids mistakes due to SQL arrays starting at one.

**Comment by paulrevere4** [comment]
Hey I'm looking to get more involved in this project. Can I take this issue?

We're talking about [ArrayElementAtFunction](https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/operator/scalar/ArrayElementAtFunction.java) right?

**Comment by martint** [comment]
@paulrevere4, yes, that's the one. Go for it!

**Comment by paulrevere4** [comment]
@martint Great thanks. I'll submit the PR when its ready.

**Comment by paulrevere4** [comment]
@martint Hi I'm looking to submit a PR for this but I want to run the full test suite, what's the best way to do that? mvn clean install test ?

**Comment by martint** [comment]
`mvn clean install` should be sufficient

**Comment by paulrevere4** [comment]
Great thanks

**Comment by paulrevere4** [comment]
PR to resolve this issue is at #6400

**Comment by nezihyigitbasi** [comment]
Fixed through #6400
