### ISSUE TITLE
effectivePredicate not printed nicely as part of HiveSplit.getInfo()

### ISSUE THREAD

**Issue by losipiuk** [prestodb/presto#6223]
The `effectivePredicate` part of `HiveSlit.getInfo()` is meaningless as `TupleDomain` does not provide
`toString()` method. Only `toString(ConnectorSession)` method.

We should either:
- create standard `toString()` in `TupleDomain`
- pass session arg to `getInfo`
- drop `effectivePredicate` from getInfo alltogether

**Comment by electrum** [comment]
@martint says to drop it since it will be the same for every split

**Comment by rongrong** [comment]
I'll give this one a shot.

**Comment by rongrong** [comment]
Working on it in #6481

**Comment by findepi** [comment]
Fixed by 8b8a34bdba
