### ISSUE TITLE
The percentage in query stats is not reliable

### ISSUE THREAD

**Issue by buremba** [prestodb/presto#6253]
We're using 0.151 and the percentage in query stats is not reliable since 0.146. The percentage usually goes up to > 70% quite fast and it suddenly goes down from ~90% to ~75% a few times for most of the queries. What can cause this problem?

**Comment by martint** [comment]
In the web UI? If so, that's a known issue. There's a pending PR to fix it.

**Comment by buremba** [comment]
@martint we're using presto-client so if it's an issue related with the UI, it's probably not related with this one. Could you please share the PR, I couldn't find it?

**Comment by martint** [comment]
This is the PR that includes the fix for the web UI: https://github.com/prestodb/presto/pull/6238.

The percentage is computed from the number of processed splits vs total splits. The issue is that the total number of splits may not be known until long after the query execution starts, since they are discovered as the query runs.

Once all splits have been enumerated, the server indicates to the client that the total number is not going to change further, at which point the client can show a % progress.

**Comment by buremba** [comment]
@martint In this case, the issue is the total splits usually increase when the percentage is around 90%. Is this possible?

**Comment by martint** [comment]
When you say presto-client, do you mean the CLI? In that case, it shouldn't be possible. The CLI only displays a percentage when the server indicates that it's discovered all splits. If it's not behaving that way, it's a bug.

**Comment by buremba** [comment]
Nope, It's the StatementClient from presto-jdbc package: https://github.com/rakam-io/rakam/blob/master/rakam-presto/src/main/java/org/rakam/presto/analysis/PrestoQueryExecution.java#L165

We're still using 0.151 but planning to switch to 0.153. If nothing is changed about query execution between these releases, I can debug the issue. Otherwise I can get back to you if the issue still occurs in 0.153.

BTW the issue usually occurs when there are >150 splits .

**Comment by martint** [comment]
Oh, that code is wrong. You need to check whether `stats.isScheduled()` is true before you can compute the percentage. That will signal when all splits have been discovered, and it guarantees totalSplits won't change anymore.

Take a look at: https://github.com/prestodb/presto/blob/master/presto-cli/src/main/java/com/facebook/presto/cli/StatusPrinter.java#L288

**Comment by buremba** [comment]
Oppss, sorry for the confusion. At the time when we wrote this code, JDBC adapter didn't have progress support. We will switch to it, thanks @martint !
