### ISSUE TITLE
JOINs with one side from VALUES should use broadcast instead of partitioning

### ISSUE THREAD

**Issue by erichwang** [prestodb/presto#6257]
JOINs generally do a hash partitioning on the join keys. However, in the event that one side of the join is known to be from a VALUES statement, than we should use a broadcast instead of a hash partitioning (since it is almost certainly going to be low cardinality).

**Comment by erichwang** [comment]
Another way to do this is to leverage a stats system to report the cardinality (which is known for a VALUES node) and have the planner make decisions based on that.

**Comment by KBP-TDC** [comment]
@losipiuk @rschlussel FYI, this seems related to some work we started already.

**Comment by losipiuk** [comment]
@KBP-TDC it should work automatically based on cardinality output from StatsCalculator as soon as @rschlussel finishes her patch

**Comment by rschlussel** [comment]
Yup I'm working on automatically choosing between distributed and broadcast joins depending on whether the table on the right is sufficiently small.
