### ISSUE TITLE
Make reads from Spillers asynchronous

### ISSUE THREAD

**Issue by pnowojski** [prestodb/presto#6258]
Currently `Spiller` has a following interface:

```
public interface Spiller
        extends Closeable
{
    /**
     * Initiate spilling of pages stream. Returns completed future once spilling has finished.
     */
    CompletableFuture<?> spill(Iterator<Page> pageIterator);

    /**
     * Returns list of previously spilled Pages streams.
     */
    List<Iterator<Page>> getSpills();
}
```

This make reads from spillers synchronous, which can block operators. This should be fixed. The biggest obstacle is in how to use asynchronous reading method in `MergeSorter`.

**Comment by dain** [comment]
Aren't you going to need some sort of id so you can fetch back a specific stream?   Also, what if you need to spill multiple times?  I think you want something like this:
```java
public interface Spiller
        extends Closeable
{
    /**
     * Initiate spilling of pages stream. Returns completed future once spilling has finished.
     */
    CompletableFuture<SpillHandle> spill(Iterator<Page> pageIterator);

    /**
     * Returns list of previously spilled Pages streams.
     */
    Iterator<Page> getSpill(SpillHandle);
}
```

**Comment by pnowojski** [comment]
@dain please check how it's used in this PR:

**Comment by pnowojski** [comment]
@cberner we have a feeling that this has smaller priority compared to for example those things: https://github.com/prestodb/presto/pull/6726 https://github.com/prestodb/presto/pull/6273 . It doesn't mean that we don't want to do it, but just we would like to focus on more urgent things :) Those pages are being read synchronously but one by one. It won't block drivers for long time.

To support this claim, here are benchmark results of current implementation (spilling to single disk) and JBOD (implemented in #6726 )
https://docs.google.com/spreadsheets/d/e/2PACX-1vQwlyDzqxcGCmZ70-9IyS76Rhb18nDp-f-ss0UiYcbdSS9EymNTe1x506mubj891on8kRRGAEySVI3W/pubchart?oid=1708510955&format=image

during those benchmarks, disks were heavily utilized with sequential writes/reads AND cpu on the cluster was stable ~100%. Problem with missing asynchronous reads should be visible as either random reads or low cpu usage.

**Comment by cberner** [comment]
Putting off the async refactoring seems ok, but we need to change the interface to avoid reading back all the spills at the same time. Right now is needs to open an unbounded number of files, which just isn't going to work when going to remote storage (how we will implement the spiller interface)

**Comment by pnowojski** [comment]
Avoiding reading back all spill at same time is not only "interface" change. It would require reimplementing merging algorithm, that would also significantly slow down merging. Merging would have to be done in stages, like first merge/aggregate first 1/10'th of the spilled files and write result back to disk. Next second 2/10'th, etc, and at the end read, merge and aggregate 10 pre-merged files. This is do-able but it doubles IO operations and add complexity. 

I don't know, maybe it could be implemented differently by partitioning data during spilling, but this seems to have other issues.

With revocable memory, spills will be much much bigger and this would reduce number of opened files. 

What is your concern with high number of opened files on remote storage? Lack of read ahead/page cache? If that's the issue, it might be easier to implement/solve that on our side manually.

**Comment by cberner** [comment]
Yes, and it's a change that was put off so that the first implementation could be merged early. 1/nth at a time is the standard way of performing a merge sort, as far as I know.

The problem with a large number of files is read buffers. We need megabytes or tens of megabytes per file. 

More generally, my concern is that the current approach fundamentally can't scale because of the requirement that all spills be opened at the same time.
