### ISSUE TITLE
Power support libraries for presto-hive.

### ISSUE THREAD

**Issue by ArchaB** [prestodb/presto#6263]
While trying to port Presto on ppc64le system, Presto-Hive failed with the following error. 

```
[ERROR] Caused by: java.lang.RuntimeException: failed to load Hadoop native library
[ERROR] at com.facebook.presto.hadoop.HadoopNative.requireHadoopNative(HadoopNative.java:58)
[ERROR] at com.facebook.presto.hive.HdfsEnvironment.<clinit>(HdfsEnvironment.java:33)
[ERROR] ... 76 more
[ERROR] Caused by: java.lang.RuntimeException: library not found: /nativelib/Linux-ppc64le/libhadoop.so
[ERROR] at com.facebook.presto.hadoop.HadoopNative.loadLibrary(HadoopNative.java:88)
[ERROR] at com.facebook.presto.hadoop.HadoopNative.requireHadoopNative(HadoopNative.java:47)
[ERROR] ... 77 more
[ERROR] -> [Help 1]
```

The hadoop-cdh4-0.9.jar used by presto-hive does not have power compatible library files. 
Latest stable version of hadoop (2.7.1-power) has the power support. 
Is it possible to update the jar used internally by presto to include the power compatible library files.

**Comment by electrum** [comment]
Is there a public CI service like Travis CI that runs ppc64le?

**Comment by ArchaB** [comment]
@electrum, There is no public CI at present to run ppc64le. We have an internal CI setup where we currently run builds and can share the results if needed.

**Comment by gerrith3** [comment]
We are working to build a public CI in a couple of locations for ppc64le but they are not yet in place.  In the interim we can freely share results from our internal builds.  It is also possible to get access to ppc64le VMs from Oregon State University's OSL http://osuosl.org/services/powerdev or from UNICAMP: http://openpower.ic.unicamp.br/minicloud/ .
