### ISSUE TITLE
Track memory used for buffers during reading spills in BinaryFileSpiller

### ISSUE THREAD

**Issue by pnowojski** [prestodb/presto#6272]
`BinaryFileSpiller::getSpills` uses internally `BufferedInputStream` and doesn't track how much memory is allocated for those buffers. This can potentially cause out of memory issues.

**Comment by pnowojski** [comment]
@cberner `BufferedInputStream` and `BufferedOutputStream` are using by default 8KB for internal buffers. Is this really an issue? It would take 128 spills per one operator to use 1MB. With 32MB `operator_memory_limit` it means that for handling `32MB * 128 = 4GB` of data per operator, we would consume only 1MB of untracked memory per operator. 

With revocable memory average spill sizes will go up to values in hundreds of MB, which will further decrease significance of this "leak" (the bigger individual spills, the smaller number of spills, thus the smaller number of simultaneously opened files).

**Comment by cberner** [comment]
Yes, that seems like a real issue to me. Suppose you spill 1TB instead of 4GB. It'll be hundreds of MB then. Pretty much anything that's not bounded and small needs to be tracked. For example, in the aggregations we even account for the overhead of object headers

**Comment by losipiuk** [comment]
Implemented in https://github.com/prestodb/presto/pull/6726/commits/cf4fe4938735323c4cd2b595dbacaff32bc0d244
