### ISSUE TITLE
Presto docker containers on a cluster can't communicate

### ISSUE THREAD

**Issue by harrison-svds** [prestodb/presto#6275]
I have installed Presto on Docker containers on three nodes of an existing Hadoop cluster (1 coordinator, 2 workers).  Calling the discovery server API `/v1/service` method indicates that the workers have successfully registered with the discovery server, but when I run the Presto CLI and run `select * from system.runtime.nodes` I only see the coordinator listed.  I suspect it is because the worker containers have registered the Docker container IP with the discovery server, as opposed to the host server and port, and the coordinator cannot communicate with docker containers on other machines.  Is there any way to tell the workers to advertise a different host to the discovery server?  Or am I misunderstanding my problem?

**Comment by electrum** [comment]
You can set "node.ip" in your node.properties file to override the detected IP address.

**Comment by harrison-svds** [comment]
This worked!  Thank you!
