### ISSUE TITLE
if a query's session.source is null, query-list does not render

### ISSUE THREAD

**Issue by tarekrached** [prestodb/presto#6287]
rendering a [query's session.source](https://github.com/prestodb/presto/blob/master/presto-main/src/main/resources/webapp/assets/query-list.js#L172) errors out if the source is `null`, because [truncateString blindly calls inputString.length](https://github.com/prestodb/presto/blob/master/presto-main/src/main/resources/webapp/assets/utils.js#L120) without checking if it's a string

**Comment by electrum** [comment]
Thanks for the report. Is this fixed by #6238?

**Comment by tarekrached** [comment]
yeah, that fixes it, but I think this reference to [query.session.source.toLowerCase()](https://github.com/raghavsethi/presto/blob/f2148acbfc45f2174c8d95424a39c48ff77d3e75/presto-main/src/main/resources/webapp/assets/query-list.js#L263) will cause an error for the same reason

**Comment by tarekrached** [comment]
looks like that [has been resolved, too](https://github.com/raghavsethi/presto/blob/657aecf4428491f80ac903d81115979dfcfdcf75/presto-main/src/main/resources/webapp/assets/query-list.js#L271)!

thanks @raghavsethi, nice work!

**Comment by raghavsethi** [comment]
Haha no problem. Closing this task.
