### ISSUE TITLE
Support table functions

### ISSUE THREAD

**Issue by kokosing** [prestodb/presto#6288]
I want to add a support for user defined table functions. But first I would love to hear if such a feature would be useful and it is needed.

My raw plan is to:
- add a concept of table function
- implement Unnest as table function
- change UnnestNode to be something like TableFunctionNode but with a unnest function method
- expose table function UDF interface (UDTF)

I could image UDTF interface as something like below:

```
public interface TableFunction
{
    enum Distibution
    {
        GATHER, // all the input/output rows will be handled by single node
        BROADCAST, // all the input/output rows will be handled by all the nodes
        SCATTER // all the input/output rows will be scattered among the nodes
    }

    /** 
     * @returns the list of output types if function is capable to handle given input types
     */
    Optional<List<SqlType>> isCapable(List<SqlType> inputTypes);

    default Distibution getDistribution()
    {
        return Distibution.SCATTER;
    }

    // one of below method has to be implemented
    default RecordSet createRecordSet(RecordSink recordSink)
    {
        throw new UnsupportedOperationException();
    }

    default ConnectorPageSource createPageSource(ConnectorPageSink pageSink)
    {
        throw new UnsupportedOperationException();
    }
}
```

There could be plenty of potential usage of this. The most obvious is to leverage the machine learning and statistical tools with presto like R.

```
SELECT * from rtable(lineitem, 'some R code');
```

My plan is to work on this in my slack time. Depending on feedback I got I think I could try prioritize it higher to work on it in regular basis.

@martint

**Comment by martint** [comment]
Here are the relevant parts from the spec:

```
<table function derived table> ::=
  TABLE <left paren> <collection value expression> <right paren>

<collection value expression> ::=
    <array value expression>
  | <multiset value expression>
```

> 6) If `TP` simply contains a `<table function derived table>` `TFDT`, then:
>    a) The <collection value expression> immediately contained in `TFDT` shall be a `<routine invocation>`.
>    b) Let `CN` be the `<correlation name>` simply contained in `TP`.
>    c) Let `CVE` be the `<collection value expression>` simply contained in `TP`.
>    d) Case:
>        i) If TP specifies a `<derived column list>` `DCL`, then let `TFDCL` be 
>            `( DCL )`
>        ii) Otherwise, let `TFDCL` be a zero-length string.
>    e) TP is equivalent to the `<table primary>`
>        `UNNEST ( CVE ) AS CN TFDCL`

**Comment by kokosing** [comment]
I posted a PR that add support for scalar table functions. Scalar here means that for every single input row, table functions can return multiple rows. It leverages the `UNNEST` code. The main difference between `UNNEST` and `TABLE` is for input type `ARRAY<ROW<BIGINT, VARCHAR>>`, `UNNEST` will return a relation with single column `<ROW<BIGINT, VARCHAR>` while `TABLE` will return two columns `BIGINT, VARCHAR`.

See: https://github.com/prestodb/presto/pull/6424

> There are some parallels between these kinds of functions and regular tables. In fact, one could think of a table reference as a magic table function that produces the collection of rows in a table. It is very possible that all the work we're doing to describe physical properties of tables (partitioning, sorting, etc.) is applicable to table functions, so it'd be worth thinking about whether it's possible to converge to a common way of modeling both.

Maybe I misread your idea, but to me it sounds like a re-inventing the concept of connector. I am not sure if it is good idea.

When I was posting this issue I was thinking about distributed function which consumes all the relation and returns the relation, where output rows could be disconnected with input rows. I thought it would be useful for analytic algorithms which could not be simple represent in SQL, for example k-means.

```
select * from t, TABLE(kmeans(3, t.x, ty)) c;
```
could output
```
t.x  | t.y  | c.x  | c.y
1    | 1    | null | null
1    | -1   | null | null
-1   | 1    | null | null
-1   | -1   | null | null
11   | 11   | null | null
11   | 9    | null | null
9    | 11   | null | null
9    | 9    | null | null
null | null | 0    | 0
null | null | 10   | 10
````

But the more I think about it the less confident I become about how it could be achieved.


> Also, we should consider how to bridge all existing functions that return arrays to work in a table context -- possibly by modeling as "single stream" table functions.

I am not sure if its a good idea. To me its sounds like magic keyword, put whatever you like and we will return a relation for you. I prefer more strict form of contract that allows only a collection of `ROW`s as input for `TABLE`. Does `ANSI SQL` allow to pass ARRAY<BIGINT> as argument for table function?

**Comment by garyelephant** [comment]
Hi，any update of this ？engines like spark and flink have already support this feature
