### ISSUE TITLE
O(N^2) behavior when grouping by double column containing NaNs

### ISSUE THREAD

**Issue by martint** [prestodb/presto#6295]
NaNs are not equal to any other value (even to NaN). This causes insertions into the hash table of a group by or join to become O(N) for NaN values.

Once https://github.com/prestodb/presto/issues/1508 is implemented, this should no longer be a problem. In the meantime, we should consider failing queries that GROUP BY or JOIN on NaNs.

**Comment by paulrevere4** [comment]
@martint Can I give this one a shot?

**Comment by martint** [comment]
This should be fixed by https://github.com/prestodb/presto/pull/10392
