### ISSUE TITLE
UI shows NaN when loading

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#6296]
I reproduced by connecting to one of our clusters with HTTPS, where the HTML page can load but all the resources throw 401.

<img width="1197" alt="screen shot 2016-10-07 at 12 46 34 pm" src="https://cloud.githubusercontent.com/assets/9230/19203466/2c7ec930-8c8c-11e6-8f1a-ceaea0aa8cfc.png">

**Comment by smitaminakshi** [comment]
Hello, 
Is there any update on this?

Regards,
Smita
