### ISSUE TITLE
Remove deprecated Parquet config flags

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#6299]
There are two properties marked as deprecated:
- `hive.parquet-predicate-pushdown.enabled`
- `hive.parquet-optimized-reader.enabled`

I assume they are intended to be removed once the features are deemed stable. We should make them default to true, then remove later, or perhaps just remove immediately.

**Comment by nezihyigitbasi** [comment]
We have been using the new reader for quite some time in production and I think it's in good shape (except for an issue I recently fixed: #6290). When we remove these properties, do we also want to remove [these](https://github.com/prestodb/presto/blob/master/presto-hive/src/main/java/com/facebook/presto/hive/HiveSessionProperties.java#L72-L81) session properties? And if we remove both the session and config properties, then this means we no longer need the old reader, but I am not really sure whether we are there yet. I wonder what other Parquet users think. @zhenxiao @billonahill

**Comment by zhenxiao** [comment]
@electrum @nezihyigitbasi  sure. Let me work on it.  
How about we defaults the config to be true, and remove the configs and session properties? We just started using the new Parquet reader, everything is going fine. I think we still need the old reader, as complex data types are only supported in old reader. I am working on supporting Map, Struct, and Arrays in the new Reader, and will submit a pull request soon.
@electrum @nezihyigitbasi @dain what do you think?

**Comment by electrum** [comment]
@zhenxiao Thanks for the explanation. How are complex types handled if the optimized reader is enabled? Does it automatically fallback to the old reader, or do queries fail?

**Comment by zhenxiao** [comment]
@electrum if the optimized reader is enabled, for complex types, it will automatically fallback to the old reader. When enabling the optimized reader, only primitive types are handled by optimized reader. The fallback is automatic.

**Comment by zsaltys** [comment]
@electrum @zhenxiao what's the state of this? Were complex types implemented on the new reader? Is it now possible to make these options default?

**Comment by nezihyigitbasi** [comment]
The new reader has complex type support, but there are issues that have to be addressed by #9156 and #9110 before we can make the new reader the default reader.
