### ISSUE TITLE
Optimize window function followed by ORDER BY

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#6302]
The following query is slower than necessary because the SortNode is redundant with the preceding WindowNode:

``` sql
SELECT *, row_number() OVER (ORDER BY key) FROM src ORDER BY key;
```

It should have the same execution plan as this (because the WindowNode already sorted the output):

``` sql
SELECT *, row_number() OVER (ORDER BY key) FROM src;
```

**Comment by martint** [comment]
Rather than optimizing that specific case, it should be done for any scenario where the input to a sort node is already sorted.

Also, this is probably not a good beginner task, since it requires understanding how physical properties work, etc.
