### ISSUE TITLE
Make Accumulo classes immutable

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#6321]
The following classes are mutable, but it should be easy to make immutable given that the setters are not used:

* `AccumuloColumnConstraint`
* `AccumuloSplit`
* `TabletSplitMetadata`

**Comment by adamjshook** [comment]
@electrum I've fixed `AccumuloColumnConstraint` and `TabletSplitMetadata`, however `AccumuloSplit` is giving me a little trouble.

Making the `List<WrappedRange> ranges` `final` and removing the setter causes failures in `TestAccumuloSplit`, saying `Can not construct instance of AccumuloSplit, problem: ranges is null`.  I had ran into this a while back, where jackson seems to be first setting `ranges` to null via the constructor, deserializes the list of `WrappedRanges`, and then calls the setter.  I was hoping the annotations on `WrappedRange's` `toBytes` and `fromBytes` would be enough to have it deserialize correctly, but it doesn't seem to be the case.  Any ideas on how to work through this?  

You can view the work for this ticket at [this branch](https://github.com/bloomberg/presto/tree/presto-6321) and the commit which causes `ranges` to be `null` in the `AccumuloSplit` [here](https://github.com/bloomberg/presto/commit/e26ed5209b1835c56de930fc07a424b68c21e6b8).

**Comment by electrum** [comment]
I found the problem. You need to change `getWrappedRanges()` to have `@JsonProperty("ranges")`, since the default name is based on the method name. It worked before since `setWrappedRanges()` had a `@JsonSetter` without an explicit name, so the property was actually serialized as `wrappedRanges` in the JSON.

**Comment by adamjshook** [comment]
That did the trick -- thank you!
