### ISSUE TITLE
CPU usage is more for queries running in PrestoDB

### ISSUE THREAD

**Issue by surendraGaddam99** [prestodb/presto#6336]
Hi ,

I am using PrestoDB Query Engine for running sql queries.
CPU Usage is observed as 70 to 80 % for each query run.
My application will be accessed by many tenants at the same time .
So how to reduce the CPU /memory usage for queries run in presto db .
Any configurations needs to be adjusted.

Thanks
Surendra

**Comment by electrum** [comment]
This is expected and is a good thing! Presto will try to use all available CPU to run your query as quickly as possible.

If you have questions about specific queries, please post in the user group: https://groups.google.com/group/presto-users

Include details such as the query SQL, table schema, table sizes, which connector, which Hive file format (if applicable), number of machines in the cluster, hardware configuration, network configuration (1 gigabit or 10 gigabit, type of switches and topology), etc.

**Comment by electrum** [comment]
We usually get the opposite question: my query isn't using enough CPU, how do I use more CPU to make it run faster (and fully utilize the hardware)

**Comment by surendraGaddam99** [comment]
Hi electrum,

In my case our portal page contains around 10 applications and Airpal with prestodb connected is one of them. If my Airpal application running on presto db uses around 70 to 80 % of CPU then other applications get slow down  and run out of memory/performance impact.
Multiple tenants will be accessing our portal page We are using oracle connector.

Thanks
Surendra
