### ISSUE TITLE
JDBC drivers: SQuirrel takes very long to connect to Presto

### ISSUE THREAD

**Issue by shubhamtagra** [prestodb/presto#6363]
For big hive databases (~4k tables in our case) it takes very long for SQuirrel to connect to Presto server. Root cause for it is that PrestoDatabaseMetaData.getColumns handling is inefficient for hive databases with lots of tables. 

For hive connector, this call invokes HiveMetadata.listTableColumns which gets the table info one by one
from metastore. And for each table info it creates a new thrift client which means a new connection, which is very costly.

Faster way is to use `get_table_objects_by_name` thrift call to get the table infos in bulk. Using this call brought down the connection time from more than half an hour to under two minutes for us.

I will open a PR to use this call instead.

**Comment by electrum** [comment]
Note that 4k is relatively small. This will need to do batching so that it works when there are 100k+ tables.

**Comment by stagraqubole** [comment]
Noted, will add batching.

**Comment by Downchuck** [comment]
Has a PR been submitted for this? I also noticed how slow Squirrel is for a complex data lake.

**Comment by tooptoop4** [comment]
Looks like same issue I face in https://github.com/prestodb/presto/issues/11442 with 3000 hive tables

**Comment by stagraqubole** [comment]
@tooptoop4 here is the PR: https://github.com/prestodb/presto/pull/11614/files

I also noticed that for issue in #11442  if Squirrel would have passed down the schema named into the query then the query would finish very fast even without these changes.

**Comment by dain** [comment]
Is SQuirreL SQL is aware that this is an issue for large databases like Presto that serve large warehouses?  If not, maybe file a issue with them?

**Comment by JustEdro** [comment]
Hi @stagraqubole, seems your PR #11614 was ignored, can you update it?
