### ISSUE TITLE
Use hard links in RPM to save space

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#6380]
The RPM is almost 600MB. We could save space by using hard links for the duplicated files. This would also save space on the user's disk (assuming RPM preserves these when unpacking).

**Comment by cawallin** [comment]
Can you elaborate a little, is this to save space when building? The RPM is about the same size as the server tarball, which is expected.

**Comment by electrum** [comment]
This is to make the RPM itself smaller and save space on local disk, Maven repos, etc. The tarball should also use hard links, but that's a separate project.

**Comment by electrum** [comment]
I did a bit of searching, and it turns out that even though an RPM (cpio) can include hard links, they might be stored as full copies. If so, this isn't useful, other than saving space after the RPM is unpacked.

The first step here is to try creating an RPM using the normal RPM tools and make sure it only stores the copy once (make sure the duplicate files are large enough not to be within the gzip window and are interleaved with other non duplicates).
