### ISSUE TITLE
how to query jsonb columns using presto

### ISSUE THREAD

**Issue by mkaja** [prestodb/presto#6382]
how to query jsonb columns using presto

**Comment by electrum** [comment]
Are you referring to the PostgreSQL connector?

**Comment by mkaja** [comment]
yes

**Comment by mkaja** [comment]
any update ?  json_extract_scalar

**Comment by rschlussel** [comment]
https://github.com/prestodb/presto/pull/7506 is a first step.  This issue is related to https://github.com/prestodb/presto/issues/6614.  Please avoid opening multiple issues for the same topic.
