### ISSUE TITLE
Add dependency injection support for custom functions

### ISSUE THREAD

**Issue by buremba** [prestodb/presto#6390]
Following up the discussion in Google Groups ([link](https://groups.google.com/forum/#!topic/presto-users/y_nsBCTP1GU)), it would be nice if Presto could construct custom functions with Guice in order to allow them to be able to use external variables such as `TypeManager` and `BlockEncodingSerde`.

**Comment by electrum** [comment]
I just looked at the code and found that all of the aggregation function methods are assumed to be static. Maybe it would be better to pass these as arguments to the methods?

I think we'll need to convert some functions like `array_agg` to the annotation framework to see exactly what is required and decide on how it should work.

**Comment by buremba** [comment]
I'm copying the post that I wrote in Google Groups:

> I think the main problem is the methods are static so Presto needs to support object methods in custom functions in order to be able to support this use-case. I'm not sure about the overhead of invoking object method versus static methods but theoretically, it's just an extra parameter.

Since the new annotation framework only allows empty constructors, we will need to use a nasty workaround for the value of `legacyArrayAgg` in `ArrayAggregationFunction` in order to convert `array_agg` to the new annotation framework.

**Comment by cberner** [comment]
Could you describe in more detail why you need access to the `TypeManager` and `BlockEncodingSerde`? Most functions don't need a `TypeManager` and can instead use the `TypeParameter` annotation

**Comment by buremba** [comment]
We have a custom type called `set<E>`, the implementation is similar to `GroupByHash`. We handle specific types such as `set<bigint>` similar to what you did with `BigintGroupByHash` for performance reasons but in order to be able to support all comparable types we use a similar algorithm to `MultiChannelGroupByHash`. We store a BlockBuilder for storing unique values similar to  `currentPageBuilder` inside `MultiChannelGroupByHash`.

Since we use `Slice` as the native type of the `set<E>`, we need to be able to serialize Block instances to Slice and vice versa.

AFAIK, the only way to do that is to use `TypeSerde` and `BlockEncodingSerde`. Here is the code block that we use:

```
public BlockRHashSet(BlockEncodingSerde serde, TypeManager typeManager, Slice slice)
    {
        BasicSliceInput input = slice.getInput();
        nextGroupId = input.readInt();

        this.type = TypeSerde.readType(typeManager, input);

        if (nextGroupId > 0) {
            Block blockBuilder = serde.readBlockEncoding(input).readBlock(input);
            currentBlockBuilder = type.createBlockBuilder(new BlockBuilderStatus(), blockBuilder.getPositionCount());
            for (int i = 0; i < blockBuilder.getPositionCount(); i++) {
                blockBuilder.writePositionTo(i, currentBlockBuilder);
                currentBlockBuilder.closeEntry();
            }
        }
        else {
            currentBlockBuilder = type.createBlockBuilder(new BlockBuilderStatus(), 100);
        }

        maxFill = input.readInt();
        mask = input.readInt();

        groupAddressByHash = new long[input.readInt()];
        for (int i = 0; i < groupAddressByHash.length; i++) {
            groupAddressByHash[i] = input.readLong();
        }
    }
```

Sorry for not publishing the full source code. We're planning to release it when it's stable. You may think that the serialization is expensive and should be avoided but since the `groupIds` never become too many, it works fine for us. We usually store the user id sets for each day.

 If we can't use those variables inside the custom functions, we will have to drop support for `set<E>` and instead support most common type variables such as `set<bigint>` and `set<integer>`.

**Comment by cberner** [comment]
I see. Why did you chose `Slice` as the native container type, rather than `Block`?

**Comment by buremba** [comment]
I actually tried to use `Block` since it seems to be a good candidate but run into an issue that I don't remember. Maybe I should try it again, I feel like I should write more code comments. :)

**Comment by cberner** [comment]
Ya, try out `Block`. It's not a perfect fit for a set, but it seems like a better fit than `Slice` and should allow you to avoid the issues with serialization and deserialization
