### ISSUE TITLE
Use RE2J for LIKE expression

### ISSUE THREAD

**Issue by haozhun** [prestodb/presto#6392]
Currently, we use Joni.

**Comment by electrum** [comment]
Some expressions such as `LIKE '%%%%%x%` can use exponential time.

**Comment by haozhun** [comment]
@dain expressed opinions against doing this without understanding why RE2 is slower for some LIKE patterns. I'm going to first do some pre-processing of LIKE patterns, and see if there are patterns that are still significantly slower.
