### ISSUE TITLE
Running  presto sql script from cli - not able to see time taken by the query.

### ISSUE THREAD

**Issue by KishorBaindoor** [prestodb/presto#6397]
Hi ,

I am using below command to run sql query. I am able to get the result of the query. But I am not able to find the time taken by query with this way. In case hive by using 2> ,  we can get details of query execution.

 ./presto-cli-0.152-executable.jar --server serverIp:port  --catalog hive --schema databaseName -f  ~/Scripts/Presto/q1.hql

**Comment by electrum** [comment]
We should add an option to show the stats for non-interactive queries. For basic timing, you can use the UNIX "time" command: https://linux.die.net/man/1/time

**Comment by nianglao** [comment]
Agree with you to show time cost when running SQLs in command line. Also better to show stats below for statistic purpose. 


 "Query 20180208_034908_03080_uysbu, FINISHED, 1 node
Splits: 18 total, 18 done (100.00%)
0:01 [8.1K rows, 41.7KB] [12.2K rows/s, 62.7KB/s]"
