### ISSUE TITLE
when join tables presto does not automate trim

### ISSUE THREAD

**Issue by yushantao** [prestodb/presto#6405]
Today i download the latest version 0.154 and i found some tasks(when JOIN tables action) did not work correctly, So i found that earlier version of presto did auto trim space,This version does not automate,Hope fix this&&best wishes~
![qq20161025-04](https://cloud.githubusercontent.com/assets/9460491/19675439/dcf7f768-9ac0-11e6-8e8e-d9ca95dbc824.jpg)

**Comment by martint** [comment]
Can you elaborate on what we should be looking for in those images? Where did you expect spaces to be auto-trimmed?
