### ISSUE TITLE
CLI hangs when initial output is short

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#6416]
This query is a good reproduction (change the values based on cluster size):

``` sql
select (select sum(totalprice) from tpch.sf200.orders) union all (select sum(totalprice) from tpch.sf1000.orders);
```

Sequence:
1. CLI shows progress for a few seconds while both subqueries run.
2. First subquery finishes and produces an output row. The second subquery keeps running.
3. CLI clears the progress display, executes the pager process and starts writing output to the pager.
4. The buffer in `OutputHandler` waits 3 seconds for more rows before any output is written.
5. The header and first row should be output. However, nothing is displayed, and attempts interact with less (including ctrl-C) do not work.

An easy way to see what is happening is to set `PRESTO_PAGER=cat` before running the CLI.

**Comment by AlekseiS** [comment]
I cannot reproduce it on local machine with "master" branch. For me after 3 sec delay I see column header and the first row. The query I used locally is:
```
select (select sum(totalprice) from tpch.sf10.orders) union all (select sum(totalprice) from tpch.sf30.orders);
```
Are there additional conditions to reproduce it?
