### ISSUE TITLE
Fix merging big pages in aggregation spilling

### ISSUE THREAD

**Issue by pnowojski** [prestodb/presto#6432]
Currently `MergeHashSort` guarantees that:

>  Positions with same hash value are guaranteed to be in the same result page.

If each row is huge (like containing `max(VARCHAR)` aggregator for large column), this can produce large output Pages, for which memory is not accounted anywhere. This memory should either be accounted or `MergingHashAggregationBuilder` should handle rows with same key that are split in consecutive pages.

Further more. `MergeHashSort` holds in memory one Page per spilled file. This memory also should be accounted.

cc @cberner

**Comment by ilfrin** [comment]
should be handled by https://github.com/prestodb/presto/pull/6726/commits/0d9a875172f62084acbb6032cda328a1c7e377f0 part of https://github.com/prestodb/presto/pull/6726

**Comment by findepi** [comment]
@ilfrin is this issue to be closed then?
