### ISSUE TITLE
Support parametrized types in aggregation framework

### ISSUE THREAD

**Issue by buremba** [prestodb/presto#6464]
The new annotation based aggregation framework doesn't seem to support parametrized types. For example the aggregation framework expects AccumulatorStateSerializer to has a zero argument constructor but the accumulator usually needs to know the parameter type in order to be able to serialize it.

Also when I the following query causes Presto to throw NPE: `select array_agg_test(1)` because it tries to cast array(T) to array(T) and cannot find a way to do it.

```
@AggregationFunction("array_agg_test")
public class TestArrayAggregationFunction
{
    @TypeParameter("T")
    @InputFunction
    public static void input(ArrayAggregationState state, @SqlType("T") Block value, @TypeParameter("T") Type type)
    {
        //
    }

    @CombineFunction
    public static void combine(ArrayAggregationState state, ArrayAggregationState otherState)
    {
        //
    }

    @TypeParameter("T")
    @OutputFunction("array(T)")
    public static void output(ArrayAggregationState state, @TypeParameter("T") Type outputType, BlockBuilder out)
    {
        //
    }
} 
```

Currently the connectors can't bind aggregation functions that uses parametrized types, `ArrayAggregation` is one of the functions that needs to use parametrized types but it doesn't use the aggregation framework. We should probably switch it to aggregation framework at some point.

**Comment by buremba** [comment]
Any update on this issue?

**Comment by electrum** [comment]
@haozhun and I had a conversation about this. It will be a major change as we don't have any support for annotated aggregation functions with type parameters.

It would be helpful to know all the specific use cases so we can have a clear picture of the required design. If these can be expressed in terms of existing functions, that would be easiest, as we can convert the existing functions.

The reason I ask for use cases is that this seems to work for `array_agg`, which doesn't really care about the contents, but might not work for things that examine the contents and possibly require different state types.

**Comment by buremba** [comment]
Hey @electrum, we have a custom type called `set` and need this feature for parametrizing the `set(<T>)` similar to `array_agg(<T>)`. As a workaround, we implement it for common types similar to `ApproximateSetAggregation` but the `set` function works similar to `HashSet` and only compares `Block`s in order to ensure that they're unique so doesn't need to know about the content as long as it's comparable.

I thought that maybe you can add a new method to `Plugin` that allows us to register functions that are not supported in new annotation based framework but if it doesn't work or is not convenient, then it's OK.
