### ISSUE TITLE
Hash partition on GroupId in aggregation exchanges

### ISSUE THREAD

**Issue by raghavsethi** [prestodb/presto#6484]
This helps in the case where there is a global aggregation and all the finals have to be processed by a single machine. Adding GroupId to the the partitioning will help distribute to a small number of machines.

**Comment by martint** [comment]
Specifically, it can help distribute work when the number of grouping sets is large, which can make queries run faster and be able to take advantage of more memory.

**Comment by raghavsethi** [comment]
This is no longer required, since `GROUPING()` is merged.
