### ISSUE TITLE
Add configurable limit on Hive partitions read

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#6517]
This will prevent the coordinator from running out of heap space, when someone tries to query a table with a very large number of partitions. I think the right place to add this is in `ThriftHiveMetastoreClient`. We just need to pass the limit + 1 as the last parameter in `getPartitionNamesFiltered` and `getPartitionNames`, then check if we got more than the limit. 
A config property should be added to `HiveClientConfig`, something like `hive.max-partitions-per-table`.
The error message that's thrown should use a new error code (added to HiveErrorCodes), like HIVE_TOO_MANY_PARTITIONS.

**Comment by electrum** [comment]
Is this supposed to be a per-call limit or cumulative for the query?

If per query, the metastore client can't track this itself since it doesn't know the query ID associated with the request.

**Comment by cberner** [comment]
per-call is what I had in mind. We just want to avoid OOM'ing the coordinator by reading an enormous number of partitions, that then get inflated into HivePartition objects

**Comment by electrum** [comment]
This should be covered by `hive.max-partitions-per-scan`.
