### ISSUE TITLE
The table can not be deleted.

### ISSUE THREAD

**Issue by handsetvn** [prestodb/presto#6547]
presto:default> select * from orders;
 orderkey | orderstatus | totalprice | orderdate 
----------+-------------+------------+-----------
        1 | aaa         |        1.1 | NULL      
(1 row)

Query 20161107_142057_00130_243y7, FINISHED, 2 nodes
Splits: 2 total, 2 done (100.00%)
0:00 [1 rows, 478B] [2 rows/s, 1.32KB/s]

presto:default> delete from orders where orderkey = 1;
Query 20161107_142122_00131_243y7 failed: This connector only supports delete where one or more partitions are deleted entirely

Can anybody help me?

**Comment by dain** [comment]
Although Presto supports arbitrary delete criteria like you have in the query above, Hive only supports deleting either the entire table for unpartitioned tables or whole partitions for partitioned tables.  If you are unfamiliar with Hive partitioning, this article seems like a reasonable introduction https://www.tutorialspoint.com/hive/hive_partitioning.htm

In Presto, you can specify the partitioning using the `partitioned_by` table property as in this example: https://prestodb.io/docs/current/connector/hive.html#examples
