### ISSUE TITLE
Catalog 'hive' does not support table property 'location'

### ISSUE THREAD

**Issue by handsetvn** [prestodb/presto#6558]
presto:mp_catalog> CREATE TABLE mp_catalog.page_views (
                ->   view_time timestamp,
                ->   user_id bigint,
                ->   page_url varchar,
                ->   ds date,
                ->   country varchar
                -> )
                -> WITH (
                ->   format = 'ORC',
                ->   partitioned_by = ARRAY['ds', 'country'],
                ->   bucketed_by = ARRAY['user_id'],
                ->   bucket_count = 50,
                ->  LOCATION = 's3://emr.presto.airpal/wikistats/orc'
                -> );
Query 20161108_080139_00132_243y7 failed: Catalog 'hive' does not support table property 'location'

presto:mp_catalog> 

Can anybody solve this? Thanks.

**Comment by yuananf** [comment]
This property is already in master, and should be available in the next release.
See https://github.com/prestodb/presto/pull/6535 

But it is ```external_location``` not ```location```
