### ISSUE TITLE
testResourceGroupInfo - random test fail 

### ISSUE THREAD

**Issue by fiedukow** [prestodb/presto#6561]
@miniway After 7d98b8e649148f7f9eedd81c25a404867e98fa34 testResourceGroupInfo fails randomly.
The fail occur on the line 
```
assertGreaterThan(global.getCpuUsage(), 0L);
```
as sometimes `global.getCpuUsage()` returns `0L`.

Should the test be modified to accept `0L` as well or is there an underlying problem causing wrong result to be returned randomly?

**Comment by cawallin** [comment]
There's an open PR to revert that until @miniway can fix the test: https://github.com/prestodb/presto/pull/6557
