### ISSUE TITLE
Maven checks Travis job fails nondeterministiacally

### ISSUE THREAD

**Issue by sopel39** [prestodb/presto#6575]
Same branch:
https://travis-ci.org/Teradata/presto/jobs/174453816
https://travis-ci.org/sopel39/presto/jobs/174441908

FYI: @martint

**Comment by martint** [comment]
The failure in first one seems to be due to OOM error. I've seen similar issues recently.

**Comment by sopel39** [comment]
I am not sure how relevant is this. Nondeterministic failures require holistic approach and investigation
