### ISSUE TITLE
Hive/Presto java.lang.ClassNotFoundException: com.mysql.jdbc.Driver

### ISSUE THREAD

**Issue by handsetvn** [prestodb/presto#6577]
hive> ADD JAR s3://xxxxxxxx/mysql-connector-java-5.1.35.jar;
Added [/mnt/tmp/xxxxxxx/mysql-connector-java-5.1.35.jar] to class path
Added resources: [s3://xxxxxx/mysql-connector-java-5.1.35.jar]
hive> ADD JAR s3://massgenie-libraries/qubole-hive-JDBC-final-0.0.6.jar;
Added [/mnt/tmp/xxxxxx/qubole-hive-JDBC-final-0.0.6.jar] to class path
Added resources: [s3://xxxxxx/qubole-hive-JDBC-final-0.0.6.jar]
hive> CREATE EXTERNAL TABLE HiveTable(
    >   id INT,
    >   id_double DOUBLE,
    >   names STRING,
    >   test INT
    > )
    > STORED BY 'org.apache.hadoop.hive.jdbc.storagehandler.JdbcStorageHandler'
    > TBLPROPERTIES (
    >   "mapred.jdbc.driver.class"="com.mysql.jdbc.Driver",
    >   "mapred.jdbc.url"="jdbc:mysql://xxxxxxx.rds.amazonaws.com:3306/mp_catalog",
    >   "mapred.jdbc.username"="root",
    >   "mapred.jdbc.input.table.name"="JDBCTable",
    >   "mapred.jdbc.output.table.name"="JDBCTable",
    >   "mapred.jdbc.password"="123456789",
    >   "mapred.jdbc.hive.lazy.split"= "true"
    > );
OK
Time taken: 1.291 seconds
hive> select * from HiveTable;
OK
Failed with exception java.io.IOException:java.lang.RuntimeException: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
Time taken: 1.543 seconds

**Comment by martint** [comment]
This issue is not related to Presto. The output you posted is from the Hive CLI. You may want to ask about or report an issue with the Hive project, instead.
