### ISSUE TITLE
How to connect a Presto database to MySQL ?

### ISSUE THREAD

**Issue by handsetvn** [prestodb/presto#6578]
Is it possible to make joins between two tables from two different Presto catalogs? Assume I have a product table in MySQL and another table sales_order in hive; can I join them? If yes, then how can I specify the catalog for MySQL and what would my query look like?

**Comment by jpavlick** [comment]
Sure, it's pretty easy. You can reference tables like this: `catalog.schema.table`. So assuming you are in your hive catalog, you can write something like:

`select * from hive.sales.sales_order join mysql.database_name.products`

This is assuming you have a mysql connection that goes by the name of `mysql`. The name of the catalog is taken from the properties file. For example, `mysql.properties` would result in a catalog name of `mysql`.

**Comment by martint** [comment]
Take a look at https://prestodb.io/docs/current/connector/mysql.html for instructions on how to configure the mysql connector.
