### ISSUE TITLE
Display better error messages for unsupported correlated query shapes

### ISSUE THREAD

**Issue by martint** [prestodb/presto#6580]
The message that's currently reported is not very helpful. We should validate the shape of the query during analysis and show a more meaningful message.

For example, for a query like:

```sql
SELECT *
FROM t
WHERE t.x IN (
   SELECT DISTINCT t.y
   FROM u
)
```

It should say something like "correlated subqueries using DISTINCT not supported", and possibly, include the name of the field referenced from the outer scope (sometimes, a typo in a column name can turn a subquery into a correlated one).

**Comment by kokosing** [comment]
It seems to be related to: https://github.com/prestodb/presto/issues/6491. I will assign myself to it and try fix that (and the other bug) in the near future

**Comment by kokosing** [comment]
Fixed with https://github.com/prestodb/presto/pull/8489
