### ISSUE TITLE
Support Unicode escaped strings

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#6585]
The standard specifies a (slightly strange) syntax for string literals with escaped Unicode in 9075-2:2011 section 5.3. The starting token in the grammar is `<Unicode character string literal>`.

The PostgreSQL manual gives an overview: https://www.postgresql.org/docs/9.6/static/sql-syntax-lexical.html#SQL-SYNTAX-STRINGS-UESCAPE

**Comment by electrum** [comment]
<img width="658" alt="screen shot 2017-02-09 at 11 57 04 am" src="https://cloud.githubusercontent.com/assets/9230/22800808/5fef4d2c-eebf-11e6-86a4-38db78be27ea.png">
<img width="514" alt="screen shot 2017-02-09 at 11 58 06 am" src="https://cloud.githubusercontent.com/assets/9230/22800807/5fec2714-eebf-11e6-96cd-3cd6a1d05090.png">
<img width="774" alt="screen shot 2017-02-09 at 12 00 53 pm" src="https://cloud.githubusercontent.com/assets/9230/22800827/70a0a094-eebf-11e6-8911-69502c168296.png">
<img width="759" alt="screen shot 2017-02-09 at 11 59 42 am" src="https://cloud.githubusercontent.com/assets/9230/22800805/5fea7bee-eebf-11e6-8983-f6c57f664f6e.png">

**Comment by electrum** [comment]
Item 21 and 22 seem to disallow surrogates, since surrogates are not a "character". This can be checked by `Character.isSurrogate()` or equivalent code. We should be conservative and reject any code points that are surrogates.

**Comment by highker** [comment]
diff out (https://github.com/prestodb/presto/pull/7357)
