### ISSUE TITLE
Query 20161110_121745_00074_ru8sf failed: line 1:15: Catalog mysqlcatalog does not exist

### ISSUE THREAD

**Issue by handsetvn** [prestodb/presto#6593]
[root@ip-10-0-0-248 /]# ls /etc/presto/conf.dist/catalog/
hive.properties  mysqlcatalog.properties
-----------------------
catalog/mysqlcatalog.properties:
connector.name=mysql
connection-url=jdbc:mysql://example.net:3306
connection-user=root
connection-password=secret

Query 20161110_121745_00074_ru8sf failed: line 1:15: Catalog mysqlcatalog does not exist
select * from mysqlcatalog.mp_catalog.JDBCTable

**Comment by dain** [comment]
The catalog file should placed inside of the etc directory in the Presto release.  It looks like this is in the system etc directory.  So you should have the following paths:
```
<presto-release>/bin/launcher
<presto-release>/lib/*.jar
<presto-release>/plugin/<plugins>
<presto-release>/etc/jvm.config
<presto-release>/etc/catalog/mysqlcatalog.properties
```
