### ISSUE TITLE
Add ability to call MySQL procedures from Presto

### ISSUE THREAD

**Issue by ghost** [prestodb/presto#6604]
presto:default> select * from mysql.mp_commerce.test;
 idtest |     testcol      
--------+------------------
      1 | Hair Care        
      2 | Body Care        
      3 | Kits & Gift Sets 
(3 rows)

Query 20161111_022956_00023_ki3sk, FINISHED, 2 nodes
Splits: 2 total, 2 done (100.00%)
0:00 [3 rows, 0B] [7 rows/s, 0B/s]

presto:default> call mysql.mp_commerce.new_procedure();
Query 20161111_023022_00024_ki3sk failed: Procedure not registered: mysql.mp_commerce.new_procedure

**Comment by cawallin** [comment]
It's currently not possible to call a procedure in mysql from presto. I'll edit this issue to reflect that this is a feature request.

**Comment by solebox** [comment]
ping?

**Comment by electrum** [comment]
Can those interested in this feature explain more about their use cases? That would help in understanding how it should work.
