### ISSUE TITLE
Add function for parsing string with unicode escapes

### ISSUE THREAD

**Issue by martint** [prestodb/presto#6608]
It should be able to handle \uxxxx sequences

**Comment by electrum** [comment]
Do you have specific format in mind? Example issue:
* Is `\\` supported?
* Are other escapes supported?
* Is this UTF-16?
* Do we support direct encoding of non-BMP characters, or are surrogates required?

**Comment by martint** [comment]
Some relevant context: https://tools.ietf.org/html/rfc5137
