### ISSUE TITLE
Support AWS V4 Signature for S3-compatible storage

### ISSUE THREAD

**Issue by zz22394** [prestodb/presto#6610]
Dear team:

September, We sent a PR(prestodb#6054) using AWS V2 Signature for S3-compatible storage and glad that it is merged.

Now we will upgrade it to enable AWS V4 Signature which is safer than V2 Signature.

We had investigated how to customize the region file in [aws-sdk-java#842](https://github.com/aws/aws-sdk-java/issues/842).
Next we will implement it in Presto connector in a few weeks.

**Comment by yuokada** [comment]
(Maybe) Related: https://github.com/prestosql/presto/pull/1276
