### ISSUE TITLE
Updating presto Blocks

### ISSUE THREAD

**Issue by handsetvn** [prestodb/presto#6612]
Is there is any possibility to update a page or a block in memory? we are working on in-memory update in presto blocks. any suggestions?

thanks in advance.

**Comment by buremba** [comment]
You should use PageBuilder and BlockBuilder for constructing Page and Block instances. Page and Block are immutable so it's not possible unless you use some nasty tricks like accessing the underlying data structure of Block instances.

**Comment by dain** [comment]
There is a fundamental assumption in Presto that blocks are immutable.  If you were to write a mutable block you would likely break hashing, sorting and other operators in Presto.

You could try writing a block that sits on copy on write data structure, but you would need to assure that the Block always returns the same values to Presto.
