### ISSUE TITLE
Presto connector

### ISSUE THREAD

**Issue by BartoszK** [prestodb/presto#6624]
Hi,

I wanted to ask if there is a Presto connector that can be used to connect to a separate Presto cluster. We have two separate Hadoop clusters, both with Presto installed. I was wondering if it is possible to query the data from both, while keeping the processing local i.e. using the local Presto resources and just transferring results to the other presto instance.

**Comment by KBP-TDC** [comment]
@BartoszK I guess extending the BaseJDBC Connector is the simplest option but introduces a bottleneck of streaming results via a single node.

**Comment by electrum** [comment]
We've discussed building this, but it requires an efficient parallel API to read data from Presto. @AlekseiS has started working on adding that API. After we have that, a Presto-to-Presto connector will follow.

**Comment by electrum** [comment]
The parallel output is in #7061
