### ISSUE TITLE
Separate independent concepts in logical planer

### ISSUE THREAD

**Issue by kokosing** [prestodb/presto#6625]
Currently logical planner does all at once: 
 - handle coercions
 - handle subqueires
 - handle prepared statement paramenters
 - etc

This makes maintenance of planner to be difficult as you need to think about all of these aspects at once when doing a change.

Take a look at method [appendInPredicateApplyNode](https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/sql/planner/SubqueryPlanner.java#L180). This method handles `IN` with a subquery, but lines 193-197 have to take care about prepared statement parameters. Check https://github.com/prestodb/presto/pull/6611/commits/d894aa4780d5595a5d56f0761d3329ef2ef6c686 to see how this method is going to look like when adding coercion handling. This hides the main purpose of that method.

Another example is `TranslationMap` which does coercion handling (adds `CAST` where needed), IMO it has two responsibilities which makes it more difficult to use this class.

I would like to propose a raw idea of refactoring to extract phases out of logical planner and run them separately. Let say phases will be executed in order.
 - A - handle prepared statement parameters
 - B - handle coercion
 - C - create plan node tree
In that way in phase C, planner do not need to care about coercion as it was done already in B and all the types should match. It looks like phases A and B will operate on `Statement` as something like `Statement` rewrite.

This is just raw idea, and I would like to hear your opinion about this. Planner is complicated and I think it is worth to untangle it a bit. Unfortunately, I am not sure if such refactor is possible as it there might be a cyclic dependencies between phases (for example to coerce the type I need to plan tree node, but to plan tree node I need to know how to coerce, so code does both at once). My plan is to play with it and see what can be achieved.

CC: @martint @sopel39 @ilfrin

**Comment by kokosing** [comment]
CC: @dain

**Comment by dain** [comment]
The logical planner is a big knot of code, and I would be happy to see it simplified.  I'm also not sure it can be done due to cyclic dependencies.  I'm also concerned about anyone working on this code without first adding more extensive testing to catch correctness errors.

Anyway, this is really @martint's call.  I only occasionally touch this code (and I usually make is worse).
