### ISSUE TITLE
DESCRIBE OUTPUT for CREATE VIEW is potentially incorrect

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#6630]
While working on #6620, I noticed that `DESCRIBE OUTPUT` for `CREATE VIEW` returns the schema of the view. My expectation is that the output should be empty, just like it is for `CREATE TABLE`, and that the current behavior is an unintended side effect of the implementation.

**Comment by electrum** [comment]
This failing test (applied on the referenced PR) demonstrates the issue:
```java
assertDescribeOutputEmpty("CREATE VIEW foo AS SELECT * FROM nation");

**Comment by rschlussel** [comment]
@electrum Do you know why the scope created in StatementAnalyzer for `visitCreateView` has the uses the relation of its input and not a rows field like `visitCreateTableAsSelect` (or an empty list if it doesn't give you a row count)?  My understanding of scope is that the relation is supposed to give information about the output.

**Comment by electrum** [comment]
That's a question for @martint

**Comment by martint** [comment]
That line is wrong. It should be returning a scope with no columns in it.
