### ISSUE TITLE
Move correlated predicates out of the subquery

### ISSUE THREAD

**Issue by kokosing** [prestodb/presto#6638]
1. In the subquery, add the non-correlated columns in the correlated predicates to the SELECT-list.
2. Move the subquery to the FROM clause in the outer query block.
3. Move the correlated predicate to either WHERE clause or the ON clause corresponding to the moved subquery in the outer query block.
4. Update the column reference in the correlated predicate to point to the column projected out of the subquery.
5. Add DISTINCT to the subquery (or indicate that the subquery is semi-joined when it is possible.)

Before:
```
SELECT c_custkey, c_name 
FROM customer 
WHERE EXISTS (
  SELECT * FROM orders WHERE o_orderdate = '1995/01/01' AND o_totalprice <= c_acctbal);
```
After:
```
SELECT c_custkey, c_name 
FROM customer, (
  SELECT DISTINCT o_custkey FROM orders WHERE o_orderdate = '1995/01/01') AS v 
WHERE v.o_totalprice <= c_acctbal;
```

This should affect performance of TPCH Q4, Q21 and Q22.

**Comment by maciejgrzybek** [comment]
@kokosing:
shouldn't 
```sql
SELECT c_custkey, c_name 
FROM customer, (
  SELECT DISTINCT o_custkey FROM orders WHERE o_orderdate = '1995/01/01') AS v 
WHERE v.o_totalprice <= c_acctbal;
```
be:
```sql
SELECT c_custkey, c_name 
FROM customer, (
  SELECT DISTINCT o_totalprice FROM orders WHERE o_orderdate = '1995/01/01') AS v 
WHERE v.o_totalprice <= c_acctbal;
```

(`o_custkey` -> `o_totalprice` in projection of subquery)
?

**Comment by kokosing** [comment]
Yes. You are right there is a mistake in the queries above.

But I am not sure if we could use this rewrite with non equality correlated predicate - `v.o_totalprice <= c_acctbal`. It seems that is will affect the cardinality of results.

@KBP-TDC  Am I right? If so then we have a mistake in `https://teraworks.teradata.com/pages/viewpage.action?spaceKey=TC4HSWARM&title=Subquery+Rewrites`

If this rewrite is only applicable to equality correlated predicate then it should be implementingt this will no better results than https://github.com/prestodb/presto/issues/6988 on which @rschlussel is working. That would mean that we should close this one.

I am sorry I did not notice this earilier ; /
