### ISSUE TITLE
Supertype not recognized in SIMPLE CASE, IF, IN (Subquery), ANY (Subquery), ALL (Subquery)

### ISSUE THREAD

**Issue by sopel39** [prestodb/presto#6654]
```
presto:sf1> SELECT IF(1, 1.0, 1);
Query 20161117_123322_00020_dd5yv failed: line 1:11: IF condition must evaluate to a boolean (actual: integer)
```
CC: @kokosing, @ilfrin, @martint, @arhimondr 

This issue is caused by `ExpressionAnalyzer#coerceToSingleType`, which doesn't use `getCommonSuperType`

**Comment by dain** [comment]
The problem is the first argument must be  `boolean` and not an `integer` (e.g. `1`).  If you change the query to `SELECT IF(true, 1.0, 1)` it works.

**Comment by sopel39** [comment]
Sorry, I pasted wrong example. This fails:
```
presto> select if(true, cast(1.0 as decimal(2,1)), 1);
Query 20161117_210022_00007_tfh7f failed: line 1:8: Result types for IF must be the same: decimal(2,1) vs integer
```

while
```
presto> select if(true, 1.0, 1);
 _col0 
-------
   1.0 
(1 row)
```
passes

**Comment by dain** [comment]
I'd also double check all other places we add implicit coercions.

**Comment by sopel39** [comment]
Fixed by: https://github.com/prestodb/presto/pull/6808/commits/459ec8875a97546a1adf12e7a16cca82a8dcf79a. @dain I have added tests for all expressions that used `ExpressionAnalyzer#coerceToSingleType`

**Comment by sopel39** [comment]
Fixed
