### ISSUE TITLE
Some test do fail due to translated Exception.getMessage

### ISSUE THREAD

**Issue by fiedukow** [prestodb/presto#6655]
Some of recently added tests do check message of RuntimeException.
Messages of some jdbc connector are translated to system language and (at least on Mac) for that reason, the test fails. Tested on polish as system language.
One example of that is:
fbd8dd8c385015a7618aaa3751135f1d8dab8dd2
TestDbResourceGroupConfigurationManager.testDuplicates():86
```
            assertTrue(ex.getCause().getMessage().startsWith("Unique index or primary key violation"));
```

but it would be nice to make sure that all standard test that are started by `mvn clean install` do pass on different system language.

The fix is to force language for test or to avoid checking exception.getMessage() content.

**Comment by fiedukow** [comment]
CC: @elonazoulay

**Comment by wenleix** [comment]
I can reproduce this issue by set my Mac language and locale to Polish and run 
```
mvn -Dtest=TestDbResourceGroupConfigurationManager#testDuplicates test
```
under `presto-resource-group-managers`. 

The issue can be resolved by adding the following line into `setup` method of the test case:
```
        Locale.setDefault(new Locale("en", "US"));
```

**Comment by findepi** [comment]
I am closing this. https://github.com/airlift/airbase/pull/98 is not yet merged, but there is nothing else we plan to do here.
