### ISSUE TITLE
Add limit on SQL query text length

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#6664]
We should have a config option for the maximum length of a SQL query. A default of 1MB might be reasonable. The logged query text should be truncated to the maximum length (as part of the reason for this change is to prevent gigantic SQL statements in the generated events).

**Comment by wenleix** [comment]
@electrum : For a query exceeds the maximum length, should we just reject it, or should we just truncate it when logging it (which I assume it's in `QueryMonitor`? ).

A similar truncation for output stage json is done in #4936

**Comment by kokosing** [comment]
Trancated query is very likely to be invalid and for sure it has different semantic. So I prefer to fail in case of too long query.

In the commit you attached, json is not truncated, but it is not even set when it is too long.

**Comment by wenleix** [comment]
Thank  you @kokosing . Yes we will failed the query if it's too long [here](https://github.com/prestodb/presto/pull/7001/commits/4366ee66bb4570a91faeccfc9b8d3eeff2050379#diff-d5a692e1563801a57b254966605ac929R293)

```
            if (query.length() > maxQueryLength) {
                 throw new PrestoException(EXCEEDED_QUERY_LENGTH_LIMIT, String.format("Maximum query length limit exceeded: %d", query.length()));
             }
```

We log the truncated query in the failure information (`FailedQueryExecution`) so we can get some context what the query looks like :).

**Comment by wenleix** [comment]
Merged. Close the issue.
