### ISSUE TITLE
presto to support bucket hive table

### ISSUE THREAD

**Issue by richardxin** [prestodb/presto#6666]
hive version: 1.1.0
CDH5.7.2
presto 0.152

1. create a bucket table in hive:
hive> create table employee(
    > id int,
    > name varchar(64),
    > age int
    > ) clustered by (age) into 2 buckets stored as orc tblproperties('transactional'='true');
2. insert 2 rows to table employee:
hive> insert into employee values(1,'hdfs',28),(2,'spark',17);
3. select from hive (OK)
hive> select * from employee;
1       hdfs    33
2       spark   17
Time taken: 0.76 seconds, Fetched: 2 row(s)
4. when I use presto:
presto:default> select * from employee;
Query 20161118_063045_00059_apgci failed: Hive table is corrupt. It is declared as being bucketed, but the files do not match the bucketing declaration. Found sub-directory in bucket directory for partition: <UNPARTITIONED>

**Comment by ray6080** [comment]
Have you configured this: `set hive.enforce.bucketing = true`?

**Comment by richardxin** [comment]
Yes, I did

**Comment by av-416** [comment]
I've also experienced this issue with Hive 1.x and Presto 0.155. I think it is related to the directory structure expected by Presto for bucketed tables. 

[This](https://github.com/prestodb/presto/blob/b080503e05b43dde5173743631a41af129fea072/presto-hive/src/main/java/com/facebook/presto/hive/BackgroundHiveSplitLoader.java#L395) is the exception thrown in the BackgroundHiveSplitLoader. 

For the ACID bucketed table you would have a folder structure like:
TABLE DIR > BASE OR DELTA DIR > BUCKET DIRS

But the BackgroundHiveSplitLoader is expecting the form TABLE DIR > BUCKET DIRS, which is the traditional form for non ACID bucketed tables. 

If this sounds about right, I can take a look into this.

**Comment by sandeep-gunnam** [comment]
Hi 

We have the same usecase and planning to go to production with this. Now we hit this road block. Could you please suggest any workaround for this problem for the moment.

Thanks in advance. 

-Sandeep

**Comment by ddjjain** [comment]
@richardxin .. we are also facing the same issue while using presto+hive. By any chance did you got any work around this ?
@av-416, Can you suggest any work around this?
@sandeep-gunnam  we are also having the same issue. Let me know if you got any work around..

Thanks in Advance

**Comment by electrum** [comment]
Presto does not support transactional Hive tables.

**Comment by sandeep-gunnam** [comment]
Thanks for your response @electrum . Any plans in future to support the same?

**Comment by richardxin** [comment]
ok, so it seems that Impala doesn't support bucket table either.

**Comment by ervazquez** [comment]
Hi,

Is there a ticket open to solve this issue? Or has it been solved already in a more recent version of Presto?

**Comment by dain** [comment]
Presto has supported bucketed tables for both read an write for a long time now.  Sorted bucketed tables are not supported for writes.

**Comment by sandeep-gunnam** [comment]
Hi Dain

Below is the particular code in Presto that is causing the exception 
if (isDirectory(next)) {
                // Fail here to be on the safe side. This seems to be the same as what Hive does
                throw new PrestoException(HIVE_INVALID_BUCKET_FILES, format("%s Found sub-directory in bucket directory for partition: %s", CORRUPT_BUCKETING, hiveFileIterator.getPartitionName()));
            }

When a ACID table is created in hive the folder structure is "PARTITION/delta_xxxx/bucket_xxx". This shows bucket files are not directly under Partition folder but under a sub-directory starting with delta. The comment in above code looks stale because hive does not have a problem with this directory structure. Are there plans to support Hive ACID tables in Presto?

**Comment by dain** [comment]
Transactional tables haven't really caught on, and without the demand, it is unlikely that anyone will implement support for them.

**Comment by sandeep-gunnam** [comment]
Thanks for your response Dain. Appreciate it. 

-Sandeep

**Comment by vaibhavjajoo** [comment]
Following up on an old thread. Has there been any update on transaction table support? We will like to handle data restatements and SCDs using Hive transactional tables and are looking for alternatives.  

Appreciate input/learnings. 

- cheers, 
VJ

**Comment by richardxin** [comment]
I haven't seen any progress on this one, it seems that the ticket was closed as "NO_FIX" due to lack of demand. :(

**Comment by jsavolainen** [comment]
Hi,

Please check https://github.com/jsavolainen/presto/tree/hive-acid for an **experimental** support for reading Hive ACID tables. The code for parsing ACID bucket structure is copied from Hive 2.3, but it should be backwards compatible with earlier Hive versions. Currently this ACID support is limited to bucket files with INSERT-only statements. Full ACID support would be much more complicated to implement.

**Comment by electrum** [comment]
Presto does not support ORC transactional tables.

**Comment by cheekoo09** [comment]
Hi Jsavolainen 

My only requirement is to query a transnational table using Presto. I do not need to insert / update using presto. Will your solution work :  https://github.com/jsavolainen/presto/tree/hive-acid  ?
Thanks

**Comment by jsavolainen** [comment]
@cheekoo09, yes, that works for reading transactional tables but it can can cause unexpected query results or failures, so I would think twice before using it in production.

**Comment by cheekoo09** [comment]
@jsavolainen Is there any other solution to this problem ? We really need to make this work. I believe Teradata distribution for Presto has fixed this issue. Do you have any insight on this ?

https://teradata.github.io/presto/docs/current/release/release-0.167-t.html#bugs-fixed

**Comment by jsavolainen** [comment]
@cheekoo09 The Teradata fork of Presto fixes just a compatibility issue with Hive 2.x non-transactional bucketed tables, but is still incompatible with transactional tables.

**Comment by engomar2003** [comment]
I have tested it with partitioned and bucketed table, it works fine on condition that all buckets in each partition are filled

**Comment by engomar2003** [comment]
create table employee(
id int,
name varchar(64),
age int
) PARTITIONED BY (country String)
clustered by (id) into 2 buckets stored as orc tblproperties('transactional'='true');

insert into employee partition(country='eg') values(1,'hfs',29),(2,'hive',28);

till now this works fine
but if I added one bucket in another partition. 'sa'
insert into employee partition(country='sa') values(3,'avro',32);
this will throw the same exception

so make sure the table is partitioned and if ORC bucketed, make sure each partition has all buckets, I don't know how to manage this logic yet in my project
