### ISSUE TITLE
Stored Procedure in presto

### ISSUE THREAD

**Issue by handsetvn** [prestodb/presto#6667]
Hello @dain ,
I have configured presto and I am trying to use it.
But I want to ask that Can we have stored procedure in presto?

Pls suggest me some links related to presto so that I can learn more about it.

**Comment by dain** [comment]
The Presto SPI allows a connector to expose callable procedures written in Java.  These are typically used by the administrator to perform maintenance operations on a catalog (e.g., compaction, flush cache, etc).  The SPI interface starts here: https://github.com/prestodb/presto/blob/master/presto-spi/src/main/java/com/facebook/presto/spi/connector/Connector.java#L98

Currently, Presto does not have the kind of SQL procedural language you many be familiar with in Oracle or PostgreSQL.
