### ISSUE TITLE
Fail to cast BIGINT with literal table specified `WITH` clause.

### ISSUE THREAD

**Issue by Lewuathe** [prestodb/presto#6685]
This query works as expected.

```
presto> WITH tab AS (
                 -> select  id from some_table
                 -> )
                 -> select cast(id as bigint) from tab where id != '10a0';
```

But when I specified with literal, it does not work.
```
presto> WITH tab AS (
                 -> select '10a0' id
                 -> )
                 -> select cast(id as bigint) from tab where id != '10a0';
Query 20161122_XXXX_XXXX_XX failed: Can not cast '10a0' to BIGINT
```

Predicates does not seem to work as expected when we specify the value with literal.
Can optimizer embed literal without considering predicate condition?
I tested this above 0.152.3 and can reproduce.

**Comment by martint** [comment]
This is the same as https://github.com/prestodb/presto/issues/3232

**Comment by Lewuathe** [comment]
@martint Sorry for missing, thanks!
