### ISSUE TITLE
catalog is not reflecting when queried after adding it in etc/catalog 

### ISSUE THREAD

**Issue by prabhacloud** [prestodb/presto#6728]
catalog added in etc/catalog/mysql.properties will not be reflected when querying it with presto-cli.jar unless if the presto service is restarted which will make the presto server offline for a moment.

**Comment by akshatnair** [comment]
@prabhacloud it is required that Presto server is restarted after adding a new catalog for it to show up. Is your ticket to confirm this behavior or add a new mechanism to ensure that someone can add a new catalog without restarting?

**Comment by dain** [comment]
The plan is to support `CREATE CATALOG` instead of using some sort of file monitor.

**Comment by prabhacloud** [comment]
@dain support for CREATE CATALOG already added.But i can't find any such statements and what if i needed to add a catalog in between and have to restart the service for reflection.Won't that create downtime.

**Comment by prabhacloud** [comment]
@akshatnair yes akshat i am talking about such mechanism to prevent the downtime from happening.
