### ISSUE TITLE
Optimize InMemoryHashAggregationBuilder.hashSortedGroupIds()

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#6730]
This method boxes one int for every group, which could be very expensive when spilling many groups. It should be optimized to avoid the boxing, but doing a sort on `int`s instead of `Integer`s

**Comment by pnowojski** [comment]
Are you sure this is an real issue? I think current solution could be good enough. Either `Integer` boxing is inlined by JIT or `Integer` is extremely short lived stack object, so GC shouldn't be a problem. Alternative is to implement own quick sort on `int` with custom comparator.

Are you more concern about general performance issues or GC issues?

**Comment by cberner** [comment]
GC. We've had many problems in the past with allocating small short lived objects, where the VM wasn't able to avoid the allocation

**Comment by pnowojski** [comment]
Ok, we will address this. 

CC @ilfrin

**Comment by fiedukow** [comment]
https://github.com/prestodb/presto/pull/6974

**Comment by fiedukow** [comment]
Merged to master, thanks @martint.
Closing.
