### ISSUE TITLE
SET SESSION allows setting invalid values to session properties

### ISSUE THREAD

**Issue by losipiuk** [prestodb/presto#6741]
Currently it is possible to set arbitrary value to session property even if it has validation function attached to it.

E.g. I can do
```
presto:public> set session task_writer_count=3;
SET SESSION
```

And it completes without error.
But then I cannot do anything until I restart cli:
Any command fails:
```
presto:public> select 1;
Query 20161201_152600_00032_8zkam failed: task_writer_count must be a power of 2: 3

presto:public> set session task_writer_count=4;
Query 20161201_152534_00031_8zkam failed: task_writer_count must be a power of 2: 3
```

**Comment by ebyhr** [comment]
This seems to be related with #5628.
