### ISSUE TITLE
Incorrect results due to improper inlining of arguments to TRY

### ISSUE THREAD

**Issue by martint** [prestodb/presto#6750]
The following query should fail:

```sql
SELECT TRY(x) IS NULL FROM (SELECT 1/y as x FROM (VALUES 1, 2, 3, 0, 4) t(y))
```

However, it succeeds and produces this incorrect output:
```
 _col0
-------
 false
 false
 false
 true
 false
(5 rows)
```

This is due to this check in MergeProjections, which only tests whether TRY appears at the root of an expression:

```java
private static boolean containsTry(ProjectNode node)
{
    return node.getAssignments().values().stream().anyMatch(TryExpression.class::isInstance);
}
```

**Comment by kokosing** [comment]
I will take care of this.

**Comment by kokosing** [comment]
Here is a fix: https://github.com/prestodb/presto/pull/6752

**Comment by electrum** [comment]
Nice work! That was fast.

**Comment by martint** [comment]
Fixed
