### ISSUE TITLE
Incorrect results for nested EXCEPT

### ISSUE THREAD

**Issue by martint** [prestodb/presto#6757]
`a EXCEPT (b EXCEPT c)` is being evaluated as `(a EXCEPT b) EXCEPT c`. This is incorrect, since EXCEPT (set subtraction) is not associative.

For example:
```
(VALUES 1) 
EXCEPT 
((VALUES 1) EXCEPT (VALUES 1))
```

Produces:
```
 _col0
-------
(0 rows)
```

The correct output should be:
```
 _col0
-------
     1
(1 row)
```

This is due to SetFlatteningOptimizer treating EXCEPT in the same manner as UNION and INTERSECT.

**Comment by martint** [comment]
cc @rschlussel

**Comment by rschlussel** [comment]
Thanks.  I can work on this
