### ISSUE TITLE
Improve ArrayFilterFunction performance

### ISSUE THREAD

**Issue by haozhun** [prestodb/presto#6779]
Performance of `ArrayFilterFunction` can be improved by:
* using `Block.isNull` and `Type.getX` instead of `readNativeValue`
* using `invokeExact` instead of `invoke`

This change would require having 5 variations of ArrayFilterFunction. This change may also make using the new scalar function framework from Chris work.

`TestArrayFilterFunction` and `BenchmarkArrayFilterFunction` are the relevant tests and benchmarks.

**Comment by wenleix** [comment]
Although the idea is similar to https://github.com/prestodb/presto/issues/6780, we don't need to do byte code generation for this one. The implementation idea would be to specialize the method for 5 types, similar to [ArrayContains](https://github.com/prestodb/presto/blob/c73359fe2173e01140b7d5f102b286e81c1ae4a8/presto-main/src/main/java/com/facebook/presto/operator/scalar/ArrayContains.java)

**Comment by nezihyigitbasi** [comment]
@wenleix @haozhun is anyone currently working on this?

**Comment by wenleix** [comment]
@nezihyigitbasi  I discussed with @haozhun , the proposed method is to write 5 specialized version of the code. However, @haozhun needs some investigation about if there is any type features missing in lambda expression. I will assign back to him for now :)

**Comment by wenleix** [comment]
An incorrect implementation: https://github.com/wenleix/presto/commit/78ea25563fffb74e9ba0cc33bf28ef5033435647. Just for reference.
