### ISSUE TITLE
Tableau Web Connector broken in 0.157

### ISSUE THREAD

**Issue by dabaitu** [prestodb/presto#6797]
Initial queries to populate catalogs and schemas work fine.

Once actual query is entered, we encounter:

tableauwdc-1.1.0.js:116 Uncaught Looks like the WDC is calling a tableau function before tableau.init() has been called._sendMessage @ tableauwdc-1.1.0.js:116log @ tableauwdc-1.1.0.js:49(anonymous function) @ presto-connector.html:264dispatch @ jquery-2.2.3.min.js:3r.handle @ jquery-2.2.3.min.js:3
tableauwdc-1.1.0.js:116 Uncaught Looks like the WDC is calling a tableau function before tableau.init() has been called.

**Comment by nezihyigitbasi** [comment]
Which Tableau version is this? According to #5537 the web connector should be working fine with Tableau 9.2.7.

Btw we have an old version running fine where the diff is the jquery version (it's `jquery-1.11.1.min.js` instead of `jquery-2.2.3.min.js`). Can you try reverting to that jquery version and see if it helps?

**Comment by dabaitu** [comment]
@nezihyigitbasi I accessed the web connector not through Tableau but using address of presto ui with /tableau/presto-connector.html?
Entering a query through there resulted in the errors I reported. Will give reverting jquery a try.

**Comment by nezihyigitbasi** [comment]
wait, I don't think you can run queries like that. Can you try with a tableau client without reverting anything?

**Comment by dabaitu** [comment]
doesn't Tableau configure the web connector by specifying the url of the web connector? I was just accessing the url directly

**Comment by nezihyigitbasi** [comment]
>>  I accessed the web connector not through Tableau

>> I was just accessing the url directly

From what you say I understand that you aren't using a Tableau client but rather access through the browser directly. You cannot run queries like that (please see how the web connector works [here](https://onlinehelp.tableau.com/current/api/wdc/en-us/help.htm#WDC/wdc_phases.htm))

You need to enter that url to the web connector interface in the Tableau client (shown here in the [docs](https://onlinehelp.tableau.com/current/api/wdc/en-us/help.htm#WDC/wdc_how_it_works.htm%3FTocPath%3DBasic%2520Concepts%7C_____1)).

**Comment by dabaitu** [comment]
thanks @nezihyigitbasi 
Running through Tableau worked.
Running queries directly through the url use to work in 0.143, that's how we tested our https hack. I was using the url directly to figure out issues with inspect and stuff when our Tableau users reported queries stopped working when we upgraded to 0.149. Looks like everything's good with 0.157
