### ISSUE TITLE
Create Table with external_location creates managed table

### ISSUE THREAD

**Issue by mcs1408** [prestodb/presto#6812]
When creating a table in presto with an external_location on S3 like the following

CREATE TABLE mcs_test ( field1 bigint, field2 bigint) WITH ( format='TEXTFILE', external_location='s3://my_bucket/path/to/dir/`);

it will still create a managed table in hive metastore on that external location. Especially when issuing a drop statement on that table it will not - as stated in the documentation - just delete the metadata of that table, but also the underlying files.

We are using Presto 0.158 with Hive Metastore 2.1.0-snapshot.

**Comment by electrum** [comment]
Fixed in #6813
