### ISSUE TITLE
Array Intersect Exists

### ISSUE THREAD

**Issue by amitna1r** [prestodb/presto#6823]
Build a function:
array_intersect_exists(array<E>, array<E>) -> boolean

That basically checks if the intersect of the two input arrays is NOT NULL. This would be more optimized than doing a cardinality(array_intersect(a1,a2)) > 0, since this would exit out once a common element is found.

**Comment by raghavsethi** [comment]
Already implemented.

**Comment by austenpiers** [comment]
@raghavsethi  

What is the UDF then??
Please include UDF name and link source code

**Comment by raghavsethi** [comment]
@martint You told me this was done, but I can't find it in the code either?

**Comment by raghavsethi** [comment]
Ah sorry, I misunderstood. This is under review: #7233
