### ISSUE TITLE
Simple Cassandra query so slow in Presto

### ISSUE THREAD

**Issue by hakangs** [prestodb/presto#6828]
I have a very simple Cassandra query:

`select sha1 from main_file_hashes where folder_id = '584a67c1ed902bc11554d8ad';`

and it returns empty result from Cassandra. But when I run the same query from Presto CLI, it takes so long (~2 mins) and query does not return result.

What am I missing here ?

Cassandra : 1 node, Presto : 1 node, both are running on the same server.

**Comment by KBP-TDC** [comment]
@hakangs Could you please take a look at the Presto UI and find out from the Live Plan (or EXPLAIN ANALYZE) how many rows are fetched by Presto from Cassandra? Maybe the predicate pushdown you expect does not happen?

**Comment by cawallin** [comment]
Also, what's the schema of your table? Only partitioning keys are pushed down to Presto currently.

**Comment by hakangs** [comment]
@cawallin the column in the where clause is not a partition key.

@KBP-TDC how can I do that ? I just have Presto CLI.

**Comment by electrum** [comment]
`EXPLAIN ANALYZE` is a normal query you can run from the CLI (or anything else that lets you run Presto queries): https://prestodb.io/docs/current/sql/explain-analyze.html

The web interface is available by accessing the Presto coordinator in your browser (whatever host:port you use in the CLI, just put that in your browser): https://prestodb.io/docs/current/admin/web-interface.html

**Comment by cawallin** [comment]
@hakangs I'm going to close this issue, if you still need assistance please provide the EXPLAIN ANALYZE output.

For the Cassandra connector, Presto will do a full table scan unless the predicate is on either the partition key or both the partition key and one or more clustering keys.

**Comment by gopal9405** [comment]
I cannot able to run the CREATE table query in Cassandra through presto cli

**Comment by ashishranjan2404** [comment]
facing the same issue, can we re-open this issue ? i can share the Analyze
