### ISSUE TITLE
map_filter does not support aggregation as input

### ISSUE THREAD

**Issue by rongrong** [prestodb/presto#6834]
>SELECT map_filter(map(array['k'], array[sum(x)]), (k, v) -> v IS NOT NULL)
  FROM (
    VALUES (1, 2), (1, 3), (2, 3)) AS t(x, y)
  GROUP BY y;

failed: aggregation analysis not yet implemented for: com.facebook.presto.sql.tree.LambdaExpression

**Comment by haozhun** [comment]
Fixed by #6835
