### ISSUE TITLE
When I use presto to read hive table data with parquet format,I got incorrect data from hive table

### ISSUE THREAD

**Issue by JasonBian** [prestodb/presto#6839]
when I use presto to read the hive table data with parquet format,I got the data is not the original data in hive table.For example, When I use hive sql to read the data from table,I got the data is "wttdqj5j", but when I use presto to read the hive table, I got the data like this "d9101db878a4b34a6d3d3454a7d52373"

![image](https://cloud.githubusercontent.com/assets/3529844/21134988/11f2178a-c15b-11e6-8697-27c32154fa17.png)

**Comment by nezihyigitbasi** [comment]
Which Presto version and which parquet reader are you using? If you are using the default/old Parquet reader can you also try running your query with the new one?

```
set session hive.parquet_optimized_reader_enabled=true;
```

**Comment by JasonBian** [comment]
@nezihyigitbasi my presto version is 0.152;
when I set seeion hive.parquet_optimized_reader_enabled=true;
![image](https://cloud.githubusercontent.com/assets/3529844/21168519/9b0bca68-c1ef-11e6-8fa6-0e9683826c31.png)
 but when I change to select * from table,it looks ok, and the presto query return the collect value.

**Comment by nezihyigitbasi** [comment]
I would check the parquet-level schema against the hive table schema as I guess `home_addr` column only exists in the hive schema (that's why it cannot be found in the parquet file schema). To see the schema of the parquet files you can use parquet-tools (or put a breakpoint in `ParquetPageSource` constructor and check `fileSchema`).

BTW it is always helpful to see the entire stack trace, for that you can start the presto cli with `--debug`.

**Comment by JasonBian** [comment]
@nezihyigitbasi For your advise,I use parquet-tools to check the fileschema,I found that the schema is correct,but when I debug the code I got the HIVE_CURSOR_ERROR problem
`ERROR	SplitRunner-12-62	com.facebook.presto.execution.TaskExecutor	Error processing Split 20161226_081512_00011_3s7am.1.0-0 {path=hdfs://bi-test/data_result/user/dw_user_wide_table_gid/20161223/part-r-00796.gz.parquet, start=268435456, length=33554432, hosts=[bi-02, bi-04], database=report_dw_mdp, table=dw_user_wide_table_gid, forceLocalScheduling=false, partitionName=day=20161223, effectivePredicate=com.facebook.presto.spi.predicate.TupleDomain@c7d45780} (start = 1482740113033, wall = 74 ms, cpu = 0 ms, calls = 1): HIVE_CURSOR_ERROR: home_addr not found in message user_gid {
  optional binary gid;
  optional binary imsi_md5;
}`

**Comment by JasonBian** [comment]
@nezihyigitbasi I've got the reason, the createParquetPageSource method of ParquetPageSourceFactory to change the query columns(gid, home_addr) to parquet.schema.Type list
`List<parquet.schema.Type> fields = columns.stream()
                    .filter(column -> column.getColumnType() == REGULAR)
                    .map(column -> getParquetType(column, fileSchema, useParquetColumnNames))
                    .filter(Objects::nonNull)
                    .collect(toList());` 
according to the column.getHiveColumnIndex() find the parquet.schema.Type from the fileSchema is really are(gid, imsi_md5).what cause this issue,I'm not sure.Maybe the parquet jar is different between hive and presto.

At last,I set hive.parquet.use-column-names=true in the catalog/hive.properties, the useParquetColumnNames param will be true,then it will getParquetType according to the parquet column names.After I change the properties,the query return correct result.
