### ISSUE TITLE
Presto authentication Bug -- work with kerberos

### ISSUE THREAD

**Issue by zhoushineyoung** [prestodb/presto#6863]
Error, ***Query 20161213_101323_00023_xxxxx failed: Access Denied: Cannot select from table db_xxx.tb_xxx***, occured when i submit the query statement, ***presto --server 10.8.8.88:15050 --catalog hive --schema adhoc_test --execute "select count(`*`) as count from presto_proxy_test_orders11;" --user adhoc***.

And i think that's a wrong result returning. 

test case context:
1. I created a database and a table with name ***adhoc_test*** and ***presto_proxy_test_orders11*** under a kerberos authentication enabled hadoop env, as user ***adhoc***. And the very user ***adhoc*** is the **owner** of db ***adhoc_test*** by default.
2. We can expect the result, user ***adhoc*** should have **all** privileges to do anything(select, drop ...) to table ***presto_proxy_test_orders11*** by inheritance.
3. But the returning result is not that mentioned point-2 above.
4. And every thing is ok in Hive.

**Comment by akshatnair** [comment]
Can you share your hive connector config values?
