### ISSUE TITLE
try_cast fails instead of returning null

### ISSUE THREAD

**Issue by nezihyigitbasi** [prestodb/presto#6869]
```
presto:nyigitbasi> select try_cast(5 as timestamp);
Query 20161213_213326_00011_i93iv failed: line 1:8: Cannot cast integer to timestamp
com.facebook.presto.sql.analyzer.SemanticException: line 1:8: Cannot cast integer to timestamp
```

```
presto:nyigitbasi> select try_cast(cast('x' as char(1)) as timestamp);
Query 20161213_213337_00012_i93iv failed: line 1:8: Cannot cast char(1) to timestamp
com.facebook.presto.sql.analyzer.SemanticException: line 1:8: Cannot cast char(1) to timestamp
```

Tested with both the master and `0.149`.

**Comment by haozhun** [comment]
This is intentional because there is no cast from integer/char to timestamp. cc @raghavsethi

**Comment by nezihyigitbasi** [comment]
For `try_cast` Presto docs say `Like cast(), but returns null if the cast fails.`, based on this shouldn't these queries return `null`?

**Comment by raghavsethi** [comment]
@nezihyigitbasi My understanding is that `try` and `try_cast` are intended to be runtime checks for bad data and are not intended to skip basic correctness checks. @martint do you agree with that assessment?

**Comment by haozhun** [comment]
IIRC, we decided to make `try` behave consistently.

My argument for differentiating `try_cast` for cast that exist and cast that doesn't is that doing so doesn't provide more expressive power. (If the user just wants a now, write NULL.) Given it will always be `NULL`, it's likely an error in user query.

**Comment by martint** [comment]
@raghavsethi, yes, that's the correct interpretation. Both functions are expected to fail when a cast between two types is not registered, since it's a function resolution/type inference error. 

We may want to improve the error message to make it clear it's about the cast not existing vs a given value not being convertible.
