### ISSUE TITLE
Bad error message when ORDER BY a table column shadowed by a field

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#6883]
The following query:
```
SELECT x.c as x
FROM (VALUES 1) x(c)
ORDER BY  x.c
```

Fails with:
```
Query 20161214_182133_00031_xsi4f failed: line 1:8: Expression "x"."c" is not of type ROW
com.facebook.presto.sql.analyzer.SemanticException: line 1:8: Expression "x"."c" is not of type ROW
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitDereferenceExpression(ExpressionAnalyzer.java:380)
```

and the CLI renders the SELECT line in red. However, the actual error is in the ORDER BY clause, the SELECT should have analyzed just fine

**Comment by cberner** [comment]
@sopel39 assigning this to you as I assume this is caused by your recent ORDER BY change

**Comment by martint** [comment]
Fixing this is a little tricky. It's a side-effect of analyzing the rewritten expression (which inlines the AST nodes from the select clause if there are any references). It requires analyzing the unmodified ORDER BY expressions using a sort of delegating scope (try with output scope first, delegate to source scope if a name cannot be resolved).

**Comment by martint** [comment]
It may be possible to do by creating a synthetic scope with the shape of the output scope and the source scope as its parent.

**Comment by sopel39** [comment]
I think it's due to `StatementAnalyzer::extractAggregates`, which extracts unrewritten sort keys from `QuerySpecification`, see: https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java#L1687.
Those sort keys should be rewritten to use projection output. I will test tomorrow if that's the issue and post some bugfix.

**Comment by martint** [comment]
It's because analyzeOrderBy analyzes the rewritten expression, which inlines the expressions from the select clause (including their "location").

**Comment by sopel39** [comment]
I think this can be fixed by not rewriting `DereferenceExpression` since it doesn't make sense to insert complex expression into `DereferenceExpression.base`.

**Comment by martint** [comment]
It's a broader problem. The rewrite causes other location information to be lost.

I have a tentative fix based on the approach I described above, but surprisingly, it breaks queries of the form:

```
SELECT ... AS a, ... AS a
FROM t
ORDER BY a
```

This is an interesting case, because it is technically ambiguous.

**Comment by martint** [comment]
The spec is actually pretty clear about it:

> When two elements with equivalent names are permitted, then the element name is ambiguous and attempts to reference either element by name will raise a syntax error.

**Comment by sopel39** [comment]
Scopes don't have information about expressions anymore, so they are not suitable for expression substituting, right?

The problem with location is that we want to fail with a proper message during order by expression analysis? If that's the case, then we could also pass some `location map` to analyzer that would override expression location.

It might also be possible to rewrite name references in substituted expression with proper location and add them to analysis. Maybe that's actually the cleanest solution?

**Comment by martint** [comment]
In the longer term, we should figure out how to make the analyzer no rewrite expressions. In the original design, the analyzer was supposed to just analyze the AST for correct semantics and annotate nodes with whatever information is needed for the planner. Any necessary manipulation of expressions for the purpose of creating a query plan is expected to happen during planning.
