### ISSUE TITLE
Refactor query test framework (unit tests)?

### ISSUE THREAD

**Issue by kokosing** [prestodb/presto#6910]
This issue is continuation of discussion from https://github.com/prestodb/presto/pull/6848#issuecomment-267527207.
It is going to collect all the problems we currently have with actual unit test framework (aka `AbstractTestQueries`) and check if we need a migration to some new test framework. Also it is going evaluate if we need migration from `testng` to `junit5`. 

Feel free to contribute!

I imagine that at some point this issue will be either:
 - closed as what we have now is good enough
 - or short design doc will be created with proposed solution and possible migration path

**Comment by kokosing** [comment]
1.  Currently we are not able to test features (or feature toggles). All the tests are run per each test setup which causes test redundancy and longer development cycle. Related signs are:
       - Connector specific tests run queries like `SELECT ... FROM (VALUES ...)` which do not use connector (do not read actual data). 
      - It is not possible to select tests which could cover only part of functionality. See https://github.com/prestodb/presto/commit/e1023ddd5402297d82ba07027bce1464a64d2996 test was running all the tests while it requires only test aggregation. This seems to be getting more importance as we are getting closer to the new optimizer and we will be changing query plans (like changing the join order).

**Comment by martint** [comment]
One of the big reasons AbstractTestQueries is so massive is that there's no way to make separate test classes depend on some state object (e.g., the query runner) that gets initialized once before all the tests run and gets torn down when the suite finishes.

**Comment by kokosing** [comment]
Another issue is that connector classes are not loaded in isolated class loaders, so it is not possible to test a connector which have dependencies conflict with presto-main. See https://github.com/prestodb/presto/pull/6995

**Comment by electrum** [comment]
A problem addressed by neither `testng` or `junit5` is how to do a test matrix. Today, we do it with inheritance, but that requires a child class for each matrix combination, so we end up with `N * X * Y * Z * ...` test classes (where `N` is the number of abstract base classes).

**Comment by electrum** [comment]
Something that does work today is to click on a test method in the IDE and select which child class to use to run the test. This feature is very important for developing.

**Comment by martint** [comment]
I'd like to move to a model where the connector tests are separated from the engine (analyzer/planner/execution) tests. A few ideas:
* Create a connector verification suite that exercises the connector APIs as the engine is supposed to use them
* Create a lightweight testing connector that exposes tables with various organizations and types that the engine supports and craft a set of queries that exercise each of the functions. Maybe we can leverage some of tempto's abilities to provide a query and expected resultset.
* Break up AbstractTestQueries into different functional areas, similar to how some of the logical planner tests are being structured. One of the reasons we haven't done this is that initializing the query runner is expensive, and there's no way to reuse it across multiple test classes. With a lighter-weight connector, this would be less of a problem.
