### ISSUE TITLE
Class  not found"...hdfs.DistributedFileSystem"

### ISSUE THREAD

**Issue by ffpeng90** [prestodb/presto#6915]
Hi,all:
   Recently, i am trying to write a new connector for presto, which will access some Files on HDFS which file format has not supported by hive. It always throws exception [java.lang.ClassNotFoundException: Class org.apache.hadoop.hdfs.DistributedFileSystem not found] when try to get fileSystem instance with code [path.getFileSystem()].

1. At the beginning, i thought the jar is missing, so i add  

groupId: org.apache.hadoop; artifactId: hadoop-hdfs; version: 2.2.0
groupId: org.apache.hadoop; artifactId: hadoop-common; version: 2.2.0

into connector pom.   However it does not work.  When Debugging, i can see  class "Path, FileSystem"  is linked to the jar "hadoop-common:2.2.0". And when loadFileSystems(), get nothing.   

2. Then i modify the pom according the pom file of Connector presto-raptor.  so i add 

groupId: com.facebook.presto.hive; artifactId: hive-apache
groupId: com.facebook.presto.hive; artifactId: hadoop-apache2

into pom.  I can see  class "Path, FileSystem"  is linked to the jar "xxx/.m2/repository/com/facebook/presto/hadoop/hadoop-apache2/0.8/hadoop-apache2-0.8.jar!/org/apache/hadoop/fs/Path.class" , but i still get the same exception. 

Is there any limitation on using hadoop-xxx.jar?  I cann't get the DistributedFileSystem instance in runtime  period by reflection.   But i can see the class file in IDE Intellij. 
Is there anyone offer me some advice?

**Comment by ffpeng90** [comment]
I modify my code according to this link(https://github.com/prestodb/presto/issues/4090),  And  Finally got FileSystem instance.  

However,  when i try to getFileStatus().  It throws EOFException like this:
`End of File Exception between local host is: "xxx/10.9.196.218"; destination host is: "10.2.26.92":9083; : java.io.EOFException; For more details see:  http://wiki.apache.org/hadoop/EOFException`

Is there Any advice?
 
i will log my progress on the page, for anyone who need it.

**Comment by ray6080** [comment]
To use Hadoop related jars, you can add this dependency into maven
com.facebook.presto.hadoop:hadoop-apache2:0.9
instead of adding apache hadoop as dependency directly. I did this before and it seems everything is fine.
