### ISSUE TITLE
Performance regression for OUTER JOINs

### ISSUE THREAD

**Issue by pnowojski** [prestodb/presto#6923]
Following simple query:

```
SELECT COUNT(*) FROM store_sales s FULL OUTER JOIN web_sales w 
  ON s.ss_item_sk = w.ws_item_sk 
 AND s.ss_sold_date_sk = w.ws_sold_date_sk;
```

has slowed down between versions 154 and 157 by the factor of 10. On 8 nodes cluster it was completing in ~60 seconds now it completes in over 540 seconds, with very low CPU usage (constant ~20% of 24 cores) regardless of the `task_concurrency`. It doesn't seem to be the problem with hash partitioning (https://github.com/prestodb/presto/pull/6864). From profiling it seems like the problem is with `OuterLookupSource.OuterPositionTracker#positionVisited` method (called from `PartitionedLookupSource#appendTo`) in which code spends ~90% of the time.

This code was changed recently by @dain here https://github.com/prestodb/presto/commit/4f0f9fae5611bbcb0632798a751adda0d9f40a62 
Previous version of `PartitionedLookupSource` didn't synchronize `visitedPositions[][]` array, but `OuterLookupSource` did synchronize it. Currently, both are synchronized.

From profiling it looks like synchronization/locking prevents query from utilizing more CPU. I didn't have time to look deeper into this code, but is this synchronization absolutely required? Has something else changed recently in this area?

CC @KBP-TDC

**Comment by dain** [comment]
IIRC, this was part of a big fix for parallel outer joins with filter functions where we were getting incorrect results when you had called stateful functions.  If the position tracking needs to have concurrent access also, would need to do something like have each reader track positions separately and then merge them together in the end.

**Comment by KBP-TDC** [comment]
Thanks @pnowojski for identifying the root cause.
@martint @dain Could you guys please offer some insights here?

**Comment by dain** [comment]
@KBP-TDC see above

**Comment by sopel39** [comment]
@dain Why synchronization is needed for visited position tracking? IIRC, join operators are partitioned, so they should mark different positions in boolean array. Concurrent, unsynchronized writes to Java array are OK according to: http://stackoverflow.com/questions/8978191/java-concurrency-writing-to-different-indexes-of-the-same-array.

CC: @losipiuk

**Comment by pnowojski** [comment]
@sopel39, @losipiuk it is needed. First of all, only build side is hash partitioned. Probe side is not, so every joining thread can write to all `visitedPositions` in all partitions.

Secondly, as far as I understand memory and thread model in Java, even if that wasn't the case, you still need to pass make those writes visible between threads. Quoting from your link:

> However you need to synchronize a write/read to the same index if you want to make sure the consumer thread sees the last value written by the producer thread.

If you have one thread writing values to some array and you want those values to be visible by second thread, first thread after finishing writes has to make (encounter?) a memory barrier (like entering `synchronized` section).

Having said that, actually writes doesn't have to be synchronized here, because all threads starting with `boolean[][] vistedPositions` filled with `false`, and there is only one type of write access - setting some position to `true`. Since we don't care about write orders, there is no need for synchronization of those writes - even if they touch same array position. However, before reading those values from some different threads, all writing threads need to encounter memory barrier.

I have code that exactly does that (unsychronzed writes, synchronized commit), but I'm trying to make one `checkState` to work, which is surprisingly difficult.

**Comment by dain** [comment]
@martint what is your take on the proposed synchronization above?

**Comment by pnowojski** [comment]
Fixed
