### ISSUE TITLE
incorrect number of rows returned by quantified predicate 

### ISSUE THREAD

**Issue by the6campbells** [prestodb/presto#6932]
presto release 0.160

query using a quantified predicate is not returning the expected number of rows

in the following example, tjoin2 has four rows and derived table returns 0 rows

query expected to return 4 rows but returns 0 rows

select 1  from postgres_cert.public.tjoin2 where 5 > all 
	( select 1 from postgres_cert.public.tjoin1 where 1 = 0 )

**Comment by akshatnair** [comment]
this query seems to be incorrect as well, it should return 0 rows
`select regionkey from region where 5 > ALL (select 0 union select null);`
 regionkey 
-----------
         0 
         1 
         2 
         3 
         4

**Comment by kokosing** [comment]
CC: @ArturGajowy Seems to be related to https://github.com/prestodb/presto/issues/6653

**Comment by martint** [comment]
Duplicate. Closing.
