### ISSUE TITLE
Partial aggregation push down optimizer rewrite

### ISSUE THREAD

**Issue by kokosing** [prestodb/presto#6938]
For plans for queries like
```
SELECT max(nationkey), min(nationkey) 
FROM region r, nation n 
WHERE r.regionkey = n.regionkey
```

can be rewritten  from
```                                                                                                                                                                                               
     - Aggregate()                                                                                                     
              max_13 := "max"("nationkey")                                                                                     
              min_14 := "min"("nationkey")                 
           - InnerJoin[("regionkey" = "regionkey_1")
             - TableScan[tpch:tpch:region]                       
             - TableScan[tpch:tpch:nation]
```
to
```                                                                                                                                                                                               
     - Aggregate()                                                                                                     
              max_15 := "max"("max_13")                                                                                     
              min_16 := "min"("min_14")                 
           - InnerJoin[("regionkey" = "regionkey_1")
             - TableScan[tpch:tpch:region]                                                                                                                          
             - Aggregate()  GROUP BY regionkey                                                                                                
                      max_13 := "max"("nationkey")                                                                                     
                      min_14 := "min"("nationkey")                       
                - TableScan[tpch:tpch:nation]
```

Thanks to above rewrite join build table is expected to be smaller and hence there is expectation that query should be executed faster.

Any thoughts? Is all the above correct? Am I missed something?

CC: @rschlussel @pnowojski

**Comment by kokosing** [comment]
It may affect subqueries performance as it is typical that subquery rewrites adds aggregation on top of join.

**Comment by pnowojski** [comment]
I think this can not be a general rule that can be applied every time. It heavily depends on number of distinct values for key column in both probe and build table. 

Generally speaking IMO this should wait for betters stats and cost calculator, so that rewriter could intelligently choose between those two plans.

**Comment by KBP-TDC** [comment]
To generalize this case, I would add predicates since it would expose a trade-off of doing pre-aggregation early rather then after a potentially selective join. And, yes, as @pnowojski mentioned above, looking at NDVs of join keys and grouping keys is important.

**Comment by akshatnair** [comment]
I think this is applicable to only some aggregate functions not all.

**Comment by rschlussel** [comment]
I believe you can use partial aggregations for most of the aggregate functions, but they're not all as simple as count/sum/min/max.  e.g. there are parallel algorithms for standard deviation and variance, where you compute partial aggregations on the various bits, but it's not just computing the stddev on the subset and combining those values.
