### ISSUE TITLE
inconsistency in decimal support

### ISSUE THREAD

**Issue by the6campbells** [prestodb/presto#6942]
connectors such as mysql and postgres both will describe/project decimal columns as double
meanwhile decimal type is listed as supported in presto and would be returned from both postgres and mysql drivers connecting directly

select  cdec, cast(1 as decimal(1))  from postgres_cert.public.tdec

ColumnIndex	getColumnName	getColumnTypeName	getPrecision	getScale	isNullable	getTableName	getSchemaName	getCatalogName	getColumnClassName	getColumnDisplaySize	getColumnLabel	getColumnType	isAutoIncrement	isCaseSensitive	isCurrency	isDefinitelyWritable	isReadOnly	isSearchable	isSigned	isWritable
1	cdec	DOUBLE	17	0	2				java.lang.Double	24	cdec	8	false	false	false	false	true	true	true	false
2	_col1	DECIMAL(1,0)	0	0	2				java.math.BigDecimal	0	_col1	3	false	false	false	false	true	true	false	false

Presto describe of table

Column	Type	Comment
rnum	integer	
cdec	double	

MySql
ColumnIndex	getColumnName	getColumnTypeName	getPrecision	getScale	isNullable	getTableName	getSchemaName	getCatalogName	getColumnClassName	getColumnDisplaySize	getColumnLabel	getColumnType	isAutoIncrement	isCaseSensitive	isCurrency	isDefinitelyWritable	isReadOnly	isSearchable	isSigned	isWritable
1	rnum	INT	11	0	0	tdec		dbcert	java.lang.Integer	11	rnum	4	false	false	false	true	false	true	true	true
2	cdec	DECIMAL	7	2	1	tdec		dbcert	java.math.BigDecimal	9	cdec	3	false	true	false	true	false	true	true	true

Postgres
ColumnIndex	getColumnName	getColumnTypeName	getPrecision	getScale	isNullable	getTableName	getSchemaName	getCatalogName	getColumnClassName	getColumnDisplaySize	getColumnLabel	getColumnType	isAutoIncrement	isCaseSensitive	isCurrency	isDefinitelyWritable	isReadOnly	isSearchable	isSigned	isWritable
1	rnum	int4	10	0	0				java.lang.Integer	11	rnum	4	false	false	false	false	false	true	true	true
2	cdec	numeric	7	2	1				java.math.BigDecimal	9	cdec	2	false	false	false	false	false	true	true	true

**Comment by dain** [comment]
The decimal type is very new and not fully enabled yet.  Once it is, we will update the other connectors to support it.

**Comment by the6campbells** [comment]
might help if the release notes/docs could identify where support is partial as new types are introduced. 

i.e. https://prestodb.io/docs/current/language/types.html and has a general statement re connectors and the connector pages themselves say nothing specific i.e. https://prestodb.io/docs/current/connector/mysql.html
