### ISSUE TITLE
issues casting value expressions  to TIME WITH TIME ZONE or TIMESTAMP WITH TIME ZONE

### ISSUE THREAD

**Issue by the6campbells** [prestodb/presto#6945]
https://prestodb.io/docs/current/language/types.html
https://prestodb.io/docs/current/functions/conversion.html

time with time zone and timestamp with time zone are not accepted target types for cast expression

i.e. 

select  cast(c1 as time with time zone)  from ( values ('01:02:03.456 -05:00') ) T (c1)

Error: Query failed (#20161221_233527_00091_bvv36): line 1:9: Cannot cast varchar(19) to time with time zone
SQLState:  null
ErrorCode: 1

select  cast(c1 as timestamp with time zone)  from mysql_cert.dbcert.tsdchar where rnum=12
-but- forcing type case to varchar will work
select  cast(cast(c1 as varchar(27)) as timestamp)  from mysql_cert.dbcert.tsdchar where rnum=12

Error: Query failed (#20161221_234349_00104_bvv36): line 1:9: Cannot cast char(27) to timestamp with time zone
SQLState:  null
ErrorCode: 1

**Comment by fiedukow** [comment]
Thanks for report.
It looks like VARCHAR(x) -> TIME WITH TIME ZONE cast is missing. It looks like a bug. I'll try to fix it together with #7122.

As for casting from CHAR(x) -> TIME(STAMP). Presto does not support implicit casts for explicit cast argument. This seems like a bug but I have to confront that with SQL standard first.
