### ISSUE TITLE
Query optimizer generates incorrect plans for some logical expressions

### ISSUE THREAD

**Issue by ggreg** [prestodb/presto#6954]
Reproduce with:
```
select (a=8 or b=2) and (a=8 or c=3) or (b=9) from (values (1, 2, 3)) as t (a, b, c);
```

`(a=8 or b=2) and (a=8 or c=3)` should become `a=8 or (b=2 and c=3)`. The query optimizer turns it into `a=8 and (b=2 and c=3)`

**Comment by ggreg** [comment]
I added this test case to `testExtractsCommonPredicate`:

```java
assertSimplifies("((A OR B) AND A) OR D", "(A AND B) OR D");
```

The result is:

```
Expected :("d" OR ("a" AND "b"))
Actual   :("a" OR "d")
```

**Comment by ggreg** [comment]
I added the test case below to `testExtractsCommonPredicate`:

```java
assertSimplifies("((A or B) and (A or C)) or D", "A or (B and C) or D");
```

And the output is:

```
Expected :(("b" AND "c") OR ("a" OR "d"))
Actual   :("d" OR ("c" AND ("a" AND "b")))
```

**Comment by kokosing** [comment]
@sopel39 can you take a look at this, I think you have a context with this part of optimizer
