### ISSUE TITLE
maximum aggregate of time type returning incorrect value 

### ISSUE THREAD

**Issue by the6campbells** [prestodb/presto#6963]
Version: 0.160

The expected projected value is  23:59:30 and not the returned value of 12:00:00

select max( vtm.ctm ) from postgres_cert.public.vtm 

source data 
rnum	ctm
0	<null>
1	00:00:00
2	12:00:00
3	23:59:30

describe of table 

Column	Type	Comment
rnum	integer	
ctm	time

**Comment by fiedukow** [comment]
I'll try to reproduce that.

**Comment by ArturGajowy** [comment]
@fiedukow did you manage? :)

**Comment by fiedukow** [comment]
Yes. 
It seems to be caused by https://github.com/prestodb/presto/issues/7122
Closing as this new ticket describes underlying problem much better.

**Comment by the6campbells** [comment]
The discussion thread #7122 seems to about Presto and timestamp and time zone semantics. Was not clear how that ties into incorrect aggregation of a TIME type. Please review and reopen as applicable.

**Comment by fiedukow** [comment]
`time` semantic is aligned with `timestamp` semantic.
`time with time zone` semantic is aligned with `timestamp with time zone` semantic.

As such, time (w/o TZ) does apply use timezone to the value. The semantic may differ between connectors as well. Maybe I closed this a little bit to early as this may also be connected to wrong behaviour on PostgreSQL connector side. I think that this should be retested after fixing semantic in Presto though, as check on Presto side is definitely required to fix other problems properly.

Sorry for closing that to early. Leaving open and assigning to myself as I'm going to dive into `TIMESTAMP` problem now.
