### ISSUE TITLE
cannot cast ( <sd> as <interval-type>)

### ISSUE THREAD

**Issue by the6campbells** [prestodb/presto#6964]
Version: 0.160

Online documentation does not list a supported cast matrix.
https://prestodb.io/docs/current/functions/conversion.html

Attempting to cast to an interval type fails
https://prestodb.io/docs/current/language/types.html

i.e. select cast(1  as interval year) from postgres_cert.public.tversion
Error: Query failed (#20161224_143722_00066_ztdeg): line 1:28: extraneous input 'year' expecting {')', 'ARRAY'}
SQLState:  null
ErrorCode: 1

**Comment by findepi** [comment]
fixed by #9350
