### ISSUE TITLE
Running Presto on MapR

### ISSUE THREAD

**Issue by bhgames** [prestodb/presto#6971]
Hello,

I tried installing Presto on a MapR VirtualBox single-node test cluster. When trying to select from a hive table, I got this:

Query 20161227_220444_00001_zk96j failed: No FileSystem for scheme: maprfs

I suppose I should not be surprised. Is there any support for MapRFS, or is there some kind of workaround where I can treat an NFS mountpoint to the MapRFS as a normal file system or something?

Thanks.

**Comment by akshatnair** [comment]
Currently there is no support for MapR. Check this pull request that was submitted sometime ago https://github.com/prestodb/presto/pull/1669
Work is in progress to get Presto working on MapR
