### ISSUE TITLE
JDBC driver returns 0 for precision and displaysize for projected character value expressions

### ISSUE THREAD

**Issue by the6campbells** [prestodb/presto#6975]
Various vendors will return a precision and display size for the projected column and expression applied to the column. Presto is returning no precision or display size information for a column reference or character value expression. 

**Presto JDBC**
ColumnIndex	getColumnName	getColumnTypeName	getPrecision	getScale	isNullable	getTableName	getSchemaName	getCatalogName	getColumnClassName	getColumnDisplaySize	getColumnLabel	getColumnType	isAutoIncrement	isCaseSensitive	isCurrency	isDefinitelyWritable	isReadOnly	isSearchable	isSigned	isWritable
1	cchar	CHAR(32)	0	0	2				java.lang.String	0	cchar	1	false	false	false	false	true	true	false	false
2	_col1	VARCHAR(32)	0	0	2				java.lang.String	0	_col1	-16	false	false	false	false	true	true	false	false

**Teradata Presto JDBC**

ColumnIndex	getColumnName	getColumnTypeName	getPrecision	getScale	isNullable	getTableName	getSchemaName	getCatalogName	getColumnClassName	getColumnDisplaySize	getColumnLabel	getColumnType	isAutoIncrement	isCaseSensitive	isCurrency	isDefinitelyWritable	isReadOnly	isSearchable	isSigned	isWritable
1	cchar	CHAR(32)	32	0	1				java.lang.String	32	cchar	1	false	false	false	false	true	true	false	false
2	_col1	VARCHAR(32)	32	0	1				java.lang.String	32	_col1	12	false	false	false	false	true	true	false	false

Describe of referenced table

Column	Type	Comment
rnum	integer	
cchar	char(32)

**Comment by electrum** [comment]
This sounds easy to fix. Do you have a test or example code so I can be sure I'm understanding the problem?

**Comment by the6campbells** [comment]
Something like the following should show the problem.

ResultSet rs = stmt.executeQuery("select c1, upper(c1) from ( values (cast('AAAAA' as char(5)))) t1 (c1) ");	
ResultSetMetaData rsMd = rs.getMetaData();

	for (int i=1; i <= rsMd.getColumnCount(); i++){
			System.out.println(
					String.format(
							"Column Name:%s, display size:%d, type name:%s, type id:%d, precision:%d, scale:%d",
							rsMd.getColumnName(i),
							rsMd.getColumnDisplaySize(i),
							rsMd.getColumnTypeName(i),
							rsMd.getColumnType(i),
							rsMd.getPrecision(i),
							rsMd.getScale(i)
							)
					);
		}

**Comment by delding** [comment]
Filling meta data info into `PrestoResultSet` is not implemented yet, working on it
