### ISSUE TITLE
in-list with decimal types fails with object.getClass (class java.lang.Long) and type.getJavaType (double) do not agree

### ISSUE THREAD

**Issue by the6campbells** [prestodb/presto#6984]
When the in-list has decimal values with different precision the exception is thrown 

i.e. ok
SELECT 
	c1,
	case when c1 in ( decimal '2.0', decimal '3.0'   ) then 'a' else 'b' end
FROM ( values ( cast (1 as double) ) ) T (c1)

i.e. fails
SELECT 
	c1,
	case when c1 in ( decimal '2.0', decimal '30.0'   ) then 'a' else 'b' end
FROM ( values ( cast (1 as double) ) ) T (c1)

**Comment by cawallin** [comment]
Fixed by #7211
