### ISSUE TITLE
Aggregate before join for simple correlated scalar subqueries

### ISSUE THREAD

**Issue by rschlussel** [prestodb/presto#6988]
Correlated scalar subqueries currently get rewritten to a left outer join followed by an aggregation with a grouping on all the columns from the left table, followed by a filter.   When the join condition is an equality join condition in conjunctive normal form, we can instead perform the aggregation before the join, and group by the join keys.  

Example:
```
SELECT *
FROM nation n1
WHERE (n1.nationkey > (
      SELECT avg(nationkey)
      FROM nation n2
      WHERE n1.regionkey=n2.regionkey)
```

Currently
we would do
```
- Filter ("nationkey" > "avg")
    - Aggregate(Group by: all columns from the left talbe, aggregation: avg("n2.nationkey"))
         - LeftJoin("regionkey" = "regionkey")
             - Add unique id (nation)
                  - Tablescan (nation)
              - Tablescan (nation)
```

Instead we could aggregate before the join.
```
- Filter ("nationkey" > "avg")
         - LeftJoin("regionkey" = "regionkey")
             - Tablescan (nation)
             - Aggregate(Group by: regionkey, aggregation: avg(nationkey))
                  - Tablescan (nation)
```

Thoughts?

@kokosing @sopel39

**Comment by rschlussel** [comment]
I didn't do rigorous benchmarking, but when I manually rewrote tpc-ds q1 this way , and ran it locally on 1gb, it went from ~4m to ~20s

**Comment by kokosing** [comment]
Wow! Nice speedup! Sounds like low hanging fruit. Would you like to
implement this? If no I can take care of this.

No comments from me, LGTM.

pt., 30.12.2016, 19:33 użytkownik Rebecca Schlussel <
notifications@github.com> napisał:

I didn't do rigorous benchmarking, but when I manually rewrote tpc-ds q1
this way , and ran it locally on 1gb, it went from ~4m to ~20s

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/prestodb/presto/issues/6988#issuecomment-269805849>,
or mute
the thread

**Comment by rschlussel** [comment]
I can work on it

**Comment by sopel39** [comment]
>Correlated scalar subqueries currently get rewritten to a left outer join followed by an aggregation with a grouping on all the columns from the left table, followed by a filter.

In order to remove aggregation it's not enough that it groups on all the columns from the left table. Additionally rows from left table have be unique. Otherwise left rows cardinality would change.

**Comment by kokosing** [comment]
If it is just for subquery it should work. Also it does not need
AssignUniqueId node on the left side, which was used to preserve
cardinality. No grouping after join, means that cardinality will not be
affected.

pt., 30.12.2016, 22:56 użytkownik Karol Sobczak <notifications@github.com>
napisał:

**Comment by kokosing** [comment]
In regards of implementation, I think you should based your work on https://github.com/prestodb/presto/pull/6920, where there is a commit which extract `NodeDecorelator`  (see https://github.com/prestodb/presto/pull/6920/commits/ecf50cb503dd28ccea8b2712eee80fa1acdd41370. Alternatively you could just use this commit. Then your rewrite rule is going to be very similar to `TransformCorrelatedScalarAggregationToJoin`.

**Comment by sopel39** [comment]
>If it is just for subquery it should work. Also it does not need AssignUniqueId node on the left side, which was used to preserve cardinality. No grouping after join, means that cardinality will not be affected.

Yes, but you could easily make the rule work in generic case (e.g: when join left input is unique). To determine uniqueness you can just write some simple visitor (similar to the one that determines is plan is scalar).

`AssignUniqueId` can be removed by `PruneUnreferencedSymbols`, when `AssignUniqueId` is not needed anymore when top grouping is removed.

**Comment by kokosing** [comment]
+1

sob., 31.12.2016, 10:47 użytkownik Karol Sobczak <notifications@github.com>
napisał:

**Comment by kokosing** [comment]
We can do it two steeps - iteratively. First support in subquery, then make
it generic. Up to Rebecca.

sob., 31.12.2016, 10:57 użytkownik Grzegorz Kokosiński <
g.kokosinski@gmail.com> napisał:

**Comment by rschlussel** [comment]
@sopel39 How would we know in the general case if rows are unique when we don't enforce any constraints on the data?  The only other case I can think of is if the left side is the result of a group by.

**Comment by sopel39** [comment]
@rschlussel indeed group by and `AssignUniqueId` provide uniqueness trait.

**Comment by sopel39** [comment]
@rschlussel There might also be other nodes (e.g: `set union`, `RowNumberNode`). You have to check node classes.
