### ISSUE TITLE
Implement EXPLAIN (TYPE VALIDATE)

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#7017]
Validates that the given statement is a validate SQL query, returns "TRUE" if it is a validate query, or may fail with an exception.

The implementation should be as cheap as possible, in particular we should avoid running any potentially expensive optimizations.

Example:
```
EXPLAIN (TYPE VALIDATE) SELECT 1
> TRUE
```

```
EXPLAIN (TYPE VALIDATE) SELECT * FROM my_secret_table
```

(exception, assuming "my_secret_table" is one that the user doesn't have access to)

**Comment by martint** [comment]
> The implementation should be as cheap as possible, in particular we should avoid running any potentially expensive optimizations.

In fact, it should not do any planning or optimization. It should only run through the analyzer.
