### ISSUE TITLE
Error during analysis in GROUP BY query with array function filter

### ISSUE THREAD

**Issue by hzzz823** [prestodb/presto#7021]
i want to get non null element in groupby result
`select filter(array_agg(addr), x->x is not null) from table1 group by name`

and get error
`Query 20170107_072818_00132_w2332 failed: aggregation analysis not yet implemented for: com.facebook.presto.sql.tree.LambdaExpression
`

**Comment by martint** [comment]
I believe this is a duplicate of https://github.com/prestodb/presto/issues/6834. What version are you running? It should be fixed in 0.161.

**Comment by hzzz823** [comment]
thank you! 😯
