### ISSUE TITLE
string function replace(string, search, replace) 

### ISSUE THREAD

**Issue by hzzz823** [prestodb/presto#7023]
select name from table1;
result is:
1
2
3

but select replace('1', name, 'a') from table1;
result is:
a
1
1

and select replace('1', name) from table1;
result is:

1
1

why all column except column equals 'a' be replaced by '1'  ...🤔

**Comment by martint** [comment]
When you do `replace('1', name, 'a')`, you're asking to replace any occurrences of the value of the `name` column in the string `1` with the character `a`. So:

```
name = '1'  ->  replace('1', '1', 'a')  -> 'a'
name = '2'  ->  replace('1', '2', 'a')  -> '1' (since '1' does not contain any '2')
name = '3'  ->  replace('1', '3', 'a')  -> '1' (since '1' does not contain any '3')
```

The form `replace('1', name)` is equivalent to `replace('1', name, '')`
