### ISSUE TITLE
Presto can't execute simple Tableau "custom sql" query that contains count(*)

### ISSUE THREAD

**Issue by brian-rickman** [prestodb/presto#7035]
I’m playing with Tableau, and when I use the “custom sql” feature it wraps my query as a sub-select with a limit…

Custom SQL:
```
SELECT count(*) from tpch.sf100.lineitem
```

Tableau generated query:
```
SELECT 1 AS "number_of_records",
"custom_sql_query"."_col0" AS "xcol0"
FROM (
SELECT count(*) from tpch.sf100.lineitem
) "custom_sql_query"
LIMIT 100000
```

I am running Presto 0.162 with Teradata patches.

Presto error:
```
[Teradata][Presto] (1060) Presto Query Error: line 2:3: Column 'custom_sql_query._col0' cannot be resolved (1)
```

Further research uncovered what I think is a Presto bug: the generated name for the inner query’s aggregation is not available to the outer query.  

```
presto:default> SELECT count(*) from tpch.sf1.lineitem;
  _col0
---------
6001215
(1 row)

presto:default> SELECT 1 AS "number_of_records", "custom_sql_query".* FROM ( SELECT count(*) from tpch.sf1.lineitem ) "custom_sql_query" LIMIT 100000; 

number_of_records |  _col1
-------------------+---------
                 1 | 6001215
(1 row)

presto:default> SELECT 1 AS "number_of_records", "custom_sql_query"._col0 FROM ( SELECT count(*) from tpch.sf1.lineitem ) "custom_sql_query" LIMIT 100000; 
Query 20170109_170144_00074_gb74w failed: line 1:34: Column 'custom_sql_query._col0' cannot be resolved SELECT 1 AS "number_of_records", "custom_sql_query"._col0 FROM ( SELECT count(*) from tpch.sf1.lineitem ) "custom_sql_query" LIMIT 100000

presto:default> SELECT 1 AS "number_of_records", "custom_sql_query"._col1 FROM ( SELECT count(*) from tpch.sf1.lineitem ) "custom_sql_query" LIMIT 100000; 
Query 20170109_163718_00069_gb74w failed: line 1:34: Column 'custom_sql_query._col1' cannot be resolved SELECT 1 AS "number_of_records", "custom_sql_query"._col1 FROM ( SELECT count(*) from tpch.sf1.lineitem ) "custom_sql_query" LIMIT 100000

presto:default> SELECT 1 AS "number_of_records", "custom_sql_query"._col0 FROM ( SELECT count(*) as _col0 from tpch.sf1.lineitem ) "custom_sql_query" LIMIT 100000; 

number_of_records |  _col0
-------------------+---------
                 1 | 6001215
(1 row)

```

**Comment by kokosing** [comment]
I tested the tableau generated query on postgres and it does not work there either:

```
postgres=# SELECT "custom_sql_query"."_col0" FROM ( SELECT count(*) from (SELECT 1) x) "custom_sql_query" ;
ERROR:  column custom_sql_query._col0 does not exist
LINE 1: SELECT "custom_sql_query"."_col0" FROM ( SELECT count(*) fro...
```

Can you please test the tableau custom query with connection to postgres, to see if it works and if so what query is generated for postgres?

Anyway, the generated names in postgress are accessible by outer queries, see:
```
postgres=# SELECT * FROM ( SELECT count(*) from (SELECT 1) x) "custom_sql_query" ;                          
 count 
-------
     1
(1 row)

postgres=# SELECT "custom_sql_query"."count" FROM ( SELECT count(*) from (SELECT 1) x) "custom_sql_query" ;
 count 
-------
     1
(1 row)
```

I think it would nice to have it working in Presto. 

It might be possible that Tableau is using some Jdbc Metadata to access column names which then are used in generated queries

**Comment by brian-rickman** [comment]
Connecting Tableau to Postgres and using the custom query `select count(*) from test` works fine.  Will post the generated query when I figure out how to get the PG log from the docker container.

**Comment by martint** [comment]
Columns that are derived from complex expressions don't have a name, so they can't be referenced from the outer query. The name _col0 is not a real name. It's only created for display purposes.

**Comment by kokosing** [comment]
Would tableau work with Presto for you if you would use following query:
```
SELECT count(*) as count from tpch.sf100.lineitem
```

**Comment by brian-rickman** [comment]
Yes, Tableau works fine with Presto as long as an alias is assigned to the aggregate column.

**Comment by etiennegoldstein** [comment]
Yes, I've seen this with Tableau/Presto as well. All columns need to have a name.
