### ISSUE TITLE
Unable to escape equal sign (=) in like statement

### ISSUE THREAD

**Issue by eklicious** [prestodb/presto#7057]
The following statements do not work.

SELECT * FROM [table] WHERE SEGMENT like '%= $75K'
SELECT * FROM [table] WHERE SEGMENT like '%\\= $75K' ESCAPE '\\'

Strangely, this statement also doesn't work when I remove the equal sign and leave the blank space.
SELECT * FROM [table] WHERE SEGMENT like '% $75K'

But this statement does work when I remove the equal sign and blank space.
SELECT * FROM [table] WHERE SEGMENT like '%$75K'

**Comment by dain** [comment]
The equals sign (`=`) is not a special character in a like expression and does not need to be escaped.   Regardless both version work:
```
> SELECT 'foo=$75K' LIKE '%=$75K';
 _col0 
-------
 true  

SELECT 'foo=$75K' LIKE '%\=$75K' escape '\';
 _col0 
-------
 true  
```
