### ISSUE TITLE
Improve performance of getting results by parallelizing download

### ISSUE THREAD

**Issue by AlekseiS** [prestodb/presto#7061]
Currently all query results are downloaded via a single channel from a coordinator to a client. As a result, queries downloading large amounts of data can take a long time because of the limited throughput. Also, it adds pressure on the coordinator.
The goal of this task is to increase download throughput by downloading results in parallel from worker nodes.

**Comment by AlekseiS** [comment]
Implement ArbitraryOutputBuffer which will be used by the last shuffle stage: https://github.com/prestodb/presto/pull/7029

**Comment by AlekseiS** [comment]
New ArbitraryOutputBuffer implementation which supersedes the previous version: https://github.com/prestodb/presto/pull/7080

**Comment by findepi** [comment]
Note that this change will impact deployment architecture. Currently, only the coordinator needs to be exposed to the client. This is important when client and presto cluster live in different networks, so it's not just impl detail.

While I'm all for such a change, when introduced, it might require a config switch.
