### ISSUE TITLE
Support "array by table subquery" constructor

### ISSUE THREAD

**Issue by martint** [prestodb/presto#7066]
From the spec:

```
<array value constructor> ::=
    <array value constructor by enumeration>
  | <array value constructor by query>

<array value constructor by query> ::=
  ARRAY <table subquery>
```

> 3) If `<array value constructor by query>` is specified, then
> a) The `<query expression>` QE simply contained in the `<table subquery>` shall be of degree 1 (one). Let
`ET` be the declared type of the column in the result of `<query expression>`.
> b) The declared type of the `<array value constructor by query>` is array with element type `ET` and maximum
cardinality equal to the implementation-defined maximum cardinality IMDC for such array types.

> 3) The result of `<array value constructor by query>` is determined as follows:
> a) `QE` is evaluated, producing a table `T`. Let `N` be the number of rows in `T`.
> b) If `N` is greater than `IMDC`, then an exception condition is raised: data exception — array data, right truncation.
> c) The result of `<array value constructor by query>` is an array of `N` elements such that for all i, 1 (one) ≤ `i` ≤ `N`, the value of the `i-th` element is the value of the only column in the `i-th` row of `T`.
> NOTE 167 — The ordering of the array elements is effectively determined by the General Rules of Subclause 7.13, “`<query expression>`”.

In simple terms,

```sql
SELECT ARRAY (SELECT x FROM t)
```

is equivalent to

```sql
SELECT (SELECT array_agg(x) FROM t)
```

**Comment by kokosing** [comment]
@findepi it is nice subquery related task, maybe you would like to take it next sprint?
