### ISSUE TITLE
CLI: when last line had multiple statements, arrow up recalls last command instead of last line

### ISSUE THREAD

**Issue by findepi** [prestodb/presto#7098]
### steps to reproduce

* In CLI, run two statements in one line, e.g. `SET SESSION reorder_joins=true; SET SESSION join_distribution_type = 'automatic';`
* press arrow up `↑` key

### expected

* last line recalled, so that I can edit it and re-execute

### observed

* last statement recalled

**Comment by electrum** [comment]
This is intended behavior. We save each command as a separate history item. This allows easily repeating a previous query, even if it was originally on multiple lines.

**Comment by findepi** [comment]
@electrum, sure for multi-line statements recalling whole last statement would be _the_ expected behavior.
The case I meant was when the line contains multiple statements, all within that line.

Compare the CLI's behavior to what bash shows after `echo 1; echo 2; <ENTER><UP>`. Or postgresql's CLI after `select 1; select 2; <ENTER><UP>`.

**Comment by electrum** [comment]
What happens if you have a multi line statement and the last line contains multiple statements? The only consistent behavior is to put statements in the history, not lines.

**Comment by findepi** [comment]
Well, I am not the one to judge. I think there should be some kind of 'established practice for CLIs' that should be followed.

**Comment by electrum** [comment]
The alternative is to put the original lines into the history as a single item when the first complete statement is found. This is what psql seems to do. However, I'm not sure jline supports that. If it does, that could be an improvement over the current behavior.
