### ISSUE TITLE
Set LastAccessTime in Hive metastore when executing query

### ISSUE THREAD

**Issue by drdee** [prestodb/presto#7126]
The Hive Metastore has support for tracking when a table was accessed by storing a timestamp. Setting this information makes it easier to manage large datawarehouses and detect tables that are no longer being queried. 

https://github.com/apache/hive/blob/master/ql/src/java/org/apache/hadoop/hive/ql/hooks/UpdateInputAccessTimeHook.java shows how it's used by Hive itself.

**Comment by dain** [comment]
Isn't this something the metastore should be doing?

**Comment by AhmedKamal** [comment]
@drdee Any updates regarding this issue ?
