### ISSUE TITLE
Raptor: AssignmentLimiter incorrectly handles multiple unavailable nodes

### ISSUE THREAD

**Issue by ggreg** [prestodb/presto#7136]
- [x] Fix injected `AssignmentLimiter` constructor that calls `this(nodeSupplier, ticker, config.getReassignmentDelay(), config.getReassignmentDelay());` rather than `this(nodeSupplier, ticker, config.getReassignmentDelay(), config.getReassignmentInterval());`
- [x] Ensure all offline nodes are marked as soon as they are discovered offline. With the current implementation, `AssignmentLimiter.checkAssignFrom()` throws an exception when one node is either within the reassignment delay or reassignment throttling. As a consequence the loop in `DatabaseShardManager.loadBucketAssignments()` does not go through the subsequent offline node and `AssignmentLimiter.delayedNodes` has no entry for these other offline nodes. This shifts the delay for these nodes and make the cluster unavailable for queries longer than expected.
- [ ] Control concurrency of recovery: once the nodes are marked offline, the number of buckets to recover at the same time should be configurable. This can be expressed as a maximum read (or read/write/delete) throughput that the backup storage can support. This would supersede the action of the reassignment throttling that limits the number of bucket per time period to recover.

**Comment by ggreg** [comment]
cc @electrum @erichwang

**Comment by ggreg** [comment]
@jessesleeping did you already address some of this points?

**Comment by jessesleeping** [comment]
The first two points were fixed a while ago. 

For the third one, right now the recovery concurrency control are done implicitly in the following ways:
(1) `storage.max-recovery-threads` control the total number of threads used in recovery
(2) `backup.timeout` plus the internal retry in implementation of `BackupStore`. `BackupStore` can backoff on overloaded and Raptor will keep waiting until the total time of a request exceed the configured timeout. 

We don't have a explicit way to throttle the backup store based on bandwidth or qps right now.
