### ISSUE TITLE
CTE with INSERT

### ISSUE THREAD

**Issue by bdm123** [prestodb/presto#7138]
Is there support for the following HiveQL statement or similar without creating intermediate tables?

WITH q1 AS (SELECT key, value FROM src WHERE key = '5') 
   FROM q1 INSERT INTO s1 SELECT *;

**Comment by martint** [comment]
Yes, but the syntax would be:

```
INSERT INTO s1
WITH q1 AS (...)
SELECT * FROM q1
```

**Comment by haozhun** [comment]
INSERT INTO s1
WITH q1 AS (SELECT key, value FROM src WHERE key = '5')
SELECT * FROM q1;

In addition, I would like to point out that Presto does not materialize CTEs right now. It is subject to change.
