### ISSUE TITLE
Raptor: expose restful endpoint to control background services

### ISSUE THREAD

**Issue by ggreg** [prestodb/presto#7141]
We experienced cases when we needed to trigger Raptor background services such as compaction and local shard cleaning with Raptor. All these services run at fixed interval. The goal here is to provide an interface to control them from external processes.

One way to implement that, is through restful endpoint for each service among:

- Local Shard Cleaner
- Backup Shard Cleaner
- Shard Compactor
- BucketBalancer
- Shard RecoveryManager

What would be the format of endpoints? For example:
- /local_shard_cleaner/state and then use a verb to update the expected state of the service
- State is one of `running` or `stopped` and there is also *stats* about objects from the last run, for example `bucket_assignments`, `nb_available_nodes`, etc...

[edited] Options are:
- System tables
- JMX
- Rest is not possible without adding an interface to expose connector-specific endpoints

**Comment by ggreg** [comment]
cc @electrum @erichwang @raghavsethi

**Comment by martint** [comment]
Presto doesn't currently have any mechanism to expose connector-specific functions via the HTTP interface. This is a much larger discussion than what the names of the endpoints should be.

One possible way to approach this is by exposing the data through system tables or connector-specific functions.

**Comment by ggreg** [comment]
System tables sound good as they are easy to query and discover. We also talked about using JMX.
