### ISSUE TITLE
Migrate BeginTableWrite to iterative optimizer

### ISSUE THREAD

**Issue by kokosing** [prestodb/presto#7171]

**Comment by alandpost** [comment]
Martin says:  "BeginWriteTable is a total hack. It’s doing something that should really be part of a “begin query”/“end query” lifecycle. See the comments at the top of that class....  It needs to be part of the query execution (after analysis and planning is done)....  It shouldn’t be migrated to the iterative optimizer.  We should think about how to extend query lifecycle to inject these hooks and how to pass the additional information to workers, etc."
