### ISSUE TITLE
Migrate MergeWindows to iterative optimizer

### ISSUE THREAD

**Issue by kokosing** [prestodb/presto#7175]

**Comment by maciejgrzybek** [comment]
PR: https://github.com/Teradata/presto/pull/495.
Will be started against prestodb/presto once https://github.com/prestodb/presto/pull/7300 is merged.

**Comment by amrutagokhale** [comment]
prestodb PR here: https://github.com/prestodb/presto/pull/7817

**Comment by amrutagokhale** [comment]
Closing this, since https://github.com/prestodb/presto/pull/7817 was merged.
