### ISSUE TITLE
Add support for MapR

### ISSUE THREAD

**Issue by petroav** [prestodb/presto#7189]
For background on previous work see https://github.com/prestodb/presto/pull/1658 and https://github.com/prestodb/presto/pull/1669.

This issue tracks the work needed to get MapR support for Presto on par with that for HDP and CDH. We plan on bundling and shading the MapR dependencies like we do for other Hadoop distros. For this purpose I've created this project: https://github.com/Teradata/presto-hadoop-mapr5.

So far we've managed to query data in MapR FS with minimal code changes (mostly around configuration, nothing in the engine itself). We also built a docker container with MapR and are currently trying to run all the Presto product tests on MapR to see if any queries won't work.

**Comment by petroav** [comment]
@dain and @rsilvery: I'm including the list of dependencies (and their corresponding licenses) that we are pulling in.

| Dependency | Version | Type | License | Notes |
| ------------ | -------- | ----- | -------- | ------ |
| org.apache.hadoop:hadoop-core | 1.0.3-mapr-5.2.0 | compile | Apache 2.0 | |	
| com.mapr.hadoop:maprfs | 5.2.0-mapr | compile | Proprietary | |
| com.google.protobuf:protobuf-java | 2.5.0 | compile | BSD 2-clause | |
| org.json:json | 20080701 | compile | JSON License | MIT with additional line "The Software shall be used for Good, not Evil" |
| xerces:xercesImpl | 2.9.1 | compile | Apache 2.0 | |
| xml-apis:xml-apis | 1.3.04 | compile | Apache 2.0 | |
| xalan:xalan | 2.7.1	compile | Apache 2.0 | |
| xalan:serializer | 1.14 | compile | Apache 2.0 | |
| org.yaml:snakeyaml | 1.2 | compile | Apache 2.0 | |
| org.apache.hadoop:hadoop-common | 3.1.1 | compile | Apache 2.0 | |
| org.apache.hadoop:hadoo-annotations | 2.7.0-mapr-1607 | compile | Apache 2.0 | |
| jdk.tools:jdk.tools | 1.8 | system | Your JDK's license | This just comes with the JDK | |
| com.google.guava:guava | 14.0.1 | compile | Apache 2.0 | |
| commons-cli:commons-cli | 1.2 | compile | Apache 2.0 | |
| org.apache.commons:commons-math3 | 3.1.1 | compile | Apache 2.0 | |
| xmlenc:xmlenc | 0.52 | compile | BSD 2-clause | |
| commons-httpclient:commons-httpclient | 3.1 | compile | Apache 2.0 | |
| commons-codec:commons-codec | 1.4 | compile | Apache 2.0 | |
| commons-io:commons-io | 2.4 | compile | Apache 2.0 | |
| commons-net:commons-net | 3.1 | compile | Apache 2.0 | |
| commons-collections:commons-collections | 3.2.2 | compile | Apache 2.0 | |
| commons-lang:commons-lang | 2.6 | compile | Apache 2.0 | |
| commons-configuration:commons-configuration | 1.6 | compile | Apache 2.0 | |
| commons-digester:commons-digester | 1.8 | compile | Apache 2.0 | |
| org.codehaus.jackson:jackson-core-asl | 1.9.13 | compile | Apache 2.0 | |
| org.codehaus.jackson:jackson-mapper-asl | 1.9.13 | compile | Apache 2.0 | |
| com.google.code.gson:gson | 2.2.4 | compile | Apache 2.0 | |
| org.apache.curator:curator-client | 2.7.1 | compile | Apache 2.0 | |
| org.apache.curator:curator-recipes | 2.7.1 | compile | Apache 2.0 | |
| org.apache.htrace:htrace-core | 3.1.0 | compile | Apache 2.0 | |
| org.apache.zookeeper:zookeeper | 3.4.5-mapr-1503 | compile | Apache 2.0 | |
| og.apache.commons:commons-compress | 1.4.1 | compile | Apache 2.0 | |
| org.tukaani:xz | 1.0 | compile | Public Domain | |
| org.apache.hadoop:hadoop-auth | 2.7.0-mapr-1607 | compile | Apache 2.0 | |
| org.apache.httpcomponents:httpclient | 4.2.5 | compile | Apache 2.0 | |
| org.apache.httpcompoenents:httpcore | 4.2.4 | compile | Apache 2.0 | |
| org.apache.directory.server:apacheds-kerberos-codec | 2.0.0-M15 | compile | Apache 2.0 | |
| org.apache.directory.server:apacheds-i18n | 2.0.0-M15 | compile | Apache 2.0 | |
| org.apache.directory.api:api-asn1-api | 1.0.0-M20 | compile | Apache 2.0 | |
| org.apache.directory.api:api-util | 1.0.0-M20 | compile | Apache 2.0 | |
| org.apache.curator:curator-framework | 2.7.1 | compile | Apache 2.0 | |
| commons-daemon:commons-daemon | 1.0.1 | compile | Apache 2.0 | |
| org.mortbay.jetty:servlet-api-2.5 | 6.1.4 | compile | CDDL 1.0 | |
| org.eclipse.jdt:core | 3.1.1 | compile | Eclipse Public License v1.0 | |
| oro:oro | 2.0.8 | compile | Apache 1.1 | |
| org.mortbay.jetty:jetty-servlet-tester | 6.1.14 | compile | Apache 2.0 | |
| org.mortbay.jetty:jetty | 6.1.14 | compile | Apache 2.0 | |
| org.mortbay.jetty:jetty-util | 6.1.14 | compile | Apache 2.0 | |
| org.aspectj:aspectjrt | 1.6.5 | compile | Eclipse Public License v1.0 | |
| net.java.dev.eval:eval | 0.5 | compile | Apache 2.0 | |
| org.testng:testng | 6.2.1 | test | Apache 2.0 | |
| junit:junit | 3.8.1 | test | Common Public License Version 1.0 | |
| org.beanshell:bsh | 2.0b4 | test | Sun Public License/ LGPL | BeanShell is dual licensed under both the SPL and LGPL. You may use and develop BeanShell under either license. |
| com.beust:jcommander | 1.12 | test | Apache 2.0 | |
| org.slf4j:jcl-over-slf4j | 1.7.13 | runtime | MIT | https://www.slf4j.org/license.html |
| org.slf4j:log4j-over-slf4j | 1.7.13 | runtime | Apache 2.0 | The SLF4J website says all binaries are distributed under MIT license (see link above), but this jar says it's under Apache 2.0 |
| org.sf4j:slf4j-api | 1.7.13 | runtime | MIT | |
| org.slf4j:sl4j-nop | 1.7.13 | runtime | MIT | |

For completeness' sake I included all dependencies, even the ones that don't get packaged up (runtime & test). This list was obtained by running `mvn dependency:tree` in the [presto-hadoop-mapr5](https://github.com/Teradata/presto-hadoop-mapr5) project, whose artifact is then a dependency of the MapR connector. @dain can you confirm that this is the right way to identify the dependencies we're pulling and that I'm not missing something.

I'm not familiar with all the licenses here but it seems like almost everything is Apache 2.0 and there are no GPL licensed jars that we package. I'm also not sure if this is the minimum required set of dependencies so it may be possible for us to shade more. It looks like the only thing we need permission for is the `maprfs` jar.

**Comment by l1x** [comment]
Does anybody know what is the status of this as of now?
