### ISSUE TITLE
not able to run any command in Hadoop HA Cluster

### ISSUE THREAD

**Issue by gouravbhalla22** [prestodb/presto#7202]
hi 

i am getting below error while running any command.any idea.

[hadoop@namenode logs]$ hadoop dfs -mkdir /input
DEPRECATED: Use of this script to execute hdfs command is deprecated.
Instead use the hdfs command for it.

-mkdir: java.net.UnknownHostException: ha-cluster
Usage: hadoop fs [generic options] -mkdir [-p] <path> ...

thanks
Gourav Bhalla

**Comment by cawallin** [comment]
Hello, this seems like a Hadoop issue rather than a Presto issue, please ask your question either on StackOverflow or in some Hadoop-specific forum. (To venture a guess, you might not have all of the requisite Hadoop HA configs specified)
