### ISSUE TITLE
Presto does not see some data from Cassandra

### ISSUE THREAD

**Issue by JanDoerrenhaus** [prestodb/presto#7206]
I have the table datamart_hourly_total_sessions, with a column called "time_extract__" as its partitioning key.

When I do the following query on the Cassandra side, in CQL, I get 230 results:
`select distinct time_extract__ from datamart_hourly_total_sessions;`

Doing the same query in presto, I get the same 230 results. Both in cassandra and in presto, one of the returned values is `2017-01-17`.

If I then do the following query on the Cassandra side, I get results, and on the presto side, I get no results:
`select * from datamart_hourly_total_sessions where time_extract__ = '2017-01-17';`

So essentially, presto will confirm (with the first query) that there are values for that key, but then ignore them when querying for them. Restarting the entire presto cluster helps, it will then 'see' the data, but that's not a solution. My guess would be some kind of caching issue..?

PS: I am on Presto 0.150, but I don't think anything regarding this has been changed recently?

**Comment by cawallin** [comment]
It's a matter of caching/partition loading. When you do the query for a single value, it tries to locate the partition in the cache, but if the cache is out of date, it won't return anything. Try adjusting ``cassandra.schema-cache-ttl`` and/or ``cassandra.schema-refresh-interval``. (See the note also in this PR: https://github.com/prestodb/presto/pull/6794/files)
