### ISSUE TITLE
Generate consecutive JOINs in one loop

### ISSUE THREAD

**Issue by idemura** [prestodb/presto#7216]
Instead of several scanners (LookupJoinOperator) and page builders in between to produce pages, we will have one loop with several lookups generated. With Teradata change merging projection into merge this will bring significant performance difference (especially on wide rows).

**Comment by sopel39** [comment]
Could you provide some (short) design doc about the idea? This will make it easy to discuss aspects about the solution. There are some potential issues like projections or other nodes between consecutive joins. It's often not obvious that projection should be pushed down through join (it might be up to optimizer to decide).

> With Teradata change merging projection into merge this will bring significant performance difference (especially on wide rows).

What did you mean in this sentence?

**Comment by idemura** [comment]
Let me experiment first. Idea is to avoid page builders when we have several joins in chain. Sometimes projections can happen in between so teradata work will help to make this more generic.

**Comment by Praveen2112** [comment]
What if there is a filter in between the joins ? This will be similar to a whole stage code generation for query (as in Spark and hyperDB). In case of distributed environment  we generate a code for a entire task ( having only a single operator which consumes the input and gives the output for each task). This change could bring a significant improvement in performance.

**Comment by sopel39** [comment]
We did some Wholestage compilation in Presto experiments. Presentation link is here: https://docs.google.com/presentation/d/1OTC_2oD61cxNUa7HTm4aDXVGCGpisvYOXHjMrLA_sp0/edit#slide=id.p
For 8 consecutive joins we got 2x speedup with multiple joins compiled into one operator, so definitely there is place for improvement.

**Comment by Praveen2112** [comment]
@sopel39 That's super cool....Was the code generated on a task level or on the query level(Single task and Single operator excluding the LookupSource)......

**Comment by sopel39** [comment]
@Praveen2112 only operators that supported wholestage were compiled into single operator (I guess query level). In our case it was `ProjectNode`, `JoinNode` and `FilterNode`.

**Comment by Praveen2112** [comment]
@sopel39 If it was at a query level only a single task will be created or multiple tasks ?
You could also include > TopNNode .
Correct me If I am wrong , If we generate it at a task level (Input or Exchange Client -> Operator -> Output Buffer) then we could achieve parallel execution of various splits.

**Comment by sopel39** [comment]
Ah, right. It was task level then. It basically compiled multiple operators into single `Operator` class. This compiled operator is treated like every other operator (e.g: `LookupJoinOperator`) therefore it is parallelized on task level.

**Comment by Praveen2112** [comment]
Ok.You could also try incorporating `TopNNode` along with `ProjectNode` and others. For generating code for a task we could create a `PlanVisitor` which visits all the node of a plan for the above task. Each node would generate a code for its associated operation. At Terradata was it implemented in this way ?

**Comment by highker** [comment]
resolved by https://github.com/prestodb/presto/pull/8629
