### ISSUE TITLE
How does Presto pass SQL logical operators like 'OR' 'And' to connector?

### ISSUE THREAD

**Issue by hong-zhu** [prestodb/presto#7219]
I'm building a Presto Connector. When I try to build native query, it looks like Presto doesn't pass down SQL logical operators to connector. For instance:

`SELECT * FROM listings 
WHERE (created_date >= timestamp '2015-01-01' and
       created_date <= timestamp '2015-02-01')
   OR (created_date >= timestamp '2015-03-01' and
       created_date <= timestamp '2015-04-01')`

How do I know it's 'OR' or 'And' operator for these 2 ranges above?

**Comment by haozhun** [comment]
Presto pass down `com.facebook.presto.spi.predicate.TupleDomain`. It can represent something like

```
(a > 5 AND a < 10) OR a = 15 OR (a > 30)
AND
b != 20
```

It cannot represent `a = 1 OR b = 2`.

It cannot represent `a > 0 AND b > 0 AND a + b < 10`. But it can represent `(a > 0 AND a < 10) AND (b > 0 AND b < 10)`.

**Comment by hong-zhu** [comment]
@haozhun I can not find any api in TupleDomain for me to get the operator information.
I need to know, for two conditions, whether they are connected by 'OR' or 'And' in TupleDomain or somewhere else.

**Comment by electrum** [comment]
It should get pushed down as a domain with two ranges. If I run this query against the Hive connector:
```sql
EXPLAIN
SELECT * FROM hive_table
WHERE ds BETWEEN '2016-01-01' AND '2016-01-05'
   OR ds BETWEEN '2016-01-10' AND '2016-01-15';
```
We see that predicate pushdown works correctly:
```
ds := HiveColumnHandle{...}                                                                      
    :: [[2016-01-01], [2016-01-02], [2016-01-03], [2016-01-04], [2016-01-05], [2016-01-10], [2016-01-11], [2016-01-12], [2016-01-13], [2016-01-14], [2016-01-15]]                                           
```

**Comment by hong-zhu** [comment]
@electrum Thank you for your help.
I can get the values in two ranges from TupleDomain, it's ok. 
My problem is by the time my native query builder receive TupleDomain, it seems there is no way to know if it's 'OR' or 'And' for these 2 ranges. 
Can I assume for any column in where clause, if there are 2 ranges in TupleDomain, it's a 'OR" SQL operator?
