### ISSUE TITLE
Not able to query Tweets from Kafka Topic in Presto 

### ISSUE THREAD

**Issue by balaji-krishnan72** [prestodb/presto#7230]
Hi
Versions
  Presto - .163
  Kafka - 2.10-0.8.2.2

I have a 3 node Hadoop cluster and run Kafka and Presto on top of that. I am unable to query Tweets  through Presto. While it can describe tweets table, but every time when i query it comes back with ZERO rows. Independently, if i use 

./bin/kafka\-console\-consumer.sh --zookeeper localhost:2181 --topic jsontweets --from-beginning 

i can see data in the topic.

presto:kafka> describe jsontweets;
      Column       |  Type   | Extra |                   Comment
-------------------+---------+-------+---------------------------------------------
 _partition_id     | bigint  |       | Partition Id
 _partition_offset | bigint  |       | Offset for the message within the partition
 _segment_start    | bigint  |       | Segment start offset
 _segment_end      | bigint  |       | Segment end offset
 _segment_count    | bigint  |       | Running message count per segment
 _key              | varchar |       | Key text
 _key_corrupt      | boolean |       | Key data is corrupt
 _key_length       | bigint  |       | Total number of key bytes
 _message          | varchar |       | Message text
 _message_corrupt  | boolean |       | Message data is corrupt
 _message_length   | bigint  |       | Total number of message bytes
(11 rows)

presto:kafka> select count(*) from jsontweets;
 _col0
-------
     0
(1 row)

At times i also get the following error
presto:kafka> select count(*) from jsontweets;
Query 20170126_060559_00019_e44py failed: null

My kafka.properties file looks like the following
connector.name=kafka
kafka.nodes=192.168.xxx.xxx:9092,192.168.xxx.xxx:9092,192.168.xxx.xxx:9092
kafka.table-names=kafka.jsontweets
kafka.hide-internal-columns=false

Thanks so much

Bala

**Comment by erikbeebe** [comment]
Hi Bala,

If you didn't already - try changing your table name in kafka.properties from 'kafka.jsontweets' to 'jsontweets' - that's likely the issue.

Cheers
Erik
