### ISSUE TITLE
Error parsing decimal using RCFile Text

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#7250]
With
```
set session hive.rcfile_optimized_reader_enabled = false;
```

following may occur

```
java.lang.ArithmeticException: Rounding necessary
java.math.BigDecimal.commonNeedIncrement(BigDecimal.java:4148)
java.math.BigDecimal.needIncrement(BigDecimal.java:4204)
java.math.BigDecimal.divideAndRound(BigDecimal.java:4112)
java.math.BigDecimal.setScale(BigDecimal.java:2452)
java.math.BigDecimal.setScale(BigDecimal.java:2386)
com.facebook.presto.spi.type.Decimals.rescale(Decimals.java:259)
com.facebook.presto.hive.ColumnarTextHiveRecordCursor.parseDecimalColumn(ColumnarTextHiveRecordCursor.java:507)
com.facebook.presto.hive.ColumnarTextHiveRecordCursor.parseDecimalColumn(ColumnarTextHiveRecordCursor.java:495)
com.facebook.presto.hive.ColumnarTextHiveRecordCursor.parseColumn(ColumnarTextHiveRecordCursor.java:625)
com.facebook.presto.hive.ColumnarTextHiveRecordCursor.isNull(ColumnarTextHiveRecordCursor.java:583)
com.facebook.presto.hive.HiveCoercionRecordCursor.isNull(HiveCoercionRecordCursor.java:150)
com.facebook.presto.hive.HiveRecordCursor.isNull(HiveRecordCursor.java:237)
com.facebook.presto.spi.RecordPageSource.getNextPage(RecordPageSource.java:107)
com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:256)
com.facebook.presto.operator.Driver.processInternal(Driver.java:378)
com.facebook.presto.operator.Driver.processFor(Driver.java:301)
com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:555)
com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:691)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)

**Comment by findepi** [comment]
I observed that
* with `hive.rcfile_optimized_reader_enabled=false` we currently get `ArithmeticException: Rounding necessary`
* with `hive.rcfile_optimized_reader_enabled=true` we currently get `IllegalStateException: Read decimal value scale larger than column scale`
* whereas Hive reads the values (rounds `HALF_UP`)

What is the expected behavior in Presto? Does the _expected_ behavior depend on the `hive.rcfile_optimized_reader_enabled` flag?

(FWIW, similar problem arises when reading `varchar(n)`. `com.facebook.presto.hive.ColumnarTextHiveRecordCursor#parseStringColumn(int, byte[], int, int)` truncates input to `n` characters.)

@electrum, @martint, @sopel39, @losipiuk

**Comment by sopel39** [comment]
One node: `presto-orc` is also used in Raptor, so any semantics change to `presto-orc` will also change behavior how raptor reads the data.

**Comment by dain** [comment]
Was this file written with one schema and then is being read with another schema?

**Comment by findepi** [comment]
@dain, I can't tell how it was originally, but yes, this is how I reproduce this issue:

* In hive, create RC table with `string` column, fill it with some decimals
* in hive, create RC table with `decimal(p,s)` column, load the first table's data file as data for the new table
* query the table from hive and presto

**Comment by findepi** [comment]
@dain, @electrum, @martint, what's the expected behavior in this issue?

**Comment by electrum** [comment]
Both Presto readers should produce the same result as Hive does when reading the table.

**Comment by findepi** [comment]
@electrum i realized there is also a similar problem when value stored in text has too many digits before the decimal point (as compared to _after the dot_, as discussed so far). I understand that both old and new reader should return `NULL` just as Hive does (today both throw an exception).
