### ISSUE TITLE
Request for supporting SSE-KMS 

### ISSUE THREAD

**Issue by chappidmAWS** [prestodb/presto#7264]
Currently, Presto supports SSE ([hive.s3.sse.enabled](https://prestodb.io/docs/0.157/connector/hive.html)) w.r.t AES256
It would be nice if it supports SSE-KMS where a customer can specify the [kms-key-id](http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingKMSEncryption.html) for SSE.
Like, hive.s3.sse.kms-key-id

**Comment by electrum** [comment]
We support `hive.s3.kms-key-id` which is used to create `KMSEncryptionMaterialsProvider` (Java SDK). Is this what you're looking for?

**Comment by electrum** [comment]
You can see all the S3 properties for the Hive connector here: https://prestodb.io/docs/current/connector/hive.html#s3-configuration-properties

**Comment by chappidmAWS** [comment]
Thank you for your quick response.
I am afraid, that's not my use-case.
Ref : http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingKMSEncryption.html

> "When you upload an object, you can specify the KMS key using the x-amz-server-side-encryption-aws-kms-key-id header. If the header is not present in the request, Amazon S3 assumes the default KMS key. Regardless, the KMS key ID that Amazon S3 uses for object encryption must match the KMS key ID in the policy, otherwise Amazon S3 denies the request."

Implies the [putObjectRequest](https://github.com/prestodb/presto/blob/master/presto-hive/src/main/java/com/facebook/presto/hive/PrestoS3FileSystem.java#L985-L990)  will be 
`PutObjectRequest putRequest = new PutObjectRequest(bucketName,
   keyName, file).withSSEAwsKeyManagementParams(new SSEAwsKeyManagementParams(keyID));`
Currently` hive.s3.kms-key-id` is used for [ClientSideEncryption](https://github.com/prestodb/presto/blob/master/presto-hive/src/main/java/com/facebook/presto/hive/PrestoS3FileSystem.java#L643-L669)

**Comment by electrum** [comment]
I see, thanks for clarifying. This looks easy to do, but I wouldn't have a way to test it. Do you want to send a pull request to add this?

**Comment by chappidmAWS** [comment]
#7276
