### ISSUE TITLE
Presto 0.165 Could not execute a query with a join

### ISSUE THREAD

**Issue by jabonillomelvin** [prestodb/presto#7280]
```
Query 20170202_085543_00004_cu622 failed: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
```

I got this error every time I query with a join but If I run a single table query it works fine.

Can anyone please help me what is the problem? I have a 1 coordinator and 1 worker

**Comment by zhaoshengbo** [comment]
show your sql please.

**Comment by jabonillomelvin** [comment]
Hi @zhaoshengbo 

If I run the query without a worker the query works fine but if the query was with a worker it doesn't.

```
SELECT
       COUNT(Lesson.id) as opened,
       SUM(CASE WHEN Book.cancel_flag_by_teacher = 1 THEN 1 ELSE 0 END) as cancel,
       SUM(CASE WHEN Book.cancel_flag_by_teacher = 0 THEN 1 ELSE 0 END) as booked
FROM
       lesson AS Lesson
               LEFT JOIN (
                        SELECT
                            id,
                            lesson_id,
                            cancel_flag_by_member,
                            cancel_flag_by_teacher,
                            lesson_note_penalty_flag,
                            no_show
                        FROM book
                        WHERE cancel_flag_by_member = 0
                    ) Book
                    ON Lesson.id = Book.lesson_id
                 WHERE Lesson.scheduled_start_datetime BETWEEN date_parse('" . $from_datetime . "', '%Y-%m-%d %H:%i:%s') AND date_parse('" . $to_datetime . "', '%Y-%m-%d %H:%i:%s')
                    AND Lesson.delete_flag = 0
                 GROUP BY Lesson.teacher_id
```

even a simple query like this
```
SELECT COUNT(*) from lesson;
```

**Comment by zhaoshengbo** [comment]
do you run the query from presto-cli?
show me the error message please.

**Comment by KBP-TDC** [comment]
@jabonillomelvin the initial error ("Could not create connection to database server") indicates that you may have restrictions on accessing your MySQL instance from some Presto nodes. Please make sure that all nodes is your cluster are allowed to ping your MySQL machine.

**Comment by jabonillomelvin** [comment]
Hi @zhaoshengbo,

```
MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up
```

this is the error

**Comment by jabonillomelvin** [comment]
@KBP-TDC 

I can see that my worker is active
```
     select * from system.runtime.nodes;
               node_id                |         http_uri         | node_version | coordinator | state  
--------------------------------------+--------------------------+--------------+-------------+--------
 92146eda-e916-11e6-aeba-83ae8b0c4f5a | http://172.17.10.33:8080 | 0.165        | false       | active 
 23S3hk7N-1N43-P098-Hnn2-12BVx34lK19  | http://172.17.10.16:8080 | 0.165        | true        | active 

```

There are times that the query will run but almost of the time the query will error 
```
MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up
```

**Comment by jabonillomelvin** [comment]
If I will stop the worker, no problem occurred, so what I think is in the worker side which I can not figure out why

**Comment by zhaoshengbo** [comment]
@jabonillomelvin you can execute `telnet mysql_ip_address port` at the  worker node , maybe your worker node can't connect the mysql.

**Comment by jabonillomelvin** [comment]
@zhaoshengbo I cannot telnet the mysql_ip_address but I can ping

**Comment by zhaoshengbo** [comment]
show the telnet error message

**Comment by jabonillomelvin** [comment]
@zhaoshengbo 
```
telnet: Unable to connect to remote host: Connection refused
```

**Comment by zhaoshengbo** [comment]
something wrong with your mysql configuration 
http://serverfault.com/questions/139323/mysql-bind-to-more-than-one-ip-address

**Comment by jabonillomelvin** [comment]
@zhaoshengbo I can now telnet my mysql_ip_address but still cannot create database server

**Comment by zhaoshengbo** [comment]
grant remote privilege to the user who connect the mysql at the worker node

**Comment by rschlussel** [comment]
If you have more questions about using Presto with MySQL, you can ask on the the presto users group.  presto-users@googlegroups.com
