### ISSUE TITLE
INSERT creating new Hive table partition uses wrong field delimiters for text format

### ISSUE THREAD

**Issue by bdm123** [prestodb/presto#7301]
Hi - When running INSERT INTO a hive table as defined below, it seems Presto is writing valid data files. However running subsequent SELECTs on the table will return all NULL values. When running the SELECT in Hive, the same files are read and displayed correctly.  Is this a known/fixed bug or is there an issue with my table definition? I'm running Presto 0.152.3. 

```
CREATE TABLE `test`(
  `d` timestamp,
  `a` string,
  `b` string,
  `c` string
)
PARTITIONED BY (
  `p` string)
ROW FORMAT SERDE
  'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES (
  'field.delim'='\t',
  'line.delim'='\n',
  'serialization.format'='\t')
STORED AS INPUTFORMAT
  'org.apache.hadoop.mapred.TextInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION
  's3://bucket'
TBLPROPERTIES (
  'serialization.null.format'=''
)

```

Thanks

**Comment by bdm123** [comment]
More details of the issue


1) Initial INSERT reads returns NULL values

```
presto> insert into test select TIMESTAMP '2016-12-01', 'a','b','c','p';
INSERT: 1 row
presto> select * from test;
  d   |  a   |  b   |  c   | p
------+------+------+------+---
 NULL | NULL | NULL | NULL | p

```
2) Second INSERT returns NULL for first row but reads new row correctly
```
presto> insert into test select TIMESTAMP '2016-12-01', 'a','b','c','p';
INSERT: 1 row
presto> select * from test;
            d            |  a   |  b   |  c   | p
-------------------------+------+------+------+---
 NULL                    | NULL | NULL | NULL | p
 2016-12-01 00:00:00.000 | a    | b    | c    | p

```

**Comment by ebyhr** [comment]
I reproduced latest Presto build. This is just FYI, It seems that this issue occurs when you specify new partition as the value.

```
presto:default> insert into test2 select TIMESTAMP '2016-12-01', 'a','b','c','a';
INSERT: 1 row

Query 20170208_030953_00002_ieepu, FINISHED, 1 node
Splits: 51 total, 51 done (100.00%)
0:03 [0 rows, 0B] [0 rows/s, 0B/s]

presto:default> select * from test2;
            d            |  a   |  b   |  c   | p 
-------------------------+------+------+------+---
 NULL                    | NULL | NULL | NULL | p 
 2016-12-01 00:00:00.000 | a    | b    | c    | p 
 NULL                    | NULL | NULL | NULL | a 
 2016-12-01 00:00:00.000 | a    | b    | c    | p 
 2016-12-01 00:00:00.000 | a    | b    | c    | p 
(5 rows)

Query 20170208_030959_00003_ieepu, FINISHED, 1 node
Splits: 21 total, 21 done (100.00%)
0:02 [5 rows, 210B] [2 rows/s, 98B/s]

presto:default> insert into test2 select TIMESTAMP '2016-12-01', 'a','b','c','b';
INSERT: 1 row

Query 20170208_031015_00004_ieepu, FINISHED, 1 node
Splits: 51 total, 51 done (100.00%)
0:04 [0 rows, 0B] [0 rows/s, 0B/s]

presto:default> select * from test2;
            d            |  a   |  b   |  c   | p 
-------------------------+------+------+------+---
 2016-12-01 00:00:00.000 | a    | b    | c    | p 
 NULL                    | NULL | NULL | NULL | p 
 2016-12-01 00:00:00.000 | a    | b    | c    | p 
 NULL                    | NULL | NULL | NULL | a 
 NULL                    | NULL | NULL | NULL | b 
 2016-12-01 00:00:00.000 | a    | b    | c    | p 
(6 rows)

Query 20170208_031021_00005_ieepu, FINISHED, 1 node
Splits: 22 total, 22 done (100.00%)
0:02 [6 rows, 252B] [2 rows/s, 125B/s]
```

I could confirmed following create definition.
```sql
CREATE TABLE test2(
d timestamp,
a string,
b string,
c string
)
PARTITIONED BY (p string)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES (
'field.delim'='\t',
'line.delim'='\n',
'serialization.format'='\t')
```

**Comment by ankitdixit** [comment]
I tried to debug this issue in code and found out that the value of feild.delim  is not being passed correctly in the case of first insert in a partition.
In MetastoreUtil file, getHiveSchema() method is called which is picking its Storage schema and serde parameters by eventually making a getschema for partition call which does not have information about table delimiters, hence it tried to use default delimiters and returns null when it fails to read the value.

**Comment by ebyhr** [comment]
Nice found @ankitdixit ! Are you going to send the Pull Request?

**Comment by ankitdixit** [comment]
@ebyhr raising one

**Comment by ankitdixit** [comment]
Looking some more, i found out that the issue is presto does not use field delimiters specified while creating a table if there is not data in the partition. The first insert is done using default delimiters and subsequently the read fails.

**Comment by gcassarini** [comment]
Hi,
I found the same behaviour in presto version 0.170. Is it possible?

Thanks

**Comment by bdm123** [comment]
This has been open for awhile. Should probably be flagged as a bug by one of the guys?

**Comment by Kuntal-G** [comment]
I also faced similar issue of getting Null value through Presto select query every time, i'm inserting data into hive partitioned table from presto (happens only for new partition only):

> CREATE EXTERNAL TABLE ext1 (string_col STRING, int_col INT)
PARTITIONED BY (vdate BIGINT)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
COLLECTION ITEMS TERMINATED BY ','
LINES TERMINATED BY '\n'
LOCATION 's3://[path_to_table]/ext1/';

> insert into ext1 values('test01', 1, 20170530);

 string_col | int_col |  vdate   
------------+---------+----------
 test01 1   | NULL    | 20170530


> insert into ext1 values('test01', 2, 20170530);

 string_col | int_col |  vdate   
------------+---------+----------
 test01 1   | NULL   | 20170530 
 test01     |      2 | 20170530

**Comment by alexey-kotlyar** [comment]
Just to confirm, experiencing the same issue on Presto 0.189. Seems like only text format is affected, recreating the target table with ORC storage format resolved the issue for me.

**Comment by ebyhr** [comment]
FYI, Started preparing PR to this issue.
