### ISSUE TITLE
source building error

### ISSUE THREAD

**Issue by zhangshuyu** [prestodb/presto#7317]
I met some errors when building presto.

> [ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.1.13:revision (default) on project presto-spi: .git directory could not be found! Please specify a valid [dotGitDirectory] in your pom.xml -> [Help 1]

I just download "https://github.com/prestodb/presto/archive/0.165.zip" and run the  command(mvn clean install -DskipTests) from the project root directory, then it happened.
I can't find any config files about "git-commit-id-plugin".
What should I do？Someone help me？

**Comment by electrum** [comment]
We don't support those zip files. GitHub creates them automatically and you can't turn them off. Please clone th repository instead. You can checkout the tag for a specific version.
