### ISSUE TITLE
Create one source of truth for query progress

### ISSUE THREAD

**Issue by fbertsch** [prestodb/presto#7340]
Currently, query progress is calculated as either: % of Drivers Completed [0], or % of Splits Completed [1]. The JDBC driver exposes splits [2], along with some other stats, so consumers could do what they like with those.

It would be nice if there were a centralized source of truth about query progress. This information could then be exposed to any services that need query progress. This way improvements could be made to the progress bars (hint, hint) and would be beneficial to all.

[0] https://github.com/prestodb/presto/blob/c73359fe2173e01140b7d5f102b286e81c1ae4a8/presto-main/src/main/resources/webapp/assets/query.js#L814
[1] https://github.com/wenleix/presto/blob/ca9e478b6942bf8e58ce4de8f065c1df61731009/presto-cli/src/main/java/com/facebook/presto/cli/StatusPrinter.java#L218
[2] https://github.com/prestodb/presto/blob/3c17fd330a54906ab7ba33b04a8c6de628280af6/presto-jdbc/src/main/java/com/facebook/presto/jdbc/QueryStats.java#L40

**Comment by raghavsethi** [comment]
@fbertsch I agree, this should be fixed.

**Comment by fbertsch** [comment]
I think I'll go ahead and take this one then :)

**Comment by raghavsethi** [comment]
@fbertsch There's an outstanding PR on the web UI, so I would wait a couple of days until that lands.

**Comment by fbertsch** [comment]
@raghavsethi, got a link?

**Comment by raghavsethi** [comment]
https://github.com/prestodb/presto/pull/7270

**Comment by raghavsethi** [comment]
You can start now :)

**Comment by fbertsch** [comment]
Perfect! Thanks!

**Comment by electrum** [comment]
This will also help with the rule that we can't compute progress until the query is fully scheduled (the "scheduled" flag is true). So this new field should be null / missing until then.

(If you compute it before then, it quickly reaches 99% and stays there)

**Comment by raghavsethi** [comment]
Merged #7662.
