### ISSUE TITLE
Improve memory performance for MAP_UNION and MAP_AGG

### ISSUE THREAD

**Issue by wenleix** [prestodb/presto#7342]
When most aggregation keys are different, we have found in some cases `MAP_UNION` can take up to 4x memory compared with `ARRAY_AGG`. One potential reason could be `TypedSet` is not quite memory efficient.

A microbenchmark:
- Create the dataset:
```
CREATE TABLE  test_id_and_map AS 
SELECT id, MAP(ARRAY [1], ARRAY [id]) as m
FROM
(
  select sequence(1, 10000000) AS seq
) tmp
CROSS JOIN UNNEST(seq) AS t(id)
```

- The queries:
```
CREATE TABLE test_map_union AS
SELECT id, MAP_UNION(m) AS m_agg
FROM test_id_and_map
GROUP BY id
```

vs.

```
CREATE TABLE test_array_agg AS
SELECT id, ARRAY_AGG(m) AS m_agg
FROM test_id_and_map
GROUP BY id
```

The peak memories for this case are 7.07G and 2.38G, respectively.

**Comment by wenleix** [comment]
Several potential places that `KeyValuePairs` might use a lot memory:
- The default `EXPECTED_ENTRIES` and `EXPECTED_ENTRY_SIZE` might not be a good number
- The keys are stored twice in `keySet` and `keyBlockBuilder`
- The extra object overhead for `IntArrayList`, as discussed in https://github.com/prestodb/presto/pull/7349
- Not sure how many bytes it will consume for `isMultiValue` because of alignment.

**Comment by wenleix** [comment]
Related issue: https://github.com/prestodb/presto/issues/6313

**Comment by nezihyigitbasi** [comment]
Superseded by #7421.

**Comment by wenleix** [comment]
Some previous optimization is done in https://github.com/prestodb/presto/issues/6313. @nezihyigitbasi  is working on some further optimization to reduce the memory footprint :)
