### ISSUE TITLE
cassandra - connector bug : query result error

### ISSUE THREAD

**Issue by richardxu80** [prestodb/presto#7361]
Environment is :
Cassandra 3.0 ( only one node for test) + presto 0.161

Issue:
could not get correct result by using presto query cassandra

![error](https://cloud.githubusercontent.com/assets/11187852/22910541/996bde1a-f295-11e6-957f-f43576c1e03e.png)

**Comment by richardxu80** [comment]
It is a very strange bug. more test result for reference:

`select count(*) from restore` ==> presto-cli and cqlsh returen same result

`select lot_id from restore where lot_id like 'D6Q14%'` could get result, but '=' operator couldn't
![error](https://cloud.githubusercontent.com/assets/11187852/22911527/2b0d9ebc-f29b-11e6-9daa-f62752648077.PNG)

**Comment by richardxu80** [comment]
seems it was caused by cache. do any one knows how to change cache config?

![error2](https://cloud.githubusercontent.com/assets/11187852/22911687/fe0252f4-f29b-11e6-915c-db58ce4fd2ba.PNG)

**Comment by cawallin** [comment]
https://prestodb.io/docs/current/connector/cassandra.html -- see ``cassandra.schema-cache-ttl`` and ``cassandra.schema-refresh-interval`` in particular

**Comment by richardxu80** [comment]
@cawallin how can I get more detail about schema-cache-ttl and schema-refresh-interval? want to get more detail and so that I can adjust how to avoid "dirty read" through prestodb

**Comment by cawallin** [comment]
The schema cache is a Guava cache (see https://github.com/prestodb/presto/blob/master/presto-cassandra/src/main/java/com/facebook/presto/cassandra/CachingCassandraSchemaProvider.java#L97) -- schema-cache-ttl is expiresAfterWrite and schema-refresh-interval is refreshAfterWrite, see the Guava documentation for how those work exactly: https://github.com/google/guava/wiki/CachesExplained
