### ISSUE TITLE
Query Cassandra Mviews from Prestodb

### ISSUE THREAD

**Issue by santhavathi** [prestodb/presto#7363]
0
down vote
favorite
	

Unable to query cassandra mviews from prestodb.
It gives below error.
presto> select * from mykeyspace1.mymview1 where phone in ('1234567890');
Query 20170213_131643_00074_5smf2 failed: line 1:15: Table cassandra.mykeyspace1.mymview1 does not exist

We observed this issue with DSE 5.0.4 and prestodb 0.158

**Comment by cawallin** [comment]
@santhavathi -- if you're interested in fixing this, there are a couple of places to look. First, Presto does not recognize materialized views as tables. Assuming it's safe to handle materialized views in exactly the same way as tables, you need to modify the listTables() method in CassandraMetadata (you'll have to modify the table cache in CachingCassandraSchemaProvider). Start with that, there may be other changes in the execution needed.

**Comment by cawallin** [comment]
Thanks for looking into this!

**Comment by ebyhr** [comment]
I started developping this. Still WIP, though.
https://github.com/ebyhr/presto/tree/7363

**Comment by ebyhr** [comment]
I'm writing tests, but current Cassandra test server is `2.1.16`. 
Materialized view is supported grater than `3.0`.
https://github.com/prestodb/presto-cassandra-server/blob/master/pom.xml#L46

@cawallin Is there the plan which upgrade this?

[New in Cassandra 3.0: Materialized Views](https://www.datastax.com/dev/blog/new-in-cassandra-3-0-materialized-views)

**Comment by cawallin** [comment]
@ebyhr The docker container that runs the product tests is the most recent version of Cassandra (I think 3.9), you can give that a try. The integration tests are version 2.1.x and the product tests run against 3.x so that we can test a broad version range without adding too much of a testing burden.

**Comment by ebyhr** [comment]
Thanks for teaching me the version policy. I'm going to write the product tests.

**Comment by ebyhr** [comment]
Materialized View in presto-cassandra is already supported.
