### ISSUE TITLE
Inconsistent non-deterministic function behaviour

### ISSUE THREAD

**Issue by sopel39** [prestodb/presto#7374]
When running:
```
select random(), random() from (VALUES 1,2,3) t(a);
```
I got following result:
```
       _col0        |       _col1        
--------------------+--------------------
 0.5270616678450946 | 0.5270616678450946 
 0.8931855360815748 | 0.8931855360815748 
 0.5952549674284885 | 0.5952549674284885 
```

However, when I run:
```
select random(), random()+1 from (VALUES 1,2,3) t(a)
```
I got following result, which calls `random()` twice for each row:
```
        _col0        |       _col1        
---------------------+--------------------
  0.5246386517543292 | 1.9999490995495495 
 0.44048377882829604 | 1.5099625519640845 
  0.6671711990457818 | 1.0863682891876703
```

Additionally:
```
select random() from (VALUES 1,2,3) t(a) order by random()+1;
```
returns unordered results:
```
        _col0        
---------------------
 0.06403045816590291 
  0.5080858624217778 
  0.9777841992432877
```

The inconsistency is caused by tricky merging of nondeterministic expressions in planner. 
How this should work @martint ? What does standard says? 
**EDIT** think we should decide on one behavior or the other. I think outputting the same nondeterministic function call result might be problematic though. Consider following examples:
```
1. random(a) random(t1.a)
2. random(a+1) random(1+a)
3. random(cast(((a and b) or c) as integer)) random(cast(((a or c) and (b or c)) as integer))
```
Those are the same random function calls, but it is potentially exponential problem to recognize it. I think it's more intuitive not to assume the same random function call returns the same value within row.

We could work on that after: https://github.com/prestodb/presto/pull/7315 and https://github.com/prestodb/presto/pull/7354

FYI: @kokosing 

might be related to: https://github.com/prestodb/presto/issues/3653

**Comment by martint** [comment]
This is a long-standing issue. It hasn't been high-priority enough to fix it.

Unfortunately, the spec doesn't say anything about this. `rand()` doesn't exist in standard SQL and no other class of functions has similar semantics.

What would seem to make logical sense is to prevent any merging of non-deterministic functions. Some scenarios are more challenging: should a filter be pushed through a projection that invokes a non-deterministic function? Assuming invocations of the same instance are truly independent from each other, it's probably ok. But, then, it raises the question of what's, really, a non-deterministic function? All non-deterministic functions can be though of as operating on some hidden state, so the sequencing of invocations might affect how that state is mutated.

**Comment by sopel39** [comment]
>  Some scenarios are more challenging: should a filter be pushed through a projection that invokes a non-deterministic function

Could you give some example? I looked at `PredicatePushDown` and it seems not to push filters through projection that depend on non-deterministic symbols.

> All non-deterministic functions can be though of as operating on some hidden state, so the sequencing of invocations might affect how that state is mutated.

If standard doesn't define any particular order of computations (e.g: for projection columns or where conditions) then authors of non-deterministic functions shouldn't assume any order. Thus they cannot rely on hidden states probably. After all, SQL is rather declarative, not imperative language.

My view is that merging duplicate computations of same expressions is rather an optimization. The result should be the same as if the expressions were computed multiple times. Therefore such optimization cannot be applied to non-deterministic expressions.

It's really confusing that `select rand(), rand()` uses the same random value, but `select rand(), rand()+1` doesn't. If a user wants to duplicate the same random value, he probably should explicitly write: `select a, a from (select rand() as a)`

Can we go with this direction @martint ? It seems to be consistent and clear. Otherwise it will be really difficult (or computationally expensive) to try recognizing all identical invocations of the same non-deterministic functions (to have a consistent behavior).

**Comment by martint** [comment]
Indeed, we **should not** dedup calls to non-deterministic functions. Hence, my comment about "What would seem to make logical sense is to prevent any merging of non-deterministic functions".

I was just expanding on some potential gotchas for the general class of non-deterministic functions. Other than rand() (especially, if it was *true* random), there really no non-deterministic function, since any possible implementation would have to rely on internal state and would be sensitive to invocation order or count.

E.g., let's say I define a function call "counter()" that returns a monotonically increasing number across invocations. By Presto's definition, it's a non-deterministic function, since it doesn't return the same output given the same input. Of course, in the broadest sense, it's not truly non-deterministic, since you can easily predict what its next output would be.

With such a function, a query like:

```sql
SELECT * FROM (
    SELECT x, counter()
    FROM (VALUES 0, 0, 1, 1) t(x)
)
WHERE x = 1
```

would produce:

(1, 3), (1, 4)

while 

```sql
SELECT x, counter()
FROM (
    SELECT * 
    FROM (VALUES 0, 0, 1, 1) t(x)
   WHERE x = 1
)
```

would produce

(1, 1), (1, 2)

Anyway, this is just a cooked up example to illustrate my points. It's not important, so let's not focus on it.
