### ISSUE TITLE
Lambdas are not suffciently verified during analyzis

### ISSUE THREAD

**Issue by sopel39** [prestodb/presto#7376]
Query:
```
select filter(array [5], x -> x + a > 0) from (VALUES (1,2)) t(a,b);
```
fails with:
```
Query 20170215_110307_00000_geqw6 failed: No type for symbol field
```

This should be addressed after #7354 and #7315 are merged.

FYI: @martint @kokosing

**Comment by findepi** [comment]
Note: 
```
select filter(array [5], x -> x + a > 0) from (VALUES (1,2)) t(a,b) GROUP BY a;
```
also fails, this time with `Compiler failed and interpreter is disabled` (due to `com.facebook.presto.sql.relational.RowExpressionVisitor#visitInputReference` throwing `UnsupportedOperationException`).

**Comment by martint** [comment]
I believe this is the same as https://github.com/prestodb/presto/issues/6982

**Comment by findepi** [comment]
Indeed
