### ISSUE TITLE
create external table but how to define `fields terminated`

### ISSUE THREAD

**Issue by hzzz823** [prestodb/presto#7388]
in s3://test
1,2

then:
`create table hzzz (a varchar, b varchar) with ( external_location = 's3://test', format = 'TEXTFILE' )`
`select * from hzzz`

retult is:
a         b
1,2    null

should i define `fields terminated`? and how?

**Comment by yuananf** [comment]
There is a pending pull request about this
https://github.com/prestodb/presto/pull/6387

**Comment by MichaelChirico** [comment]
Why is this issue closed when the PR is still open?
