### ISSUE TITLE
Unable to use kafka topics that are avro encoded

### ISSUE THREAD

**Issue by mmcalli** [prestodb/presto#7391]
Are there any plans to allow prestodb to support kafka topics that are avro encoded? These are topics where from the commandline you need to use the `kafka-avro-console-consumer` rather than the `kafka-console-consumer`.

**Comment by gaohao** [comment]
I think you can write a avro row decoder under presto-record-decoder, should be straightforward

**Comment by electrum** [comment]
The Kafka connector doesn't have an active maintainer. Contributions such as this are very welcome!

**Comment by findepi** [comment]
https://github.com/prestodb/presto/pull/11108 is merged. Let me close this. Of course, the Avro support implemented may or may not be sufficient in your particular use-case. Please create new, more specific issue (if it does not exist yet).
