### ISSUE TITLE
Extract planner (and parser) as separate project

### ISSUE THREAD

**Issue by kokosing** [prestodb/presto#7399]
Nowadays when John (or any Big data tech startup, or some open-source community) wants to create an SQL on hadoop (or whatever data source), they choose [calcite](https://calcite.apache.org/) to parse SQL, create and optimize the query plan. For example take a look at [SQL on Flink streaming](https://ci.apache.org/projects/flink/flink-docs-release-1.2/dev/table_api.html) is great project is not perfect

Although calcite is a well know project and a great tool, it is not a perfect one. I think it would be really great for people who want to do their own SQL to have a possibility of choosing parser/optimizer framework. When everything planned as [new optimizer work](https://github.com/prestodb/presto/wiki/New-Optimizer) get completed, I think presto planner will be much better than calcite (or at least competitive). 

Presto parser and planner are very much independent (to execution) components. It is due the usage of well designed SPI. So it should be fairly easy (like two weeks of work ;) ) to extract this as separate project.

Why should we care?
 - having planner as separated project might create a new community around it, and so it will be better tested, it will have more bugfixes
 - Presto will be more popular
 - from the point of view of Presto, planner will be more stable
 - from the point of view of planner, it will be easier to develop it when you do not need to run whole Presto automation per each planner change

I post this issue because I am curious about your opinion on this. If it get enough appreciation from you then we might think if it is doable and play with it on hackathon.

**Comment by kokosing** [comment]
CC: @martint @ilfrin @sopel39

**Comment by kokosing** [comment]
I think I exaggerated a bit. Making it a separate module will be enough so far. . That approach is much simpler and has many advantages:
 - that way anyone could take the `presto-planner` as dependency to his own `SQL`
 - presto development would not be hurted as still all change set can be posted in one PR
 - much better domain separation as planner would be separated from main

**Comment by dain** [comment]
In the long term, this might be something we may want to do.  The downside is if you want people to use this code as a library, you need to start maintaining them as a library, which means you have less ability to make big changes (no one wants to rewrite their code all the time).  Right now the analyzer and planner are going through big changes, and I don't think we are prepared to slow down progress right now.
