### ISSUE TITLE
Documentation for try and try_cast not clear for cast errors

### ISSUE THREAD

**Issue by bsullins** [prestodb/presto#7402]
it appears that try() and try_cast() are not handling invalid type cast errors. Here is what I'm seeing on the teradata sandbox vm

`presto> select try(cast(0.01 as date));`
`Query 20170217_090614_00041_fchrk failed: line 1:12: Cannot cast decimal(2,2) to date`
`select try(cast(0.01 as date))`

and try_cast()

`presto> select try_cast(0.01 as timestamp);`
`Query 20170217_084646_00032_fchrk failed: line 1:8: Cannot cast decimal(2,2) to timestamp`
`select try_cast(0.01 as timestamp)`

**Comment by dain** [comment]
I believe the issue here is there is no function that can cast from decimal to date.  This would be the equivalent of `SELECT try(someUnknownFunction(0.01))`.  The query is rejected during analysis instead of this being a runtime (data dependent) error which is what the try syntax handles.

**Comment by bsullins** [comment]
If it only works when it's a valid cast, what's the point of the function? Reading the documentation, it sounds like if it's an invalid cast (e.g. 0.01 to timestamp), then it would return NULL instead of failing?

**Comment by electrum** [comment]
The purpose of the function is to allow handling invalid data. For example, `cast('123' as bigint)` works but `cast('xxx' as bigint)` fails. Note that `try_cast` existed before `try` -- the latter is more generic and can be used for any expression.

**Comment by electrum** [comment]
This is similar to doing `SELECT try(foo())` where `foo()` is a function that doesn't exist. It's going to fail at analysis time.

**Comment by electrum** [comment]
I see the confusion with the documentation. It says _returns null if the cast fails_ which means _fails at runtime_. That's different than the cast not existing, but it's easy to misinterpret. We can make the documentation more explicit.

**Comment by bsullins** [comment]
@electrum great, yeah that's my point exactly. To your example above, what if I had a column with 123, and xxx in it? either try_cast() or try() handle that?
