### ISSUE TITLE
Setup credentials connecting to Presto

### ISSUE THREAD

**Issue by daiduongbian44** [prestodb/presto#7410]
Hi,
Anyone tries setting up the credentials in presto? I want to limit the connections to presto by using the credential (such as username and password) but i have no idea setting up this.
Hope anyone help me.
Thanks all.

**Comment by daiduongbian44** [comment]
@martint hope you have some advice for me =)) thanks

**Comment by cawallin** [comment]
@daiduongbian44 -- see the following documentation about security in Presto: https://prestodb.io/docs/current/security.html. In release 0.166, there is only Kerberos authentication available, but in the upcoming 0.167 release, you will be able to authenticate against an external LDAP server. (for a preview of what that will look like, see these docs: https://teradata.github.io/presto/docs/current/security/ldap.html)

**Comment by daiduongbian44** [comment]
thank you @cawallin, i'm going to try it out

**Comment by cawallin** [comment]
OK, glad to hear that -- I'll close this issue then.
