### ISSUE TITLE
Add support for Thrift data

### ISSUE THREAD

**Issue by Yaliang** [prestodb/presto#7422]
We hope to leverage the power of Presto by developing the support for LZO Thrift data files. This data format is still widely used within Twitter, and presumably in other companies as well. We'd like to share the design and progress via [this doc](https://docs.google.com/document/d/19lRXXGUfF7O5bDq-uAGd9Qq7_Hp97yotmwrblTc9CAk/edit?usp=sharing).

**Comment by Yaliang** [comment]
+cc @billonahill @dabaitu

**Comment by cawallin** [comment]
@AlekseiS how does https://github.com/prestodb/presto/pull/7119 relate to this?

**Comment by AlekseiS** [comment]
@cawallin the goal of https://github.com/prestodb/presto/pull/7119 is to develop a full thrift connector. As far as I understand the goal of this issue is to just support thrift encoding for data files. @Yaliang is my understanding correct?

**Comment by Yaliang** [comment]
@AlekseiS Yes. It is.

**Comment by Yaliang** [comment]
We have merged our patch in twitter-fork and deployed in production. The shared doc has updated with our design details and performance report.
