### ISSUE TITLE
Optimize IN expression with single value

### ISSUE THREAD

**Issue by erichwang** [prestodb/presto#7430]
An IN expression with a single value, such as (a IN ('abc)) can be optimized to an equivalent equality of (a = 'abc'). This is a far more efficient from of execution. There are several ways to go about this:
1) Have an expression optimizer that specifically replaces these expressions at optimization time.
2) Have the IN bytecode compiler directly generate the equality for the expression at execution time.

There is some discussion here to be had between those approaches, especially when considering how to optimize if there are a low cardinality of values in the IN clause.

**Comment by martint** [comment]
It should be done in an optimizer. That has the advantage that the simplified expression may become a candidate for partition pruning, etc.

**Comment by erichwang** [comment]
Note that this already works for predicates as a side-effect of the predicate pushdown optimization.
