### ISSUE TITLE
Presto Call store procedure from mysql connector

### ISSUE THREAD

**Issue by tuanvn6467** [prestodb/presto#7433]
Hello @dain ,
I have configured presto and I am trying to use it.
i have mysql connector and it work very good with query
But when i called store procedure/function from mysql connector, it have error:

presto:default> select * from mysql.mp_commerce.test;
idtest | testcol
--------+------------------
1 | Hair Care
2 | Body Care
3 | Kits & Gift Sets
(3 rows)

Query 20161111_022956_00023_ki3sk, FINISHED, 2 nodes
Splits: 2 total, 2 done (100.00%)
0:00 [3 rows, 0B] [7 rows/s, 0B/s]

presto:default> call mysql.mp_commerce.new_procedure();
Query 20161111_023022_00024_ki3sk failed: Procedure not registered: mysql.mp_commerce.new_procedure

Pls suggest me some links related to presto so that I can learn more about it.

Thanks & Best Regards

**Comment by cawallin** [comment]
@tuanvn6467 Presto does not support calling stored procedures or functions from connectors. For more information, see https://prestodb.io/

**Comment by sbansal6** [comment]
@tuanvn6467 :- is there a timeline on when this will be implement or supported.
