### ISSUE TITLE
Improve the performance of MapTransformKeyFunction and MapTransformValueFunction

### ISSUE THREAD

**Issue by wenleix** [prestodb/presto#7436]
Lambda functions `transform_key` and `transform_value` are introduced in https://github.com/prestodb/presto/issues/7285, and currently they are not less efficient since they are not using byte-code generation .

We should optimize it similar to the `transform` lambda function, introduce the benchmark class, as done in https://github.com/prestodb/presto/issues/6780.

**Comment by wenleix** [comment]
The benchmark in https://github.com/prestodb/presto/pull/7461 shows byte-code generation for this is probably not promising :(

**Comment by geraint0923** [comment]
For the `transform_values`, I think re-adding keys to a new `InterleavedBlock` might negate the benefit of bytecode generation. Can you try just re-construct the value part and re-use the key part?

**Comment by highker** [comment]
Here the benchmark results of reusing key/value part

Benchmark                                      (name)  Mode  Cnt    Score   Error  Units
BenchmarkTransformKey.benchmark        transform_keys  avgt   20  154.039 ± 6.796  ns/op
BenchmarkTransformKey.benchmark  exact_transform_keys  avgt   20  141.211 ± 3.684  ns/op


Benchmark                                          (name)  Mode  Cnt   Score   Error  Units
BenchmarkTransformValue.benchmark        transform_values  avgt   20  85.330 ± 1.298  ns/op
BenchmarkTransformValue.benchmark  exact_transform_values  avgt   20  79.679 ± 7.166  ns/op


Both faster c.p. https://github.com/prestodb/presto/pull/7461
