### ISSUE TITLE
Investigate if Hive connector should add stats properties

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#7438]
Partitions (or unpartitioned tables) written by Hive seem to have the following properties (tested with Hive 1.2.1):

* `COLUMN_STATS_ACCURATE` = `true`
* `numFiles`
* `numRows`
* `rawDataSize`
* `totalSize`

This looks like a good starting point: https://github.com/apache/hive/blob/master/standalone-metastore/src/main/java/org/apache/hadoop/hive/common/StatsSetupConst.java

**Comment by rschlussel2** [comment]
The following column stats are used in the CBO (https://github.com/prestodb/presto/pull/9788):
min value
max value
NDVs
nulls
datasize

**Comment by highker** [comment]
For reference (https://cwiki.apache.org/confluence/display/Hive/Column+Statistics+in+Hive)

**Comment by arhimondr** [comment]
Basic statistics: https://github.com/prestodb/presto/pull/10456

**Comment by martint** [comment]
@arhimondr, your fix covers this issue, right? Can we close it?

**Comment by arhimondr** [comment]
Yes
