### ISSUE TITLE
Support enabling SSL for MongoDB connector

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#7447]
Add a new config option `mongodb.ssl.enabled` in `MongoClientConfig`, utilize it in `MongoClientModule` and document it in the `mongo.rst` file.

**Comment by kruppel** [comment]
@ebyhr @electrum Did this stem for the question on the IRC channel? An earlier PR was posted by the OP for this issue in #7440 😄.

**Comment by ebyhr** [comment]
Oops! I made almost the same PR. I closed my PR :) 
Thank you for telling me!

**Comment by electrum** [comment]
Yes, I filed this based on the IRC question. I didn't realize there was already a PR. Sorry for the confusion.
