### ISSUE TITLE
com.facebook.presto.sql.SqlFormatter.Formatter#visitCreateSchema did not escape schema name

### ISSUE THREAD

**Issue by Jimexist** [prestodb/presto#7465]
In this method (com.facebook.presto.sql.SqlFormatter.Formatter#visitCreateSchema) the schema's name gets appended directly, without checking against com.facebook.presto.sql.SqlFormatter#NAME_PATTERN.

Suggest changing to using com.facebook.presto.sql.SqlFormatter.Formatter#formatName(com.facebook.presto.sql.tree.QualifiedName)

**Comment by Jimexist** [comment]
In Master:

https://github.com/prestodb/presto/blob/master/presto-parser/src/main/java/com/facebook/presto/sql/SqlFormatter.java#L699

Minimal example:
```
    @Test
    public void test() {
        String string = "create schema \"360\"";
        Statement statement = new SqlParser().createStatement(string);
        String formatted = SqlFormatter.formatSql(statement, Optional.empty());
        Assertions.assertThat(formatted).isEqualTo("create schema 360");
    }
```

**Comment by electrum** [comment]
Thanks for finding this. Do you want to submit this fix as a Pull Request?

**Comment by Jimexist** [comment]
@electrum the PR is here https://github.com/prestodb/presto/pull/7467
