### ISSUE TITLE
Support column removals in presto-raptor

### ISSUE THREAD

**Issue by mradwan** [prestodb/presto#7476]
Currently presto supports adding new columns to an existing table in raptor, would be great if we can also add column removals to delete unused columns arbitrary positions in existing tables.

**Comment by electrum** [comment]
Depends on #7483

**Comment by electrum** [comment]
Raptor uses a per-table column ID, which is not tracked separately (adding a column just picks the `max(id) + 1`, so for the first version, we can restrict dropping the last column from the table.

**Comment by AlekseiS** [comment]
I assume this is done as part of https://github.com/prestodb/presto/pull/7514
