### ISSUE TITLE
Wrong (similar) field is returned

### ISSUE THREAD

**Issue by ebuildy** [prestodb/presto#7479]
Hadoop: 2.6
PrestoDB: Presto CLI 0.148
Connector: Hive (Hive 1.2)

I have a Parquet Hive table, with 20 fields:
- fullname
- browser_fullname
- ....

Running the query ``SELECT COUNT(*), fullname FROM sample2 GROUP BY fullname;``

gives ``browser_fullname`` field instead of ``fullname``.

Tested with Hive on Tez and Apache Drill, it's ok:

![](http://b3.ms/a8XAjV0zABDx)

**Comment by nezihyigitbasi** [comment]
I suspect there is some sort of schema mismatch here, you should compare the  Hive schema vs. the Parquet file level schema to confirm that. 

BTW by default Presto uses index-based access when reading columns from Parquet files, and probably the Hive column index for the `fullname` column points to the `browser_fullname` column in the Parquet file. You can try setting `hive.parquet.use-column-names=true` to see whether it helps.

**Comment by KBP-TDC** [comment]
Please add "--debug" when starting the CLI for get more verbose logging.

**Comment by ebuildy** [comment]
Hello @nezihyigitbasi , you are right, setting ``hive.parquet.use-column-names=true`` did the trick.

Thanks you guys for such fast answers.

**Comment by sdia** [comment]
Hello everyone,

I am using Presto through AWS EMR, I think I have the same issue described here. So far the only way I interact with Presto is via the cli. Can someone tell me how and where to set `hive.parquet.use-column-names`. 

Thanks in you in advance!

**Comment by ebuildy** [comment]
Can you try with ``SET SESSION`` such as described https://prestodb.io/docs/current/sql/set-session.html ?
