### ISSUE TITLE
Presto-accumulo connector incorrectly requires a Column Family to be present for an external table

### ISSUE THREAD

**Issue by ducky427** [prestodb/presto#7490]
Currently in the presto-accumulo connector for an external table, when mapping from accumulo value to prestodb column, it is required that column family  be non-empty. This shouldn't be the case as it is possible to have this as empty.

The offending line is https://github.com/prestodb/presto/blob/47e12e761f3731dd2800456d59e64071bbdae909/presto-accumulo/src/main/java/com/facebook/presto/accumulo/conf/AccumuloTableProperties.java#L59

Just removing `.omitEmptyStrings()` fixes the issue.

**Comment by adamjshook** [comment]
Fixed in #7563
