### ISSUE TITLE
Presto taking very long time to execute the query. Its running slower than hive on EMR

### ISSUE THREAD

**Issue by mehramanish** [prestodb/presto#7491]
We tried running the query on presto-cli and its taking >36mins to execute
whereas when we run the same query on hive it gets run in 70secs.

We are using R3 8x large cluster with 9 nodes.

Avg utilization(on ganglia) is <20% . No other job is running in parallel on the cluster.

We have altered few configurations as stated below but not much improvement is been observed.

query.max-memory=500GB   -> initial value of this was 30GB
query.max-memory-per-node=100GB  -> initial value of this was 103177999352B
query.max-age=30m  -> initial value of this was 
task.concurrency = 2 -> initial value of this was 1
task.share-index-loading=true -> initial value of this was false
distributed-index-joins-enabled=true -> initial value of this was false
exchange.client-threads=50  -> initial value of this was 25

query that we used is as below
`CREATE TABLE ZZMD00 AS 
select	a11.time_bckt_id  time_bckt_id,
	max(a17.time_bckt_nm)  time_bucket_name,
	a11.time_id  time_id,
	max(a17.time_nm)  time_name,
	a11.team_id  team_id,
	max(a15.team_nm)  team_name,
	a11.cust_group  prescriber_group_code,
	a11.rpt_f_obr_sls_geo_prod_prscrbr_class_flag  rpt_f_obr_sls_geo_prod_prscrbr_class_flag,
	a12.impersonation_flag  impersonation_flg,
	a12.parent_geo_id  geo_id,
	max(a12.parent_geo_nm)  geo_name,
	TRIM(a11.curr_val_rating_group)  curr_value_rating_group,
	max(CONCAT(a11.curr_val_rating_group, ' Value Rating'))  CustCol_17,
	a13.agn_prod_id  agn_prod_id,
	max(a13.agn_prod_nm)  agn_prod_name,
	max(a13.agn_prod_level)  agn_prod_level,
	max(a13.agn_prod_cd)  agn_prod_cd,
	a12.access_type  access_type,
	a12.EMP_ID  EMP_ID,
	a12.parent_geo_level_id  GEO_LEVEL_ID,
	max(a12.parent_geo_level_desc)  geo_level_desc,
	a16.mstr_user_id  mstr_user_id_1,
	a17.time_bckt_type  time_bucket_type,
	avg(a11.curr_trx_share)  Curr_TRx_Share,
	max(a11.curr_geo_ct)  Current_Geo_Count,
	max(a11.prev_geo_ct)  Previous_Geo_Count,
	sum(a11.curr_nrx)  WJXBFS1,
	avg(a11.prev_trx_share)  Prev_TRx_Share,
	sum(a11.curr_trx)  WJXBFS2,
	sum(a11.curr_tot_prscrbr_ct)  WJXBFS3,
	sum(a11.curr_new_prscrbr_ct)  WJXBFS4,
	sum(a11.prev_nrx)  WJXBFS5,
	sum(a11.prev_trx)  WJXBFS6
from	allergan_insight_db.rpt_f_obr_sls_geo_prod_prscrbr_class	a11
	join	allergan_insight_db.rpt_m_emp_geo_access	a12
	  on 	(a11.cntry_id = a12.cntry_id and 
	a11.geo_id = a12.geo_id)
	join	allergan_insight_db.rpt_d_prod_mkt	a13
	  on 	(a11.cntry_id = a13.cntry_id and 
	a11.mkt_id = a13.mkt_id and 
	a11.prod_id = a13.prod_id and 
	a11.prod_level = a13.prod_level)
	join	allergan_insight_db.rpt_d_prod	a14
	  on 	(a11.cntry_id = a14.cntry_id and 
	a11.mkt_id = a14.mkt_id and 
	a11.prod_id = a14.prod_id and 
	a11.prod_level = a14.prod_level)
	join	allergan_insight_db.rpt_d_geo	a15
	  on 	(a11.cntry_id = a15.cntry_id and 
	a11.geo_id = a15.geo_id and 
	a11.team_id = a15.team_id)
	join	allergan_insight_db.rpt_d_user_securty	a16
	  on 	(a11.cntry_id = a16.cntry_id and 
	a12.EMP_ID = a16.EMP_ID)
	join	allergan_insight_db.rpt_d_time_bckt	a17
	  on 	(a11.cntry_id = a17.cntry_id and 
	a11.team_id = a17.team_id and 
	a11.time_bckt_id = a17.time_bckt_id and 
	a11.time_id = a17.time_id)
where	(a12.parent_geo_id = a11.geo_id
 and a12.parent_geo_level_id = a15.GEO_LEVEL_ID
 and a12.impersonation_flag in ('N')
 and a16.mstr_user_id in ('apoorva.dorai@zsassociates.com')
 and a14.comp_flag in ('N')
 and a11.time_bckt_id in (23)
 and a12.access_type in ('Retail-Mobile')
 and TRIM(a11.curr_val_rating_group) <> 'Unassigned'
 and a17.time_bckt_type in ('Trend-Sales'))
group by	a11.time_bckt_id,
	a11.time_id,
	a11.team_id,
	a11.cust_group,
	a11.rpt_f_obr_sls_geo_prod_prscrbr_class_flag,
	a12.impersonation_flag,
	a12.parent_geo_id,
	TRIM(a11.curr_val_rating_group),
	a13.agn_prod_id,
	a12.access_type,
	a12.EMP_ID,
	a12.parent_geo_level_id,
	a16.mstr_user_id,
	a17.time_bckt_type`

Explain plan of the query is 
`
 - Output[time_bckt_id, time_bucket_name, time_id, time_name, team_id, team_name, prescriber_group_code, rpt_f_obr_sls_geo_prod_prscrbr_class_flag, impersonation_flg, geo_id, geo_name, curr
         time_bucket_name := max
         time_name := max_152
         team_name := max_153
         prescriber_group_code := cust_group
         impersonation_flg := impersonation_flag
         geo_id := parent_geo_id
         geo_name := max_154
         curr_value_rating_group := trim
         CustCol_17 := max_155
         agn_prod_name := max_156
         agn_prod_level := max_157
         agn_prod_cd := max_158
         EMP_ID := emp_id
         GEO_LEVEL_ID := parent_geo_level_id
         geo_level_desc := max_159
         mstr_user_id_1 := mstr_user_id
         time_bucket_type := time_bckt_type
         Curr_TRx_Share := avg
         Current_Geo_Count := max_160
         Previous_Geo_Count := max_161
         WJXBFS1 := sum
         Prev_TRx_Share := avg_162
         WJXBFS2 := sum_163
         WJXBFS3 := sum_164
         WJXBFS4 := sum_165
         WJXBFS5 := sum_166
         WJXBFS6 := sum_167
     - RemoteExchange[GATHER] => time_bckt_id:double, max:varchar, time_id:varchar, max_152:varchar, team_id:varchar, max_153:varchar, cust_group:varchar, rpt_f_obr_sls_geo_prod_prscrbr_cla
         - Project => [sum_167:double, access_type:varchar, sum_166:double, sum_165:double, max_160:double, sum_164:double, max_161:double, sum_163:double, sum:double, team_id:varchar, time
             - Aggregate(FINAL)[time_bckt_id, time_id, team_id, cust_group, rpt_f_obr_sls_geo_prod_prscrbr_class_flag, impersonation_flag, parent_geo_id, trim, agn_prod_id, access_type, emp
                     max_153 := "max"("max_340")
                     max_154 := "max"("max_341")
                     sum_167 := "sum"("sum_356")
                     max_155 := "max"("max_342")
                     sum_166 := "sum"("sum_355")
                     max_156 := "max"("max_343")
                     sum_165 := "sum"("sum_354")
                     max_160 := "max"("max_348")
                     sum_164 := "sum"("sum_353")
                     max := "max"("max_338")
                     max_161 := "max"("max_349")
                     sum_163 := "sum"("sum_352")
                     max_152 := "max"("max_339")
                     sum := "sum"("sum_350")
                     max_157 := "max"("max_344")
                     max_158 := "max"("max_345")
                     max_159 := "max"("max_346")
                     avg_162 := "avg"("avg_351")
                     avg := "avg"("avg_347")
                 - LocalExchange[HASH] ("time_id", "access_type", "parent_geo_id", "team_id", "time_bckt_id", "rpt_f_obr_sls_geo_prod_prscrbr_class_flag", "impersonation_flag", "trim", "agn
                     - RemoteExchange[REPARTITION] => time_bckt_id:double, time_id:varchar, team_id:varchar, cust_group:varchar, rpt_f_obr_sls_geo_prod_prscrbr_class_flag:varchar, impersona
                         - Project => [time_bckt_id:double, time_id:varchar, team_id:varchar, cust_group:varchar, rpt_f_obr_sls_geo_prod_prscrbr_class_flag:varchar, impersonation_flag:varch
                                 $hashvalue_699 := "combine_hash"("combine_hash"("combine_hash"("combine_hash"("combine_hash"("combine_hash"("combine_hash"("combine_hash"("combine_hash"("co
                             - Aggregate(PARTIAL)[time_bckt_id, time_id, team_id, cust_group, rpt_f_obr_sls_geo_prod_prscrbr_class_flag, impersonation_flag, parent_geo_id, trim, agn_prod_id
                                     max_340 := "max"("team_nm")
                                     sum_355 := "sum"("prev_nrx")
                                     max_341 := "max"("parent_geo_nm")
                                     sum_354 := "sum"("curr_new_prscrbr_ct")
                                     max_342 := "max"("concat")
                                     sum_353 := "sum"("curr_tot_prscrbr_ct")
                                     max_343 := "max"("agn_prod_nm")
                                     sum_352 := "sum"("curr_trx")
                                     sum_350 := "sum"("curr_nrx")
                                     avg_347 := "avg"("curr_trx_share")
                                     max_348 := "max"("curr_geo_ct")
                                     max_338 := "max"("time_bckt_nm")
                                     max_349 := "max"("prev_geo_ct")
                                     max_339 := "max"("time_nm")
                                     max_344 := "max"("agn_prod_level")
                                     max_345 := "max"("agn_prod_cd")
                                     avg_351 := "avg"("prev_trx_share")
                                     max_346 := "max"("parent_geo_level_desc")
                                     sum_356 := "sum"("prev_trx")
                                 - Project => [access_type:varchar, curr_tot_prscrbr_ct:double, agn_prod_nm:varchar, team_id:varchar, time_bckt_nm:varchar, time_bckt_id:double, trim:varchar
                                         $hashvalue_698 := "combine_hash"("combine_hash"("combine_hash"("combine_hash"("combine_hash"("combine_hash"("combine_hash"("combine_hash"("combine_h
                                     - Project => [access_type:varchar, curr_tot_prscrbr_ct:double, agn_prod_nm:varchar, team_id:varchar, time_bckt_nm:varchar, time_bckt_id:double, trim:var
                                             trim := "trim"("curr_val_rating_group")
                                             concat := "concat"("curr_val_rating_group", CAST(' Value Rating' AS VARCHAR))
                                         - InnerJoin[("team_id_389" = "team_id_390") AND ("cntry_id_391" = "cntry_id_392") AND ("time_id_393" = "time_id_394")] => [team_id:varchar, cntry_id
                                             - LocalExchange[ROUND_ROBIN] () => team_id:varchar, cntry_id_71:double, time_id:varchar, access_type:varchar, curr_tot_prscrbr_ct:double, agn_pr
                                                 - Project => [team_id:varchar, cntry_id_71:double, time_id:varchar, access_type:varchar, curr_tot_prscrbr_ct:double, agn_prod_nm:varchar, ti
                                                     - RemoteExchange[REPARTITION] => team_id:varchar, cntry_id_71:double, time_id:varchar, access_type:varchar, curr_tot_prscrbr_ct:double,
                                                         - Project => [access_type:varchar, cntry_id_71:double, curr_tot_prscrbr_ct:double, agn_prod_nm:varchar, team_id:varchar, time_bckt_i
                                                                 $hashvalue_693 := "combine_hash"("combine_hash"("combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("team_id"), 0)), C
                                                             - InnerJoin[("cntry_id_385" = "cntry_id_386") AND ("emp_id_387" = "emp_id_388")] => [cntry_id:double, emp_id:varchar, access_typ
                                                                 - LocalExchange[ROUND_ROBIN] () => cntry_id:double, emp_id:varchar, access_type:varchar, cntry_id_71:double, curr_tot_prscrb
                                                                     - Project => [cntry_id:double, emp_id:varchar, access_type:varchar, cntry_id_71:double, curr_tot_prscrbr_ct:double, agn_
                                                                         - RemoteExchange[REPARTITION] => cntry_id:double, emp_id:varchar, access_type:varchar, cntry_id_71:double, curr_tot_
                                                                             - Project => [access_type:varchar, cntry_id_71:double, curr_tot_prscrbr_ct:double, agn_prod_nm:varchar, team_id:
                                                                                     $hashvalue_687 := "combine_hash"("combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("cntry_id_71"
                                                                                     $hashvalue_688 := "combine_hash"("combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("cntry_id"),
                                                                                 - InnerJoin[("team_id_377" = "team_id_378") AND ("parent_geo_id_379" = "geo_id_380") AND ("expr_381" = "geo_
                                                                                     - LocalExchange[ROUND_ROBIN] () => team_id:varchar, expr_322:double, cntry_id:double, geo_id:varchar, ac
                                                                                         - Project => [team_id:varchar, expr_322:double, cntry_id:double, geo_id:varchar, access_type:varchar
                                                                                             - RemoteExchange[REPARTITION] => team_id:varchar, expr_322:double, cntry_id:double, geo_id:varch
                                                                                                 - Project => [access_type:varchar, curr_tot_prscrbr_ct:double, agn_prod_nm:varchar, team_id:
                                                                                                         $hashvalue_680 := "combine_hash"("combine_hash"("combine_hash"("combine_hash"(BIGINT
                                                                                                         $hashvalue_681 := "combine_hash"("combine_hash"("combine_hash"("combine_hash"(BIGINT
                                                                                                     - Project => [access_type:varchar, curr_tot_prscrbr_ct:double, agn_prod_nm:varchar, team
                                                                                                             expr_322 := CAST("parent_geo_level_id" AS DOUBLE)
                                                                                                         - InnerJoin[("prod_level_369" = "prod_level_370") AND ("prod_id_371" = "prod_id_372"
                                                                                                             - LocalExchange[ROUND_ROBIN] () => cntry_id_9:double, prod_id:varchar, prod_leve
                                                                                                                 - Project => [cntry_id_9:double, prod_id:varchar, prod_level:varchar, mkt_id
                                                                                                                     - RemoteExchange[REPARTITION] => cntry_id_9:double, prod_id:varchar, pro
                                                                                                                         - Project => [access_type:varchar, curr_tot_prscrbr_ct:double, cntry
                                                                                                                                 $hashvalue_674 := "combine_hash"("combine_hash"("combine_has
                                                                                                                                 $hashvalue_673 := "combine_hash"("combine_hash"("combine_has
                                                                                                                             - InnerJoin[("prod_level_361" = "prod_level_362") AND ("mkt_id_3
                                                                                                                                 - LocalExchange[ROUND_ROBIN] () => mkt_id:varchar, prod_id:v
                                                                                                                                     - Project => [mkt_id:varchar, prod_id:varchar, prod_leve
                                                                                                                                         - RemoteExchange[REPARTITION] => mkt_id:varchar, pro
                                                                                                                                             - Project => [access_type:varchar, curr_tot_prsc
                                                                                                                                                     $hashvalue_667 := "combine_hash"("combin
                                                                                                                                                     $hashvalue_666 := "combine_hash"("combin
                                                                                                                                                 - InnerJoin[("cntry_id_357" = "cntry_id_358"
                                                                                                                                                     - LocalExchange[ROUND_ROBIN] () => cntry
                                                                                                                                                         - Project => [cntry_id:double, geo_i
                                                                                                                                                             - RemoteExchange[REPARTITION] =>
                                                                                                                                                                 - Project => [prev_trx:doubl
                                                                                                                                                                         $hashvalue_661 := "c
                                                                                                                                                                     - Filter[("trim"("curr_v
                                                                                                                                                                         - TableScan[hive:hiv
                                                                                                                                                                                 LAYOUT: hive
                                                                                                                                                                                 cntry_id :=
                                                                                                                                                                                 team_id := H
                                                                                                                                                                                 geo_id := Hi
                                                                                                                                                                                 prod_id := H
                                                                                                                                                                                 prod_level :
                                                                                                                                                                                 mkt_id := Hi
                                                                                                                                                                                 time_id := H
                                                                                                                                                                                 curr_val_rat
                                                                                                                                                                                 rpt_f_obr_sl
                                                                                                                                                                                 curr_trx :=
                                                                                                                                                                                 prev_trx :=
                                                                                                                                                                                 curr_nrx :=
                                                                                                                                                                                 prev_nrx :=
                                                                                                                                                                                 curr_trx_sha
                                                                                                                                                                                 prev_trx_sha
                                                                                                                                                                                 curr_tot_prs
                                                                                                                                                                                 curr_new_prs
                                                                                                                                                                                 curr_geo_ct
                                                                                                                                                                                 prev_geo_ct
                                                                                                                                                                                 cust_group :
                                                                                                                                                                                     :: [[NEW
                                                                                                                                                                                 time_bckt_id
                                                                                                                                                                                     :: [[23.
                                                                                                                                                                                 HiveColumnHa
                                                                                                                                                                                     :: [[Are
                                                                                                                                                     - LocalExchange[HASH] ("cntry_id_358", "
                                                                                                                                                         - Project => [cntry_id_9:double, par
                                                                                                                                                             - RemoteExchange[REPARTITION] =>
                                                                                                                                                                 - Project => [access_type:va
                                                                                                                                                                         $hashvalue_665 := "c
                                                                                                                                                                     - Filter[(("impersonatio
                                                                                                                                                                         - TableScan[hive:hiv
                                                                                                                                                                                 LAYOUT: hive
                                                                                                                                                                                 cntry_id_9 :
                                                                                                                                                                                 parent_geo_i
                                                                                                                                                                                 parent_geo_l
                                                                                                                                                                                 geo_id_12 :=
                                                                                                                                                                                 emp_id := Hi
                                                                                                                                                                                 access_type
                                                                                                                                                                                 parent_geo_n
                                                                                                                                                                                 parent_geo_l
                                                                                                                                                                                 impersonatio
                                                                                                                                 - LocalExchange[HASH] ("prod_level_362", "mkt_id_364", "cntr
                                                                                                                                     - Project => [mkt_id_27:varchar, prod_id_24:varchar, pro
                                                                                                                                         - RemoteExchange[REPARTITION] => mkt_id_27:varchar,
                                                                                                                                             - Project => [prod_id_24:varchar, agn_prod_id:va
                                                                                                                                                     $hashvalue_672 := "combine_hash"("combin
                                                                                                                                                     $hashvalue_671 := "combine_hash"("combin
                                                                                                                                                 - TableScan[hive:hive:allergan_insight_db:rp
                                                                                                                                                         LAYOUT: hive
                                                                                                                                                         cntry_id_21 := HiveColumnHandle{clie
                                                                                                                                                         agn_prod_id := HiveColumnHandle{clie
                                                                                                                                                         agn_prod_cd := HiveColumnHandle{clie
                                                                                                                                                         agn_prod_level := HiveColumnHandle{c
                                                                                                                                                         prod_id_24 := HiveColumnHandle{clien
                                                                                                                                                         prod_level_26 := HiveColumnHandle{cl
                                                                                                                                                         mkt_id_27 := HiveColumnHandle{client
                                                                                                                                                         agn_prod_nm := HiveColumnHandle{clie
                                                                                                             - LocalExchange[HASH] ("prod_level_370", "prod_id_372", "cntry_id_374", "mkt_id_
                                                                                                                 - Project => [cntry_id_46:double, prod_id_49:varchar, prod_level_51:varchar,
                                                                                                                     - RemoteExchange[REPARTITION] => cntry_id_46:double, prod_id_49:varchar,
                                                                                                                         - Project => [prod_level_51:varchar, $hashvalue_678:bigint, cntry_id
                                                                                                                                 $hashvalue_678 := "combine_hash"("combine_hash"("combine_has
                                                                                                                                 $hashvalue_679 := "combine_hash"("combine_hash"("combine_has
                                                                                                                             - Filter[("comp_flag" = CAST('N' AS VARCHAR))] => [cntry_id_46:d
                                                                                                                                 - TableScan[hive:hive:allergan_insight_db:rpt_d_prod, origin
                                                                                                                                         LAYOUT: hive
                                                                                                                                         cntry_id_46 := HiveColumnHandle{clientId=hive, name=
                                                                                                                                         prod_id_49 := HiveColumnHandle{clientId=hive, name=p
                                                                                                                                         prod_level_51 := HiveColumnHandle{clientId=hive, nam
                                                                                                                                         mkt_id_52 := HiveColumnHandle{clientId=hive, name=mk
                                                                                                                                         comp_flag := HiveColumnHandle{clientId=hive, name=co
                                                                                     - LocalExchange[HASH] ("team_id_378", "geo_id_380", "geo_level_id_382", "cntry_id_384") => team_id_74:va
                                                                                         - Project => [team_id_74:varchar, geo_level_id:double, cntry_id_71:double, geo_id_75:varchar, team_n
                                                                                             - RemoteExchange[REPARTITION] => team_id_74:varchar, geo_level_id:double, cntry_id_71:double, ge
                                                                                                 - Project => [geo_id_75:varchar, cntry_id_71:double, geo_level_id:double, team_nm:varchar, $
                                                                                                         $hashvalue_686 := "combine_hash"("combine_hash"("combine_hash"("combine_hash"(BIGINT
                                                                                                         $hashvalue_685 := "combine_hash"("combine_hash"("combine_hash"("combine_hash"(BIGINT
                                                                                                     - TableScan[hive:hive:allergan_insight_db:rpt_d_geo, originalConstraint = true] => [cntr
                                                                                                             LAYOUT: hive
                                                                                                             cntry_id_71 := HiveColumnHandle{clientId=hive, name=cntry_id, hiveType=double, h
                                                                                                             team_id_74 := HiveColumnHandle{clientId=hive, name=team_id, hiveType=string, hiv
                                                                                                             geo_id_75 := HiveColumnHandle{clientId=hive, name=geo_id, hiveType=string, hiveC
                                                                                                             geo_level_id := HiveColumnHandle{clientId=hive, name=geo_level_id, hiveType=doub
                                                                                                             team_nm := HiveColumnHandle{clientId=hive, name=team_nm, hiveType=string, hiveCo
                                                                 - LocalExchange[HASH] ("cntry_id_386", "emp_id_388") => cntry_id_92:double, emp_id_91:varchar, mstr_user_id:varchar, cntry_i
                                                                     - Project => [cntry_id_92:double, emp_id_91:varchar, mstr_user_id:varchar, cntry_id_386:double, emp_id_388:varchar, $has
                                                                         - RemoteExchange[REPARTITION] => cntry_id_92:double, emp_id_91:varchar, mstr_user_id:varchar, cntry_id_386:double, e
                                                                             - Project => [emp_id_91:varchar, cntry_id_92:double, $hashvalue_692:bigint, mstr_user_id:varchar]
                                                                                     $hashvalue_692 := "combine_hash"("combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("cntry_id_92"
                                                                                 - Filter[("mstr_user_id" = CAST('apoorva.dorai@zsassociates.com' AS VARCHAR))] => [emp_id_91:varchar, mstr_u
                                                                                     - TableScan[hive:hive:allergan_insight_db:rpt_d_user_securty, originalConstraint = (CAST('apoorva.dorai@
                                                                                             LAYOUT: hive
                                                                                             emp_id_91 := HiveColumnHandle{clientId=hive, name=emp_id, hiveType=string, hiveColumnIndex=2, pa
                                                                                             mstr_user_id := HiveColumnHandle{clientId=hive, name=mstr_user_id, hiveType=string, hiveColumnIn
                                                                                             cntry_id_92 := HiveColumnHandle{clientId=hive, name=cntry_id, hiveType=double, hiveColumnIndex=5
                                             - LocalExchange[HASH] ("team_id_390", "cntry_id_392", "time_id_394") => team_id_110:varchar, cntry_id_107:double, time_id_112:varchar, time_bckt
                                                 - Project => [team_id_110:varchar, cntry_id_107:double, time_id_112:varchar, time_bckt_type:varchar, time_nm:varchar, time_bckt_nm:varchar,
                                                     - RemoteExchange[REPARTITION] => team_id_110:varchar, cntry_id_107:double, time_id_112:varchar, time_bckt_type:varchar, time_nm:varchar,
                                                         - Project => [cntry_id_107:double, time_id_112:varchar, $hashvalue_697:bigint, team_id_110:varchar, time_bckt_type:varchar, time_nm:
                                                                 $hashvalue_697 := "combine_hash"("combine_hash"("combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("team_id_110"), 0)
                                                             - Filter[(("time_bckt_id_111" = 23.0) AND ("time_bckt_type" = CAST('Trend-Sales' AS VARCHAR)))] => [cntry_id_107:double, team_id
                                                                 - TableScan[hive:hive:allergan_insight_db:rpt_d_time_bckt, originalConstraint = ((23.0 = "time_bckt_id_111") AND (CAST('Tren
                                                                         LAYOUT: hive
                                                                         cntry_id_107 := HiveColumnHandle{clientId=hive, name=cntry_id, hiveType=double, hiveColumnIndex=0, partitionKey=fals
                                                                         team_id_110 := HiveColumnHandle{clientId=hive, name=team_id, hiveType=string, hiveColumnIndex=3, partitionKey=false}
                                                                         time_bckt_id_111 := HiveColumnHandle{clientId=hive, name=time_bckt_id, hiveType=double, hiveColumnIndex=4, partition
                                                                         time_id_112 := HiveColumnHandle{clientId=hive, name=time_id, hiveType=string, hiveColumnIndex=5, partitionKey=false}
                                                                         time_bckt_nm := HiveColumnHandle{clientId=hive, name=time_bckt_nm, hiveType=string, hiveColumnIndex=6, partitionKey=
                                                                         time_bckt_type := HiveColumnHandle{clientId=hive, name=time_bckt_type, hiveType=string, hiveColumnIndex=7, partition
                                                                         time_nm := HiveColumnHandle{clientId=hive, name=time_nm, hiveType=string, hiveColumnIndex=8, partitionKey=false}

(1 row)
(END)
`

**Comment by KBP-TDC** [comment]
This seems to be pretty complex query. Are stats computed on the tables?
Also, you should be looking at EXPLAIN ANALYZE to understand where is the biggest bottleneck in this query.

**Comment by RothA** [comment]
Came across this article that shows a few tweaks that may need to occur when running on EMR.  Worth a try? http://brandonharris.io/evaluating-big-data-performance-of-prestodb-and-parquet-on-s3-storage/
