### ISSUE TITLE
Incorrect handling of Dates in AccumuloRecordCursor#getLong

### ISSUE THREAD

**Issue by ducky427** [prestodb/presto#7492]
It seems that for a `java.sql.Date`, the [`getLong`](https://github.com/prestodb/presto/blob/master/presto-accumulo/src/main/java/com/facebook/presto/accumulo/io/AccumuloRecordCursor.java#L221) method of AccumuloRecordCursor returns the number of milliseconds, whereas it is expected to return the number of days. The latter behaviour can be seen in a similar method for [presto-jdbc](https://github.com/prestodb/presto/blob/master/presto-base-jdbc/src/main/java/com/facebook/presto/plugin/jdbc/JdbcRecordCursor.java#L161)

**Comment by ducky427** [comment]
If this is the correct assessment, I can submit a PR.

**Comment by electrum** [comment]
This looks like a correct assessment to me. The existing Accumulo tests in `TestAccumuloDistributedQueries` use dates, so I'm curious why they don't catch this.

cc @adamjshook

**Comment by adamjshook** [comment]
@ducky427 It correctly returns the number of days.

```presto:default> create table foo (id bigint, a date);
presto:default> insert into foo values (1, DATE '2016-01-01');
presto:default> select * from foo;
 id |     a      
----+------------
  1 | 2016-01-01 
```
The value stored in Accumulo is the number of days: `16801` in this case.
```
root@default> scan -t foo
\x08\x80\x00\x00\x00\x00\x00\x00\x01 ___ROW___:___ROW___ []    \x08\x80\x00\x00\x00\x00\x00\x00\x01
\x08\x80\x00\x00\x00\x00\x00\x00\x01 a:a []    \x08\x80\x00\x00\x00\x00\x00A\xA1
```

Printing the value of `java.sql.Date#getTime` when decoding this value returns the number of days `16801`:
```
System.out.println(new Date(new LongLexicoder().decode(decodeBytes("\\x08\\x80\\x00\\x00\\x00\\x00\\x00A\\xA1"))).getTime());
16801
```

**Comment by adamjshook** [comment]
On second look, it is working because it creates a new `Date` using the `long` constructor, passing it the number of days as if it were the number of milliseconds. The data is all correct but it doesn't align with what the `Date` API says it should be returning.  It should be updated to be less confusing.

**Comment by ducky427** [comment]
Thanks @adamjshook!
