### ISSUE TITLE
java.lang.IllegalArgumentException: left and right type do not match in comparison expression

### ISSUE THREAD

**Issue by wyukawa** [prestodb/presto#7496]
Hi

I use presto 0.167 + HDP 2.5.3 + hive connector

The following error occurred
```
java.lang.IllegalArgumentException: left and right type do not match in comparison expression (((CASE WHEN ("code" = BIGINT '1') THEN 'a' ELSE 'b' END) = 'aaa'))
```

table
```
desc test;		
code bigint
```

query
```
SELECT
a
FROM
(
SELECT
    case when code = 1 then 'a' else 'b' end as a
FROM test
UNION ALL
SELECT
    'aaa' as a
) WHERE  a = 'aaa'
```
This error doesn't occur in presto 0.166.

I guess https://github.com/prestodb/presto/commit/6ec736dd91753ad2566890d24205e5b35811b27b is related

And, there is no error in the following query in presto 0.167
```
SELECT
a
FROM
(
SELECT
    case when code = 1 then varchar 'a' else varchar 'b' end as a
FROM test
UNION ALL
SELECT
    'aaa' as a
) WHERE  a = 'aaa'
```

**Comment by erichwang** [comment]
@losipiuk, I have a PR to remove the check for now. Can you follow up here and see where the actual bugs are originating?

**Comment by losipiuk** [comment]
Fixed

**Comment by wyukawa** [comment]
Thanks!
