### ISSUE TITLE
Hardware requirement for Prestodb Server

### ISSUE THREAD

**Issue by jabonillomelvin** [prestodb/presto#7511]
Recommended
HDD?
CPU?
Memory

Minimum
HDD
CPU
Memory

**Comment by KBP-TDC** [comment]
http://teradata.github.io/presto/docs/current/system-requirements/hardware-requirements.html
We actually find it common to have 128-256GB of RAM per node, dual CPUs (8-16 cores), 10Gbps or Infiniband network.
Presto does not use it own storage really so standard HDD for HDFS or S3 in AWS work great.

**Comment by cawallin** [comment]
Closing this, let us know if you need any more assistance.
