### ISSUE TITLE
Add default_priority for query_priority scheduling policy

### ISSUE THREAD

**Issue by rongrong** [prestodb/presto#7521]
In resource group configuration, currently if we configure a group's scheduling policy to use `query_priority`, each of the query submitted to that resource group and its sub-groups need to provide a priority. This is inconvenient when managing sub-groups.

- Add a `defaultPriority` field to each sub-group if a group's scheduling policy is `query_priority`
- Validate that `defaultPriority` is configured when using `"schedulingPolicy": "query_priority"`
- When query submitted to a `query_priority` resource group does not provide a priority, use the default.

**Comment by electrum** [comment]
Is this a problem with the data model in the SPI, or with the `FileResourceGroup` implementation?

**Comment by rongrong** [comment]
Not sure what you mean. It's more like a adding a feature than fixing a problem I suppose. ResourceGroupSpec would have an additional input. Alternatively we can use "schedulingWeight" but that's probably more confusing.

**Comment by highker** [comment]
@martint @rongrong @electrum @haozhun @wenleix as discussed, what we need is a deterministic priority queue only for the current resource group (not its subgroups). Neither query_priority nor weighted scheduling policy can achieve this. We may introduce a new policy but that will be too adhoc. Leave the patch on hold for now until we figure out what exactly is needed.
