### ISSUE TITLE
Do you recommend to connect prestodb to mysql?

### ISSUE THREAD

**Issue by jabonillomelvin** [prestodb/presto#7526]
I want to implement this prestodb for big data query but the problem is that prestodb is so much slower than the native mysql. Mysql takes 20 seconds but for me this is already bad. For prestodb it took me so long I don't know what is the problem of it, about 1.46 minute.

Please tell me if there is a way to make my prestodb more faster. For now this is just a test feature having only 1 server with coordinator and worker node.

**Comment by dain** [comment]
The Presto connector for MySQL is designed for joining "dimension" data into big "fact" tables provided by another connector (e.g., Hive, Cassandra, Accumulo, etc).  The MySQL connector implementation uses a single JDBC connection per table per query.  The connector can only push down simple filters to the MySQL engine, so in many cases all of the data is streamed back to Presto.

So to answer the question "Do you recommend to connect prestodb to mysql?", absolutely for the right workload.

**Comment by jabonillomelvin** [comment]
@dain So having join queries is not recommended for this?

Situation is that there are two big tables joining and to be process in prestodb but it was so very slow.

**Comment by dain** [comment]
What I'm saying is the mysql connector is good for reading "small" amounts of data into a larger Presto query where the bulk of the data is coming from another system.  For example, you have large table of web visits in Hive, and you join in device information from a mysql database.  If you want to work exclusively with data in single mysql database, you are best off doing that in mysql itself.
