### ISSUE TITLE
SimplifyExpressions and DesugaringOptimizer doesn't process all expressions in tree

### ISSUE THREAD

**Issue by sopel39** [prestodb/presto#7527]
`SimplifyExpressions` and `DesugaringOptimizer` works only for project, filter and table scan. What about other nodes, e.g:

* arguments of aggregation function call
* Probably `ApplyNode` should also be handled (it contains assignments)
* join node filter function
* values node?

FYI: @martint @haozhun

**Comment by haozhun** [comment]
Arguments of aggregation function call should be fine? We pre-project them.

For values node, it looks like they're interpreted on the coordinator (I'm guessing based on how the explain plan looks like)? As a result, this shouldn't be a problem?

I agree with you that `ApplyNode` and join filter function are likely broken.

**Comment by sopel39** [comment]
Actually, `ApplyNode` is also fine probably. Expression can only be: `sym_a IN (sym_b), sym_a <= ANY(sym_b)` etc... It doesn't contain any lambda or timezone expression.

I think values don't have any complex expression either because those are projected above values node (e.g: in case of nondeterministic expressions)?

It's tricky though that we have to analyze each case separately and one has to understand what desugaring does. I wonder whether there is a way to make desugaring node independent?

**Comment by sopel39** [comment]
Fix: https://github.com/prestodb/presto/pull/7674

**Comment by haozhun** [comment]
This should remain open for now because https://github.com/prestodb/presto/pull/7674 will be partially backed out to fix trunk.

**Comment by sopel39** [comment]
Fixed by: https://github.com/prestodb/presto/pull/7779

**Comment by sopel39** [comment]
fixed
