### ISSUE TITLE
How to Calculate CPU and Memory utilization for Public Cloud accounting purpose?

### ISSUE THREAD

**Issue by garyelephant** [prestodb/presto#7554]
I can see Resource Utilization Summary in Presto Query Monitoring UI, is there any can tell me what does these metrics exactly mean:

(1) CPU Time, 
(2) Peak Memory
(3) Cumulative Memory

And if I want to charge for my customers by query level in presto deployed on public cloud, How can I calculate CPU and Memory consumption by a specific query ?

**Comment by cawallin** [comment]
You can use a custom EventListener to track resource utilization on a per-query basis (https://prestodb.io/docs/current/develop/event-listener.html). If you have further questions, please ask on the presto-users mailing list.
