### ISSUE TITLE
Provide examples for ARRAY and MAP functions

### ISSUE THREAD

**Issue by wenleix** [prestodb/presto#7555]
Current documents for Presto [ARRAY](https://prestodb.io/docs/current/functions/array.html) and [MAP](https://prestodb.io/docs/current/functions/map.html) functions are not so comprehensive: it only has the function signature and some text description. 

Providing some examples (as we did in [Lambda](https://prestodb.io/docs/current/functions/lambda.html) and [JSON](https://prestodb.io/docs/current/functions/json.html) will help user understand the function and drive the Presto adoption.

**Comment by renato2099** [comment]
Hi @wenleix  :)
I added the missing examples and wrote some comments on my [pr](https://github.com/prestodb/presto/pull/7557). If there is more to be done, I'd be happy to contribute.

**Comment by LeeHearn** [comment]
@renato2099 @haozhun
How can I help get this completed?
