### ISSUE TITLE
compile (default-compile) on project presto-jdbc-java6: Compilation failure: Compilation failure

### ISSUE THREAD

**Issue by saksim** [prestodb/presto#7568]
hello guys,
I promised i have followed each step of this project, however, several errors occur no matter which computer i used. The detailed errors as followed:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project presto-jdbc-java6: Compilation failure: Compilation failure:
[ERROR] bootstrap class path not set in conjunction with -source 1.6
[ERROR] /home/hadoop/presto-jdbc-java6/src/main/java/com/facebook/presto/jdbc/PrestoConnection.java:[59,7] error: PrestoConnection is not abstract and does not override abstract method getNetworkTimeout() in Connection
[ERROR] /home/hadoop/presto-jdbc-java6/src/main/java/com/facebook/presto/jdbc/PrestoDatabaseMetaData.java:[31,7] error: PrestoDatabaseMetaData is not abstract and does not override abstract method generatedKeyAlwaysReturned() in DatabaseMetaData
[ERROR] /home/hadoop/presto-jdbc-java6/src/main/java/com/facebook/presto/jdbc/PrestoResultSet.java:[72,7] error: PrestoResultSet is not abstract and does not override abstract method getObject(String,Class) in ResultSet
[ERROR] where T is a type-variable:
[ERROR] T extends Object declared in method getObject(String,Class)
[ERROR] /home/hadoop/presto-jdbc-java6/src/main/java/com/facebook/presto/jdbc/PrestoDriver.java:[32,7] error: PrestoDriver is not abstract and does not override abstract method getParentLogger() in Driver

BTW, each computer of my cluster as followed:
linux os：Centos7.2-64bit;
jdk：jdk-1.7.80
maven: 3.3.9
python: 2.7.5

Thanks for your reply in advance.

**Comment by saksim** [comment]
I had put an issue at:
https://github.com/prestodb/presto-jdbc-java6/issues/17
But nobody answered my question.
Does anyone have any idea about this issue?

Thanks

**Comment by cawallin** [comment]
I believe that the presto-jdbc-java6 project works only with Java 6, not Java 7. A Java 7 JDBC driver is available for free download from www.teradata.com/presto.

I'm closing this ticket, feel free to re-open it if you have further questions.

**Comment by saksim** [comment]
@cawallin Thanks for your response. It is relly helpful.

Actually, I do have a further question whether I can use java7 for higher PRESTO-version **(e.g. PRESTO-0.86+, which requares JDK8)** in the same way or not.

Thanks for your reply again.

**Comment by cawallin** [comment]
Yes, the Java 7 JDBC driver available for download can connect to Presto versions that run on Java 8.
