### ISSUE TITLE
[JDBC] ResultSetMetaData.getColumnClassName() gives java.lang.String for array types.

### ISSUE THREAD

**Issue by jaehc** [prestodb/presto#7574]
Hi, all.

There seems a somewhat confusing behavior in `ResultSetMetaData.getColumnClassName()` when it gives the class name for array types. It returns `java.lang.String.class.getName()`.
It is intuitively(surely, not for all people) to have `java.sql.Array.class.getName()` as a result value, rather than `java.lang.String.class.getName()`.
I've looked into the code `ResultSetMetaData.getColumnClassName()` and found out it tries to follow the logic the same as `javax.sql.rowset.RowSetMetaDataImpl.getColumnClassName()` which is the same case for hive jdbc as well.

Is this behavior intended?

Thanks for reading.

**Comment by electrum** [comment]
We just merged a fix this for this yesterday: https://github.com/prestodb/presto/commit/7dae00a72db6700d48efd9ac8407270951065e8a
