### ISSUE TITLE
Add `parse_duration` UDF

### ISSUE THREAD

**Issue by raghavsethi** [prestodb/presto#7578]
This would take in an airlift Duration string and return an interval.

**Comment by nezihyigitbasi** [comment]
Per our discussion with @raghavsethi, @wjiangiqx will work on this.

**Comment by nezihyigitbasi** [comment]
@wjiangiqx stopped working on this.

**Comment by nezihyigitbasi** [comment]
@janewangfb will work on this one.

**Comment by findepi** [comment]
`parse_duration` has been implemented
