### ISSUE TITLE
JOIN with criteria containing OR predicates may be slow

### ISSUE THREAD

**Issue by maciejgrzybek** [prestodb/presto#7581]
The join cannot create a lookup table for criteria with OR predicates, therefore they're executed as a filter.
E.g.
```sql
SELECT
    COUNT(*) FROM store_sales a, store_sales b
WHERE a.ss_item_sk = b.ss_item_sk
    AND (a.ss_sold_date_sk = b.ss_sold_date_sk OR a.ss_sold_date_sk = b.ss_sold_date_sk + 1);
```
performs much slower (3x on my laptop and sf1 TPC-DS data set) than equivalent
```sql
with x as (
    select * from store_sales a, store_sales b where a.ss_item_sk = b.ss_item_sk and a.ss_sold_date_sk = b.ss_sold_date_sk
  UNION
    select * from store_sales a, store_sales b where a.ss_item_sk = b.ss_item_sk and a.ss_sold_date_sk = b.ss_sold_date_sk + 1)
select count(*) from x;
```

Selectivity of `ss_item_sk` is pretty low, therefore JOIN becomes almost cross-join, then filter (with OR predicates) come to play but it has a lot to process what could be already filtered out in lookup phase.

The idea is to create multiple lookup tables. However, there's a drawback of such a solution, which is memory usage.

Until we have fully baked statistics, this solution should be feature-flagged and probably disabled by default. We can make a decision automatically once we have statistics.

**Comment by maciejgrzybek** [comment]
I'm going to work on that. If there are any comments, they're more than welcome. :)

**Comment by maciejgrzybek** [comment]
This rewrite works with the assumption that predicates are disjoint, which means the same row cannot satisfy both parts of `UNION` at the same time.
If it's possible, then we would need to add a negation of the other part of `UNION` in each side and use `UNION ALL` instead, e.g.:
 ```sql
with x as (
    select * from store_sales a, store_sales b where a.ss_item_sk = b.ss_item_sk and a.ss_sold_date_sk = b.ss_sold_date_sk AND NOT (a.ss_sold_date_sk = b.ss_sold_date_sk + 1)
  UNION ALL 
    select * from store_sales a, store_sales b where a.ss_item_sk = b.ss_item_sk and a.ss_sold_date_sk = b.ss_sold_date_sk + 1 AND NOT (a.ss_sold_date_sk = b.ss_sold_date_sk))
select count(*) from x;
```

**Comment by cawallin** [comment]
We shouldn't assume that the predicates are disjoint; the rewrite should include 
UNION ALL
select * from store_sales a, store_sales b where a.ss_item_sk = b.ss_item_sk and a.ss_sold_date_sk = b.ss_sold_date_sk + 1 AND (a.ss_sold_date_sk = b.ss_sold_date_sk))

If it always evaluates to false, other optimizers will remove that branch.

**Comment by maciejgrzybek** [comment]
This rewrite was only an example to illustrate how serious the performance problem is.
I assumed that the change of the JOIN operator is the way to go but maybe proper rewrite would be sufficient?

**Comment by maciejgrzybek** [comment]
@dain or @martint, do you have any opinions/preferences about the implementation of it?
I'd say I'd prefer rewrite for such an optimization as long as it's performance-wise identical to multi lookup join but I'm not convinced about it.

**Comment by maciejgrzybek** [comment]
The obvious advantage of multi lookup solution is when there're multiple OR predicates. Then, UNION-approach forces us to read data (table scan) many times.
E.g. three predicates with OR would produce 7 UNION selects. (3 UNIONs for 2 predicates).
Building multiple lookup tables can be done without additional data reads.

**Comment by maciejgrzybek** [comment]
@dain / @martint: do you have any thoughts on this?

**Comment by tooptoop4** [comment]
reopen
