### ISSUE TITLE
Do cleanup of local unassigned shards on Raptor node startup

### ISSUE THREAD

**Issue by AlekseiS** [prestodb/presto#7585]
Currently, local cleanup of unassigned shards on Raptor happens periodically and it takes several cycles of (interval + jitter) time to completely cleanup unassigned shards. Such process is necessary for periodic runs, but when node just starts up we can safely delete all unassigned shards and only wait for jittered amount of time before doing it.
The code is in `com.facebook.presto.raptor.metadata.ShardCleaner`, `cleanLocalShards()`method is a good starting point.

**Comment by AlekseiS** [comment]
cc @erichwang , @raghavsethi

**Comment by raghavsethi** [comment]
Closing, since fix is merged.
