### ISSUE TITLE
presto cassandra count error

### ISSUE THREAD

**Issue by fredxie26** [prestodb/presto#7592]
Hi all,

I am currently facing an error that really confused me.
I have a large chunk of data stored on Cassandra (126,692,361 rows). I did a select count(*) from cqlsh. Although it took about 2 hours for the count to finish, but the result is correct.

I did the same thing from presto. It took about 20 mins, but the result is wrong. The number is 253,384,722, which is exactly double as the result from cql.

When I did this for smaller size of data(eg: 20000 rows), presto shows the right number as expected.
Could anyone tell me what`s wrong with the Cassandra connector?
Thanks.

**Comment by cawallin** [comment]
Can you give us more information (your data, ideally, but also the # partitions, schema, etc)? It's hard to say what's wrong if we don't know those things.

**Comment by fredxie26** [comment]
Hi cawallin,

Thanks for replying. My cassandra keyspace and table schema are as following:

create keyspace test with replication = {'class': 'SimpleStrategy', 'replication_factor': 1};

CREATE TABLE card_test (
  area_id TEXT,
  city_id TEXT,
  device_id TEXT,
  created_date timestamp,
  card_no TEXT,
  PRIMARY KEY ((area_id, city_id , device_id), card_no , created_date)
)WITH CLUSTERING ORDER BY (card_no ASC, created_date ASC);

The Presto version we used is 0.159. Thanks

**Comment by fredxie26** [comment]
Hi cawallin,

I tested the problem again using the newest release version 0.169 and the problem is resolved, count result is correct. The issue only appears in 0.159. Thanks.

**Comment by cawallin** [comment]
Great! Glad that's working now. I'll close this ticket then.
