### ISSUE TITLE
map_values variant that return an array of values sorted by key

### ISSUE THREAD

**Issue by haozhun** [prestodb/presto#7597]
Do we want to add such a function?

Alternatively, it could be achieved by
* Turning the map into array of rows (which we don't have today)
* Sorting the array of row (ideally, with a custom comparator, which we don't support today)
* Transform the array with lambda to drop the key

**Comment by nezihyigitbasi** [comment]
Another way to accomplish this is:

```
presto:sf10000> select array_agg(value) from (
             -> select value from unnest(map(array['b', 'c', 'a'], array[1,2,3])) T(key,value) order by key
             -> );
   _col0
-----------
 [3, 1, 2]
(1 row)

```

**Comment by haozhun** [comment]
The problem with unnest is that in real queries, it tend to involve group by.
