### ISSUE TITLE
How to configure Presto searches to be case-insensitive?

### ISSUE THREAD

**Issue by felarof99** [prestodb/presto#7605]
In my case, Presto connects to a MySQL database which has been configured to be case-insensitive. But any search through Presto seems to be case-sensitive.

**Questions:**
1) Is there a way to configure Presto searches to be case-**in**sensitive? If not, can something be changed in the Presto-MySQL connector to make the searches case-insensitive?

2) If underlying DB is case-insensitive, shouldn't Presto searches also be case-insensitive? (I presume that Presto only generates the query plan and the actual execution happens on the underlying database)

Example: Consider the below table on MySQL.

| name |
|------|
| adam |
| Alan |

select * from table where name like '%a%'
// returns adam, Alan on MySQL
// returns only adam on Presto

select * from table where name = 'Adam'
// returns adam on MySQL
// returns NIL on Presto

**Comment by felarof99** [comment]
Can someone please help with this? Thank you.

**Comment by dain** [comment]
This is not currently possible with Presto.  There is a feature of ANSI SQL called *collation* that I think would allow for this kind of processing, but it is not something we have on our roadmap to implement.  In the mean time, I suggest you use `lower` or a case insensitive regular expression (https://prestodb.io/docs/current/functions/regexp.html).
