### ISSUE TITLE
Implement an exists() lambda function

### ISSUE THREAD

**Issue by amitna1r** [prestodb/presto#7614]
The requirement is for a lambda function as below:
```
    exists(array<T>, function<T, boolean>) → boolean
```

Currently this can be achieved using filter as:
```
    filter(array<T>, function<T, boolean>) <> array[]
```

However using filter is not efficient, since it needs to parse all values. exists() would make it much more efficient.

**Comment by wenleix** [comment]
`reduce` can be used for better efficiency. For example, the following statement will do `exists(ARR, x->x=2)`:

```
select reduce(ARRAY[1, 2, 3, 4, 5], false, (exist, x) -> exist OR (x = 2), x->x);
-- true
```

**Comment by amitna1r** [comment]
@wenleix, this is a good idea.
However I guess it will still loop through all elements once, although it will not evaluate the comparison once it finds a match.
