### ISSUE TITLE
Supporting for OR expression in TupleDomain

### ISSUE THREAD

**Issue by Praveen2112** [prestodb/presto#7616]
In general for Presto Connector , the `com.facebook.presto.spi.predicate.TupleDomain` (#7219,)has 

>      * TupleDomain is internally represented as a normalized map of each column to its
>      * respective allowable value Domain. Conceptually, these Domains can be thought of
>      * as being AND'ed together to form the representative predicate.

We had implemented a version which would support "OR" expression also.These are the list of changes we did..

1.Modified the TupleDomain which would now hold a TupleExpression object(An abstract class with seperate implementation for **AND** and **OR** operator) instead of holding a Map of ColumnHandle and its Domain.

2.Created a TupleExpressionVisitor using which we could traverse through the TupleExpression.

3.Created a new DomainTranslator which would translate the FilterPredicate to the TupleExpression.

4.Created a custom serializer and deserializer for the TupleExpression and linked it to the HandleResolver for Jackson.

5.We have created a new Implementaion for OrcPredicate which would now use the TupleExpression for determinig list of stripes and row groups that has to be processed.

6.Some changes in the optimizer for supporting this change.

These are list of changes we did . Is this a right approach to solve this problem ?. Would there be any issues in this implementation. As of now we are not getting any issues in this implementation.

**Comment by maciejgrzybek** [comment]
Relates to https://github.com/prestodb/presto/issues/5861.

**Comment by Praveen2112** [comment]
@maciejgrzybek we have an implementation which supports the OR expression in TupleDomain. Is your workaround is similar to this implementation?? Would there be any issues in this implementation ?

**Comment by maciejgrzybek** [comment]
@Praveen2112 I'm not saying there is any competing solution. I was simply linking issues to emphasize it could be a duplicate (of issues, not implementations).

I see one potential problem. How do you communicate from the connector if your connector can satisfy the constraint only partially?
Does connector have to rebuild the `TupleExpression` (which I believe is a tree of `TupleDomain`) to express what part of it is satisfied? It seems a bit more complicated than you described.

**Comment by Praveen2112** [comment]
Anyways a filter operation will occur on the top of the TableScan node. In case of querying over ORC files in hive connector , in the new implementation we will process only the stripes whose statistics satisfy the criteria. As of now we have handled only for the criteria which are handled in TupleDomain (Filter expression which can be translated to TupleDomain, can be expressed as TupleExpression even if it has a OR condition )

**Comment by Praveen2112** [comment]
@martint , @dain Will the above implementation will properly scale or will there be any issues ?
