### ISSUE TITLE
Detect failed node for communication error

### ISSUE THREAD

**Issue by wenleix** [prestodb/presto#7618]
When a node failed during the query execution, often `TOO_MANY_REQUEST_FAILED` (on coordinator) or `PAGE_TRANSPORT_TIMEOUT` (on worker) are thrown. 

Once the coordinator see such errors, it should consult `FailureDetector`, and if the targeting node is a known failed node, we should thrown an `NODE_FAILED_DURING_QUERY_EXECUTION` (name TBD) error instead. This could help diagnose whether a query failure is an Presto software issue, or an hardware issue. 

We need to rewrite the failure reason for these two types of exceptions.

**Comment by dain** [comment]
I believe @electrum wanted something like `HOST_UNREACHABLE`.

**Comment by wenleix** [comment]
We can add an optional destination URI into `ExecutionFailureInfo`.

For `PAGE_TRANSPORT_TIMEOUT`, it will be constructed into `ExecutionFailureInfo` in `SqlTask.createTaskStatus`. For all the case, we should just extract the optional destination URI at `Failures.toFailure`

**Comment by wenleix** [comment]
We will adding a `getStatus` method which takes the hostname and the port in `FailureDetector`. `FailureDetector` now needs to have more detailed status (`UNRECHABLE`, `NOT_RESPONDING`, `LOOKS_GOOD`)

**Comment by wenleix** [comment]
We should reuse the [ping method](https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/failureDetector/HeartbeatFailureDetector.java#L311) in `HeartbeatFailureDetector`. The exception thrown on `httpClient` are:

- `java.net.SocketTimeoutException: Connect Timeout` if the destination is unreachable (banned by firewall, etc).
- 'java.net.ConnectException: Connection refused`: If we ping some random unopened port.
- `org.eclipse.jetty.client.HttpResponseException: HTTP protocol violation`: If we ping on a non-HTTP port (e.g. 22)
