### ISSUE TITLE
Optimize count queries for fixed cardinality

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#7628]
Consider the following query:
```sql
SELECT count(*) FROM (
  SELECT sum(orderkey) FROM orders
)
```
We can turn this query into a static `VALUES (1)` at planning time since we know the subquery will always return one row.

**Comment by navinvishy** [comment]
I'm interested in working on this. I guess this also applies to max(),min() etc. I'm assuming this needs to be done in the optimization phase. Would it be something along the lines of [EmptyDeleteOptimizer](https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/EmptyDeleteOptimizer.java)?
Any pointer to code that does something related would be very useful!

**Comment by martint** [comment]
Take a look at the rules in https://github.com/prestodb/presto/tree/master/presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule for some examples.

**Comment by navinvishy** [comment]
Great! Thanks, that's useful. I'll start looking at this.
