### ISSUE TITLE
Create authentication plugin for basic auth and move out LDAP

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#7632]
The current [LDAP](https://prestodb.io/docs/current/security/ldap.html) support has two parts:

1. Infrastructure in `LdapFilter` to support basic authentication using user/password.
2. LDAP-specific logic to authenticate a user/password.

We should split this up so that second part is in a plugin, allowing other types of authenticators, such as a list of usernames and passwords stored in a file (using PBKDF2 or similar). The LDAP code would be moved into a plugin.

The new plugin can be modeled after `SystemAccessControl`. We'll have a `BasicAuthenticatorFactory` that creates a `BasicAuthenticator` and allow a single instance configured using `etc/basic-authenticator.properties`. 

The interface only needs one method (for now):
```java
public interface BasicAuthenticator
{
    /**
     * Authenticate the provided user and password.
     *
     * @return the authenticated entity
     * @throws AccessDeniedException if not allowed
     */
    Principal createAuthenticatedPrincipal(String user, String password);
}
```

**Comment by anderk57** [comment]
What is the status of this?  Can you merge https://github.com/quantopian/presto/commit/254825c63d6bbe6f1b15c343d8ad1517fb3c1554 to mainline or are you waiting for it to be properly refactored to a plugin?

**Comment by RamonReis** [comment]
Hello there!
I'm willing to address this issue but that's the first time that I do this kind of thing. Are there any tips that'd help me solve this issue?
This'd be a learning experience for me.
Ty in advance.
