### ISSUE TITLE
Support index acess for Row Type

### ISSUE THREAD

**Issue by wenleix** [prestodb/presto#7640]
Today we only support access by field for Row Type. For row types without field types, we have to first cast it into a Row with field names:

```
presto > select CAST(v AS ROW(f1 BIGINT, f2 VARCHAR)).f1 
from (VALUES ROW(ROW(1, 'a')), ROW(ROW(2, 'b'))) AS t(v);

 _col0
-------
     1
     2
(2 rows)
```

It will be nice to support index access, i.e. `v[1]` will return the first field of the row.

**Comment by geraint0923** [comment]
Good idea! But I think we should only allow constant index, otherwise it will be hard to infer the field type.

**Comment by wenleix** [comment]
Related PR for `.` operator:

https://github.com/prestodb/presto/pull/3636
https://github.com/prestodb/presto/pull/2378

**Comment by wenleix** [comment]
Looking at how PostgreSQL and Oracle solve the problem.  In Postgre SQL,  the row constructor will construct an `record`:
```
wxie=# select pg_typeof(ROW('x',1));                                                     

pg_typeof 
-----------
 record
```

The composite type stored in table has its own type name. If I understand correctly, the only way to extract specific field from an unnamed record is to cast it into a defined `composite type` , e.g. http://stackoverflow.com/questions/4700661/how-can-i-extract-the-values-from-a-record-as-individual-columns-in-postgresql  :


```
CREATE TYPE my_type AS (
   f1 VARCHAR,
   f2 INTEGER
);

WITH tmp AS
(
	SELECT ROW('x', 1) x
	UNION ALL
	SELECT ROW('y', 2) x
	UNION ALL
	SELECT ROW('z', 3) x
)
SELECT (x::text::my_type).f2 FROM tmp
```


Would like to hear any comments/suggestions from people who are more familiar with PostgreSQL :).

**Comment by wenleix** [comment]
In Oracle, the `RECORD` type always have `FieldName`: https://docs.oracle.com/cd/B28359_01/appdev.111/b28370/record_definition.htm#LNPLS01338, https://docs.oracle.com/cd/B28359_01/appdev.111/b28370/collections.htm#BABHHJGA. 

Previous SQL engine doesn't have the same flexibility as Presto to get unnamed RowType. As such, accessing field in unnamed RowType is not a pain point for them.

We plan to add constant subscript access support for RowType in Presto

**Comment by electrum** [comment]
Index access seems strange given that it must be constant. It's really a tuple, not an array. What about generating well-known synthetic field names? For example, f1, f2, or c1, c2, etc. This makes it obvious they are constant field accesses and not array accesses.

**Comment by wenleix** [comment]
@electrum We probably want to use something that cannot be a legal field name then :). What about `."$field1"`, `."$field2"` then? (Similar to the hidden bucket column name).

**Comment by electrum** [comment]
No, you want it to be easy to access. There's no problem with conflicts since you can't have a partially anonymous row. They're either all named or none are.

**Comment by martint** [comment]
That's not true. They type of a "relation" is multiset(row(...)). If that relation is a subquery, some fields may be unnamed (e.g., if they are the result of some complex expression and don't have an alias)

**Comment by martint** [comment]
I think we should hold off adding this feature for now. I really don't like the idea of adding synthetic fields with some arbitrary name, and the subscript operator version has enough edge cases and potential complications that we need to think about it very carefully.
