### ISSUE TITLE
"Column not resolved" if use of alias column with having clause

### ISSUE THREAD

**Issue by ebuildy** [prestodb/presto#7656]
- java version "1.8.0_77"
- Presto CLI 0.161
- hive.parquet.use-column-names=true
- connector.name=hive-hadoop2

``HAVING`` clause seems not recognize alias column (maybe because the ``hive.parquet.use-column-names`` option?):

```
presto:default> SELECT COUNT(*) as ct, data_query FROM datahub WHERE name = 'click_serp' AND data_type = 'serp' GROUP BY data_query HAVING ct > 10 ORDER BY ct DESC LIMIT 10;

Query 20170323_101118_00005_gjee5 failed: line 1:124: Column 'ct' cannot be resolved
```

But if I remove the HAVING clause, it works fine:

```
presto:default> SELECT COUNT(*) as ct, data_query FROM datahub WHERE name = 'click_serp' AND data_type = 'serp' GROUP BY data_query ORDER BY ct DESC LIMIT 10;

Query 20170323_101128_00006_gjee5, RUNNING, 3 nodes, 954 splits
....
```

**Comment by losipiuk** [comment]
cc: @findepi, @sopel39

**Comment by sopel39** [comment]
According to SQL standard, `WHERE` and `HAVING` don't have access to output columns. Only `ORDER BY` has.

**Comment by ebuildy** [comment]
Ho I see, this is because I "try" query first on a small sample running on mySQL, and mySQL seems permit that (sqlmode_only_full_group_by).

Very sorry for that, thanks you for your time.
