### ISSUE TITLE
what is the rule about ImportOrder 

### ISSUE THREAD

**Issue by zhangxin0112** [prestodb/presto#7657]
i want to add new a connector ,but i found some problems about maven checkstyle .
for example. code in my a.java

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Collections;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Collection;

i build the porject , error messages:
[ERROR] src/main/java/com/facebook/presto/elasticsearch/EsRecordCursor.java:[29] (imports) ImportOrder: Wrong order for 'java.util.Collections' import.
[ERROR] src/main/java/com/facebook/presto/elasticsearch/EsRecordCursor.java:[33] (imports) ImportOrder: Wrong order for 'java.util.Collection' import.

question:
how can i know the importorder .hope your help.

**Comment by yuananf** [comment]
This is the code style that presto uses:
https://github.com/airlift/codestyle

**Comment by ArturGajowy** [comment]
@zhangxin0112 the import order is enforced by the following checkstyle rule:

```
        <module name="ImportOrder">
            <property name="groups" value="*,javax,java" />
            <property name="separated" value="true" />
            <property name="option" value="bottom" />
            <property name="sortStaticImportsAlphabetically" value="true" />
        </module>
```

Unfortunately, it's not too explicit and in my case I had to refer to checkstyle's docs to make sense of how to fix my case. See here: http://checkstyle.sourceforge.net/config_imports.html#ImportOrder

BTW, what connector are you working on? Elasticsearch?

Hope this helps!

**Comment by zhangxin0112** [comment]
Thanks u. I will retry. Ye.i am working it.
