### ISSUE TITLE
db/TestQueues.testBasic is nondeterministic

### ISSUE THREAD

**Issue by jessesleeping** [prestodb/presto#7667]
db/TestQueues.testBasic sometimes fails due to a race condition. Tests that have the similar wait-assert pattern can have the same issue.

In ``db/TestQueues.testBasic`` we call [``waitForQueryState()``](https://github.com/prestodb/presto/blob/3e7fb92bbbb65dda7ae60d3c4edc635c077e87ad/presto-tests/src/test/java/com/facebook/presto/execution/resourceGroups/db/TestQueues.java#L248) to wait until a query is running. This function directly checks the state machine of a query. However, [a following assertion](https://github.com/prestodb/presto/blob/3e7fb92bbbb65dda7ae60d3c4edc635c077e87ad/presto-tests/src/test/java/com/facebook/presto/execution/resourceGroups/db/TestQueues.java#L99) checks a counter maintains by the state change listener. It's possible that after a state change happens, the listener has not been triggered or has not finished at the point we are checking the assert. Such a race condition causes the related test (not only the TestQueues.testBasic) to be nondeterministic (see [error log here](https://s3.amazonaws.com/archive.travis-ci.org/jobs/213531979/log.txt)).

To reproduce the issue, one can comment out [this line](https://github.com/prestodb/presto/blob/3e7fb92bbbb65dda7ae60d3c4edc635c077e87ad/presto-tests/src/test/java/com/facebook/presto/execution/resourceGroups/db/TestQueues.java#L253) to increase the possibility of the failure.

**Comment by jessesleeping** [comment]
I will work on this issue and submit a PR soon :)

**Comment by cawallin** [comment]
Fixed by  #7677 (cc @jessesleeping, re-open if that's not the case)
