### ISSUE TITLE
Validate or filter layouts returned from connectors

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#7668]
`ConnectorMetadata.getTableLayouts()` is passed a list of `desiredColumns` which are the columns the engine needs from the layout. What happens if the connector returns a layout that doesn't contain all the columns?

The contract here isn't clear. We should clarify if this is an error or not in the Javadoc for the method, then add code in `MetadataManager` to either filter list or throw an error.

There is code in `AddExchanges` that does filtering, but other places do not. That code should be moved to `MetadataManager` (and possibly changed to be validation rather than a filter) so that all callers get the same behavior.

@martint, @erichwang thoughts?

**Comment by erichwang** [comment]
Yup, I agree that we should document the behavior and consolidate code in MetadataManager. As for the specifics, I don't have any particular preference as to whether it is considered an error or silently managed. In either case, it should be just as easy to implement. Maybe do it on the presto side to make it a bit easier for connectors?

**Comment by jessesleeping** [comment]
Based on the logic in ``AddExchanges.java`` ([here](https://github.com/prestodb/presto/blob/d4e08bfd026d2ef44a38d335ba506b7a73f32b44/presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/AddExchanges.java#L580)) , we return a ``PlanWithProperties`` object if the result from ``MetadataManager.getLayouts()`` is an empty list. If the result is not empty and no layout in the result contains all the required columns, we throw an exception via the ``checkState()`` call. Now if we want to keep this logic and move the filter/validation code into ``MetadataManager``, how can we know whether the result is originally empty or it becomes empty after being filtered?
