### ISSUE TITLE
Where can i find all release download link ?

### ISSUE THREAD

**Issue by chenliang613** [prestodb/presto#7671]
In Installing Presto section, only provides the download for 0.170 as below, but i want to download 0.166, when can i find all release download link ? 
------------------
Download the Presto server tarball, presto-server-0.170.tar.gz, and unpack it. The tarball will contain a single top-level directory, presto-server-0.170, which we will call the installation directory.

**Comment by chenliang613** [comment]
https://repo1.maven.org/maven2/com/facebook/presto/presto-server/

i suggest adding the link to presto's documentation.

**Comment by electrum** [comment]
You can change "current" to any version in the docs URL: https://prestodb.io/docs/0.166/

Also, as mentioned, every Presto release artifact is available forever in Maven Central.
