### ISSUE TITLE
Postgresql connector: Doesn't support create statements

### ISSUE THREAD

**Issue by zmhassan** [prestodb/presto#7673]
Hi,

Just wanted to double check but postgresql connector doesn't support create operations right?
Got this error:
```
presto:sales> CREATE TABLE distributors ( id integer , name varchar(40) );
Query 20170326_173757_00078_mncty failed: This connector does not support creating tables
```

**Comment by cawallin** [comment]
If you look at the limitations section, the fact that postgresql doesn't support CREATE is listed in the docs: https://prestodb.io/docs/current/connector/postgresql.html.

**Comment by zmhassan** [comment]
Thanks.
