### ISSUE TITLE
LDAP product tests fail with Docker for Mac

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#7676]
The Presto server fails to start because it can't talk to the LDAP server. It's not clear if this is due to a network configuration problem with Docker or because the LDAP server is not starting or dies after starting.

```
2017-03-23T18:39:21.223Z	ERROR	main	com.facebook.presto.server.PrestoServer	Unable to create injector, see the following errors:
 
 1) Error injecting constructor, java.lang.RuntimeException: javax.naming.CommunicationException: ldapserver:636 [Root exception is java.net.ConnectException: Connection refused]
   at com.facebook.presto.server.security.LdapFilter.<init>(LdapFilter.java:92)
   while locating com.facebook.presto.server.security.LdapFilter
   at com.facebook.presto.server.security.ServerSecurityModule.lambda$setup$3(ServerSecurityModule.java:53) (via modules: com.facebook.presto.server.security.ServerSecurityModule -> io.airlift.configuration.ConditionalModule -> com.facebook.presto.server.security.ServerSecurityModule$$Lambda$27/333693383)
   while locating javax.servlet.Filter annotated with @com.google.inject.multibindings.Element(setName=@io.airlift.http.server.TheServlet,uniqueId=336, type=MULTIBINDER, keyType=)
   at io.airlift.http.server.HttpServerModule.configure(HttpServerModule.java:68) (via modules: io.airlift.http.server.HttpServerModule -> com.google.inject.multibindings.Multibinder$RealMultibinder)
   while locating java.util.Set<javax.servlet.Filter> annotated with @io.airlift.http.server.TheServlet()
     for parameter 4 at io.airlift.http.server.HttpServerProvider.<init>(HttpServerProvider.java:72)
   while locating io.airlift.http.server.HttpServerProvider
   at io.airlift.http.server.HttpServerModule.configure(HttpServerModule.java:64)
   while locating io.airlift.http.server.HttpServer
 Caused by: java.lang.RuntimeException: javax.naming.CommunicationException: ldapserver:636 [Root exception is java.net.ConnectException: Connection refused]

**Comment by sanjay990** [comment]
@electrum : Can you confirm if you have entry for `ldapserver` in `/etc/hosts`
https://github.com/prestodb/presto/tree/master/presto-product-tests#os-x-using-docker-for-mac-macos-10103-yosemite-or-newer-preferred-way

**Comment by electrum** [comment]
@sanjay990 I didn't setup any of these entries, but they shouldn't be required for running tests, only if you want to debug in IntelliJ or otherwise connect to them from outside Docker (from the Mac host). All the other tests work fine without them.

**Comment by electrum** [comment]
I'm not very familiar with Docker, so this might be fine, but I notice that the LDAP container doesn't have any ports listed, while all the other containers do:
```
[dphillips@laptop:~] docker ps
CONTAINER ID        IMAGE                                           COMMAND                  CREATED             STATUS              PORTS                                                                                                                                                                                                                                                                                                           NAMES
b3b70f691a69        teradatalabs/centos6-java8-oracle-openldap:14   "/bin/sh -c /tmp/f..."   2 minutes ago       Up 2 minutes                                                                                                                                                                                                                                                                                                                        common_ldapserver_1
0d003cbc39d3        mysql                                           "docker-entrypoint..."   2 minutes ago       Up 2 minutes        3306/tcp, 0.0.0.0:13306->13306/tcp                                                                                                                                                                                                                                                                              common_mysql_1
90f8d2e4e3ca        postgres                                        "/docker-entrypoin..."   2 minutes ago       Up 2 minutes        5432/tcp, 0.0.0.0:15432->15432/tcp                                                                                                                                                                                                                                                                              common_postgres_1
e39ee81b102a        cassandra:3.9                                   "/docker-entrypoin..."   2 minutes ago       Up 2 minutes        7000-7001/tcp, 7199/tcp, 9160/tcp, 0.0.0.0:9042->9042/tcp                                                                                                                                                                                                                                                       common_cassandra_1
326a3b3f5566        teradatalabs/cdh5-hive:14                       "/bin/sh -c /root/..."   2 minutes ago       Up 2 minutes        1004/tcp, 0.0.0.0:1180->1180/tcp, 1006/tcp, 8030-8033/tcp, 0.0.0.0:8020->8020/tcp, 0.0.0.0:8088->8088/tcp, 0.0.0.0:9000->9000/tcp, 0.0.0.0:9083->9083/tcp, 8040-8042/tcp, 10020/tcp, 19888/tcp, 50010/tcp, 0.0.0.0:10000->10000/tcp, 0.0.0.0:50070->50070/tcp, 50020/tcp, 50470/tcp, 0.0.0.0:50075->50075/tcp   common_hadoop-master_1
```

**Comment by maciejgrzybek** [comment]
@electrum: We've just tried this on Docker Version 17.03.0-ce-mac2 (Docker for Mac).
`presto-product-tests/bin/run_on_docker.sh singlenode-ldap -g ldap_cli`
returned:
```
2017-03-27 20:08:05 INFO: Completed 15 tests
2017-03-27 20:08:05 INFO: 15 SUCCEEDED      /      0 FAILED      /      0 SKIPPED
2017-03-27 20:08:05 INFO: Tests execution took 21.9 seconds

===============================================
tempto-tests
Total tests run: 15, Failures: 0, Skips: 0
===============================================
```

Can you make sure you have enough memory assigned to the docker service?
Please go to the docker preferences > advanced > memory.
By default it's 2 GB which, as we realized, is not sufficient.
My configuration is 8 GB of memory for docker VM and I don't have `/etc/hosts` configured for debugging, so as you.

We also tried to reproduce your scenario by not starting docker container with LDAP server. However, the error was slightly different (`javax.naming.CommunicationException: ldapserver:636 [Root exception is java.net.UnknownHostException: ldapserver]`) instead of `connection refused`.
Please confirm that your problem is not connected with insufficient memory before we dive into details more.

If it's not a problem with memory (after you increase the limit the problem persists), please try running product tests with `export LEAVE_CONTAINERS_ALIVE_ON_EXIT=true`. This will prevent tearing down the containers. Then, please do `docker ps`, once you hit the error, and confirm that `common_ldapserver_1` is on the list. If not, then we have to understand why it's dead or didn't even start in the first place (which does not happen on my environment).

---

Speaking of exposed ports which you don't see in the `docker ps`, they are not needed unless you want to connect to the container from outside of docker (e.g. when debugging in IntelliJ having a Hadoop cluster in docker).

**Comment by maciejgrzybek** [comment]
In addition to my env (Docker for Mac), we also tried on Docker Toolbox and Docker running natively on Linux. This worked just fine on all the environments.

**Comment by electrum** [comment]
@maciejgrzybek Thanks! I had forgotten to increase the Docker memory on my new laptop. Increasing to 4GB from the default 2GB fixed it. We should update the README, since we only mention memory for the old Docker Toolbox.

**Comment by sanjay990** [comment]
@electrum : I'll update the README
