### ISSUE TITLE
Flaky tests that rely on async counters/variables

### ISSUE THREAD

**Issue by jessesleeping** [prestodb/presto#7689]
Test cases like [``AbstractTestDistributedQueries.testQueryLoggingCount``](https://github.com/prestodb/presto/blob/de1e6782eb843d67298fcfb66ebea2740b6f06ee/presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestDistributedQueries.java#L712) assert on a counter that is updated by a query state change listener. There is a race condition between the assertion on the counter and the execution of the listener (similar issue here #7667). 

To reproduce the problem, one can manually add a sleep in the listener callback (e.g. sleep 10ms [here](https://github.com/prestodb/presto/blob/16cd00b9b74b7f2532df55fad9d9cecf1ec3dd42/presto-main/src/main/java/com/facebook/presto/execution/SqlQueryManager.java#L393)).

**Comment by jessesleeping** [comment]
A possible solution can be switching to a wait-timeout pattern instead of the one-shot assertion (see #7677). However, this can slow down the entire CI test.

My opinion is that we should not assert on those async counter/variable in the unit tests. Because they are designed for monitoring usage (e.g. dashboards, cli) and can be stale.

**Comment by losipiuk** [comment]
duplicates #8953
