### ISSUE TITLE
Where is SqlBaseBaseVisitor<Node>?

### ISSUE THREAD

**Issue by hshe233** [prestodb/presto#7708]
In presto.sql.parser there is
class AstBuilder
        extends SqlBaseBaseVisitor<Node>

There is no SqlBaseBaseVisitor generated by ANTLR. Where can I find it?

**Comment by ebyhr** [comment]
I think you can find here.
`presto/presto-parser/target/generated-sources/antlr4/com/facebook/presto/sql/parser`

Or you can move there with Ctrl + B on AstBuilder's `SqlBaseBaseVisitor` if you use intelliJ IDEA.

**Comment by hshe233** [comment]
I have built lisenter type.. now i get the visitor ones by modifying the generate configuration..
