### ISSUE TITLE
Intermittent failures in TestHiveDistributedQueries.testQueryLoggingCount

### ISSUE THREAD

**Issue by losipiuk** [prestodb/presto#7709]
We saw query count to be 5 while test expects it to be 4.
My guess it is because tests from `TestHiveDistributedQueries` are run in parallel and query from another test was counted.

Is there a way to specify that one of the tests must be run on its own (not in parallel with others) in TestNG?

**Comment by electrum** [comment]
The exclusive aspect should already be handled by the `executeExclusively()` which acquires an exclusive lock on the query runner. Everything that runs a query acquires a shared locked.

**Comment by flakycov** [comment]
FYI - We have also seen this flaky failure (```java.lang.AssertionError: expected [4] but found [5]```)

**Comment by findepi** [comment]
Duplicates #8953
