### ISSUE TITLE
Parquet ROW Type Does Not Support Schema Evolution

### ISSUE THREAD

**Issue by fbertsch** [prestodb/presto#7713]
We use `ROW` types for a lot of Json data the we put into parquet format and read from Presto. One issue we have run into is that general schema evolution rules do not apply to ROW types; that is, we can't add new fields to a `ROW` type and expect previous schemas to still be applicable.

Note: we set `hive.parquet.use-column-names=true`.

# Test Case

For an example of this, see [0]. We have outlined many of the forms of schema evolution we use, and the last two are adding and removing elements from a `ROW` type. Note the schema evolution for the "Nested Row Type - Adding a Subcolumn" is the following:

```
message example {
    required group nested {
        required binary id (UTF8);
        required binary exists (UTF8);
    }
}
```

to

```
message example {
    required group nested {
        required binary id (UTF8);
        required binary exists (UTF8);
        required binary added (UTF8);
    }
}
```

# Result

it errors with `Schema mismatch, metastore schema for row column nested has 3 fields but parquet schema has 2 fields`.

The issue comes from [1], which prevents differing `STRUCT` types from having different numbers of elements from the Hive metastore schema.

# Expected Result

We expected that the `ROW` type have schema evolution similar to that of adding a new column; old parquet files without the column just have `NULL` for the value. New files with the column can be read with the old.

We propose letting nested `ROW` types have the same rules of schema evolution as general parquet schemas; possibly by using a recursive definition for `ROW` types.

[0] https://github.com/fbertsch/schema_evolution_exploration/blob/master/presto_col_names/Schema_Evolution_Exploration.ipynb
[1] https://github.com/prestodb/presto/blob/master/presto-hive/src/main/java/com/facebook/presto/hive/parquet/ParquetHiveRecordCursor.java#L745

**Comment by nezihyigitbasi** [comment]
@fbertsch the new Parquet reader should have support for schema evolution for ROW types, can you please give it a try? (set `hive.parquet-optimized-reader.enabled=true`)

**Comment by fbertsch** [comment]
It works! Thanks!
