### ISSUE TITLE
DatabaseMetadata.getColumns extremely slow with both Presto and  Teradata Presto drivers

### ISSUE THREAD

**Issue by the6campbells** [prestodb/presto#7718]
Reading the Resultset from  DatabaseMetadata.getColumns() for a specified catalog, schema, table is very slow using the Presto 0.170 driver and server. 

The Teradata 0.157.t8 driver to read time for the Resultset the lag is fast but getColumns is slow.

Using a simple JDBC program one can see the elapsed time to read the Resultset from getColumns is extremely slow with the Presto driver as-is and when compared to the Teradata Presto JDBC driver.

So to an extent both have poor performance getting a very small amount of metadata from a MySQL database.

**Basic loop on tables in a schema and get column metadata**

	String schem = null;
		ResultSet rs = dbMeta.getTables( "mysql_gosales","gosales_1021", "%", tableTypes);
		
		if (rs != null) {
			while (rs.next()) {
				long st = System.currentTimeMillis();
				ResultSet rs2 = dbMeta.getColumns("mysql_gosales","gosales_1021", rs.getString("TABLE_NAME"), "%");
				long et = System.currentTimeMillis() - st;
				System.out.println(String.format("Method DatabaseMetadata.getColumns(%s,%s,%s) took %d msec", 
						"mysql_gosales","gosales_1021", rs.getString("TABLE_NAME"), et));
				if (rs2 != null) {
					st = System.currentTimeMillis();
					while (rs2.next()) {
						String c1 = rs2.getString("TABLE_CAT");
						String c2 = rs2.getString("TABLE_SCHEM");
						String c3 = rs2.getString("TABLE_NAME");
						Integer c4 = rs2.getInt("DATA_TYPE");
						String c5 = rs2.getString("TYPE_NAME");
						Integer c6 = rs2.getInt("COLUMN_SIZE");
						Integer c7 = rs2.getInt("DECIMAL_DIGITS");
					}
					rs2.close();
					et = System.currentTimeMillis() - st;
					System.out.println(String.format("Reading Resultset from DatabaseMetadata.getColumns took %d msec", et));
				}
			}
			rs.close();

**Presto 0.170 JDBC driver**

Method DatabaseMetadata.getColumns(mysql_gosales,gosales_1021,branch) took 1103 msec
Reading Resultset from DatabaseMetadata.getColumns took 24602 msec
Method DatabaseMetadata.getColumns(mysql_gosales,gosales_1021,conversion_rate) took 47 msec
Reading Resultset from DatabaseMetadata.getColumns took 25683 msec
Method DatabaseMetadata.getColumns(mysql_gosales,gosales_1021,country) took 42 msec
Reading Resultset from DatabaseMetadata.getColumns took 25637 msec
Method DatabaseMetadata.getColumns(mysql_gosales,gosales_1021,currency_lookup) took 38 msec
Reading Resultset from DatabaseMetadata.getColumns took 25710 msec
Method DatabaseMetadata.getColumns(mysql_gosales,gosales_1021,euro_conversion) took 36 msec
Reading Resultset from DatabaseMetadata.getColumns took 25687 msec
Method DatabaseMetadata.getColumns(mysql_gosales,gosales_1021,inventory_levels) took 32 msec
Reading Resultset from DatabaseMetadata.getColumns took 51968 msec
Method DatabaseMetadata.getColumns(mysql_gosales,gosales_1021,order_details) took 35 msec
Reading Resultset from DatabaseMetadata.getColumns took 25477 msec
Method DatabaseMetadata.getColumns(mysql_gosales,gosales_1021,order_header) took 35 msec
Reading Resultset from DatabaseMetadata.getColumns took 26379 msec
Method DatabaseMetadata.getColumns(mysql_gosales,gosales_1021,order_method) took 34 msec
Reading Resultset from DatabaseMetadata.getColumns took 25697 msec
Method DatabaseMetadata.getColumns(mysql_gosales,gosales_1021,product) took 37 msec
Reading Resultset from DatabaseMetadata.getColumns took 25715 msec
Method DatabaseMetadata.getColumns(mysql_gosales,gosales_1021,product_brand) took 32 msec
Reading Resultset from DatabaseMetadata.getColumns took 25592 msec
Method DatabaseMetadata.getColumns(mysql_gosales,gosales_1021,product_color_lookup) took 29 msec
Reading Resultset from DatabaseMetadata.getColumns took 25621 msec
Method DatabaseMetadata.getColumns(mysql_gosales,gosales_1021,product_forecast) took 44 msec
Reading Resultset from DatabaseMetadata.getColumns took 25489 msec
Method DatabaseMetadata.getColumns(mysql_gosales,gosales_1021,product_line) took 30 msec
Reading Resultset from DatabaseMetadata.getColumns took 25606 msec
Method DatabaseMetadata.getColumns(mysql_gosales,gosales_1021,product_name_lookup) took 35 msec
Reading Resultset from DatabaseMetadata.getColumns took 25545 msec
Method DatabaseMetadata.getColumns(mysql_gosales,gosales_1021,product_size_lookup) took 36 msec
Reading Resultset from DatabaseMetadata.getColumns took 25597 msec
Method DatabaseMetadata.getColumns(mysql_gosales,gosales_1021,product_type) took 34 msec
Reading Resultset from DatabaseMetadata.getColumns took 25603 msec
Method DatabaseMetadata.getColumns(mysql_gosales,gosales_1021,return_reason) took 24 msec
Reading Resultset from DatabaseMetadata.getColumns took 25587 msec
Method DatabaseMetadata.getColumns(mysql_gosales,gosales_1021,returned_item) took 27 msec
Reading Resultset from DatabaseMetadata.getColumns took 25517 msec
Method DatabaseMetadata.getColumns(mysql_gosales,gosales_1021,sales_region) took 30 msec
Reading Resultset from DatabaseMetadata.getColumns took 25535 msec
Method DatabaseMetadata.getColumns(mysql_gosales,gosales_1021,sales_target) took 26 msec
Reading Resultset from DatabaseMetadata.getColumns took 25657 msec
Method DatabaseMetadata.getColumns(mysql_gosales,gosales_1021,time_dimension) took 31 msec
Reading Resultset from DatabaseMetadata.getColumns took 25988 msec
Method DatabaseMetadata.getColumns(mysql_gosales,gosales_1021,time_quarter_lookup) took 33 msec
Reading Resultset from DatabaseMetadata.getColumns took 25602 msec
Method DatabaseMetadata.getColumns(mysql_gosales,gosales_1021,xgorev) took 40 msec

**Same test using the Teradata Presto 0.157 t8 release JDBC driver**

Method DatabaseMetadata.getColumns(mysql_gosales,gosales_1021,branch) took 25565 msec
Reading Resultset from DatabaseMetadata.getColumns took 3 msec
Method DatabaseMetadata.getColumns(mysql_gosales,gosales_1021,conversion_rate) took 25710 msec
Reading Resultset from DatabaseMetadata.getColumns took 1 msec
Method DatabaseMetadata.getColumns(mysql_gosales,gosales_1021,country) took 25601 msec
Reading Resultset from DatabaseMetadata.getColumns took 7 msec
Method DatabaseMetadata.getColumns(mysql_gosales,gosales_1021,currency_lookup) took 25475 msec
Reading Resultset from DatabaseMetadata.getColumns took 4 msec
Method DatabaseMetadata.getColumns(mysql_gosales,gosales_1021,euro_conversion) took 25418 msec
Reading Resultset from DatabaseMetadata.getColumns took 0 msec
Method DatabaseMetadata.getColumns(mysql_gosales,gosales_1021,inventory_levels) took 25614 msec
Reading Resultset from DatabaseMetadata.getColumns took 2 msec
....

If instead of looping on the Resultset of getTables you just call getColumns for all objects in the schema

**Teradata JDBC driver**
Method DatabaseMetadata.getColumns(mysql_gosales,gosales_1021) took 26308 msec
Reading Resultset from DatabaseMetadata.getColumns took 184 msec

**Presto JDBC driver**
Method DatabaseMetadata.getColumns(mysql_gosales,gosales_1021) took 1645 msec
Reading Resultset from DatabaseMetadata.getColumns took 24398 msec

**Comment by msdotnetclr** [comment]
I noticed that when the connector is pointing to a database with a lot if views, and the views are backed by pretty complex queries, the DatabaseMetadata methods are extremely slow. I am not sure if it is a Presto driver issue though - it is more a problem in JDBC base driver over all.
