### ISSUE TITLE
Function aware predicate pushdown

### ISSUE THREAD

**Issue by buremba** [prestodb/presto#7720]
When we cast the values or pass them to functions, predicate pushdown doesn't work. It would be great if the system could understand that the following queries can also take advantage of predicate pushdown.

`select count(*) from table where cast(created_at as date) > date '2017-4-1'`

`select count(*) from table where date_trunc('day', created_at) > date '2017-4-1'`

**Comment by dain** [comment]
We have talked about this before, and it is pretty difficult.  IIRC the issue is you need to move the function from one side of the comparison to the other, and most functions don't have an inverse.  Alternatively, we could implement push down for functions, but many connectors have different semantics for even simple functions like casts.  

BTW The work around for this issue is to manually, put the functions on the other side of the comparison operator (if possible).

**Comment by buremba** [comment]
Yes, it but the problem is that most of our queries are auto-generated and since our backend doesn't know about the PrestoDB functions and casts, we can't generate the appropriate query.

I'm aware that most of the functions are irreversible but they don't always need to be one-to-one reversible. Here is an example query that we execute:

```
SELECT *
FROM
  (
   SELECT
     "date_trunc"('week', CAST("_time" AS DATE)) "week"
   , "collection"
   , "count"(*) "total"
   FROM table
   GROUP BY 1, 2
) 
WHERE ("week" IN (date '2016-10-03', date '2016-11-21')) 
```

`date_trunc` is also not reversible but if we can re-write the query as follows:

```
SELECT *
FROM
  (
   SELECT
     "date_trunc"('week', CAST("_time" AS DATE)) "week"
   , "collection"
   , "count"(*) "total"
   FROM table 
   WHERE _time BETWEEN date '2016-10-03' and date '2016-10-10' 
           OR _time BETWEEN date '2016-11-21' and date '2016-11-28'
   GROUP BY 1, 2
) 
```

The query planner can make the predicate pushdown work. It requires a reverse-expression implementation of `date_trunc` function so an extra interface for functions. It would also solve #6595.

It still requires a lot of work because now we need an interface for optional reverse-expression operation of functions. However; I believe that predicate pushdown is a killer feature because it saves lots of necessary IO and has a big impact on typical queries.

**Comment by buremba** [comment]
I believe that it's not a good idea to close the issues that don't have any recent activity. Just because no one had anything to talk about the issue, you shouldn't assume that it doesn't exist. 

Also, you're losing all the historical relevant messages about the issue in case someone creates the issue again at some point.

**Comment by rongrong** [comment]
The stale bot is not ideal but it does help closing some old issues that's no longer relevant and nobody is working on or planning to work on. If it accidentally closed something useful, please reopen. Sorry for the inconvenience. Thanks for your support!

**Comment by buremba** [comment]
Actually, that bot closed 7 issues that I created but if there's no interest in implementing them in the future, feel free to close. However; I believe that it's not helpful for the community.
