### ISSUE TITLE
NULL values are not allowed on the probe side of SemiJoin operator

### ISSUE THREAD

**Issue by the6campbells** [prestodb/presto#7726]
Presto server/driver 0.170

select tjoin1.rnum, tjoin1.c1 from mysql_cert.dbcert.tjoin1 where  tjoin1.c1 not in (select tjoin2.c1 from mysql_cert.dbcert.tjoin2)

NULL values are not allowed on the probe side of SemiJoin operator

MySQL tables

create table TJOIN1 (RNUM integer   not null , C1 integer null, C2 integer null);

insert into TJOIN1 (RNUM, C1, C2) values ( 0, 10, 15);
insert into TJOIN1 (RNUM, C1, C2) values ( 1, 20, 25);
insert into TJOIN1 (RNUM, C1, C2) values ( 2, NULL, 50);

create table TJOIN2 (RNUM integer   not null , C1 integer null, C2 char(2) null);

insert into TJOIN2 (RNUM, C1, C2) values ( 0, 10, 'BB');
insert into TJOIN2 (RNUM, C1, C2) values ( 1, 15, 'DD');
insert into TJOIN2 (RNUM, C1, C2) values ( 2, NULL, 'EE');
insert into TJOIN2 (RNUM, C1, C2) values ( 3, 10, 'FF');

**Comment by sopel39** [comment]
There is an ongoing effort to allow for NULL values in probe side of `SemiJoin`.
`NULL values are not allowed on the probe side of SemiJoin operator` was introduced as a temporary measure to prevent incorrect logical predicate results, see: https://github.com/prestodb/presto/issues/6622

**Comment by the6campbells** [comment]
Similar to some other work in progress items in Presto, it would help to see the public documentation include a known-restrictions/limitations section. 

This would simplify the process of pointing a "user" to the known restriction vs pointing them to one or more issues in Git where it may require them to skim several entries to see what the issues are separate from when they may have been removed.

**Comment by ArturGajowy** [comment]
@the6campbells this limitation has been documented [here, in the 'note'](https://prestodb.io/docs/current/sql/select.html#in) and [here, at the bottom of page](https://prestodb.io/docs/current/functions/comparison.html).

**Comment by ArturGajowy** [comment]
I agree that a standalone known restrictions / limitations chapter would be an improvement to the docs, though.
