### ISSUE TITLE
character comparison with distinct predicate produces different results

### ISSUE THREAD

**Issue by the6campbells** [prestodb/presto#7728]
Presto server/jdbc 0.170

Mapped to MySQL

select rnum, tchar.cchar from mysql_cert.dbcert.tchar where tchar.cchar is not distinct from ' '
returns 2 rows 

select rnum, tchar.cchar from mysql_cert.dbcert.tchar  where tchar.cchar = ' ' OR (tchar.cchar IS NULL AND ' ' IS NULL)
returns 0 rows

create table TCHAR ( RNUM integer  not null , CCHAR char(32 )  null  ) ;

insert into TCHAR(RNUM, CCHAR) values ( 0, NULL);
insert into TCHAR(RNUM, CCHAR) values ( 1, '');
insert into TCHAR(RNUM, CCHAR) values ( 2, ' ');
insert into TCHAR(RNUM, CCHAR) values ( 3, 'BB');
insert into TCHAR(RNUM, CCHAR) values ( 4, 'EE');
insert into TCHAR(RNUM, CCHAR) values ( 5, 'FF');

**Comment by sopel39** [comment]
`' '` is `VARCHAR` literal by default. You have to cast it to `CHAR` first, see:
```
presto:default> select cchar from tchar where cchar = cast(' ' as char(32)) OR (tchar.cchar IS NULL AND cast(' ' as char(32)) IS NULL);
              cchar               
----------------------------------
                                  
                                  
(2 rows)
```
