### ISSUE TITLE
join on predicate incorrectly evaluated producing incorrect result set

### ISSUE THREAD

**Issue by the6campbells** [prestodb/presto#7729]
Presto server/jdbc 0.170.

Mapped to MySQL

select tjoin1.rnum, tjoin1.c1, tjoin2.c2 from mysql_cert.dbcert.tjoin1 left outer join mysql_cert.dbcert.tjoin2 on ( tjoin1.c1 = tjoin2.c1 and tjoin2.c2 > 'C' )

Expected 3 rows
0	10	FF
1	20	<null>
2	<null>	<null>

Received
0	10	FF
0	10	BB
1	20	<null>
2	<null>	<null>

create table TJOIN1 (RNUM integer   not null , C1 integer null, C2 integer null);

insert into TJOIN1 (RNUM, C1, C2) values ( 0, 10, 15);
insert into TJOIN1 (RNUM, C1, C2) values ( 1, 20, 25);
insert into TJOIN1 (RNUM, C1, C2) values ( 2, NULL, 50);

create table TJOIN2 (RNUM integer   not null , C1 integer null, C2 char(2) null);

insert into TJOIN2 (RNUM, C1, C2) values ( 0, 10, 'BB');
insert into TJOIN2 (RNUM, C1, C2) values ( 1, 15, 'DD');
insert into TJOIN2 (RNUM, C1, C2) values ( 2, NULL, 'EE');
insert into TJOIN2 (RNUM, C1, C2) values ( 3, 10, 'FF');

**Comment by sopel39** [comment]
Same as: https://github.com/prestodb/presto/issues/7728, please cast `'C'` to `CHAR` first. And then verify results

**Comment by the6campbells** [comment]
An explicit cast would have to assign a precision >= the precision of the value expression being compared against. i.e cast ( 'C' as char(1)) will not work while cast ('C' as char(2 or 3 ...)) will.

**Comment by sopel39** [comment]
I am not sure what exactly your issue is, but I think the workaround is to cast both sides (or one side) to char type of the same length. Alternatively you could cast both sides to varchar, truncate and then compare.
We are working on improved character types support and casts in general. Currently casts and character types conform to SQL standard only partially. See: https://github.com/prestodb/presto/issues/6112

**Comment by the6campbells** [comment]
I'm speaking from the perspective trying to support Presto from a product which dynamically generates SQL based on "model based" rules vs hand coded SQL.  

If this issue https://github.com/prestodb/presto/issues/6975 was resolved, it would help us to dynamically plan better based on knowing if a char/varchar is involved. 

As is: trying to push comparisons to the data in the interim requires.

(a) customer knows 100% they are only using varchars in their source database comparisons applied in presto correctly

(b) customer unsure if they use char or not.

In the case of (b) that means testing+shipping configurations they have to turn on which pessimistically applies rtrim(cast(<c> as varchar)) around literals and value expressions to force correct results in comparisons.

**Comment by sopel39** [comment]
Both chars and varchars and compared without space padding. If you want to achieve (emulate) comparisons with space padding then you have to use `rtrim`.
