### ISSUE TITLE
hive.rcfile_optimized_reader_enabled=true CHAR regression

### ISSUE THREAD

**Issue by fiedukow** [prestodb/presto#7734]
Steps:
`create table khaki_t WITH (format = 'RCTEXT') as select cast('khaki' as char(20)) khaki_c;`
`SELECT count(*) FROM khaki_t WHERE khaki_c = 'khaki[15spaceshere]';`

Current behavior:
```
_col0 
-------
     0 
```

Expected behavior:
```
_col0 
-------
     1
```

Workaround:
`set session hive.rcfile_optimized_reader_enabled=false;`

Regression was introduced in commits range:
`0c6c3b24ff37b4c35c228b68b64073eb58c03983..fdc4a384794c6d782d6c8e2e94a523109c552a27`

FYI: @dain

**Comment by dain** [comment]
I can't reproduce this.  The table being created is `ORC` and therefor the reading is not effected by the `hive.rcfile_optimized_reader_enabled`. Specifically, the query above returns 0 regardless of this flag setting.  The only value that makes this query work is: `SELECT count(*) FROM khaki_t WHERE khaki_c = 'khaki               '`.

I'm pretty sure this is related to the `char` and `varchar` comparison project that is ongoing.  For example, this query returns false `select cast('01234' as char(10)) = '01234'` but this one returns true `select cast('01234' as char(10)) = '01234     '`.

If you have a reproduction for this issue, please reopen this issue.

cc @losipiuk

**Comment by fiedukow** [comment]
I think our discussion became at least weird due to github removing consecutive spaces in comments ;)

Anyway. I obviously messed steps up by using `WITH (format = 'ORC')`, here is reproduction on current master (80ed6c0) with fixed steps (`WITH (format = 'RCTEXT')`):
http://showterm.io/0dfcab26942b52003554e

I modified steps in issue report, reopening now.
