### ISSUE TITLE
`max(null)` fails in planner

### ISSUE THREAD

**Issue by haozhun** [prestodb/presto#7741]
`java.lang.IllegalArgumentException: Expected method MethodHandle(BlockState,Block)void parameter 1 type to be void (unknown)`

**Comment by ebyhr** [comment]
@haozhun Would you tell me the expected result? Following is ```sum(null)``` result.

```sh
presto> select sum(null);
Query 20170528_141915_00000_8iapz failed: line 1:8: Could not choose a best candidate operator. Explicit type casts must be added.
Candidates are:
         * sum(double):double
         * sum(real):real
         * sum(bigint):bigint
         * sum(interval day to second):interval day to second
         * sum(interval year to month):interval year to month
         * sum(decimal(1,0)):decimal(38,0)
```

**Comment by haozhun** [comment]
From your paste, it looks like it has been fixed. The current result is still not ideal. But I wouldn't call it a bug. Thank you for your investigation.
