### ISSUE TITLE
PrestoDB memory leak on Docker

### ISSUE THREAD

**Issue by goindwalia** [prestodb/presto#7765]
I am trying to run PrestoDB in a dockerized environment. When I try running a complex query, memory shoots up and is never released after the query. In non-dockerized environment, things work fine against same data. I have tried looking at the problem by displaying GC verbose but no luck. What could be the possible problem?

**Comment by nezihyigitbasi** [comment]
Are you sure the memory is not released even after the GC runs? One way to check that is to trigger a full GC in the Presto JVM through command line: `jmap -histo:live <pid>`

**Comment by smith-m** [comment]
Hey, I think I am running into a similar issue running standalone presto (.177) in a single container on a 112GB VM with the jvm set to -Xmx108G. After being up for ~3 weeks in a docker container, some relatively simple queries reading only a few million rows started returning "PrestoException: No free space available for spill" as an error.

I've checked, and the presto container has no query running and is sitting idle at about 71GB of memory usage.

After running garbage collection with the aforementioned command, memory usage immediately dropped to 18GB.

[prestojvmgarbagecollection.txt](https://github.com/prestodb/presto/files/1112939/prestojvmgarbagecollection.txt)
