### ISSUE TITLE
Lambda name resolution should use Scope mechanism

### ISSUE THREAD

**Issue by sopel39** [prestodb/presto#7790]
Currently lambdas use separate and dedicated name resolution mechanism. This causes various problems:
https://github.com/prestodb/presto/issues/7780
https://github.com/prestodb/presto/issues/7784
https://github.com/prestodb/presto/issues/9023
and makes it hard (error prone) to analyze/plan very complex queries (with subqueries, lambdas, complex order by)

Therefore lambdas should also use Scopes mechanism for name resolution. The unification would make analyzing/planning easier and reduce possible errors.

FYI: @haozhun @martint @findepi @kokosing

**Comment by findepi** [comment]
Roadmap:

- [ ] `ExpressionAnalyzer` (PR #9026)
- [ ] `TranslationMap` (PR #9090)
- [ ] `AggregationAnalyzer`
