### ISSUE TITLE
Limit is not accounted for when transforming correlated scalar subquery with aggregation into join

### ISSUE THREAD

**Issue by sopel39** [prestodb/presto#7824]
Flat with limit
```
presto:sf1> select count(*) from (select * from (values (7,1), (7,2), (7,3), (7,4), (7,5), (7,6)) t(orderkey, value) where orderkey = 7 limit 5);
 _col0 
-------
     5 
(1 row)
```
flat without limit:
```
presto:sf1> select count(*) from (select * from (values (7,1), (7,2), (7,3), (7,4), (7,5), (7,6)) t(orderkey, value) where orderkey = 7);
 _col0 
-------
     6 
(1 row)
```
correlated with limit:
```
presto:sf1> select corr_key, (select count(*) from (select * from (values (7,1), (7,2), (7,3), (7,4), (7,5), (7,6)) t(orderkey, value) where orderkey = corr_key limit 5)) from (values 7) t(corr_key);
 corr_key | _col1 
----------+-------
        7 |     6 
(1 row)
```

Limit is removed and then ignored in `com.facebook.presto.sql.planner.optimizations.TransformCorrelatedScalarAggregationToJoin`

FYI: @kokosing

**Comment by kokosing** [comment]
When EXIST is transformed to scalar subquery the limit is added which is
then ignored in mentioned class. The easiest fix fix is to remove code
which adds unnecessary Limit and the one which ignores it.

13.04.2017 14:26 "Karol Sobczak" <notifications@github.com> napisał(a):
