### ISSUE TITLE
Optimize memory usage for aggregations where GROUP BY includes Partition column

### ISSUE THREAD

**Issue by Downchuck** [prestodb/presto#7838]
I've recently seen a case of:
SELECT count(distinct x),day,etc where day between a and b group by day, etc

Queries fail running out of memory at 1TB of usage. A single day will take up 50gigs of ram, but a month takes over 1TB. Given that the GROUP BY includes the partition column, we know that all aggregations of distinct can be calculated within the partitioned files, and so the planner could have squeezed this into ram, moving through the partitions.

**Comment by martint** [comment]
We're currently working on being able to execute queries "bucket by bucket" (for some notion of bucket the engine can reason about) to handle cases like these.

**Comment by Downchuck** [comment]
That makes sense. For those tagging along: in Hive, a partition may have a bucket column, and so within that partition there may be several files, with the data split by a hash function run on the bucketed column.

@martint Will this also add smartness for sorted data? Within Hive, I setup sorted tables, with just one file per partition, most often. That is in HQL: PARTITION BY (... ) CLUSTER BY (...) SORT BY (...) INTO 1 BUCKETS.

In those cases, SELECT DISTINCT on a bucket could really keep ram usage down.

**Comment by electrum** [comment]
A potential alternative that is far faster and more memory efficient:

https://prestodb.io/docs/current/functions/aggregate.html#approx_distinct

**Comment by Downchuck** [comment]
In this case, we're using UUIDs - the +/- 2.3% SE is exactly what occurs.
