### ISSUE TITLE
How to get started after running server?

### ISSUE THREAD

**Issue by leolorenzoluis** [prestodb/presto#7840]
Are there any database seed that one can test right away? For example, connecting to a MySQL database with an Oracle database and performing a join operation using Presto?

**Comment by ArturGajowy** [comment]
Both mysql and oracle provide sample schemas - you can use them. I think both of them even have an 'employees' schema - not sure how similar are those though. Anyway, even if the schemas (and their data) are different, you can join the tables from those schemas on, say, numerical ids.

In the future please use the [presto-users group](https://groups.google.com/forum/#!forum/presto-users) for such questions.
