### ISSUE TITLE
Skipping based on TimeStamp statistics

### ISSUE THREAD

**Issue by Praveen2112** [prestodb/presto#7845]
In the current Presto OrcReader, the stripes are selected based on the ColumnStatistics for that particular stripe. If the filter criteria is in between the min and  max value of that stripe then we will process it else we would skip it. But if the filter column is of type Timestamp then we are not skipping it based on the min and max value. It is possible to get the min and max value for the Timestamp column (in epoch time) from the OrcMetaData and in the TupleDomain the timestamp criteria is also in epoch time. In the OrcMetadataReader we could get the column statistics for Timestamp column and we could use it to skip the stripes. Any issues in the above implementation.

**Comment by electrum** [comment]
We should be able to handle it like other types. It's possible the ORC reader was implemented before we had push down for those types and we didn't go back and add it. cc @dain

**Comment by Praveen2112** [comment]
We just have to read the Timestamp Statistics from metadata of ORC and then initialize  IntegerColumnStatistics which would hold the min and max value of the epoch time.
