### ISSUE TITLE
Return empty if data lives in nested folder when querying external table in s3

### ISSUE THREAD

**Issue by linusguan** [prestodb/presto#7867]
When querying an external table with `LOCATION 's3://somebucket/someprefix'`

If the data lives in nested path, for example, `s3://somebucket/someprefix/foo/data1.avro` and `s3://somebucket/someprefix/bar/data2.avro`, presto returns empty data while Hive knows to look deeper into nested path and return proper result.

**Comment by nezihyigitbasi** [comment]
If you want the same behavior as Hive you can set `hive.recursive-directories=true` in your Presto configuration.

**Comment by nezihyigitbasi** [comment]
Please reopen if that doesn't work

**Comment by electrum** [comment]
We should verify if this is now default in Hive and if so, enable by default.

**Comment by nezihyigitbasi** [comment]
Filed #7873
