### ISSUE TITLE
what is the  latest architecture diagram ?

### ISSUE THREAD

**Issue by zhangxin0112** [prestodb/presto#7868]
hi.
search with google the  presto architecture diagram 
![3ba3f8d860c64e990fe896c2f11e2099_articlex 1](https://cloud.githubusercontent.com/assets/8244097/25218829/de3ff66c-25de-11e7-9a42-9b4f65b7b260.png)

now i clone the presto 0.173 ,i read the source code , found the sql parsered in the client . it means the sql parsered finished in the client .so  the architecture diagram may like this ?
![3ba3f8d860c64e990fe896c2f11e2099_articlex](https://cloud.githubusercontent.com/assets/8244097/25218845/ea31dd82-25de-11e7-8fb6-732cefde975d.png)

is am i wrong ?

**Comment by ArturGajowy** [comment]
I think the arrows show the dependencies and I believe there's no dependency from parser/analyzer to the client. So the upper picture is correct. It might be that the responsibility of parsing has leaked from the pareser/analyzer module to the client, but that would be an implementation slip-up, not an architecture change nor a change in module's dependencies.

**Comment by zhangxin0112** [comment]
"It might be that the responsibility of parsing has leaked from the pareser/analyzer module to the client, "
yes .u are right . that is what my real intention .
my second pic makes u misunderstanding .

**Comment by ArturGajowy** [comment]
@zhangxin0112 Please file an issue describing the "SQL parsing is (partially) done on the client" problem, ideally describing a proposed solution :)

**Comment by zhangxin0112** [comment]
ye.i could try . 
For now i just understand the module presto-cli's relationship with other module . the presto's a big project . it may take my  appreciable time to completely understand it .

**Comment by martint** [comment]
The diagram shows request and data flows, not dependencies.

The reason the cli depends on the parser is that we use it to tokenize the queries to detect boundaries when the user types a query across multiple lines.

**Comment by electrum** [comment]
The CLI only uses the lexer (not parser) to find the statement delimiter (semicolon). It needs a lexer to properly handle quoted strings, comments, etc.
