### ISSUE TITLE
Investigate whether hive.recursive-directories should be enabled by default

### ISSUE THREAD

**Issue by nezihyigitbasi** [prestodb/presto#7873]

**Comment by nezihyigitbasi** [comment]
@electrum Hive has a config property `hive.mapred.supports.subdirectories` (default: false), that configures this behavior. So for now I don't think we should enable our recursive flag by default in Presto.

**Comment by kokosing** [comment]
@nezihyigitbasi From what you said in the last comment it looks like we could close this issue. Do you agree?
