### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by wanggnot** [prestodb/presto#7879]
Traceback (most recent call last):
  File "./launcher.py", line 436, in main
    handle_command(command, o)
  File "./launcher.py", line 322, in handle_command
    run(process, options)
  File "./launcher.py", line 249, in run
    os.execvpe(args[0], args, env)
  File "/usr/lib/python2.7/os.py", line 355, in execvpe
    _execvpe(file, args, env)
  File "/usr/lib/python2.7/os.py", line 382, in _execvpe
    func(fullname, *argrest)
OSError: [Errno 2] No such file or directory
please help me to resove it

**Comment by desavera** [comment]
+1

**Comment by electrum** [comment]
Can you provide more details on how to reproduce this? The problem is not clear from the information provided.

**Comment by electrum** [comment]
Is "java" available in the PATH environment in which the launcher is run?

**Comment by oldbelvey** [comment]
+1

**Comment by erkansirin78** [comment]
+1

**Comment by erkansirin78** [comment]
I solved it 
`[root@localhost]# export PATH=$PATH:/usr/jdk64/jdk1.8.0_112/bin/`
It can't see JAVA path

**Comment by ayush-san** [comment]
Why does java home need to be set for running launcher.py file?

**Comment by miraj-godha-guavus** [comment]
This error comes, when java is not installed or its path is not correctly setup

**Comment by wanggnot** [comment]
您好！您的来信以收到，谢谢您的来信，我这会儿暂时无法收看您的邮件，我会以最快的速度拜读您的来信。
