### ISSUE TITLE
Whether presto has white paper or Design document ？

### ISSUE THREAD

**Issue by zhangxin0112** [prestodb/presto#7909]
Whether presto has white paper or Design document ？
it will help me in-depth understanding of presto (about logical plan --> optimized logical plan --> fragments --> distributed logical plan --> subplans --> tasks ?? ).
something to help me to understand the link about sql --> task .

**Comment by akshatnair** [comment]
This is more of a google group question, (https://groups.google.com/forum/#!forum/presto-users)
Closing as this is not an issue. Look for some topics that have been discussed and some presentations that have been shared in the group

**Comment by zhangxin0112** [comment]
OK. Got it .
Thanks u. 
@akshatnair
