### ISSUE TITLE
Aggregate Function: numeric_histogram raises Query 20170427_185829_00272_a33cx failed: No nodes available to run query

### ISSUE THREAD

**Issue by satheeshravir** [prestodb/presto#7915]
I am using presto 0.169. When I run the following query all the workers get killed and no proper error message is thrown to the server logs. 

select numeric_histogram(epoch, 60, 2) from table name;

Note: epoch is a bigint

-----------------------------------------------
System Specs:
-----------------------------------------------
OS: Ubuntu 14.04 LTS
16G RAM

-----------------------------------------------
JVM Config
-----------------------------------------------
-server
-Xmx8G
-XX:+UseG1GC
-XX:G1HeapRegionSize=32M
-XX:+UseGCOverheadLimit
-XX:+ExplicitGCInvokesConcurrent
-XX:+HeapDumpOnOutOfMemoryError
-XX:+ExitOnOutOfMemoryError
-XX:ErrorFile=/home/ubuntu/presto/data/err.log

**Comment by findepi** [comment]
Quoting to https://prestodb.io/docs/current/functions/aggregate.html 

> numeric_histogram(buckets, value, weight)

perhaps you wanted `numeric_histogram(60, epoch, 2)` or something (note the order of parameters!)

If you want to report crash, please add more information, like how nodes crashed. Perhaps repro steps (best if using `tpch` or `memory` connector).
