### ISSUE TITLE
Receiving NULL values when querying array column types in hive 

### ISSUE THREAD

**Issue by martink-2** [prestodb/presto#7947]
I have a table in hive that has a column of `array(varchar)` type. 
Querying this column in **v0.164** and earlier returns correct values.
Querying the column in **v0.165** and above returns NULL values.

The hive config file is:

```
connector.name=hive-hadoop2
hive.metastore.uri=thrift://<hostname>:9083
hive.config.resources=/etc/hadoop/conf/core-site.xml,/etc/hadoop/conf/hdfs-site.xml
hive.parquet.use-column-names=true
hive.parquet-optimized-reader.enabled=true
hive.parquet-predicate-pushdown.enabled=true
hive.storage-format=PARQUET
hive.compression-codec=SNAPPY
```
If I disable`hive.parquet-optimized-reader` setting, then it returns correct values in **v0.165** and above, however, I then encounter an different issue regarding reading DECIMAL column types.

**Comment by nezihyigitbasi** [comment]
There are known issues with complex type null handling in the new parquet reader and @zhenxiao is working on that. The thing is v0.165 introduced support for maps/arrays in the new parquet reader that's why it starts failing in that version.

That aside, do you see the problem with decimals also with v0.164 (using the old reader)? If not, this means there is some regression in the old reader.

**Comment by martink-2** [comment]
> That aside, do you see the problem with decimals also with v0.164 (using the old reader)? 

Yes, when I'm not using the optimized reader I get the following error when trying to SELECT decimal columns 
`Query 20170502_203121_00001_e9wv6 failed: Can not read value at 0 in block 0 in file hdfs://<file>.parquet`
Tested it on v0.164, 0.165, 0.169, 0.173 with same results.

**Comment by drdee** [comment]
@zhenxiao @nezihyigitbasi -- do you have a status update regarding fixing support of complex type null handling in the new parquet reader?

**Comment by bramth** [comment]
@zhenxiao @nezihyigitbasi is there any updates regarding this? i am using v0.183
and I experienced similar issue

however if parquet optimized reader is set to false, if there is nested schema difference between two partitions, it will cause schema mismatch error

**Comment by nezihyigitbasi** [comment]
I haven't been working on Parquet stuff for quite some time, so no updates from me. @zhenxiao any updates from your side?

BTW there were several decimal related fixes in the past several releases, if you are seeing issues with decimals please give the latest release a try. If you are seeing some other issue, please open a new issue and give some details so someone can take a look.

**Comment by zhenxiao** [comment]
For old Parquet reader, schema evolution is supported in this PR:
https://github.com/prestodb/presto/pull/6675

Will work on new Parquet reader fix Q4 this year.

**Comment by bramth** [comment]
Looking forward to it! Thanks!

**Comment by dotcomputercraft** [comment]
@zhenxiao -  Here are some parquet input files that containing array of structs with primitive type and map when array has multiple entries containing nulls.  It can help your development work to fix the new parquet reader.  Looking forward to a fix.  
[Archive.zip](https://github.com/prestodb/presto/files/1393176/Archive.zip)
[part-00024.parquet.zip](https://github.com/prestodb/presto/files/1393177/part-00024.parquet.zip)

**Comment by dswalter** [comment]
I'm running into this issue as well, where I have an `array(varchar)` that is nullable. Hive is able to handle it just fine, but the optimized reader fails for my workload. Would anyone have pointers as to where to start looking in the codebase to resolve this?

**Comment by hustnn** [comment]
@zhenxiao 

I also had this problem using 0.195 when enable optimized parquet reader when there is schema mismatch for nested structure on different partitions.

**Comment by sj860908** [comment]
This problem is making us to kept our version at 0.170.

Any updates on the fix?

**Comment by nezihyigitbasi** [comment]
@sj860908 Did you try Presto 0.203+? The optimized Parquet reader has several fixes for proper complex type handling.

**Comment by sj860908** [comment]
@nezihyigitbasi using the newer version fixed the issue. Thanks!
