### ISSUE TITLE
Does Prestodb supports LDAP not secure LDAPS.

### ISSUE THREAD

**Issue by mayank-malhotra** [prestodb/presto#7954]
I know Prestodb supports LDAPS integration but my organization doesn't support LDAPS or secure LDAP integration. So I tried using LDAP in config.properties file then error came:
**Invalid configuration property authentication.ldap.url: LDAP without SSL/TLS unsupported. Expected ldaps://**

Is there any way I can use ldap as my organization doesn't support ldaps://

**Comment by electrum** [comment]
I think we don't support that because it means the passwords would be sent to the LDAP server in plaintext (so anyone on the network could easily sniff them).

**Comment by electrum** [comment]
If you don't care about security, you could run `stunnel` on the Presto coordinator to accept secure connections from Presto and tunnel them to your LDAP server:

https://bsriram.info/2010/09/13/tunnelling-ldap-using-stunnel/
http://www.tldp.org/HOWTO/archived/LDAP-Implementation-HOWTO/ssl.html

We might be able to non-secure LDAP if we could enforce digest authentication (so the password would never be sent over the wire), but I don't know enough about LDAP to know the full security implications:

http://docs.oracle.com/javase/jndi/tutorial/ldap/security/digest.html
