### ISSUE TITLE
CLI should bail out as soon as query fails

### ISSUE THREAD

**Issue by martint** [prestodb/presto#7960]
I've observed a case where the web UI indicates the query has failed and the CLI marks a stage as failed ("X") but keeps printing progress and query stats for a while. This presumably happens because the coordinator continues to return "next" links in the response, and the CLI blindly follows them.

There are two possible solutions to this:
- Coordinator should stop producing "next" links once the query fails. An argument against this is that some clients might be interested in getting the most accurate stats about query execution even after a failure.
- CLI should detect the query has failed and abort.

**Comment by dain** [comment]
This is a sign that there is something broken in the cluster.  Once a stage is marked as failed (which is what you are describing), the failure should quickly propagate to the query state.

**Comment by martint** [comment]
It did... according to the UI, the query was failed. According to the CLI, one of the stages had failed, but the CLI kept going (not hung, still refreshing query state from the server)

**Comment by martint** [comment]
The speculation is that the statement resource continues to wait until the final task info is gathered from workers, but the UI does not -- hence the discrepancy.
