### ISSUE TITLE
Expose grantee to SystemAccessControl

### ISSUE THREAD

**Issue by jdintruff** [prestodb/presto#7964]
Currently the SystemAccessControl interface includes the identity of the user who is granting privileges when authorizing grants. The grantee, however, is not included. Including the grantee in this interface would allow plugins to do security checks on who can be granted access to tables instead of just checking the granting user.

**Comment by electrum** [comment]
This seems reasonable to me. Should we also add the `withGrantOption` flag?

**Comment by jdintruff** [comment]
@electrum I've posted my patch to #8061 and took your suggestion of adding that flag to more closely reflect the Grant API. I've made these changes symmetric with the Revoke API as well.
