### ISSUE TITLE
Undocumented breaking changes in SPI?

### ISSUE THREAD

**Issue by RobinUS2** [prestodb/presto#7978]
I was wondering what we can do about the fact that SPI has breaking changes every now and then that are not documented. This is not ideal for a plugin ecosystem. An example can be found here https://github.com/RobinUS2/presto-bloomfilter/pull/48/commits/1451881a3de3c366db73d6aa04858608292bd802

Sometimes it also looks like mainly refactoring (not sure about the example above), but especially in that case it may be better to stabilize the API over for example naming conventions.

What do you think?

**Comment by electrum** [comment]
That change was made for 623eeb8561ac1a04f51539b4c265a4ef9f8883ab.

In this case, we could have made it in a backwards compatible way:
```java
@Deprecated
default Type createType(List<TypeParameter> parameters)
{
    throw new UnsupportedOperationException("createType not implemented");
}

default Type createType(TypeManager typeManager, List<TypeParameter> parameters)
{
    return createType(typeManager, parameters);
}
```

It definitely should have been mentioned in the release notes for 0.175.

cc @haozhun
