### ISSUE TITLE
Can't cast REAL to JSON

### ISSUE THREAD

**Issue by idemura** [prestodb/presto#7981]
Sample: `SELECT CAST(CAST(1.234 AS REAL) AS JSON)`, while casting double is fine: `SELECT CAST(1.234 AS JSON)`. Documentation says this is supported.

**Comment by striderarun** [comment]
Hi,I would like to work on this one.

**Comment by idemura** [comment]
Hi Arun,
I made a quick PR for that yesterday (before your email). There should be
other tasks.

**Comment by haozhun** [comment]
Fixed in #7983
