### ISSUE TITLE
Improve query parameters '?' handling.

### ISSUE THREAD

**Issue by sopel39** [prestodb/presto#7989]
Currently, query parameters (`?`) are handled in various places across the planner. The process is as follows:
1. When query is first sent to backend, it is parsed and the parse tree (AST) is (is it?) then cached for further use
2. AST is reanalyzed with `Parameter index -> expression` bindings
3. Query plan is rebuild based on analysis and `Parameter index -> expression` bindings
    - `Parameter` nodes are replaced with expressions by `ParameterRewriter`

The problem with this approach are:
1. Only AST parse tree can be cached. The rest (analysis, query plan) have to be rebuild/reanalyzed
2. `ParameterRewriter` is used on a point basis extensively across the planner (>=17 usages). 
    - Places where `ParameterRewriter` is used in planner are often unrelated to query parameters (e.g: in `PlanBuilder`). The impression is that `ParameterRewriter` and `Parameter` are leaking to unrelated code
    - One has to remember about `Parameter` support whenever planning/projecting `Expression`

With the goal to cleanup potentially unrelated `ParameterRewriter` usages I am proposing the following refactor:
1. Analyze `EXECUTE` parameter bindings separately from query. This will result in `Parameter index -> type` bindings
2. Analyze query with `Parameter index -> type` bindings.
3. Build query plan based on analysis (no `Parameter` specific code)
    - Such query plan can be cached for further use with the same parameter types
4. Introduce some kind of `ParameterDesugarer` which would replace `Parameter` nodes witch appropriate constants or expressions (which can be evaluated to constants).

The benefits of this approach are:
1. Query plan can be reused with parameters of the same type
2. `ParameterRewriter` is not handled explicitly throughout the planner. The code significantly simplifies.

This is somehow related to: https://github.com/prestodb/presto/issues/7398

What do you think @rschlussel @martint ?

**Comment by rschlussel** [comment]
I don't fully understand the proposal, but I agree that the current situation of sprinkling the translation throughout the planner leaves a ton of room for bugs and it would be much better to do it all in one place.  Doing that by way of a ParameterDesugarer seems like a good approach.  Could you explain what you mean by the first two steps?

**Comment by sopel39** [comment]
>  Could you explain what you mean by the first two steps?

Basically I propose to separately analyze `EXECUTE` parameters to deduce their types. Then use the types to analyze actual query. The benefit is that if the query already have been analyzed with given parameter types, we could reuse such analysis.

**Comment by findepi** [comment]
> The benefit is that if the query have been already analyzed with given parameter types, we could reuse such analysis.

Yes, as long we cache the analysis / initial query plan, not the final plan.
The final plan may easily depend on particular values (e.g. predicate pushdown, or `LIKE ?` being translated to `=` for some parameter values)
