### ISSUE TITLE
Implement functions that encodes float/double according to IEEE-754

### ISSUE THREAD

**Issue by wenleix** [prestodb/presto#8007]
tentative signature: (need to think over the name)

```
to_ieee754_binary32(real)      -> varbinary
Encodes real in IEEE 754 single-precision binary floating-point format

to_ieee754_binary64(double) -> varbinary
Encodes double in IEEE 754 double-precision binary floating-point format
```

**Comment by wenleix** [comment]
@ausgoo Are you interested in working on this as a beginner task? It should be quite straightforward :)

**Comment by ausgoo** [comment]
@wenleix , sure. Can you create a Bootcamp task and assign that to me? Thanks.

**Comment by ausgoo** [comment]
@wenleix , could you assign this issue to me, seems I cannot assign it to myself. Thanks.

**Comment by wenleix** [comment]
Resolved by https://github.com/prestodb/presto/pull/8091
