### ISSUE TITLE
Ignore ALREADY_EXISTS error in CreateTableTask

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#8016]
For non-transactional connectors, the `createTable` call can fail with `ALREADY_EXISTS` and should be ignored if the `notExists` flag is set.

**Comment by sfilipco** [comment]
I would like to pick up this task. Please let me know if anyone else is working on it.

**Comment by sfilipco** [comment]
How do you recommend that I test the fix?

I am currently trying to write a `TestCreateTableTask` suite with a test that mocks `tableHandle.isPresent()` to return `false` and `metadata.createTable` to throw `PrestoException(ALREADY_EXISTS)`.

Thanks
