### ISSUE TITLE
One big bad query crashed all concurrent running queries

### ISSUE THREAD

**Issue by chengat1314** [prestodb/presto#8077]
Hi @raghavsethi thank for you feedback.
As discussed, I create a new issue. 
We are running Presto 0.170 on EMR.
with setting
http-server.threads.max=500
discovery-server.enabled=true
sink.max-buffer-size=1GB
query.max-memory=300GB
query.max-memory-per-node=15GB
query.max-history=300
query.min-expire-age=30m
http-server.http.port=8889
http-server.log.path=/var/log/presto/http-request.log
http-server.log.max-size=67108864B
http-server.log.max-history=5
log.max-size=268435456B
log.max-history=5
query.max-run-time = 60m
task.concurrency = 32
node-scheduler.network-topology = flat
exchange.http-client.request-timeout = 1200s
task.cpu-timer-enabled = false

using g1gc refer https://prestodb.io/docs/current/installation/deployment.html

The issue is that a very big bad query will crash all concurrent running queries. 
My guess here is jvm restart and killed all the other queries.
and it's because of this setting?
-XX:+ExitOnOutOfMemoryError
 

please find the log as follows:
2017-05-17T06:09:21.769Z        ERROR   remote-task-callback-124318     com.facebook.presto.execution.StageStateMachine Stage 20170517_060516_00750_dxfd7.5 failed
com.facebook.presto.spi.PrestoException: Encountered too many errors talking to a worker node. The node may have crashed or be under too much load. This is probably a transient issue, so please retry your query in a few minutes. (getting task status http://172.31.29.25:8889/v1/task/20170517_060516_00750_dxfd7.5.9 - 12 failures, time since last success 123.85s)
        at com.facebook.presto.server.remotetask.RequestErrorTracker.requestFailed(RequestErrorTracker.java:126)
        at com.facebook.presto.server.remotetask.ContinuousTaskStatusFetcher.failed(ContinuousTaskStatusFetcher.java:188)
        at com.facebook.presto.server.remotetask.SimpleHttpResponseHandler.onFailure(SimpleHttpResponseHandler.java:83)
        at com.google.common.util.concurrent.Futures$4.run(Futures.java:1123)
        at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
        Suppressed: java.lang.RuntimeException: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
                at com.google.common.base.Throwables.propagate(Throwables.java:240)

 Caused by: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
                ... 8 more
        Suppressed: java.lang.RuntimeException: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
                at com.google.common.base.Throwables.propagate(Throwables.java:240)
                at io.airlift.http.client.ResponseHandlerUtils.propagate(ResponseHandlerUtils.java:23)
                at io.airlift.http.client.FullJsonResponseHandler.handleException(FullJsonResponseHandler.java:58)
                at io.airlift.http.client.FullJsonResponseHandler.handleException(FullJsonResponseHandler.java:38)
                at io.airlift.http.client.jetty.JettyHttpClient$JettyResponseFuture.failed(JettyHttpClient.java:876)
                at io.airlift.http.client.jetty.JettyHttpClient$BufferingResponseListener.onComplete(JettyHttpClient.java:1114)
                at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:193)
                at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:185)

Also many logs like this
 ContinuousTaskStatusFetcher-20170517_055848_00735_dxfd7.41.10-2140514   com.facebook.presto.server.remotetask.RequestErrorTracker       Error getting task status 20170517_055848_00735_dxfd7.41.10: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed: http://172.31.20.30:8889/v1/task/20170517_055848_00735_dxfd7.41.10
2017-05-17T06:09:22.885Z        WARN    ContinuousTaskStatusFetcher-20170517_060244_00743_dxfd7.4.12-2138600    com.facebook.presto.server.remotetask.RequestErrorTracker       Error getting task status 20170517_060244_00743_dxfd7.4.12: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed: http://172.31.20.30:8889/v1/task/20170517_060244_00743_dxfd7.4.12
2017-05-17T06:09:22.887Z        WARN    ContinuousTaskStatusFetcher-20170517_060205_00737_dxfd7.4.13-2138600    com.facebook.presto.server.remotetask.RequestErrorTracker       Error getting task status 20170517_060205_00737_dxfd7.4.13: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed: http://172.31.20.30:8889/v1/task/20170517_060205_00737_dxfd7.4.13
2017-05-17T06:09:22.888Z        WARN    TaskInfoFetcher-20170517_060205_00737_dxfd7.23.8-2138600        com.facebook.presto.server.remotetask.RequestErrorTracker       Error getting info for task 20170517_060205_00737_dxfd7.23.8: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed: http://172.31.17.171:8889/v1/task/20170517_060205_00737_dxfd7.23.8
2017-05-17T06:09:22.890Z        WARN    TaskInfoFetcher-20170517_060516_00750_dxfd7.1.10-2138600        com.facebook.presto.server.remotetask.RequestErrorTracker       Error getting info for task 20170517_060516_00750_dxfd7.1.10: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed: http://172.31.17.171:8889/v1/task/20170517_060516_00750_dxfd7.1.10
2017-05-17T06:09:22.890Z        WARN    TaskInfoFetcher-20170517_060241_00742_dxfd7.8.7-2138600 com.facebook.presto.server.remotetask.RequestErrorTracker       Error getting info for task 20170517_060241_00742_dxfd7.8.7: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed: http://172.31.17.171:8889/v1/task/20170517_060241_00742_dxfd7.8.7
2017-05-17T06:09:22.890Z        WARN    TaskInfoFetcher-20170517_060245_00744_dxfd7.23.8-2138600        com.facebook.presto.server.remotetask.RequestErrorTracker       Error getting info for task 20170517_060245_00744_dxfd7.23.8: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed: http://172.31.17.171:8889/v1/task/20170517_060245_00744_dxfd7.23.8
2017-05-17T06:09:22.892Z        WARN    TaskInfoFetcher-20170517_060758_00752_dxfd7.24.13-2140514       com.facebook.presto.server.remotetask.RequestErrorTracker       Error getting info for task 20170517_060758_00752_dxfd7.24.13: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed: http://172.31.17.171:8889/v1/task/20170517_060758_00752_dxfd7.24.13

**Comment by chengat1314** [comment]
one interesting finding.
after the crash we lost one worker(we can see from the UI). 
CPU usage not high but keep at 20%. 
check top
   PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                                                                                                                   
 13067 presto    20   0 61.1g 3.3g  47m S  1.0  5.3   1:52.57 presto-server   
Also found a spike in the ganglia dashboard in "Loads/Procs" metrics "1-min".
Have this spike every time when crash. 
![image](https://cloud.githubusercontent.com/assets/3798412/26242725/fee1930a-3cbb-11e7-863e-e5b2ea746de4.png)


When I login into the worker.  the crash happened at around May 19 08:13
I found no more logs for file server.log and http-request.log. 
-rw-r--r-- 1 presto presto 4030647977 May 19 09:42 launcher.log
-rw-r--r-- 1 presto presto   91954255 May 19 08:14 server.log
-rw-r--r-- 1 presto presto   33261844 May 19 08:13 http-request.log

last a few log in server.log
2017-05-19T08:13:09.209Z	ERROR	Announcer-2	io.airlift.discovery.client.Announcer	Expected service announcement after 8000.00ms, but announcement was delayed 13.61s
2017-05-19T08:13:09.211Z	INFO	20170519_081126_00615_u9hkt.18.9-1-661	com.amazonaws.latency	ServiceName=[Amazon S3], StatusCode=[200], ServiceEndpoint=[https://grab-helios.s3-ap-southeast-1.amazonaws.com], Exception=[org.apache.http.NoHttpResponseException: The target server failed to respond], RequestType=[GetObjectMetadataRequest], AWSRequestID=[null, 3EED24581ACBCF35], HttpClientPoolPendingCount=0, RetryCapacityConsumed=0, HttpClientPoolAvailableCount=1, RequestCount=2, Exception=1, HttpClientPoolLeasedCount=95, RetryPauseTime=[219.494], ResponseProcessingTime=[0.052], ClientExecuteTime=[41062.346], HttpClientSendRequestTime=[0.07, 0.226], HttpRequestTime=[12853.336, 13607.328], RequestSigningTime=[0.128, 0.1], CredentialsRequestTime=[0.003, 0.002], HttpClientReceiveResponseTime=[0.151, 9.673], 
2017-05-19T08:14:09.438Z	INFO	Code-Cache-GC-Trigger	com.facebook.presto.server.CodeCacheGcTrigger	Triggering GC to avoid Code Cache eviction bugs

tailf launcher.log
I got 
10813:             1             16  sun.reflect.GeneratedConstructorAccessor98
10814:             1             16  sun.reflect.GeneratedConstructorAccessor9865
10815:             1             16  sun.reflect.GeneratedConstructorAccessor9866
10816:             1             16  sun.reflect.GeneratedConstructorAccessor9867
10817:             1             16  sun.reflect.GeneratedConstructorAccessor9868
10818:             1             16  sun.reflect.GeneratedConstructorAccessor990
10819:             1             16  sun.reflect.GeneratedConstructorAccessor9900
10820:             1             16  sun.reflect.GeneratedConstructorAccessor9901
10821:             1             16  sun.reflect.GeneratedConstructorAccessor9902
10822:             1             16  sun.reflect.GeneratedConstructorAccessor9949
10823:             1             16  sun.reflect.GeneratedConstructorAccessor996
10824:             1             16  sun.reflect.GeneratedConstructorAccessor9997
10825:             1             16  sun.reflect.GeneratedConstructorAccessor9998
10826:             1             16  sun.reflect.GeneratedMethodAccessor1
10827:             1             16  sun.reflect.GeneratedMethodAccessor10
10828:             1             16  sun.reflect.GeneratedMethodAccessor100
10829:             1             16  sun.reflect.GeneratedMethodAccessor103
10830:             1             16  sun.reflect.GeneratedMethodAccessor105
10831:             1             16  sun.reflect.GeneratedMethodAccessor106
10832:             1             16  sun.reflect.GeneratedMethodAccessor108
10833:             1             16  sun.reflect.GeneratedMethodAccessor11
10834:             1             16  sun.reflect.GeneratedMethodAccessor110
10835:             1             16  sun.reflect.GeneratedMethodAccessor111
10836:             1             16  sun.reflect.GeneratedMethodAccessor113
10837:             1             16  sun.reflect.GeneratedMethodAccessor115
10838:             1             16  sun.reflect.GeneratedMethodAccessor117
10839:             1             16  sun.reflect.GeneratedMethodAccessor118
10840:             1             16  sun.reflect.GeneratedMethodAccessor12
10841:             1             16  sun.reflect.GeneratedMethodAccessor120
10842:             1             16  sun.reflect.GeneratedMethodAccessor122
10843:             1             16  sun.reflect.GeneratedMethodAccessor123
10844:             1             16  sun.reflect.GeneratedMethodAccessor125
10845:             1             16  sun.reflect.GeneratedMethodAccessor127
10846:             1             16  sun.reflect.GeneratedMethodAccessor129
10847:             1             16  sun.reflect.GeneratedMethodAccessor13
10848:             1             16  sun.reflect.GeneratedMethodAccessor130
10849:             1             16  sun.reflect.GeneratedMethodAccessor132
10850:             1             16  sun.reflect.GeneratedMethodAccessor134
10851:             1             16  sun.reflect.GeneratedMethodAccessor135
10852:             1             16  sun.reflect.GeneratedMethodAccessor136
10853:             1             16  sun.reflect.GeneratedMethodAccessor137
10854:             1             16  sun.reflect.GeneratedMethodAccessor138
10855:             1             16  sun.reflect.GeneratedMethodAccessor139
10856:             1             16  sun.reflect.GeneratedMethodAccessor14
10857:             1             16  sun.reflect.GeneratedMethodAccessor140
10858:             1             16  sun.reflect.GeneratedMethodAccessor141
10859:             1             16  sun.reflect.GeneratedMethodAccessor142
10860:             1             16  sun.reflect.GeneratedMethodAccessor143
10861:             1             16  sun.reflect.GeneratedMethodAccessor144
10862:             1             16  sun.reflect.GeneratedMethodAccessor145
10863:             1             16  sun.reflect.GeneratedMethodAccessor146
10864:             1             16  sun.reflect.GeneratedMethodAccessor147
10865:             1             16  sun.reflect.GeneratedMethodAccessor148
10866:             1             16  sun.reflect.GeneratedMethodAccessor149
10867:             1             16  sun.reflect.GeneratedMethodAccessor15
10868:             1             16  sun.reflect.GeneratedMethodAccessor152
10869:             1             16  sun.reflect.GeneratedMethodAccessor153
10870:             1             16  sun.reflect.GeneratedMethodAccessor154
10871:             1             16  sun.reflect.GeneratedMethodAccessor155
10872:             1             16  sun.reflect.GeneratedMethodAccessor156
10873:             1             16  sun.reflect.GeneratedMethodAccessor157
10874:             1             16  sun.reflect.GeneratedMethodAccessor158
10875:             1             16  sun.reflect.GeneratedMethodAccessor159
10876:             1             16  sun.reflect.GeneratedMethodAccessor16
10877:             1             16  sun.reflect.GeneratedMethodAccessor160
10878:             1             16  sun.reflect.GeneratedMethodAccessor161
10879:             1             16  sun.reflect.GeneratedMethodAccessor162
10880:             1             16  sun.reflect.GeneratedMethodAccessor164
10881:             1             16  sun.reflect.GeneratedMethodAccessor165
10882:             1             16  sun.reflect.GeneratedMethodAccessor166
10883:             1             16  sun.reflect.GeneratedMethodAccessor168
10884:             1             16  sun.reflect.GeneratedMethodAccessor169
10885:             1             16  sun.reflect.GeneratedMethodAccessor170
10886:             1             16  sun.reflect.GeneratedMethodAccessor172
10887:             1             16  sun.reflect.GeneratedMethodAccessor173
10888:             1             16  sun.reflect.GeneratedMethodAccessor174
10889:             1             16  sun.reflect.GeneratedMethodAccessor176
10890:             1             16  sun.reflect.GeneratedMethodAccessor178
10891:             1             16  sun.reflect.GeneratedMethodAccessor179
10892:             1             16  sun.reflect.GeneratedMethodAccessor180
10893:             1             16  sun.reflect.GeneratedMethodAccessor181
10894:             1             16  sun.reflect.GeneratedMethodAccessor182
10895:             1             16  sun.reflect.GeneratedMethodAccessor184
10896:             1             16  sun.reflect.GeneratedMethodAccessor187
10897:             1             16  sun.reflect.GeneratedMethodAccessor188
10898:             1             16  sun.reflect.GeneratedMethodAccessor190
10899:             1             16  sun.reflect.GeneratedMethodAccessor191
10900:             1             16  sun.reflect.GeneratedMethodAccessor193
10901:             1             16  sun.reflect.GeneratedMethodAccessor195
10902:             1             16  sun.reflect.GeneratedMethodAccessor196
10903:             1             16  sun.reflect.GeneratedMethodAccessor197
10904:             1             16  sun.reflect.GeneratedMethodAccessor199
10905:             1             16  sun.reflect.GeneratedMethodAccessor2
10906:             1             16  sun.reflect.GeneratedMethodAccessor201
10907:             1             16  sun.reflect.GeneratedMethodAccessor203
10908:             1             16  sun.reflect.GeneratedMethodAccessor205
10909:             1             16  sun.reflect.GeneratedMethodAccessor206
10910:             1             16  sun.reflect.GeneratedMethodAccessor208
10911:             1             16  sun.reflect.GeneratedMethodAccessor210
10912:             1             16  sun.reflect.GeneratedMethodAccessor211
10913:             1             16  sun.reflect.GeneratedMethodAccessor212
10914:             1             16  sun.reflect.GeneratedMethodAccessor214
10915:             1             16  sun.reflect.GeneratedMethodAccessor215
10916:             1             16  sun.reflect.GeneratedMethodAccessor216
10917:             1             16  sun.reflect.GeneratedMethodAccessor218
10918:             1             16  sun.reflect.GeneratedMethodAccessor219
10919:             1             16  sun.reflect.GeneratedMethodAccessor220
10920:             1             16  sun.reflect.GeneratedMethodAccessor222
10921:             1             16  sun.reflect.GeneratedMethodAccessor224
10922:             1             16  sun.reflect.GeneratedMethodAccessor226
10923:             1             16  sun.reflect.GeneratedMethodAccessor228
10924:             1             16  sun.reflect.GeneratedMethodAccessor230
10925:             1             16  sun.reflect.GeneratedMethodAccessor232
10926:             1             16  sun.reflect.GeneratedMethodAccessor234
10927:             1             16  sun.reflect.GeneratedMethodAccessor236
10928:             1             16  sun.reflect.GeneratedMethodAccessor237
10929:             1             16  sun.reflect.GeneratedMethodAccessor238
10930:             1             16  sun.reflect.GeneratedMethodAccessor239
10931:             1             16  sun.reflect.GeneratedMethodAccessor240
10932:             1             16  sun.reflect.GeneratedMethodAccessor241
10933:             1             16  sun.reflect.GeneratedMethodAccessor242
10934:             1             16  sun.reflect.GeneratedMethodAccessor243
10935:             1             16  sun.reflect.GeneratedMethodAccessor244
10936:             1             16  sun.reflect.GeneratedMethodAccessor247
10937:             1             16  sun.reflect.GeneratedMethodAccessor248
10938:             1             16  sun.reflect.GeneratedMethodAccessor249
10939:             1             16  sun.reflect.GeneratedMethodAccessor25
10940:             1             16  sun.reflect.GeneratedMethodAccessor250
10941:             1             16  sun.reflect.GeneratedMethodAccessor251
10942:             1             16  sun.reflect.GeneratedMethodAccessor252
10943:             1             16  sun.reflect.GeneratedMethodAccessor253
10944:             1             16  sun.reflect.GeneratedMethodAccessor255
10945:             1             16  sun.reflect.GeneratedMethodAccessor256
10946:             1             16  sun.reflect.GeneratedMethodAccessor257
10947:             1             16  sun.reflect.GeneratedMethodAccessor258
10948:             1             16  sun.reflect.GeneratedMethodAccessor259
10949:             1             16  sun.reflect.GeneratedMethodAccessor26
10950:             1             16  sun.reflect.GeneratedMethodAccessor260
10951:             1             16  sun.reflect.GeneratedMethodAccessor261
10952:             1             16  sun.reflect.GeneratedMethodAccessor262
10953:             1             16  sun.reflect.GeneratedMethodAccessor263
10954:             1             16  sun.reflect.GeneratedMethodAccessor264
10955:             1             16  sun.reflect.GeneratedMethodAccessor265
10956:             1             16  sun.reflect.GeneratedMethodAccessor266
10957:             1             16  sun.reflect.GeneratedMethodAccessor268
10958:             1             16  sun.reflect.GeneratedMethodAccessor27
10959:             1             16  sun.reflect.GeneratedMethodAccessor270
10960:             1             16  sun.reflect.GeneratedMethodAccessor271
10961:             1             16  sun.reflect.GeneratedMethodAccessor274
10962:             1             16  sun.reflect.GeneratedMethodAccessor278
10963:             1             16  sun.reflect.GeneratedMethodAccessor28
10964:             1             16  sun.reflect.GeneratedMethodAccessor281
10965:             1             16  sun.reflect.GeneratedMethodAccessor285
10966:             1             16  sun.reflect.GeneratedMethodAccessor286
10967:             1             16  sun.reflect.GeneratedMethodAccessor287
10968:             1             16  sun.reflect.GeneratedMethodAccessor288
10969:             1             16  sun.reflect.GeneratedMethodAccessor289
10970:             1             16  sun.reflect.GeneratedMethodAccessor29
10971:             1             16  sun.reflect.GeneratedMethodAccessor290
10972:             1             16  sun.reflect.GeneratedMethodAccessor291
10973:             1             16  sun.reflect.GeneratedMethodAccessor292
10974:             1             16  sun.reflect.GeneratedMethodAccessor293
10975:             1             16  sun.reflect.GeneratedMethodAccessor294
10976:             1             16  sun.reflect.GeneratedMethodAccessor295
10977:             1             16  sun.reflect.GeneratedMethodAccessor296
10978:             1             16  sun.reflect.GeneratedMethodAccessor297
10979:             1             16  sun.reflect.GeneratedMethodAccessor298
10980:             1             16  sun.reflect.GeneratedMethodAccessor299
10981:             1             16  sun.reflect.GeneratedMethodAccessor3
10982:             1             16  sun.reflect.GeneratedMethodAccessor30
10983:             1             16  sun.reflect.GeneratedMethodAccessor300
10984:             1             16  sun.reflect.GeneratedMethodAccessor301
10985:             1             16  sun.reflect.GeneratedMethodAccessor302
10986:             1             16  sun.reflect.GeneratedMethodAccessor303
10987:             1             16  sun.reflect.GeneratedMethodAccessor304
10988:             1             16  sun.reflect.GeneratedMethodAccessor306
10989:             1             16  sun.reflect.GeneratedMethodAccessor308
10990:             1             16  sun.reflect.GeneratedMethodAccessor31
10991:             1             16  sun.reflect.GeneratedMethodAccessor310
10992:             1             16  sun.reflect.GeneratedMethodAccessor312
10993:             1             16  sun.reflect.GeneratedMethodAccessor313
10994:             1             16  sun.reflect.GeneratedMethodAccessor316
10995:             1             16  sun.reflect.GeneratedMethodAccessor317
10996:             1             16  sun.reflect.GeneratedMethodAccessor318
10997:             1             16  sun.reflect.GeneratedMethodAccessor32
10998:             1             16  sun.reflect.GeneratedMethodAccessor320
10999:             1             16  sun.reflect.GeneratedMethodAccessor322
11000:             1             16  sun.reflect.GeneratedMethodAccessor324
11001:             1             16  sun.reflect.GeneratedMethodAccessor326
11002:             1             16  sun.reflect.GeneratedMethodAccessor327
11003:             1             16  sun.reflect.GeneratedMethodAccessor33
11004:             1             16  sun.reflect.GeneratedMethodAccessor330
11005:             1             16  sun.reflect.GeneratedMethodAccessor332
11006:             1             16  sun.reflect.GeneratedMethodAccessor334
11007:             1             16  sun.reflect.GeneratedMethodAccessor335
11008:             1             16  sun.reflect.GeneratedMethodAccessor338
11009:             1             16  sun.reflect.GeneratedMethodAccessor340
11010:             1             16  sun.reflect.GeneratedMethodAccessor341
11011:             1             16  sun.reflect.GeneratedMethodAccessor343
11012:             1             16  sun.reflect.GeneratedMethodAccessor345
11013:             1             16  sun.reflect.GeneratedMethodAccessor347
11014:             1             16  sun.reflect.GeneratedMethodAccessor348
11015:             1             16  sun.reflect.GeneratedMethodAccessor35
11016:             1             16  sun.reflect.GeneratedMethodAccessor350
11017:             1             16  sun.reflect.GeneratedMethodAccessor351
11018:             1             16  sun.reflect.GeneratedMethodAccessor352
11019:             1             16  sun.reflect.GeneratedMethodAccessor355
11020:             1             16  sun.reflect.GeneratedMethodAccessor359
11021:             1             16  sun.reflect.GeneratedMethodAccessor36
11022:             1             16  sun.reflect.GeneratedMethodAccessor361
11023:             1             16  sun.reflect.GeneratedMethodAccessor363
11024:             1             16  sun.reflect.GeneratedMethodAccessor364
11025:             1             16  sun.reflect.GeneratedMethodAccessor365
11026:             1             16  sun.reflect.GeneratedMethodAccessor366
11027:             1             16  sun.reflect.GeneratedMethodAccessor367
11028:             1             16  sun.reflect.GeneratedMethodAccessor368
11029:             1             16  sun.reflect.GeneratedMethodAccessor369
11030:             1             16  sun.reflect.GeneratedMethodAccessor370
11031:             1             16  sun.reflect.GeneratedMethodAccessor371
11032:             1             16  sun.reflect.GeneratedMethodAccessor372
11033:             1             16  sun.reflect.GeneratedMethodAccessor373
11034:             1             16  sun.reflect.GeneratedMethodAccessor374
11035:             1             16  sun.reflect.GeneratedMethodAccessor375
11036:             1             16  sun.reflect.GeneratedMethodAccessor376
11037:             1             16  sun.reflect.GeneratedMethodAccessor377
11038:             1             16  sun.reflect.GeneratedMethodAccessor378
11039:             1             16  sun.reflect.GeneratedMethodAccessor4
11040:             1             16  sun.reflect.GeneratedMethodAccessor48
11041:             1             16  sun.reflect.GeneratedMethodAccessor49
11042:             1             16  sun.reflect.GeneratedMethodAccessor5
11043:             1             16  sun.reflect.GeneratedMethodAccessor50
11044:             1             16  sun.reflect.GeneratedMethodAccessor51
11045:             1             16  sun.reflect.GeneratedMethodAccessor52
11046:             1             16  sun.reflect.GeneratedMethodAccessor53
11047:             1             16  sun.reflect.GeneratedMethodAccessor54
11048:             1             16  sun.reflect.GeneratedMethodAccessor55
11049:             1             16  sun.reflect.GeneratedMethodAccessor56
11050:             1             16  sun.reflect.GeneratedMethodAccessor57
11051:             1             16  sun.reflect.GeneratedMethodAccessor58
11052:             1             16  sun.reflect.GeneratedMethodAccessor59
11053:             1             16  sun.reflect.GeneratedMethodAccessor6
11054:             1             16  sun.reflect.GeneratedMethodAccessor60
11055:             1             16  sun.reflect.GeneratedMethodAccessor61
11056:             1             16  sun.reflect.GeneratedMethodAccessor62
11057:             1             16  sun.reflect.GeneratedMethodAccessor63
11058:             1             16  sun.reflect.GeneratedMethodAccessor64
11059:             1             16  sun.reflect.GeneratedMethodAccessor65
11060:             1             16  sun.reflect.GeneratedMethodAccessor66
11061:             1             16  sun.reflect.GeneratedMethodAccessor67
11062:             1             16  sun.reflect.GeneratedMethodAccessor68
11063:             1             16  sun.reflect.GeneratedMethodAccessor69
11064:             1             16  sun.reflect.GeneratedMethodAccessor7
11065:             1             16  sun.reflect.GeneratedMethodAccessor70
11066:             1             16  sun.reflect.GeneratedMethodAccessor71
11067:             1             16  sun.reflect.GeneratedMethodAccessor72
11068:             1             16  sun.reflect.GeneratedMethodAccessor74
11069:             1             16  sun.reflect.GeneratedMethodAccessor75
11070:             1             16  sun.reflect.GeneratedMethodAccessor76
11071:             1             16  sun.reflect.GeneratedMethodAccessor77
11072:             1             16  sun.reflect.GeneratedMethodAccessor78
11073:             1             16  sun.reflect.GeneratedMethodAccessor79
11074:             1             16  sun.reflect.GeneratedMethodAccessor8
11075:             1             16  sun.reflect.GeneratedMethodAccessor80
11076:             1             16  sun.reflect.GeneratedMethodAccessor81
11077:             1             16  sun.reflect.GeneratedMethodAccessor82
11078:             1             16  sun.reflect.GeneratedMethodAccessor83
11079:             1             16  sun.reflect.GeneratedMethodAccessor84
11080:             1             16  sun.reflect.GeneratedMethodAccessor85
11081:             1             16  sun.reflect.GeneratedMethodAccessor86
11082:             1             16  sun.reflect.GeneratedMethodAccessor87
11083:             1             16  sun.reflect.GeneratedMethodAccessor88
11084:             1             16  sun.reflect.GeneratedMethodAccessor89
11085:             1             16  sun.reflect.GeneratedMethodAccessor9
11086:             1             16  sun.reflect.GeneratedMethodAccessor90
11087:             1             16  sun.reflect.GeneratedMethodAccessor91
11088:             1             16  sun.reflect.GeneratedMethodAccessor92
11089:             1             16  sun.reflect.GeneratedMethodAccessor93
11090:             1             16  sun.reflect.GeneratedMethodAccessor94
11091:             1             16  sun.reflect.GeneratedMethodAccessor95
11092:             1             16  sun.reflect.GeneratedMethodAccessor96
11093:             1             16  sun.reflect.GeneratedMethodAccessor97
11094:             1             16  sun.reflect.GeneratedMethodAccessor99
11095:             1             16  sun.reflect.ReflectionFactory
11096:             1             16  sun.reflect.generics.tree.BooleanSignature
11097:             1             16  sun.reflect.generics.tree.BottomSignature
11098:             1             16  sun.reflect.generics.tree.ByteSignature
11099:             1             16  sun.reflect.generics.tree.DoubleSignature
11100:             1             16  sun.reflect.generics.tree.IntSignature
11101:             1             16  sun.reflect.generics.tree.LongSignature
11102:             1             16  sun.reflect.generics.tree.VoidDescriptor
11103:             1             16  sun.rmi.registry.RegistryImpl$$Lambda$131/1367503763
11104:             1             16  sun.rmi.registry.RegistryImpl$$Lambda$132/62803825
11105:             1             16  sun.rmi.registry.RegistryImpl_Skel
11106:             1             16  sun.rmi.runtime.Log$LoggerLogFactory
11107:             1             16  sun.rmi.transport.DGCImpl$$Lambda$129/425107133
11108:             1             16  sun.rmi.transport.DGCImpl$2$$Lambda$130/62309924
11109:             1             16  sun.rmi.transport.DGCImpl_Skel
11110:             1             16  sun.rmi.transport.proxy.RMIDirectSocketFactory
11111:             1             16  sun.rmi.transport.tcp.TCPTransport$1
11112:             1             16  sun.security.rsa.RSAKeyFactory
11113:             1             16  sun.security.ssl.DummyX509KeyManager
11114:             1             16  sun.security.util.ByteArrayLexOrder
11115:             1             16  sun.security.util.ByteArrayTagOrder
11116:             1             16  sun.text.normalizer.NormalizerImpl
11117:             1             16  sun.text.normalizer.NormalizerImpl$AuxTrieImpl
11118:             1             16  sun.text.normalizer.NormalizerImpl$FCDTrieImpl
11119:             1             16  sun.text.normalizer.NormalizerImpl$NormTrieImpl
11120:             1             16  sun.util.locale.provider.AuxLocaleProviderAdapter$NullProvider
11121:             1             16  sun.util.locale.provider.CalendarDataUtility$CalendarWeekParameterGetter
11122:             1             16  sun.util.locale.provider.TimeZoneNameUtility$TimeZoneNameGetter
11123:             1             16  sun.util.resources.LocaleData$LocaleDataResourceBundleControl
Total      48548788    52007652128
, 2.5459894 secs]
 [Times: user=15.42 sys=0.03, real=11.44 secs] 
         vmop                    [threads: total initially_running wait_to_block]    [time: spin block sync cleanup vmop] page_trap_count
183337.547: G1CollectForAllocation           [     513          0              0    ]      [     0     0     0     1 11444    ]  0   
2017-05-19T09:43:53.632+0000: 183348.992: Total time for which application threads were stopped: 11.4466649 seconds, Stopping threads took: 0.0000778 seconds
2017-05-19T09:43:53.632+0000: 183348.992: [GC concurrent-mark-abort]
2017-05-19T09:43:53.632+0000: 183348.993: Application time: 0.0006104 seconds

**Comment by chengat1314** [comment]
One more graph 
<img width="581" alt="image" src="https://cloud.githubusercontent.com/assets/3798412/26242763/23f637ae-3cbc-11e7-9f56-4188427e7db6.png">

![image](https://cloud.githubusercontent.com/assets/3798412/26242812/4f3e2e12-3cbc-11e7-84e8-5fb29ab48fe8.png)
for this case, the cpu is always more than 60% more even no job was running.

**Comment by raghavsethi** [comment]
Using CPU when no queries are running seems like a separate problem. Could you file an issue with information specific to that?  There's too much going on in this issue.

**Comment by chengat1314** [comment]
hi @raghavsethi  yeah I guess, too much infor.
I think I may found the problem. it's because of network bottleneck. 
We were using m4.4 which has bandwidth limited at 2Gb/s;
When I look at the network traffic history, the bandwidth reached near 3Gb and that's when our cluster crash. After restart cluster, everything want back immediately. 

My Solution was to change to the instance support better network performance (up to 10Gb).
Now looks better in production cluster. and the network reach 5Gb when same load came. 
While, now looks good but not sure if we have new problem or not. will keep update if any issues. 

So @raghavsethi  based this, would you mind help me to understand why we have those errors above?  

Thanks,
Cheng Feng

**Comment by raghavsethi** [comment]
Sorry, what problem are you referring to if the network bottleneck is resolved?

**Comment by chengat1314** [comment]
@raghavsethi ,sorry for too much infor. the network bottleneck resolved by change the instances.
My question is if you know why the the network bottleneck can cause the issue described above?
Is possible the network bottleneck lead to kicking out the workers and fail the queries? 
Thank!

**Comment by raghavsethi** [comment]
Yes, the network bottleneck can lead to messages being lost, which would lead to the coordinator thinking worker nodes have dropped out. If any worker node currently running splits for a query drops out, the query will fail.

**Comment by chengat1314** [comment]
ok, I see thanks @raghavsethi
