### ISSUE TITLE
Add UUID Type

### ISSUE THREAD

**Issue by Downchuck** [prestodb/presto#8094]
There are very many use cases I've hit where a UUID is a column in the data -- some data provides split it into two longs (like Adobe), many send it in base 16 as a string, some upper case some lower case, some with hyphens, some without. Then there's this cool variant by Adobe: "128-bit number that consists of 2 signed, positive, 64-bit numbers in base 10, both padded to 19 zeros, and then concatenated". [SiteCatalyst](https://marketing.adobe.com/resources/help/en_US/sc/clickstream/analytics_clickstream.pdf)

The code for DECIMAL is very similar for what a UUID might look like. It's just two 64 bit longs.

**Comment by dain** [comment]
Instead, why not add support for `BINARY(16)`?

**Comment by Downchuck** [comment]
it can be pretty awful working with BINARY - it's available in Hive but the learning curve and maintenance for anyone using it is just too high for me to push, so we end up using hex strings.

Note UUID is a specific type supported in SQL Server, PostgreSQL and the like; there's been at least one plug-in attempt for Presto and well, it's more of a semantic and usability thing. I can use two longs, as well, and split it up, but just like BINARY, I get into usability issues with consumers (analysts running SQL queries).

This is far more of a usability item than a tech item, unfortunately. Otherwise, yes, I think BINARY(16) of course makes a lot of sense. So does int128 if we're thinking those kind of thoughts.

**Comment by Downchuck** [comment]
Postgresql valid values for input of cast(str as binary(16)):
https://www.postgresql.org/docs/9.1/static/datatype-uuid.html

Mac address parsing might extend a few more inputs, such as an ipv6 host address:
https://www.postgresql.org/docs/9.1/static/datatype-net-types.html


Some uuid conversion cases:
```
uuid(binary(16)) : str,
uuid_high(binary(16)) : long
uuid_low(binary(16)) : long
```

Some other casts:
```
to_hex(binary(16))  : char(32),
binary16(long,long) : binary(16)
```

**Comment by ankitpal11** [comment]
how can i create table with a column that will contain a unique default value ?
