### ISSUE TITLE
JDBC SSL via LDAP on AWS EMR

### ISSUE THREAD

**Issue by samelamin** [prestodb/presto#8108]
Hi All,

We would like to integrate AD authentication to our presto cluster hosted on AWS EMR

Is that at all possible? I heard that the current JDBC driver does not support SSL 

Is that still the case? 

Any ideas how I can implement this feature?

**Comment by cawallin** [comment]
The Teradata driver (available from www.teradata.com/presto) supports SSL, so you can use that. There's also an open PR about adding SSL support to the open source driver (https://github.com/prestodb/presto/pull/7725)

**Comment by cawallin** [comment]
I'm going to close this, feel free to ask any additional questions or re-open if it doesn't work for you.
