### ISSUE TITLE
Add HiveConnector procedure to set a table to be offline to Presto

### ISSUE THREAD

**Issue by wenleix** [prestodb/presto#8118]
Currently the only way to set a table to be offline to Presto is via Hive:

```
hive> ALTER TABLE bad_table SET TBLPROPERTIES ('presto_offline' = 'Evil table to Presto');
```

Presto should able to offline a table through Connector Procedure: https://prestodb.io/docs/current/sql/call.html

**Comment by dain** [comment]
Really, we should be able to alter table properties.

**Comment by wenleix** [comment]
We should have a procedure call for Hive connector to set table/partition properties.
