### ISSUE TITLE
Error while accessing individual array element of a array column (complex data type) from a table 

### ISSUE THREAD

**Issue by vandana7** [prestodb/presto#8129]
i am  facing some problem while accessing individual array element from an array column.when i am executing query for accessing array column it gets executed and i am getting my result correct but when i am trying to access individual element of same array column i am getting an error.

schema of my table:
    Column    |       Type       | Extra | Comment 
--------------+------------------+-------+---------
 cust_id      | varchar          |       |         
 year         | integer          |       |         
 month        | integer          |       |         
 age          | integer          |       |         
 gender       | varchar          |       |         
 educated     | varchar          |       |         
 is_married   | varchar          |       |         
 array_int    | array(integer)   |       |         
 array_string | array(varchar)   |       |         
 array_date   | array(timestamp) |       |         
 card_count   | integer          |       |         
 debit_count  | integer          |       |         
 credit_count | integer          |       |         
 deposit      | double           |       |         
 hq_deposit   | double           |       |         
(15 rows)

executed queries 
1) select array_int from array_com;(for accessing array column from table)
output:
            array_int             
----------------------------------
 [1234, 5678, 9101, 11121, 12357] 
 [1235, 5679, 9102, 11122, 12358] 
 [1236, 5680, 9103, 11123, 12359] 
 [1237, 5681, 9104, 11124, 12360] 
 [1238, 5682, 9105, 11125, 12361] 
 [1239, 5683, 9106, 11126, 12362] 
 [1240, 5684, 9107, 11127, 12363] 
 [1241, 5685, 9108, 11128, 12364] 
 [1242, 5686, 9109, 11129, 12365] 
 [1243, 5687, 9110, 11130, 12366] 
 [1244, 5688, 9111, 11131, 12367] 
 [1245, 5689, 9112, 11132, 12368] 
 [1246, 5690, 9113, 11133, 12369] 

2)  select array_int[1] from array_com;(for accessing individual array element from array column)
output:(Error m getting)
Query 20170525_125437_00035_vkcsi failed: line 1:8: Operator $operator$SUBSCRIPT(array(integer),bigint):integer argument 0 must evaluate to a array(integer) (actual: array(integer))
select array_int[1] from array_com

note: i am trying to build my own custom connector.

**Comment by findepi** [comment]
Could you provide steps to reproduce? I tried:

```
presto> select x[1] from (values array[1,2]) t(x);
 _col0 
-------
     1 
(1 row)
```
and
```
presto> create table memory.default.t as select * from (values array[1,2]) t(x);
CREATE TABLE: 1 row

presto> select x[1] from memory.default.t;
 _col0 
-------
     1 
(1 row)
```

**Comment by vandana7** [comment]
Thanks for the reply, I tried with hive connector and its working fine. I think it's an issue with my custom connector.
