### ISSUE TITLE
Operator '-' '+' cannot be applied between timestamp

### ISSUE THREAD

**Issue by ebuildy** [prestodb/presto#8135]
- PrestoDB 0.161
- Apache Hive with parquet files

Running this query (to sessionize web events):

```
SELECT user_id, date_timestamp - LAG(date_timestamp) 
OVER (PARTITION BY user_id ORDER BY date_timestamp) 
FROM searches 
```

Give error: ``line 1:39: '-' cannot be applied to timestamp, timestamp``.

It works fine if I use ``to_unixtime(date_timestamp)`` but wondering why is not possible between timestamp?

Thanks you,

**Comment by findepi** [comment]
cc @fiedukow

**Comment by ebyhr** [comment]
I checked latest codes and the reason seems that `TimeOperators`, `TimestampOperators`, `TimestampWithTimeZoneOperators` and `TimeWithTimeZoneOperators` don't have `@ScalarOperator(ADD)` and `@ScalarOperator(SUBTRACT)`.

Followings are simple examples to implement the operator.
```
presto> select localtimestamp + localtimestamp;
Query 20170722_153921_00002_6va4p failed: line 1:23: '+' cannot be applied to timestamp, timestamp
```

Implement  add operator (Please ignore the detail since this is just a example)
```java
    @ScalarOperator(ADD)
    @SqlType(StandardTypes.TIMESTAMP)
    public static long add(ConnectorSession session, @SqlType(StandardTypes.TIMESTAMP) long left, @SqlType(StandardTypes.TIMESTAMP) long right)
    {
        long timeMillis = unpackMillisUtc(left) + unpackMillisUtc(right);
        return packDateTimeWithZone(timeMillis, session.getTimeZoneKey());
    }
```

Execute same query
```
presto> select localtimestamp + localtimestamp;
          _col0          
-------------------------
 2065-02-10 16:26:00.133 
(1 row)
```

**Comment by martint** [comment]
Adding two time stamps doesn't make much sense. Subtracting two time stamps should produce an "interval day to second".

**Comment by electrum** [comment]
Merged PR for subtraction
