### ISSUE TITLE
CLI doesn't abort query on the server when partial results already shown in pager

### ISSUE THREAD

**Issue by findepi** [prestodb/presto#8142]
## Steps to reproduce

1. in CLI execute
```
select * from tpch.sf1.orders;
```
2. wait until initial results are already visible (but query is still running)
3. press `q` to quit pager

Now CLI prints 
```
(query aborted by user)

Query 20170529_130533_00023_9v5js, RUNNING, 1 node
Splits: 20 total, 0 done (0.00%)
0:05 [0 rows, 0B] [0 rows/s, 0B/s]

Query aborted by user
```

## Observed

- Query still running on the server.
- Query is only killed by "Failing abandoned query".
- if query is killed manually in the UI, it ends immediately, so it looks like CLI fails to deliver kill to the server

**Comment by haozhun** [comment]
Is this fixed? I can't reproduce it.

**Comment by cawallin** [comment]
@arhimondr fixed it in https://github.com/prestodb/presto/pull/8575.
