### ISSUE TITLE
Integer Multiplication Overflow on multiplying large integers

### ISSUE THREAD

**Issue by abhishekshenoy** [prestodb/presto#8145]
Scenario:

On multiplying two large Integers it throws an **Multiplication Integer Overflow**

**ex: select col1 from table where col1 > 100000*1000000;**

On seeing the code i found that as the parameters are within the integer range it hits the IntegerOperator Class which for the multiply function is wrapper on top of Math Library functions.

    public static int multiplyExact(int x, int y) {
        long r = (long)x * (long)y;
        if ((int)r != r) {
            throw new ArithmeticException("integer overflow");
        }
        return (int)r;
    }

This is being handled implicitly in hive. Have moved with a workaround as of now but how is this being handled as of now in presto ?

**Comment by electrum** [comment]
Raising an error on overflow is required by the SQL standard and is generally what you want, since it prevents you from silently getting an incorrect answer. Hive handles this by ignoring overflow. You can switch to a different data type by casting one of the values to BIGINT or DECIMAL.

```sql
SELECT cast(x AS bigint) * y;
SELECT cast(x AS decimal(38)) * y;
```

**Comment by electrum** [comment]
You can also use DOUBLE if you fine with using approximate numerics.

**Comment by abhishekshenoy** [comment]
In my case the col1 is already a bigint , the issue happens on multiplying the two integers contants. And finding out this scenario in the filter condition to apply a cast will be an unnecesary overhead while parsing the query ( i recieve the query from an upstream layer which is dumb and only role is to form query as the input ) .

**Comment by electrum** [comment]
What is your desired outcome on overflow?

**Comment by abhishekshenoy** [comment]
On mathematical operations it would be fine to ignore such overflows.
