### ISSUE TITLE
Please update joda-time dependency from 2.8.2 to 2.9.9.

### ISSUE THREAD

**Issue by omercioglu** [prestodb/presto#8153]
Please update joda-time dependency version from 2.8.2 to 2.9.9.
Version 2.8.2 is released nearly 2 years ago (Aug 11, 2015) and contains out of date time-zone data, resulting in errors in date-time functions.

**Comment by haozhun** [comment]
I filed an issue with joda. But I don't expect that they'll fix it. https://github.com/JodaOrg/joda-time/issues/427

I believe the best way to address this is to:
* Update to joda 2.9.4 now
* Refrain from updating joda until we update minimum java version to 8u121

**Comment by haozhun** [comment]
After a discussion with @martint, we decide that this is not a significant enough issue for Presto. We'll just update to joda 2.9.9 with a release notes mentioning this known bug.

**Comment by electrum** [comment]
We should increase the minimum Java version if this will cause incorrect results on older versions. As we've seen many times, users often miss release notes.

**Comment by martint** [comment]
> We should increase the minimum Java version if this will cause incorrect results on older versions. As we've seen many times, users often miss release notes.

That's a bit heavy-handed. The issue affects a single timezone that is unlikely to be used by any Presto user in practice. Some users may not be able to update to the latest version of Java so easily. It's better to just document it as a known issue.

**Comment by omercioglu** [comment]
Actually joda update also includes 2 years worth of DST adjustments as
well. While operating on time series data, international timestamp
conversions deviates several hours in such cases without this update.
Other alternatives may be including the updated joda library manually or
recompiling presto with updated pom.

**Comment by haozhun** [comment]
Fixed by 8156.
