### ISSUE TITLE
Avoid unnecessary exchange and partial aggregation in correlated scalar subquery and correlated IN predicate

### ISSUE THREAD

**Issue by findepi** [prestodb/presto#8171]
For a correlated scalar subquery like
```
select name, (select max(name) from region where regionkey = nation.regionkey) from nation;
```

we currently produce the following plan (i'm using `set session push_aggregation_through_join = false;` to have the plan more readable)
```
 - Output[name, _col1] => [name:varchar(25), max:varchar(25)]
     _col1 := max
   - RemoteExchange[GATHER] => name:varchar(25), max:varchar(25)
     - Project[] => [name:varchar(25), max:varchar(25)]
x      - Aggregate(FINAL)[name, regionkey, unique][$hashvalue] => [name:varchar(25), regionkey:bigint, unique:bigint, $hashvalue:bigint, max:varchar(25)]
x          max := "max"("max_17")
x        - LocalExchange[HASH][$hashvalue] ("name", "regionkey", "unique") => name:varchar(25), regionkey:bigint, unique:bigint, max_17:varbinary, $hashvalue:bigint
x          - Aggregate(PARTIAL)[name, regionkey, unique][$hashvalue_23] => [name:varchar(25), regionkey:bigint, unique:bigint, $hashvalue_23:bigint, max_17:varbinary]
x              max_17 := "max"("name_1")
             - Project[] => [name:varchar(25), regionkey:bigint, unique:bigint, name_1:varchar(25), $hashvalue_23:bigint]
                 $hashvalue_23 := "combine_hash"("combine_hash"("combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("name"), 0)), COALESCE("$operator$hash_code"("regionkey"), 0)), COALESCE("$operator$hash_code"("unique"), 0))
               - LeftJoin[("regionkey" = "regionkey_0")][$hashvalue_18, $hashvalue_20] => [name:varchar(25), regionkey:bigint, unique:bigint, name_1:varchar(25)]
                 - RemoteExchange[REPARTITION][$hashvalue_18] => name:varchar(25), regionkey:bigint, unique:bigint, $hashvalue_18:bigint
                   - Project[] => [name:varchar(25), regionkey:bigint, unique:bigint, $hashvalue_19:bigint]
                       $hashvalue_19 := "combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("regionkey"), 0))
                     - AssignUniqueId => [name:varchar(25), regionkey:bigint, unique:bigint]
                       - TableScan[tpch:tpch:nation:sf0.01, originalConstraint = true] => [name:varchar(25), regionkey:bigint]
                           name := tpch:name
                           regionkey := tpch:regionkey
                 - LocalExchange[HASH][$hashvalue_20] ("regionkey_0") => regionkey_0:bigint, name_1:varchar(25), $hashvalue_20:bigint
                   - RemoteExchange[REPARTITION][$hashvalue_21] => regionkey_0:bigint, name_1:varchar(25), $hashvalue_21:bigint
                     - ScanProject[table = tpch:tpch:region:sf0.01, originalConstraint = true] => [regionkey_0:bigint, name_1:varchar(25), $hashvalue_22:bigint]
                         $hashvalue_22 := "combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("regionkey_0"), 0))
                         regionkey_0 := tpch:regionkey
                         name_1 := tpch:name
```

the part marked has redundant local exchange and partial aggregation. Since the aggregation's group contains unique symbol assigned before join then, at least as long the aggregation remains above the join, no exchange is needed. Values with same group key will be in the same split (pipeline) anyway. The marked group could be replaced with single step aggregation (and no exchange).

Same applies to correlated IN predicates.

cc @kokosing

**Comment by kokosing** [comment]
IMO this kind of optimization well fits into the new optimizer idea (cost-based) where plan with unique symbol would have physical property (aka. trait) which would say that values are split locally unique (there are no duplicate in any other split) and so cost-based optimizer would not add any local exchanges and partial aggregation there.

**Comment by KBP-TDC** [comment]
@kokosing The traits are crucial here. No cost-based decision is made however.

**Comment by kokosing** [comment]
True!

02.06.2017 20:28 "Kamil Bajda-Pawlikowski" <notifications@github.com>
napisał(a):

@kokosing <https://github.com/kokosing> The traits are crucial here. No
cost-based decision is made however.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/prestodb/presto/issues/8171#issuecomment-305873852>,
or mute
the thread

**Comment by findepi** [comment]
@mbasmanova thanks for the heads up! No, we're not. Just mind that there's an outstanding PR in this space (https://github.com/prestodb/presto/pull/10204) that you may want to base on, to avoid potential conflicts.

**Comment by sopel39** [comment]
> That would definitely improve performance. Basically stream here is locally "partitioned" on unique id.

Local exchange could be avoided by adding support for "primary keys" to `com.facebook.presto.sql.planner.optimizations.StreamPropertyDerivations.Visitor#visitExchange`. When a non duplicated "primary key" is part of exchange node output symbols we can say that stream is partitioned on all symbols.

**Comment by mbasmanova** [comment]
@sopel39 Karol, I didn't realize initially that what I'm seeing is different from what's been reported in this issue. Here, both partial and final aggregations happen on the same worker node. In my case, there is a hash redistribution between partial and final aggregations. The difference is that spatial join using broadcast, while regular hash join doesn't. If I `set session distributed_join=false;`, I can reproduce the issue using the same query. 

```
presto:tiny> set session distributed_join=false;

presto:tiny>  explain (type distributed) select name, (select max(name) from region where regionkey = nation.regionkey) from nation;
 explain (type distributed) select name, (select max(name) from region where regionkey = nation.regionkey) from nation;

 Fragment 0 [SINGLE]
     Output layout: [name, max]
     Output partitioning: SINGLE []
     Execution Flow: UNGROUPED_EXECUTION
     - Output[name, _col1] => [name:varchar(25), max:varchar(25)]
             _col1 := max
         - RemoteSource[1] => [name:varchar(25), max:varchar(25)]

 Fragment 1 [HASH]
     Output layout: [name, max]
     Output partitioning: SINGLE []
     Execution Flow: UNGROUPED_EXECUTION
     - Project[] => [name:varchar(25), max:varchar(25)]
 x        - Aggregate(FINAL)[name, regionkey, unique][$hashvalue] => [name:varchar(25), regionkey:bigint, unique:bigint, $hashvalue:bigint, max:varchar(25)]
 x                max := "max"("max_16")
 x            - LocalExchange[HASH][$hashvalue] ("name", "regionkey", "unique") => name:varchar(25), regionkey:bigint, unique:bigint, max_16:varchar(25), $hashvalue:bigint
 x                - RemoteSource[2] => [name:varchar(25), regionkey:bigint, unique:bigint, max_16:varchar(25), $hashvalue_17:bigint]

 Fragment 2 [SOURCE]
 x    Output layout: [name, regionkey, unique, max_16, $hashvalue_22]
 x    Output partitioning: HASH [name, regionkey, unique][$hashvalue_22]
 x    Execution Flow: UNGROUPED_EXECUTION
 x    - Aggregate(PARTIAL)[name, regionkey, unique][$hashvalue_22] => [name:varchar(25), regionkey:bigint, unique:bigint, $hashvalue_22:bigint, max_16:varchar(25)]
             max_16 := "max"("name_1")
         - Project[] => [name:varchar(25), regionkey:bigint, unique:bigint, name_1:varchar(25), $hashvalue_22:bigint]
                 $hashvalue_22 := "combine_hash"("combine_hash"("combine_hash"(bigint '0', COALESCE("$operator$hash_code"("name"), 0)), COALESCE("$operator$hash_code"("regionkey"), 0)), COALESCE("$operator$hash_code"("unique"), 0))
             - LeftJoin[("regionkey" = "regionkey_0")][$hashvalue_18, $hashvalue_19] => [name:varchar(25), regionkey:bigint, unique:bigint, name_1:varchar(25)]
                     Distribution: REPLICATED
                 - Project[] => [name:varchar(25), regionkey:bigint, unique:bigint, $hashvalue_18:bigint]
                         $hashvalue_18 := "combine_hash"(bigint '0', COALESCE("$operator$hash_code"("regionkey"), 0))
                     - AssignUniqueId => [name:varchar(25), regionkey:bigint, unique:bigint]
                         - TableScan[tpch:tpch:nation:sf0.01, originalConstraint = true] => [name:varchar(25), regionkey:bigint]
                                 Cost: {rows: 25 (500B), cpu: 500.00, memory: 0.00, network: 0.00}
                                 regionkey := tpch:regionkey
                                 name := tpch:name
                 - LocalExchange[HASH][$hashvalue_19] ("regionkey_0") => regionkey_0:bigint, name_1:varchar(25), $hashvalue_19:bigint
                     - RemoteSource[3] => [regionkey_0:bigint, name_1:varchar(25), $hashvalue_20:bigint]

 Fragment 3 [SOURCE]
     Output layout: [regionkey_0, name_1, $hashvalue_21]
     Output partitioning: BROADCAST []
     Execution Flow: UNGROUPED_EXECUTION
     - ScanProject[table = tpch:tpch:region:sf0.01, originalConstraint = true] => [regionkey_0:bigint, name_1:varchar(25), $hashvalue_21:bigint]
             Cost: {rows: 5 (100B), cpu: 100.00, memory: 0.00, network: 0.00}/{rows: 5 (150B), cpu: 250.00, memory: 0.00, network: 0.00}
             $hashvalue_21 := "combine_hash"(bigint '0', COALESCE("$operator$hash_code"("regionkey_0"), 0))
             name_1 := tpch:name
             regionkey_0 := tpch:regionkey                                                                                                                                                                                                               
```

I believe the whole `Fragment 1` above can be avoided and additionally partition aggregation could be done in a streaming fashion (e.g. aggregate subsequent records while unique id is the same; once it changes, emit the aggregate value and start aggregating next batch.)

Does this make sense?

**Comment by sopel39** [comment]
> partition aggregation could be done in a streaming fashion (e.g. aggregate subsequent records while unique id is the same; once it changes, emit the aggregate value and start aggregating next batch.)

Great idea! We know that the data is partitioned on unique id, but also sorted by unique id. Definitely makes sense. There is not streaming aggregation operator yet.

**Comment by sopel39** [comment]
@mbasmanova are you working on this? Should you assign yourself to the issue? I think Tpch/q21 should benefit greatly from fixing this issue.

**Comment by mbasmanova** [comment]
@sopel39 @martint I've been looking into whether I could use local properties to propagate enough information from the `AssignUniqueId` node to the `Aggregation` node.

I'm consider two different scenarios: distributed and broadcast join.

For distributed join, I have this plan:

```
- Aggregation
  - LeftJoin
    - RemoteExchange
      - Project: +hash(id)
        - AssignUniqueId: +unique
          - Probe (a, b, id)
    - Remote Exchange
      - Project: +hash(id)
        - Build (c, id)
```

and for broadcast join (e.g. spatial join), I have a different plan:

```
- Aggregation
  - SpatialJoin
      - AssignUniqueId: +unique
        - Probe (a, b)
      - Remote Exchange (REPLICATED)
        - Build (c)
```

In a distributed case scenario, `Aggregation` and `AssignUniqueId` nodes are separated by a `RemoteExchange` which drops all local properties. Hence, to propagate the `grouping(unique)` local property I need to move `AssignUniqueId` closer to the `Join`. However, if I do that, I'll no longer be able to skip `RemoteExchange` between partial and final aggregations.

In a broadcast case scenario,  `Aggregation` and `AssignUniqueId` node are part of the same fragment and therefore I can easily propagate `grouping(unique)` local property, but then I have the same problem as in distributed join case with `RemoteExchange` between partial and final aggregations.

Any ideas?

**Comment by sopel39** [comment]
> However, if I do that, I'll no longer be able to skip RemoteExchange between partial and final aggregations.

Why that would be the case? There can still be `RemoteExchange` below `LeftJoin` and `AssignUniqueId`, no? e.g:
```
   - Aggregation[Streaming]
     - LeftJoin[join_keys]
       - AssignUniqueId
         - RemoteExchange[join_keys]
```
Am I missing something?

> Hence, to propagate the grouping(unique) local property I need to move 
I don't think `grouping(unique)` is enough. You specifically need information that rows are strictly ordered (in our case `unique_id` ensures that).

**Comment by sopel39** [comment]
All in one here is what I would do:

- [Add better support (partitioning) for AssignUniqueId to PropertyDerivations] 
- [Add rules for pushup of AssignUniqueId though projection and exchange]
- [Add support for strict ordering in StreamProperties]
- [Add better support (partitioning, strict order) for AssignUniqueId in StreamPropertyDeriviations] 
- [Add streaming aggregation operator]
- [Add rule that converts SINGLE aggregation into streaming if data is strictly ordered]

**Comment by mbasmanova** [comment]
@sopel39 Karol, thank you for helping to think through this. I think you are correct that `grouping(unique)` local property is not enough to skip `LocalExchange` between partial and final aggregations. A group of 2+ probe rows with same `unique` value coming into the join may get distributed into different local threads and will require a local exchange to come together for the final aggregation. 

Unless... `AssignUniqueId` happens after probe rows have been split into local threads. Current implementation of `AssignUniqueIdOperator` doesn't seem to support parallel local execution though.

Overall, I like the set of changes you outlined. I have only a few questions.

* Why do we need `strict ordering` in StreamProperties? Can't we add `distinct` or `unique` local property instead?
* Why do we need both `ActualProperties` and `StreamProperties`? 
* Would it be simpler to modify `AssignUniqueIdOperator` to support parallel local execution?

CC: @martint

**Comment by sopel39** [comment]
> Unless... AssignUniqueId happens after probe rows have been split into local threads. Current implementation of AssignUniqueIdOperator doesn't seem to support parallel local execution though.

It must support parallel local execution to work correctly, because it is executed in parallel within a task. There is: `com.facebook.presto.operator.AssignUniqueIdOperator#rowIdPool`. 

> Why do we need strict ordering in StreamProperties?

Strict order is not required (my mistake, corrected previous posts), just information that rows are ordered should be enough. 

> Can't we add distinct or unique local property instead?

Probe rows that pass though `LeftJoin` won't be unique, but they will be ordered on all columns via `unique_id`.

> Why do we need both ActualProperties and StreamProperties?

Supporting `AssignUniqueId` in `ActualProperties` will allow to avoid remove exchange before aggregation if `AssignUniqueId` is in source stage. See your example: https://github.com/prestodb/presto/issues/8171#issuecomment-387549439
It is also needed so that SINGLE aggregation can be later converted into STREAMING

Supporting `AssignUniqueId` in `StreamProperties` is needed so that you can convert `SINGLE` aggregation into `STREAMING`. Note that `SINGLE->STREAMING` conversion is a local decision on a pipeline level.

> Would it be simpler to modify AssignUniqueIdOperator to support parallel local execution?

It does support that by my knowledge, @kokosing ?

**Comment by kokosing** [comment]
> It does support that by my knowledge, @kokosing ?

👍

**Comment by mbasmanova** [comment]
@sopel39 @kokosing @martint 

Karol, I believe I understand the big picture, but still have some questions. Here is the story I'm working through:

`ActualProperties` describe data distributed across nodes. `StreamProperties` describe data distributed across threads within a single node.

`ActualProperties` are computed by `PropertyDerivations` and used in `AddExchanges` to add `RemoteExchange`s.

`StreamProperties` are computed by `StreamPropertyDerivations` and used in `AddLocalExchanges` to add `LocalExchange`s.

`ActualProperties` consist of local and global properties. Local properties are: constant, sorting, grouping. Constant implies sorting and sorting implies grouping. Global properties are: partitioned_on(col1, col2, etc.) (across nodes). We could use `partitioned_on(unique)` to describe properties of the `AssignUniqueId` output.

`StreamProperties` consists of distribution, partitioningColumns, ordered and otherActualProperties. We could use `partitioningColumns={unique}` and `ordered=true` to describe properties of the `AssignUniqueId` output.

I don't understand what `Global#streamPartitioning` is and how it is related to `StreamProperties` if at all. Could someone explain?

For an aggregation node, the planner needs to decide whether (1) local exchange is needed; (2) remote exchange is needed; (3) streaming aggregation applies.

`AssignUniqueId` produces a stream of data with partitioned_by(unique) (across local streams and across nodes) and grouping(unique) (within a local stream) properties.

AddLocalExchanges is responsible for deciding (1). It can use StreamProperties.partitioningColumns(unique) to skip LocalExchange.

AddExchanges is responsible for deciding (2). It can use ActualProperties.global.partitioned_on(unique) to skip RemoteExchange.

AddLocalExchanges is responsible for deciding (3) (is it? or should it be a separate rule that runs *after* AddLocalExchanges?). It can use StreamProperties.ordered to enable streaming aggregation.

With the following plans, PropertyDerivations#visitJoin and StreamPropertyDerivations#visitJoin need to preserve partitioned_by(unique) and grouping(unique) properties. (It might be necessary to update #visitProjection to preserve these properties as well.)

Distributed join:

```
- Aggregation
  - Join
    - AssignUniqueId
      - RemoteExchange
        - probe
    - RemoteExchange
      - build
```

Broadcast join:

```
- Aggregation
  - Join
    - AssignUniqueId
        - probe
    - RemoteExchange
      - build
```

Does this sound about right?

**Comment by mbasmanova** [comment]
@sopel39 @martint Karol, Martin, #10731 builds on top of #10681 and adds streaming support to `HashAggregationOperator`, updates `[Stream]PropertyDerivations` to set `partitioned_on(unique)` and `grouped(unique)` properties, and uses these in `AddLocalExchanges` to plan streaming aggregations.
