### ISSUE TITLE
Hive connector cannot read all DecimalTypes from Parquet with Predicate

### ISSUE THREAD

**Issue by smith-m** [prestodb/presto#8183]
Error is returned when hive connector is used to select some parquet decimal types when using a query predicate.

For example, where the column "msrp" is decimal(18,0) or decimal(18,2)
"select msrp from product" returns a result.

"select msrp from product where company_id = 1" returns this error:

![image](https://cloud.githubusercontent.com/assets/23284218/26799931/420f9810-49ec-11e7-800c-d2096a2e0384.png)

This error occurs with these catalog properties:
>hive.parquet-optimized-reader.enabled=true
>hive.parquet-predicate-pushdown.enabled=true

My thought is that the recent PR to improve presto support for all decimal types did not account for skipValues. https://github.com/prestodb/presto/pull/7537

Fixing this issue could be as simple as using the same type check to use readLong or readInt instead of readBytes in ParquetShortDecimalColumnReader.java skipValues()

**Comment by nezihyigitbasi** [comment]
@smith-m Seems like you have an idea about the fix, can you please open a PR?

**Comment by smith-m** [comment]
@nezihyigitbasi I created a PR here that I believe addresses the issue

https://github.com/prestodb/presto/pull/8208
