### ISSUE TITLE
Make the resource group configuration manager event based

### ISSUE THREAD

**Issue by elonazoulay** [prestodb/presto#8188]
Change the behavior of the resource group configuration manager to be event based instead of polling the database.
Add a reload procedure that will reload the configuration based on updated db or json file (for file based resource group configuration manager).

**Comment by nezihyigitbasi** [comment]
#6483 sounds related.

**Comment by electrum** [comment]
What's wrong with polling? MySQL doesn't provide any event system, so we'd have to rely on manual notifying after updating the database, and that seems less robust / more error prone. It's especially bad if you have multiple Presto clusters reading the same data.
