### ISSUE TITLE
Add system tables to show resource group configuration

### ISSUE THREAD

**Issue by elonazoulay** [prestodb/presto#8189]
Add system tables to show information about how resource groups are configured:
1) resource_group_specs: current resource group specs and associated properties
2) parent_child: parent child relationships of resource group specs
3) configured_groups: configured groups and their current properties, can be many for one resource group spec (i.e. if ${USER} and ${SOURCE} syntax are used).

**Comment by electrum** [comment]
Can you write out the full schemas? I'm not very familiar with resource groups so I'd like to make sure I understand the proposal.

**Comment by elonazoulay** [comment]
# Resource Group Spec system table
1. resource_group_template_id VARCHAR

**Comment by elonazoulay** [comment]
# Configured Resource Groups system table
Mapping between all resource group ids and their associated resource group templated id.
This is a one to many relationship between resource group template id and resource group id.

**Table**: `configured_groups`

Column name | Type
resource_group_templated_id | VARCHAR
resource_group_id | VARCHAR

**Comment by elonazoulay** [comment]
# Parent Child system table
Contains a one to many mapping of parent and child resource group template ids.
**Table**: `resource_group_parent_child`

Column name | Type
------------- | ---------
parent_template_id | VARCHAR
child_template_id | VARCHAR

**Comment by elonazoulay** [comment]
# Selectors system table
Contains information about the currently loaded selectors.
**Table**: `selectors`

Column name | Type
------------- | ---------
resource_group_id | VARCHAR
user_regex | VARCHAR
source_regex | VARCHAR

**Comment by elonazoulay** [comment]
# Resource Groups Global Properties system table
Contains name value pairs for all resource group global properties.
Currently there is only a single property `cpu_quota_period`.
**Table**: `resource_groups_global_properties`

Column name | Type
------------- | ---------
name | VARCHAR
value | VARCHAR

**Comment by elonazoulay** [comment]
@electrum Thanks for looking at this! Let me know what you think.

**Comment by elonazoulay** [comment]
This information will be useful to verify that the cluster and database are in sync. Also the configured groups table will be the only place an admin can see that information.

**Comment by elonazoulay** [comment]
All of these system tables would go into a schema called "resource_groups" so as not to pollute the system schema with too many tables.

**Comment by electrum** [comment]
This looks reasonable overall, though we should eliminate the one-to-many tables. Those are better expressed as a foreign-key-to-parent in the child tables. It both prevents a join and makes it clear that there is exactly one parent.

**Comment by electrum** [comment]
How do global properties work? Is that something which will be well-known? If so, we should just make that a normal column.

**Comment by elonazoulay** [comment]
@electrum - Currently global properties only contains 1 property. Added as a column to the resource group specs table (above).

**Comment by elonazoulay** [comment]
Updated the configured resource group table to have primary key be the resource group id and 1 to 1 mapping to resource group template id.
This table gives the ability to see currently configured resource groups.

**Comment by elonazoulay** [comment]
These tables will be put into a connector associated with the resource groups plugin.
