### ISSUE TITLE
User Session properties inside JDBC connector (or any custom connector)

### ISSUE THREAD

**Issue by zdeneksejcek** [prestodb/presto#8199]
Hi, trying to find out how to get current user set in session inside my customized JDBC connector. I am about to use new sqlserver connector, but need to adjust it to send current user from session.

Is there an easy way?
Thanks.

**Comment by jaehc** [comment]
@zdeneksejcek 
Hi, I have the exact same problem as yours. I opened an issue #8164 about this. Have you found out some?

**Comment by zdeneksejcek** [comment]
No solution yet, I tried to investigate though code and no success. I am now as proficient in reading Presto source code as I would like to be, so there might be simple solution, but I don't see it.

1) First thing to find out is whether current user is even distributed across nodes.
2) Other issue I have is that I don't know a lifecycle of specific components (Driver, Client etc.). I need to have current user on query basis, not stored somewhere in singleton :(

If you have time, we can cooperate on this.

**Comment by Downchuck** [comment]
Could this make it into the connection string? Not the best situation but gets me out of some difficulties.

**Comment by dain** [comment]
There is no way to get the session user and there are no plans to expose that to connectors.  The reason for this is Presto supports views which impersonate users, and we don't connectors to make decissions based on the session user.  If you add a connector access control implementation, we will pass the current user (after any impersonation) the connector.
