### ISSUE TITLE
Implement map_merge_agg

### ISSUE THREAD

**Issue by highker** [prestodb/presto#8203]
As discussed, this is an aggregation function taking a column of map type as input and produces a single map wrt lambda specification. The lambda function defines how maps should be merged by key.

The syntax is similar to https://github.com/prestodb/presto/issues/7814

The following example should return `{'a':5, 'b':7, 'c':3, 'd':6}`
```
select map_merge_agg(m, 0, (x, s) -> x + s, (s1, s2) -> s1 + s2, s -> s)
from ( values 
    (map(array['a', 'b', 'c'], array[1, 2, 3])),
    (map(array['a', 'b', 'd'], array[4, 5, 6]))
) as t(m)
```
The reason we are not using `reduce_agg` in https://github.com/prestodb/presto/issues/7814 is due to
- No existing function can merge two maps with a lambda (unless we add lambda support for `map_concat`).
- Even we have `map_concat` with lambda, the performance would be poor given the aggregation state will be copied every time we call `map_concat`.

The issue is blocked by https://github.com/prestodb/presto/issues/7814 to enhance aggregation functions with lambda.

**Comment by mbrandow** [comment]
shouldn't b return 7 here

**Comment by highker** [comment]
my fault; fixed

**Comment by mrbrahman** [comment]
This would be an awesome feature to have! 👍
