### ISSUE TITLE
Make TRY a syntactic sugar using lambda

### ISSUE THREAD

**Issue by haozhun** [prestodb/presto#8221]
Due to the requirement in lazy evaluation of expression in TRY, it is handled specially in a bunch cases. Now that we have lambda, such special handling is no longer necessary if we rewrite try using lambda.

* This allows us to remove a bunch code in expression compiler dedicated to handle TRY.
* This removes the constraint that try cannot be used inside lambda.

**Comment by wenleix** [comment]
@haozhun : Do you mean to rewrite `TRY(expr)` into something like `()->expr`?

**Comment by martint** [comment]
No, the idea is to make TRY a regular function that takes a lambda instead of being a special concept throughout the engine (especially, the code generator). Then, an SQL expression like `TRY(a/b)` becomes syntactic sugar for `try_function(() -> a/b)`

**Comment by highker** [comment]
Assigned to @shixuan-fan; let's implement this in these steps:
- create an internal try_function that takes a lambda
- de-sugar TRY with try_function
- remove all special handling for TRY

**Comment by findepi** [comment]
@highker i see 2 PRs closed related to this. Is this issue done?

**Comment by highker** [comment]
Yes it has been merged.
