### ISSUE TITLE
Issue setting LDAP authentication using JDBC for EMR presto

### ISSUE THREAD

**Issue by puneethpotu** [prestodb/presto#8230]
HI, I was able to setup Successfully setup LDAP authentication for webUI following the presto LDAP documentation.
I also installed JDBC driver on my mac and connecting to presto EMR server to run SQL from SQL workbench.
URL I am using to connect is ```jdbc:presto://hostname:8889/hive```.

After the LDAP is set up, i am still able to connect to presto without passing credentials. How can I restrict anonymous logins from presto-cli or from JDBC connections.

BTW, I am using port 18433 in config.properties because hue is using 8443 and I couldn't start presto if used 8443 port.

Appreciate your help.

**Comment by findepi** [comment]
Hi @puneethpotu,

Unfortunately I don't know the answer. However, questions like this one are better served by the user group -- https://groups.google.com/group/presto-users
