### ISSUE TITLE
Presto doesn't respect x-forwarded-proto header

### ISSUE THREAD

**Issue by afilipchik** [prestodb/presto#8232]
In our environment presto is deployed behind proxy which terminates SSL. So, clients connecting to proxy via HTTPS and proxy is connecting to Presto via http. Because of the protocol change proxy attaches  "X-Forwarded-Proto: https" header to the request.

However, when request hits com.facebook.presto.server.StatementResource X-Forwarded-Proto information is lost. It results in the urls with a wrong protocol returned to the caller.

Example: 
call: POST https://localhost:8080/v1/statement
response: NextUrl: http://localhost:8080/query.html?20170609_221443_00004_k9urh

Client tries to access query.htm via http and fails. 

I fixed it locally by adding simple check to StatementResource.getNextResults:
`String forwardedProtocol = servletRequest.getHeader(HttpHeaders.X_FORWARDED_PROTO);
  if ((!queryInfo.isFinalQueryInfo()) || (!exchangeClient.isClosed())) {
      nextResultsUri = createNextResultsUri(uriInfo, forwardedProtocol);
  }`

but I think it should be fixed upstream, probably in the place where jetty is configured (probably ForwardedRequestCustomizer). It looks like all Jetty logic is hidden in Airlift framework, and I couldn't find enough documentation to make a fix.

Please advice on the best course of action.

**Comment by alexlukelevy** [comment]
@afilipchik Did you ever find an easier solution? I'm having the same issue and wondered whether there was Jetty property I could set.

**Comment by afilipchik** [comment]
Not really. we patched it locally for now.

**Comment by sajjoseph** [comment]
@afilipchik Basically, what you are suggesting is this:
If Jetty gets HTTP (and not HTTPS) request, ignore the X-Forwarded-Proto field even if it contains https - right?
I didn't terminate https at proxy and thus not experiencing the issue (proxy will act like a pass through for https traffic). Now that StatementResource.java is deleted (from 0.190 onwards), we have to figure out how the code has changed and how it behaves with HTTP traffic (+ special header variable set to the value you mentioned above).

**Comment by electrum** [comment]
This is implemented now. Thanks @actgardner!
