### ISSUE TITLE
Column name resolution issue

### ISSUE THREAD

**Issue by majk-p** [prestodb/presto#8250]
I've found following issue regarding column name resolution when switching from version 0.158 to 0.178.
Using version 0.158 this query:
 > SELECT catalog.schema.table."column" FROM catalog.schema.table GROUP BY "column" ORDER BY catalog.schema.table."column" ASC;

Worked fine. Using v 0.178 I've got:
 > Query 20170613_104018_34104_v6755 failed: line 1:95: Column 'catalog.schema.table.column' cannot be resolved

It seems to be a problem with `ExpressionAnalyzer` that has changed over those versions.

Stacktrace for this query:
 > com.facebook.presto.sql.analyzer.SemanticException: line 1:95: Column 'catalog.schema.table.column' cannot be resolved
 >	at com.facebook.presto.sql.analyzer.SemanticExceptions.missingAttributeException(SemanticExceptions.java:30)
 >	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitDereferenceExpression(ExpressionAnalyzer.java:399)
 >	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitDereferenceExpression(ExpressionAnalyzer.java:282)
 >	at com.facebook.presto.sql.tree.DereferenceExpression.accept(DereferenceExpression.java:53)
 >	at com.facebook.presto.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)
 >	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:301)
 >	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:258)
 >	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyzeExpressions(ExpressionAnalyzer.java:1441)
 >	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyzeExpressionsWithSymbols(ExpressionAnalyzer.java:1394)
 >	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.getExpressionTypes(ExpressionAnalyzer.java:1360)
 >	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.getExpressionTypes(ExpressionAnalyzer.java:1348)
 >	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.getExpressionTypes(ExpressionAnalyzer.java:1336)
 >	at com.facebook.presto.sql.planner.optimizations.DesugaringOptimizer$Rewriter.desugar(DesugaringOptimizer.java:203)
 >	at com.facebook.presto.sql.planner.plan.Assignments.lambda$rewrite$1(Assignments.java:109)
 >	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
 >	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
 >	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
 >	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
 >	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
 >	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
 >	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
 >	at com.facebook.presto.sql.planner.plan.Assignments.rewrite(Assignments.java:110)
 >	at com.facebook.presto.sql.planner.optimizations.DesugaringOptimizer$Rewriter.visitProject(DesugaringOptimizer.java:125)
 >	at com.facebook.presto.sql.planner.optimizations.DesugaringOptimizer$Rewriter.visitProject(DesugaringOptimizer.java:77)
 >	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:92)
 >	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
 >	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:73)
 >	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
 >	at java.util.Collections$2.tryAdvance(Collections.java:4717)
 >	at java.util.Collections$2.forEachRemaining(Collections.java:4725)
 >	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
 >	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
 >	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
 >	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
 >	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
 >	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:74)
 >	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:38)
 >	at com.facebook.presto.sql.planner.optimizations.DesugaringOptimizer$Rewriter.visitPlan(DesugaringOptimizer.java:99)
 >	at com.facebook.presto.sql.planner.optimizations.DesugaringOptimizer$Rewriter.visitPlan(DesugaringOptimizer.java:77)
 >	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitSort(PlanVisitor.java:104)
 >	at com.facebook.presto.sql.planner.plan.SortNode.accept(SortNode.java:88)
 >	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
 >	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:95)
 >	at com.facebook.presto.sql.planner.optimizations.DesugaringOptimizer$Rewriter.visitProject(DesugaringOptimizer.java:124)
 >	at com.facebook.presto.sql.planner.optimizations.DesugaringOptimizer$Rewriter.visitProject(DesugaringOptimizer.java:77)
 >	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:92)
 >	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
 >	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:95)
 >	at com.facebook.presto.sql.planner.optimizations.DesugaringOptimizer$Rewriter.visitProject(DesugaringOptimizer.java:124)
 >	at com.facebook.presto.sql.planner.optimizations.DesugaringOptimizer$Rewriter.visitProject(DesugaringOptimizer.java:77)
 >	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:92)
 >	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
 >	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:95)
 >	at com.facebook.presto.sql.planner.optimizations.DesugaringOptimizer$Rewriter.visitProject(DesugaringOptimizer.java:124)
 >	at com.facebook.presto.sql.planner.optimizations.DesugaringOptimizer$Rewriter.visitProject(DesugaringOptimizer.java:77)
 >	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:92)
 >	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
 >	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:73)
 >	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
 >	at java.util.Collections$2.tryAdvance(Collections.java:4717)
 >	at java.util.Collections$2.forEachRemaining(Collections.java:4725)
 >	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
 >	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
 >	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
 >	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
 >	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
 >	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:74)
 >	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:38)
 >	at com.facebook.presto.sql.planner.optimizations.DesugaringOptimizer$Rewriter.visitPlan(DesugaringOptimizer.java:99)
 >	at com.facebook.presto.sql.planner.optimizations.DesugaringOptimizer$Rewriter.visitPlan(DesugaringOptimizer.java:77)
 >	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:49)
 >	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:82)
 >	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:27)
 >	at com.facebook.presto.sql.planner.optimizations.DesugaringOptimizer.optimize(DesugaringOptimizer.java:74)
 >	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:130)
 >	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:121)
 >	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:312)
 >	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:291)
 >	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:247)
 >	at com.facebook.presto.execution.QueuedExecution.lambda$start$1(QueuedExecution.java:62)
 >	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 >	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 >	at java.lang.Thread.run(Thread.java:745)

**Comment by kokosing** [comment]
@sopel39 is this related with ORDER BY?

**Comment by findepi** [comment]
Repro steps:

```
create table memory.default.x as select * from (values 1) x(a);

SELECT memory.default.x.a FROM memory.default.x GROUP BY a ORDER BY memory.default.x.a ASC; -- fails
SELECT memory.default.x.a FROM memory.default.x GROUP BY a ORDER BY a ASC; -- works
```

**Comment by majk-p** [comment]
Additionally, there seems to be related problem with aliasing. Following queries fail with `column ... cannot be resolved`:

    SELECT catalog.schema.table."column" as "abc" FROM catalog.schema.table GROUP BY "abc" ORDER BY catalog.schema.table."column" ASC;
    SELECT catalog.schema.table."column" as "abc" FROM catalog.schema.table GROUP BY catalog.schema.table."column" ORDER BY "abc" ASC;

And following work:

    SELECT catalog.schema.table."column" as "abc" FROM catalog.schema.table GROUP BY "abc" ORDER BY "abc" ASC;
    SELECT catalog.schema.table."column" as "abc" FROM catalog.schema.table GROUP BY catalog.schema.table."column" ORDER BY catalog.schema.table."column" ASC;

**Comment by findepi** [comment]
@majk-p , yup. Investigating.

**Comment by majk-p** [comment]
Additional finding. Only mixing both fully qualified name and alias breaks the query. Using number in any combination breaks nothing. Following queries work:

    SELECT catalog.schema.table."column" as "abc" FROM catalog.schema.table GROUP BY "abc" ORDER BY 1 ASC;
    SELECT catalog.schema.table."column" as "abc" FROM catalog.schema.table GROUP BY catalog.schema.table."column" ORDER BY "abc" ASC;
    SELECT catalog.schema.table."column" as "abc" FROM catalog.schema.table GROUP BY 1 ORDER BY "abc" ASC;
    SELECT catalog.schema.table."column" as "abc" FROM catalog.schema.table GROUP BY 1 ORDER BY catalog.schema.table."column" ASC;

**Comment by findepi** [comment]
git-bisected this to 5d45fd80e4451c0853f7212b7adfb1e3b8efdcaf
