### ISSUE TITLE
Add a `@GET` method to `/v1/memory` endpoint

### ISSUE THREAD

**Issue by haozhun** [prestodb/presto#8258]
Right now, in order to find out memory allocation (to queries) on a worker, we have to do: 
```
curl -H "Content-Type: application/json" -X POST \
  -d '{"coordinatorId":"", "version":0, "assignments":[]}' \
 'http://prestoXXXX:7777/v1/memory?pretty'
```

We should have a GET method on `/v1/memory` to simplify this.

**Comment by sdpatil** [comment]
I am new at open source contribution and not sure how this process works but I would love to contribute to presto. For this particular task if I add an implementation of GET method like below would that be satisfactory?

  ```
  @GET
    @Produces(MediaType.APPLICATION_JSON)
    public MemoryInfo getMemoryInfo(){
        return memoryManager.getInfo();
    }
```

**Comment by raghavsethi** [comment]
@sdpatil yes, that would be a good place to start.

**Comment by sdpatil** [comment]
Thanks, i will work on this issue

**Comment by raghavsethi** [comment]
Merged.
