### ISSUE TITLE
Queries are accepted when the server is starting up and can only see a few workers

### ISSUE THREAD

**Issue by raghavsethi** [prestodb/presto#8260]
Accepting queries when only a few workers are 'available' can cause query runtimes to balloon, or even worse, cause massive skew in memory allocations and cause the small number of workers to go into reserved state.

Some solutions, in order of desirability:
- The coordinator can reject queries that come in if the number of workers is less than a configurable minimum (maybe hash partition count)
- Coordinator rejects queries when few workers are available AND total uptime is short
- Coordinator queues queries for a small configurable time window when few workers are available AND total uptime is short, and then starts them when the threshold is reached.

**Comment by dain** [comment]
Maybe just add a "min-worker-nodes" property.

**Comment by nezihyigitbasi** [comment]
Fixed in [0.182](https://prestodb.io/docs/current/release/release-0.182.html).
