### ISSUE TITLE
Unify planing of CROSS JOIN UNNEST and LATERAL

### ISSUE THREAD

**Issue by kokosing** [prestodb/presto#8265]
> In the future, we should consider unifying how LATERAL and CROSS JOIN UNNEST are planned, and leave it to the optimizers to transform into specialized operations.

From https://github.com/prestodb/presto/pull/8218/commits/714069254e23b339fc2f82cc9183e85568708f15#r121742503

CC: @martint

**Comment by kokosing** [comment]
Does it mean we should plan CROSS JOIN UNNEST as `Lateral` node, and then rewrite this `Lateral` to proper `Join` node?

**Comment by atris** [comment]
@kokosing Is this still relevant? While reading CROSS JOIN code, this sort of came into perspective for me. Worth discussing?

**Comment by kokosing** [comment]
Do you have any idea how it could be tackled?
