### ISSUE TITLE
Does MongoDB Connector support Predicate Pushdown for TIMESTAMP?

### ISSUE THREAD

**Issue by howfree** [prestodb/presto#8287]
I tried the two ways, but got the same input.
1) select count(id) from mongodb.kryods.trade 
where cast(biz_date as timestamp) > to_timestamp('2017-05-01','yyyy-mm-dd') and shop_identy = 810007516
**Explain**:  
ScanFilterProject[table = mongodb:kryods.trade, originalConstraint = ((CAST("biz_date" AS timestamp) > "$literal$timestamp"(1493568000000)) AND ("shop_identy" = BIGINT '810007516')), filterPredicate = (("shop_identy" = BIGINT '810007516') AND (CAST("biz_date" AS timestamp) > "$literal$timestamp"(1493568000000)))] => [id:bigint]
                Cost: 100.00%, Input: 2774 rows (726B), Output: 570 rows (5.01kB), Filtered: 79.45% 

2) select count(id) from mongodb.kryods.trade 
where cast(biz_date as timestamp) > to_timestamp('2017-05-31','yyyy-mm-dd') and shop_identy = 810007516

**Explain**: 
        - ScanFilterProject[table = mongodb:kryods.trade, originalConstraint = ((CAST("biz_date" AS timestamp) > "$literal$timestamp"(1496160000000)) AND ("shop_identy" = BIGINT '810007516')), filterPredicate = (("shop_identy" = BIGINT '810007516') AND (CAST("biz_date" AS timestamp) > "$literal$timestamp"(1496160000000)))] => [id:bigint]
                Cost: 100.00%, Input: 2774 rows (726B), Output: 0 rows (0B), Filtered: 100.00%
                Input avg.: 2774.00 lines, Input std.dev.: 0.00%

I wonder whether MondoDB Connector support this feature or not ?
thanks.

**Comment by electrum** [comment]
Push down doesn't work (for any connector) if there is a function or other expression surrounding the column. It needs to be a direct predicate:

biz_date >= ...

**Comment by howfree** [comment]
@electrum 
I removed "cast " operator and changed it into the following,but they still have the same input.
1) select count(id) from mongodb.kryods.trade where biz_date > timestamp '2017-05-01 UTC' and shop_identy = 810007516
 Explain: Cost: 100.00%, Input: 2774 rows (726B), Output: 570 rows (5.01kB), Filtered: 79.45%
2) select count(id) from mongodb.kryods.trade where biz_date > timestamp '2017-05-31 UTC' and shop_identy = 810007516
Expalin: Cost: 100.00%, Input: 2774 rows (726B), Output: 0 rows (0B), Filtered: 100.00%

I suppose No. 1 should has 570 rows and the second should be 0 rows which are loaded into Presto from MongoDB.  right ?

thanks.

**Comment by tooptoop4** [comment]
Reopen
