### ISSUE TITLE
When aggregation spills, unspilling should allocate memory from operator's context

### ISSUE THREAD

**Issue by findepi** [prestodb/presto#8304]
Currently the unspilling declares memory allocation in system context (`com.facebook.presto.operator.aggregation.builder.SpillableHashAggregationBuilder#mergeFromDisk`, `com.facebook.presto.operator.aggregation.builder.SpillableHashAggregationBuilder#mergeFromDiskAndMemory` contain `operatorContext.getSystemMemoryContext().newAggregatedMemoryContext()`).

Instead, it should allocate in "normal" memory pool (via operator's context).

cc @losipiuk

**Comment by findepi** [comment]
@nezihyigitbasi with system memory being merged with user memory, is there a point in keeping this issue around?

**Comment by nezihyigitbasi** [comment]
@findepi I don't think so.
