### ISSUE TITLE
Insert DateTime into MySQL

### ISSUE THREAD

**Issue by pd04152129** [prestodb/presto#8305]
I have MySQL table where one of column having datatype **DateTime**. Using presto I want to insert DateTime inside this column. But I am getting following error when I am executing query. I can't change dattype of my column.

Query:
insert into mysql.myschema.datetest values cast (current_date as timestamp);

Error:
Query 20170616_04392  failed: Data truncation: Incorrect datetime value: '1497551400000' for column 'stdate' at row 1

Also tried with another way

Query:
insert into mysql.myschema.datetest values( cast(date_format( cast('2017-06-06 01:01:01.123' as timestamp), '%Y-%m-%d %H:%i:%s') as timestamp));

Error:
Query 20170616_045202 failed: Data truncation: Incorrect datetime value: '1496691061000' for column 'stdate' at row 1

**Comment by jogamol** [comment]
i have the same issue..did you resolved it?

**Comment by archongum** [comment]
`show create table` gets `datetime` in MySQL but gets `timestamp` in Presto.
```sql
insert into mysql_table (datetime_col) (
  select datetime_col from mysql_table
)
```
exception: 
> java.lang.RuntimeException: com.facebook.presto.spi.PrestoException: Unsupported column type: timestamp

Is there any alternatives?

**Comment by cjie** [comment]
+1

**Comment by anandativo** [comment]
+1
