### ISSUE TITLE
Presto Build Failure - zip file is empty

### ISSUE THREAD

**Issue by breckinridge22** [prestodb/presto#8308]
I am trying to build presto on my local machine to run it using an IDE. But when I run a mvn clean install it fails to build the final project: prestobenchto-benchmarks. Here is the error:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.10:analyze-only (default) on project presto-benchto-benchmarks: Cannot analyze dependencies: zip file is empty ->

Could use some help resolving this issue.

**Comment by haozhun** [comment]
This is likely corruption in ~/.m2/respository

Delete the said dependency (that failed to be analyzed) from your local maven cache, and retry.

I recommend that you also update your maven to the latest release.

**Comment by breckinridge22** [comment]
The dependency doesnt exist in the .m2/repository so i cant delete it.. do you have any other suggestion

**Comment by petroav** [comment]
@breckinridge22 you should be using the maven wrapper script included in the Presto repo. So the command should be `./mvnw clean install -DskipTests`.

**Comment by satybald** [comment]
You can find an empty file dependency and delete it from a repository.
```
cd ~/.m2/repository
find -iname "*.jar" -type f -empty
```
