### ISSUE TITLE
Add JMX statistics concerning memory revoking

### ISSUE THREAD

**Issue by losipiuk** [prestodb/presto#8313]
Currently Presto does not expose any runtime statistics related to memory revoking mechanism.
Having those would be helpful for monitoring and diagnosing problems on production.

We need to work out actual list of stats to be added but it could contain:
* counter for scheduled revoking requests
* counter for how much memory revoking was requested

This issue will be relevant as soon as #7895 is merged in.

cc: @findepi

**Comment by dain** [comment]
If possible, distribution of revoked memory size per task and/or operator... that way we can see if we are revoking lots of small stuff or large stuff
