### ISSUE TITLE
Support more types for Cassandra INSERT

### ISSUE THREAD

**Issue by ebyhr** [prestodb/presto#8315]
Currently, Cassandra connector cannot insert following data types.
```
blob, frozen<set<type>>, inet, list<type>, map<type,type>, set<type>, timeuuid, decimal, uuid, varint
```

I'm trying to resolve this by following steps.
1. Add variable `List<CassandraType> cassandraTypes` in `CassandraRecordSink` to get target table column definitions in the constructor.

2. Modify `CassandraRecordSink#append*()` like this. 
```java
    @Override
    public void appendDouble(double value)
    {
        CassandraType cassandraType = cassandraTypes.get(field);
        if (CassandraType.DECIMAL.equals(cassandraType)) {
            append(CassandraType.DECIMAL.getJavaValue(value));
        }
        else {
            append(value);
        }
    }
```
Before this change, it just returns `append(value);`.

I read datastax's `TypeCodec.MappingCodec` a little, and i think it may be a better way.

Relates : [#discussion_r121732844](https://github.com/prestodb/presto/pull/7451#discussion_r121732844)
Cc: @cawallin, @arhimondr

**Comment by cawallin** [comment]
Either of those seems fine, whichever turns out cleaner.

**Comment by ebyhr** [comment]
Thanks for your comment. I will try both.
