### ISSUE TITLE
Presto Build Fail - zip file empty

### ISSUE THREAD

**Issue by breckinridge22** [prestodb/presto#8317]
I cloned presto from git and am trying to run a mvn clean install to build it. It failed on this error:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.10:analyze-only (default) on project presto-benchto-benchmarks: Cannot analyze dependencies: zip file is empty -> [Help 1]

I was told to delete the project from my maven cache but the presto-benchto-benchmarks dependency doesnt exist there, so i cant delete it. I tried deleting the entire presto dependency but that also didnt work. 

Any suggestions on how to get this built.

**Comment by findepi** [comment]
Instead of `mvn clean install` try `./mvnw clean install`, this will use correct maven version automatically.

I'll close this issue (such temporary problems are better served by the user group), but you can comment here if you still have problems.
