### ISSUE TITLE
where clause in custom connector

### ISSUE THREAD

**Issue by dabansal** [prestodb/presto#8351]
Hi All,

I have written a custom connector which calls a REST endpoint as data source. How can I access the  information passed in where clause of the SQL query ? Is there an object which can give me this information so that I can further pass this information to REST endpoint so I get filtered results.

Thanks,
Dheeraj

**Comment by kokosing** [comment]
Where predicate is passed as `Constraint` in method `com.facebook.presto.spi.connector.ConnectorMetadata#getTableLayouts`
