### ISSUE TITLE
Access control checks for SHOW SCHEMAS and SHOW TABLES are not implemented in Hive connector

### ISSUE THREAD

**Issue by egalych** [prestodb/presto#8368]
Methods: filterSchemas, filterTables, checkCanShowSchemas, checkCanShowTables introduced in 0.167 in SqlStandardAccessControl are not implemented

**Comment by amrutagokhale** [comment]
It's not the case that these methods are not implemented. The current implementation of these methods in SqlStandardAccessControl in Hive connector is a no-op. I think the reason behind this is that Presto doesn't yet support defining privileges on schemas or catalogs in `sql-standard` mode. So in this mode, anyone can see what is inside a schema or a catalog. 

Can you please elaborate on what were you expecting these methods to do?

**Comment by egalych** [comment]
While there is no support for schema level privileges, table level privileges could be used to return only those tables that are available to user. Simple implementation of filterTables could filter tables that do not have select permission for a user.

**Comment by amrutagokhale** [comment]
I see your point. Yeah, `filterTables` and `checkCanShowTables` can be implemented to return/show only those tables for which user has `SELECT` privilege.

**Comment by egalych** [comment]
Would it be possible to merge pull request since all checks have passed?
