### ISSUE TITLE
TestHiveSplitSource::testReaderWaitsForSplits is flaky

### ISSUE THREAD

**Issue by flakycov** [prestodb/presto#8374]
`TestHiveSplitSource::testReaderWaitsForSplits` failed for us on commit `cdd2cfd` but did not fail in the [corresponding run on Travis](https://travis-ci.org/prestodb/presto/jobs/241367902):

```
java.util.concurrent.TimeoutException: null
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:434)
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:85)
        at com.facebook.presto.hive.TestHiveSplitSource.testReaderWaitsForSplits(TestHiveSplitSource.java:147)
```
Our tool confirms that this test is flaky. We set up our build environment to be as close to your Travis environment as possible, using Ubuntu 14.04.5 LTS, Java HotSpot 1.8.0_111-b14 and Maven 3.3.9.

**Comment by alandpost** [comment]
I just ran into this in Travis

**Comment by flakycov** [comment]
@alandpost In addition to this one, we have a list of several other tests that we have found to be flaky too in Presto. Would you like us to open issues for them (we didn't want to "spam" you with a bunch of reports at once unsolicited)? Is there anything else that we can try to collect to make them easier to diagnose (aside from stack traces)?

**Comment by electrum** [comment]
Yes, please do file issues about these. Either a single issue or separate is fine. Having a stack trace that includes the test method is good.
