### ISSUE TITLE
Remove partial flush for TopN

### ISSUE THREAD

**Issue by haozhun** [prestodb/presto#8384]
Partial flush for TopN has both benefits and downsides:
* reducing global memory usage
* reducing parallelism

Note that partial TopN doesn't reduce the data size at all (unlike partial group by). Therefore, if partial flush happens, the local TopN is completely useless. (Exception exists when the size of a row is correlated with the relative order of its ORDER BY column)

As a result, if partial flush is necessary for TopN, it means basically all rows are streamed to the final TopN, rendering the partial TopN useless. When this happens, the parallelism of a query skydives. 

At the same time, this means the input rows for TopN is more than the global memory limit. Otherwise, reducing global memory usage wouldn't be very useful. Assuming a reasonable global memory limit of 500GB. Streaming this amount of data to one node, and have that one node handle all the rows is going to be painfully slow.

As a result, we conclude that we should just remove partial flush for TopN.

**Comment by findepi** [comment]
> As a result, if partial flush is necessary for TopN, it means basically all rows are streamed to the final TopN, rendering the partial TopN useless.

True as long as memory limit for partial TopN is fixed number. If partial flush has no benefits at all, let's remove it. If it, however, does have benefits, it could be reworked to use revokable memory.
