### ISSUE TITLE
Query ends with error when referencing non-existing key with subscript operator

### ISSUE THREAD

**Issue by majk-p** [prestodb/presto#8386]
Query ends with error when referencing non-existing key with subscript operator, e.g. the following query fails in Presto 0.178

    select
      m['foo'], -- 'bar'
      m['na'] -- NULL
    from (
      values
        (map(array['foo'], array['bar']))
    ) as t(m)
 
This worked well at least in Presto 0.158.
 
According to https://github.com/prestodb/presto/issues/4228 the subscript operator should return null for non-existing key.
 
This works well with `element_at(m,k)`
 
    select
      element_at(m, 'foo'), -- 'bar'
      element_at(m, 'na') -- NULL
    from (
    values
        (map(array['foo'], array['bar']))
    ) as t(m)
 
But apparently not with [] anymore.

**Comment by electrum** [comment]
This is the expected behavior. It was changed to match the SQL standard. We got the behavior wrong when we first implemented it. Sorry for the inconvenience.
