### ISSUE TITLE
Improve support for TupleDomain creation when cast are present

### ISSUE THREAD

**Issue by losipiuk** [prestodb/presto#8409]
Current mechanism for creating `TupleDomain` from filtering condition of shape:
```
CAST(column as LT) <op> literal
```
where `column` is of type `CT` and `literal` is of type `LT`, needs improvement.

1.  Current mechanism does not support case when many values from `CT` map to single value in `LT` (like with cast from `TIMESTAMP` to `DATE`, or from `DOUBLE` to `BIGINT` for large values)
2. It requires that CT to be strict subset of LT. It is for example not the case for cast `DECIMAL -> DOUBLE` as not every `DECIMAL` is exactly representable in `DOUBLE` domain.

Current mechanism depends on `SATURATED_FLOOR_CAST(v: T1): T2` operator. It finds biggest value in `T2` which if cast to `T1` would be less than or equal to `v` (or smallest value in `T2` domain if no such value exists).

The proposal is to change the semantics of `SFC(v: T1): T2` to:
* find value`w` in `T2` such that 
  * `CAST(w as T1) <= v` 
  * and for each `w'` <= `w` CAST(w' as T1) <= CAST(w as T1)`

Or more casually find smallest value in `T2` which if cast back to `T1` is less than or equal to `v` (preferably equal or not much less than `v`)

Then we extend this mechanism with twin operator `SATURATED_CEIL_CAST(v: T1):T2`.

And then introduce following transformation rules when `TupleDomain` is built:
* `CAST(c as LT) < v)` -> `c < SCC(v as CT)`
* `CAST(c as LT) <= v)` -> `c <= SCC(v as CT)`
* `CAST(c as LT) > v)` -> `c > SFC(v as CT)`
* `CAST(c as LT) >= v)` -> `c >= SFC(v as CT)`
* `CAST(c as LT) = v)` -> `c >= SFC(v as CT) AND c <= SCC(v as CT)`
* `CAST(c as LT) != v)` -> `c < SFC(v as CT) OR c > SCC(v as CT)`

Also it is important that we need to keep original expression in `Filter` as the `TupleDomain` coming from transformation may match for more values than original constraint.

cc: @sopel39

**Comment by electrum** [comment]
Can you give a few concrete examples?

**Comment by martint** [comment]
This is great. It's exactly what I was thinking.
