### ISSUE TITLE
Add IPv6 normalization UDF

### ISSUE THREAD

**Issue by MohamedBassem** [prestodb/presto#8427]
It would be nice to have UDFs for normalizing IPs and specially IPv6. By normalization I mean, padding with zeros, removing the zero padding and handling consecutive blocks of zeros (`::`).
I'd be happy to work on it.

**Comment by haozhun** [comment]
Standards track [RFC 5952 A Recommendation for IPv6 Address Text Representation](https://tools.ietf.org/html/rfc5952) basically determined what a "normalized" IPv6 representation should look like:

* remove all leading zeros
* use lower case letters
* Use `::` 

If we are going to provide a ipv6 normalization udf, it's likely not going to be what you described.

For your use case, a parse function that returns a `varbinary(16)` might be useful. But I don't know exactly how you are going to use it.

**Comment by MohamedBassem** [comment]
@haozhun 
I'm suggesting two UDFS:
1- One that takes an IP and normalize it in exactly the way you mentioned.
Example: `0000:0000:0000:0000:0000:0000:0000:001A => ::1a`

2- One that takes an IP and pads it with zeros. It's useful to support range queries.
Example: `::1A => 0000:0000:0000:0000:0000:0000:0000:001a`

Sorry if the description wasn't clear enough.

**Comment by haozhun** [comment]
Note (for future reference): special IPv6 addresses: https://networkengineering.stackexchange.com/questions/356/what-ipv6-prefixes-should-never-be-routed/441

**Comment by haozhun** [comment]
Superseded by #8509
