### ISSUE TITLE
Throttle queries per user/role basis

### ISSUE THREAD

**Issue by dabansal** [prestodb/presto#8438]
Hi All,

Is there a provision to throttle queries on the basis of user so one user is not hogging entire system and one query is not consuming all the resources of the cluster.

It is like allocating quota of hardware resources so that user can use what they are paying for.

Thanks,
Dheeraj

**Comment by nezihyigitbasi** [comment]
Please take a look at Presto's resource groups support ([here](https://prestodb.io/docs/current/admin/resource-groups.html)), it should help you do what you want.
