### ISSUE TITLE
Unable to use correlated symbol in HAVING clause

### ISSUE THREAD

**Issue by kokosing** [prestodb/presto#8456]
```
SELECT (
    SELECT avg(totalprice) 
    FROM orders GROUP BY custkey, orderdate
    HAVING avg(totalprice) < a
) FROM (VALUES 900) t(a); 

Query 20170708_154529_00025_r9p5s failed: line 1:95: '("avg"("totalprice") < "a")' must be an aggregate expression or appear in GROUP BY clause
```

**Comment by kokosing** [comment]
cc: @sopel39 @findepi

**Comment by sopel39** [comment]
I don't think currently correlated symbols can be used in aggregation context. It is doable (e.g: correlated symbol should be treated as constant) but not supported right now. However, error message: ` '("avg"("totalprice") < "a")'` is rather strange, so maybe something fishy happens
