### ISSUE TITLE
Parquet reader returns wrong value for DecimalType of specified scale.

### ISSUE THREAD

**Issue by smith-m** [prestodb/presto#8465]
from presto .177

the column decimal(18,2), msrp

select msrp from product where id =1;

The product table is written from spark with parquet.

This returns a value of 5,149,500.00 instead of the expected value of 51,495.00. Reading the same record in PySpark shows the expected value of 51,495.00. Rewriting the table as ORC resolves this issue.

**Comment by nezihyigitbasi** [comment]
- Do you use the new reader? (is `hive.parquet-optimized-reader.enabled` true?)
- Do you have test data to repro it so that someone can take a look at it and fix?

**Comment by nezihyigitbasi** [comment]
I guess to debug you need to put a breakpoint in `ParquetShortDecimalColumnReader::readValue()`, something may be messed up in that method.

**Comment by smith-m** [comment]
Both of these parquet flags are enabled on presto:

hive.parquet-optimized-reader.enabled=true
hive.parquet-predicate-pushdown.enabled=true

This PySpark code creates a table that illustrates the issue

`from pyspark.sql.types import *
from decimal import *
example = [
    (0,Decimal("1234.00")),
    (1,Decimal("52000.00")),
    (2,Decimal("300000.12"))
]

schema = StructType([
    StructField("id", IntegerType(), True),
    StructField("msrp", DecimalType(18,2), True)]
)
exampleDF = spark.createDataFrame(example,schema).coalesce(1)
exampleDF.write.mode("overwrite").format("parquet").saveAsTable("calc.decimal_test")`

I can upload the resulting parquet file as well if it is helpful.

With precision set to 19, this issue does not happen, so I imagine it is an issue with the int precision logic.

**Comment by smith-m** [comment]
Example table

[part-00000-0058f5f6-c60a-4d1d-b405-09f8b30e9f79.snappy.parquet.zip](https://github.com/prestodb/presto/files/1137376/part-00000-0058f5f6-c60a-4d1d-b405-09f8b30e9f79.snappy.parquet.zip)

**Comment by nezihyigitbasi** [comment]
@smith-m I think I got what's going on. According to the Parquet [spec](https://github.com/Parquet/parquet-format/blob/master/LogicalTypes.md) when decimals are encoded with primitives (int32/int64) Parquet stores only the unscaled value. I created a #8488 to fix this, can you please try that patch with your datasets? I tested it with the test parquet file above and it works fine.
