### ISSUE TITLE
tableName is null in Cassandra connector

### ISSUE THREAD

**Issue by majk-p** [prestodb/presto#8470]
I need to perform schema scan for my databases connected to presto. Performing table-level scan looks like:

    SELECT table_name, column_name, data_type
    FROM "some-schema".information_schema.columns
    WHERE table_schema = 'some-schema'
    ORDER BY column_name ASC

It works fine for all SQL databases. When trying to scan Cassandra I'm facing following error:

 > Query ***** failed: tableName is null

It seems to be problem with `CassandraMetadata.java` not supporting empty `table_name` predicate here: https://github.com/prestodb/presto/blob/master/presto-cassandra/src/main/java/com/facebook/presto/cassandra/CassandraMetadata.java#L188

It seems there's a wrong method used: `prefix.getSchemaName()` where I believe it should be: `if (prefix.getTableName() == null) {`

**Comment by ebyhr** [comment]
I think `if (prefix.getSchemaName() == null || prefix.getTableName() == null)` is better than replacing from getSchemaName to getTableName.  Do you have a plan to make the PR?

**Comment by majk-p** [comment]
I could make a PR for that, but I'm short on time at the moment. If you'd like to take it feel free to do so. I've found similar issues in couple more connectors if you'd want to take a look.
