### ISSUE TITLE
explain for join fails on Hive when partition_by contains TS column

### ISSUE THREAD

**Issue by maciejgrzybek** [prestodb/presto#8497]
Steps to reproduce:
1. Create a table with timestamp column which is partition key:
  `create table ts_table (a bigint, ts timestamp) with (partitioned_by = array['ts']);`
2. Insert any data into such table (does not reproduce when table is empty):
  `insert into ts_table values (1, cast(current_time as timestamp));`
3. Create any other table (doesn't have to contain TS column):
  `create table other_table (a bigint);`
4. Try to join both tables (TS column doesn't have to be included in the join criteria):
```
presto:default> explain select ts_table.*, other_table.* from ts_table, other_table where ts_table.a = other_table.a;
Query 20170713_202815_00064_etzv2 failed: index (1) must be less than size (1)
```

**Comment by findepi** [comment]
@maciejgrzybek, did you see #8329?

**Comment by maciejgrzybek** [comment]
Good point, it's duplicate. Closing, thanks!
