### ISSUE TITLE
outer join  on hive and presto？

### ISSUE THREAD

**Issue by AomoDa** [prestodb/presto#8511]
官方文档上有这么一句话，
原文地址是 http://prestodb-china.com/docs/current/migration/from-hive.html

![wechatimg5](https://user-images.githubusercontent.com/20105041/28240771-eefc841a-69b9-11e7-8fd3-743dc8ed0087.jpeg)

我感到非常疑惑，使用hive进行测试，我的hive版本是 2.1.0
结果显示：
![489ac68a612172d5cadcf4faf880d4d1](https://user-images.githubusercontent.com/20105041/28240779-10ebfa7e-69ba-11e7-8603-f4e9757c56df.png)
![cc069cc643237e1cfd6dd6478686fae2](https://user-images.githubusercontent.com/20105041/28240781-18c1186a-69ba-11e7-9cfa-8099d366753f.png)

经过我的测试，我感觉 ”注意Hive认为 ON 子句是 WHERE 子句的一部分“ 这句话是不对的。

**Comment by ray6080** [comment]
这应该是京东的Presto分支的文档，不是Presto官方的文档。我认为应该到[JD-Presto](https://github.com/CHINA-JD/presto/)这里评论。

**Comment by rschlussel** [comment]
Please file issues in English
