### ISSUE TITLE
Can't connect to Hive Metastore with SASL

### ISSUE THREAD

**Issue by rohit-kulk** [prestodb/presto#8526]
I want to use SASL with username and password to connect to Hive Metastore & HDFS. After looking in the documentation, I see this property:

hive.metastore.authentication.type - One of NONE or KERBEROS

- When using the default value of NONE, Kerberos authentication is disabled and no other properties need to be configured.
- When set to KERBEROS the Hive connector will connect to the Hive metastore Thrift service using SASL and authenticate using Kerberos.

I want to use SASL without Kerberos.. But the only two options are None (which is no authentication) or Kerberos (with SASL). Is there any way for me to pass the username and password for Hive Metastore and HDFS without using Kerberos?

**Comment by cawallin** [comment]
No, unfortunately the only options right now are no authentication and Kerberos authentication. We don't currently have a way to pass down the username/password from the CLI to connectors, so that needs to be in place before we can use SASL with an individual user's credentials.
