### ISSUE TITLE
Temporary table left after insert into mysql table fails

### ISSUE THREAD

**Issue by harbby** [prestodb/presto#8536]
Hi I found a bug to implement jdbc insert into!
It is like this:
         When the mysql character set is latin1 - cp1252 West European,
I execute the insert statement: insert into test1 values ('世界', cast ('Ver.1.3' as varchar (100)))
I got the following error:
         Query 20170718_012821_00019_yucvr failed: Incorrect string value: '\ xE8 \ xB4 \ xB5 \ xE9 \ x98 \ xB3 ...' for column 'user_addr_name' at row 1
After a period of time there are many temporary table:
![2017-07-18 09-40-57](https://user-images.githubusercontent.com/19815755/28296899-8b923c7c-6b9d-11e7-8cc1-10b5d5f77ff9.png)

**Comment by ideal-hp** [comment]
At the moment I was so resolved:
       Modify the commit () method of the prestou-base-jdbc module JdbcRecordSink.java file:
![image](https://user-images.githubusercontent.com/19815755/28297070-75ff8238-6b9e-11e7-89d7-ff0f83e9ef48.png)
       DropTemporaryTable () method is as follows:
    private void DropTemporaryTable()
    {
        String temporaryTable = ((BaseJdbcClient) jdbcClient).quoted(handle.getCatalogName(), handle.getSchemaName(), handle.getTemporaryTableName());
        String cleanupSql = "DROP TABLE " + temporaryTable;
        try (java.sql.Statement statement = connection.createStatement()) {
            statement.execute(cleanupSql);
        }
        catch (SQLException e) {
            //throw new PrestoException(JDBC_ERROR, e);
        }
    }
