### ISSUE TITLE
SymbolsExtractor doesn't correctly extract all symbols from JoinNode

### ISSUE THREAD

**Issue by sopel39** [prestodb/presto#8552]
Check https://github.com/prestodb/presto/commit/079f5fa94488a07f987cf5af767bf66130c32849#diff-f35aac8ae02c212c0868dc5ccb916327R213 to see how symbols (dependencies) from join node should be extracted.

`SymbolsExtractor` need to correctly extract all symbols from join node. Probably there are mode nodes (e.g: with `Assignments`) where not all symbols are extracted. In fact, `SymbolsExtractor` should probably be refactored so that methods names are more explicit in what context to use them, e.g: 
```
extractDependencies
extractSubtreeSymbols
```
 and so on...

FYI: @kokosing

**Comment by kokosing** [comment]
I will take care of this, as I already started to work on `Symbol*Extractor`, see https://github.com/prestodb/presto/pull/8324
