### ISSUE TITLE
Presto Performance Tuning

### ISSUE THREAD

**Issue by abhishekshenoy** [prestodb/presto#8556]
_We are Using Presto 0.171

We have cluster of 23 nodes , 20 datanodes and 3 master nodes wherein we have given fault tolerance support for namenode.

Our presto workers are collocated with the datnodes and Our presto coordinator with the namenode.

Each DataNode has 180 GB Ram(120 gb is dedicated to Yarn) Have given the JVM heap size for presto as 21G , Max memory for each query as 100G and Max-memory for a query per node as 5GB.

Each Data node has 48CPU's and i can see that by default the task.max-worker threads is 96(48*2) and task.concurrency is 16.

Our Block Size for hive is set as 134Mb.

Our hive table stores data in Parquet format._

Queries:

1.I can see only one task per node getting scheduled in the presto GUI , what is the role of task.max-worker-threads and task.concurrency?

2.How can i increase the number of tasks that gets scheduled per node?

3.How is the block size and splits in presto related , will i be able to see a performance increment if i increase the max-split-size in hive connector to 134 MB ? _(Have tried it but it throws an exception on starting presto server)_

4.Even though my table is partitioned and my query filter has partitioned col filter it takes nearly 10-15 mins to fetch 220 columns , i can see that its working on 84000 splits. If i decrease the number of columns to 50 , the time decreases to 1 min and 20 columns it takes 20s. Is there away i can improve this? 

5.I have added these properties in addition to the default config properties but could not get any major performance benefits. It will be helpful to know if i have used them right.

a.**task.concurrency=32**_(As default was 16 , doubled it but even when it was 16 i can see only 1 task per node)_

b.**task.writer-count=32**

c.**node-scheduler.min-candidates=20** _( As we have 20 nodes, coordinator would use 20 nodes to decide where splits have to be processed instead of 10 which is the default value)_

d.**node-scheduler.network-topology=flat** _( As it would ensure that 50% of the queue for scheduling splits is reserved for local splits)_

e.**node-scheduler.max-splits-per-node=300** _(default was 200 , but could not see any added benefit while the query has 220 odd columns)_

f.**node-scheduler.max-pending-splits-per-task=30** _(Default was 10)_

g.**query.execution-policy=phased** _( At any point in time we will have max of 10 queries working in parallel so would the default value be better ?)_

**Comment by abhishekshenoy** [comment]
Wrong place to post this

**Comment by satybald** [comment]
for reference, could you post links here?

**Comment by mnoumanshahzad** [comment]
Hi @abhishekshenoy I am looking for answers to similar questions as yours. Can you share your findings or maybe point to a resource you found useful?
