### ISSUE TITLE
toLowerCase

### ISSUE THREAD

**Issue by MichaelAlo** [prestodb/presto#8578]
Hi, 

Is the the toLowerCase function is the one that generates an issue when try to query a MySQL table whose name is in upper case with dbGetQuery?

My MySQL tables are in upper case and it seems that the query is sent in lower case and so have the message that the table does not exist (case sensitive issue then).

Cheers 

```private static String checkLowerCase(String value, String name)
    {
        if (value == null) {
            throw new NullPointerException(format("%s is null", name));
        }
        checkArgument(value.equals(value.toLowerCase(ENGLISH)), "%s is not lowercase", name);
        return value;
    }
```

**Comment by ITGrocery** [comment]
I found the same problem same as up，what shoud i do to solve it?
