### ISSUE TITLE
passing password to presto-cli for automated scripts

### ISSUE THREAD

**Issue by moshir** [prestodb/presto#8609]
I read that presto-cli --password prompts for user password.
However, when using presto-cli to automate queries (e.g. views), what's the approach ? 
I also read about $PRESTO_PASSWORD environment variable, is it document somewhere ?

**Comment by moshir** [comment]
closing
PRESTO_PASSWORD  needs to be set system wise
and  --password needs to be passed to presto-cli

**Comment by dain** [comment]
In unix, environment variables are not "system wide".  For example, in a bash shell on linux, you can execute the presto cli with `PRESTO_PASSWORD=foo presto`.  This will pass the password to the cli using the environment variables scoped to that single command.  For scripts, using environment variables is the preferred approach, so you password is not exposed to others using the `ps` command.

**Comment by brokenjacobs** [comment]
I realize this is a closed issue, but I wanted to point out that on a linux system at least, environment variables are world readable by default via the /proc filesystem.

cat /proc/PID/environ
To see what I mean. 

An option that supports reading this value from a file would be more secure.
