### ISSUE TITLE
when i execute "show catalog", only print "system"

### ISSUE THREAD

**Issue by liuch0730** [prestodb/presto#8626]
i have already configured "hive.properties" in etc/catalog.
hive.properties
    connector.name=hive-hadoop2
    hive.metastore.uri=thrift://hadoop0:9083
but when i execute "./presto" and "show catalog", only print "system".
when i execute "./presto --catalog hive" and "show  schemas", print "Catalog hive does not exist".

thanks!

**Comment by liuch0730** [comment]
version:presto 0.181

**Comment by akshatnair** [comment]
Did you restart Presto after adding `hive.properties` file?

**Comment by anubhav100** [comment]
@akshatnair i am facing the same issue with same properties and yes i restarted it

**Comment by liuch0730** [comment]
@akshatnair @anubhav100 thanks.
just at that moment， i restart it, it print "Catalog hive does not exist"  as before.
so i redeployed it and restart，it works。
