### ISSUE TITLE
what't the specific propertis meaning of resource group?

### ISSUE THREAD

**Issue by youngqi2017** [prestodb/presto#8633]
I am research the presto, I noticed the new feature of resource group. but I can not understand some properties of of resource group. For example softMemoryLimit: if a query which peakMemoryBytes and totalBytes value are all bigger than the softMemoryLimit value. what had happened?

**Comment by nezihyigitbasi** [comment]
For a resource group, if the sum of the `totalMemoryReservation` of all running queries in that group (and it subgroups) exceeds the soft memory limit new queries will be queued.

If you have additional questions please use the [presto-users group](https://groups.google.com/forum/#!forum/presto-users).
