### ISSUE TITLE
Ignore max memory per node when resources are overcommitted

### ISSUE THREAD

**Issue by zsaltys** [prestodb/presto#8638]
Sometimes when we want to run unreasonable queries we like to set resource_overcommit = true on a session level. However that does not protect you from max memory per node limitation as we still get local memory errors even with resource_overcommit = true. It's not possible to change the max memory per node with a session parameter. It would be great if it were possible to change the max memory per node from a session or to simply allow queries to use whatever is available.

**Comment by nezihyigitbasi** [comment]
Did you check the `query_max_memory` session parameter (you will still be bounded by the `query.max-memory` configuration parameter if you try going above that)?

**Comment by haozhun** [comment]
In current implementation, queries with `resource_overcommit` does not respect local memory limit or global memory limit. It can go over both.

However, they will be the first that get killed if memory is not sufficient overall (when you have multiple queries running).

**Comment by zsaltys** [comment]
@haozhun @nezihyigitbasi here's some proof showing that resource_overcommit does not ignore local memory limits:

![screen shot 2017-08-10 at 10 42 15 am](https://user-images.githubusercontent.com/1583403/29164888-f08de158-7db8-11e7-8cd0-31736f5dbda3.png)

You can see in the screenshot of the query that spilling and overcommit is enabled yet the query fails with 5gb local memory limit. Each worker has 50gb heaps with 10% given per query. Can you help me find out why this happens?

**Comment by zsaltys** [comment]
If that helps the query runs:  count(distinct some_field) as some_field_unique .. I know this is very memory intensive but I dont understand why the local limit is being respected.

**Comment by zsaltys** [comment]
@nezihyigitbasi @haozhun I've been pointed to this patch: https://github.com/prestodb/presto/commit/36fd02257cbfb1c0598c72eab8591517bf6dd2ed

It seems what's happening is that when resource overcommit is enabled then worker memory is limited to general pool amount. Which in my opinion does not make sense. For example on our machines we have:

reserved 51,569,672,323
system 41,234,543,411
general 10,282,142,794

So the query dies on 10 GB. I think maybe perhaps when queries use resource overcommit they should run on reserved pool? Or be promoted to reserved pool?

Any help would be appreciated,

Thanks!

**Comment by zsaltys** [comment]
@cberner your input would be very valuable here. thanks!

**Comment by cberner** [comment]
The reason that overcommitted queries don't run in the reserved pool is that the typical setup is to have the general pool be much larger than the reserved pool. Technically, it would be possible to allow them to grow to the full size of reserved + general, but the implementation would be a bit difficult, as the accounting system wasn't designed that way.
Normally you would size your reserved pool to be significantly smaller than half the heap. I'd target ~20%. In that case things will work more as you expect: overcommitting a query will allow it to use a large amount of memory.
If that doesn't work for you, you might want to increase query.max-memory, and then reduce it for queries that don't need very much memory via the session property. That will have the effect of letting queries run in the reserved pool with a higher limit.

**Comment by haozhun** [comment]
@zsaltys 

The problem with your set up is your reserve pool size (which should always equal to local memory limit) is way too high. (Your screenshot shows a 5GB local memory limit. But your reserved pool is showing 50G. I would assume you got them from two different setups)

An example of a reasonable configuration is 200GB heap: 30G reserved, 90G general, 80G system. In such a configuration, whether a query with "resource_overcommit" can use 90 or 120 is not that big of a difference, and wasn't worth the engineering effort.

Do you really need a 50GB per-query local memory limit? Please lower it if you don't. If you have one or two query that needs it, please fix those queries.

**Comment by zsaltys** [comment]
@haozhun Yes, I understand what you're saying and I've already lowered to reserved pool to 10G. Thank you for your help.

**Comment by sopel39** [comment]
This still seem to be an issue. Query with `resource_overcommit=true` will fail with `Query exceeded local memory limit...` when spill is enabled.
