### ISSUE TITLE
Select query is not throwing any exception, when select operation is performed inside an unexisting database

### ISSUE THREAD

**Issue by geetikagupta16** [prestodb/presto#8639]
I am using presto hive connector and presto-cli, when I tried to execute the following query from presto-cli inside an unexisting database, it does not throw any exception.

> presto:xyz> select * from default.test;
> id
`----
`
> 1 
> (1 row)

Below is the output for show schemas in presto-cli :

> presto:xyz> show schemas;
       Schema
` --------------------
`
> default            
> information_schema
> (2 rows)

When I tried to perform the above select query, it executed successfully however it should throw a `SchemaNotFound` Exception as `xyz` is not present in my hive schemas;

**Comment by kokosing** [comment]
When you use `default.test` in a query you refer for a `test` table from `default` schema (not from `xyz`). In such case it does not matter what schema is set in your session.
