### ISSUE TITLE
Java JDBC连接hive执行SQL时候报400

### ISSUE THREAD

**Issue by chaojichantui** [prestodb/presto#8651]
优秀的京东团队:
           您好，我现在用您的Presto,感觉非常好，但是有一点点问题想请教一下，我用Java JDBC连接时连接比如mysql非常好，但是hive报错400很遗憾我debug调试就是 执行sql语句   select * from table_name报错，
不知道什么原因，还望能够解决一下，不胜感谢

                  中国大唐移动通信有限公司  Adley  
联系方式： maxin@cattsoft.com

**Comment by kokosing** [comment]
Can you please use English otherwise we are unable to help you .

**Comment by sd4324530** [comment]
这个是facebook在维护的，不是京东，我也是醉了
