### ISSUE TITLE
Session Properties

### ISSUE THREAD

**Issue by zrjnike** [prestodb/presto#8659]
how should i get Session Properties in Scalar Function
https://prestodb.io/docs/current/develop/functions.html
Session defined:
connection.unwrap(PrestoConnection.class).setSessionProperty("name", "value");
like https://prestodb.io/docs/current/release/release-0.78.html

**Comment by zrjnike** [comment]
@electrum @joshk please help

**Comment by electrum** [comment]
You can add `ConnectorSession` as the first argument to your function. See `DateTimeFunctions` for an example.

**Comment by zrjnike** [comment]
@electrum  , Sorry for Excuse again,
      i have tested,but it just return null,
i have down the presto code 0.173 test,and the reason is that    properties    attribute is null,how to fix this?
please help! thanks
![image](https://user-images.githubusercontent.com/27471173/29062671-2168b664-7c55-11e7-91bd-a3d94e4563ba.png)


@Override
    public <T> T getProperty(String propertyName, Class<T> type)
    {
        if (properties == null) {
            throw new PrestoException(INVALID_SESSION_PROPERTY, format("Unknown session property: %s.%s", catalog, propertyName));
        }

        return sessionPropertyManager.decodeCatalogPropertyValue(connectorId, catalog, propertyName, properties.get(propertyName), type);
    }
