### ISSUE TITLE
How to build presto like tarball

### ISSUE THREAD

**Issue by dabansal** [prestodb/presto#8660]
Hi All,

I am able to build using "mvn clean build" after modifying presto 0.178 codebase but it is creating individual jar files in each of the sub-projects. 

Is there a way to build presto in the same format what which we download from presto's website with all the folders.

Thanks,
Dheeraj

**Comment by petroav** [comment]
@dabansal After a build, the `presto-server/target` folder will contain the tar ball. For the RPM you'll have to look in `presto-server-rpm/target`.
