### ISSUE TITLE
Chat communication, alternative to IRC

### ISSUE THREAD

**Issue by satybald** [prestodb/presto#8676]
Many FOSS projects use IRC, however, the service has some disadvantages in terms of staying always online to get the messages. Also, I noticed that not many folks from Presto are using it. I'm wondering if community thought about using some other services for chat communication instead of IRC? 

Found some reference to pros and cons for existsing chat for FOSS.
https://github.com/reactiflux/volunteers/issues/25

**Comment by synhershko** [comment]
From personal experience I can recommend gitter, it works very well for FOSS projects and has github integration. Another path I'm seeing many projects take is open up their Slack account to the public.

**Comment by haozhun** [comment]
Presto has a slack channel at prestodb.slack.com
