### ISSUE TITLE
join fewest columns for order by

### ISSUE THREAD

**Issue by lvijay** [prestodb/presto#8679]
I found that when joining two tables with an ORDER BY and a LIMIT, Presto on Hive performs much better when the two tables are joined on the fewest possible columns and then INNER joined with themselves.

Running the second example results in a significantly better performance than the first (2x faster on my cluster, lesser memory, higher concurrency).

    SELECT cols -- 10 dim columns, 4 aggregated fact columns
    FROM
        dim 
    LEFT OUTER JOIN
        fact
    ON
        dim.key1=fact.key1
    GROUP BY
        ...
    ORDER BY dim.name
    LIMIT 1000

vs

    SELECT cols -- all requested dim columns
    FROM
        dim
    INNER JOIN
        (
            SELECT dim.key1, dim.name, SUM(fact.clicks) AS "clicks"
            FROM
                dim
            LEFT OUTER JOIN
                fact
            ON dim.key1 = fact.key1
            GROUP BY 1, 2
            ORDER BY dim.name
            LIMIT 1000
        ) AS joined
    ON dim.key1=joined.key1
    ORDER BY dim.name
    LIMIT 1000

The ask is that the query planner execute requests of the form `t1 ⋊ t2 ORDER BY x LIMIT y` instead as `t1 ⋈ t2 ⋈ (t1' ⋊ t2' ORDER BY x LIMIT y) ORDER BY x LIMIT y`

where ⋊ is LEFT OUTER JOIN, ⋈ is INNER JOIN and t1' and t2' are sub-selects from which only the join columns and ordering columns are projected.

**Comment by electrum** [comment]
This type of transformation is not safe, unfortunately, since there's no guarantee the connector will produce identical rows for each table scan. For example, someone may add or remove files in between scans.

**Comment by lvijay** [comment]
You're right, @electrum.  I hadn't thought of the race condition at all.

That's a pity because this really speeds up performance and, in our particular usecase, it won't actually cause problems in practice.  We don't delete ids and while it is possible that someone edits `name` in flight and we'd show `boeing, airbus` because someone fixed a typo on "iarbus" while the query was executing, it's something _we_ can live with.  (In my original example, we'd project the ordering columns from `joined` rather than `dim`.)

I also realized that self-joins also face this problem.  Is it the case that Presto's semantics dictate that a tablescan will be done exactly as many times as the table is mentioned in the query?  So, in the self-join case of `t1 x t1`, scanning t1 twice is justified because t1 is mentioned twice.

Do you think there's a case to be made for adding a query option `repeated-datasource-read-race-ignore=true` (actual name TBD) that could then support this feature?

The larger problem which prompted this query rewrite is that ordering several columns causes CPU spikes on workers and causes slowdowns.

**Comment by martint** [comment]
With the right transaction isolation, it can be a safe transformation.

**Comment by lvijay** [comment]
@electrum @martint where would I start with making these changes?
