### ISSUE TITLE
Filtering with subquery cause constraint to be TupleDomain.ALL

### ISSUE THREAD

**Issue by xiaoyao1991** [prestodb/presto#8680]
In `ConnectorMetadata`, the `getTableLayouts` method takes a parameter `Constraint<ColumnHandle> constraint` that holds the filtering semantics. I leverage this to implement some custom predicate pushdown logics for my custom made connectors. However, I found that when a query filters on some values from a subquery, the `constraint` will be short-circuited and be `TupleDomain.ALL`. 

e.g. 
```sql
SELECT SUM(tx_value) FROM tx 
WHERE tx_blocknumber IN 
    (SELECT block_number FROM block WHERE block_timestamp >= 1501964936)
```

The constraint will be `TupleDomain.ALL` in `ConnectorMetadata.getTableLayouts` method for `tx` table. The connector will essentially then scan the full `tx` table without any predicate pushdown.

I'm seeing if there's anyway I can override the behavior so that I can still get the constraint(maybe in some other lazy-evaluation way) instead of just `TupleDomain.ALL` in such case. 

Any help would be appreciated.

**Comment by electrum** [comment]
The engine asks for table layouts during planning, then starts executing the query at which time the subquery is run. In other words, the subquery is run too late to provide a `TupleDomain`. This should be solved by the Dynamic Partition Pruning work in ##8588.

**Comment by electrum** [comment]
The work around for now, assuming the subquery produces a relatively small number of values (maybe ~1000), is to run the subquery first, then substitute them into the outer query. This is obviously less than ideal, but is possible if you have another system them is generating / running the queries.

**Comment by xiaoyao1991** [comment]
@electrum Thanks. I understand that table layouts is computed during planning. I've tried some hacks such as to change the `splitSource` on the fly, but it could cause bad corner case error. 

Any plan on when the Dynamic Partition Pruning would be merged?

**Comment by electrum** [comment]
Actually, another potential option is make the connector take advantage of index joins. It might be possible if the query is written like this:

```sql
SELECT SUM(tx.tx_value)
FROM block
JOIN tx ON block.block_number = tx.tx_blocknumber
WHERE block.block_timestamp >= 1501964936
```

The index join will do a batched nested-loop index lookup against `tx`. This might not be efficient if `tx` is not inherently indexed or if there are many rows for each `tx_blocknumber`.

Take a look at `IndexedTpchPlugin` for an example. You can play around with it by changing `TpchQueryRunner` to install `IndexedTpchPlugin` instead of `TpchPlugin`. Just run the `main()` method. This is a nice trick to quickly start the server (several connectors have these runner classes). Try out queries against the indexed TPCH connector and make sure it will work for your use case before investing effort in implementing it in your connector.

**Comment by electrum** [comment]
I haven't been following the work on that feature. You can ask on the Pull Request or in the IRC or Slack channel.

**Comment by xiaoyao1991** [comment]
Thanks! I will take a look into that.

**Comment by Praveen2112** [comment]
@xiaoyao1991 I guess Presto's optimizer will convert the above query to semi join and the Predicate push down will be applied to the build side table(block table).

**Comment by xiaoyao1991** [comment]
@Praveen2112 In order for that to happen, does the connector need to be written in some way? I'm relying on the `getTableLayouts` in metadata to narrow down the number of splits to splitManager, and I'm not seeing the behavior you described. Maybe I'm missing something?

**Comment by Praveen2112** [comment]
@xiaoyao1991 I guess it is independent of the connector provided the connector has proper way of handling the` TupleDomain`.`TupleDomain.ALL` will be created in these conditions 
1. When there is no filter criteria.
2. When there is OR condition in the filter criteria (A=1 or B = 2) .
3.When there is some function in filter criteria (fun(A) =2 ).

Does the filter condition in filter query satisfies any on the above condition.
Which version of Presto are you using ? Can you share the query plan created for the above query ?

**Comment by xiaoyao1991** [comment]
@Praveen2112 I'm using 0.181, query plan looks like:
```
 - Output[_col0] => [sum:double]
         _col0 := sum
     - Aggregate(FINAL) => [sum:double]
             sum := "sum"("sum_11")
         - LocalExchange[SINGLE] () => sum_11:double
             - RemoteExchange[GATHER] => sum_11:double
                 - Aggregate(PARTIAL) => [sum_11:double]
                         sum_11 := "sum"("tx_value")
                     - FilterProject[filterPredicate = "expr_5"] => [tx_value:double]
                         - Project[] => [tx_blocknumber:bigint, tx_value:double, expr_5:boolean]
                             - SemiJoin[tx_blocknumber = block_number][$hashvalue, $hashvalue_13] => [tx_blocknumber:bigint, tx_value:double, $hashvalue:bigint, expr_5:boolean]
                                 - RemoteExchange[REPARTITION][$hashvalue] => tx_blocknumber:bigint, tx_value:double, $hashvalue:bigint
                                     - ScanProject[table = ethereum:EthereumTableHandle(connectorId=EthereumConnectorId(connectorId=ethereum), schemaName=default, tableName=transaction), originalConstra
                                             $hashvalue_12 := "combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("tx_blocknumber"), 0))
                                             LAYOUT: EthereumTableLayoutHandle(table=EthereumTableHandle(connectorId=EthereumConnectorId(connectorId=ethereum), schemaName=default, tableName=transaction)
                                             tx_blocknumber := EthereumColumnHandle(connectorId=EthereumConnectorId(connectorId=ethereum), ordinalPosition=3, name=tx_blockNumber, type=bigint)
                                             tx_value := EthereumColumnHandle(connectorId=EthereumConnectorId(connectorId=ethereum), ordinalPosition=7, name=tx_value, type=double)
                                 - LocalExchange[SINGLE] () => block_number:bigint, $hashvalue_13:bigint
                                     - RemoteExchange[REPARTITION - REPLICATE NULLS AND ANY][$hashvalue_14] => block_number:bigint, $hashvalue_14:bigint
                                         - ScanFilterProject[table = ethereum:EthereumTableHandle(connectorId=EthereumConnectorId(connectorId=ethereum), schemaName=default, tableName=block), originalCon
                                                 $hashvalue_15 := "combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("block_number"), 0))
                                                 LAYOUT: EthereumTableLayoutHandle(table=EthereumTableHandle(connectorId=EthereumConnectorId(connectorId=ethereum), schemaName=default, tableName=block),
                                                 block_number := EthereumColumnHandle(connectorId=EthereumConnectorId(connectorId=ethereum), ordinalPosition=0, name=block_number, type=bigint)
                                                 block_timestamp := EthereumColumnHandle(connectorId=EthereumConnectorId(connectorId=ethereum), ordinalPosition=15, name=block_timestamp, type=bigint)
```

**Comment by Praveen2112** [comment]
@xiaoyao1991 from the query plan we can infer that the query is translated to Semi Join. I guess `TupleDomain.ALL` is obtained for the table Transaction which doesnt have any filter criteria whereas Table Block has a filter criteria and a corresponding TupleDomain is generated.

**Comment by xiaoyao1991** [comment]
@Praveen2112 thanks a bunch for looking. I don't understand why it interprets that Transaction table doesn't have any filter criteria. In the query that generates the above execution plan ```
SELECT SUM(tx_value) FROM tx 
WHERE tx_blocknumber IN 
    (SELECT block_number FROM block WHERE block_timestamp >= 1501964936)
```
the `WHERE tx_blocknumber IN...` should be considered as a filter on Transaction table right?

**Comment by Praveen2112** [comment]
In the above query the filter criteria is actually converted to a semi join and its executed so for the probe side table(tx_blocknumber) the TupleDomain is set to All. As electrum said from Dynamic Partition , based on the values of the build side table (block) we might get a TupleDomain which will be used for filtering the tx_blocknumber table.

**Comment by findepi** [comment]
This has been answered. https://github.com/prestodb/presto/issues/7428 tracks the dynamic filtering feature.
