### ISSUE TITLE
Presto and Mongo DB issues

### ISSUE THREAD

**Issue by clakkina** [prestodb/presto#8688]
Hi Team,

I am trying to use Presto with MongoDB and having below issue after connecting to the database.

![image](https://user-images.githubusercontent.com/27369310/29038584-34b8ac7c-7b76-11e7-9330-a1497f3d25fd.png)

Here is my mongod config file:
============================
[root@ushdbld00058lb catalog]# cat mongodb.properties
connector.name=mongodb
#mongodb.seeds=host1,host:port
mongodb.seeds=host:27017
mongodb.credentials=usr:pass@admin
mongodb.ssl.enabled=true
============================

Could someone please look into this issue and let me know further.

Thanks,
Chandra L.

**Comment by princekumaragstar** [comment]
I am also getting the same error.
