### ISSUE TITLE
I think that incorrect implementation MemorySplitManager

### ISSUE THREAD

**Issue by Bongss** [prestodb/presto#8714]
**MemorySplitManager class**

In getSplit(), 
I think that **MemorySplit's fifth parameter**(expectedRows) should **dataFragment.getRows() / splitsPerNode** when it constructs MemorySplit objects.

```
new MemorySplit(
              layout.getTable(),
              i,
              splitsPerNode,
              dataFragment.getHostAddress(),
              dataFragment.getRows()));  // --> dataFragment.getRows() / splitsPerNode
```
Since data is divided by **numberOfSplits**(or **splitsPerNode**), **Each MemorySplit** is likely to have the following expectedRows: **dataFragment.getRows() / splitsPerNode**

In fact, I'm not sure. but I don't understand that why that field is **dataFragment.getRows()** in spite of doing split.

**Comment by pnowojski** [comment]
I think it is correct as it is. `MemoryDataFragment` represents a data fragment of a table stored on some particular node. As I remember this 5th parameter is not about the number of rows returned by this split, but about the validating that after restarting worker, we do not loose any data. But I'm also not 100% sure. You can always change the code and is if the tests are passing - and if not find out why.
