### ISSUE TITLE
Filter predicate like is not pushed down in case of using wildcards

### ISSUE THREAD

**Issue by Msirkovsky** [prestodb/presto#8727]
In this query:

`select * from table where name like 'Test'`

predicate `name like 'Test'` is pushed down. But in the following query doesn’t:

`select * from table where name like '%Test%'`

My catalog is MS SQL.

**Comment by akshatnair** [comment]
It is probably because in the first query it gets converted to an equality predicate which is definitely pushed down for JDBC connectors. It may not be the case for the LIKE predicates.

**Comment by Msirkovsky** [comment]
Yes I find the code that replace `like predicate` with the equality predicate (`ExpressionInterpreter.java`). Can you explain me why LIKE predicate with wildcards cant be pushed down for JDBC connectors as well?
Thank you.

**Comment by findepi** [comment]
What gets pushed down to a connector is not a predicate, but a simpler constraint, expressed as a `TupleDomain` (list of non-overlapping ranges). Obviously, `name like '%Test%'` cannot be translated to such a form, so currently it cannot be pushed down.
