### ISSUE TITLE
Partition key is Timestamp Type 

### ISSUE THREAD

**Issue by subway1211** [prestodb/presto#8742]
java.lang.invoke.WrongMethodTypeException: cannot convert MethodHandle(ConnectorSession,long)Slice to (Object)Object
	at java.lang.invoke.MethodHandle.asTypeUncached(MethodHandle.java:775)
	at java.lang.invoke.MethodHandle.asType(MethodHandle.java:761)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.lambda$buildPartitions$0(InformationSchemaPageSourceProvider.java:299)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.buildPartitions(InformationSchemaPageSourceProvider.java:289)
	at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.getInformationSchemaTable(InformationSchemaPageSourceProvider.java:156)
	at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.getInternalTable(InformationSchemaPageSourceProvider.java:138)
	at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.createPageSource(InformationSchemaPageSourceProvider.java:96)
	at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:56)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:219)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:300)
	at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:234)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:538)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:229)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:623)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:463)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

**Comment by maciejgrzybek** [comment]
Can you provide steps to reproduce, please? Is it for explain or regular select on table partitioned by TS column? What version do you run?

**Comment by maciejgrzybek** [comment]
I tried many operations on timestamp-partitioned table (created in Hive using DDL):
```sql
hive> create table ts_partitioned (a int) partitioned by(ts timestamp);
```
1. simple select:
```sql
select * from hive.default.ts_partitioned;
 a |           ts
---+-------------------------
 1 | 1970-01-01 06:23:16.305
(1 row)
```
2. explain (presuming it could have something to do with https://github.com/prestodb/presto/issues/8329):
```sql
explain select * from hive.default.ts_partitioned;
                                                                        Query Plan
--------------------------------------------------------------------------------
 - Output[a, ts] => [a:integer, ts:timestamp]
```
3. describe:
```sql
desc hive.default.ts_partitioned;
 Column |   Type    |     Extra     | Comment
--------+-----------+---------------+---------
 a      | integer   |               |
 ts     | timestamp | partition key |
(2 rows)
```
4. query `information_schema.columns`:
```sql
select * from hive.information_schema.columns;
...
Query 20170815_143707_00014_fdd42, FINISHED, 1 node
```
5. query `information_schema.tables`:
```sql
select * from hive.information_schema.tables;
...
Query 20170815_143801_00015_fdd42, FINISHED, 1 node
```

All of them works fine on both master (HEAD = 25e988287f61845c0519e236fb08fad62e9f05c2) and on 179t release candidate.

Please provide more details, so we could reproduce this issue.

**Comment by subway1211** [comment]
[root@localhost bin]# ./presto 
presto> show partitions from hive.default.qs_table;

Query 20170815_173231_00000_4jhkb, FAILED, 1 node
Splits: 50 total, 0 done (0.00%)
0:03 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20170815_173231_00000_4jhkb failed: cannot convert MethodHandle(ConnectorSession,long)Slice to (Object)Object

presto> explain show partitions from hive.default.qs_table;
                                                                                                                                                              
--------------------------------------------------------------------------------------------------------------------------------------------------------------
 - Output[yr, dt] => [max:varchar, max_3:timestamp]                                                                                                           
         yr := max                                                                                                                                            
         dt := max_3                                                                                                                                          
     - Project[] => [max:varchar, max_3:timestamp]                                                                                                            
         - Sort[partition_number ASC_NULLS_LAST] => [partition_number:bigint, max:varchar, max_3:timestamp]                                                   
             - LocalExchange[SINGLE] () => partition_number:bigint, max:varchar, max_3:timestamp                                                              
                 - RemoteExchange[GATHER] => partition_number:bigint, max:varchar, max_3:timestamp                                                            
                     - Aggregate(FINAL)[partition_number] => [partition_number:bigint, max:varchar, max_3:timestamp]                                          
                             max := "max"("max_21")                                                                                                           
                             max_3 := "max"("max_22")                                                                                                         
                         - LocalExchange[HASH][$hashvalue] ("partition_number") => partition_number:bigint, max_22:bigint, max_21:varbinary, $hashvalue:bigint
                             - RemoteExchange[REPARTITION][$hashvalue_23] => partition_number:bigint, max_22:bigint, max_21:varbinary, $hashvalue_23:bigint   
                                 - Project[] => [partition_number:bigint, max_22:bigint, max_21:varbinary, $hashvalue_24:bigint]                              
                                         $hashvalue_24 := "combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("partition_number"), 0))                  
                                     - Aggregate(PARTIAL)[partition_number] => [partition_number:bigint, max_22:bigint, max_21:varbinary]                     
                                             max_22 := "max"("expr_1")                                                                                        
                                             max_21 := "max"("expr")                                                                                          
                                         - ScanFilterProject[table = $info_schema@hive:hive:information_schema:__internal_partitions__, originalConstraint = (
                                                 expr := CAST((CASE WHEN ("partition_key" = CAST('yr' AS varchar)) THEN "partition_value" END) AS varchar)    
                                                 expr_1 := CAST((CASE WHEN ("partition_key" = CAST('dt' AS varchar)) THEN "partition_value" END) AS timestamp)
                                                 table_schema := table_schema                                                                                 
                                                 table_name := table_name                                                                                     
                                                 partition_number := partition_number                                                                         
                                                 partition_key := partition_key                                                                               
                                                 partition_value := partition_value                                                                           
                                                                                                                                                              
(1 row)

Query 20170815_173239_00001_4jhkb, FINISHED, 1 node
Splits: 1 total, 1 done (100.00%)
0:04 [0 rows, 0B] [0 rows/s, 0B/s]

**Comment by subway1211** [comment]
presto> desc hive.default.qs_table;
 Column  |   Type    |     Extra     | Comment 
---------+-----------+---------------+---------
 id      | integer   |               |         
 content | varchar   |               |         
 yr      | varchar   | partition key |         
 dt      | timestamp | partition key |         
(4 rows)

Query 20170815_173419_00002_4jhkb, FINISHED, 1 node
Splits: 18 total, 18 done (100.00%)
0:00 [4 rows, 285B] [8 rows/s, 639B/s]

**Comment by subway1211** [comment]
works on presto version 0.180

**Comment by findepi** [comment]
related to #8329

**Comment by maciejgrzybek** [comment]
Confirmed, both on master and 179t. Will work on that.

**Comment by subway1211** [comment]
Only problems  with  `show partitions from catalog.schema.table`
