### ISSUE TITLE
Presto workers do not recover with out of heap errors

### ISSUE THREAD

**Issue by zsaltys** [prestodb/presto#8763]
We run presto 0.170 latest on AWS EMR. 30 nodes. Config like this:

cat /etc/presto/conf/config.properties
coordinator=false
node-scheduler.include-coordinator=false
discovery.uri=http://SOMEHOST:8889
http-server.threads.max=500
discovery-server.enabled=false
sink.max-buffer-size=1GB
query.max-memory=150GB
query.max-memory-per-node=51569672323B
query.max-history=40
query.min-expire-age=30m
http-server.http.port=8889
http-server.log.path=/var/log/presto/http-request.log
http-server.log.max-size=67108864B
http-server.log.max-history=5
log.max-size=268435456B
log.max-history=5
experimental.spiller-spill-path=/mnt/tmp/presto/spills

cat /etc/presto/conf/jvm.config
-verbose:class
-server
-Xmx103139344646
-Xmn512M
-XX:+UseConcMarkSweepGC
-XX:+ExplicitGCInvokesConcurrent
-XX:+CMSClassUnloadingEnabled
-XX:+AggressiveOpts
-XX:+HeapDumpOnOutOfMemoryError
-XX:OnOutOfMemoryError=kill -9 %p
-XX:ReservedCodeCacheSize=150M
-Xbootclasspath/p:
-Dhive.config.resources=/etc/hadoop/conf/core-site.xml,/etc/hadoop/conf/hdfs-site.xml
-Djava.library.path=/usr/lib/hadoop/lib/native/:/usr/lib/hadoop-lzo/lib/native/:/usr/lib/

After a query runs for a while it fails with the error: com.facebook.presto.spi.PrestoException: Encountered too many errors talking to a worker node. The node may have crashed or be under too much load. This is probably a transient issue, so please retry your query in a few minutes. (getting task status http://10.99.83.129:8889/v1/task/20170817_135056_00009_wi7j8.2.14 - 29 failures, time since last success 302.37s)

However presto does not recover .. All workers seem to be trying to do something but failing with out of heap exceptions. I'm attaching an example worker node log, stack trace and the params used for the query.

When running the top command I see: 

  4989 root      20   0 5589m 503m 9864 S  0.3  0.4   0:33.09 java
  7956 presto    20   0  106g  98g 9572 S  0.3 82.3 623:13.36 presto-server
     1 root      20   0 19636 2080 1736 S  0.0  0.0   0:01.13 init
     2 root      20   0     0    0    0 S  0.0  0.0   0:00.00 kthreadd
     3 root      20   0     0    0    0 S  0.0  0.0   0:00.04 ksoftirqd/0
     4 root      20   0     0    0    0 S  0.0  0.0   0:00.00 kworker/0:0

It seems something bad happens to presto workers and they cannot recover. Could this be related to resource overcommit?

![screen shot 2017-08-17 at 4 21 15 pm](https://user-images.githubusercontent.com/1583403/29420279-6cb1d932-8369-11e7-97a8-5264522941ad.png)

**Comment by zsaltys** [comment]
Actually I notice that presto workers are recovering .. But It's been over 1 hour and out of 30 nodes only 22 have recovered and there's no queries running on the cluster except the one that made all the workers crash.

**Comment by satybald** [comment]
It might be unrelated but still why you're running CMS garbage collector instead of G1 for 100GB heap?
