### ISSUE TITLE
Max-run-time is enforced using query create time instead of start execution time

### ISSUE THREAD

**Issue by nishantrayan** [prestodb/presto#8780]
I think we should enforce query max run time using its start execution time instead of create time. The query could be stuck in the queue for a while and it would count that time towards the time-before-kill.

https://github.com/prestodb/presto/blob/2ffc0e14b6966d274d09dc735ca3ff069893012b/presto-main/src/main/java/com/facebook/presto/execution/SqlQueryManager.java#L552

**Comment by nezihyigitbasi** [comment]
I confirm this is the case. If a query gets queued too long it can still be killed with the query max runtime limit even though it didn't run at all.
