### ISSUE TITLE
Integrate Glue Data Catalog with Hive connector

### ISSUE THREAD

**Issue by mbeitchman** [prestodb/presto#8786]
I would like to contribute the integration with the Glue Hive Metastore compatible service. 

http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/glue/AWSGlue.html
https://aws.amazon.com/glue/faqs/

Should this be an implementation of the following interface?

https://github.com/prestodb/presto/blob/master/presto-hive/src/main/java/com/facebook/presto/hive/metastore/ExtendedHiveMetastore.java

**Comment by swaranga** [comment]
mbeitchman@ were you able to get this done?

**Comment by mbeitchman** [comment]
@swaranga It's almost done. Should be submitting it soon.

**Comment by mostafazh** [comment]
Would love to see this merged too @mbeitchman ... If anything I can help with, please let me know :smile:

**Comment by dmmiller612** [comment]
@mbeitchman  In the same boat. I can help with anything if you would like to distribute the work.

**Comment by rentaow** [comment]
Next EMR release will have Glue Presto support. In the mean time, I will try to submit a design/pr in the near future.

**Comment by mostafazh** [comment]
As @rentaow promised :+1: http://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-presto.html#emr-presto-glue :tada:

**Comment by rentaow** [comment]
I've linked my doc outlining the proposed changes for contributing this feature. I'd appreciate if I could get some feedback. I will work on submitting a PR if we are on same page with this.

https://docs.google.com/document/d/1Q0GwDsauqzGei_TD5fL4yvwK1knCMtMOvHknut668Co/edit?usp=sharing
https://groups.google.com/forum/#!topic/presto-users/zA93pHYDs7c

**Comment by rentaow** [comment]
Addressed by #9934

**Comment by mbeitchman** [comment]
Awesome work @rentaow ! Let's get a committer to take a look at the PR. Have you sent a message on the slack channel?

**Comment by findepi** [comment]
https://github.com/prestodb/presto/pull/9934 is merged.

**Comment by scraly** [comment]
Have you tested this Glue integration through a Presto deployed outside of a AWS EMR cluster?
Thx

**Comment by findepi** [comment]
@scraly you can use Glue for example with Starburst Presto (https://www.starburstdata.com/presto-aws-cloud/), which is *not* based on AWS EMR.

**Comment by scraly** [comment]
Thanks, I am watching it in some slides right now.
I'll take a look.

**Comment by scraly** [comment]
This starsbust presto version is only if we want deploy a presto in AWS but what about deploying a presto in a kubernetes cluster (in a docker container)?

thanks

**Comment by findepi** [comment]
@scraly that would work too -- just as with any other Presto build. Starburst Presto is in no way limited to AWS.
