### ISSUE TITLE
Release Pain Points (tracking)

### ISSUE THREAD

**Issue by haozhun** [prestodb/presto#8790]
Flaky tests we encountered on mac:
#8787: Flaky Test in TestDistributedSpilledQueries @ArturGajowy @losipiuk 
#8788: Flaky test TestCassandraTokenSplitManager @arhimondr @cawallin 

Full-ci failures:
#8776: Flaky test TestHiveClient.testGetTableStatsBucketedStringInt @alandpost @kokosing 

This is not a flaky test. But we're considering running release on our linux servers and we can't because of this issue:
#8789: AccumuloQueryRunner doesn't work on IPv6-only Linux @adamjshook

**Comment by findepi** [comment]
@haozhun it the intention is to track flaky tests in one place, you can add #8914 & #8953 to the list.

**Comment by raghavsethi** [comment]
Closing, since this appears to be outdated.
