### ISSUE TITLE
Fix EffectivePredicateExtractor to return actual predicates

### ISSUE THREAD

**Issue by sopel39** [prestodb/presto#8797]
Currently EPE returns predicates for projections that don't account for null, e.g: for `Project a := b`, EPE returns `a = b` (instead of `a=b or a is null`). This causes various problems (e.g: see https://github.com/prestodb/presto/commit/c18dd0b) and makes the logic tricky and delicate.

EPE is used along with `EqualityInference` which produces predicates based on EPE results. Since EPE doesn't really produce predicates (but rather equivalence classes for projections) `EqualityInference` conclusions are based on wrong assumptions.

The proposal is to fix `EPE` and append `or is null` for predicates that are derived from projections (and that can return null). This would remove need to https://github.com/prestodb/presto/commit/c18dd0b, which seems like a workaround for EPE issue.

What do you think @martint ?

FYI: @findepi @rschlussel 

Related to  https://github.com/prestodb/presto/issues/8796 since it touches same code.

**Comment by rschlussel** [comment]
1. the predicate should be`a=b or a is null and b is null`
2. I tried doing this once, and it caused some problem because of EPE being used both for deriving equivalences and for producing predicates.  Unfortunately I don't remember what didn't work about it, but my conclusion was to do it right we'd need to separate the two features.

**Comment by sopel39** [comment]
Interesting, did it cause test failures?

**Comment by sopel39** [comment]
Another approach would be to make `EqualityInference` produce actual predicates based on equivalences (e.g: `a = b or (a is null and b is null)` and just call EPE an equivalence extractor

**Comment by rschlussel** [comment]
I believe there were failures, but i don't remember with certainty.  I think the problem maybe related to visitProject().  I should have made a note somewhere with my findings.

**Comment by sopel39** [comment]
Also, I wonder if https://github.com/prestodb/presto/commit/c18dd0b doesn't support more cases since it only checks if function can return null on non null input? Therefore it can correctly support predicates that are derived from projections.
