### ISSUE TITLE
Rewrite `a=a` to `a is not null` in top level where predicates

### ISSUE THREAD

**Issue by sopel39** [prestodb/presto#8806]
TPC-DS Q78 has predicates like:
```
...
LEFT JOIN cs ON ("cs_sold_year" = "ss_sold_year")
   AND ("cs_item_sk" = "cs_item_sk")
   AND ("cs_customer_sk" = "ss_customer_sk"))
...
```
Rewriting `"cs_item_sk" = "cs_item_sk"` to `is not null` might improve performance since no actual comparison is required and not null predicate can be pushed down to connector

FYI: @findepi

**Comment by electrum** [comment]
This won't be correct for float/double (NaN) or other types that have weird equality.

**Comment by kokosing** [comment]
In regards to standard of SQL, is there anything like NaN there defined? If so then I would expect syntax to support things like `a IS NAN`. Maybe there is also a definition how such types are compared, is it exact with Java? Then maybe we could replace that with something equivalent to `a IS NOT NULL AND a IS NOT NAN` (which is even stricter).

I noticed that Oracle have such expressions, see http://www.java2s.com/Tutorial/Oracle/0040__Query-Select/UseISNANoperator.htm. While Teradata or Sqlserver has ISNUMERIC function which has a bit different semantic, but I saw people to overuse that function to achieve the above.

**Comment by martint** [comment]
No, floating point numbers with IEEE754 semantics don't exist in the spec. It only talks about approximate numeric types, but most details are left to the implementers.

**Comment by kokosing** [comment]
Does it make this rewrite to be correct then? It seems that this depends on the semantic/convention we have internally for float number comparisons.  As I understand we follow IEEE754 (or Java). Then maybe we need to have some scalar functions like `isNan(float)` or `isNaN(double)`?

**Comment by sopel39** [comment]
I don't think this rewrite is worth it then. It's benefits are negligible (I think predicates like `cs_item_sk" = "cs_item_sk` are rarely a case in real world), but it opens a pandora box by touching type equality semantics. I would close it for now.

**Comment by electrum** [comment]
We have this: https://prestodb.io/docs/current/functions/math.html#is_nan
