### ISSUE TITLE
Add hamming_distance function between two VARCHARs

### ISSUE THREAD

**Issue by haozhun** [prestodb/presto#8812]

**Comment by lvijay** [comment]
@haozhun, I'm curious.  Do you have a reference for this?  isn't XOR the same?  and iirc there's a `levenshtein` strings.

**Comment by haozhun** [comment]
You can see how hamming_distance for strings are defined on [wikipedia]( https://en.wikipedia.org/wiki/Hamming_distance)

**Comment by satybald** [comment]
I'm really curious why this feature is needed? @haozhun

**Comment by lvijay** [comment]
Also, will this align arguments left or align right?  is `hamming_distance('croak', 'oak')` 2 or 5
