### ISSUE TITLE
ORDER BY list in window function OVER is mishandled

### ISSUE THREAD

**Issue by crvv** [prestodb/presto#8816]
SQL:
```
WITH data(x) AS (SELECT 1 UNION SELECT 2 UNION SELECT 3)
SELECT x, row_number() OVER(ORDER BY x ASC, x DESC) AS id FROM data
```
Presto 0.182:

| x | id |
| -- | -- |
| 3 | 1 |
| 2 | 2 |
| 1 | 3 |

PostgreSQL:

| x | id |
| -- | -- |
| 1 | 1 |
| 2 | 2 |
| 3 | 3 |

**Comment by maciejgrzybek** [comment]
What happens here, most likely, is Presto overriding the value of orderings in the map when two entries in the order-by clause have the same symbol.
Then, the last seen is stored in the map.
The question is whether we should throw an exception, making user aware that he's trying to do something strange, or ignore the second occurrence of the same symbol, as Postgres does.
