### ISSUE TITLE
Issue with UDF that takes a ROW type

### ISSUE THREAD

**Issue by usmanm** [prestodb/presto#8823]
Hey guys, I've trying to write a UDF that takes in a `ROW` type, but the query just seems to fail. I tried to attach a debugger, and the UDF handler function doesn't even get called. 

Source code:
```
    @Description("Return account name")
    @ScalarFunction("account_name")
    @SqlType(StandardTypes.VARCHAR)
    public static Slice accountName(@SqlType(StandardTypes.ROW) Slice account) {
        return Slices.utf8Slice("hello");
    }
```

Out:
```
presto> SELECT account_name('a');
Query 20170823_182853_00000_35grs failed: null

presto> SELECT account_name(ROW(1, 2));
Query 20170823_182902_00001_35grs failed: null

presto> SELECT account_name(CAST(ROW(1, 2) AS ROW(x INT, y INT)));
Query 20170823_183154_00003_35grs failed: null
```

I can't seem to find any documentation around UDFs that take in complex types. Any idea what I might be doing wrong?

**Comment by findepi** [comment]
@usmanm `row` is represented at run-time as `Block` (not `Slice` as in your code). See for example `RowEqualOperator` for UDF operating on rows.

If you want to get a more meaningful exception from CLI, run in with `--debug`.

Also, user list is a better place for this kind of problem solving. It is easier to get help there.
