### ISSUE TITLE
Incorrect result for array_min/max of doubles containing NaN

### ISSUE THREAD

**Issue by martint** [prestodb/presto#8836]
`array_min(array[1, 2, nan()])` => `1`
`array_min(array[nan(), 1, 2])` => `NaN`

This probably occurs because the array_min function interprets `false` when comparing with NaN incorrectly.

The function should return `NaN` if any of the elements is `NaN` (similar to how NULLs are treated).

**Comment by findepi** [comment]
Same for `min`, `max` aggregations:
```
select max(a) from (values nan(), 1.0) t(a); -- NaN
select max(a) from (values 1.0, nan()) t(a); -- 1.0
```
