### ISSUE TITLE
presto-cli: csv output without quotes

### ISSUE THREAD

**Issue by shigemk2** [prestodb/presto#8845]
When using presto-cli with csv output option, it results data with double quotes.

```sh
$ presto --server example:8889 --catalog hive --schema default --file sample.sql --output-format CSV
"1000","mix","test"
"1","mix2","fs"
"2","mix3","test"
"33","fromscratch","mi"
"333","bdash","aaa"
```

But I need csv results without double quotes. 

```sh
$ presto --server example:8889 --catalog hive --schema default --file sample.sql --output-format CSV
1000,mix,test
1,mix2,fs
2,mix3,test
33,fromscratch,mi
333,bdash,aaa
```

According to RFC 4180, field data may or may not be enclosed in double quotes. https://tools.ietf.org/html/rfc4180

So, I need to create new output-format options.

- CSV(default output-format option)
- CSV_HEADER
- **CSV_WITHOUT_QUOTES**
- **CSV_HEADER_WITHOUT_QUOTES**

**Comment by amarcum** [comment]
+1
I am also looking for this functionality in a file export that I am doing.

**Comment by zsaltys** [comment]
+1

**Comment by leoChaoGlut** [comment]
Solution as follow:

1. `com.facebook.presto.cli.Query.createOutputPrinter(OutputFormat format, Writer writer, List<String>`
2. `au.com.bytecode.opencsv.CSVWriter.CSVWriter(Writer writer, char separator)`
3. `au.com.bytecode.opencsv.CSVWriter.writeNext(String[] nextLine)`

**Comment by ebyhr** [comment]
Implemented as an experiment. I will send PR later. 

```
ebyhr:presto ebyhr$ presto-cli/target/presto-cli-0.197-SNAPSHOT-executable.jar -f select.txt --output-format CSV_WITHOUT_QUOTES
1,1,1
ebyhr:presto ebyhr$ 
ebyhr:presto ebyhr$ presto-cli/target/presto-cli-0.197-SNAPSHOT-executable.jar -f select.txt --output-format CSV_HEADER_WITHOUT_QUOTES
c1,c2,c3
1,1,1
```

**Comment by ebyhr** [comment]
The PR was merged into https://github.com/prestosql/presto/pull/319
The new option names are `CSV_UNQUOTED` and `CSV_HEADER_UNQUOTED`. It will be release on version 305.
