### ISSUE TITLE
Release notes for Presto 0.184

### ISSUE THREAD

**Issue by raghavsethi** [prestodb/presto#8871]
## Christina Wallin     
- [x]  08-23 10:36:56    d7bd920c8a Use ReopeningCluster in EmbeddedCassandra
- [x]  08-23 10:36:56    f1bfb2fdee Sleep between statistics refresh in EmbeddedCassandra
- [x]  08-29 10:34:35    609ca63dbf Process pending reads upon noMorePages event
## David Phillips       
- [x]  08-21 13:48:31    3c24cefd30 Fix 'Cannot cast' wording
- [x]  08-21 13:50:26    3c89137611 Remove JSON serialization from metastore Action
- [x]  08-23 07:33:11    a7e07d1a84 Set alwaysRun = true on all @AfterClass
- [x]  08-23 07:36:15    3ba8f8d27f Create build directory for presto-docs
- [x]  08-23 08:01:53    96ed6a160e Provide final stats in JDBC progress callback
- [x]  08-23 08:02:45    430466d04c Use automatic width for tables in documentation
- [x]  08-23 10:52:26    32b66fff83 Require coalesce to have at least two arguments
- [x]  08-23 10:52:26    74d1b62b4c Add line separators in visitFunctionCall in AstBuilder
- [x]  08-23 10:59:19    5bc9087c74 Fix error categorization in local file connector
- [x]  08-23 11:05:28    520c4762fc Remove AssertJ dependency which is now in Airbase
- [x]  08-23 11:06:16    f310084854 Remove unused provider file for TPCH plugin
- [x]  08-23 11:15:45    66f9e9faf1 Remove obsolete test files for old Hive versions
- [x]  08-23 12:46:13    c816fbb87d Extract duplicate testing session in SPI tests
- [x]  08-23 12:57:09    aeb415b210 Add source to ConnectorSession
- [x]  08-23 13:14:10    3d7969f8f2 Add additional context information to HdfsEnvironment
- [x]  08-25 09:08:19    a89a95a472 Allow overriding verifier database connection acquisition
- [x]  08-28 14:25:38    708f5f6b95 Use TupleDomain.all() in the blackhole TableLayout
## German Gil           
- [x]  08-21 09:13:49    dd60f3ea04 Add queued query statistics Adding the number of queued queries at any given point, this is similar to the number of running queries. Also adding the queued time.
## Grzegorz Kokosiński 
- [x]   08-22 01:42:05    0f4aab5ec9 Move TPCDS tiny statistics data to proper directory
- [x]   08-22 01:42:05    1a2b2f6faa Test TPCDS statistics for all supported schemas
- [x]   08-22 01:42:05    41e947e643 Fix range fraction calculation in TPC-DS stats
- [x]   08-22 01:42:05    9b40bd7720 Remove unused parameter
- [x]   08-22 01:42:05    9ba6eaf1a8 Return TPCDS statistics values in Presto internal representation
- [x]   08-22 01:42:05    f62bcd1f22 Make TPCDS schema scale parsing coherent with TPCH
- [x]   08-22 22:11:04    da5ea7d142 Make ExpressionRewriteRules static and public
- [x]   08-22 22:11:04    fb88087ced Rename ExpressionRewriteRule to ExpressionRewriter
- [x]   08-25 00:19:28    e759a4afca Run PruneCountAggregationOverScalar only for single output default aggregation
- [x]   08-25 00:33:33    4dbf0b9b8f Remove Cassandra from docker compose other than singlenode and multinode
- [x]   08-25 00:33:33    7275d594c4 Run Cassandra only in singlenode and multinode environments
- [x]   08-25 00:33:33    eee30aeda0 Initialize CassandraSession lazily
- [x]   08-28 06:12:43    285aa96af1 Remove unused field in SpillableHashAggregationBuilder
- [x]   08-28 06:12:43    ce39f59e6c Make sure everything gets closed in SpillableHashAggregationBuilder
- [x]   08-28 21:38:37    54aa42128e Make resolveGroup accept only GroupReference
## Haozhun Jin          
- [x]  08-21 12:02:01    f4b969328c Improve error message for functions involving TypedSet
- [x]  08-22 11:09:23    c3719f1d97 Remove redundant field from AbstractSingleMapBlock
- [x]  08-22 11:10:16    f0da07d486 Fix split_to_map function to produce map block
- [x]  08-22 15:49:04    4cb8337067 Fix tests that produce legacy block for maps
- [x]  08-24 15:35:04    b270c7233f Add support for zero-argument lambda expression
- [x]  08-24 15:40:07    3e31629dda Improve map element_at performance by utilizing MapBlock O(1) access
## James Sun            
- [x]  08-19 23:00:02    2dc00ed5e3 Move CursorProcessor to project package
- [x]  08-19 23:00:02    ac8cf11d08 Wire scheduled executor in driver context
- [x]  08-19 23:00:02    e13a99d10e Introduce yield signals to operators
- [x]  08-19 23:00:02    ed9af44c99 Remove deprecated getExecutor in driver context
- [x]  08-24 13:14:56    4efb7c28ba Add yield signals to page processors
- [x]  08-24 13:14:56    b9b731fe71 Use the whole previouslyComputedResults in page processor
- [x]  08-24 15:50:11    b9736752f7 Add Hamming distance function between two VARCHARs
- [x]  08-25 17:08:18    b25c452c62 Use VariableWidthBlock when reading blocks with slice direct reader
- [x]  08-25 17:08:18    cfe4a7e631 Add methods for getting truncated char/varchar lengths with offsets
## Karol Sobczak        
- [ ]  08-28 05:20:27    40f7aa9f6d Lookup.resolveGroup returns a Stream instead of List
## Leiqing Cai          
- [x]  08-20 15:04:39    0e0aec7c8a Move formatting logic in Unnest.toString() into SqlFormatter
- [x]  08-21 12:20:49    fbc26e5893 Fix Unnest.equals() by comparing field withOrdinality
- [x]  08-28 15:17:21    a004dfc3d3 Rename grammar nodes tableProperty and tableProperties
## Martin Traverso      
- [ ]  08-21 10:41:59    1bd2e8f66a Remove obsolete 'racy' comments
- [ ]  08-21 10:41:59    d79d8da2ff Fix theoretical race condition in getSizeInBytes()
- [ ]  08-21 10:42:50    007471c129 Add configuration option to disable table statistics
## Nezih Yigitbasi      
- [ ]  08-20 12:16:48    995b913488 Prune QueryStats when pruning QueryInfo
- [ ]  08-20 12:17:32    3d92f0e753 Track output buffer memory usage in the task context
## Raghav Sethi         
- [x]  08-24 12:34:31    c22b7e1977 Add lookupSourcePositions to JoinOperatorInfo
## Wenlei Xie           
- [x]  08-21 18:21:03    6dc5d4f5d7 Minor refactor in TestSliceArrayBlock
- [x]  08-21 18:21:03    ca61b15db2 Minor fix to DictionaryBlock memory accounting
- [x]  08-25 22:14:57    227e1ffd7f Remove unused method in MongoPageSource
- [x]  08-25 22:14:57    c364cd7345 Migrate to new RowBlock
- [x]  08-25 22:14:57    e41d4030cc Add RowBlock for row type
- [x]  08-25 22:14:57    f5fad18176 Minor refactor in RowToRowCast bytecode generation
## Łukasz Osipiuk      
- [x]   08-21 00:02:19    7697dfe790 Fix PageBuilder use in benchmark binary file spiller
- [x]   08-24 06:50:30    be5b0f7e64 Remove explicit generic type arguments
- [x]   08-24 06:50:30    d33b8265df Remove unused properties from TestQuerySpillLimits
- [x]   08-24 06:50:30    f725b8e717 Remove unused configuration from TestQuerySpillLimits
- [x]   08-24 08:07:09    1bcf5fd6a1 Strengthen verifications in join yield test
- [x]   08-24 08:07:09    661fc1db77 Change test to allow operator produce final output with delay
- [x]   08-24 08:07:09    f7d857b3d8 Fix input handling in LJO yield test
- [x]   08-28 00:14:49    93e0b47287 Fix partition filtering for various types
- [x]   08-29 00:36:32    4f6aa5813b Allow max-memory-per-node to be exactly (xmx - reservedMemory)

**Comment by highker** [comment]
General Changes:
- Prevent a query that contains ``CROSS JOIN`` from not releasing CPU resource or keeping running after it has been killed.
- Add :func:`hamming_distance` function.



Hive Changes:
- Reduce system memory usage when reading table columns containing string values from ORC or DWRF files. This can prevent high GC overhead or out-of-memory crash.

**Comment by wenleix** [comment]
No user visible changes.

**Comment by haozhun** [comment]
General

```
* Fix query failure for ``split_to_map(...)[...]``.
* Improve performance of :func:`element_at` for maps from O(n) to O(1).
  Map subscript has been like this since 0.180.
```

**Comment by kokosing** [comment]
General

```
 * Aggregation queries with ``count(*)`` and non empty ``GROUP BY`` clause were incorrectly statically evaluated. This was fixed and now this optimization only works for queries with an empty `GROUP BY` clause only.
```

Tpcds

```
 * Fix statistics retrieval for ``TPCDS``  tables when using ``SHOW STATS FOR ...``
```

**Comment by cawallin** [comment]
General
```
* Improve performance of ``GATHER`` exchange in some cases.
```

**Comment by losipiuk** [comment]
```
Hive
-----

* Fix partition filtering which was broken when partition keys used CHAR, DECIMAL, or DATE datatype.
```

**Comment by ggilfb** [comment]
```
General
-----

* Add number queued queries and queued time to the query manager statistics.
```

**Comment by raghavsethi** [comment]
@kokosing re:
'Aggregation queries with ``count(*)`` and non empty ``GROUP BY`` clause were 
   incorrectly statically evaluated. This was fixed and now this optimization only works 
   for queries with an empty `GROUP BY` clause only.'

What would happen when they were incorrectly statically evaluated?

**Comment by kokosing** [comment]
Query was aborted with planning error.

**Comment by raghavsethi** [comment]
@kokosing: On TPC-DS, was it just that the null fraction stat was wrong?
