### ISSUE TITLE
Functions for char/varbinary

### ISSUE THREAD

**Issue by haozhun** [prestodb/presto#8876]
| Function name              | varchar       | char           | varbinary       |
| -------------------------- | ------------- | -------------- | --------------- |
| chr                        | implemented   | conflict       | not applicable  |
| codepoint                  | implemented   | [ ]            | not applicable  |
| concat                     | implemented   | [ ]            | implemented     |
| length                     | implemented   | implemented    | implemented     |
| levenshtein distance       | implemented   | [ ]            | [ ]             |
| hamming distance           | implemented   | [ ]            | [ ]             |
| lower                      | implemented   | implemented    | not applicable  |
| lpad                       | implemented   | ?              | [ ]             |
| ltrim                      | implemented   | implemented    | [ ] 2-arg only? |
| replace                    | implemented   | [ ]            | [ ]             |
| reverse                    | implemented   | [ ]            | [ ]             |
| rpad                       | implemented   | ?              | [ ]             |
| rtrim                      | implemented   | implemented    | [ ] 2-arg only? |
| split                      | implemented   | [ ]            | [ ]             |
| split_part                 | implemented   | [ ]            | [ ]             |
| split_to_map               | implemented   | [ ]            | [ ]             |
| strpos/position            | implemented   | [ ]            | [ ]             |
| substr                     | implemented   | implemented    | [ ]             |
| trim                       | implemented   | implemented    | [ ] 2-arg only? |
| upper                      | implemented   | implemented    | not applicable  |

**Comment by haozhun** [comment]
@electrum How should documentation be organized for these functions?

**Comment by dain** [comment]
* I don't think `chr` should be on this list since it doesn't have a string parameter.
* the pad functions seem ok for `char` but rpad of space would be a noop
* I haven't seen the 3-arg version of the trim functions, but I could imagine that someone would want to remove specific bytes

**Comment by electrum** [comment]
We could probably change "chr" to return char(1). It would have if the type existed in the beginning.
