### ISSUE TITLE
Use broadcast join for non-equality joins

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#8892]
When a join would end up on a single machine, we should optimize it to a broadcast join. This happens for the below query for an inner join, but not a left join.

```sql
SELECT orderkey
FROM orders o
LEFT JOIN customer c ON o.shippriority BETWEEN c.custkey AND c.nationkey;

**Comment by rschlussel2** [comment]
Should be fixed by https://github.com/prestodb/presto/pull/9747/commits/252481ce9917e946e14218f69c89b8970ce173d4 (in the iterative optimizer only)
