### ISSUE TITLE
Set cache-control properly on static resources

### ISSUE THREAD

**Issue by raghavsethi** [prestodb/presto#8895]
Setting cache control could speed up the loading of large files like `browser.min.js` and therefore make the Web UI a lot snappier.

**Comment by manubhats** [comment]
@raghavsethi  Can you or someone assign this to me? I am not seeing an option to self-assign.

**Comment by raghavsethi** [comment]
I can't assign it to you either - will assign it to myself to take it out of rotation, but it's all yours.
