### ISSUE TITLE
Add option to partition Hive writes on partition keys

### ISSUE THREAD

**Issue by dain** [prestodb/presto#8901]
Some queries need to write thousands of partitions, and in that case the partitions should be distributed across the workers instead of having all workers write all partitions.  This should be controllable via a session property that when set changes the InsertLayout and CreateTableLayout in `HiveMetadata` to declare a partitioning.

**Comment by findepi** [comment]
For ETL-style queries, you need to bump several safely valves (and so -- going unsage) to get the query pass.
