### ISSUE TITLE
Use hardlinks/symlinks in tarball to reduce size by 70%

### ISSUE THREAD

**Issue by edmorley** [prestodb/presto#8904]
The tarball currently contains many duplicated files, which bloat the filesize considerably, making Docker images based on it much larger than necessary.

Replacing these with hardlinks (using [rdfind](https://rdfind.pauldreik.se/)) reduces the disk usage by ~70%:

```bash
$ mkdir /tmp/presto
$ curl https://repo1.maven.org/maven2/com/facebook/presto/presto-server/0.183/presto-server-0.183.tar.gz | tar -zxC /tmp/presto/
...
$ du -hs /tmp/presto/
484M    /tmp/presto/

$ rdfind -makehardlinks true /tmp/presto/
Now scanning "/tmp/presto", found 865 files.
Now have 865 files in total.
Removed 0 files due to nonunique device and inode.
Now removing files with zero size from list...removed 0 files
Total size is 505366109 bytes or 482 Mib
Now sorting on size:removed 186 files due to unique sizes from list.679 files left.
Now eliminating candidates based on first bytes:removed 0 files from list.679 files left.
Now eliminating candidates based on last bytes:removed 0 files from list.679 files left.
Now eliminating candidates based on md5 checksum:removed 0 files from list.679 files left.
It seems like you have 679 files that are not unique
Totally, 327 Mib can be reduced.
Now making results file results.txt
Now making hard links.
Making 610 links.

$ du -hs /tmp/presto/
156M    /tmp/presto/
```

I don't know whether hardlinks or symlinks would be preferable, but it would be great to fix this upstream either way, to avoid having to do so in downstream docker images.

(There's also #6380 filed, but it's about the RPM specifically)

**Comment by electrum** [comment]
I just noticed that the unpacked tarball disk usage is substantially larger (~12%) than the tarball size. This is surprising since almost all files are jars (zip files) which shouldn't compress at all. I wonder of gzip is able to compress the contents of duplicate files? I didn't think it could look that far ahead.

**Comment by electrum** [comment]
@dain just pointed out that zip file entries are compressed individually, since each is directly accessible, so when you compress the entire zip file you can compress across entries.
