### ISSUE TITLE
get table from prosto sql

### ISSUE THREAD

**Issue by niceczj** [prestodb/presto#8910]
how use prosto-parser to get the tables in a query sql?
a query sql has too many formats，how can i parser it correct?

**Comment by electrum** [comment]
You can do something like this:
```java
SqlParser parser = new SqlParser();
Statement statement = parser.createStatement("SELECT * FROM orders");

new DefaultTraversalVisitor<Void, Void>()
{
    @Override
    protected Void visitTable(Table node, Void context)
    {
        System.out.println(node.getName());
        return null;
    }
}.process(statement, null);
```
But note that analyzing SQL correctly is quite difficult. For example, you could have an unqualified table `orders`, or a fully qualified one `tpch.tiny.orders`.
