### ISSUE TITLE
hive.parquet.use-column-names should default to true

### ISSUE THREAD

**Issue by mfeteanu-dni** [prestodb/presto#8911]
We have experienced issues recently with schema evolution using parquet files.

By default presto will use column indexes to access data in parquet files. This means that when you add columns to the metadata but not in the underlying parquet files (imagine the common case where you only add them to new files), any of the following can happen, depending on the order and type of columns:
- a hard to interpret error (null pointer exception, or some json message)
- garbage data in the new column (if it's a confusion between compatible type columns)
- wrong data (columns are "offset" if all are string for example).

The only possible benefit for having the hive.parquet.use-column-names setting default to false is a possible increase in speed (not checking the file metadata to figure out where the columns is).

Unless we can have an explicit failure mode I think the setting should default to the safer value (true). By explicit failure mode I mean that if the file has different columns from the schema then failure should be immediate and clear from the error message (although I guess then there will be no speed advantage anymore?).

Thoughts?

**Comment by electrum** [comment]
What does Hive do by default (Apache, Cloudera, Hortonworks)? Our intention is to match Hive's behavior.

**Comment by electrum** [comment]
Using the wrong setting can result in incorrect results in either scenario. For example:

* With named, if you swap two column names in the metastore (perhaps indirectly by removing and adding a column), and the columns have the same type.
* With positional, if you write columns of the same type in different order.

So we definitely want to do the right thing by default, but the question is, which one is right?

**Comment by mfeteanu-dni** [comment]
We tested this on a cluster where the different systems shared the metastore and loaded the data from the same parquet files (basically EMR):
- in Spark it works fine if we set spark.sql.parquet.mergeSchema to true. This does make declaring the data frame noticeably slower, I assume because all metadata files are checked. More important is that when it fails (if the option is not set), it fails noisily and clearly (does not return wrong data).
- In Hive everything works fine without any extra options. I was not able to test what the option is to use indexes instead of names. It seems to be parquet.column.index.access, but I did not test. This suggests that the default is to use names, see patch 3: https://issues.apache.org/jira/browse/HIVE-7800.

As for your examples, I think the case of adding columns (at the end or in the middle) is more common than columns types changing, at least in my experience. It is also more natural to assume that data would have to be re-processed on changing data types than on column addition. But these are more opinions from personal experience than technical arguments.

**Comment by kgalieva** [comment]
@electrum I totally agree with @mfeteanu-dni. Column indexes work fine only when both table definition in  metastore and parquet schema match exactly, or when there are only additions to the end of a schema. Whereas when column names are used there are no problems with schema evolution. 
Here are three cases, that work when `hive.parquet.use-column-names = true` and break with the default `hive.parquet.use-column-names = false`:
- column is added to a schema in metastore, but not exists in a parquet file
- column is added to parquet file, but not exists in a schema in metastore
- columns order in a schema in metastore doesn't match with an order in a parquet file

**Comment by piyushnarang** [comment]
We're running into a variant of this problem when we try to read data in Presto that was written to a partitioned table using Spark-SQL(using `spark.sql.parquet.writeLegacyFormat=true`). It seems to be that Spark-SQL's parquet writer is including the partition fields in the beginning of the file and hence parquet file schema. The Hive table definition that Presto is basing its's column indexes off though seems to list the partition columns at the end of the list. 

Thus, any attempts to read these tables with `hive.parquet.use-column-names = false` results in errors as the indexes mismatch and the field types do as well. This seems to fall into @kgalieva 's category 3. Setting use-column-names = true seems to work.

**Comment by findepi** [comment]
> What does Hive do by default (Apache, Cloudera, Hortonworks)? Our intention is to match Hive's behavior.

@kgalieva do you happen to know the answer to @electrum's question?
