### ISSUE TITLE
[0.133] Deadlocks on worker node

### ISSUE THREAD

**Issue by guangyy** [prestodb/presto#8927]
Hello there,
We are running an old version of Presto, 0.133, from time to time, the cluster gets into a state that some worker would not response, jstack shows it is a deadlock issue:

>  Found one Java-level deadlock:
>  =============================
>  "Task-20170905_164816_67612_d3r9x.14.19-118770":
>    waiting to lock monitor 0x00007fbbcf556e58 (object 0x00007f8c8ebd80b8, a com.facebook.presto.operator.ExchangeClient),
>    which is held by "Task-20170905_164816_67612_d3r9x.14.19-118696"
>  "Task-20170905_164816_67612_d3r9x.14.19-118696":
>    waiting to lock monitor 0x00007fbbcd53eaf8 (object 0x00007f8c8f2cb7a0, a com.facebook.presto.operator.HttpPageBufferClient),
>    which is held by "exchange-client-4"
>  "exchange-client-4":
>    waiting to lock monitor 0x00007fbbcf556e58 (object 0x00007f8c8ebd80b8, a com.facebook.presto.operator.ExchangeClient),
>    which is held by "Task-20170905_164816_67612_d3r9x.14.19-118696"

Before I spend time doing further investigation, just would like to check if this is a known issue and has been fixed in later version? Thanks!

**Comment by dain** [comment]
Version 0.133 was released on Jan 15, 2016.  I have a memory of fixing a bug like this in that code, but couldn't tell you when.  Please, update to a recent release, and if it reoccurs, open a new issue.
