### ISSUE TITLE
Allow to override s3 filesystem class

### ISSUE THREAD

**Issue by zsaltys** [prestodb/presto#8936]
This is not necessarily an issue report but more of a question to presto devs. We would like to be able to override via hive catalog config the s3 filesystem class so we can inject instead the amazon EMRFS file system implementation and get presto to work with EMRFS. We wanted to ask if such a patch would be considered a good idea and would be accepted for merging?

The proposal would be to let modify hive catalog config with a param like this:

hive.s3class=com.aws.foo.bar.EmrfsFileSystem

Thank you

**Comment by rentaow** [comment]
There was a previous PR #5940 for this same use case that was rejected because Presto community did not want configs that had class name in the config values. 

I'm also curious to what community think about adding a config to use EmrFS specifically.

**Comment by electrum** [comment]
Please try this out: https://github.com/prestodb/presto/pull/8938

**Comment by rentaow** [comment]
Awesome, thanks for the link electrum

**Comment by zsaltys** [comment]
@electrum thanks for the response. closing this.
