### ISSUE TITLE
Union query on with limit not planned correctly

### ISSUE THREAD

**Issue by amarwah** [prestodb/presto#8957]
I have a union query with a limit (using a view) which runs for a while and hits the per-node memory limit. The query completes quickly if I run the limit query on either side of the union query individually.

**Comment by findepi** [comment]
@amarwah could you possible share original query (the one that fails) and the one working ones, along with `explain analyze` output? Or even better, of the original query is complex, try to simplify it first before sharing.

**Comment by amarwah** [comment]
Failing query:
presto:default> select * from xxx (view over a simple union) where date = current_date and customer = 'yyy' limit 10;

Query 20170912_202828_00593_xzb4w, FAILED, 8 nodes
Splits: 900 total, 463 done (51.44%)
2:49 [11.6M rows, 1.63GB] [68.5K rows/s, 9.89MB/s]

Query 20170912_202828_00593_xzb4w failed: Query exceeded local memory limit of 8GB

Working query:
select * from yyy (underlying table) where date = current_date and customer = 'zzz' limit 10;

**Comment by amarwah** [comment]
presto version: 0.182

**Comment by amarwah** [comment]
Note that both date/customer are partition columns. Still working on trying to get the ginormous explain output presented in a readable form.

**Comment by amarwah** [comment]
Sorry for the unreadable output (note that parts of the explain output is redacted for privacy reasons). The plan seems complex, seems to include repartitioning, the view is just a select * union over two tables which have exactly the same schema:
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 - Output[_col0] => [expr_1989:integer]                                                                                                                                                                                                 
         Cost: {rows: 10, bytes: ?}                                                                                                                                                                                                     
         _col0 := expr_1989                                                                                                                                                                                                             
     - Project[] => [expr_1989:integer]                                                                                                                                                                                                 
             Cost: {rows: 10, bytes: ?}                                                                                                                                                                                                 
             expr_1989 := 1                                                                                                                                                                                                             
         - LocalExchange[ROUND_ROBIN] () =>                                                                                                                                                                                             
                 Cost: {rows: 10, bytes: ?}                                                                                                                                                                                             
             - Limit[10] => []                                                                                                                                                                                                          
                     Cost: {rows: 10, bytes: ?}                                                                                                                                                                                         
                 - LocalExchange[SINGLE] () =>                                                                                                                                                                                          
                         Cost: {rows: 10, bytes: ?}                                                                                                                                                                                     
                     - RemoteExchange[GATHER] =>                                                                                                                                                                                        
                             Cost: {rows: 10, bytes: ?}                                                                                                                                                                                 
                         - LimitPartial[10] => [expr_1105:varchar, expr_1106:varchar, expr_1107:integer, expr_1108:varchar, expr_1109:bigint, expr_1110:varchar, expr_1111:varchar, expr_1112:varchar, expr_1113:varchar, expr_1114:varc
                                 Cost: {rows: 10, bytes: ?}                                                                                                                                                                             
                             - Project[] => [expr_1105:varchar, expr_1106:varchar, expr_1107:integer, expr_1108:varchar, expr_1109:bigint, expr_1110:varchar, expr_1111:varchar, expr_1112:varchar, expr_1113:varchar, expr_1114:varchar
                                 - Aggregate(FINAL)[expr_1105, expr_1106, expr_1107, expr_1108, expr_1109, expr_1110, expr_1111, expr_1112, expr_1113, expr_1114, expr_1115, expr_1116, expr_1117, expr_1118, expr_1119, expr_1120, expr
                                     - LocalExchange[HASH][$hashvalue] ("expr_1105", "expr_1106", "expr_1107", "expr_1108", "expr_1109", "expr_1110", "expr_1111", "expr_1112", "expr_1113", "expr_1114", "expr_1115", "expr_1116", "exp
                                         - Project[] => [expr_1105:varchar, expr_1106:varchar, expr_1107:integer, expr_1108:varchar, expr_1109:bigint, expr_1110:varchar, expr_1111:varchar, expr_1112:varchar, expr_1113:varchar, expr_
                                                 $hashvalue_1995 := "combine_hash"("combine_hash"("combine_hash"("combine_hash"("combine_hash"("combine_hash"("combine_hash"("combine_hash"("combine_hash"("combine_hash"("combine_hash"
                                             - Project[] => [expr_1105:varchar, expr_1106:varchar, expr_1107:integer, expr_1108:varchar, expr_1109:bigint, expr_1110:varchar, expr_1111:varchar, expr_1112:varchar, expr_1113:varchar, 
 - RemoteExchange[REPARTITION][$hashvalue_1993] => 
                                                     - Aggregate(PARTIAL)[
                                                         - ScanProject[table = hive:hive:default:access_logs_v1, originalConstrain
                                                                 date := HiveColumnHandle{clientId=hive, name=date, hiveType=date, hiveColumnIndex=-1, columnType=PARTITION_KEY, comment=Optional.empty}                                
                                                                     :: [[2017-09-12]]                                                                                                                                                  
                                                                 hourofday := HiveColumnHandle{clientId=hive, name=hourofday, hiveType=int, hiveColumnIndex=-1, columnType=PARTITION_KEY, comment=Optional.empty}                       
                                                                     :: [[0], [1], [2], [3], [4], [5], [6], [7]]                                                                                                                        
                                                                 customer := HiveColumnHandle{clientId=hive, name=customer, hiveType=string, hiveColumnIndex=-1, columnType=PARTITION_KEY, comment=Optional.empty}                      
                                                                     :: [[wapo]]                                                                                                                                                        
                                         - Project[] => [expr_1105:varchar, expr_1106:varchar, expr_1107:integer, expr_1108:varchar, expr_1109:bigint, expr_1110:varchar, expr_1111:varchar, expr_1112:varchar, expr_1113:varchar, expr_
                                                 $hashvalue_1998 := "combine_hash"("combine_hash"("combine_hash"("combine_hash"("combine_hash"("combine_hash"("combine_hash"("combine_hash"("combine_hash"("combine_hash"("combine_hash"
                                             - Project[] => [expr_1105:varchar, expr_1106:varchar, 
                                                 - RemoteExchange[REPARTITION][$hashvalue_1996] => 
                                                     - Aggregate(PARTIAL)[customer_name_441, property_442, 
                                                         - ScanProject[table = hive:hive:default:access_logs_v2, originalConstraint = (("date_659" = "$literal$date"(BIGINT '17421')) AND ("customer_661" = CAST('xxx' AS varchar)))] =
                                                                 $hashvalue_1997 := "combine_hash"("combine_hash"("combine_hash"("combine_hash"("combine_hash"("combine_hash"("combine_hash"("combine_hash"("combine_hash"("combine_hash
                                                                 LAYOUT: hive

**Comment by electrum** [comment]
It looks like you used `UNION` vs `UNION ALL`. For former will do a distinct, which can run out of memory since it needs to hold the entire result.

**Comment by amarwah** [comment]
Ah right, I totally missed that, thanks!
