### ISSUE TITLE
flatten nested struct

### ISSUE THREAD

**Issue by lumost** [prestodb/presto#8959]
It's currently possible to flatten nested maps and arrays in presto such as with the following 
```
SELECT student, score
FROM tests
CROSS JOIN UNNEST(scores) AS t (score);
```

but it does not appear possible to flatten nested Structs.  Is it possible to extend the unnest semantics to work with structs?

**Comment by wenleix** [comment]
I believed this is fixed by https://github.com/prestodb/presto/issues/8151 . You can use 

```
SELECT student, score1, score2
FROM tests
CROSS JOIN UNNEST(ARRAY[score_struct]) AS t(score1, score2)
```

Remember to disable session property `legacy_unnest`

**Comment by wenleix** [comment]
I believed this is fixed by https://github.com/prestodb/presto/issues/8151 . You can use 

```
SELECT student, score1, score2
FROM tests
CROSS JOIN UNNEST(ARRAY[score_struct]) AS t(score1, score2)
```

Remember to disable session property `legacy_unnest`
