### ISSUE TITLE
Presto + Views + HDFS

### ISSUE THREAD

**Issue by amarwah** [prestodb/presto#8963]
This is a follow up to another issue I created recently. We have been looking at ways to seamlessly drop deprecated columns for hdfs based presto tables for efficiency and scale out. One way to do this is to use views and use underlying tables with slowly changing schema to migrate users off using deprecated columns (changing the view definition to be a union over underlying versioned tables selecting relevant columns only). Hope you get the picture.

Functionally this works but when we did a beta with our production workload there were many complaints about query slow down. Rolling back the change fixed everything. The queries we run are typically very simple combinations of filtering/aggregation, no joins. It seems as though planning of union queries is not very optimal at this point. Or maybe something is broken wrt planning view based queries specifically. Please provide info on whether this is a known gap, and if so, is it part of the future roadmap.

**Comment by electrum** [comment]
Views are identical to a subquery. During planning, when we encounter a view reference, the view query is inlined, exactly as if it was written as a subquery. You can verify this by doing an `EXPLAIN` of a view vs a subquery.

Did you use `UNION` or `UNION ALL`? A `UNION` does a distinct of the results, which is quite expensive. For your use case, you likely want `UNION ALL` which just concatenates the relations.

**Comment by amarwah** [comment]
Yep, I totally missed that, thanks!
