### ISSUE TITLE
Add submittedQueries counter to SqlQueryManager

### ISSUE THREAD

**Issue by martint** [prestodb/presto#8967]
There's a counter for started and completed queries, but we're missing one that tracks the number of queries submitted to Presto.

**Comment by tsunny** [comment]
Hi Martin, I would be happy to take a look at this. 

I was going through the SQLQueryManager code. And these are my thoughts so far.

I am planning to add counter similar to started and completed in SqlQueryManagerStats to track the number of queries submitted and this counter will be updated in the method createQuery() before or after line 456: queries.put(queryId, queryExecution);

Do you think updating the counter in this place would be good enough or is there any other locations I need to consider as well.

Thanks,
Sunny
