### ISSUE TITLE
calling java procedure using Presto JDBC

### ISSUE THREAD

**Issue by petterpat** [prestodb/presto#8971]
HI,

I  have written one class as POManager.java which having methods contain queries for oracle database through Presto server.

Load this class into oracle data dictionary using Loadjava tool.

Then write package and package body in PlSql to publish  POManager.class.

After call java stored procedure from PlSql block. it execute query from POManager class method.

All above steps properly working with OJDBC and MySql JDBC.

But when we execute with presto  JDBC it throws Runtime exception while loading PrestoDriver class.

 

I followed all above steps from following link.

https://docs.oracle.com/database/121/JJDEV/cheight.htm#JJDEV13305

Thanks in Advance

**Comment by electrum** [comment]
Can you explain more about your setup? Presto does not ship with a connector for Oracle. Are you using a third party connector or one that you wrote yourself?
