### ISSUE TITLE
Ignore SpnegoFilter during inner https(secure) request

### ISSUE THREAD

**Issue by BlueStalker** [prestodb/presto#8973]
Currently the SpnegoFilter will ignore the http request, so there would be problem if the coordinator has been kerberized and also the inner communication is thru https, since SpnegoFilter will always return 401 and all the inner communication https request will fail.

A Potential fix is to add a special header for the inner http request and let SpnegoFilter bypass the Auth check if the header matches.

**Comment by cawallin** [comment]
This PR adds the ability to have Kerberos authentication between Presto nodes: https://github.com/prestodb/presto/pull/8859. That will solve your problem.

**Comment by findepi** [comment]
https://github.com/prestodb/presto/pull/8859 mentioned above was superseded by https://github.com/prestodb/presto/pull/9683. Closing.
