### ISSUE TITLE
GraphQL Endpoint? 

### ISSUE THREAD

**Issue by gowtham-sai** [prestodb/presto#8979]
New future plans to support GraphQL queries directly?

**Comment by gowtham-sai** [comment]
As it so mandy days, just tagging top committer. 

@electrum @dain , any future plan to support GraphQL endpoint ? 
or any alternative is here?

**Comment by martint** [comment]
For management APIs or for query execution?

We might implement it for management APIs at some point, but no concrete plans at this time.

**Comment by gowtham-sai** [comment]
For Query execution.  I dont think we need for management APIs

**Comment by martint** [comment]
What kinds of queries are you thinking of running? I'm not very familiar with the capabilities of GraphQL, but as far as I understand it, it's not designed for the kind of analytic queries Presto can run.

**Comment by gowtham-sai** [comment]
@martint Yep, may be you are correct. GraphQl might not be designed for analytical queries. I can think of the following scenario. Basically in our case, we have user profiling or daily activity. So, we can use GraphQl to extract like all the users who have purchased something, or visited some product or performed particular event.
