### ISSUE TITLE
Enable TPC-H and TPC-DS product test queries to run on their respective connectors

### ISSUE THREAD

**Issue by petroav** [prestodb/presto#9003]
Statistics were recently added to the TPC-H and TPC-DS connectors. This task tracks the work needed to run those queries on their respective connectors both for regular presto product test runs on Travis as well as for presto-checks. Currently all these queries run on the Hive connector which does not have statistics for the tables. This work is needed in preparation of the introduction of the CBO so that we can test its correctness (in other words run the queries with stats, with the CBO on and ensure we get correct results).

A working spike for this work is available on https://github.com/Teradata/presto/tree/enable-tpch-tpcds-stats. That branch unquarantines queries, changes some column names/aliases so that they run on the connectors and introduces new groups so that the load on Travis executors is evenly spread out. A working spike for presto-checks is available on https://github.com/Teradata/presto-checks/tree/tpcds-on-separate-executors. That branch spreads out TPC-DS queries on different executors so jobs don't time out.

**Comment by findepi** [comment]
> Currently all these queries run on the Hive connector which does not have statistics for the tables. 

There was some work in progress by @kokosing to bring stats for Hive connector in product tests. The idea was to test TPC-{H,DS} queries on Hive connector (with stats) rather on tpch/tpcds connectors, because Hive connector is more "production-like". E.g tpch connector has certain unusual features implemented which are there only for the sake of other tests.

**Comment by petroav** [comment]
> to bring stats for Hive connector in product tests

Interesting, didn't know that. On internal JIRAs the last comments seemed to indicate that we're going to use the TPC-H and DS connectors instead of Hive. @kokosing is your work on a branch somewhere?

**Comment by kokosing** [comment]
Everything is merged into presto/master. In recent tempto (1.36) statistics for immutable tables are injected into hive, so when running queries agains TPCH or TPCDS, planner will be able to access stats. All you need to do (in TD incoming release)  is to set session properties to enable rules that are using stats.

**Comment by petroav** [comment]
Oh well, I guess I did some work I didn't need to do :) I'm closing this ticket as its no longer relevant.
