### ISSUE TITLE
libprocname.so file missing in rpm file

### ISSUE THREAD

**Issue by zz22394** [prestodb/presto#9009]
After installing presto using .rpm file, I always got the following error in ``launcher.log``:
```
ERROR: ld.so: object '/usr/lib/presto/bin/procname/Linux-x86_64/libprocname.so' from LD_PRELOAD cannot be preloaded: ignored.
```
I found ``libprocname.so`` in presto source code folder:
presto-server/target/presto-server-0.182/bin/procname/Linux-x86_64/libprocname.so

However this file cannot be found in rpm file.
Currently only 3 files in /usr/lib/presto/bin :
```
launcher
launcher.properties
launcher.py
```

So I added a section in pom.xml to add libprocname.so into rpm file.

**Comment by ashwinhs** [comment]
Can it because you are using Java 32bit version?

**Comment by electrum** [comment]
@cawallin This is strange. How did the RPM ever work without this file?

**Comment by electrum** [comment]
Ah, this is actually a warning from `ld.so` and is "ignored" (as the message says), which is why it works.
