### ISSUE TITLE
Presto Tuning to improve multiple queries in parallel

### ISSUE THREAD

**Issue by ashwinhs** [prestodb/presto#9012]
Hello - We are facing an issue with running multiple queries in our cluster. If we run single queries (no other queries running in the cluster) it runs pretty fast. If we start running > 2 queries, the performance degrades and the queries take double the time to run. We checked the utilization, the memory util is not 100%, CPU is not overloaded. Any ideas/suggestions what parameters we can tune to improve this?

**Comment by akshatnair** [comment]
You can run explain analyze on one of the query to see which stage is taking the longest time. When you file an issue, it is always useful to post system information and Presto configuration to help understand it better.

**Comment by akshatnair** [comment]
You can also observe the queries on web UI to ensure that they are indeed running in parallel and not serially.

**Comment by tooptoop4** [comment]
getting the same issue, if only 1 query is running on its own then finishes in less than 2mins. But if that same query is running in 2 sessions in parallel then one session finishes in 2mins but the other session takes 15mins.


 "queryStats" : {
    "createTime" : "2019-07-01T15:47:16.880Z",
    "executionStartTime" : "2019-07-01T15:47:16.958Z",
    "lastHeartbeat" : "2019-07-01T15:52:04.410Z",
    "elapsedTime" : "4.80m",
    "queuedTime" : "78.83ms",
    "resourceWaitingTime" : "44.86us",
    "executionTime" : "4.80m",
    "analysisTime" : "2.27s",
    "totalPlanningTime" : "2.27s",
    "finishingTime" : "0.00ms",
    "totalTasks" : 2,
    "runningTasks" : 2,
    "completedTasks" : 0,
    "totalDrivers" : 674,
    "queuedDrivers" : 203,
    "runningDrivers" : 0,
    "blockedDrivers" : 17,
    "completedDrivers" : 454,
    "cumulativeUserMemory" : 0.0,
    "userMemoryReservation" : "0B",
    "totalMemoryReservation" : "107.73MB",
    "peakUserMemoryReservation" : "0B",
    "peakTotalMemoryReservation" : "114.09MB",
    "peakTaskUserMemory" : "0B",
    "peakTaskTotalMemory" : "75.76MB",
    "scheduled" : false,
    "totalScheduledTime" : "52.00s",
    "totalCpuTime" : "8.52s",
    "totalBlockedTime" : "2.18h",
    "fullyBlocked" : false,
    "blockedReasons" : [ ],
    "rawInputDataSize" : "67.03MB",
    "rawInputPositions" : 2324036,
    "processedInputDataSize" : "288.24MB",
    "processedInputPositions" : 2324036,
    "outputDataSize" : "187.86MB",
    "outputPositions" : 1630090,
    "physicalWrittenDataSize" : "0B",
    "stageGcStatistics" : [ {
      "stageId" : 0,
      "tasks" : 1,
      "fullGcTasks" : 0,
      "minFullGcSec" : 0,
      "maxFullGcSec" : 0,
      "totalFullGcSec" : 0,
      "averageFullGcSec" : 0
    }, {
      "stageId" : 1,
      "tasks" : 1,
      "fullGcTasks" : 0,
      "minFullGcSec" : 0,
      "maxFullGcSec" : 0,
      "totalFullGcSec" : 0,
      "averageFullGcSec" : 0
    } ],
    "operatorSummaries" : [ ],
    "logicalWrittenDataSize" : "0B",
    "writtenPositions" : 0,
    "spilledDataSize" : "0B"
  },
  "setSessionProperties" : { },
  "resetSessionProperties" : [ ],
  "setRoles" : { },
  "addedPreparedStatements" : { },
  "deallocatedPreparedStatements" : [ ],
  "clearTransactionId" : false,


not sure what NO_MORE_BUFFERS means:
      "lastHeartbeat" : "2019-07-01T15:52:04.515Z",
      "outputBuffers" : {
        "type" : "PARTITIONED",
        "state" : "NO_MORE_BUFFERS",
        "canAddBuffers" : false,
        "canAddPages" : true,
        "totalBufferedBytes" : 35024393,
        "totalBufferedPages" : 419,
        "totalRowsSent" : 1630090,
        "totalPagesSent" : 2552,
        "buffers" : [ ]
      },
