### ISSUE TITLE
Add query plan to QueryCompletedEvent

### ISSUE THREAD

**Issue by raghavsethi** [prestodb/presto#9016]
This makes debugging certain classes of problems much easier

**Comment by zz22394** [comment]
@raghavsethi  Do you mean adding StageInfo into QueryCompletedEvent, 
like outputStage in QueryInfo ?

**Comment by raghavsethi** [comment]
No, I mean adding the string representation of the plan (textLogicalPlan or textDistributedPlan) to the QueryCompletedEvent.
