### ISSUE TITLE
Any way to force presto to select individual rows instead of whole table?

### ISSUE THREAD

**Issue by yaningzhu** [prestodb/presto#9028]
I have a query like this:

```
SELECT users.*
FROM prepared_list 
  JOIN users ON prepared_list.user_id = users.id
WHERE prepared_list.attribute = 1
```

I noticed that presto will read the entire `users` table, even if the number of rows affected from `prepared_list` is really small.

It would be much faster to pluck out the individual rows from `users` instead of reading the whole table. Is there a way to force presto to do that?

I'm using the mysql connector. Not sure if that affects anything.

**Comment by findepi** [comment]
@yaningzhu , first of all, issues like this are better handled by the user group (https://groups.google.com/forum/#!forum/presto-users).

Second,

- you can break your query into two (first pull user IDs then query `users` table)
- there's ongoing work in the area of "dynamic filtering", e.g. https://github.com/prestodb/presto/pull/8588 which is going to handle certain cases like this better (as far as connector can support this, which in case of simple connector like mysql might be harder to do as compared to hive connector)
- if both tables are in the same mysql database, you can also define view in mysql and force join there, as this would make much more sense then joining in presto (possible even if this is just a part of bigger query)
