### ISSUE TITLE
Unsigned numeric datatype mapping to signed may cause data outside valid range

### ISSUE THREAD

**Issue by flashput** [prestodb/presto#9069]
`com.facebook.presto.plugin.jdbc.BaseJdbcClient.toPrestoType()`

tinyint unsigned (0-255) is casted to tinyint (-128 - 127) 

unsigned data from jdbc datasource (mysql in my case) may casted with error as follows:

```
com.mysql.jdbc.exceptions.jdbc4.MySQLDataException: '160' in column '9' is outside valid range for the datatype TINYINT.
```

**Comment by BrainMonkey** [comment]
Having the same issues, been going through the source code but it doesn't look like it leveraging mysql jdbc connector : ResultSetMetaData.GetColumnClassName() 
https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-type-conversions.html

Looking at how can implement a check on the mysql plugin

**Comment by mpontillo** [comment]
I just hit this issue today with the MySQL connector:

```
Query 20200313_053633_02686_r9ndg failed: '145' in column '3' is outside valid range for the datatype TINYINT.
```
