### ISSUE TITLE
Support array construction with more than 254 elements

### ISSUE THREAD

**Issue by wenleix** [prestodb/presto#9073]
```
presto> SELECT
            ->   ARRAY[
            ->     x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x,
            ->     x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x,
            ->     x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x,
            ->     x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x,
            ->     x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x,
            ->     x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x,
            ->     x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x,
            ->     x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x,
            ->     x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x,
            ->     x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x,
            ->     x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x,
            ->     x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x,
            ->     x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x,
            ->     x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x,
            ->     x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x,
            ->     x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x
            ->   ]
            -> FROM (VALUES 0) AS t(x)
            -> ;
Query 20170929_184152_27787_2axhq failed: Too many arguments for array constructor
```

**Comment by satybald** [comment]
I've looked into the issue a bit. What I found the main issue is that arrays in presto [under the hood is a scalar function](https://github.com/prestodb/presto/blob/53e650b0eb5714372222332e496497619be8d30c/presto-main/src/main/java/com/facebook/presto/operator/scalar/ArrayConstructor.java#L105-L130). Array converted to the function with java reflection magic. However, a method in JVM can only have up to 254 arguments.

> https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.11
> The number of method parameters is limited to 255 by the definition of a method descriptor (§4.3.3), where the limit includes one unit for this in the case of instance or interface method invocations.

**Comment by yingsu00** [comment]
I'm working on it.

**Comment by martint** [comment]
This requires allowing scalar functions to take a variable number of arguments (via an array) and making the expression compiler adapt the signatures.
