### ISSUE TITLE
Understanding some hive.metastore.* parameters

### ISSUE THREAD

**Issue by prabcs** [prestodb/presto#9082]
Hi,

Following up from https://github.com/prestodb/presto/issues/1182#issuecomment-39823550 - 

> However, it will end up making more metastore calls.

I couldn't find much documentation or material related to this. Hence, asking my questions here -

1. Can it impact hive as well ? or just Presto ?
2. Are there any benchmarks done when testing performance on those parameters ?
3. Has the minimum value of `1ms` tested for performance ?
4. What JMX parameters to look out for in order to track the impact this might have on the Presto/Hive ?

Thanks !

**Comment by shixuan-fan** [comment]
1. The config should only impact Presto behavior, not Hive as a compute engine. But if Presto is issuing more metastore calls and metastore performance is impacted, then Hive's performance might be impacted.
2&3. I personally am not sure.
4. Maybe `ThriftHiveMetastoreStats` to see the metastore call latency?
