### ISSUE TITLE
Support for multiple query event listeners

### ISSUE THREAD

**Issue by nishantrayan** [prestodb/presto#9100]
Hi,
My team uses presto and also one of the heavy users for event listener plugin to track queries and latencies along with success/failures. There is case where it would have been nice to separate out functionalities of the single giant plugin into query-logger vs metric-collector. Currently the way I understand from the documentation: https://github.com/prestodb/presto/blob/master/presto-docs/src/main/sphinx/develop/event-listener.rst#event-listener we can only have one plugin active at a time.
Looking at the code (more specifically.https://github.com/prestodb/presto/blob/6e7c9ca25cfc7940c961638fbc06b692b7b869c0/presto-main/src/main/java/com/facebook/presto/eventlistener/EventListenerManager.java#L59) looks like its fairly straight forward to extend for multiple event listener plugins. I want to get some thoughts on this feature. I can pick it up as well

**Comment by electrum** [comment]
The main difficulty is how to configure it. With a single event listener, we just have a single `event-listener.properties` file. For multiple listeners, we'd need an `etc/event/` directory with multiple files, similar to connectors.

You can split this out within your plugin like this:
```java
public class MultiEventListener
{
    private final Set<EventListener> listeners;

    @Inject
    public MultiEventListener(Set<EventListener> listeners)
    {
        this.listeners = ImmutableSet.copyOf(listeners);
    }

    @Override
    public queryCreated(QueryCreatedEvent queryCreatedEvent)
    {
        for (EventListener listener : listeners) {
	    listener.queryCreated(queryCreatedEvent);
        }
    }

    @Override
    public void queryCompleted(QueryCompletedEvent queryCompletedEvent)
    {
        for (EventListener listener : listeners) {
	    listener.queryCompleted(queryCompletedEvent);
        }
    }

    @Override
    public void splitCompleted(SplitCompletedEvent splitCompletedEvent)
    {
        for (EventListener listener : listeners) {
	    listener.splitCompleted(splitCompletedEvent);
        }
    }
}
```

If you're using Guice, you can bind them like this:

```java
Multibinder<EventListener> eventBinder = newSetBinder(binder, EventListener.class);
eventBinder.addBinding().to(QueryLogger.class).in(Scopes.SINGLETON);
eventBinder.addBinding().to(MetricCollector.class).in(Scopes.SINGLETON);
```

Or just create it explicitly.

**Comment by nishantrayan** [comment]
Thanks @electrum 

>  For multiple listeners, we'd need an etc/event/ directory with multiple files, similar to connectors.


I was hoping that we can use the same `etc/event-listener.properties` but having capability to suggest multiple plugins using `event-listener.names=plugin1,plugin2,plugin3` property. After the properties file is parsed we can split them and load the required plugins. Any thoughts? I like this because its very simple for end user than thinking of having a custom plugin and having a separate mechanism to configure it with multiple sub plugins.

>You can split this out within your plugin like this:

I like this idea but wondering if you meant adding this as a capability in presto side or having it in the one allowed custom plugin ?

**Comment by nishantrayan** [comment]
Hi @electrum,
It will be great to know if you think it might be worth implementing it *inside* presto . 

CCing @nezihyigitbasi as well.

**Comment by qinghui-xu** [comment]
It seems this topic is not active since a while, but I find this feature request useful when we discuss the possibility to add an query history extension. I think we need to have the support for several `EventListener` by following the suggestions for adding a custom listener for queries without impacting other existent `EventListener` (https://github.com/prestodb/presto/issues/12185#issuecomment-452470696).

More generally, being able to have more than 1 `EventListener` should make it easier to provide new plugins. 

Also, some remarques regarding to @nishantrayan's suggestion:
> I was hoping that we can use the same `etc/event-listener.properties` but having capability to suggest multiple plugins using `event-listener.names=plugin1,plugin2,plugin3` property. After the properties file is parsed we can split them and load the required plugins. Any thoughts? I like this because its very simple for end user than thinking of having a custom plugin and having a separate mechanism to configure it with multiple sub plugins.

Maybe we can use yaml configuration file, such that each event-listener can have its proper section, this might be more readable and maintainable as a configuration file.

**Comment by findepi** [comment]
> Maybe we can use yaml configuration file, such that each event-listener can have its proper section, this might be more readable and maintainable as a configuration file.

Interesting idea. So this could be something like `etc/event-listener.yaml` in a form:
```
listeners:
- event-listener.name: ....
  other-properties: ...

- event-listener.name: ....
  other-properties: ...
```

@electrum any objections?

**Comment by qinghui-xu** [comment]
I could also contribute on this to move forward if a decision is made.
