### ISSUE TITLE
presto jdbc executeQuery(CATS)

### ISSUE THREAD

**Issue by petterpat** [prestodb/presto#9129]
I want to find queryId and start time and end time of executed query. using presto JDBC
 I am executing like show catalogs;
then getting queryId of that query and also getting start and end time of query. unwraping `PrestoResultSet.class`  everything is working fine. like
```java
 final ResultSet resultSet = st.getResultSet();                           	
		   PrestoResultSet  uRs = (PrestoResultSet)rs;
```
  `System.out.println(uRs.getQueryId());` it will gives query id of above query.
but when i executing query  `create table hive.test.region2 as select * form mysql.tpch.region;`
query is executing on server but in program throwing error
```
java.sql.SQLException: SQL statement is not a query: create table hive.test.region2 as select * from mysql.tpch.region
	at com.facebook.presto.jdbc.Presto
 com.facebook.presto.jdbc.PrestoStatement.executeQuery(PrestoStatement.java:73)
	at com.com.facebook.presto.jdbc.PrestotPreparedStatement.executeQuery(PrestoStatement.java:52)
	at QyueryReader2.main(QyueryReader2.java:29)
```

**Comment by electrum** [comment]
`executeQuery()` is for queries that return a result set (rows). DDL such as `CREATE TABLE` only return an update count, not a result set, so they should be used with `executeUpdate()` instead.

Please comment or reopen if you have further questions.
