### ISSUE TITLE
change hadoop dependency version for presto

### ISSUE THREAD

**Issue by totticarter** [prestodb/presto#9140]
We have a hadoop version of ourself, which modified some auth related source code. Now, I want to integrate this version of hadoop to presto, but I do not know which pom file I should process, as I found that presto put the apache hadoop class file to a jar hadoop-apache2-2.7.*-1.jar, which is different to the hadoop-common-2.**.jar or hadoop-hdfs-2.**.jar

**Comment by yuananf** [comment]
The project is https://github.com/prestodb/presto-hadoop-apache2

**Comment by electrum** [comment]
@yuananf Thanks for responding!

@totticarter I'm closing the issue as I believe it is resolved. Please comment or reopen if you have further questions.
