### ISSUE TITLE
How to implement a variable number of arguments udf?

### ISSUE THREAD

**Issue by armsword** [prestodb/presto#9146]
I want to implement a udf function, but it‘s a variable number of arguments, for example:
`concat_ws(separator,str1,str2,...)`

I write a function like this:

`
public static Slice concatWS(@SqlType(StandardTypes.VARCHAR) Slice separator, @SqlType(StandardTypes.VARCHAR)Slice... args) 
{
}
`

But，When I use this function(three parameters), it executes failed, error is 'Unexpected parameters xxxx'. I use 'show functions;',it displays its parameter list just is two. 

So,how can I implement a variable number of arguments udf?

Thanks.

**Comment by ebyhr** [comment]
This thread in google group may help you.  
https://groups.google.com/d/msg/presto-users/gIj_nQY901Y/xkTmdax9AgAJ

>Unfortunately, it's not possible to define a vararg function in a plugin. For now, you can definite multiple versions of the function (such as versions for one to five arguments) that can cover most/all usages.
>We don't do vararg yet with annotations because it's hard to pass the arguments efficiently. The ones built into the engine (such as string concatenation in the ConcatFunction class) get around this by code generating a version of the function for each arity.
>The fact that you get an error at runtime is a bug in the validation. I filed an issue to improve it:
>https://github.com/prestodb/presto/issues/8977
