### ISSUE TITLE
build presto on Windows failed

### ISSUE THREAD

**Issue by totticarter** [prestodb/presto#9147]
**Even through I know that building presto on Windows is hard to complete successfully, but I have to do that, and I got several Error like following:**

[ERROR] Failed to execute goal io.takari.maven.plugins:presto-maven-plugin:0.1.12:generate-service-descriptor (default-generate-service-descriptor) on project presto-jmx: Execution default-generate-service-descriptor of goal io
.takari.maven.plugins:presto-maven-plugin:0.1.12:generate-service-descriptor failed: A required class was missing while executing io.takari.maven.**plugins:presto-maven-plugin**:0.1.12:generate-service-descriptor: com\facebook\pres
to\connector\jmx\JmxColumnHandle (wrong name: com/facebook/presto/connector/jmx/JmxColumnHandle)
[ERROR] -----------------------------------------------------
[ERROR] realm =    extension>io.takari.maven.plugins:presto-maven-plugin:0.1.12
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/Users/cubeli/.m2/repository-tbds/io/takari/maven/plugins/presto-maven-plugin/0.1.12/presto-maven-plugin-0.1.12.jar
[ERROR] urls[1] = file:/C:/Users/cubeli/.m2/repository-tbds/com/google/guava/guava/14.0.1/guava-14.0.1.jar
[ERROR] urls[2] = file:/C:/Users/cubeli/.m2/repository-tbds/com/facebook/presto/presto-spi/0.76/presto-spi-0.76.jar
[ERROR] urls[3] = file:/C:/Users/cubeli/.m2/repository-tbds/io/airlift/slice/0.7/slice-0.7.jar
[ERROR] urls[4] = file:/C:/Users/cubeli/.m2/repository-tbds/com/fasterxml/jackson/core/jackson-annotations/2.4.2/jackson-annotations-2.4.2.jar
[ERROR] urls[5] = file:/C:/Users/cubeli/.m2/repository-tbds/com/fasterxml/jackson/core/jackson-databind/2.4.2/jackson-databind-2.4.2.jar
[ERROR] urls[6] = file:/C:/Users/cubeli/.m2/repository-tbds/com/fasterxml/jackson/core/jackson-core/2.4.2/jackson-core-2.4.2.jar
[ERROR] urls[7] = file:/C:/Users/cubeli/.m2/repository-tbds/org/codehaus/plexus/plexus-utils/3.0.17/plexus-utils-3.0.17.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

**While not all the modules built failed, I got some successfully built modules like:**
[INFO] presto-root ........................................ SUCCESS [  6.971 s]
[INFO] presto-spi ......................................... SUCCESS [  7.063 s]
[INFO] presto-array ....................................... SUCCESS [  1.702 s]
[INFO] presto-client ...................................... SUCCESS [  2.964 s]
[INFO] presto-parser ...................................... SUCCESS [  2.834 s]
[INFO] presto-bytecode .................................... SUCCESS [  1.911 s]
[INFO] presto-tpch ........................................ SUCCESS [  2.174 s]
[INFO] presto-main ........................................ SUCCESS [ 41.407 s]
[INFO] presto-tests ....................................... SUCCESS [ 32.339 s]
**[INFO] presto-jmx ......................................... FAILURE [ 15.256 s]**
[INFO] presto-record-decoder .............................. SUCCESS [  3.120 s]
[INFO] presto-kafka ....................................... SKIPPED
[INFO] presto-redis ....................................... SKIPPED

anyone knows how to resolve this problem?

**Comment by ebyhr** [comment]
You can build presto on a Linux VM in windows. Is it possible to run the VM in your environment?

https://groups.google.com/forum/#!topic/presto-users/IGOwvF18824
#2351
