### ISSUE TITLE
Raptor data on disk keeps growing

### ISSUE THREAD

**Issue by teejteej** [prestodb/presto#9159]
Using Presto 0.183 on a single server with both coordinator and worker on the same Presto instance. Metadata is stored in the MySQL adapter.

The workload consists of continuous DELETE + (re)INSERT of same but updated data. Disk space keeps growing, as it seems the space for the deleted rows is never reclaimed.

The only non-default property for the Raptor connector is `storage.max-shard-rows=100000`.
A fresh copy of the data is around 1GB, but after a few weeks it's grows to about 120GB.

I'm not sure what can be done to fix this, or maybe there is no sweeper implemented yet. Or will the problem disappear once there is a dedicated Presto instance for the coordinator, separated from the workers?

**Comment by electrum** [comment]
Data is only deleted if a backup store is configured. State tracking for local data is not exact, so it's not safe to cleanup if the local machine is the only copy. Running without a backup store is intended only for testing purposes.

For a single machine, you can set
```
backup.provider=file
backup.directory=/backup
```
For multiple machines, this needs to be a shared directory such as NFS.

**Comment by electrum** [comment]
If the data churn is high relatively available disk space, you may need to decrease these:

* `raptor.local-clean-time`
* `raptor.backup-clean-time`

**Comment by electrum** [comment]
Please comment or reopen if you have further questions.
