### ISSUE TITLE
Create a function to calculate correlation

### ISSUE THREAD

**Issue by satheeshravir** [prestodb/presto#9161]
Consider a query result that returns two columns A and B as follows. It would be better if there is a function that calculates correlation between the two columns.

A  |  B
--|--
2  |  3
6  |  7
0  |  0

**Comment by akshatnair** [comment]
https://prestodb.io/docs/current/functions/aggregate.html
check this:
corr(y, x) → double
Returns correlation coefficient of input values.

**Comment by satheeshravir** [comment]
👍
