### ISSUE TITLE
 Table does not have partition columns: hive

### ISSUE THREAD

**Issue by thanhlv93** [prestodb/presto#9183]
Hello,
I tried to show partitions from hive table but I got a message : 

>  Table does not have partition columns: hive.default.network

My command : 

> SHOW PARTITIONS FROM network

This is my command to create hive table: 

> CREATE TABLE Network (country String, city String,rowFormat int,startTime float," +
                "endTime float, userId int, type int,version int, operator String, netInt int, cmd int,subCmd int ," 
                "total int, failed int, exeTime int)  PARTITIONED BY (dt string) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\\t' STORED AS TEXTFILE

and I could using beeline to show Network partitions : 

> show partitions network; 
Respone : 

> +-------------------+--+
|     partition     |
+-------------------+--+
| dt=2017-10-20-11  |
+-------------------+--+

Please tell me if you have any suggest to fix this issue . Thanks.

**Comment by electrum** [comment]
Please run SHOW CREATE TABLE in Presto and paste the output.

**Comment by thanhlv93** [comment]
Hello @electrum ,

presto:default> show create table network;
            Create Table             
-------------------------------------
 CREATE TABLE hive.default.network ( 
    country varchar,                 
    city varchar,                    
    rowformat integer,               
    starttime real,                  
    endtime real,                    
    userid integer,                  
    type integer,                    
    version integer,                 
    operator varchar,                
    netint integer,                  
    cmd integer,                     
    subcmd integer,                  
    total integer,                   
    failed integer,                  
    exetime integer                  
 )                                   
 WITH (                              
    format = 'TEXTFILE'              
 )                                   
(1 row)

-------------------------
I can't see partitions when run in Presto .

**Comment by thanhlv93** [comment]
After restarted hive metastore then I can query partitions in Presto. 
Thanks all.
