### ISSUE TITLE
Does Presto supports Insert "load data local inpath "

### ISSUE THREAD

**Issue by thanhlv93** [prestodb/presto#9186]
Hello all,
I'm using this query : 

> load data local inpath abc/test into table test

with jdbc:hive://.... 
But when I changed to jdbc:presto:// , I can't using "  load data local inpath " ,so How can I use "  load data local inpath " in Presto ?

**Comment by akshatnair** [comment]
There is no such command supported in Presto.  Use `insert into` or you can load using Hive and then query from Presto.

https://prestodb.io/docs/current/sql/insert.html
