### ISSUE TITLE
Prestodb option task-max-threads is not honored as a parameter

### ISSUE THREAD

**Issue by chriscroswhite** [prestodb/presto#9191]
At least in release 185, setting anything for task.max-worker-threads is ignored, the code specifies number of processors * 2.

**Comment by chriscroswhite** [comment]
The above was introduced as far back as 148.

TaskManagerConfig.java: 47
private int maxWorkerThreads = Runtime.getRuntime().availableProcessors() * 2;

**Comment by chriscroswhite** [comment]
Is airlift messed up?  Seems @Config is not getting the parameter set?

**Comment by nezihyigitbasi** [comment]
Presto logs all config values on startup, can you double check the value of `task.max-worker-threads` in the logs?

**Comment by findepi** [comment]
@chriscroswhite please reopen if you're still having the problem
