### ISSUE TITLE
Presto not asyn data with hive 

### ISSUE THREAD

**Issue by thanhlv93** [prestodb/presto#9198]
Hello all,
I have an issue about asyn data between hive and Presto , my steps:

Step 1 : check partitions by hive jdbc

>jdbc:hive2://127.0.0.1:10000>  show partitions network;
+-------------------+--+
|     partition     |
+-------------------+--+
| dt=2017-10-20-11  |
| dt=2017-10-20-12  |
+-------------------+--+
2 rows selected (0.143 seconds)

Step 2: Check partitions by presto : 

>presto:default> show partitions from network;
      dt       
 +---------------
 2017-10-20-11 
 2017-10-20-12 
(2 rows)
Query 20171023_043821_00022_3nugm, FINISHED, 1 node
Splits: 50 total, 50 done (100.00%)
0:00 [2 rows, 116B] [8 rows/s, 471B/s]

Ok , now the number of partitions are same.

Step 3 : I put new data into hive database by command 
 
> String sql = "load data local inpath 'home/test/data1.txt' into table Network partition(dt='2017-10-20-10'";
stmt.execute(sql);

Step 4: I check again my partitions by hive jdbc 

> jdbc:hive2://127.0.0.1:10000> show partitions network;
+-------------------+--+
|     partition     |
+-------------------+--+
| dt=2017-10-20-10  |
| dt=2017-10-20-11  |
| dt=2017-10-20-12  |
+-------------------+--+
3 rows selected (1.887 seconds)

Ok now new partition is created.

Step 5: I check again my partition by Presto : 

> presto:default> show partitions from network;
      dt       
 +---------------
 2017-10-20-11 
 2017-10-20-12 
(2 rows)
Query 20171023_043821_00022_3nugm, FINISHED, 1 node
Splits: 50 total, 50 done (100.00%)
0:00 [2 rows, 116B] [8 rows/s, 471B/s]

Why my new partition is not show ?

Step 6 : I restarted hive metastore and check again partitions by presto 

> presto:default> show partitions from network;
      dt       
 +---------------
 2017-10-20-11 
 2017-10-20-12 
 2017-10-20-10 
(3 rows)
Query 20171023_044814_00026_3nugm, FINISHED, 1 node
Splits: 50 total, 50 done (100.00%)
0:00 [3 rows, 174B] [10 rows/s, 632B/s]

Now new my partition is showing , so why I need to restart hive metastore ? Please tell me if you have any suggest !
Thanks

**Comment by akshatnair** [comment]
`hive.metastore-cache-ttl` have you changed this value? 
What version of Presto is this?

**Comment by thanhlv93** [comment]
This is my config in hive.properties 

> connector.name=hive-hadoop2
hive.metastore.uri=thrift://localhost:9083
hive.config.resources=/home/cpu60020-local/Documents/Setup/Java/server/hadoop/conf/core-site.xml,/home/cpu60020-local/Documents/Setup/Java/server/hadoop/conf/hdfs-site.xml
hive.allow-drop-table=true
hive.allow-rename-table=true
hive.metastore-cache-ttl=0s
hive.metastore-refresh-interval=0s

Presto version : 0.186

**Comment by electrum** [comment]
Just to rule out any Presto side caching (meaning that the metastore restart just appears to fix and is unrelated), if you run `SHOW PARTITIONS` in Presto multiple times, do you always get the same result? I'd like to be certain that the metastore restart is what is actually fixing the problem.

**Comment by electrum** [comment]
Note that the two metastore cache settings are the default settings (we disabled Presto metastore caching a while back when we added transaction support for the Hive connector and made the caching per-transaction)

**Comment by thanhlv93** [comment]
@electrum I run SHOW PARTITIONS in Presto multiple times and I get the same result .
I tried to update version 
Presto : 0.187
Hive : 02.3.0
but same issue .

**Comment by thanhlv93** [comment]
New data just appears when I restart metastore.

**Comment by thanhlv93** [comment]
I changed from derby db to postgres db and it's working perfect !
