### ISSUE TITLE
Mutiple count distinct cause the query to be Blocked most of the time

### ISSUE THREAD

**Issue by tomerstar** [prestodb/presto#9200]
Hi,
I have a complex query with multiple count distinct 
select	a11.dk_dat_mo  dk_dat_mo,
	a16.MCO_TAP_CD  MCO_TAP_CD,
	a15.dir_nm  dir_nm,
	count(distinct Case when a13.nws_fmly='T' and (a12.CED_SNM='MOC' or a12.CED_SNM='MTC') then a11.dd_imsi else NULL end)  WJXBFS1,
	count(distinct Case when a13.nws_fmly='T' and a12.CED_SNM='MOC' then a11.dd_imsi else NULL end)  WJXBFS2,
	count(distinct Case when a13.nws_fmly='T' and a12.CED_SNM='MTC' then a11.dd_imsi else NULL end)  WJXBFS3,
	sum(Case when a13.nws_fmly='T' and (a12.CED_SNM='MOC' or a12.CED_SNM='MTC') then (a11.chgb_dur / 60.0) else 0 end)  WJXBFS4,
	sum(Case when a13.nws_fmly='T' and a12.CED_SNM='MOC' then (a11.chgb_dur / 60.0) else 0 end)  WJXBFS5,
	sum(Case when a13.nws_fmly='T' and a12.CED_SNM='MTC' then (a11.chgb_dur / 60.0) else 0 end)  WJXBFS6,
	count(distinct Case when a13.nws_fmly='S' and (a12.CED_SNM='MOC' or a12.CED_SNM='MTC') then a11.dd_imsi else NULL end)  WJXBFS7,
	count(distinct Case when a13.nws_fmly='S' and a12.CED_SNM='MOC' then a11.dd_imsi else NULL end)  WJXBFS8,
	count(distinct Case when a13.nws_fmly='S' and a12.CED_SNM='MTC' then a11.dd_imsi else NULL end)  WJXBFS9,
	sum(Case when a13.nws_fmly='S' and (a12.CED_SNM='MOC' or a12.CED_SNM='MTC') then a11.no_evt else 0 end)  WJXBFSa,
	sum(Case when a13.nws_fmly='S' and a12.CED_SNM='MOC' then a11.no_evt else 0 end)  WJXBFSb,
	sum(Case when a13.nws_fmly='S' and a12.CED_SNM='MTC' then a11.no_evt else 0 end)  WJXBFSc,
	count(distinct Case when a13.nws_fmly='G' and a12.CED_SNM<>'MOC' then a11.dd_imsi else NULL end)  WJXBFSd,
	sum(Case when a13.nws_fmly='G' and a12.CED_SNM<>'MOC' then (a11.chgb_vol / 1048576.0) else 0 end)  WJXBFSe
from	t_ftcd_dy	a11, 
	T_DCED	a12, 
	T_DNWS	a13, 
	T_DORG	a14, 
	T_DDIR	a15, 
	T_DMCO	a16, 
	T_DBRA	a17, 
	T_DPCS	a18, 
	T_DAFS	a19
where	a11.dk_ced = a12.dk_ced and 
	a11.dk_nws = a13.dk_nws and 
	a11.dk_org_cnp = a14.dk_org and 
	a11.dk_dir = a15.dk_dir and 
	a11.cl_id = a16.DK_MCO and 
	a11.cl_id = a17.cl_id and 
	a11.dk_bra = a17.dk_bra and 
	a11.dk_pcs = a18.dk_pcs and 
	a11.dk_afs_taf = a19.DK_AFS
 and	(
		a18.SM_RLVNT in ('Y')
		 and a19.AFS_CD in ('C')
		 and a15.dir_nm in ('Own Subscribers')
		 and a11.dk_dat_mo in (330)
		 and ((a17.bra_rt_cd not in ('N') and a16.MCO_TAP_CD in ('FRAF1'))
		or a16.MCO_TAP_CD not in ('FRAF1'))
		 and a14.org_cntry not in ('Not available')
	 and 1 = 1
)
group by	a11.dk_dat_mo,
	a16.MCO_TAP_CD,
	a15.dir_nm;

when i remove all the count distinct but one, the query is fast.
if i return one more count distinct it is starting to slow down and im starting to see a lot of Blocked status on the currently running stage.
if all the count distincts are there the query is completely stuck and out of 21 workers i can see maybe 1 or 2 in running state while the rest are Blocked.
the same query in hive finished quicker.
By the way, im runnin gon CDH 5.11 with hive connector, presto version 0.171
Is this a bug or expected Behavior?
If you need me to share some logs i would be happy to.
Regards,
Tomer

**Comment by jiangzhx** [comment]
@tomerstar any progress?
find way to fix this?

**Comment by martint** [comment]
Try disabling the `use_mark_distinct` option:

```
SET SESSION use_mark_distinct = false;
```
