### ISSUE TITLE
JDBC driver does not support setting session properties

### ISSUE THREAD

**Issue by chriscroswhite** [prestodb/presto#9203]
In an effort to support 3rd party tool use of the JDBC driver, we need to enable setting session properties.

**Comment by akshatnair** [comment]
Is there any other standard enterprise JDBC driver that does that for any other database?
Is it part of JDBC specification or you want to add something Presto specific?

**Comment by chriscroswhite** [comment]
Actually, I am completely off base now that you poked me for more information.  Closing this, as its not correct in stating the problem+solution.

**Comment by electrum** [comment]
Based on our earlier discussion, you want `SET SESSION` to work from JDBC, correct? That seems like a reasonable thing for us to support.
