### ISSUE TITLE
Add config parameter for Kerberized Coordinator behind a Load Balancer

### ISSUE THREAD

**Issue by allanwilson** [prestodb/presto#9212]
In our environment, we are using the MIT Kerberos distro.  Our Coordinator for the Production Presto Cluster sits behind a load balancer.  The basic MIT distro doesn't support the creation of SPN aliases according to our SYSAD team and SpnegoFilter.java in presto only picks up the FQDN of the coordinator host, and not the DNS name advertised for the Coordinator.

We use Hashicorp's  Consul to create service names and Fabio for a Load Balancer.

For example:  
Load Balanced Name  al.presto.service.somedomain.com
Host Name for Coordinator:  coord1.somedomain.com

SpnegoFilter.java would always pick coord1.somedomain.com from /etc/hosts (due to how   InetAddress.getLocalHost().getCanonicalHostName().toLowerCase(Locale.US); works).  The presto client would be expecting to authenticate against  al.presto.service.somedomain.com, but the coordinator would obtain a key for coord1.somedomain.com SPN so the creation of a shared session key for the authentication was never correct.

My workaround was to update SpengoFilter.java to use a system property to specify the correct hostname (SPN) to be used by the coordinator.
-Dkrb5.spn.hostname=al.presto.service.somedomain.com, if this property isn't specified it would revert back to the default behavior of getting the host name.

I would like to know, if I were to make the changes to support the use of the krb5.spn.hostname property specified in config.properties (opposed to jvm.conf, what we do) would it be accepted and incorporated into presto so we don't have to keep making this customization every time we want to deploy a newer presto distro?

BTW...We already went through the legal process to contribute back to the distro.

Thanks

**Comment by electrum** [comment]
We use a load balanced setup for Kerberos and it works like this: the load balancer sends an HTTP 307 to direct the client to the coordinator host, then the client authenticates to the specific machine it is connecting to.

My limited understanding of Kerberos is that the SPN must be unique and can't be shared across machines. Per this [documentation](https://msdn.microsoft.com/en-us/library/ms677949(v=vs.85).aspx):

> If you install multiple instances of a service on computers throughout a forest, each instance must have its own SPN. ...  an SPN always includes the name of the host computer on which the service instance is running 

This great [book](https://steveloughran.gitbooks.io/kerberos_and_hadoop/content/sections/what_is_kerberos.html) says the same thing:

> ... the bits of Kerberos which handle logins, the Kerberos Domain Controllers, treat repeated attempts to log in as the same principal within a short period of time as some attack on the system, such as a replay or key guessing attack. The requests are all automatically rejected

We are happy to accept a patch to configure this if it's needed, but I'd like to understand why.

**Comment by allanwilson** [comment]
Interesting.. Which load balancer does your site use?  Our load balancer is
Fabio and runs in a docker container. I've never been able to get the
actual host name returned to the client for the presto session.  I can only
get it to see the published service name, al.presto.service.somedomain.com
or the hostname of the balancer's vip.  The SPN is only associated with the
coordinators for our Presto Cluster and only those coordinator hosts have a
keytab with a key for those SPNs so I don't think there is a
danger/exposure there.

This is one site that discusses some setup options for a Kerberized service
behind a load balancer.
https://ssimo.org/blog/id_019.html   The solution I was able to make work
was the one titled 'Use only one common Service Principal Name', but the
presto code had to be tweaked to load the key for the common SPN instead of
the local host's name.

**Comment by electrum** [comment]
The load balancer is custom. The important part is that it does an HTTP redirect and is not proxying the requests.

I think if the load balancer is going to proxy requests, it needs to handle Kerberos itself and make new Kerberos requests itself to the backend machines (basically using an impersonation model).

**Comment by allanwilson** [comment]
Yeah... Fabio definitely doesn't do that.
We use Consul to publish the presto service within a reserved DNS
subdomain.  Fabio is used as a front end to the service and it does work
somewhat like a proxy. It can't handle keytabs.

We'll stick with Fabio for now and modify the presto code.  We aren't
worried about specifying a SPN that can be used on more than one host
because no one will be able to sneak another box into our realm, grab the
keytabs, and register in CONSUL to offer the service.  It requires a token
stored in Vault to register the service in CONSUL too.

Thx
-Allan
