### ISSUE TITLE
Tpc benchmark  failed as something like "Schema tpcds_10gb_txt does not exist" 

### ISSUE THREAD

**Issue by linwukang** [prestodb/presto#9214]
I have setup the benchto server and it works, then I run a tpc-h benchmark according to instruction of Presto Benchto benchmarks, the benchmark carried on and failed as something like "Schema tpcds_10gb_txt does not exist". 
I wonder how to generate the data for benchmark, It seems that there's no documents address this subject.  

Any suggestions is welcomed :-)

LOG:
========================================================================
071143_00533_hzwkt): line 16:1: Schema tpch_1tb_orc does not exist
15:11:44.399 INFO  [main] c.t.b.d.l.LoggingBenchmarkExecutionListener - Finished benchmark: presto/tpch
15:11:44.399 INFO  [main] c.t.b.d.e.BenchmarkExecutionDriver - [17 of 25] processing benchmark: Benchmark{name=presto/tpch, uniqueName=presto_tpch_database=hive_prefix=_query=q13_schema=tpch_1tb_orc_tpch_large=tpch_1tb_orc_tpch_medium=tpcds_10gb_txt_tpch_small=tpch_10gb_orc, sequenceId=2017-10-25T06:58:48:119, dataSource=presto, environment=presto-emr-v0147, queries=[Query{name=q13, sqlTemplate=SELECT
c_count,
count(*) as custdist
FROM (
SELECT
c.custkey,
count(o.orderkey)
FROM
"${database}"."${schema}"."${prefix}customer" c
LEFT OUTER JOIN
"${database}"."${schema}"."${prefix}orders" o
ON
c.custkey = o.custkey
AND o.comment NOT LIKE '%special%requests%'
GROUP BY c.custkey
) AS c_orders (c_custkey, c_count)
GROUP BY
c_count
ORDER BY
custdist DESC,
c_count DESC
;}], runs=10, prewarmRuns=2, concurrency=1, frequency=Optional[PT168H], beforeBenchmarkMacros=[], afterBenchmarkMacros=[], beforeExecutionMacros=[sleep-4s, presto/session_set_reorder_joins.sql], afterExecutionMacros=[], variables={schema=tpch_1tb_orc, query-names=presto/tpch/q13.sql, before-execution=sleep-4s, presto/session_set_reorder_joins.sql, prefix=, query=q13, prewarm-runs=2, tpch_large=tpch_1tb_orc, frequency=7, tpch_medium=tpcds_10gb_txt, tpch_small=tpch_10gb_orc, database=hive, datasource=presto, quarantine=false, runs=10}}
15:11:44.404 INFO  [pool-34-thread-1] c.t.b.d.m.s.ShellMacroExecutionDriver - Executing macro: 'echo "Sleeping for 4s" && sleep 4'
15:11:48.426 ERROR [pool-34-thread-1] c.t.b.d.e.BenchmarkExecutionDriver - Query Execution failed for benchmark presto/tpch
15:11:48.427 INFO  [pool-34-thread-1] c.t.b.d.m.s.ShellMacroExecutionDriver - Executing macro: 'echo "Sleeping for 4s" && sleep 4'
15:11:52.451 ERROR [pool-34-thread-1] c.t.b.d.e.BenchmarkExecutionDriver - Query Execution failed for benchmark presto/tpch
15:11:52.451 INFO  [main] c.t.b.d.l.LoggingBenchmarkExecutionListener - Executing benchmark: presto/tpch
15:11:52.471 INFO  [pool-35-thread-1] c.t.b.d.m.s.ShellMacroExecutionDriver - Executing macro: 'echo "Sleeping for 4s" && sleep 4'
15:11:56.474 INFO  [pool-35-thread-1] c.t.b.d.l.LoggingBenchmarkExecutionListener - Query started: q13 (1/10)
15:11:56.489 ERROR [pool-35-thread-1] c.t.b.d.e.BenchmarkExecutionDriver - Query Execution failed for benchmark presto/tpch
15:11:56.490 ERROR [pool-35-thread-1] c.t.b.d.l.LoggingBenchmarkExecutionListener - Query failed: q13 (1/10), execution error: Query failed (#20171025_071155_00536_hzwkt): line 9:1: Schema tpch_1tb_orc does not exist

**Comment by linwukang** [comment]
I fix this by myself, just run ./presto-benchto-benchmarks/generate_schemas/generate-tpch.py first to create data, it tooks long time to generate the data.

**Comment by hustnn** [comment]
I check the code of ./presto-benchto-benchmarks/generate_schemas/generate-tpch.py. 

It just print some strings. How to make the data generate work?
