### ISSUE TITLE
presto-cli Bug in --krb5-remote-service-name parsing / and realm, blocking use of fully qualified service principal

### ISSUE THREAD

**Issue by HariSekhon** [prestodb/presto#9216]
I'm running presto-cli 0.187 and finding that its parsing of `--krb5-remote-service-name` is buggy and not permitting specifying the krb5 service name properly if appending `@REALM` - it appears to be taking the value as only the first part of the service principal inferring the latter part automatically. I've managed to work around this using `--krb5-disable-remote-service-hostname-canonicalization` but the handling of this option should allow fully specifying the service principal and at the very least the error message should be changed to reflect the actual disallowed characters as it's reporting the wrong ones:

The error message complains about the characters `/` / `:` but it appears that it's the `@` symbol that actually breaks it. The error doesn't reflect this, instead stating it's one of the above characters which aren't actually found in the resulting principal:

```
Error running command: Kerberos error for [presto@<realm>@docker_presto_1.docker_network]: Invalid name provided (Mechanism level: Illegal character in realm name; one of: '/', ':', '' (600))
```
(I've replaced my actual realm literal with the `<realm>` token placeholder)

Here is the full command:

```
presto-cli --server https://presto:7779 --enable-authentication --user <user> --krb5-keytab-path /etc/security/keytabs/my.service.keytab --krb5-principal <user>@<realm> --krb5-remote-service-name HTTP@<realm> --truststore-path /etc/presto/keystore.jks --truststore-password <password>
# the error only shows when you try to query, eg.
presto> show tables from hive.default;
Error running command: Kerberos error for [HTTP@<realm>@docker_presto_1.docker_network]: Invalid name provided (Mechanism level: Illegal character in realm name; one of: '/', ':', '' (600))
presto>
```
What I'd expect to put in the `--krb5-remote-service-name` field is actually `HTTP/presto` or `HTTP/presto@<realm>`, trying the first one does not result in the error above even though the previous error states that it should fail because `/` is not allowed (why wouldn't it be allowed it's a standard part of a service principal). It only breaks with the above message when adding `@anything` even without `/presto` being included.

If I put just `HTTP/presto` for `--krb5-remote-service-name` then it autocompletes to the wrong realm and is rejected by the KDC:
```
presto-cli --server https://presto:7779 --enable-authentication --user <user> --krb5-keytab-path /etc/security/keytabs/my.service.keytab --krb5-principal <user>@<realm> --krb5-remote-service-name HTTP/presto --truststore-path /etc/presto/keystore.jks --truststore-password <password>
presto> show tables from hive.default;
Error running command: Kerberos error for [HTTP/presto@docker_presto_1.docker_network]: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Server not found in Kerberos database (7) - LOOKING_UP_SERVER))
presto> 
```

but notice it doesn't complain about the slash in `HTTP/presto`, it goes all the way through to the KDC who cannot find the credential because it's the wrong realm autocompleting to the FQDN of the docker container by the look on it.

So then trying to specify the realm explicitly with either `HTTP@<realm>` or `HTTP/presto@<realm>` formats both result in the same error stating rejection based on the wrong characters which aren't present:

```
presto-cli --server https://presto:7779 --enable-authentication --user <user> --krb5-keytab-path /etc/security/keytabs/my.service.keytab --krb5-principal <user>@<realm> --krb5-remote-service-name HTTP@<realm> --truststore-path /etc/presto/keystore.jks --truststore-password <password>
presto> show tables from hive.default;
Error running command: Kerberos error for [HTTP@<realm>@docker_presto_1.docker_network]: Invalid name provided (Mechanism level: Illegal character in realm name; one of: '/', ':', '' (600))
presto> 
```

```
presto-cli --server https://presto:7779 --enable-authentication --user <user> --krb5-keytab-path /etc/security/keytabs/my.service.keytab --krb5-principal <user>@<realm> --krb5-remote-service-name HTTP/presto@<realm> --truststore-path /etc/presto/keystore.jks --truststore-password <password>
presto> show tables from hive.default;
Error running command: Kerberos error for [HTTP/presto@<realm>@docker_presto_1.docker_network]: Invalid name provided (Mechanism level: Illegal character in realm name; one of: '/', ':', '' (600))
presto> 
```
I understand what it's trying to do, simplify the value required to the `--krb5-remote-service-name` option by inference but it should permit inline overrides such that if `@` is detected in the principal value then it doesn't append an inferred realm from canonicalized service hostname. Right now I just work around this behaviour by omitting the suffix and using the nice short switch `--krb5-disable-remote-service-hostname-canonicalization`, but the error is currently misleading and the behaviour could be improved to permit specifying the full principal which would be shorter than using the above switch to disable the behaviour.

To confirm the version I'm seeing this in:
```
presto-cli --version
Presto CLI 0.187
```

Thanks for your great work on this project so far btw.

Cheers

Hari

**Comment by electrum** [comment]
Thanks for the detailed report!

That error message actually comes from the JDK Kerberos code: http://hg.openjdk.java.net/jdk8u/jdk8u/jdk/file/d5a00b1e8f78/src/share/classes/sun/security/krb5/internal/Krb5.java#l372

I don't know much about Kerberos, but I can tell you that our integration tests (in the `presto-product-tests` directory) use `presto-server` for the service name and our production setup uses `presto.coordinator.https`. I think if you remove the leading `HTTP/` then it will work. (Maybe it is always assumed to be `HTTP` since it uses SPNEGO?)

Allowing a full service principal is a good idea and is easy to add. In most cases, you want the automatic hostname creation as the client can be used to talk to many different servers. In our case, we actually point the client at a VIP uses an HTTP redirect to send the client to a specific Presto cluster, so it would be impossible to configure the hostname up front. (And I agree the option to disable canonicalization seem excessively long.)

Regarding the *"Illegal character in realm name"* message, it can be helpful to run the CLI with `--debug` to print the full stack trace, which can help show where the error is coming from.

**Comment by SolidBrave** [comment]
I am working right now on a Cluster and my KDC is configured to have a REALM != Hostname. If i try to querry something i get the error Invalid credentials, because the @hostname is just the wrong autocomplete. In all together @HariSekhon problem is my problem aswell.

**Comment by liyubin117** [comment]
> I am working right now on a Cluster and my KDC is configured to have a REALM != Hostname. If i try to querry something i get the error Invalid credentials, because the hostname is just the wrong autocomplete as realm. All together @HariSekhon problem is my problem aswell.
> EDIT: With the difference that --krb5-diable-remote-service-hostname-canonicalization gets ignored and it still appends the wrong realm.

In fact, the problem is server-end principal's keytab form, you need to create keytab as follow:
```
addprinc -randkey presto
addprinc -randkey presto/debian
ktadd -e "aes256-cts:normal" -k presto.keytab presto
ktadd -e "aes256-cts:normal" -k presto.keytab presto/debian
```
