### ISSUE TITLE
Wrong error message for UNION type mismatch

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#9230]
This should be column 1, not 0.
```
presto> select 123, 'foo' union all select 'bar', 999;
Query 20171027_202828_44812_fkpyx failed: line 1:19: column 0 in UNION query has incompatible types: integer, varchar(3)

**Comment by electrum** [comment]
If possible, the error location should also be set to the position of the column that has the error in the first query.

**Comment by PradnyaBora** [comment]
I would like to fix this issue. I have started looking into code. can you please assign it to me.

**Comment by raghavsethi** [comment]
Hey @PradnyaBora any progress on this, it's yours.

**Comment by AgustinCB** [comment]
Is the problem that the column number should 1-indexed?

**Comment by aromero-pm** [comment]
I've looked at a few SQL dialects (Oracle, SQL Server, MySQL, ANSI) and column ordinals are generally 1-indexed. In general, though, their use is discouraged because they're brittle -- if you change the query suddenly the ordinals don't line up.

**Comment by kokosing** [comment]
Fix: https://github.com/prestodb/presto/pull/10160
