### ISSUE TITLE
How can I use Sentry to instead of hive metastore for auth?

### ISSUE THREAD

**Issue by lynch0227** [prestodb/presto#9250]
Hi Guys,
  Now we use Hue to query Hive, and using Sentry service to do auth.
  We meet a big problem when using presto instead of hue, we don't know how to intergate presto with sentry.
  Do you have use cases for this issue, or do you have any plan to release this feature for furture?
Thank you.

**Comment by electrum** [comment]
I'm not familiar with Sentry. Today, the Hive connector supports the `sql-standard` authorization mode which uses the privileges provided by the Hive metastore: https://prestodb.io/docs/current/connector/hive-security.html

If Sentry supports the standard Hive metastore APIs for security, then it should work.
