### ISSUE TITLE
Not able to get correct Longdecimal Value from slice 

### ISSUE THREAD

**Issue by geetikagupta16** [prestodb/presto#9256]
I am trying to get a value from a LongDecimal DataType variable using the below method from UnscaledDecimal128Arithmetic class: 

`unscaledDecimalToBigInteger((Slice) rawdata))`

The above command returns me a wrong BigInteger value. For Example, Suppose my decimal value is `12345678901.12345678` and I am getting `123456789011234569549`. 

Is there any way to get the exact decimal value from the slice.

**Comment by findepi** [comment]
cc @sopel39

**Comment by sopel39** [comment]
Could you give an exact code snippet (or SQL) how you are doing it? It might be the case that the converted literal was double initially and lost precision when converting to decimal. However, without the code I cannot reproduce the case.

**Comment by geetikagupta16** [comment]
Please find the details below:

Schema of the table: 

> presto:default> desc uniqdata;
       Column        |      Type      | Extra | Comment 
---------------------+----------------+-------+---------
 cust_id             | integer        |       |         
 cust_name           | varchar        |       |         
 active_emui_version | varchar        |       |         
 dob                 | timestamp      |       |         
 doj                 | timestamp      |       |         
 bigint_column1      | bigint         |       |         
 bigint_column2      | bigint         |       |         
 decimal_column1     | decimal(30,10) |       |         
 decimal_column2     | decimal(36,10) |       |         
 double_column1      | double         |       |         
 double_column2      | double         |       |         
 integer_column1     | integer        |       |         
(12 rows)

SQL query used :

> presto:default> select decimal_column1 from uniqdata where decimal_column1=12345678901.1234000000;

When I try to execute the above query using my custom connector the decimal value in the where clause gets converted to a Slice value, but to create a filter expression in my connector I need the corresponding decimal value for that slice, So I need to find a way to convert that Slice into a BigDecimal value.

**Comment by sopel39** [comment]
> the decimal value in the where clause gets converted to a Slice value

Which decimal value? `decimal_column1` or `12345678901.1234000000`.
By default non-integer numeric literals are of double type in Presto. To get literal of type decimal you should write `decimal '12345678901.123400000'`.

**Comment by geetikagupta16** [comment]
Thanks. 
Using `decimal '12345678901.123400000'` solves the issue.
