### ISSUE TITLE
Implement JSON predicates

### ISSUE THREAD

**Issue by wenleix** [prestodb/presto#9260]
Update: We should use JSON predicate defined in SQL:2016. See the second comment.

-------------------------------------------------------

```SQL
is_json_scalar(JSON 'null') -> true
is_json_scalar(JSON 'true') -> true
is_json_scalar(JSON 'false') -> true
is_json_scalar(JSON '123') -> true
is_json_scalar(JSON '"abc"') -> true

is_json_scalar(JSON '[1, 2, 3]') -> false
is_json_scalar(JSON '{"a": 1, "b": 2'}') -> false
```

This will help to have the same functionality  of Hive's [get_json_object](https://cwiki.apache.org/confluence/display/Hive/LanguageManual+UDF#LanguageManualUDF-get_json_object), which has slightly different behavior depends on whether the extracted JSON is a JSON scalar or not:

```SQL
SELECT 
apply(json_extract(...), 
      x -> if(is_json_scalar(x), cast(x as varchar), json_format(x)))
```

## Questions
- Should the function name be `is_json_scalar` or `is_scalar`?
- Should we make `apply` an open lambda function? cc @haozhun

**Comment by shixuan-fan** [comment]
I guess `is_scalar` is kind of vague if we only take JSON as input?

**Comment by wenleix** [comment]
We should use the JSON predicate syntax defined in SQL:2016:

<img width="811" alt="screen shot 2017-11-27 at 22 14 43" src="https://user-images.githubusercontent.com/799346/33304943-90d06692-d3c0-11e7-97f6-5ebd2de1716d.png">

According to spec, JSON null is considered as JSON Scalar:

<img width="737" alt="screen shot 2017-11-27 at 22 21 05" src="https://user-images.githubusercontent.com/799346/33305102-56486abe-d3c1-11e7-8fa5-5278e235ef92.png">


In conformance rules, SPEC says:

```
Without Feature T821, “Basic SQL/JSON query operators”, conforming SQL language shall not contain <JSON predicate>.
```

**Comment by shixuan-fan** [comment]
Per offline discussion with @wenleix and @martint , we will implement `is_json_scalar` function. `<JSON predicate>` requires the operand type to be string (varchar), which needs further consideration.
