### ISSUE TITLE
Unable to Fetch Result on Decimal Type With Equal To Operator 

### ISSUE THREAD

**Issue by anubhav100** [prestodb/presto#9263]
created a orc table in hive metastore with presto 

1. presto:default> create table test2(id decimal(7,3)) with(format='orc');
CREATE TABLE

2. presto:default> insert into test2 values(decimal '1234.444');
INSERT: 1 row

query the data from hive metastore

3. presto:default> select * from test2 where id=1234.444;
 id 
----
(0 rows)

i got no result here but if instead of = operator when i used >= it works fine

4. presto:default> select * from test2 where id>=1234.444;
    id    
----------
 1234.444 
(1 row)

**Comment by sopel39** [comment]
Hi @anubhav100 

Currently numeric literals are of `DOUBLE` type and `DECIMALS` coerce to `DOUBLE`. When you write `id=1234.444` then `id` will be coerced to `DOUBLE`. However, there might not be an exact double representation of a decimal. Therefore equality comparison might fail. 

To fix the comparison (e.g: to do what you intended) you can just write:
```
presto:default> select * from test2 where id=DECIMAL `1234.444`;
```

**Comment by anubhav100** [comment]
@sopel39  Hi,what if my decimal value exceeds range of double then there be data loss,how it will be handled ?

**Comment by sopel39** [comment]
Decimal range (min, max value) is tighter than double range. However, big decimal numbers won't have exact double representation. In that case, the decimal would be converted to the closest double value.

**Comment by anubhav100** [comment]
step1:CREATE TABLE

presto:default> create table hive.default.decimaltest(a decimal(11,4),b decimal(19,4));
CREATE TABLE

step 2:
presto:default> insert into hive.default.decimaltest values(Decimal '12.11', Decimal '1234567.8899');
INSERT: 1 row

Query 20171103_065648_00010_4hcp6, FINISHED, 1 node
Splits: 51 total, 51 done (100.00%)
0:01 [0 rows, 0B] [0 rows/s, 0B/s]

step 3:query the table

presto:default> select b from hive.default.decimaltest where b =1234567.8899;
      b       
--------------
 1234567.8899 
(1 row)

@sopel39  in this scenario i didn't prefix the decimal keyword then how does this works

**Comment by sopel39** [comment]
> in this scenario i didn't prefix the decimal keyword then how does this works i get the right result

It could be that `1234567.8899` has an exact double representation. Generally comparing doubles by equality is not recommended.

**Comment by findepi** [comment]
@anubhav100 FYI, #9369 will make it possible to treat literals e.g. `1234.444` as DECIMAL even without `DECIMAL '...'`.
(This is going to be behind a feature toggle for some time)
