### ISSUE TITLE
presto impersonate a simple user on non-kerberos/non-hdfs hivemetastore setup?

### ISSUE THREAD

**Issue by tooptoop4** [prestodb/presto#9265]
Apache Drill allows user impersonation like below, does Presto allow similar? 
ie hostA runs hive, mysql, hivemetastore,ranger. Hive is run on linux file system not hdfs of hostA. hostB runs Presto. Ranger allows certain users to view certain tables in hive. Can presto 'login' to the metastore as various hive users or just the unix user running presto-cli? Assume not all hive users have unix accounts.

{
  "type": "hive",
  "enabled": true,
  "configProps": {
    "hive.metastore.uris": "thrift://host:9083",
    "javax.jdo.option.ConnectionURL": "jdbc:mysql://host:3306/metastore",
    "javax.jdo.option.ConnectionDriverName": "com.mysql.jdbc.Driver",
    "javax.jdo.option.ConnectionUserName": "bill",
    "javax.jdo.option.ConnectionPassword": "pass",
    "hive.metastore.warehouse.dir": "file:///home/ec2-user/warehouse",
    "fs.default.name": "file:///"
  }
}

**Comment by electrum** [comment]
If you set `hive.security=sql-standard`, the Hive connector will perform authorization checks against the metastore using the privileges defined in the metastore.

**Comment by electrum** [comment]
See https://prestodb.io/docs/current/connector/hive-security.html

**Comment by tooptoop4** [comment]
what user will presto use to connect to hive? how do you pass in hive user/password to presto? especially if hive using unkerborised linux filesystem not hdfs/s3.

**Comment by electrum** [comment]
Unless you’re using Kerberos, there is no user or authentication for the metastore.

**Comment by leolorenzoluis** [comment]
@electrum What needs to be done in order to support plain user authentication to the metastore?

**Comment by arhimondr** [comment]
@leolorenzoluis I never heard about plain authentication for Metastore. As far as i know the only option is Kerberos authentication. Could you please point to the plain authentication documentation?

**Comment by leolorenzoluis** [comment]
@arhimondr I mean impersonation.  https://prestodb.io/docs/current/connector/hive-security.html

> Impersonation Accessing the Hive Metastore
> Presto does not currently support impersonating the end user when accessing the Hive metastore.
