### ISSUE TITLE
localfile npe

### ISSUE THREAD

**Issue by mikebell90** [prestodb/presto#9276]
The LocalFileRecordCursor has a somewhat embarassing boog

```
  @Override
  public boolean isNull(int field)
  {
      checkArgument(field < columns.size(), "Invalid field index");
      String fieldValue = getFieldValue(field);
      log.info("field, fieldValue" + field + " " + fieldValue);
      return fieldValue.equals("null") || Strings.isNullOrEmpty(fieldValue) 
  }
```

If the value is null (which is the case for the TEST data btw due to extra rows at end!), it will NPE.
Fix is trivial - reverse the OR clauses or the the equals test ("null".equals(fieldValue)). Not sure I have time right now for a PR, so just documenting.

**Comment by findepi** [comment]
@mikebell90 good catch! I encourage you to make a PR with a fix.
