### ISSUE TITLE
Add Modernizer checks for default Charset and Locale

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#9278]
Examples of error prone functions:

* `String(byte[])`
* `String.getBytes()`
* `String.toLowerCase()`
* `String.toUpperCase()`
* `new FileReader(..)`

Any existing usages should be fixed in one commit, then a second commit should add the checks that ban the usages.

**Comment by findepi** [comment]
FWIW Findbugs has some coverage for that http://findbugs.sourceforge.net/bugDescriptions.html#DM_DEFAULT_ENCODING

**Comment by electrum** [comment]
SpotBugs code for `DM_DEFAULT_ENCODING`: https://github.com/spotbugs/spotbugs/blob/master/spotbugs/src/main/java/edu/umd/cs/findbugs/detect/DefaultEncodingDetector.java

**Comment by findepi** [comment]
@electrum is your intention to extract the blacklist from spotbugs's code na define modernizer checks based on that?
assuming we won't keep the lists in sync, what about running spotbugs over the code base, but having only `DM_DEFAULT_ENCODING` enabled?
