### ISSUE TITLE
Create reusable type mapping tests for JDBC connectors

### ISSUE THREAD

**Issue by findepi** [prestodb/presto#9290]
Type mapping between Presto and external database accessed by JDBC connector is done in `BaseJdbcClient` (`presto-base-jdbc`). While implementation is shared, correctness should be integration-tested against each database we have connector for (currently: postgresql, sqlserver, mysql). This should be implemented as reusable test (like `AbstractTestQueries`) with possibility to disable selected tests by a concrete connector e.g. for unsupported types.

Context https://github.com/prestodb/presto/pull/9285#issuecomment-341991161

**Comment by kbajda** [comment]
Also relevant for the Redshift connector.

**Comment by ArturGajowy** [comment]
[This and the 4 following tests](https://github.com/prestodb/presto/blob/master/presto-mysql/src/test/java/com/facebook/presto/plugin/mysql/TestMySqlDistributedQueries.java#L97) might be of help/inspiration :)

**Comment by findepi** [comment]
@ArturGajowy thanks! Do you recall why the data mapping tests are distributed?
(That's probably why I didn't find them 🙂  )

**Comment by ArturGajowy** [comment]
No idea, probably because the original tests that were refactored into that DSL were distributed. As far as I see, there's no dependency on the tests being distributed. But maybe @sopel39 will know? He started the CHAR/VARCHAR work.

**Comment by sopel39** [comment]
> Do you recall why the data mapping tests are distributed?

I don't thing there is any particular need for them to be distributed.

**Comment by sopel39** [comment]
Also if the test don't need to be distributed then we could possibly extend `LocalQueryRunner` to have method similar to: `Pair<MaterializedResult, Page> LocalQueryRunner::execute`. Then we could additionally test if connector writes correct representation of data types. We could for instance validate that char blocks returned by connector don't have trailing spaces.

CC: @ArturGajowy

**Comment by ArturGajowy** [comment]
> char blocks returned by connector don't have trailing spaces.

Don't the current tests check that?

**Comment by sopel39** [comment]
> Don't the current tests check that?

I don't think so, they only check that `MaterializedResult` is equal to inserted value? I don't think this implies that Slice representation is correct for instance.

**Comment by findepi** [comment]
Surely the current tests do not do this. Hence #9282 (the bug was not about incorrect semantics, but about incorrect cast implementation).
