### ISSUE TITLE
PostgreSQL SQL Grants

### ISSUE THREAD

**Issue by HariSekhon** [prestodb/presto#9291]
The latest docs for 0.188 say that the PostgreSQL connector doesn't support SQL Grants.

Given that the catalog definition for only has a single "connection-user" the PostresSQL native grants would not be able to differentiate between Presto users connecting through to PostgreSQL so it looks like it would be all or nothing access right now, which means there is currently no authorization for PostgreSQL in Presto and will be DoA in security conscious environments.

Any chance of adding SQL Grants support for PostgreSQL connector?

I'm looking here:

https://prestodb.io/docs/current/connector/postgresql.html

**Comment by HariSekhon** [comment]
Also relates to getting Ranger integration #8980

**Comment by findepi** [comment]
Please follow https://github.com/prestodb/presto/pull/11475

**Comment by findepi** [comment]
Related: https://github.com/prestodb/presto/pull/11475. This is roles/grants support for Hive connector. Postgres connector can build on that.
