### ISSUE TITLE
presto hive metastore refresh error when kerberos is enabled

### ISSUE THREAD

**Issue by pi9nc** [prestodb/presto#9292]
hi, i have a presto cluster(0.187) with kerberos enabled.

in order to speed up the access of hive connetor, i configure the metastore cache policy with the following properties:
   

- hive.metastore.authentication.type=KERBEROS

- hive.metastore-cache-ttl= 2h

- hive.metastore-refresh-interval= 30m

but when i restart the cluster,the log shows some kerberos error,
 
![image](https://user-images.githubusercontent.com/4282133/32450673-c400afd0-c34f-11e7-82b1-d55eddf5d149.png)

from the source code, i think the metastoreAuthentication is not properly setted.
![image](https://user-images.githubusercontent.com/4282133/32450807-2a24e38a-c350-11e7-9049-2f98cf60d2ea.png)

anyone get any idea of this?

**Comment by akshatnair** [comment]
Do you have other related properties set for KERBEROS authentication? There is a troubleshooting guide
https://community.teradata.com/t5/Presto/Presto-Kerberos-Troubleshooting/td-p/70691

BTW not sure why you are enabling KERBEROS to speed it up? Did it always use Kerberos for authentication?

**Comment by akshatnair** [comment]
I am going to close this as it is not an issue for Github but feel free to post for on the Presto-users Google group for troubleshooting issues.
