### ISSUE TITLE
Integer overflow possible when multiplying INTERVAL YEAR TO MONTH and INTEGER

### ISSUE THREAD

**Issue by findepi** [prestodb/presto#9342]
Currently we detect integer overflow when multiplying `INTEGER` values:
```
presto> select 256 * 256 * 256 * 256;
Query 20171114_154126_00068_9ghqy failed: integer multiplication overflow: 16777216 * 256
```

However, when multiplying `INTERVAL YEAR TO MONTH` and `INTEGER` values overflow is silently ignored:
```
presto> select (INTERVAL '1' YEAR) * 256 * 256 * 256 * 256;
 _col0
-------
 0-0
(1 row)
```

**Comment by photogamerun** [comment]
I did a workaround to support this senario by enhance  the Antlr  grammar
presto:default> select 256l * 256l * 256l * 256l;
   _col0    
------------
 4294967296 
(1 row)

**Comment by haozhun** [comment]
A fix for this should cover both `INTERVAL YEAR TO MONTH` and `INTERVAL DAY TO SECOND`.

A fix for this should cover `add`, `subtract`, `multiply`, `divide`, `negate`.

In particular, divide and 2 variants of multiply involves math with double. They should observe the same high level rule of SQL, i.e. `clamping` (lose any leading significant digits after rounding or truncating) is not allowed.
