### ISSUE TITLE
Add product test for multinode-tls with Kerberos and Client Certificates

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#9356]
We should validate that both of these authentication modes work with secure internal communication.

**Comment by kokosing** [comment]
AFAIR we do not have such product tests. All we have is to have docker cluster configured in a way that certain authentication modes are enabled and then we run some basic product tests consisting of table scan, insert, update etc.

That would mean we need to prepare docker cluster with coordinator and workers configured to use tls and Kerberos and then run product tests. Is it this what you want? Then would you like to run this in regular travis build in the job with PRODUCT_TEST_SPECIFIC_ENVIRONMENT?

Hopefully, no new docker images are needed. It looks like only new testing profile has to be added and  it can be configured in docker-compose level.

Can you please say something about your motivation for this? Why do you think it is important? It seems that we have both multinode-tls and singlenode with kerberos with client certificates. Why do you think we need to merge this together? AFAIR even when singlenode is used, communication between coordinator and worker (in the same JVM) uses the same communication mechanism as in multinode case, that would mean the most cases are covered. What is it missing? 

After this task is fixed then maybe we could remove simple multinode-tls and singlenode-kerberos profiles, as the merged one covers them both, don't you think? Having many docker profiles is hard to maintain.

**Comment by electrum** [comment]
I’m not familiar enough with the setup to comment on how it should work.

The motivation is that making sure internode communication works when you are using authentication. The CLI and JDBC use a different HTTP client, so we have zero test coverage for this scenario. In fact, Kerberos broke in the latest release (Jetty client SPNEGO change which isn’t tested).

**Comment by kokosing** [comment]
I will give it a shoot. However I do not to promise you any date.

**Comment by kokosing** [comment]
WIP PR: https://github.com/prestodb/presto/pull/9368

**Comment by kokosing** [comment]
@electrum Can you please share more details about this configuration (you can simply comment in the mentioned WIP PR)?
As I understand you have cluster where nodes comminucation is secured with TLS and coordinator node requires Kerberos authentications for client to connect, am I right? If so it looks like client and workers communicate with coordinator on different secured port. Is it possible to expose two different https server ports with one Presto node? Or how worker can avoid kerberos authentication when connecting to coordinator.

**Comment by electrum** [comment]
Sorry for the confusion. TLS client certificates and Kerberos are separate tasks. So we need two additional setups, one for Kerberos and one for certs.

Related, Presto now supports multiple auth modes, so the mixed mode setup you mentioned should also work, but that’s yet another task. All auth modes work over the same port. If the client presents a cert, it will be used. Otherwise we do Kerberos.

**Comment by kokosing** [comment]
Environment with TLS client certificates already exists, see https://github.com/prestodb/presto/tree/master/presto-product-tests#running-the-product-tests
> multinode-tls - psuedo-distributed Hadoop installation running on a single Docker container and a distributed Presto installation running on multiple Docker containers. Presto is configured to only accept connections on the HTTPS port (7878), and both coordinator and worker traffic is encrypted. For multinode-tls, the default configuration is 1 coordinator and 2 workers.

Here https://github.com/prestodb/presto/pull/9368 I am adding enviromnemnt with is using TLS internally and master is also using kerberos.
