### ISSUE TITLE
Limit does not terminate query when underlying query is highly selective

### ISSUE THREAD

**Issue by haozhun** [prestodb/presto#9357]
NOTE: "Merge tiny pages" (or any issue related to operator level buffering) is beyond the scope of this post.

# What happened?

Take a task with 3 pipelines for example. For simplicity, let's assume
* Each pipeline has only 1 driver.
* Limit is 1.
* ScanFilterProject will produce 1 element total.

The first assumption is quite unlikely, especially for `Driver C`. However, this doesn't matter. When these assumptions don't hold, it may appear that there are more failure scenarios. But they all have the same root cause.

Below is the operators that belong to each driver.

```
     Driver A          Driver B             Driver C

    TaskOutput
        |            LocalExSink (X)      LocalExSink (Y)
      Limit                |                    |
        |            LocalExSrc (Y)     ScanFilterProject
  LocalExSrc (X)
```

Here is the sequence of event when a row hits the limit operator:

1. `Limit` got marked as finished.
2. `TaskOutput` got marked as finished (`Driver.processInternal` propagates finish through drivers upwards)
3. `Driver A` got marked as finished (`Driver.isFinishedInternal` returns true if last operator is finished)
4. `LocalExSrc (X)` got teared down (`TaskRunner.run` calls `split.destroy()` if `split.isFinished()`)
5. LocalExchange for X got teared down because the only consumer is closed.
6. Things that didn't happen:
  * The future that Driver B previously returned from its `isBlocked` method didn't unblock. (This will be discussed below.)
  * If `LocalExSink.isFinished` had been invoked, it would return true. But it didn't get invoked.
  * `SqlTaskExecution.checkTaskCompletion` didn't mark the task as finished because the task still has live drivers. (In this particular case, one could argue that the task should be teared down because the only writer to the task output buffer is closed. But in a more general case, this argue may not stand. This is not the root cause, although it could be a valid optimization.)

Now, let's look at `Driver B` and see why it did not unblock.

The code below plays a key role in how a Driver enters and exits blocked state. It is simplified (based on `Driver.processInternal`) for illustrative purpose:

```
List<ListenableFuture<?>> blockedFutures = new ArrayList<>();
for (Operator operator : operators) {
    ListenableFuture<?> blocked = operator.isBlocked();
    if (!blocked.isDone()) {
        blockedFutures.add(blocked.get());
    }
}
if (!blockedFutures.isEmpty()) {
    return firstFinishedFuture(blockedFutures);
}
return NOT_BLOCKED;
```

Immediately after the one single row is propagated through `Driver B`
* `LocalExSrc (Y)` is blocked because its input buffer is empty.
* `LocalExSink (X)` is not blocked because the its output buffer is not full. It will be happily accept more inputs whenever input is available.

As a result, transition of `LocalExSink (X)` from one "not blocked" state to another "not blocked" state does not affect the blocked state of `Driver B`. Although `LocalExSink (X)` transitioned from "no output" to "finished", `Driver B` did not wake up.

In this case, since `Driver C` is not going to produce any pages anymore, the query will not tear down until table scan finishes.

# My proposal

Below shows the current and proposed states that represent the "block"edness of operators. Arrow represents the transitions that matters (i.e. transitions that signal a driver may need to be woken up).

```
operator states (current)

                              +-------------+
   +------------------------> | not blocked |
   |                          +-------------+
   |
   |                          +-------------+
   +------------------------- |   blocked   |
                              +-------------+

operator states (proposed)

 (e.g. exchange sink operator went from "full" to "finished")
   +------------------------> +----------------------+
   |                          | has output           |
   |                          | (including finished) |
   |   +--------------------> +----------------------+
   |   | (e.g. exchange sink operator went from "not full" to "finished")
   |   +--------------------- +-------------------+
   |                          | don't have output |
   |                          | need input        |
   |   +--------------------> +-------------------+
   |   | (e.g. exchange sink operator went from "full" to "not full")
   |   +--------------------- +---------------------+
   |                          | don't have output   |
   |                          | not ready for input |
   +------------------------- +---------------------+
```

**Comment by sopel39** [comment]
I wonder if just having separate states for INPUT and OUTPUT wouldn't be cleaner instead of having such combined states (e.g: `don't have output and not ready for input`).

Do you plan for the current blocked future to return new state or the to refactor the future so that it signals a state change? 

Finally, I wonder if in longer term it would be beneficial to extend mechanism of `Work` to the operator level (e.g: maybe as in https://github.com/prestodb/presto/issues/8697). Pipeline execution would be then top-down based while operators would be pull based. Currently operators are push and pull at the same time and I feel this introduces additional complexity and edge cases.

**Comment by haozhun** [comment]
My current thought is along the lines of "refactor the future so that it signals a state change". However, I would like it to be implemented in such a way that the author will think about the 3 states when they write a new operator. But then again, new operators don't come up that often. As a result, it's likely not worth it if it makes things more complicated. I haven't made up my mind yet.

**Comment by sopel39** [comment]
> I see that doing it in a blocked way makes implementation easier

I think just making operators one-directional (e.g: pull based) would make implementation easier.

> I don't understand how #8697 would work

Maybe the naming isn't the best (e.g: it probably should be named `AsyncSource`). The idea is exactly to handle sources that could potentially block, but instead of blocking wait for the source to complete, caller should use `BlockingSource::isFinished` first to ensure that `BlockingSource::next` won't block. 

> I don't understand how #8697 would work. I see that doing it in a blocked way makes implementation easier. But how will time slicing between operators work with this blocking scheme?

For that matter I think `BlockingSource#next` could act as `Work#process` (e.g: try to get result), but I think this should be explicitly stated. I will try to make it clearer and extend the idea of `Work`.

**Comment by sopel39** [comment]
@haozhun this is what I have in mind for longer term: https://github.com/prestodb/presto/issues/9470
