### ISSUE TITLE
PrestoDB No nodes available to run query with Hive

### ISSUE THREAD

**Issue by annisun** [prestodb/presto#9360]
coordinator=true
node-scheduler.include-coordinator=false
http-server.http.port=8080
query.max-memory=50GB
query.max-memory-per-node=1GB
discovery-server.enabled=true
discovery.uri=http://172.16.9.100:8080

connector.name=hive-hadoop2
hive.metastore.uri=thrift://172.16.9.100:9083
hive.config.resources=/etc/hadoop/conf/core-site.xml,/etc/hadoop/conf/hdfs-site.xml
hive.force-local-scheduling=true

this is Configuration of my master node,
I running  the query "select * from incentive_pl.incentive_pl_detail limit 1000",

it's throw the error ：
![lalpbbcc1sntqd_nahnnbca_1056_537](https://user-images.githubusercontent.com/26518100/32928873-3fc46048-cb8f-11e7-8aef-13bb00341129.png)

what‘s happened about presto?

**Comment by zhaiyuyong** [comment]
how much nodes?

**Comment by annisun** [comment]
10 nodes 




------------------
DT Team   ---　李焰
skype: dm_sj_itly
Tel:15625255565
创颖峻网络科技（深圳）有限公司
 

 
 
 
------------------ Original ------------------

**Comment by zhaiyuyong** [comment]
use presto-cli   execute  "select * FROM system.runtime.nodes"  
show the nodes status

**Comment by annisun** [comment]
this picture is the result







------------------
DT Team   ---　李焰
skype: dm_sj_itly
Tel:15625255565
创颖峻网络科技（深圳）有限公司
 

 
 
 
------------------ Original ------------------
