### ISSUE TITLE
How To Use Preaggreate Tables In Our Custom Connector

### ISSUE THREAD

**Issue by anubhav100** [prestodb/presto#9364]
I have created Preaggregate Tables in my connector is there a way to change presto query plan so that it will query my preaggreagate table

**Comment by kokosing** [comment]
What does it mean `Preaggregate Tables`? What does it mean `my connector`?

**Comment by anubhav100** [comment]
@kokosing i am working on custom connector for a input format that i am using with presto and preaggregate tables contains the result of aggregate functions like count() and sum()

**Comment by anubhav100** [comment]
@kokosing what i really means is can i push down my aggregates at presto level?

**Comment by electrum** [comment]
This is not currently supported by the connector interface. You will need to expose them as normal tables and write queries to reference them explicitly.

**Comment by anubhav100** [comment]
@electrum can i change the logical plan of query in presto?

**Comment by electrum** [comment]
Not without changing the planner in the engine.
