### ISSUE TITLE
Hive Offline Partition can be deleted from Presto side

### ISSUE THREAD

**Issue by wenleix** [prestodb/presto#9371]
When a partition is offline, both the partition and the table cannot be dropped from Hive side:

```
hive>
       >
       > alter table test_wxie_part drop partition(ds='2017-10-01');
Command ran:
1: alter table test_wxie_part drop partition(ds='2017-10-01')

FAILED: SemanticException [Error 30011]: Partition protected from being dropped di@test_wxie_part@ds=2017-10-01. To drop this partition anyway, add "IGNORE PROTECTION" to the end of your command.


hive > drop table test_wxie_part;
Starting task [DDLTask{id=Stage-0, name=DDL}] in serial mode
FAILED: Error in metadata: {Table test_wxie_part Partitionds=2017-10-01 is protected from being dropped}. 
```

But both partition and table can be dropped from Presto side.

`presto_offline` has the same behavior.

**Comment by wenleix** [comment]
See https://github.com/prestodb/presto/pull/3687 for Metadata Delete support

**Comment by electrum** [comment]
This is a job for the metastore. Every consumer of the metastore shouldn’t have to enforce every constaint. That’s the whole point of having an API.
