### ISSUE TITLE
Introduce a type-safe visitor in the SPI for all standard types

### ISSUE THREAD

**Issue by findepi** [prestodb/presto#9410]
Sometimes a block of code needs to do different things depending on `Type` passed. When differentiating isn't handled by Type's API, we need to resort to `if instanceof` checks for all the types. A `TypeVisitor` could be used instead to make sure all types are properly covered.

**Comment by findepi** [comment]
cc @electrum @martint

**Comment by electrum** [comment]
One consideration is that the visitor should be resolved / bound up front, rather than having the if-chain happen for each value. There’s also the question of how to make it work with nested / structural types.
