### ISSUE TITLE
why still codeCache workaround  ?

### ISSUE THREAD

**Issue by zhaiyuyong** [prestodb/presto#9411]
```java
// workaround for CodeCache GC issue
        if (JavaVersion.current().getMajor() == 8) {
            configBinder(binder).bindConfig(CodeCacheGcConfig.class);
            binder.bind(CodeCacheGcTrigger.class).in(Scopes.SINGLETON);
        }
https://github.com/prestodb/presto/pull/2123

**Comment by electrum** [comment]
The bug was re-introduced (came back) in the JVM, so we had to restore the workaround.

**Comment by zhaiyuyong** [comment]
it is recommended to expose a parameter control.

**Comment by martint** [comment]
@electrum, I don't think this is an issue any more. We've been meaning to remove that class.

**Comment by nezihyigitbasi** [comment]
Some time ago I tried to reproduce this with Java 1.8.133 (IIRC) using @martint's test (https://github.com/martint/jittest) and I couldn't, so the bug is probably fixed.

**Comment by martint** [comment]
https://github.com/prestodb/presto/pull/9418

**Comment by nezihyigitbasi** [comment]
Closing as #9418 is merged.
