### ISSUE TITLE
the new version is worse than the old one, has anyone ever met?

### ISSUE THREAD

**Issue by zhaiyuyong** [prestodb/presto#9414]
presto0.123  presto185
the same jvm.config 
-server
-Xmx66G
-XX:+UseG1GC
-XX:G1HeapRegionSize=64M
-XX:+UseGCOverheadLimit
-XX:+ExplicitGCInvokesConcurrent
-XX:+HeapDumpOnOutOfMemoryError
-XX:OnOutOfMemoryError=kill -9 %p
-XX:+AggressiveOpts
-XX:+UseNUMA
-XX:ReservedCodeCacheSize=512M
-verbose:class
-XX:+PrintGCApplicationConcurrentTime
-XX:+PrintGCApplicationStoppedTime
-XX:+PrintGCCause
-XX:+PrintGCDateStamps
-XX:+PrintGCTimeStamps
-XX:+PrintGCDetails
-XX:+PrintReferenceGC
-XX:+PrintClassHistogramAfterFullGC
-XX:+PrintClassHistogramBeforeFullGC
-XX:PrintFLSStatistics=2
-XX:+PrintAdaptiveSizePolicy
-XX:+PrintSafepointStatistics
-XX:PrintSafepointStatisticsCount=1
-Xloggc:/data2/presto/data/var/log/presto-gc.log

**Comment by kokosing** [comment]
In what aspect of Presto functionality you experience worse behavior? Have you tried to use Presto mailing list first, as it is not known yet if your issue is related with Presto code or the way you use it (configuration, etc)?

**Comment by kokosing** [comment]
Please try to post as much details as you can, otherwise we are unable to help you.

**Comment by findepi** [comment]
@zhaiyuyong , since there are no details here yet, let's move the discussion to the mailing list.

**Comment by electrum** [comment]
Note that those releases are about two years apart, and in that time there have been thousands of changes.
