### ISSUE TITLE
SetSessionTask does not validate that value decodes

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#9433]
We allow setting an invalid session property, causing the CLI (or other client) to get stuck with the invalid value (which can't be changed because future queries are rejected).

```
presto> set session iterative_optimizer_timeout = 'xxx';
SET SESSION           

presto> select 123;
Query 20171129_055858_00027_aw6kc failed: iterative_optimizer_timeout is invalid: xxx

presto> set session iterative_optimizer_timeout = '5s';
Query 20171129_055907_00028_aw6kc failed: iterative_optimizer_timeout is invalid: xxx
```
Note that other types of errors, such as using the wrong type or setting a property which doesn't exist, are validated properly.

**Comment by findepi** [comment]
@electrum did you see #6741 ?
