### ISSUE TITLE
Query about libprocname and launcher script.

### ISSUE THREAD

**Issue by asowani** [prestodb/presto#9443]
Hi,

I come from C/C++ development background and new to maven based builds. I am evaluating Presto on ppc64le and faced an issue with libprocname - x86_64 version of this library gets included in the RPM. I want to fix this issue by including platform specific (ppc64le) version if procname library. I looked at Presto code to see how this library is pulled or built but can't figure it out. For that matter I am not sure how the launcher script also gets in the RPM.

Can somebody educate me on how procname library gets included? Or if there is some elaborate documentation about this, please direct me to it.

Thanks in advance!
Atul.

**Comment by asowani** [comment]
Well, I think I understand this issue a bit. While building I think maven downloads certain packages from maven repositories. For example: 
https://oss.sonatype.org/content/repositories/snapshots/com/facebook/presto/presto-server/0.190-SNAPSHOT/presto-server-0.190-20171129.081641-51.tar.gz

Now this package contains libprocname which is built for x86_64. Now who owns these repositories and what is the procedure to update the tarball in those repositories? Any idea? Thanks!

**Comment by electrum** [comment]
* `presto-server-rpm` is built by unpacking the `presto-server` tarball via the `maven-dependency-plugin`: https://github.com/prestodb/presto/blob/master/presto-server-rpm/pom.xml
* `presto-server` builds a tarball that includes the Airlift launcher: https://github.com/prestodb/presto/blob/master/presto-server/src/main/provisio/presto.xml
* Airlift launcher includes `libprocname.so`: https://github.com/airlift/airlift/tree/master/launcher/src/main/resources/procname/Linux-x86_64
* procname is here: https://github.com/airlift/procname

**Comment by electrum** [comment]
When you build `presto-server-rpm`, it has a dependency on `presto-server`. If that artifact is already in your local repository and the snapshot has not expired (I think Maven expires them at midnight), it will be used. If you do a build of `presto-server` or the whole project with `mvn install`, it will install into your local repository.

The snapshot repository on **oss.sonatype.org** is published to periodically by a CI server run by the Presto team.

**Comment by electrum** [comment]
Support in Airlift: https://github.com/airlift/airlift/pull/581

**Comment by asowani** [comment]
@electrum Thanks for the info - I think it explains the process in fair details. I will start my exploration using this data. Thank you! :)
