### ISSUE TITLE
Determine strategy for running product-tests with Java 9

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#9491]
The Docker images currently contain Java 8, so we might need additional images (and have to keep both around until we fully move to Java 9 and drop support for Java 8).

**Comment by sopel39** [comment]
FYI: @ilfrin @kokosing

**Comment by kokosing** [comment]
Docker images with java8 are pushed to docker hub, so we might do a migration to java9 in docker-images of all the images there and push images to hub. That way we will have both kind of images available on dockerhub. In case of regression of java8, we could do hotfix brach (forked from master before the migration) and release new docker images, hope it won't happen.

Is there are work in progress somewhere with java9 migration? I could contribute product-tests migration part of work.
