### ISSUE TITLE
Ask a question about the command - show create table XXX

### ISSUE THREAD

**Issue by hugoren** [prestodb/presto#9513]
Why doesn't this command display an index？
Is it a matter of consideration？
Thank you for your answer

**Comment by ebyhr** [comment]
FYI, the information are managed in [Help.java](https://github.com/prestodb/presto/blob/c73359fe2173e01140b7d5f102b286e81c1ae4a8/presto-cli/src/main/java/com/facebook/presto/cli/Help.java)
