### ISSUE TITLE
CLI should refuse to work with expired certificates in --keystore-path

### ISSUE THREAD

**Issue by findepi** [prestodb/presto#9516]
When running product tests we're using `docker.cluster.jks` file that contains an expired certificate. 
CLI should by default refuse to authenticate server when server uses an expired certificate, but it doesn't do that (not only in tests, at least when `--keystore-path` is specified).

**Comment by electrum** [comment]
This will also be a problem for JDBC. I'm surprised the default JDK trust manager would accept expired certificates.
