### ISSUE TITLE
How to use Presto's mysql-connector to convert a Presto's sql query in hive or other catalogs into a entity table in mysql?

### ISSUE THREAD

**Issue by pengshuang** [prestodb/presto#9523]
I am a new bird for Presto. Recently I am faced with a task to convert a Presto's sql query in hive into an entity table in mysql? Like this:

`CREATE TABLE mysql.t1 AS SELECT c1, c2 from hive.t2 where ...`

I find many Presto's document but I can't find any solutions. Can anyone help me solve it?

**Comment by findepi** [comment]
@pengshuang `CREATE TABLE ... AS SELECT ...` can definitely be used, could you describe your problem better? 

I encourage you to join user group https://groups.google.com/group/presto-users

**Comment by pengshuang** [comment]
Thanks, I see!
