### ISSUE TITLE
Support extracting milliseconds from a timestamp

### ISSUE THREAD

**Issue by findepi** [prestodb/presto#9524]
```
presto> select extract(second from (timestamp '2017-10-24 23:00:23.206'));
 _col0
-------
    23
```

but
```
presto> select extract(millisecond from (timestamp '2017-10-24 23:00:23.206'));
Query 20171208_215149_00048_uhmtc failed: line 1:8: Invalid EXTRACT field: millisecond
```

IMO this should be supported.

**Comment by ebyhr** [comment]
Started implementing this enhancement. Probably, `time` is also needed?

```
presto> select extract(millisecond from (time '23:00:23.206'));
Query 20171211_071755_00000_ymkvm failed: line 1:8: Invalid EXTRACT field: millisecond
```

**Comment by findepi** [comment]
Yes, this could be useful for `time` too (and `time with time zone`, `timestamp with time zone`).

However, @ebyhr I'd suggest that you wait until #9385 is merged (a big change around temporal values handling and I'd really prefer to avoid conflicts there).
Last but not least, I think it would be good if @martint ACK-ed this enhancement too.

**Comment by martint** [comment]
```
select extract(second from (timestamp '2017-10-24 23:00:23.206'));
 _col0
-------
    23
```

Hmm.. that's actually incorrect. It should return `23.206`, per the SQL spec:

```
7) If <extract expression> is specified, then 
  Case:
  a) If <extract field> is a <primary datetime field> that does not specify SECOND [...]
  b) Otherwise, the declared type of the result is an implementation-defined exact 
     numeric type with scale not less than the specified or implied
     <time fractional seconds precision> or <interval fractional seconds precision>, 
     as appropriate, of the SECOND <primary datetime field> of the <extract source>.
```

and 

```
Values in interval fields other than SECOND are integers and have precision 2 
when not the first field. SECOND, however, can be defined to have an 
<interval fractional seconds precision> that indicates the number of decimal 
digits maintained following the decimal point in the seconds value. When not 
the first field, SECOND has a precision of 2 places before the decimal point.
```

```
4) The maximum value of `<interval fractional seconds precision>` is 
   implementation-defined, but shall not be less than 6.
5) [...]
6) An <interval fractional seconds precision>, if specified, shall be greater than 
   or equal to 0 (zero) and shall not be greater than the implementation-defined 
   maximum. If SECOND is specified and <interval fractional seconds precision>
   is not specified, then an `<interval fractional seconds precision> `of 6 is implicit.
```

Support for milliseconds field is not defined in the specification, but at first glance, it would seem reasonable to add support for it. However, it would introduce an inconsistency that I haven't thought much about yet:

`extract(minute from timestamp '2017-10-24 23:00:23.206')` -> `0`
`extract(second from timestamp '2017-10-24 23:00:23.206')` -> `23.206`
`extract(millisecond from timestamp '2017-10-24 23:00:23.206')` -> `206`

That's because the spec considers the last field (second) to be a catch all that covers everything smaller than a second.

**Comment by findepi** [comment]
So `extract(second from timestamp '2017-10-24 23:00:23.206')` should be changed to have type `decimal(5, 3)`, right?
If we follow this path, we should probably not add `extract(millisecond ...`. But also it would be less needed -- My original use-case (i remember only vaguely) was around some math on individual timestamp fields. And i had to workaround inability to extract (and preserve) milliseconds. If `extract(seconds ...)` preserved milliseconds part too, I would not need to `extract(millisecond ...`.

**Comment by martint** [comment]
> @martint i said decimal(5,3) because our timestamp corresponds to SQL standard's timestamp(3).

I understand where that came from, but I don't think there's anywhere currently in Presto where a precision of 3 is implied. It might as well be `timestamp(6)` but without enough accuracy to have anything other than 0s after the 3rd decimal digit.

**Comment by dain** [comment]
I'm leaning towards saying we should add the `millisecond` functionality for convenience, but when I look forward to the day when we support nano precision, I'm leaf with the question about how we would implement `microseconds` and `nanoseconds`.  Specifically would `microseconds` and `nanoseconds` only return the 3 digits, or would they return `6` and `9` digits?
