### ISSUE TITLE
Allow modulus operation on TIMESTAMP and INTERVAL DAY TO SECOND type

### ISSUE THREAD

**Issue by findepi** [prestodb/presto#9525]
Given table with `timestamp` information, one could want to aggregate this data into 5-second buckets.
Therefore I propose to allow `%` operation between `timestamp`¹ and `interval day to second`.

Thus, `some_timestamp % interval '5' second` would round down the timestamp value to a timestamp that is a multiple of 5 seconds, allowing aggregation.

Currently, the simplest alternative is: `date_trunc('second', some_timestamp) - interval '1' second * (second(some_timestamp) % 5)`

¹) i would be reluctant to allow the same for `timestamp with time zone`, as the semantics would not be as obvious as they would be for `timestamp`

**Comment by sopel39** [comment]
> Given table with timestamp information, one could want to aggregate this data into 5-second buckets.

If you wan't to aggregate data info 5-seconds buckets then you should rather divide by 5 seconds instead of `%`.

> Currently, the simplest alternative is: `date_trunc('second', some_timestamp) - interval '1' second * (second(some_timestamp) % 5)`

Why can't you simply convert timestamp to millis and divide by `5000`

**Comment by findepi** [comment]
First, it's not natural to convert `timestamp` to millis, because `to_unixtime(timestamp)` returns a `double` which needs to be casted to `bigint` before i leverage integer arithmetics (`/ 5`). And then you need to convert the result back to get human-readable timestamp that you can render and not just some bucketing key.

Second, I think I totally screwed this issue up.`%` should by no means do what I wanted it to do, ever. At best, I could `some_timestamp - some_timestamp % interval '5' seconds` which is not much differently from what's possible today.

**Comment by electrum** [comment]
Something like date_trunc() that works for fractional units would be very useful for aggregation. One problem is how to deal with specifications that are not fractions. For example, rounding to 5 minutes is well defined for any hour of the day.  But how would 7 minutes work?

**Comment by findepi** [comment]
@electrum what about revised proposal:
```
date_trunc(unit, n, timestamp) -- e.g. date_trunc('second', 5, some_timestamp)
```

would round `timestamp` to multiple of `n unit`. The constraint would be that `theHigherUnit.to(unit) % n == 0`, so "7 minutes" would not be allowed.
