### ISSUE TITLE
Inadequate representation of temporal types in tests

### ISSUE THREAD

**Issue by findepi** [prestodb/presto#9527]
There are 3 places in tests where for the sake of comparisons we convert data to "common type domain":

* `com.facebook.presto.testing.MaterializedResult#toJdbcTypes`
* `com.facebook.presto.tests.TestingPrestoClient#convertToRowValue`
* `com.facebook.presto.tests.H2QueryRunner#rowMapper`

However, 
1. we use wrong type for `timestamp with time zone`: `java.sql.Timestamp` (so we ignore time zone in comparisons)
   * we also use wrong `timestamp with time zone` literals in H2... H2 doesn't have `timestamp with time zone` literals despite what `com.facebook.presto.tests.AbstractTestQueries#testAtTimeZone` has to say about that
2. we use wrong type for `time with time zone`: `java.sql.Time` (we we ignore timezone/zone offset in comparisons)
3. using JDBC type domain as "common type domain" in tests, makes us to use `java.sql.{Date,Time,Timestamp}` which all extend `java.util.Date` and all bear limitations and discomfort related to this class. 

#### Proposal A (fix `{time,timestamp} with time zone` representation)
* [x] (https://github.com/prestodb/presto/pull/9603) represent `timestamp with time zone` as `java.time.ZonedDateTime` (this is in line with JDBC 4.2 spec suggesting that `java.time.ZonedDateTime` can be used as a representation for `timestamp with time zone`)
* [x] (https://github.com/prestodb/presto/pull/9605) represent `time with time zone` as `java.time.OffsetTime` (currently there seem to be no tests covering political time zones for `time with time zone` and we want to remove support for political time zones for `time with time zone` anyway; this is in line with JDBC 4.2 spec suggesting that `java.time.OffsetTime` can be used as a representation for `time with time zone`)

#### Proposal B (use better types for everything)
* [x] proposal A +
* [x] (https://github.com/prestodb/presto/pull/9632) for `date` use `java.time.LocalDate` rather than `java.sql.Date`
* [x] (https://github.com/prestodb/presto/pull/9647) for `time` use `java.time.LocalTime` rather than `java.sql.Time`
* [x] (https://github.com/prestodb/presto/pull/9647) for `timestamp` use `java.time.LocalDateTime` rather than `java.sql.Timestamp`
* [x] (https://github.com/prestodb/presto/pull/9632) rename `MaterializedResult#toJdbcTypes` to something else, e.g. `toCommonTestTypes`

(I consciously choose not to use Joda Time for tests. They only reason for doing so would be to use the same library we use for execution, which is IMO a false argument.)

related to #9385 
cc @losipiuk @martint @haozhun

**Comment by losipiuk** [comment]
vote +1 for `Proposal B (use better types for everything)` (as long as you have time to address that). It would make tests more explicit and understandable IMO.

**Comment by findepi** [comment]
With `Proposal A (fix {time,timestamp} with time zone representation)` completed and @losipiuk approval for aiming higher, I've started to work on `Proposal B (use better types for everything)`: https://github.com/prestodb/presto/pull/9632
