### ISSUE TITLE
Implement HMAC functions

### ISSUE THREAD

**Issue by martint** [prestodb/presto#9542]
They should be implemented per https://tools.ietf.org/html/rfc2104.

Suggested names: `hmac_sha1`, `hmac_md5`, etc., and should take a VARBINARY key and message.

**Comment by electrum** [comment]
Like the other hashing functions in `VarbinaryFunctions`, these can use the Guava utility methods such as `Hashing.hmacMd5()`.

**Comment by nezihyigitbasi** [comment]
Fixed by https://github.com/prestodb/presto/pull/9565.
