### ISSUE TITLE
Java 9 support

### ISSUE THREAD

**Issue by martint** [prestodb/presto#9558]
Master task to track work need to get Presto working on Java 9.

## Running on Java 9

- [x] https://github.com/airlift/airlift/pull/429
- [x] https://github.com/airlift/airlift/pull/437
- [x] https://github.com/airlift/airlift/pull/446
- [x] https://github.com/airlift/airlift/pull/438
- [x] https://github.com/prestodb/presto/pull/5789
- [x] https://github.com/prestodb/presto/pull/8618
- [x] https://github.com/prestodb/presto/pull/9557
- [x] https://github.com/prestodb/presto/pull/9469
- [x] https://github.com/airlift/airlift/pull/592
- [x] https://github.com/prestodb/presto/issues/9563
- [x] https://github.com/prestodb/presto/pull/9582
- [x] https://github.com/prestodb/presto/pull/9587
- [x] https://github.com/prestodb/presto/pull/9561 (IDE only problem)

## Building with Java 9

- [x] https://github.com/airlift/airbase/pull/125
- [x] https://github.com/airlift/parameternames/pull/8
- [x] https://github.com/airlift/drift/pull/35
- [x] https://github.com/airlift/airlift/pull/593
- [x] https://github.com/airlift/drift/pull/34
- [x] https://github.com/airlift/airbase/pull/129
- [x] https://github.com/prestodb/presto/pull/9568
- [x] https://github.com/airlift/discovery/pull/43
- [x] https://github.com/prestodb/presto/pull/9580
- [x] https://github.com/prestodb/presto/issues/9583

## Other issues caused by Java 9

- [x] https://github.com/airlift/airbase/pull/126
- [x] https://github.com/airlift/resolver/pull/14
- [x] https://github.com/prestodb/presto/issues/9592
- [x] https://github.com/prestodb/presto/pull/9593

**Comment by tooptoop4** [comment]
i see all tasks complete, can this be closed?

**Comment by electrum** [comment]
Presto has been running in production on Java 9+ for quite a while.
