### ISSUE TITLE
Split string on semicolon (;)

### ISSUE THREAD

**Issue by nidhibhargava** [prestodb/presto#9569]
I have a string ex: a = "PACKAGE;MIXED PACKAGE:RT:FLT+HOT;2;397.22" and I want to split the string on semicolon (;). So the result is ["PACKAGE", "MIXED PACKAGE:RT:FLT+HOT", "2","397.22"]

But it doesn't seem to be working. I am using Presto v0-157

**Comment by akshatnair** [comment]
Please provide the syntax you used in your query. What is the output you are seeing?

**Comment by nidhibhargava** [comment]
I tried the following syntax, none of them work

split(a, '[\;]')
split(a, ';')

Output I get ["PACKAGE;MIXED PACKAGE:RT:FLT+HOT;2;397.22"]
The result I would expect is ["PACKAGE", "MIXED PACKAGE:RT:FLT+HOT", "2","397.22"]

**Comment by nezihyigitbasi** [comment]
I just tried with 0.191

```
presto:s> select split('PACKAGE;MIXED PACKAGE:RT:FLT+HOT;2;397.22', ';');
                     _col0
------------------------------------------------
 [PACKAGE, MIXED PACKAGE:RT:FLT+HOT, 2, 397.22]
(1 row)
```

**Comment by nidhibhargava** [comment]
I am using 0.157, not sure if the support for added in later versions

**Comment by akshatnair** [comment]
It worked on a table column too. Please upgrade your server.

```
presto:sf1> select c1, split(c1,';') from t1;
                c1                |                _col1                
----------------------------------+-------------------------------------
 PACKAGE;MIXED PACKAGE:RT:FLT+HOT | [PACKAGE, MIXED PACKAGE:RT:FLT+HOT] 
(1 row)

```
