### ISSUE TITLE
Whether the presto has supported to SQL Querying on hbase currently?

### ISSUE THREAD

**Issue by phoenixhadoop** [prestodb/presto#959]
Hi Presto Team:
I would like to use Presto for SQL Querying on a table that has been exist in my hbase.So far,I find Presto that has supported to query data from datasources as Hive/HDFS with SQL,but i am not sure whether it has supported to query data from a exist table of hbase as well as SQL Querying. Please give me some helps,Thank you very much.I will wait your replies online.

**Comment by raghuvineel** [comment]
@rishidwivedi 
Did you happen to work on that and open sourced it? I am in need of presto-hbase connector. Any help would be great.

**Comment by kevintvh** [comment]
Any update on this please?
