### ISSUE TITLE
Presto does not support the where condition of char

### ISSUE THREAD

**Issue by hugoren** [prestodb/presto#9590]
presto version is 0.188
my sql statement is:   select * from mysql.db.user where usrname='boss'
The field of username is char
But I couldn't find the results
I saw your records for 2016
https://github.com/prestodb/presto/issues/5320
You said that "Add CHAR support to JDBC driver."
But why?
Thank you

**Comment by findepi** [comment]
@hugoren currently you would need to pad the searched value with spaces:
```
select * from mysql.db.user where usrname='boss         '
```

so that the length of the constant is the same as the length of the `char(x)` field.

Note: this is current known limitation, not as it should be.
