### ISSUE TITLE
date type from cassandra not working

### ISSUE THREAD

**Issue by baluKanattil** [prestodb/presto#9597]
While using cassandra connector to connect scylladb, for tables having `date` type column presto gives the error `cassandraType is null` when querying.

**Comment by eparesh** [comment]
Anyone was able to work around on how to use cassandra table with date column?

**Comment by findepi** [comment]
@baluKanattil for the record, does the same problem occur when using Cassandra instead of ScyllaDB?

**Comment by findepi** [comment]
`date` type is currently not supported by the cassandra connector. Of course, an unsupported data type should be ignored on read (if possible). I don't know the reason, why it isn't so in the cassandra connector (but I would assume there must be some). Obviously, even better would be to support the `date` data type.

**Comment by forainychen** [comment]
just see there is PR for this support, in case anyone is interested.
https://github.com/prestodb/presto/pull/7123
