### ISSUE TITLE
Web UI, Live plan: Table operators do not contain the basic information about the data sources

### ISSUE THREAD

**Issue by dudu-markovitz** [prestodb/presto#9602]
It seems there is no catalog.schema.table information

**Comment by bill-warshaw** [comment]
It would be helpful for `tablescan` nodes to show the actual table they query, but it'd also be nice to see similar information for other operators (e.g. for `filter`, the actual filters, for `aggregation`, the actual aggregation being run, etc).

Maybe hover tooltips would be the way to go?  Or is this information that would better be put in the `Stage Plan` view?
