### ISSUE TITLE
Issue with multiple keys in keytab of Kerberized Presto

### ISSUE THREAD

**Issue by decimusphostle** [prestodb/presto#9626]
I have been playing around with Presto's Kerberos functionality and while I have gotten it to work, I have a setup/use-case that is similar to the one described here: https://github.com/prestodb/presto/issues/9212 where the clients connect to the coordinator with an 'alias' (DNS-wise) as opposed to the FQDN of the host the coordinator is running on (which is assumed by presto to be the 'un-overrideable' default).

Per suggestions here(https://ssimo.org/blog/id_019.html), it seemed like using a keytab with multi-keys (i.e. containing separate principals corresponding to SPN's for the FQDN of the host, the DNS alias for this host, etc.) could be a potential solution for this type of 'general Kerberos scenario'. Unfortunately while the coordinator recognizes/reads in these keys it seems to error out trying to use the right key in say validating the checksum. (See relevant server logs here: https://pastebin.com/LzrRJkFn and the corresponding client CLI error here: https://pastebin.com/r14VzrSU)

Does anyone here have any suggestions on working around this? Could this be a bug, perhaps?

PS: It is not immediately clear what to make of this line in the logs(specially since the keytype being looked up should be in the keytab, IMO):

Found unsupported keytype (1) for presto/somehost.some-dc.somedomain.com@SOMEREALM.COM

**Comment by akshatnair** [comment]
Have you updated the JCE policy files? You can read more about it here
https://prestodb.io/docs/current/security/server.html

**Comment by decimusphostle** [comment]
Sorry for the delayed response. 

> Have you updated the JCE policy files?

Yes, we have.

The issue I am referring to is when the (Presto) setup is taking the 'Kerberos approach' described [here](https://ssimo.org/blog/id_019.html) - under the heading **'Use multiple keys, one per name'**. When the coordinator is passed in a keytab with multiple keys - each corresponding to a different DNS alias (to the physical box) on which the daemon is running - as the logs show (linked above), while the keys are being read in correctly, the coordinator does not appear to use the right key for authenticating.

---

To elaborate some more here is what the configured keytab file looks like:

decimusphostle@somehost:~$ klist -kKet /home/presto/presto-somehost-multi-presto-kt.keytab 
Keytab name: FILE:/home/presto/presto-somehost-multi-presto-kt.keytab
KVNO Timestamp        Principal
---- ---------------- ---------------------------------------------------------
   2 19/12/2017 15:02 presto@SOMEREALM.COM (aes256-cts-hmac-sha1-96)  (0xad80)
   2 19/12/2017 15:02 presto@SOMEREALM.COM (arcfour-hmac)  (0x52ec)
   2 19/12/2017 15:02 presto@SOMEREALM.COM (des3-cbc-sha1)  (0xfb15)
   2 19/12/2017 15:02 presto@SOMEREALM.COM (des-cbc-crc)  (0x86e9)
   2 19/12/2017 15:02 presto/somehostdev-coordinator-secure.presto.service.somedomain.com@SOMEREALM.COM (aes256-cts-hmac-sha1-96)  (0xf0cf)
   2 19/12/2017 15:02 presto/somehostdev-coordinator-secure.presto.service.somedomain.com@SOMEREALM.COM (arcfour-hmac)  (0x1d8d)
   2 19/12/2017 15:02 presto/somehostdev-coordinator-secure.presto.service.somedomain.com@SOMEREALM.COM (des3-cbc-sha1)  (0x58a4)
   2 19/12/2017 15:02 presto/somehostdev-coordinator-secure.presto.service.somedomain.com@SOMEREALM.COM (des-cbc-crc)  (0xab31)
   3 19/12/2017 15:02 presto/somehost.somedomain.com@SOMEREALM.COM (aes256-cts-hmac-sha1-96)  (0xf1f3)
   3 19/12/2017 15:02 presto/somehost.somedomain.com@SOMEREALM.COM (arcfour-hmac)  (0x6493)
   3 19/12/2017 15:02 presto/somehost.somedomain.com@SOMEREALM.COM (des3-cbc-sha1)  (0x31f7)
   3 19/12/2017 15:02 presto/somehost.somedomain.com@SOMEREALM.COM (des-cbc-crc)  (0x5e85)
   2 19/12/2017 15:02 presto/somehost.somesubdomain.somedomain.com@SOMEREALM.COM (aes256-cts-hmac-sha1-96)  (0xe6679)
   2 19/12/2017 15:02 presto/somehost.somesubdomain.somedomain.com@SOMEREALM.COM (arcfour-hmac)  (0x7ae1)
   2 19/12/2017 15:02 presto/somehost.somesubdomain.somedomain.com@SOMEREALM.COM (des3-cbc-sha1)  (0xbf19)
   2 19/12/2017 15:02 presto/somehost.somesubdomain.somedomain.com@SOMEREALM.COM (des-cbc-crc)  (0x5157)
decimusphostle@somehost:~$

As is noted [here](https://github.com/prestodb/presto/issues/9212), due to Presto's behavior of defaulting to picking the FQDN of the physical host (of the coordinator - without allowing to specify an override for the SPN), things only work if I configure the coordinator with a keytab that has an SPN == FQDN. But unfortunately in my/our use case, clients are connecting in via a DNS alias (which allows us to keep things flexible as regards our deployment[s]) so either being able to override the SPN ( as noted in #9212 ) or supporting multiple-keys (one per SPN) would be a work-around.

**Comment by alloydwhitlock** [comment]
This isn't necessarily a Presto issue, but a Kerberos issue. Kerberos will perform reverse-DNS lookups to validate that the host is what it says it is. When this occurs, the host is saying "SOMEHOST.YOURDOMAIN.COM" and not your "ALIAS.YOURNAME.DOMAIN". Disabling the RDNS or modifying acceptor settings could make your coordinator less secure, so I cannot condone that. 

Instead of using a CNAME for your Presto Coordinator, look at creating an A record for the aliased name and bind the corresponding records IP to an interface on the Presto Coordinator. RDNS lookups would pass at that time. If your host fails, you would bind the IP on the new host. In our Kerberos setup, which does something similar, we use Quagga to bind BGP IP addresses to the hosts so we can move around the BGP VIP.
