### ISSUE TITLE
system.runtime.queries join system.runtime.tasks on query_id field

### ISSUE THREAD

**Issue by qli-aa** [prestodb/presto#9641]
Presto 0.166
we use presto with hive and s3, try to get statistics about s3 input bytes and output bytes from system connector
```
SELECT
    q.user as user,
    sum(raw_input_bytes) as raw_input_bytes,
    sum(raw_input_rows) as raw_input_rows,
    sum(processed_input_bytes) as processed_input_bytes,
    sum(processed_input_rows) as processed_input_rows,
    sum(output_bytes) as output_bytes,
    sum(output_rows) as output_rows,
    sum(date_diff('second', q.started, q."end")) as running_time
FROM
    system.runtime.queries as q JOIN system.runtime.tasks as t
ON
    q.query_id = t.query_id
AND
    q.state in ('FINISHED', 'FAILED')
GROUP BY user;
``` 

but only return very few results, then I found the distinct query_id numbers is not matched
system.runtime.queries had 1277 records
system.runtime.tasks only had 24 records

**Comment by nezihyigitbasi** [comment]
Some tasks are probably purged. There is a config property `task.info.max-age` that determines how long to keep the task info around in memory. If you set it too long it may have consequences on memory usage. 

Is this a one off analysis that you are doing or are you trying to collect such statistics from your system? If the latter using [event listeners](https://prestodb.io/docs/current/develop/event-listener.html) may be a better option.

**Comment by qli-aa** [comment]
thanks, system connector is a simple interface I can use it to run query to get such statistics quickly.
