### ISSUE TITLE
Incorrect FILTER clause evaluation order

### ISSUE THREAD

**Issue by martint** [prestodb/presto#9656]
According to the SQL specification, the `FILTER` clause for an aggregation query should be applied to the rows in the group before the arguments to the aggregation are evaluated. 

Currently, expressions in the aggregation arguments are evaluated before the filter, leading to queries failing when they shouldn't.

For example:

```sql
select sum(1 / a) filter (where a <> 0) 
from (values (1), (0)) t(a)
```

fails with "/ by zero" error.

References:

> ### 10.9 `<aggregate function>`
> d) If AF is immediately contained in a `<set function specification>` SFS, then a group of a grouped table of the aggregation query of SFS.

> 2) Let T be the argument source of AF.

> 4) Case:
> a) If `<filter clause>` is specified, then the `<search condition>` is effectively evaluated for each row of T. Let T1 be the collection of rows of T for which the result of the `<search condition>` is True.
> b) Otherwise, let T1 be T.

> 7) If `<general set function>` is specified, then:
> a) Let TX be the single-column table that is the result of applying the `<value expression>` to each row of T1 and eliminating null values

**Comment by findepi** [comment]
@martint did you see https://github.com/prestodb/presto/issues/9528 ?

**Comment by martint** [comment]
> @martint did you see #9528

I hadn't seen that. I filed this one based on a recent question from that user in our internal groups.

**Comment by findepi** [comment]
Note: possible solutions are being discussed under https://github.com/prestodb/presto/issues/11205

**Comment by Vayu** [comment]
is there a progress on that?
