### ISSUE TITLE
SHOW SCHEMAS&TABLES in memory connector recognize only default and information_schema schema

### ISSUE THREAD

**Issue by ebyhr** [prestodb/presto#9669]
Memory connector can create schemas, but `SHOW SCHEMAS` and `SHOW TABLES` doesn't recognize it.

Below is reproducing step.
```
presto> create table memory.test.t1(c1 int);
CREATE TABLE
```

```
presto> show schemas in memory;
       Schema       
--------------------
 default            
 information_schema 
(2 rows)

Query 20180104_022814_00199_x222s, FINISHED, 1 node
Splits: 18 total, 18 done (100.00%)
0:00 [2 rows, 35B] [37 rows/s, 651B/s]

presto> 
presto> show tables in memory.test;
Query 20180104_023102_00200_x222s failed: line 1:1: Schema 'test' does not exist
show tables in memory.test
```

`SHOW COLUMNS` and (of course) `SELECT` query success.
```
presto> show columns in memory.test.t1;
 Column |  Type   | Extra | Comment 
--------+---------+-------+---------
 c1     | integer |       |         
(1 row)

Query 20180104_023539_00202_x222s, FINISHED, 1 node
Splits: 18 total, 18 done (100.00%)
0:00 [1 rows, 54B] [12 rows/s, 683B/s]
presto>
presto> select * from memory.test.t1;
 c1 
----
(0 rows)

Query 20180104_023134_00201_x222s, FINISHED, 1 node
Splits: 17 total, 17 done (100.00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]
```

**Comment by kokosing** [comment]
As I mentioned in PR, IMO the bug is not about you are not able to see schemas, but about the fact you was able to create table in schema which does not exists.

**Comment by ebyhr** [comment]
Thanks for your comment. I'll close the PR and send new PR check schema before create table/view.

**Comment by ebyhr** [comment]
FYI,

Raptor connector can create table in schema which does not exists and show table works.
```
presto> show schemas from raptor;
       Schema       
--------------------
 information_schema 
 system             
(2 rows)

presto> 
presto> create table raptor.test.t1(id int);
CREATE TABLE
presto> 
presto> show schemas from raptor;
       Schema       
--------------------
 information_schema 
 system             
 test               
(3 rows)
presto> 
presto> show tables from raptor.test;
 Table 
-------
 t1    
(1 row)
```

**Comment by electrum** [comment]
Yes, Raptor was implemented before we had schema creation and we never bother to fix it. This is addressed in version 2 rewrite.

**Comment by ebyhr** [comment]
@electrum 
Thanks, I don't touch raptor's code. Which do you think is better about memory connector? Raise schema not exist error or make schema automatically as raptor. 

I found blackhole connector is same as memory connector and feel raptor's behavior looks good on memory and blackhole connectors from the perspective of flexibility.

**Comment by kokosing** [comment]
> the perspective of flexibility

Then in case of bug in script or typo mistake you would not notice it. I prefer fail fast instead of automagical behaviour.

**Comment by ebyhr** [comment]
@kokosing 
I see. You're right. I've never thought about bug or typo situation. Sorry...!
