### ISSUE TITLE
Client serialization of arrays of Bing tiles is wrong

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#9679]
Given an array of Bing tiles, Presto CLI outputs copies of the first element of the array.

> presto> select array[bing_tile(1, 2, 10), bing_tile(3, 4, 11)];
> select array[bing_tile(1, 2, 10), bing_tile(3, 4, 11)];
>                    _col0                    
> --------------------------------------------
>  [{x=1, y=2, zoom=10}, {x=1, y=2, zoom=10}] 
> (1 row) 

> presto> select bing_tile(1, 2, 10), bing_tile(3, 4, 11);
> select bing_tile(1, 2, 10), bing_tile(3, 4, 11);
>         _col0        |        _col1        
> ---------------------+---------------------
>  {x=1, y=2, zoom=10} | {x=3, y=4, zoom=11} 
> (1 row)

CC: @nezihyigitbasi

**Comment by nezihyigitbasi** [comment]
I also tried a map of bing tiles and it fails too:

```
select map(array[bing_tile(1, 2, 10)], array[bing_tile(3, 4, 11)]);
```

**Comment by nezihyigitbasi** [comment]
#9680 fixes  the array serialization issue, I will open a new issue to track the map serialization issue.
