### ISSUE TITLE
A problem encountered to me when using the basejdbc connector to extract data from mysql

### ISSUE THREAD

**Issue by totticarter** [prestodb/presto#9697]
A problem encountered to me when using the basejdbc connector to extract data from mysql. 
To prevent from getting huge amount of data from mysql, a common field in the target mysql table is sent to the datasource as the condition of "order by limit", so that only "limit" number of rows to be transfered 
 up to presto. I got the correct query result on my testing virtual machine environment, however, empty result got when I run this code on the online production server. anyone knows how to resolve this problem?

**Comment by findepi** [comment]
see https://github.com/prestodb/presto/issues/9698
