### ISSUE TITLE
presto  mysql very very slow

### ISSUE THREAD

**Issue by haosky** [prestodb/presto#9714]
presto  mysql very very slow

**Comment by findepi** [comment]
Please use user group for this type of observations. Also, be sure to include some context -- what you mean by slow? what would you expect? what are you trying to do?

(note, btw., that mysql connector -- if this is what you're referring to -- is single-threaded, so will always be slow, with respect to some definitions of "slow")

**Comment by haosky** [comment]
Sorry！  I am a newbie here .

I am benefit from Presto is a distributed SQL query engine supports any connector.but , using Presto to with only MySQL , it slower than  MySQL query engine without presto? How to get  the  effective configuration ? While sending a simple MySQL query ,will presto return MySQL data access only the MySQL server by presto worker node or remote scheduling ? Can i reduce I/O operations?

**Comment by findepi** [comment]
Hi

If you use Presto to connect to single MySQL instance and nothing else, you are not going to have any performance gain compared to using MySQL alone.
Presto is a distributed query engine, but MySQL server is not distributed, so -- generally speaking -- your queries will not execute as distributed either. (There are some exceptions to this, but this is a general rule)

However, if you have multiple MySQL servers OR other data sources (other relational databases or Hive, or something else), Presto will serve you well.

**Comment by haosky** [comment]
Thank you anyway！
