### ISSUE TITLE
Feature request for memory connector

### ISSUE THREAD

**Issue by elonazoulay** [prestodb/presto#9718]
Users have requested that we provide a low latency cache to power dashboards and speed up etl with the following features:

- Cache to hold data in memory for lowest latency access
- Evenly skewed data so that all workers have the same amount of memory
- Lightweight (low cpu) compression for the cached data
- Different encodings to aid in faster access (for filtering, aggregation) to the data

**Comment by elonazoulay** [comment]
We had implemented this connector and will attach a pull request shortly.

**Comment by findepi** [comment]
> We had implemented this connector

@elonazoulay is it somehow in relation to `memory` or `raptor` connectors?

**Comment by findepi** [comment]
My impression is that the goals outlined in this feature requests are covered already by `raptor` and `memory` connectors.
Of course, if there are use-cases where these fail short, a PR is more than welcome!
