### ISSUE TITLE
does presto support this?

### ISSUE THREAD

**Issue by photogamerun** [prestodb/presto#9738]
does presto support insert into new table new partiton from old one?

insert into table biflt1_o_orderdetail partition (d='2018-01-09') as select * from o_orderdetail where d='2018-01-09';

**Comment by electrum** [comment]
Yes, but unlike in Hive, there’s no special syntax for partition columns. They look like normal columns and you specify them as columns in the SELECT (and in the optional list of target columns for the INSERT).

In other words, they are like “dynamic partitions” in Hive.

**Comment by photogamerun** [comment]
ok thanks!
