### ISSUE TITLE
Does presto support keberos keytab cache model?

### ISSUE THREAD

**Issue by photogamerun** [prestodb/presto#9746]
current I use cli to access presto server with keberos security model

./presto-cli-0.190-executable.jar --server https://svr5737hw1288.hadoop.uat.qa.nt.ctripcorp.com:7778 --enable-authentication --krb5-principal biflt@DC.SH.CTRIPCORP.COM --krb5-keytab-path /home/biflt/biflt.keytab --krb5-remote-service-name hive --keystore-path /tmp/keystore.jks --keystore-password presto --source presto-cli --catalog hive --schema default;

but actually I don't want to indicate the keytab file as well as principal

it works?

but when I want to use keytab cache model

I use below command and it throw exception 

kinit -kt /home/biflt/biflt.keytab biflt@DC.SH.CTRIPCORP.COM
./presto-cli-0.190-executable.jar --server https://svr5737hw1288.hadoop.uat.qa.nt.ctripcorp.com:7778 --enable-authentication --krb5-remote-service-name hive --keystore-path /tmp/keystore.jks --keystore-password presto --source presto-cli --catalog hive --schema default;

exception
Debug is  true storeKey false useTicketCache false useKeyTab true doNotPrompt true ticketCache is null isInitiator true KeyTab is /etc/krb5.keytab refreshKrb5Config is true principal is null tryFirstPass is false useFirstPass is false storePass is false clearPass is false
Refreshing Kerberos configuration
Java config name: /etc/krb5.conf
Loaded from Java config
>>> KdcAccessibility: reset
		[Krb5LoginModule] authentication failed 
Unable to obtain Principal Name for authentication 

what should I do? any one else can help?

**Comment by findepi** [comment]
Presto uses built-in Kerberos client and thus doesn't know what `kinit` command you executed. 
This might be a problem if you are used to the `kinit`-way, but this behavior is simpler and more portable. For Presto to leverage `kinit`-stored credentials, it needs to know which Kerberos client library stack you use.

**Comment by photogamerun** [comment]
now I change some presto code to get credential ticket cache file if I can not found it from System.env

code like belows

public final class KerberosUtil
{
    private static final String FILE_PREFIX = "FILE:";

    private KerberosUtil() {}

    public static Optional<String> defaultCredentialCachePath()
    {
        String value = nullToEmpty(System.getenv("KRB5CCNAME"));
        if (value.startsWith(FILE_PREFIX)) {
            value = value.substring(FILE_PREFIX.length());
        }
        value = emptyToNull(value);
        if (value == null) {
            value = sun.security.krb5.internal.ccache.FileCredentialsCache.getDefaultCacheName();
        }

        return Optional.ofNullable(emptyToNull(value));
    }
}

I have run it and it works fine
kinit -kt /tmp/data_fin.keytab data_fin@DC.SH.CTRIPCORP.COM

./presto-cli-0.190-executable.jar --server https://svr13358hw1288:7778 --enable-authentication --krb5-remote-service-name hive --keystore-path /tmp/keystore.jks --keystore-password presto --file /tmp/test.sql --user data_fin --source presto-cli --catalog hive --schema default;

now I can access the presto server without indicating krb related arguments

**Comment by findepi** [comment]
Answered.
