### ISSUE TITLE
simple Select * query in partition table works in hive but no in  presto

### ISSUE THREAD

**Issue by photogamerun** [prestodb/presto#9754]
I have run a query to access hive table

from hive that the definition

show create table

CREATE TABLE `dw_cardb.penetration_rate_domestic_hol`(
  `holorders` string COMMENT '酒店订单量', 
  `departure` string COMMENT '酒店离店时间', 
  `carorders` string COMMENT '用车订单数', 
  `cityname` string COMMENT '城市', 
  `rate` float COMMENT '渗透率', 
  `total_order` string COMMENT '用车总订单数（用来排序）', 
  `rank` string COMMENT '排序值', 
  `cityid` string COMMENT '城市ID')
COMMENT '酒店租车交叉订单底层表'
PARTITIONED BY ( 
  `d` string COMMENT 'date')
ROW FORMAT SERDE 
  'org.apache.hadoop.hive.ql.io.orc.OrcSerde' 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.orc.OrcInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.orc.OrcOutputFormat'
LOCATION
  'hdfs://ns/user/biuser/warehouse/etl/DW_CarDB.db/penetration_rate_domestic_hol'
TBLPROPERTIES (
  'last_modified_by'='bicar', 
  'last_modified_time'='1511168459', 
  'metadata.partition.life'='30', 
  'transient_lastDdlTime'='1511168459')
Time taken: 0.139 seconds, Fetched: 25 row(s)

desc dw_cardb.penetration_rate_domestic_hol

holorders           	string              	酒店订单量               
departure           	string              	酒店离店时间              
carorders           	string              	用车订单数               
cityname            	string              	城市                  
rate                	float               	渗透率                 
total_order         	string              	用车总订单数（用来排序）        
rank                	string              	排序值                 
cityid              	string              	城市ID                
d                   	string              	date                
	 	 
# Partition Information	 	 
# col_name            	data_type           	comment             
	 	 
d                   	string              	date      

and I executed query it works fine in hive

hive> select * from dw_cardb.penetration_rate_domestic_hol where d<='2018-01-13' limit 1;
OK
holorders	departure	carorders	cityname	rate	total_order	rank	cityid	d
3662.0		56.0	三亚	0.01529219	237.0	1	43	2017-09-29

but in presto I executed the same query again it throw this exception

presto:default> select * from dw_cardb.penetration_rate_domestic_hol where d<='2018-01-13' limit 1;
Query 20180117_021024_00066_fkj6g failed: There is a mismatch between the table and partition schemas. The types are incompatible and cannot be coerced. The column 'rate' in table 'dw_cardb.penetration_rate_domestic_hol' is declared as type 'float', but partition 'd=$%7Bpre_3date}' declared column 'usedate_d' as type 'string'.

from the exception I think it's not clear for me to identify the problem.

**Comment by pradeepbhadani** [comment]
@photogamerun  What was the solution to fix this issue?
