### ISSUE TITLE
S3 filesystem error: the region 'us-east-1' is wrong; expecting 'eu-west-1' 

### ISSUE THREAD

**Issue by nezihyigitbasi** [prestodb/presto#9758]
From the user group:

> We just upgraded Presto from 0.186 to 0.192. After the upgrade, we are seeing this when running any query: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-west-1' Enabling S3 region pinning fixes this, but we have buckets in multiple regions, so this isn't an option. Is there anything that changed that could cause this?

**Comment by nezihyigitbasi** [comment]
There were changes made as part of #9588 that may have caused this.

With the latest code if no endpoint or region is explicitly configured we use the `us-east-1` region.

```
clientBuilder.withRegion(US_EAST_1);
```

Previously we weren't setting any region. When I made that change I checked that with the aws sdk java team in this issue:  aws/aws-sdk-java#1423

I will follow up with them in the meantime, @avirtuos any ideas?

**Comment by nezihyigitbasi** [comment]
Setting `hive.s3.global-bucket-access=true` with the #9759 should solve this issue.

**Comment by avirtuos** [comment]
The AWS SDK documentation for S3 does say 

> After you build a client with the builder, it's immutable and the region cannot be changed. If you are working with multiple AWS Regions for the same service, you should create multiple clients—one per region.

but I feel like I've not had to do that previously as the client handled this for me. I found an issue on the aws-sdk-java github that seems to shed some light on what we are seeing 

https://github.com/aws/aws-sdk-java/issues/1142

It seems the deprecated client interface was automatically resolving the endpoint for us and this functionality is not present in the new builder. We may need to add the same resolution logic to PrestoS3Filesystem. createAmazonS3Client(...). The result of that resolution would likely be worth caching across instances of PrestoS3Filesystem to avoid a round trip per file/split to do the lookup.

I'm going to see if I can produce a PR with this modification tonight, let me know if you disagree with this approach. I think it is the quickest way to unblock this.

**Comment by avirtuos** [comment]
Nevermind, just saw your PR.
