### ISSUE TITLE
Finish INNER / RIGHT OUTER JOIN early when right side of the join is empty

### ISSUE THREAD

**Issue by ggilfb** [prestodb/presto#9769]
Consider a query like:
```
with x as (select 1 as id from (values 1) as t(id) where false), y as (select 2 as id)
select * from y right outer join x on y.id = x.id;
```
The query won't return any results, however, the left side would have been fully evaluated. 
Terminate query with RIGHT OUTER JOIN if the right side doesn't produce any rows.
This also applies to inner joins, if there is a side that produces 0 rows and a join is involved, then the query could finish pretty early.

**Comment by findepi** [comment]
@ggilfb this is pretty neat idea and something we have thought about in the past too. I am curious how often do you experience queries that would benefit from this? I.e. what's real-world gain from having this?

**Comment by ggilfb** [comment]
@findepi Unfortunately this happens more often than not, usually the problem arises with users making a mistake with a filter. Given the data sizes, the left table can be pretty big and expensive to read, leaving us with wasted CPU (and a used slot).

**Comment by kokosing** [comment]
It should be easy I could write some optimizer rules for that. But since we currently we have a lot to do I would not expect it to happen any time soon.

@ggilfb if you wish you could post a pull request to handle your case. It should work in similar way as `com.facebook.presto.sql.planner.iterative.rule.RemoveEmptyDelete` does. We will support you with review and merge process.

**Comment by findepi** [comment]
@kokosing , if i understand what you mean, this would do if we can realize the right side is empty _during planning_. 
@ggilfb Are your tables partitioned? Does it happen that "users making a mistake with a filter" leads to all partitions being discarded from table on the right side?

**Comment by kokosing** [comment]
@ggilfb Does #9776 relate to this issue?

**Comment by ggilfb** [comment]
@kokosing: The issue is a bit different, although in theory #9776 should optimize this change even further if there is a faster way to determine if there are no rows to return.
@findepi: Yes, the tables in this case are partitioned.

I'm taking the task and will check out the proposed solution.

**Comment by findepi** [comment]
Note: https://github.com/prestodb/presto/pull/9848 was merged and later reverted in https://github.com/prestodb/presto/pull/10485
