### ISSUE TITLE
Push down LIMIT through LEFT JOIN

### ISSUE THREAD

**Issue by findepi** [prestodb/presto#9783]
For a query like 
```
SELECT .. FROM
a LEFT OUTER JOIN b ON a.key = b.key
ORDER BY a.something LIMIT 10
```
 the `LIMIT` can be applied before the join, as in:
```
SELECT .. FROM
(SELECT * FROM a ORDER BY a.something LIMIT 10) LEFT OUTER JOIN b ON a.key = b.key
ORDER BY a.something LIMIT 10
```

Furthermore, if we knew that `b.key` is unique, we could even eliminate the LIMIT above the JOIN, leaving only LIMIT below, on the left side.

**Comment by meggamind** [comment]
I'm working on this

**Comment by ankitdixit** [comment]
@martint @findepi I see that this issue still exists. Can i work on this?

**Comment by findepi** [comment]
i started to look into this yesterday.
