### ISSUE TITLE
row_number() produces wrong results with some inequality filters

### ISSUE THREAD

**Issue by yingsu00** [prestodb/presto#9792]
A filter of = x or <0 on row_number() would be optimized and produce correct empty result set:

```
presto:ad_metrics> select id, val, rank from (select id, val, row_number() over (PARTITION by id) as rank from test) where rank < 0;
 id | val | rank
----+-----+------
(0 rows)
```

But if we change the filter to <= x where x is a negative number, it produces non-empty result set which was wrong. 
```
presto:ad_metrics> select id, val, rank from (select id, val, row_number() over (PARTITION by id) as rank from test) where rank <=-1;
 id | val  | rank
----+------+------
  1 | -100 |    1
  2 |  -50 |    1
(2 rows)
```

This is because the planner created a RowNumberNode, but visitFilter() does not try to optimize it because the tupleDomain and the range represented by upperbound is the same. Instead it just return the original RowNumberNode with maxRowCountPerPartition = -1. 

To fix this, the planner should recogonize this is an empty upperbound.

**Comment by martint** [comment]
Fix merged
