### ISSUE TITLE
Any user can use presto-cli in keberos model when using right keytab and principal

### ISSUE THREAD

**Issue by photogamerun** [prestodb/presto#9794]
when I use presto-cli, I found if I use right keytab and principal when I access presto server. I can indicate any --user.

like bellow:  
./presto-cli-0.190-executable.jar --server https://svr5737hw1288.hadoop.uat.qa.nt.ctripcorp.com:7778 --enable-authentication --krb5-config-path /etc/krb5.conf --krb5-principal biflt@DC.SH.CTRIPCORP.COM --krb5-keytab-path /home/biflt/biflt.keytab --krb5-remote-service-name hive --keystore-path /tmp/keystore.jks --keystore-password presto --user abc --source presto-cli --catalog hive --schema default;

./presto-cli-0.190-executable.jar --server https://svr5737hw1288.hadoop.uat.qa.nt.ctripcorp.com:7778 --enable-authentication --krb5-config-path /etc/krb5.conf --krb5-principal biflt@DC.SH.CTRIPCORP.COM --krb5-keytab-path /home/biflt/biflt.keytab --krb5-remote-service-name hive --keystore-path /tmp/keystore.jks --keystore-password presto --user bcd--source presto-cli --catalog hive --schema default;

they are all working. but from my understanding

only in this case, it works
./presto-cli-0.190-executable.jar --server https://svr5737hw1288.hadoop.uat.qa.nt.ctripcorp.com:7778 --enable-authentication --krb5-config-path /etc/krb5.conf --krb5-principal biflt@DC.SH.CTRIPCORP.COM --krb5-keytab-path /home/biflt/biflt.keytab --krb5-remote-service-name hive --keystore-path /tmp/keystore.jks --keystore-password presto --user biflt --source presto-cli --catalog hive --schema default;

**Comment by sopel39** [comment]
@losipiuk could you answer this?

**Comment by findepi** [comment]
@photogamerun you need to implement `SystemAccessControl`, specifically the `SystemAccessControl.checkCanSetUser(Principal principal, String userName)` method.
