### ISSUE TITLE
Presto Build Fail -checkstyle violations

### ISSUE THREAD

**Issue by shaojie1980** [prestodb/presto#9805]
I cloned presto from git and am trying to run a mvn clean install to build it. It failed on this error:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (checkstyle) on project presto-spi: You have 43401 Checkstyle violations. -> [Help 1]

Any suggestions on how to get this built.

**Comment by findepi** [comment]
Did you do that on Windows?

**Comment by shaojie1980** [comment]
yes.
errors like:

[ERROR] src\main\resources\com\facebook\presto\spi\type\zone-index.properties:[2287] (regexp) RegexpMultiline: Line contains carriage return

**Comment by kokosing** [comment]
I am sorry, we do not support the build on Windows machine. Please see: https://github.com/prestodb/presto/#requirements
