### ISSUE TITLE
Can run describe/show columns without SELECT privileges

### ISSUE THREAD

**Issue by amoghmargoor** [prestodb/presto#9809]
We observe that the users not having select privileges on a table can successfully run describe or show columns upon it. Isn't this a bug ? For instance Hive Authorization based on SQL Standards do not allow describe/show columns on tables without SELECT privileges: https://cwiki.apache.org/confluence/display/Hive/SQL+Standard+Based+Hive+Authorization

**Comment by electrum** [comment]
This could be implemented by adding a `filterColumns` method to `ConnectorAccessControl`. We should also add a `checkCanShowColumnsMetadata`, similar to the check in `SystemAccessControl`, to provide a good error message for `SHOW COLUMNS`.

**Comment by amoghmargoor** [comment]
Thanks @electrum ... will fix and raise PR for the same.

**Comment by amoghmargoor** [comment]
@electrum PR for the same: https://github.com/prestodb/presto/pull/9894 
Please take a look.
