### ISSUE TITLE
Optimize aggregating distinct values

### ISSUE THREAD

**Issue by cosinequanon** [prestodb/presto#9828]
Currently `array_agg(distinct ...)` is more efficient than `array_distinct(array_agg(...))` which causes users to have to make sure they structure their queries correctly. It feels like we could determine this statically and optimize the inefficient case. This is important because the bad case can blow up in memory and cause the query to fail

**Comment by kokosing** [comment]
Have you meant `array_agg(array_distinct(...))`?

When you do `EXPLAIN` on these queries what difference do you see?

**Comment by kokosing** [comment]
> Have you meant array_agg(array_distinct(...))?

Please nevermind this question. Your issue description is correct.
