### ISSUE TITLE
Optimize spatial queries

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#9834]
Presto supports a set of geospatial functions which allow computations on geometry objects (https://prestodb.io/docs/current/functions/geospatial.html). These functions could be used to construct spatial queries that join two relations using a spatial relationship between their columns. Such queries are referred to as spatial joins. For example, 

```
SELECT *
FROM points p, cities c
WHERE ST_Contains(ST_GeometryFromText(p.city_polygon), ST_Point(p.longitute, p.latitude))
```
Today this query runs as a nested loop join with a filter on top. `ST_Contains(ST_GeometryFromText(p.city_polygon), ST_Point(p.longitute, p.latitude))` expression is evaluated on every combination of rows from points and cities. This is quite inefficient.

Techniques used to optimize equi joins (hash-based partitioning and hash tables) can be extended to spatial joins. (http://www.cs.umd.edu/~hjs/pubs/jacoxtrjoin07.pdf offers a good summary of research in the area).

To partition the datasets one needs to do the following:

1. Pick one relation
2. Compute overall extent of the geometries in that relation (minimum bounding box that contains all the geometries)
3. Collect a sample of the data
4. Split the overall extent into non-overlapping rectangles to achieve most even distribution of the sample data (using KDB-tree).
5. Use the rectangles created in step 4 to define partitions and partition both relations. For every row, find all partition rectangles which overlap with the bounding box of the row geometry and copy the row into all of these partitions. 

To join a pair of matching partitions (on a single machine):

1. Pick a smaller partition and build an R-Tree containing all geometries from that partition (assumes the partition can fit in memory)
2. Process rows from the other partition one by one. For each row, lookup candidate matches in the R-Tree and then check spatial relationship for these candidates. To avoid duplicate results (due to partitioning) perform an extra check before emitting a match. Verify that a reference point of the intersection of the bounding boxes of the matching geometries (lower left corner) lies within the partition's rectangle.

First step is to implement broadcast spatial join, e.g. spatial join where one relation is small enough to fit into a single machine. This doesn't require any changes to partitioning step, but single node execution needs to change to use R-Tree instead of a hash table. 

Here is a WIP PR: https://github.com/prestodb/presto/pull/9474

**Comment by sopel39** [comment]
I have found similar problem with distributed sort. Currently the partially ordered data would be steamed to one node to be merged. Ideally though it would be best if at runtime we partition sorted data into intervals (which contain roughly the same amount of data). This would probably require sampling (as you mentioned) to happen before data is actually partitioned.
How you though about how would you like to implement such sampling and partitioning for spatial join? Currently Presto needs to know how to partition data at every stage before the execution is started. There is not support for determining partitioning at runtime. Maybe you have some ideas how to push that forward?

**Comment by mbasmanova** [comment]
@sopel Karol, indeed sampling and partitioning based on sampling results is not supported out of the box. Essentially, we need to run two queries instead of one. First query to gather statistics about the data. Second query to perform the join using the statistics computed by the first query. 

One option could be to put the first query into a WITH clause, but we would need to reference that query twice (once for each join relation) and with the current implementation it would be executed twice producing potentially different results (unless we come up with a stable sampling algorithm) and make partitions of the join relations inconsistent with each other. Adding support for temporary tables could unlock this option.

Another option is to gather spatial statistics for individual partitions before running the query and storing them in Hive Metastore. At query planning time we could use these statistics without needing to compute them. (In this case, we would assume that non-geometry columns are not correlated with geometry columns.) We've been discussing the use of histograms for CBO. If we choose to compute equi-height end-biased histograms, then distributed sort could leverage these to determine partitioning scheme at query planning time.

We also thought about creating a UDFA to compute the partitioning scheme and have the user apply that UDFA, save results to a table and provide the name of the table in the spatial join query.

Finally, we've seen users successfully perform large spatial joins in Hive using Bing tiles method. The idea is to convert each geometry into a set of covering tiles and join the relations on tile IDs. This converts a 2-dim problem into a 1-dim one and allows the use of hash join. The result is a set of pairs of geometries which are likely to satisfy join relationship. Assuming there are not too many false positives, computing spatial relationship for each pair may not be bad. After finishing the broadcast spatial join PR (#9474), I want to take a closer look at this option.

**Comment by findepi** [comment]
> we've seen users successfully perform large spatial joins in Hive using Bing tiles method.

This sounds like a good idea, but this also isn't stateless. AFAIU, you need to determine bing tiles zoom level and this needs to correspond to size of shapes you join on.
For example, if you're joining events with countries, then coarse tiling might be sufficient. However, if you're joining events within cities of a country, then coarse tiling would effectively mean a disguised cross join.

IMO, this approach, if reinforced with either statistics or sampling, may be very effective.

**Comment by sopel39** [comment]
> This converts a 2-dim problem into a 1-dim one and allows the use of hash join. The result is a set of pairs of geometries which are likely to satisfy join relationship.

You would still need to select only district joined pairs based on left/right unique row ids, right? This is because the same shape pairs might be joined from different tiles (if they cross tile boundary).

**Comment by sopel39** [comment]
What if we add mechanism to Presto for runtime partitioning selection? One (designated or random) node might compute partitioning and broadcast (possibly though coordinator) it to other tasks? That would be the nicest solution from user perspective (no additional steps needed).

For dist sort there are now two stages:
1. round robin: partially sorts data
2. merge data on single node.

If could be that some task at stage 1 computes data distribution and broadcasts it to other tasks in stage 1.

> If we choose to compute equi-height end-biased histograms, then distributed sort could leverage these to determine partitioning scheme at query planning time.

That would work only if you try to join/sort data that comes directly from table scan.

**Comment by mbasmanova** [comment]
>> You would still need to select only district joined pairs based on left/right unique row ids, right? 

That's right. Although, this step is not needed if at least one of the relations is made of points.

**Comment by mbasmanova** [comment]
>> What if we add mechanism to Presto for runtime partitioning selection? One (designated or random) node might compute partitioning and broadcast (possibly though coordinator) it to other tasks?

That would be nice. I believe dynamic partition pruning has introduced something similar.

**Comment by sopel39** [comment]
> That would be nice. I believe dynamic partition pruning has introduced something similar.

Indeed. I was also thinking about dynamic partition pruning. Maybe Presto could have some concept of auxiliary services that could be used for pushing small amount of data between nodes and master.
