### ISSUE TITLE
Report memory usage for PartitionOutputOperator

### ISSUE THREAD

**Issue by highker** [prestodb/presto#9858]
Memory usage is only reported once in `PartitionOutputOperator` to save
CPU usage. This can lead to incorrect memory estimation causing full GC
issues. Switch to updating memory per input page.

prototype: #9088

**Comment by findepi** [comment]
Does this issue cover also reporting POO's memory as "normal" user memory? (currently it feeds on system memory i believe)

**Comment by highker** [comment]
@findepi, I think @nezihyigitbasi has a PR to unify user and system memory pool. So this is going to happen soon.

**Comment by nezihyigitbasi** [comment]
Currently I don't have a PR yet for unifying the user/system pools, but that's the plan.

**Comment by findepi** [comment]
@nezihyigitbasi is there a problem with updating POO to report mem usage to user pool and updating other places later? No big-bang effect, I know.. :)

**Comment by nezihyigitbasi** [comment]
I don't see any problem with that.

**Comment by nezihyigitbasi** [comment]
@findepi Thinking more about allocating from the user pool, I can understand why allocating POO memory from the user pool may make sense, but if we do it then some queries that were running fine previously may fail (if the memory usage of POO + query's existing memory usage exceeds the memory limit).

**Comment by findepi** [comment]
> ... but if we do it then some queries that were running fine previously may fail 

True, but this is true for any change in memory accounting (like fixing the accounting in an operator that was previously underestimating).
Maybe it's possible to introduce this with a feature toggle?

**Comment by martint** [comment]
Fixed for 0.196
