### ISSUE TITLE
error : too many open partitions

### ISSUE THREAD

**Issue by kripakaranj** [prestodb/presto#9870]
hello,
I have set hive.max-partitions-per-writers=300.
I try to insert data that has about 257 distinct values for the partitioned columns.
I still get error: too many open partitions .

**Comment by electrum** [comment]
Is your table bucketed? Can you paste the result of `SHOW CREATE TABLE xxx`?

**Comment by kripakaranj** [comment]
Create Table
----------------------------------------------------------------
 CREATE TABLE hive.presto_poc.XXXXXX (
    event_time timestamp,
    app_server varchar(30),
    load_file varchar(80),
    retention varchar(12),
    synthetic_id char(36),
    attr3 varchar(80),
    attr6 varchar(200),
    attr8 varchar(20),
    attr9 varchar(36),
    attr10 varchar(200),
    attr13 varchar(200),
    attr14 varchar(50),
    attr15 varchar(36),
    attr16 varchar(200),
    attr17 varchar(2000),
    attr18 varchar(2000),
    attr19 varchar(2000),
    attr20 varchar(2000),
    attr21 varchar(2000),
    attr22 varchar(2000),
    attr24 varchar(2000),
    attr24 varchar(2000),
    attr25 varchar(2000),
    attr26 varchar(200),
    attr27 varchar(200),
    attr28 varchar(200),
    attr29 varchar(200),
    attr30 varchar(200),
    attr31 varchar(200),
    attr32 varchar(200),
    attr33 varchar(200),
    attr34 varchar(200),
    uuid varchar(36),
    event_time_client timestamp,
    attr35 varchar(200),
    attr36 varchar(2000),
    attr37 varchar(2000),
    attr38 varchar(200),
    attr39 varchar(200),
    attr40 varchar(200),
    attr41 varchar(200),
    attr42 varchar(200),
    attr43 varchar(200),
    attr44 varchar(200),
    attr45 varchar(200),
    attr46 varchar(200),
    attr47 varchar(200),
    attr48 varchar(200),
    attr49 varchar(200),
    attr50 varchar(200),
    attr51 varchar(200),
    attr52 varchar(200),
    attr53 varchar(200),
    attr54 varchar(200),
    attr55 varchar(200),
    attr56 varchar(2000),
    attr57 varchar(2000),
    attr58 varchar(2000),
    attr59 varchar(2000),
    attr60 varchar(2000),
    attr1 varchar(30),
    attr12 varchar(80),
    attr2 varchar(10),
    attr11 varchar(80),
    attr23 varchar(80),
    attr4 varchar(200),
    attr5 varchar(200),
    attr7 varchar(200),
    app_name varchar(80),
    event_name varchar(80),
    event_day varchar(30)
 )
 WITH (
    external_location = 's3://######/',
    format = 'PARQUET',
    partitioned_by = ARRAY['app_name','event_name','event_day']
 )

**Comment by electrum** [comment]
Thanks. Please verify that you are inserting fewer than 300 partitions. Assuming this is your insert query:
```sql
INSERT INTO xxx
SELECT app_name, event_name, event_day, ...
FROM ...
```
Change it to this:
```sql
SELECT count(DISTINCT row(app_name, event_name, event_day))
FROM ...
```

**Comment by kripakaranj** [comment]
thank you David for your quick response .....
 
here is all the data points i think could be useful  : 

--------------
presto:presto_poc> SELECT count(DISTINCT row(app_name, event_name, event_day))
                -> FROM XXXX WHERE date_format(event_time,'%Y-%m-%d') IN ('2017-12-05','2017-12-06', '2017-12-07');
 _col0
-------
   298
(1 row)

----------------
insert into YYYYYY (
 event_time        	,
 app_server        	,
 load_file         	,
 retention         	,
 synthetic_id      	,
 attr3             	,
 attr6             	,
 attr8             	,
 attr9             	,
 attr10            	,
 attr13            	,
 attr14            	,
 attr15            	,
 attr16            	,
 attr17            	,
 attr18            	,
 attr19            	,
 attr20            	,
 attr21            	,
 attr22            	,
 attr24            	,
 attr25            	,
 attr26            	,
 attr27            	,
 attr28            	,
 attr29            	,
 attr30            	,
 attr31            	,
 attr32            	,
 attr33            	,
 attr34            	,
 uuid              	,
 event_time_client 	,
 attr35            	,
 attr36            	,
 attr37            	,
 attr38            	,
 attr39            	,
 attr40            	,
 attr41            	,
 attr42            	,
 attr43            	,
 attr44            	,
 attr45            	,
 attr46            	,
 attr47            	,
 attr48            	,
 attr49            	,
 attr50            	,
 attr51            	,
 attr52            	,
 attr53            	,
 attr54            	,
 attr55            	,
 attr56            	,
 attr57            	,
 attr58            	,
 attr59            	,
 attr60            	,
 attr1             	,
 attr12            	,
 attr2             	,
 attr11            	,
 attr23            	,
 attr4             	,
 attr5             	,
 attr7             	,
 app_name          	,
 event_name        	,
 event_day         	 )
          SELECT
 event_time        	,
 app_server        	,
 load_file         	,
 retention         	,
 synthetic_id      	,
 attr3             	,
 attr6             	,
 attr8             	,
 attr9             	,
 attr10            	,
 attr13            	,
 attr14            	,
 attr15            	,
 attr16            	,
 attr17            	,
 attr18            	,
 attr19            	,
 attr20            	,
 attr21            	,
 attr22            	,
 attr24            	,
 attr25            	,
 attr26            	,
 attr27            	,
 attr28            	,
 attr29            	,
 attr30            	,
 attr31            	,
 attr32            	,
 attr33            	,
 attr34            	,
 uuid              	,
 event_time_client 	,
 attr35            	,
 attr36            	,
 attr37            	,
 attr38            	,
 attr39            	,
 attr40            	,
 attr41            	,
 attr42            	,
 attr43            	,
 attr44            	,
 attr45            	,
 attr46            	,
 attr47            	,
 attr48            	,
 attr49            	,
 attr50            	,
 attr51            	,
 attr52            	,
 attr53            	,
 attr54            	,
 attr55            	,
 attr56            	,
 attr57            	,
 attr58            	,
 attr59            	,
 attr60            	,
 attr1             	,
 attr12            	,
 attr2             	,
 attr11            	,
 attr23            	,
 attr4             	,
 attr5             	,
 attr7   ,
 app_name          	,
 event_name        	,
 cast(date_format(even_time,'%Y-%m-%d') as VARCHAR(12)   )    	     	
FROM XXXXXXX  
WHERE date_format(event_time,'%Y-%m-%d') IN ('2017-12-05','2017-12-06', '2017-12-07');

Query 20180131_195017_00000_g9z7h, FAILED, 17 nodes
Splits: 2,483 total, 581 done (23.40%)
1:29 [147M rows, 19.3GB] [1.65M rows/s, 222MB/s]

Query 20180131_195017_00000_g9z7h failed: Too many open partitions
---------------------------


server.log
output 

2018-01-31T19:49:44.979Z	INFO	main	com.facebook.presto.metadata.StaticCatalogStore	-- Loading catalog /etc/presto/conf/catalog/hive.properties --
2018-01-31T19:49:45.833Z	INFO	main	Bootstrap	PROPERTY                                           DEFAULT     RUNTIME                                                            DESCRIPTION
2018-01-31T19:49:45.835Z	INFO	main	Bootstrap	hive.max-partitions-per-writers                    100         300                                                                Maximum number of partitions per writer

**Comment by kripakaranj** [comment]
@electrum there is no issue when i split the above insert into 3 SQLs and run them in parallel in three sessions

**Comment by Frogglet** [comment]
Was this ever resolved? I appear to be getting the same kind of issue. Despite the fact that I increase the hive.max-partitions-per-writers config to 1000 I get this error: `Exceeded limit of 100 open writers for partitions/buckets`.

Is it not picking up the configuration for some reason?

**Comment by PowerToThePeople111** [comment]
I ran into the same error as Frogglet. Any updates would be appreciated.

**Comment by carlshan** [comment]
Just noting that I have run into the same issue.

**Comment by etzelm** [comment]
Ran into this today and found that for our Presto cluster size we had the following session property set too high:

hash_partition_count

By lowering that count we were able to mitigate the following error:

"com.facebook.presto.spi.PrestoException: Exceeded limit of 100 open writers for partitions/buckets"

**Comment by Akanksha-kedia** [comment]
Can explain how hash partition count is taken into consideration as per my knowledge based in join_distribution_type= partitioned then this parameters are validated.
