### ISSUE TITLE
`Schema mismatch' error for 'struct' field

### ISSUE THREAD

**Issue by raj638111** [prestodb/presto#9883]
We are facing this issue in production. We have a Hive External table with Parquet... in which one of the field is of type `struct<>`. The number of fields for this `struct<>`(in Parquet data) might vary each day. The issue for us is ; When we query the table from Hive the query executes successfully. Hive is able to gracefully handle any missing fields(By placing `null` value for those fields). But from Presto the query **fails** when there is a mismatch b/w number of fields in Table Schema(Hive metastore) & the no of fields in the actual data(Parquet data). Here is a small example through which I am able to replicate this issue. Please note all the 3 tables I have given below refers to the same S3 location

**Create tables & Load data**
```
create external table test2(
  others struct<name: string>
)PARTITIONED BY (
subject string)
ROW FORMAT SERDE
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
STORED AS INPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
  's3://somebucket/rj-struct';
insert overwrite table test2 partition(subject='english') select named_struct('name','bob');

create external table test3(
  others struct<name: string, mark: string>
)PARTITIONED BY (
subject string)
ROW FORMAT SERDE
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
STORED AS INPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
  's3://somebucket/rj-struct';
insert overwrite table test3 partition(subject='math') select named_struct('name','sam','mark','50');

create external table test4(
  others struct <name: string, mark: string, attendance: string>
)PARTITIONED BY (
subject string)
ROW FORMAT SERDE
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
STORED AS INPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
  's3://somebucket/rj-struct';
insert overwrite table test4 partition(subject='history') select named_struct('name','tom','mark','60','attendance','good');
```
**Update partition information for table test3 from Hive client**
```
msck repair table test3
Repair: Added partition to metastore test3:subject=english
Repair: Added partition to metastore test3:subject=history
Repair: Added partition to metastore test3:subject=math
```

**// Query execution from Hive client (Hive handles this situation gracefull by placing 'null' for 'mark' field**
```
select * from tier3_rgunasekaran.test3 where subject='english';
{"name":"bob","mark":null}	english
```

**//Query execution from Presto (Whereas Presto throws error)**
```
select * from tier3_rgunasekaran.test3 where subject='english';
Query 20180202_045250_00009_pw2eg failed: com.facebook.presto.spi.PrestoException

Error opening Hive split s3://somebucket/rj-struct/subject=english/22221ce7cc644b21958d609a52f98e1d_000000 (offset=0, length=191): Schema mismatch, metastore schema for row column others has 2 fields but parquet schema has 1 fields

```
PS : The **Presto version** we are using is `0.157`

**Comment by findepi** [comment]
> The Presto version we are using is 0.157

@raj638111 i don't know the solution for this problem, but this version is pretty old. Could you try out 0.193? 
Also note that there are 2 Parquet reader implementations (`hive.parquet-optimized-reader.enabled`) and there also an important setting `hive.parquet.use-column-names`, which often helps when schema is meant to be flexible.

**Comment by raj638111** [comment]
Looks like the version we are using(`0.157`) do not even have the property `hive.parquet.use_column_names` and the version of Presto is controlled by the vendor :(

**Comment by findepi** [comment]
@raj638111 assuming there is a fix for your issue (either already exists in 0.193 or gets developed and released in e.g. 0.194), how would you apply it?

Please let me close this issue. I would be grateful if you could -- at some point in the future, or on some other environment -- check whether the bug still affects you in 0.193 or then-current version.
