### ISSUE TITLE
Support split_to_map with lambda to resolve key conflicts

### ISSUE THREAD

**Issue by rongrong** [prestodb/presto#9891]
The current version of `split_to_map` would fail if there's duplicate keys. Since the input is a string there's very little users can do about it. Supporting a second version of this function that accepts a lambda function `(k, old_val, new_val) -> varchar` so users can specify how to resolve the key conflicts.

For example,
```split_to_map('a:b,a:d', ',', ':', (k, v1, v2) -> v2)```
will keep the last value when there are duplicate keys, and return `{'a':'d'}`, while
```split_to_map('a:b,a:d', ',', ':', (k, v1, v2) -> v1)```
will keep the first value when there are deplicate keys, and return `{'a':'b'}`, and
```split_tp_map('a:b,a:d', ',', ':', (k, v1, v2) -> v1 || v2)```
will sum up all values of the same key, and return `{'a':'bd'}`.

**Comment by ongmingyang** [comment]
Just to clarify, the lambda is a left to right reduce function, right?

**Comment by martint** [comment]
> Just to clarify, the lambda is a left to right reduce function, right?

Yes
