### ISSUE TITLE
Kerberos Problem

### ISSUE THREAD

**Issue by pengyf584** [prestodb/presto#9902]
when the presto config kerberos ,the query throw `INTERNAL ERROR:Cannot cast com.facebook.presto.hive.HiveColumnHandle to com.facebook.presto.hive.HiveColumnHandle` .who can help me!

**Comment by losipiuk** [comment]
Thanks for reporting issue.

Please provide steps to reproduce the issue. With amount of information given there is now way we can help you.

Closing for now.
