### ISSUE TITLE
Flaky tests: TestHiveIntegrationSmokeTest.testScaleWriters

### ISSUE THREAD

**Issue by sopel39** [prestodb/presto#9905]
```
[ERROR] testScaleWriters(com.facebook.presto.hive.TestHiveIntegrationSmokeTest)  Time elapsed: 95.918 s  <<< FAILURE!
java.lang.AssertionError: Iterators differ at element [0]: [4] != [3] expected [[4]] but found [[3]]
	at com.facebook.presto.hive.TestHiveIntegrationSmokeTest.testScaleWriters(TestHiveIntegrationSmokeTest.java:1577)
```

FYI: @electrum

**Comment by findepi** [comment]
Indeed, recently it fails from time to time.

**Comment by findepi** [comment]
Recently @kokosing improved Travis tests stability by https://github.com/prestodb/presto/pull/10086, this seems to next thing to fix.

**Comment by findepi** [comment]
Any idea how this can be fixed? On our internal infra this one fails much more often than on Travis.

**Comment by sopel39** [comment]
This test almost constantly fails on our infra. Apparently even with large writes the writers never scale up to four (we get mostly 3).

Maybe the underlying feature is broken?

**Comment by haozhun** [comment]
This failed a few time for me yesterday on Travis as well.

**Comment by findepi** [comment]
Fixed by https://github.com/prestodb/presto/pull/10613
