### ISSUE TITLE
Presto tests TEST_SPECIFIC_MODULES=presto-tests take a long time

### ISSUE THREAD

**Issue by sopel39** [prestodb/presto#9907]
For example: https://travis-ci.org/prestodb/presto/builds/337969486.

`TEST_SPECIFIC_MODULES=presto-tests` takes now about 1h while other jobs mostly around 30mins. We should probably split this into two jobs or address testing holistically.

FYI: @findepi @electrum

**Comment by kokosing** [comment]
Do we have log (report) files from tests execution? We could diagnose which tests are taking so long and maybe there is something we could fix.

**Comment by kokosing** [comment]
Testing with iterative optimizer disabled added new 14 minutes, see:
https://travis-ci.org/prestodb/presto/builds/337483026
https://travis-ci.org/prestodb/presto/builds/337458054

**Comment by kokosing** [comment]
See https://github.com/prestodb/presto/pull/9910, I remove there tests which have coverage with different tests. Maybe this will be good enough solution.
