### ISSUE TITLE
Release notes for release 0.194

### ISSUE THREAD

**Issue by haozhun** [prestodb/presto#9909]
## David Phillips
- [x]  01-31 18:47:58    4f935164b8 Return a proper exit code from CLI
- [x]  02-01 11:54:51    40d678a721 Support setting client tags in JDBC driver
- [x]  02-01 11:54:51    603f48a07e Add update type to JDBC driver
- [x]  02-01 11:54:51    9869ed6d36 Add client info option to CLI
- [x]  02-01 11:54:51    c66519e555 Allow configuring network timeout for JDBC driver
- [x]  02-01 11:54:51    d3277139c4 Remove unused parser instance from CLI
- [x]  02-06 07:27:21    2514128867 Cleanup Optional warning in TestBufferingSplitSource
- [x]  02-06 07:27:21    517a72a512 Use Javadoc for enums in SourcePartitionedScheduler
- [x]  02-06 07:27:21    60d5176d0c Remove deprecated method in ConnectorSplitSource
- [x]  02-06 07:27:21    bd2e491371 Remove deprecated method in ConnectorSplitManager
- [x]  02-06 07:27:21    cb002c717c Remove deprecated getNextBatch method in SplitSource
- [x]  02-06 07:27:21    f44178df7a Fix warnings in SPI PartitionHandle classes
- [x]  02-06 07:27:21    fcd1109192 Remove callers of deprecated ConnectorSplitSource method
- [x]  02-06 07:29:37    66b953c016 Remove debug flag from ClientSession
- [x]  02-06 07:29:37    f08c60c0de Add QueryRunner factory for tests
## German Gil
- [x]  02-05 12:23:18    1c6c5d1a3d Fix query hang when partitions are offline for retention
## Grzegorz Kokosiński
- [x]  02-05 01:10:48    3a8b1abfd3 Remove predicate pushdown switch in TPCH connector
- [x]  02-05 01:10:48    70e5fe2555 Fix TPCH predicate pushdown when filtering column is pruned
- [x]  02-05 01:10:48    7ff3f73a55 Accept Tpch columns as List
- [x]  02-05 01:10:48    d7c56cefa1 Make predicate to always present in TpchRecordSet
- [x]  02-05 01:10:48    dc97a1effa Rename variable
- [x]  02-06 00:15:27    a4b99e6660 Fix Cassandra listTables denies empty table_name
- [x]  02-06 00:44:21    2eee3079be Add predicate pushdown for part type and container
- [x]  02-06 00:44:21    c45778204f Remove ORDER_STATUS_VALUES variable
- [x]  02-06 00:44:21    ecbae0b71c Apply Constraint.predicate on TPCH columns
- [x]  02-06 03:39:52    0c68b1f299 Test PreparedStatement
- [x]  02-06 03:39:52    0e4802e8d8 Extract connection method
- [x]  02-06 03:39:52    80e8d06a11 Fix shouldSetTimezone() so it works with or without Kerberos
- [x]  02-06 03:39:52    c6b034a673 Fix Simba specific JDBC tests
## Haozhun Jin
- [x]  01-30 10:17:23    0e7339be83 Use whenAnyCompleteCancelOthers in Airlift
- [x]  01-30 10:17:23    6913dd7ac7 Update to Airlift 0.163
- [x]  01-30 10:17:23    eb3beb760c Remove performance optimization for Future cancellation
## James Sun
- [x]  01-31 11:58:29    e52a845f8e Add Hive storage format session property
## Karol Sobczak
- [x]  01-31 02:23:06    25a3729be6 Remove unused variable from LocalExchange
- [x]  02-01 02:24:17    6774be51db Compare nanos delta instead of direct comparison
- [x]  02-05 03:46:37    27526fd841 Introduce OrderingScheme
- [x]  02-05 03:46:37    38109f8361 Use OrderingScheme in WindowNode.Specification
- [x]  02-05 03:46:37    3b1176199c Refactor matching of ordering scheme for TopN node
- [x]  02-05 03:46:37    3e3a122d60 Use OrderingScheme in TopNNode
- [x]  02-05 03:46:37    8373ebc189 Rename fields/methods from PlanMatchPattern.Ordering
- [x]  02-05 03:46:37    8cd5d67eec Use OrderingScheme in SortNode
- [x]  02-05 04:43:08    c8144b1ad1 Make local exchanger responsible for blocking writes
- [x]  02-06 01:52:40    90faa28ce2 Fix incorrect SortOrder returned in PlanMatchPattern.Ordering#getSortOrder
- [x]  02-06 02:20:11    ff4061c7e5 Remove LocalExchangeMemoryManager#setNoBlockOnFull
## Martin Traverso
- [x]  02-02 12:34:35    4daade0933 Simplify tuple domain used for layout contraint evaluation
- [x]  02-02 12:34:35    4e34fc70b4 Memoize construction of expression interpreter for layout constraints
- [x]  02-02 12:34:35    a6b75f260c Make TupleDomain simplify logic first class
- [x]  02-02 12:34:35    b13beba7da Make variable name more precise
## Nezih Yigitbasi
- [x]  01-31 09:27:10    511ef139a0 Fix flaky test TestQueryManager.testQueryCpuLimit
- [x]  01-31 14:19:33    e3021135f2 Fix deadlock in QueryContext::setMemoryPool
- [x]  02-05 09:56:19    2cfe4234f4 Fix peak memory in query details UI
## Piotr Findeisen
- [x]  01-30 11:48:08    37107ba7d0 Add close() method to ConnectionFactory interface
- [x]  01-30 11:48:36    2b31a2bf6c Fix predicate push-down in TPCH connector
- [x]  01-30 11:49:07    2d2525ad92 Construct proper literal for DATE in LiteralInterpreter.toExpression
- [x]  01-30 11:49:07    3c49e772fa Rename TestReorderJoins to TestEliminateCrossJoins
- [x]  01-30 11:49:07    6dcf901b58 Remove redundant StatsCalculator creation in AbstractTestQueryFramework
- [x]  01-30 11:49:07    6f2c2b0b94 Add clearRanges to ColumnStatistics.builder()
- [x]  01-30 11:49:07    964d89f15f Do not set config switch to its default
- [x]  01-30 11:49:07    9ff3ac523d Fix typo
- [x]  01-30 11:49:07    dae5acbddd Add ColumnStatistics.UNKNOWN_COLUMN_STATISTICS
- [x]  01-30 11:49:07    e284a9eaf2 Reorder fields to match constructor arguments
- [x]  01-30 11:49:42    1ca5abf38e Consider boxing when checking whether value matches type
- [x]  01-30 11:50:32    2ce8949b21 Fix static import of format method
- [x]  01-30 11:50:32    9ea1497e3d Use static import for String.format
- [x]  01-30 11:51:19    6184932211 Ensure tables initially not analyzed
- [x]  01-30 11:51:19    e1cc790c20 Update tempto to 1.45
- [x]  01-30 11:51:19    f03bc1635a Fix stopping of product tests's containers upon exit
- [x]  01-30 11:51:42    c72b97b6d0 Add missing 'alwaysRun' in @AfterClass
- [x]  01-30 11:52:14    2da0722faf Add Symbol statistics to PlanNodeStatsEstimate
- [x]  01-30 11:52:14    5b1bc2d5a6 Use doubles instead Estimates in PlanNodeStatsEstimate
- [x]  01-30 11:52:14    8482c6fd52 Remove Filter above TableScan logic from CoefficientBasedStatsCalculator
- [x]  01-30 11:52:14    f4a644df54 Compute PlanNode output size based on symbol stats
- [x]  01-30 11:52:30    165540532a Fix confusing varargs invocation
- [x]  01-30 11:52:30    54e9285264 Remove unused field
- [x]  01-31 03:29:28    b4d1d26d7c Expose low/high value in statistics for Hive tables
- [x]  01-31 03:29:28    ba00baa295 Return low/high value in show stats
- [x]  01-31 03:29:43    4da96b4e91 Change StatsCalculator API and cache stats in Memo
- [x]  01-31 03:29:43    71b44887f2 Store group information as single object in Memo
- [x]  01-31 03:29:43    978afcb1f9 Maintain group back-references in Memo
- [x]  01-31 03:29:43    ad009a1bd8 Separate IterativeOptimizer's internal Context and rules' context
- [x]  01-31 03:29:43    f375cca10d Decrement references within Memo.deleteGroup
- [x]  02-05 02:20:20    7272f95655 Add a test that Presto works without iterative optimizer
- [x]  02-05 02:20:36    40dd0efe7b Create distributed plans in BenchmarkPlanner
- [x]  02-05 04:02:31    016b607204 Allow overriding temporary table name generation
## Raghav Sethi
- [x]  02-01 21:19:36    0b0ac94d22 Add refresh failure counter to DB resource group manager
## Sam Rash
- [x]  02-02 07:31:12    3fc4a3e18a Use appropriate initial state object in generated aggregation code
- [x]  02-02 07:31:12    ac10c1b9c0 Improve Histogram Memory Usage in Group-By Case
## Yi He
- [x]  01-30 12:38:31    35156499ce Enhance error message when session property uses unknown catalog

**Comment by haozhun** [comment]
@electrum @ggilfb @kokosing @highker @sopel39 @martint @nezihyigitbasi @findepi @raghavsethi @rash67 @hellium01

**Comment by nezihyigitbasi** [comment]
General
--------
- Fix peak memory in the query details web UI, which was previously empty.
- Fix a deadlock in the new memory management framework introduced in the previous release.

**Comment by hellium01** [comment]
* Improve error message when session property reference invalid connector, which was previously misleading.

**Comment by ggilfb** [comment]
General
--------
- Fix query hang when partitions are offline for retention

**Comment by martint** [comment]
```
* Fix planning performance regression when querying tables with many partitions.
```

**Comment by highker** [comment]
**General**
-------------
- Limit number of values for `min`, `max`, `min_by`, and `max_by` to be at most 10000.

**Hive**
-------------
- Add corresponding session properties `hive_storage_format` and `respect_table_format` for config `hive.storage-format` and `hive.respect-table-format` respectively.
- Reduce ORC file reader memory consumption by only allocating buffers for values when accessed in the query.

**Comment by findepi** [comment]
General
--------
```
* ``SHOW STATS``` now shows minimum and maximum value for a column (currently implemented for Hive connector).
```

> 2b31a2b Fix predicate push-down in TPCH connector
> 1ca5abf Consider boxing when checking whether value matches type -- fixes indexed queries in TPCH

Do we write about TPCH? This is visible change, but probably not very interesting, right?

**Comment by kokosing** [comment]
TPCH
---
 - Remove `tpch.predicate-pushdown` switch and enable support for predicate pushdown for `orderstatus` column of `orders` by default
> That switch was not documented, so I assumed that nobody used that
 - Add support for predicate pushdown for `type` and `container` columns of `part` table
 - Fix several bugs in predicate pushdown

Cassandra
---
 - Fix list table names when running queries like: `SELECT * FROM some_schema.information_schema.columns WHERE table_schema = 'some-schema'`

**Comment by electrum** [comment]
```
General Changes
---

* Add :func:`word_stem` function.

JDBC Driver Changes
---

* Allow configuring connection network timeout with ``setNetworkTimeout()``.
* Allow setting client tags via the ``ClientTags`` client info property.
* Expose update type via ``getUpdateType()`` on ``PrestoStatement``.

CLI Changes
---

* Add ``--client-info`` option for specifying client info.
* Add ``--ignore-errors` option to continue processing in batch mode when an error occurs.
* Return a non-zero exit status when an error occurs.

Hive Changes
---

* Allow setting username used to access Hive metastore via the ``hive.metastore.username`` config property.

**Comment by rash67** [comment]
Generated Code
---
* Use appropriate initial state object in generated aggregation code: 
single for non-group-by and group-by state for group-by queries

Histogram Memory Optimization
---
* change from a per-group instance of a histogram (customized hash 
table), to a single instance for all groups. We traded a little CPU,
but saw memory reduced from literally 1+ GB to 50 mb (java Object
overhead being the main saver). This should unblock some histogram
queries in production.
