### ISSUE TITLE
how to push down or condition

### ISSUE THREAD

**Issue by huangfeng1993** [prestodb/presto#9935]
for example, sql is "select * from mysql.table where a =1 or b=2", then the accepted request of mysql is "select * from table", it is not suitable when the size of table is too big.

**Comment by losipiuk** [comment]
Hello, thanks for question.

Pushing down condition with `OR` when two disjuncts are touching different columns is not currently supported. You may try to rewrite your query to facilitate `UNION` it may or not be possible depending on your data characteristics.

In the future please use prestodb users group - https://groups.google.com/forum/#!forum/presto-users - for asking questions. Github issues are more for tracking work to be done (bugs/new features). :)
