### ISSUE TITLE
log() function does not conform to SQL 2016

### ISSUE THREAD

**Issue by martint** [prestodb/presto#9939]
From section `6.30 <numeric value function>`:

```
<general logarithm function> ::=
  LOG <left paren> <general logarithm base> <comma>
      <general logarithm argument> <right paren>
```

The current implementation has the arguments reversed `log(value, base)`.

**Comment by haozhun** [comment]
Is there any plan on the steps to fix this? What are the dependencies?

**Comment by electrum** [comment]
My thought is that we announce that the function will be removed (users can convert to `ln(x) / ln(b)` which is how it's implemented anyway), then we wait a suitable length of time, maybe one year, before re-introducing the corrected version of the function.

**Comment by findepi** [comment]
>  then we wait a suitable length of time, maybe one year, before re-introducing the corrected version of the function.

shall we keep this issue open until then?
