### ISSUE TITLE
Add killQuery interface to QueryManager

### ISSUE THREAD

**Issue by highker** [prestodb/presto#9997]
Add a new `killQuery` interface to `QueryManager` that takes a reason as the parameter. Unlike `cancelQuery` that is usually issued from users, `killQuery` is used by admin to mitigate production issues if necessary.

Some other requirements:
- Add new end point to `QueryResource`.
- The new interface should go through `KillQueryProcedure` is possible.
- Add "bulk" kill queries capability in the web UI.

**Comment by electrum** [comment]
This should use a new error code, distinct from “user cancelled” (which means the user cancelled their own query as opposed to someone else killing it).
